In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.07
LBP_003_PET                                                      0.00 0.98      0.03
LBP_012_CT                                                       0.00 0.97      0.04
LBP_012_PET                                                      0.00 0.98      0.03
LBP_021_CT                                                       0.00 0.98      0.02
LBP_021_PET                                                      0.00 0.95      0.08
LBP_030_CT                                                       0.00 1.00      0.01
LBP_030_PET                                                      0.00 0.96      0.05
LBP_102_CT                                                       0.00 0.95      0.08
LBP_102_PET                                                      0.00 0.97      0.05
LBP_111_CT                                                       0.02 0.88      0.18
LBP_111_PET                                                      0.01 0.91      0.14
LBP_120_CT                                                       0.00 0.98      0.03
LBP_120_PET                                                      0.00 0.97      0.04
LBP_201_CT                                                       0.01 0.93      0.10
LBP_201_PET                                                      0.00 0.99      0.02
LBP_210_CT                                                       0.00 0.94      0.08
LBP_210_PET                                                      0.01 0.92      0.12
LBP_300_CT                                                       0.00 0.98      0.04
LBP_300_PET                                                      0.02 0.90      0.15
first_order_10Percentile_CT                                      0.00 0.96      0.06
first_order_10Percentile_PET                                     0.00 0.96      0.06
first_order_90Percentile_CT                                      0.00 0.98      0.04
first_order_90Percentile_PET                                     0.00 0.98      0.03
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 1.00      0.00
first_order_Entropy_CT_c16                                       0.00 0.99      0.02
first_order_Entropy_PET_b2                                       0.00 0.98      0.02
first_order_Entropy_PET_c04                                      0.00 0.98      0.02
first_order_InterquartileRange_CT                                0.01 0.94      0.09
first_order_InterquartileRange_PET                               0.00 1.00      0.00
first_order_Kurtosis_CT                                          0.00 0.99      0.02
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.00 0.97      0.04
first_order_Maximum_PET                                          0.00 0.99      0.01
first_order_MeanAbsoluteDeviation_CT                             0.00 1.00      0.00
first_order_MeanAbsoluteDeviation_PET                            0.00 0.98      0.02
first_order_Mean_CT                                              0.00 0.99      0.01
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.99      0.02
first_order_Median_PET                                           0.00 0.97      0.04
first_order_Minimum_CT                                           0.00 1.00      0.00
first_order_Minimum_PET                                          0.03 0.87      0.20
first_order_Range_CT                                             0.00 0.98      0.03
first_order_Range_PET                                            0.00 0.99      0.02
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.98      0.03
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 1.00      0.00
first_order_RootMeanSquared_CT                                   0.00 0.99      0.01
first_order_RootMeanSquared_PET                                  0.00 1.00      0.01
first_order_Skewness_CT                                          0.00 0.97      0.05
first_order_Skewness_PET                                         0.00 0.96      0.06
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.95      0.08
first_order_Uniformity_CT_c16                                    0.00 0.97      0.05
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 0.99      0.02
first_order_Variance_CT                                          0.00 0.99      0.01
first_order_Variance_PET                                         0.00 0.98      0.03
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_CT_c16                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 1.00      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.99      0.02
glcm_ClusterProminence_d_1_CT_b20                                0.00 0.99      0.01
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.96      0.06
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.96      0.07
glcm_ClusterProminence_d_1_PET_c04                               0.01 0.93      0.10
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_c16                                     0.00 0.99      0.01
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.95      0.08
glcm_ClusterShade_d_1_PET_c04                                    0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_b20                                  0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.98      0.03
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.02
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.99      0.01
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.01
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.01
glcm_Contrast_d_1_PET_b2                                         0.00 0.99      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.98      0.03
glcm_Correlation_d_1_CT_b20                                      0.00 1.00      0.01
glcm_Correlation_d_1_CT_c16                                      0.01 0.94      0.10
glcm_Correlation_d_1_PET_b2                                      0.00 0.98      0.04
glcm_Correlation_d_1_PET_c04                                     0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_b20                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.02
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_b20                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_b2                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.97      0.05
glcm_Id_d_1_CT_b20                                               0.00 0.99      0.01
glcm_Id_d_1_CT_c16                                               0.00 1.00      0.01
glcm_Id_d_1_PET_b2                                               0.00 0.99      0.02
glcm_Id_d_1_PET_c04                                              0.00 0.99      0.01
glcm_Idm_d_1_CT_b20                                              0.00 0.99      0.01
glcm_Idm_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idm_d_1_PET_c04                                             0.00 0.99      0.01
glcm_Idmn_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_c16                                             0.00 0.98      0.02
glcm_Idmn_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Idmn_d_1_PET_c04                                            0.00 0.98      0.02
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idn_d_1_CT_c16                                              0.00 0.99      0.01
glcm_Idn_d_1_PET_b2                                              0.00 1.00      0.00
glcm_Idn_d_1_PET_c04                                             0.00 0.99      0.01
glcm_Imc1_d_1_CT_b20                                             0.00 0.95      0.08
glcm_Imc1_d_1_CT_c16                                             0.01 0.92      0.11
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.02
glcm_Imc2_d_1_CT_b20                                             0.01 0.94      0.09
glcm_Imc2_d_1_CT_c16                                             0.00 0.98      0.03
glcm_Imc2_d_1_PET_b2                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.95      0.08
glcm_InverseVariance_d_1_CT_b20                                  0.00 0.97      0.05
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_b2                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.00
glcm_JointAverage_d_1_CT_b20                                     0.00 0.99      0.01
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_b2                                     0.00 0.98      0.02
glcm_JointAverage_d_1_PET_c04                                    0.00 1.00      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.96      0.07
glcm_JointEnergy_d_1_CT_c16                                      0.00 0.99      0.02
glcm_JointEnergy_d_1_PET_b2                                      0.00 0.98      0.03
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.95      0.07
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.01 0.94      0.10
glcm_MCC_d_1_CT_c16                                              0.00 0.96      0.05
glcm_MCC_d_1_PET_b2                                              0.00 0.98      0.03
glcm_MCC_d_1_PET_c04                                             0.00 0.98      0.03
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.98      0.03
glcm_MaximumProbability_d_1_CT_c16                               0.00 0.96      0.07
glcm_MaximumProbability_d_1_PET_b2                               0.00 0.96      0.06
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.95      0.08
glcm_SumAverage_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_b2                                       0.00 0.98      0.02
glcm_SumAverage_d_1_PET_c04                                      0.00 1.00      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.99      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_b2                                       0.00 0.98      0.03
glcm_SumEntropy_d_1_PET_c04                                      0.00 1.00      0.01
glcm_SumSquares_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumSquares_d_1_CT_c16                                       0.00 0.98      0.03
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_c04                                      0.00 1.00      0.01
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.01 0.94      0.09
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 0.97      0.04
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 0.96      0.06
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.05
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.98      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.96      0.06
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.96      0.06
gldm_DependenceVariance_d_1_CT_c16                               0.01 0.93      0.11
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.96      0.06
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.98      0.02
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.98      0.02
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 0.98      0.02
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 1.00      0.00
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.98      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.95      0.08
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.98      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.96      0.05
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.95      0.08
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 0.96      0.06
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.03
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.95      0.07
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.01 0.94      0.09
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.98      0.04
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.98      0.03
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.01 0.92      0.12
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.97      0.04
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.01 0.92      0.13
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.99      0.01
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.97      0.05
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.97      0.04
glrlm_GrayLevelNonUniformity_CT_c16                              0.01 0.94      0.10
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.98      0.03
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.98      0.02
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.95      0.08
glrlm_GrayLevelVariance_PET_b2                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_PET_c04                                  0.00 0.97      0.05
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.00 0.99      0.01
glrlm_HighGrayLevelRunEmphasis_CT_c16                            0.00 0.99      0.01
glrlm_HighGrayLevelRunEmphasis_PET_b2                            0.00 0.98      0.03
glrlm_HighGrayLevelRunEmphasis_PET_c04                           0.00 0.96      0.06
glrlm_LongRunEmphasis_CT_b20                                     0.00 0.97      0.04
glrlm_LongRunEmphasis_CT_c16                                     0.00 0.96      0.06

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic      p  -log2(p)
LBP_003_CT                                                       0.16   0.69      0.53
LBP_003_PET                                                      0.13   0.72      0.48
LBP_012_CT                                                       0.03   0.86      0.21
LBP_012_PET                                                      0.11   0.75      0.42
LBP_021_CT                                                       2.78   0.10      3.39
LBP_021_PET                                                      0.02   0.90      0.15
LBP_030_CT                                                       0.06   0.81      0.30
LBP_030_PET                                                      0.00   0.98      0.02
LBP_102_CT                                                       0.04   0.85      0.24
LBP_102_PET                                                      1.17   0.28      1.84
LBP_111_CT                                                       0.06   0.80      0.32
LBP_111_PET                                                      0.07   0.79      0.33
LBP_120_CT                                                       0.06   0.81      0.30
LBP_120_PET                                                      0.00   1.00      0.00
LBP_201_CT                                                       1.42   0.23      2.10
LBP_201_PET                                                      0.36   0.55      0.87
LBP_210_CT                                                       0.69   0.41      1.30
LBP_210_PET                                                      0.06   0.81      0.31
LBP_300_CT                                                       0.06   0.81      0.30
LBP_300_PET                                                      0.18   0.67      0.58
first_order_10Percentile_CT                                      0.06   0.80      0.32
first_order_10Percentile_PET                                     0.40   0.53      0.93
first_order_90Percentile_CT                                      0.75   0.39      1.37
first_order_90Percentile_PET                                     0.00   1.00      0.00
first_order_Energy_CT                                            0.00   0.99      0.02
first_order_Energy_PET                                           0.71   0.40      1.32
first_order_Entropy_CT_b20                                       0.01   0.92      0.12
first_order_Entropy_CT_c16                                       0.13   0.72      0.48
first_order_Entropy_PET_b2                                       0.03   0.85      0.23
first_order_Entropy_PET_c04                                      0.01   0.91      0.13
first_order_InterquartileRange_CT                                0.19   0.66      0.60
first_order_InterquartileRange_PET                               0.01   0.93      0.11
first_order_Kurtosis_CT                                          0.00   1.00      0.00
first_order_Kurtosis_PET                                         0.00   0.95      0.08
first_order_Maximum_CT                                           0.23   0.63      0.67
first_order_Maximum_PET                                          0.00   0.97      0.04
first_order_MeanAbsoluteDeviation_CT                             0.02   0.89      0.17
first_order_MeanAbsoluteDeviation_PET                            0.01   0.93      0.11
first_order_Mean_CT                                              0.00   0.95      0.07
first_order_Mean_PET                                             0.01   0.93      0.11
first_order_Median_CT                                            0.00   1.00      0.00
first_order_Median_PET                                           0.00   1.00      0.00
first_order_Minimum_CT                                           0.00   0.95      0.07
first_order_Minimum_PET                                          1.59   0.21      2.27
first_order_Range_CT                                             0.13   0.72      0.48
first_order_Range_PET                                            0.00   0.97      0.04
first_order_RobustMeanAbsoluteDeviation_CT                       0.04   0.85      0.24
first_order_RobustMeanAbsoluteDeviation_PET                      0.01   0.92      0.12
first_order_RootMeanSquared_CT                                   0.01   0.93      0.11
first_order_RootMeanSquared_PET                                  0.00   0.95      0.07
first_order_Skewness_CT                                          0.30   0.58      0.78
first_order_Skewness_PET                                         0.00   0.99      0.02
first_order_TotalEnergy_CT                                       0.00   0.99      0.02
first_order_TotalEnergy_PET                                      0.71   0.40      1.32
first_order_Uniformity_CT_b20                                    0.11   0.75      0.42
first_order_Uniformity_CT_c16                                    0.06   0.81      0.31
first_order_Uniformity_PET_b2                                    0.00   0.97      0.04
first_order_Uniformity_PET_c04                                   0.01   0.93      0.10
first_order_Variance_CT                                          0.02   0.90      0.15
first_order_Variance_PET                                         0.10   0.75      0.42
glcm_Autocorrelation_d_1_CT_b20                                  0.03   0.87      0.21
glcm_Autocorrelation_d_1_CT_c16                                  0.04   0.84      0.25
glcm_Autocorrelation_d_1_PET_b2                                  0.05   0.82      0.28
glcm_Autocorrelation_d_1_PET_c04                                 0.00   1.00      0.00
glcm_ClusterProminence_d_1_CT_b20                                0.04   0.83      0.26
glcm_ClusterProminence_d_1_CT_c16                                0.09   0.77      0.38
glcm_ClusterProminence_d_1_PET_b2                                2.52   0.11      3.16
glcm_ClusterProminence_d_1_PET_c04                               0.01   0.92      0.12
glcm_ClusterShade_d_1_CT_b20                                     1.36   0.24      2.04
glcm_ClusterShade_d_1_CT_c16                                     0.14   0.71      0.50
glcm_ClusterShade_d_1_PET_b2                                     6.64   0.01      6.65
glcm_ClusterShade_d_1_PET_c04                                    0.17   0.68      0.56
glcm_ClusterTendency_d_1_CT_b20                                  0.08   0.78      0.36
glcm_ClusterTendency_d_1_CT_c16                                  0.11   0.74      0.44
glcm_ClusterTendency_d_1_PET_b2                                  0.11   0.75      0.42
glcm_ClusterTendency_d_1_PET_c04                                 0.01   0.91      0.14
glcm_Contrast_d_1_CT_b20                                         0.00   0.97      0.04
glcm_Contrast_d_1_CT_c16                                         0.04   0.84      0.25
glcm_Contrast_d_1_PET_b2                                         0.00   0.96      0.06
glcm_Contrast_d_1_PET_c04                                        0.01   0.93      0.10
glcm_Correlation_d_1_CT_b20                                      0.06   0.81      0.30
glcm_Correlation_d_1_CT_c16                                      0.37   0.54      0.88
glcm_Correlation_d_1_PET_b2                                      0.01   0.93      0.10
glcm_Correlation_d_1_PET_c04                                     0.00   0.98      0.02
glcm_DifferenceAverage_d_1_CT_b20                                0.01   0.91      0.13
glcm_DifferenceAverage_d_1_CT_c16                                0.00   0.96      0.06
glcm_DifferenceAverage_d_1_PET_b2                                0.05   0.83      0.27
glcm_DifferenceAverage_d_1_PET_c04                               0.00   0.99      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00   0.98      0.03
glcm_DifferenceEntropy_d_1_CT_c16                                0.00   0.96      0.07
glcm_DifferenceEntropy_d_1_PET_b2                                0.00   0.94      0.08
glcm_DifferenceEntropy_d_1_PET_c04                               0.04   0.84      0.25
glcm_DifferenceVariance_d_1_CT_b20                               0.00   0.96      0.06
glcm_DifferenceVariance_d_1_CT_c16                               0.07   0.80      0.33
glcm_DifferenceVariance_d_1_PET_b2                               0.00   0.99      0.01
glcm_DifferenceVariance_d_1_PET_c04                              0.03   0.85      0.23
glcm_Id_d_1_CT_b20                                               0.03   0.87      0.20
glcm_Id_d_1_CT_c16                                               0.00   1.00      0.00
glcm_Id_d_1_PET_b2                                               0.08   0.77      0.37
glcm_Id_d_1_PET_c04                                              0.00   0.95      0.07
glcm_Idm_d_1_CT_b20                                              0.03   0.87      0.20
glcm_Idm_d_1_CT_c16                                              0.00   0.99      0.02
glcm_Idm_d_1_PET_b2                                              0.07   0.79      0.33
glcm_Idm_d_1_PET_c04                                             0.00   0.97      0.05
glcm_Idmn_d_1_CT_b20                                             0.05   0.82      0.29
glcm_Idmn_d_1_CT_c16                                             0.03   0.86      0.21
glcm_Idmn_d_1_PET_b2                                             0.64   0.42      1.24
glcm_Idmn_d_1_PET_c04                                            0.01   0.94      0.09
glcm_Idn_d_1_CT_b20                                              0.02   0.88      0.18
glcm_Idn_d_1_CT_c16                                              0.00   0.98      0.03
glcm_Idn_d_1_PET_b2                                              0.09   0.76      0.40
glcm_Idn_d_1_PET_c04                                             0.00   0.98      0.03
glcm_Imc1_d_1_CT_b20                                             0.00   0.96      0.05
glcm_Imc1_d_1_CT_c16                                             0.44   0.51      0.97
glcm_Imc1_d_1_PET_b2                                             0.02   0.90      0.16
glcm_Imc1_d_1_PET_c04                                            0.00   0.98      0.03
glcm_Imc2_d_1_CT_b20                                             0.07   0.79      0.35
glcm_Imc2_d_1_CT_c16                                             0.98   0.32      1.63
glcm_Imc2_d_1_PET_b2                                             0.06   0.80      0.32
glcm_Imc2_d_1_PET_c04                                            0.01   0.92      0.11
glcm_InverseVariance_d_1_CT_b20                                  0.02   0.88      0.19
glcm_InverseVariance_d_1_CT_c16                                  0.01   0.92      0.12
glcm_InverseVariance_d_1_PET_b2                                  0.17   0.68      0.56
glcm_InverseVariance_d_1_PET_c04                                 0.02   0.88      0.19
glcm_JointAverage_d_1_CT_b20                                     0.00   0.97      0.05
glcm_JointAverage_d_1_CT_c16                                     0.13   0.72      0.47
glcm_JointAverage_d_1_PET_b2                                     0.01   0.92      0.13
glcm_JointAverage_d_1_PET_c04                                    0.00   0.98      0.03
glcm_JointEnergy_d_1_CT_b20                                      0.29   0.59      0.77
glcm_JointEnergy_d_1_CT_c16                                      0.06   0.80      0.31
glcm_JointEnergy_d_1_PET_b2                                      0.01   0.92      0.13
glcm_JointEnergy_d_1_PET_c04                                     0.01   0.92      0.12
glcm_JointEntropy_d_1_CT_b20                                     0.00   0.98      0.03
glcm_JointEntropy_d_1_CT_c16                                     0.11   0.73      0.44
glcm_JointEntropy_d_1_PET_b2                                     0.04   0.85      0.24
glcm_JointEntropy_d_1_PET_c04                                    0.01   0.91      0.13
glcm_MCC_d_1_CT_b20                                              0.05   0.83      0.27
glcm_MCC_d_1_CT_c16                                              0.04   0.85      0.24
glcm_MCC_d_1_PET_b2                                              0.00   0.96      0.05
glcm_MCC_d_1_PET_c04                                             0.04   0.84      0.25
glcm_MaximumProbability_d_1_CT_b20                               0.07   0.79      0.34
glcm_MaximumProbability_d_1_CT_c16                               0.03   0.87      0.20
glcm_MaximumProbability_d_1_PET_b2                               0.06   0.80      0.32
glcm_MaximumProbability_d_1_PET_c04                              0.00   0.97      0.04
glcm_SumAverage_d_1_CT_b20                                       0.00   0.97      0.05
glcm_SumAverage_d_1_CT_c16                                       0.13   0.72      0.47
glcm_SumAverage_d_1_PET_b2                                       0.01   0.92      0.13
glcm_SumAverage_d_1_PET_c04                                      0.00   0.98      0.03
glcm_SumEntropy_d_1_CT_b20                                       0.00   0.98      0.03
glcm_SumEntropy_d_1_CT_c16                                       0.15   0.70      0.51
glcm_SumEntropy_d_1_PET_b2                                       0.04   0.85      0.23
glcm_SumEntropy_d_1_PET_c04                                      0.03   0.85      0.23
glcm_SumSquares_d_1_CT_b20                                       0.07   0.80      0.33
glcm_SumSquares_d_1_CT_c16                                       0.08   0.77      0.37
glcm_SumSquares_d_1_PET_b2                                       0.10   0.75      0.42
glcm_SumSquares_d_1_PET_c04                                      0.01   0.91      0.13
gldm_DependenceEntropy_d_1_CT_b20                                0.11   0.74      0.43
gldm_DependenceEntropy_d_1_CT_c16                                0.36   0.55      0.87
gldm_DependenceEntropy_d_1_PET_b2                                0.01   0.93      0.11
gldm_DependenceEntropy_d_1_PET_c04                               0.46   0.50      1.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.08   0.78      0.36
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.11   0.75      0.42
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.67   0.41      1.27
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.04   0.84      0.24
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00   0.96      0.05
gldm_DependenceNonUniformity_d_1_CT_c16                          1.71   0.19      2.38
gldm_DependenceNonUniformity_d_1_PET_b2                          0.07   0.80      0.33
gldm_DependenceNonUniformity_d_1_PET_c04                         0.14   0.71      0.50
gldm_DependenceVariance_d_1_CT_b20                               1.43   0.23      2.11
gldm_DependenceVariance_d_1_CT_c16                               0.01   0.94      0.09
gldm_DependenceVariance_d_1_PET_b2                               0.01   0.93      0.10
gldm_DependenceVariance_d_1_PET_c04                              0.75   0.38      1.38
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.39   0.53      0.91
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.30   0.58      0.78
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.01   0.91      0.14
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00   0.99      0.02
gldm_GrayLevelVariance_d_1_CT_b20                                0.01   0.90      0.15
gldm_GrayLevelVariance_d_1_CT_c16                                0.02   0.90      0.16
gldm_GrayLevelVariance_d_1_PET_b2                                0.09   0.76      0.39
gldm_GrayLevelVariance_d_1_PET_c04                               0.00   0.96      0.06
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.05   0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.03   0.85      0.23
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.05   0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00   0.97      0.04
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.01   0.90      0.15
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.05   0.82      0.28
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.16   0.69      0.53
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00   0.97      0.04
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.27   0.60      0.73
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.02   0.88      0.19
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.08   0.78      0.36
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00   0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.03   0.87      0.21
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.05   0.83      0.27
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.05   0.82      0.29
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.23   0.63      0.66
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.11   0.74      0.43
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00   0.95      0.07
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00   0.96      0.06
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.05   0.83      0.27
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.02   0.89      0.17
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00   0.95      0.07
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.08   0.78      0.36
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00   0.98      0.03
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.22   0.64      0.65
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.01   0.93      0.10
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.24   0.63      0.67
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.06   0.81      0.31
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.06   0.80      0.32
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.03   0.87      0.21
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.37   0.54      0.88
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.30   0.58      0.78
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.04   0.84      0.26
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.17   0.68      0.55
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00   0.95      0.08
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.15   0.70      0.52
glrlm_GrayLevelNonUniformity_CT_b20                              0.00   1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.57   0.45      1.15
glrlm_GrayLevelNonUniformity_PET_b2                              0.04   0.83      0.26
glrlm_GrayLevelNonUniformity_PET_c04                             0.00   0.99      0.01
glrlm_GrayLevelVariance_CT_b20                                   0.00   0.97      0.04
glrlm_GrayLevelVariance_CT_c16                                   0.01   0.92      0.12
glrlm_GrayLevelVariance_PET_b2                                   0.10   0.75      0.41
glrlm_GrayLevelVariance_PET_c04                                  0.10   0.75      0.42
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.03   0.87      0.21

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['glcm_ClusterShade_d_1_PET_b2',
       'glrlm_LongRunLowGrayLevelEmphasis_CT_c16',
       'glszm_GrayLevelNonUniformity_PET_c04',
       'glszm_LargeAreaEmphasis_CT_c16',
       'glszm_LargeAreaLowGrayLevelEmphasis_CT_c16',
       'glszm_ZoneVariance_CT_c16'],
      dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [18]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data[vif_data['VIF'] > 100000]

                           feature           VIF
0                 shape_Elongation  2.096355e+11
1                   shape_Flatness  3.609232e+11
2            shape_LeastAxisLength  2.691126e+12
3            shape_MajorAxisLength  7.524811e+12
4    shape_Maximum2DDiameterColumn  2.124339e+13
..                             ...           ...
369                    LBP_111_PET  5.922282e+11
370                    LBP_120_PET  3.305758e+11
371                    LBP_201_PET  1.508996e+12
372                    LBP_210_PET  1.369708e+12
373                    LBP_300_PET  7.392136e+09

[374 rows x 2 columns]

# Standardization

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

# Standardize non-categorical and then concat with the categorical
scaler = RobustScaler()  
X_std = scaler.fit_transform(X)
X_std = pd.DataFrame(X_std, columns=X_columns, index=X_index)

In [25]:
# Standardize the numeric part 
X_MAASTRO_column = X_MAASTRO.columns
X_MAASTRO_index = X_MAASTRO.index

X_MAASTRO_std = scaler.transform(X_MAASTRO)

# Change the standardized part into a dataframe 
X_MAASTRO_std = pd.DataFrame(X_MAASTRO_std, columns=X_MAASTRO_column, index=X_MAASTRO_index)

In [26]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

In [27]:
X_new_std.isna().sum().sum()

0

In [28]:
X_new_std["LBP_003_PET"]

0      1.259511
1      3.566490
2      0.000000
3      3.059892
4      0.000000
         ...
134    0.000000
135    0.401955
136    0.000000
137    0.000000
138    0.000000
Name: LBP_003_PET, Length: 139, dtype: float64

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [29]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:51:12,930] A new study created in memory with name: no-name-bf243262-33b8-4b96-bdb6-0c03b984077e

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-16 00:51:14,194] Trial 0 failed with parameters: {} because of the following error: ValueError('search direction contains NaN or infinite values').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_80879/4166082094.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 454, in fit
    raise ValueError("search direction contains NaN or infinite values")
ValueError: search direction contains NaN or infinite values
[W 2024-04-16 00:51:14,212] Trial 0 failed with value None.

ValueError: search direction contains NaN or infinite values

In [30]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {}

In [31]:
# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [34]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [35]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:54:19,397] A new study created in memory with name: no-name-3c00979d-6230-4797-8db9-0e1e9a8cc597

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.6624472573839663

[I 2024-04-16 00:54:20,148] A new study created in memory with name: no-name-250dc81f-4739-4162-883f-909ebfba89ef

Fold 5 C-index: 0.5774647887323944
[I 2024-04-16 00:54:20,136] Trial 0 finished with value: 0.6505821991392386 and parameters: {}. Best is trial 0 with value: 0.6505821991392386.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6505821991392386], datetime_start=datetime.datetime(2024, 4, 16, 0, 54, 19, 450869), datetime_complete=datetime.datetime(2024, 4, 16, 0, 54, 20, 134630), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6505821991392386

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651830695444
Fold 2 IBS: 0.22157791625059692
Fold 3 IBS: 0.20453594280733517
Fold 4 IBS: 0.22473802997425457
Fold 5 IBS: 0.21812431597978285
[I 2024-04-16 00:54:20,872] Trial 0 finished with value: 0.21659054466378475 and parameters: {}. Best is trial 0 with value: 0.21659054466378475.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054466378475], datetime_start=datetime.datetime(2024, 4, 16, 0, 54, 20, 183087), datetime_complete=datetime.datetime(2024, 4, 16, 0, 54, 20, 871931), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054466378475

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.651
train_ibs:  0.217

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.592

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:54:21,130] A new study created in memory with name: no-name-cfe74e1f-0f33-43b5-93b0-14202f95aa0f

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683

[I 2024-04-16 00:54:22,444] A new study created in memory with name: no-name-c2079d69-4631-405d-a5ae-79da934f29de

Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:54:22,433] Trial 0 finished with value: 0.6921467241250704 and parameters: {}. Best is trial 0 with value: 0.6921467241250704.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6921467241250704], datetime_start=datetime.datetime(2024, 4, 16, 0, 54, 21, 166948), datetime_complete=datetime.datetime(2024, 4, 16, 0, 54, 22, 433165), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6921467241250704

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21388429370731754
Fold 2 IBS: 0.16947150486287754
Fold 3 IBS: 0.16443846820135807
Fold 4 IBS: 0.24040286625883342
Fold 5 IBS: 0.20342676247270347
[I 2024-04-16 00:54:23,835] Trial 0 finished with value: 0.19832477910061802 and parameters: {}. Best is trial 0 with value: 0.19832477910061802.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19832477910061802], datetime_start=datetime.datetime(2024, 4, 16, 0, 54, 22, 502419), datetime_complete=datetime.datetime(2024, 4, 16, 0, 54, 23, 835386), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19832477910061802

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.692
train_ibs:  0.198

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.597

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.221

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:54:24,182] A new study created in memory with name: no-name-96ddab9a-2a05-431d-b40b-41978739bfda

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:25,322] Trial 0 finished with value: 0.6901012700903632 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6901012700903632.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:26,333] Trial 1 finished with value: 0.6903530007523196 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6903530007523196.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:27,308] Trial 2 finished with value: 0.6865575268665628 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6903530007523196.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:54:28,492] Trial 3 finished with value: 0.6910863472198066 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.6910863472198066.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:54:29,876] Trial 4 finished with value: 0.6919330943693707 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.6919330943693707.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:31,141] Trial 5 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:54:32,111] Trial 6 finished with value: 0.6938910133900722 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:33,130] Trial 7 finished with value: 0.6901012700903632 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:54:34,075] Trial 8 finished with value: 0.6946398099670021 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:34,928] Trial 9 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 00:54:36,332] Trial 10 finished with value: 0.6814682608160527 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:37,619] Trial 11 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.3734960813237434}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 00:54:38,718] Trial 12 finished with value: 0.6825898482458188 and parameters: {'l1_ratio': 0.11356797167713778}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:40,198] Trial 13 finished with value: 0.6937008428308518 and parameters: {'l1_ratio': 0.4449202644507797}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:41,641] Trial 14 finished with value: 0.6913333929091824 and parameters: {'l1_ratio': 0.2893683497253}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:54:43,002] Trial 15 finished with value: 0.6901473800836564 and parameters: {'l1_ratio': 0.5663511759427868}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.5821596244131455
[I 2024-04-16 00:54:43,513] Trial 16 finished with value: 0.649440945521955 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:44,389] Trial 17 finished with value: 0.6902867556770029 and parameters: {'l1_ratio': 0.8244104217192855}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 00:54:45,271] Trial 18 finished with value: 0.6944525047008059 and parameters: {'l1_ratio': 0.3798015106074873}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:54:46,645] Trial 19 finished with value: 0.6910402372265134 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:47,976] Trial 20 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.4060784267370561}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:49,548] Trial 21 finished with value: 0.6943206793730636 and parameters: {'l1_ratio': 0.33492971197046034}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:51,138] Trial 22 finished with value: 0.6864699918525572 and parameters: {'l1_ratio': 0.20350763212036774}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:54:52,327] Trial 23 finished with value: 0.693746952824145 and parameters: {'l1_ratio': 0.4714090815951266}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931

Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:53,609] Trial 24 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.39872004425394175}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:54:54,790] Trial 25 finished with value: 0.6864699918525572 and parameters: {'l1_ratio': 0.2047855727725989}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:56,290] Trial 26 finished with value: 0.6943206793730636 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:54:58,170] Trial 27 finished with value: 0.6920206293833762 and parameters: {'l1_ratio': 0.526404719543659}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.75
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:54:59,776] Trial 28 finished with value: 0.6891208779335004 and parameters: {'l1_ratio': 0.6276972916515388}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 00:55:01,296] Trial 29 finished with value: 0.6834337301023587 and parameters: {'l1_ratio': 0.1391392813300431}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:02,470] Trial 30 finished with value: 0.6894601436094624 and parameters: {'l1_ratio': 0.26103069374174487}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:03,610] Trial 31 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.42504378566334805}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:04,860] Trial 32 finished with value: 0.693469247250919 and parameters: {'l1_ratio': 0.3513068739102617}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:05,962] Trial 33 finished with value: 0.6928079856879947 and parameters: {'l1_ratio': 0.45511889559771357}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:07,711] Trial 34 finished with value: 0.6928645112399163 and parameters: {'l1_ratio': 0.5197231016182638}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.75
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:09,452] Trial 35 finished with value: 0.6932941772229079 and parameters: {'l1_ratio': 0.306558542839888}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:11,200] Trial 36 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.41820673676854797}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:12,548] Trial 37 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.42690535349469017}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:13,980] Trial 38 finished with value: 0.6902453306562906 and parameters: {'l1_ratio': 0.7448456868133118}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:16,907] Trial 39 finished with value: 0.6901473800836564 and parameters: {'l1_ratio': 0.597239423422592}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:18,881] Trial 40 finished with value: 0.694544724687392 and parameters: {'l1_ratio': 0.43941885286525595}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:22,733] Trial 41 finished with value: 0.6929520462539219 and parameters: {'l1_ratio': 0.49432600142492505}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:31,882] Trial 42 finished with value: 0.6857136450100227 and parameters: {'l1_ratio': 0.23754419756151202}. Best is trial 5 with value: 0.6954375818302492.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:36,521] Trial 43 finished with value: 0.6963304389731062 and parameters: {'l1_ratio': 0.4108759560861602}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:37,690] Trial 44 finished with value: 0.6963304389731062 and parameters: {'l1_ratio': 0.41548531625584345}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:39,097] Trial 45 finished with value: 0.6901012700903632 and parameters: {'l1_ratio': 0.6650853818004321}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:55:40,680] Trial 46 finished with value: 0.6910863472198066 and parameters: {'l1_ratio': 0.5536376141166528}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:41,882] Trial 47 finished with value: 0.6929520462539219 and parameters: {'l1_ratio': 0.5063994947206192}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931

Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:42,869] Trial 48 finished with value: 0.6923137850660451 and parameters: {'l1_ratio': 0.29873605267001413}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:43,886] Trial 49 finished with value: 0.6943621043937761 and parameters: {'l1_ratio': 0.355745098499332}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:45,225] Trial 50 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:46,547] Trial 51 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.42563613705308495}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:47,992] Trial 52 finished with value: 0.6946398099670021 and parameters: {'l1_ratio': 0.475165012444404}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:49,290] Trial 53 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.37435743625386736}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:50,912] Trial 54 finished with value: 0.6901473800836564 and parameters: {'l1_ratio': 0.5688899967178812}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:55:52,259] Trial 55 finished with value: 0.693047131533532 and parameters: {'l1_ratio': 0.972687298645671}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:53,427] Trial 56 finished with value: 0.694544724687392 and parameters: {'l1_ratio': 0.4380274476517663}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 00:55:54,676] Trial 57 finished with value: 0.6944525047008059 and parameters: {'l1_ratio': 0.38183503274900876}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:55:55,963] Trial 58 finished with value: 0.6894601436094624 and parameters: {'l1_ratio': 0.26349736625794984}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:55:57,176] Trial 59 finished with value: 0.6946398099670021 and parameters: {'l1_ratio': 0.4783788562725973}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:58,208] Trial 60 finished with value: 0.6952135365159208 and parameters: {'l1_ratio': 0.32859892155460607}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:55:59,349] Trial 61 finished with value: 0.6963304389731062 and parameters: {'l1_ratio': 0.4117473826713238}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:00,626] Trial 62 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.40471518954279423}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:01,842] Trial 63 finished with value: 0.6920206293833762 and parameters: {'l1_ratio': 0.5269618376196294}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:02,961] Trial 64 finished with value: 0.6937008428308518 and parameters: {'l1_ratio': 0.4462280824699452}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.75
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:04,055] Trial 65 finished with value: 0.694233144359058 and parameters: {'l1_ratio': 0.3147313718149082}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:05,055] Trial 66 finished with value: 0.6952549615366334 and parameters: {'l1_ratio': 0.3547301901964412}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:06,269] Trial 67 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.39626397357514925}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:07,545] Trial 68 finished with value: 0.6928079856879947 and parameters: {'l1_ratio': 0.4567131728874593}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:08,657] Trial 69 finished with value: 0.6903530007523196 and parameters: {'l1_ratio': 0.2716319242939854}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:09,980] Trial 70 finished with value: 0.6937959281104621 and parameters: {'l1_ratio': 0.48754539734555474}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:11,126] Trial 71 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.4161240735605186}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931

Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:12,203] Trial 72 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.42307785573652956}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:13,405] Trial 73 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.36634064931048543}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:14,896] Trial 74 finished with value: 0.6920206293833762 and parameters: {'l1_ratio': 0.5244501333749242}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:16,153] Trial 75 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.3971655367534999}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:17,521] Trial 76 finished with value: 0.6937008428308518 and parameters: {'l1_ratio': 0.4541988721950681}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:19,284] Trial 77 finished with value: 0.6901473800836564 and parameters: {'l1_ratio': 0.578621040403159}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:24,212] Trial 78 finished with value: 0.6943206793730636 and parameters: {'l1_ratio': 0.34237880676604254}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:25,829] Trial 79 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.41782934016392664}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:27,072] Trial 80 finished with value: 0.6929520462539219 and parameters: {'l1_ratio': 0.501907114000914}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:28,296] Trial 81 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.4299727226781332}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:29,596] Trial 82 finished with value: 0.693746952824145 and parameters: {'l1_ratio': 0.4650062464113186}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 00:56:30,994] Trial 83 finished with value: 0.6944525047008059 and parameters: {'l1_ratio': 0.3805231665127908}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:32,053] Trial 84 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.428489490367322}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:56:33,546] Trial 85 finished with value: 0.6910863472198066 and parameters: {'l1_ratio': 0.5439933656281303}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:34,603] Trial 86 finished with value: 0.6943206793730636 and parameters: {'l1_ratio': 0.3326169760591041}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:35,992] Trial 87 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.37066386335279894}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:37,742] Trial 88 finished with value: 0.6929520462539219 and parameters: {'l1_ratio': 0.4946244107218348}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:39,597] Trial 89 finished with value: 0.6913333929091824 and parameters: {'l1_ratio': 0.29470810034785055}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:40,718] Trial 90 finished with value: 0.6857136450100227 and parameters: {'l1_ratio': 0.23578060659877265}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:42,393] Trial 91 finished with value: 0.6954375818302492 and parameters: {'l1_ratio': 0.4182346263895191}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:44,010] Trial 92 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.407419752357548}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:45,330] Trial 93 finished with value: 0.693746952824145 and parameters: {'l1_ratio': 0.4673232746739079}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:56:46,774] Trial 94 finished with value: 0.695391471836956 and parameters: {'l1_ratio': 0.3882861643925188}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:48,141] Trial 95 finished with value: 0.6937008428308518 and parameters: {'l1_ratio': 0.44246849690069534}. Best is trial 43 with value: 0.6963304389731062.

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:50,380] Trial 96 finished with value: 0.6943206793730636 and parameters: {'l1_ratio': 0.34570926129495827}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.75
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:51,685] Trial 97 finished with value: 0.694233144359058 and parameters: {'l1_ratio': 0.31222999134269813}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:56:52,895] Trial 98 finished with value: 0.6938449033967791 and parameters: {'l1_ratio': 0.5119143744273287}. Best is trial 43 with value: 0.6963304389731062.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697

[I 2024-04-16 00:56:54,065] A new study created in memory with name: no-name-22a83617-1e74-4d1b-af02-08d4a9ae613b

Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:56:54,045] Trial 99 finished with value: 0.6963304389731062 and parameters: {'l1_ratio': 0.4115400760211988}. Best is trial 43 with value: 0.6963304389731062.


* Best trial for C-index:
 FrozenTrial(number=43, state=TrialState.COMPLETE, values=[0.6963304389731062], datetime_start=datetime.datetime(2024, 4, 16, 0, 55, 31, 977965), datetime_complete=datetime.datetime(2024, 4, 16, 0, 55, 36, 520891), params={'l1_ratio': 0.4108759560861602}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=43, value=None)


* Best Score for C-index:
 0.6963304389731062

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21388436919013662
Fold 2 IBS: 0.16872554090906264
Fold 3 IBS: 0.16585866370109062
Fold 4 IBS: 0.24094148368043922
Fold 5 IBS: 0.2027081696158459
[I 2024-04-16 00:56:55,440] Trial 0 finished with value: 0.198423645419315 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.198423645419315.
Fold 1 IBS: 0.2138847246005204
Fold 2 IBS: 0.1713907076279496
Fold 3 IBS: 0.1720826886294347
Fold 4 IBS: 0.22847681941955345
Fold 5 IBS: 0.20556841143778454
[I 2024-04-16 00:56:56,673] Trial 1 finished with value: 0.19828067034304855 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.19828067034304855.
Fold 1 IBS: 0.21388488162509872
Fold 2 IBS: 0.1720185457250986
Fold 3 IBS: 0.17311301412835467
Fold 4 IBS: 0.22352367437864135
Fold 5 IBS: 0.20661093300189348
[I 2024-04-16 00:56:57,843] Trial 2 finished with value: 0.19783020977181737 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.21388443459292844
Fold 2 IBS: 0.1690612126387475
Fold 3 IBS: 0.16711965228602046
Fold 4 IBS: 0.2393448022959076
Fold 5 IBS: 0.20306662676555667
[I 2024-04-16 00:56:58,776] Trial 3 finished with value: 0.1984953457158321 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.21388436124452687
Fold 2 IBS: 0.16880963483271966
Fold 3 IBS: 0.16566983809276828
Fold 4 IBS: 0.24124369167358117
Fold 5 IBS: 0.2027372320762933
[I 2024-04-16 00:56:59,727] Trial 4 finished with value: 0.19846895158397784 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.21388452956315143
Fold 2 IBS: 0.1701867115325285
Fold 3 IBS: 0.16919001174075976
Fold 4 IBS: 0.23581463224642538
Fold 5 IBS: 0.20420902888023806
[I 2024-04-16 00:57:00,635] Trial 5 finished with value: 0.19865698279262062 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.2138842971062154
Fold 2 IBS: 0.16940947267548123
Fold 3 IBS: 0.1644927586452849
Fold 4 IBS: 0.24035244026000802
Fold 5 IBS: 0.20342577279308133
[I 2024-04-16 00:57:01,532] Trial 6 finished with value: 0.19831294829601415 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.21388437341413574
Fold 2 IBS: 0.16869793532643237
Fold 3 IBS: 0.16595083946398934
Fold 4 IBS: 0.24081095957947377
Fold 5 IBS: 0.20270476792526565
[I 2024-04-16 00:57:02,423] Trial 7 finished with value: 0.19840977514185937 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.2138844804780509
Fold 2 IBS: 0.1696477801115847
Fold 3 IBS: 0.1681445647245519
Fold 4 IBS: 0.2377038467348608
Fold 5 IBS: 0.20362325860254576
[I 2024-04-16 00:57:03,420] Trial 8 finished with value: 0.1986007861303188 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.2138845618055211
Fold 2 IBS: 0.17052593982932784
Fold 3 IBS: 0.1698128734212492
Fold 4 IBS: 0.2347497671469039
Fold 5 IBS: 0.20448453259273053
[I 2024-04-16 00:57:04,822] Trial 9 finished with value: 0.1986915349591465 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.21388616205636699
Fold 2 IBS: 0.17645767065268464
Fold 3 IBS: 0.17541383077798978
Fold 4 IBS: 0.2157363843717844
Fold 5 IBS: 0.21006888034803056
[I 2024-04-16 00:57:05,848] Trial 10 finished with value: 0.19831258564137128 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.19783020977181737.
Fold 1 IBS: 0.21388502498192644
Fold 2 IBS: 0.17267598703076467
Fold 3 IBS: 0.17373999593075604
Fold 4 IBS: 0.22057911588529072
Fold 5 IBS: 0.2074526951519072
[I 2024-04-16 00:57:07,026] Trial 11 finished with value: 0.19766656379612904 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388762071002543
Fold 2 IBS: 0.17964781788242243
Fold 3 IBS: 0.17615015441348758
Fold 4 IBS: 0.21270380676972425
Fold 5 IBS: 0.21275116038547462
[I 2024-04-16 00:57:08,038] Trial 12 finished with value: 0.19902811203222687 and parameters: {'l1_ratio': 0.04835900598617554}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388493704383676
Fold 2 IBS: 0.17228343339658042
Fold 3 IBS: 0.17337424193442222
Fold 4 IBS: 0.22222215480471272
Fold 5 IBS: 0.20695277576657983
[I 2024-04-16 00:57:08,983] Trial 13 finished with value: 0.19774350858922637 and parameters: {'l1_ratio': 0.2114475350243538}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138850550512913
Fold 2 IBS: 0.1728145238455031
Fold 3 IBS: 0.17385348715052973
Fold 4 IBS: 0.2201981341908881
Fold 5 IBS: 0.20758398435179157
[I 2024-04-16 00:57:10,016] Trial 14 finished with value: 0.19766703691800075 and parameters: {'l1_ratio': 0.18459727307810245}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21390597237525544
Fold 2 IBS: 0.22157248545839575
Fold 3 IBS: 0.20443373677958782
Fold 4 IBS: 0.224003806616893
Fold 5 IBS: 0.2161868784715117
[I 2024-04-16 00:57:10,712] Trial 15 finished with value: 0.21602057594032872 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388509330496025
Fold 2 IBS: 0.17298117232946572
Fold 3 IBS: 0.17397097582537002
Fold 4 IBS: 0.21977745813637042
Fold 5 IBS: 0.20772826742564596
[I 2024-04-16 00:57:11,710] Trial 16 finished with value: 0.19766859340436246 and parameters: {'l1_ratio': 0.1772909900515591}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.213884658976353
Fold 2 IBS: 0.17108063626874134
Fold 3 IBS: 0.17140867978908542
Fold 4 IBS: 0.23103389887795664
Fold 5 IBS: 0.2051316513687463
[I 2024-04-16 00:57:12,639] Trial 17 finished with value: 0.19850790505617658 and parameters: {'l1_ratio': 0.32122361783531583}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388520694006463
Fold 2 IBS: 0.17346484873197546
Fold 3 IBS: 0.1742612741967526
Fold 4 IBS: 0.218849051804974
Fold 5 IBS: 0.20807896103711737
[I 2024-04-16 00:57:13,529] Trial 18 finished with value: 0.19770786854217684 and parameters: {'l1_ratio': 0.15862043873278764}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388463608689248
Fold 2 IBS: 0.17096422264530084
Fold 3 IBS: 0.17110523291370813
Fold 4 IBS: 0.23188283526696712
Fold 5 IBS: 0.20500477359773714
[I 2024-04-16 00:57:14,484] Trial 19 finished with value: 0.19856834010212115 and parameters: {'l1_ratio': 0.33553118018836076}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138844224328681
Fold 2 IBS: 0.16889458639591506
Fold 3 IBS: 0.16682209199849574
Fold 4 IBS: 0.23980726662915544
Fold 5 IBS: 0.20292215794305885
[I 2024-04-16 00:57:15,439] Trial 20 finished with value: 0.19846610507989865 and parameters: {'l1_ratio': 0.5735915190759935}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388538276074517
Fold 2 IBS: 0.1740237415085293
Fold 3 IBS: 0.17459409111818178
Fold 4 IBS: 0.21796339352810165
Fold 5 IBS: 0.20846952473715835
[I 2024-04-16 00:57:16,362] Trial 21 finished with value: 0.19778722673054325 and parameters: {'l1_ratio': 0.13635505299002057}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388493677441808
Fold 2 IBS: 0.17228227515251796
Fold 3 IBS: 0.17337300577834983
Fold 4 IBS: 0.22222807074250248
Fold 5 IBS: 0.2069510234954445
[I 2024-04-16 00:57:17,602] Trial 22 finished with value: 0.19774386238864655 and parameters: {'l1_ratio': 0.21151771449890427}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388564790657863
Fold 2 IBS: 0.17491446107843295
Fold 3 IBS: 0.17493179946638593
Fold 4 IBS: 0.21734296563920333
Fold 5 IBS: 0.20898845980277966
[I 2024-04-16 00:57:18,850] Trial 23 finished with value: 0.1980126667786761 and parameters: {'l1_ratio': 0.1124690541840564}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388474106273642
Fold 2 IBS: 0.17143715794110106
Fold 3 IBS: 0.17221280349514032
Fold 4 IBS: 0.22785389083079066
Fold 5 IBS: 0.2056863469468316
[I 2024-04-16 00:57:20,119] Trial 24 finished with value: 0.19821498805532003 and parameters: {'l1_ratio': 0.2785887116400876}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388456458771282

Fold 2 IBS: 0.1705544765835578
Fold 3 IBS: 0.16986686960505
Fold 4 IBS: 0.2346389666114288
Fold 5 IBS: 0.20450114401823224
[I 2024-04-16 00:57:21,163] Trial 25 finished with value: 0.19868920428119635 and parameters: {'l1_ratio': 0.38971525832834536}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138851812456519
Fold 2 IBS: 0.17337212387309434
Fold 3 IBS: 0.1741993036293637
Fold 4 IBS: 0.21900244767207094
Fold 5 IBS: 0.20802325154179155
[I 2024-04-16 00:57:22,172] Trial 26 finished with value: 0.19769646159239446 and parameters: {'l1_ratio': 0.16249222718249173}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138938382863775
Fold 2 IBS: 0.22157714031057676
Fold 3 IBS: 0.204411983184728
Fold 4 IBS: 0.22294279167832742
Fold 5 IBS: 0.21578496298560398
[I 2024-04-16 00:57:22,842] Trial 27 finished with value: 0.2157221432891227 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388430000113584
Fold 2 IBS: 0.1693612909386374
Fold 3 IBS: 0.1645410781832172
Fold 4 IBS: 0.24034207167566646
Fold 5 IBS: 0.20342510498417318
[I 2024-04-16 00:57:23,898] Trial 28 finished with value: 0.19831076915656604 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138849168754049
Fold 2 IBS: 0.17217467571249626
Fold 3 IBS: 0.17328534899320047
Fold 4 IBS: 0.2226749454512554
Fold 5 IBS: 0.20683229643271328
[I 2024-04-16 00:57:24,830] Trial 29 finished with value: 0.19777043669301406 and parameters: {'l1_ratio': 0.21683231629619723}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388629421993316
Fold 2 IBS: 0.17682270932126273
Fold 3 IBS: 0.1755450203495111
Fold 4 IBS: 0.21542024153650735
Fold 5 IBS: 0.21037065131963378
[I 2024-04-16 00:57:25,846] Trial 30 finished with value: 0.19840898334936963 and parameters: {'l1_ratio': 0.07865340906447406}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388521141666367
Fold 2 IBS: 0.17347866361277484
Fold 3 IBS: 0.17426998320342937
Fold 4 IBS: 0.21882237692109652
Fold 5 IBS: 0.20808903751403274
[I 2024-04-16 00:57:26,809] Trial 31 finished with value: 0.1977090545335994 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388475239808385
Fold 2 IBS: 0.17148015617313445
Fold 3 IBS: 0.1723053685349769
Fold 4 IBS: 0.22743817581108322
Fold 5 IBS: 0.20575610201238473
[I 2024-04-16 00:57:27,735] Trial 32 finished with value: 0.19817291098593265 and parameters: {'l1_ratio': 0.27357119396913165}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138848151084526
Fold 2 IBS: 0.17173409772047926
Fold 3 IBS: 0.17273064169653196
Fold 4 IBS: 0.22529447015949683
Fold 5 IBS: 0.20616033120924682
[I 2024-04-16 00:57:28,640] Trial 33 finished with value: 0.19796087117884148 and parameters: {'l1_ratio': 0.24877046578938972}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388512314480135
Fold 2 IBS: 0.17311004906244487
Fold 3 IBS: 0.17405331273417585
Fold 4 IBS: 0.2194606008433801
Fold 5 IBS: 0.20784582505914959
[I 2024-04-16 00:57:29,600] Trial 34 finished with value: 0.19767098216879037 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138846369082635
Fold 2 IBS: 0.1709689020222874
Fold 3 IBS: 0.17111663040071567
Fold 4 IBS: 0.23185672517639833
Fold 5 IBS: 0.20500983431512956
[I 2024-04-16 00:57:30,511] Trial 35 finished with value: 0.1985673457645589 and parameters: {'l1_ratio': 0.3349958381129322}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.213884323499145
Fold 2 IBS: 0.1691532680513386
Fold 3 IBS: 0.16494758176221
Fold 4 IBS: 0.24109132279406362
Fold 5 IBS: 0.20313423459912064
[I 2024-04-16 00:57:31,438] Trial 36 finished with value: 0.19844214614117556 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138844953702266
Fold 2 IBS: 0.1698201292062338
Fold 3 IBS: 0.16848488876248274
Fold 4 IBS: 0.23713789924813167
Fold 5 IBS: 0.20379494918019053
[I 2024-04-16 00:57:32,405] Trial 37 finished with value: 0.19862447235345307 and parameters: {'l1_ratio': 0.4618429561833801}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388442764056637
Fold 2 IBS: 0.1689683312305137
Fold 3 IBS: 0.1669515538527582
Fold 4 IBS: 0.23963250508523704
Fold 5 IBS: 0.20298253648832495
[I 2024-04-16 00:57:33,352] Trial 38 finished with value: 0.19848387085948005 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388496786663105
Fold 2 IBS: 0.1724184888735976
Fold 3 IBS: 0.17350941127977754
Fold 4 IBS: 0.2215601383061512
Fold 5 IBS: 0.20715115411721796
[I 2024-04-16 00:57:34,198] Trial 39 finished with value: 0.19770483208867506 and parameters: {'l1_ratio': 0.20371314742924654}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388601965430393
Fold 2 IBS: 0.17605762420286905
Fold 3 IBS: 0.17524571725194624
Fold 4 IBS: 0.2162536543038485
Fold 5 IBS: 0.20970757552435515
[I 2024-04-16 00:57:35,088] Trial 40 finished with value: 0.19823011818746455 and parameters: {'l1_ratio': 0.0902077919103536}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138851502531393
Fold 2 IBS: 0.1732364441796279
Fold 3 IBS: 0.17412434097022797
Fold 4 IBS: 0.21918260121624977
Fold 5 IBS: 0.2079460730131657
[I 2024-04-16 00:57:35,984] Trial 41 finished with value: 0.19767492192648212 and parameters: {'l1_ratio': 0.1674193581841118}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138851113941134
Fold 2 IBS: 0.17305810505770064
Fold 3 IBS: 0.17402289085850095
Fold 4 IBS: 0.21958681558123427
Fold 5 IBS: 0.20780034191603572
[I 2024-04-16 00:57:36,894] Trial 42 finished with value: 0.197670652961517 and parameters: {'l1_ratio': 0.17403241938277308}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388696425434403
Fold 2 IBS: 0.17841354516183003
Fold 3 IBS: 0.17592644623459253
Fold 4 IBS: 0.21407923635277223
Fold 5 IBS: 0.21176896151346725
[I 2024-04-16 00:57:37,784] Trial 43 finished with value: 0.19881503070340123 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138846612652138
Fold 2 IBS: 0.17109253813285022
Fold 3 IBS: 0.1714379873107158
Fold 4 IBS: 0.23093747916371746
Fold 5 IBS: 0.20514358826141513
[I 2024-04-16 00:57:38,690] Trial 44 finished with value: 0.1984992508267825 and parameters: {'l1_ratio': 0.31985948791409313}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.2138848165277879
Fold 2 IBS: 0.17174006949639506
Fold 3 IBS: 0.17274009631644716
Fold 4 IBS: 0.22525400059635778
Fold 5 IBS: 0.20617078276237694
[I 2024-04-16 00:57:39,633] Trial 45 finished with value: 0.19795795313987297 and parameters: {'l1_ratio': 0.24826083905790292}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388558873805544
Fold 2 IBS: 0.17471910704356078
Fold 3 IBS: 0.17486155210405321
Fold 4 IBS: 0.21743778596207558
Fold 5 IBS: 0.2088868534782484
[I 2024-04-16 00:57:40,489] Trial 46 finished with value: 0.1979581774651987 and parameters: {'l1_ratio': 0.11705177098606492}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388457230093405
Fold 2 IBS: 0.17062201686461756
Fold 3 IBS: 0.17001251614223142
Fold 4 IBS: 0.2343505505355922
Fold 5 IBS: 0.20457431355756073
[I 2024-04-16 00:57:41,374] Trial 47 finished with value: 0.19868879388018718 and parameters: {'l1_ratio': 0.3830453253067302}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388938762377566
Fold 2 IBS: 0.18163362353611887
Fold 3 IBS: 0.20440361613518174
Fold 4 IBS: 0.20745785482570245
Fold 5 IBS: 0.21425290647878034
[I 2024-04-16 00:57:42,148] Trial 48 finished with value: 0.20432747771991183 and parameters: {'l1_ratio': 0.031697267572632026}. Best is trial 11 with value: 0.19766656379612904.
Fold 1 IBS: 0.21388502537958776
Fold 2 IBS: 0.1726777974802222
Fold 3 IBS: 0.17374142716017324
Fold 4 IBS: 0.22057356840502693
Fold 5 IBS: 0.2074544909746452
[I 2024-04-16 00:57:43,099] Trial 49 finished with value: 0.19766646187993106 and parameters: {'l1_ratio': 0.190689678045818}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388440607938616

Fold 2 IBS: 0.1687302436372449
Fold 3 IBS: 0.1665463043097159
Fold 4 IBS: 0.23998063559859353
Fold 5 IBS: 0.20279600525810057
[I 2024-04-16 00:57:44,077] Trial 50 finished with value: 0.1983875189766082 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388511664985185
Fold 2 IBS: 0.17308286992597052
Fold 3 IBS: 0.17403783616795956
Fold 4 IBS: 0.21953230750548927
Fold 5 IBS: 0.20782090282600116
[I 2024-04-16 00:57:44,932] Trial 51 finished with value: 0.19767180661505449 and parameters: {'l1_ratio': 0.1731078328032106}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.2138849956004868
Fold 2 IBS: 0.17254222180713405
Fold 3 IBS: 0.1736305061988107
Fold 4 IBS: 0.22100432391464694
Fold 5 IBS: 0.20731922810385905
[I 2024-04-16 00:57:45,815] Trial 52 finished with value: 0.19767625512498752 and parameters: {'l1_ratio': 0.1972193563254032}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388481479517635
Fold 2 IBS: 0.17173279429151136
Fold 3 IBS: 0.17272854901005957
Fold 4 IBS: 0.2253034289799876
Fold 5 IBS: 0.2061580195085683
[I 2024-04-16 00:57:46,868] Trial 53 finished with value: 0.19796152131706063 and parameters: {'l1_ratio': 0.24888323135652285}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388559816895666
Fold 2 IBS: 0.17475034525061975
Fold 3 IBS: 0.17487704220429806
Fold 4 IBS: 0.21741407696718984
Fold 5 IBS: 0.20890351706918273
[I 2024-04-16 00:57:48,019] Trial 54 finished with value: 0.19796611593204944 and parameters: {'l1_ratio': 0.11629675066807432}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388469963101828
Fold 2 IBS: 0.17127161094634288
Fold 3 IBS: 0.17187157503115633
Fold 4 IBS: 0.22934473348425877
Fold 5 IBS: 0.20538573335342591
[I 2024-04-16 00:57:49,101] Trial 55 finished with value: 0.19835167048924043 and parameters: {'l1_ratio': 0.2985982022464991}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.2138845905408806
Fold 2 IBS: 0.17074812280010496
Fold 3 IBS: 0.17035466063505944
Fold 4 IBS: 0.23370321243006595
Fold 5 IBS: 0.20470080929077758
[I 2024-04-16 00:57:50,183] Trial 56 finished with value: 0.19867827913937772 and parameters: {'l1_ratio': 0.36814278259512045}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388450607268716
Fold 2 IBS: 0.16993844517809567
Fold 3 IBS: 0.16871112396725457
Fold 4 IBS: 0.23670044362762713
Fold 5 IBS: 0.20393074087324584
[I 2024-04-16 00:57:51,388] Trial 57 finished with value: 0.19863305194378206 and parameters: {'l1_ratio': 0.4489994655356767}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388544403041151
Fold 2 IBS: 0.1742292733312646
Fold 3 IBS: 0.17468433936026118
Fold 4 IBS: 0.21776937171235988
Fold 5 IBS: 0.20860709190933818
[I 2024-04-16 00:57:52,579] Trial 58 finished with value: 0.1978351040687271 and parameters: {'l1_ratio': 0.1299855408485913}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.2138869575653041
Fold 2 IBS: 0.17839986617236786
Fold 3 IBS: 0.17592427799637303
Fold 4 IBS: 0.2140926351332224
Fold 5 IBS: 0.21175697494588375
[I 2024-04-16 00:57:53,708] Trial 59 finished with value: 0.19881214236263023 and parameters: {'l1_ratio': 0.05996425586024892}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.21388483452333654
Fold 2 IBS: 0.17181472105933163
Fold 3 IBS: 0.17284949075834835
Fold 4 IBS: 0.22474708717773278
Fold 5 IBS: 0.20629466711878772
[I 2024-04-16 00:57:54,884] Trial 60 finished with value: 0.19791816012750743 and parameters: {'l1_ratio': 0.24197496410285593}. Best is trial 49 with value: 0.19766646187993106.
Fold 1 IBS: 0.2138850856829847
Fold 2 IBS: 0.1729473125972107
Fold 3 IBS: 0.1739487158585223
Fold 4 IBS: 0.21985455676317137
Fold 5 IBS: 0.20769088651941128
[I 2024-04-16 00:57:55,967] Trial 61 finished with value: 0.19766531148426006 and parameters: {'l1_ratio': 0.17870057023997313}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388506213537326
Fold 2 IBS: 0.17284996798154922
Fold 3 IBS: 0.17387371454243783
Fold 4 IBS: 0.22011659986104815
Fold 5 IBS: 0.20760951208293002
[I 2024-04-16 00:57:56,965] Trial 62 finished with value: 0.19766697132066768 and parameters: {'l1_ratio': 0.1831994743955898}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138850074633568
Fold 2 IBS: 0.17259539607032173
Fold 3 IBS: 0.17367554590436377
Fold 4 IBS: 0.22082048543858177
Fold 5 IBS: 0.20737290506568593
[I 2024-04-16 00:57:57,830] Trial 63 finished with value: 0.197669867988462 and parameters: {'l1_ratio': 0.1945656575078991}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388472982567977
Fold 2 IBS: 0.17141330593793633
Fold 3 IBS: 0.17212431084426733
Fold 4 IBS: 0.22826369538833488
Fold 5 IBS: 0.20560453413175
[I 2024-04-16 00:57:58,718] Trial 64 finished with value: 0.19825811522559364 and parameters: {'l1_ratio': 0.28374688065327447}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388598966905312
Fold 2 IBS: 0.17596995110179553
Fold 3 IBS: 0.17520759396951083
Fold 4 IBS: 0.21634345858993753
Fold 5 IBS: 0.20962985890182853
[I 2024-04-16 00:57:59,593] Trial 65 finished with value: 0.19820737044642509 and parameters: {'l1_ratio': 0.09167517340283993}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388493067029293
Fold 2 IBS: 0.17225512059055786
Fold 3 IBS: 0.1733450954169152
Fold 4 IBS: 0.2223643471278225
Fold 5 IBS: 0.20691698737617398
[I 2024-04-16 00:58:00,497] Trial 66 finished with value: 0.1977532962363525 and parameters: {'l1_ratio': 0.21312024901900456}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388445098055203
Fold 2 IBS: 0.1692805156259515
Fold 3 IBS: 0.16749617197895394
Fold 4 IBS: 0.23871213804386932
Fold 5 IBS: 0.20326687077362693
[I 2024-04-16 00:58:01,396] Trial 67 finished with value: 0.19852802948059076 and parameters: {'l1_ratio': 0.5239841372609237}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138852972403067
Fold 2 IBS: 0.17375190741185836
Fold 3 IBS: 0.17444757685723536
Fold 4 IBS: 0.21835179474711164
Fold 5 IBS: 0.20826019199536772
[I 2024-04-16 00:58:02,318] Trial 68 finished with value: 0.19773935365037595 and parameters: {'l1_ratio': 0.14635430056255044}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138850313791181
Fold 2 IBS: 0.1727056727224919
Fold 3 IBS: 0.1737712508703658
Fold 4 IBS: 0.2204957532126711
Fold 5 IBS: 0.20748646263959028
[I 2024-04-16 00:58:03,239] Trial 69 finished with value: 0.19766883416484743 and parameters: {'l1_ratio': 0.18942581039571943}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138847628405854
Fold 2 IBS: 0.17152135172431676
Fold 3 IBS: 0.1723822028015697
Fold 4 IBS: 0.22705912898020292
Fold 5 IBS: 0.2058223842069204
[I 2024-04-16 00:58:04,150] Trial 70 finished with value: 0.19813396611071904 and parameters: {'l1_ratio': 0.2691055201288479}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388501791707556
Fold 2 IBS: 0.17264343067097904
Fold 3 IBS: 0.17371427494731573
Fold 4 IBS: 0.22067232279623034
Fold 5 IBS: 0.2074208701103279
[I 2024-04-16 00:58:05,035] Trial 71 finished with value: 0.1976671832883857 and parameters: {'l1_ratio': 0.19228531195267054}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388488639334685
Fold 2 IBS: 0.17203826771117547
Fold 3 IBS: 0.17313850794341695
Fold 4 IBS: 0.2234230383523755
Fold 5 IBS: 0.2066405071525816
[I 2024-04-16 00:58:05,982] Trial 72 finished with value: 0.19782504151057928 and parameters: {'l1_ratio': 0.22550870825896724}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138846973505136
Fold 2 IBS: 0.17126044356410353
Fold 3 IBS: 0.171851027035062
Fold 4 IBS: 0.22942892815302873
Fold 5 IBS: 0.2053713778315497
[I 2024-04-16 00:58:06,908] Trial 73 finished with value: 0.1983592947868515 and parameters: {'l1_ratio': 0.29978298455457597}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388572492462138
Fold 2 IBS: 0.1751648909632716
Fold 3 IBS: 0.17499033681315385
Fold 4 IBS: 0.21717305054623015
Fold 5 IBS: 0.20914541849392748
[I 2024-04-16 00:58:07,819] Trial 74 finished with value: 0.19807188434824088 and parameters: {'l1_ratio': 0.1070100474924941}. Best is trial 61 with value: 0.19766531148426006.

Fold 1 IBS: 0.21388534161436484
Fold 2 IBS: 0.17389378880260667
Fold 3 IBS: 0.17452675718300817
Fold 4 IBS: 0.2180847924343947
Fold 5 IBS: 0.20837400636365672
[I 2024-04-16 00:58:08,834] Trial 75 finished with value: 0.19775293727960622 and parameters: {'l1_ratio': 0.1409912157240269}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388502813630633
Fold 2 IBS: 0.17269029176388578
Fold 3 IBS: 0.1737606037071706
Fold 4 IBS: 0.22053855478333909
Fold 5 IBS: 0.2074668384772341
[I 2024-04-16 00:58:09,802] Trial 76 finished with value: 0.19766826337358717 and parameters: {'l1_ratio': 0.1901068706694525}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388460331880524
Fold 2 IBS: 0.17079324824699885
Fold 3 IBS: 0.17059303317867783
Fold 4 IBS: 0.23318117427365354
Fold 5 IBS: 0.20478351532468056
[I 2024-04-16 00:58:10,884] Trial 77 finished with value: 0.19864711486856318 and parameters: {'l1_ratio': 0.3583730947174012}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21395276988370887
Fold 2 IBS: 0.22157268115817527
Fold 3 IBS: 0.2045052228072405
Fold 4 IBS: 0.22464497216331486
Fold 5 IBS: 0.21812911371050864
[I 2024-04-16 00:58:11,485] Trial 78 finished with value: 0.2165609519445896 and parameters: {'l1_ratio': 0.0008166682782179691}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388436374698486
Fold 2 IBS: 0.16877593587488174
Fold 3 IBS: 0.16573672815051343
Fold 4 IBS: 0.241152677474123
Fold 5 IBS: 0.20271888553018858
[I 2024-04-16 00:58:12,737] Trial 79 finished with value: 0.19845371815533833 and parameters: {'l1_ratio': 0.7120921418578845}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388485692157852
Fold 2 IBS: 0.17191247067560428
Fold 3 IBS: 0.17298038704900817
Fold 4 IBS: 0.22413530124999165
Fold 5 IBS: 0.20645098675686183
[I 2024-04-16 00:58:13,732] Trial 80 finished with value: 0.19787280053060888 and parameters: {'l1_ratio': 0.23458016436479462}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388503662276978
Fold 2 IBS: 0.17273226347804532
Fold 3 IBS: 0.17379152266670983
Fold 4 IBS: 0.2204185936919303
Fold 5 IBS: 0.20750932636872105
[I 2024-04-16 00:58:14,673] Trial 81 finished with value: 0.19766734856563523 and parameters: {'l1_ratio': 0.1883347283837923}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388530017388255
Fold 2 IBS: 0.17376143496826185
Fold 3 IBS: 0.17445259416529188
Fold 4 IBS: 0.21833025840890374
Fold 5 IBS: 0.20826789233943016
[I 2024-04-16 00:58:15,572] Trial 82 finished with value: 0.19773949601115404 and parameters: {'l1_ratio': 0.14598729530222154}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388635210918516
Fold 2 IBS: 0.17697986895811427
Fold 3 IBS: 0.17559611741298148
Fold 4 IBS: 0.21531689710740168
Fold 5 IBS: 0.21050521940189224
[I 2024-04-16 00:58:16,436] Trial 83 finished with value: 0.19845689099791497 and parameters: {'l1_ratio': 0.0765801014714239}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388507508700483
Fold 2 IBS: 0.17290625366611684
Fold 3 IBS: 0.1739163917566655
Fold 4 IBS: 0.21998169177133492
Fold 5 IBS: 0.2076511024875081
[I 2024-04-16 00:58:17,311] Trial 84 finished with value: 0.19766810295372603 and parameters: {'l1_ratio': 0.18069753554229123}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388480249289663
Fold 2 IBS: 0.17168342125546046
Fold 3 IBS: 0.17264540031100561
Fold 4 IBS: 0.2256739511770828
Fold 5 IBS: 0.20606631584246535
[I 2024-04-16 00:58:18,181] Trial 85 finished with value: 0.19799077821578218 and parameters: {'l1_ratio': 0.25339338049379806}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388492634851486
Fold 2 IBS: 0.17221641259389023
Fold 3 IBS: 0.17332947484968134
Fold 4 IBS: 0.2224603600788896
Fold 5 IBS: 0.2068923475515256
[I 2024-04-16 00:58:19,060] Trial 86 finished with value: 0.19775670428450032 and parameters: {'l1_ratio': 0.21426953148315483}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138850436126985
Fold 2 IBS: 0.17276411593161708
Fold 3 IBS: 0.1738154566349314
Fold 4 IBS: 0.22033002021582973
Fold 5 IBS: 0.2075396123800122
[I 2024-04-16 00:58:19,967] Trial 87 finished with value: 0.19766684975501775 and parameters: {'l1_ratio': 0.1868995542245189}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138851755227175
Fold 2 IBS: 0.17334721654909083
Fold 3 IBS: 0.174185070557874
Fold 4 IBS: 0.2190086940319283
Fold 5 IBS: 0.20801012185502532
[I 2024-04-16 00:58:21,011] Trial 88 finished with value: 0.19768725570332718 and parameters: {'l1_ratio': 0.16338026440504286}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138843438755076
Fold 2 IBS: 0.16891111418261343
Fold 3 IBS: 0.16532275173794986
Fold 4 IBS: 0.24144832404065664
Fold 5 IBS: 0.202857581112338
[I 2024-04-16 00:58:22,019] Trial 89 finished with value: 0.1984848229898131 and parameters: {'l1_ratio': 0.7754581028063904}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388910056182445
Fold 2 IBS: 0.1813936201172651
Fold 3 IBS: 0.1763361128449125
Fold 4 IBS: 0.20827998561824632
Fold 5 IBS: 0.2140643155845845
[I 2024-04-16 00:58:23,302] Trial 90 finished with value: 0.19879262694536656 and parameters: {'l1_ratio': 0.03360044866858938}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388508900205233
Fold 2 IBS: 0.1729608277765118
Fold 3 IBS: 0.17395675043376913
Fold 4 IBS: 0.21982225112324855
Fold 5 IBS: 0.2077108105575745
[I 2024-04-16 00:58:24,236] Trial 91 finished with value: 0.19766714577863126 and parameters: {'l1_ratio': 0.17808402798804523}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388558666605775
Fold 2 IBS: 0.17471206955964813
Fold 3 IBS: 0.1748591436646398
Fold 4 IBS: 0.21744221851542966
Fold 5 IBS: 0.20888311563338802
[I 2024-04-16 00:58:25,282] Trial 92 finished with value: 0.19795642680783268 and parameters: {'l1_ratio': 0.11721895227317079}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138847675445227
Fold 2 IBS: 0.17154256941845364
Fold 3 IBS: 0.1724158779687067
Fold 4 IBS: 0.22688984979927418
Fold 5 IBS: 0.2058517371320642
[I 2024-04-16 00:58:26,339] Trial 93 finished with value: 0.1981169603726043 and parameters: {'l1_ratio': 0.26714097357195976}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388504309953651
Fold 2 IBS: 0.17276029969954987
Fold 3 IBS: 0.17381371811711105
Fold 4 IBS: 0.22033602961198392
Fold 5 IBS: 0.20753748399003788
[I 2024-04-16 00:58:27,223] Trial 94 finished with value: 0.19766651490364387 and parameters: {'l1_ratio': 0.187004177428969}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138849017740432
Fold 2 IBS: 0.1721103413351115
Fold 3 IBS: 0.17321861513181044
Fold 4 IBS: 0.223033739482892
Fold 5 IBS: 0.20673801777739892
[I 2024-04-16 00:58:28,174] Trial 95 finished with value: 0.19779712310025124 and parameters: {'l1_ratio': 0.22104617307412408}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388540181941582
Fold 2 IBS: 0.17408629594116332
Fold 3 IBS: 0.17462303550224054
Fold 4 IBS: 0.21790357389398143
Fold 5 IBS: 0.2085134449970412
[I 2024-04-16 00:58:29,052] Trial 96 finished with value: 0.19780235043076846 and parameters: {'l1_ratio': 0.1343084889624756}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388524238975018
Fold 2 IBS: 0.1735826160436179
Fold 3 IBS: 0.17433925480774268
Fold 4 IBS: 0.21863737698570984
Fold 5 IBS: 0.20814792696723983
[I 2024-04-16 00:58:29,964] Trial 97 finished with value: 0.1977184834388121 and parameters: {'l1_ratio': 0.15356970071785223}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.2138859726910212
Fold 2 IBS: 0.1759193350834323
Fold 3 IBS: 0.1751850639590515
Fold 4 IBS: 0.21640501019354877
Fold 5 IBS: 0.20959721527988934
[I 2024-04-16 00:58:30,848] Trial 98 finished with value: 0.1981985194413886 and parameters: {'l1_ratio': 0.09252708360856582}. Best is trial 61 with value: 0.19766531148426006.
Fold 1 IBS: 0.21388468152212528
Fold 2 IBS: 0.17118941328523776
Fold 3 IBS: 0.1716836950204512
Fold 4 IBS: 0.23009392894954425
Fold 5 IBS: 0.20526591285143117
[I 2024-04-16 00:58:31,724] Trial 99 finished with value: 0.19842352632575794 and parameters: {'l1_ratio': 0.30827152392934354}. Best is trial 61 with value: 0.19766531148426006.


* Best trial for IBS:
 FrozenTrial(number=61, state=TrialState.COMPLETE, values=[0.19766531148426006], datetime_start=datetime.datetime(2024, 4, 16, 0, 57, 54, 891026), datetime_complete=datetime.datetime(2024, 4, 16, 0, 57, 55, 967242), params={'l1_ratio': 0.17870057023997313}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=61, value=None)


* Best Score for IBS:
 0.19766531148426006

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.696
train_ibs:  0.198

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.4108759560861602)

test_cindex : 0.597

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.17870057023997313)

test_ibs:  0.221

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:58:31,970] A new study created in memory with name: no-name-4db85697-b9eb-4fe7-9140-b03984097e85

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:58:51,734] Trial 0 finished with value: 0.7030408096722214 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 00:58:55,182] Trial 1 finished with value: 0.6866757853240973 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 00:58:57,818] Trial 2 finished with value: 0.6865628369372352 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:58:58,400] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:58:59,158] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:59:04,791] Trial 5 finished with value: 0.6875588573976407 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:59:25,645] Trial 6 finished with value: 0.7003915574155236 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:59:27,161] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-16 00:59:32,652] Trial 8 finished with value: 0.5220657276995305 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 00:59:36,845] Trial 9 finished with value: 0.6843546579233972 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:59:37,241] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:59:49,957] Trial 11 finished with value: 0.7129880534930061 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 11 with value: 0.7129880534930061.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 01:00:07,228] Trial 12 finished with value: 0.7136148495363072 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4617373338142137, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 12 with value: 0.7136148495363072.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 01:00:20,648] Trial 13 finished with value: 0.7038198416451461 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.430322282186733, 'max_features': None, 'min_weight_fraction_leaf': 0.1716937452680298, 'warm_start': False}. Best is trial 12 with value: 0.7136148495363072.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:00:23,292] Trial 14 finished with value: 0.7602465352824544 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.3957120070742282, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.089729602908424, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8526785714285714

Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:00:26,309] Trial 15 finished with value: 0.7343450964479536 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.25141113328809755, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08807762154599924, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:00:27,074] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.14975474925617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08683497083568477, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:00:30,532] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.2626050058723245, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09309567321799868, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:00:33,889] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.3309803154711108, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:00:36,680] Trial 19 finished with value: 0.7340057280550107 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.20097738776716928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004060792657387402, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:00:38,623] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 338, 'oob_score': True, 'max_samples': 0.35693963129044115, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2193383546745456, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:00:41,232] Trial 21 finished with value: 0.7779048552353404 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.21528073308536597, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003731938697099116, 'warm_start': True}. Best is trial 21 with value: 0.7779048552353404.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:00:44,210] Trial 22 finished with value: 0.752249027173715 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.21351240485158024, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05645873540440379, 'warm_start': True}. Best is trial 21 with value: 0.7779048552353404.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:00:46,536] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.10559201477694438, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0543102792101534, 'warm_start': True}. Best is trial 21 with value: 0.7779048552353404.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 01:00:50,880] Trial 24 finished with value: 0.8128881217878812 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.5202247887132748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055102552661176425, 'warm_start': True}. Best is trial 24 with value: 0.8128881217878812.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:00:54,272] Trial 25 finished with value: 0.8467871740018396 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.5294667085607988, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0009549918209556772, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:00:58,490] Trial 26 finished with value: 0.8357998254083719 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030815899349523192, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 01:01:01,976] Trial 27 finished with value: 0.8154314118311712 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.5366581083873809, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04171876755905933, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:01:03,121] Trial 28 finished with value: 0.7398099516796621 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.5323444883008067, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12312681780325545, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:01:05,048] Trial 29 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.7488754310335448, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4166359773604548, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:01:08,170] Trial 30 finished with value: 0.7457160010311196 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.6638952960819583, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.21039766295115211, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:01:12,261] Trial 31 finished with value: 0.8228219119541365 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 447, 'oob_score': True, 'max_samples': 0.5119028984984925, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04799860054302019, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:01:15,881] Trial 32 finished with value: 0.8283539838162529 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.5077512231481354, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03147207521246989, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 01:01:19,254] Trial 33 finished with value: 0.8478361859257715 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.8584661298748817, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0013006402560399475, 'warm_start': True}. Best is trial 33 with value: 0.8478361859257715.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:01:24,571] Trial 34 finished with value: 0.8422439465988829 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.8051060893851159, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0025452104786982815, 'warm_start': True}. Best is trial 33 with value: 0.8478361859257715.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:01:27,809] Trial 35 finished with value: 0.8479190359671964 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.851099838620899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0006376549948954823, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:01:29,821] Trial 36 finished with value: 0.8357733598958312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.8488502380681998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:01:31,538] Trial 37 finished with value: 0.7493589594949148 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.838509019374533, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11746503943647707, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:01:33,870] Trial 38 finished with value: 0.8269487899780733 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.983590036262626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0747020966452816, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 01:01:36,783] Trial 39 finished with value: 0.8488165780826342 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 366, 'oob_score': False, 'max_samples': 0.8540574611869531, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.003840718247711571, 'warm_start': True}. Best is trial 39 with value: 0.8488165780826342.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:01:37,737] Trial 40 finished with value: 0.7838958563538545 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 255, 'oob_score': False, 'max_samples': 0.6968308474648358, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1433423288180575, 'warm_start': True}. Best is trial 39 with value: 0.8488165780826342.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:01:40,329] Trial 41 finished with value: 0.8339513578572 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.8146887408542629, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00030843677515235353, 'warm_start': True}. Best is trial 39 with value: 0.8488165780826342.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 01:01:43,608] Trial 42 finished with value: 0.8527456969756898 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.8942734851141386, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019055206736150496, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:01:45,542] Trial 43 finished with value: 0.8329513212195849 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.8879208843012818, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024852775173615727, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 01:01:50,620] Trial 44 finished with value: 0.8284000938095459 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.971999569566476, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0698334924574171, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9578059071729957
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 01:01:55,569] Trial 45 finished with value: 0.8518750701142708 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9104218782867626, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024937549243351627, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 01:02:02,670] Trial 46 finished with value: 0.6796157756689281 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1067722201468298, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:02:04,750] Trial 47 finished with value: 0.832163823891929 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.7669727046770091, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03264002904034867, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 01:02:13,604] Trial 48 finished with value: 0.6819362044806578 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.8722529283282636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06413914181540917, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:02:14,639] Trial 49 finished with value: 0.7669851463413936 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.9459839136267338, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27564743124552793, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 01:02:16,899] Trial 50 finished with value: 0.8514951495112056 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.917967126420836, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02319686989352488, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 01:02:19,205] Trial 51 finished with value: 0.8489438569070961 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9289683360127683, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023119305249152552, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:02:21,463] Trial 52 finished with value: 0.8368758936093602 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.9275960987240828, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027445561377387837, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:02:23,828] Trial 53 finished with value: 0.8341782684645521 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.9963955115386218, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07497043940676032, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:02:25,851] Trial 54 finished with value: 0.8398435330387523 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.7837298182053988, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02193560985062079, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 01:02:27,822] Trial 55 finished with value: 0.8219440143194507 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.9517190573290379, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10034820978930141, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:02:31,520] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.7182532763821678, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4854877691508544, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:02:32,680] Trial 57 finished with value: 0.7672408301883777 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.9040778587892617, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03837565066969165, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:02:34,901] Trial 58 finished with value: 0.7948120286056691 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.8249820267316494, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01929205978496117, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 01:02:46,781] Trial 59 finished with value: 0.8255623295039989 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.8851281818695599, 'max_features': None, 'min_weight_fraction_leaf': 0.13481929816020052, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:02:50,525] Trial 60 finished with value: 0.6647990426822765 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.5822185880662518, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08420948524085664, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:02:54,317] Trial 61 finished with value: 0.8506580861327173 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.8606110350218901, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015110313973031744, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 01:02:57,302] Trial 62 finished with value: 0.8300902705204353 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 333, 'oob_score': False, 'max_samples': 0.9591404172905456, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052973041467924364, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9578059071729957
Fold 5 C-index: 0.9530516431924883
[I 2024-04-16 01:03:00,598] Trial 63 finished with value: 0.8610676139692007 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.9230175999956005, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.042893630067511276, 'warm_start': True}. Best is trial 63 with value: 0.8610676139692007.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:03:03,667] Trial 64 finished with value: 0.8375002766548523 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.9053029008061164, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0456198017341522, 'warm_start': True}. Best is trial 63 with value: 0.8610676139692007.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.9411764705882353
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:03:04,475] Trial 65 finished with value: 0.862830086693586 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 21, 'oob_score': False, 'max_samples': 0.9333236086463597, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02092334357643291, 'warm_start': True}. Best is trial 65 with value: 0.862830086693586.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:03:08,301] Trial 66 finished with value: 0.8385902613042819 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.9302682395779636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06527850624266292, 'warm_start': True}. Best is trial 65 with value: 0.862830086693586.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.9509803921568627
Fold 4 C-index: 0.9704641350210971
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 01:03:09,315] Trial 67 finished with value: 0.8657942252331653 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.9913887161519704, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018844036271850925, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5064935064935064
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:03:09,799] Trial 68 finished with value: 0.8174509885641156 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 8, 'oob_score': False, 'max_samples': 0.9989888731321823, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017648709064596993, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 01:03:10,674] Trial 69 finished with value: 0.8423287573429021 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 65, 'oob_score': False, 'max_samples': 0.887987247235582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04202274734020557, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8427230046948356
[I 2024-04-16 01:03:11,224] Trial 70 finished with value: 0.7782611486627746 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 3, 'oob_score': False, 'max_samples': 0.9627766912202452, 'max_features': None, 'min_weight_fraction_leaf': 0.1928493145321546, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 01:03:11,997] Trial 71 finished with value: 0.8611111724953842 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.9346836401527917, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01764397901477166, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9241071428571429
Fold 3 C-index: 0.9411764705882353
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 01:03:12,819] Trial 72 finished with value: 0.8673945949552773 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.978021668649595, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017507956127588386, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:03:13,705] Trial 73 finished with value: 0.8423948256428619 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 53, 'oob_score': False, 'max_samples': 0.9500892988572575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057332316418011384, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:03:14,896] Trial 74 finished with value: 0.8269197321386292 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9756907704831479, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08223919145457521, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.577922077922078
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:03:15,378] Trial 75 finished with value: 0.7295696268020816 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.919061026360145, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35481417747069804, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 01:03:17,112] Trial 76 finished with value: 0.8656574036606651 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 92, 'oob_score': False, 'max_samples': 0.9821338123357319, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0386998813751704, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 01:03:18,806] Trial 77 finished with value: 0.8575007319010522 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9820410736083862, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04031426725454558, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9483568075117371
[I 2024-04-16 01:03:20,676] Trial 78 finished with value: 0.8613008907593895 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 99, 'oob_score': False, 'max_samples': 0.9870196811414806, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04316121707142663, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 01:03:22,413] Trial 79 finished with value: 0.8581373501847294 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.982100579279894, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03947436058443923, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:03:43,111] Trial 80 finished with value: 0.6882224644262152 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.996557008225936, 'max_features': None, 'min_weight_fraction_leaf': 0.09397968262050733, 'warm_start': False}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 01:03:44,219] Trial 81 finished with value: 0.8491747206994761 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 78, 'oob_score': False, 'max_samples': 0.9688899122872592, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.045053504997941765, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:03:45,473] Trial 82 finished with value: 0.833424193596789 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.9839430534728586, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06330005525600567, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 01:03:46,234] Trial 83 finished with value: 0.8519766625997554 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.9425371719661932, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03632534485337897, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:03:47,358] Trial 84 finished with value: 0.8342928597556141 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 87, 'oob_score': False, 'max_samples': 0.9707179242624712, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07502533547645525, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 01:03:49,601] Trial 85 finished with value: 0.843360078962459 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 98, 'oob_score': False, 'max_samples': 0.9999603856937841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04591706500803319, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9436619718309859
[I 2024-04-16 01:03:52,837] Trial 86 finished with value: 0.8504787873998202 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.9508012356542417, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01106819826749143, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:03:53,886] Trial 87 finished with value: 0.8033762770898729 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 56, 'oob_score': False, 'max_samples': 0.9393248272694704, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0585651420807417, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:03:54,615] Trial 88 finished with value: 0.8083928266115115 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.8788991859381762, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10989569253629844, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:03:55,188] Trial 89 finished with value: 0.8710610216955061 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.9776940371468902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03508377856391107, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:03:55,990] Trial 90 finished with value: 0.8578165857665454 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.9637994442455189, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011418176135514232, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.

Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:03:56,623] Trial 91 finished with value: 0.8434168286757482 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.9684043724798074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03304632175550328, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:03:57,612] Trial 92 finished with value: 0.8439347614602981 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.9379025342651837, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0080128467059435, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 01:03:58,363] Trial 93 finished with value: 0.7775838399834235 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.921219997977047, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23116679435682758, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:03:59,256] Trial 94 finished with value: 0.8416362068255558 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.9808103888471272, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01357145766778422, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:03:59,978] Trial 95 finished with value: 0.8567356149578261 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 23, 'oob_score': False, 'max_samples': 0.9008882936748592, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050931523296795955, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:04:00,959] Trial 96 finished with value: 0.8123444935843995 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.9567182017832458, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032219267251555404, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:04:01,686] Trial 97 finished with value: 0.8206951097591665 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 12, 'oob_score': False, 'max_samples': 0.8306888663828067, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07102483582015064, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9662447257383966
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:04:02,602] Trial 98 finished with value: 0.858633677785933 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 44, 'oob_score': False, 'max_samples': 0.8752095179234526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015337889322115085, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7468354430379747

[I 2024-04-16 01:06:15,551] A new study created in memory with name: no-name-2f811965-4125-4efa-93b7-113bd4079399

Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:06:15,489] Trial 99 finished with value: 0.6714410654454491 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 135, 'oob_score': False, 'max_samples': 0.8773141075149282, 'max_features': None, 'min_weight_fraction_leaf': 0.031973101293928885, 'warm_start': False}. Best is trial 89 with value: 0.8710610216955061.


* Best trial for C-index:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.8710610216955061], datetime_start=datetime.datetime(2024, 4, 16, 1, 3, 54, 635515), datetime_complete=datetime.datetime(2024, 4, 16, 1, 3, 55, 187510), params={'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.9776940371468902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03508377856391107, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=89, value=None)


* Best Score for C-index:
 0.8710610216955061

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1909314497468114
Fold 2 IBS: 0.1838756947663154
Fold 3 IBS: 0.1815068818887493
Fold 4 IBS: 0.19707523042251168
Fold 5 IBS: 0.1912952641441048
[I 2024-04-16 01:07:47,520] Trial 0 finished with value: 0.18893690419369852 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20853319279195734
Fold 2 IBS: 0.18485634190294598
Fold 3 IBS: 0.18461398747386223
Fold 4 IBS: 0.1877281956699156
Fold 5 IBS: 0.21188684258082258
[I 2024-04-16 01:07:52,320] Trial 1 finished with value: 0.19552371208390076 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-16 01:07:54,437] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-16 01:08:05,198] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-16 01:08:11,458] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21548891686111923
Fold 2 IBS: 0.18020165037882038
Fold 3 IBS: 0.18803723401151992
Fold 4 IBS: 0.16918458189908994
Fold 5 IBS: 0.21190068797606287
[I 2024-04-16 01:08:28,413] Trial 5 finished with value: 0.19296261422532246 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.19294818685700066
Fold 2 IBS: 0.18635164797102344
Fold 3 IBS: 0.18167455180137812
Fold 4 IBS: 0.20513583275335814
Fold 5 IBS: 0.2066717152663197
[I 2024-04-16 01:09:15,393] Trial 6 finished with value: 0.194556386929816 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21224269880602273
Fold 2 IBS: 0.2141019684670013
Fold 3 IBS: 0.20009412298826473
Fold 4 IBS: 0.21863959904131022
Fold 5 IBS: 0.21558345426998946
[I 2024-04-16 01:09:30,237] Trial 7 finished with value: 0.21213236871451766 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-16 01:09:46,258] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20967175046992442
Fold 2 IBS: 0.18823479945265645
Fold 3 IBS: 0.18938652891539456
Fold 4 IBS: 0.19233411841816767
Fold 5 IBS: 0.2128466160365194
[I 2024-04-16 01:09:51,607] Trial 9 finished with value: 0.1984947626585325 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-16 01:10:11,648] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20619739601295609
Fold 2 IBS: 0.20334035647220894
Fold 3 IBS: 0.1911208062859065
Fold 4 IBS: 0.20396163181367089
Fold 5 IBS: 0.2115767925024512
[I 2024-04-16 01:10:24,059] Trial 11 finished with value: 0.20323939661743876 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2129281659837464
Fold 2 IBS: 0.18052307192750347
Fold 3 IBS: 0.19384199684749281
Fold 4 IBS: 0.16605951351765671
Fold 5 IBS: 0.20750897373210847
[I 2024-04-16 01:10:46,822] Trial 12 finished with value: 0.19217234440170156 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9944667777599061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10294337889507951}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.22525022980227782
Fold 2 IBS: 0.17353533245380492
Fold 3 IBS: 0.2186524977667984
Fold 4 IBS: 0.16891548073075577
Fold 5 IBS: 0.195621507153405
[I 2024-04-16 01:13:34,069] Trial 13 finished with value: 0.19639500958140838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.9694270540157217, 'max_features': None, 'min_weight_fraction_leaf': 0.1530029930440125}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20207016804160097
Fold 2 IBS: 0.18676975489553133
Fold 3 IBS: 0.1859149971296697
Fold 4 IBS: 0.18527924758332295
Fold 5 IBS: 0.2121788775815752
[I 2024-04-16 01:13:55,885] Trial 14 finished with value: 0.19444260904634003 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.7631177214580046, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21229864789095249}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.23195220862648563
Fold 2 IBS: 0.17801482955351014
Fold 3 IBS: 0.2238672203869343
Fold 4 IBS: 0.17050279887387504
Fold 5 IBS: 0.19954112067881152
[I 2024-04-16 01:15:53,171] Trial 15 finished with value: 0.20077563562392334 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.9970673523205843, 'max_features': None, 'min_weight_fraction_leaf': 0.09604984749674861}. Best is trial 0 with value: 0.18893690419369852.

Fold 1 IBS: 0.20734234035106477
Fold 2 IBS: 0.19501278136445316
Fold 3 IBS: 0.19189186563894495
Fold 4 IBS: 0.20108964805923063
Fold 5 IBS: 0.21696638887997266
[I 2024-04-16 01:16:17,748] Trial 16 finished with value: 0.20246060485873324 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8184724465806228, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31376919111755797}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2044812145296246
Fold 2 IBS: 0.1892546993686875
Fold 3 IBS: 0.1828749961924705
Fold 4 IBS: 0.18912670463318382
Fold 5 IBS: 0.2139231124295064
[I 2024-04-16 01:16:35,774] Trial 17 finished with value: 0.19593214543069454 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.3060837787360696, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005619770510688432}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20139160726914623
Fold 2 IBS: 0.18585932800995397
Fold 3 IBS: 0.1861218453981356
Fold 4 IBS: 0.17860006262773243
Fold 5 IBS: 0.21242561284402064
[I 2024-04-16 01:17:09,120] Trial 18 finished with value: 0.19287969122979776 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.680642613858846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12812974712655775}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.19475177999010934
Fold 2 IBS: 0.1806621111583486
Fold 3 IBS: 0.20798143410401362
Fold 4 IBS: 0.18842371294257598
Fold 5 IBS: 0.193632305175787
[I 2024-04-16 01:18:27,792] Trial 19 finished with value: 0.1930902686741669 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.8923233540949727, 'max_features': None, 'min_weight_fraction_leaf': 0.22336599579981053}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20817199028963768
Fold 2 IBS: 0.1944729659806337
Fold 3 IBS: 0.19194057745960344
Fold 4 IBS: 0.19612566987348856
Fold 5 IBS: 0.21820445689560775
[I 2024-04-16 01:18:45,496] Trial 20 finished with value: 0.2017831320997942 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.7871968885021372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34030385853489}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20308184281641078
Fold 2 IBS: 0.18787487745449374
Fold 3 IBS: 0.18644008925665942
Fold 4 IBS: 0.17992150803863177
Fold 5 IBS: 0.21291813326735048
[I 2024-04-16 01:19:20,763] Trial 21 finished with value: 0.19404729016670924 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.6572584969235378, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14838827402273672}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20654820321735085
Fold 2 IBS: 0.18962828737601528
Fold 3 IBS: 0.185529015857085
Fold 4 IBS: 0.1883836481555542
Fold 5 IBS: 0.2126687891109743
[I 2024-04-16 01:19:51,553] Trial 22 finished with value: 0.19655158874339593 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.46195099482658086, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10498907050446149}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20481511212109618
Fold 2 IBS: 0.1844344269805195
Fold 3 IBS: 0.19010112321844747
Fold 4 IBS: 0.1869176995788077
Fold 5 IBS: 0.2115140936991531
[I 2024-04-16 01:20:34,648] Trial 23 finished with value: 0.19555649111960477 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.6264034454811965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1320111380928695}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2092170982707326
Fold 2 IBS: 0.18289973319337763
Fold 3 IBS: 0.1919325961094944
Fold 4 IBS: 0.16823270962284748
Fold 5 IBS: 0.21044728631185722
[I 2024-04-16 01:21:14,586] Trial 24 finished with value: 0.19254588470166184 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.719949031993126, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.047830597712283124}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2290576901691574
Fold 2 IBS: 0.17488066885927944
Fold 3 IBS: 0.21244798204721357
Fold 4 IBS: 0.1603090486630914
Fold 5 IBS: 0.1970567986118096
[I 2024-04-16 01:25:27,280] Trial 25 finished with value: 0.19475043767011027 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.7351782445421919, 'max_features': None, 'min_weight_fraction_leaf': 0.04415795390433877}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2121221369156162
Fold 2 IBS: 0.17877099581032507
Fold 3 IBS: 0.18754679403766977
Fold 4 IBS: 0.16742425771531183
Fold 5 IBS: 0.20985771345552479
[I 2024-04-16 01:25:41,060] Trial 26 finished with value: 0.19114437958688954 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.8988182112124266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042097403512899145}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20686889245887538
Fold 2 IBS: 0.1884083338020966
Fold 3 IBS: 0.18876792339211537
Fold 4 IBS: 0.18514060806030716
Fold 5 IBS: 0.21563289269901484
[I 2024-04-16 01:25:51,349] Trial 27 finished with value: 0.19696373008248186 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.9352174038267842, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1848211474281298}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2102390531465248
Fold 2 IBS: 0.19154600711242953
Fold 3 IBS: 0.1897192957913833
Fold 4 IBS: 0.19302593080209796
Fold 5 IBS: 0.2126485490317729
[I 2024-04-16 01:26:03,135] Trial 28 finished with value: 0.1994357671768417 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.835160294304069, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24988045818731303}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2076850643866418
Fold 2 IBS: 0.19039634048388074
Fold 3 IBS: 0.18805324142901297
Fold 4 IBS: 0.18708234280984531
Fold 5 IBS: 0.20808498184621124
[I 2024-04-16 01:26:08,911] Trial 29 finished with value: 0.19626039419111846 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.899280299131193, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03665012005683188}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20493578440458557
Fold 2 IBS: 0.18241197625185288
Fold 3 IBS: 0.19204977253497849
Fold 4 IBS: 0.18098544383534507
Fold 5 IBS: 0.21220160549991307
[I 2024-04-16 01:26:13,714] Trial 30 finished with value: 0.19451691650533504 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 98, 'oob_score': False, 'max_samples': 0.9941488361918993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16827524032488794}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21287229922024917
Fold 2 IBS: 0.18118028230968794
Fold 3 IBS: 0.19442622412409546
Fold 4 IBS: 0.16510921719597976
Fold 5 IBS: 0.21193514194112287
[I 2024-04-16 01:26:38,157] Trial 31 finished with value: 0.19310463295822702 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.8464896605652109, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057598037551301065}. Best is trial 0 with value: 0.18893690419369852.

Fold 1 IBS: 0.20878411136352604
Fold 2 IBS: 0.18596824822942906
Fold 3 IBS: 0.19066800479976556
Fold 4 IBS: 0.17194213397317673
Fold 5 IBS: 0.20965199730588724
[I 2024-04-16 01:26:56,148] Trial 32 finished with value: 0.1934028991343569 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.7212112540749575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10884764482583958}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.26672933578367825
Fold 2 IBS: 0.17260981802328967
Fold 3 IBS: 0.218462235370602
Fold 4 IBS: 0.17492701943122574
Fold 5 IBS: 0.1712325610179695
[I 2024-04-16 01:27:08,654] Trial 33 finished with value: 0.20079219392535302 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 19, 'oob_score': True, 'max_samples': 0.6049706297065969, 'max_features': None, 'min_weight_fraction_leaf': 0.01786422641292886}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2169857185382466
Fold 2 IBS: 0.17663452883651862
Fold 3 IBS: 0.19651528599307333
Fold 4 IBS: 0.1636190754494162
Fold 5 IBS: 0.21255587036122034
[I 2024-04-16 01:27:28,293] Trial 34 finished with value: 0.19326209583569504 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.9447229736600063, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0757592075819458}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21316734022588915
Fold 2 IBS: 0.18026213073590652
Fold 3 IBS: 0.19473913010599572
Fold 4 IBS: 0.16964617097320425
Fold 5 IBS: 0.2099274130167616
[I 2024-04-16 01:27:45,945] Trial 35 finished with value: 0.19354843701155144 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.8021292339953092, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04491877876683002}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21398404476907304
Fold 2 IBS: 0.2213161761944828
Fold 3 IBS: 0.20488054697385918
Fold 4 IBS: 0.2246644996137753
Fold 5 IBS: 0.21853149612739048
[I 2024-04-16 01:28:01,274] Trial 36 finished with value: 0.21667535273571614 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 374, 'oob_score': True, 'max_samples': 0.5753896028655068, 'max_features': None, 'min_weight_fraction_leaf': 0.40732906376297884}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20659830129520304
Fold 2 IBS: 0.18385914614148338
Fold 3 IBS: 0.19016216373439407
Fold 4 IBS: 0.17123880715306228
Fold 5 IBS: 0.21120851794107792
[I 2024-04-16 01:28:18,234] Trial 37 finished with value: 0.19261338725304414 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.6964969230154789, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08458648773948732}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21136283326206354
Fold 2 IBS: 0.18356207109099051
Fold 3 IBS: 0.18380554812391878
Fold 4 IBS: 0.17036515364813978
Fold 5 IBS: 0.2102540447203662
[I 2024-04-16 01:28:29,330] Trial 38 finished with value: 0.19186993016909576 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.4953139253289448, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03213232318563604}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.19530028285277534
Fold 2 IBS: 0.18103597363741977
Fold 3 IBS: 0.19055271974611424
Fold 4 IBS: 0.17599814929084945
Fold 5 IBS: 0.19710966192966495
[I 2024-04-16 01:29:06,866] Trial 39 finished with value: 0.18799935749136473 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 190, 'oob_score': False, 'max_samples': 0.5208817292734901, 'max_features': None, 'min_weight_fraction_leaf': 0.12110152747008576}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2139862133124592
Fold 2 IBS: 0.2215286962880667
Fold 3 IBS: 0.2048896857470274
Fold 4 IBS: 0.22483605023926195
Fold 5 IBS: 0.21848105410604549
[I 2024-04-16 01:29:13,762] Trial 40 finished with value: 0.21674433993857217 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.44676149019096106, 'max_features': None, 'min_weight_fraction_leaf': 0.23842072140001497}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2009860240135767
Fold 2 IBS: 0.18034071969915927
Fold 3 IBS: 0.19435159603275015
Fold 4 IBS: 0.1739979095620913
Fold 5 IBS: 0.19815837872213873
[I 2024-04-16 01:30:05,461] Trial 41 finished with value: 0.1895669256059432 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.5061856948956256, 'max_features': None, 'min_weight_fraction_leaf': 0.11169740239883391}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.228097670669022
Fold 2 IBS: 0.1749977426980276
Fold 3 IBS: 0.1954046550227859
Fold 4 IBS: 0.1627916445243243
Fold 5 IBS: 0.19529585517632986
[I 2024-04-16 01:31:24,455] Trial 42 finished with value: 0.19131751361809793 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5079379573053203, 'max_features': None, 'min_weight_fraction_leaf': 0.026318069624792054}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.21400582170048152
Fold 2 IBS: 0.2212482026565116
Fold 3 IBS: 0.205116493458099
Fold 4 IBS: 0.2247062721100724
Fold 5 IBS: 0.21830660590584794
[I 2024-04-16 01:31:30,925] Trial 43 finished with value: 0.21667667916620248 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.37770293147318823, 'max_features': None, 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19583153004447376
Fold 2 IBS: 0.17911352312673134
Fold 3 IBS: 0.1940263304775934
Fold 4 IBS: 0.1786128101414542
Fold 5 IBS: 0.19758751595069282
[I 2024-04-16 01:32:17,967] Trial 44 finished with value: 0.1890343419481891 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 137, 'oob_score': False, 'max_samples': 0.5215068036754404, 'max_features': None, 'min_weight_fraction_leaf': 0.12548156505108574}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20016280258876293
Fold 2 IBS: 0.18106442587863425
Fold 3 IBS: 0.1817907647526564
Fold 4 IBS: 0.1985749666148987
Fold 5 IBS: 0.20971747943219898
[I 2024-04-16 01:32:38,408] Trial 45 finished with value: 0.19426208785343027 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 122, 'oob_score': False, 'max_samples': 0.3837754218314978, 'max_features': None, 'min_weight_fraction_leaf': 0.17659447211135293}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19608238087631935
Fold 2 IBS: 0.17861720429508926
Fold 3 IBS: 0.19796756489608158
Fold 4 IBS: 0.18158631252973012
Fold 5 IBS: 0.19724266192510972
[I 2024-04-16 01:33:24,480] Trial 46 finished with value: 0.19029922490446602 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.5602811177430677, 'max_features': None, 'min_weight_fraction_leaf': 0.12838422086973741}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19729763464906347
Fold 2 IBS: 0.16564154574645254
Fold 3 IBS: 0.19496992988930276
Fold 4 IBS: 0.188463746593695
Fold 5 IBS: 0.19590518681404473
[I 2024-04-16 01:33:39,355] Trial 47 finished with value: 0.1884556087385117 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.549833569332551, 'max_features': None, 'min_weight_fraction_leaf': 0.12900539608380052}. Best is trial 39 with value: 0.18799935749136473.

Fold 1 IBS: 0.2015902982015954
Fold 2 IBS: 0.1857104387603733
Fold 3 IBS: 0.1790267886123672
Fold 4 IBS: 0.19557127495348786
Fold 5 IBS: 0.20398058535823538
[I 2024-04-16 01:33:48,929] Trial 48 finished with value: 0.19317587717721182 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.5260405815006272, 'max_features': None, 'min_weight_fraction_leaf': 0.21390971396804748}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2145391454105467
Fold 2 IBS: 0.22377474389972024
Fold 3 IBS: 0.20445767011409766
Fold 4 IBS: 0.22686036777266955
Fold 5 IBS: 0.2243610480605514
[I 2024-04-16 01:33:50,747] Trial 49 finished with value: 0.21879859505151708 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.26830717105159463, 'max_features': None, 'min_weight_fraction_leaf': 0.14767412671365485}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20005417967793443
Fold 2 IBS: 0.18085907927728326
Fold 3 IBS: 0.18581136458405717
Fold 4 IBS: 0.19912498551548968
Fold 5 IBS: 0.2109545583240917
[I 2024-04-16 01:34:04,431] Trial 50 finished with value: 0.19536083347577127 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.5952614036305829, 'max_features': None, 'min_weight_fraction_leaf': 0.2798858457285205}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20076463657446927
Fold 2 IBS: 0.17713877093292119
Fold 3 IBS: 0.19996192389062428
Fold 4 IBS: 0.18121132742738624
Fold 5 IBS: 0.19572402265390276
[I 2024-04-16 01:34:49,388] Trial 51 finished with value: 0.19096013629586076 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.5577690942008394, 'max_features': None, 'min_weight_fraction_leaf': 0.12192044372727744}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1965900685059138
Fold 2 IBS: 0.18294591457379972
Fold 3 IBS: 0.1839564616023395
Fold 4 IBS: 0.19468395450865694
Fold 5 IBS: 0.20915752471790008
[I 2024-04-16 01:35:01,032] Trial 52 finished with value: 0.193466784781722 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.47223606642136245, 'max_features': None, 'min_weight_fraction_leaf': 0.19930586110679174}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19053943720172403
Fold 2 IBS: 0.18766910427757014
Fold 3 IBS: 0.1781113837658672
Fold 4 IBS: 0.1885299079588205
Fold 5 IBS: 0.20605183718762635
[I 2024-04-16 01:35:37,249] Trial 53 finished with value: 0.19018033407832163 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 170, 'oob_score': False, 'max_samples': 0.4126678500571366, 'max_features': None, 'min_weight_fraction_leaf': 0.12643674241667632}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20601886283438436
Fold 2 IBS: 0.1817223144274711
Fold 3 IBS: 0.18985236916813075
Fold 4 IBS: 0.17101045403398027
Fold 5 IBS: 0.20269562569299265
[I 2024-04-16 01:36:37,363] Trial 54 finished with value: 0.19025992523139182 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.4257775164744506, 'max_features': None, 'min_weight_fraction_leaf': 0.08411093295534}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19459726930679694
Fold 2 IBS: 0.18297242221796922
Fold 3 IBS: 0.1965180423739642
Fold 4 IBS: 0.17875447156988206
Fold 5 IBS: 0.19484700232226768
[I 2024-04-16 01:37:41,296] Trial 55 finished with value: 0.18953784155817602 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.6395078607296397, 'max_features': None, 'min_weight_fraction_leaf': 0.15889763539063495}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1882079873320902
Fold 2 IBS: 0.17893510442701313
Fold 3 IBS: 0.18768488465792385
Fold 4 IBS: 0.19786494939978266
Fold 5 IBS: 0.19517745378652535
[I 2024-04-16 01:38:04,703] Trial 56 finished with value: 0.18957407592066705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.6383861034558203, 'max_features': None, 'min_weight_fraction_leaf': 0.19322310512139276}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19299807491899834
Fold 2 IBS: 0.18365494631669205
Fold 3 IBS: 0.1877472060862737
Fold 4 IBS: 0.18335325539123815
Fold 5 IBS: 0.19776713087091158
[I 2024-04-16 01:38:56,564] Trial 57 finished with value: 0.18910412271682278 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.6100018518887674, 'max_features': None, 'min_weight_fraction_leaf': 0.15840214758179427}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20739704645746
Fold 2 IBS: 0.18780635854882632
Fold 3 IBS: 0.18701677075522546
Fold 4 IBS: 0.1836166948150953
Fold 5 IBS: 0.21415553404975177
[I 2024-04-16 01:39:11,559] Trial 58 finished with value: 0.19599848092527175 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.6639277088940287, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15215857760776447}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19040076453809218
Fold 2 IBS: 0.18363877768088577
Fold 3 IBS: 0.18685481091428083
Fold 4 IBS: 0.18608582839272733
Fold 5 IBS: 0.19596627174135858
[I 2024-04-16 01:40:02,883] Trial 59 finished with value: 0.18858929065346894 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.6141962522920374, 'max_features': None, 'min_weight_fraction_leaf': 0.16569628029180983}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19728417814617552
Fold 2 IBS: 0.1848259343000363
Fold 3 IBS: 0.18020836278748756
Fold 4 IBS: 0.19937482047392596
Fold 5 IBS: 0.2020282375792895
[I 2024-04-16 01:40:22,914] Trial 60 finished with value: 0.19274430665738299 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.5963407401950178, 'max_features': None, 'min_weight_fraction_leaf': 0.2259745892736023}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19057325218977889
Fold 2 IBS: 0.18756815083836095
Fold 3 IBS: 0.1764902290639015
Fold 4 IBS: 0.19414138806493458
Fold 5 IBS: 0.19954577838438423
[I 2024-04-16 01:41:12,057] Trial 61 finished with value: 0.189663759708272 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.5322501774355544, 'max_features': None, 'min_weight_fraction_leaf': 0.16473932045402911}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2018497163128481
Fold 2 IBS: 0.1772483574047875
Fold 3 IBS: 0.20635720214178183
Fold 4 IBS: 0.17564544580494643
Fold 5 IBS: 0.19458335182903166
[I 2024-04-16 01:43:05,951] Trial 62 finished with value: 0.1911368146986791 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.690008488050583, 'max_features': None, 'min_weight_fraction_leaf': 0.1470861922108762}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19064418333065583
Fold 2 IBS: 0.18865306264594373
Fold 3 IBS: 0.18796770034223975
Fold 4 IBS: 0.19052254543799213
Fold 5 IBS: 0.19585413668160062
[I 2024-04-16 01:43:54,863] Trial 63 finished with value: 0.19072832568768644 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.6215475330033557, 'max_features': None, 'min_weight_fraction_leaf': 0.17501707768999425}. Best is trial 39 with value: 0.18799935749136473.

Fold 1 IBS: 0.1928095274883131
Fold 2 IBS: 0.1829210242425621
Fold 3 IBS: 0.19880360343847653
Fold 4 IBS: 0.1863866229226835
Fold 5 IBS: 0.1951582078859148
[I 2024-04-16 01:45:26,208] Trial 64 finished with value: 0.19121579719558998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 188, 'oob_score': False, 'max_samples': 0.775924036717329, 'max_features': None, 'min_weight_fraction_leaf': 0.20625622507811242}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19101081770652317
Fold 2 IBS: 0.18371867374090417
Fold 3 IBS: 0.1824200640830827
Fold 4 IBS: 0.19925148398280748
Fold 5 IBS: 0.19796558416349588
[I 2024-04-16 01:46:11,119] Trial 65 finished with value: 0.19087332473536267 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.6380685376962676, 'max_features': None, 'min_weight_fraction_leaf': 0.1379890948874851}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1961693420915139
Fold 2 IBS: 0.18615725230494348
Fold 3 IBS: 0.1819983398530402
Fold 4 IBS: 0.19777910918822209
Fold 5 IBS: 0.20858166806712258
[I 2024-04-16 01:46:41,698] Trial 66 finished with value: 0.19413714230096843 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.5795795619141482, 'max_features': None, 'min_weight_fraction_leaf': 0.25843319308808477}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20756228991444287
Fold 2 IBS: 0.18241014181886153
Fold 3 IBS: 0.19010780605990774
Fold 4 IBS: 0.1965188911328108
Fold 5 IBS: 0.2165228499983226
[I 2024-04-16 01:46:47,741] Trial 67 finished with value: 0.19862439578486912 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.5272795412017645, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18877241981072748}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20184305095794017
Fold 2 IBS: 0.1787309749723237
Fold 3 IBS: 0.20120678595418764
Fold 4 IBS: 0.1742316565111679
Fold 5 IBS: 0.201516055621083
[I 2024-04-16 01:48:02,218] Trial 68 finished with value: 0.19150570480334048 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.4839695093257508, 'max_features': None, 'min_weight_fraction_leaf': 0.09899473983366885}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19755614540805655
Fold 2 IBS: 0.18177535693963126
Fold 3 IBS: 0.20403660662298992
Fold 4 IBS: 0.1787311115843317
Fold 5 IBS: 0.1965089126275851
[I 2024-04-16 01:49:03,560] Trial 69 finished with value: 0.1917216266365189 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.7420524473335729, 'max_features': None, 'min_weight_fraction_leaf': 0.17368349136374633}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19473380707808208
Fold 2 IBS: 0.18358627266893093
Fold 3 IBS: 0.1958997961194511
Fold 4 IBS: 0.18138380012465705
Fold 5 IBS: 0.197366737447653
[I 2024-04-16 01:50:05,295] Trial 70 finished with value: 0.19059408268775482 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.6489452374894027, 'max_features': None, 'min_weight_fraction_leaf': 0.15841991648450945}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20365881101077704
Fold 2 IBS: 0.1766635333908709
Fold 3 IBS: 0.1993723191750982
Fold 4 IBS: 0.174992812149042
Fold 5 IBS: 0.19926969814851359
[I 2024-04-16 01:50:56,211] Trial 71 finished with value: 0.19079143477486035 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.5595698482795526, 'max_features': None, 'min_weight_fraction_leaf': 0.11106694826397323}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19961023365297115
Fold 2 IBS: 0.17879413625764815
Fold 3 IBS: 0.1946529980492873
Fold 4 IBS: 0.172974660208681
Fold 5 IBS: 0.19533108806851757
[I 2024-04-16 01:51:34,615] Trial 72 finished with value: 0.18827262324742106 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.5134747414571056, 'max_features': None, 'min_weight_fraction_leaf': 0.1165099939333998}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2406658422448618
Fold 2 IBS: 0.17543636765365264
Fold 3 IBS: 0.20872262379305262
Fold 4 IBS: 0.1582660703515272
Fold 5 IBS: 0.19305772551331746
[I 2024-04-16 01:52:51,129] Trial 73 finished with value: 0.19522972591128235 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.6983010650965532, 'max_features': None, 'min_weight_fraction_leaf': 0.06449301509276852}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19712103206343998
Fold 2 IBS: 0.17660849812337273
Fold 3 IBS: 0.20208369494673262
Fold 4 IBS: 0.17445202335805232
Fold 5 IBS: 0.19445977234046177
[I 2024-04-16 01:53:12,512] Trial 74 finished with value: 0.18894500416641186 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.6110803063418331, 'max_features': None, 'min_weight_fraction_leaf': 0.09204014156660344}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19432597845488106
Fold 2 IBS: 0.1842349926772866
Fold 3 IBS: 0.17663862700419186
Fold 4 IBS: 0.18869159471341404
Fold 5 IBS: 0.1973738153761847
[I 2024-04-16 01:53:24,226] Trial 75 finished with value: 0.18825300164519165 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 110, 'oob_score': False, 'max_samples': 0.4564581127887277, 'max_features': None, 'min_weight_fraction_leaf': 0.09124814911718805}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19230824727470416
Fold 2 IBS: 0.17979735372963127
Fold 3 IBS: 0.17444978919585724
Fold 4 IBS: 0.18891860783041628
Fold 5 IBS: 0.20640760960543755
[I 2024-04-16 01:53:32,234] Trial 76 finished with value: 0.18837632152720932 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.4493825077620159, 'max_features': None, 'min_weight_fraction_leaf': 0.07484643760885143}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2096553878490079
Fold 2 IBS: 0.19546776810936306
Fold 3 IBS: 0.18466297504921592
Fold 4 IBS: 0.2027457827860734
Fold 5 IBS: 0.2159279265126386
[I 2024-04-16 01:53:33,966] Trial 77 finished with value: 0.2016919680612598 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.44623638751286704, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08351576114037278}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20288745878228068
Fold 2 IBS: 0.18021364044634894
Fold 3 IBS: 0.18544008572673462
Fold 4 IBS: 0.1954523164372797
Fold 5 IBS: 0.20662987774761257
[I 2024-04-16 01:53:39,350] Trial 78 finished with value: 0.1941246758280513 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.34348495165141796, 'max_features': None, 'min_weight_fraction_leaf': 0.07160945459759985}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20051892419249925
Fold 2 IBS: 0.16576553460873114
Fold 3 IBS: 0.17900575343589448
Fold 4 IBS: 0.21493954058739861

Fold 5 IBS: 0.19832262248550672
[I 2024-04-16 01:53:42,952] Trial 79 finished with value: 0.19171047506200603 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.4577545127391126, 'max_features': None, 'min_weight_fraction_leaf': 0.09781938022887349}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19426839896125792
Fold 2 IBS: 0.17981710691108702
Fold 3 IBS: 0.17861065931527556
Fold 4 IBS: 0.19911223696785046
Fold 5 IBS: 0.2081704718696194
[I 2024-04-16 01:53:48,735] Trial 80 finished with value: 0.19199577480501806 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 99, 'oob_score': False, 'max_samples': 0.40696501409993335, 'max_features': None, 'min_weight_fraction_leaf': 0.05418386307803515}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1928921274877498
Fold 2 IBS: 0.17968754745319848
Fold 3 IBS: 0.1856899889798534
Fold 4 IBS: 0.17837447428728506
Fold 5 IBS: 0.198631389144611
[I 2024-04-16 01:54:05,063] Trial 81 finished with value: 0.18705510547053955 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.5144714895930234, 'max_features': None, 'min_weight_fraction_leaf': 0.1183473468834669}. Best is trial 81 with value: 0.18705510547053955.
Fold 1 IBS: 0.19498785748501332
Fold 2 IBS: 0.18416000234892713
Fold 3 IBS: 0.1749811263553196
Fold 4 IBS: 0.19243209083637866
Fold 5 IBS: 0.2042109093465032
[I 2024-04-16 01:54:13,386] Trial 82 finished with value: 0.19015439727442837 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.4814517826261244, 'max_features': None, 'min_weight_fraction_leaf': 0.09388371332845069}. Best is trial 81 with value: 0.18705510547053955.
Fold 1 IBS: 0.196572591750229
Fold 2 IBS: 0.17992831027310296
Fold 3 IBS: 0.1912315696277225
Fold 4 IBS: 0.18222555877807528
Fold 5 IBS: 0.19873701220967457
[I 2024-04-16 01:54:34,433] Trial 83 finished with value: 0.18973900852776088 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.5487216062543878, 'max_features': None, 'min_weight_fraction_leaf': 0.11933876697393087}. Best is trial 81 with value: 0.18705510547053955.
Fold 1 IBS: 0.18928116916252316
Fold 2 IBS: 0.17681207829778872
Fold 3 IBS: 0.18036591522167056
Fold 4 IBS: 0.19071008027550745
Fold 5 IBS: 0.1968400042365038
[I 2024-04-16 01:54:41,747] Trial 84 finished with value: 0.18680184943879874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.5072704415810627, 'max_features': None, 'min_weight_fraction_leaf': 0.13923559758770704}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.19635077420451166
Fold 2 IBS: 0.16965044412515498
Fold 3 IBS: 0.18051935687673434
Fold 4 IBS: 0.19261116494168012
Fold 5 IBS: 0.2029196071758891
[I 2024-04-16 01:54:46,676] Trial 85 finished with value: 0.18841026946479403 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 51, 'oob_score': False, 'max_samples': 0.4328219024747799, 'max_features': None, 'min_weight_fraction_leaf': 0.13506145126211014}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.2118790715218371
Fold 2 IBS: 0.18649002683647467
Fold 3 IBS: 0.18683588827455805
Fold 4 IBS: 0.20089312342129093
Fold 5 IBS: 0.2113793647760344
[I 2024-04-16 01:54:50,189] Trial 86 finished with value: 0.19949549496603905 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 47, 'oob_score': False, 'max_samples': 0.34070435538857635, 'max_features': None, 'min_weight_fraction_leaf': 0.14319233231910872}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.19246098793488453
Fold 2 IBS: 0.14417757029810832
Fold 3 IBS: 0.19013491268897229
Fold 4 IBS: 0.20432510462782214
Fold 5 IBS: 0.20794628568704515
[I 2024-04-16 01:54:51,327] Trial 87 finished with value: 0.1878089722473665 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 4, 'oob_score': False, 'max_samples': 0.4322924864630003, 'max_features': None, 'min_weight_fraction_leaf': 0.1115168177522978}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.19090029461234054
Fold 2 IBS: 0.14137499469636072
Fold 3 IBS: 0.1812986156169945
Fold 4 IBS: 0.207189515156582
Fold 5 IBS: 0.1920780785637807
[I 2024-04-16 01:54:52,225] Trial 88 finished with value: 0.18256829972921168 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.4387811941970341, 'max_features': None, 'min_weight_fraction_leaf': 0.11484074874869586}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.1943419444091425
Fold 2 IBS: 0.15233546024160036
Fold 3 IBS: 0.18773534658058533
Fold 4 IBS: 0.2073548214922775
Fold 5 IBS: 0.20084896018721313
[I 2024-04-16 01:54:53,643] Trial 89 finished with value: 0.18852330658216374 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.4337687502966132, 'max_features': None, 'min_weight_fraction_leaf': 0.06543133288022018}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.22601211378830166
Fold 2 IBS: 0.23023726982761436
Fold 3 IBS: 0.21891610644565596
Fold 4 IBS: 0.21627736857389285
Fold 5 IBS: 0.21447814217631173
[I 2024-04-16 01:54:54,296] Trial 90 finished with value: 0.22118420016235532 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 3, 'oob_score': False, 'max_samples': 0.37200101251335593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07632016824081125}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.2031710494812762
Fold 2 IBS: 0.16277512848511938
Fold 3 IBS: 0.18279796790018857
Fold 4 IBS: 0.19635097053183548
Fold 5 IBS: 0.21148201052572227
[I 2024-04-16 01:54:57,009] Trial 91 finished with value: 0.19131542538482837 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.39839348368477034, 'max_features': None, 'min_weight_fraction_leaf': 0.1077523273534647}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.19236727730692432
Fold 2 IBS: 0.17971654848915258
Fold 3 IBS: 0.17691334078269377
Fold 4 IBS: 0.19493487111241187
Fold 5 IBS: 0.19796548040061543
[I 2024-04-16 01:55:02,210] Trial 92 finished with value: 0.18837950361835962 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 64, 'oob_score': False, 'max_samples': 0.4924231584508079, 'max_features': None, 'min_weight_fraction_leaf': 0.13667336203315236}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.19352514327853118
Fold 2 IBS: 0.18116170295711229
Fold 3 IBS: 0.17842605559273972
Fold 4 IBS: 0.19526873278026627
Fold 5 IBS: 0.1975533434467797
[I 2024-04-16 01:55:07,374] Trial 93 finished with value: 0.18918699561108582 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 20, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.49548416980447385, 'max_features': None, 'min_weight_fraction_leaf': 0.11434274596559542}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.19662678661285796
Fold 2 IBS: 0.18002758970706242
Fold 3 IBS: 0.18252512585918226
Fold 4 IBS: 0.2005080205374747
Fold 5 IBS: 0.20057411855259485
[I 2024-04-16 01:55:10,732] Trial 94 finished with value: 0.19205232825383445 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.46704862070515885, 'max_features': None, 'min_weight_fraction_leaf': 0.08985062448642944}. Best is trial 88 with value: 0.18256829972921168.

Fold 1 IBS: 0.19946297870294474
Fold 2 IBS: 0.1787195203639327
Fold 3 IBS: 0.18978142216242233
Fold 4 IBS: 0.19366785888566598
Fold 5 IBS: 0.20885493662651164
[I 2024-04-16 01:55:13,546] Trial 95 finished with value: 0.19409734334829548 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 16, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.43465916069396443, 'max_features': None, 'min_weight_fraction_leaf': 0.14266992337047604}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.21394879098507638
Fold 2 IBS: 0.22071767868681683
Fold 3 IBS: 0.204663570980379
Fold 4 IBS: 0.22456834280613222
Fold 5 IBS: 0.21820813733001868
[I 2024-04-16 01:55:16,081] Trial 96 finished with value: 0.21642130415768462 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.2533979604399289, 'max_features': None, 'min_weight_fraction_leaf': 0.13387701169883912}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.21396124342871353
Fold 2 IBS: 0.22122834841340494
Fold 3 IBS: 0.20452977366874636
Fold 4 IBS: 0.22481229988409993
Fold 5 IBS: 0.2178285026005057
[I 2024-04-16 01:55:19,037] Trial 97 finished with value: 0.2164720335990941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.5052035799981648, 'max_features': None, 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.20092800237475308
Fold 2 IBS: 0.16438642104717785
Fold 3 IBS: 0.18331492320780918
Fold 4 IBS: 0.19098858919975734
Fold 5 IBS: 0.21618831164728108
[I 2024-04-16 01:55:21,144] Trial 98 finished with value: 0.1911612494953557 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 15, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.4548224820450948, 'max_features': None, 'min_weight_fraction_leaf': 0.1035182522031739}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.21383386308421298
Fold 2 IBS: 0.2200257502519249
Fold 3 IBS: 0.20425687587883834
Fold 4 IBS: 0.22452054619512135
Fold 5 IBS: 0.21752026236388408
[I 2024-04-16 01:55:24,778] Trial 99 finished with value: 0.21603145955479636 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.3646962100401976, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 88 with value: 0.18256829972921168.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.18256829972921168], datetime_start=datetime.datetime(2024, 4, 16, 1, 54, 51, 332546), datetime_complete=datetime.datetime(2024, 4, 16, 1, 54, 52, 224831), params={'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.4387811941970341, 'max_features': None, 'min_weight_fraction_leaf': 0.11484074874869586}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.18256829972921168

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.871
train_ibs:  0.183

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [58]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=8, max_features='auto', max_leaf_nodes=17,
                     max_samples=0.9776940371468902, min_samples_split=9,
                     min_weight_fraction_leaf=0.03508377856391107,
                     n_estimators=19, random_state=123, warm_start=True)

test_cindex:  0.628

RandomSurvivalForest(max_depth=17, max_features=None, max_leaf_nodes=9,
                     max_samples=0.4387811941970341, min_samples_leaf=15,
                     min_samples_split=14,
                     min_weight_fraction_leaf=0.11484074874869586,
                     n_estimators=5, random_state=123)

test_ibs:  0.226

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [61]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:55:25,907] A new study created in memory with name: no-name-99c1fa6c-c291-4ee2-af3c-75d35e192141

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:55:27,671] Trial 0 finished with value: 0.7473957621833802 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:55:32,303] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 01:55:42,379] Trial 2 finished with value: 0.6923003209128187 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:55:43,718] Trial 3 finished with value: 0.7413714438756912 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:55:47,567] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:55:51,632] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:55:54,167] Trial 6 finished with value: 0.732293770804161 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 01:56:00,522] Trial 7 finished with value: 0.6734752861581592 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:56:01,071] Trial 8 finished with value: 0.7390137804420783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6103286384976526
[I 2024-04-16 01:56:14,583] Trial 9 finished with value: 0.6536058926723091 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:56:19,157] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:56:20,511] Trial 11 finished with value: 0.7248022715139639 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13639294401318086}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:56:22,408] Trial 12 finished with value: 0.738919783054472 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.12081901960613745}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.538961038961039
Fold 2 C-index: 0.6852678571428571
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6737089201877934
[I 2024-04-16 01:56:22,970] Trial 13 finished with value: 0.6572495141146298 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 7, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7093678865761541, 'min_weight_fraction_leaf': 0.22382320879779793}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:56:26,790] Trial 14 finished with value: 0.8155995223580931 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.08844623426024902}. Best is trial 14 with value: 0.8155995223580931.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8616071428571429

Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:56:30,676] Trial 15 finished with value: 0.8175678569374233 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:56:32,433] Trial 16 finished with value: 0.7175541981326802 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.89699542693011, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:56:34,234] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.14923859685882634, 'min_weight_fraction_leaf': 0.19291420116320776}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:56:46,483] Trial 18 finished with value: 0.6918780011802125 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 219, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8864397155885823, 'min_weight_fraction_leaf': 0.0011986328064286234}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 01:56:48,305] Trial 19 finished with value: 0.7150367802836787 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3872109746184179, 'min_weight_fraction_leaf': 0.06841061583155703}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:56:50,257] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 371, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6674617762374991, 'min_weight_fraction_leaf': 0.4096697647298415}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:56:52,223] Trial 21 finished with value: 0.7705821650610357 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8915767644233141, 'min_weight_fraction_leaf': 0.08195092579029489}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:56:56,508] Trial 22 finished with value: 0.8131242613173569 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8806702750475447, 'min_weight_fraction_leaf': 0.0853931201588063}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 01:57:00,097] Trial 23 finished with value: 0.7943607256594918 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9341500043945721, 'min_weight_fraction_leaf': 0.17794205149320266}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:57:03,657] Trial 24 finished with value: 0.8122314041744998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.996241305116031, 'min_weight_fraction_leaf': 0.04979027572818695}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:57:09,420] Trial 25 finished with value: 0.8353010848093593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8365322692071835, 'min_weight_fraction_leaf': 0.030976654928121905}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:57:34,650] Trial 26 finished with value: 0.6938412342440664 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8432409992602206, 'min_weight_fraction_leaf': 0.02898048784225954}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 01:57:38,472] Trial 27 finished with value: 0.8136023118221501 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7138942545087488, 'min_weight_fraction_leaf': 0.027613753152892502}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:57:40,500] Trial 28 finished with value: 0.7738447531802879 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 243, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7067616351924364, 'min_weight_fraction_leaf': 0.15462169599864348}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:57:43,441] Trial 29 finished with value: 0.7394671851138874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 342, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6331179010773698, 'min_weight_fraction_leaf': 0.10457848931222141}. Best is trial 25 with value: 0.8353010848093593.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 01:57:45,813] Trial 30 finished with value: 0.6952756411321559 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.21007556306018008}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 01:57:49,431] Trial 31 finished with value: 0.8109658972018442 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7335324657551858, 'min_weight_fraction_leaf': 0.025638936264718012}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:57:54,914] Trial 32 finished with value: 0.8258846366631387 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 454, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9206859827921332, 'min_weight_fraction_leaf': 0.07830549040677996}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:57:59,357] Trial 33 finished with value: 0.752143038287942 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9312265778306535, 'min_weight_fraction_leaf': 0.09779873758442217}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 01:58:04,851] Trial 34 finished with value: 0.8237631510650582 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 419, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8502925518169527, 'min_weight_fraction_leaf': 0.07190376521891352}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 01:58:10,009] Trial 35 finished with value: 0.6805975493975609 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8479407413376732, 'min_weight_fraction_leaf': 0.2727797492864307}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:58:30,798] Trial 36 finished with value: 0.7042474047675116 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 419, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7665754532614238, 'min_weight_fraction_leaf': 0.05998425415499972}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:58:32,904] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6168907596043948, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 01:58:36,800] Trial 38 finished with value: 0.7712053322439204 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.48791124460782864, 'min_weight_fraction_leaf': 0.11636327504384883}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 01:58:47,285] Trial 39 finished with value: 0.6866596996178657 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9454171110339408, 'min_weight_fraction_leaf': 0.16103442323742076}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 01:58:49,865] Trial 40 finished with value: 0.73136266775953 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8248201121352144, 'min_weight_fraction_leaf': 0.062324276491539266}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:58:53,589] Trial 41 finished with value: 0.8194462435049387 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9532794241644034, 'min_weight_fraction_leaf': 0.08780433668579535}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 01:58:57,614] Trial 42 finished with value: 0.8161218223168293 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9925634601195337, 'min_weight_fraction_leaf': 0.011813467862108337}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 01:59:01,554] Trial 43 finished with value: 0.8277187329169176 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9526082362533064, 'min_weight_fraction_leaf': 0.04745958703609952}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:59:04,245] Trial 44 finished with value: 0.8061876207151526 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9584447959914432, 'min_weight_fraction_leaf': 0.042996535753400594}. Best is trial 25 with value: 0.8353010848093593.

Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:59:06,337] Trial 45 finished with value: 0.7453193052128062 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 315, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7943188724004586, 'min_weight_fraction_leaf': 0.13248513273448603}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:59:08,529] Trial 46 finished with value: 0.7484591428509685 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 414, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8628193765768433, 'min_weight_fraction_leaf': 0.10117431862592552}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:59:16,045] Trial 47 finished with value: 0.6898405522600619 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9678182278668181, 'min_weight_fraction_leaf': 0.04505624352097245}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:59:21,407] Trial 48 finished with value: 0.7805504590529708 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 387, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7579522296203552, 'min_weight_fraction_leaf': 0.014387233594138467}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:59:25,350] Trial 49 finished with value: 0.7647035593034277 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9238974310190072, 'min_weight_fraction_leaf': 0.23849933216996128}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 01:59:28,654] Trial 50 finished with value: 0.6991075412401303 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9957902969950577, 'min_weight_fraction_leaf': 0.12248746772427224}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:59:32,982] Trial 51 finished with value: 0.8293064151056295 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 351, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9215454148342977, 'min_weight_fraction_leaf': 0.08156726752603399}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 01:59:36,649] Trial 52 finished with value: 0.8252797596290984 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 315, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9167408381067254, 'min_weight_fraction_leaf': 0.06667579377107945}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:59:40,739] Trial 53 finished with value: 0.8278627934828447 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9035701569637378, 'min_weight_fraction_leaf': 0.04859656248662959}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:59:44,596] Trial 54 finished with value: 0.8352140020905686 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9125432991997491, 'min_weight_fraction_leaf': 0.03206288242066289}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:59:47,348] Trial 55 finished with value: 0.8289524986399364 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 240, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.797364748691682, 'min_weight_fraction_leaf': 0.03710106747804083}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:59:48,821] Trial 56 finished with value: 0.7823862339632688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 01:59:51,199] Trial 57 finished with value: 0.8321404095277231 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8192002992527245, 'min_weight_fraction_leaf': 0.03955892145134048}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 02:00:00,192] Trial 58 finished with value: 0.7041901514005171 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 167, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6659973923607253, 'min_weight_fraction_leaf': 0.027230063640658893}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 02:00:02,906] Trial 59 finished with value: 0.8286971643711862 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 194, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7850187786845839, 'min_weight_fraction_leaf': 8.414791031117336e-05}. Best is trial 25 with value: 0.8353010848093593.

Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 02:00:04,574] Trial 60 finished with value: 0.8339962837677252 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7803239385177003, 'min_weight_fraction_leaf': 0.005453058174879628}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 02:00:06,942] Trial 61 finished with value: 0.8421154836916532 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 131, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.806720965637479, 'min_weight_fraction_leaf': 0.0015497906295155323}. Best is trial 61 with value: 0.8421154836916532.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 02:00:10,411] Trial 62 finished with value: 0.8412359074004486 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 121, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.807914741169143, 'min_weight_fraction_leaf': 0.017275515706874415}. Best is trial 61 with value: 0.8421154836916532.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 02:00:11,977] Trial 63 finished with value: 0.8418841701577955 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7471161630300795, 'min_weight_fraction_leaf': 0.02164269686952123}. Best is trial 61 with value: 0.8421154836916532.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 02:00:13,582] Trial 64 finished with value: 0.8425402944529242 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7444072631782004, 'min_weight_fraction_leaf': 0.019461022888333096}. Best is trial 64 with value: 0.8425402944529242.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 02:00:15,256] Trial 65 finished with value: 0.8421939282528357 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 111, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7409613764589495, 'min_weight_fraction_leaf': 0.017696281413854598}. Best is trial 64 with value: 0.8425402944529242.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 02:00:16,949] Trial 66 finished with value: 0.8440112453188864 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7424477137148021, 'min_weight_fraction_leaf': 0.021932301189429612}. Best is trial 66 with value: 0.8440112453188864.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 02:00:18,768] Trial 67 finished with value: 0.8479116267246294 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7307848129741745, 'min_weight_fraction_leaf': 0.016035187560656326}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:00:20,777] Trial 68 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 115, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6903237979510266, 'min_weight_fraction_leaf': 0.35364036783604025}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 02:00:22,329] Trial 69 finished with value: 0.7934960061594778 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 77, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5906341058203064, 'min_weight_fraction_leaf': 0.05853231432954687}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 02:00:23,487] Trial 70 finished with value: 0.8370199541752875 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 42, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.746202010308237, 'min_weight_fraction_leaf': 0.01718513441911046}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 02:00:24,324] Trial 71 finished with value: 0.8315863683193498 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 28, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7286910789490153, 'min_weight_fraction_leaf': 0.021392176623630743}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 02:00:26,642] Trial 72 finished with value: 0.845010691191986 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 130, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6877705225452767, 'min_weight_fraction_leaf': 0.016534328495177237}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 02:00:28,912] Trial 73 finished with value: 0.8464476262798024 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 124, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6950988475816776, 'min_weight_fraction_leaf': 0.0008685229148859483}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 02:00:30,982] Trial 74 finished with value: 0.8555893751688586 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 132, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6774440080108878, 'min_weight_fraction_leaf': 0.004532767529812777}. Best is trial 74 with value: 0.8555893751688586.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 02:00:33,046] Trial 75 finished with value: 0.834080320445655 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 141, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5277241651577844, 'min_weight_fraction_leaf': 0.00034951661289149213}. Best is trial 74 with value: 0.8555893751688586.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 02:00:38,318] Trial 76 finished with value: 0.6621863920044102 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 141, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6900957324692815, 'min_weight_fraction_leaf': 0.05551936393621635}. Best is trial 74 with value: 0.8555893751688586.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 02:00:39,980] Trial 77 finished with value: 0.858408551105818 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 85, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6427403214768266, 'min_weight_fraction_leaf': 0.011137087979573197}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:00:41,363] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 90, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.645711194297668, 'min_weight_fraction_leaf': 0.41218066030994116}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 02:00:42,472] Trial 79 finished with value: 0.8173293044101382 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 63, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6063283426127006, 'min_weight_fraction_leaf': 0.03219406437302813}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6572769953051644
[I 2024-04-16 02:00:43,987] Trial 80 finished with value: 0.6802368592860896 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 101, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6797865329606951, 'min_weight_fraction_leaf': 0.30841556955373983}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 02:00:45,952] Trial 81 finished with value: 0.8423825904046769 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7131028174450602, 'min_weight_fraction_leaf': 0.009906725312419967}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 02:00:47,847] Trial 82 finished with value: 0.8462213089907028 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 155, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7220615522106731, 'min_weight_fraction_leaf': 0.01596811650239777}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 02:00:49,897] Trial 83 finished with value: 0.8266385730616012 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 159, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6391133175097252, 'min_weight_fraction_leaf': 0.039630933710605595}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 02:00:51,795] Trial 84 finished with value: 0.845886314298163 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7149268731531023, 'min_weight_fraction_leaf': 0.010204531997757376}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 02:00:53,727] Trial 85 finished with value: 0.7966870936124656 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 143, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5571788120979523, 'min_weight_fraction_leaf': 0.052349117710787846}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:00:54,687] Trial 86 finished with value: 0.7768163367147537 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 59, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5862744605305834, 'min_weight_fraction_leaf': 0.07101851576926227}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 02:00:55,951] Trial 87 finished with value: 0.6790163744147233 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 89, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6750432673914222, 'min_weight_fraction_leaf': 0.015105478852784723}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 02:01:00,730] Trial 88 finished with value: 0.6689726915499177 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 170, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7071205580703166, 'min_weight_fraction_leaf': 0.034641210394640964}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 02:01:03,239] Trial 89 finished with value: 0.8275515269804254 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 210, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6231287731677, 'min_weight_fraction_leaf': 0.0272446470925741}. Best is trial 77 with value: 0.858408551105818.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 02:01:05,252] Trial 90 finished with value: 0.8052128181213003 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 156, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6593243539845698, 'min_weight_fraction_leaf': 0.056494043546166495}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 02:01:07,009] Trial 91 finished with value: 0.8440803173811705 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 128, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7225655744279161, 'min_weight_fraction_leaf': 0.013637383517672729}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 02:01:08,771] Trial 92 finished with value: 0.8571108480345735 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 127, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7279610537008266, 'min_weight_fraction_leaf': 0.008737769636097927}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9578059071729957
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 02:01:10,597] Trial 93 finished with value: 0.8551425134552435 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7278711689328157, 'min_weight_fraction_leaf': 0.00826825686537057}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 02:01:13,205] Trial 94 finished with value: 0.866733060426232 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7692755291164257, 'min_weight_fraction_leaf': 0.006944921267975795}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 02:01:15,817] Trial 95 finished with value: 0.8445142185952648 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7669577786786118, 'min_weight_fraction_leaf': 0.044649174116016065}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 02:01:18,221] Trial 96 finished with value: 0.8396585023010648 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 148, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.684661981274086, 'min_weight_fraction_leaf': 0.008786170259833718}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 02:01:21,091] Trial 97 finished with value: 0.8279858779359974 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.69951914293224, 'min_weight_fraction_leaf': 0.03894786555507988}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 02:01:23,733] Trial 98 finished with value: 0.8490282471357398 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6503126145421575, 'min_weight_fraction_leaf': 0.0007737014426484837}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7974683544303798

[I 2024-04-16 02:01:26,318] A new study created in memory with name: no-name-c5e0e72c-f820-4878-86d8-89ecf2a4b905

Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 02:01:26,304] Trial 99 finished with value: 0.7792227629070073 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 170, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5365720508426045, 'min_weight_fraction_leaf': 0.004358450234500475}. Best is trial 94 with value: 0.866733060426232.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.866733060426232], datetime_start=datetime.datetime(2024, 4, 16, 2, 1, 10, 603077), datetime_complete=datetime.datetime(2024, 4, 16, 2, 1, 13, 204985), params={'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7692755291164257, 'min_weight_fraction_leaf': 0.006944921267975795}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.866733060426232

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.20324441808559623
Fold 2 IBS: 0.1951588328187537
Fold 3 IBS: 0.19070420150494224
Fold 4 IBS: 0.19874690830095737
Fold 5 IBS: 0.21043314938440771
[I 2024-04-16 02:01:34,268] Trial 0 finished with value: 0.19965750201893145 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.19965750201893145.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-16 02:01:45,109] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.19965750201893145.
Fold 1 IBS: 0.20420205971539113
Fold 2 IBS: 0.1912585061325825
Fold 3 IBS: 0.18653624989741915
Fold 4 IBS: 0.18761526375944965
Fold 5 IBS: 0.2069146602615986
[I 2024-04-16 02:01:54,105] Trial 2 finished with value: 0.1953053479532882 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.20893596688851945
Fold 2 IBS: 0.19051701187606018
Fold 3 IBS: 0.18955624451377623
Fold 4 IBS: 0.1909289943501129
Fold 5 IBS: 0.20700072377138612
[I 2024-04-16 02:01:57,201] Trial 3 finished with value: 0.197387788279971 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-16 02:02:05,920] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-16 02:02:10,422] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.20565604200336957
Fold 2 IBS: 0.1984154995749487
Fold 3 IBS: 0.19127221043732198
Fold 4 IBS: 0.20318673337184806
Fold 5 IBS: 0.2114491354913557
[I 2024-04-16 02:02:18,498] Trial 6 finished with value: 0.2019959241757688 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21033134855617358
Fold 2 IBS: 0.21628633133422068
Fold 3 IBS: 0.2012050801829807
Fold 4 IBS: 0.2178792316620616
Fold 5 IBS: 0.21649960246279268
[I 2024-04-16 02:02:24,937] Trial 7 finished with value: 0.21244031883964584 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.2120398563907811
Fold 2 IBS: 0.19006412590155936
Fold 3 IBS: 0.18594102315027772
Fold 4 IBS: 0.19174839772207844
Fold 5 IBS: 0.21188341229500296
[I 2024-04-16 02:02:26,335] Trial 8 finished with value: 0.19833536309193991 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21319807558872467
Fold 2 IBS: 0.21979786241557914
Fold 3 IBS: 0.20373457069650647
Fold 4 IBS: 0.2237435946433909
Fold 5 IBS: 0.21834175061840702
[I 2024-04-16 02:02:37,822] Trial 9 finished with value: 0.21576317079252166 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.2139727346768592
Fold 2 IBS: 0.2213120202940904
Fold 3 IBS: 0.20503568053719107
Fold 4 IBS: 0.2245613118501098
Fold 5 IBS: 0.21766314539351875
[I 2024-04-16 02:02:49,373] Trial 10 finished with value: 0.21650897855035384 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21030497940211074
Fold 2 IBS: 0.19290206618360403
Fold 3 IBS: 0.19556818516782043
Fold 4 IBS: 0.19882387041781702
Fold 5 IBS: 0.2119717933704952
[I 2024-04-16 02:02:52,153] Trial 11 finished with value: 0.20191417890836946 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.20706972434681659
Fold 2 IBS: 0.19699623140204683
Fold 3 IBS: 0.18982889221830407
Fold 4 IBS: 0.19862716585283102
Fold 5 IBS: 0.20846386022396718
[I 2024-04-16 02:02:55,809] Trial 12 finished with value: 0.20019717480879312 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21602403915542812
Fold 2 IBS: 0.22135942967444958
Fold 3 IBS: 0.207522129090302
Fold 4 IBS: 0.22681102026289354
Fold 5 IBS: 0.2196363896884173
[I 2024-04-16 02:02:56,420] Trial 13 finished with value: 0.21827060157429812 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.1768405475625161}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.2066392480842299
Fold 2 IBS: 0.18785902454116382
Fold 3 IBS: 0.1885942421588505
Fold 4 IBS: 0.1788911402119244
Fold 5 IBS: 0.20431026187277884
[I 2024-04-16 02:02:59,575] Trial 14 finished with value: 0.1932587833737895 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8615610863035676, 'min_weight_fraction_leaf': 0.00662188941038383}. Best is trial 14 with value: 0.1932587833737895.

Fold 1 IBS: 0.20959115925098934
Fold 2 IBS: 0.177742818125481
Fold 3 IBS: 0.19464554067335235
Fold 4 IBS: 0.1636648885496132
Fold 5 IBS: 0.19935152208595006
[I 2024-04-16 02:03:09,102] Trial 15 finished with value: 0.1889991857370772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.0023088139988564262}. Best is trial 15 with value: 0.1889991857370772.
Fold 1 IBS: 0.21154186523364313
Fold 2 IBS: 0.1735802006784233
Fold 3 IBS: 0.1912219340060055
Fold 4 IBS: 0.1616965665766284
Fold 5 IBS: 0.19959277710979445
[I 2024-04-16 02:03:18,455] Trial 16 finished with value: 0.18752666872089896 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8957765840335672, 'min_weight_fraction_leaf': 0.010191311991891749}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.2091620042024494
Fold 2 IBS: 0.19801258235187924
Fold 3 IBS: 0.19122454802730907
Fold 4 IBS: 0.20232133278486802
Fold 5 IBS: 0.2151637052938854
[I 2024-04-16 02:03:25,884] Trial 17 finished with value: 0.20317683453207822 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9042785918294833, 'min_weight_fraction_leaf': 0.42038595995868033}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.21392851730727483
Fold 2 IBS: 0.2203112302740686
Fold 3 IBS: 0.20531706619567533
Fold 4 IBS: 0.22509036885374237
Fold 5 IBS: 0.21706040157641074
[I 2024-04-16 02:03:34,463] Trial 18 finished with value: 0.21634151684143438 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 312, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.22508105757456376}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20737708257366003
Fold 2 IBS: 0.19609767402580006
Fold 3 IBS: 0.18819938430471037
Fold 4 IBS: 0.20114004954392087
Fold 5 IBS: 0.2160102452576919
[I 2024-04-16 02:03:40,485] Trial 19 finished with value: 0.20176488714115665 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895543806821031, 'min_weight_fraction_leaf': 0.3097789443945588}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20350526528548746
Fold 2 IBS: 0.1982406915490011
Fold 3 IBS: 0.18876305026521908
Fold 4 IBS: 0.20043423378955613
Fold 5 IBS: 0.21482167675282082
[I 2024-04-16 02:03:48,295] Trial 20 finished with value: 0.20115298352841693 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8867517870122669, 'min_weight_fraction_leaf': 0.3678346055590361}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20919624684418117
Fold 2 IBS: 0.18900125773576712
Fold 3 IBS: 0.18773554697157677
Fold 4 IBS: 0.1917518862972034
Fold 5 IBS: 0.21122350951612398
[I 2024-04-16 02:03:51,070] Trial 21 finished with value: 0.1977816894729705 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8638184920383039, 'min_weight_fraction_leaf': 0.006217904257385862}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20780417605287888
Fold 2 IBS: 0.1882276018836113
Fold 3 IBS: 0.18544272265859707
Fold 4 IBS: 0.1829868094290558
Fold 5 IBS: 0.20717739840838342
[I 2024-04-16 02:03:56,939] Trial 22 finished with value: 0.1943277416865053 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9916304513453179, 'min_weight_fraction_leaf': 0.04142928400152037}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20109565009641497
Fold 2 IBS: 0.18094793231494766
Fold 3 IBS: 0.1937268937497428
Fold 4 IBS: 0.169009702983042
Fold 5 IBS: 0.19936047028886142
[I 2024-04-16 02:04:03,329] Trial 23 finished with value: 0.18882812988660175 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8538011958709324, 'min_weight_fraction_leaf': 0.013387254497520491}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.19457759163477775
Fold 2 IBS: 0.18792017350002727
Fold 3 IBS: 0.18490451457597312
Fold 4 IBS: 0.18484796411143414
Fold 5 IBS: 0.20342560527330505
[I 2024-04-16 02:04:08,565] Trial 24 finished with value: 0.19113516981910345 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7063615578289446, 'min_weight_fraction_leaf': 0.09753635397668133}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20505987377954846
Fold 2 IBS: 0.1783437638943379
Fold 3 IBS: 0.19502663651026692
Fold 4 IBS: 0.16888712557905158
Fold 5 IBS: 0.19936260036326842
[I 2024-04-16 02:04:15,033] Trial 25 finished with value: 0.18933600002529466 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8862362117578689, 'min_weight_fraction_leaf': 0.043860428079719994}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20176453553034204
Fold 2 IBS: 0.18135156347758707
Fold 3 IBS: 0.19087086985496254
Fold 4 IBS: 0.1735135267565779
Fold 5 IBS: 0.19937116775114117
[I 2024-04-16 02:04:29,186] Trial 26 finished with value: 0.18937433267412213 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 360, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9394823781600602, 'min_weight_fraction_leaf': 0.1647525192290286}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.19492411516971328
Fold 2 IBS: 0.18097482376757582
Fold 3 IBS: 0.19106644620180185
Fold 4 IBS: 0.17049571801587696
Fold 5 IBS: 0.19801397361945633
[I 2024-04-16 02:04:38,714] Trial 27 finished with value: 0.18709501535488485 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8191666066640952, 'min_weight_fraction_leaf': 0.09646653508544777}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20208702878992982
Fold 2 IBS: 0.19166074112978226
Fold 3 IBS: 0.1844014838460033
Fold 4 IBS: 0.18676803790959648
Fold 5 IBS: 0.20623856857749273
[I 2024-04-16 02:04:46,898] Trial 28 finished with value: 0.1942311720505609 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 314, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8334931071137727, 'min_weight_fraction_leaf': 0.088560330847152}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.197211862541379
Fold 2 IBS: 0.17905640106995538
Fold 3 IBS: 0.18853806208802265
Fold 4 IBS: 0.17482419472113186
Fold 5 IBS: 0.20296059811142658
[I 2024-04-16 02:04:56,877] Trial 29 finished with value: 0.18851822370638308 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7276031224679027, 'min_weight_fraction_leaf': 0.10829907781144071}. Best is trial 27 with value: 0.18709501535488485.

Fold 1 IBS: 0.2081043148093001
Fold 2 IBS: 0.20420509768667056
Fold 3 IBS: 0.1962340623978483
Fold 4 IBS: 0.2096506990203624
Fold 5 IBS: 0.21353357787911675
[I 2024-04-16 02:05:04,087] Trial 30 finished with value: 0.20634555035865962 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7314863609037403, 'min_weight_fraction_leaf': 0.10563608457720963}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.19730717896052297
Fold 2 IBS: 0.18529441321477938
Fold 3 IBS: 0.18533366129064377
Fold 4 IBS: 0.18248960193133745
Fold 5 IBS: 0.20221423911324402
[I 2024-04-16 02:05:13,307] Trial 31 finished with value: 0.19052781890210552 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6216891695240637, 'min_weight_fraction_leaf': 0.06291410320510718}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.19898317991982656
Fold 2 IBS: 0.18002409337384578
Fold 3 IBS: 0.18862277222324778
Fold 4 IBS: 0.17331221595669444
Fold 5 IBS: 0.1991038102552761
[I 2024-04-16 02:05:21,678] Trial 32 finished with value: 0.18800921434577814 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7623736719965445, 'min_weight_fraction_leaf': 0.0321952074579447}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.1991986657356779
Fold 2 IBS: 0.1815149249243747
Fold 3 IBS: 0.1872127920748621
Fold 4 IBS: 0.1764430725221634
Fold 5 IBS: 0.20202426211852528
[I 2024-04-16 02:05:33,124] Trial 33 finished with value: 0.1892787434751207 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7600744603373085, 'min_weight_fraction_leaf': 0.15599210206825725}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20103382861142927
Fold 2 IBS: 0.19282964416498558
Fold 3 IBS: 0.1870859874481926
Fold 4 IBS: 0.196226382758684
Fold 5 IBS: 0.2123300166052512
[I 2024-04-16 02:05:42,774] Trial 34 finished with value: 0.19790117191770853 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.47644913459202465, 'min_weight_fraction_leaf': 0.06966651301171624}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20779030731749934
Fold 2 IBS: 0.20307190870749472
Fold 3 IBS: 0.1962710157037756
Fold 4 IBS: 0.21081039601280466
Fold 5 IBS: 0.2132998921564787
[I 2024-04-16 02:05:49,636] Trial 35 finished with value: 0.2062487039796106 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 293, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6176859663338274, 'min_weight_fraction_leaf': 0.10956820043618563}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.21290730554088733
Fold 2 IBS: 0.21811017960573384
Fold 3 IBS: 0.20259067726637844
Fold 4 IBS: 0.22217655091339963
Fold 5 IBS: 0.2176672935324032
[I 2024-04-16 02:05:57,848] Trial 36 finished with value: 0.2146904013717605 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8179384621484631, 'min_weight_fraction_leaf': 0.0350871457115}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20937538943889084
Fold 2 IBS: 0.1976588452266711
Fold 3 IBS: 0.19445670151606664
Fold 4 IBS: 0.20487984959052633
Fold 5 IBS: 0.21266809601522105
[I 2024-04-16 02:06:03,330] Trial 37 finished with value: 0.20380777635747518 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.727246384588029, 'min_weight_fraction_leaf': 0.12859608190892008}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20530011772785173
Fold 2 IBS: 0.19803832641530136
Fold 3 IBS: 0.18877575404214447
Fold 4 IBS: 0.2041315572944101
Fold 5 IBS: 0.21433733406277344
[I 2024-04-16 02:06:10,349] Trial 38 finished with value: 0.2021166179084962 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.18743659703875493}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.2126855497240101
Fold 2 IBS: 0.21939483841221513
Fold 3 IBS: 0.204514596423358
Fold 4 IBS: 0.2241774075643293
Fold 5 IBS: 0.21770096331347819
[I 2024-04-16 02:06:15,678] Trial 39 finished with value: 0.21569467108747814 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 227, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5177303386477011, 'min_weight_fraction_leaf': 0.2437702761952286}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20205635314852127
Fold 2 IBS: 0.1779550910748468
Fold 3 IBS: 0.19199273466468036
Fold 4 IBS: 0.16938184753905136
Fold 5 IBS: 0.2016814036986973
[I 2024-04-16 02:06:29,826] Trial 40 finished with value: 0.18861348602515943 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 425, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7599898043769167, 'min_weight_fraction_leaf': 0.04836923196673275}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20353704880860568
Fold 2 IBS: 0.17829121646794985
Fold 3 IBS: 0.1934981237320483
Fold 4 IBS: 0.16969026055921907
Fold 5 IBS: 0.20110029965603304
[I 2024-04-16 02:06:45,868] Trial 41 finished with value: 0.18922338984477122 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7760359149297024, 'min_weight_fraction_leaf': 0.05040101778889726}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20482842806207383
Fold 2 IBS: 0.1759182336741199
Fold 3 IBS: 0.1924090734725373
Fold 4 IBS: 0.16621668500349204
Fold 5 IBS: 0.20008837310029803
[I 2024-04-16 02:06:58,600] Trial 42 finished with value: 0.18789215866250425 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.07308613146326948}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.19842848181510805
Fold 2 IBS: 0.18062994551768752
Fold 3 IBS: 0.19088081768989523
Fold 4 IBS: 0.17229498637104404
Fold 5 IBS: 0.19881715613809028
[I 2024-04-16 02:07:09,240] Trial 43 finished with value: 0.18821027750636501 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8119352159878038, 'min_weight_fraction_leaf': 0.08910421030553545}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.2124764225213534
Fold 2 IBS: 0.21791314037114443
Fold 3 IBS: 0.2020724966160973
Fold 4 IBS: 0.22110609114819313
Fold 5 IBS: 0.2175856606149026
[I 2024-04-16 02:07:16,405] Trial 44 finished with value: 0.21423076225433818 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8109881601003952, 'min_weight_fraction_leaf': 0.02764976413213125}. Best is trial 27 with value: 0.18709501535488485.

Fold 1 IBS: 0.2057886310768082
Fold 2 IBS: 0.19693079192071614
Fold 3 IBS: 0.19129734861332404
Fold 4 IBS: 0.19629616500268943
Fold 5 IBS: 0.21038967978117093
[I 2024-04-16 02:07:27,182] Trial 45 finished with value: 0.20014052327894177 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 486, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9606319416987669, 'min_weight_fraction_leaf': 0.06471432252401287}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20934463006342957
Fold 2 IBS: 0.16626348855382878
Fold 3 IBS: 0.19117275286807775
Fold 4 IBS: 0.1653610699678058
Fold 5 IBS: 0.19753335331998537
[I 2024-04-16 02:07:37,720] Trial 46 finished with value: 0.18593505895462542 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.925572429448618, 'min_weight_fraction_leaf': 0.08676721083273177}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20078459799720833
Fold 2 IBS: 0.17648515464578451
Fold 3 IBS: 0.19226229201317951
Fold 4 IBS: 0.17044349838265743
Fold 5 IBS: 0.1988228675530043
[I 2024-04-16 02:07:48,135] Trial 47 finished with value: 0.1877596821183668 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 264, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9213571492568404, 'min_weight_fraction_leaf': 0.13981998741957938}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20777470701020084
Fold 2 IBS: 0.19819806121913253
Fold 3 IBS: 0.19206408523089602
Fold 4 IBS: 0.20455345941908806
Fold 5 IBS: 0.21359199143332838
[I 2024-04-16 02:07:54,643] Trial 48 finished with value: 0.20323646086252917 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 268, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9948675206762962, 'min_weight_fraction_leaf': 0.14355467192528748}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20833920868185066
Fold 2 IBS: 0.19641978742053248
Fold 3 IBS: 0.19089914369604163
Fold 4 IBS: 0.19551044582583754
Fold 5 IBS: 0.21209727532100356
[I 2024-04-16 02:07:58,372] Trial 49 finished with value: 0.20065317218905315 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9302954535353424, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20772600832510035
Fold 2 IBS: 0.1742560953767108
Fold 3 IBS: 0.18899681699563198
Fold 4 IBS: 0.17664643353661777
Fold 5 IBS: 0.20207162913086515
[I 2024-04-16 02:08:05,487] Trial 50 finished with value: 0.18993939667298523 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9554972202974833, 'min_weight_fraction_leaf': 0.07893980965459402}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2175228940538217
Fold 2 IBS: 0.16882647052353114
Fold 3 IBS: 0.19262466994453928
Fold 4 IBS: 0.16127708924491224
Fold 5 IBS: 0.19790007020123332
[I 2024-04-16 02:08:16,874] Trial 51 finished with value: 0.18763023879360755 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.906363786004768, 'min_weight_fraction_leaf': 0.01993763032727272}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.1994294701749906
Fold 2 IBS: 0.18271153506347773
Fold 3 IBS: 0.1877412420614239
Fold 4 IBS: 0.1779301349070125
Fold 5 IBS: 0.20347444570159795
[I 2024-04-16 02:08:22,330] Trial 52 finished with value: 0.19025736558170053 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9180205789374659, 'min_weight_fraction_leaf': 0.208464530420868}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2143294788132567
Fold 2 IBS: 0.16871602133484195
Fold 3 IBS: 0.18923830444515657
Fold 4 IBS: 0.16447114425777135
Fold 5 IBS: 0.1979457995777836
[I 2024-04-16 02:08:34,182] Trial 53 finished with value: 0.18694014968576203 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.882994548404635, 'min_weight_fraction_leaf': 0.0192164714981712}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21491661558194466
Fold 2 IBS: 0.16865192696486195
Fold 3 IBS: 0.18911632922455485
Fold 4 IBS: 0.164322793559542
Fold 5 IBS: 0.19780078494724415
[I 2024-04-16 02:08:45,476] Trial 54 finished with value: 0.18696169005562951 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8791259750871762, 'min_weight_fraction_leaf': 0.021612413990603922}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21165029134764404
Fold 2 IBS: 0.21713184039980743
Fold 3 IBS: 0.2020959160332439
Fold 4 IBS: 0.2196516953463444
Fold 5 IBS: 0.2174205266346621
[I 2024-04-16 02:08:51,173] Trial 55 finished with value: 0.2135900539523404 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8732977999719564, 'min_weight_fraction_leaf': 0.0218387875769675}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2079119279717199
Fold 2 IBS: 0.17452040666804391
Fold 3 IBS: 0.18897194723766658
Fold 4 IBS: 0.17595369607084504
Fold 5 IBS: 0.20128067491490945
[I 2024-04-16 02:08:59,212] Trial 56 finished with value: 0.18972773057263695 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 306, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.843782187611387, 'min_weight_fraction_leaf': 0.021841146008507534}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20727371387572535
Fold 2 IBS: 0.18581142935300873
Fold 3 IBS: 0.18420810577126234
Fold 4 IBS: 0.1826954923475708
Fold 5 IBS: 0.20414460425521397
[I 2024-04-16 02:09:04,728] Trial 57 finished with value: 0.19282666912055624 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8940258738700295, 'min_weight_fraction_leaf': 0.006298394024379893}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21401047841123993
Fold 2 IBS: 0.22071750963432682
Fold 3 IBS: 0.20490008002784188
Fold 4 IBS: 0.22480148510035142
Fold 5 IBS: 0.21794170884649433
[I 2024-04-16 02:09:10,406] Trial 58 finished with value: 0.21647425240405088 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 253, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.28101469689358977, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2260705108377443
Fold 2 IBS: 0.16842595034518754
Fold 3 IBS: 0.19588890831987768
Fold 4 IBS: 0.15796822714732367
Fold 5 IBS: 0.19732972937931428
[I 2024-04-16 02:09:25,076] Trial 59 finished with value: 0.18913666520588948 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9752510141915198, 'min_weight_fraction_leaf': 0.00018268589057236773}. Best is trial 46 with value: 0.18593505895462542.

Fold 1 IBS: 0.207285461038795
Fold 2 IBS: 0.1927181173372502
Fold 3 IBS: 0.1875847073262801
Fold 4 IBS: 0.18626542533097468
Fold 5 IBS: 0.21021231166082874
[I 2024-04-16 02:09:31,971] Trial 60 finished with value: 0.19681320453882573 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 303, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9034006727918623, 'min_weight_fraction_leaf': 0.05252660219522337}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22222320857283578
Fold 2 IBS: 0.16627488261932677
Fold 3 IBS: 0.1907907801291295
Fold 4 IBS: 0.15665311269211
Fold 5 IBS: 0.19448240192170554
[I 2024-04-16 02:09:43,895] Trial 61 finished with value: 0.18608487718702152 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9365705541234135, 'min_weight_fraction_leaf': 0.031783148716693396}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21973293186989468
Fold 2 IBS: 0.16637936737733827
Fold 3 IBS: 0.19084524745309966
Fold 4 IBS: 0.15860503455855104
Fold 5 IBS: 0.1960405475543053
[I 2024-04-16 02:09:57,023] Trial 62 finished with value: 0.1863206257626378 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8532460059088829, 'min_weight_fraction_leaf': 0.02556027420253138}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21238622298854687
Fold 2 IBS: 0.16823306514375236
Fold 3 IBS: 0.19013144832783335
Fold 4 IBS: 0.16590277189776537
Fold 5 IBS: 0.1970812292594398
[I 2024-04-16 02:10:08,458] Trial 63 finished with value: 0.18674694752346754 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8424289412976247, 'min_weight_fraction_leaf': 0.035176521776568326}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21251914188212104
Fold 2 IBS: 0.16818501271313005
Fold 3 IBS: 0.19002328427487689
Fold 4 IBS: 0.1664131535050948
Fold 5 IBS: 0.19696216365791347
[I 2024-04-16 02:10:19,392] Trial 64 finished with value: 0.18682055120662727 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8468079509014251, 'min_weight_fraction_leaf': 0.056675259960032524}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21335380335193527
Fold 2 IBS: 0.16775952418293757
Fold 3 IBS: 0.18982870088983628
Fold 4 IBS: 0.1660804448667969
Fold 5 IBS: 0.19752793426971405
[I 2024-04-16 02:10:30,590] Trial 65 finished with value: 0.18691008151224403 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.033593279538543006}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2068314777271677
Fold 2 IBS: 0.1818823653044113
Fold 3 IBS: 0.1867008108426068
Fold 4 IBS: 0.17981107312892297
Fold 5 IBS: 0.20387830728635054
[I 2024-04-16 02:10:42,102] Trial 66 finished with value: 0.19182080685789185 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 353, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8472356401950124, 'min_weight_fraction_leaf': 0.0529366596136866}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20910483652280304
Fold 2 IBS: 0.17971015740109278
Fold 3 IBS: 0.18400026782476006
Fold 4 IBS: 0.17665742258292663
Fold 5 IBS: 0.20576920507641572
[I 2024-04-16 02:10:50,446] Trial 67 finished with value: 0.19104837788159965 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9444982451072708, 'min_weight_fraction_leaf': 0.03899677855324381}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20648940063369117
Fold 2 IBS: 0.19534295455434322
Fold 3 IBS: 0.188144538063623
Fold 4 IBS: 0.1949169470370693
Fold 5 IBS: 0.21053498455388758
[I 2024-04-16 02:10:56,794] Trial 68 finished with value: 0.19908576496852284 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7877895913453183, 'min_weight_fraction_leaf': 0.08102747544818781}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20394166174782688
Fold 2 IBS: 0.19677346569963913
Fold 3 IBS: 0.1891515065612692
Fold 4 IBS: 0.20045487618638197
Fold 5 IBS: 0.21575779723377045
[I 2024-04-16 02:11:04,409] Trial 69 finished with value: 0.20121586148577753 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 348, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8640937048774974, 'min_weight_fraction_leaf': 0.35844113234477204}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22147390576901926
Fold 2 IBS: 0.16878361070952955
Fold 3 IBS: 0.19289742131501394
Fold 4 IBS: 0.15642450822458037
Fold 5 IBS: 0.19573438642899904
[I 2024-04-16 02:11:18,080] Trial 70 finished with value: 0.18706276648942843 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9698512970131481, 'min_weight_fraction_leaf': 0.06206444655888782}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2124760152458227
Fold 2 IBS: 0.16848172025498606
Fold 3 IBS: 0.18992014324883777
Fold 4 IBS: 0.1661336629114953
Fold 5 IBS: 0.19710870332529623
[I 2024-04-16 02:11:29,572] Trial 71 finished with value: 0.1868240489972876 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 364, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8456035306116515, 'min_weight_fraction_leaf': 0.03120135154758281}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20761621244028333
Fold 2 IBS: 0.18073216921965327
Fold 3 IBS: 0.18760014895363192
Fold 4 IBS: 0.17874893912085807
Fold 5 IBS: 0.2039376815310608
[I 2024-04-16 02:11:41,526] Trial 72 finished with value: 0.19172703025309748 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8291126566575869, 'min_weight_fraction_leaf': 0.04256934859560442}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20211788261215158
Fold 2 IBS: 0.19294690613170354
Fold 3 IBS: 0.18803486936318167
Fold 4 IBS: 0.19413860771999508
Fold 5 IBS: 0.2102569188255651
[I 2024-04-16 02:11:50,848] Trial 73 finished with value: 0.19749903693051937 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.846356865587186, 'min_weight_fraction_leaf': 0.2814399755208377}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20536086673630327
Fold 2 IBS: 0.17349069261053238
Fold 3 IBS: 0.1911214435179867
Fold 4 IBS: 0.17057554919102758
Fold 5 IBS: 0.20023229606825985
[I 2024-04-16 02:12:02,129] Trial 74 finished with value: 0.18815616962482198 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7862604176864406, 'min_weight_fraction_leaf': 0.03192322260543996}. Best is trial 46 with value: 0.18593505895462542.

Fold 1 IBS: 0.22613938863893251
Fold 2 IBS: 0.17078566610790855
Fold 3 IBS: 0.1918060554350325
Fold 4 IBS: 0.1609525872259648
Fold 5 IBS: 0.19576638517676706
[I 2024-04-16 02:12:17,062] Trial 75 finished with value: 0.1890900165169211 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6854858143225422, 'min_weight_fraction_leaf': 0.014781978409836638}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20539145272671636
Fold 2 IBS: 0.19530699928990344
Fold 3 IBS: 0.18948528388235533
Fold 4 IBS: 0.19829570272263905
Fold 5 IBS: 0.21090398924576984
[I 2024-04-16 02:12:23,943] Trial 76 finished with value: 0.1998766855734768 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8663542569451897, 'min_weight_fraction_leaf': 0.06164950444687135}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20654354205828143
Fold 2 IBS: 0.17481441674697265
Fold 3 IBS: 0.190269325626355
Fold 4 IBS: 0.1769715113695994
Fold 5 IBS: 0.20037808458125742
[I 2024-04-16 02:12:33,880] Trial 77 finished with value: 0.18979537607649316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9399264729381039, 'min_weight_fraction_leaf': 0.10623157459313898}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2065942499274735
Fold 2 IBS: 0.19961139432967556
Fold 3 IBS: 0.1894644134677184
Fold 4 IBS: 0.20244453199859094
Fold 5 IBS: 0.21574470591763428
[I 2024-04-16 02:12:45,826] Trial 78 finished with value: 0.20277185912821852 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9999311602709532, 'min_weight_fraction_leaf': 0.4401997700779695}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20965660103993905
Fold 2 IBS: 0.21451072548088435
Fold 3 IBS: 0.2008395703355506
Fold 4 IBS: 0.21812402366212838
Fold 5 IBS: 0.2171583261557509
[I 2024-04-16 02:12:52,198] Trial 79 finished with value: 0.21205784933485067 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 359, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.744066131242477, 'min_weight_fraction_leaf': 0.0003126429952054685}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.19920711484535378
Fold 2 IBS: 0.1727542533999705
Fold 3 IBS: 0.198159865775465
Fold 4 IBS: 0.16954739238056218
Fold 5 IBS: 0.1930221685631568
[I 2024-04-16 02:12:54,483] Trial 80 finished with value: 0.18653815899290166 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 54, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8861080232545328, 'min_weight_fraction_leaf': 0.08125126316020383}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20442121006254585
Fold 2 IBS: 0.17137671300656207
Fold 3 IBS: 0.1975998202082012
Fold 4 IBS: 0.17524013402906885
Fold 5 IBS: 0.20426389074330129
[I 2024-04-16 02:12:56,691] Trial 81 finished with value: 0.19058035360993586 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 49, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8924014900526624, 'min_weight_fraction_leaf': 0.08895593181563541}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.203359031317457
Fold 2 IBS: 0.17507697438294065
Fold 3 IBS: 0.19434783445230705
Fold 4 IBS: 0.18058791137985974
Fold 5 IBS: 0.2012314104175464
[I 2024-04-16 02:12:58,926] Trial 82 finished with value: 0.19092063239002216 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 72, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8437598446832416, 'min_weight_fraction_leaf': 0.035990855986975975}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.19219159084396767
Fold 2 IBS: 0.17334766089986578
Fold 3 IBS: 0.23524594127404763
Fold 4 IBS: 0.19902956101664537
Fold 5 IBS: 0.18842503110492315
[I 2024-04-16 02:12:59,392] Trial 83 finished with value: 0.19764795702788993 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 2, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.922118731830056, 'min_weight_fraction_leaf': 0.0731545299433685}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20428511342436048
Fold 2 IBS: 0.1799896301725076
Fold 3 IBS: 0.19388724212464398
Fold 4 IBS: 0.16511001105053083
Fold 5 IBS: 0.19735867420569436
[I 2024-04-16 02:13:09,594] Trial 84 finished with value: 0.18812613419554744 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7909804561731724, 'min_weight_fraction_leaf': 0.11700828810083208}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2084578775348877
Fold 2 IBS: 0.19426457594186483
Fold 3 IBS: 0.18723611667351553
Fold 4 IBS: 0.19465436303183162
Fold 5 IBS: 0.20935163978665147
[I 2024-04-16 02:13:15,496] Trial 85 finished with value: 0.19879291459375023 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8719624179281165, 'min_weight_fraction_leaf': 0.051803457363457664}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22544247042865825
Fold 2 IBS: 0.1630256513468111
Fold 3 IBS: 0.19256909998854008
Fold 4 IBS: 0.15361651395715145
Fold 5 IBS: 0.19523852469599223
[I 2024-04-16 02:13:28,670] Trial 86 finished with value: 0.1859784520834306 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 315, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.946980497925672, 'min_weight_fraction_leaf': 0.029863072952735582}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.211698666811812
Fold 2 IBS: 0.1694289503007478
Fold 3 IBS: 0.19473357708600428
Fold 4 IBS: 0.16005631916809057
Fold 5 IBS: 0.199773102803706
[I 2024-04-16 02:13:34,035] Trial 87 finished with value: 0.18713812323407214 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 122, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9539230969817603, 'min_weight_fraction_leaf': 0.09652136904782926}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22020171827988244
Fold 2 IBS: 0.16926990713298445
Fold 3 IBS: 0.192284914228334
Fold 4 IBS: 0.15728200170563308
Fold 5 IBS: 0.19628056361797028
[I 2024-04-16 02:13:53,976] Trial 88 finished with value: 0.18706382099296087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 389, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9726994171981167, 'min_weight_fraction_leaf': 0.08008172538980439}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20869335287489973
Fold 2 IBS: 0.18877635099296655
Fold 3 IBS: 0.18545543987934543
Fold 4 IBS: 0.17645918166901373
Fold 5 IBS: 0.21071300836085144
[I 2024-04-16 02:13:58,844] Trial 89 finished with value: 0.19401946675541537 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 239, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9218401474143084, 'min_weight_fraction_leaf': 0.031265444034943385}. Best is trial 46 with value: 0.18593505895462542.

Fold 1 IBS: 0.20699759070252
Fold 2 IBS: 0.18410685277890454
Fold 3 IBS: 0.18353461706009355
Fold 4 IBS: 0.17619715129676206
Fold 5 IBS: 0.20499796617822919
[I 2024-04-16 02:14:06,486] Trial 90 finished with value: 0.1911668356033019 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8225840845043781, 'min_weight_fraction_leaf': 0.05864804834976011}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.217351763728157
Fold 2 IBS: 0.16945843188909548
Fold 3 IBS: 0.19034007843019582
Fold 4 IBS: 0.16244329382110362
Fold 5 IBS: 0.19781268762530857
[I 2024-04-16 02:14:17,369] Trial 91 finished with value: 0.1874812510987721 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8861509812631121, 'min_weight_fraction_leaf': 0.014224520657611844}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21696045553773013
Fold 2 IBS: 0.1704866822169904
Fold 3 IBS: 0.19085468141611783
Fold 4 IBS: 0.16103376128943614
Fold 5 IBS: 0.19876434589766828
[I 2024-04-16 02:14:28,518] Trial 92 finished with value: 0.18761998527158857 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9049528527068132, 'min_weight_fraction_leaf': 0.04231066950649405}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21196935165584188
Fold 2 IBS: 0.16722659903939105
Fold 3 IBS: 0.18987039220392843
Fold 4 IBS: 0.16499345338196442
Fold 5 IBS: 0.19764939088148178
[I 2024-04-16 02:14:38,537] Trial 93 finished with value: 0.1863418374325215 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9366747152403195, 'min_weight_fraction_leaf': 0.027802926132591547}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2059404253018163
Fold 2 IBS: 0.19380402974059494
Fold 3 IBS: 0.1876033430944384
Fold 4 IBS: 0.18405168741196726
Fold 5 IBS: 0.20458819720505517
[I 2024-04-16 02:14:45,913] Trial 94 finished with value: 0.1951975365507744 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9495699974520388, 'min_weight_fraction_leaf': 0.02871372240989487}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2094685066050624
Fold 2 IBS: 0.16927915291225965
Fold 3 IBS: 0.1924577643225916
Fold 4 IBS: 0.16602944533090672
Fold 5 IBS: 0.1957721996217021
[I 2024-04-16 02:14:54,973] Trial 95 finished with value: 0.18660141375850448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9791039731673459, 'min_weight_fraction_leaf': 0.04549233298877235}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20755395439739033
Fold 2 IBS: 0.1763119523991306
Fold 3 IBS: 0.19451944450840733
Fold 4 IBS: 0.1665181624649935
Fold 5 IBS: 0.1980829739408134
[I 2024-04-16 02:15:03,064] Trial 96 finished with value: 0.18859729754214705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 252, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9801531481203417, 'min_weight_fraction_leaf': 0.07059907684587055}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20778648807186673
Fold 2 IBS: 0.17421281284427612
Fold 3 IBS: 0.19712933488182183
Fold 4 IBS: 0.1640966839457895
Fold 5 IBS: 0.20039762446205991
[I 2024-04-16 02:15:12,390] Trial 97 finished with value: 0.1887245888411628 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9277927488483547, 'min_weight_fraction_leaf': 0.04722615213705901}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20725528002259883
Fold 2 IBS: 0.1985207548275814
Fold 3 IBS: 0.18902050026034625
Fold 4 IBS: 0.20014645511817541
Fold 5 IBS: 0.21107782417383592
[I 2024-04-16 02:15:17,837] Trial 98 finished with value: 0.20120416288050755 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 263, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9830419480731235, 'min_weight_fraction_leaf': 0.011263511832006995}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2017930721181439
Fold 2 IBS: 0.18583437036224545
Fold 3 IBS: 0.18941659088417465
Fold 4 IBS: 0.1839889537529638
Fold 5 IBS: 0.2037986821166232
[I 2024-04-16 02:15:24,960] Trial 99 finished with value: 0.1929663338468302 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4230786458254288, 'min_weight_fraction_leaf': 0.05722085597839154}. Best is trial 46 with value: 0.18593505895462542.


* Best trial for IBS:
 FrozenTrial(number=46, state=TrialState.COMPLETE, values=[0.18593505895462542], datetime_start=datetime.datetime(2024, 4, 16, 2, 7, 27, 215585), datetime_complete=datetime.datetime(2024, 4, 16, 2, 7, 37, 719275), params={'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.925572429448618, 'min_weight_fraction_leaf': 0.08676721083273177}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=46, value=None)


* Best Score for IBS:
 0.18593505895462542

In [62]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.867
train_ibs:  0.186

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=14, max_features='auto', max_leaf_nodes=18,
                   max_samples=0.7692755291164257, min_samples_leaf=2,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.006944921267975795,
                   n_estimators=182, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.616

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=3,
                   max_samples=0.925572429448618, min_samples_leaf=5,
                   min_samples_split=17,
                   min_weight_fraction_leaf=0.08676721083273177,
                   n_estimators=272, random_state=123, warm_start=True)

IBS: 0.214

In [66]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 02:15:27,926] A new study created in memory with name: no-name-d7796f30-7f05-4522-b6cf-e56e4645f809

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:16:21,495] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:16:45,775] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:17:12,725] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:18:18,434] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:18:41,727] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:18:48,211] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:19:22,173] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:19:30,925] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:19:32,140] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 02:21:19,121] Trial 9 finished with value: 0.7148887835576376 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7148887835576376.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 02:24:00,431] Trial 10 finished with value: 0.6739494649137633 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7148887835576376.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:57,349] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7148887835576376.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.795774647887324
[I 2024-04-16 02:29:27,758] Trial 12 finished with value: 0.7399996696599189 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:30:32,758] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:32:06,327] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:33:55,835] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:34:48,953] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:36:43,988] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:20,690] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:29,863] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:40:36,739] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 02:42:55,896] Trial 21 finished with value: 0.6762505605169181 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:45:01,096] Trial 22 finished with value: 0.7204995689745777 and parameters: {'subsample': 0.8956069884856214, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2154325997461391, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.38657871816113815, 'max_features': 'auto', 'min_impurity_decrease': 5.581115247824534e-07, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:46:46,911] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7743503496065262, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.31930849090648333, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9663328483036315, 'min_weight_fraction_leaf': 0.441052304834414, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:48:17,982] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8969825748215434, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21976013005558012, 'n_estimators': 340, 'criterion': 'squared_error', 'ccp_alpha': 0.785180332493211, 'min_weight_fraction_leaf': 0.2669492013977464, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:49:52,792] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8840318412875596, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.27382248438555523, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 2.0183033060186855, 'min_weight_fraction_leaf': 0.33643534713187806, 'max_features': 'auto', 'min_impurity_decrease': 5.889654690360788e-06, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:51:16,973] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7565765917190008, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.4300954216773497, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6678836557349488, 'min_weight_fraction_leaf': 0.06207030473994396, 'max_features': 1, 'min_impurity_decrease': 7.622421032390112e-07, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:20,532] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.322970332048742, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 5.9472530603001, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 7.551787280023211e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:59,199] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.5232204998663266, 'n_estimators': 326, 'criterion': 'squared_error', 'ccp_alpha': 4.188554251555486, 'min_weight_fraction_leaf': 0.43612805409636834, 'max_features': 0.1, 'min_impurity_decrease': 3.2161459286083955e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:54:07,626] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.32499045544570565, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 2.694991982922698, 'min_weight_fraction_leaf': 0.37973053029520576, 'max_features': 'log2', 'min_impurity_decrease': 1.983769791843576e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:54:49,134] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.1618733123667288, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.29835074442775955, 'max_features': 'auto', 'min_impurity_decrease': 3.855449012555335e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.744131455399061
[I 2024-04-16 02:57:07,963] Trial 31 finished with value: 0.7065394554594882 and parameters: {'subsample': 0.9458857893837966, 'learning_rate': 0.016420196712320707, 'dropout_rate': 0.2035906465216125, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.36089352993330637, 'max_features': 'auto', 'min_impurity_decrease': 4.318534340206297e-07, 'validation_fraction': 0.9595045281115817, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 02:59:31,717] Trial 32 finished with value: 0.7338746949532662 and parameters: {'subsample': 0.8638126341310897, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.22569622133720652, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.019083703384414813, 'min_weight_fraction_leaf': 0.351646089861356, 'max_features': 'auto', 'min_impurity_decrease': 1.0352347378444166e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:01:07,869] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8787207656433499, 'learning_rate': 0.025630755044466963, 'dropout_rate': 0.2619733844963128, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.3487071420031831, 'max_features': 'auto', 'min_impurity_decrease': 1.3326513674306949e-07, 'validation_fraction': 0.855139201184975, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:02:50,282] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7038358300021869, 'learning_rate': 0.016887189012329846, 'dropout_rate': 0.37019259462044524, 'n_estimators': 472, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8672217172879074, 'min_weight_fraction_leaf': 0.4224409922525036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0476374112133879e-07, 'validation_fraction': 0.9083519198432543, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:04:50,474] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.8534970531902419, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.29894506704091134, 'n_estimators': 429, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1524333738759642, 'min_weight_fraction_leaf': 0.16211724647631331, 'max_features': None, 'min_impurity_decrease': 8.53144724712845e-07, 'validation_fraction': 0.8123223724670843, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:02,944] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6682496627875864, 'learning_rate': 0.008294153240894362, 'dropout_rate': 0.14303426030295235, 'n_estimators': 312, 'criterion': 'squared_error', 'ccp_alpha': 0.48701662298918014, 'min_weight_fraction_leaf': 0.24844276308137436, 'max_features': 'auto', 'min_impurity_decrease': 1.0611200051423029e-05, 'validation_fraction': 0.6528075856343438, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:08:30,734] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7883126136564298, 'learning_rate': 0.03053220011751144, 'dropout_rate': 0.21915428448310503, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.198246212835568, 'min_weight_fraction_leaf': 0.2937098339627597, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.36353542989298265, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:09:12,992] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.022165709324438794, 'dropout_rate': 0.7673236646699829, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.4820963556426466, 'max_features': 'auto', 'min_impurity_decrease': 2.4453569806717e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:10:03,722] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.01319475669500773, 'dropout_rate': 0.4241449034531136, 'n_estimators': 345, 'criterion': 'squared_error', 'ccp_alpha': 2.0500352682881138, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:11:34,345] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5863013406787322, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.34949562340400464, 'n_estimators': 415, 'criterion': 'squared_error', 'ccp_alpha': 0.5271854997531392, 'min_weight_fraction_leaf': 0.415431900491221, 'max_features': 'auto', 'min_impurity_decrease': 2.2073664358493507e-07, 'validation_fraction': 0.7117322595758466, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 03:13:46,879] Trial 41 finished with value: 0.7277354181838703 and parameters: {'subsample': 0.9412170634308962, 'learning_rate': 0.016796866360623053, 'dropout_rate': 0.20081359178715893, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.01657550447328801, 'min_weight_fraction_leaf': 0.3505399688940837, 'max_features': 'auto', 'min_impurity_decrease': 9.905607188997223e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.744131455399061
[I 2024-04-16 03:15:45,718] Trial 42 finished with value: 0.7253442328364919 and parameters: {'subsample': 0.9171766984451564, 'learning_rate': 0.007773927115663986, 'dropout_rate': 0.2396004577204922, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.0083279040311737, 'min_weight_fraction_leaf': 0.36341209364761096, 'max_features': 'auto', 'min_impurity_decrease': 8.600111371198923e-07, 'validation_fraction': 0.9483049107677477, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:17:59,571] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.9108232635752186, 'learning_rate': 0.008003076263430912, 'dropout_rate': 0.16429624388711278, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 1.148366461475106, 'min_weight_fraction_leaf': 0.3638040744851804, 'max_features': 'auto', 'min_impurity_decrease': 8.346293016478022e-06, 'validation_fraction': 0.9399411414156236, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:19:59,301] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9989761273684051, 'learning_rate': 0.00565702820673318, 'dropout_rate': 0.23815552262133566, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 1.8660544568187023, 'min_weight_fraction_leaf': 0.32701048366833557, 'max_features': 'auto', 'min_impurity_decrease': 9.164976275637937e-07, 'validation_fraction': 0.8820072870943625, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:22:06,960] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8626347512538699, 'learning_rate': 0.020184095116582045, 'dropout_rate': 0.1399746504160479, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 6.649876339233933, 'min_weight_fraction_leaf': 0.41535848381884183, 'max_features': 0.1, 'min_impurity_decrease': 1.758780255854688e-05, 'validation_fraction': 0.965992193119439, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:22:22,785] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.9600435779641728, 'learning_rate': 0.030307000616944805, 'dropout_rate': 0.9694253886674298, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.5293904611088607, 'min_weight_fraction_leaf': 0.3707204535290808, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013554285626863527, 'validation_fraction': 0.8433619277880944, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 20}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6502347417840375
[I 2024-04-16 03:23:04,798] Trial 47 finished with value: 0.6837407748517323 and parameters: {'subsample': 0.8232452491390325, 'learning_rate': 0.0010864400202530565, 'dropout_rate': 0.19509781722453806, 'n_estimators': 246, 'criterion': 'squared_error', 'ccp_alpha': 0.09577969393946249, 'min_weight_fraction_leaf': 0.4612510836743603, 'max_features': 'auto', 'min_impurity_decrease': 2.290718019355971e-06, 'validation_fraction': 0.9987850848994776, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:23:05,669] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9205853887854631, 'learning_rate': 0.015063288166862612, 'dropout_rate': 0.6996455537664029, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 1.234909174722316, 'min_weight_fraction_leaf': 0.3468414050166919, 'max_features': None, 'min_impurity_decrease': 1.1980803500659586e-06, 'validation_fraction': 0.789476910449492, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:23:28,678] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.8584821913791967, 'learning_rate': 0.04184187217123891, 'dropout_rate': 0.5876831898987365, 'n_estimators': 279, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3158222061342544, 'min_weight_fraction_leaf': 0.31138294902869135, 'max_features': 'log2', 'min_impurity_decrease': 5.926066318715653e-07, 'validation_fraction': 0.9027576817684192, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:25:22,993] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.970830915699766, 'learning_rate': 0.008517040180540838, 'dropout_rate': 0.11630369695875253, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.6764289629319513, 'min_weight_fraction_leaf': 0.22751653971684832, 'max_features': 'auto', 'min_impurity_decrease': 4.971000534416321e-06, 'validation_fraction': 0.9492160383375527, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 03:27:01,925] Trial 51 finished with value: 0.7251886212920475 and parameters: {'subsample': 0.7962239992639443, 'learning_rate': 0.022072089207892297, 'dropout_rate': 0.24568799595260493, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.012353393991434636, 'min_weight_fraction_leaf': 0.3966155265905691, 'max_features': 'auto', 'min_impurity_decrease': 2.1936100454733836e-07, 'validation_fraction': 0.8455432081663881, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 03:28:53,102] Trial 52 finished with value: 0.7305458194801607 and parameters: {'subsample': 0.8040225491688882, 'learning_rate': 0.022140218438295653, 'dropout_rate': 0.24737218107101291, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.03660198360294675, 'min_weight_fraction_leaf': 0.3884889792121647, 'max_features': 'auto', 'min_impurity_decrease': 2.2796958064199354e-07, 'validation_fraction': 0.854324003727559, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:30:56,801] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.7871371108234366, 'learning_rate': 0.023042656989511353, 'dropout_rate': 0.25313788059133613, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.9311410844850458, 'min_weight_fraction_leaf': 0.4094624681121705, 'max_features': 'auto', 'min_impurity_decrease': 1.770926710327986e-07, 'validation_fraction': 0.8394982011711836, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:31:31,809] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8216003600781934, 'learning_rate': 0.018771949946189165, 'dropout_rate': 0.8506831202560587, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.48953881004914557, 'min_weight_fraction_leaf': 0.2730613968304923, 'max_features': 'auto', 'min_impurity_decrease': 2.4544669130589735e-07, 'validation_fraction': 0.8744022302982001, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:33:14,551] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9137725083286111, 'learning_rate': 0.03334997201384794, 'dropout_rate': 0.29231716916379974, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.400772188710969, 'min_weight_fraction_leaf': 0.4998387701732778, 'max_features': 'auto', 'min_impurity_decrease': 1.1484691000127718e-07, 'validation_fraction': 0.7499576977802935, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:35:13,195] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.7301701043140242, 'learning_rate': 0.07563239727117915, 'dropout_rate': 0.18285747474549977, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 1.3142104786505762, 'min_weight_fraction_leaf': 0.398818501696366, 'max_features': 'auto', 'min_impurity_decrease': 1.37107675515093e-06, 'validation_fraction': 0.9769184491065465, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 03:37:00,846] Trial 57 finished with value: 0.7130737733674322 and parameters: {'subsample': 0.8447974448466777, 'learning_rate': 0.026300674571633445, 'dropout_rate': 0.3933140501049528, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.0019231547695728619, 'min_weight_fraction_leaf': 0.4497752574786321, 'max_features': 'auto', 'min_impurity_decrease': 3.0397473583824277e-07, 'validation_fraction': 0.9043607687797511, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:38:12,427] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8001260306807542, 'learning_rate': 0.04035739114123531, 'dropout_rate': 0.34309202286041174, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 7.96887264775278, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 1, 'min_impurity_decrease': 2.548222090790957e-06, 'validation_fraction': 0.8368053032017708, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:39:57,367] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9386320465614315, 'learning_rate': 0.0046218127846011405, 'dropout_rate': 0.23726258582704846, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9495956426269169, 'min_weight_fraction_leaf': 0.3507587728220414, 'max_features': 0.1, 'min_impurity_decrease': 5.327348003678687e-07, 'validation_fraction': 0.7937489212794213, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 18}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:41:14,409] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.7457764864101614, 'learning_rate': 0.013913019847381093, 'dropout_rate': 0.2802313234402579, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 2.8029484350487133, 'min_weight_fraction_leaf': 0.2614148759574215, 'max_features': 'auto', 'min_impurity_decrease': 1.9564560597564265e-07, 'validation_fraction': 0.8811459545611348, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:43:12,830] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8807242730119922, 'learning_rate': 0.011237316919845534, 'dropout_rate': 0.21913936290206518, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.4933072636379361, 'min_weight_fraction_leaf': 0.3875891410631565, 'max_features': 'auto', 'min_impurity_decrease': 9.882732394296688e-07, 'validation_fraction': 0.9372322610150985, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 03:45:25,259] Trial 62 finished with value: 0.7295264107604176 and parameters: {'subsample': 0.9069044656671411, 'learning_rate': 0.01643486305639612, 'dropout_rate': 0.16523918422475894, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.022435687471224874, 'min_weight_fraction_leaf': 0.37553845203078473, 'max_features': 'auto', 'min_impurity_decrease': 5.889332196421936e-07, 'validation_fraction': 0.9275594296798731, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:47:43,167] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.9801560241682516, 'learning_rate': 0.02043806262474091, 'dropout_rate': 0.1375051834367063, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.7183706920220042, 'min_weight_fraction_leaf': 0.3699000085884939, 'max_features': 'auto', 'min_impurity_decrease': 3.9039071549423344e-07, 'validation_fraction': 0.9934903904178206, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:49:28,378] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9277442486522394, 'learning_rate': 0.01565980187000121, 'dropout_rate': 0.10698873156508726, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 0.3045978164453682, 'min_weight_fraction_leaf': 0.33394184808274385, 'max_features': 'auto', 'min_impurity_decrease': 1.4496904143040433e-06, 'validation_fraction': 0.919872382223042, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 03:51:24,018] Trial 65 finished with value: 0.669905005917179 and parameters: {'subsample': 0.8389348527747851, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.1831917670580087, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.002774117008967604, 'min_weight_fraction_leaf': 0.30504352196445944, 'max_features': 'log2', 'min_impurity_decrease': 7.298411535762544e-07, 'validation_fraction': 0.9673516401919608, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:53:15,934] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8803601425460227, 'learning_rate': 0.02454986182406897, 'dropout_rate': 0.2457020680116681, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 1.0543834057431296, 'min_weight_fraction_leaf': 0.39762979335749954, 'max_features': 'auto', 'min_impurity_decrease': 1.062308544034983e-07, 'validation_fraction': 0.8856930810090413, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:54:48,048] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.9039131398456093, 'learning_rate': 0.005393688405155129, 'dropout_rate': 0.30991266215324687, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.7765508574580127, 'min_weight_fraction_leaf': 0.4319443057218696, 'max_features': 'auto', 'min_impurity_decrease': 0.04710428475886704, 'validation_fraction': 0.7743163230527812, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:56:39,432] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6800178109385019, 'learning_rate': 0.02933409598200374, 'dropout_rate': 0.17928084108359857, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.6074461301183274, 'min_weight_fraction_leaf': 0.4780015649862437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.013697139277504513, 'validation_fraction': 0.8638940835250288, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:57:54,406] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7692672682208916, 'learning_rate': 0.01769416030307426, 'dropout_rate': 0.27876204748733485, 'n_estimators': 374, 'criterion': 'friedman_mse', 'ccp_alpha': 0.286953040189292, 'min_weight_fraction_leaf': 0.2913187893803262, 'max_features': 'auto', 'min_impurity_decrease': 2.1481238791541268e-07, 'validation_fraction': 0.9566923161441689, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:59:29,572] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.8100461387280435, 'learning_rate': 0.009720778256433736, 'dropout_rate': 0.1582247006910296, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.32462660328254567, 'max_features': 'auto', 'min_impurity_decrease': 4.620887402185137e-07, 'validation_fraction': 0.8233170212984697, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:01:23,190] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.8895178823933076, 'learning_rate': 0.0141589777741273, 'dropout_rate': 0.19713266114650715, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.26273325094178557, 'min_weight_fraction_leaf': 0.3798826712848097, 'max_features': 'auto', 'min_impurity_decrease': 5.75677082319795e-07, 'validation_fraction': 0.9240897742855856, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 04:03:05,437] Trial 72 finished with value: 0.7362433481107317 and parameters: {'subsample': 0.8642777625557101, 'learning_rate': 0.02186591972980013, 'dropout_rate': 0.22937371721341443, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.004815838793413725, 'min_weight_fraction_leaf': 0.35789966830713343, 'max_features': 'auto', 'min_impurity_decrease': 1.5921848241604391e-07, 'validation_fraction': 0.9292016960714522, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:03:27,083] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8636670131007999, 'learning_rate': 0.03250475281963551, 'dropout_rate': 0.22773314504043318, 'n_estimators': 178, 'criterion': 'squared_error', 'ccp_alpha': 0.7340529855138669, 'min_weight_fraction_leaf': 0.35875610620029763, 'max_features': 'auto', 'min_impurity_decrease': 1.625419403219883e-07, 'validation_fraction': 0.9704103462569147, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:05:11,448] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.9442631157989567, 'learning_rate': 0.021290745338913994, 'dropout_rate': 0.2680216449479869, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.6201513737559716, 'min_weight_fraction_leaf': 0.335188908651544, 'max_features': 'auto', 'min_impurity_decrease': 3.513254689525364e-07, 'validation_fraction': 0.18271784653855216, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:06:29,351] Trial 75 finished with value: 0.7260941507877564 and parameters: {'subsample': 0.8321594525103285, 'learning_rate': 0.05118727647103342, 'dropout_rate': 0.32340656921315775, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.008839136595664831, 'min_weight_fraction_leaf': 0.3770321771415034, 'max_features': 'auto', 'min_impurity_decrease': 1.6809052999382329e-07, 'validation_fraction': 0.9136795904227917, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:07:49,408] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.8394003484184053, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.33024491820993, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 0.3152854263053759, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 0.0004591155005280019, 'validation_fraction': 0.9138168401699509, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:09:01,879] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9753940115175919, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.2959323288697957, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.283213839796126, 'min_weight_fraction_leaf': 0.1508392399442322, 'max_features': 1, 'min_impurity_decrease': 1.0435805071795419e-07, 'validation_fraction': 0.9927089836547902, 'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 11}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:10:24,587] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.9259347360875612, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.3915655480454143, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.9809253886223749, 'min_weight_fraction_leaf': 0.3733741757380721, 'max_features': 'auto', 'min_impurity_decrease': 1.5055551845496619e-07, 'validation_fraction': 0.9291562047924866, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:12:08,356] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8989541367720106, 'learning_rate': 0.06143531661227892, 'dropout_rate': 0.12785764143532674, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.6703560127430094, 'min_weight_fraction_leaf': 0.35485369908449244, 'max_features': 0.1, 'min_impurity_decrease': 8.782239961636543e-07, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:13:29,383] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04966610548933414, 'dropout_rate': 0.1648630717352459, 'n_estimators': 431, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.4045734888864501, 'max_features': 'auto', 'min_impurity_decrease': 3.191262319869447e-07, 'validation_fraction': 0.8923340974201528, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6029411764705882
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 04:15:01,338] Trial 81 finished with value: 0.6744664286969589 and parameters: {'subsample': 0.8204753653660055, 'learning_rate': 0.04319851444329214, 'dropout_rate': 0.2121998392139111, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.02534349958176617, 'min_weight_fraction_leaf': 0.19125171416337036, 'max_features': 'auto', 'min_impurity_decrease': 2.565945077766206e-07, 'validation_fraction': 0.9541426339705571, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:16:37,078] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.8644226713292206, 'learning_rate': 0.018537386015478913, 'dropout_rate': 0.25663963968872483, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.28961979264370374, 'min_weight_fraction_leaf': 0.42326153107157766, 'max_features': 'auto', 'min_impurity_decrease': 1.675412775388128e-07, 'validation_fraction': 0.8621305841831005, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:17:32,518] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7358074146930308, 'learning_rate': 0.025706300160214, 'dropout_rate': 0.22968230522988387, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.49700068111119755, 'min_weight_fraction_leaf': 0.38468084627630217, 'max_features': 'auto', 'min_impurity_decrease': 4.1067211462896935e-07, 'validation_fraction': 0.8206125715100036, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6629464285714286
Fold 3 C-index: 0.6936274509803921
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.687793427230047
[I 2024-04-16 04:17:36,919] Trial 84 finished with value: 0.6801102414539131 and parameters: {'subsample': 0.42529357448835425, 'learning_rate': 0.02762233475108975, 'dropout_rate': 0.20280079758879627, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 0.20868220613127783, 'min_weight_fraction_leaf': 0.3160345364912664, 'max_features': 'auto', 'min_impurity_decrease': 6.38504114422443e-07, 'validation_fraction': 0.7210112012398474, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 04:18:45,050] Trial 85 finished with value: 0.7302130922224155 and parameters: {'subsample': 0.7970928489554175, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.3033612838692909, 'n_estimators': 397, 'criterion': 'squared_error', 'ccp_alpha': 0.011240889643051085, 'min_weight_fraction_leaf': 0.34141609928683797, 'max_features': 'auto', 'min_impurity_decrease': 1.9571285619395883e-06, 'validation_fraction': 0.6711551666986062, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:20:02,809] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.7801819526684379, 'learning_rate': 0.04588676944797367, 'dropout_rate': 0.357396641130168, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.4506190457160326, 'min_weight_fraction_leaf': 0.34072181196437984, 'max_features': 'log2', 'min_impurity_decrease': 1.8472872213713208e-06, 'validation_fraction': 0.6189549502198839, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:21:01,138] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.6437268568076402, 'learning_rate': 0.06917862456904772, 'dropout_rate': 0.30671889534310337, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 1.0467343938198086, 'min_weight_fraction_leaf': 0.36233395118072964, 'max_features': 'sqrt', 'min_impurity_decrease': 5.495613028050001e-06, 'validation_fraction': 0.9483334737685223, 'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:22:17,054] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.962719081727985, 'learning_rate': 0.03821268022738647, 'dropout_rate': 0.4180635358371704, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7258523809610303, 'min_weight_fraction_leaf': 0.3460523584882933, 'max_features': 'auto', 'min_impurity_decrease': 3.0700401682957075e-06, 'validation_fraction': 0.6833916423614368, 'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:23:00,986] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.8357489060156716, 'learning_rate': 0.0484285379083209, 'dropout_rate': 0.27310144029573485, 'n_estimators': 310, 'criterion': 'squared_error', 'ccp_alpha': 2.209004069839297, 'min_weight_fraction_leaf': 0.28633856037020633, 'max_features': 'auto', 'min_impurity_decrease': 1.012846054245825e-06, 'validation_fraction': 0.9999095319465745, 'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:23:50,160] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.8746630223915809, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.3306578048242935, 'n_estimators': 330, 'criterion': 'squared_error', 'ccp_alpha': 4.633272020962325, 'min_weight_fraction_leaf': 0.3779481569897128, 'max_features': None, 'min_impurity_decrease': 8.00355252800393e-05, 'validation_fraction': 0.9050973139966927, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 8}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 04:25:04,987] Trial 91 finished with value: 0.7157332482337333 and parameters: {'subsample': 0.7933548327638641, 'learning_rate': 0.003312019603128164, 'dropout_rate': 0.2507679538048139, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.03780967061735356, 'min_weight_fraction_leaf': 0.39772958841171435, 'max_features': 'auto', 'min_impurity_decrease': 2.499487061211126e-07, 'validation_fraction': 0.8580115400818135, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:26:34,363] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.7561961860443563, 'learning_rate': 0.023527180352486913, 'dropout_rate': 0.16479361613280366, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.43394239821505587, 'min_weight_fraction_leaf': 0.42562332923735957, 'max_features': 'auto', 'min_impurity_decrease': 1.6938318820779942e-06, 'validation_fraction': 0.9701449564634904, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:27:33,095] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8059949627822843, 'learning_rate': 0.01234024470004173, 'dropout_rate': 0.29267203803789943, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.20319330870280422, 'min_weight_fraction_leaf': 0.365699391779537, 'max_features': 'auto', 'min_impurity_decrease': 1.6653350619746936e-07, 'validation_fraction': 0.9355041944373461, 'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:28:27,376] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.6999082025869978, 'learning_rate': 0.017219979911559023, 'dropout_rate': 0.373035235690205, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 6.420837118226172, 'min_weight_fraction_leaf': 0.40883838967583214, 'max_features': 'auto', 'min_impurity_decrease': 4.6709965065070267e-07, 'validation_fraction': 0.887860002388832, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:29:54,624] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5105271208530126, 'learning_rate': 0.007748724766312231, 'dropout_rate': 0.23543004659865058, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.5595582823457022, 'min_weight_fraction_leaf': 0.2213775810637544, 'max_features': 'auto', 'min_impurity_decrease': 1.0829272877301445e-06, 'validation_fraction': 0.6772676512149463, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7769953051643192
[I 2024-04-16 04:31:25,463] Trial 96 finished with value: 0.7256628426099365 and parameters: {'subsample': 0.9098985521833942, 'learning_rate': 0.052234132276152874, 'dropout_rate': 0.21111234228536274, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.03142354075915592, 'min_weight_fraction_leaf': 0.3283302077126804, 'max_features': 'auto', 'min_impurity_decrease': 1.3235311220249993e-07, 'validation_fraction': 0.8042400059038284, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:32:33,992] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.901549774839904, 'learning_rate': 0.0518850036895118, 'dropout_rate': 0.49263846952113033, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8327347493373075, 'min_weight_fraction_leaf': 0.30244388210473977, 'max_features': 'auto', 'min_impurity_decrease': 1.4238172259761717e-07, 'validation_fraction': 0.7814800742737378, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:34:06,705] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.946617594291913, 'learning_rate': 0.06132823148390858, 'dropout_rate': 0.20690053299878008, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.25682935609263036, 'min_weight_fraction_leaf': 0.32255361828136364, 'max_features': 1, 'min_impurity_decrease': 3.172670658418841e-07, 'validation_fraction': 0.7982829558993232, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.5654008438818565

[I 2024-04-16 04:35:42,932] A new study created in memory with name: no-name-b8837bf1-5a65-4876-b167-24715598e979

Fold 5 C-index: 0.7629107981220657
[I 2024-04-16 04:35:42,881] Trial 99 finished with value: 0.6977749461751669 and parameters: {'subsample': 0.998129126621856, 'learning_rate': 0.00967252777219979, 'dropout_rate': 0.18568433870901738, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004394117663473222, 'min_weight_fraction_leaf': 0.3369308574386013, 'max_features': 'auto', 'min_impurity_decrease': 8.018566601368315e-06, 'validation_fraction': 0.7574519027338645, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.7399996696599189], datetime_start=datetime.datetime(2024, 4, 16, 2, 26, 57, 359162), datetime_complete=datetime.datetime(2024, 4, 16, 2, 29, 27, 757082), params={'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=12, value=None)


* Best Score for C-index:
 0.7399996696599189

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:36:12,358] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:36:24,919] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:36:39,687] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:37:19,875] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:37:33,739] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:37:37,505] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:37:59,246] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:38:05,496] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:38:06,361] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.2128537475974278
Fold 2 IBS: 0.22024902992742937
Fold 3 IBS: 0.2036757896357088
Fold 4 IBS: 0.22379989362838207
Fold 5 IBS: 0.21720663584018296
[I 2024-04-16 04:39:15,127] Trial 9 finished with value: 0.2155570193258262 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21361208429589837
Fold 2 IBS: 0.22119337423142857
Fold 3 IBS: 0.20422163542183314
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21784773839776864
[I 2024-04-16 04:40:58,305] Trial 10 finished with value: 0.21628765863973537 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:42:52,960] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.2138342515802909
Fold 2 IBS: 0.22140255954991353
Fold 3 IBS: 0.20446094529787798
Fold 4 IBS: 0.22465623055238298
Fold 5 IBS: 0.2179885030861713
[I 2024-04-16 04:44:31,645] Trial 12 finished with value: 0.2164684980133273 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:45:11,351] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:46:39,540] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:47:35,371] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:48:08,308] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:49:21,760] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:49:58,842] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:50:06,753] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:51:19,680] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21368081158317526
Fold 2 IBS: 0.22153122053697344
Fold 3 IBS: 0.20438589708295674
Fold 4 IBS: 0.22463565682317985
Fold 5 IBS: 0.21798450581810203
[I 2024-04-16 04:52:37,363] Trial 21 finished with value: 0.21644361836887746 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21302790139502722
Fold 2 IBS: 0.2203859020701612

Fold 3 IBS: 0.2039525932207316
Fold 4 IBS: 0.22401636959265878
Fold 5 IBS: 0.21723302548509774
[I 2024-04-16 04:54:06,912] Trial 22 finished with value: 0.2157231583527353 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:55:26,153] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:56:18,491] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:57:03,287] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:57:45,413] Trial 26 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:57:50,584] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:58:04,736] Trial 28 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:58:54,678] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:00:16,599] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21326862978576686
Fold 2 IBS: 0.2210813893462159
Fold 3 IBS: 0.20416936232206076
Fold 4 IBS: 0.224409146213765
Fold 5 IBS: 0.2174662620955696
[I 2024-04-16 05:01:38,463] Trial 31 finished with value: 0.21607895795267562 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21265462725075449
Fold 2 IBS: 0.2204257334985705
Fold 3 IBS: 0.20397494518039208
Fold 4 IBS: 0.22436470362658575
Fold 5 IBS: 0.2171702564147175
[I 2024-04-16 05:03:00,850] Trial 32 finished with value: 0.21571805319420406 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:03:52,053] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:04:41,362] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:04:57,668] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:05:58,580] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:06:05,118] Trial 37 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:06:30,130] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:07:05,231] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:07:51,453] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21343972924860297
Fold 2 IBS: 0.22040213418324436
Fold 3 IBS: 0.20422553455737508
Fold 4 IBS: 0.223054763444453
Fold 5 IBS: 0.217277332164069
[I 2024-04-16 05:09:07,975] Trial 41 finished with value: 0.21567989871954887 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21319951383922744
Fold 2 IBS: 0.2203384834690888
Fold 3 IBS: 0.20412438325013108
Fold 4 IBS: 0.22368658846556563
Fold 5 IBS: 0.21713298280303828
[I 2024-04-16 05:10:24,543] Trial 42 finished with value: 0.21569639036541025 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:11:59,830] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:13:19,527] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:13:42,966] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21367772856775613
Fold 2 IBS: 0.22135025645802206
Fold 3 IBS: 0.20434795802913167
Fold 4 IBS: 0.22452690894235955
Fold 5 IBS: 0.21798015093325962
[I 2024-04-16 05:14:45,014] Trial 46 finished with value: 0.2163766005861058 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:15:16,387] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:15:16,748] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:15:17,045] Trial 49 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 05:15:53,722] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.2131461429175361
Fold 2 IBS: 0.2208495886734572
Fold 3 IBS: 0.20421136524084818
Fold 4 IBS: 0.22451211402844548
Fold 5 IBS: 0.21752021771340435
[I 2024-04-16 05:16:55,534] Trial 51 finished with value: 0.21604788571473826 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.213580508502216
Fold 2 IBS: 0.22096543904993846
Fold 3 IBS: 0.20426426298705622
Fold 4 IBS: 0.22452441731877534
Fold 5 IBS: 0.21764616670366058
[I 2024-04-16 05:17:45,224] Trial 52 finished with value: 0.21619615891232935 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:18:25,797] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:19:05,281] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:19:33,533] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:19:53,950] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:20:17,282] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:20:43,162] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:21:03,692] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:21:20,879] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:21:58,069] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9319260511303565, 'learning_rate': 0.006981217524957076, 'dropout_rate': 0.2694290399109642, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.2266262530125842, 'min_weight_fraction_leaf': 0.2262208916321135, 'max_features': 'auto', 'min_impurity_decrease': 6.393438969585487e-06, 'validation_fraction': 0.968342815685117, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21261827944826023
Fold 2 IBS: 0.21980190055259302
Fold 3 IBS: 0.20384635335083123
Fold 4 IBS: 0.22428599240586905
Fold 5 IBS: 0.21675480287088003
[I 2024-04-16 05:22:31,057] Trial 62 finished with value: 0.21546146572568672 and parameters: {'subsample': 0.9972198040262032, 'learning_rate': 0.008659221224759001, 'dropout_rate': 0.18470289302046516, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.022476866600004634, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 3.745982455886227e-06, 'validation_fraction': 0.9275220875852723, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:22:41,397] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9899309662352432, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:23:09,678] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9658825052862857, 'learning_rate': 0.010845363858236992, 'dropout_rate': 0.13571080979315037, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.3681339382709387, 'min_weight_fraction_leaf': 0.15534331606940482, 'max_features': 'log2', 'min_impurity_decrease': 8.60046486145071e-06, 'validation_fraction': 0.9205869937759958, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21299720012323184
Fold 2 IBS: 0.21967979851217223
Fold 3 IBS: 0.2038040121811597
Fold 4 IBS: 0.2242157275656328
Fold 5 IBS: 0.21668589828394494
[I 2024-04-16 05:23:41,903] Trial 65 finished with value: 0.21547652733322833 and parameters: {'subsample': 0.9661607708539444, 'learning_rate': 0.008868026173365113, 'dropout_rate': 0.17835638219464384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.002725826040487267, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:24:04,313] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9998769833869746, 'learning_rate': 0.003967598379054899, 'dropout_rate': 0.17654958266634313, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.8981368148483696, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'auto', 'min_impurity_decrease': 7.140027633149786e-05, 'validation_fraction': 0.6362228335648394, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:24:23,164] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8945386029541793, 'learning_rate': 0.01494075298406419, 'dropout_rate': 0.209071801122636, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1837261226658302, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5552258602982892e-05, 'validation_fraction': 0.7259068897097584, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-16 05:24:55,693] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.843502945752621, 'learning_rate': 0.02075147594960792, 'dropout_rate': 0.16252263519114862, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.057901034918407895, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.6846740503948187, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:25:18,121] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.01037165919107231, 'dropout_rate': 0.19004731427008625, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.34303232955200197, 'min_weight_fraction_leaf': 0.3579731281150166, 'max_features': 'auto', 'min_impurity_decrease': 0.00014344627836102727, 'validation_fraction': 0.7769648880006281, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:25:43,596] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6499145948799803, 'learning_rate': 0.008667614598934925, 'dropout_rate': 0.2379061541841675, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.6762661413605899, 'min_weight_fraction_leaf': 0.2053436289550881, 'max_features': None, 'min_impurity_decrease': 2.7112245092072337e-05, 'validation_fraction': 0.5272974695233066, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21365420908986738
Fold 2 IBS: 0.2209721070161024
Fold 3 IBS: 0.2043021502572646
Fold 4 IBS: 0.22456249898531583
Fold 5 IBS: 0.2176782657279134
[I 2024-04-16 05:26:11,819] Trial 71 finished with value: 0.21623384621529276 and parameters: {'subsample': 0.9554665295189709, 'learning_rate': 0.004772306432110387, 'dropout_rate': 0.30773217080297294, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.019537053946387287, 'max_features': 'auto', 'min_impurity_decrease': 3.603782675882374e-06, 'validation_fraction': 0.8818766703918308, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.2103768252217124
Fold 2 IBS: 0.21850284034383607
Fold 3 IBS: 0.20294546345453016
Fold 4 IBS: 0.22323961452248642
Fold 5 IBS: 0.2153595452182885
[I 2024-04-16 05:26:41,496] Trial 72 finished with value: 0.2140848577521707 and parameters: {'subsample': 0.9233416329717381, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.12211037740366137, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004815836437462028, 'min_weight_fraction_leaf': 0.2452551786385524, 'max_features': 'auto', 'min_impurity_decrease': 1.5300590715832769e-06, 'validation_fraction': 0.974284387349558, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.2140848577521707.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:26:47,707] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.916509573532907, 'learning_rate': 0.01366625897147706, 'dropout_rate': 0.10211108319082117, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.35137810274202946, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'auto', 'min_impurity_decrease': 5.253021283264037e-07, 'validation_fraction': 0.9862680394354211, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 72 with value: 0.2140848577521707.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:27:12,598] Trial 74 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.98093897605085, 'learning_rate': 0.01711555655405715, 'dropout_rate': 0.13243922080536136, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.7083433911466146, 'min_weight_fraction_leaf': 0.24361782259873882, 'max_features': 'auto', 'min_impurity_decrease': 1.0928587879200682e-06, 'validation_fraction': 0.8125486143795312, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 72 with value: 0.2140848577521707.
Fold 1 IBS: 0.20177055563075577
Fold 2 IBS: 0.209535009765422
Fold 3 IBS: 0.196660791504323
Fold 4 IBS: 0.21686059369436475
Fold 5 IBS: 0.20762944158941038
[I 2024-04-16 05:27:34,745] Trial 75 finished with value: 0.2064912784368552 and parameters: {'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:27:53,583] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8788463737285552, 'learning_rate': 0.0916936247639216, 'dropout_rate': 0.16070017323462005, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.32254979446846543, 'max_features': 'auto', 'min_impurity_decrease': 1.6370541352867706e-06, 'validation_fraction': 0.7514206020918085, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268

Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:28:10,425] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9277566139958084, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.19520203577374073, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.27180012569333806, 'max_features': 1, 'min_impurity_decrease': 6.5181445049333515e-06, 'validation_fraction': 0.6076036057733984, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 05:28:24,310] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9641397901643791, 'learning_rate': 0.08426314282635561, 'dropout_rate': 0.1247743198402547, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 0.30089158245836867, 'min_weight_fraction_leaf': 0.28488038648314357, 'max_features': 'auto', 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.6689444692488747, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:28:39,673] Trial 79 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9058167204807939, 'learning_rate': 0.07449175092046981, 'dropout_rate': 0.2195581561902862, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 0.5632393945180738, 'min_weight_fraction_leaf': 0.3103740193108716, 'max_features': 0.1, 'min_impurity_decrease': 9.7137748926677e-06, 'validation_fraction': 0.849557227325558, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:28:57,062] Trial 80 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04033855340571721, 'dropout_rate': 0.17133798886674423, 'n_estimators': 423, 'criterion': 'friedman_mse', 'ccp_alpha': 1.024900175040304, 'min_weight_fraction_leaf': 0.2650334083023682, 'max_features': 'auto', 'min_impurity_decrease': 5.230611844746115e-06, 'validation_fraction': 0.7958053728402417, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.213006975409325
Fold 2 IBS: 0.22058981150149234
Fold 3 IBS: 0.2038292466524223
Fold 4 IBS: 0.2241672122172358
Fold 5 IBS: 0.2173545648278883
[I 2024-04-16 05:29:21,912] Trial 81 finished with value: 0.21578956212167277 and parameters: {'subsample': 0.7840956251329788, 'learning_rate': 0.008693963960519305, 'dropout_rate': 0.24759233856802285, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2888444623370858, 'max_features': 'auto', 'min_impurity_decrease': 1.9009142355302227e-06, 'validation_fraction': 0.9214054941984873, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:29:53,279] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8257398205366486, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.1461667964581519, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.1946035339480217, 'max_features': 'auto', 'min_impurity_decrease': 2.6687516010357667e-06, 'validation_fraction': 0.8952878298653584, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:30:10,703] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.981472556868282, 'learning_rate': 0.0030220411792046976, 'dropout_rate': 0.1911593145934642, 'n_estimators': 375, 'criterion': 'squared_error', 'ccp_alpha': 0.8179280838957377, 'min_weight_fraction_leaf': 0.48985212977722026, 'max_features': 'auto', 'min_impurity_decrease': 3.455195546201241e-05, 'validation_fraction': 0.938557669326888, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:30:28,554] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8647540438080621, 'learning_rate': 0.08343776887241991, 'dropout_rate': 0.22709419020503996, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5507721391645963, 'min_weight_fraction_leaf': 0.24659978585785525, 'max_features': 'log2', 'min_impurity_decrease': 1.5548907893179703e-07, 'validation_fraction': 0.979412404338395, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:30:55,502] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7329827146706644, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.10328003473955753, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2872262650985504, 'min_weight_fraction_leaf': 0.2118047441439845, 'max_features': 'auto', 'min_impurity_decrease': 7.161280890174719e-07, 'validation_fraction': 0.8326344162343784, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:31:13,297] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.968028637803562, 'learning_rate': 0.012332676724282343, 'dropout_rate': 0.3116356702759888, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.20691530526186325, 'min_weight_fraction_leaf': 0.17880882745231644, 'max_features': 'sqrt', 'min_impurity_decrease': 4.559575312773901e-06, 'validation_fraction': 0.5736364556858768, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:31:42,282] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.586845457594135, 'learning_rate': 0.015087793813163719, 'dropout_rate': 0.1289037142883289, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 1.7523211277779085, 'min_weight_fraction_leaf': 0.1388142878843003, 'max_features': 'auto', 'min_impurity_decrease': 3.1579639125192316e-07, 'validation_fraction': 0.9007381558442704, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 9}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:31:57,939] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9384285478087404, 'learning_rate': 0.008432408233149245, 'dropout_rate': 0.2555430411709441, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 0.5917857287890423, 'min_weight_fraction_leaf': 0.30147465751502, 'max_features': 'auto', 'min_impurity_decrease': 1.3322358120453633e-06, 'validation_fraction': 0.7530800224575359, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:32:24,017] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8566436667378682, 'learning_rate': 0.01150450588881658, 'dropout_rate': 0.1670492025845379, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.16544408115726048, 'max_features': 'auto', 'min_impurity_decrease': 1.2718861827092477e-05, 'validation_fraction': 0.999916960516484, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:32:37,725] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9108486830124928, 'learning_rate': 0.07073008964456817, 'dropout_rate': 0.2036613424933201, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.12697803926229267, 'max_features': None, 'min_impurity_decrease': 8.395207931535954e-05, 'validation_fraction': 0.8697930286831252, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21298041191430933
Fold 2 IBS: 0.22048509717101197
Fold 3 IBS: 0.2037935347009234
Fold 4 IBS: 0.22416608987358
Fold 5 IBS: 0.21726205535451415
[I 2024-04-16 05:33:03,152] Trial 91 finished with value: 0.21573743780286775 and parameters: {'subsample': 0.7918122624467706, 'learning_rate': 0.008764883268716819, 'dropout_rate': 0.23147171525582408, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.28864883630713, 'max_features': 'auto', 'min_impurity_decrease': 2.433769869200532e-06, 'validation_fraction': 0.9330807112636796, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21273002612666614
Fold 2 IBS: 0.22020162175537994
Fold 3 IBS: 0.20375739205646468
Fold 4 IBS: 0.22398391162161366
Fold 5 IBS: 0.21696727449411685
[I 2024-04-16 05:33:30,486] Trial 92 finished with value: 0.21552804521084826 and parameters: {'subsample': 0.7970612869259553, 'learning_rate': 0.006846874820718422, 'dropout_rate': 0.14896704674181122, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.048376779302453654, 'min_weight_fraction_leaf': 0.2632936345144107, 'max_features': 'auto', 'min_impurity_decrease': 2.1668791988162493e-06, 'validation_fraction': 0.962264255678676, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 05:34:00,215] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8863794702939648, 'learning_rate': 0.005644515103436926, 'dropout_rate': 0.1511320088851303, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.8672812842462059, 'min_weight_fraction_leaf': 0.2631664572752167, 'max_features': 'auto', 'min_impurity_decrease': 9.594887622043012e-07, 'validation_fraction': 0.9597976992445604, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:34:23,200] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7555668093579782, 'learning_rate': 0.003024128821367058, 'dropout_rate': 0.18020067991764227, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.5370821041135924, 'min_weight_fraction_leaf': 0.3269802231121252, 'max_features': 'auto', 'min_impurity_decrease': 5.453652008067023e-07, 'validation_fraction': 0.9064168309630759, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:34:46,236] Trial 95 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8285555969881634, 'learning_rate': 0.0011500826880246348, 'dropout_rate': 0.1263312272620864, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.0677877027733826, 'min_weight_fraction_leaf': 0.23754287719496792, 'max_features': 'auto', 'min_impurity_decrease': 1.5717571529922772e-06, 'validation_fraction': 0.9416814543721681, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:35:11,913] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7078782825524117, 'learning_rate': 0.024032062736360556, 'dropout_rate': 0.21333201870671714, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.23399465857880092, 'min_weight_fraction_leaf': 0.2509877726726459, 'max_features': 'auto', 'min_impurity_decrease': 4.132954919887874e-06, 'validation_fraction': 0.966821915092678, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:35:33,271] Trial 97 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9362560013369767, 'learning_rate': 0.0062939849492930095, 'dropout_rate': 0.25430805534041345, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.20566514949538883, 'min_weight_fraction_leaf': 0.2189843961179572, 'max_features': 1, 'min_impurity_decrease': 8.03183490237945e-06, 'validation_fraction': 0.8835944049341534, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:36:01,181] Trial 98 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.979668618259463, 'learning_rate': 0.016116253930051894, 'dropout_rate': 0.15171316016644432, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 0.526527014614438, 'min_weight_fraction_leaf': 0.27830242472777905, 'max_features': 'auto', 'min_impurity_decrease': 2.2015056170379928e-06, 'validation_fraction': 0.8376875978231397, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21217724232754462
Fold 2 IBS: 0.21947402353962686
Fold 3 IBS: 0.2021045597995369
Fold 4 IBS: 0.22160198829426855

Fold 5 IBS: 0.2170864632573697
[I 2024-04-16 05:36:16,821] Trial 99 finished with value: 0.21448885544366933 and parameters: {'subsample': 0.8012390519326651, 'learning_rate': 0.05269659590897164, 'dropout_rate': 0.27553624278288036, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 0.004383883527848379, 'min_weight_fraction_leaf': 0.353628504086837, 'max_features': 0.1, 'min_impurity_decrease': 8.641052711851521e-07, 'validation_fraction': 0.6285370472109972, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.2064912784368552], datetime_start=datetime.datetime(2024, 4, 16, 5, 27, 12, 601270), datetime_complete=datetime.datetime(2024, 4, 16, 5, 27, 34, 744404), params={'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.2064912784368552

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.74
train_ibs:  0.206

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.058133567268478875,
                                 criterion='squared_error',
                                 dropout_rate=0.2527776031497929,
                                 learning_rate=0.0012227187192111223,
                                 max_depth=1, max_features='auto',
                                 max_leaf_nodes=20,
                                 min_impurity_decrease=1.5094636128058346e-06,
                                 min_samples_leaf=15, min_samples_split=20,
                                 min_weight_fraction_leaf=0.2151989029549357,
                                 n_estimators=489, random_state=123,
                                 subsample=0.873850481285158,
                                 validation_fraction=0.9945176333416724)

C-index score: 0.618

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008810810992982535,
                                 criterion='squared_error',
                                 dropout_rate=0.1693875032679634,
                                 learning_rate=0.08843409287484169,
                                 max_features='auto', max_leaf_nodes=15,
                                 min_impurity_decrease=5.157320437854681e-06,
                                 min_samples_leaf=16, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29044798941528627,
                                 n_estimators=403, random_state=123,
                                 subsample=0.8646743646205938,
                                 validation_fraction=0.7489142536117352)

IBS: 0.215

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 05:36:27,459] A new study created in memory with name: no-name-1738cdcb-12ca-421a-8dad-28ad1792dc84

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:36:29,768] Trial 0 finished with value: 0.6944636137409307 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6944636137409307.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:36:40,446] Trial 1 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6944636137409307.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:36:43,809] Trial 2 finished with value: 0.6961513774540109 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6961513774540109.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:36:48,058] Trial 3 finished with value: 0.6998507204466902 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6998507204466902.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:36:53,455] Trial 4 finished with value: 0.7052118164888607 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7052118164888607.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:37:00,634] Trial 5 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7052118164888607.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:37:04,245] Trial 6 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7052118164888607.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:37:05,263] Trial 7 finished with value: 0.6970345508257922 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7052118164888607.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:37:09,488] Trial 8 finished with value: 0.6963829730339437 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7052118164888607.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:37:19,075] Trial 9 finished with value: 0.6954440058977934 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7052118164888607.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:37:25,215] Trial 10 finished with value: 0.702214114466351 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 4 with value: 0.7052118164888607.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 05:37:31,923] Trial 11 finished with value: 0.7069041650112775 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7069041650112775.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:37:38,581] Trial 12 finished with value: 0.7054383131070545 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.2495649826842376, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7069041650112775.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:37:46,424] Trial 13 finished with value: 0.6963001229925186 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7069041650112775.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:37:53,705] Trial 14 finished with value: 0.7097286166853328 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24475605651992097, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:38:01,077] Trial 15 finished with value: 0.6961831187036477 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.6890184489677957, 'n_estimators': 365, 'learning_rate': 0.08616677729964022}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:38:10,195] Trial 16 finished with value: 0.7045454559641974 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.10221023026090809, 'n_estimators': 423, 'learning_rate': 0.08463638125592773}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:38:19,067] Trial 17 finished with value: 0.7005804633073833 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 413, 'learning_rate': 0.08749976591807801}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:38:25,625] Trial 18 finished with value: 0.6998392169960579 and parameters: {'subsample': 0.35888747153360906, 'dropout_rate': 0.3446615188677563, 'n_estimators': 324, 'learning_rate': 0.09062397105934869}. Best is trial 14 with value: 0.7097286166853328.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:38:34,365] Trial 19 finished with value: 0.7081187042151826 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7196046509277619, 'n_estimators': 431, 'learning_rate': 0.08300323114610605}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:38:43,204] Trial 20 finished with value: 0.6989463598532007 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.7628923189846966, 'n_estimators': 438, 'learning_rate': 0.0796244585080611}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:38:51,056] Trial 21 finished with value: 0.7082091045222121 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.6080226687634136, 'n_estimators': 387, 'learning_rate': 0.09637537942321125}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:38:59,682] Trial 22 finished with value: 0.707950452665223 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.648340841365569, 'n_estimators': 396, 'learning_rate': 0.09976063116358903}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:39:09,290] Trial 23 finished with value: 0.7012775603280097 and parameters: {'subsample': 0.18705783897996425, 'dropout_rate': 0.8014372139995105, 'n_estimators': 457, 'learning_rate': 0.06637801331934103}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:39:14,640] Trial 24 finished with value: 0.7013507265983591 and parameters: {'subsample': 0.200517161883317, 'dropout_rate': 0.5837609897056383, 'n_estimators': 268, 'learning_rate': 0.07941478149071228}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:39:24,562] Trial 25 finished with value: 0.7027803934666461 and parameters: {'subsample': 0.284474180935654, 'dropout_rate': 0.9550172423277872, 'n_estimators': 497, 'learning_rate': 0.09135558293617337}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:39:31,604] Trial 26 finished with value: 0.6970489195694486 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.7450358283876386, 'n_estimators': 354, 'learning_rate': 0.08004450663761903}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:39:39,695] Trial 27 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.5697175944982166, 'n_estimators': 399, 'learning_rate': 0.09643487713965615}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:39:49,247] Trial 28 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.6095590802808257, 'dropout_rate': 0.5112334444909608, 'n_estimators': 459, 'learning_rate': 0.039422923782858485}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:39:49,986] Trial 29 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.6152426654259456, 'n_estimators': 28, 'learning_rate': 0.06046208382653473}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:39:51,970] Trial 30 finished with value: 0.7079111228439251 and parameters: {'subsample': 0.15736775526254157, 'dropout_rate': 0.39389709011778673, 'n_estimators': 93, 'learning_rate': 0.016814619253793885}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:39:59,820] Trial 31 finished with value: 0.7072016560882931 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.6513836708134688, 'n_estimators': 386, 'learning_rate': 0.09787732519743787}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:40:08,997] Trial 32 finished with value: 0.7062407699428821 and parameters: {'subsample': 0.102000681955651, 'dropout_rate': 0.7191462515540235, 'n_estimators': 436, 'learning_rate': 0.09964883579545385}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:40:16,082] Trial 33 finished with value: 0.7023311187552218 and parameters: {'subsample': 0.21799908034261378, 'dropout_rate': 0.7889631732045862, 'n_estimators': 350, 'learning_rate': 0.09281177669706939}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:40:24,292] Trial 34 finished with value: 0.7008196091529206 and parameters: {'subsample': 0.31478192981222664, 'dropout_rate': 0.4664686457083578, 'n_estimators': 399, 'learning_rate': 0.07454136223949474}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:40:29,055] Trial 35 finished with value: 0.7029434050318291 and parameters: {'subsample': 0.16380438916747353, 'dropout_rate': 0.6323437303377722, 'n_estimators': 242, 'learning_rate': 0.08243244936365145}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:40:34,775] Trial 36 finished with value: 0.6977706598693223 and parameters: {'subsample': 0.2448213009315035, 'dropout_rate': 0.8406270020449047, 'n_estimators': 294, 'learning_rate': 0.07132179141407224}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:40:41,921] Trial 37 finished with value: 0.7074359759382125 and parameters: {'subsample': 0.15292524757403228, 'dropout_rate': 0.5224514621370668, 'n_estimators': 339, 'learning_rate': 0.0930883201889077}. Best is trial 14 with value: 0.7097286166853328.

Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:40:51,672] Trial 38 finished with value: 0.6989953351395177 and parameters: {'subsample': 0.33048034552384, 'dropout_rate': 0.6976297360005081, 'n_estimators': 475, 'learning_rate': 0.07592765916956654}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:40:54,552] Trial 39 finished with value: 0.7004117594622088 and parameters: {'subsample': 0.22454104883455767, 'dropout_rate': 0.42809022439175537, 'n_estimators': 145, 'learning_rate': 0.06709978541578802}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:41:02,573] Trial 40 finished with value: 0.6999757272963805 and parameters: {'subsample': 0.4315561410698563, 'dropout_rate': 0.31977079521516183, 'n_estimators': 387, 'learning_rate': 0.08547143533731932}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:41:04,495] Trial 41 finished with value: 0.7063824175110003 and parameters: {'subsample': 0.15825860794080826, 'dropout_rate': 0.19088951028672188, 'n_estimators': 95, 'learning_rate': 0.01965516030876265}. Best is trial 14 with value: 0.7097286166853328.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:41:06,250] Trial 42 finished with value: 0.7151179596135444 and parameters: {'subsample': 0.13701019322015295, 'dropout_rate': 0.29305153369756815, 'n_estimators': 86, 'learning_rate': 0.01809054212903405}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:41:15,136] Trial 43 finished with value: 0.7045823344816297 and parameters: {'subsample': 0.13613017047488835, 'dropout_rate': 0.29438555936144584, 'n_estimators': 421, 'learning_rate': 0.005124837830886821}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:41:15,410] Trial 44 finished with value: 0.6916975072983537 and parameters: {'subsample': 0.1023646265230407, 'dropout_rate': 0.6058824707347543, 'n_estimators': 3, 'learning_rate': 0.04450424844427492}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:41:19,658] Trial 45 finished with value: 0.7022435837412162 and parameters: {'subsample': 0.19317043995957506, 'dropout_rate': 0.4953880279234909, 'n_estimators': 212, 'learning_rate': 0.03400538573985265}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:41:25,459] Trial 46 finished with value: 0.7006560425755417 and parameters: {'subsample': 0.5584819329312725, 'dropout_rate': 0.17732760347256354, 'n_estimators': 278, 'learning_rate': 0.09437854818226239}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:41:30,488] Trial 47 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.7043944586378885, 'dropout_rate': 0.3866750871073523, 'n_estimators': 248, 'learning_rate': 0.008209618821055878}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:41:33,329] Trial 48 finished with value: 0.7086184944001426 and parameters: {'subsample': 0.1379525209438608, 'dropout_rate': 0.6604314111556595, 'n_estimators': 144, 'learning_rate': 0.027763821111874188}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:41:36,217] Trial 49 finished with value: 0.7015142931757381 and parameters: {'subsample': 0.235204116115493, 'dropout_rate': 0.2935223361503146, 'n_estimators': 146, 'learning_rate': 0.02713079119975165}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:41:37,629] Trial 50 finished with value: 0.7007245238733104 and parameters: {'subsample': 0.3007185319443088, 'dropout_rate': 0.4326780653706334, 'n_estimators': 68, 'learning_rate': 0.01493400516489795}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:41:40,203] Trial 51 finished with value: 0.7095769675477446 and parameters: {'subsample': 0.14433220846513578, 'dropout_rate': 0.6632815026586311, 'n_estimators': 130, 'learning_rate': 0.028875771136203637}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:41:43,145] Trial 52 finished with value: 0.706772301377479 and parameters: {'subsample': 0.14223503343808253, 'dropout_rate': 0.7035673592180675, 'n_estimators': 151, 'learning_rate': 0.028107843893741723}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:41:45,420] Trial 53 finished with value: 0.7012775603280097 and parameters: {'subsample': 0.18084501246025336, 'dropout_rate': 0.5688695163997718, 'n_estimators': 115, 'learning_rate': 0.02226148292543457}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:41:47,764] Trial 54 finished with value: 0.7078943411024599 and parameters: {'subsample': 0.13552530159803536, 'dropout_rate': 0.7530872428648736, 'n_estimators': 119, 'learning_rate': 0.013446451144475902}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:41:48,886] Trial 55 finished with value: 0.7034170117503232 and parameters: {'subsample': 0.24578210702110784, 'dropout_rate': 0.6680193152993067, 'n_estimators': 52, 'learning_rate': 0.03707999621987184}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:41:52,157] Trial 56 finished with value: 0.7013507265983591 and parameters: {'subsample': 0.19340689641966768, 'dropout_rate': 0.8321976170610199, 'n_estimators': 169, 'learning_rate': 0.047136404299294346}. Best is trial 42 with value: 0.7151179596135444.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:41:56,073] Trial 57 finished with value: 0.705558041665912 and parameters: {'subsample': 0.13255352665271855, 'dropout_rate': 0.1489263492523255, 'n_estimators': 195, 'learning_rate': 0.027591961923099432}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:41:57,597] Trial 58 finished with value: 0.7007555333353943 and parameters: {'subsample': 0.17416143586357416, 'dropout_rate': 0.5462080102365253, 'n_estimators': 74, 'learning_rate': 0.011328842929283312}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:42:00,077] Trial 59 finished with value: 0.6997119381715959 and parameters: {'subsample': 0.20888054176926357, 'dropout_rate': 0.9039379306471309, 'n_estimators': 127, 'learning_rate': 0.031847044864100685}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:42:01,859] Trial 60 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.806998487000496, 'dropout_rate': 0.7272681272876578, 'n_estimators': 89, 'learning_rate': 0.019152560964519696}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:42:11,137] Trial 61 finished with value: 0.7073433036564113 and parameters: {'subsample': 0.1239427288811029, 'dropout_rate': 0.6220524914495925, 'n_estimators': 450, 'learning_rate': 0.08853620297725286}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:42:18,740] Trial 62 finished with value: 0.7053968880863419 and parameters: {'subsample': 0.10580102593543769, 'dropout_rate': 0.667040149110754, 'n_estimators': 377, 'learning_rate': 0.09501796771179648}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:42:27,296] Trial 63 finished with value: 0.6980073927170506 and parameters: {'subsample': 0.2675273969344081, 'dropout_rate': 0.5957736009201164, 'n_estimators': 408, 'learning_rate': 0.05310509552722724}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:42:33,849] Trial 64 finished with value: 0.7048846833341029 and parameters: {'subsample': 0.15913606586602846, 'dropout_rate': 0.7792954092362613, 'n_estimators': 326, 'learning_rate': 0.062049332343317054}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:42:42,792] Trial 65 finished with value: 0.706528750051699 and parameters: {'subsample': 0.13542833698724366, 'dropout_rate': 0.6444360310321701, 'n_estimators': 437, 'learning_rate': 0.09880460715471064}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:42:52,581] Trial 66 finished with value: 0.7072211620997448 and parameters: {'subsample': 0.10040712787726518, 'dropout_rate': 0.6847682388974488, 'n_estimators': 471, 'learning_rate': 0.08958058624938083}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:42:55,980] Trial 67 finished with value: 0.701141050027687 and parameters: {'subsample': 0.17787951320930911, 'dropout_rate': 0.7299763391196123, 'n_estimators': 174, 'learning_rate': 0.023938382638102475}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:43:03,419] Trial 68 finished with value: 0.7022579524848724 and parameters: {'subsample': 0.21341930605515397, 'dropout_rate': 0.5374655554850591, 'n_estimators': 356, 'learning_rate': 0.08287301811865723}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:43:04,411] Trial 69 finished with value: 0.713977909232057 and parameters: {'subsample': 0.13386078991177455, 'dropout_rate': 0.2403614303220229, 'n_estimators': 41, 'learning_rate': 0.09616745956791403}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 05:43:05,228] Trial 70 finished with value: 0.6996097549215963 and parameters: {'subsample': 0.24353408393186574, 'dropout_rate': 0.2232519618178151, 'n_estimators': 34, 'learning_rate': 0.09628272418596807}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:05,512] Trial 71 finished with value: 0.7147746380355737 and parameters: {'subsample': 0.14076159807333913, 'dropout_rate': 0.2643242519310487, 'n_estimators': 4, 'learning_rate': 0.09996673647561895}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:43:05,901] Trial 72 finished with value: 0.7025628936642486 and parameters: {'subsample': 0.14114180270302049, 'dropout_rate': 0.2652579740180665, 'n_estimators': 10, 'learning_rate': 0.09215147869729351}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:43:06,589] Trial 73 finished with value: 0.7058777630243657 and parameters: {'subsample': 0.18597033136891927, 'dropout_rate': 0.3387481585466534, 'n_estimators': 25, 'learning_rate': 0.08724162653839172}. Best is trial 42 with value: 0.7151179596135444.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 05:43:07,690] Trial 74 finished with value: 0.7168014906492589 and parameters: {'subsample': 0.1257479601061123, 'dropout_rate': 0.21768906703332452, 'n_estimators': 50, 'learning_rate': 0.09624856013840787}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:43:08,756] Trial 75 finished with value: 0.7035972573521865 and parameters: {'subsample': 0.16241378872306664, 'dropout_rate': 0.22213084092839774, 'n_estimators': 48, 'learning_rate': 0.09673090105194403}. Best is trial 74 with value: 0.7168014906492589.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:43:10,114] Trial 76 finished with value: 0.7126059968307328 and parameters: {'subsample': 0.12810404574114276, 'dropout_rate': 0.1264138980258778, 'n_estimators': 64, 'learning_rate': 0.09044759680033072}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:11,433] Trial 77 finished with value: 0.7074285666956454 and parameters: {'subsample': 0.20432383639940413, 'dropout_rate': 0.12350639075807664, 'n_estimators': 62, 'learning_rate': 0.09123799597665833}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:43:13,095] Trial 78 finished with value: 0.6998265294626578 and parameters: {'subsample': 0.2888140245596445, 'dropout_rate': 0.1732670735583789, 'n_estimators': 81, 'learning_rate': 0.03992715085041981}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 05:43:15,219] Trial 79 finished with value: 0.7026652497171254 and parameters: {'subsample': 0.12563495446440606, 'dropout_rate': 0.19705909945598774, 'n_estimators': 105, 'learning_rate': 0.09949358189428424}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:43:15,816] Trial 80 finished with value: 0.7012020837768324 and parameters: {'subsample': 0.6304010850525665, 'dropout_rate': 0.26971402742338824, 'n_estimators': 22, 'learning_rate': 0.0938483265422296}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:43:16,895] Trial 81 finished with value: 0.7090086960650157 and parameters: {'subsample': 0.1549929515205009, 'dropout_rate': 0.1428487731213716, 'n_estimators': 49, 'learning_rate': 0.09997419351034813}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:43:17,921] Trial 82 finished with value: 0.7038525916209365 and parameters: {'subsample': 0.15531632016950042, 'dropout_rate': 0.1346471118599922, 'n_estimators': 46, 'learning_rate': 0.09718186380698612}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:43:19,145] Trial 83 finished with value: 0.7139773184675416 and parameters: {'subsample': 0.1221673402182878, 'dropout_rate': 0.20897602713998817, 'n_estimators': 57, 'learning_rate': 0.09404726692292412}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 05:43:19,603] Trial 84 finished with value: 0.6995222199075906 and parameters: {'subsample': 0.17662619285159722, 'dropout_rate': 0.24424483355284318, 'n_estimators': 14, 'learning_rate': 0.08955678954116336}. Best is trial 74 with value: 0.7168014906492589.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 05:43:20,501] Trial 85 finished with value: 0.7210042592135316 and parameters: {'subsample': 0.12137873787446377, 'dropout_rate': 0.20529355154590012, 'n_estimators': 39, 'learning_rate': 0.09423091853893174}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:21,328] Trial 86 finished with value: 0.7122596331843811 and parameters: {'subsample': 0.11887203183460839, 'dropout_rate': 0.2894791244297029, 'n_estimators': 35, 'learning_rate': 0.0942916041305338}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:22,157] Trial 87 finished with value: 0.7131035150409213 and parameters: {'subsample': 0.11927541824456432, 'dropout_rate': 0.30549615907614114, 'n_estimators': 35, 'learning_rate': 0.08544730735892528}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:23,019] Trial 88 finished with value: 0.7114157513278411 and parameters: {'subsample': 0.12308379685167438, 'dropout_rate': 0.2927567314055005, 'n_estimators': 37, 'learning_rate': 0.07751125202422979}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:23,251] Trial 89 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.4102248519891853, 'dropout_rate': 0.20427170782117932, 'n_estimators': 1, 'learning_rate': 0.08742901792161126}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:43:24,540] Trial 90 finished with value: 0.7013777828754153 and parameters: {'subsample': 0.2312212611763706, 'dropout_rate': 0.31637220123630144, 'n_estimators': 61, 'learning_rate': 0.08338785532272983}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 05:43:25,418] Trial 91 finished with value: 0.7104767841916908 and parameters: {'subsample': 0.12052878600446693, 'dropout_rate': 0.28781804992274984, 'n_estimators': 38, 'learning_rate': 0.09384745277869144}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 05:43:25,947] Trial 92 finished with value: 0.7078476403446514 and parameters: {'subsample': 0.11529512196337657, 'dropout_rate': 0.3243404144314929, 'n_estimators': 18, 'learning_rate': 0.09147189913483574}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:26,909] Trial 93 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.99766016156918, 'dropout_rate': 0.3692952238325904, 'n_estimators': 37, 'learning_rate': 0.07791338463464278}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:28,935] Trial 94 finished with value: 0.7028703797845173 and parameters: {'subsample': 0.1934088393037397, 'dropout_rate': 0.1738491900013395, 'n_estimators': 81, 'learning_rate': 0.08589949248677163}. Best is trial 85 with value: 0.7210042592135316.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:30,301] Trial 95 finished with value: 0.7155090658688474 and parameters: {'subsample': 0.12484453387894283, 'dropout_rate': 0.23765374553059515, 'n_estimators': 61, 'learning_rate': 0.07130959264701398}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:43:31,702] Trial 96 finished with value: 0.7072748223586425 and parameters: {'subsample': 0.17874678279255996, 'dropout_rate': 0.2470445756825669, 'n_estimators': 65, 'learning_rate': 0.0950256037265761}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:43:32,958] Trial 97 finished with value: 0.7037579586365414 and parameters: {'subsample': 0.16563473650426971, 'dropout_rate': 0.214520127200523, 'n_estimators': 57, 'learning_rate': 0.07110719044640092}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:43:35,036] Trial 98 finished with value: 0.6996386308782091 and parameters: {'subsample': 0.25624588990368563, 'dropout_rate': 0.27781729888598783, 'n_estimators': 101, 'learning_rate': 0.08062035216684603}. Best is trial 85 with value: 0.7210042592135316.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688

[I 2024-04-16 05:43:36,637] A new study created in memory with name: no-name-dca82e9b-91cf-4368-8de4-c4601f018f0f

Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:43:36,631] Trial 99 finished with value: 0.6985655664395451 and parameters: {'subsample': 0.21908810854423394, 'dropout_rate': 0.2378147184632113, 'n_estimators': 75, 'learning_rate': 0.08502344394400864}. Best is trial 85 with value: 0.7210042592135316.


* Best trial for C-index:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.7210042592135316], datetime_start=datetime.datetime(2024, 4, 16, 5, 43, 19, 605005), datetime_complete=datetime.datetime(2024, 4, 16, 5, 43, 20, 501361), params={'subsample': 0.12137873787446377, 'dropout_rate': 0.20529355154590012, 'n_estimators': 39, 'learning_rate': 0.09423091853893174}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=85, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.12137873787446377, 'dropout_rate': 0.20529355154590012, 'n_estimators': 39, 'learning_rate': 0.09423091853893174}


* Best Score for C-index:
 0.7210042592135316

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24543748741914098
Fold 2 IBS: 0.23317848666127475
Fold 3 IBS: 0.18721324013097929
Fold 4 IBS: 0.2627413120655669
Fold 5 IBS: 0.2088844422588817
[I 2024-04-16 05:43:39,158] Trial 0 finished with value: 0.2274909937071687 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.3157615176698962
Fold 2 IBS: 0.32189237562862166
Fold 3 IBS: 0.2788861650869375
Fold 4 IBS: 0.3152651041057157
Fold 5 IBS: 0.3046807334754616
[I 2024-04-16 05:43:49,854] Trial 1 finished with value: 0.3072971791933265 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.2736129440677976
Fold 2 IBS: 0.2992916550922806
Fold 3 IBS: 0.2344928921000292
Fold 4 IBS: 0.2750087278739297
Fold 5 IBS: 0.2592818752777806
[I 2024-04-16 05:43:53,286] Trial 2 finished with value: 0.26833761888236357 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.2771997655106299
Fold 2 IBS: 0.2738997354359799
Fold 3 IBS: 0.23937090990720106
Fold 4 IBS: 0.2632441371572647
Fold 5 IBS: 0.22125549483997795
[I 2024-04-16 05:43:57,249] Trial 3 finished with value: 0.25499400857021065 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.277366146333423
Fold 2 IBS: 0.2874473566684048
Fold 3 IBS: 0.2433090583875763
Fold 4 IBS: 0.25644247192741454
Fold 5 IBS: 0.23122093156589923
[I 2024-04-16 05:44:02,706] Trial 4 finished with value: 0.2591571929765436 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.29964122631726436
Fold 2 IBS: 0.3204039646090136
Fold 3 IBS: 0.2615357263447192
Fold 4 IBS: 0.3032899768975731
Fold 5 IBS: 0.2968638928198015
[I 2024-04-16 05:44:09,895] Trial 5 finished with value: 0.29634695739767436 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.23142715981972764
Fold 2 IBS: 0.20264709709911605
Fold 3 IBS: 0.17325615036677913
Fold 4 IBS: 0.24090901161401929
Fold 5 IBS: 0.19041091163397286
[I 2024-04-16 05:44:13,433] Trial 6 finished with value: 0.207730066106723 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.207730066106723.
Fold 1 IBS: 0.2076748777046715
Fold 2 IBS: 0.18513286928098505
Fold 3 IBS: 0.17458570926946737
Fold 4 IBS: 0.20959901500077463
Fold 5 IBS: 0.18484804625610043
[I 2024-04-16 05:44:14,483] Trial 7 finished with value: 0.1923681035023998 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.2483266230281813
Fold 2 IBS: 0.24322669159502178
Fold 3 IBS: 0.19314995217139108
Fold 4 IBS: 0.26660384269502313
Fold 5 IBS: 0.20592581375019903
[I 2024-04-16 05:44:18,649] Trial 8 finished with value: 0.23144658464796325 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.30275986043779984
Fold 2 IBS: 0.32087941820266896
Fold 3 IBS: 0.2666014584900397
Fold 4 IBS: 0.3048081958481441
Fold 5 IBS: 0.29008700269414694
[I 2024-04-16 05:44:28,486] Trial 9 finished with value: 0.2970271871345599 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.21343330133003716
Fold 2 IBS: 0.22041746827332745
Fold 3 IBS: 0.2036139107282693
Fold 4 IBS: 0.2237771082655921
Fold 5 IBS: 0.21719902637866145
[I 2024-04-16 05:44:29,135] Trial 10 finished with value: 0.2156881629951775 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.21324338103957954
Fold 2 IBS: 0.22001717603804508
Fold 3 IBS: 0.20389467112141196
Fold 4 IBS: 0.2234486245538933
Fold 5 IBS: 0.2168716025171396
[I 2024-04-16 05:44:29,394] Trial 11 finished with value: 0.21549509105401388 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.2629915675140106
Fold 2 IBS: 0.2818051427713369
Fold 3 IBS: 0.21604618761489602
Fold 4 IBS: 0.2692560226887386
Fold 5 IBS: 0.2178728918608318
[I 2024-04-16 05:44:31,503] Trial 12 finished with value: 0.24959436248996275 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.26195181678854607
Fold 2 IBS: 0.2771979490504694
Fold 3 IBS: 0.21031993833068025
Fold 4 IBS: 0.2772718910025073
Fold 5 IBS: 0.24789677015981626
[I 2024-04-16 05:44:37,420] Trial 13 finished with value: 0.25492767306640385 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.2055469233365125
Fold 2 IBS: 0.19333008828178766
Fold 3 IBS: 0.18149798595746378
Fold 4 IBS: 0.20811509030714898
Fold 5 IBS: 0.195183209307254
[I 2024-04-16 05:44:39,296] Trial 14 finished with value: 0.19673465943803337 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.21056124354783895
Fold 2 IBS: 0.21352681391995132
Fold 3 IBS: 0.19869725603155575
Fold 4 IBS: 0.21866975920639684
Fold 5 IBS: 0.21185243931706207
[I 2024-04-16 05:44:40,768] Trial 15 finished with value: 0.21066150240456097 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.20646294925281175
Fold 2 IBS: 0.20279664668541308
Fold 3 IBS: 0.18998554437644108
Fold 4 IBS: 0.21138450932830422
Fold 5 IBS: 0.20288324042130967
[I 2024-04-16 05:44:42,038] Trial 16 finished with value: 0.20270257801285596 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.23688660254063618
Fold 2 IBS: 0.2137758878636472
Fold 3 IBS: 0.17666285067548287
Fold 4 IBS: 0.2497930363895449
Fold 5 IBS: 0.1965709716221325
[I 2024-04-16 05:44:44,533] Trial 17 finished with value: 0.21473786981828874 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.2380300059980365
Fold 2 IBS: 0.21603857243744973
Fold 3 IBS: 0.18048207133130295
Fold 4 IBS: 0.24859599562150908
Fold 5 IBS: 0.1879123954325471
[I 2024-04-16 05:44:51,155] Trial 18 finished with value: 0.21421180816416907 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.1923681035023998.
Fold 1 IBS: 0.20427482822698922
Fold 2 IBS: 0.1770757612301319

Fold 3 IBS: 0.176367138886304
Fold 4 IBS: 0.1909578398891022
Fold 5 IBS: 0.1852339049283287
[I 2024-04-16 05:44:52,266] Trial 19 finished with value: 0.1867818946321712 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.20469079919009717
Fold 2 IBS: 0.18064618713943587
Fold 3 IBS: 0.17817863512012502
Fold 4 IBS: 0.19624326076516657
Fold 5 IBS: 0.1882420126723995
[I 2024-04-16 05:44:53,237] Trial 20 finished with value: 0.18960017897744483 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.2011122965531937
Fold 2 IBS: 0.18605742016473745
Fold 3 IBS: 0.1839099329896944
Fold 4 IBS: 0.2015491239632672
Fold 5 IBS: 0.19365814954432883
[I 2024-04-16 05:44:54,033] Trial 21 finished with value: 0.19325738464304432 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.21284271933368631
Fold 2 IBS: 0.2192486563965627
Fold 3 IBS: 0.20302325984715375
Fold 4 IBS: 0.2222842490602751
Fold 5 IBS: 0.21629342497904955
[I 2024-04-16 05:44:54,292] Trial 22 finished with value: 0.2147384619233455 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.2348419715879879
Fold 2 IBS: 0.20738071144853373
Fold 3 IBS: 0.1853394669894191
Fold 4 IBS: 0.2350403623202591
Fold 5 IBS: 0.17764162614192236
[I 2024-04-16 05:44:57,291] Trial 23 finished with value: 0.20804882769762445 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.22248320058398224
Fold 2 IBS: 0.19085270418692715
Fold 3 IBS: 0.17172708052628663
Fold 4 IBS: 0.22993815392808942
Fold 5 IBS: 0.1785416369091566
[I 2024-04-16 05:44:58,489] Trial 24 finished with value: 0.1987085552268884 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.22163073147317996
Fold 2 IBS: 0.18475804653138572
Fold 3 IBS: 0.17286482380348905
Fold 4 IBS: 0.2166613752842843
Fold 5 IBS: 0.17740433408924122
[I 2024-04-16 05:45:00,180] Trial 25 finished with value: 0.19466386223631607 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.26390558661170893
Fold 2 IBS: 0.2496225923719803
Fold 3 IBS: 0.23512982867605486
Fold 4 IBS: 0.22292166483063872
Fold 5 IBS: 0.20896891408520848
[I 2024-04-16 05:45:03,240] Trial 26 finished with value: 0.23610971731511823 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.25339191360213825
Fold 2 IBS: 0.25019230722659
Fold 3 IBS: 0.2029452062831183
Fold 4 IBS: 0.2630090606503658
Fold 5 IBS: 0.20261284435575916
[I 2024-04-16 05:45:08,002] Trial 27 finished with value: 0.2344302664235943 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.20540859953998852
Fold 2 IBS: 0.19442982296416572
Fold 3 IBS: 0.18594830345561808
Fold 4 IBS: 0.206717064225803
Fold 5 IBS: 0.19825316368525325
[I 2024-04-16 05:45:08,964] Trial 28 finished with value: 0.19815139077416571 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.24931739081681506
Fold 2 IBS: 0.24842622998621017
Fold 3 IBS: 0.1946776213480084
Fold 4 IBS: 0.2705170447873235
Fold 5 IBS: 0.2017198245310104
[I 2024-04-16 05:45:25,340] Trial 29 finished with value: 0.23293162229387349 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.23178079376152108
Fold 2 IBS: 0.19101194318097925
Fold 3 IBS: 0.17718902139182244
Fold 4 IBS: 0.22759567423861712
Fold 5 IBS: 0.17976538444110904
[I 2024-04-16 05:45:27,265] Trial 30 finished with value: 0.2014685634028098 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.2011953267285645
Fold 2 IBS: 0.17931619693888584
Fold 3 IBS: 0.1801606329045483
Fold 4 IBS: 0.1999405321253404
Fold 5 IBS: 0.18860551155298044
[I 2024-04-16 05:45:28,100] Trial 31 finished with value: 0.18984364005006388 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.2025251158810651
Fold 2 IBS: 0.18779802761808984
Fold 3 IBS: 0.18144207949231633
Fold 4 IBS: 0.20105122752210586
Fold 5 IBS: 0.192358650890009
[I 2024-04-16 05:45:28,818] Trial 32 finished with value: 0.19303502028071723 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.1867818946321712.
Fold 1 IBS: 0.21653932910542498
Fold 2 IBS: 0.16923428810834246
Fold 3 IBS: 0.17497444950714738
Fold 4 IBS: 0.19323752649375797
Fold 5 IBS: 0.1773684125988523
[I 2024-04-16 05:45:30,154] Trial 33 finished with value: 0.18627080116270503 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 33 with value: 0.18627080116270503.
Fold 1 IBS: 0.21111843046231343
Fold 2 IBS: 0.21266003180843784
Fold 3 IBS: 0.19943421783538148
Fold 4 IBS: 0.21864973429916335
Fold 5 IBS: 0.21352235961056626
[I 2024-04-16 05:45:30,431] Trial 34 finished with value: 0.21107695480317248 and parameters: {'subsample': 0.10904251030586302, 'dropout_rate': 0.8662195064551774, 'n_estimators': 3, 'learning_rate': 0.07766566220378217}. Best is trial 33 with value: 0.18627080116270503.
Fold 1 IBS: 0.2608195033187159
Fold 2 IBS: 0.26762077174587684
Fold 3 IBS: 0.21669168431022803
Fold 4 IBS: 0.26490195547888185
Fold 5 IBS: 0.21034236423121236
[I 2024-04-16 05:45:33,188] Trial 35 finished with value: 0.24407525581698297 and parameters: {'subsample': 0.27868485453535496, 'dropout_rate': 0.9999743696114711, 'n_estimators': 141, 'learning_rate': 0.06694317131672249}. Best is trial 33 with value: 0.18627080116270503.
Fold 1 IBS: 0.31875352587949346
Fold 2 IBS: 0.31983686612779855
Fold 3 IBS: 0.27701938514243685
Fold 4 IBS: 0.272857937990016
Fold 5 IBS: 0.26479944774520686
[I 2024-04-16 05:45:41,782] Trial 36 finished with value: 0.2906534325769904 and parameters: {'subsample': 0.16326559473518704, 'dropout_rate': 0.8736174627174981, 'n_estimators': 421, 'learning_rate': 0.07993410500556083}. Best is trial 33 with value: 0.18627080116270503.
Fold 1 IBS: 0.25917632591228085
Fold 2 IBS: 0.2609248284281908
Fold 3 IBS: 0.2166103831499354
Fold 4 IBS: 0.26518679388858324
Fold 5 IBS: 0.21354217825341473
[I 2024-04-16 05:45:45,227] Trial 37 finished with value: 0.243088101926481 and parameters: {'subsample': 0.23660873470356106, 'dropout_rate': 0.7990281623991888, 'n_estimators': 170, 'learning_rate': 0.05621431261796065}. Best is trial 33 with value: 0.18627080116270503.
Fold 1 IBS: 0.2211542339512011
Fold 2 IBS: 0.15878441452626565
Fold 3 IBS: 0.1787190700324902

Fold 4 IBS: 0.19137957542628567
Fold 5 IBS: 0.17954640808378752
[I 2024-04-16 05:45:46,942] Trial 38 finished with value: 0.18591674040400602 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 82, 'learning_rate': 0.0684395247111694}. Best is trial 38 with value: 0.18591674040400602.
Fold 1 IBS: 0.2301128250403564
Fold 2 IBS: 0.17482409395156845
Fold 3 IBS: 0.1804210445509503
Fold 4 IBS: 0.20622114156408478
Fold 5 IBS: 0.1763773463922985
[I 2024-04-16 05:45:48,650] Trial 39 finished with value: 0.1935912902998517 and parameters: {'subsample': 0.1669627464432204, 'dropout_rate': 0.11471626893495929, 'n_estimators': 82, 'learning_rate': 0.06892741183938003}. Best is trial 38 with value: 0.18591674040400602.
Fold 1 IBS: 0.26127361158239537
Fold 2 IBS: 0.2702117097774595
Fold 3 IBS: 0.21315070084074397
Fold 4 IBS: 0.2757159479700989
Fold 5 IBS: 0.21994451436070936
[I 2024-04-16 05:45:50,908] Trial 40 finished with value: 0.24805929690628142 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.27073406810212547, 'n_estimators': 112, 'learning_rate': 0.08603457614657108}. Best is trial 38 with value: 0.18591674040400602.
Fold 1 IBS: 0.21333019654237578
Fold 2 IBS: 0.16907637022067062
Fold 3 IBS: 0.17154295269101721
Fold 4 IBS: 0.18863487320845856
Fold 5 IBS: 0.17378197648914673
[I 2024-04-16 05:45:52,160] Trial 41 finished with value: 0.1832732738303338 and parameters: {'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 58, 'learning_rate': 0.06842845994744125}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.21294279749606151
Fold 2 IBS: 0.1714945998157997
Fold 3 IBS: 0.1731288009784489
Fold 4 IBS: 0.20493010799111977
Fold 5 IBS: 0.17549285338430973
[I 2024-04-16 05:45:53,521] Trial 42 finished with value: 0.18759783193314794 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.19807687454956896, 'n_estimators': 64, 'learning_rate': 0.06911254892370094}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.2757373192244659
Fold 2 IBS: 0.26343705072611573
Fold 3 IBS: 0.23836821723730478
Fold 4 IBS: 0.24899513445606877
Fold 5 IBS: 0.21471408804071182
[I 2024-04-16 05:45:57,475] Trial 43 finished with value: 0.24825036193693345 and parameters: {'subsample': 0.20979862666572763, 'dropout_rate': 0.21348524642098904, 'n_estimators': 198, 'learning_rate': 0.0726352652201749}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.22693486364345375
Fold 2 IBS: 0.18207874133352955
Fold 3 IBS: 0.1745575599098608
Fold 4 IBS: 0.2193685130893947
Fold 5 IBS: 0.1750076321968786
[I 2024-04-16 05:45:58,814] Trial 44 finished with value: 0.19558946203462346 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.20101401396422397, 'n_estimators': 63, 'learning_rate': 0.06523605428553468}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.24864207644217515
Fold 2 IBS: 0.23560352937342835
Fold 3 IBS: 0.1931238835425645
Fold 4 IBS: 0.2591423949714222
Fold 5 IBS: 0.19731467924774693
[I 2024-04-16 05:46:00,760] Trial 45 finished with value: 0.22676531271546746 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.295844522167053, 'n_estimators': 96, 'learning_rate': 0.07358829455007394}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.2508833077420966
Fold 2 IBS: 0.23123675383313014
Fold 3 IBS: 0.22151614869590075
Fold 4 IBS: 0.24658928025833818
Fold 5 IBS: 0.19639338988186933
[I 2024-04-16 05:46:03,293] Trial 46 finished with value: 0.229323776082267 and parameters: {'subsample': 0.14485404068604799, 'dropout_rate': 0.3312246704393865, 'n_estimators': 127, 'learning_rate': 0.08365083008051383}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.25829388019114036
Fold 2 IBS: 0.22514133746208378
Fold 3 IBS: 0.21933785975058553
Fold 4 IBS: 0.23428827941771335
Fold 5 IBS: 0.19349445156166187
[I 2024-04-16 05:46:06,775] Trial 47 finished with value: 0.22611116167663697 and parameters: {'subsample': 0.24463732973960714, 'dropout_rate': 0.13911133506878087, 'n_estimators': 175, 'learning_rate': 0.0622210649734474}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.19876170222063283
Fold 2 IBS: 0.18177655309655644
Fold 3 IBS: 0.17981863242122464
Fold 4 IBS: 0.1967078660018511
Fold 5 IBS: 0.19564094622300224
[I 2024-04-16 05:46:07,314] Trial 48 finished with value: 0.19054113999265346 and parameters: {'subsample': 0.10041210259629582, 'dropout_rate': 0.19701471782839963, 'n_estimators': 18, 'learning_rate': 0.09182402211019655}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.22554775032788899
Fold 2 IBS: 0.18582833337060964
Fold 3 IBS: 0.1726364057649019
Fold 4 IBS: 0.22283582309833438
Fold 5 IBS: 0.17797434328496398
[I 2024-04-16 05:46:08,871] Trial 49 finished with value: 0.1969645311693398 and parameters: {'subsample': 0.317047365475798, 'dropout_rate': 0.4402540309495773, 'n_estimators': 75, 'learning_rate': 0.051717833751605366}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.28479062388344156
Fold 2 IBS: 0.2608710290805481
Fold 3 IBS: 0.24876266409145092
Fold 4 IBS: 0.2427820676998354
Fold 5 IBS: 0.2242746452345772
[I 2024-04-16 05:46:13,499] Trial 50 finished with value: 0.25229620599797065 and parameters: {'subsample': 0.1830774219227035, 'dropout_rate': 0.17538138388138197, 'n_estimators': 230, 'learning_rate': 0.07966264522754796}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.21010825090120375
Fold 2 IBS: 0.16984897746893804
Fold 3 IBS: 0.17217318793015232
Fold 4 IBS: 0.1931622468437262
Fold 5 IBS: 0.17831447752308413
[I 2024-04-16 05:46:14,618] Trial 51 finished with value: 0.1847214281334209 and parameters: {'subsample': 0.1422401972634589, 'dropout_rate': 0.10079252980319817, 'n_estimators': 49, 'learning_rate': 0.07018211474264216}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.21624264501821172
Fold 2 IBS: 0.17083111613550625
Fold 3 IBS: 0.1725301598822192
Fold 4 IBS: 0.18921651726350944
Fold 5 IBS: 0.17480376293016273
[I 2024-04-16 05:46:15,951] Trial 52 finished with value: 0.18472484024592187 and parameters: {'subsample': 0.13494378844422814, 'dropout_rate': 0.10510137537932576, 'n_estimators': 59, 'learning_rate': 0.06926018955996141}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.28376066393478366
Fold 2 IBS: 0.23322636528345786
Fold 3 IBS: 0.25132352872498465
Fold 4 IBS: 0.22126067195893556
Fold 5 IBS: 0.21188330336203
[I 2024-04-16 05:46:21,875] Trial 53 finished with value: 0.24029090665283834 and parameters: {'subsample': 0.14863982748363808, 'dropout_rate': 0.10187914564083042, 'n_estimators': 276, 'learning_rate': 0.07644499460442745}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.2225078927379004
Fold 2 IBS: 0.18797259457368376
Fold 3 IBS: 0.17128012103156776
Fold 4 IBS: 0.22549666468219204
Fold 5 IBS: 0.17920612441126121
[I 2024-04-16 05:46:22,970] Trial 54 finished with value: 0.19729267948732104 and parameters: {'subsample': 0.7123271512684496, 'dropout_rate': 0.1469933982907719, 'n_estimators': 49, 'learning_rate': 0.07105739554621304}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.2014987061719073
Fold 2 IBS: 0.19589272730312843
Fold 3 IBS: 0.18814317476184295
Fold 4 IBS: 0.20572308776907441
Fold 5 IBS: 0.19799278495192485
[I 2024-04-16 05:46:23,533] Trial 55 finished with value: 0.1978500961915756 and parameters: {'subsample': 0.12744461040189287, 'dropout_rate': 0.25227527653590254, 'n_estimators': 18, 'learning_rate': 0.058792439227992585}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.23549485408240572
Fold 2 IBS: 0.17986030826784885
Fold 3 IBS: 0.1884137403040017
Fold 4 IBS: 0.21513505854512668
Fold 5 IBS: 0.17711803994603156
[I 2024-04-16 05:46:25,735] Trial 56 finished with value: 0.19920440022908292 and parameters: {'subsample': 0.21188455005588142, 'dropout_rate': 0.13179976620229178, 'n_estimators': 103, 'learning_rate': 0.0641028486764566}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.2366977773273201
Fold 2 IBS: 0.18800252236617102
Fold 3 IBS: 0.19453514198565372

Fold 4 IBS: 0.2132818429711161
Fold 5 IBS: 0.17851437335007553
[I 2024-04-16 05:46:27,487] Trial 57 finished with value: 0.2022063316000673 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.23806025997264035, 'n_estimators': 81, 'learning_rate': 0.08927098403763303}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.21967163466408127
Fold 2 IBS: 0.18317874622959196
Fold 3 IBS: 0.1718116182769781
Fold 4 IBS: 0.21134882526508325
Fold 5 IBS: 0.17569172545376738
[I 2024-04-16 05:46:28,648] Trial 58 finished with value: 0.1923405099779004 and parameters: {'subsample': 0.2849097248903497, 'dropout_rate': 0.17854033983790962, 'n_estimators': 52, 'learning_rate': 0.06792721960100616}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.20555111235130516
Fold 2 IBS: 0.20532689463749107
Fold 3 IBS: 0.19122632129312667
Fold 4 IBS: 0.2100252252563886
Fold 5 IBS: 0.20518969454029629
[I 2024-04-16 05:46:29,134] Trial 59 finished with value: 0.20346384961572156 and parameters: {'subsample': 0.19280210316989804, 'dropout_rate': 0.1599945319557546, 'n_estimators': 15, 'learning_rate': 0.047995048145847055}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.30260929924850716
Fold 2 IBS: 0.3110528965628287
Fold 3 IBS: 0.26728473033896943
Fold 4 IBS: 0.26573121972845387
Fold 5 IBS: 0.25806623437183324
[I 2024-04-16 05:46:35,641] Trial 60 finished with value: 0.2809488760501185 and parameters: {'subsample': 0.2490257490592003, 'dropout_rate': 0.320245548964296, 'n_estimators': 319, 'learning_rate': 0.07454832842064382}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.2200778656999075
Fold 2 IBS: 0.18518849870548112
Fold 3 IBS: 0.17487140328685333
Fold 4 IBS: 0.2072263447905633
Fold 5 IBS: 0.1754187366900236
[I 2024-04-16 05:46:37,006] Trial 61 finished with value: 0.19255656983456576 and parameters: {'subsample': 0.17305081470095895, 'dropout_rate': 0.375136566118901, 'n_estimators': 64, 'learning_rate': 0.06842220294262286}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.22849738086091598
Fold 2 IBS: 0.17021091056126084
Fold 3 IBS: 0.18387308140479608
Fold 4 IBS: 0.19861732123731468
Fold 5 IBS: 0.17762694440578305
[I 2024-04-16 05:46:38,836] Trial 62 finished with value: 0.19176512769401413 and parameters: {'subsample': 0.1342292818449894, 'dropout_rate': 0.10031395553515703, 'n_estimators': 89, 'learning_rate': 0.07011431096636607}. Best is trial 41 with value: 0.1832732738303338.
Fold 1 IBS: 0.20484745028426124
Fold 2 IBS: 0.16557123281258718
Fold 3 IBS: 0.17139445616576615
Fold 4 IBS: 0.17686775794991677
Fold 5 IBS: 0.18146454666644274
[I 2024-04-16 05:46:39,726] Trial 63 finished with value: 0.18002908877579482 and parameters: {'subsample': 0.1060053487431015, 'dropout_rate': 0.23127988418023382, 'n_estimators': 38, 'learning_rate': 0.08155387781044005}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.21240483799940627
Fold 2 IBS: 0.1623857585518218
Fold 3 IBS: 0.17207976795794794
Fold 4 IBS: 0.1747540794218856
Fold 5 IBS: 0.18014868985163482
[I 2024-04-16 05:46:40,654] Trial 64 finished with value: 0.18035462675653927 and parameters: {'subsample': 0.10180710042129003, 'dropout_rate': 0.22493611916715012, 'n_estimators': 40, 'learning_rate': 0.09743269447662792}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2158805770114877
Fold 2 IBS: 0.16829801480548612
Fold 3 IBS: 0.16914201494602013
Fold 4 IBS: 0.18777977625758463
Fold 5 IBS: 0.17817459297566451
[I 2024-04-16 05:46:41,491] Trial 65 finished with value: 0.18385499519924858 and parameters: {'subsample': 0.1348839454118233, 'dropout_rate': 0.2226696810853981, 'n_estimators': 35, 'learning_rate': 0.09657359215516455}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.22779713706361782
Fold 2 IBS: 0.1835500678367058
Fold 3 IBS: 0.17184835361666992
Fold 4 IBS: 0.20334788169825696
Fold 5 IBS: 0.18014275749670697
[I 2024-04-16 05:46:42,488] Trial 66 finished with value: 0.1933372395423915 and parameters: {'subsample': 0.21995641524120108, 'dropout_rate': 0.22271190452360984, 'n_estimators': 44, 'learning_rate': 0.09973045543351286}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.21210176109007312
Fold 2 IBS: 0.18698368407792879
Fold 3 IBS: 0.17417843888371987
Fold 4 IBS: 0.21297556972502177
Fold 5 IBS: 0.18638330293562919
[I 2024-04-16 05:46:43,145] Trial 67 finished with value: 0.19452455134247454 and parameters: {'subsample': 0.8036527117288321, 'dropout_rate': 0.27509529884825623, 'n_estimators': 25, 'learning_rate': 0.09490401293367616}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.21309277813688046
Fold 2 IBS: 0.21797566261096651
Fold 3 IBS: 0.20320643623771767
Fold 4 IBS: 0.22312740270163917
Fold 5 IBS: 0.21567682370134103
[I 2024-04-16 05:46:43,388] Trial 68 finished with value: 0.21461582067770898 and parameters: {'subsample': 0.12955584019903935, 'dropout_rate': 0.29831628233275864, 'n_estimators': 1, 'learning_rate': 0.0962514739613329}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.21125311963470775
Fold 2 IBS: 0.17836748247657194
Fold 3 IBS: 0.17229144534863533
Fold 4 IBS: 0.20299389079355468
Fold 5 IBS: 0.1808615187722719
[I 2024-04-16 05:46:44,177] Trial 69 finished with value: 0.18915349140514834 and parameters: {'subsample': 0.18890607008448618, 'dropout_rate': 0.23851494482862293, 'n_estimators': 32, 'learning_rate': 0.08203348038736819}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.31376265504781536
Fold 2 IBS: 0.29649104005298327
Fold 3 IBS: 0.27400029218349753
Fold 4 IBS: 0.2404154905317096
Fold 5 IBS: 0.22700023876415942
[I 2024-04-16 05:46:52,828] Trial 70 finished with value: 0.27033394331603305 and parameters: {'subsample': 0.14078324522545957, 'dropout_rate': 0.16568782063879947, 'n_estimators': 408, 'learning_rate': 0.0901481447435182}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.23097135561629842
Fold 2 IBS: 0.15559559191765565
Fold 3 IBS: 0.18675035005166643
Fold 4 IBS: 0.18794784087978178
Fold 5 IBS: 0.1817372600371604
[I 2024-04-16 05:46:54,353] Trial 71 finished with value: 0.18860047970051252 and parameters: {'subsample': 0.10674377544765791, 'dropout_rate': 0.12961833118929164, 'n_estimators': 73, 'learning_rate': 0.09940908227593069}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2066681851135183
Fold 2 IBS: 0.1706302904060526
Fold 3 IBS: 0.17134864193400726
Fold 4 IBS: 0.2029467766548087
Fold 5 IBS: 0.17683239227414818
[I 2024-04-16 05:46:55,260] Trial 72 finished with value: 0.185685257276507 and parameters: {'subsample': 0.16219429367798271, 'dropout_rate': 0.1782286970000978, 'n_estimators': 39, 'learning_rate': 0.0865861861672653}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.215214285879969
Fold 2 IBS: 0.163158612810602
Fold 3 IBS: 0.17235640960342394
Fold 4 IBS: 0.20121838073424614
Fold 5 IBS: 0.17879297221902865
[I 2024-04-16 05:46:56,150] Trial 73 finished with value: 0.18614813224945395 and parameters: {'subsample': 0.18597033136891927, 'dropout_rate': 0.1753261848588733, 'n_estimators': 38, 'learning_rate': 0.09325827522149316}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20268084289847754
Fold 2 IBS: 0.19583521564639167
Fold 3 IBS: 0.1845680015472209
Fold 4 IBS: 0.20383339524014935
Fold 5 IBS: 0.1920183579455626
[I 2024-04-16 05:46:56,619] Trial 74 finished with value: 0.19578716265556043 and parameters: {'subsample': 0.1549331134802546, 'dropout_rate': 0.34578330340113894, 'n_estimators': 14, 'learning_rate': 0.08880318604659877}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.22546495703846037
Fold 2 IBS: 0.16823447787111576
Fold 3 IBS: 0.1742822572549072
Fold 4 IBS: 0.18643681381624938
Fold 5 IBS: 0.1771463885749247
[I 2024-04-16 05:46:57,758] Trial 75 finished with value: 0.18631297891113147 and parameters: {'subsample': 0.1270645713264064, 'dropout_rate': 0.22744316060692982, 'n_estimators': 50, 'learning_rate': 0.08580196757868053}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.24879638066547688
Fold 2 IBS: 0.21644788846441493
Fold 3 IBS: 0.21181716134682574

Fold 4 IBS: 0.2485134141944755
Fold 5 IBS: 0.19160050862980443
[I 2024-04-16 05:47:00,079] Trial 76 finished with value: 0.22343507066019946 and parameters: {'subsample': 0.16179134803259218, 'dropout_rate': 0.419783783711314, 'n_estimators': 109, 'learning_rate': 0.08167091626897967}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20604843080214338
Fold 2 IBS: 0.17849675216087169
Fold 3 IBS: 0.1748760996782727
Fold 4 IBS: 0.20466159091160982
Fold 5 IBS: 0.1858036320015903
[I 2024-04-16 05:47:00,834] Trial 77 finished with value: 0.18997730111089758 and parameters: {'subsample': 0.2243276930985941, 'dropout_rate': 0.12071886742003879, 'n_estimators': 29, 'learning_rate': 0.07730762793455846}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.25793619440791643
Fold 2 IBS: 0.19587144191501865
Fold 3 IBS: 0.22459948520743828
Fold 4 IBS: 0.21775241165792497
Fold 5 IBS: 0.20018205029034128
[I 2024-04-16 05:47:03,472] Trial 78 finished with value: 0.21926831669572794 and parameters: {'subsample': 0.12287626673759706, 'dropout_rate': 0.15485763416692047, 'n_estimators': 128, 'learning_rate': 0.09760139500608556}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2457522106806641
Fold 2 IBS: 0.20224599734640836
Fold 3 IBS: 0.20240303091569015
Fold 4 IBS: 0.2355529034689702
Fold 5 IBS: 0.18263426321470352
[I 2024-04-16 05:47:05,360] Trial 79 finished with value: 0.21371768112528727 and parameters: {'subsample': 0.1973180142174715, 'dropout_rate': 0.26293784447643637, 'n_estimators': 90, 'learning_rate': 0.08731485555810001}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.22067632466373324
Fold 2 IBS: 0.17624927344904337
Fold 3 IBS: 0.17202719749610798
Fold 4 IBS: 0.21730049556767378
Fold 5 IBS: 0.17673560989571493
[I 2024-04-16 05:47:06,302] Trial 80 finished with value: 0.19259778021445464 and parameters: {'subsample': 0.2613932849707703, 'dropout_rate': 0.202064330173782, 'n_estimators': 40, 'learning_rate': 0.09263526846391419}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.21206096002623742
Fold 2 IBS: 0.1651995387490805
Fold 3 IBS: 0.17152985432196619
Fold 4 IBS: 0.19537672299398604
Fold 5 IBS: 0.17707922560715492
[I 2024-04-16 05:47:07,179] Trial 81 finished with value: 0.184249260339685 and parameters: {'subsample': 0.17490524646533434, 'dropout_rate': 0.1788569220537291, 'n_estimators': 37, 'learning_rate': 0.09291995762116567}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.22279354778537835
Fold 2 IBS: 0.1784886069669122
Fold 3 IBS: 0.17945621934943
Fold 4 IBS: 0.2042486423091798
Fold 5 IBS: 0.17692772178148997
[I 2024-04-16 05:47:08,488] Trial 82 finished with value: 0.19238294763847807 and parameters: {'subsample': 0.1656748302619644, 'dropout_rate': 0.18324255894296368, 'n_estimators': 61, 'learning_rate': 0.09477390252988176}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20618787778791522
Fold 2 IBS: 0.203494964181843
Fold 3 IBS: 0.19458903750594153
Fold 4 IBS: 0.20914694811834128
Fold 5 IBS: 0.21098182235735252
[I 2024-04-16 05:47:08,835] Trial 83 finished with value: 0.20488012999027871 and parameters: {'subsample': 0.1022824556934966, 'dropout_rate': 0.30041751871331024, 'n_estimators': 7, 'learning_rate': 0.0913551297402999}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2406978879167472
Fold 2 IBS: 0.19340801326529164
Fold 3 IBS: 0.18361068587581464
Fold 4 IBS: 0.22085390790874676
Fold 5 IBS: 0.17774637162846546
[I 2024-04-16 05:47:10,352] Trial 84 finished with value: 0.20326337331901315 and parameters: {'subsample': 0.5584624909113933, 'dropout_rate': 0.1433195777587662, 'n_estimators': 73, 'learning_rate': 0.08256461132797006}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20464168311366823
Fold 2 IBS: 0.17567904801440765
Fold 3 IBS: 0.17345372993073394
Fold 4 IBS: 0.190771160744031
Fold 5 IBS: 0.1864252124022232
[I 2024-04-16 05:47:11,067] Trial 85 finished with value: 0.1861941668410128 and parameters: {'subsample': 0.14658213602932155, 'dropout_rate': 0.11636134246427338, 'n_estimators': 28, 'learning_rate': 0.08439809320755474}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.22353557331790747
Fold 2 IBS: 0.18964586307828982
Fold 3 IBS: 0.17483702116235933
Fold 4 IBS: 0.20188684803870596
Fold 5 IBS: 0.17772968358210683
[I 2024-04-16 05:47:12,263] Trial 86 finished with value: 0.19352699783587388 and parameters: {'subsample': 0.1821705123939037, 'dropout_rate': 0.21489682302184204, 'n_estimators': 55, 'learning_rate': 0.08783605043610347}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20663522728618372
Fold 2 IBS: 0.16992713493306674
Fold 3 IBS: 0.17452317203439577
Fold 4 IBS: 0.18996171773870657
Fold 5 IBS: 0.17744879193817054
[I 2024-04-16 05:47:13,193] Trial 87 finished with value: 0.18369920878610466 and parameters: {'subsample': 0.1205205879501397, 'dropout_rate': 0.24877711982098155, 'n_estimators': 40, 'learning_rate': 0.07961148176611225}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.21397750476088379
Fold 2 IBS: 0.17451622581398746
Fold 3 IBS: 0.1741774701631789
Fold 4 IBS: 0.2025172492081561
Fold 5 IBS: 0.17523100166791292
[I 2024-04-16 05:47:14,102] Trial 88 finished with value: 0.18808389032282385 and parameters: {'subsample': 0.20440862881305094, 'dropout_rate': 0.2523499457097179, 'n_estimators': 39, 'learning_rate': 0.08033770369557307}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2053567552269537
Fold 2 IBS: 0.1963782022446877
Fold 3 IBS: 0.1849555341029256
Fold 4 IBS: 0.20553127953020076
Fold 5 IBS: 0.19657994800597778
[I 2024-04-16 05:47:14,527] Trial 89 finished with value: 0.1977603438221491 and parameters: {'subsample': 0.22932405066568767, 'dropout_rate': 0.18531333494965943, 'n_estimators': 11, 'learning_rate': 0.09754500839459641}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.235375149061801
Fold 2 IBS: 0.19759239968155187
Fold 3 IBS: 0.1975847240239597
Fold 4 IBS: 0.2182035835143438
Fold 5 IBS: 0.1806664828174276
[I 2024-04-16 05:47:16,534] Trial 90 finished with value: 0.20588446781981676 and parameters: {'subsample': 0.1262577279641907, 'dropout_rate': 0.2835003991831958, 'n_estimators': 99, 'learning_rate': 0.07534883276700306}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.22107472893170624
Fold 2 IBS: 0.18000856684985847
Fold 3 IBS: 0.179771629906881
Fold 4 IBS: 0.20568998899675214
Fold 5 IBS: 0.1760074241932706
[I 2024-04-16 05:47:17,981] Trial 91 finished with value: 0.1925104677756937 and parameters: {'subsample': 0.11999853831426363, 'dropout_rate': 0.5129929513238454, 'n_estimators': 69, 'learning_rate': 0.07168332505298398}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2262782740625331
Fold 2 IBS: 0.1765013768089268
Fold 3 IBS: 0.17813574377943495
Fold 4 IBS: 0.20033250480285517
Fold 5 IBS: 0.17484666541405877
[I 2024-04-16 05:47:19,671] Trial 92 finished with value: 0.19121891297356175 and parameters: {'subsample': 0.1440485007553197, 'dropout_rate': 0.24181782931525808, 'n_estimators': 82, 'learning_rate': 0.06402109960446176}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20475187706504125
Fold 2 IBS: 0.18707888813688078
Fold 3 IBS: 0.18007827170477764
Fold 4 IBS: 0.20080651028223812
Fold 5 IBS: 0.19041137493658586
[I 2024-04-16 05:47:20,245] Trial 93 finished with value: 0.19262538442510474 and parameters: {'subsample': 0.17178762815637874, 'dropout_rate': 0.2104547169433691, 'n_estimators': 20, 'learning_rate': 0.07869481904781718}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.21840289347880504
Fold 2 IBS: 0.15746052068695235
Fold 3 IBS: 0.1759194525708696
Fold 4 IBS: 0.19052703236395915
Fold 5 IBS: 0.18331667772891116
[I 2024-04-16 05:47:21,407] Trial 94 finished with value: 0.18512531536589946 and parameters: {'subsample': 0.10209271466962214, 'dropout_rate': 0.1504404216498022, 'n_estimators': 53, 'learning_rate': 0.09459054530030528}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2149042569339893
Fold 2 IBS: 0.17069176959849214
Fold 3 IBS: 0.17489987803973867

Fold 4 IBS: 0.1968210219673999
Fold 5 IBS: 0.17717705751891255
[I 2024-04-16 05:47:22,554] Trial 95 finished with value: 0.1868987968117065 and parameters: {'subsample': 0.1574638138642586, 'dropout_rate': 0.15912282102770056, 'n_estimators': 52, 'learning_rate': 0.09300288337363928}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20382017098407673
Fold 2 IBS: 0.16304617903229723
Fold 3 IBS: 0.17046677831779045
Fold 4 IBS: 0.1988479250930264
Fold 5 IBS: 0.18223721600450057
[I 2024-04-16 05:47:23,448] Trial 96 finished with value: 0.18368365388633828 and parameters: {'subsample': 0.11389291137795171, 'dropout_rate': 0.1513089117226007, 'n_estimators': 38, 'learning_rate': 0.09026893567244454}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.20190868035660944
Fold 2 IBS: 0.17825190783982187
Fold 3 IBS: 0.17628135467243577
Fold 4 IBS: 0.19551749603380175
Fold 5 IBS: 0.18397851003413646
[I 2024-04-16 05:47:24,060] Trial 97 finished with value: 0.18718758978736105 and parameters: {'subsample': 0.11561443017962356, 'dropout_rate': 0.3212552426504853, 'n_estimators': 22, 'learning_rate': 0.09500831145565551}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.23291497030133765
Fold 2 IBS: 0.17952870582130567
Fold 3 IBS: 0.17592867252086788
Fold 4 IBS: 0.21641464555063408
Fold 5 IBS: 0.17369547382461686
[I 2024-04-16 05:47:25,217] Trial 98 finished with value: 0.1956964936037524 and parameters: {'subsample': 0.6340595518294957, 'dropout_rate': 0.1392716217479098, 'n_estimators': 53, 'learning_rate': 0.09078133686786893}. Best is trial 63 with value: 0.18002908877579482.
Fold 1 IBS: 0.2250593042416939
Fold 2 IBS: 0.1672583430320393
Fold 3 IBS: 0.1810702162615112
Fold 4 IBS: 0.19112170360398703
Fold 5 IBS: 0.18395108176580646
[I 2024-04-16 05:47:26,617] Trial 99 finished with value: 0.18969212978100758 and parameters: {'subsample': 0.10064643807992914, 'dropout_rate': 0.10097204350567876, 'n_estimators': 66, 'learning_rate': 0.09800772316634063}. Best is trial 63 with value: 0.18002908877579482.


* Best trial for IBS:
 FrozenTrial(number=63, state=TrialState.COMPLETE, values=[0.18002908877579482], datetime_start=datetime.datetime(2024, 4, 16, 5, 46, 38, 837811), datetime_complete=datetime.datetime(2024, 4, 16, 5, 46, 39, 726749), params={'subsample': 0.1060053487431015, 'dropout_rate': 0.23127988418023382, 'n_estimators': 38, 'learning_rate': 0.08155387781044005}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=63, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.1060053487431015, 'dropout_rate': 0.23127988418023382, 'n_estimators': 38, 'learning_rate': 0.08155387781044005}


* Best Score for IBS:
 0.18002908877579482

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.721
train_ibs:  0.18

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.20529355154590012,
                                              learning_rate=0.09423091853893174,
                                              n_estimators=39, random_state=123,
                                              subsample=0.12137873787446377)

C-index score: 0.581

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.23127988418023382,
                                              learning_rate=0.08155387781044005,
                                              n_estimators=38, random_state=123,
                                              subsample=0.1060053487431015)

IBS: 0.225

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [80]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.871   1.0
ExtraSurvivalTrees               0.867   2.0
GradientBoosting                 0.740   3.0
ComponentwiseGradientBoosting    0.721   4.0
CoxElastic                       0.696   5.0
CoxLasso                         0.692   6.0
CoxRidge                         0.651   7.0

In [81]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.180   1.0
Randomsurvivalforest           0.183   2.0
ExtraSurvivalTrees             0.186   3.0
CoxLasso                       0.198   4.5
CoxElastic                     0.198   4.5
GradientBoosting               0.206   6.0
CoxRidge                       0.217   7.0

In [82]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.628   1.0
GradientBoosting                 0.618   2.0
ExtraSurvivalTrees               0.616   3.0
CoxLasso                         0.597   4.5
CoxElastic                       0.597   4.5
CoxRidge                         0.592   6.0
ComponentwiseGradientBoosting    0.581   7.0

In [83]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.214   1.0
GradientBoosting               0.215   2.0
CoxRidge                       0.221   4.0
CoxLasso                       0.221   4.0
CoxElastic                     0.221   4.0
ComponentwiseGradientBoosting  0.225   6.0
Randomsurvivalforest           0.226   7.0

In [84]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/robust/no_selection/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_robust_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [85]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-16