In [1]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [14]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [17]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [18]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [19]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.704475,0.085656,0.059912,0.000000
1,0.101791,-0.291967,-0.755402,0.000000
2,-1.132016,0.186031,0.338093,0.524263
3,-0.017443,-0.729547,-0.709822,0.000000
4,-1.720923,1.251094,-0.285114,3.028668
...,...,...,...,...
134,0.525285,-0.150985,-0.360532,0.000000
135,0.344965,1.264145,0.011834,0.000000
136,-0.312609,-0.491468,-0.194798,0.000000
137,0.357529,1.374092,0.237230,0.000000
138,0.342282,0.972735,-0.486917,0.000000

In [20]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [21]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,-0.170593,0.654106,0.430171,0.398737
1,-0.152832,-1.450119,0.044973,2.544568
2,-0.584101,-0.575856,0.167421,0.869691
3,-1.020797,-0.876024,0.248699,0.000000
4,-0.519690,-0.080721,0.635308,0.000000
...,...,...,...,...
94,-0.135979,0.229539,-0.306881,0.000000
95,-0.507883,-0.658333,0.478960,0.000000
96,-0.382318,-1.243239,0.449591,0.000000
97,0.387916,-0.374070,0.191981,0.000000
98,-0.125793,-0.773193,-0.196876,0.000000

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [22]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:47:13,360] A new study created in memory with name: no-name-749ca9b7-deea-4d20-855f-60afdc744e99
python(81314) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098

[I 2024-04-16 00:47:23,632] A new study created in memory with name: no-name-9687990c-ce7b-43ec-9436-3ba8e274b516

Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:23,585] Trial 0 finished with value: 0.7358264523738474 and parameters: {}. Best is trial 0 with value: 0.7358264523738474.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7358264523738474], datetime_start=datetime.datetime(2024, 4, 16, 0, 47, 14, 81716), datetime_complete=datetime.datetime(2024, 4, 16, 0, 47, 23, 582168), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7358264523738474

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.17932951816141288
Fold 2 IBS: 0.15173912855888322
Fold 3 IBS: 0.17662964771229905
Fold 4 IBS: 0.1530370960050396
Fold 5 IBS: 0.19681553106978886
[I 2024-04-16 00:47:24,515] Trial 0 finished with value: 0.17151018430148474 and parameters: {}. Best is trial 0 with value: 0.17151018430148474.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17151018430148474], datetime_start=datetime.datetime(2024, 4, 16, 0, 47, 23, 728500), datetime_complete=datetime.datetime(2024, 4, 16, 0, 47, 24, 515050), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17151018430148474

In [23]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [24]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.172

#### Test

In [25]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [26]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.567
IBS score: 0.259

In [27]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [28]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [29]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:47:25,435] A new study created in memory with name: no-name-2c843a0a-8e37-4eda-9f4c-272b8ff0e351

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-16 00:47:25,670] A new study created in memory with name: no-name-ed6120db-60d8-4394-bd98-3eff16b20cda

Fold 1 C-index: 0.6471861471861472
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.6299019607843137
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:47:25,655] Trial 0 finished with value: 0.6952915433949395 and parameters: {}. Best is trial 0 with value: 0.6952915433949395.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6952915433949395], datetime_start=datetime.datetime(2024, 4, 16, 0, 47, 25, 511133), datetime_complete=datetime.datetime(2024, 4, 16, 0, 47, 25, 655500), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6952915433949395

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651654775943
Fold 2 IBS: 0.2215779056051601
Fold 3 IBS: 0.204535948534301
Fold 4 IBS: 0.2247380347558079
Fold 5 IBS: 0.2181243088160326
[I 2024-04-16 00:47:26,040] Trial 0 finished with value: 0.21659054285181217 and parameters: {}. Best is trial 0 with value: 0.21659054285181217.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054285181217], datetime_start=datetime.datetime(2024, 4, 16, 0, 47, 25, 780920), datetime_complete=datetime.datetime(2024, 4, 16, 0, 47, 26, 39591), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054285181217

In [30]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.695
train_ibs:  0.217

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.577

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:47:26,323] A new study created in memory with name: no-name-03da26bf-2ea9-4f3f-aec9-575658b3632f

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961

[I 2024-04-16 00:47:26,901] A new study created in memory with name: no-name-0f94f91e-e9c7-4158-b911-041d76bc9170

Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:26,883] Trial 0 finished with value: 0.7357337800920462 and parameters: {}. Best is trial 0 with value: 0.7357337800920462.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7357337800920462], datetime_start=datetime.datetime(2024, 4, 16, 0, 47, 26, 375365), datetime_complete=datetime.datetime(2024, 4, 16, 0, 47, 26, 882984), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7357337800920462

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.17984882789532766
Fold 2 IBS: 0.15097677823967964
Fold 3 IBS: 0.1765953973444983
Fold 4 IBS: 0.1535870472815473
Fold 5 IBS: 0.1957792713839434
[I 2024-04-16 00:47:27,322] Trial 0 finished with value: 0.1713574644289993 and parameters: {}. Best is trial 0 with value: 0.1713574644289993.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1713574644289993], datetime_start=datetime.datetime(2024, 4, 16, 0, 47, 26, 939335), datetime_complete=datetime.datetime(2024, 4, 16, 0, 47, 27, 321129), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1713574644289993

In [36]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.171

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.257

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:47:27,845] A new study created in memory with name: no-name-ec6afeab-4a25-422b-9c32-8e15562e0ffb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:28,419] Trial 0 finished with value: 0.734840922949189 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.734840922949189.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:28,933] Trial 1 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:29,473] Trial 2 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:29,830] Trial 3 finished with value: 0.7348679792262454 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:30,232] Trial 4 finished with value: 0.734840922949189 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:30,549] Trial 5 finished with value: 0.7349825705173073 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:30,822] Trial 6 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:31,146] Trial 7 finished with value: 0.734840922949189 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:31,478] Trial 8 finished with value: 0.7348679792262454 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:32,280] Trial 9 finished with value: 0.7349825705173073 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.7358483713831081.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:33,079] Trial 10 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:33,446] Trial 11 finished with value: 0.7246265236106273 and parameters: {'l1_ratio': 0.016444541243212374}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:34,043] Trial 12 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.0873928389796849}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:47:34,280] Trial 13 finished with value: 0.6951365938359007 and parameters: {'l1_ratio': 0.003240751291247554}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:35,012] Trial 14 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.14334023675256088}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:36,286] Trial 15 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.14686204034367636}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:37,403] Trial 16 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.29492929565472803}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:38,042] Trial 17 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.1278697437099071}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:38,516] Trial 18 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.06764452452390808}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:39,031] Trial 19 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:39,537] Trial 20 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:41,166] Trial 21 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.16870552103067943}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:42,121] Trial 22 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.10290429070558606}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:42,703] Trial 23 finished with value: 0.7349825705173073 and parameters: {'l1_ratio': 0.3543524189329308}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125

Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:43,095] Trial 24 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.21623254971460304}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:43,613] Trial 25 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.0853699617771228}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:44,081] Trial 26 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.17284350892750144}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:44,562] Trial 27 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.3231390668536532}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:45,088] Trial 28 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.05006338150545889}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:45,971] Trial 29 finished with value: 0.7348679792262454 and parameters: {'l1_ratio': 0.5551663189851536}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:46,406] Trial 30 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.2052530265626114}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:46,893] Trial 31 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:47,607] Trial 32 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.11271530900654927}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:47:47,906] Trial 33 finished with value: 0.6951365938359007 and parameters: {'l1_ratio': 0.0062661184216923765}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:48,367] Trial 34 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.2816935819767384}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:49,052] Trial 35 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.2503833329651749}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:49,626] Trial 36 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.13597853931319773}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:50,105] Trial 37 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.07029520243320188}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:50,510] Trial 38 finished with value: 0.734840922949189 and parameters: {'l1_ratio': 0.6666890374280088}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:51,224] Trial 39 finished with value: 0.7349825705173073 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:51,716] Trial 40 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.3396351837644522}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:52,515] Trial 41 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.15059499069998564}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:53,546] Trial 42 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.20174720161408186}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:55,053] Trial 43 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.11692006402374093}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:55,951] Trial 44 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.04418503916867171}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:56,352] Trial 45 finished with value: 0.7348679792262454 and parameters: {'l1_ratio': 0.5582592206819572}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:56,866] Trial 46 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.8167652444349325}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:57,352] Trial 47 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.23971145636476637}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173

Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:57,842] Trial 48 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.28913086771769636}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:58,351] Trial 49 finished with value: 0.7349825705173073 and parameters: {'l1_ratio': 0.3881372941956815}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:59,018] Trial 50 finished with value: 0.7333386448227486 and parameters: {'l1_ratio': 0.02973857144887264}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:47:59,585] Trial 51 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.0758489930917431}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:00,130] Trial 52 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.10500201225115977}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:00,773] Trial 53 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.17118709224302125}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:01,269] Trial 54 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.0594680598124232}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:01,782] Trial 55 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.13124910134042467}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:02,447] Trial 56 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.21009322571312605}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:48:02,645] Trial 57 finished with value: 0.6951365938359007 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:03,424] Trial 58 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.18858382094111684}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:05,655] Trial 59 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.09395086783190071}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:06,460] Trial 60 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.26322508076501777}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:07,224] Trial 61 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.08688366872297473}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:08,000] Trial 62 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.13427286191647708}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:08,621] Trial 63 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.04108464851847649}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:09,023] Trial 64 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.1755198426755306}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:09,454] Trial 65 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.10681775064471818}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:10,336] Trial 66 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.06330600199431953}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:11,018] Trial 67 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.1615803559722085}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:11,903] Trial 68 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.03878391537024327}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:12,416] Trial 69 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.13109566599341005}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:12,997] Trial 70 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.22521262401844067}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:14,035] Trial 71 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.09297281834568923}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:48:14,432] Trial 72 finished with value: 0.6951365938359007 and parameters: {'l1_ratio': 0.005021362610729302}. Best is trial 10 with value: 0.7367141722489089.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:15,060] Trial 73 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.07477035912423562}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:15,623] Trial 74 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.1478448402486734}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:16,243] Trial 75 finished with value: 0.7339751220833882 and parameters: {'l1_ratio': 0.523110210901512}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:16,642] Trial 76 finished with value: 0.7339751220833882 and parameters: {'l1_ratio': 0.6193857383371861}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:17,152] Trial 77 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.19328346899350535}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:17,618] Trial 78 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.11130464704704313}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:17,967] Trial 79 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:18,415] Trial 80 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.05226543818938653}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:18,901] Trial 81 finished with value: 0.7333386448227486 and parameters: {'l1_ratio': 0.029745851153293923}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:19,503] Trial 82 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.0773237963641062}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:21,636] Trial 83 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.13057889537613773}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:22,463] Trial 84 finished with value: 0.7333386448227486 and parameters: {'l1_ratio': 0.027490964921040965}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:23,177] Trial 85 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.15316596593619822}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:23,721] Trial 86 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.8393502475644614}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:24,163] Trial 87 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.058598542357505265}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:24,651] Trial 88 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.10870802934060594}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:25,192] Trial 89 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.3078797157164803}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:25,763] Trial 90 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.2676609645458347}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:26,412] Trial 91 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.09196511343950776}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:26,905] Trial 92 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.18003898464486312}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:27,582] Trial 93 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.11106225559762051}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:28,201] Trial 94 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.22676135074445725}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:28,712] Trial 95 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.0558182225349678}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:29,215] Trial 96 finished with value: 0.7264122378963418 and parameters: {'l1_ratio': 0.01928631616871245}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125

Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:29,675] Trial 97 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.12814300167097153}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:30,117] Trial 98 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.15926120393133159}. Best is trial 10 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173

[I 2024-04-16 00:48:30,724] A new study created in memory with name: no-name-d31147b8-5b48-422c-ba95-1d5416a3d2a4

Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 00:48:30,699] Trial 99 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.08564170045520172}. Best is trial 10 with value: 0.7367141722489089.


* Best trial for C-index:
 FrozenTrial(number=10, state=TrialState.COMPLETE, values=[0.7367141722489089], datetime_start=datetime.datetime(2024, 4, 16, 0, 47, 32, 321582), datetime_complete=datetime.datetime(2024, 4, 16, 0, 47, 33, 78663), params={'l1_ratio': 0.09799455604980911}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=10, value=None)


* Best Score for C-index:
 0.7367141722489089

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17958401971222676
Fold 2 IBS: 0.15098312924614873
Fold 3 IBS: 0.1767448712872295
Fold 4 IBS: 0.15363652262238406
Fold 5 IBS: 0.19586936134167535
[I 2024-04-16 00:48:31,294] Trial 0 finished with value: 0.17136358084193287 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.17136358084193287.
Fold 1 IBS: 0.1790606196014541
Fold 2 IBS: 0.1510332528697648
Fold 3 IBS: 0.17701163427407687
Fold 4 IBS: 0.15373342073867732
Fold 5 IBS: 0.19592625650922701
[I 2024-04-16 00:48:31,749] Trial 1 finished with value: 0.17135303679864003 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17896261637309524
Fold 2 IBS: 0.1510401822766344
Fold 3 IBS: 0.17706845641401528
Fold 4 IBS: 0.1537851323347694
Fold 5 IBS: 0.19593137200081384
[I 2024-04-16 00:48:32,362] Trial 2 finished with value: 0.17135755187986565 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17943195434741732
Fold 2 IBS: 0.15102065541550516
Fold 3 IBS: 0.17682916061902562
Fold 4 IBS: 0.15366543260435975
Fold 5 IBS: 0.19582867550753894
[I 2024-04-16 00:48:33,125] Trial 3 finished with value: 0.17135517569876935 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17960183512799482
Fold 2 IBS: 0.1509951964578936
Fold 3 IBS: 0.1767293590712289
Fold 4 IBS: 0.15365586401579356
Fold 5 IBS: 0.1957981263472237
[I 2024-04-16 00:48:33,509] Trial 4 finished with value: 0.1713560762040269 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17925798889324732
Fold 2 IBS: 0.151034843923562
Fold 3 IBS: 0.17692204855950583
Fold 4 IBS: 0.153710289546058
Fold 5 IBS: 0.19592638102542237
[I 2024-04-16 00:48:34,061] Trial 5 finished with value: 0.1713703103895591 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17983920148905785
Fold 2 IBS: 0.15097046228447386
Fold 3 IBS: 0.17660333895466626
Fold 4 IBS: 0.15359580744926207
Fold 5 IBS: 0.19576983830157307
[I 2024-04-16 00:48:34,615] Trial 6 finished with value: 0.17135572969580665 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17957460494575128
Fold 2 IBS: 0.1509699881051861
Fold 3 IBS: 0.17675312252446235
Fold 4 IBS: 0.15364461684480593
Fold 5 IBS: 0.1958605142049161
[I 2024-04-16 00:48:35,211] Trial 7 finished with value: 0.17136056932502436 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17933934618189995
Fold 2 IBS: 0.15102739017345695
Fold 3 IBS: 0.176878534539593
Fold 4 IBS: 0.15368982863107125
Fold 5 IBS: 0.19591927897821157
[I 2024-04-16 00:48:35,758] Trial 8 finished with value: 0.17137087570084658 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.1792152847935157
Fold 2 IBS: 0.1510620294042304
Fold 3 IBS: 0.1769351611792815
Fold 4 IBS: 0.15370333869348557
Fold 5 IBS: 0.19588134861951473
[I 2024-04-16 00:48:36,344] Trial 9 finished with value: 0.1713594325380056 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17872710750782753
Fold 2 IBS: 0.15112552739474236
Fold 3 IBS: 0.17720642357984287
Fold 4 IBS: 0.1539041908802992
Fold 5 IBS: 0.19602702917994355
[I 2024-04-16 00:48:37,173] Trial 10 finished with value: 0.1713980557085311 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17898766722880008
Fold 2 IBS: 0.151085180141335
Fold 3 IBS: 0.17706090721921203
Fold 4 IBS: 0.15378732967378264
Fold 5 IBS: 0.1959066079916271
[I 2024-04-16 00:48:37,728] Trial 11 finished with value: 0.17136553845095134 and parameters: {'l1_ratio': 0.2462088027506373}. Best is trial 1 with value: 0.17135303679864003.
Fold 1 IBS: 0.17906002100930285
Fold 2 IBS: 0.15103280848071154
Fold 3 IBS: 0.17701217084321239
Fold 4 IBS: 0.1537341570793609
Fold 5 IBS: 0.195925641681157
[I 2024-04-16 00:48:38,461] Trial 12 finished with value: 0.17135295981874893 and parameters: {'l1_ratio': 0.2859395773567724}. Best is trial 12 with value: 0.17135295981874893.
Fold 1 IBS: 0.21356143284790244
Fold 2 IBS: 0.22068753797025742
Fold 3 IBS: 0.20461645002201292
Fold 4 IBS: 0.2242265944998006
Fold 5 IBS: 0.21762892895573718
[I 2024-04-16 00:48:38,817] Trial 13 finished with value: 0.21614418885914208 and parameters: {'l1_ratio': 0.00776234166907247}. Best is trial 12 with value: 0.17135295981874893.
Fold 1 IBS: 0.1790464279678608
Fold 2 IBS: 0.15108712977055322
Fold 3 IBS: 0.17702439404053635
Fold 4 IBS: 0.15375106718530637
Fold 5 IBS: 0.19591165110643344
[I 2024-04-16 00:48:39,501] Trial 14 finished with value: 0.17136413401413803 and parameters: {'l1_ratio': 0.2799002900234457}. Best is trial 12 with value: 0.17135295981874893.
Fold 1 IBS: 0.17878398249758562
Fold 2 IBS: 0.15111115381289322
Fold 3 IBS: 0.1771764345956785
Fold 4 IBS: 0.15388363745354122
Fold 5 IBS: 0.19601018458216612
[I 2024-04-16 00:48:40,592] Trial 15 finished with value: 0.17139307858837294 and parameters: {'l1_ratio': 0.13093909067259135}. Best is trial 12 with value: 0.17135295981874893.
Fold 1 IBS: 0.17916548650544048
Fold 2 IBS: 0.15101393890100087
Fold 3 IBS: 0.17695682389598963
Fold 4 IBS: 0.1537060773872057
Fold 5 IBS: 0.19590482390140068
[I 2024-04-16 00:48:41,103] Trial 16 finished with value: 0.17134943011820747 and parameters: {'l1_ratio': 0.3565983398076921}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17943611562980175
Fold 2 IBS: 0.15102333224541722
Fold 3 IBS: 0.17682569454292935
Fold 4 IBS: 0.15366207301300672
Fold 5 IBS: 0.1958326987486858
[I 2024-04-16 00:48:41,608] Trial 17 finished with value: 0.17135598283596817 and parameters: {'l1_ratio': 0.555128421140091}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17913303950994525
Fold 2 IBS: 0.1510575915767241
Fold 3 IBS: 0.17698543609314749
Fold 4 IBS: 0.15373349907139972
Fold 5 IBS: 0.19595222301664897
[I 2024-04-16 00:48:42,296] Trial 18 finished with value: 0.1713723578535731 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17879589211604932
Fold 2 IBS: 0.15111964569679825
Fold 3 IBS: 0.17716507215698757
Fold 4 IBS: 0.15386830672303428
Fold 5 IBS: 0.19594909969775098
[I 2024-04-16 00:48:42,920] Trial 19 finished with value: 0.17137960327812407 and parameters: {'l1_ratio': 0.13327775243322518}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17980476765312264
Fold 2 IBS: 0.1510144402027335
Fold 3 IBS: 0.17662992495824906
Fold 4 IBS: 0.15358834532190035
Fold 5 IBS: 0.19582977009618122
[I 2024-04-16 00:48:43,334] Trial 20 finished with value: 0.17137344964643736 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17911444896837903
Fold 2 IBS: 0.15102700873181177
Fold 3 IBS: 0.17698189335124212
Fold 4 IBS: 0.15371374395891557
Fold 5 IBS: 0.19592014271367927
[I 2024-04-16 00:48:43,918] Trial 21 finished with value: 0.17135144754480555 and parameters: {'l1_ratio': 0.3212333814818189}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17920557458355182
Fold 2 IBS: 0.15105555563135936
Fold 3 IBS: 0.17694362367753294
Fold 4 IBS: 0.15371141431029495
Fold 5 IBS: 0.19587161368596112
[I 2024-04-16 00:48:44,349] Trial 22 finished with value: 0.17135755637774003 and parameters: {'l1_ratio': 0.38618017519954256}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17890604278832153
Fold 2 IBS: 0.15109544560680346
Fold 3 IBS: 0.17710665271177237
Fold 4 IBS: 0.15382571520995303
Fold 5 IBS: 0.19599410670823111
[I 2024-04-16 00:48:44,869] Trial 23 finished with value: 0.17138559260501632 and parameters: {'l1_ratio': 0.1984063647603544}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17934715052509276
Fold 2 IBS: 0.1510324774317719
Fold 3 IBS: 0.1768719048390252
Fold 4 IBS: 0.1536834455774639
Fold 5 IBS: 0.19584301179517385
[I 2024-04-16 00:48:45,539] Trial 24 finished with value: 0.17135559803370554 and parameters: {'l1_ratio': 0.4870294498304153}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17948050321460027
Fold 2 IBS: 0.1509851011034459

Fold 3 IBS: 0.17680302727562638
Fold 4 IBS: 0.15366552174881976
Fold 5 IBS: 0.19587730169037634
[I 2024-04-16 00:48:45,884] Trial 25 finished with value: 0.1713622910065737 and parameters: {'l1_ratio': 0.6017140536891199}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17911828567036817
Fold 2 IBS: 0.15104768249515776
Fold 3 IBS: 0.1769985350004711
Fold 4 IBS: 0.15374697047778124
Fold 5 IBS: 0.1959384481298246
[I 2024-04-16 00:48:46,542] Trial 26 finished with value: 0.17136998435472056 and parameters: {'l1_ratio': 0.331298221798899}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.21310138293856212
Fold 2 IBS: 0.21969880624095167
Fold 3 IBS: 0.177272964741059
Fold 4 IBS: 0.22365673065934433
Fold 5 IBS: 0.19601497940733117
[I 2024-04-16 00:48:46,999] Trial 27 finished with value: 0.20594897279744967 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17887368272381246
Fold 2 IBS: 0.15110187479748358
Fold 3 IBS: 0.17712396663096605
Fold 4 IBS: 0.15383879572952025
Fold 5 IBS: 0.19600140752430745
[I 2024-04-16 00:48:47,746] Trial 28 finished with value: 0.171387945481218 and parameters: {'l1_ratio': 0.17925368748313986}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.179273923834943
Fold 2 IBS: 0.15104532634941925
Fold 3 IBS: 0.1769083297395208
Fold 4 IBS: 0.15369715438196999
Fold 5 IBS: 0.19585915857242453
[I 2024-04-16 00:48:48,622] Trial 29 finished with value: 0.1713567785756555 and parameters: {'l1_ratio': 0.4339129998675763}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1791153731011022
Fold 2 IBS: 0.1510276893643229
Fold 3 IBS: 0.17698107493689677
Fold 4 IBS: 0.15371296617755145
Fold 5 IBS: 0.19592108316950846
[I 2024-04-16 00:48:49,028] Trial 30 finished with value: 0.17135163734987638 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17913417285648703
Fold 2 IBS: 0.15105835493197806
Fold 3 IBS: 0.17698442987993313
Fold 4 IBS: 0.15373253892255256
Fold 5 IBS: 0.19595328254016042
[I 2024-04-16 00:48:49,545] Trial 31 finished with value: 0.17137255582622224 and parameters: {'l1_ratio': 0.33943243474347135}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17905804957714885
Fold 2 IBS: 0.15105298794943567
Fold 3 IBS: 0.17703232876467456
Fold 4 IBS: 0.15377694431375813
Fold 5 IBS: 0.19594327029922207
[I 2024-04-16 00:48:50,075] Trial 32 finished with value: 0.17137271618084787 and parameters: {'l1_ratio': 0.2943836020184171}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17899475956174887
Fold 2 IBS: 0.1510900748092154
Fold 3 IBS: 0.17705442991808057
Fold 4 IBS: 0.15377848556396878
Fold 5 IBS: 0.19591398476771624
[I 2024-04-16 00:48:51,401] Trial 33 finished with value: 0.17136634692414598 and parameters: {'l1_ratio': 0.24889511011995238}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17920836804966034
Fold 2 IBS: 0.15105741790767005
Fold 3 IBS: 0.17694118598251513
Fold 4 IBS: 0.15370908886274265
Fold 5 IBS: 0.19587441621209886
[I 2024-04-16 00:48:52,562] Trial 34 finished with value: 0.1713580954029374 and parameters: {'l1_ratio': 0.3878889128074883}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17889897184767245
Fold 2 IBS: 0.15109050068015148
Fold 3 IBS: 0.17711324495263042
Fold 4 IBS: 0.15383466542174054
Fold 5 IBS: 0.19598722983619343
[I 2024-04-16 00:48:53,437] Trial 35 finished with value: 0.17138492254767765 and parameters: {'l1_ratio': 0.19631609988412568}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17931548087213725
Fold 2 IBS: 0.1510061451451858
Fold 3 IBS: 0.17689752945658885
Fold 4 IBS: 0.15370808957591778
Fold 5 IBS: 0.19589914632186414
[I 2024-04-16 00:48:54,078] Trial 36 finished with value: 0.17136527827433876 and parameters: {'l1_ratio': 0.4644722486947227}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1793985761346956
Fold 2 IBS: 0.15100521942659204
Fold 3 IBS: 0.1768492450458239
Fold 4 IBS: 0.1536848726958033
Fold 5 IBS: 0.1958920461054045
[I 2024-04-16 00:48:54,548] Trial 37 finished with value: 0.17136599188166385 and parameters: {'l1_ratio': 0.5304993409494819}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17949739765834907
Fold 2 IBS: 0.1510034382926601
Fold 3 IBS: 0.17678798062788872
Fold 4 IBS: 0.15365086118330482
Fold 5 IBS: 0.19589337819646446
[I 2024-04-16 00:48:55,017] Trial 38 finished with value: 0.17136661119173344 and parameters: {'l1_ratio': 0.6198989258080023}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17907039037776334
Fold 2 IBS: 0.15106137738875694
Fold 3 IBS: 0.17702118558947394
Fold 4 IBS: 0.15376168187205683
Fold 5 IBS: 0.19595495129417512
[I 2024-04-16 00:48:55,460] Trial 39 finished with value: 0.17137391730444523 and parameters: {'l1_ratio': 0.29991537347265707}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17916015186599338
Fold 2 IBS: 0.15107585121521763
Fold 3 IBS: 0.17696150785667436
Fold 4 IBS: 0.15371068705891666
Fold 5 IBS: 0.1958994363394041
[I 2024-04-16 00:48:55,943] Trial 40 finished with value: 0.17136152686724124 and parameters: {'l1_ratio': 0.35356657874615494}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1790029236053133
Fold 2 IBS: 0.15103220458663316
Fold 3 IBS: 0.17704699595765022
Fold 4 IBS: 0.15376832362104154
Fold 5 IBS: 0.1959224626511894
[I 2024-04-16 00:48:56,531] Trial 41 finished with value: 0.17135458208436552 and parameters: {'l1_ratio': 0.2520520314754908}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17926495840088286
Fold 2 IBS: 0.15103944207837244
Fold 3 IBS: 0.17691602130234357
Fold 4 IBS: 0.15370452127442863
Fold 5 IBS: 0.19593275888675893
[I 2024-04-16 00:48:57,114] Trial 42 finished with value: 0.17137154038855731 and parameters: {'l1_ratio': 0.427819623047467}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17906371218175315
Fold 2 IBS: 0.1510568377653771
Fold 3 IBS: 0.17702720908957426
Fold 4 IBS: 0.1537699345986172
Fold 5 IBS: 0.1959486341122668
[I 2024-04-16 00:48:57,533] Trial 43 finished with value: 0.1713732655495177 and parameters: {'l1_ratio': 0.2968993434364841}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17867588003429655
Fold 2 IBS: 0.15109496574053755
Fold 3 IBS: 0.17722759450408843
Fold 4 IBS: 0.1539096292827876
Fold 5 IBS: 0.19599150243085295
[I 2024-04-16 00:48:58,439] Trial 44 finished with value: 0.1713799143985126 and parameters: {'l1_ratio': 0.062069898702991955}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17894654113566838
Fold 2 IBS: 0.15109173450352198
Fold 3 IBS: 0.17708324447696105
Fold 4 IBS: 0.15380528899606083
Fold 5 IBS: 0.1959145454492854
[I 2024-04-16 00:48:59,008] Trial 45 finished with value: 0.17136827091229953 and parameters: {'l1_ratio': 0.22141233389455595}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1788597203085067
Fold 2 IBS: 0.15105764484832931
Fold 3 IBS: 0.17712529590399964
Fold 4 IBS: 0.15383108906154827
Fold 5 IBS: 0.195950154174355
[I 2024-04-16 00:49:00,073] Trial 46 finished with value: 0.17136478085934778 and parameters: {'l1_ratio': 0.1658975752262637}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17919760038944899
Fold 2 IBS: 0.1510502679353418
Fold 3 IBS: 0.17695052751335866
Fold 4 IBS: 0.15371802518961566
Fold 5 IBS: 0.19594479937959197
[I 2024-04-16 00:49:00,572] Trial 47 finished with value: 0.1713722440814714 and parameters: {'l1_ratio': 0.3814019531259425}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1796900647823447
Fold 2 IBS: 0.15096739547790797
Fold 3 IBS: 0.1766894512769558
Fold 4 IBS: 0.15361230696102846
Fold 5 IBS: 0.19585200957505433
[I 2024-04-16 00:49:01,056] Trial 48 finished with value: 0.17136224561465824 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1792933005955953
Fold 2 IBS: 0.1510581081832907
Fold 3 IBS: 0.17689173410646114
Fold 4 IBS: 0.15368105518608458
Fold 5 IBS: 0.19587835796815356
[I 2024-04-16 00:49:01,557] Trial 49 finished with value: 0.17136051120791707 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 16 with value: 0.17134943011820747.

Fold 1 IBS: 0.17877727213414701
Fold 2 IBS: 0.15109320806775142
Fold 3 IBS: 0.17716574753037861
Fold 4 IBS: 0.15385539803348391
Fold 5 IBS: 0.19598487862985922
[I 2024-04-16 00:49:02,309] Trial 50 finished with value: 0.17137530087912406 and parameters: {'l1_ratio': 0.11338510694936829}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17900900942089837
Fold 2 IBS: 0.15103675947210204
Fold 3 IBS: 0.1770414645060716
Fold 4 IBS: 0.15376075899211938
Fold 5 IBS: 0.1959287812499061
[I 2024-04-16 00:49:03,077] Trial 51 finished with value: 0.1713553547282195 and parameters: {'l1_ratio': 0.2544539865445068}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1790228218571628
Fold 2 IBS: 0.1510470888170803
Fold 3 IBS: 0.1770289703630868
Fold 4 IBS: 0.15374350822619956
Fold 5 IBS: 0.19594307104053688
[I 2024-04-16 00:49:03,547] Trial 52 finished with value: 0.17135709206081323 and parameters: {'l1_ratio': 0.26005323176164424}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17912076458551243
Fold 2 IBS: 0.15103166039372787
Fold 3 IBS: 0.17697630597150507
Fold 4 IBS: 0.15376387249195012
Fold 5 IBS: 0.19592656634760208
[I 2024-04-16 00:49:04,114] Trial 53 finished with value: 0.1713638339580595 and parameters: {'l1_ratio': 0.3245134031404312}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17895327751841517
Fold 2 IBS: 0.1510964150649718
Fold 3 IBS: 0.17707703833061852
Fold 4 IBS: 0.15379683542308284
Fold 5 IBS: 0.19592160115546445
[I 2024-04-16 00:49:04,601] Trial 54 finished with value: 0.17136903349851057 and parameters: {'l1_ratio': 0.22369412830424654}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17882287021127236
Fold 2 IBS: 0.1511167543485648
Fold 3 IBS: 0.17714928170453814
Fold 4 IBS: 0.15385488888812723
Fold 5 IBS: 0.19594599203774138
[I 2024-04-16 00:49:05,101] Trial 55 finished with value: 0.1713779574380488 and parameters: {'l1_ratio': 0.14780977803797543}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17917614350198846
Fold 2 IBS: 0.15103595532913286
Fold 3 IBS: 0.17696939349655313
Fold 4 IBS: 0.15373600648103528
Fold 5 IBS: 0.19592491166935277
[I 2024-04-16 00:49:05,499] Trial 56 finished with value: 0.1713684820956125 and parameters: {'l1_ratio': 0.36898496105598644}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17923663664227887
Fold 2 IBS: 0.15101024546140912
Fold 3 IBS: 0.17691665609864912
Fold 4 IBS: 0.15373271438587385
Fold 5 IBS: 0.19590269386959444
[I 2024-04-16 00:49:05,946] Trial 57 finished with value: 0.1713597892915611 and parameters: {'l1_ratio': 0.4059732750610126}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17903081692384262
Fold 2 IBS: 0.15107643597471052
Fold 3 IBS: 0.1770385053175196
Fold 4 IBS: 0.15377039279817573
Fold 5 IBS: 0.19597355292699203
[I 2024-04-16 00:49:06,648] Trial 58 finished with value: 0.1713779407882481 and parameters: {'l1_ratio': 0.27324063246047037}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17909882379666853
Fold 2 IBS: 0.15108066804153314
Fold 3 IBS: 0.17699578011076803
Fold 4 IBS: 0.15372692751236525
Fold 5 IBS: 0.19590420888488297
[I 2024-04-16 00:49:07,308] Trial 59 finished with value: 0.17136128166924358 and parameters: {'l1_ratio': 0.3133639402655621}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1788946790429982
Fold 2 IBS: 0.15108749833223994
Fold 3 IBS: 0.17711725607938167
Fold 4 IBS: 0.15384010800946105
Fold 5 IBS: 0.19598304943708894
[I 2024-04-16 00:49:07,921] Trial 60 finished with value: 0.17138451818023395 and parameters: {'l1_ratio': 0.1950658437270253}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1793770855448283
Fold 2 IBS: 0.15105195719247058
Fold 3 IBS: 0.1768467134273403
Fold 4 IBS: 0.15370392554206072
Fold 5 IBS: 0.19587224219973237
[I 2024-04-16 00:49:08,491] Trial 61 finished with value: 0.17137038478128647 and parameters: {'l1_ratio': 0.5115019231013023}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17948489705447024
Fold 2 IBS: 0.15099484256773296
Fold 3 IBS: 0.17679911570296883
Fold 4 IBS: 0.15366171387513644
Fold 5 IBS: 0.19588147650317686
[I 2024-04-16 00:49:09,187] Trial 62 finished with value: 0.1713644091406971 and parameters: {'l1_ratio': 0.6063370210443361}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17914753475514522
Fold 2 IBS: 0.15106735290147819
Fold 3 IBS: 0.17697262913329773
Fold 4 IBS: 0.153721281750557
Fold 5 IBS: 0.1958866624887361
[I 2024-04-16 00:49:09,907] Trial 63 finished with value: 0.17135909220584283 and parameters: {'l1_ratio': 0.34657244276013355}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17897753764213586
Fold 2 IBS: 0.1510514144773027
Fold 3 IBS: 0.1770548176847602
Fold 4 IBS: 0.15376636743408206
Fold 5 IBS: 0.19594693644931938
[I 2024-04-16 00:49:10,666] Trial 64 finished with value: 0.17135941473752006 and parameters: {'l1_ratio': 0.23226828107524009}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17956739151146883
Fold 2 IBS: 0.15103574483780932
Fold 3 IBS: 0.17674661365752858
Fold 4 IBS: 0.153650832572444
Fold 5 IBS: 0.1958537271023772
[I 2024-04-16 00:49:11,195] Trial 65 finished with value: 0.17137086193632559 and parameters: {'l1_ratio': 0.6761835762994113}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17945633321339496
Fold 2 IBS: 0.15103630821533653
Fold 3 IBS: 0.17680899170656375
Fold 4 IBS: 0.15368953524227713
Fold 5 IBS: 0.19585216109209608
[I 2024-04-16 00:49:11,666] Trial 66 finished with value: 0.17136866589393368 and parameters: {'l1_ratio': 0.5740790887539559}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17924135692714321
Fold 2 IBS: 0.15101365869026084
Fold 3 IBS: 0.17694104280427503
Fold 4 IBS: 0.15372844509167763
Fold 5 IBS: 0.19590632888661427
[I 2024-04-16 00:49:12,356] Trial 67 finished with value: 0.1713661664799942 and parameters: {'l1_ratio': 0.40913967667629036}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17935753287820355
Fold 2 IBS: 0.15103921428406644
Fold 3 IBS: 0.17686315302048064
Fold 4 IBS: 0.15371419133408065
Fold 5 IBS: 0.19585314033420734
[I 2024-04-16 00:49:12,805] Trial 68 finished with value: 0.1713654463702077 and parameters: {'l1_ratio': 0.49524928097076193}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1787148939792497
Fold 2 IBS: 0.15108782008985663
Fold 3 IBS: 0.1772052177576678
Fold 4 IBS: 0.1538920842979843
Fold 5 IBS: 0.1959837987312717
[I 2024-04-16 00:49:13,429] Trial 69 finished with value: 0.17137676297120602 and parameters: {'l1_ratio': 0.08305411096963486}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17903897919707581
Fold 2 IBS: 0.1510820279134694
Fold 3 IBS: 0.17703111654735373
Fold 4 IBS: 0.15376027955600519
Fold 5 IBS: 0.19590397228880319
[I 2024-04-16 00:49:13,856] Trial 70 finished with value: 0.17136327510054147 and parameters: {'l1_ratio': 0.27668726816381456}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1790128326240647
Fold 2 IBS: 0.15103961840373614
Fold 3 IBS: 0.1770379995067463
Fold 4 IBS: 0.15375601774168227
Fold 5 IBS: 0.19593274139256078
[I 2024-04-16 00:49:14,388] Trial 71 finished with value: 0.17135584193375802 and parameters: {'l1_ratio': 0.25598229481397594}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17910481539450504
Fold 2 IBS: 0.15101991397417397
Fold 3 IBS: 0.17699044208319495
Fold 4 IBS: 0.15372198935898962
Fold 5 IBS: 0.1959103309283278
[I 2024-04-16 00:49:14,949] Trial 72 finished with value: 0.17134949834783825 and parameters: {'l1_ratio': 0.31634244778559384}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17916954650071623
Fold 2 IBS: 0.1510169028297287
Fold 3 IBS: 0.17695326544641485
Fold 4 IBS: 0.15370268954171698
Fold 5 IBS: 0.1959089177034057
[I 2024-04-16 00:49:15,445] Trial 73 finished with value: 0.1713502644043965 and parameters: {'l1_ratio': 0.3589369118813811}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17910978247655432
Fold 2 IBS: 0.15102357193353502
Fold 3 IBS: 0.17698603041921168
Fold 4 IBS: 0.15371767453560872

Fold 5 IBS: 0.1959153936247194
[I 2024-04-16 00:49:15,934] Trial 74 finished with value: 0.17135049059792581 and parameters: {'l1_ratio': 0.3188475466506644}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.1791177750325778
Fold 2 IBS: 0.15102945844501012
Fold 3 IBS: 0.17697894913260018
Fold 4 IBS: 0.15371094557817447
Fold 5 IBS: 0.1959235266963892
[I 2024-04-16 00:49:16,328] Trial 75 finished with value: 0.17135213097695035 and parameters: {'l1_ratio': 0.3229533747185797}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17917381462126708
Fold 2 IBS: 0.15102001885648014
Fold 3 IBS: 0.1769495304715724
Fold 4 IBS: 0.15374755942208862
Fold 5 IBS: 0.19591322044019194
[I 2024-04-16 00:49:16,818] Trial 76 finished with value: 0.17136082876232006 and parameters: {'l1_ratio': 0.3614250298741148}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17930603170952508
Fold 2 IBS: 0.1509993843802153
Fold 3 IBS: 0.17688087927573307
Fold 4 IBS: 0.15371657518046836
Fold 5 IBS: 0.19589092434228003
[I 2024-04-16 00:49:17,246] Trial 77 finished with value: 0.17135875897764435 and parameters: {'l1_ratio': 0.45719203042355566}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17910857226689175
Fold 2 IBS: 0.15102268066536484
Fold 3 IBS: 0.17698710453207064
Fold 4 IBS: 0.15371869473894925
Fold 5 IBS: 0.19591416059365013
[I 2024-04-16 00:49:17,639] Trial 78 finished with value: 0.1713502425593853 and parameters: {'l1_ratio': 0.3182339463139639}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17911479584554907
Fold 2 IBS: 0.15102726420924426
Fold 3 IBS: 0.1769815861221011
Fold 4 IBS: 0.15371345199159236
Fold 5 IBS: 0.19592049573861897
[I 2024-04-16 00:49:18,294] Trial 79 finished with value: 0.17135151878142113 and parameters: {'l1_ratio': 0.3214119979467087}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17924500271473567
Fold 2 IBS: 0.15101629508315714
Fold 3 IBS: 0.17693759430841954
Fold 4 IBS: 0.15372515132697212
Fold 5 IBS: 0.1959099641594492
[I 2024-04-16 00:49:18,855] Trial 80 finished with value: 0.17136680151854675 and parameters: {'l1_ratio': 0.41161572835701826}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17911094230597652
Fold 2 IBS: 0.1510244261113618
Fold 3 IBS: 0.17698500148674312
Fold 4 IBS: 0.15371669712997194
Fold 5 IBS: 0.19591657503886123
[I 2024-04-16 00:49:19,298] Trial 81 finished with value: 0.1713507284145829 and parameters: {'l1_ratio': 0.319437581035919}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17907947962446738
Fold 2 IBS: 0.15106752508630794
Fold 3 IBS: 0.17701308121309178
Fold 4 IBS: 0.15375052804784903
Fold 5 IBS: 0.195963492979012
[I 2024-04-16 00:49:19,643] Trial 82 finished with value: 0.17137482139014565 and parameters: {'l1_ratio': 0.30408772848295035}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17918566036310274
Fold 2 IBS: 0.15104230432348337
Fold 3 IBS: 0.1769610067910702
Fold 4 IBS: 0.153728009438133
Fold 5 IBS: 0.1959337439234148
[I 2024-04-16 00:49:20,063] Trial 83 finished with value: 0.1713701449678408 and parameters: {'l1_ratio': 0.37440253375121735}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17914322650660025
Fold 2 IBS: 0.15106445193394996
Fold 3 IBS: 0.17697643705436478
Fold 4 IBS: 0.15372490674608777
Fold 5 IBS: 0.19588229603247873
[I 2024-04-16 00:49:20,617] Trial 84 finished with value: 0.1713582636546963 and parameters: {'l1_ratio': 0.3442414028089386}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17905688426565036
Fold 2 IBS: 0.1510304798457873
Fold 3 IBS: 0.17701498459534923
Fold 4 IBS: 0.1537381648092306
Fold 5 IBS: 0.1959224186138088
[I 2024-04-16 00:49:21,206] Trial 85 finished with value: 0.17135258642596526 and parameters: {'l1_ratio': 0.2845261545049097}. Best is trial 16 with value: 0.17134943011820747.
Fold 1 IBS: 0.17910448388257216
Fold 2 IBS: 0.15101966984360338
Fold 3 IBS: 0.17699073682382888
Fold 4 IBS: 0.15372226395448674
Fold 5 IBS: 0.1959099928514107
[I 2024-04-16 00:49:21,774] Trial 86 finished with value: 0.17134942947118037 and parameters: {'l1_ratio': 0.31617649869393666}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17920505456767985
Fold 2 IBS: 0.15105520889778373
Fold 3 IBS: 0.1769440480419977
Fold 4 IBS: 0.1537118474014786
Fold 5 IBS: 0.19587109180923715
[I 2024-04-16 00:49:22,380] Trial 87 finished with value: 0.1713574501436354 and parameters: {'l1_ratio': 0.3858635650528154}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17926667423720777
Fold 2 IBS: 0.15104057399527107
Fold 3 IBS: 0.1769145398550067
Fold 4 IBS: 0.1537031028697864
Fold 5 IBS: 0.19593432761392549
[I 2024-04-16 00:49:22,706] Trial 88 finished with value: 0.17137184371423947 and parameters: {'l1_ratio': 0.42897977787413566}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.1791511829670689
Fold 2 IBS: 0.15106980948913398
Fold 3 IBS: 0.17696940947201484
Fold 4 IBS: 0.15371821554825216
Fold 5 IBS: 0.1958903569940928
[I 2024-04-16 00:49:23,180] Trial 89 finished with value: 0.17135979489411252 and parameters: {'l1_ratio': 0.34856838422667125}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17894048371407745
Fold 2 IBS: 0.15106509338833335
Fold 3 IBS: 0.17707479996849296
Fold 4 IBS: 0.15378222123725757
Fold 5 IBS: 0.1959545838421545
[I 2024-04-16 00:49:23,674] Trial 90 finished with value: 0.1713634364300632 and parameters: {'l1_ratio': 0.2091740804277522}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17910015566399717
Fold 2 IBS: 0.15108157271505335
Fold 3 IBS: 0.17699459362924255
Fold 4 IBS: 0.1537258337121951
Fold 5 IBS: 0.19590556857030475
[I 2024-04-16 00:49:24,075] Trial 91 finished with value: 0.17136154485815858 and parameters: {'l1_ratio': 0.31402106867869894}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17911193611836496
Fold 2 IBS: 0.15104340409638325
Fold 3 IBS: 0.1770042121163997
Fold 4 IBS: 0.153754767655252
Fold 5 IBS: 0.19593248833903862
[I 2024-04-16 00:49:24,588] Trial 92 finished with value: 0.1713693616650877 and parameters: {'l1_ratio': 0.32813430852510034}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17906729076848144
Fold 2 IBS: 0.15103820569688728
Fold 3 IBS: 0.17700566268688622
Fold 4 IBS: 0.15372522262552774
Fold 5 IBS: 0.19593310096362032
[I 2024-04-16 00:49:25,056] Trial 93 finished with value: 0.1713538965482806 and parameters: {'l1_ratio': 0.2892637405274299}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.1791771090347787
Fold 2 IBS: 0.15103659952822834
Fold 3 IBS: 0.17696854118150504
Fold 4 IBS: 0.15373519401761665
Fold 5 IBS: 0.19592580857552927
[I 2024-04-16 00:49:25,520] Trial 94 finished with value: 0.17136865046753164 and parameters: {'l1_ratio': 0.3695282579676198}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17897609485126217
Fold 2 IBS: 0.15107719173580866
Fold 3 IBS: 0.1770715146911247
Fold 4 IBS: 0.15380179837112767
Fold 5 IBS: 0.19597247236831894
[I 2024-04-16 00:49:26,008] Trial 95 finished with value: 0.17137981440352842 and parameters: {'l1_ratio': 0.24193380638008483}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17922182915511956
Fold 2 IBS: 0.15106639568374347
Fold 3 IBS: 0.17692946991239933
Fold 4 IBS: 0.1537461382008968
Fold 5 IBS: 0.19588790725493202
[I 2024-04-16 00:49:26,599] Trial 96 finished with value: 0.1713703480414182 and parameters: {'l1_ratio': 0.3963191481012885}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17902865014238184
Fold 2 IBS: 0.15107495141005253
Fold 3 IBS: 0.17704047067998993
Fold 4 IBS: 0.1537730813610415
Fold 5 IBS: 0.19597149151062
[I 2024-04-16 00:49:26,968] Trial 97 finished with value: 0.17137772902081716 and parameters: {'l1_ratio': 0.27233839004300403}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17907289828973608
Fold 2 IBS: 0.15106305215017568
Fold 3 IBS: 0.17701896707471865
Fold 4 IBS: 0.15375864080391846
Fold 5 IBS: 0.1959572797334884
[I 2024-04-16 00:49:27,357] Trial 98 finished with value: 0.17137416761040744 and parameters: {'l1_ratio': 0.30104185652341775}. Best is trial 86 with value: 0.17134942947118037.
Fold 1 IBS: 0.17885681120253602

Fold 2 IBS: 0.15109000931956318
Fold 3 IBS: 0.17713983113321774
Fold 4 IBS: 0.15386028475603727
Fold 5 IBS: 0.19598488937913855
[I 2024-04-16 00:49:27,751] Trial 99 finished with value: 0.17138636515809855 and parameters: {'l1_ratio': 0.17481454265540544}. Best is trial 86 with value: 0.17134942947118037.


* Best trial for IBS:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.17134942947118037], datetime_start=datetime.datetime(2024, 4, 16, 0, 49, 21, 212099), datetime_complete=datetime.datetime(2024, 4, 16, 0, 49, 21, 773188), params={'l1_ratio': 0.31617649869393666}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=86, value=None)


* Best Score for IBS:
 0.17134942947118037

In [42]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.737
train_ibs:  0.171

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.09799455604980911)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.31617649869393666)

test_ibs:  0.257

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:49:28,289] A new study created in memory with name: no-name-de583c67-596e-4471-bf45-c99c399fac31

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 00:49:33,018] Trial 0 finished with value: 0.7575203363732566 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 00:49:37,392] Trial 1 finished with value: 0.750478431579118 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:49:40,507] Trial 2 finished with value: 0.7520712510356254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:49:41,372] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:49:42,582] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 00:49:47,812] Trial 5 finished with value: 0.7462602486577217 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 00:49:54,904] Trial 6 finished with value: 0.7576976783760393 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:49:57,419] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 00:50:04,801] Trial 8 finished with value: 0.5380281690140845 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 00:50:08,613] Trial 9 finished with value: 0.748452073539184 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:50:09,037] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.40740851493126695, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:50:13,640] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.11379276107227315, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:50:21,670] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 00:50:24,700] Trial 13 finished with value: 0.7581182539062076 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 13 with value: 0.7581182539062076.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 00:50:25,521] Trial 14 finished with value: 0.7907144637948861 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0992244164616675, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 00:50:26,194] Trial 15 finished with value: 0.7816150812624114 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.8147833133306369, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 00:50:26,371] Trial 16 finished with value: 0.765813594477808 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.8484814588885312, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08082385841318356, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.

Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 00:50:27,203] Trial 17 finished with value: 0.7851258260885514 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16544550098450153, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 00:50:28,286] Trial 18 finished with value: 0.7834440402483949 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13294582901895255, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 00:50:29,141] Trial 19 finished with value: 0.7742809868075984 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9945705745432233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09964492104707659, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:50:29,520] Trial 20 finished with value: 0.7628622503029641 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.8673418291441284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37827446502466894, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 00:50:30,050] Trial 21 finished with value: 0.7872501961326841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.9624638447657676, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.8051643192488263
[I 2024-04-16 00:50:30,227] Trial 22 finished with value: 0.7873570802451841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.9336744347879812, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19282610776605333, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7488262910798122
[I 2024-04-16 00:50:30,409] Trial 23 finished with value: 0.7541962121280221 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.6843026151576985, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2504370920378234, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 00:50:30,672] Trial 24 finished with value: 0.7858778057568998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 50, 'oob_score': True, 'max_samples': 0.8085053499703132, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17035312846001988, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 00:50:31,659] Trial 25 finished with value: 0.7899316539935477 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.9171920870810285, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07664126778540013, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 00:50:32,369] Trial 26 finished with value: 0.7817663440763265 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.8983378428295576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06306617081281016, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 00:50:33,286] Trial 27 finished with value: 0.7856141531151757 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.7989579262543244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09596584472346859, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 00:50:34,285] Trial 28 finished with value: 0.7853982513847043 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.5360953547457009, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014347840876196644, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 00:50:34,520] Trial 29 finished with value: 0.7695772354631409 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.6977978899499365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2196223213316708, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 00:50:35,171] Trial 30 finished with value: 0.7981448890436417 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 82, 'oob_score': True, 'max_samples': 0.7311645169232817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.059569167808063095, 'warm_start': True}. Best is trial 30 with value: 0.7981448890436417.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 00:50:35,896] Trial 31 finished with value: 0.7982641653072841 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.745146001885883, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05174429879930956, 'warm_start': True}. Best is trial 31 with value: 0.7982641653072841.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7742616033755274
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:50:36,394] Trial 32 finished with value: 0.8032544311992128 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.7397628776532771, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04641084093066284, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:50:37,066] Trial 33 finished with value: 0.7999277380363321 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.7321956680996766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0042513284435347215, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 00:50:37,472] Trial 34 finished with value: 0.7980620370159766 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 74, 'oob_score': True, 'max_samples': 0.7190350277691129, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002617826444773601, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 00:50:37,757] Trial 35 finished with value: 0.8195885025512174 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.6491391650041388, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04473837361201603, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 00:50:38,275] Trial 36 finished with value: 0.8149421898615685 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6500614805101094, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.042163225365865975, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 00:50:38,965] Trial 37 finished with value: 0.8201548198575692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.6316988824284715, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03372830367211485, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 00:50:39,574] Trial 38 finished with value: 0.7864200685622795 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6475925530300135, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1261541633669147, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 00:50:40,392] Trial 39 finished with value: 0.7994601394099836 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.5500795764120797, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0407216828679674, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 00:50:41,167] Trial 40 finished with value: 0.8144744547521597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.5974594004293988, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03731085344043298, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 00:50:41,807] Trial 41 finished with value: 0.8146670383091891 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.5688957234666421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.038323603584419504, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 00:50:42,731] Trial 42 finished with value: 0.8217769675659046 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.565436601526051, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03253349071458341, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 00:50:44,013] Trial 43 finished with value: 0.8194179790264864 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.5414105158165579, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02824952898790397, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 00:50:44,724] Trial 44 finished with value: 0.7844759249669818 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.4812619709263958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0734121445676241, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 00:50:45,575] Trial 45 finished with value: 0.7812420451089397 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.4132359110524421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10574093555624242, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 00:50:48,719] Trial 46 finished with value: 0.742796454430003 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 277, 'oob_score': False, 'max_samples': 0.6435530257070258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02588599089196765, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 00:50:49,387] Trial 47 finished with value: 0.8020413535841735 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.513428105668999, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005073560345181239, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 00:50:51,652] Trial 48 finished with value: 0.7605416340753064 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.4250487747986099, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07826456635516901, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:50:52,399] Trial 49 finished with value: 0.7646180284055469 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.3288612699820465, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11977607788857622, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:50:53,068] Trial 50 finished with value: 0.7516085439508142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.6056621314066971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27891660351802283, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 00:50:53,613] Trial 51 finished with value: 0.8156329206993581 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.5653247525904954, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024675273648228607, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 00:50:54,258] Trial 52 finished with value: 0.8105679483498613 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.668807800129283, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023886857070088842, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:50:55,048] Trial 53 finished with value: 0.8092844755529726 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.5049892673780266, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0302062450326431, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 00:50:55,968] Trial 54 finished with value: 0.7837218500992189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 223, 'oob_score': False, 'max_samples': 0.5694355594036941, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08503386755881623, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:50:56,994] Trial 55 finished with value: 0.8023260161047514 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.6230580876154783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06106714571926695, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 00:50:58,936] Trial 56 finished with value: 0.7505163979885541 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.37386377532060755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020276597591653404, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 00:50:59,580] Trial 57 finished with value: 0.7370660000414045 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 265, 'oob_score': False, 'max_samples': 0.673626054002652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.32552397591019333, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:51:00,460] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.5859997242165991, 'max_features': None, 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 00:51:00,970] Trial 59 finished with value: 0.7738001567018483 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.4578032212133656, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14288340865089383, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:51:04,531] Trial 60 finished with value: 0.7576418826254305 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.5248616932098589, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09178626486905285, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 00:51:05,362] Trial 61 finished with value: 0.8121405300073643 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.5673407402421513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04324260858798204, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:51:06,084] Trial 62 finished with value: 0.8048963624250977 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.6136771186690915, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.061141393518585746, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:51:06,673] Trial 63 finished with value: 0.8129059673027221 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.5632723911430406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03896879562886681, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 00:51:07,742] Trial 64 finished with value: 0.8200972064136438 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.4849644523201697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015459623887936643, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 00:51:08,592] Trial 65 finished with value: 0.8200556403698938 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.4915234805630325, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01325985667696578, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 00:51:09,222] Trial 66 finished with value: 0.7991290530701981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.44421584072665865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01688809895377827, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 00:51:09,887] Trial 67 finished with value: 0.8455736642377335 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 00:51:11,044] Trial 68 finished with value: 0.8406053556611222 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'max_samples': 0.49738412507640734, 'max_features': None, 'min_weight_fraction_leaf': 0.002433553898016293, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 00:51:12,063] Trial 69 finished with value: 0.8316567836473476 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.38288786338976266, 'max_features': None, 'min_weight_fraction_leaf': 0.010924103557748996, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 00:51:13,536] Trial 70 finished with value: 0.8325253087831349 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.3768797583243322, 'max_features': None, 'min_weight_fraction_leaf': 0.007358190561024822, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 00:51:15,183] Trial 71 finished with value: 0.8074401022098655 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.2977376592001145, 'max_features': None, 'min_weight_fraction_leaf': 0.007777034521166985, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 00:51:16,422] Trial 72 finished with value: 0.8207621073356813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3758248033560092, 'max_features': None, 'min_weight_fraction_leaf': 0.0021403509786410697, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 00:51:18,169] Trial 73 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.37703659520841803, 'max_features': None, 'min_weight_fraction_leaf': 0.0030355880739053242, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 00:51:19,691] Trial 74 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.37759120849945615, 'max_features': None, 'min_weight_fraction_leaf': 0.005738060589732854, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 00:51:20,680] Trial 75 finished with value: 0.8064988630989438 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3512499599110515, 'max_features': None, 'min_weight_fraction_leaf': 0.0016091095350437782, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:51:21,510] Trial 76 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.2200825864677213, 'max_features': None, 'min_weight_fraction_leaf': 0.3808353622830714, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 00:51:22,529] Trial 77 finished with value: 0.7898601663797173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.38697496089808264, 'max_features': None, 'min_weight_fraction_leaf': 0.0678874889911297, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 00:51:23,308] Trial 78 finished with value: 0.7983796631750157 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.2971389951907717, 'max_features': None, 'min_weight_fraction_leaf': 0.0014283193772283813, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 00:51:24,127] Trial 79 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.3832306547359522, 'max_features': None, 'min_weight_fraction_leaf': 0.001325860823554314, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 00:51:27,611] Trial 80 finished with value: 0.7638486802036979 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.2259926589326255, 'max_features': None, 'min_weight_fraction_leaf': 0.051988057609908274, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 00:51:28,828] Trial 81 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.3902826764643792, 'max_features': None, 'min_weight_fraction_leaf': 0.01424010512203431, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 00:51:30,066] Trial 82 finished with value: 0.8037666314114749 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.35665467332899853, 'max_features': None, 'min_weight_fraction_leaf': 0.02723621966149422, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 00:51:30,997] Trial 83 finished with value: 0.7910748783864995 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.27364682713049737, 'max_features': None, 'min_weight_fraction_leaf': 0.003437924737021262, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 00:51:32,096] Trial 84 finished with value: 0.7981013668372744 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.42217891643501637, 'max_features': None, 'min_weight_fraction_leaf': 0.05691895142137581, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 00:51:33,371] Trial 85 finished with value: 0.8142696016233687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.44215445453616553, 'max_features': None, 'min_weight_fraction_leaf': 0.015948474032128478, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 00:51:34,403] Trial 86 finished with value: 0.8039740360073753 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 467, 'oob_score': False, 'max_samples': 0.34536985759892425, 'max_features': None, 'min_weight_fraction_leaf': 0.03379453130696234, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 00:51:35,273] Trial 87 finished with value: 0.8009672435320422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3948765985014735, 'max_features': None, 'min_weight_fraction_leaf': 0.049452906101561514, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 00:51:36,064] Trial 88 finished with value: 0.7958162763557586 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.3168310392190445, 'max_features': None, 'min_weight_fraction_leaf': 0.011197201541028177, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 00:51:37,064] Trial 89 finished with value: 0.8188472945459484 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.46056239467229443, 'max_features': None, 'min_weight_fraction_leaf': 0.02927897429150622, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 00:51:37,899] Trial 90 finished with value: 0.8280743039205017 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3677724129924504, 'max_features': None, 'min_weight_fraction_leaf': 0.0015288688784384722, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 00:51:38,665] Trial 91 finished with value: 0.8315449166262722 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.37527324355860175, 'max_features': None, 'min_weight_fraction_leaf': 0.00032873883511814225, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:51:39,544] Trial 92 finished with value: 0.8152302082764418 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.36969362389667315, 'max_features': None, 'min_weight_fraction_leaf': 0.020344390663164187, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 00:51:40,296] Trial 93 finished with value: 0.8013473051581448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.3234854377137636, 'max_features': None, 'min_weight_fraction_leaf': 0.034235535617443455, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 00:51:41,309] Trial 94 finished with value: 0.8317597304647398 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.40292152817878885, 'max_features': None, 'min_weight_fraction_leaf': 0.0013715257783006587, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 00:51:42,371] Trial 95 finished with value: 0.8054182483946754 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.43651122516239244, 'max_features': None, 'min_weight_fraction_leaf': 0.0516435889873805, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 00:51:43,203] Trial 96 finished with value: 0.781897576085816 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.40560294670004454, 'max_features': None, 'min_weight_fraction_leaf': 0.0001044161694674754, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 00:51:43,870] Trial 97 finished with value: 0.8076329995928095 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.33588267636278435, 'max_features': None, 'min_weight_fraction_leaf': 0.019808016366776694, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 00:51:46,569] Trial 98 finished with value: 0.7563224015679627 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.4120109800767605, 'max_features': None, 'min_weight_fraction_leaf': 0.0696147483073608, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.

[I 2024-04-16 00:51:47,482] A new study created in memory with name: no-name-06494c9c-09bb-43fb-b875-ef1dd112a692

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 00:51:47,473] Trial 99 finished with value: 0.81879604728486 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.4642145775222535, 'max_features': None, 'min_weight_fraction_leaf': 0.04423293101031651, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.


* Best trial for C-index:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.8455736642377335], datetime_start=datetime.datetime(2024, 4, 16, 0, 51, 9, 229372), datetime_complete=datetime.datetime(2024, 4, 16, 0, 51, 9, 887148), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=67, value=None)


* Best Score for C-index:
 0.8455736642377335

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16912942286746
Fold 2 IBS: 0.15736700168879125
Fold 3 IBS: 0.17596810644035646
Fold 4 IBS: 0.21476462245142444
Fold 5 IBS: 0.18140709105634753
[I 2024-04-16 00:51:49,975] Trial 0 finished with value: 0.17972724890087594 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.17972724890087594.
Fold 1 IBS: 0.1695457408702072
Fold 2 IBS: 0.15431589011481192
Fold 3 IBS: 0.17931251537071569
Fold 4 IBS: 0.19778743079510175
Fold 5 IBS: 0.1838708756319808
[I 2024-04-16 00:51:50,623] Trial 1 finished with value: 0.1769664905565635 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-16 00:51:51,083] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-16 00:51:52,786] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-16 00:51:54,039] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.18261661077179908
Fold 2 IBS: 0.14215438755582593
Fold 3 IBS: 0.19825307809201306
Fold 4 IBS: 0.1894541695729735
Fold 5 IBS: 0.17258301646825175
[I 2024-04-16 00:51:56,165] Trial 5 finished with value: 0.17701225249217267 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.1793072949109339
Fold 2 IBS: 0.17146943238736864
Fold 3 IBS: 0.1801865051168754
Fold 4 IBS: 0.2169078691801737
Fold 5 IBS: 0.1927889640697635
[I 2024-04-16 00:51:57,999] Trial 6 finished with value: 0.18813201313302302 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.20628331122669447
Fold 2 IBS: 0.20810768242984765
Fold 3 IBS: 0.196178000210441
Fold 4 IBS: 0.21720909429106852
Fold 5 IBS: 0.2120048382129915
[I 2024-04-16 00:51:59,972] Trial 7 finished with value: 0.2079565852742086 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-16 00:52:03,098] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17251108291109596
Fold 2 IBS: 0.16372104609445076
Fold 3 IBS: 0.1752499545194017
Fold 4 IBS: 0.19923941269775702
Fold 5 IBS: 0.1807428948937162
[I 2024-04-16 00:52:03,759] Trial 9 finished with value: 0.17829287822328432 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2138914608019449
Fold 2 IBS: 0.22021134435777845
Fold 3 IBS: 0.20482550997958907
Fold 4 IBS: 0.22548051560881624
Fold 5 IBS: 0.21733795012904839
[I 2024-04-16 00:52:04,727] Trial 10 finished with value: 0.2163493561754354 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17089799911696577
Fold 2 IBS: 0.1343759168934981
Fold 3 IBS: 0.18019414575478068
Fold 4 IBS: 0.19691489378360008
Fold 5 IBS: 0.17134875048281803
[I 2024-04-16 00:52:04,861] Trial 11 finished with value: 0.17074634120633253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1938573372077058
Fold 2 IBS: 0.15264524705837576
Fold 3 IBS: 0.1835875292339129
Fold 4 IBS: 0.19186721611439267
Fold 5 IBS: 0.17242006747034438
[I 2024-04-16 00:52:05,048] Trial 12 finished with value: 0.17887547941694631 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.7748822387405266, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020197386275102834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1753396733634442
Fold 2 IBS: 0.14659590196214217
Fold 3 IBS: 0.18564941996432435
Fold 4 IBS: 0.19697957764971377
Fold 5 IBS: 0.1760898132139911
[I 2024-04-16 00:52:05,890] Trial 13 finished with value: 0.17613087723072313 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 110, 'oob_score': False, 'max_samples': 0.9282504676473301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18437150857335638
Fold 2 IBS: 0.13940627158607374
Fold 3 IBS: 0.19735408203235827
Fold 4 IBS: 0.19502160042084687
Fold 5 IBS: 0.17327657876201488
[I 2024-04-16 00:52:06,861] Trial 14 finished with value: 0.17788600827493004 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.9418551640023243, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1903120334095733
Fold 2 IBS: 0.13604392965192902
Fold 3 IBS: 0.20770281014511405
Fold 4 IBS: 0.21649791040859048
Fold 5 IBS: 0.17399213158709487
[I 2024-04-16 00:52:06,979] Trial 15 finished with value: 0.18490976304046036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.9969315225031997, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10400906232299456}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.17234717281067394
Fold 2 IBS: 0.168695961879054
Fold 3 IBS: 0.17428134482390595
Fold 4 IBS: 0.20512326820357737
Fold 5 IBS: 0.1858777602458117
[I 2024-04-16 00:52:07,389] Trial 16 finished with value: 0.1812651015926046 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.8254434867518305, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27558800117237026}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1701072167867666
Fold 2 IBS: 0.15066297678714172
Fold 3 IBS: 0.18453320195882447
Fold 4 IBS: 0.19299945063741186
Fold 5 IBS: 0.17720564069954053
[I 2024-04-16 00:52:09,944] Trial 17 finished with value: 0.17510169737393705 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.7509985501856506, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0026257659295356476}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18294194940487038
Fold 2 IBS: 0.14058077366331193
Fold 3 IBS: 0.19786106053237812
Fold 4 IBS: 0.19006278490632897
Fold 5 IBS: 0.17207512016650234
[I 2024-04-16 00:52:13,159] Trial 18 finished with value: 0.17670433773467834 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16955416166590404
Fold 2 IBS: 0.15212211732759853
Fold 3 IBS: 0.18191729427832115
Fold 4 IBS: 0.1920689530206985
Fold 5 IBS: 0.1791048456801592
[I 2024-04-16 00:52:16,309] Trial 19 finished with value: 0.1749534743945363 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6173177066935658, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1243900714081905}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17714686876701324
Fold 2 IBS: 0.16932933496556507
Fold 3 IBS: 0.17717541750009574
Fold 4 IBS: 0.19713572873566637
Fold 5 IBS: 0.1888282875493155
[I 2024-04-16 00:52:18,272] Trial 20 finished with value: 0.18192312750353118 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.3628004877999946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13255231046532823}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16913535340838307
Fold 2 IBS: 0.15272782624748996
Fold 3 IBS: 0.18157422278730082
Fold 4 IBS: 0.19159866778115425
Fold 5 IBS: 0.18035473161483767
[I 2024-04-16 00:52:21,488] Trial 21 finished with value: 0.17507816036783316 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6011378896362364, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04460079180106673}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17030810384993947
Fold 2 IBS: 0.15141739726332304
Fold 3 IBS: 0.18252438545010272
Fold 4 IBS: 0.19011356122343498
Fold 5 IBS: 0.178289463693237
[I 2024-04-16 00:52:24,029] Trial 22 finished with value: 0.17453058229600743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.6303687757401123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10192378722318633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17546673577503152
Fold 2 IBS: 0.15775731851311675
Fold 3 IBS: 0.1781524236691594
Fold 4 IBS: 0.18862200168076865
Fold 5 IBS: 0.1781929228483396
[I 2024-04-16 00:52:26,162] Trial 23 finished with value: 0.1756382804972832 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.47299192016675806, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11363003519604899}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17094376831357636
Fold 2 IBS: 0.1646895387119759
Fold 3 IBS: 0.1747842391429866
Fold 4 IBS: 0.19494361629603088
Fold 5 IBS: 0.1866353242437713
[I 2024-04-16 00:52:28,001] Trial 24 finished with value: 0.1783992973416682 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 20, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.6280222894166756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17647963073148}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16901499831887323
Fold 2 IBS: 0.1608317214516487
Fold 3 IBS: 0.1762379772561786
Fold 4 IBS: 0.19348054932052614
Fold 5 IBS: 0.18439435643852217
[I 2024-04-16 00:52:30,059] Trial 25 finished with value: 0.1767919205571498 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.4737896318177208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09514387992502697}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16929634538840924
Fold 2 IBS: 0.15790827738905253
Fold 3 IBS: 0.17685741513951483
Fold 4 IBS: 0.1967559497411602
Fold 5 IBS: 0.185385205701487
[I 2024-04-16 00:52:31,952] Trial 26 finished with value: 0.17724063867192474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.8171469856554013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23317683759042168}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17086891563968248
Fold 2 IBS: 0.1631508903913892
Fold 3 IBS: 0.17528408462417908
Fold 4 IBS: 0.19656070086825392
Fold 5 IBS: 0.1871180876095544
[I 2024-04-16 00:52:33,925] Trial 27 finished with value: 0.1785965358266118 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.69231778632942, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05016618054550538}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21403025999388117
Fold 2 IBS: 0.22062977018591617
Fold 3 IBS: 0.20516689505844507
Fold 4 IBS: 0.22458172975885837
Fold 5 IBS: 0.21781943709735221
[I 2024-04-16 00:52:34,862] Trial 28 finished with value: 0.21644561841889062 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.26154064534881144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1313308679038699}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1728058934917983
Fold 2 IBS: 0.16613273087140148
Fold 3 IBS: 0.1752425051862629
Fold 4 IBS: 0.19545037913945612
Fold 5 IBS: 0.18577836193667824
[I 2024-04-16 00:52:36,970] Trial 29 finished with value: 0.17908197412511942 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.590452735593326, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1894700331250358}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18009129126221046
Fold 2 IBS: 0.16991867934953306
Fold 3 IBS: 0.18118166421743642
Fold 4 IBS: 0.21329354235589876
Fold 5 IBS: 0.19503330809108468
[I 2024-04-16 00:52:38,822] Trial 30 finished with value: 0.18790369705523266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.2125304486051036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17449717368418352
Fold 2 IBS: 0.15873065763573396
Fold 3 IBS: 0.17799356833494584
Fold 4 IBS: 0.18990025142492684

Fold 5 IBS: 0.17698987901902175
[I 2024-04-16 00:52:41,119] Trial 31 finished with value: 0.1756223060197624 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.6141886010044044, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.050889504115644586}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17921499719523448
Fold 2 IBS: 0.14457659998302025
Fold 3 IBS: 0.18892068480933402
Fold 4 IBS: 0.1881785321534129
Fold 5 IBS: 0.17366220512930025
[I 2024-04-16 00:52:43,378] Trial 32 finished with value: 0.17491060385406038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.7145937356077748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.040680386261001684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17839650482493216
Fold 2 IBS: 0.14376103753095715
Fold 3 IBS: 0.19179232168292484
Fold 4 IBS: 0.19114956333888955
Fold 5 IBS: 0.17341358371378018
[I 2024-04-16 00:52:45,663] Trial 33 finished with value: 0.17570260221829676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7166906016039446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09227781345982045}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16932356014486769
Fold 2 IBS: 0.15500446673627225
Fold 3 IBS: 0.17911021415557007
Fold 4 IBS: 0.1924434421788033
Fold 5 IBS: 0.1827561791077991
[I 2024-04-16 00:52:48,382] Trial 34 finished with value: 0.17572757246466247 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6617651070453551, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03171407678135554}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17172138717448102
Fold 2 IBS: 0.1489493130650319
Fold 3 IBS: 0.18425400801471595
Fold 4 IBS: 0.1932643172167075
Fold 5 IBS: 0.17711273715249415
[I 2024-04-16 00:52:51,302] Trial 35 finished with value: 0.1750603525246861 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.7113768772571837, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15846671523399145}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17419660096638498
Fold 2 IBS: 0.14719187785917906
Fold 3 IBS: 0.18565125612910302
Fold 4 IBS: 0.19257551123464545
Fold 5 IBS: 0.17764557195591085
[I 2024-04-16 00:52:52,818] Trial 36 finished with value: 0.17545216362904464 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 165, 'oob_score': False, 'max_samples': 0.5150316876314238, 'max_features': None, 'min_weight_fraction_leaf': 0.07821728657119803}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16964600099214439
Fold 2 IBS: 0.15385862052455887
Fold 3 IBS: 0.18067679456916436
Fold 4 IBS: 0.19330218283868858
Fold 5 IBS: 0.18067145906944948
[I 2024-04-16 00:52:54,706] Trial 37 finished with value: 0.17563101159880112 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6558408084386204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026524892218781126}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21398210519775457
Fold 2 IBS: 0.22147310463890008
Fold 3 IBS: 0.20484795914030776
Fold 4 IBS: 0.22469082739864527
Fold 5 IBS: 0.21847043318447362
[I 2024-04-16 00:52:57,766] Trial 38 finished with value: 0.21669288591201624 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.5446753536916582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20739916362370578
Fold 2 IBS: 0.1396518555288153
Fold 3 IBS: 0.20101553841044428
Fold 4 IBS: 0.18775948197861053
Fold 5 IBS: 0.17175126099969984
[I 2024-04-16 00:53:02,603] Trial 39 finished with value: 0.18151546010825514 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.7867614811876313, 'max_features': None, 'min_weight_fraction_leaf': 0.11443308942980066}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18099751369940803
Fold 2 IBS: 0.14073570153984705
Fold 3 IBS: 0.19394522353389632
Fold 4 IBS: 0.1899027663588423
Fold 5 IBS: 0.17323048606648403
[I 2024-04-16 00:53:04,937] Trial 40 finished with value: 0.17576233823969556 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.5666383752254781, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07880882141692147}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1711305979532741
Fold 2 IBS: 0.14944644009789185
Fold 3 IBS: 0.1838255715011791
Fold 4 IBS: 0.19303788294761579
Fold 5 IBS: 0.17769110415876982
[I 2024-04-16 00:53:07,464] Trial 41 finished with value: 0.17502631933174614 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 312, 'oob_score': True, 'max_samples': 0.7412385222820266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16945209847062737}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1766253375339953
Fold 2 IBS: 0.14548886613385514
Fold 3 IBS: 0.18810559860305523
Fold 4 IBS: 0.18904619197923261
Fold 5 IBS: 0.17490826493381245
[I 2024-04-16 00:53:12,287] Trial 42 finished with value: 0.17483485183679015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.8639712154486969, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16678569984405386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2139789554890857
Fold 2 IBS: 0.22135558660927104
Fold 3 IBS: 0.2047725162249457
Fold 4 IBS: 0.22463102393551193
Fold 5 IBS: 0.21859845040133852
[I 2024-04-16 00:53:16,355] Trial 43 finished with value: 0.2166673065320306 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.8907059888796497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18785889346357237
Fold 2 IBS: 0.15285827950678846
Fold 3 IBS: 0.18232508298547248
Fold 4 IBS: 0.18846580968340798
Fold 5 IBS: 0.17332117086709029
[I 2024-04-16 00:53:19,418] Trial 44 finished with value: 0.17696584730126633 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.846059951367212, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14736137547860684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1824125215519607
Fold 2 IBS: 0.142066615195965
Fold 3 IBS: 0.1952477350951836
Fold 4 IBS: 0.19275254902170263
Fold 5 IBS: 0.17385783785418485
[I 2024-04-16 00:53:23,190] Trial 45 finished with value: 0.17726745174379938 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.7898763610119546, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11906682715479999}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16985840962071383
Fold 2 IBS: 0.16096525914717788
Fold 3 IBS: 0.18227104026957164
Fold 4 IBS: 0.20281275724564665
Fold 5 IBS: 0.1850460571787144
[I 2024-04-16 00:53:23,590] Trial 46 finished with value: 0.18019070469236487 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.6496915230774891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08221811754778048}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16980857091041326
Fold 2 IBS: 0.15719115142034723
Fold 3 IBS: 0.1767449129839921
Fold 4 IBS: 0.19510331227382113
Fold 5 IBS: 0.1831755952242518
[I 2024-04-16 00:53:27,703] Trial 47 finished with value: 0.17640470856256513 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.8914383434724882, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24824101632322468}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19349637716238946
Fold 2 IBS: 0.18021514079410297
Fold 3 IBS: 0.1797766992061227
Fold 4 IBS: 0.20805913242700583
Fold 5 IBS: 0.19958771263889286
[I 2024-04-16 00:53:30,473] Trial 48 finished with value: 0.19222701244570276 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.9967788477130068, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2029239852759813
Fold 2 IBS: 0.13716491759028818
Fold 3 IBS: 0.2084231173473227
Fold 4 IBS: 0.19129569538138264
Fold 5 IBS: 0.16960756021085094
[I 2024-04-16 00:53:33,469] Trial 49 finished with value: 0.18188305516116512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.6825737614746896, 'max_features': None, 'min_weight_fraction_leaf': 0.020427001696118233}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1847999347983001
Fold 2 IBS: 0.15364870601921565
Fold 3 IBS: 0.1822009992001216
Fold 4 IBS: 0.18809108511963865
Fold 5 IBS: 0.17414367995939478
[I 2024-04-16 00:53:34,383] Trial 50 finished with value: 0.17657688101933416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8644699746287099, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06989429005204871}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17038930280276898
Fold 2 IBS: 0.15348758465747694
Fold 3 IBS: 0.18016675506323593
Fold 4 IBS: 0.1938593087420373
Fold 5 IBS: 0.18099103292628088
[I 2024-04-16 00:53:39,065] Trial 51 finished with value: 0.17577879683836 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.727895633786626, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18327602934679604}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17451701150431106
Fold 2 IBS: 0.14671503382427162
Fold 3 IBS: 0.18683750953876657
Fold 4 IBS: 0.19257094181568649
Fold 5 IBS: 0.17615300496682904
[I 2024-04-16 00:53:42,875] Trial 52 finished with value: 0.17535870032997297 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.7478990221520405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14624323581313917}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17559006537700683
Fold 2 IBS: 0.16972487299848873
Fold 3 IBS: 0.17529653726657532
Fold 4 IBS: 0.19855196165239603
Fold 5 IBS: 0.1851918744321701
[I 2024-04-16 00:53:47,353] Trial 53 finished with value: 0.1808710623453274 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.8074226422105014, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27324344422148944}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17595680778437212
Fold 2 IBS: 0.17008267991566167
Fold 3 IBS: 0.17604437670258266
Fold 4 IBS: 0.19769140576353486
Fold 5 IBS: 0.18734084278780233
[I 2024-04-16 00:53:53,112] Trial 54 finished with value: 0.18142322259079072 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.5775945927656037, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2001668400822587}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16773815898136948
Fold 2 IBS: 0.1576076816374329
Fold 3 IBS: 0.17803399667907918
Fold 4 IBS: 0.19725085339663992
Fold 5 IBS: 0.18451260927365026
[I 2024-04-16 00:53:54,851] Trial 55 finished with value: 0.17702865999363437 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.6303629140203428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16685382022581927}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18003668325471714
Fold 2 IBS: 0.14323357247265056
Fold 3 IBS: 0.19283157086976438
Fold 4 IBS: 0.192092008764836
Fold 5 IBS: 0.17436160978254575
[I 2024-04-16 00:53:58,231] Trial 56 finished with value: 0.17651108902890275 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.7623102674577037, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09861841429774906}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17302493479017875
Fold 2 IBS: 0.1667969562590488
Fold 3 IBS: 0.17568508570553082
Fold 4 IBS: 0.1958388085038477
Fold 5 IBS: 0.18612204667403598
[I 2024-04-16 00:54:02,656] Trial 57 finished with value: 0.1794935663865284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.6746410572190499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19693288454187685
Fold 2 IBS: 0.16031608536235142
Fold 3 IBS: 0.18209014838073903
Fold 4 IBS: 0.18830938207544887
Fold 5 IBS: 0.1722123575079718
[I 2024-04-16 00:54:05,978] Trial 58 finished with value: 0.1799721715736776 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.9493525765812034, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.033039474629030334}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17638204755824788
Fold 2 IBS: 0.14724121981954666
Fold 3 IBS: 0.18830472263321374
Fold 4 IBS: 0.18908125561308473
Fold 5 IBS: 0.17501568142226698
[I 2024-04-16 00:54:07,039] Trial 59 finished with value: 0.175204985409272 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.706317491452594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.011952641009515354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17441654996325617
Fold 2 IBS: 0.16879198972806275
Fold 3 IBS: 0.1747308489003251
Fold 4 IBS: 0.19678299634235394
Fold 5 IBS: 0.18428329935051413
[I 2024-04-16 00:54:08,377] Trial 60 finished with value: 0.1798011368569024 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.4446079220615766, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13552790545628873}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1726966416095679
Fold 2 IBS: 0.14791648216625575
Fold 3 IBS: 0.18587926582625136
Fold 4 IBS: 0.19250544947641468
Fold 5 IBS: 0.1767138327798232
[I 2024-04-16 00:54:11,802] Trial 61 finished with value: 0.17514233437166257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.7350539425199517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15353880193597452}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1784711929725387
Fold 2 IBS: 0.14471049906571562
Fold 3 IBS: 0.19083362219368874
Fold 4 IBS: 0.19321298173368606

Fold 5 IBS: 0.17601995444169838
[I 2024-04-16 00:54:14,738] Trial 62 finished with value: 0.1766496500814655 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.6969767031486694, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11947149985769817}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17325965795999854
Fold 2 IBS: 0.16035062956465257
Fold 3 IBS: 0.17539882197990753
Fold 4 IBS: 0.193362443315604
Fold 5 IBS: 0.1796554283287958
[I 2024-04-16 00:54:17,235] Trial 63 finished with value: 0.17640539622979168 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 311, 'oob_score': True, 'max_samples': 0.6304198495967799, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16702154024396243}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17417602273955624
Fold 2 IBS: 0.1480464954861786
Fold 3 IBS: 0.1861637654245361
Fold 4 IBS: 0.19307278746213727
Fold 5 IBS: 0.17661238768457427
[I 2024-04-16 00:54:19,502] Trial 64 finished with value: 0.1756142917593965 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.8416513210854921, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16738759238643802}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1822613083064998
Fold 2 IBS: 0.1416365045076241
Fold 3 IBS: 0.1960788715196419
Fold 4 IBS: 0.19275645033338762
Fold 5 IBS: 0.1744182820015701
[I 2024-04-16 00:54:23,272] Trial 65 finished with value: 0.17743028333374472 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.7722883894951643, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0665684368743143}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17389086197303102
Fold 2 IBS: 0.16790129559912909
Fold 3 IBS: 0.1751507252355886
Fold 4 IBS: 0.19750324318227722
Fold 5 IBS: 0.18620949704754197
[I 2024-04-16 00:54:26,620] Trial 66 finished with value: 0.18013112460751357 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.5947629158546897, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20025339037463216}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17423384494498612
Fold 2 IBS: 0.14631335780890575
Fold 3 IBS: 0.18861958817402585
Fold 4 IBS: 0.19245950764813075
Fold 5 IBS: 0.175067247621942
[I 2024-04-16 00:54:32,017] Trial 67 finished with value: 0.1753387092395981 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.7217571884559283, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13013771636318264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17535705050457914
Fold 2 IBS: 0.15778179636614245
Fold 3 IBS: 0.17763073839385685
Fold 4 IBS: 0.19018833285814207
Fold 5 IBS: 0.17770479034207873
[I 2024-04-16 00:54:33,994] Trial 68 finished with value: 0.17573254169295985 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.5191868058797825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.047795726630053076}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17480337133090915
Fold 2 IBS: 0.16874159329787056
Fold 3 IBS: 0.17579652970954177
Fold 4 IBS: 0.1923367638029231
Fold 5 IBS: 0.18690613654154167
[I 2024-04-16 00:54:38,588] Trial 69 finished with value: 0.17971687893655724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.18576927332867577, 'max_features': 'log2', 'min_weight_fraction_leaf': 7.114682696795181e-05}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20781268631997615
Fold 2 IBS: 0.13838860575441492
Fold 3 IBS: 0.21122911345717027
Fold 4 IBS: 0.19170717046621447
Fold 5 IBS: 0.16987800654423307
[I 2024-04-16 00:54:44,471] Trial 70 finished with value: 0.18380311650840175 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.8126013453538647, 'max_features': None, 'min_weight_fraction_leaf': 0.10415283732963354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16897127550996938
Fold 2 IBS: 0.15333527019800122
Fold 3 IBS: 0.18108923812924368
Fold 4 IBS: 0.19125151911620464
Fold 5 IBS: 0.1804095239747975
[I 2024-04-16 00:54:49,722] Trial 71 finished with value: 0.17501136538564327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.5965842869794661, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04020616684856252}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16942384334835775
Fold 2 IBS: 0.1534316341977167
Fold 3 IBS: 0.18126076316917372
Fold 4 IBS: 0.1918304245116947
Fold 5 IBS: 0.1797086597106947
[I 2024-04-16 00:54:54,628] Trial 72 finished with value: 0.17513106498752753 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.64967240812612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042859490745800255}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17483538806839433
Fold 2 IBS: 0.15903414917848718
Fold 3 IBS: 0.178305987368802
Fold 4 IBS: 0.18895015857840794
Fold 5 IBS: 0.17674514740069427
[I 2024-04-16 00:55:01,050] Trial 73 finished with value: 0.17557416611895713 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 468, 'oob_score': False, 'max_samples': 0.614601651625123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08656637647813382}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685354387079355
Fold 2 IBS: 0.1519242369397579
Fold 3 IBS: 0.18329403645197254
Fold 4 IBS: 0.19121480234741198
Fold 5 IBS: 0.17959179151928248
[I 2024-04-16 00:55:05,866] Trial 74 finished with value: 0.17491206119327207 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.564394176347414, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0639505821191327}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16870518179470842
Fold 2 IBS: 0.1524006924636778
Fold 3 IBS: 0.1824052463489283
Fold 4 IBS: 0.19198874945374883
Fold 5 IBS: 0.17971814686012724
[I 2024-04-16 00:55:12,976] Trial 75 finished with value: 0.1750436033842381 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.5549716215197416, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06244978633063567}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17388421751906138
Fold 2 IBS: 0.1679541870820109
Fold 3 IBS: 0.17539898304019086
Fold 4 IBS: 0.1953143658823387
Fold 5 IBS: 0.18647747737304407
[I 2024-04-16 00:55:23,857] Trial 76 finished with value: 0.1798058461793292 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.5288500192319384, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016585234890071264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17761169418416847
Fold 2 IBS: 0.16895784550549822
Fold 3 IBS: 0.17542226135379532
Fold 4 IBS: 0.19549660202075014
Fold 5 IBS: 0.18743069872463708
[I 2024-04-16 00:55:38,800] Trial 77 finished with value: 0.18098382035776983 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.3800215746179153, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03735564012092016}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16818314645426713
Fold 2 IBS: 0.15369061634554518
Fold 3 IBS: 0.18213459050433092
Fold 4 IBS: 0.19123211966917278
Fold 5 IBS: 0.17979973767912885
[I 2024-04-16 00:55:43,556] Trial 78 finished with value: 0.17500804213048896 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.4897248144615137, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053996872945124036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1682237549262069
Fold 2 IBS: 0.15295334400832536
Fold 3 IBS: 0.18214608764478374
Fold 4 IBS: 0.19238806563941324
Fold 5 IBS: 0.18028732465861996
[I 2024-04-16 00:55:48,965] Trial 79 finished with value: 0.17519971537546983 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.49575398669591153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06405554874562534}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17507598055558485
Fold 2 IBS: 0.16867091079334554
Fold 3 IBS: 0.1744565827712509
Fold 4 IBS: 0.1954950968251498
Fold 5 IBS: 0.18635102171872073
[I 2024-04-16 00:55:54,105] Trial 80 finished with value: 0.18000991853281037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.43759421275648835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0533463490707784}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1714174399032279
Fold 2 IBS: 0.14887499618081926
Fold 3 IBS: 0.1849640281040515
Fold 4 IBS: 0.1899572218408997
Fold 5 IBS: 0.17713400076306418
[I 2024-04-16 00:55:58,127] Trial 81 finished with value: 0.17446953735841247 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5784234487575245, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10829522154445037}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16877649511183368
Fold 2 IBS: 0.1546883871779083
Fold 3 IBS: 0.18056083236056208
Fold 4 IBS: 0.19133957386634493
Fold 5 IBS: 0.18162520349661385
[I 2024-04-16 00:56:03,009] Trial 82 finished with value: 0.17539809840265258 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5722759399876282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10440976094597362}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685240734239476
Fold 2 IBS: 0.15222241351006804
Fold 3 IBS: 0.1822020345828932
Fold 4 IBS: 0.19079185577835267
Fold 5 IBS: 0.17960640446910925
[I 2024-04-16 00:56:07,256] Trial 83 finished with value: 0.17466935635287414 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.5451307479888213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0724192455670338}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17338079162104056
Fold 2 IBS: 0.15920893592551924
Fold 3 IBS: 0.17825449140901586
Fold 4 IBS: 0.18925769833312683
Fold 5 IBS: 0.17742455682194408
[I 2024-04-16 00:56:11,811] Trial 84 finished with value: 0.17550529482212932 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.5442180702857965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07567351514027787}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1690383568215189
Fold 2 IBS: 0.15230702588653305
Fold 3 IBS: 0.1822765777502009
Fold 4 IBS: 0.19170674176025757
Fold 5 IBS: 0.18006279876989542
[I 2024-04-16 00:56:16,822] Trial 85 finished with value: 0.17507830019768117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.5030563110008609, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09285296477077623}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17784444889141396
Fold 2 IBS: 0.14568494632276702
Fold 3 IBS: 0.18681231725936967
Fold 4 IBS: 0.18938575035357394
Fold 5 IBS: 0.17417653028434565
[I 2024-04-16 00:56:26,708] Trial 86 finished with value: 0.17478079862229406 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.6227373925109708, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11680143459253466}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17320771484108127
Fold 2 IBS: 0.1471439015418838
Fold 3 IBS: 0.1868119711290211
Fold 4 IBS: 0.191522355137527
Fold 5 IBS: 0.17549663792817793
[I 2024-04-16 00:56:30,902] Trial 87 finished with value: 0.17483651611553824 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.6363957788305546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1264522778930551}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.177279146128294
Fold 2 IBS: 0.14462990587422714
Fold 3 IBS: 0.18982364231541823
Fold 4 IBS: 0.19123959493668208
Fold 5 IBS: 0.17462972301152646
[I 2024-04-16 00:56:35,491] Trial 88 finished with value: 0.17552040245322958 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.643212285009443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11042020211203352}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18172829377621072
Fold 2 IBS: 0.15455308362712544
Fold 3 IBS: 0.18079631963918813
Fold 4 IBS: 0.1866909754534505
Fold 5 IBS: 0.17486062534932048
[I 2024-04-16 00:56:40,640] Trial 89 finished with value: 0.17572585956905906 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 379, 'oob_score': False, 'max_samples': 0.6745160130358284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13729294470437828}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17159615871766515
Fold 2 IBS: 0.1492340100734715
Fold 3 IBS: 0.18525391328974408
Fold 4 IBS: 0.19170238188043215
Fold 5 IBS: 0.17723852207113783
[I 2024-04-16 00:56:45,961] Trial 90 finished with value: 0.17500499720649015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6100442323266079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08381032204107067}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17439132896823156
Fold 2 IBS: 0.1476318214680082
Fold 3 IBS: 0.1865038949155308
Fold 4 IBS: 0.19098341263244506
Fold 5 IBS: 0.17516827480713895
[I 2024-04-16 00:56:51,833] Trial 91 finished with value: 0.17493574655827088 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.6220455817398846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12351605327621175}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17132240828700077
Fold 2 IBS: 0.14948366004568905
Fold 3 IBS: 0.1849774655279456
Fold 4 IBS: 0.19091977764974633
Fold 5 IBS: 0.17791613386648897
[I 2024-04-16 00:56:55,441] Trial 92 finished with value: 0.17492388907537415 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.5773252805729456, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1260508695586116}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17523723037867286
Fold 2 IBS: 0.1453570091149411
Fold 3 IBS: 0.18962747105019612
Fold 4 IBS: 0.19107181469212342

Fold 5 IBS: 0.1747309238915691
[I 2024-04-16 00:56:58,955] Trial 93 finished with value: 0.1752048898255005 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.5630698614554802, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0944985972942633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17026943747099219
Fold 2 IBS: 0.15255352423829832
Fold 3 IBS: 0.18160069813968083
Fold 4 IBS: 0.19096533404342483
Fold 5 IBS: 0.1822030877543707
[I 2024-04-16 00:57:02,017] Trial 94 finished with value: 0.17551841632935336 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.5751544947591161, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14409687866880386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17475332961241374
Fold 2 IBS: 0.14521126379405494
Fold 3 IBS: 0.18914044635556457
Fold 4 IBS: 0.19026828870845303
Fold 5 IBS: 0.1744104734429843
[I 2024-04-16 00:57:05,876] Trial 95 finished with value: 0.1747567603826941 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.5892575789175918, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11211324848978509}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21400356610903593
Fold 2 IBS: 0.22204327857369352
Fold 3 IBS: 0.20415553733700337
Fold 4 IBS: 0.2250379696399111
Fold 5 IBS: 0.21815296605159928
[I 2024-04-16 00:57:06,417] Trial 96 finished with value: 0.21667866354224863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.46700128900375126, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35031312034195705}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.173562295845494
Fold 2 IBS: 0.14742220750236526
Fold 3 IBS: 0.18545169450924154
Fold 4 IBS: 0.18866406353263676
Fold 5 IBS: 0.17639414796763403
[I 2024-04-16 00:57:10,123] Trial 97 finished with value: 0.1742988818714743 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.5401266728628165, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11341150154917841}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.179800528231758
Fold 2 IBS: 0.15504407580671617
Fold 3 IBS: 0.18062194922738495
Fold 4 IBS: 0.18693465453878075
Fold 5 IBS: 0.17539368811607456
[I 2024-04-16 00:57:13,358] Trial 98 finished with value: 0.1755589791841429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.5436809153821575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10940615561612807}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18678959754522786
Fold 2 IBS: 0.14275774495321747
Fold 3 IBS: 0.19217915320067025
Fold 4 IBS: 0.18335908765764633
Fold 5 IBS: 0.17253698272333465
[I 2024-04-16 00:57:17,106] Trial 99 finished with value: 0.1755245132160193 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.694819405505868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07480505292477731}. Best is trial 11 with value: 0.17074634120633253.


* Best trial for IBS:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.17074634120633253], datetime_start=datetime.datetime(2024, 4, 16, 0, 52, 4, 731899), datetime_complete=datetime.datetime(2024, 4, 16, 0, 52, 4, 860551), params={'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=11, value=None)


* Best Score for IBS:
 0.17074634120633253

In [48]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.846
train_ibs:  0.171

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=12,
                     max_samples=0.48042970450395145, min_samples_leaf=1,
                     min_samples_split=4,
                     min_weight_fraction_leaf=0.0025914663927405594,
                     n_estimators=289, random_state=123, warm_start=True)

test_cindex:  0.602

RandomSurvivalForest(max_depth=1, max_features='auto', max_leaf_nodes=18,
                     max_samples=0.7351810575897255, min_samples_leaf=11,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.008231293935378081,
                     n_estimators=2, random_state=123)

test_ibs:  0.233

In [52]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 00:57:18,108] A new study created in memory with name: no-name-2faa02ae-db1e-4fa3-84ec-ef91420caf17

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 00:57:19,062] Trial 0 finished with value: 0.763120153205612 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:57:20,901] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:57:24,497] Trial 2 finished with value: 0.7549111845989632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:57:24,879] Trial 3 finished with value: 0.7581427541761773 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:57:26,194] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:57:27,591] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:57:28,355] Trial 6 finished with value: 0.7620861007898516 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 00:57:30,355] Trial 7 finished with value: 0.7433829385982176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.715962441314554
[I 2024-04-16 00:57:30,491] Trial 8 finished with value: 0.7526603922254165 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7206572769953051
[I 2024-04-16 00:57:34,474] Trial 9 finished with value: 0.7327992570997183 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:57:35,860] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:57:36,561] Trial 11 finished with value: 0.7610279984130963 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:57:37,546] Trial 12 finished with value: 0.7656344262692516 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:57:38,469] Trial 13 finished with value: 0.7565522092481783 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 00:57:39,244] Trial 14 finished with value: 0.7616650689919885 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:57:39,829] Trial 15 finished with value: 0.7545769177214963 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7656344262692516.

Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 00:57:40,788] Trial 16 finished with value: 0.7335270596877141 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:57:41,397] Trial 17 finished with value: 0.7591715308548418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:57:42,422] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:57:43,170] Trial 19 finished with value: 0.7663281634231028 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 00:57:43,998] Trial 20 finished with value: 0.746722729311177 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8975839614288115, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:57:44,779] Trial 21 finished with value: 0.7629692767153701 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9830051091386647, 'min_weight_fraction_leaf': 0.11961357903200062}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:57:45,480] Trial 22 finished with value: 0.7628892919669691 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8609656753336752, 'min_weight_fraction_leaf': 0.15663178852989545}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:57:46,232] Trial 23 finished with value: 0.7509593791567746 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.737236690052532, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:57:47,035] Trial 24 finished with value: 0.7611911126952604 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9222263146213784, 'min_weight_fraction_leaf': 0.08957779552546857}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.859375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 00:57:47,635] Trial 25 finished with value: 0.7561901306130971 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8274383615832067, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:57:52,124] Trial 26 finished with value: 0.7444877442865183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6539680943502474, 'min_weight_fraction_leaf': 0.04317449484749}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:57:53,057] Trial 27 finished with value: 0.7566253755185277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9365238772272462, 'min_weight_fraction_leaf': 0.14306800767196773}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8415178571428571
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:57:53,682] Trial 28 finished with value: 0.7600206204906962 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7383223503010752, 'min_weight_fraction_leaf': 0.20900889157295355}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:57:55,444] Trial 29 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4766061840882204, 'min_weight_fraction_leaf': 0.25297594889320807}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:57:56,399] Trial 30 finished with value: 0.7619426335421767 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.09166005683798992}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 00:57:57,138] Trial 31 finished with value: 0.7601328692954678 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9462932212483206, 'min_weight_fraction_leaf': 0.12021009726526694}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:57:57,997] Trial 32 finished with value: 0.760869569103513 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9864877695110971, 'min_weight_fraction_leaf': 0.06164320836318145}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:57:58,752] Trial 33 finished with value: 0.7624746237982056 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9301489258006082, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 00:57:59,229] Trial 34 finished with value: 0.7567330098622376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9912043386887608, 'min_weight_fraction_leaf': 0.02249172399095729}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:58:01,438] Trial 35 finished with value: 0.7529807806767499 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.766068607890644, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 00:58:02,219] Trial 36 finished with value: 0.7591886238684845 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8553115001753557, 'min_weight_fraction_leaf': 0.22873450590105582}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:58:03,156] Trial 37 finished with value: 0.7555796977821257 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6217761713512069, 'min_weight_fraction_leaf': 0.12934411260414114}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 00:58:07,044] Trial 38 finished with value: 0.7535108102301846 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 428, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.04910893285740458}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 00:58:07,484] Trial 39 finished with value: 0.7553157338682244 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8005826243516873, 'min_weight_fraction_leaf': 0.07469351697759873}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 00:58:08,129] Trial 40 finished with value: 0.7605112688643425 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9569519035429586, 'min_weight_fraction_leaf': 0.2757731212264245}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:58:08,842] Trial 41 finished with value: 0.7609843014176124 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8687619648747806, 'min_weight_fraction_leaf': 0.15295888294766263}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 00:58:09,627] Trial 42 finished with value: 0.7638303926085905 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.906955015046886, 'min_weight_fraction_leaf': 0.10454210976347417}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8370535714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:58:10,396] Trial 43 finished with value: 0.7591740994887395 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8217177439443847, 'min_weight_fraction_leaf': 0.10552735389681006}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:58:11,127] Trial 44 finished with value: 0.7612405402767923 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9989309278077574, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 00:58:11,798] Trial 45 finished with value: 0.7628719194609885 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9091736520975473, 'min_weight_fraction_leaf': 0.0038012551219620827}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.7347417840375586
[I 2024-04-16 00:58:15,189] Trial 46 finished with value: 0.7501344600750558 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 359, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5368271784486555, 'min_weight_fraction_leaf': 0.10615317714605318}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 00:58:15,351] Trial 47 finished with value: 0.7516793229025998 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 31, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9594946112358607, 'min_weight_fraction_leaf': 0.17333335446497328}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:58:16,128] Trial 48 finished with value: 0.7562519939011765 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7685785296036635, 'min_weight_fraction_leaf': 0.13176023447811921}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5432900432900433
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5738396624472574
Fold 5 C-index: 0.460093896713615
[I 2024-04-16 00:58:16,997] Trial 49 finished with value: 0.5820501126470459 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8880373878399398, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:17,914] Trial 50 finished with value: 0.7630008769419695 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7034625855110039, 'min_weight_fraction_leaf': 0.07304621552955944}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:58:18,857] Trial 51 finished with value: 0.7612490374113632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7321671383859141, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:58:19,831] Trial 52 finished with value: 0.7629420794152763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6907063917898906, 'min_weight_fraction_leaf': 0.0661877659346652}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:58:20,911] Trial 53 finished with value: 0.7596563589778932 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 480, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9052538185294309, 'min_weight_fraction_leaf': 0.08508715956661925}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:58:21,681] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.577878588672621, 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 00:58:22,582] Trial 55 finished with value: 0.7704458139436589 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7999514777179073, 'min_weight_fraction_leaf': 0.035270943770753044}. Best is trial 55 with value: 0.7704458139436589.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 00:58:23,515] Trial 56 finished with value: 0.771384781079809 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7991467335557068, 'min_weight_fraction_leaf': 0.027992113153361142}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 00:58:26,151] Trial 57 finished with value: 0.74717809865806 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 248, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.79672071864693, 'min_weight_fraction_leaf': 0.016889715164357902}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 00:58:26,856] Trial 58 finished with value: 0.7677971640851675 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.828019859852415, 'min_weight_fraction_leaf': 0.03447642547531156}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 00:58:27,520] Trial 59 finished with value: 0.7697165233781805 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8346072695502785, 'min_weight_fraction_leaf': 0.0002567835070198393}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:58:28,279] Trial 60 finished with value: 0.7674757615164577 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 321, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6391411801898657, 'min_weight_fraction_leaf': 0.03561049450086254}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:58:28,968] Trial 61 finished with value: 0.7665829043736004 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6492185512714621, 'min_weight_fraction_leaf': 0.03617201704474487}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 00:58:29,676] Trial 62 finished with value: 0.7674728962234336 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 319, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5312924276275225, 'min_weight_fraction_leaf': 0.040385592930900376}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 00:58:30,381] Trial 63 finished with value: 0.7710730622821746 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5292658633860801, 'min_weight_fraction_leaf': 0.03711866587371772}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 00:58:31,072] Trial 64 finished with value: 0.7657902697781489 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.39806376813911337, 'min_weight_fraction_leaf': 0.03599381902829695}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 00:58:31,687] Trial 65 finished with value: 0.7621709115338706 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5323188905088267, 'min_weight_fraction_leaf': 0.010814253491385636}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 00:58:32,355] Trial 66 finished with value: 0.7691537029891617 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.49002509944053235, 'min_weight_fraction_leaf': 0.053181149195751426}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:32,935] Trial 67 finished with value: 0.7604151188182366 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.43798216039712035, 'min_weight_fraction_leaf': 0.0010098437298928856}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 00:58:33,489] Trial 68 finished with value: 0.7683829874029711 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6113081575629796, 'min_weight_fraction_leaf': 0.057217831184053644}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 00:58:34,007] Trial 69 finished with value: 0.7639295695425288 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5915899101823151, 'min_weight_fraction_leaf': 0.05522041323530981}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:58:34,803] Trial 70 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47632910975325155, 'min_weight_fraction_leaf': 0.35980997926626934}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:58:35,443] Trial 71 finished with value: 0.768254027368253 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6101916618563699, 'min_weight_fraction_leaf': 0.024998041606770292}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:58:36,123] Trial 72 finished with value: 0.7628057101379913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.32440915793159353, 'min_weight_fraction_leaf': 0.018643504112019715}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:36,708] Trial 73 finished with value: 0.7656587582763213 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5609478284070107, 'min_weight_fraction_leaf': 0.05622629784226072}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:58:37,221] Trial 74 finished with value: 0.7584779347240282 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5118014483585279, 'min_weight_fraction_leaf': 0.02563279470181265}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:58:37,855] Trial 75 finished with value: 0.7573932258116945 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6069046410719314, 'min_weight_fraction_leaf': 0.08378422745274237}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:58:40,203] Trial 76 finished with value: 0.7521751447219839 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.497864611352535, 'min_weight_fraction_leaf': 0.06709163220470778}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:40,666] Trial 77 finished with value: 0.7620487699772043 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 196, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6683682203156043, 'min_weight_fraction_leaf': 0.011300445410194197}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:58:41,220] Trial 78 finished with value: 0.760363871557148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.42677810376705305, 'min_weight_fraction_leaf': 0.052012092584961866}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 00:58:41,793] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7173081556448422, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 00:58:42,406] Trial 80 finished with value: 0.7683639336867342 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.35277360385569917, 'min_weight_fraction_leaf': 0.02852600943088988}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:42,915] Trial 81 finished with value: 0.7691928560351028 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3390678218166532, 'min_weight_fraction_leaf': 0.03153990098917725}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:43,440] Trial 82 finished with value: 0.7646076128469184 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 224, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3230507568153901, 'min_weight_fraction_leaf': 0.0014394857922413185}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 00:58:43,943] Trial 83 finished with value: 0.7614147057143738 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.23361689093258667, 'min_weight_fraction_leaf': 0.019775489029462356}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 00:58:44,515] Trial 84 finished with value: 0.7495893806395312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 260, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27445260818266226, 'min_weight_fraction_leaf': 0.09592965050134614}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:58:45,141] Trial 85 finished with value: 0.758556238262173 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3862488114937627, 'min_weight_fraction_leaf': 0.04471114770202597}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:58:45,597] Trial 86 finished with value: 0.7708567082564886 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 201, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.36377499756925225, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 00:58:46,496] Trial 87 finished with value: 0.7565355685297506 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3759670482683807, 'min_weight_fraction_leaf': 0.0767440911470792}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 00:58:48,129] Trial 88 finished with value: 0.7609903537745347 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.46073886535297426, 'min_weight_fraction_leaf': 0.05833982872177459}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 00:58:48,925] Trial 89 finished with value: 0.7699832161020457 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.295955749271664, 'min_weight_fraction_leaf': 0.010964572281232194}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 00:58:49,234] Trial 90 finished with value: 0.75952694664796 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27944226981321685, 'min_weight_fraction_leaf': 0.012928542240062478}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 00:58:50,038] Trial 91 finished with value: 0.7801238175459491 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3602425648795669, 'min_weight_fraction_leaf': 0.02981466940699433}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 00:58:50,785] Trial 92 finished with value: 0.7662740508689903 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.25077855422842626, 'min_weight_fraction_leaf': 0.04540069770937229}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 00:58:51,583] Trial 93 finished with value: 0.7619860192654835 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.34979442362410473, 'min_weight_fraction_leaf': 0.06734177243231611}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:52,012] Trial 94 finished with value: 0.7645085743822805 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.193678974775281, 'min_weight_fraction_leaf': 0.010805974584784796}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:52,925] Trial 95 finished with value: 0.7709939821242033 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30647854490295495, 'min_weight_fraction_leaf': 0.03078253598240698}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 00:58:53,759] Trial 96 finished with value: 0.7702698288265208 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3052686496163978, 'min_weight_fraction_leaf': 0.029515857916013147}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 00:58:54,594] Trial 97 finished with value: 0.7686062560974729 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30685683165847666, 'min_weight_fraction_leaf': 0.03193125520570377}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 00:58:55,459] Trial 98 finished with value: 0.7910857462403429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}. Best is trial 98 with value: 0.7910857462403429.

[I 2024-04-16 00:58:56,306] A new study created in memory with name: no-name-62e41c12-4b03-4736-b320-874c9a274fa1

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 00:58:56,294] Trial 99 finished with value: 0.7902101231341658 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21478988941660257, 'min_weight_fraction_leaf': 0.0040275983337470555}. Best is trial 98 with value: 0.7910857462403429.


* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.7910857462403429], datetime_start=datetime.datetime(2024, 4, 16, 0, 58, 54, 600522), datetime_complete=datetime.datetime(2024, 4, 16, 0, 58, 55, 458381), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for C-index:
 0.7910857462403429

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1894050222499581
Fold 2 IBS: 0.18197094047238005
Fold 3 IBS: 0.18636461603352758
Fold 4 IBS: 0.19277723911134473
Fold 5 IBS: 0.19455867868991514
[I 2024-04-16 00:58:58,703] Trial 0 finished with value: 0.1890152993114251 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-16 00:59:03,010] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20172405646713062
Fold 2 IBS: 0.2032359255005334
Fold 3 IBS: 0.19513408046545
Fold 4 IBS: 0.2118539452893589
Fold 5 IBS: 0.20729390842542533
[I 2024-04-16 00:59:06,991] Trial 2 finished with value: 0.20384838322957965 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20209415878470963
Fold 2 IBS: 0.20376840661760706
Fold 3 IBS: 0.19482805354546556
Fold 4 IBS: 0.21132760062349532
Fold 5 IBS: 0.2062713273884813
[I 2024-04-16 00:59:08,916] Trial 3 finished with value: 0.2036579093919518 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-16 00:59:11,903] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-16 00:59:14,288] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1904913206168486
Fold 2 IBS: 0.18444679148666562
Fold 3 IBS: 0.1856399244213203
Fold 4 IBS: 0.19570316353343864
Fold 5 IBS: 0.19484476324380895
[I 2024-04-16 00:59:17,621] Trial 6 finished with value: 0.19022519266041643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.19248537415224085
Fold 2 IBS: 0.19105800071812176
Fold 3 IBS: 0.19070595715673386
Fold 4 IBS: 0.2001633927865564
Fold 5 IBS: 0.20070302537730883
[I 2024-04-16 00:59:19,459] Trial 7 finished with value: 0.19502315003819234 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20480968165568902
Fold 2 IBS: 0.20484102123135522
Fold 3 IBS: 0.1975354311772608
Fold 4 IBS: 0.21193929006953224
Fold 5 IBS: 0.20806725700632217
[I 2024-04-16 00:59:19,894] Trial 8 finished with value: 0.2054385362280319 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.2113464419407712
Fold 2 IBS: 0.2169269042702578
Fold 3 IBS: 0.2014624387193473
Fold 4 IBS: 0.2214616279249577
Fold 5 IBS: 0.21570168611580814
[I 2024-04-16 00:59:24,545] Trial 9 finished with value: 0.21337981979422843 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-16 00:59:28,012] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1959863918798848
Fold 2 IBS: 0.19656167181968498
Fold 3 IBS: 0.19210822980372252
Fold 4 IBS: 0.2085074674907661
Fold 5 IBS: 0.20360120107474317
[I 2024-04-16 00:59:30,948] Trial 11 finished with value: 0.1993529924137603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.18512904520321427
Fold 2 IBS: 0.1740527886135347
Fold 3 IBS: 0.1861816706148936
Fold 4 IBS: 0.1893061222535103
Fold 5 IBS: 0.18959027778216106
[I 2024-04-16 00:59:35,668] Trial 12 finished with value: 0.18485198089346278 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19581913848034474
Fold 2 IBS: 0.19606584700533666
Fold 3 IBS: 0.18996353898817178
Fold 4 IBS: 0.2052342771852341
Fold 5 IBS: 0.2042479606113508
[I 2024-04-16 00:59:39,333] Trial 13 finished with value: 0.19826615245408763 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19648331141303396
Fold 2 IBS: 0.1983397281797131
Fold 3 IBS: 0.19106070821891877
Fold 4 IBS: 0.20858865485637526
Fold 5 IBS: 0.20490088125230282
[I 2024-04-16 00:59:42,273] Trial 14 finished with value: 0.1998746567840688 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.18485198089346278.

Fold 1 IBS: 0.19593558348243098
Fold 2 IBS: 0.19875475852789654
Fold 3 IBS: 0.1903333352589917
Fold 4 IBS: 0.20748251302147644
Fold 5 IBS: 0.203704702028721
[I 2024-04-16 00:59:44,380] Trial 15 finished with value: 0.19924217846390332 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21249912881980682
Fold 2 IBS: 0.2205333193107399
Fold 3 IBS: 0.2035653160933136
Fold 4 IBS: 0.22350418932951804
Fold 5 IBS: 0.2173028001714802
[I 2024-04-16 00:59:48,741] Trial 16 finished with value: 0.21548095074497176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19183114805047974
Fold 2 IBS: 0.19128424686172338
Fold 3 IBS: 0.18814594086160835
Fold 4 IBS: 0.20499323686954313
Fold 5 IBS: 0.20021013474043506
[I 2024-04-16 00:59:51,754] Trial 17 finished with value: 0.1952929414767579 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-16 00:59:52,944] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.1938760896028742
Fold 2 IBS: 0.19481663520802522
Fold 3 IBS: 0.18987914648212936
Fold 4 IBS: 0.20616644798233227
Fold 5 IBS: 0.20329633873487413
[I 2024-04-16 00:59:56,258] Trial 19 finished with value: 0.19760693160204706 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.20735529929388963
Fold 2 IBS: 0.208787348599295
Fold 3 IBS: 0.20137982249029263
Fold 4 IBS: 0.22312888688520593
Fold 5 IBS: 0.21346429994402807
[I 2024-04-16 00:59:56,459] Trial 20 finished with value: 0.21082313144254225 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.190149663845766
Fold 2 IBS: 0.1836146541541013
Fold 3 IBS: 0.18617574190891484
Fold 4 IBS: 0.19484231855727627
Fold 5 IBS: 0.19454635613742202
[I 2024-04-16 00:59:59,524] Trial 21 finished with value: 0.18986574692069608 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.18788264608767696
Fold 2 IBS: 0.17893614961467227
Fold 3 IBS: 0.18648188730398177
Fold 4 IBS: 0.19163081844739127
Fold 5 IBS: 0.1923382065001444
[I 2024-04-16 01:00:02,626] Trial 22 finished with value: 0.18745394159077333 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.182703884521614
Fold 2 IBS: 0.16927944395517258
Fold 3 IBS: 0.18708643964817723
Fold 4 IBS: 0.18405528016378853
Fold 5 IBS: 0.18780835196581747
[I 2024-04-16 01:00:06,225] Trial 23 finished with value: 0.18218668005091396 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1895746301789297
Fold 2 IBS: 0.18039920275165355
Fold 3 IBS: 0.18517396368706437
Fold 4 IBS: 0.1961580074360814
Fold 5 IBS: 0.195878956164384
[I 2024-04-16 01:00:10,723] Trial 24 finished with value: 0.1894369520436226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19405738204668507
Fold 2 IBS: 0.19184743202663856
Fold 3 IBS: 0.19007884771101807
Fold 4 IBS: 0.20222541889504655
Fold 5 IBS: 0.20019121612149113
[I 2024-04-16 01:00:14,400] Trial 25 finished with value: 0.19568005936017588 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1940402932834844
Fold 2 IBS: 0.19432298692911043
Fold 3 IBS: 0.1892928247871703
Fold 4 IBS: 0.20429929982391268
Fold 5 IBS: 0.2021205628117341
[I 2024-04-16 01:00:20,201] Trial 26 finished with value: 0.19681519352708238 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19637495341237682
Fold 2 IBS: 0.1958296716242794
Fold 3 IBS: 0.19032854761836807
Fold 4 IBS: 0.20681694152044366
Fold 5 IBS: 0.2037201720927651
[I 2024-04-16 01:00:25,333] Trial 27 finished with value: 0.19861405725364661 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1975709578546784
Fold 2 IBS: 0.19829442573017972
Fold 3 IBS: 0.1915470690360173
Fold 4 IBS: 0.21031250675637114
Fold 5 IBS: 0.20365042057523824
[I 2024-04-16 01:00:28,743] Trial 28 finished with value: 0.20027507599049693 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.20387777006226956
Fold 2 IBS: 0.21044805665332703
Fold 3 IBS: 0.1968442774138352
Fold 4 IBS: 0.21672718054203935
Fold 5 IBS: 0.2104572520340109
[I 2024-04-16 01:00:31,677] Trial 29 finished with value: 0.20767090734109636 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.18218668005091396.

Fold 1 IBS: 0.18923073618097216
Fold 2 IBS: 0.17632006586851645
Fold 3 IBS: 0.18707067058836963
Fold 4 IBS: 0.19307240934736852
Fold 5 IBS: 0.19343354994654252
[I 2024-04-16 01:00:36,398] Trial 30 finished with value: 0.18782548638635385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1949036294792145
Fold 2 IBS: 0.1886371865011974
Fold 3 IBS: 0.19117863815442443
Fold 4 IBS: 0.2001198684681372
Fold 5 IBS: 0.19929856633981852
[I 2024-04-16 01:00:40,793] Trial 31 finished with value: 0.19482757778855841 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7284646777879923, 'min_weight_fraction_leaf': 0.03048718971899994}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.18836540230737153
Fold 2 IBS: 0.1781707184035029
Fold 3 IBS: 0.18564681721521098
Fold 4 IBS: 0.19277633701007463
Fold 5 IBS: 0.19331832607908583
[I 2024-04-16 01:00:44,224] Trial 32 finished with value: 0.18765552020304915 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8171100382086772, 'min_weight_fraction_leaf': 0.06242514513187879}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1837243286986642
Fold 2 IBS: 0.1726544375035722
Fold 3 IBS: 0.1857048039781507
Fold 4 IBS: 0.18788491866873833
Fold 5 IBS: 0.18954352546044614
[I 2024-04-16 01:00:49,740] Trial 33 finished with value: 0.18390240286191434 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.905569688846346, 'min_weight_fraction_leaf': 0.06699217911977255}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1801276242273068
Fold 2 IBS: 0.16520339426201733
Fold 3 IBS: 0.18553268896786967
Fold 4 IBS: 0.1845750159169672
Fold 5 IBS: 0.1835692206281775
[I 2024-04-16 01:00:55,023] Trial 34 finished with value: 0.1798015888004677 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.10969593086442025}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18049877857539035
Fold 2 IBS: 0.16663989287720696
Fold 3 IBS: 0.18469182662740596
Fold 4 IBS: 0.18574114889368326
Fold 5 IBS: 0.18477116270355273
[I 2024-04-16 01:01:01,713] Trial 35 finished with value: 0.18046856193544786 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 457, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9462418908074179, 'min_weight_fraction_leaf': 0.11750983562787085}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18037101974860273
Fold 2 IBS: 0.1669625142647935
Fold 3 IBS: 0.18453294697417297
Fold 4 IBS: 0.18631688561897877
Fold 5 IBS: 0.18678549330288546
[I 2024-04-16 01:01:07,403] Trial 36 finished with value: 0.18099377198188668 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.923638047949589, 'min_weight_fraction_leaf': 0.1257504807357439}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17994058405266816
Fold 2 IBS: 0.1669807265270973
Fold 3 IBS: 0.18438556878610593
Fold 4 IBS: 0.18645614257107018
Fold 5 IBS: 0.18554286319286462
[I 2024-04-16 01:01:13,945] Trial 37 finished with value: 0.18066117702596124 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.927527615447799, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18898732734511295
Fold 2 IBS: 0.1878387228485354
Fold 3 IBS: 0.18584838878907442
Fold 4 IBS: 0.20176513401286975
Fold 5 IBS: 0.1980065946518465
[I 2024-04-16 01:01:19,442] Trial 38 finished with value: 0.1924892335294878 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 413, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.22752773294338688}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17998400007564072
Fold 2 IBS: 0.1668284973568401
Fold 3 IBS: 0.1844288585354833
Fold 4 IBS: 0.1864703671417796
Fold 5 IBS: 0.18549779412503536
[I 2024-04-16 01:01:27,913] Trial 39 finished with value: 0.1806419034469558 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 395, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9298380017873809, 'min_weight_fraction_leaf': 0.12443904045417477}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.19739525553280404
Fold 2 IBS: 0.1991580825645237
Fold 3 IBS: 0.1908160522932353
Fold 4 IBS: 0.2108648699893906
Fold 5 IBS: 0.20525415655389037
[I 2024-04-16 01:01:33,069] Trial 40 finished with value: 0.2006976833867688 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8393239125172784, 'min_weight_fraction_leaf': 0.2776601558023945}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18022938402780667
Fold 2 IBS: 0.16672467510224806
Fold 3 IBS: 0.18478016395935146
Fold 4 IBS: 0.18505725419817942
Fold 5 IBS: 0.18499738141995034
[I 2024-04-16 01:01:39,021] Trial 41 finished with value: 0.1803577717415072 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9543142613189195, 'min_weight_fraction_leaf': 0.12203673286244354}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17977178159556786
Fold 2 IBS: 0.1648846924548364
Fold 3 IBS: 0.18522486265052154
Fold 4 IBS: 0.18475497257812473
Fold 5 IBS: 0.18410321441673297
[I 2024-04-16 01:01:45,774] Trial 42 finished with value: 0.17974790473915667 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9452765507108519, 'min_weight_fraction_leaf': 0.11124594841889346}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.19434886045869684
Fold 2 IBS: 0.1937482656990757
Fold 3 IBS: 0.18774938995929302
Fold 4 IBS: 0.2069666602426304
Fold 5 IBS: 0.20174569854155797
[I 2024-04-16 01:01:57,589] Trial 43 finished with value: 0.1969117749802508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503494540371628, 'min_weight_fraction_leaf': 0.16912809120322597}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.17791881709956506
Fold 2 IBS: 0.16086621549432498
Fold 3 IBS: 0.1866107993369831
Fold 4 IBS: 0.18206826755641561
Fold 5 IBS: 0.18254737423971062
[I 2024-04-16 01:02:03,773] Trial 44 finished with value: 0.17800229474539986 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996789958831329, 'min_weight_fraction_leaf': 0.1062495666001656}. Best is trial 44 with value: 0.17800229474539986.

Fold 1 IBS: 0.18107213977138975
Fold 2 IBS: 0.17375539456626857
Fold 3 IBS: 0.18442566650093445
Fold 4 IBS: 0.19068424307356363
Fold 5 IBS: 0.18831741970696433
[I 2024-04-16 01:02:10,003] Trial 45 finished with value: 0.18365097272382416 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9992649320581628, 'min_weight_fraction_leaf': 0.15624439720920977}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.19953982633918327
Fold 2 IBS: 0.19967504623742535
Fold 3 IBS: 0.19245042867286613
Fold 4 IBS: 0.2085347403492104
Fold 5 IBS: 0.20542311562702958
[I 2024-04-16 01:02:17,388] Trial 46 finished with value: 0.20112463144514292 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 471, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8649488262826621, 'min_weight_fraction_leaf': 0.10003378636590125}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18628122203639155
Fold 2 IBS: 0.18394244229194334
Fold 3 IBS: 0.18418434284415144
Fold 4 IBS: 0.2000447066326781
Fold 5 IBS: 0.19669443529653688
[I 2024-04-16 01:02:23,047] Trial 47 finished with value: 0.19022942982034025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 328, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9498767799232638, 'min_weight_fraction_leaf': 0.20999351713918613}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18671807379697955
Fold 2 IBS: 0.1852509952197599
Fold 3 IBS: 0.18550487325289164
Fold 4 IBS: 0.20047588792062881
Fold 5 IBS: 0.19727228734012894
[I 2024-04-16 01:02:30,217] Trial 48 finished with value: 0.19104442350607775 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.797873402462955, 'min_weight_fraction_leaf': 0.1860519578289726}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.1826607073352976
Fold 2 IBS: 0.175421589749594
Fold 3 IBS: 0.18312277636383603
Fold 4 IBS: 0.19167275635552322
Fold 5 IBS: 0.18980799753609187
[I 2024-04-16 01:02:38,004] Trial 49 finished with value: 0.18453716546806856 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 476, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.961215604578711, 'min_weight_fraction_leaf': 0.11365414847803179}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17958611811383737
Fold 2 IBS: 0.17743708698305577
Fold 3 IBS: 0.1852250945699171
Fold 4 IBS: 0.19623907958032022
Fold 5 IBS: 0.19263688422130817
[I 2024-04-16 01:02:40,444] Trial 50 finished with value: 0.18622485269368774 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7701980857578967, 'min_weight_fraction_leaf': 0.13552189689536387}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17789145417182875
Fold 2 IBS: 0.1616433832004363
Fold 3 IBS: 0.1864085525144377
Fold 4 IBS: 0.18238123808283335
Fold 5 IBS: 0.18355417475301875
[I 2024-04-16 01:02:46,836] Trial 51 finished with value: 0.17837576054451096 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 399, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9009463698475542, 'min_weight_fraction_leaf': 0.09217858789465802}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17799920113623321
Fold 2 IBS: 0.1605144874097507
Fold 3 IBS: 0.18702940084671463
Fold 4 IBS: 0.1819808205423802
Fold 5 IBS: 0.18038337030867524
[I 2024-04-16 01:02:53,798] Trial 52 finished with value: 0.1775814560487508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 354, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8951291579049074, 'min_weight_fraction_leaf': 0.08581751823710401}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17775260791357536
Fold 2 IBS: 0.16149694714321464
Fold 3 IBS: 0.18707407916258054
Fold 4 IBS: 0.18274340233986375
Fold 5 IBS: 0.18259760716876144
[I 2024-04-16 01:03:00,799] Trial 53 finished with value: 0.17833292874559917 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.09240390871992925}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17940640525802973
Fold 2 IBS: 0.16245697210383966
Fold 3 IBS: 0.1891181060291726
Fold 4 IBS: 0.18256414899356924
Fold 5 IBS: 0.18141515612084266
[I 2024-04-16 01:03:07,118] Trial 54 finished with value: 0.17899215770109078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8266050067672521, 'min_weight_fraction_leaf': 0.08824574600148365}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19512770880551733
Fold 2 IBS: 0.19505507233319871
Fold 3 IBS: 0.19092891056177175
Fold 4 IBS: 0.20445218046771954
Fold 5 IBS: 0.2016905007036287
[I 2024-04-16 01:03:14,609] Trial 55 finished with value: 0.19745087457436722 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8830194506473868, 'min_weight_fraction_leaf': 0.08551025986155897}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19639982363347272
Fold 2 IBS: 0.19605394572022347
Fold 3 IBS: 0.19089762812749347
Fold 4 IBS: 0.2039025193177431
Fold 5 IBS: 0.20198750112683878
[I 2024-04-16 01:03:20,912] Trial 56 finished with value: 0.19784828358515433 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8305267551869411, 'min_weight_fraction_leaf': 0.08769411360825642}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17994763927738225
Fold 2 IBS: 0.1548261798648236
Fold 3 IBS: 0.19395939238204377
Fold 4 IBS: 0.175460592586965
Fold 5 IBS: 0.1780360580615449
[I 2024-04-16 01:03:28,918] Trial 57 finished with value: 0.1764459724345519 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9047823438465082, 'min_weight_fraction_leaf': 0.052520359548060905}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.21397444187069029
Fold 2 IBS: 0.22136998164786137
Fold 3 IBS: 0.2048209672135687
Fold 4 IBS: 0.22466869218034594
Fold 5 IBS: 0.21857265758585154
[I 2024-04-16 01:03:36,493] Trial 58 finished with value: 0.21668134809966358 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8971095327680366, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17919617267498053
Fold 2 IBS: 0.15724293354129823
Fold 3 IBS: 0.18865418939534942
Fold 4 IBS: 0.17914737264855643
Fold 5 IBS: 0.17930084192384113
[I 2024-04-16 01:03:43,872] Trial 59 finished with value: 0.17670830203680515 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8551879186310293, 'min_weight_fraction_leaf': 0.052198438381039824}. Best is trial 57 with value: 0.1764459724345519.

Fold 1 IBS: 0.17659457791938485
Fold 2 IBS: 0.15948702371575116
Fold 3 IBS: 0.18725320428102982
Fold 4 IBS: 0.18157027728642194
Fold 5 IBS: 0.18138733472020935
[I 2024-04-16 01:03:53,732] Trial 60 finished with value: 0.17725848358455942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 346, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7897702249078459, 'min_weight_fraction_leaf': 0.017004106952235656}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17815851130122365
Fold 2 IBS: 0.15937759601308119
Fold 3 IBS: 0.18671233531081954
Fold 4 IBS: 0.18030514263303932
Fold 5 IBS: 0.18041925981213724
[I 2024-04-16 01:04:02,627] Trial 61 finished with value: 0.1769945690140602 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8618449302748573, 'min_weight_fraction_leaf': 0.05544116405394582}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.189985439243045
Fold 2 IBS: 0.18589864301215556
Fold 3 IBS: 0.1868011652028388
Fold 4 IBS: 0.1963593578324162
Fold 5 IBS: 0.19462526820614628
[I 2024-04-16 01:04:10,457] Trial 62 finished with value: 0.19073397469932035 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7867417360932117, 'min_weight_fraction_leaf': 0.05261239827242224}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17825665056431175
Fold 2 IBS: 0.15873188722190795
Fold 3 IBS: 0.18623232494405856
Fold 4 IBS: 0.1804776675580393
Fold 5 IBS: 0.18054470634521663
[I 2024-04-16 01:04:19,852] Trial 63 finished with value: 0.17684864732670685 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 370, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8646509137730156, 'min_weight_fraction_leaf': 0.021855538175638154}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17870866019509835
Fold 2 IBS: 0.15879041008416891
Fold 3 IBS: 0.1868471374565984
Fold 4 IBS: 0.17989027006562788
Fold 5 IBS: 0.18013032641306964
[I 2024-04-16 01:04:29,555] Trial 64 finished with value: 0.17687336084291264 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8648441638800866, 'min_weight_fraction_leaf': 0.01786212960035921}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17816324436800104
Fold 2 IBS: 0.16489393379706804
Fold 3 IBS: 0.18434438709838466
Fold 4 IBS: 0.1849311299136772
Fold 5 IBS: 0.18219012941004298
[I 2024-04-16 01:04:36,792] Trial 65 finished with value: 0.17890456491743478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 312, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.017748854587234637}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17911936362446912
Fold 2 IBS: 0.16110107360924447
Fold 3 IBS: 0.18681685101625886
Fold 4 IBS: 0.18222885762114663
Fold 5 IBS: 0.18129003273610622
[I 2024-04-16 01:04:44,453] Trial 66 finished with value: 0.17811123572144505 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7615860595939867, 'min_weight_fraction_leaf': 0.01711923253055358}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19752620497233223
Fold 2 IBS: 0.1978697596463517
Fold 3 IBS: 0.19204767218293306
Fold 4 IBS: 0.20544650914067045
Fold 5 IBS: 0.20224204696962983
[I 2024-04-16 01:04:58,110] Trial 67 finished with value: 0.19902643858238345 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6948127421387615, 'min_weight_fraction_leaf': 0.0007645315715799281}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18980037835825866
Fold 2 IBS: 0.18504474080399536
Fold 3 IBS: 0.18675479711869114
Fold 4 IBS: 0.19583872452973888
Fold 5 IBS: 0.1964614031322392
[I 2024-04-16 01:05:07,970] Trial 68 finished with value: 0.19078000878858464 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7554408511314311, 'min_weight_fraction_leaf': 0.05091993963276509}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19466218577890979
Fold 2 IBS: 0.19389682402255248
Fold 3 IBS: 0.1911241110746692
Fold 4 IBS: 0.2034533752298619
Fold 5 IBS: 0.20173582211641464
[I 2024-04-16 01:05:20,252] Trial 69 finished with value: 0.19697446364448162 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8049955125325536, 'min_weight_fraction_leaf': 0.06630598317301307}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18081283621129376
Fold 2 IBS: 0.16107815895963368
Fold 3 IBS: 0.18537244320497517
Fold 4 IBS: 0.18258777899134426
Fold 5 IBS: 0.1815710558255509
[I 2024-04-16 01:05:27,987] Trial 70 finished with value: 0.17828445463855955 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8704614691107458, 'min_weight_fraction_leaf': 0.03817571210017591}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.1784816385243448
Fold 2 IBS: 0.15527940159437076
Fold 3 IBS: 0.189332198745705
Fold 4 IBS: 0.17821728855635274
Fold 5 IBS: 0.17857494171269278
[I 2024-04-16 01:05:39,484] Trial 71 finished with value: 0.17597709382669321 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8554024477419847, 'min_weight_fraction_leaf': 0.025336147177118625}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17798712426248403
Fold 2 IBS: 0.15484687758413454
Fold 3 IBS: 0.19067949460417397
Fold 4 IBS: 0.17810023131975267
Fold 5 IBS: 0.17841198739744782
[I 2024-04-16 01:05:51,021] Trial 72 finished with value: 0.1760051430335986 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8330512937031878, 'min_weight_fraction_leaf': 0.018742428478884406}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17863483477490216
Fold 2 IBS: 0.1551139005400038
Fold 3 IBS: 0.18916719727949505
Fold 4 IBS: 0.17811149370150642
Fold 5 IBS: 0.1783525956517838
[I 2024-04-16 01:06:04,324] Trial 73 finished with value: 0.17587600438953827 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8535353080113882, 'min_weight_fraction_leaf': 0.02393524919371511}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17931869016352942
Fold 2 IBS: 0.15516920228584516
Fold 3 IBS: 0.19388065315077987
Fold 4 IBS: 0.17839512488731568
Fold 5 IBS: 0.17847323379272784
[I 2024-04-16 01:06:16,259] Trial 74 finished with value: 0.1770473808560396 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8501055473932629, 'min_weight_fraction_leaf': 0.028866969062217605}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.21400073415496554
Fold 2 IBS: 0.2208296768873117
Fold 3 IBS: 0.20504439468604338
Fold 4 IBS: 0.22482948519570425
Fold 5 IBS: 0.21793226667188703
[I 2024-04-16 01:06:30,835] Trial 75 finished with value: 0.21652731151918242 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.28939609623192764, 'min_weight_fraction_leaf': 0.38792353869222}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18092605908791307
Fold 2 IBS: 0.1626714178491272
Fold 3 IBS: 0.1886398695722679
Fold 4 IBS: 0.18093264680250482
Fold 5 IBS: 0.18045471816506836
[I 2024-04-16 01:06:40,941] Trial 76 finished with value: 0.17872494229537628 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827568227091456, 'min_weight_fraction_leaf': 0.07075108588012974}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17853049514002048
Fold 2 IBS: 0.1606985623136455
Fold 3 IBS: 0.18934483196588067
Fold 4 IBS: 0.18117152161929295
Fold 5 IBS: 0.18168995291214574
[I 2024-04-16 01:06:50,697] Trial 77 finished with value: 0.17828707279019707 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 253, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8619520401496605, 'min_weight_fraction_leaf': 0.0541974809924827}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19018486273820845
Fold 2 IBS: 0.18580998501512688
Fold 3 IBS: 0.18646870485036496
Fold 4 IBS: 0.20416606516994676
Fold 5 IBS: 0.1976686334381368
[I 2024-04-16 01:07:13,934] Trial 78 finished with value: 0.19285965024235677 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4023122117577047, 'min_weight_fraction_leaf': 0.011653305300887117}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18468957100688832
Fold 2 IBS: 0.16220991806931515
Fold 3 IBS: 0.18433081379618457
Fold 4 IBS: 0.17919815038465237
Fold 5 IBS: 0.18126334949504005
[I 2024-04-16 01:07:31,578] Trial 79 finished with value: 0.1783383605504161 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.03184523795085815}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17809409767141368
Fold 2 IBS: 0.16747623448062568
Fold 3 IBS: 0.18492844526895663
Fold 4 IBS: 0.18608517724457674
Fold 5 IBS: 0.18436399027788122
[I 2024-04-16 01:07:42,930] Trial 80 finished with value: 0.18018958898869078 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7484656416215983, 'min_weight_fraction_leaf': 0.04261824663727039}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17861172388733232
Fold 2 IBS: 0.15579353335819895
Fold 3 IBS: 0.1930699509858784
Fold 4 IBS: 0.17862157523488698
Fold 5 IBS: 0.17918780109521346
[I 2024-04-16 01:07:53,784] Trial 81 finished with value: 0.17705691691230202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 263, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8580633834636456, 'min_weight_fraction_leaf': 0.026226351015522897}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17739332474625047
Fold 2 IBS: 0.15403352099493925
Fold 3 IBS: 0.19030462796552475
Fold 4 IBS: 0.17855931327525473
Fold 5 IBS: 0.1790999880755793
[I 2024-04-16 01:08:09,587] Trial 82 finished with value: 0.1758781550115097 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8118689779244362, 'min_weight_fraction_leaf': 0.0010966926240786878}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1773851694171574
Fold 2 IBS: 0.16253921619926498
Fold 3 IBS: 0.18775729750357517
Fold 4 IBS: 0.1836022417123993
Fold 5 IBS: 0.18177710952263798
[I 2024-04-16 01:08:23,303] Trial 83 finished with value: 0.17861220687100693 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8057382985870164, 'min_weight_fraction_leaf': 0.009258817492808987}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1854433030470413
Fold 2 IBS: 0.17681758475146342
Fold 3 IBS: 0.18419070581251012
Fold 4 IBS: 0.19690664360230137
Fold 5 IBS: 0.19542658681834563
[I 2024-04-16 01:08:35,120] Trial 84 finished with value: 0.18775696480633236 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.00018800640948312233}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19527212215204012
Fold 2 IBS: 0.19258034396176488
Fold 3 IBS: 0.19043822340063868
Fold 4 IBS: 0.202063421121186
Fold 5 IBS: 0.2007148431354912
[I 2024-04-16 01:08:46,803] Trial 85 finished with value: 0.19621379075422415 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9164856547650563, 'min_weight_fraction_leaf': 0.04956990041330743}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1784741230904449
Fold 2 IBS: 0.16087953939758443
Fold 3 IBS: 0.1866329755757358
Fold 4 IBS: 0.18365448231497417
Fold 5 IBS: 0.1817122965130897
[I 2024-04-16 01:09:04,062] Trial 86 finished with value: 0.1782706833783658 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8799886531366731, 'min_weight_fraction_leaf': 0.0714128496838598}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18097049161570794
Fold 2 IBS: 0.1577854964552635
Fold 3 IBS: 0.18632859616594455
Fold 4 IBS: 0.17862370973831698
Fold 5 IBS: 0.1800955319809405
[I 2024-04-16 01:09:17,711] Trial 87 finished with value: 0.17676076519123468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8197308829626436, 'min_weight_fraction_leaf': 0.02805135094342286}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19437352689769452
Fold 2 IBS: 0.1865309874000275
Fold 3 IBS: 0.19048273944837096
Fold 4 IBS: 0.19874750141792227
Fold 5 IBS: 0.19780307418997603
[I 2024-04-16 01:09:32,785] Trial 88 finished with value: 0.19358756587079823 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 283, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8170223392194952, 'min_weight_fraction_leaf': 0.026015865108324397}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1843070555126035
Fold 2 IBS: 0.16138922163775485
Fold 3 IBS: 0.184029881060334
Fold 4 IBS: 0.18094300604589247
Fold 5 IBS: 0.18208306151695186
[I 2024-04-16 01:09:40,375] Trial 89 finished with value: 0.17855044515470733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.709051290189657, 'min_weight_fraction_leaf': 0.03884059880747235}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.18417873567489768
Fold 2 IBS: 0.17215507074054423
Fold 3 IBS: 0.18759974758071274
Fold 4 IBS: 0.1889870504957803
Fold 5 IBS: 0.18950903071510605
[I 2024-04-16 01:09:52,546] Trial 90 finished with value: 0.1844859270414082 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 262, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9722689668575789, 'min_weight_fraction_leaf': 0.013698489831834436}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17828049657703648
Fold 2 IBS: 0.15670442146325114
Fold 3 IBS: 0.1885595963781235
Fold 4 IBS: 0.17837564239035944
Fold 5 IBS: 0.17924664597888262
[I 2024-04-16 01:10:07,091] Trial 91 finished with value: 0.17623336055753064 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396105042050885, 'min_weight_fraction_leaf': 0.053257094236011215}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17808001067342502
Fold 2 IBS: 0.15510139507880186
Fold 3 IBS: 0.18938170342854968
Fold 4 IBS: 0.1775338584977204
Fold 5 IBS: 0.17890319352130446
[I 2024-04-16 01:10:18,245] Trial 92 finished with value: 0.17580003223996027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17659770951694037
Fold 2 IBS: 0.16139548906489803
Fold 3 IBS: 0.1883833499377513
Fold 4 IBS: 0.18122376165938103
Fold 5 IBS: 0.18108443878413408
[I 2024-04-16 01:10:29,046] Trial 93 finished with value: 0.17773694979262095 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7779337650340382, 'min_weight_fraction_leaf': 0.07493855611907659}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1788420501389833
Fold 2 IBS: 0.1563664608382856
Fold 3 IBS: 0.1914656292286683
Fold 4 IBS: 0.17846880498246692
Fold 5 IBS: 0.17925187035417264
[I 2024-04-16 01:10:42,292] Trial 94 finished with value: 0.17687896310851536 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8379618640137403, 'min_weight_fraction_leaf': 0.06135463764973173}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.18233221300286004
Fold 2 IBS: 0.1548941049902076
Fold 3 IBS: 0.1911036971629455
Fold 4 IBS: 0.17526110217876542
Fold 5 IBS: 0.17738838491733422
[I 2024-04-16 01:10:58,128] Trial 95 finished with value: 0.17619590045042255 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9112906365218221, 'min_weight_fraction_leaf': 0.035312691708068014}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.19307487236591833
Fold 2 IBS: 0.1896720972205889
Fold 3 IBS: 0.189921274941199
Fold 4 IBS: 0.19850258678674562
Fold 5 IBS: 0.19947771844377382
[I 2024-04-16 01:11:10,062] Trial 96 finished with value: 0.19412970995164514 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.915276824625892, 'min_weight_fraction_leaf': 0.043225362789876695}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17892075643860444
Fold 2 IBS: 0.15510444608753537
Fold 3 IBS: 0.19306794455023804
Fold 4 IBS: 0.17799888388058782
Fold 5 IBS: 0.1791674987979104
[I 2024-04-16 01:11:20,427] Trial 97 finished with value: 0.17685190595097522 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6707252385790339, 'min_weight_fraction_leaf': 0.03691531290573905}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.20874228003675835
Fold 2 IBS: 0.21425684765888878
Fold 3 IBS: 0.19860629371051958
Fold 4 IBS: 0.21913583881591187
Fold 5 IBS: 0.21337794366871632
[I 2024-04-16 01:11:30,619] Trial 98 finished with value: 0.210823840778159 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7396489612918897, 'min_weight_fraction_leaf': 0.3157312701103638}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1810496922027384
Fold 2 IBS: 0.15501841966956653
Fold 3 IBS: 0.19245123255364907
Fold 4 IBS: 0.17446547560484074
Fold 5 IBS: 0.17710424236035277
[I 2024-04-16 01:11:39,373] Trial 99 finished with value: 0.1760178124782295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8849892919469375, 'min_weight_fraction_leaf': 0.007259167100140962}. Best is trial 92 with value: 0.17580003223996027.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.17580003223996027], datetime_start=datetime.datetime(2024, 4, 16, 1, 10, 7, 129405), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 18, 244271), params={'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=92, value=None)


* Best Score for IBS:
 0.17580003223996027

In [54]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.176

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=19, max_features=1, max_leaf_nodes=12,
                   max_samples=0.21404335777324493, min_samples_leaf=1,
                   min_samples_split=4,
                   min_weight_fraction_leaf=0.0013133682808468272,
                   n_estimators=405, random_state=123, warm_start=True)

C-index score: 0.572

ExtraSurvivalTrees(max_depth=14, max_features=None, max_leaf_nodes=6,
                   max_samples=0.8396800309305413, min_samples_leaf=5,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.02494499808293557,
                   n_estimators=305, oob_score=True, random_state=123)

IBS: 0.221

In [58]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:11:43,532] A new study created in memory with name: no-name-e1a887f7-ad0a-4b6d-9ad9-990f03ba831f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:12:32,244] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:12:55,311] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:13:32,210] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:14:33,153] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:15:02,409] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:15:11,626] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:16:24,973] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:16:50,983] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:16:54,043] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:21:15,979] Trial 9 finished with value: 0.7610259439316011 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.7253521126760564
[I 2024-04-16 01:26:42,156] Trial 10 finished with value: 0.6762046627675529 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:30:29,714] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:35:16,441] Trial 12 finished with value: 0.7542227664538642 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:38:10,622] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:41:34,742] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:45:57,647] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:48:16,784] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:50:58,302] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:54:28,813] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:54:35,899] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:55:41,147] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 01:57:48,443] Trial 21 finished with value: 0.6762505605169181 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 01:59:42,714] Trial 22 finished with value: 0.713908524620727 and parameters: {'subsample': 0.8956069884856214, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2154325997461391, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.38657871816113815, 'max_features': 'auto', 'min_impurity_decrease': 5.581115247824534e-07, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:01:16,248] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7743503496065262, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.31930849090648333, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9663328483036315, 'min_weight_fraction_leaf': 0.441052304834414, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:02:24,469] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8969825748215434, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21976013005558012, 'n_estimators': 340, 'criterion': 'squared_error', 'ccp_alpha': 0.785180332493211, 'min_weight_fraction_leaf': 0.2669492013977464, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:03:40,524] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8840318412875596, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.27382248438555523, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 2.0183033060186855, 'min_weight_fraction_leaf': 0.33643534713187806, 'max_features': 'auto', 'min_impurity_decrease': 5.889654690360788e-06, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:04:57,750] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7565765917190008, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.4300954216773497, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6678836557349488, 'min_weight_fraction_leaf': 0.06207030473994396, 'max_features': 1, 'min_impurity_decrease': 7.622421032390112e-07, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:06:53,106] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.322970332048742, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 5.9472530603001, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 7.551787280023211e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:07:32,094] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.5232204998663266, 'n_estimators': 326, 'criterion': 'squared_error', 'ccp_alpha': 4.188554251555486, 'min_weight_fraction_leaf': 0.43612805409636834, 'max_features': 0.1, 'min_impurity_decrease': 3.2161459286083955e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:07:40,893] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.32499045544570565, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 2.694991982922698, 'min_weight_fraction_leaf': 0.37973053029520576, 'max_features': 'log2', 'min_impurity_decrease': 1.983769791843576e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:08:09,628] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.1618733123667288, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.29835074442775955, 'max_features': 'auto', 'min_impurity_decrease': 3.855449012555335e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:09:59,923] Trial 31 finished with value: 0.7183781009689083 and parameters: {'subsample': 0.9458857893837966, 'learning_rate': 0.016420196712320707, 'dropout_rate': 0.2035906465216125, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.36089352993330637, 'max_features': 'auto', 'min_impurity_decrease': 4.318534340206297e-07, 'validation_fraction': 0.9595045281115817, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 02:11:52,376] Trial 32 finished with value: 0.7475960929275194 and parameters: {'subsample': 0.8638126341310897, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.22569622133720652, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.019083703384414813, 'min_weight_fraction_leaf': 0.351646089861356, 'max_features': 'auto', 'min_impurity_decrease': 1.0352347378444166e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:13:31,725] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9565444847948921, 'learning_rate': 0.016942278074178134, 'dropout_rate': 0.26584476281814184, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.3586353681932053, 'max_features': 'auto', 'min_impurity_decrease': 1.3326513674306949e-07, 'validation_fraction': 0.8389914767654065, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:15:05,459] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7038358300021869, 'learning_rate': 0.026650337425697362, 'dropout_rate': 0.369220485987212, 'n_estimators': 472, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8672217172879074, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0420752279999204e-07, 'validation_fraction': 0.9169827663346786, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:16:22,801] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.8615302123878027, 'learning_rate': 0.016287667469869524, 'dropout_rate': 0.16621310899612352, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1524333738759642, 'min_weight_fraction_leaf': 0.16211724647631331, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:17:04,729] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6682496627875864, 'learning_rate': 0.030254735591726832, 'dropout_rate': 0.29166011812932907, 'n_estimators': 299, 'criterion': 'squared_error', 'ccp_alpha': 0.48701662298918014, 'min_weight_fraction_leaf': 0.24844276308137436, 'max_features': 'auto', 'min_impurity_decrease': 2.2923203534620568e-05, 'validation_fraction': 0.8152696073327098, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:17:38,339] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7883126136564298, 'learning_rate': 0.02225236619873, 'dropout_rate': 0.7511928761026783, 'n_estimators': 408, 'criterion': 'squared_error', 'ccp_alpha': 1.198246212835568, 'min_weight_fraction_leaf': 0.42198945643308866, 'max_features': None, 'min_impurity_decrease': 8.54824079758415e-06, 'validation_fraction': 0.36353542989298265, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:19:07,740] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0010786268484829992, 'dropout_rate': 0.4076069474884072, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.295727563116735, 'max_features': 'auto', 'min_impurity_decrease': 1.0214527419957568e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:20:27,853] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.041857701576065075, 'dropout_rate': 0.3444296796757608, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.49564059074376393, 'max_features': 1, 'min_impurity_decrease': 2.966650399906854e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:21:25,527] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5863013406787322, 'learning_rate': 0.007311607072090859, 'dropout_rate': 0.22290618957651392, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 0.5271854997531392, 'min_weight_fraction_leaf': 0.2674270064426415, 'max_features': 'auto', 'min_impurity_decrease': 2.2073664358493507e-07, 'validation_fraction': 0.6520524706411407, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 10}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6455399061032864
[I 2024-04-16 02:21:25,877] Trial 41 finished with value: 0.6429727820316606 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.01362396235680392, 'dropout_rate': 0.2062435369784147, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.01657550447328801, 'min_weight_fraction_leaf': 0.3505399688940837, 'max_features': 'auto', 'min_impurity_decrease': 3.2101990795082183e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6774891774891775
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7394366197183099
[I 2024-04-16 02:23:07,610] Trial 42 finished with value: 0.7155999282604174 and parameters: {'subsample': 0.8533107407997301, 'learning_rate': 0.007773927115663986, 'dropout_rate': 0.13112078909045524, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.002608770948556355, 'min_weight_fraction_leaf': 0.4128432753433128, 'max_features': 'auto', 'min_impurity_decrease': 5.944083612909987e-07, 'validation_fraction': 0.8846352497042296, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:24:59,118] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8537828670002746, 'learning_rate': 0.006387564095638705, 'dropout_rate': 0.14103084365529428, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.817694027019807, 'min_weight_fraction_leaf': 0.4055199685421495, 'max_features': 'auto', 'min_impurity_decrease': 1.0127188716001679e-07, 'validation_fraction': 0.8846775181555923, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:24,945] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9979692688170061, 'learning_rate': 0.018866368595143467, 'dropout_rate': 0.13470507680405208, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.1995459782383484, 'min_weight_fraction_leaf': 0.46282880746501454, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7785221066313981, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:28:01,029] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.9423581992051376, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.1841937912472535, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.415353860249426, 'min_weight_fraction_leaf': 0.21565594544774125, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.9726137478639892, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:28:11,377] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8422605515062627, 'learning_rate': 0.023740342140917903, 'dropout_rate': 0.9694253886674298, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 6.2946137459239395, 'min_weight_fraction_leaf': 0.32020062193032595, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0058604443673675e-07, 'validation_fraction': 0.8666993731020032, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:29:56,549] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.8213077858159359, 'learning_rate': 0.006066129837698666, 'dropout_rate': 0.2502078347914406, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 1.0929789618945918, 'min_weight_fraction_leaf': 0.37165158771817175, 'max_features': 'log2', 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.7292699872905781, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:30:36,442] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7434813106553043, 'learning_rate': 0.014252633864159536, 'dropout_rate': 0.10308804442602489, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 0.43583456106887075, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 'auto', 'min_impurity_decrease': 1.1669342789968816e-06, 'validation_fraction': 0.9922167438954732, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:30:53,029] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7918904765497661, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.46610361399140793, 'max_features': None, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8725986413596462, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:32:00,084] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9263228105960017, 'learning_rate': 0.03241286314321831, 'dropout_rate': 0.28503824367896063, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.3883012665777896, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 5.669547081135241e-07, 'validation_fraction': 0.21769072749948642, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7347417840375586
[I 2024-04-16 02:33:30,520] Trial 51 finished with value: 0.7185570650203711 and parameters: {'subsample': 0.8666208085311428, 'learning_rate': 0.010299237341157315, 'dropout_rate': 0.22486517268782114, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.01237319335130728, 'min_weight_fraction_leaf': 0.40520668278071015, 'max_features': 'auto', 'min_impurity_decrease': 4.3165690993230386e-07, 'validation_fraction': 0.9299180470052416, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7279411764705882
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:34:54,389] Trial 52 finished with value: 0.7047318894129233 and parameters: {'subsample': 0.862657875185063, 'learning_rate': 0.008306104796295998, 'dropout_rate': 0.2416732200644876, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.03660243985093782, 'min_weight_fraction_leaf': 0.42223276607292903, 'max_features': 'auto', 'min_impurity_decrease': 1.9405719092810494e-07, 'validation_fraction': 0.9395823090270392, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:36:41,231] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.967375882472721, 'learning_rate': 0.001394900878889816, 'dropout_rate': 0.1429837848690379, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.45374308869283775, 'min_weight_fraction_leaf': 0.4108404544677715, 'max_features': 'auto', 'min_impurity_decrease': 4.0655981745194066e-07, 'validation_fraction': 0.8259835575505652, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:38:32,666] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8134129014758551, 'learning_rate': 0.019733381620994493, 'dropout_rate': 0.18641432881009587, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.9596523069530926, 'min_weight_fraction_leaf': 0.2970013736941614, 'max_features': 'auto', 'min_impurity_decrease': 1.1580334563112213e-06, 'validation_fraction': 0.8996663522529539, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:28,731] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9195938698764112, 'learning_rate': 0.015173363534313505, 'dropout_rate': 0.3034930079612927, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.35259963018802765, 'min_weight_fraction_leaf': 0.36508275980555405, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.9545460877946491, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:40:49,444] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.5150383761242161, 'learning_rate': 0.004332984500606809, 'dropout_rate': 0.23996644019536584, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6264958328369468, 'min_weight_fraction_leaf': 0.3385656815459147, 'max_features': 'auto', 'min_impurity_decrease': 5.479611541769766e-07, 'validation_fraction': 0.9991586611408243, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 02:42:30,512] Trial 57 finished with value: 0.7056496649292628 and parameters: {'subsample': 0.8773751542246392, 'learning_rate': 0.008949552280352413, 'dropout_rate': 0.35136020576582316, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.001936457287774803, 'min_weight_fraction_leaf': 0.46006445679681335, 'max_features': 1, 'min_impurity_decrease': 4.834524920287448e-06, 'validation_fraction': 0.5189236064802895, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:44:17,247] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.6843244921733918, 'learning_rate': 0.0253510504546932, 'dropout_rate': 0.12033118040350205, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 1.625653153563989, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'auto', 'min_impurity_decrease': 1.5983704938418812e-07, 'validation_fraction': 0.7886847055500306, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:45:17,692] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.021369220605781735, 'dropout_rate': 0.4274904250363094, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.4410912197424578, 'max_features': 0.1, 'min_impurity_decrease': 3.251577586017116e-07, 'validation_fraction': 0.8548774558884649, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:45:33,430] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.18796169351263226, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 2.934583742024675, 'min_weight_fraction_leaf': 0.22745666702108258, 'max_features': 'log2', 'min_impurity_decrease': 1.7635925207609514e-06, 'validation_fraction': 0.8928900471979833, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:47:00,474] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.9082876532055691, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.22106826324294734, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22580244780696104, 'min_weight_fraction_leaf': 0.39038531498517337, 'max_features': 'auto', 'min_impurity_decrease': 6.513707268856941e-07, 'validation_fraction': 0.9307105316317981, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:48:48,334] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.9763302214447585, 'learning_rate': 0.01082289338801184, 'dropout_rate': 0.16671702405067812, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.7562237450148781, 'min_weight_fraction_leaf': 0.4020635676726066, 'max_features': 'auto', 'min_impurity_decrease': 9.006731163870761e-07, 'validation_fraction': 0.9167969646120265, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.744131455399061
[I 2024-04-16 02:50:35,874] Trial 63 finished with value: 0.7378685391643164 and parameters: {'subsample': 0.8703294082808486, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.2614766602947102, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.37595194847909125, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.9646429973127362, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:52:21,499] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7961678718772995, 'learning_rate': 0.015415575577593231, 'dropout_rate': 0.262554001169913, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.2777045506790212, 'min_weight_fraction_leaf': 0.33434502833689206, 'max_features': 'auto', 'min_impurity_decrease': 3.33975749875224e-07, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:59,650] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8385594937622445, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.30265220308227164, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.29056375204041135, 'min_weight_fraction_leaf': 0.28320128906700315, 'max_features': 'auto', 'min_impurity_decrease': 1.5031409606569138e-07, 'validation_fraction': 0.962588947418926, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:55:37,818] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8825125214383175, 'learning_rate': 0.01896416177644482, 'dropout_rate': 0.3845297883432178, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 2.1083391199212573, 'min_weight_fraction_leaf': 0.37068365181765817, 'max_features': 'auto', 'min_impurity_decrease': 2.926750067783851e-07, 'validation_fraction': 0.8532835495181553, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:57:02,290] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4585158632928328, 'learning_rate': 0.014185974978345665, 'dropout_rate': 0.20713420518497186, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.31472432527464905, 'max_features': 'sqrt', 'min_impurity_decrease': 4.927665175660364e-07, 'validation_fraction': 0.9061207180731781, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:58:29,102] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.9444579521154932, 'learning_rate': 0.003984164164187884, 'dropout_rate': 0.3349732603740458, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 1.078654850128927, 'min_weight_fraction_leaf': 0.1817947096952169, 'max_features': 'auto', 'min_impurity_decrease': 1.3822768751381375e-06, 'validation_fraction': 0.9998779842696178, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:59:22,453] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7351244679725103, 'learning_rate': 0.021607496405331474, 'dropout_rate': 0.6578270843665299, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.41822793529640967, 'max_features': 'auto', 'min_impurity_decrease': 7.981891756908656e-06, 'validation_fraction': 0.8252701554197789, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 03:00:48,425] Trial 70 finished with value: 0.7431871031407425 and parameters: {'subsample': 0.7696833733505561, 'learning_rate': 0.009479076517851487, 'dropout_rate': 0.27892959003506596, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.010016393064755276, 'min_weight_fraction_leaf': 0.38115268230138605, 'max_features': None, 'min_impurity_decrease': 1.0506244573812146e-07, 'validation_fraction': 0.7475037972329144, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7065727699530516
[I 2024-04-16 03:02:12,749] Trial 71 finished with value: 0.722533881479949 and parameters: {'subsample': 0.7726307722867607, 'learning_rate': 0.009349407530944867, 'dropout_rate': 0.272889788803047, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.43478396682346765, 'max_features': None, 'min_impurity_decrease': 1.417211124243175e-07, 'validation_fraction': 0.6051329974465358, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:42,683] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7701057123127394, 'learning_rate': 0.009957649760499912, 'dropout_rate': 0.27848137285412433, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.7357633085189087, 'min_weight_fraction_leaf': 0.37805750469189997, 'max_features': None, 'min_impurity_decrease': 1.0230782331935316e-07, 'validation_fraction': 0.6095946706874, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:04:51,213] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.82176382526325, 'learning_rate': 0.05058817311100894, 'dropout_rate': 0.23811185280532784, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.35666680166132303, 'min_weight_fraction_leaf': 0.4363333364980036, 'max_features': None, 'min_impurity_decrease': 1.4978008424793533e-07, 'validation_fraction': 0.6393756125190079, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:00,878] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6354098366620761, 'learning_rate': 0.013009902635057455, 'dropout_rate': 0.3101706081176934, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7099066346200665, 'min_weight_fraction_leaf': 0.4804502891962041, 'max_features': None, 'min_impurity_decrease': 2.271616193402817e-07, 'validation_fraction': 0.6862699083190502, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:07:25,986] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9104967643697162, 'learning_rate': 0.01724034992100258, 'dropout_rate': 0.26334849962817525, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.5692251904189567, 'min_weight_fraction_leaf': 0.35851813148439854, 'max_features': None, 'min_impurity_decrease': 2.0843558415731406e-07, 'validation_fraction': 0.5063775748030491, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:08:53,870] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5556564275523779, 'learning_rate': 0.0033204528527945613, 'dropout_rate': 0.3636837900816117, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3042363908259532, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.2249424139094463e-07, 'validation_fraction': 0.561045056767258, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:10:30,799] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7208569038924214, 'learning_rate': 0.026256982803923905, 'dropout_rate': 0.2305409399859041, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.9525490995769573, 'min_weight_fraction_leaf': 0.398138662499872, 'max_features': None, 'min_impurity_decrease': 3.9802168951657813e-07, 'validation_fraction': 0.7435745226595007, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.7723004694835681
[I 2024-04-16 03:11:38,537] Trial 78 finished with value: 0.7520537875882294 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.012134054211554952, 'dropout_rate': 0.17020981110797495, 'n_estimators': 371, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25792648841120175, 'max_features': None, 'min_impurity_decrease': 0.0002607692087694095, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 03:11:53,680] Trial 79 finished with value: 0.7612651729154684 and parameters: {'subsample': 0.5770898503146864, 'learning_rate': 0.005718089536250872, 'dropout_rate': 0.8831816560103296, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.006784676195889549, 'min_weight_fraction_leaf': 0.26783577777991785, 'max_features': None, 'min_impurity_decrease': 0.00026754667959111344, 'validation_fraction': 0.45556658035861064, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:12:05,637] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.005715181757518938, 'dropout_rate': 0.8564920404565602, 'n_estimators': 301, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.2585934440223751, 'max_features': None, 'min_impurity_decrease': 0.00022588848940598272, 'validation_fraction': 0.4281000770625221, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 03:12:33,971] Trial 81 finished with value: 0.7574041343834572 and parameters: {'subsample': 0.573469759644561, 'learning_rate': 0.00917313652468523, 'dropout_rate': 0.7551006664918564, 'n_estimators': 378, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025432538716388925, 'min_weight_fraction_leaf': 0.2330447322703676, 'max_features': None, 'min_impurity_decrease': 0.0003172843737611832, 'validation_fraction': 0.47647246663093756, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:12:51,926] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.6061238477976733, 'learning_rate': 0.012604022944147218, 'dropout_rate': 0.8294471229873877, 'n_estimators': 356, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5341063025845167, 'min_weight_fraction_leaf': 0.19664785169557314, 'max_features': None, 'min_impurity_decrease': 0.0007825748634975355, 'validation_fraction': 0.3806000784667706, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:13:06,075] Trial 83 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6535018868517685, 'learning_rate': 0.0014826800610252661, 'dropout_rate': 0.8992417742346922, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20169466462041857, 'min_weight_fraction_leaf': 0.22451223837031314, 'max_features': None, 'min_impurity_decrease': 0.0003609663069928288, 'validation_fraction': 0.4711031887993497, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:13:32,534] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.58189223841496, 'learning_rate': 0.008316297732970858, 'dropout_rate': 0.6818395627907664, 'n_estimators': 335, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.28172882309407266, 'max_features': None, 'min_impurity_decrease': 0.001202775121736422, 'validation_fraction': 0.38945203718855725, 'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 79 with value: 0.7612651729154684.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:13:51,446] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.6947678980383888, 'learning_rate': 0.06101724551624799, 'dropout_rate': 0.7652597742653805, 'n_estimators': 317, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5339563287597978, 'min_weight_fraction_leaf': 0.24506733493657065, 'max_features': None, 'min_impurity_decrease': 0.0001261040433430487, 'validation_fraction': 0.46765139398223676, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:14:08,435] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5329646889170038, 'learning_rate': 0.006001760143614843, 'dropout_rate': 0.8650393351469537, 'n_estimators': 381, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2772447793960837, 'min_weight_fraction_leaf': 0.2595916601449126, 'max_features': None, 'min_impurity_decrease': 8.277387430400139e-05, 'validation_fraction': 0.5331294902958005, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:14:48,891] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5772171688575647, 'learning_rate': 0.012297427382052604, 'dropout_rate': 0.5450508211122536, 'n_estimators': 389, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8948782241791482, 'min_weight_fraction_leaf': 0.30432090537719336, 'max_features': None, 'min_impurity_decrease': 0.000380077265080333, 'validation_fraction': 0.5815548971606083, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:14:53,546] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4900792232135173, 'learning_rate': 0.01688118268369649, 'dropout_rate': 0.9961303410511458, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 0.32151562869669414, 'min_weight_fraction_leaf': 0.22873481062830656, 'max_features': None, 'min_impurity_decrease': 0.0016050858690837527, 'validation_fraction': 0.47521875145819903, 'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 03:15:17,102] Trial 89 finished with value: 0.7615428784886943 and parameters: {'subsample': 0.6088139660412204, 'learning_rate': 0.007354720529210388, 'dropout_rate': 0.7165927205059781, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019083182133763817, 'min_weight_fraction_leaf': 0.16713831321323547, 'max_features': None, 'min_impurity_decrease': 6.11919023761631e-05, 'validation_fraction': 0.33082778557332754, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:15:39,393] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.6135996513302981, 'learning_rate': 0.0030759059571325367, 'dropout_rate': 0.714239153071518, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5934237823972953, 'min_weight_fraction_leaf': 0.15409787484394483, 'max_features': 1, 'min_impurity_decrease': 0.00026420223842921306, 'validation_fraction': 0.3182942803078493, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 03:16:18,452] Trial 91 finished with value: 0.7168916928997893 and parameters: {'subsample': 0.6770337747529735, 'learning_rate': 0.007750641496074201, 'dropout_rate': 0.49424724681798277, 'n_estimators': 365, 'criterion': 'friedman_mse', 'ccp_alpha': 0.15430903718460776, 'min_weight_fraction_leaf': 0.16791051943811458, 'max_features': None, 'min_impurity_decrease': 0.00012772803486333308, 'validation_fraction': 0.2316993389350888, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:16:36,905] Trial 92 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6546522174060683, 'learning_rate': 0.009421883094809201, 'dropout_rate': 0.8281440643598538, 'n_estimators': 347, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20594179048085923, 'min_weight_fraction_leaf': 0.1883593742681352, 'max_features': None, 'min_impurity_decrease': 0.0006394831666927118, 'validation_fraction': 0.2857429575523451, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 03:16:52,122] Trial 93 finished with value: 0.7646572367824584 and parameters: {'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:17:08,292] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.5329981668085512, 'learning_rate': 0.00588357274756517, 'dropout_rate': 0.9010663710372596, 'n_estimators': 398, 'criterion': 'friedman_mse', 'ccp_alpha': 0.795356671502603, 'min_weight_fraction_leaf': 0.2746770457528657, 'max_features': None, 'min_impurity_decrease': 4.317472301123062e-05, 'validation_fraction': 0.5341505661514357, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:17:21,531] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.6002877490535967, 'learning_rate': 0.0013964687008740234, 'dropout_rate': 0.913293216331538, 'n_estimators': 380, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4770423805467064, 'min_weight_fraction_leaf': 0.23547436381465842, 'max_features': 0.1, 'min_impurity_decrease': 6.5600170925824e-05, 'validation_fraction': 0.1768997582284634, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:17:35,179] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.5679830672067219, 'learning_rate': 0.014679960066405966, 'dropout_rate': 0.9491815550373798, 'n_estimators': 409, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0851736428778953, 'min_weight_fraction_leaf': 0.2093965001338856, 'max_features': 'log2', 'min_impurity_decrease': 0.0003929451723108634, 'validation_fraction': 0.4438191336127031, 'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 93 with value: 0.7646572367824584.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:17:57,129] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.6256579983686182, 'learning_rate': 0.019674657185705456, 'dropout_rate': 0.7920862318111374, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.09841883603325133, 'max_features': None, 'min_impurity_decrease': 0.0029478086506526746, 'validation_fraction': 0.4123056392425912, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:18:20,853] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5456143354363114, 'learning_rate': 0.012065355654311702, 'dropout_rate': 0.7084124127731201, 'n_estimators': 352, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8220715155379084, 'min_weight_fraction_leaf': 0.2513160795401591, 'max_features': None, 'min_impurity_decrease': 0.00015199016859086491, 'validation_fraction': 0.337785152154958, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-16 03:18:23,896] A new study created in memory with name: no-name-ad62f506-133a-44c3-9962-c3a9cbde009e

Fold 5 C-index: 0.5
[I 2024-04-16 03:18:23,862] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.599460814358584, 'learning_rate': 0.0043948047101492775, 'dropout_rate': 0.5980587986289647, 'n_estimators': 93, 'criterion': 'friedman_mse', 'ccp_alpha': 6.574588525520643, 'min_weight_fraction_leaf': 0.2853352301155438, 'max_features': None, 'min_impurity_decrease': 0.0002068890339707658, 'validation_fraction': 0.4936737452445755, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 93 with value: 0.7646572367824584.


* Best trial for C-index:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.7646572367824584], datetime_start=datetime.datetime(2024, 4, 16, 3, 16, 36, 912011), datetime_complete=datetime.datetime(2024, 4, 16, 3, 16, 52, 121121), params={'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=93, value=None)


* Best Score for C-index:
 0.7646572367824584

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:18:55,440] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:19:11,534] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:19:28,007] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:19:54,484] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:20:04,448] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:20:06,890] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:20:32,721] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:20:40,828] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:20:41,889] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21267714729986278
Fold 2 IBS: 0.21995458442119498
Fold 3 IBS: 0.2035491555712707
Fold 4 IBS: 0.22393486370134422
Fold 5 IBS: 0.21704380099016626
[I 2024-04-16 03:21:49,302] Trial 9 finished with value: 0.21543191039676776 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21361208429589837
Fold 2 IBS: 0.2211926211265032
Fold 3 IBS: 0.20422163542183314
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21784292940455638
[I 2024-04-16 03:23:30,301] Trial 10 finished with value: 0.21628654622010784 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:25:26,192] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21383702367729038
Fold 2 IBS: 0.22138950456459866
Fold 3 IBS: 0.20443495965406222
Fold 4 IBS: 0.22467340762574997
Fold 5 IBS: 0.21799662270999748
[I 2024-04-16 03:27:05,351] Trial 12 finished with value: 0.21646630364633973 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 03:27:54,228] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:29:17,785] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:30:30,359] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:31:10,425] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:32:39,565] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:33:27,892] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:33:35,743] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:35:02,667] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21372933425701268
Fold 2 IBS: 0.2215356606685715
Fold 3 IBS: 0.2044331250210804
Fold 4 IBS: 0.22465964732749286
Fold 5 IBS: 0.21808855196539592
[I 2024-04-16 03:36:32,534] Trial 21 finished with value: 0.2164892638479107 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21261860662587898
Fold 2 IBS: 0.2196324435594265

Fold 3 IBS: 0.20356521623761553
Fold 4 IBS: 0.22397661990425946
Fold 5 IBS: 0.21681927203314136
[I 2024-04-16 03:38:14,751] Trial 22 finished with value: 0.21532243167206438 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:39:47,417] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:40:47,806] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:41:45,716] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:43:12,763] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:43:21,480] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:43:49,482] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:44:58,572] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:45:32,431] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2135108348694222
Fold 2 IBS: 0.221167731954742
Fold 3 IBS: 0.20422105908762206
Fold 4 IBS: 0.22456358064764176
Fold 5 IBS: 0.21787287595995244
[I 2024-04-16 03:47:05,132] Trial 31 finished with value: 0.2162672165038761 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21277031226041587
Fold 2 IBS: 0.21977571218645117
Fold 3 IBS: 0.2037868553635057
Fold 4 IBS: 0.22437947964183458
Fold 5 IBS: 0.2169740152088292
[I 2024-04-16 03:48:33,596] Trial 32 finished with value: 0.2155372749322073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:49:35,889] Trial 33 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9175730211318314, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.23558036461669868, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 2.2672612842512112e-05, 'validation_fraction': 0.8391863465064515, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:50:35,299] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6818728654527908, 'learning_rate': 0.014570474664799389, 'dropout_rate': 0.39687420252491534, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9857366581537508, 'min_weight_fraction_leaf': 0.2451263696303153, 'max_features': 'sqrt', 'min_impurity_decrease': 7.173213136739857e-06, 'validation_fraction': 0.9231140468377321, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:50:53,242] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7474352307553052, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.29459319086620417, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 7.199479090473024e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:52:08,974] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.3498267997183648, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.2894426185614589, 'max_features': 'auto', 'min_impurity_decrease': 6.773052750173388e-05, 'validation_fraction': 0.7819324141806283, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:52:11,492] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.23919145342953393, 'max_features': None, 'min_impurity_decrease': 2.5414170052989375e-06, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:52:55,775] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8670579303141319, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.1728262906688144, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42202283765123816, 'min_weight_fraction_leaf': 0.35239546646921105, 'max_features': 'auto', 'min_impurity_decrease': 0.00017081434930634308, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:53:35,093] Trial 39 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8154589849054708, 'learning_rate': 0.006878494063124208, 'dropout_rate': 0.5323261217237781, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 1.1477698683125066, 'min_weight_fraction_leaf': 0.11023361948341703, 'max_features': 1, 'min_impurity_decrease': 1.7677159455067355e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:54:39,869] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.22290618957651392, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.5274073849776741, 'min_weight_fraction_leaf': 0.2739610635014299, 'max_features': 'auto', 'min_impurity_decrease': 2.272398816394983e-07, 'validation_fraction': 0.8717079478922802, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2111176339922491
Fold 2 IBS: 0.21706325506301344
Fold 3 IBS: 0.20271114308166202
Fold 4 IBS: 0.22388756035618385
Fold 5 IBS: 0.21496756928312347
[I 2024-04-16 03:56:10,391] Trial 41 finished with value: 0.21394943235524638 and parameters: {'subsample': 0.993176118879571, 'learning_rate': 0.01271988915310228, 'dropout_rate': 0.152367046323752, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.19182471840022747, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21394943235524638.
Fold 1 IBS: 0.21089915783305027
Fold 2 IBS: 0.21498627855376068
Fold 3 IBS: 0.2034648608532915
Fold 4 IBS: 0.22110504116581475
Fold 5 IBS: 0.21385442301724614
[I 2024-04-16 03:57:50,693] Trial 42 finished with value: 0.21286195228463267 and parameters: {'subsample': 0.9646924257252548, 'learning_rate': 0.012507391626216524, 'dropout_rate': 0.10802959125648778, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327408119788757, 'min_weight_fraction_leaf': 0.13510597987400375, 'max_features': 'auto', 'min_impurity_decrease': 1.0593992090305253e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 03:59:30,745] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828284890903175, 'learning_rate': 0.011543268886217308, 'dropout_rate': 0.11584589616484722, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.09682559138790292, 'max_features': 'auto', 'min_impurity_decrease': 1.0125868029922384e-07, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:00:57,358] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992870370700113, 'learning_rate': 0.022847552015173876, 'dropout_rate': 0.1556807870961761, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.1403134453903068, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21224782790603694
Fold 2 IBS: 0.2189260608342495
Fold 3 IBS: 0.20307124042767
Fold 4 IBS: 0.22313607826909793
Fold 5 IBS: 0.216439921823279
[I 2024-04-16 04:01:30,318] Trial 45 finished with value: 0.2147642258520667 and parameters: {'subsample': 0.8888212863898438, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.20487736976615575, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.027893207681183953, 'min_weight_fraction_leaf': 0.06753391487815072, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9448766575733668, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:01:48,369] Trial 46 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.016684121596597847, 'dropout_rate': 0.10891325683572217, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.04784747079432074, 'max_features': 0.1, 'min_impurity_decrease': 2.0166271580558924e-07, 'validation_fraction': 0.24435732275143762, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:02:12,976] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7729061863940228, 'learning_rate': 0.02995584278149796, 'dropout_rate': 0.19790330487666663, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.05716507411653311, 'max_features': 0.1, 'min_impurity_decrease': 1.0699422270078741e-07, 'validation_fraction': 0.9565097869700105, 'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:02:51,765] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8446010144291817, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.14247687075474555, 'n_estimators': 294, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 0.1, 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.8246274171002186, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:03:17,097] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6917414996198523, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.2874751071933402, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.08230947204902768, 'max_features': 0.1, 'min_impurity_decrease': 1.8211699167585496e-07, 'validation_fraction': 0.6513576271964052, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:03:41,348] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.019482931131151772, 'dropout_rate': 0.6676032114338903, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.013701950422388753, 'max_features': 'log2', 'min_impurity_decrease': 7.041814507237016e-07, 'validation_fraction': 0.7324600365192867, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2125423492162011
Fold 2 IBS: 0.21917859422188082
Fold 3 IBS: 0.20326597997084148
Fold 4 IBS: 0.22346421338690958
Fold 5 IBS: 0.21658511688910384
[I 2024-04-16 04:05:05,767] Trial 51 finished with value: 0.21500725073698734 and parameters: {'subsample': 0.9574902141624301, 'learning_rate': 0.013974517784402708, 'dropout_rate': 0.19663405810878032, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288632756573364, 'min_weight_fraction_leaf': 0.1845530130003769, 'max_features': 'sqrt', 'min_impurity_decrease': 5.505988736711189e-07, 'validation_fraction': 0.8981152080635156, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:06:39,261] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8963301244448798, 'learning_rate': 0.014496942793188729, 'dropout_rate': 0.149261379708028, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.3267109398107992, 'min_weight_fraction_leaf': 0.19350109364955276, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0314361105633666e-07, 'validation_fraction': 0.8673271583656655, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:07:48,184] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.937858776808653, 'learning_rate': 0.01317678110087918, 'dropout_rate': 0.20949679348390188, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.9371275797883157, 'min_weight_fraction_leaf': 0.16718449303286065, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0035393968280476e-07, 'validation_fraction': 0.9639725916044029, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:07:58,150] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5502453589475278, 'learning_rate': 0.005289059095661144, 'dropout_rate': 0.16758744743711101, 'n_estimators': 147, 'criterion': 'squared_error', 'ccp_alpha': 0.6055238018097719, 'min_weight_fraction_leaf': 0.1222904374725215, 'max_features': 'sqrt', 'min_impurity_decrease': 8.119424084486158e-07, 'validation_fraction': 0.8019436577478607, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21151156199161855
Fold 2 IBS: 0.21784621797452874

Fold 3 IBS: 0.20286393718880646
Fold 4 IBS: 0.22391249179729633
Fold 5 IBS: 0.21519882725417372
[I 2024-04-16 04:09:19,445] Trial 55 finished with value: 0.21426660724128474 and parameters: {'subsample': 0.9703353679292269, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.2676210325613897, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.036860238643527846, 'min_weight_fraction_leaf': 0.21798842867076448, 'max_features': None, 'min_impurity_decrease': 4.086647023052284e-07, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:10:17,902] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9556274374724505, 'learning_rate': 0.022777236721630217, 'dropout_rate': 0.36674252455714285, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.3101553395317078, 'min_weight_fraction_leaf': 0.21445816437013876, 'max_features': None, 'min_impurity_decrease': 4.99089267664694e-07, 'validation_fraction': 0.8444326224317742, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2111687028051771
Fold 2 IBS: 0.2144165092431595
Fold 3 IBS: 0.20113060921449374
Fold 4 IBS: 0.22322228050971296
Fold 5 IBS: 0.21261135031718192
[I 2024-04-16 04:10:19,168] Trial 57 finished with value: 0.21250989041794505 and parameters: {'subsample': 0.9885544496318819, 'learning_rate': 0.02570846317737359, 'dropout_rate': 0.11524078732039367, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.0019474604343284706, 'min_weight_fraction_leaf': 0.1539893411018015, 'max_features': None, 'min_impurity_decrease': 3.011740016899961e-07, 'validation_fraction': 0.8976605224112223, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:10:19,703] Trial 58 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9760257284010853, 'learning_rate': 0.044170756425452734, 'dropout_rate': 0.10695167335108825, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 0.7470878188226159, 'min_weight_fraction_leaf': 0.1623750980802567, 'max_features': None, 'min_impurity_decrease': 3.402621023187449e-07, 'validation_fraction': 0.8839190525574698, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:10:23,385] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8651178500686678, 'learning_rate': 0.031729459746086146, 'dropout_rate': 0.1294932593082019, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 2.4509996240950476, 'min_weight_fraction_leaf': 0.14999314729494934, 'max_features': None, 'min_impurity_decrease': 1.564084650521852e-07, 'validation_fraction': 0.996741201133535, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:10:31,385] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9167528164906635, 'learning_rate': 0.024844206422551217, 'dropout_rate': 0.10027142034172723, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 1.5027931264041994, 'min_weight_fraction_leaf': 0.1840765520407988, 'max_features': None, 'min_impurity_decrease': 0.026115039984674165, 'validation_fraction': 0.9013568181484788, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21273370328437058
Fold 2 IBS: 0.21868788641242787
Fold 3 IBS: 0.20291275785992635
Fold 4 IBS: 0.22394573517913938
Fold 5 IBS: 0.21633996486417809
[I 2024-04-16 04:11:49,486] Trial 61 finished with value: 0.21492400952000845 and parameters: {'subsample': 0.9931174804814122, 'learning_rate': 0.016529825628647618, 'dropout_rate': 0.1935981459085364, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.0813695010094894, 'min_weight_fraction_leaf': 0.12194954374946233, 'max_features': None, 'min_impurity_decrease': 1.1729202879091808e-06, 'validation_fraction': 0.9481060427790172, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:13:11,556] Trial 62 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9972168379620757, 'learning_rate': 0.028217399882747345, 'dropout_rate': 0.1806381271548384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.3084041748420949, 'min_weight_fraction_leaf': 0.12013391362008917, 'max_features': None, 'min_impurity_decrease': 1.1386618305709938e-06, 'validation_fraction': 0.9457754330032251, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21192094947972812
Fold 2 IBS: 0.21732792727914613
Fold 3 IBS: 0.20380983776958678
Fold 4 IBS: 0.22289315056880815
Fold 5 IBS: 0.21548234130166077
[I 2024-04-16 04:13:13,410] Trial 63 finished with value: 0.21428684127978598 and parameters: {'subsample': 0.9627141857439078, 'learning_rate': 0.019891228353589942, 'dropout_rate': 0.2615796624395084, 'n_estimators': 49, 'criterion': 'squared_error', 'ccp_alpha': 0.01736018686586977, 'min_weight_fraction_leaf': 0.04375001956932725, 'max_features': None, 'min_impurity_decrease': 2.9650355903328224e-07, 'validation_fraction': 0.9569907594316491, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:13:14,318] Trial 64 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9999396727165888, 'learning_rate': 0.018638455478477044, 'dropout_rate': 0.2603466948459836, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.002024697263514, 'min_weight_fraction_leaf': 0.044141253094182736, 'max_features': None, 'min_impurity_decrease': 2.608122256111053e-07, 'validation_fraction': 0.9599786586698028, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:13:16,424] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9663925144780658, 'learning_rate': 0.037231214360123326, 'dropout_rate': 0.32454189899564956, 'n_estimators': 65, 'criterion': 'squared_error', 'ccp_alpha': 0.35061828245011545, 'min_weight_fraction_leaf': 0.000243933620821285, 'max_features': None, 'min_impurity_decrease': 1.0838199976610403e-07, 'validation_fraction': 0.9980175670026158, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:13:16,832] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9019393211486977, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.14697195606329974, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.7042671412306138, 'min_weight_fraction_leaf': 0.07018529613097008, 'max_features': None, 'min_impurity_decrease': 3.137142110783047e-07, 'validation_fraction': 0.779814650235569, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 57 with value: 0.21250989041794505.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:13:22,875] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.922035492452401, 'learning_rate': 0.02138812894899817, 'dropout_rate': 0.2208120967013012, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.09999708192212713, 'max_features': None, 'min_impurity_decrease': 1.467292826198341e-07, 'validation_fraction': 0.8460725291615868, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:13:24,918] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8097361669626262, 'learning_rate': 0.01637373351805548, 'dropout_rate': 0.2712783926055171, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.1308191878488825, 'min_weight_fraction_leaf': 0.02994710580328633, 'max_features': None, 'min_impurity_decrease': 1.0530798801381977e-06, 'validation_fraction': 0.9163895657291438, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:13:25,862] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8571881441778102, 'learning_rate': 0.0012168162419408535, 'dropout_rate': 0.42050912513013483, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 3.9712948739952747, 'min_weight_fraction_leaf': 0.12752076636262508, 'max_features': None, 'min_impurity_decrease': 4.3978604154583156e-07, 'validation_fraction': 0.964953947287593, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21002215842803912
Fold 2 IBS: 0.21297063105779915
Fold 3 IBS: 0.20313255536155353
Fold 4 IBS: 0.21999212755417724
Fold 5 IBS: 0.21255973126676214
[I 2024-04-16 04:13:38,544] Trial 70 finished with value: 0.21173544073366624 and parameters: {'subsample': 0.9468320464736178, 'learning_rate': 0.025309924459591012, 'dropout_rate': 0.1674120259573768, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010011659889289447, 'min_weight_fraction_leaf': 0.09294987278666268, 'max_features': None, 'min_impurity_decrease': 5.705070769293452e-06, 'validation_fraction': 0.8209425786658539, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21072608333691198
Fold 2 IBS: 0.21401453478291746
Fold 3 IBS: 0.20284454754508327
Fold 4 IBS: 0.22338804279177132
Fold 5 IBS: 0.21335338822747257
[I 2024-04-16 04:13:51,199] Trial 71 finished with value: 0.21286531933683134 and parameters: {'subsample': 0.9476651528090181, 'learning_rate': 0.024411666195060494, 'dropout_rate': 0.17430063929290213, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.026599566986409653, 'min_weight_fraction_leaf': 0.09751530095580928, 'max_features': None, 'min_impurity_decrease': 4.532054889066385e-06, 'validation_fraction': 0.8665443299833158, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:14:03,899] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9366080309436607, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.13262889403233624, 'n_estimators': 169, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6884427794811623, 'min_weight_fraction_leaf': 0.09471989813086933, 'max_features': None, 'min_impurity_decrease': 6.727144219685939e-06, 'validation_fraction': 0.7986403101682931, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:14:26,442] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8857292786754678, 'learning_rate': 0.026134449034871034, 'dropout_rate': 0.16958042534169554, 'n_estimators': 242, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3564153148878991, 'min_weight_fraction_leaf': 0.0675437991522329, 'max_features': None, 'min_impurity_decrease': 1.2822715066526718e-05, 'validation_fraction': 0.8508580960070242, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:14:38,465] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9667167267229794, 'learning_rate': 0.03460218408739485, 'dropout_rate': 0.23922069132815701, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9478289085025897, 'min_weight_fraction_leaf': 0.040648200160109275, 'max_features': None, 'min_impurity_decrease': 0.0004132854571878442, 'validation_fraction': 0.9118732389838691, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.2108264636051011
Fold 2 IBS: 0.21614741779802119
Fold 3 IBS: 0.20270071891532052
Fold 4 IBS: 0.22138908682592695
Fold 5 IBS: 0.21464613153207532
[I 2024-04-16 04:14:42,464] Trial 75 finished with value: 0.21314196373528901 and parameters: {'subsample': 0.9385875657011895, 'learning_rate': 0.03024192192848759, 'dropout_rate': 0.31026391284421334, 'n_estimators': 98, 'criterion': 'friedman_mse', 'ccp_alpha': 0.008766215704230302, 'min_weight_fraction_leaf': 0.088197239599825, 'max_features': 'log2', 'min_impurity_decrease': 2.34297511452969e-05, 'validation_fraction': 0.8182037482219422, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:14:59,535] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9478601603991035, 'learning_rate': 0.029703712882555727, 'dropout_rate': 0.30760503014637186, 'n_estimators': 217, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6031244247920138, 'min_weight_fraction_leaf': 0.08521606153633404, 'max_features': 'log2', 'min_impurity_decrease': 1.826805985778275e-05, 'validation_fraction': 0.7127838617807927, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:15:02,718] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.834194505922225, 'learning_rate': 0.023289065494024846, 'dropout_rate': 0.5946683576609367, 'n_estimators': 105, 'criterion': 'friedman_mse', 'ccp_alpha': 5.8752783688356525, 'min_weight_fraction_leaf': 0.10946812472698092, 'max_features': 'log2', 'min_impurity_decrease': 3.863869195457471e-05, 'validation_fraction': 0.8140600247331974, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:15:06,119] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9202091045129451, 'learning_rate': 0.019797687069268054, 'dropout_rate': 0.12670174450467558, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2910342652485194, 'min_weight_fraction_leaf': 0.15713001580184646, 'max_features': 'log2', 'min_impurity_decrease': 6.996091386072907e-06, 'validation_fraction': 0.7499357618644306, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:15:08,047] Trial 79 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9732609597246192, 'learning_rate': 0.027328730151233487, 'dropout_rate': 0.26312746311148777, 'n_estimators': 53, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3668553929390492, 'min_weight_fraction_leaf': 0.13178723776048706, 'max_features': 1, 'min_impurity_decrease': 3.5229801834435753e-06, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:15:14,127] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9344911008533908, 'learning_rate': 0.010633768390963052, 'dropout_rate': 0.3607582604573143, 'n_estimators': 130, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 'log2', 'min_impurity_decrease': 4.704228580458697e-05, 'validation_fraction': 0.8794203590137769, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21128104502826947
Fold 2 IBS: 0.2177939632602238
Fold 3 IBS: 0.202062918285923
Fold 4 IBS: 0.2220570307012409
Fold 5 IBS: 0.215203473940832
[I 2024-04-16 04:15:17,102] Trial 81 finished with value: 0.21367968624329783 and parameters: {'subsample': 0.883668494603156, 'learning_rate': 0.0320493886753143, 'dropout_rate': 0.22584451920971726, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038423779386081554, 'min_weight_fraction_leaf': 0.06634784234748042, 'max_features': 0.1, 'min_impurity_decrease': 1.4048004741754647e-05, 'validation_fraction': 0.9236349807357848, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.20983058110579608
Fold 2 IBS: 0.21307838506839907
Fold 3 IBS: 0.20156611960689727
Fold 4 IBS: 0.22102813568136667
Fold 5 IBS: 0.21191457851765924
[I 2024-04-16 04:15:19,856] Trial 82 finished with value: 0.2114835599960237 and parameters: {'subsample': 0.9775351216671477, 'learning_rate': 0.03625251959157783, 'dropout_rate': 0.2304960144192588, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017671076422469716, 'min_weight_fraction_leaf': 0.05682074279635106, 'max_features': None, 'min_impurity_decrease': 5.222380988059964e-06, 'validation_fraction': 0.8329660882357115, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:15:22,819] Trial 83 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.980690245556926, 'learning_rate': 0.031857704007181985, 'dropout_rate': 0.22968230522988387, 'n_estimators': 80, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8197918628434602, 'min_weight_fraction_leaf': 0.057928624179806834, 'max_features': None, 'min_impurity_decrease': 1.2599470077449364e-05, 'validation_fraction': 0.7797865611811227, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:15:28,654] Trial 84 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9075135722909342, 'learning_rate': 0.03559224920264127, 'dropout_rate': 0.16623286657907432, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.512352281665378, 'min_weight_fraction_leaf': 0.10287384413406744, 'max_features': 0.1, 'min_impurity_decrease': 5.529311462542002e-06, 'validation_fraction': 0.8246387147196982, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:15:38,320] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9399767088887255, 'learning_rate': 0.04090952135292814, 'dropout_rate': 0.15193033105151865, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3342330512314949, 'min_weight_fraction_leaf': 0.08669540229802705, 'max_features': 1, 'min_impurity_decrease': 1.6658136731423827e-05, 'validation_fraction': 0.8565340610034006, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 5}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:15:41,309] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.875251314446822, 'learning_rate': 0.054611780581555074, 'dropout_rate': 0.18611522621903143, 'n_estimators': 75, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23548502503527302, 'min_weight_fraction_leaf': 0.14949731859104587, 'max_features': None, 'min_impurity_decrease': 2.4419902202859148e-05, 'validation_fraction': 0.8919356176714629, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:15:42,069] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9722232383830184, 'learning_rate': 0.0372364299275435, 'dropout_rate': 0.3020378568783464, 'n_estimators': 28, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0716748672357443, 'min_weight_fraction_leaf': 0.17652784181036787, 'max_features': 'log2', 'min_impurity_decrease': 9.189811058262566e-06, 'validation_fraction': 0.9265266924948802, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:15:59,382] Trial 88 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.45521815335975935, 'learning_rate': 0.024635453467641497, 'dropout_rate': 0.22592407076200724, 'n_estimators': 225, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5932990711529844, 'min_weight_fraction_leaf': 0.05795880477433249, 'max_features': 0.1, 'min_impurity_decrease': 0.00010910005120952281, 'validation_fraction': 0.86583149343058, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 6}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.20406423720489414

Fold 2 IBS: 0.20607296701907554
Fold 3 IBS: 0.19811121797640907
Fold 4 IBS: 0.22011942798029224
Fold 5 IBS: 0.20776003972546755
[I 2024-04-16 04:16:03,688] Trial 89 finished with value: 0.2072255779812277 and parameters: {'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:16:08,952] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8590448841763807, 'learning_rate': 0.04392267936156322, 'dropout_rate': 0.13081530577107772, 'n_estimators': 94, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8187200341244589, 'min_weight_fraction_leaf': 0.1356329779047198, 'max_features': None, 'min_impurity_decrease': 6.919028711702198e-05, 'validation_fraction': 0.7579364095018994, 'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2139765219514961
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:16:14,832] Trial 91 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9464598565951264, 'learning_rate': 0.033436459700910935, 'dropout_rate': 0.1074479916910401, 'n_estimators': 111, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1567080004847236, 'min_weight_fraction_leaf': 0.21909447348643799, 'max_features': None, 'min_impurity_decrease': 3.232645761160545e-05, 'validation_fraction': 0.836686056082251, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:16:23,384] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9026696667848182, 'learning_rate': 0.028827888997212704, 'dropout_rate': 0.16259306451315403, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4965227315126272, 'min_weight_fraction_leaf': 0.22285254340641944, 'max_features': None, 'min_impurity_decrease': 0.00017018904827513644, 'validation_fraction': 0.796918264996305, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:16:25,876] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9798482306398367, 'learning_rate': 0.031825834623114814, 'dropout_rate': 0.2049131658034791, 'n_estimators': 69, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20667716682270093, 'min_weight_fraction_leaf': 0.2585203230729044, 'max_features': None, 'min_impurity_decrease': 3.0851445660062647e-06, 'validation_fraction': 0.9763122670150756, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2101879570260367
Fold 2 IBS: 0.21250628812533257
Fold 3 IBS: 0.20007025298318656
Fold 4 IBS: 0.22265647904327204
Fold 5 IBS: 0.21257939770958625
[I 2024-04-16 04:16:29,619] Trial 94 finished with value: 0.21160007497748282 and parameters: {'subsample': 0.9310591269229673, 'learning_rate': 0.02763334095363912, 'dropout_rate': 0.12795712192217606, 'n_estimators': 86, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05749842893076747, 'min_weight_fraction_leaf': 0.11026254544432534, 'max_features': 'auto', 'min_impurity_decrease': 5.8091196946415505e-05, 'validation_fraction': 0.9026577264245155, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:16:33,403] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9218225521402408, 'learning_rate': 0.02753178161235845, 'dropout_rate': 0.12793297330846434, 'n_estimators': 85, 'criterion': 'friedman_mse', 'ccp_alpha': 1.235276138540849, 'min_weight_fraction_leaf': 0.11051958866648452, 'max_features': 'auto', 'min_impurity_decrease': 6.515583307515859e-05, 'validation_fraction': 0.7292708592638782, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:16:34,067] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7993135167464014, 'learning_rate': 0.03108695961488799, 'dropout_rate': 0.14512603486936382, 'n_estimators': 24, 'criterion': 'friedman_mse', 'ccp_alpha': 0.49652833519783807, 'min_weight_fraction_leaf': 0.08008525725013409, 'max_features': 'auto', 'min_impurity_decrease': 4.444264351736355e-06, 'validation_fraction': 0.9242462136422857, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:16:48,144] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.845660486112679, 'learning_rate': 0.038767353066908594, 'dropout_rate': 0.18221216046279998, 'n_estimators': 200, 'criterion': 'friedman_mse', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.09201897280645036, 'max_features': 'auto', 'min_impurity_decrease': 0.0002353321351929941, 'validation_fraction': 0.8287626512220347, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:16:52,833] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8944546679246258, 'learning_rate': 0.036127203223985056, 'dropout_rate': 0.10388522337492916, 'n_estimators': 103, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8167233797377258, 'min_weight_fraction_leaf': 0.19553165108199336, 'max_features': 'auto', 'min_impurity_decrease': 1.7492280036351012e-05, 'validation_fraction': 0.899014721584761, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21406463377160456
Fold 2 IBS: 0.22130490881763304
Fold 3 IBS: 0.20441078654944964
Fold 4 IBS: 0.2243095706255849
Fold 5 IBS: 0.21724050836884118
[I 2024-04-16 04:16:53,241] Trial 99 finished with value: 0.21626608162662264 and parameters: {'subsample': 0.24110557495742024, 'learning_rate': 0.034155925108170324, 'dropout_rate': 0.12401586667496287, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004427324419918794, 'min_weight_fraction_leaf': 0.07004102983569523, 'max_features': 'auto', 'min_impurity_decrease': 3.069838649017234e-05, 'validation_fraction': 0.6766066266445131, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.


* Best trial for IBS:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.2072255779812277], datetime_start=datetime.datetime(2024, 4, 16, 4, 15, 59, 389885), datetime_complete=datetime.datetime(2024, 4, 16, 4, 16, 3, 688040), params={'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=89, value=None)


* Best Score for IBS:
 0.2072255779812277

In [60]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.765
train_ibs:  0.207

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.046986154574499193,
                                 dropout_rate=0.9141084507237711,
                                 learning_rate=0.005228819896792163,
                                 max_leaf_nodes=13,
                                 min_impurity_decrease=0.00017501601948817654,
                                 min_samples_leaf=15, min_samples_split=11,
                                 min_weight_fraction_leaf=0.2724947676380759,
                                 n_estimators=395, random_state=123,
                                 subsample=0.6128161811459047,
                                 validation_fraction=0.542037097833947)

C-index score: 0.579

GradientBoostingSurvivalAnalysis(ccp_alpha=0.019065157478907357,
                                 dropout_rate=0.10084377376256726,
                                 learning_rate=0.032246585462716706,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.552978044824526e-05,
                                 min_samples_leaf=9, min_samples_split=18,
                                 min_weight_fraction_leaf=0.21843803937299006,
                                 n_estimators=92, random_state=123,
                                 subsample=0.9081334064688743,
                                 validation_fraction=0.8292287698601738)

IBS: 0.218

In [64]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 04:16:56,699] A new study created in memory with name: no-name-7b173a3e-5d24-4839-854e-8084fb218ec5

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:16:58,056] Trial 0 finished with value: 0.6944636137409307 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6944636137409307.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:17:07,843] Trial 1 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6944636137409307.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:17:09,495] Trial 2 finished with value: 0.6961513774540109 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6961513774540109.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:17:11,830] Trial 3 finished with value: 0.6998507204466902 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6998507204466902.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:17:15,871] Trial 4 finished with value: 0.7071311757818737 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7071311757818737.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:17:19,792] Trial 5 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7071311757818737.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:17:21,399] Trial 6 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7071311757818737.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:17:21,748] Trial 7 finished with value: 0.6970345508257922 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7071311757818737.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:17:23,654] Trial 8 finished with value: 0.6963829730339437 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7071311757818737.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:17:29,399] Trial 9 finished with value: 0.6963829730339437 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7071311757818737.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:17:33,330] Trial 10 finished with value: 0.7043333280896598 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 4 with value: 0.7071311757818737.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:17:37,971] Trial 11 finished with value: 0.7117135919830906 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:17:42,357] Trial 12 finished with value: 0.7077038592710622 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.2495649826842376, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:17:48,209] Trial 13 finished with value: 0.6963001229925186 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:17:54,309] Trial 14 finished with value: 0.7085477411276022 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24475605651992097, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:17:59,430] Trial 15 finished with value: 0.6961831187036477 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.6890184489677957, 'n_estimators': 365, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:18:08,110] Trial 16 finished with value: 0.7038284006369043 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.10221023026090809, 'n_estimators': 423, 'learning_rate': 0.08463638125592773}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:18:16,277] Trial 17 finished with value: 0.7015194304435336 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 413, 'learning_rate': 0.08749976591807801}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:18:20,984] Trial 18 finished with value: 0.7007781841322082 and parameters: {'subsample': 0.35888747153360906, 'dropout_rate': 0.3446615188677563, 'n_estimators': 324, 'learning_rate': 0.09062397105934869}. Best is trial 11 with value: 0.7117135919830906.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:18:27,552] Trial 19 finished with value: 0.7112672852816713 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7196046509277619, 'n_estimators': 431, 'learning_rate': 0.08300323114610605}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:18:34,244] Trial 20 finished with value: 0.6989877848739133 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.7628923189846966, 'n_estimators': 435, 'learning_rate': 0.08036525450908355}. Best is trial 11 with value: 0.7117135919830906.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:18:37,527] Trial 21 finished with value: 0.7122062524178215 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.6080226687634136, 'n_estimators': 272, 'learning_rate': 0.09637537942321125}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:18:39,902] Trial 22 finished with value: 0.7113087103023839 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.648340841365569, 'n_estimators': 239, 'learning_rate': 0.07782058471981552}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:18:42,487] Trial 23 finished with value: 0.7041773117778856 and parameters: {'subsample': 0.1850567218204376, 'dropout_rate': 0.6259773504515653, 'n_estimators': 251, 'learning_rate': 0.06566568862548955}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:18:43,581] Trial 24 finished with value: 0.7032948701936568 and parameters: {'subsample': 0.20380943129128443, 'dropout_rate': 0.7988926683999303, 'n_estimators': 147, 'learning_rate': 0.07588307954590223}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:18:46,414] Trial 25 finished with value: 0.6981295342737168 and parameters: {'subsample': 0.41518848496569194, 'dropout_rate': 0.6016821664374092, 'n_estimators': 276, 'learning_rate': 0.0936398395175903}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:18:48,668] Trial 26 finished with value: 0.7009146944325307 and parameters: {'subsample': 0.2958189169734158, 'dropout_rate': 0.5455297895617938, 'n_estimators': 220, 'learning_rate': 0.07899647003461208}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:18:49,543] Trial 27 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.9861686560685959, 'n_estimators': 112, 'learning_rate': 0.09100705603827391}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:18:51,989] Trial 28 finished with value: 0.6944636137409307 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.46951077947078645, 'n_estimators': 235, 'learning_rate': 0.06152638329235058}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:18:52,459] Trial 29 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.35484349011455046, 'n_estimators': 62, 'learning_rate': 0.09242866512727076}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:18:53,451] Trial 30 finished with value: 0.7051772099461999 and parameters: {'subsample': 0.1573472469684153, 'dropout_rate': 0.6002931582377272, 'n_estimators': 123, 'learning_rate': 0.045332354247913605}. Best is trial 21 with value: 0.7122062524178215.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:18:57,320] Trial 31 finished with value: 0.712247677438534 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.7221246238360712, 'n_estimators': 290, 'learning_rate': 0.08166797607699186}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:19:00,818] Trial 32 finished with value: 0.706981977948151 and parameters: {'subsample': 0.15536598902320387, 'dropout_rate': 0.8396188948643704, 'n_estimators': 287, 'learning_rate': 0.06857437298310941}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:19:04,911] Trial 33 finished with value: 0.7006433550421416 and parameters: {'subsample': 0.22215986403186463, 'dropout_rate': 0.737228067382418, 'n_estimators': 328, 'learning_rate': 0.07973487744142521}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:19:08,265] Trial 34 finished with value: 0.7112672852816713 and parameters: {'subsample': 0.10333640058600022, 'dropout_rate': 0.5061637317558012, 'n_estimators': 257, 'learning_rate': 0.07104054321866782}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:19:15,008] Trial 35 finished with value: 0.7034412027343555 and parameters: {'subsample': 0.24430564869860838, 'dropout_rate': 0.6502343683868661, 'n_estimators': 394, 'learning_rate': 0.08752983240865389}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:19:17,947] Trial 36 finished with value: 0.7016634910094607 and parameters: {'subsample': 0.30986291207776295, 'dropout_rate': 0.42504221478450555, 'n_estimators': 243, 'learning_rate': 0.07503185856076539}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:19:18,172] Trial 37 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.15404891104429022, 'dropout_rate': 0.5777667876383752, 'n_estimators': 1, 'learning_rate': 0.059207327336158105}. Best is trial 31 with value: 0.712247677438534.

Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:19:20,177] Trial 38 finished with value: 0.7089841872825892 and parameters: {'subsample': 0.1499958194858822, 'dropout_rate': 0.7725266545363573, 'n_estimators': 192, 'learning_rate': 0.09420011192077271}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:19:24,800] Trial 39 finished with value: 0.6999757272963805 and parameters: {'subsample': 0.3156029735189495, 'dropout_rate': 0.6953650320328696, 'n_estimators': 339, 'learning_rate': 0.06456811545507721}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:19:28,365] Trial 40 finished with value: 0.6981243970059214 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.5032648019886721, 'n_estimators': 289, 'learning_rate': 0.07255507912086517}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:19:35,911] Trial 41 finished with value: 0.7112943415587276 and parameters: {'subsample': 0.10437662902118044, 'dropout_rate': 0.7241425957577687, 'n_estimators': 497, 'learning_rate': 0.08366722876107535}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:19:43,975] Trial 42 finished with value: 0.706138096091611 and parameters: {'subsample': 0.19932946077399294, 'dropout_rate': 0.6527300834892888, 'n_estimators': 479, 'learning_rate': 0.08265173665343624}. Best is trial 31 with value: 0.712247677438534.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:19:50,458] Trial 43 finished with value: 0.7130206649994963 and parameters: {'subsample': 0.13706595864882293, 'dropout_rate': 0.9339744762032774, 'n_estimators': 456, 'learning_rate': 0.07750332744257205}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:19:51,878] Trial 44 finished with value: 0.7095062142752042 and parameters: {'subsample': 0.13326295226620088, 'dropout_rate': 0.9440135587632654, 'n_estimators': 162, 'learning_rate': 0.0770300673656163}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:19:59,078] Trial 45 finished with value: 0.6998265294626578 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.8539308168489239, 'n_estimators': 457, 'learning_rate': 0.03400538573985265}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:20:01,956] Trial 46 finished with value: 0.701433576639784 and parameters: {'subsample': 0.18428780736560837, 'dropout_rate': 0.9004605391692919, 'n_estimators': 272, 'learning_rate': 0.0970712138212341}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:20:03,879] Trial 47 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.7043689793515533, 'dropout_rate': 0.8126939101630105, 'n_estimators': 219, 'learning_rate': 0.008209618821055878}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:20:11,318] Trial 48 finished with value: 0.7075968182456049 and parameters: {'subsample': 0.1389275319026894, 'dropout_rate': 0.18029276633892521, 'n_estimators': 389, 'learning_rate': 0.06863089732485125}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:20:14,714] Trial 49 finished with value: 0.6996629628852788 and parameters: {'subsample': 0.222152181303445, 'dropout_rate': 0.9045757420323403, 'n_estimators': 305, 'learning_rate': 0.09057969807199051}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:20:20,613] Trial 50 finished with value: 0.6970903445901611 and parameters: {'subsample': 0.5279529259672888, 'dropout_rate': 0.303556222736179, 'n_estimators': 355, 'learning_rate': 0.05378378517676694}. Best is trial 43 with value: 0.7130206649994963.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:20:29,214] Trial 51 finished with value: 0.7130991095606787 and parameters: {'subsample': 0.10888451531029869, 'dropout_rate': 0.6911926207928873, 'n_estimators': 498, 'learning_rate': 0.08761544554674441}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:20:38,374] Trial 52 finished with value: 0.7039163879461249 and parameters: {'subsample': 0.18370309800596674, 'dropout_rate': 0.5671640315979039, 'n_estimators': 467, 'learning_rate': 0.08881991358667468}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:20:46,312] Trial 53 finished with value: 0.7094625172797203 and parameters: {'subsample': 0.12235314965386802, 'dropout_rate': 0.6916167218480871, 'n_estimators': 459, 'learning_rate': 0.09477772623342627}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:20:54,747] Trial 54 finished with value: 0.7083698058065672 and parameters: {'subsample': 0.1696678906728003, 'dropout_rate': 0.42126569726594026, 'n_estimators': 449, 'learning_rate': 0.08714068305758996}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:21:00,148] Trial 55 finished with value: 0.7094625172797203 and parameters: {'subsample': 0.1345280064553199, 'dropout_rate': 0.6199236041575378, 'n_estimators': 392, 'learning_rate': 0.09948550089347807}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:21:09,968] Trial 56 finished with value: 0.699885326989351 and parameters: {'subsample': 0.27329656408034453, 'dropout_rate': 0.5194091093440398, 'n_estimators': 498, 'learning_rate': 0.08148815502660413}. Best is trial 51 with value: 0.7130991095606787.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:21:12,214] Trial 57 finished with value: 0.7112597350160668 and parameters: {'subsample': 0.10151923981488473, 'dropout_rate': 0.7689210783424986, 'n_estimators': 198, 'learning_rate': 0.07629080266810488}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:21:16,348] Trial 58 finished with value: 0.6996629628852788 and parameters: {'subsample': 0.21883265779975936, 'dropout_rate': 0.6749360717747499, 'n_estimators': 316, 'learning_rate': 0.08524691400923577}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:21:22,012] Trial 59 finished with value: 0.7049285213526244 and parameters: {'subsample': 0.17426935548515637, 'dropout_rate': 0.9831447030648263, 'n_estimators': 417, 'learning_rate': 0.09727387898658899}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:21:24,611] Trial 60 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.8248424696270813, 'dropout_rate': 0.629559741845428, 'n_estimators': 236, 'learning_rate': 0.07907851868897463}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:21:32,957] Trial 61 finished with value: 0.7122286237222972 and parameters: {'subsample': 0.12566435979954882, 'dropout_rate': 0.745391339966418, 'n_estimators': 483, 'learning_rate': 0.08301652675870907}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:21:40,221] Trial 62 finished with value: 0.7112234472631498 and parameters: {'subsample': 0.136282674809055, 'dropout_rate': 0.8095328060233183, 'n_estimators': 481, 'learning_rate': 0.08946618855252851}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:21:42,690] Trial 63 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.6038235962186711, 'dropout_rate': 0.7319325816115824, 'n_estimators': 262, 'learning_rate': 0.07234095966141037}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:21:46,427] Trial 64 finished with value: 0.7041773117778856 and parameters: {'subsample': 0.19512057164733534, 'dropout_rate': 0.7059467142696543, 'n_estimators': 340, 'learning_rate': 0.08475417086663772}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:21:53,013] Trial 65 finished with value: 0.7094625172797203 and parameters: {'subsample': 0.1338717839938493, 'dropout_rate': 0.5836385331062908, 'n_estimators': 432, 'learning_rate': 0.09211664393621975}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:21:56,722] Trial 66 finished with value: 0.7005414512844798 and parameters: {'subsample': 0.24118412064292954, 'dropout_rate': 0.7536730800872367, 'n_estimators': 292, 'learning_rate': 0.07899052820432013}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:22:01,854] Trial 67 finished with value: 0.7104014844158705 and parameters: {'subsample': 0.10290773442773296, 'dropout_rate': 0.673956078039829, 'n_estimators': 376, 'learning_rate': 0.09538574222650928}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:22:08,804] Trial 68 finished with value: 0.7057724032091646 and parameters: {'subsample': 0.1716140369137206, 'dropout_rate': 0.7908943655271745, 'n_estimators': 440, 'learning_rate': 0.08538311250775099}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:22:16,636] Trial 69 finished with value: 0.6999757272963805 and parameters: {'subsample': 0.3308399547866366, 'dropout_rate': 0.6416892751982621, 'n_estimators': 469, 'learning_rate': 0.08153461344209138}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:22:22,624] Trial 70 finished with value: 0.7095793805455537 and parameters: {'subsample': 0.154131491910291, 'dropout_rate': 0.8784964883729391, 'n_estimators': 408, 'learning_rate': 0.06985787653333236}. Best is trial 51 with value: 0.7130991095606787.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:22:31,171] Trial 71 finished with value: 0.71320901587916 and parameters: {'subsample': 0.11763923239715199, 'dropout_rate': 0.7180345268448158, 'n_estimators': 491, 'learning_rate': 0.08398811307843873}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:22:39,276] Trial 72 finished with value: 0.709577108570782 and parameters: {'subsample': 0.13427604124883824, 'dropout_rate': 0.600626454995321, 'n_estimators': 479, 'learning_rate': 0.0880395924326876}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:22:46,070] Trial 73 finished with value: 0.7070580095115244 and parameters: {'subsample': 0.20317676603231183, 'dropout_rate': 0.8357006361147093, 'n_estimators': 482, 'learning_rate': 0.07442319023204992}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:22:52,819] Trial 74 finished with value: 0.7095086272730133 and parameters: {'subsample': 0.10099983845623818, 'dropout_rate': 0.5455017771930928, 'n_estimators': 446, 'learning_rate': 0.09216266257313775}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:23:00,600] Trial 75 finished with value: 0.7095793805455537 and parameters: {'subsample': 0.16470372978246808, 'dropout_rate': 0.7486645603883859, 'n_estimators': 489, 'learning_rate': 0.06528957260434526}. Best is trial 71 with value: 0.71320901587916.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:23:03,774] Trial 76 finished with value: 0.708569660136863 and parameters: {'subsample': 0.12434011705244034, 'dropout_rate': 0.7103032106194158, 'n_estimators': 280, 'learning_rate': 0.07664381547289889}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:23:13,113] Trial 77 finished with value: 0.7013507265983591 and parameters: {'subsample': 0.22220686134441753, 'dropout_rate': 0.6784671369069507, 'n_estimators': 497, 'learning_rate': 0.0826154315166118}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:23:15,473] Trial 78 finished with value: 0.7105304444505884 and parameters: {'subsample': 0.12290838116216221, 'dropout_rate': 0.7744312410557403, 'n_estimators': 215, 'learning_rate': 0.08969614966690463}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:23:18,804] Trial 79 finished with value: 0.700765496598808 and parameters: {'subsample': 0.2603517630815616, 'dropout_rate': 0.6630930639118289, 'n_estimators': 249, 'learning_rate': 0.07822420968867079}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:23:28,400] Trial 80 finished with value: 0.7084821251228576 and parameters: {'subsample': 0.15133512060021007, 'dropout_rate': 0.14030017497322128, 'n_estimators': 454, 'learning_rate': 0.04414229297870615}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:23:36,125] Trial 81 finished with value: 0.7123161587363029 and parameters: {'subsample': 0.11810978161524177, 'dropout_rate': 0.714262898308278, 'n_estimators': 499, 'learning_rate': 0.08244812871423682}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:23:43,466] Trial 82 finished with value: 0.7068893056663499 and parameters: {'subsample': 0.18650787900552562, 'dropout_rate': 0.7307622049706647, 'n_estimators': 467, 'learning_rate': 0.08536047431097528}. Best is trial 71 with value: 0.71320901587916.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:23:52,373] Trial 83 finished with value: 0.7141479830153102 and parameters: {'subsample': 0.11713675251393994, 'dropout_rate': 0.6202793429199533, 'n_estimators': 494, 'learning_rate': 0.08136047667579}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:24:01,079] Trial 84 finished with value: 0.7141479830153102 and parameters: {'subsample': 0.12344044723407396, 'dropout_rate': 0.6103501050918866, 'n_estimators': 498, 'learning_rate': 0.08084258351466489}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:24:09,587] Trial 85 finished with value: 0.7086404134094033 and parameters: {'subsample': 0.1539149122122388, 'dropout_rate': 0.6061352467370532, 'n_estimators': 488, 'learning_rate': 0.08168857200697503}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:24:17,359] Trial 86 finished with value: 0.7141479830153102 and parameters: {'subsample': 0.11823736852899727, 'dropout_rate': 0.5668962034671127, 'n_estimators': 500, 'learning_rate': 0.0737715826407305}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:24:25,755] Trial 87 finished with value: 0.7103553744225775 and parameters: {'subsample': 0.12358295976576067, 'dropout_rate': 0.5727200298530648, 'n_estimators': 471, 'learning_rate': 0.07412134998399601}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:24:34,870] Trial 88 finished with value: 0.703352935932797 and parameters: {'subsample': 0.2045594249304002, 'dropout_rate': 0.5266720146129319, 'n_estimators': 500, 'learning_rate': 0.06731180808839467}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:24:41,592] Trial 89 finished with value: 0.6999025610260312 and parameters: {'subsample': 0.40686391605243105, 'dropout_rate': 0.631443833727712, 'n_estimators': 457, 'learning_rate': 0.08060028645242533}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:24:47,580] Trial 90 finished with value: 0.7057724032091646 and parameters: {'subsample': 0.17597805764840802, 'dropout_rate': 0.7062097739842834, 'n_estimators': 429, 'learning_rate': 0.07208323895851027}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:24:56,048] Trial 91 finished with value: 0.7131675908584475 and parameters: {'subsample': 0.11954199157449044, 'dropout_rate': 0.5590972323039661, 'n_estimators': 484, 'learning_rate': 0.08695814820506881}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:25:06,013] Trial 92 finished with value: 0.7086428264072124 and parameters: {'subsample': 0.1483452035218285, 'dropout_rate': 0.46637559832227504, 'n_estimators': 488, 'learning_rate': 0.08362281168232341}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:25:14,707] Trial 93 finished with value: 0.7076624342503497 and parameters: {'subsample': 0.12000621148518252, 'dropout_rate': 0.4932997606912581, 'n_estimators': 474, 'learning_rate': 0.08668033719691395}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:25:22,630] Trial 94 finished with value: 0.708598988388691 and parameters: {'subsample': 0.16367213637171724, 'dropout_rate': 0.5558341530400551, 'n_estimators': 445, 'learning_rate': 0.03784083828401163}. Best is trial 83 with value: 0.7141479830153102.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:25:29,588] Trial 95 finished with value: 0.7094625172797203 and parameters: {'subsample': 0.1199135036722207, 'dropout_rate': 0.5839401027981712, 'n_estimators': 462, 'learning_rate': 0.061855666476710404}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:25:37,895] Trial 96 finished with value: 0.7024993703051814 and parameters: {'subsample': 0.2311827821383683, 'dropout_rate': 0.6585523342036481, 'n_estimators': 486, 'learning_rate': 0.07706695062595409}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:25:45,779] Trial 97 finished with value: 0.7070038969574118 and parameters: {'subsample': 0.18936712295841307, 'dropout_rate': 0.6878526479424686, 'n_estimators': 499, 'learning_rate': 0.08021051284835994}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:25:53,952] Trial 98 finished with value: 0.7103305901202926 and parameters: {'subsample': 0.13851165769575755, 'dropout_rate': 0.618728916052098, 'n_estimators': 471, 'learning_rate': 0.01973626745486202}. Best is trial 83 with value: 0.7141479830153102.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683

[I 2024-04-16 04:26:00,863] A new study created in memory with name: no-name-c20789b1-226c-4577-b0f7-5eaae4283778

Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:26:00,834] Trial 99 finished with value: 0.7112672852816713 and parameters: {'subsample': 0.10081299773066818, 'dropout_rate': 0.532036650759635, 'n_estimators': 406, 'learning_rate': 0.04831408684473379}. Best is trial 83 with value: 0.7141479830153102.


* Best trial for C-index:
 FrozenTrial(number=83, state=TrialState.COMPLETE, values=[0.7141479830153102], datetime_start=datetime.datetime(2024, 4, 16, 4, 23, 43, 471682), datetime_complete=datetime.datetime(2024, 4, 16, 4, 23, 52, 373346), params={'subsample': 0.11713675251393994, 'dropout_rate': 0.6202793429199533, 'n_estimators': 494, 'learning_rate': 0.08136047667579}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=83, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11713675251393994, 'dropout_rate': 0.6202793429199533, 'n_estimators': 494, 'learning_rate': 0.08136047667579}


* Best Score for C-index:
 0.7141479830153102

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24543748741914098
Fold 2 IBS: 0.23317848666127475
Fold 3 IBS: 0.18721324013097929
Fold 4 IBS: 0.2627413120655669
Fold 5 IBS: 0.2088844422588817
[I 2024-04-16 04:26:01,846] Trial 0 finished with value: 0.2274909937071687 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.3157615176698962
Fold 2 IBS: 0.32189237562862166
Fold 3 IBS: 0.2788861650869375
Fold 4 IBS: 0.3152651041057157
Fold 5 IBS: 0.3046807334754616
[I 2024-04-16 04:26:11,292] Trial 1 finished with value: 0.3072971791933265 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.2736129440677976
Fold 2 IBS: 0.2992916550922806
Fold 3 IBS: 0.2344928921000292
Fold 4 IBS: 0.2750087278739297
Fold 5 IBS: 0.2592818752777806
[I 2024-04-16 04:26:12,985] Trial 2 finished with value: 0.26833761888236357 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.2771997655106299
Fold 2 IBS: 0.2738997354359799
Fold 3 IBS: 0.23937090990720106
Fold 4 IBS: 0.2632441371572647
Fold 5 IBS: 0.2212979631240525
[I 2024-04-16 04:26:15,478] Trial 3 finished with value: 0.2550025022270256 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.27805471299567597
Fold 2 IBS: 0.2874473566684048
Fold 3 IBS: 0.24410101256671504
Fold 4 IBS: 0.25640437320659143
Fold 5 IBS: 0.23487496471233735
[I 2024-04-16 04:26:19,164] Trial 4 finished with value: 0.2601764840299449 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.29964122631726436
Fold 2 IBS: 0.3204039646090136
Fold 3 IBS: 0.2615357263447192
Fold 4 IBS: 0.3032899768975731
Fold 5 IBS: 0.2968638928198015
[I 2024-04-16 04:26:23,832] Trial 5 finished with value: 0.29634695739767436 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.23142715981972764
Fold 2 IBS: 0.20264709709911605
Fold 3 IBS: 0.17325615036677913
Fold 4 IBS: 0.24090901161401929
Fold 5 IBS: 0.19041091163397286
[I 2024-04-16 04:26:25,755] Trial 6 finished with value: 0.207730066106723 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.207730066106723.
Fold 1 IBS: 0.2076748777046715
Fold 2 IBS: 0.18513286928098505
Fold 3 IBS: 0.17458570926946737
Fold 4 IBS: 0.20959901500077463
Fold 5 IBS: 0.18476777976713055
[I 2024-04-16 04:26:26,173] Trial 7 finished with value: 0.19235205020460583 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.2483266230281813
Fold 2 IBS: 0.24322669159502178
Fold 3 IBS: 0.19314995217139108
Fold 4 IBS: 0.26660384269502313
Fold 5 IBS: 0.20592581375019903
[I 2024-04-16 04:26:28,125] Trial 8 finished with value: 0.23144658464796325 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.30275986043779984
Fold 2 IBS: 0.32087941820266896
Fold 3 IBS: 0.2668449825851155
Fold 4 IBS: 0.3048081958481441
Fold 5 IBS: 0.2897432005575174
[I 2024-04-16 04:26:33,934] Trial 9 finished with value: 0.29700713152624914 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.21343330133003716
Fold 2 IBS: 0.22041746827332745
Fold 3 IBS: 0.2036139107282693
Fold 4 IBS: 0.2237771082655921
Fold 5 IBS: 0.21719902637866145
[I 2024-04-16 04:26:34,223] Trial 10 finished with value: 0.2156881629951775 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.21324338103957954
Fold 2 IBS: 0.22001717603804508
Fold 3 IBS: 0.20389838834403085
Fold 4 IBS: 0.2234486245538933
Fold 5 IBS: 0.2168716025171396
[I 2024-04-16 04:26:34,428] Trial 11 finished with value: 0.21549583449853768 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.2629915675140106
Fold 2 IBS: 0.2825563693897473
Fold 3 IBS: 0.21593005806154597
Fold 4 IBS: 0.2692560226887386
Fold 5 IBS: 0.21894739562536478
[I 2024-04-16 04:26:35,263] Trial 12 finished with value: 0.24993628265588144 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.26195181678854607
Fold 2 IBS: 0.2771979490504694
Fold 3 IBS: 0.21031993833068025
Fold 4 IBS: 0.2772718910025073
Fold 5 IBS: 0.24789677015981626
[I 2024-04-16 04:26:38,819] Trial 13 finished with value: 0.25492767306640385 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.2055469233365125
Fold 2 IBS: 0.19333008828178766
Fold 3 IBS: 0.18149798595746378
Fold 4 IBS: 0.20811509030714898
Fold 5 IBS: 0.195183209307254
[I 2024-04-16 04:26:39,546] Trial 14 finished with value: 0.19673465943803337 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.21056124354783895
Fold 2 IBS: 0.21352681391995132
Fold 3 IBS: 0.19869725603155575
Fold 4 IBS: 0.21866975920639684
Fold 5 IBS: 0.21172909265842005
[I 2024-04-16 04:26:40,110] Trial 15 finished with value: 0.2106368330728326 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.20646294925281175
Fold 2 IBS: 0.20279664668541308
Fold 3 IBS: 0.18998554437644108
Fold 4 IBS: 0.21138450932830422
Fold 5 IBS: 0.20288324042130967
[I 2024-04-16 04:26:40,596] Trial 16 finished with value: 0.20270257801285596 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.23688660254063618
Fold 2 IBS: 0.2137758878636472
Fold 3 IBS: 0.17666285067548287
Fold 4 IBS: 0.2497930363895449
Fold 5 IBS: 0.1965709716221325
[I 2024-04-16 04:26:41,663] Trial 17 finished with value: 0.21473786981828874 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.2380300059980365
Fold 2 IBS: 0.21603857243744973
Fold 3 IBS: 0.18053222769598407
Fold 4 IBS: 0.24859599562150908
Fold 5 IBS: 0.18807842816224846
[I 2024-04-16 04:26:45,497] Trial 18 finished with value: 0.2142550459830456 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19235205020460583.
Fold 1 IBS: 0.2031709654645555

Fold 2 IBS: 0.17580127670955806
Fold 3 IBS: 0.17528921045094445
Fold 4 IBS: 0.19335846310954638
Fold 5 IBS: 0.18393908760893649
[I 2024-04-16 04:26:45,914] Trial 19 finished with value: 0.18631180066870817 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.20469079919009717
Fold 2 IBS: 0.18025608024789408
Fold 3 IBS: 0.17685175698416405
Fold 4 IBS: 0.19581523101059145
Fold 5 IBS: 0.18727333669387985
[I 2024-04-16 04:26:46,308] Trial 20 finished with value: 0.1889774408253253 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.20189804584228907
Fold 2 IBS: 0.18605742016473745
Fold 3 IBS: 0.18348619158171814
Fold 4 IBS: 0.20331810366947325
Fold 5 IBS: 0.1908481491711361
[I 2024-04-16 04:26:46,655] Trial 21 finished with value: 0.1931215820858708 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.21284271933368631
Fold 2 IBS: 0.2192486563965627
Fold 3 IBS: 0.20302325984715375
Fold 4 IBS: 0.2222842490602751
Fold 5 IBS: 0.21629342497904955
[I 2024-04-16 04:26:46,864] Trial 22 finished with value: 0.2147384619233455 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.2348917797349592
Fold 2 IBS: 0.20769957467350794
Fold 3 IBS: 0.18549623005600968
Fold 4 IBS: 0.23641453105930002
Fold 5 IBS: 0.1779298937972312
[I 2024-04-16 04:26:48,043] Trial 23 finished with value: 0.2084864018642016 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.22248320058398224
Fold 2 IBS: 0.19085270418692715
Fold 3 IBS: 0.17172708052628663
Fold 4 IBS: 0.22993815392808942
Fold 5 IBS: 0.17824316338374027
[I 2024-04-16 04:26:48,527] Trial 24 finished with value: 0.19864886052180514 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.22163073147317996
Fold 2 IBS: 0.18475804653138572
Fold 3 IBS: 0.17331748188225873
Fold 4 IBS: 0.21709780321243938
Fold 5 IBS: 0.17657967717546202
[I 2024-04-16 04:26:49,195] Trial 25 finished with value: 0.19467674805494517 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.2644858792854229
Fold 2 IBS: 0.2486759491682301
Fold 3 IBS: 0.23968905490265519
Fold 4 IBS: 0.233199526306374
Fold 5 IBS: 0.21523412642420733
[I 2024-04-16 04:26:50,920] Trial 26 finished with value: 0.24025690721737786 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.25339191360213825
Fold 2 IBS: 0.25022116382378556
Fold 3 IBS: 0.2027814453844964
Fold 4 IBS: 0.2630090606503658
Fold 5 IBS: 0.20584840848674393
[I 2024-04-16 04:26:53,452] Trial 27 finished with value: 0.23505039838950598 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.20540859953998852
Fold 2 IBS: 0.19442982296416572
Fold 3 IBS: 0.18594830345561808
Fold 4 IBS: 0.20627241806463292
Fold 5 IBS: 0.19728010245800706
[I 2024-04-16 04:26:53,842] Trial 28 finished with value: 0.19786784929648246 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.24931739081681506
Fold 2 IBS: 0.24842622998621017
Fold 3 IBS: 0.19459921221273313
Fold 4 IBS: 0.2705170447873235
Fold 5 IBS: 0.2016835897601879
[I 2024-04-16 04:26:54,947] Trial 29 finished with value: 0.23290869351265395 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.23174847485595682
Fold 2 IBS: 0.19128796842178517
Fold 3 IBS: 0.17767376513300048
Fold 4 IBS: 0.22759567423861712
Fold 5 IBS: 0.1794959808639681
[I 2024-04-16 04:26:55,631] Trial 30 finished with value: 0.20156037270266552 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.20253248725392248
Fold 2 IBS: 0.17931619693888584
Fold 3 IBS: 0.17973382077103708
Fold 4 IBS: 0.20229641185319444
Fold 5 IBS: 0.1855900070709249
[I 2024-04-16 04:26:55,959] Trial 31 finished with value: 0.18989378477759294 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.20269608548879392
Fold 2 IBS: 0.1873323872627565
Fold 3 IBS: 0.1810031134706015
Fold 4 IBS: 0.2024962863301319
Fold 5 IBS: 0.19135184112982986
[I 2024-04-16 04:26:56,335] Trial 32 finished with value: 0.19297594273642274 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.2191025946584095
Fold 2 IBS: 0.17272299635536464
Fold 3 IBS: 0.17299267926664363
Fold 4 IBS: 0.19924065778878075
Fold 5 IBS: 0.17739225309334633
[I 2024-04-16 04:26:57,041] Trial 33 finished with value: 0.18829023623250896 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.21111843046231343
Fold 2 IBS: 0.21266003180843784
Fold 3 IBS: 0.20103190734294876
Fold 4 IBS: 0.21864973429916335
Fold 5 IBS: 0.21352235961056626
[I 2024-04-16 04:26:57,287] Trial 34 finished with value: 0.21139649270468594 and parameters: {'subsample': 0.10904251030586302, 'dropout_rate': 0.8662195064551774, 'n_estimators': 3, 'learning_rate': 0.07766566220378217}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.2610163432176493
Fold 2 IBS: 0.26762077174587684
Fold 3 IBS: 0.21669168431022803
Fold 4 IBS: 0.26490195547888185
Fold 5 IBS: 0.2140864787020716
[I 2024-04-16 04:26:58,308] Trial 35 finished with value: 0.24486344669094148 and parameters: {'subsample': 0.27868485453535496, 'dropout_rate': 0.9999743696114711, 'n_estimators': 141, 'learning_rate': 0.06694317131672249}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.31994669955591354
Fold 2 IBS: 0.31984844063617285
Fold 3 IBS: 0.2822168355097264
Fold 4 IBS: 0.2724252295658644
Fold 5 IBS: 0.26632732232374356
[I 2024-04-16 04:27:03,604] Trial 36 finished with value: 0.2921529055182842 and parameters: {'subsample': 0.16326559473518704, 'dropout_rate': 0.8736174627174981, 'n_estimators': 421, 'learning_rate': 0.07993410500556083}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.25917632591228085
Fold 2 IBS: 0.2609248284281908
Fold 3 IBS: 0.2170741765420036
Fold 4 IBS: 0.26518679388858324
Fold 5 IBS: 0.21399443848503105
[I 2024-04-16 04:27:05,213] Trial 37 finished with value: 0.2432713126512179 and parameters: {'subsample': 0.23660873470356106, 'dropout_rate': 0.7990281623991888, 'n_estimators': 170, 'learning_rate': 0.05621431261796065}. Best is trial 19 with value: 0.18631180066870817.
Fold 1 IBS: 0.21687032870860762
Fold 2 IBS: 0.16204476664655687

Fold 3 IBS: 0.17929942687774186
Fold 4 IBS: 0.19699676923820636
Fold 5 IBS: 0.17398211460958732
[I 2024-04-16 04:27:06,146] Trial 38 finished with value: 0.18583868121614 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 82, 'learning_rate': 0.0684395247111694}. Best is trial 38 with value: 0.18583868121614.
Fold 1 IBS: 0.22888158579155815
Fold 2 IBS: 0.1778204923038366
Fold 3 IBS: 0.18090871975165124
Fold 4 IBS: 0.20677627347434813
Fold 5 IBS: 0.17142461059239106
[I 2024-04-16 04:27:06,989] Trial 39 finished with value: 0.19316233638275704 and parameters: {'subsample': 0.1669627464432204, 'dropout_rate': 0.11471626893495929, 'n_estimators': 82, 'learning_rate': 0.06892741183938003}. Best is trial 38 with value: 0.18583868121614.
Fold 1 IBS: 0.26127361158239537
Fold 2 IBS: 0.2702117097774595
Fold 3 IBS: 0.21315070084074397
Fold 4 IBS: 0.2757159479700989
Fold 5 IBS: 0.21996299901762018
[I 2024-04-16 04:27:08,015] Trial 40 finished with value: 0.2480629938376636 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.27073406810212547, 'n_estimators': 112, 'learning_rate': 0.08603457614657108}. Best is trial 38 with value: 0.18583868121614.
Fold 1 IBS: 0.21130908212131316
Fold 2 IBS: 0.16950458163807905
Fold 3 IBS: 0.173988589024671
Fold 4 IBS: 0.19152670241943476
Fold 5 IBS: 0.17104229031766843
[I 2024-04-16 04:27:08,655] Trial 41 finished with value: 0.1834742491042333 and parameters: {'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 58, 'learning_rate': 0.06842845994744125}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21294279749606151
Fold 2 IBS: 0.1721178863934776
Fold 3 IBS: 0.1740474676169385
Fold 4 IBS: 0.20626702855104131
Fold 5 IBS: 0.1726885306438222
[I 2024-04-16 04:27:09,405] Trial 42 finished with value: 0.1876127421402682 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.19807687454956896, 'n_estimators': 64, 'learning_rate': 0.06911254892370094}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.27619832200527716
Fold 2 IBS: 0.26409112204334506
Fold 3 IBS: 0.2400491729418356
Fold 4 IBS: 0.2479075330588565
Fold 5 IBS: 0.21944252036270145
[I 2024-04-16 04:27:11,798] Trial 43 finished with value: 0.24953773408240315 and parameters: {'subsample': 0.20979862666572763, 'dropout_rate': 0.21348524642098904, 'n_estimators': 198, 'learning_rate': 0.0726352652201749}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.22693486364345375
Fold 2 IBS: 0.18207874133352955
Fold 3 IBS: 0.1745575599098608
Fold 4 IBS: 0.2193685130893947
Fold 5 IBS: 0.17467768969059308
[I 2024-04-16 04:27:12,383] Trial 44 finished with value: 0.19552347353336635 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.20101401396422397, 'n_estimators': 63, 'learning_rate': 0.06523605428553468}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.24864207644217515
Fold 2 IBS: 0.23560352937342835
Fold 3 IBS: 0.1931238835425645
Fold 4 IBS: 0.2591423949714222
Fold 5 IBS: 0.19731467924774693
[I 2024-04-16 04:27:13,414] Trial 45 finished with value: 0.22676531271546746 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.295844522167053, 'n_estimators': 96, 'learning_rate': 0.07358829455007394}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.25293066476235887
Fold 2 IBS: 0.23258749253799554
Fold 3 IBS: 0.2223556758424619
Fold 4 IBS: 0.2479267002431483
Fold 5 IBS: 0.2031274131689728
[I 2024-04-16 04:27:14,698] Trial 46 finished with value: 0.23178558931098747 and parameters: {'subsample': 0.14485404068604799, 'dropout_rate': 0.3312246704393865, 'n_estimators': 127, 'learning_rate': 0.08365083008051383}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.2590136426830659
Fold 2 IBS: 0.2253999840879848
Fold 3 IBS: 0.21962782493947147
Fold 4 IBS: 0.2356839366305581
Fold 5 IBS: 0.19684585550554456
[I 2024-04-16 04:27:16,601] Trial 47 finished with value: 0.227314248769325 and parameters: {'subsample': 0.24463732973960714, 'dropout_rate': 0.13911133506878087, 'n_estimators': 175, 'learning_rate': 0.0622210649734474}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.19663557888972058
Fold 2 IBS: 0.18382034240803868
Fold 3 IBS: 0.1793312166111293
Fold 4 IBS: 0.1993595853919695
Fold 5 IBS: 0.18523794622328227
[I 2024-04-16 04:27:16,902] Trial 48 finished with value: 0.18887693390482807 and parameters: {'subsample': 0.10041210259629582, 'dropout_rate': 0.19701471782839963, 'n_estimators': 18, 'learning_rate': 0.09182402211019655}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.22554775032788899
Fold 2 IBS: 0.18582833337060964
Fold 3 IBS: 0.1726364057649019
Fold 4 IBS: 0.22283582309833438
Fold 5 IBS: 0.17769840201135484
[I 2024-04-16 04:27:17,622] Trial 49 finished with value: 0.19690934291461795 and parameters: {'subsample': 0.317047365475798, 'dropout_rate': 0.4402540309495773, 'n_estimators': 75, 'learning_rate': 0.051717833751605366}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.28745221489682693
Fold 2 IBS: 0.2679493081350069
Fold 3 IBS: 0.25002397933621046
Fold 4 IBS: 0.24603541064964232
Fold 5 IBS: 0.22731176900680403
[I 2024-04-16 04:27:20,556] Trial 50 finished with value: 0.25575453640489815 and parameters: {'subsample': 0.1830774219227035, 'dropout_rate': 0.17538138388138197, 'n_estimators': 230, 'learning_rate': 0.07966264522754796}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20022944809474333
Fold 2 IBS: 0.18479399804340646
Fold 3 IBS: 0.18282976257143463
Fold 4 IBS: 0.19689403986055964
Fold 5 IBS: 0.19191634899064533
[I 2024-04-16 04:27:20,855] Trial 51 finished with value: 0.19133271951215788 and parameters: {'subsample': 0.10358892676543137, 'dropout_rate': 0.22720521392768178, 'n_estimators': 13, 'learning_rate': 0.09287462339627435}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21760797584658234
Fold 2 IBS: 0.16591251336533458
Fold 3 IBS: 0.1726818482680744
Fold 4 IBS: 0.19253547633522453
Fold 5 IBS: 0.17251264133994632
[I 2024-04-16 04:27:21,424] Trial 52 finished with value: 0.18425009103103243 and parameters: {'subsample': 0.1340598833564528, 'dropout_rate': 0.10510137537932576, 'n_estimators': 49, 'learning_rate': 0.09073092908320783}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.2844325178702371
Fold 2 IBS: 0.2371816044209461
Fold 3 IBS: 0.2524362212563039
Fold 4 IBS: 0.2287334597164004
Fold 5 IBS: 0.2154162681906941
[I 2024-04-16 04:27:24,893] Trial 53 finished with value: 0.2436400142909163 and parameters: {'subsample': 0.14837293905417098, 'dropout_rate': 0.10434469711993904, 'n_estimators': 276, 'learning_rate': 0.06985484887716305}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.23385137149839316
Fold 2 IBS: 0.18679674469095284
Fold 3 IBS: 0.17592668477690157
Fold 4 IBS: 0.23080777578679756
Fold 5 IBS: 0.17619812038540442
[I 2024-04-16 04:27:25,358] Trial 54 finished with value: 0.2007161394276899 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.1495897230999219, 'n_estimators': 54, 'learning_rate': 0.09044420938220789}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.24558452787161258
Fold 2 IBS: 0.21225395994141127
Fold 3 IBS: 0.21390290726817265
Fold 4 IBS: 0.23025834120692723
Fold 5 IBS: 0.1900797004421133
[I 2024-04-16 04:27:26,213] Trial 55 finished with value: 0.2184158873460474 and parameters: {'subsample': 0.14046116994290284, 'dropout_rate': 0.25227527653590254, 'n_estimators': 98, 'learning_rate': 0.09802843682031426}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21753206574407552
Fold 2 IBS: 0.17902455957681843
Fold 3 IBS: 0.17230603256679577
Fold 4 IBS: 0.20583633761789466
Fold 5 IBS: 0.17369445836809871
[I 2024-04-16 04:27:26,838] Trial 56 finished with value: 0.18967869077473662 and parameters: {'subsample': 0.19002151941221274, 'dropout_rate': 0.3060080718603104, 'n_estimators': 73, 'learning_rate': 0.04838203204104383}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.22155630237314053
Fold 2 IBS: 0.17621326539130433
Fold 3 IBS: 0.17318286771725722

Fold 4 IBS: 0.21234116935596248
Fold 5 IBS: 0.17496721369462195
[I 2024-04-16 04:27:27,316] Trial 57 finished with value: 0.1916521637064573 and parameters: {'subsample': 0.22011128988939735, 'dropout_rate': 0.17296438704055608, 'n_estimators': 49, 'learning_rate': 0.07586937026396535}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20712451000200607
Fold 2 IBS: 0.1872772816103758
Fold 3 IBS: 0.17693753937978524
Fold 4 IBS: 0.20322441833559401
Fold 5 IBS: 0.1877441673818591
[I 2024-04-16 04:27:27,651] Trial 58 finished with value: 0.19246158334192404 and parameters: {'subsample': 0.2849097248903497, 'dropout_rate': 0.36573681723837637, 'n_estimators': 31, 'learning_rate': 0.060250528734790795}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20840523189667032
Fold 2 IBS: 0.16954415076351176
Fold 3 IBS: 0.17248829895886533
Fold 4 IBS: 0.19198239637835499
Fold 5 IBS: 0.17570932494225114
[I 2024-04-16 04:27:28,655] Trial 59 finished with value: 0.1836258805879307 and parameters: {'subsample': 0.1419077907205734, 'dropout_rate': 0.13977283335900992, 'n_estimators': 85, 'learning_rate': 0.036522038667423116}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21672010486884258
Fold 2 IBS: 0.17101744138992256
Fold 3 IBS: 0.17323050630151315
Fold 4 IBS: 0.19432386687801784
Fold 5 IBS: 0.1715369690681281
[I 2024-04-16 04:27:29,703] Trial 60 finished with value: 0.18536577770128485 and parameters: {'subsample': 0.1366875434774738, 'dropout_rate': 0.13861414791217685, 'n_estimators': 114, 'learning_rate': 0.03658146462691025}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20602143909571435
Fold 2 IBS: 0.17285319884856357
Fold 3 IBS: 0.17148094186257504
Fold 4 IBS: 0.19513126427347133
Fold 5 IBS: 0.1771632191733838
[I 2024-04-16 04:27:30,469] Trial 61 finished with value: 0.1845300126507416 and parameters: {'subsample': 0.13446633870139904, 'dropout_rate': 0.12808177950881078, 'n_estimators': 87, 'learning_rate': 0.03248449755710054}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21338484399181257
Fold 2 IBS: 0.17100924034587825
Fold 3 IBS: 0.17353474408267436
Fold 4 IBS: 0.1992541800772075
Fold 5 IBS: 0.17252514505393274
[I 2024-04-16 04:27:31,475] Trial 62 finished with value: 0.1859416307103011 and parameters: {'subsample': 0.13405352504732157, 'dropout_rate': 0.10038254126544646, 'n_estimators': 111, 'learning_rate': 0.036568276132970604}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.2170866118237794
Fold 2 IBS: 0.17799633435555082
Fold 3 IBS: 0.1764362754121712
Fold 4 IBS: 0.19297934006878936
Fold 5 IBS: 0.17028735174489068
[I 2024-04-16 04:27:32,721] Trial 63 finished with value: 0.18695718268103628 and parameters: {'subsample': 0.1277985799371253, 'dropout_rate': 0.12429680217187232, 'n_estimators': 135, 'learning_rate': 0.03622719215914738}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.22377990470363418
Fold 2 IBS: 0.17540929983381395
Fold 3 IBS: 0.17555240169373143
Fold 4 IBS: 0.20651941779360478
Fold 5 IBS: 0.17237493544508975
[I 2024-04-16 04:27:34,271] Trial 64 finished with value: 0.19072719189397483 and parameters: {'subsample': 0.19702876981729325, 'dropout_rate': 0.10090595181580482, 'n_estimators': 158, 'learning_rate': 0.02915716019460439}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21210279177044872
Fold 2 IBS: 0.1724769013850374
Fold 3 IBS: 0.1715472216156799
Fold 4 IBS: 0.1929473822795359
Fold 5 IBS: 0.1763706668946698
[I 2024-04-16 04:27:35,308] Trial 65 finished with value: 0.18508899278907434 and parameters: {'subsample': 0.13534260079947247, 'dropout_rate': 0.16211040629912343, 'n_estimators': 115, 'learning_rate': 0.02919524476455393}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.2086531322661041
Fold 2 IBS: 0.1806411811645162
Fold 3 IBS: 0.174598071385821
Fold 4 IBS: 0.20413231337422638
Fold 5 IBS: 0.1819769479710032
[I 2024-04-16 04:27:36,057] Trial 66 finished with value: 0.19000032923233415 and parameters: {'subsample': 0.25178535118619716, 'dropout_rate': 0.16495752353326598, 'n_estimators': 83, 'learning_rate': 0.026441057321368477}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.2070540285861105
Fold 2 IBS: 0.18002501393783174
Fold 3 IBS: 0.17340364033504818
Fold 4 IBS: 0.19921947338635618
Fold 5 IBS: 0.17954451905234775
[I 2024-04-16 04:27:37,107] Trial 67 finished with value: 0.18784933505953885 and parameters: {'subsample': 0.17628258949715941, 'dropout_rate': 0.23323266546667046, 'n_estimators': 110, 'learning_rate': 0.02209670247372877}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.2348741182195271
Fold 2 IBS: 0.19380495981121493
Fold 3 IBS: 0.18575913178828074
Fold 4 IBS: 0.23275714439139975
Fold 5 IBS: 0.17931329182387995
[I 2024-04-16 04:27:39,169] Trial 68 finished with value: 0.2053017292068605 and parameters: {'subsample': 0.21686074577372216, 'dropout_rate': 0.13164501400328954, 'n_estimators': 196, 'learning_rate': 0.030800283053279493}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20960971662477393
Fold 2 IBS: 0.1724196636421936
Fold 3 IBS: 0.17267982152196554
Fold 4 IBS: 0.19805751576652011
Fold 5 IBS: 0.17865218031933053
[I 2024-04-16 04:27:40,341] Trial 69 finished with value: 0.18628377957495673 and parameters: {'subsample': 0.1309292223158648, 'dropout_rate': 0.1587364331803722, 'n_estimators': 131, 'learning_rate': 0.021222546610156535}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21775459506041608
Fold 2 IBS: 0.18800370410416664
Fold 3 IBS: 0.1715347279406619
Fold 4 IBS: 0.21982254945262433
Fold 5 IBS: 0.18624175365960974
[I 2024-04-16 04:27:41,032] Trial 70 finished with value: 0.19667146604349575 and parameters: {'subsample': 0.8530915147095388, 'dropout_rate': 0.2454372405517462, 'n_estimators': 86, 'learning_rate': 0.033668538384933035}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21652576243867416
Fold 2 IBS: 0.17305404224169546
Fold 3 IBS: 0.17172650518869598
Fold 4 IBS: 0.1952331010805371
Fold 5 IBS: 0.1740637663481096
[I 2024-04-16 04:27:41,938] Trial 71 finished with value: 0.18612063545954244 and parameters: {'subsample': 0.14065660368164415, 'dropout_rate': 0.1845684698870902, 'n_estimators': 105, 'learning_rate': 0.03760282616326456}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20347724890092156
Fold 2 IBS: 0.17884350382421213
Fold 3 IBS: 0.17679575063913877
Fold 4 IBS: 0.19846489648149124
Fold 5 IBS: 0.18382747736279897
[I 2024-04-16 04:27:43,008] Trial 72 finished with value: 0.18828177544171254 and parameters: {'subsample': 0.16809617507788363, 'dropout_rate': 0.14193089094888545, 'n_estimators': 120, 'learning_rate': 0.01667961187045417}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.19994706433262535
Fold 2 IBS: 0.18386111256567148
Fold 3 IBS: 0.17867217473945368
Fold 4 IBS: 0.20083076346275738
Fold 5 IBS: 0.18509379748180232
[I 2024-04-16 04:27:43,456] Trial 73 finished with value: 0.18968098251646207 and parameters: {'subsample': 0.12815046385802628, 'dropout_rate': 0.13096610878181625, 'n_estimators': 42, 'learning_rate': 0.044787680719330425}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.22170819531936062
Fold 2 IBS: 0.1808329990613844
Fold 3 IBS: 0.17379439511250389
Fold 4 IBS: 0.21105887764768813
Fold 5 IBS: 0.17322964618961104
[I 2024-04-16 04:27:44,459] Trial 74 finished with value: 0.1921248226661096 and parameters: {'subsample': 0.19651433107520055, 'dropout_rate': 0.2729211266998668, 'n_estimators': 114, 'learning_rate': 0.03471229822615198}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21505448220909684
Fold 2 IBS: 0.17187221140193826
Fold 3 IBS: 0.17539980324861199
Fold 4 IBS: 0.19722821873057353
Fold 5 IBS: 0.17399056501845794
[I 2024-04-16 04:27:46,005] Trial 75 finished with value: 0.18670905612173572 and parameters: {'subsample': 0.1270645713264064, 'dropout_rate': 0.10325716295023467, 'n_estimators': 160, 'learning_rate': 0.027187741948550045}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.27279513238516145
Fold 2 IBS: 0.2969858674136322

Fold 3 IBS: 0.23054394267833275
Fold 4 IBS: 0.27895191507279604
Fold 5 IBS: 0.25683011697051605
[I 2024-04-16 04:27:36,769] Trial 76 finished with value: 0.2672213949040877 and parameters: {'subsample': 0.7815899098735377, 'dropout_rate': 0.15568721954888723, 'n_estimators': 333, 'learning_rate': 0.038380847630475584}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.2134266504233145
Fold 2 IBS: 0.1806008546727606
Fold 3 IBS: 0.1727394209991852
Fold 4 IBS: 0.2067021380764206
Fold 5 IBS: 0.1811886564373895
[I 2024-04-16 04:27:51,754] Trial 77 finished with value: 0.19093154412181407 and parameters: {'subsample': 0.22380896794758492, 'dropout_rate': 0.223235951943684, 'n_estimators': 93, 'learning_rate': 0.030144736081125657}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20107212380951917
Fold 2 IBS: 0.18248092538711716
Fold 3 IBS: 0.17884990049571556
Fold 4 IBS: 0.19734752701464475
Fold 5 IBS: 0.18708437778913986
[I 2024-04-16 04:27:52,372] Trial 78 finished with value: 0.18936697089922733 and parameters: {'subsample': 0.1603893728372387, 'dropout_rate': 0.17576644885087386, 'n_estimators': 70, 'learning_rate': 0.024765547200182973}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21477487736617915
Fold 2 IBS: 0.1770542344607555
Fold 3 IBS: 0.17341893158621452
Fold 4 IBS: 0.19408996971697084
Fold 5 IBS: 0.17028367605978148
[I 2024-04-16 04:27:53,782] Trial 79 finished with value: 0.1859243378379803 and parameters: {'subsample': 0.12476711920136348, 'dropout_rate': 0.12549162898742322, 'n_estimators': 145, 'learning_rate': 0.03172915785244858}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.21187689957829525
Fold 2 IBS: 0.18398824594002902
Fold 3 IBS: 0.17335151753702527
Fold 4 IBS: 0.20788349600553666
Fold 5 IBS: 0.18328995209209545
[I 2024-04-16 04:27:55,100] Trial 80 finished with value: 0.19207802223059633 and parameters: {'subsample': 0.2613932849707703, 'dropout_rate': 0.20474271883288092, 'n_estimators': 140, 'learning_rate': 0.017798516052250034}. Best is trial 41 with value: 0.1834742491042333.
Fold 1 IBS: 0.20588415710111452
Fold 2 IBS: 0.1730856363400365
Fold 3 IBS: 0.17176034829447936
Fold 4 IBS: 0.18615840132480813
Fold 5 IBS: 0.17196861282638137
[I 2024-04-16 04:27:56,080] Trial 81 finished with value: 0.181771431177364 and parameters: {'subsample': 0.11993447893931333, 'dropout_rate': 0.12494005203793415, 'n_estimators': 105, 'learning_rate': 0.03208117985590775}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.2127059173273915
Fold 2 IBS: 0.17186844974244664
Fold 3 IBS: 0.17128884701216102
Fold 4 IBS: 0.2017907993967618
Fold 5 IBS: 0.17460709189854626
[I 2024-04-16 04:27:57,018] Trial 82 finished with value: 0.18645222107546147 and parameters: {'subsample': 0.18048998452831577, 'dropout_rate': 0.12941525687208416, 'n_estimators': 101, 'learning_rate': 0.03197852395024858}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.2194468245327855
Fold 2 IBS: 0.18518814438932968
Fold 3 IBS: 0.17159486019831355
Fold 4 IBS: 0.217695243415427
Fold 5 IBS: 0.17842896226828958
[I 2024-04-16 04:27:57,828] Trial 83 finished with value: 0.19447080696082905 and parameters: {'subsample': 0.5228328857397202, 'dropout_rate': 0.15916886456358592, 'n_estimators': 76, 'learning_rate': 0.04085560370841025}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.300835942347273
Fold 2 IBS: 0.285191886517957
Fold 3 IBS: 0.2631163777633693
Fold 4 IBS: 0.24620343958943777
Fold 5 IBS: 0.23721106124165733
[I 2024-04-16 04:28:08,048] Trial 84 finished with value: 0.2665117414919389 and parameters: {'subsample': 0.11921448771014957, 'dropout_rate': 0.18182246079552472, 'n_estimators': 494, 'learning_rate': 0.04761428445999186}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.2254988239514827
Fold 2 IBS: 0.17894100335366506
Fold 3 IBS: 0.17537778565796736
Fold 4 IBS: 0.19820045758326568
Fold 5 IBS: 0.17275723570147253
[I 2024-04-16 04:28:09,792] Trial 85 finished with value: 0.19015506124957066 and parameters: {'subsample': 0.15549041837014022, 'dropout_rate': 0.12346425217675844, 'n_estimators': 151, 'learning_rate': 0.03400417435869015}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.20388399576844474
Fold 2 IBS: 0.19323374197782414
Fold 3 IBS: 0.18545473210891303
Fold 4 IBS: 0.20491997422101285
Fold 5 IBS: 0.19521950838066998
[I 2024-04-16 04:28:10,975] Trial 86 finished with value: 0.19654239049137295 and parameters: {'subsample': 0.1941107714101864, 'dropout_rate': 0.14182751008745983, 'n_estimators': 126, 'learning_rate': 0.009313476604200871}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.20444678648828865
Fold 2 IBS: 0.20019161515453693
Fold 3 IBS: 0.19018590245199146
Fold 4 IBS: 0.20698474698665806
Fold 5 IBS: 0.20061840867996333
[I 2024-04-16 04:28:11,388] Trial 87 finished with value: 0.20048549195228768 and parameters: {'subsample': 0.11949992057721498, 'dropout_rate': 0.21327717794710632, 'n_estimators': 40, 'learning_rate': 0.019977581613973575}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.20287687475353763
Fold 2 IBS: 0.17714129012382462
Fold 3 IBS: 0.17521280640031842
Fold 4 IBS: 0.1975541647057191
Fold 5 IBS: 0.1821413477020621
[I 2024-04-16 04:28:12,148] Trial 88 finished with value: 0.18698529673709238 and parameters: {'subsample': 0.15747626832181136, 'dropout_rate': 0.189585036737375, 'n_estimators': 87, 'learning_rate': 0.025341217674642487}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.19812747710996062
Fold 2 IBS: 0.18496024424785318
Fold 3 IBS: 0.18006285544939832
Fold 4 IBS: 0.1943430234859582
Fold 5 IBS: 0.1907093365237412
[I 2024-04-16 04:28:12,671] Trial 89 finished with value: 0.1896405873633823 and parameters: {'subsample': 0.10087658162801826, 'dropout_rate': 0.12079275834589914, 'n_estimators': 56, 'learning_rate': 0.028804408858476068}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.2594403493550406
Fold 2 IBS: 0.2496029600326474
Fold 3 IBS: 0.21478832588551466
Fold 4 IBS: 0.2559540020660912
Fold 5 IBS: 0.20412065796584544
[I 2024-04-16 04:28:14,452] Trial 90 finished with value: 0.23678125906102787 and parameters: {'subsample': 0.23942515047712537, 'dropout_rate': 0.26618354246126075, 'n_estimators': 183, 'learning_rate': 0.053174085387297246}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.2116832011774982
Fold 2 IBS: 0.17190274848050371
Fold 3 IBS: 0.17262632314101062
Fold 4 IBS: 0.19912986066456434
Fold 5 IBS: 0.17325889393387622
[I 2024-04-16 04:28:15,428] Trial 91 finished with value: 0.18572020547949059 and parameters: {'subsample': 0.13469317665276367, 'dropout_rate': 0.10582367417633373, 'n_estimators': 107, 'learning_rate': 0.03537470065708482}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.20300065383471555
Fold 2 IBS: 0.17921905016104867
Fold 3 IBS: 0.17564981847756103
Fold 4 IBS: 0.19623730793444644
Fold 5 IBS: 0.18247323357371217
[I 2024-04-16 04:28:15,985] Trial 92 finished with value: 0.18731601279629675 and parameters: {'subsample': 0.14649043443465362, 'dropout_rate': 0.1500027283422939, 'n_estimators': 65, 'learning_rate': 0.032499500236360584}. Best is trial 81 with value: 0.181771431177364.
Fold 1 IBS: 0.20734145920650368
Fold 2 IBS: 0.16972415820850573
Fold 3 IBS: 0.1715909448893927
Fold 4 IBS: 0.18496864826727374
Fold 5 IBS: 0.1739878724102624
[I 2024-04-16 04:28:16,865] Trial 93 finished with value: 0.18152261659638766 and parameters: {'subsample': 0.12098460820177237, 'dropout_rate': 0.11978813044506781, 'n_estimators': 96, 'learning_rate': 0.039463829092430826}. Best is trial 93 with value: 0.18152261659638766.
Fold 1 IBS: 0.28369387295393855
Fold 2 IBS: 0.2798568533319738
Fold 3 IBS: 0.2479891374539572
Fold 4 IBS: 0.2496803883609833
Fold 5 IBS: 0.22724976681385348
[I 2024-04-16 04:28:23,346] Trial 94 finished with value: 0.25769400378294127 and parameters: {'subsample': 0.1788775339697396, 'dropout_rate': 0.16950276816362408, 'n_estimators': 410, 'learning_rate': 0.04003657432193033}. Best is trial 93 with value: 0.18152261659638766.
Fold 1 IBS: 0.21652163344622521
Fold 2 IBS: 0.17384804415161437

Fold 3 IBS: 0.1730444856942059
Fold 4 IBS: 0.2078118105594406
Fold 5 IBS: 0.1726855062527798
[I 2024-04-16 04:28:24,158] Trial 95 finished with value: 0.1887822960208532 and parameters: {'subsample': 0.20603499818629928, 'dropout_rate': 0.1146228273465264, 'n_estimators': 91, 'learning_rate': 0.042392461808359164}. Best is trial 93 with value: 0.18152261659638766.
Fold 1 IBS: 0.20648347961858549
Fold 2 IBS: 0.20643794993984038
Fold 3 IBS: 0.19466029615625455
Fold 4 IBS: 0.21236891856726114
Fold 5 IBS: 0.20653743680416023
[I 2024-04-16 04:28:24,426] Trial 96 finished with value: 0.20529761621722034 and parameters: {'subsample': 0.11517878134212854, 'dropout_rate': 0.4933732563935224, 'n_estimators': 15, 'learning_rate': 0.035798638536663166}. Best is trial 93 with value: 0.18152261659638766.
Fold 1 IBS: 0.22872724174787454
Fold 2 IBS: 0.18940280361943704
Fold 3 IBS: 0.17802392222300426
Fold 4 IBS: 0.21468859489239034
Fold 5 IBS: 0.17630931950961182
[I 2024-04-16 04:28:25,272] Trial 97 finished with value: 0.1974303763984636 and parameters: {'subsample': 0.16769614855568227, 'dropout_rate': 0.5915083285154504, 'n_estimators': 104, 'learning_rate': 0.043614149675363555}. Best is trial 93 with value: 0.18152261659638766.
Fold 1 IBS: 0.22169564653824395
Fold 2 IBS: 0.18861180981596404
Fold 3 IBS: 0.17135639172899989
Fold 4 IBS: 0.22139643547070223
Fold 5 IBS: 0.17944021081826556
[I 2024-04-16 04:28:25,879] Trial 98 finished with value: 0.19650009887443512 and parameters: {'subsample': 0.6256495106817341, 'dropout_rate': 0.1502723001871735, 'n_estimators': 73, 'learning_rate': 0.0457453640848225}. Best is trial 93 with value: 0.18152261659638766.
Fold 1 IBS: 0.22047209908297663
Fold 2 IBS: 0.17554715867207066
Fold 3 IBS: 0.17330088553203074
Fold 4 IBS: 0.1975736506878685
Fold 5 IBS: 0.17430958973577337
[I 2024-04-16 04:28:26,922] Trial 99 finished with value: 0.18824067674214398 and parameters: {'subsample': 0.14161964217833095, 'dropout_rate': 0.19200783480343173, 'n_estimators': 118, 'learning_rate': 0.037395299604195686}. Best is trial 93 with value: 0.18152261659638766.


* Best trial for IBS:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.18152261659638766], datetime_start=datetime.datetime(2024, 4, 16, 4, 28, 15, 991280), datetime_complete=datetime.datetime(2024, 4, 16, 4, 28, 16, 864506), params={'subsample': 0.12098460820177237, 'dropout_rate': 0.11978813044506781, 'n_estimators': 96, 'learning_rate': 0.039463829092430826}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=93, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.12098460820177237, 'dropout_rate': 0.11978813044506781, 'n_estimators': 96, 'learning_rate': 0.039463829092430826}


* Best Score for IBS:
 0.18152261659638766

In [66]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.714
train_ibs:  0.182

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6202793429199533,
                                              learning_rate=0.08136047667579,
                                              n_estimators=494,
                                              random_state=123,
                                              subsample=0.11713675251393994)

C-index score: 0.573

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.11978813044506781,
                                              learning_rate=0.039463829092430826,
                                              n_estimators=96, random_state=123,
                                              subsample=0.12098460820177237)

IBS: 0.231

In [70]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [71]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.846   1.0
ExtraSurvivalTrees               0.791   2.0
GradientBoosting                 0.765   3.0
CoxElastic                       0.737   4.0
CoxPH                            0.736   5.5
CoxLasso                         0.736   5.5
ComponentwiseGradientBoosting    0.714   7.0
CoxRidge                         0.695   8.0

In [72]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxLasso                       0.171   2.0
CoxElastic                     0.171   2.0
Randomsurvivalforest           0.171   2.0
CoxPH                          0.172   4.0
ExtraSurvivalTrees             0.176   5.0
ComponentwiseGradientBoosting  0.182   6.0
GradientBoosting               0.207   7.0
CoxRidge                       0.217   8.0

In [73]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.602   1.0
GradientBoosting                 0.579   2.0
CoxRidge                         0.577   3.0
ComponentwiseGradientBoosting    0.573   4.0
ExtraSurvivalTrees               0.572   5.0
CoxPH                            0.567   6.0
CoxLasso                         0.566   7.5
CoxElastic                       0.566   7.5

In [74]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.218   1.0
CoxRidge                       0.221   2.5
ExtraSurvivalTrees             0.221   2.5
ComponentwiseGradientBoosting  0.231   4.0
Randomsurvivalforest           0.233   5.0
CoxLasso                       0.257   6.5
CoxElastic                     0.257   6.5
CoxPH                          0.259   8.0

In [75]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/robust/rent/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_robust_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [76]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-16