In [1]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic      p  -log2(p)
MTV                       0.07   0.80      0.33
SUVpeak                   0.17   0.68      0.56
TLG                       0.38   0.54      0.90
age                       0.09   0.77      0.38
cavum_oris                0.00   0.99      0.02
charlson                  1.66   0.20      2.34
female                    2.67   0.10      3.29
histgrade_high            0.13   0.72      0.48
hpv_related              12.67 <0.005     11.39
hypopharynx               0.00   0.99      0.01
larynx                    0.00   0.98      0.03
oropharynx                0.00   0.98      0.02
pack_years                0.06   0.81      0.31
uicc8_III-IV              0.09   0.76      0.39

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.59 0.44      1.17
SUVpeak                   0.01 0.91      0.14
TLG                       0.00 0.96      0.06
age                       0.43 0.51      0.97
cavum_oris                0.41 0.52      0.94
charlson                  0.87 0.35      1.51
female                    2.39 0.12      3.04
histgrade_high            0.11 0.74      0.44
hpv_related               6.46 0.01      6.51
hypopharynx               0.04 0.84      0.25
larynx                    0.97 0.33      1.62
oropharynx                0.85 0.36      1.49
pack_years                0.00 0.99      0.01
uicc8_III-IV              0.00 0.95      0.07

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [18]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Standardization

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = StandardScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [31]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [32]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [33]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [34]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.776210,1,0,1,0,0,1,0.0,0,-1.101176,0.0,0.646616,-0.296907,-0.179158
1,-0.737256,0,0,0,0,1,0,0.0,1,0.105775,0.0,-1.098689,-0.763433,-0.587333
2,-0.158251,0,1,0,0,0,1,0.0,1,0.705374,1.0,-0.581431,0.191169,-0.192863
3,1.354953,0,0,0,0,1,0,0.0,1,0.550384,0.0,-1.499271,-0.705173,-0.594926
4,0.985240,0,0,0,0,1,0,0.0,1,1.233028,0.0,-1.032545,-0.613919,-0.540373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.024835,0,0,1,0,0,1,1.0,0,-1.101176,0.0,-0.312822,-0.615257,-0.488161
135,1.105290,0,0,1,0,0,1,1.0,0,-1.101176,1.0,-0.704742,0.522969,-0.099128
136,-0.354794,0,0,1,0,0,1,1.0,1,0.638406,0.0,0.535536,-0.413130,-0.282017
137,0.703351,0,0,1,0,0,1,1.0,1,2.049005,1.0,-0.642817,0.038162,-0.253362
138,0.185257,0,0,1,0,0,1,1.0,0,-1.002083,1.0,0.383799,-0.293266,-0.218233

In [35]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [36]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.677762,0,0,1,0,0,1,1,1,-1.101176,0,0.825303,0.810851,0.735160
1,-0.677762,0,0,1,0,0,0,0,0,-0.220344,1,-0.398117,-0.465891,-0.433005
2,-0.677762,0,0,1,0,0,0,0,1,-0.836927,1,0.462036,-0.307534,-0.238909
3,0.097786,1,0,0,0,1,1,0,1,0.880696,1,-0.434513,-0.298839,-0.382433
4,1.261108,0,0,1,0,0,1,1,1,1.497278,0,-0.221413,0.245788,-0.068806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.744076,1,0,0,0,1,0,0,0,1.321112,1,3.768483,-0.432451,0.121154
95,0.356302,0,0,0,0,1,0,0,1,6.562062,1,0.381603,-0.352789,-0.266854
96,0.356302,0,0,1,0,0,1,1,1,-1.101176,1,-0.376799,0.338380,-0.094801
97,-0.807020,0,0,1,0,0,1,1,0,-1.101176,0,0.593113,-0.144792,-0.091527
98,0.227044,0,0,0,1,0,1,0,0,0.660488,1,-0.104629,-0.626775,-0.476444

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [37]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:49:40,842] A new study created in memory with name: no-name-847ac761-860d-4d08-b266-a2ade24b8c99

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853

[I 2024-04-13 23:49:43,079] A new study created in memory with name: no-name-075c332f-c652-49f2-81ec-080a12fad5af

Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:43,067] Trial 0 finished with value: 0.7580581707147598 and parameters: {}. Best is trial 0 with value: 0.7580581707147598.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7580581707147598], datetime_start=datetime.datetime(2024, 4, 13, 23, 49, 41, 33018), datetime_complete=datetime.datetime(2024, 4, 13, 23, 49, 43, 66270), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7580581707147598

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.18224790157453516
Fold 2 IBS: 0.17936175872826987
Fold 3 IBS: 0.15783244652723072
Fold 4 IBS: 0.14729407963908242
Fold 5 IBS: 0.27375338992298043
[I 2024-04-13 23:49:44,363] Trial 0 finished with value: 0.18809791527841974 and parameters: {}. Best is trial 0 with value: 0.18809791527841974.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18809791527841974], datetime_start=datetime.datetime(2024, 4, 13, 23, 49, 43, 227178), datetime_complete=datetime.datetime(2024, 4, 13, 23, 49, 44, 363151), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18809791527841974

In [38]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [39]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.188

#### Test

In [40]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [41]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.585
IBS score: 0.288

In [42]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [43]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [44]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:49:44,913] A new study created in memory with name: no-name-f2e0514e-6f95-4bf9-b02f-e876ae54ad5a

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6212121212121212
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8037974683544303

[I 2024-04-13 23:49:45,434] A new study created in memory with name: no-name-63669f38-2793-4460-ac69-b1b99bdcc702

Fold 5 C-index: 0.5633802816901409
[I 2024-04-13 23:49:45,427] Trial 0 finished with value: 0.6797683103857922 and parameters: {}. Best is trial 0 with value: 0.6797683103857922.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6797683103857922], datetime_start=datetime.datetime(2024, 4, 13, 23, 49, 44, 966583), datetime_complete=datetime.datetime(2024, 4, 13, 23, 49, 45, 426821), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6797683103857922

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651674697263
Fold 2 IBS: 0.22157791016872225
Fold 3 IBS: 0.20453594089893293
Fold 4 IBS: 0.2247380328252742
Fold 5 IBS: 0.21812431423859643
[I 2024-04-13 23:49:46,060] Trial 0 finished with value: 0.21659054297569966 and parameters: {}. Best is trial 0 with value: 0.21659054297569966.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054297569966], datetime_start=datetime.datetime(2024, 4, 13, 23, 49, 45, 467562), datetime_complete=datetime.datetime(2024, 4, 13, 23, 49, 46, 60101), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054297569966

In [45]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [46]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.68
train_ibs:  0.217

#### Test

In [47]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [48]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [49]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [50]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:49:46,737] A new study created in memory with name: no-name-0d2fe2c3-d7ba-4af1-a9b1-f1199db5d134

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848

[I 2024-04-13 23:49:47,947] A new study created in memory with name: no-name-ad40fd59-2a90-47d1-b123-a146bfb2d38c

Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:47,938] Trial 0 finished with value: 0.7581946810150825 and parameters: {}. Best is trial 0 with value: 0.7581946810150825.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7581946810150825], datetime_start=datetime.datetime(2024, 4, 13, 23, 49, 46, 850589), datetime_complete=datetime.datetime(2024, 4, 13, 23, 49, 47, 937941), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7581946810150825

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1825807460821382
Fold 2 IBS: 0.17777166673446226
Fold 3 IBS: 0.15623537467337423
Fold 4 IBS: 0.1449349600534243
Fold 5 IBS: 0.27134181046825767
[I 2024-04-13 23:49:49,356] Trial 0 finished with value: 0.18657291160233133 and parameters: {}. Best is trial 0 with value: 0.18657291160233133.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18657291160233133], datetime_start=datetime.datetime(2024, 4, 13, 23, 49, 47, 984104), datetime_complete=datetime.datetime(2024, 4, 13, 23, 49, 49, 356347), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18657291160233133

In [51]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [52]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.187

#### Test

In [53]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [54]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.59

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.284

In [55]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [56]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:49:50,249] A new study created in memory with name: no-name-71e23b88-a18b-4f95-ae2e-a1eaab6d5c62

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:51,517] Trial 0 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:53,169] Trial 1 finished with value: 0.7564579420156853 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:54,661] Trial 2 finished with value: 0.7555650848728281 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:55,901] Trial 3 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:57,260] Trial 4 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:58,331] Trial 5 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7573018238722253.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:49:59,666] Trial 6 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:01,224] Trial 7 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:03,318] Trial 8 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:05,303] Trial 9 finished with value: 0.7564579420156853 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:06,825] Trial 10 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:09,025] Trial 11 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:10,237] Trial 12 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:11,487] Trial 13 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:12,995] Trial 14 finished with value: 0.7555650848728281 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:14,248] Trial 15 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:15,692] Trial 16 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:17,140] Trial 17 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:18,412] Trial 18 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:19,767] Trial 19 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:21,753] Trial 20 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:24,139] Trial 21 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:25,930] Trial 22 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9952149413953396}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:27,394] Trial 23 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8898693182098678}. Best is trial 6 with value: 0.7581946810150825.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:28,856] Trial 24 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:30,138] Trial 25 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9368557715647121}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5915492957746479
[I 2024-04-13 23:50:30,514] Trial 26 finished with value: 0.6862615881779541 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:31,892] Trial 27 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6022588122254688}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:33,288] Trial 28 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6499747968454208}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:34,878] Trial 29 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9010792166439672}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:36,079] Trial 30 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8107108448948633}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:37,341] Trial 31 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9790160904460925}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:38,979] Trial 32 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9889509715055751}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:40,084] Trial 33 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9033942188713268}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:41,062] Trial 34 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9969906676119189}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:42,156] Trial 35 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9145273991086058}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:43,396] Trial 36 finished with value: 0.7555650848728281 and parameters: {'l1_ratio': 0.23789482035414378}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:44,481] Trial 37 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7342815000174964}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:45,579] Trial 38 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8450450825036032}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:46,564] Trial 39 finished with value: 0.7564579420156853 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:47,624] Trial 40 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6762726602177129}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:48,871] Trial 41 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9440922341009589}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:49,992] Trial 42 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8282402619647127}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:51,366] Trial 43 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8728227878830854}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:52,863] Trial 44 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7762299288231321}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:54,353] Trial 45 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.5088251847768541}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:55,576] Trial 46 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9428787838786565}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848

Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:56,951] Trial 47 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9991045282580079}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:50:59,058] Trial 48 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8619031648167028}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:00,888] Trial 49 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.920787420171088}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:02,849] Trial 50 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8176586649944165}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:04,632] Trial 51 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8741637922449004}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:05,655] Trial 52 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9573244425037278}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:06,998] Trial 53 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9596035370242477}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:08,133] Trial 54 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9048315222450667}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:09,393] Trial 55 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8400241295521387}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:10,591] Trial 56 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7944416688958207}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:11,776] Trial 57 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.742931320212047}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:13,105] Trial 58 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.706285456028981}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:14,612] Trial 59 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9534461449471617}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:16,486] Trial 60 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8902829732926482}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:18,931] Trial 61 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9670348868417531}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:22,386] Trial 62 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9223754759119208}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:24,501] Trial 63 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9711124571119798}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:26,252] Trial 64 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9242531939493123}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:28,870] Trial 65 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9895593978036881}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:31,616] Trial 66 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8622329645634031}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:34,298] Trial 67 finished with value: 0.7555650848728281 and parameters: {'l1_ratio': 0.10022359348974141}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:35,830] Trial 68 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8858056810077122}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:37,405] Trial 69 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9982048868245822}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:39,079] Trial 70 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.6278366970608916}. Best is trial 6 with value: 0.7581946810150825.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:41,571] Trial 71 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9432506176402061}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:43,502] Trial 72 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.931431881485834}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:44,899] Trial 73 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9003575197631176}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:46,277] Trial 74 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9653162527053213}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:47,787] Trial 75 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8544199718175486}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:49,261] Trial 76 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.7744674953178161}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:50,682] Trial 77 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9781779419470991}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:52,540] Trial 78 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.5526741878863375}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:54,145] Trial 79 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8341654726402552}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:55,984] Trial 80 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9294442049882141}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:57,461] Trial 81 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9650005972962583}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:51:58,606] Trial 82 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8916254846736968}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:00,648] Trial 83 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9426889451388358}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:02,174] Trial 84 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9971684918976088}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:04,310] Trial 85 finished with value: 0.7564579420156853 and parameters: {'l1_ratio': 0.33218847491866843}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:05,897] Trial 86 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9080519097096644}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:07,466] Trial 87 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.976841397653535}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:09,545] Trial 88 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.4403970354214953}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:11,516] Trial 89 finished with value: 0.7573018238722253 and parameters: {'l1_ratio': 0.8101264333541216}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:13,529] Trial 90 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9986021252316596}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:14,860] Trial 91 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8782233972984056}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:16,099] Trial 92 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9467672077926574}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:17,452] Trial 93 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9146411047411054}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:19,179] Trial 94 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9765663123022124}. Best is trial 6 with value: 0.7581946810150825.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:20,783] Trial 95 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8500811128918233}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:22,539] Trial 96 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9322830193458949}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:24,083] Trial 97 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.9576366890677402}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:25,853] Trial 98 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8940005361147841}. Best is trial 6 with value: 0.7581946810150825.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848

[I 2024-04-13 23:52:27,589] A new study created in memory with name: no-name-371c0d34-502e-4bb9-a3d6-20a5c3e409a9

Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:52:27,552] Trial 99 finished with value: 0.7581946810150825 and parameters: {'l1_ratio': 0.8707339867614515}. Best is trial 6 with value: 0.7581946810150825.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.7581946810150825], datetime_start=datetime.datetime(2024, 4, 13, 23, 49, 58, 342505), datetime_complete=datetime.datetime(2024, 4, 13, 23, 49, 59, 659033), params={'l1_ratio': 0.980766121964777}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.7581946810150825

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1826930793406474
Fold 2 IBS: 0.17814098168529346
Fold 3 IBS: 0.15607788318957047
Fold 4 IBS: 0.14507981109510232
Fold 5 IBS: 0.27092973904575407
[I 2024-04-13 23:52:30,073] Trial 0 finished with value: 0.18658429887127354 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.18658429887127354.
Fold 1 IBS: 0.18287199758336523
Fold 2 IBS: 0.17882425604642588
Fold 3 IBS: 0.1559432644144467
Fold 4 IBS: 0.14534435289145511
Fold 5 IBS: 0.2707544925394689
[I 2024-04-13 23:52:31,707] Trial 1 finished with value: 0.18674767269503237 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.18658429887127354.
Fold 1 IBS: 0.1829089514469264
Fold 2 IBS: 0.17896411692047573
Fold 3 IBS: 0.15600761798837737
Fold 4 IBS: 0.1453400489680181
Fold 5 IBS: 0.2705781041195937
[I 2024-04-13 23:52:33,463] Trial 2 finished with value: 0.18675976788867826 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.18658429887127354.
Fold 1 IBS: 0.18272725168734452
Fold 2 IBS: 0.1783195725395617
Fold 3 IBS: 0.15612623564821185
Fold 4 IBS: 0.14516021596983392
Fold 5 IBS: 0.27093132564105576
[I 2024-04-13 23:52:35,244] Trial 3 finished with value: 0.18665292029720154 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.18658429887127354.
Fold 1 IBS: 0.18267292212007985
Fold 2 IBS: 0.1780157122746497
Fold 3 IBS: 0.1561251076903256
Fold 4 IBS: 0.14512027183063678
Fold 5 IBS: 0.27101993172824357
[I 2024-04-13 23:52:37,097] Trial 4 finished with value: 0.1865907891287871 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.18658429887127354.
Fold 1 IBS: 0.18278430569206205
Fold 2 IBS: 0.17856206952450193
Fold 3 IBS: 0.15599305852745315
Fold 4 IBS: 0.14517042556506124
Fold 5 IBS: 0.2706423467642959
[I 2024-04-13 23:52:39,032] Trial 5 finished with value: 0.18663044121467484 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.18658429887127354.
Fold 1 IBS: 0.18259030558433864
Fold 2 IBS: 0.1777785223936892
Fold 3 IBS: 0.1561980948589147
Fold 4 IBS: 0.14489016727889803
Fold 5 IBS: 0.271332707496662
[I 2024-04-13 23:52:40,541] Trial 6 finished with value: 0.1865579595225005 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.1826552471280701
Fold 2 IBS: 0.17814660942384367
Fold 3 IBS: 0.15618975450477607
Fold 4 IBS: 0.1450577635859424
Fold 5 IBS: 0.2708624939053946
[I 2024-04-13 23:52:42,352] Trial 7 finished with value: 0.18658237370960537 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.18275936175011404
Fold 2 IBS: 0.1784487026632027
Fold 3 IBS: 0.15604861017328134
Fold 4 IBS: 0.14517033839121185
Fold 5 IBS: 0.2707864221432747
[I 2024-04-13 23:52:43,908] Trial 8 finished with value: 0.1866426870242169 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.18277907558358356
Fold 2 IBS: 0.1786309888137703
Fold 3 IBS: 0.1560181829093764
Fold 4 IBS: 0.1452467244949124
Fold 5 IBS: 0.2706703860507458
[I 2024-04-13 23:52:46,851] Trial 9 finished with value: 0.18666907157047768 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.1825882870810292
Fold 2 IBS: 0.1777771866395898
Fold 3 IBS: 0.1562071034556407
Fold 4 IBS: 0.14489451748550267
Fold 5 IBS: 0.2713437307401112
[I 2024-04-13 23:52:49,317] Trial 10 finished with value: 0.1865621650803747 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.18258225225163388
Fold 2 IBS: 0.17777255909763628
Fold 3 IBS: 0.15623043664839228
Fold 4 IBS: 0.14493089497825168
Fold 5 IBS: 0.2713333998519654
[I 2024-04-13 23:52:51,143] Trial 11 finished with value: 0.18656990856557593 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.18258368291559685
Fold 2 IBS: 0.17777345215608165
Fold 3 IBS: 0.15622574853588525
Fold 4 IBS: 0.14492703155750314
Fold 5 IBS: 0.27132537815384333
[I 2024-04-13 23:52:52,867] Trial 12 finished with value: 0.18656705866378206 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.18262662854542042
Fold 2 IBS: 0.1779589236820284
Fold 3 IBS: 0.15626857723014814
Fold 4 IBS: 0.1449264902868209
Fold 5 IBS: 0.27107663396272347
[I 2024-04-13 23:52:54,781] Trial 13 finished with value: 0.18657145074142828 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.18296637422953918
Fold 2 IBS: 0.1793078553393852
Fold 3 IBS: 0.15589719536601454
Fold 4 IBS: 0.1454285036834412
Fold 5 IBS: 0.2703041073212185
[I 2024-04-13 23:52:56,787] Trial 14 finished with value: 0.18678080718791973 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.1865579595225005.
Fold 1 IBS: 0.18261880310792278
Fold 2 IBS: 0.1778235333022951
Fold 3 IBS: 0.15613488335664502
Fold 4 IBS: 0.14494701683534952
Fold 5 IBS: 0.2711296805251933
[I 2024-04-13 23:52:58,520] Trial 15 finished with value: 0.18653078342548116 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18263009804087654
Fold 2 IBS: 0.1779612841655985
Fold 3 IBS: 0.15625727052114133
Fold 4 IBS: 0.1449185869100297
Fold 5 IBS: 0.27105320451830583
[I 2024-04-13 23:53:00,898] Trial 16 finished with value: 0.18656408883119038 and parameters: {'l1_ratio': 0.8461342967218289}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18263305581717865
Fold 2 IBS: 0.17796329418721824
Fold 3 IBS: 0.1562380786636213
Fold 4 IBS: 0.14491084377056462
Fold 5 IBS: 0.27127024019694246
[I 2024-04-13 23:53:03,063] Trial 17 finished with value: 0.18660310252710505 and parameters: {'l1_ratio': 0.8410920720523418}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18270348182643345
Fold 2 IBS: 0.17830504843667444
Fold 3 IBS: 0.1560568205065647
Fold 4 IBS: 0.1450231269736854
Fold 5 IBS: 0.27082378603752555
[I 2024-04-13 23:53:04,668] Trial 18 finished with value: 0.18658245275617671 and parameters: {'l1_ratio': 0.5756090453726656}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18262568507048085
Fold 2 IBS: 0.1779845224156248
Fold 3 IBS: 0.15613541834252953
Fold 4 IBS: 0.14503962753387917
Fold 5 IBS: 0.2710774761628298
[I 2024-04-13 23:53:06,666] Trial 19 finished with value: 0.18657254590506883 and parameters: {'l1_ratio': 0.7905917946901896}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18259190781841866
Fold 2 IBS: 0.17780435947791742
Fold 3 IBS: 0.1562313396412134
Fold 4 IBS: 0.14501911166765585
Fold 5 IBS: 0.2713102715516801
[I 2024-04-13 23:53:08,206] Trial 20 finished with value: 0.1865913980313771 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18257442775977145
Fold 2 IBS: 0.17779208749629902
Fold 3 IBS: 0.15628981232415745
Fold 4 IBS: 0.1450558802988013
Fold 5 IBS: 0.27139160105208493
[I 2024-04-13 23:53:09,652] Trial 21 finished with value: 0.18662076178622283 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18259579501110684
Fold 2 IBS: 0.17780778036684092
Fold 3 IBS: 0.15621546696428096
Fold 4 IBS: 0.14500745481314917
Fold 5 IBS: 0.2712800963646821
[I 2024-04-13 23:53:10,967] Trial 22 finished with value: 0.186581318704012 and parameters: {'l1_ratio': 0.9084391297728723}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.1826489370572582
Fold 2 IBS: 0.17799881144849067
Fold 3 IBS: 0.15620272304765723
Fold 4 IBS: 0.14497962007131493
Fold 5 IBS: 0.2711645938552275
[I 2024-04-13 23:53:12,460] Trial 23 finished with value: 0.1865989370959897 and parameters: {'l1_ratio': 0.75397714149245}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18271024829072188
Fold 2 IBS: 0.17817795582364038
Fold 3 IBS: 0.15616403245310187
Fold 4 IBS: 0.145117658316779
Fold 5 IBS: 0.2710310060583445
[I 2024-04-13 23:53:14,069] Trial 24 finished with value: 0.18664018018851752 and parameters: {'l1_ratio': 0.6169068675056646}. Best is trial 15 with value: 0.18653078342548116.

Fold 1 IBS: 0.182597095351905
Fold 2 IBS: 0.17780878281458193
Fold 3 IBS: 0.15621078519759202
Fold 4 IBS: 0.1450040193628384
Fold 5 IBS: 0.27127120030386354
[I 2024-04-13 23:53:15,305] Trial 25 finished with value: 0.18657837660615617 and parameters: {'l1_ratio': 0.9058787695685316}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18258218281612165
Fold 2 IBS: 0.17777251677605124
Fold 3 IBS: 0.15623066423870974
Fold 4 IBS: 0.1449310825047383
Fold 5 IBS: 0.27133378912614853
[I 2024-04-13 23:53:16,817] Trial 26 finished with value: 0.18657004709235386 and parameters: {'l1_ratio': 0.9973554689957201}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.1826243644080164
Fold 2 IBS: 0.17798356580742047
Fold 3 IBS: 0.15614784526094985
Fold 4 IBS: 0.1450431116078512
Fold 5 IBS: 0.27108642287726653
[I 2024-04-13 23:53:18,842] Trial 27 finished with value: 0.1865770619923009 and parameters: {'l1_ratio': 0.7927751225334085}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18268932888908043
Fold 2 IBS: 0.17816917448767014
Fold 3 IBS: 0.15608030380774454
Fold 4 IBS: 0.14516710718368606
Fold 5 IBS: 0.27091522908244164
[I 2024-04-13 23:53:20,488] Trial 28 finished with value: 0.18660422869012455 and parameters: {'l1_ratio': 0.6413027219856557}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18302835012493993
Fold 2 IBS: 0.22048794875746475
Fold 3 IBS: 0.20354441127442757
Fold 4 IBS: 0.22342084982087337
Fold 5 IBS: 0.2179707672096293
[I 2024-04-13 23:53:21,533] Trial 29 finished with value: 0.209690465437467 and parameters: {'l1_ratio': 0.016175696683504215}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.182622637569475
Fold 2 IBS: 0.1779561953216964
Fold 3 IBS: 0.15613535681168722
Fold 4 IBS: 0.14493695628346578
Fold 5 IBS: 0.2711036879377904
[I 2024-04-13 23:53:24,008] Trial 30 finished with value: 0.18655096678482297 and parameters: {'l1_ratio': 0.8591058455809369}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.1826413653413669
Fold 2 IBS: 0.17796708749440157
Fold 3 IBS: 0.15622011643820374
Fold 4 IBS: 0.14510261719391743
Fold 5 IBS: 0.2712361275028405
[I 2024-04-13 23:53:26,455] Trial 31 finished with value: 0.18663346279414603 and parameters: {'l1_ratio': 0.8318787883380663}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18258706229147265
Fold 2 IBS: 0.17780095547411034
Fold 3 IBS: 0.1562568020677034
Fold 4 IBS: 0.14502943298688267
Fold 5 IBS: 0.2713405835649222
[I 2024-04-13 23:53:28,299] Trial 32 finished with value: 0.18660296727701825 and parameters: {'l1_ratio': 0.9260547704750562}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.1826550287912644
Fold 2 IBS: 0.1780029081224229
Fold 3 IBS: 0.15618287750308488
Fold 4 IBS: 0.1449637034782509
Fold 5 IBS: 0.2711304511037978
[I 2024-04-13 23:53:30,536] Trial 33 finished with value: 0.18658699379976418 and parameters: {'l1_ratio': 0.744919927712684}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18257868846545722
Fold 2 IBS: 0.17779510936126394
Fold 3 IBS: 0.1562630732463181
Fold 4 IBS: 0.14504419291552534
Fold 5 IBS: 0.27138194460666576
[I 2024-04-13 23:53:32,162] Trial 34 finished with value: 0.1866126017190461 and parameters: {'l1_ratio': 0.9376164162053305}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18262284012627317
Fold 2 IBS: 0.177956334183563
Fold 3 IBS: 0.15613464238267916
Fold 4 IBS: 0.14493642421046682
Fold 5 IBS: 0.2711023137513681
[I 2024-04-13 23:53:34,031] Trial 35 finished with value: 0.18655051093087005 and parameters: {'l1_ratio': 0.8587481900394036}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.1826458371655465
Fold 2 IBS: 0.17814436991574367
Fold 3 IBS: 0.15606025167569262
Fold 4 IBS: 0.14506661000870996
Fold 5 IBS: 0.27112838887786145
[I 2024-04-13 23:53:35,724] Trial 36 finished with value: 0.18660909152871086 and parameters: {'l1_ratio': 0.6894475323793506}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18288883414897322
Fold 2 IBS: 0.17889683511756116
Fold 3 IBS: 0.15605189064681363
Fold 4 IBS: 0.14534511428983674
Fold 5 IBS: 0.27067398284208705
[I 2024-04-13 23:53:37,447] Trial 37 finished with value: 0.18677133140905436 and parameters: {'l1_ratio': 0.2554913150275543}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18261682707790428
Fold 2 IBS: 0.17782091697012944
Fold 3 IBS: 0.15614191609120368
Fold 4 IBS: 0.14495220333322514
Fold 5 IBS: 0.2711430766836924
[I 2024-04-13 23:53:38,938] Trial 38 finished with value: 0.18653498803123097 and parameters: {'l1_ratio': 0.8694743357206125}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18264050956290032
Fold 2 IBS: 0.17799519331543565
Fold 3 IBS: 0.15609126195089945
Fold 4 IBS: 0.14500183310564557
Fold 5 IBS: 0.2712175785963404
[I 2024-04-13 23:53:41,269] Trial 39 finished with value: 0.18658927530624428 and parameters: {'l1_ratio': 0.7668635591837233}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18261827395664815
Fold 2 IBS: 0.17782314358759965
Fold 3 IBS: 0.15613675655652037
Fold 4 IBS: 0.14494839847424865
Fold 5 IBS: 0.27113324907056674
[I 2024-04-13 23:53:44,173] Trial 40 finished with value: 0.18653196432911673 and parameters: {'l1_ratio': 0.8668650731968813}. Best is trial 15 with value: 0.18653078342548116.
Fold 1 IBS: 0.18262062222460643
Fold 2 IBS: 0.17782487609662986
Fold 3 IBS: 0.15612842272918795
Fold 4 IBS: 0.14494224878765705
Fold 5 IBS: 0.27111736447470414
[I 2024-04-13 23:53:47,970] Trial 41 finished with value: 0.18652670686255707 and parameters: {'l1_ratio': 0.8626786313052448}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826137786967554
Fold 2 IBS: 0.17782113245360937
Fold 3 IBS: 0.15615231154293638
Fold 4 IBS: 0.1449602263427305
Fold 5 IBS: 0.2711637857746034
[I 2024-04-13 23:53:50,679] Trial 42 finished with value: 0.186542246962127 and parameters: {'l1_ratio': 0.875019881029666}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18265476729627153
Fold 2 IBS: 0.17797815655880458
Fold 3 IBS: 0.15617414147213943
Fold 4 IBS: 0.14506275771539429
Fold 5 IBS: 0.27113687743587683
[I 2024-04-13 23:53:53,557] Trial 43 finished with value: 0.18660134009569734 and parameters: {'l1_ratio': 0.8052991007135147}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18269518462525822
Fold 2 IBS: 0.1781422682709876
Fold 3 IBS: 0.1560711907599972
Fold 4 IBS: 0.14507477115495565
Fold 5 IBS: 0.27090581505482647
[I 2024-04-13 23:53:58,961] Trial 44 finished with value: 0.18657784597320504 and parameters: {'l1_ratio': 0.6938079604362521}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18261264203035274
Fold 2 IBS: 0.17782028220232915
Fold 3 IBS: 0.15615643492416176
Fold 4 IBS: 0.14496321266541945
Fold 5 IBS: 0.27117150153948905
[I 2024-04-13 23:54:00,545] Trial 45 finished with value: 0.18654481467235043 and parameters: {'l1_ratio': 0.8771028327733216}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1828139680084885
Fold 2 IBS: 0.1787258317407575
Fold 3 IBS: 0.15593971058833456
Fold 4 IBS: 0.14524771383200066
Fold 5 IBS: 0.27078602161240045
[I 2024-04-13 23:54:02,679] Trial 46 finished with value: 0.18670264915639634 and parameters: {'l1_ratio': 0.34291267707472417}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18273033774577366
Fold 2 IBS: 0.17843210402891094
Fold 3 IBS: 0.1559906398298801
Fold 4 IBS: 0.14504558613462384
Fold 5 IBS: 0.2709445415779433
[I 2024-04-13 23:54:04,210] Trial 47 finished with value: 0.18662864186342634 and parameters: {'l1_ratio': 0.5063994947206192}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18266851398597603
Fold 2 IBS: 0.1780127788417795
Fold 3 IBS: 0.156139055643738
Fold 4 IBS: 0.14513091974137737
Fold 5 IBS: 0.27104714363520227
[I 2024-04-13 23:54:06,024] Trial 48 finished with value: 0.18659968236961463 and parameters: {'l1_ratio': 0.7256046199060133}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1825700433341351
Fold 2 IBS: 0.1777889531556954
Fold 3 IBS: 0.15614930065824736
Fold 4 IBS: 0.1450657084046905

Fold 5 IBS: 0.2712063814448089
[I 2024-04-13 23:54:09,302] Trial 49 finished with value: 0.18655607739951546 and parameters: {'l1_ratio': 0.9533747955148694}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.182694156414943
Fold 2 IBS: 0.1781668981429178
Fold 3 IBS: 0.15606469614602242
Fold 4 IBS: 0.1451557949146759
Fold 5 IBS: 0.27088556667520813
[I 2024-04-13 23:54:12,168] Trial 50 finished with value: 0.18659342245875343 and parameters: {'l1_ratio': 0.6355126009518985}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18260945314808652
Fold 2 IBS: 0.17781788550647537
Fold 3 IBS: 0.15616783777756874
Fold 4 IBS: 0.14497161979587717
Fold 5 IBS: 0.2711896026040896
[I 2024-04-13 23:54:14,872] Trial 51 finished with value: 0.18655127976641944 and parameters: {'l1_ratio': 0.8830080032072889}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18265223715921625
Fold 2 IBS: 0.17797428213237454
Fold 3 IBS: 0.15618477542954717
Fold 4 IBS: 0.14507649197896977
Fold 5 IBS: 0.2711685971858659
[I 2024-04-13 23:54:17,217] Trial 52 finished with value: 0.18661127677719472 and parameters: {'l1_ratio': 0.814276329671256}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18260713359578942
Fold 2 IBS: 0.1778161339437594
Fold 3 IBS: 0.15617615540363947
Fold 4 IBS: 0.1449777325459228
Fold 5 IBS: 0.27120541243785573
[I 2024-04-13 23:54:22,302] Trial 53 finished with value: 0.18655651358539335 and parameters: {'l1_ratio': 0.8873549131257374}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18260252991027306
Fold 2 IBS: 0.17778656920209918
Fold 3 IBS: 0.1561738692372883
Fold 4 IBS: 0.14507311529882808
Fold 5 IBS: 0.27121483446916256
[I 2024-04-13 23:54:26,647] Trial 54 finished with value: 0.18657018362353023 and parameters: {'l1_ratio': 0.9595490434492127}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18263067205099753
Fold 2 IBS: 0.1779881258607131
Fold 3 IBS: 0.15612590748977376
Fold 4 IBS: 0.14502656435477873
Fold 5 IBS: 0.2710437112928736
[I 2024-04-13 23:54:29,686] Trial 55 finished with value: 0.18656299620982736 and parameters: {'l1_ratio': 0.7824512871200684}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826133390033337
Fold 2 IBS: 0.17782080311755108
Fold 3 IBS: 0.1561538820536958
Fold 4 IBS: 0.1449613835727845
Fold 5 IBS: 0.27116677505027703
[I 2024-04-13 23:54:32,305] Trial 56 finished with value: 0.18654323655952845 and parameters: {'l1_ratio': 0.8758259448550425}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826399300358417
Fold 2 IBS: 0.17796612541845924
Fold 3 IBS: 0.15622476958945686
Fold 4 IBS: 0.14510605871666996
Fold 5 IBS: 0.27124497662641195
[I 2024-04-13 23:54:34,561] Trial 57 finished with value: 0.1866363720773679 and parameters: {'l1_ratio': 0.834250893347143}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18267236868984268
Fold 2 IBS: 0.17801534439447708
Fold 3 IBS: 0.15612653080806455
Fold 4 IBS: 0.14512160838730695
Fold 5 IBS: 0.27102334711788173
[I 2024-04-13 23:54:38,365] Trial 58 finished with value: 0.1865918398795146 and parameters: {'l1_ratio': 0.7202584507834706}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1829133242466262
Fold 2 IBS: 0.179116335919019
Fold 3 IBS: 0.15601253416323957
Fold 4 IBS: 0.14543286960180302
Fold 5 IBS: 0.27055898580198057
[I 2024-04-13 23:54:41,123] Trial 59 finished with value: 0.18680680994653368 and parameters: {'l1_ratio': 0.17271115709842155}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826000189250147
Fold 2 IBS: 0.17781102730375958
Fold 3 IBS: 0.15620025693011227
Fold 4 IBS: 0.14499629696624425
Fold 5 IBS: 0.27125121620753334
[I 2024-04-13 23:54:42,639] Trial 60 finished with value: 0.18657176326653285 and parameters: {'l1_ratio': 0.9001754746146958}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18261727932972874
Fold 2 IBS: 0.17782240514545994
Fold 3 IBS: 0.1561403030641149
Fold 4 IBS: 0.14495101392120008
Fold 5 IBS: 0.27114000450688847
[I 2024-04-13 23:54:45,731] Trial 61 finished with value: 0.1865342011934784 and parameters: {'l1_ratio': 0.8686570945048345}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18260167650108886
Fold 2 IBS: 0.1777860112114094
Fold 3 IBS: 0.15617642517734462
Fold 4 IBS: 0.14507484228392364
Fold 5 IBS: 0.27121989290308285
[I 2024-04-13 23:54:48,530] Trial 62 finished with value: 0.18657176961536986 and parameters: {'l1_ratio': 0.9610023766412396}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826514753018729
Fold 2 IBS: 0.17797596493740883
Fold 3 IBS: 0.15617694273106247
Fold 4 IBS: 0.1450706885557201
Fold 5 IBS: 0.27115724448600614
[I 2024-04-13 23:54:54,685] Trial 63 finished with value: 0.18660646320241409 and parameters: {'l1_ratio': 0.8104603968178263}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826163318330257
Fold 2 IBS: 0.1778205475180857
Fold 3 IBS: 0.15614369001332953
Fold 4 IBS: 0.14495351041132665
Fold 5 IBS: 0.271146441279589
[I 2024-04-13 23:54:57,086] Trial 64 finished with value: 0.1865361042110713 and parameters: {'l1_ratio': 0.8703710095677702}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18264404932919567
Fold 2 IBS: 0.17799551181969728
Fold 3 IBS: 0.1562186644494481
Fold 4 IBS: 0.14499245175630282
Fold 5 IBS: 0.2711995350645413
[I 2024-04-13 23:54:59,118] Trial 65 finished with value: 0.18661004248383703 and parameters: {'l1_ratio': 0.7613994569310706}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18259221624855054
Fold 2 IBS: 0.17780500503419389
Fold 3 IBS: 0.1562283531459121
Fold 4 IBS: 0.145016916924475
Fold 5 IBS: 0.2713045991680561
[I 2024-04-13 23:55:01,407] Trial 66 finished with value: 0.18658941810423751 and parameters: {'l1_ratio': 0.9155627098794084}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826340170569414
Fold 2 IBS: 0.1779639447634136
Fold 3 IBS: 0.15623493905277613
Fold 4 IBS: 0.144908328669542
Fold 5 IBS: 0.2712642776261766
[I 2024-04-13 23:55:04,555] Trial 67 finished with value: 0.18660110143376998 and parameters: {'l1_ratio': 0.8394678431767346}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1825939673267893
Fold 2 IBS: 0.17778094296133037
Fold 3 IBS: 0.15619824405938876
Fold 4 IBS: 0.1448821905740459
Fold 5 IBS: 0.271265588419416
[I 2024-04-13 23:55:06,739] Trial 68 finished with value: 0.18654418666819406 and parameters: {'l1_ratio': 0.9743177457323272}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18262386627423835
Fold 2 IBS: 0.17795703714876768
Fold 3 IBS: 0.15613102378147106
Fold 4 IBS: 0.14493372780136107
Fold 5 IBS: 0.2710953530413148
[I 2024-04-13 23:55:09,537] Trial 69 finished with value: 0.1865482016094306 and parameters: {'l1_ratio': 0.85694079453076}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18258264700515592
Fold 2 IBS: 0.17779924319988777
Fold 3 IBS: 0.1562507847574133
Fold 4 IBS: 0.1450351879727887
Fold 5 IBS: 0.2713554745132462
[I 2024-04-13 23:55:11,979] Trial 70 finished with value: 0.1866046674896984 and parameters: {'l1_ratio': 0.9305297804501909}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826102959660044
Fold 2 IBS: 0.17781852033157539
Fold 3 IBS: 0.1561648234939874
Fold 4 IBS: 0.14496939983741555
Fold 5 IBS: 0.27118386064161176
[I 2024-04-13 23:55:14,244] Trial 71 finished with value: 0.18654938005411886 and parameters: {'l1_ratio': 0.8814390374116529}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.1826269140242764
Fold 2 IBS: 0.17798541170296836
Fold 3 IBS: 0.15613916311567932
Fold 4 IBS: 0.14503636990897256
Fold 5 IBS: 0.27106915243844093
[I 2024-04-13 23:55:16,222] Trial 72 finished with value: 0.1865714022380675 and parameters: {'l1_ratio': 0.7885705276429072}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18265116835651501
Fold 2 IBS: 0.17797364134059374
Fold 3 IBS: 0.15618824035218873
Fold 4 IBS: 0.1450790583506837
Fold 5 IBS: 0.27117520104101894
[I 2024-04-13 23:55:18,803] Trial 73 finished with value: 0.1866134618882 and parameters: {'l1_ratio': 0.8159746068523603}. Best is trial 41 with value: 0.18652670686255707.

Fold 1 IBS: 0.18261691621706228
Fold 2 IBS: 0.17782098343932493
Fold 3 IBS: 0.15614159814021916
Fold 4 IBS: 0.14495196889022768
Fold 5 IBS: 0.2711424711303331
[I 2024-04-13 23:55:20,543] Trial 74 finished with value: 0.1865347875634334 and parameters: {'l1_ratio': 0.8693131368936011}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18265769389109618
Fold 2 IBS: 0.17800469504415845
Fold 3 IBS: 0.1561742081163794
Fold 4 IBS: 0.14495671229029594
Fold 5 IBS: 0.27111397070819115
[I 2024-04-13 23:55:22,407] Trial 75 finished with value: 0.1865814560100242 and parameters: {'l1_ratio': 0.7410231761145568}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18259435732656015
Fold 2 IBS: 0.1778066685259249
Fold 3 IBS: 0.15622065159803722
Fold 4 IBS: 0.14501125481224078
Fold 5 IBS: 0.27128993626355785
[I 2024-04-13 23:55:24,142] Trial 76 finished with value: 0.18658457370526418 and parameters: {'l1_ratio': 0.9112874259530965}. Best is trial 41 with value: 0.18652670686255707.
Fold 1 IBS: 0.18262178644181426
Fold 2 IBS: 0.17782573596244064
Fold 3 IBS: 0.15612427724699623
Fold 4 IBS: 0.14493918976557055
Fold 5 IBS: 0.2711094636903926
[I 2024-04-13 23:55:26,049] Trial 77 finished with value: 0.18652409062144285 and parameters: {'l1_ratio': 0.8606102150962986}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18264245752093858
Fold 2 IBS: 0.17796782114139917
Fold 3 IBS: 0.15621656284822122
Fold 4 IBS: 0.1450999912162542
Fold 5 IBS: 0.2712293724892648
[I 2024-04-13 23:55:29,595] Trial 78 finished with value: 0.1866312410432156 and parameters: {'l1_ratio': 0.8300765798579041}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18257706627898881
Fold 2 IBS: 0.17779396161276342
Fold 3 IBS: 0.1562817608283656
Fold 4 IBS: 0.14504785334192777
Fold 5 IBS: 0.27139142466804045
[I 2024-04-13 23:55:33,345] Trial 79 finished with value: 0.1866184133460172 and parameters: {'l1_ratio': 0.9405268213169947}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18258308587159258
Fold 2 IBS: 0.17777307487362107
Fold 3 IBS: 0.15622770469783173
Fold 4 IBS: 0.1449286438128267
Fold 5 IBS: 0.2713287267077182
[I 2024-04-13 23:55:35,887] Trial 80 finished with value: 0.18656824719271806 and parameters: {'l1_ratio': 0.995700209484268}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18262321446787178
Fold 2 IBS: 0.17795659072476153
Fold 3 IBS: 0.1561333220898674
Fold 4 IBS: 0.1449354396779806
Fold 5 IBS: 0.2710997742941365
[I 2024-04-13 23:55:38,453] Trial 81 finished with value: 0.18654966825092356 and parameters: {'l1_ratio': 0.8580879815205177}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18279560101593254
Fold 2 IBS: 0.17856655598460167
Fold 3 IBS: 0.15596876542351024
Fold 4 IBS: 0.14515419132083363
Fold 5 IBS: 0.27086607186997175
[I 2024-04-13 23:55:41,603] Trial 82 finished with value: 0.18667023712296996 and parameters: {'l1_ratio': 0.41727503208944616}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.182601377688589
Fold 2 IBS: 0.1778120663399032
Fold 3 IBS: 0.15619538083342321
Fold 4 IBS: 0.14499270790577118
Fold 5 IBS: 0.27124193578737993
[I 2024-04-13 23:55:43,459] Trial 83 finished with value: 0.18656869371101328 and parameters: {'l1_ratio': 0.8975494642248371}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.1826148235982841
Fold 2 IBS: 0.17781942187199007
Fold 3 IBS: 0.15614858027139766
Fold 4 IBS: 0.14495747404448261
Fold 5 IBS: 0.27115668315896874
[I 2024-04-13 23:55:45,101] Trial 84 finished with value: 0.1865393965890246 and parameters: {'l1_ratio': 0.8731102035343172}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18263129404946843
Fold 2 IBS: 0.1779885748720475
Fold 3 IBS: 0.15612371264599867
Fold 4 IBS: 0.14502492310474296
Fold 5 IBS: 0.27103949657361315
[I 2024-04-13 23:55:46,504] Trial 85 finished with value: 0.18656160024917412 and parameters: {'l1_ratio': 0.781446150056503}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.182627572159279
Fold 2 IBS: 0.17795956736976587
Fold 3 IBS: 0.15626549220310265
Fold 4 IBS: 0.14492401363737772
Fold 5 IBS: 0.2710702378834682
[I 2024-04-13 23:55:47,947] Trial 86 finished with value: 0.1865693766505987 and parameters: {'l1_ratio': 0.850479298828471}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18267757855656466
Fold 2 IBS: 0.17815996777079043
Fold 3 IBS: 0.15612507416871904
Fold 4 IBS: 0.14500704495769423
Fold 5 IBS: 0.2709869858119179
[I 2024-04-13 23:55:51,202] Trial 87 finished with value: 0.18659133025313723 and parameters: {'l1_ratio': 0.6585776222351463}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18258632764321867
Fold 2 IBS: 0.17780037593700926
Fold 3 IBS: 0.15625943099816395
Fold 4 IBS: 0.14503138395897694
Fold 5 IBS: 0.27134562986921157
[I 2024-04-13 23:55:53,742] Trial 88 finished with value: 0.1866046296813161 and parameters: {'l1_ratio': 0.9275667780754516}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18264873071228857
Fold 2 IBS: 0.17797201624489875
Fold 3 IBS: 0.15619616025160354
Fold 4 IBS: 0.1450849128250091
Fold 5 IBS: 0.27119025362356614
[I 2024-04-13 23:55:56,548] Trial 89 finished with value: 0.18661841473147325 and parameters: {'l1_ratio': 0.8198736574296784}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18273011648644005
Fold 2 IBS: 0.17832133130258934
Fold 3 IBS: 0.1561177513987327
Fold 4 IBS: 0.14515326180825433
Fold 5 IBS: 0.2709151330741145
[I 2024-04-13 23:55:59,341] Trial 90 finished with value: 0.18664751881402622 and parameters: {'l1_ratio': 0.5485323194707394}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.1826167316897893
Fold 2 IBS: 0.1778208458316095
Fold 3 IBS: 0.1561422658592383
Fold 4 IBS: 0.14495245870921886
Fold 5 IBS: 0.27114372470203985
[I 2024-04-13 23:56:01,969] Trial 91 finished with value: 0.18653520535837917 and parameters: {'l1_ratio': 0.8696469004722879}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18261810096390282
Fold 2 IBS: 0.17782301522928218
Fold 3 IBS: 0.15613737329370456
Fold 4 IBS: 0.14494885333259802
Fold 5 IBS: 0.2711344239219303
[I 2024-04-13 23:56:05,876] Trial 92 finished with value: 0.18653235334828358 and parameters: {'l1_ratio': 0.8671762308680895}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18260034295733826
Fold 2 IBS: 0.1778112753182364
Fold 3 IBS: 0.15619909387506486
Fold 4 IBS: 0.14499544316038132
Fold 5 IBS: 0.27124900296979504
[I 2024-04-13 23:56:09,079] Trial 93 finished with value: 0.18657103165616318 and parameters: {'l1_ratio': 0.8995478347158438}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.182620197913337
Fold 2 IBS: 0.17798047394986594
Fold 3 IBS: 0.15615490267874932
Fold 4 IBS: 0.14505435216826465
Fold 5 IBS: 0.2711152890971595
[I 2024-04-13 23:56:10,955] Trial 94 finished with value: 0.18658504316147528 and parameters: {'l1_ratio': 0.7998964202966108}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18264158546396447
Fold 2 IBS: 0.17799384411638666
Fold 3 IBS: 0.15622672470791246
Fold 4 IBS: 0.14499900416826578
Fold 5 IBS: 0.27121090642224466
[I 2024-04-13 23:56:13,051] Trial 95 finished with value: 0.1866144129757548 and parameters: {'l1_ratio': 0.7651947597925196}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.1826309916643463
Fold 2 IBS: 0.17796189154165745
Fold 3 IBS: 0.1562448406489194
Fold 4 IBS: 0.1449162419161851
Fold 5 IBS: 0.271047150861315
[I 2024-04-13 23:56:14,730] Trial 96 finished with value: 0.18656022332648464 and parameters: {'l1_ratio': 0.8446047007662784}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.18261875453447782
Fold 2 IBS: 0.1778234972925109
Fold 3 IBS: 0.15613505648470452
Fold 4 IBS: 0.14494714453441734
Fold 5 IBS: 0.27113001035600126
[I 2024-04-13 23:56:17,091] Trial 97 finished with value: 0.18653089264042239 and parameters: {'l1_ratio': 0.8660083803602437}. Best is trial 77 with value: 0.18652409062144285.
Fold 1 IBS: 0.182603190352609
Fold 2 IBS: 0.17778700072556403
Fold 3 IBS: 0.15617191835212552
Fold 4 IBS: 0.1450717781637212
Fold 5 IBS: 0.2712247809822062
[I 2024-04-13 23:56:19,133] Trial 98 finished with value: 0.18657173371524519 and parameters: {'l1_ratio': 0.9584272611494052}. Best is trial 77 with value: 0.18652409062144285.

Fold 1 IBS: 0.1826438584305466
Fold 2 IBS: 0.17796876109479737
Fold 3 IBS: 0.15621198957389612
Fold 4 IBS: 0.1450966199403859
Fold 5 IBS: 0.2712203585949212
[I 2024-04-13 23:56:21,382] Trial 99 finished with value: 0.18662831752690945 and parameters: {'l1_ratio': 0.8277760149481713}. Best is trial 77 with value: 0.18652409062144285.


* Best trial for IBS:
 FrozenTrial(number=77, state=TrialState.COMPLETE, values=[0.18652409062144285], datetime_start=datetime.datetime(2024, 4, 13, 23, 55, 24, 148756), datetime_complete=datetime.datetime(2024, 4, 13, 23, 55, 26, 44610), params={'l1_ratio': 0.8606102150962986}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=77, value=None)


* Best Score for IBS:
 0.18652409062144285

In [57]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [58]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.187

#### Test

In [59]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [60]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.980766121964777)

test_cindex : 0.59

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.8606102150962986)

test_ibs:  0.284

In [61]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [62]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:56:23,640] A new study created in memory with name: no-name-9cdbe7e8-920a-44ee-8e77-ea6ac4865b2c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6408450704225352
[I 2024-04-13 23:56:43,901] Trial 0 finished with value: 0.7372744686944293 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7372744686944293.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:56:55,935] Trial 1 finished with value: 0.74027341750814 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.74027341750814.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-13 23:57:04,530] Trial 2 finished with value: 0.7431341569351123 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:57:06,724] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:57:10,503] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:57:25,720] Trial 5 finished with value: 0.7299704758481619 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:57:44,998] Trial 6 finished with value: 0.7171141106323402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:57:52,756] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6126760563380281
[I 2024-04-13 23:58:25,502] Trial 8 finished with value: 0.5225352112676056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:58:39,317] Trial 9 finished with value: 0.7250144025097357 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:58:40,775] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 23:58:51,931] Trial 11 finished with value: 0.7414728561808361 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 23:59:03,144] Trial 12 finished with value: 0.7380805853192668 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8619834498485652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1611753146667314, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:59:11,231] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1567471583060459, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7464788732394366
[I 2024-04-13 23:59:19,651] Trial 14 finished with value: 0.8012393138587386 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1306449501762567, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7370892018779343
[I 2024-04-13 23:59:25,280] Trial 15 finished with value: 0.7949512064262649 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.9835664616143871, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0921839163034627, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7230046948356808
[I 2024-04-13 23:59:27,452] Trial 16 finished with value: 0.7913196149300414 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9622193970781673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07748782870655765, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8839662447257384
Fold 5 C-index: 0.7417840375586855
[I 2024-04-13 23:59:32,134] Trial 17 finished with value: 0.7952544618554078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.8172323984404596, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10327357472994507, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 23:59:36,502] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.525862463381169, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7089201877934272
[I 2024-04-13 23:59:37,740] Trial 19 finished with value: 0.7740929694743747 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.8094383772852811, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2171861810731355, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-13 23:59:44,300] Trial 20 finished with value: 0.7896403509052692 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.7024632981250558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11709282828400099, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7276995305164319
[I 2024-04-13 23:59:54,459] Trial 21 finished with value: 0.7918532818563494 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.8592332834187432, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09213353726970255, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 00:00:05,268] Trial 22 finished with value: 0.7987506334970494 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9966124899846646, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.006871014098231751, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 00:00:16,453] Trial 23 finished with value: 0.7965507033377867 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8404793290892639, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 00:00:27,615] Trial 24 finished with value: 0.8010124032513863 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.8944464461493312, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003220931076182737, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:00:38,209] Trial 25 finished with value: 0.8009100471985094 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.9947609548616138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04884572997850131, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 00:00:50,828] Trial 26 finished with value: 0.8019323166712997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.8936722563667562, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 00:01:03,229] Trial 27 finished with value: 0.7848754931720334 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.7589607003643692, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05616441169904532, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 00:01:15,269] Trial 28 finished with value: 0.7687300510570361 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.47643241204116027, 'max_features': None, 'min_weight_fraction_leaf': 0.21228506833672414, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 00:01:26,779] Trial 29 finished with value: 0.791216072808157 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18639977321756945, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 00:01:35,990] Trial 30 finished with value: 0.8141045941707695 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.8995699838431843, 'max_features': None, 'min_weight_fraction_leaf': 0.048019257453591285, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 00:01:44,913] Trial 31 finished with value: 0.8102976168343801 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.8965443067001324, 'max_features': None, 'min_weight_fraction_leaf': 0.04869831874272522, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:01:54,804] Trial 32 finished with value: 0.8044151254239035 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.7822231835771817, 'max_features': None, 'min_weight_fraction_leaf': 0.05953475058332531, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:02:05,539] Trial 33 finished with value: 0.8002008917150547 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.7587808099894491, 'max_features': None, 'min_weight_fraction_leaf': 0.06414988767677843, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:02:17,404] Trial 34 finished with value: 0.802539604149412 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.9277369756073641, 'max_features': None, 'min_weight_fraction_leaf': 0.13073113131665734, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:02:30,427] Trial 35 finished with value: 0.8025908514105005 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.9215912670469352, 'max_features': None, 'min_weight_fraction_leaf': 0.12213968035691111, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:02:42,213] Trial 36 finished with value: 0.8030592181442181 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.7521477069490586, 'max_features': None, 'min_weight_fraction_leaf': 0.028614277170057895, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:02:51,838] Trial 37 finished with value: 0.7924417951105628 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.6723788047810191, 'max_features': None, 'min_weight_fraction_leaf': 0.027521497544371276, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:03:06,075] Trial 38 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.7390641925180915, 'max_features': None, 'min_weight_fraction_leaf': 0.0747020966452816, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 00:03:17,898] Trial 39 finished with value: 0.770986545074277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.6220569630425845, 'max_features': None, 'min_weight_fraction_leaf': 0.2635408988115671, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:03:26,607] Trial 40 finished with value: 0.8014911829899953 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.5663987587631532, 'max_features': None, 'min_weight_fraction_leaf': 0.07499456126338316, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:03:38,047] Trial 41 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 439, 'oob_score': True, 'max_samples': 0.7534073290864295, 'max_features': None, 'min_weight_fraction_leaf': 0.03371263169436823, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:03:49,237] Trial 42 finished with value: 0.8004185708465463 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.7191743052052858, 'max_features': None, 'min_weight_fraction_leaf': 0.03134587591441676, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:03:58,349] Trial 43 finished with value: 0.8044421817009597 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7630755401354222, 'max_features': None, 'min_weight_fraction_leaf': 0.08864460050779976, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:04:08,385] Trial 44 finished with value: 0.7970569598688273 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.6530853458961033, 'max_features': None, 'min_weight_fraction_leaf': 0.0960200605067859, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:04:12,794] Trial 45 finished with value: 0.8063373500099402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.7241711356177275, 'max_features': None, 'min_weight_fraction_leaf': 0.03945374601794358, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:04:32,435] Trial 46 finished with value: 0.7213832269889107 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.7253224444871529, 'max_features': None, 'min_weight_fraction_leaf': 0.03678143977799287, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:04:37,684] Trial 47 finished with value: 0.7895586843791148 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.3630824057039081, 'max_features': None, 'min_weight_fraction_leaf': 0.07375724144112171, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 00:04:56,136] Trial 48 finished with value: 0.7518177358789349 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.8664880785038714, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 00:05:01,559] Trial 49 finished with value: 0.79501517952681 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.8009921187460273, 'max_features': None, 'min_weight_fraction_leaf': 0.14468128914092981, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:05:05,088] Trial 50 finished with value: 0.8025838944631485 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.5979222342836801, 'max_features': None, 'min_weight_fraction_leaf': 0.010569144430309353, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:05:10,016] Trial 51 finished with value: 0.8027595552556749 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.737951588098304, 'max_features': None, 'min_weight_fraction_leaf': 0.08276842957644326, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:05:19,299] Trial 52 finished with value: 0.8046323522601799 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.88848382237019, 'max_features': None, 'min_weight_fraction_leaf': 0.10800154944324664, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 00:05:24,798] Trial 53 finished with value: 0.800061200877051 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.9477043092007602, 'max_features': None, 'min_weight_fraction_leaf': 0.1769969783833071, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:05:32,236] Trial 54 finished with value: 0.8075268254192226 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.8862399763900326, 'max_features': None, 'min_weight_fraction_leaf': 0.04347302641797581, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:05:40,882] Trial 55 finished with value: 0.8100342825585477 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.8308423379101402, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04184905264916955, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:05:56,830] Trial 56 finished with value: 0.7307990843706159 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.8390380366939857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04576803383695833, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:06:00,549] Trial 57 finished with value: 0.8035130393589224 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.862792308947798, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06959281888785387, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:06:06,915] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9167198766277185, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:06:12,873] Trial 59 finished with value: 0.8154047485458795 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.960673091645226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016185485823452278, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:06:27,384] Trial 60 finished with value: 0.7281182409672728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.9694253886674298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017099050018490658, 'warm_start': False}. Best is trial 59 with value: 0.8154047485458795.

Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:06:34,622] Trial 61 finished with value: 0.8091270566720341 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.8024635915627699, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04437120929765639, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:06:42,668] Trial 62 finished with value: 0.8100170485218674 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.8255198768266782, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04384835034305919, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:06:49,429] Trial 63 finished with value: 0.8116391962302029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.8867126274469075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018776766987265683, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:06:54,992] Trial 64 finished with value: 0.805082894192702 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.822935057311086, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012420915832592992, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:06:59,976] Trial 65 finished with value: 0.8127164933462323 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.9479411108137946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019799142307208247, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:07:04,138] Trial 66 finished with value: 0.8152263609296293 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.9503349354445524, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02249332834269111, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:07:08,301] Trial 67 finished with value: 0.8117067729375418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.947093672368275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01713780998356157, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:07:12,713] Trial 68 finished with value: 0.8089947790490772 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.944193226589343, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002610024525408112, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:07:17,175] Trial 69 finished with value: 0.816613418694436 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.9994241275208928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018458075829861618, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:07:22,261] Trial 70 finished with value: 0.8107505717647113 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.9759466742205646, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020962084356569866, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:07:27,373] Trial 71 finished with value: 0.809906689908171 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.9691411143781642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019131120871457744, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:07:31,325] Trial 72 finished with value: 0.8163018383661023 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9857485121561103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019949674867014808, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:07:35,789] Trial 73 finished with value: 0.8209526975590314 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 179, 'oob_score': True, 'max_samples': 0.9999465776424662, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0037053086158703695, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:07:39,789] Trial 74 finished with value: 0.8089728600398164 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.9451824063260522, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006367895628996485, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:07:45,043] Trial 75 finished with value: 0.8193500558621478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.9983757102481674, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00202750601418214, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:07:49,785] Trial 76 finished with value: 0.8120677808474076 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 190, 'oob_score': True, 'max_samples': 0.992384429953266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06509728021815406, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 00:07:52,926] Trial 77 finished with value: 0.8245454518214682 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'max_samples': 0.994249602929978, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003950036087865894, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:07:56,994] Trial 78 finished with value: 0.8200379214069133 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.9921516335417828, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0013870857819101067, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:08:00,327] Trial 79 finished with value: 0.8145453138629154 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.9936071962591497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001248251048872611, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:08:05,998] Trial 80 finished with value: 0.7350889356536794 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'max_samples': 0.9980073532203214, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027351555411740894, 'warm_start': False}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 00:08:09,513] Trial 81 finished with value: 0.814530945119259 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 134, 'oob_score': True, 'max_samples': 0.974317190473141, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008552111924736726, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:08:11,555] Trial 82 finished with value: 0.818405951458202 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.9200032426792089, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004694893977022773, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:08:13,973] Trial 83 finished with value: 0.816209618379516 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.9644628063092593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05687217713082389, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:08:15,255] Trial 84 finished with value: 0.8122353006098141 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 43, 'oob_score': True, 'max_samples': 0.925618686700756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002296274259735591, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:08:17,822] Trial 85 finished with value: 0.8104992933979698 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.912496637320817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06207048371618876, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:08:21,106] Trial 86 finished with value: 0.8114849995979849 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.97217788579977, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03336570424835292, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:08:23,644] Trial 87 finished with value: 0.8229024307173397 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.9977866104840274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05743230682168733, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:08:26,708] Trial 88 finished with value: 0.8163898256753228 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.9290745100371565, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055244525623157625, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7034313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:08:29,556] Trial 89 finished with value: 0.7348861423976064 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.16405866867269464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03211514251936686, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.715962441314554
[I 2024-04-14 00:08:31,353] Trial 90 finished with value: 0.7889841593617299 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 44, 'oob_score': True, 'max_samples': 0.9275901377744842, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2513921457170648, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 00:08:33,976] Trial 91 finished with value: 0.8154508585391724 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9984694614507701, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05353258404318052, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 00:08:36,567] Trial 92 finished with value: 0.7935889758097764 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9795045559078126, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30990393575918357, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:08:39,462] Trial 93 finished with value: 0.8139388966416563 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 93, 'oob_score': True, 'max_samples': 0.9084682802153162, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.056428548931904784, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:08:41,422] Trial 94 finished with value: 0.8132041893160448 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9288744492993337, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08347470326932997, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:08:46,271] Trial 95 finished with value: 0.8036708753502536 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9612484718465076, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09744509645373221, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:08:50,612] Trial 96 finished with value: 0.8082626231905751 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.8773134009465923, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0004414494070137942, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 00:08:53,855] Trial 97 finished with value: 0.825818370590428 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6924882629107981
[I 2024-04-14 00:08:57,330] Trial 98 finished with value: 0.7931972050153308 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9818733759466801, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.34016797358596224, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.869198312236287

[I 2024-04-14 00:09:03,716] A new study created in memory with name: no-name-a1f30fdc-d96c-4615-8ecd-5a6ce5586277

Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:09:03,669] Trial 99 finished with value: 0.733396625437319 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.9114919789954895, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031714611388828556, 'warm_start': False}. Best is trial 97 with value: 0.825818370590428.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.825818370590428], datetime_start=datetime.datetime(2024, 4, 14, 0, 8, 50, 652436), datetime_complete=datetime.datetime(2024, 4, 14, 0, 8, 53, 855090), params={'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=97, value=None)


* Best Score for C-index:
 0.825818370590428

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1750328804590392
Fold 2 IBS: 0.2457909346263125
Fold 3 IBS: 0.16304371295824233
Fold 4 IBS: 0.15636010174832157
Fold 5 IBS: 0.23719057610640573
[I 2024-04-14 00:09:17,993] Trial 0 finished with value: 0.19548364117966427 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19548364117966427.
Fold 1 IBS: 0.18431216543925236
Fold 2 IBS: 0.20449576284397977
Fold 3 IBS: 0.1734496564138547
Fold 4 IBS: 0.1702249879841256
Fold 5 IBS: 0.22320286146192567
[I 2024-04-14 00:09:21,203] Trial 1 finished with value: 0.19113708682862765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-14 00:09:23,755] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-14 00:09:34,565] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-14 00:09:42,874] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.18112177909144025
Fold 2 IBS: 0.21559325389144568
Fold 3 IBS: 0.16126717086083114
Fold 4 IBS: 0.14612944369048034
Fold 5 IBS: 0.2233514487463136
[I 2024-04-14 00:09:54,164] Trial 5 finished with value: 0.1854926192561022 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.1741078934640366
Fold 2 IBS: 0.20103465197964324
Fold 3 IBS: 0.16459803471117013
Fold 4 IBS: 0.16185722968286678
Fold 5 IBS: 0.2275095895598425
[I 2024-04-14 00:10:05,075] Trial 6 finished with value: 0.18582147987951186 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2112963873415951
Fold 2 IBS: 0.2163217730619842
Fold 3 IBS: 0.20084732748350573
Fold 4 IBS: 0.218588755276252
Fold 5 IBS: 0.21598442308805077
[I 2024-04-14 00:10:17,087] Trial 7 finished with value: 0.21260773325027754 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-14 00:10:37,090] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.184925661127663
Fold 2 IBS: 0.2085223967682221
Fold 3 IBS: 0.17516209049302708
Fold 4 IBS: 0.17855956510549414
Fold 5 IBS: 0.2209085976393104
[I 2024-04-14 00:10:41,570] Trial 9 finished with value: 0.19361566222674337 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-14 00:13:28,878] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18095919781067835
Fold 2 IBS: 0.20577163118124792
Fold 3 IBS: 0.1716987840867246
Fold 4 IBS: 0.17502946521027946
Fold 5 IBS: 0.2198343004178619
[I 2024-04-14 00:30:43,299] Trial 11 finished with value: 0.19065867574135845 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17390057719337093
Fold 2 IBS: 0.20052745262326843
Fold 3 IBS: 0.1641107464885408
Fold 4 IBS: 0.161310620284919
Fold 5 IBS: 0.22799428371541863
[I 2024-04-14 00:30:52,675] Trial 12 finished with value: 0.18556873606110355 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18027770462477655
Fold 2 IBS: 0.21277323191047734
Fold 3 IBS: 0.16455120069297058
Fold 4 IBS: 0.1566383560604833
Fold 5 IBS: 0.22277178793167127
[I 2024-04-14 00:30:57,554] Trial 13 finished with value: 0.1874024562440758 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.19012850590013755
Fold 2 IBS: 0.2508215358616786
Fold 3 IBS: 0.16250392476408873
Fold 4 IBS: 0.13720938920743592
Fold 5 IBS: 0.2363581833511397
[I 2024-04-14 00:31:13,902] Trial 14 finished with value: 0.1954043078168961 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.8286563887351183, 'max_features': None, 'min_weight_fraction_leaf': 0.09422981531813096}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18457894361619234
Fold 2 IBS: 0.20704365739729078
Fold 3 IBS: 0.17241207107928186
Fold 4 IBS: 0.17174770550689625
Fold 5 IBS: 0.21936818212879036
[I 2024-04-14 00:31:45,961] Trial 15 finished with value: 0.1910301119456903 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.6817544899569143, 'max_features': 'auto', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 5 with value: 0.1854926192561022.

Fold 1 IBS: 0.1827776694681521
Fold 2 IBS: 0.20934680739331213
Fold 3 IBS: 0.16890212120236864
Fold 4 IBS: 0.1686588011660482
Fold 5 IBS: 0.2195767733572381
[I 2024-04-14 00:32:09,546] Trial 16 finished with value: 0.18985243451742384 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24786833673530304}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140210250926074
Fold 2 IBS: 0.22165374242688704
Fold 3 IBS: 0.20482992077952775
Fold 4 IBS: 0.2248506856151436
Fold 5 IBS: 0.21866286292181575
[I 2024-04-14 00:32:17,778] Trial 17 finished with value: 0.2168036473671963 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3527363076520275}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21398207456199575
Fold 2 IBS: 0.2210878885925555
Fold 3 IBS: 0.20500084248625938
Fold 4 IBS: 0.22467759051518113
Fold 5 IBS: 0.21837641563069746
[I 2024-04-14 00:32:35,291] Trial 18 finished with value: 0.21662496235733783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17751239261549384
Fold 2 IBS: 0.25254123379304744
Fold 3 IBS: 0.17260860317747417
Fold 4 IBS: 0.15329948726148748
Fold 5 IBS: 0.23725228156825823
[I 2024-04-14 00:32:36,644] Trial 19 finished with value: 0.1986427996831522 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.7744054221786105, 'max_features': None, 'min_weight_fraction_leaf': 0.15294426956488405}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140058010941674
Fold 2 IBS: 0.22070271305097472
Fold 3 IBS: 0.20512571269324692
Fold 4 IBS: 0.2244581340346379
Fold 5 IBS: 0.2175740773836072
[I 2024-04-14 00:32:46,388] Trial 20 finished with value: 0.21637328765132682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': None, 'min_weight_fraction_leaf': 0.3111340864325056}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17301280315188314
Fold 2 IBS: 0.19545931456517315
Fold 3 IBS: 0.1650054298323013
Fold 4 IBS: 0.1623577222774968
Fold 5 IBS: 0.22550368553678712
[I 2024-04-14 00:33:00,692] Trial 21 finished with value: 0.1842677910727283 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8774254573678859, 'max_features': None, 'min_weight_fraction_leaf': 0.38285115003898385}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17215244177111103
Fold 2 IBS: 0.18853820269712923
Fold 3 IBS: 0.16580216324267041
Fold 4 IBS: 0.16693346335577489
Fold 5 IBS: 0.22851547915283357
[I 2024-04-14 00:33:15,843] Trial 22 finished with value: 0.1843883500439038 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8533162629857436, 'max_features': None, 'min_weight_fraction_leaf': 0.39473610054688535}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17177605757487213
Fold 2 IBS: 0.1873134062038458
Fold 3 IBS: 0.16528873750502146
Fold 4 IBS: 0.16415554447420388
Fold 5 IBS: 0.22606704734165115
[I 2024-04-14 00:33:33,997] Trial 23 finished with value: 0.1829201586199189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17276619506594362
Fold 2 IBS: 0.18752575408286087
Fold 3 IBS: 0.1660506832687537
Fold 4 IBS: 0.16535591796486823
Fold 5 IBS: 0.2269916388177798
[I 2024-04-14 00:33:51,110] Trial 24 finished with value: 0.18373803784004125 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.911762237036045, 'max_features': None, 'min_weight_fraction_leaf': 0.4145963396824019}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1791579050529914
Fold 2 IBS: 0.18710203409403112
Fold 3 IBS: 0.17160657333121804
Fold 4 IBS: 0.1730776073587778
Fold 5 IBS: 0.23520287606237242
[I 2024-04-14 00:34:12,670] Trial 25 finished with value: 0.18922939917987816 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9270259482202138, 'max_features': None, 'min_weight_fraction_leaf': 0.44717127940994156}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17277943380976452
Fold 2 IBS: 0.20056722047631442
Fold 3 IBS: 0.1648928002543546
Fold 4 IBS: 0.16219739373996186
Fold 5 IBS: 0.22641514420706116
[I 2024-04-14 00:34:33,634] Trial 26 finished with value: 0.18537039849749132 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9129740059593043, 'max_features': None, 'min_weight_fraction_leaf': 0.3870919920523195}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17240759648455306
Fold 2 IBS: 0.18549219526338728
Fold 3 IBS: 0.16616481950290676
Fold 4 IBS: 0.16561034850301004
Fold 5 IBS: 0.22653216582265312
[I 2024-04-14 00:34:49,203] Trial 27 finished with value: 0.18324142511530206 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9882040097907008, 'max_features': None, 'min_weight_fraction_leaf': 0.45340256450947913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.173798138626336
Fold 2 IBS: 0.18532321108542035
Fold 3 IBS: 0.1668142641939112
Fold 4 IBS: 0.16714200768594834
Fold 5 IBS: 0.2276860831891378
[I 2024-04-14 00:35:07,979] Trial 28 finished with value: 0.18415274095615075 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9741542767559068, 'max_features': None, 'min_weight_fraction_leaf': 0.450638299943646}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.213981238234591
Fold 2 IBS: 0.22129600200231184
Fold 3 IBS: 0.20476687908413987
Fold 4 IBS: 0.22462916295400534
Fold 5 IBS: 0.21851703166023365
[I 2024-04-14 00:35:24,606] Trial 29 finished with value: 0.21663806278705633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.773357424692515, 'max_features': None, 'min_weight_fraction_leaf': 0.4837438075147879}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17449266503317365
Fold 2 IBS: 0.19742695190345053
Fold 3 IBS: 0.16471477798087575
Fold 4 IBS: 0.16267147593706363
Fold 5 IBS: 0.22648735220891497
[I 2024-04-14 00:35:41,645] Trial 30 finished with value: 0.18515864461269568 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 377, 'oob_score': False, 'max_samples': 0.9986438777088522, 'max_features': None, 'min_weight_fraction_leaf': 0.42773069772809913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18186563850382112
Fold 2 IBS: 0.18838226339150496
Fold 3 IBS: 0.1747206639662102
Fold 4 IBS: 0.17560736221213202
Fold 5 IBS: 0.23404857262959045
[I 2024-04-14 00:36:00,941] Trial 31 finished with value: 0.19092490014065175 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.939658841329532, 'max_features': None, 'min_weight_fraction_leaf': 0.4524256463348925}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398563901141657
Fold 2 IBS: 0.22134596740550985
Fold 3 IBS: 0.2048025990579434
Fold 4 IBS: 0.22461415055237854
Fold 5 IBS: 0.21851803782809134
[I 2024-04-14 00:36:18,709] Trial 32 finished with value: 0.21665327877106794 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.7396444271446992, 'max_features': None, 'min_weight_fraction_leaf': 0.4501495537267681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19337121417130673
Fold 2 IBS: 0.19511882700454072
Fold 3 IBS: 0.18642967451701625
Fold 4 IBS: 0.1895345717679471
Fold 5 IBS: 0.21856358775020004
[I 2024-04-14 00:36:39,382] Trial 33 finished with value: 0.19660357504220216 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.9933327757837453, 'max_features': None, 'min_weight_fraction_leaf': 0.49338351231891625}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397810999123087
Fold 2 IBS: 0.22130875696604183
Fold 3 IBS: 0.2047621585928816
Fold 4 IBS: 0.2246288907097577
Fold 5 IBS: 0.21863208708031015
[I 2024-04-14 00:36:56,390] Trial 34 finished with value: 0.21666200066804442 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8938554646810188, 'max_features': None, 'min_weight_fraction_leaf': 0.45754449369723726}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397501954215553
Fold 2 IBS: 0.22130442891193944
Fold 3 IBS: 0.20482836466241144
Fold 4 IBS: 0.22464430529398755
Fold 5 IBS: 0.22545436387504872
[I 2024-04-14 00:37:17,251] Trial 35 finished with value: 0.2180412964571085 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.8179898225635556, 'max_features': None, 'min_weight_fraction_leaf': 0.406528295392146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18423128002886327
Fold 2 IBS: 0.20075733721613034
Fold 3 IBS: 0.17640819175973563
Fold 4 IBS: 0.18326652441136565
Fold 5 IBS: 0.21536169700367772
[I 2024-04-14 00:37:34,811] Trial 36 finished with value: 0.1920050060839545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9504880220263004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3678752707538403}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398603848843456
Fold 2 IBS: 0.2212516593844012
Fold 3 IBS: 0.20480476599516775
Fold 4 IBS: 0.22467106118379263
Fold 5 IBS: 0.2186056754258949
[I 2024-04-14 00:37:53,033] Trial 37 finished with value: 0.2166638400955382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.6134779412492984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42910258289196446}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736188003490057
Fold 2 IBS: 0.19364285777259932
Fold 3 IBS: 0.1647798135113072
Fold 4 IBS: 0.1633666298088931
Fold 5 IBS: 0.22711044098051275
[I 2024-04-14 00:38:08,138] Trial 38 finished with value: 0.18450370848446362 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.7324083825350811, 'max_features': None, 'min_weight_fraction_leaf': 0.3267902150060746}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17613246987510892
Fold 2 IBS: 0.25370396104689813
Fold 3 IBS: 0.16470531172106329
Fold 4 IBS: 0.15671091985566343
Fold 5 IBS: 0.23754782764703308
[I 2024-04-14 00:38:28,168] Trial 39 finished with value: 0.19776009802915337 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.8998447540408812, 'max_features': None, 'min_weight_fraction_leaf': 0.26335636534084506}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139718451769373
Fold 2 IBS: 0.22132290174406308
Fold 3 IBS: 0.2049379534123754
Fold 4 IBS: 0.2246651821236489
Fold 5 IBS: 0.21845691499847839
[I 2024-04-14 00:38:43,357] Trial 40 finished with value: 0.21667095949110057 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.5051356852082238, 'max_features': None, 'min_weight_fraction_leaf': 0.46950692236254693}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736115784806322
Fold 2 IBS: 0.19708658583278066
Fold 3 IBS: 0.1647004041861114
Fold 4 IBS: 0.16193266728653144
Fold 5 IBS: 0.2269439330088383
[I 2024-04-14 00:38:55,825] Trial 41 finished with value: 0.1848550337589788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.8766530642885175, 'max_features': None, 'min_weight_fraction_leaf': 0.37480517219328874}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17445559716534967
Fold 2 IBS: 0.20736534205005006
Fold 3 IBS: 0.16501326377011497
Fold 4 IBS: 0.16209455350644228
Fold 5 IBS: 0.22737252886994871
[I 2024-04-14 00:39:14,467] Trial 42 finished with value: 0.18726025707238114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9712277852430382, 'max_features': None, 'min_weight_fraction_leaf': 0.4047116771034673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19485182356242944
Fold 2 IBS: 0.1960274570730997
Fold 3 IBS: 0.18423026068342546
Fold 4 IBS: 0.18829121228006515
Fold 5 IBS: 0.23411274191187137
[I 2024-04-14 00:39:32,308] Trial 43 finished with value: 0.19950269910217824 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8817254098792388, 'max_features': None, 'min_weight_fraction_leaf': 0.43343991639669144}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1712641582188513
Fold 2 IBS: 0.18994637490008684
Fold 3 IBS: 0.16479726253163554
Fold 4 IBS: 0.1632404230753816
Fold 5 IBS: 0.22572502599434202
[I 2024-04-14 00:39:50,665] Trial 44 finished with value: 0.18299464894405942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.9374671457275974, 'max_features': None, 'min_weight_fraction_leaf': 0.41455323262354377}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19234550794011246
Fold 2 IBS: 0.200986097128332
Fold 3 IBS: 0.1855643390306468
Fold 4 IBS: 0.1932590693758762
Fold 5 IBS: 0.21341012086817227
[I 2024-04-14 00:40:09,913] Trial 45 finished with value: 0.19711302686862794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9378530595799813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42089417671131313}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398691344914347
Fold 2 IBS: 0.22137599652455153
Fold 3 IBS: 0.20479386291855103
Fold 4 IBS: 0.2246023464574881
Fold 5 IBS: 0.21853103069298896
[I 2024-04-14 00:40:26,327] Trial 46 finished with value: 0.2166580300085446 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.7938991773051969, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4697812825251582}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1747444583541159
Fold 2 IBS: 0.23713516882516442
Fold 3 IBS: 0.16640805876585935
Fold 4 IBS: 0.1610873512530414
Fold 5 IBS: 0.234167489152576
[I 2024-04-14 00:40:47,878] Trial 47 finished with value: 0.1947085052701514 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.9498935746233631, 'max_features': None, 'min_weight_fraction_leaf': 0.33913737671094774}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398162469590376
Fold 2 IBS: 0.22136781149843104
Fold 3 IBS: 0.20480753036595514
Fold 4 IBS: 0.22461586717115936
Fold 5 IBS: 0.21858421480458282
[I 2024-04-14 00:41:05,934] Trial 48 finished with value: 0.21667140970720644 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8399357435042919, 'max_features': None, 'min_weight_fraction_leaf': 0.43949783817145754}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18607291644289184
Fold 2 IBS: 0.1997166990883884
Fold 3 IBS: 0.17871196581310303
Fold 4 IBS: 0.1866755623669813
Fold 5 IBS: 0.21401906861191788
[I 2024-04-14 00:41:24,068] Trial 49 finished with value: 0.19303924246465648 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 480, 'oob_score': False, 'max_samples': 0.9976678104279734, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4100286247036702}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398689006749297
Fold 2 IBS: 0.22138730674766524
Fold 3 IBS: 0.20483789730275198
Fold 4 IBS: 0.22469041440834978
Fold 5 IBS: 0.21866425238172585
[I 2024-04-14 00:41:35,327] Trial 50 finished with value: 0.21671335218159715 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7082075481455445, 'max_features': None, 'min_weight_fraction_leaf': 0.35750036696317244}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17354922029359332
Fold 2 IBS: 0.20364062415291528
Fold 3 IBS: 0.1656072740863152
Fold 4 IBS: 0.1629843663853799
Fold 5 IBS: 0.22805293589620068
[I 2024-04-14 00:41:44,717] Trial 51 finished with value: 0.18676688416288084 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.9128659910136828, 'max_features': None, 'min_weight_fraction_leaf': 0.3781612359397365}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1713164651684285
Fold 2 IBS: 0.1908535842776438
Fold 3 IBS: 0.16501795349457885
Fold 4 IBS: 0.16355225040434904
Fold 5 IBS: 0.22558632701889753
[I 2024-04-14 00:42:00,245] Trial 52 finished with value: 0.18326531607277957 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.8747189140359779, 'max_features': None, 'min_weight_fraction_leaf': 0.39127818009875937}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1944075620870496
Fold 2 IBS: 0.19446392844340746
Fold 3 IBS: 0.18592909130830435
Fold 4 IBS: 0.18840569735760734
Fold 5 IBS: 0.23475202007425236
[I 2024-04-14 00:42:19,246] Trial 53 finished with value: 0.19959165985412422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9590363563278936, 'max_features': None, 'min_weight_fraction_leaf': 0.47102290336229075}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398291231618569
Fold 2 IBS: 0.22130196765397775
Fold 3 IBS: 0.20479880441504156
Fold 4 IBS: 0.22463025012599544
Fold 5 IBS: 0.21857716931098428
[I 2024-04-14 00:42:32,212] Trial 54 finished with value: 0.21665822076443692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8049999889328818, 'max_features': None, 'min_weight_fraction_leaf': 0.41366841406796956}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19752377093956933
Fold 2 IBS: 0.20161258811122215
Fold 3 IBS: 0.18853359622298724
Fold 4 IBS: 0.19729854245931258
Fold 5 IBS: 0.21444154842475172
[I 2024-04-14 00:42:45,571] Trial 55 finished with value: 0.1998820092315686 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8604557082726361, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.39803093257208977}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18353091887871
Fold 2 IBS: 0.20136616660184192
Fold 3 IBS: 0.17417121851089504
Fold 4 IBS: 0.1806079641160692
Fold 5 IBS: 0.21629928891489889
[I 2024-04-14 00:43:01,317] Trial 56 finished with value: 0.191195111404483 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.9140825717192246, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.33142873928622046}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.176153787215779
Fold 2 IBS: 0.255503897064317
Fold 3 IBS: 0.16322193569881852
Fold 4 IBS: 0.15492145863817686
Fold 5 IBS: 0.23637436039500087
[I 2024-04-14 00:43:18,031] Trial 57 finished with value: 0.19723508780241844 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.846572289034959, 'max_features': None, 'min_weight_fraction_leaf': 0.1892509778618988}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21396974144117978
Fold 2 IBS: 0.22126810284573772
Fold 3 IBS: 0.20478519546942675
Fold 4 IBS: 0.22462583298910568
Fold 5 IBS: 0.2186668640880457
[I 2024-04-14 00:43:35,452] Trial 58 finished with value: 0.21666314736669912 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.9616810596485048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4994697733211825}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17564136184525772
Fold 2 IBS: 0.25480558879113324
Fold 3 IBS: 0.1643534207862224
Fold 4 IBS: 0.1574357976027508
Fold 5 IBS: 0.24128856654900457
[I 2024-04-14 00:43:38,816] Trial 59 finished with value: 0.19870494711487374 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9304423548229083, 'max_features': None, 'min_weight_fraction_leaf': 0.30249606930327194}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397063753981885
Fold 2 IBS: 0.22120321030131956
Fold 3 IBS: 0.20498353734020044
Fold 4 IBS: 0.22465541176579787
Fold 5 IBS: 0.21817456614748645
[I 2024-04-14 00:43:52,584] Trial 60 finished with value: 0.21659747261892465 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.2967533381027988, 'max_features': None, 'min_weight_fraction_leaf': 0.45702707568744816}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1723055398262932
Fold 2 IBS: 0.19143168367074548
Fold 3 IBS: 0.16495123980236973
Fold 4 IBS: 0.16377185203308486
Fold 5 IBS: 0.22590801582391506
[I 2024-04-14 00:44:04,753] Trial 61 finished with value: 0.18367366623128167 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.8753600395959259, 'max_features': None, 'min_weight_fraction_leaf': 0.3908186672612388}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1734277654013816
Fold 2 IBS: 0.20401881796514246
Fold 3 IBS: 0.16490921556493102
Fold 4 IBS: 0.1622125526423405
Fold 5 IBS: 0.2282204138485982
[I 2024-04-14 00:44:16,147] Trial 62 finished with value: 0.18655775308447872 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.8863444595022553, 'max_features': None, 'min_weight_fraction_leaf': 0.3630397965166024}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17425299200408814
Fold 2 IBS: 0.19784814184405533
Fold 3 IBS: 0.16448226706235544
Fold 4 IBS: 0.16221744449574835
Fold 5 IBS: 0.22561034364497506
[I 2024-04-14 00:44:32,287] Trial 63 finished with value: 0.18488223781024446 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.9774803581744468, 'max_features': None, 'min_weight_fraction_leaf': 0.422237244496606}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.17214163753608527
Fold 2 IBS: 0.19020363580055616
Fold 3 IBS: 0.16550959046326688
Fold 4 IBS: 0.16526794959392554
Fold 5 IBS: 0.22833087784482511
[I 2024-04-14 00:44:45,267] Trial 64 finished with value: 0.1842907382477318 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.8662053800926933, 'max_features': None, 'min_weight_fraction_leaf': 0.39542258978805284}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139792007492792
Fold 2 IBS: 0.22131668306329724
Fold 3 IBS: 0.20481655835559517
Fold 4 IBS: 0.22465389902940344
Fold 5 IBS: 0.2186107338002615
[I 2024-04-14 00:44:56,246] Trial 65 finished with value: 0.21667541499956733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 370, 'oob_score': False, 'max_samples': 0.8126605473414451, 'max_features': None, 'min_weight_fraction_leaf': 0.4432122195886301}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139839404571568
Fold 2 IBS: 0.22128662025715748
Fold 3 IBS: 0.20475660906152154
Fold 4 IBS: 0.22463254345676723
Fold 5 IBS: 0.2185879578955235
[I 2024-04-14 00:45:08,478] Trial 66 finished with value: 0.2166495342256253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.7628822009195562, 'max_features': None, 'min_weight_fraction_leaf': 0.4806954217012357}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17446682144724857
Fold 2 IBS: 0.20343226965949585
Fold 3 IBS: 0.16509877229395598
Fold 4 IBS: 0.16272402121276544
Fold 5 IBS: 0.22837609800630052
[I 2024-04-14 00:45:18,095] Trial 67 finished with value: 0.18681959652395327 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9273407143986389, 'max_features': None, 'min_weight_fraction_leaf': 0.3829484376044615}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139737017543663
Fold 2 IBS: 0.22132584453552323
Fold 3 IBS: 0.20489534413800095
Fold 4 IBS: 0.22458301458145777
Fold 5 IBS: 0.21855108631457426
[I 2024-04-14 00:45:31,354] Trial 68 finished with value: 0.21666579826478452 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.4560255505580615, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.43542376867133237}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18183019653099627
Fold 2 IBS: 0.20776625174627097
Fold 3 IBS: 0.16953634624872876
Fold 4 IBS: 0.170118714579068
Fold 5 IBS: 0.21958622926343907
[I 2024-04-14 00:45:46,815] Trial 69 finished with value: 0.18976754767370063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.970602689136413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.263156524754376}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398228747656492
Fold 2 IBS: 0.22137876391118777
Fold 3 IBS: 0.20476882960361822
Fold 4 IBS: 0.22463276305816607
Fold 5 IBS: 0.21856497560430035
[I 2024-04-14 00:46:00,152] Trial 70 finished with value: 0.21666552393076746 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 465, 'oob_score': False, 'max_samples': 0.9012147144740991, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.46397187987790006}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17367631623248717
Fold 2 IBS: 0.18729177749490242
Fold 3 IBS: 0.16716923559227603
Fold 4 IBS: 0.16896965253402357
Fold 5 IBS: 0.22871507732594165
[I 2024-04-14 00:46:10,227] Trial 71 finished with value: 0.1851644118359262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.8369240734764914, 'max_features': None, 'min_weight_fraction_leaf': 0.3894108977238639}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17623676574788
Fold 2 IBS: 0.18722146882244894
Fold 3 IBS: 0.16923825257873615
Fold 4 IBS: 0.17041309974033034
Fold 5 IBS: 0.2308208580988099
[I 2024-04-14 00:46:21,750] Trial 72 finished with value: 0.1867860889976411 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.8867920327737324, 'max_features': None, 'min_weight_fraction_leaf': 0.4157314879593541}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17466534845952894
Fold 2 IBS: 0.21319655330881065
Fold 3 IBS: 0.165618296143337
Fold 4 IBS: 0.1624164693292741
Fold 5 IBS: 0.22901894445979137
[I 2024-04-14 00:46:33,363] Trial 73 finished with value: 0.1889831223401484 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9448081876116871, 'max_features': None, 'min_weight_fraction_leaf': 0.37829799509574824}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19283001171526404
Fold 2 IBS: 0.25233074235756864
Fold 3 IBS: 0.16531718816798083
Fold 4 IBS: 0.1371287117522084
Fold 5 IBS: 0.23777310085766115
[I 2024-04-14 00:46:45,873] Trial 74 finished with value: 0.1970759509701366 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.8560145872964813, 'max_features': None, 'min_weight_fraction_leaf': 0.028106730951250714}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1765526886203159
Fold 2 IBS: 0.24189641128474174
Fold 3 IBS: 0.16693060419975347
Fold 4 IBS: 0.16161303135180896
Fold 5 IBS: 0.2376375116037371
[I 2024-04-14 00:46:54,632] Trial 75 finished with value: 0.19692604941207142 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.9957860072135883, 'max_features': None, 'min_weight_fraction_leaf': 0.34756145962819307}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1751244271301782
Fold 2 IBS: 0.24107670158411845
Fold 3 IBS: 0.16626442192082944
Fold 4 IBS: 0.16107692991176065
Fold 5 IBS: 0.23441060343413975
[I 2024-04-14 00:47:04,279] Trial 76 finished with value: 0.1955906167962053 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.9214268543378774, 'max_features': None, 'min_weight_fraction_leaf': 0.32041444551979115}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398382567775925
Fold 2 IBS: 0.22132197857579206
Fold 3 IBS: 0.20483550783639218
Fold 4 IBS: 0.22469410346846014
Fold 5 IBS: 0.2185234061706301
[I 2024-04-14 00:47:18,381] Trial 77 finished with value: 0.21667176434580676 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': None, 'min_weight_fraction_leaf': 0.4816802580265169}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139815287454151
Fold 2 IBS: 0.22144251355248706
Fold 3 IBS: 0.20476517865000235
Fold 4 IBS: 0.22461967295013774
Fold 5 IBS: 0.21859926137399327
[I 2024-04-14 00:47:32,990] Trial 78 finished with value: 0.21668163105440713 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.8709125293011857, 'max_features': None, 'min_weight_fraction_leaf': 0.4500024716514146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21393847873679495
Fold 2 IBS: 0.2206352907056855
Fold 3 IBS: 0.2052031401141122
Fold 4 IBS: 0.22465935825676747
Fold 5 IBS: 0.2170322205916447
[I 2024-04-14 00:47:44,044] Trial 79 finished with value: 0.21629369768100096 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': None, 'min_weight_fraction_leaf': 0.40382275005132695}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398666839515476
Fold 2 IBS: 0.22133561292920703
Fold 3 IBS: 0.20476084552868884
Fold 4 IBS: 0.22460858228328426
Fold 5 IBS: 0.21850495327987215
[I 2024-04-14 00:48:01,426] Trial 80 finished with value: 0.2166393324832414 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.7543724309332009, 'max_features': None, 'min_weight_fraction_leaf': 0.43164085935118673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1718240887458899
Fold 2 IBS: 0.191437443203446
Fold 3 IBS: 0.16491345446124533
Fold 4 IBS: 0.16398408770898562
Fold 5 IBS: 0.22656733476064983
[I 2024-04-14 00:48:14,310] Trial 81 finished with value: 0.18374528177604332 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.8723363913158229, 'max_features': None, 'min_weight_fraction_leaf': 0.39397540986506063}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17374604878476174
Fold 2 IBS: 0.19798109455852192
Fold 3 IBS: 0.16401735622550842
Fold 4 IBS: 0.1619573282383729
Fold 5 IBS: 0.22581911344299607
[I 2024-04-14 00:48:26,453] Trial 82 finished with value: 0.1847041882500322 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8247493235113283, 'max_features': None, 'min_weight_fraction_leaf': 0.3601096556690917}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17340750457612014
Fold 2 IBS: 0.1865209431926325
Fold 3 IBS: 0.16660200760670268
Fold 4 IBS: 0.16731704053628665
Fold 5 IBS: 0.23067593415026993
[I 2024-04-14 00:48:38,004] Trial 83 finished with value: 0.1849046860124024 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.8997196592880778, 'max_features': None, 'min_weight_fraction_leaf': 0.42074986147139254}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17452011364531658
Fold 2 IBS: 0.21400766260887688
Fold 3 IBS: 0.16568783150449218
Fold 4 IBS: 0.16229140988658286
Fold 5 IBS: 0.22955502465730293
[I 2024-04-14 00:48:50,582] Trial 84 finished with value: 0.1892124084605143 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.9496964476824827, 'max_features': None, 'min_weight_fraction_leaf': 0.37072364798951474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17525073412789557
Fold 2 IBS: 0.2105659370926584
Fold 3 IBS: 0.16602025501429193
Fold 4 IBS: 0.1622139028904671
Fold 5 IBS: 0.22956434629388905
[I 2024-04-14 00:48:59,694] Trial 85 finished with value: 0.18872303508384042 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.9768787275271766, 'max_features': None, 'min_weight_fraction_leaf': 0.389212711709705}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139824234419341
Fold 2 IBS: 0.22136539954988055
Fold 3 IBS: 0.204822165703736
Fold 4 IBS: 0.22464122963551408
Fold 5 IBS: 0.2185219969232711
[I 2024-04-14 00:49:10,185] Trial 86 finished with value: 0.21666664305086716 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.7799819637825093, 'max_features': None, 'min_weight_fraction_leaf': 0.4000713988176814}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.20027780376461612
Fold 2 IBS: 0.20307340294666915
Fold 3 IBS: 0.19102009672018105
Fold 4 IBS: 0.20003685084746606
Fold 5 IBS: 0.21421965519619954
[I 2024-04-14 00:49:22,572] Trial 87 finished with value: 0.20172556189502638 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.9292189383035607, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4390757544239005}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398570828038652
Fold 2 IBS: 0.22140151761658128
Fold 3 IBS: 0.2048003761944947
Fold 4 IBS: 0.22459594623574206
Fold 5 IBS: 0.21853396569713832
[I 2024-04-14 00:49:37,576] Trial 88 finished with value: 0.2166635028048686 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 488, 'oob_score': False, 'max_samples': 0.7896863299148335, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.45607963249620537}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17203791887421
Fold 2 IBS: 0.18726791026590833
Fold 3 IBS: 0.16576625757294128
Fold 4 IBS: 0.16530852151519143
Fold 5 IBS: 0.22888342314880578
[I 2024-04-14 00:49:50,930] Trial 89 finished with value: 0.18385280627541137 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8904926128857917, 'max_features': None, 'min_weight_fraction_leaf': 0.4120116856268681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1940772853656249
Fold 2 IBS: 0.2004241668146479
Fold 3 IBS: 0.18634724520921406
Fold 4 IBS: 0.19496657142921314
Fold 5 IBS: 0.21367459762057212
[I 2024-04-14 00:50:03,082] Trial 90 finished with value: 0.19789797328785444 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.9106880455831121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.40976298541889333}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1926191075437479
Fold 2 IBS: 0.19415079186842468
Fold 3 IBS: 0.18487947833584825
Fold 4 IBS: 0.18641681431445226
Fold 5 IBS: 0.23439208959229954
[I 2024-04-14 00:50:17,259] Trial 91 finished with value: 0.1984916563309545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.8647633953620859, 'max_features': None, 'min_weight_fraction_leaf': 0.42597944887100797}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17236214134250716
Fold 2 IBS: 0.19455412228125918
Fold 3 IBS: 0.16427712812224537
Fold 4 IBS: 0.162949090773761
Fold 5 IBS: 0.2259494780328012
[I 2024-04-14 00:50:33,746] Trial 92 finished with value: 0.18401839211051477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.8900467044086138, 'max_features': None, 'min_weight_fraction_leaf': 0.3893348459268057}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17257330060839252
Fold 2 IBS: 0.18644424300898413
Fold 3 IBS: 0.167229764854462
Fold 4 IBS: 0.16728718203115409
Fold 5 IBS: 0.22779364161313018
[I 2024-04-14 00:50:47,894] Trial 93 finished with value: 0.18426562642322458 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.951027581141039, 'max_features': None, 'min_weight_fraction_leaf': 0.44280477596355444}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17363154839056466
Fold 2 IBS: 0.22743622651322085
Fold 3 IBS: 0.1659053390876856
Fold 4 IBS: 0.1617200646570578
Fold 5 IBS: 0.2317058059728232
[I 2024-04-14 00:51:03,344] Trial 94 finished with value: 0.1920797969242704 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.8997870199007337, 'max_features': None, 'min_weight_fraction_leaf': 0.3407068895244753}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1742039929754336
Fold 2 IBS: 0.22427050607023472
Fold 3 IBS: 0.1662296675861061
Fold 4 IBS: 0.16181525206129235
Fold 5 IBS: 0.2312628649338052
[I 2024-04-14 00:51:17,721] Trial 95 finished with value: 0.1915564567253744 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.9777582543649842, 'max_features': None, 'min_weight_fraction_leaf': 0.37055856104990403}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.18206223269633873
Fold 2 IBS: 0.18820585180072097
Fold 3 IBS: 0.17369714014143833
Fold 4 IBS: 0.1751220212365198
Fold 5 IBS: 0.22437209861320465
[I 2024-04-14 00:51:32,701] Trial 96 finished with value: 0.1886918688976445 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.8430407084230132, 'max_features': None, 'min_weight_fraction_leaf': 0.41419337591128474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17261810934600746
Fold 2 IBS: 0.19291443628076307
Fold 3 IBS: 0.16469348295311864
Fold 4 IBS: 0.16293280131529528
Fold 5 IBS: 0.2265701418039605
[I 2024-04-14 00:51:49,198] Trial 97 finished with value: 0.183945794339829 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.8784577990568653, 'max_features': None, 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1806635839384418
Fold 2 IBS: 0.18847632703053457
Fold 3 IBS: 0.17326431415814442
Fold 4 IBS: 0.17486447351236495
Fold 5 IBS: 0.2258002518864047
[I 2024-04-14 00:52:05,691] Trial 98 finished with value: 0.18861379010517812 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.8075349562887142, 'max_features': None, 'min_weight_fraction_leaf': 0.3942015894342152}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17457318039218142
Fold 2 IBS: 0.19576662913389825
Fold 3 IBS: 0.1643932476316186
Fold 4 IBS: 0.16120104626761333
Fold 5 IBS: 0.22682167562644817
[I 2024-04-14 00:52:13,735] Trial 99 finished with value: 0.18455115581035195 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.8213734885898443, 'max_features': None, 'min_weight_fraction_leaf': 0.35155796421429664}. Best is trial 23 with value: 0.1829201586199189.


* Best trial for IBS:
 FrozenTrial(number=23, state=TrialState.COMPLETE, values=[0.1829201586199189], datetime_start=datetime.datetime(2024, 4, 14, 0, 33, 15, 872126), datetime_complete=datetime.datetime(2024, 4, 14, 0, 33, 33, 995735), params={'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=23, value=None)


* Best Score for IBS:
 0.1829201586199189

In [63]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [64]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.183

#### Test

In [65]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [66]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=19, max_features='log2', max_leaf_nodes=15,
                     max_samples=0.9995515317027949, min_samples_split=18,
                     min_weight_fraction_leaf=0.032175807966512454,
                     n_estimators=115, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.653

RandomSurvivalForest(max_depth=20, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9248759152889626, min_samples_split=2,
                     min_weight_fraction_leaf=0.41894325026727597,
                     n_estimators=396, random_state=123)

test_ibs:  0.206

In [67]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [68]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [69]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 00:52:17,967] A new study created in memory with name: no-name-9e6e472a-40ec-4e0c-a4ad-55f59e8e50d4

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:52:21,038] Trial 0 finished with value: 0.7836129950691764 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:52:28,101] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:52:41,653] Trial 2 finished with value: 0.7556152507681301 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:52:42,823] Trial 3 finished with value: 0.7717160075913865 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:52:47,485] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:52:53,618] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:52:56,801] Trial 6 finished with value: 0.7781769130770997 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:53:05,411] Trial 7 finished with value: 0.7508462032035622 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:53:05,965] Trial 8 finished with value: 0.7684324398125025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:53:23,491] Trial 9 finished with value: 0.7552175391299489 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:53:29,286] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:53:32,469] Trial 11 finished with value: 0.7698273464882801 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:53:36,682] Trial 12 finished with value: 0.7914452579440178 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:53:40,587] Trial 13 finished with value: 0.7653468723507815 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:53:43,736] Trial 14 finished with value: 0.7661538756898894 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.78125

Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:53:46,034] Trial 15 finished with value: 0.7684393821468035 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6267605633802817
[I 2024-04-14 00:53:49,690] Trial 16 finished with value: 0.77051229268592 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:53:52,399] Trial 17 finished with value: 0.7723249788334919 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:53:57,105] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:54:00,425] Trial 19 finished with value: 0.765551411653658 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:54:01,154] Trial 20 finished with value: 0.7391209661793047 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:54:04,264] Trial 21 finished with value: 0.7817887210557736 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:54:07,507] Trial 22 finished with value: 0.7809862642199459 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:54:10,855] Trial 23 finished with value: 0.7759304206293289 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4155863532247274, 'min_weight_fraction_leaf': 0.07928484585286968}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:54:14,410] Trial 24 finished with value: 0.7747196235015181 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.00901469432212705}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 00:54:17,598] Trial 25 finished with value: 0.780898135887688 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.895337843232826, 'min_weight_fraction_leaf': 0.09625756753241399}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:54:28,890] Trial 26 finished with value: 0.7535362780827659 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5901308628926357, 'min_weight_fraction_leaf': 0.04311046725313979}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:54:30,704] Trial 27 finished with value: 0.7700615298551389 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 00:54:33,897] Trial 28 finished with value: 0.7607683592529704 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:54:41,103] Trial 29 finished with value: 0.783702202780981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.11187426524781394}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:54:47,856] Trial 30 finished with value: 0.7671596620665804 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.23846812660748434}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:54:55,600] Trial 31 finished with value: 0.7712482704957379 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9319495980432307, 'min_weight_fraction_leaf': 0.028814153765248245}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:55:02,286] Trial 32 finished with value: 0.7875856659621985 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.83936093173654, 'min_weight_fraction_leaf': 0.10465149498791723}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:55:09,186] Trial 33 finished with value: 0.7854274383297459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8110657459614115, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:55:16,365] Trial 34 finished with value: 0.7875712972185422 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8312111470897382, 'min_weight_fraction_leaf': 0.11396804804122496}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:55:24,371] Trial 35 finished with value: 0.7805626784012362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8317242802235407, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:55:37,908] Trial 36 finished with value: 0.7392301426964731 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.919159658755392, 'min_weight_fraction_leaf': 0.12417590138595275}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:55:45,046] Trial 37 finished with value: 0.7733460193912409 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9384999627665201, 'min_weight_fraction_leaf': 0.21309962076960762}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 00:55:50,665] Trial 38 finished with value: 0.7639313460923033 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 345, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7810779808078776, 'min_weight_fraction_leaf': 0.2883645958901683}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:56:05,774] Trial 39 finished with value: 0.7557517610684528 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 438, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7126142286152415, 'min_weight_fraction_leaf': 0.051535007757158066}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:56:13,058] Trial 40 finished with value: 0.7815020978326014 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6423525258918861, 'min_weight_fraction_leaf': 0.12542889840419838}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:56:19,819] Trial 41 finished with value: 0.7864193339372411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 449, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8300934016687722, 'min_weight_fraction_leaf': 0.10960380301974583}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:56:27,668] Trial 42 finished with value: 0.7880709509204418 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 420, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0742644879267989}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:56:34,421] Trial 43 finished with value: 0.7828465399677109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 413, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7812921734334815, 'min_weight_fraction_leaf': 0.07650726650715535}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:56:41,584] Trial 44 finished with value: 0.7803513206203079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9997498444523031, 'min_weight_fraction_leaf': 0.1566845549254962}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:56:50,476] Trial 45 finished with value: 0.7788761410494602 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 498, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9223521852303842, 'min_weight_fraction_leaf': 0.059273843380186375}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:56:57,615] Trial 46 finished with value: 0.7685371916964001 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 454, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9500103809873137, 'min_weight_fraction_leaf': 0.03660618092052255}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:57:11,773] Trial 47 finished with value: 0.742317931200098 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8574312076294325, 'min_weight_fraction_leaf': 0.08931620844737977}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:57:19,212] Trial 48 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.755266816507861, 'min_weight_fraction_leaf': 0.020812961475463188}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:57:21,518] Trial 49 finished with value: 0.7845202124432327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.814593864444954, 'min_weight_fraction_leaf': 0.09888902748696558}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:57:27,384] Trial 50 finished with value: 0.7773994153326739 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 367, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6864757488123517, 'min_weight_fraction_leaf': 0.0622709472266257}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 00:57:35,796] Trial 51 finished with value: 0.7857905817313229 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 477, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8138857282473038, 'min_weight_fraction_leaf': 0.139261908142962}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:57:44,073] Trial 52 finished with value: 0.7754721899619019 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 483, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.897591154770797, 'min_weight_fraction_leaf': 0.18036745341019644}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:57:50,820] Trial 53 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8040300125345899, 'min_weight_fraction_leaf': 0.13782166853114988}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:57:57,638] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8778737344226841, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:58:01,467] Trial 55 finished with value: 0.7758270084642879 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7446102701098806, 'min_weight_fraction_leaf': 0.0765135926752003}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:58:08,983] Trial 56 finished with value: 0.7744763834479156 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 431, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957871319428308, 'min_weight_fraction_leaf': 0.15347039261632256}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:58:16,780] Trial 57 finished with value: 0.7699442097541136 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 490, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651987019932437, 'min_weight_fraction_leaf': 0.1066939379481781}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:58:32,755] Trial 58 finished with value: 0.7510997177927557 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8492110159158694, 'min_weight_fraction_leaf': 0.1370897749041413}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:58:37,391] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3278490557085546, 'min_weight_fraction_leaf': 0.20658865997161166}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 00:58:45,155] Trial 60 finished with value: 0.7646046839942156 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.2714828861387636}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:58:53,511] Trial 61 finished with value: 0.7875908032299939 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8197782912980647, 'min_weight_fraction_leaf': 0.11182880406892551}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:59:00,882] Trial 62 finished with value: 0.7867469213734538 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7728729369504425, 'min_weight_fraction_leaf': 0.08684392452952273}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:59:07,720] Trial 63 finished with value: 0.7798808652133927 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7730739126088626, 'min_weight_fraction_leaf': 0.08638346674570552}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:59:14,069] Trial 64 finished with value: 0.7930563544969358 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 397, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7094023899138029, 'min_weight_fraction_leaf': 0.016985502713105286}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 00:59:20,278] Trial 65 finished with value: 0.7782230230703928 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5432894752024745, 'min_weight_fraction_leaf': 0.021766672705799798}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:59:23,371] Trial 66 finished with value: 0.7938811826372392 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7228780771138192, 'min_weight_fraction_leaf': 0.0031520648190986253}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:59:26,396] Trial 67 finished with value: 0.7920349896145755 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7208856143139186, 'min_weight_fraction_leaf': 0.000720456341576893}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:59:29,325] Trial 68 finished with value: 0.794041883921594 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7036950154527627, 'min_weight_fraction_leaf': 0.005216408266220198}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 00:59:31,916] Trial 69 finished with value: 0.7859079077910682 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7175215556344815, 'min_weight_fraction_leaf': 0.011727820970865974}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:59:41,335] Trial 70 finished with value: 0.751088073319086 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7068868150575319, 'min_weight_fraction_leaf': 0.04275053996657477}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:59:44,314] Trial 71 finished with value: 0.7894658722092704 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6765833323968065, 'min_weight_fraction_leaf': 0.0056539519960706885}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:59:46,801] Trial 72 finished with value: 0.7914342067886004 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 303, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6657543859502482, 'min_weight_fraction_leaf': 0.0007645303007875817}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:59:49,307] Trial 73 finished with value: 0.7939687176512447 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.0006629495375479764}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:59:51,829] Trial 74 finished with value: 0.7929417632058738 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6089504598680775, 'min_weight_fraction_leaf': 0.009816745037317486}. Best is trial 68 with value: 0.794041883921594.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:59:54,169] Trial 75 finished with value: 0.7886490466297866 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.532426516857448, 'min_weight_fraction_leaf': 0.0002663514949337425}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 00:59:58,946] Trial 76 finished with value: 0.7801220886659336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6123538402148698, 'min_weight_fraction_leaf': 0.019649932961991672}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:00:01,652] Trial 77 finished with value: 0.7814522179558544 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5811927471801297, 'min_weight_fraction_leaf': 0.04878077669029726}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 01:00:04,867] Trial 78 finished with value: 0.7845818837754068 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6462796252211019, 'min_weight_fraction_leaf': 0.03369012476405811}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:00:07,719] Trial 79 finished with value: 0.7787001559323222 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5164947678000329, 'min_weight_fraction_leaf': 0.01622265318172269}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:00:09,855] Trial 80 finished with value: 0.7818525173809616 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 243, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6235631347306672, 'min_weight_fraction_leaf': 0.031552173049052425}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:00:12,520] Trial 81 finished with value: 0.7905684059227995 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6646517878972749, 'min_weight_fraction_leaf': 0.003319138338666917}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 01:00:15,280] Trial 82 finished with value: 0.7915344293360062 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6559993331175135, 'min_weight_fraction_leaf': 0.0007051454739791334}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:00:18,374] Trial 83 finished with value: 0.784834519027793 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6078088154987048, 'min_weight_fraction_leaf': 0.05269795093090639}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:00:20,667] Trial 84 finished with value: 0.7876737917407194 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 252, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.56420075442896, 'min_weight_fraction_leaf': 0.0001867103765655385}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 01:00:23,049] Trial 85 finished with value: 0.7941830791944973 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 01:00:25,349] Trial 86 finished with value: 0.7910103136701933 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7300691279502551, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:00:27,343] Trial 87 finished with value: 0.7870370369739819 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6972914076775041, 'min_weight_fraction_leaf': 0.042431862202902404}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:00:34,789] Trial 88 finished with value: 0.7393760229419569 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.592229960198248, 'min_weight_fraction_leaf': 0.016246248347428313}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:00:37,244] Trial 89 finished with value: 0.7766334763698508 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45159856922443276, 'min_weight_fraction_leaf': 0.05921570024221322}. Best is trial 85 with value: 0.7941830791944973.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 01:00:40,059] Trial 90 finished with value: 0.7708838065283327 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7242276540625545, 'min_weight_fraction_leaf': 0.34283486638092503}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:00:43,314] Trial 91 finished with value: 0.7895419037726438 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6583630297112304, 'min_weight_fraction_leaf': 0.013827947129714684}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:00:46,191] Trial 92 finished with value: 0.7920954683515248 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7515631882154823, 'min_weight_fraction_leaf': 0.028988151290404485}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:00:48,942] Trial 93 finished with value: 0.7937492188401966 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 304, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7381814767748153, 'min_weight_fraction_leaf': 0.030278173261689908}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:00:51,614] Trial 94 finished with value: 0.7930758605083875 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6942749611849839, 'min_weight_fraction_leaf': 0.02829541014533638}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:00:54,257] Trial 95 finished with value: 0.7862754612128648 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.750467494063393, 'min_weight_fraction_leaf': 0.03084864174659612}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:00:57,848] Trial 96 finished with value: 0.7937809600898336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6916627249534713, 'min_weight_fraction_leaf': 0.0642170412166308}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:01:03,492] Trial 97 finished with value: 0.7922100596425867 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6847338071332475, 'min_weight_fraction_leaf': 0.06422450776206082}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:01:07,093] Trial 98 finished with value: 0.7896281650393346 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6945703344834594, 'min_weight_fraction_leaf': 0.06929480157264988}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608

[I 2024-04-14 01:01:08,930] A new study created in memory with name: no-name-3acc9936-3da2-47bb-846f-ab3afa61d2a2

Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 01:01:08,889] Trial 99 finished with value: 0.7912614087353609 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6926648599741109, 'min_weight_fraction_leaf': 0.05098663692788332}. Best is trial 85 with value: 0.7941830791944973.


* Best trial for C-index:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.7941830791944973], datetime_start=datetime.datetime(2024, 4, 14, 1, 0, 20, 673423), datetime_complete=datetime.datetime(2024, 4, 14, 1, 0, 23, 48523), params={'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for C-index:
 0.7941830791944973

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16943133784699038
Fold 2 IBS: 0.217110921492143
Fold 3 IBS: 0.16458005935948244
Fold 4 IBS: 0.15978141365273868
Fold 5 IBS: 0.23006411985790817
[I 2024-04-14 01:01:18,287] Trial 0 finished with value: 0.18819357044185253 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 01:01:34,073] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.1920088773895634
Fold 2 IBS: 0.20722305192399237
Fold 3 IBS: 0.1843664308419076
Fold 4 IBS: 0.19578634061172853
Fold 5 IBS: 0.21729770324619507
[I 2024-04-14 01:01:47,024] Trial 2 finished with value: 0.1993364808026774 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.19258828625505786
Fold 2 IBS: 0.2045422331943319
Fold 3 IBS: 0.1853898388957368
Fold 4 IBS: 0.19796057104495973
Fold 5 IBS: 0.21730311317672968
[I 2024-04-14 01:01:52,795] Trial 3 finished with value: 0.1995568085133632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 01:02:05,267] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 01:02:11,375] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.17108054547230092
Fold 2 IBS: 0.21332710542268465
Fold 3 IBS: 0.1636503921602676
Fold 4 IBS: 0.1601897971404523
Fold 5 IBS: 0.23011170771684802
[I 2024-04-14 01:02:22,655] Trial 6 finished with value: 0.1876719095825107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.1802257330412862
Fold 2 IBS: 0.20553844032632104
Fold 3 IBS: 0.17516423786860197
Fold 4 IBS: 0.18156654611164302
Fold 5 IBS: 0.21889734913100833
[I 2024-04-14 01:02:30,508] Trial 7 finished with value: 0.1922784612957721 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19324605458737515
Fold 2 IBS: 0.20063316435414258
Fold 3 IBS: 0.18395193632306783
Fold 4 IBS: 0.19657870618224477
Fold 5 IBS: 0.2180785905917539
[I 2024-04-14 01:02:32,385] Trial 8 finished with value: 0.19849769040771686 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19947118578728948
Fold 2 IBS: 0.2128915375997729
Fold 3 IBS: 0.19180552923211425
Fold 4 IBS: 0.21059003168383789
Fold 5 IBS: 0.2166615073888468
[I 2024-04-14 01:02:47,197] Trial 9 finished with value: 0.20628395833837226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.21397612241164576
Fold 2 IBS: 0.2207394210478338
Fold 3 IBS: 0.20537940251283027
Fold 4 IBS: 0.22474853253260105
Fold 5 IBS: 0.2174222289467434
[I 2024-04-14 01:02:59,176] Trial 10 finished with value: 0.21645314149033087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.2015386647704584
Fold 2 IBS: 0.21349515547127124
Fold 3 IBS: 0.19259186402255285
Fold 4 IBS: 0.21338933172129262
Fold 5 IBS: 0.21568498079724013
[I 2024-04-14 01:03:08,469] Trial 11 finished with value: 0.20733999935656305 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.16481288780890282
Fold 2 IBS: 0.2210169243096472
Fold 3 IBS: 0.1621024154551832
Fold 4 IBS: 0.1533029510139564
Fold 5 IBS: 0.23439416692917028
[I 2024-04-14 01:03:22,142] Trial 12 finished with value: 0.18712586910337198 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17402283336818236
Fold 2 IBS: 0.2087374728480146
Fold 3 IBS: 0.17174698691539156
Fold 4 IBS: 0.17261429502370135
Fold 5 IBS: 0.22300398757472922
[I 2024-04-14 01:03:35,772] Trial 13 finished with value: 0.19002511514600381 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.2139646814364898
Fold 2 IBS: 0.22074056096749928
Fold 3 IBS: 0.20501656315227804
Fold 4 IBS: 0.22494601314735585
Fold 5 IBS: 0.21705148409657263
[I 2024-04-14 01:03:46,474] Trial 14 finished with value: 0.21634386056003913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.18712586910337198.

Fold 1 IBS: 0.21400643269593325
Fold 2 IBS: 0.22111219981278188
Fold 3 IBS: 0.20502803908063474
Fold 4 IBS: 0.22484462106669664
Fold 5 IBS: 0.21822466700224044
[I 2024-04-14 01:03:53,224] Trial 15 finished with value: 0.21664319193165743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17764770478002706
Fold 2 IBS: 0.20867663392001196
Fold 3 IBS: 0.17428317770837892
Fold 4 IBS: 0.17942136638629663
Fold 5 IBS: 0.2202481090473258
[I 2024-04-14 01:04:06,340] Trial 16 finished with value: 0.19205539836840807 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1745416753225377
Fold 2 IBS: 0.21000021208635342
Fold 3 IBS: 0.16747801651861197
Fold 4 IBS: 0.1665050437548392
Fold 5 IBS: 0.2259884313484794
[I 2024-04-14 01:04:17,051] Trial 17 finished with value: 0.18890267580616435 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.18877375960277615
Fold 2 IBS: 0.2104175503296011
Fold 3 IBS: 0.17887147368827228
Fold 4 IBS: 0.20070265473963897
Fold 5 IBS: 0.21455512687410158
[I 2024-04-14 01:04:18,292] Trial 18 finished with value: 0.19866411304687803 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1693931134036931
Fold 2 IBS: 0.21423273576779828
Fold 3 IBS: 0.16523484371479388
Fold 4 IBS: 0.16359614521845625
Fold 5 IBS: 0.23143820702196424
[I 2024-04-14 01:04:21,814] Trial 19 finished with value: 0.18877900902534114 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17421547013270003
Fold 2 IBS: 0.2050823834385182
Fold 3 IBS: 0.17114430210298628
Fold 4 IBS: 0.17339485761183707
Fold 5 IBS: 0.22351478015249363
[I 2024-04-14 01:04:30,432] Trial 20 finished with value: 0.18947035868770704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17111493042801526
Fold 2 IBS: 0.2137721819185777
Fold 3 IBS: 0.16456471169620251
Fold 4 IBS: 0.16449227846347558
Fold 5 IBS: 0.22864796656377134
[I 2024-04-14 01:04:40,828] Trial 21 finished with value: 0.1885184138140085 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16532773770032788
Fold 2 IBS: 0.2186442284652855
Fold 3 IBS: 0.16460826885307955
Fold 4 IBS: 0.15506743410900792
Fold 5 IBS: 0.23319986958345387
[I 2024-04-14 01:04:49,893] Trial 22 finished with value: 0.18736950774223093 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8844026166095639, 'min_weight_fraction_leaf': 0.08688290860444149}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16301700829191232
Fold 2 IBS: 0.219030517452768
Fold 3 IBS: 0.1623853390492206
Fold 4 IBS: 0.1532916510108008
Fold 5 IBS: 0.23013904250092193
[I 2024-04-14 01:05:02,116] Trial 23 finished with value: 0.1855727116611247 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.882373739187446, 'min_weight_fraction_leaf': 0.012868164547398506}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16304988087529812
Fold 2 IBS: 0.22094207521693815
Fold 3 IBS: 0.161348064662482
Fold 4 IBS: 0.15096714326145844
Fold 5 IBS: 0.23463058158669606
[I 2024-04-14 01:05:14,647] Trial 24 finished with value: 0.18618754912057453 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8872409155608235, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1737150468913634
Fold 2 IBS: 0.2064240961037397
Fold 3 IBS: 0.17070043959096043
Fold 4 IBS: 0.17215340254727685
Fold 5 IBS: 0.22073392460374922
[I 2024-04-14 01:05:27,591] Trial 25 finished with value: 0.1887453819474179 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9949818354422626, 'min_weight_fraction_leaf': 0.04193971879336897}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17192147575817168
Fold 2 IBS: 0.2125807619877445
Fold 3 IBS: 0.1691262873841453
Fold 4 IBS: 0.16885171298035456
Fold 5 IBS: 0.2265576203614483
[I 2024-04-14 01:05:42,949] Trial 26 finished with value: 0.18980757169437287 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8751983869140558, 'min_weight_fraction_leaf': 0.14849424791584837}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16246717022558158
Fold 2 IBS: 0.22278551957594211
Fold 3 IBS: 0.15990422558540457
Fold 4 IBS: 0.1487070056469065
Fold 5 IBS: 0.23422547394882334
[I 2024-04-14 01:05:55,914] Trial 27 finished with value: 0.18561787899653162 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.027289624478908987}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1654696844792975
Fold 2 IBS: 0.2234990134256156
Fold 3 IBS: 0.15946196024021897
Fold 4 IBS: 0.14893349177557935
Fold 5 IBS: 0.2381082176321455
[I 2024-04-14 01:06:01,835] Trial 28 finished with value: 0.18709447351057137 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8312285602471605, 'min_weight_fraction_leaf': 0.04077685648220064}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17845647167398127
Fold 2 IBS: 0.2130730563466517
Fold 3 IBS: 0.1730128250957027
Fold 4 IBS: 0.1775098861437066
Fold 5 IBS: 0.22205252382699645
[I 2024-04-14 01:06:11,943] Trial 29 finished with value: 0.19282095261740773 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7271017134796036, 'min_weight_fraction_leaf': 0.1096845451205721}. Best is trial 23 with value: 0.1855727116611247.

Fold 1 IBS: 0.16792251267623906
Fold 2 IBS: 0.2174484716230587
Fold 3 IBS: 0.16273781989489802
Fold 4 IBS: 0.1558940391227505
Fold 5 IBS: 0.23222422254692077
[I 2024-04-14 01:06:24,719] Trial 30 finished with value: 0.18724541317277338 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7293028765390641, 'min_weight_fraction_leaf': 0.08037045697723012}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16646920043412164
Fold 2 IBS: 0.22144555868438975
Fold 3 IBS: 0.1612585234507463
Fold 4 IBS: 0.15276461377317607
Fold 5 IBS: 0.23760424924495455
[I 2024-04-14 01:06:30,889] Trial 31 finished with value: 0.18790842911747765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8386292091834852, 'min_weight_fraction_leaf': 0.04730132529579094}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16030007033105986
Fold 2 IBS: 0.22398118562940655
Fold 3 IBS: 0.15846297307347587
Fold 4 IBS: 0.1470891139577854
Fold 5 IBS: 0.23657286223224763
[I 2024-04-14 01:06:36,926] Trial 32 finished with value: 0.18528124104479504 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9163496831204196, 'min_weight_fraction_leaf': 0.030126739530685447}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.172937674157177
Fold 2 IBS: 0.24427201483908298
Fold 3 IBS: 0.15582695988286352
Fold 4 IBS: 0.14290514986885272
Fold 5 IBS: 0.24818545842857834
[I 2024-04-14 01:06:41,642] Trial 33 finished with value: 0.1928254514353109 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9201437866465091, 'min_weight_fraction_leaf': 0.07060844824971078}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16533026201292797
Fold 2 IBS: 0.22263639369462013
Fold 3 IBS: 0.16342873596728688
Fold 4 IBS: 0.16226909673388507
Fold 5 IBS: 0.22835592740970792
[I 2024-04-14 01:06:45,331] Trial 34 finished with value: 0.18840408316368557 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.023639916096884216}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1768239075644783
Fold 2 IBS: 0.2081027487281694
Fold 3 IBS: 0.17413951134311367
Fold 4 IBS: 0.17907108232142022
Fold 5 IBS: 0.2215257917188389
[I 2024-04-14 01:06:59,519] Trial 35 finished with value: 0.1919326083352041 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8401348549146568, 'min_weight_fraction_leaf': 0.24235302278015497}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1940843114270721
Fold 2 IBS: 0.2056845420523829
Fold 3 IBS: 0.18788157295828922
Fold 4 IBS: 0.20006428856720795
Fold 5 IBS: 0.2177170857082032
[I 2024-04-14 01:07:05,687] Trial 36 finished with value: 0.20108636014263107 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6624062812925291, 'min_weight_fraction_leaf': 0.1276665161224413}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17340674788508836
Fold 2 IBS: 0.24768190748122734
Fold 3 IBS: 0.16867891640678653
Fold 4 IBS: 0.1616763611285437
Fold 5 IBS: 0.23877880170969434
[I 2024-04-14 01:07:14,102] Trial 37 finished with value: 0.19804454692226806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7790217874657425, 'min_weight_fraction_leaf': 0.062396376437804296}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16624738684053258
Fold 2 IBS: 0.21973229478344297
Fold 3 IBS: 0.16383689986898148
Fold 4 IBS: 0.1555626613940214
Fold 5 IBS: 0.23337565279263775
[I 2024-04-14 01:07:27,426] Trial 38 finished with value: 0.18775097913592323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9337822506368412, 'min_weight_fraction_leaf': 0.09676916841079641}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.19406740130079023
Fold 2 IBS: 0.2080998067364733
Fold 3 IBS: 0.18690687392991395
Fold 4 IBS: 0.1983924325024786
Fold 5 IBS: 0.21669307860788134
[I 2024-04-14 01:07:38,255] Trial 39 finished with value: 0.20083191861550748 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8439046690156142, 'min_weight_fraction_leaf': 0.1681587492068492}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1754231584570973
Fold 2 IBS: 0.20862733191088295
Fold 3 IBS: 0.17201575641485803
Fold 4 IBS: 0.17247754688839995
Fold 5 IBS: 0.22441791937181546
[I 2024-04-14 01:07:42,983] Trial 40 finished with value: 0.19059234260861074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 166, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.05363435608897611}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16687091698705347
Fold 2 IBS: 0.22145067973996654
Fold 3 IBS: 0.16083193542269436
Fold 4 IBS: 0.15145269120336982
Fold 5 IBS: 0.23763053320077898
[I 2024-04-14 01:07:48,906] Trial 41 finished with value: 0.18764735131077265 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8160068596533434, 'min_weight_fraction_leaf': 0.051128939929752766}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16440787739420146
Fold 2 IBS: 0.22051774173279667
Fold 3 IBS: 0.15866302088929105
Fold 4 IBS: 0.1505697309482162
Fold 5 IBS: 0.2344294950935966
[I 2024-04-14 01:07:54,015] Trial 42 finished with value: 0.18571757321162038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8502001595263011, 'min_weight_fraction_leaf': 0.025832096901499825}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.166093032959539
Fold 2 IBS: 0.22071181466302323
Fold 3 IBS: 0.16315038997597892
Fold 4 IBS: 0.1615108085837709
Fold 5 IBS: 0.22986943061414675
[I 2024-04-14 01:07:56,877] Trial 43 finished with value: 0.18826709535929176 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7462221833323165, 'min_weight_fraction_leaf': 0.019530073851423135}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17856291254676518
Fold 2 IBS: 0.20622912686970393
Fold 3 IBS: 0.1728547352397574
Fold 4 IBS: 0.17474142784909633
Fold 5 IBS: 0.22146523571485058
[I 2024-04-14 01:08:01,905] Trial 44 finished with value: 0.19077068764403465 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 183, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9478697073891121, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 32 with value: 0.18528124104479504.

Fold 1 IBS: 0.16512803721910052
Fold 2 IBS: 0.21893230349393553
Fold 3 IBS: 0.1593836385256823
Fold 4 IBS: 0.15058205502042205
Fold 5 IBS: 0.23336241815587846
[I 2024-04-14 01:08:09,628] Trial 45 finished with value: 0.18547769048300378 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6931500413934508, 'min_weight_fraction_leaf': 0.021457257714753555}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1659546836323674
Fold 2 IBS: 0.2153197227930472
Fold 3 IBS: 0.16360867863772716
Fold 4 IBS: 0.15557836846786757
Fold 5 IBS: 0.233640633124344
[I 2024-04-14 01:08:17,773] Trial 46 finished with value: 0.18682041733107066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7831947572035725, 'min_weight_fraction_leaf': 0.01931405227872043}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.2065277829489426
Fold 2 IBS: 0.216421790160963
Fold 3 IBS: 0.1977088009136629
Fold 4 IBS: 0.21668719017242724
Fold 5 IBS: 0.21616573903460984
[I 2024-04-14 01:08:24,256] Trial 47 finished with value: 0.21070226064612113 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 239, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6100992136402282, 'min_weight_fraction_leaf': 0.2926129328054348}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16819818157316316
Fold 2 IBS: 0.21738390622648787
Fold 3 IBS: 0.16156044111171175
Fold 4 IBS: 0.15316407589462896
Fold 5 IBS: 0.24011367020312108
[I 2024-04-14 01:08:29,936] Trial 48 finished with value: 0.18808405500182257 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 123, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6791860734720297, 'min_weight_fraction_leaf': 0.003213779418364194}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17209598869991036
Fold 2 IBS: 0.21187077120599623
Fold 3 IBS: 0.16727613640288252
Fold 4 IBS: 0.16695787846814034
Fold 5 IBS: 0.2272726675718586
[I 2024-04-14 01:08:33,742] Trial 49 finished with value: 0.1890946884697576 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8621088667656548, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.18268255673834424
Fold 2 IBS: 0.2116406133958206
Fold 3 IBS: 0.17317749084487088
Fold 4 IBS: 0.18115159425862645
Fold 5 IBS: 0.21966339609454685
[I 2024-04-14 01:08:36,678] Trial 50 finished with value: 0.19366313026644183 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 90, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.07395605063366822}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16168497854927735
Fold 2 IBS: 0.22270197197696373
Fold 3 IBS: 0.15969319515722263
Fold 4 IBS: 0.14836469505004918
Fold 5 IBS: 0.23398522053840312
[I 2024-04-14 01:08:49,096] Trial 51 finished with value: 0.18528601225438318 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9098861737626865, 'min_weight_fraction_leaf': 0.03317554027209381}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16283944924818344
Fold 2 IBS: 0.2217235758500272
Fold 3 IBS: 0.15875960819361015
Fold 4 IBS: 0.1480062250468594
Fold 5 IBS: 0.23242571799847053
[I 2024-04-14 01:09:02,381] Trial 52 finished with value: 0.18475091526743012 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6920435785662685, 'min_weight_fraction_leaf': 0.023623022439616993}. Best is trial 52 with value: 0.18475091526743012.
Fold 1 IBS: 0.16156116277380467
Fold 2 IBS: 0.21645044154721294
Fold 3 IBS: 0.15680725082067987
Fold 4 IBS: 0.1463271703292176
Fold 5 IBS: 0.23173369241683808
[I 2024-04-14 01:09:15,824] Trial 53 finished with value: 0.18257594357755064 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16345657480280432
Fold 2 IBS: 0.21941864722007984
Fold 3 IBS: 0.1609004507368225
Fold 4 IBS: 0.15232912028765422
Fold 5 IBS: 0.2304650281766842
[I 2024-04-14 01:09:27,317] Trial 54 finished with value: 0.185313964244809 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6831651026874692, 'min_weight_fraction_leaf': 0.003203141018784241}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21398942294707132
Fold 2 IBS: 0.22147230949301053
Fold 3 IBS: 0.20481071402497053
Fold 4 IBS: 0.22464130383350117
Fold 5 IBS: 0.21857501052674366
[I 2024-04-14 01:09:39,518] Trial 55 finished with value: 0.21669775216505943 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6865690783108706, 'min_weight_fraction_leaf': 0.38949341979712204}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21399089065449398
Fold 2 IBS: 0.2214447680813218
Fold 3 IBS: 0.20479456577543795
Fold 4 IBS: 0.22461278604587448
Fold 5 IBS: 0.21855736344590462
[I 2024-04-14 01:09:51,386] Trial 56 finished with value: 0.21668007480060658 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.602520835973954, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17871648336439458
Fold 2 IBS: 0.20746679738869533
Fold 3 IBS: 0.17495717299824248
Fold 4 IBS: 0.1821696732464211
Fold 5 IBS: 0.22029130965865304
[I 2024-04-14 01:10:02,487] Trial 57 finished with value: 0.19272028733128133 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6950911045016969, 'min_weight_fraction_leaf': 0.06162344008829474}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17152567449091236
Fold 2 IBS: 0.2132707954363787
Fold 3 IBS: 0.16577002064558846
Fold 4 IBS: 0.16352941407058058
Fold 5 IBS: 0.2293168915362626
[I 2024-04-14 01:10:13,150] Trial 58 finished with value: 0.18868255923594454 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6159821240459256, 'min_weight_fraction_leaf': 0.08195171278424525}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17647106232629753
Fold 2 IBS: 0.20824417376602933
Fold 3 IBS: 0.1723553183748716
Fold 4 IBS: 0.1736062035933313
Fold 5 IBS: 0.22224901748255857
[I 2024-04-14 01:10:26,198] Trial 59 finished with value: 0.19058515510861768 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.525386145731032, 'min_weight_fraction_leaf': 0.000152340144876216}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.17342492293804432
Fold 2 IBS: 0.2110732537830341
Fold 3 IBS: 0.16831819527481992
Fold 4 IBS: 0.16873369129336893
Fold 5 IBS: 0.22655614890084055
[I 2024-04-14 01:10:37,507] Trial 60 finished with value: 0.18962124243802156 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5735294094022945, 'min_weight_fraction_leaf': 0.10077092974890593}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16275315104094723
Fold 2 IBS: 0.22028966274589679
Fold 3 IBS: 0.16253743592400494
Fold 4 IBS: 0.15352895984062664
Fold 5 IBS: 0.23021227496706434
[I 2024-04-14 01:10:48,256] Trial 61 finished with value: 0.18586429690370798 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7582468632632998, 'min_weight_fraction_leaf': 0.014165988553227182}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16187634732795245
Fold 2 IBS: 0.21936803684113038
Fold 3 IBS: 0.1608633743218315
Fold 4 IBS: 0.15050003762977443
Fold 5 IBS: 0.23315135185396704
[I 2024-04-14 01:11:00,175] Trial 62 finished with value: 0.18515182959493115 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9688682344495251, 'min_weight_fraction_leaf': 0.03803430028119831}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16803000111589547
Fold 2 IBS: 0.21883335722590105
Fold 3 IBS: 0.16153399726646753
Fold 4 IBS: 0.15499454989097905
Fold 5 IBS: 0.23015675492479587
[I 2024-04-14 01:11:12,385] Trial 63 finished with value: 0.18670973208480782 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4289211196547223, 'min_weight_fraction_leaf': 0.03483517796766671}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16353133471191258
Fold 2 IBS: 0.22078931633305934
Fold 3 IBS: 0.16232987702451745
Fold 4 IBS: 0.1497770751049068
Fold 5 IBS: 0.23519973886423967
[I 2024-04-14 01:11:25,580] Trial 64 finished with value: 0.18632546840772718 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9928124170835537, 'min_weight_fraction_leaf': 0.0546315910617156}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16705858086425657
Fold 2 IBS: 0.21688710748739626
Fold 3 IBS: 0.16302480802361138
Fold 4 IBS: 0.16043857461543376
Fold 5 IBS: 0.22735018728687206
[I 2024-04-14 01:11:34,810] Trial 65 finished with value: 0.186951851655514 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.700753371069358, 'min_weight_fraction_leaf': 0.034080382470936726}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.2139764009793113
Fold 2 IBS: 0.22128743928758063
Fold 3 IBS: 0.20478422039927321
Fold 4 IBS: 0.22461901938020365
Fold 5 IBS: 0.21866318582772845
[I 2024-04-14 01:11:45,790] Trial 66 finished with value: 0.21666605317481946 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17803507005686864
Fold 2 IBS: 0.20584595762292543
Fold 3 IBS: 0.17289828813524646
Fold 4 IBS: 0.177343485740087
Fold 5 IBS: 0.22038680074032185
[I 2024-04-14 01:11:58,357] Trial 67 finished with value: 0.19090192045908988 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8083420047439778, 'min_weight_fraction_leaf': 0.0005690362936050055}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18517903096649513
Fold 2 IBS: 0.2068570229240262
Fold 3 IBS: 0.1787293688926839
Fold 4 IBS: 0.18812296323512723
Fold 5 IBS: 0.2160660198664728
[I 2024-04-14 01:12:09,966] Trial 68 finished with value: 0.19499088117696103 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.06709563455447608}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18645916216015707
Fold 2 IBS: 0.20636548084294315
Fold 3 IBS: 0.17885851202915032
Fold 4 IBS: 0.18718410387690065
Fold 5 IBS: 0.21792963761071232
[I 2024-04-14 01:12:20,925] Trial 69 finished with value: 0.19535937930397268 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9134125139788976, 'min_weight_fraction_leaf': 0.09022342402306419}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1757749566349244
Fold 2 IBS: 0.2608203853544215
Fold 3 IBS: 0.1687965292943309
Fold 4 IBS: 0.16154593350334548
Fold 5 IBS: 0.2409053655581546
[I 2024-04-14 01:12:30,935] Trial 70 finished with value: 0.20156863406903539 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9558804805474729, 'min_weight_fraction_leaf': 0.038804497461907755}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1641556888310035
Fold 2 IBS: 0.21756591667129618
Fold 3 IBS: 0.16214425980311192
Fold 4 IBS: 0.1527006421467362
Fold 5 IBS: 0.23008748551996394
[I 2024-04-14 01:12:42,344] Trial 71 finished with value: 0.18533079859442234 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6369371661585259, 'min_weight_fraction_leaf': 0.01592906514292467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16591246996228284
Fold 2 IBS: 0.2157266700943674
Fold 3 IBS: 0.1639704528415932
Fold 4 IBS: 0.15917069749386206
Fold 5 IBS: 0.22728835985586845
[I 2024-04-14 01:12:53,372] Trial 72 finished with value: 0.18641373004959477 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6355486112323981, 'min_weight_fraction_leaf': 0.016225042494993316}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16466547332455966
Fold 2 IBS: 0.21692658302629209
Fold 3 IBS: 0.1589302212774401
Fold 4 IBS: 0.14980038348586724
Fold 5 IBS: 0.23137411159828591
[I 2024-04-14 01:13:05,459] Trial 73 finished with value: 0.184339354542489 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5876918007096606, 'min_weight_fraction_leaf': 0.01373372285606849}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16792178126681906
Fold 2 IBS: 0.21606101236454162
Fold 3 IBS: 0.16289143446225338
Fold 4 IBS: 0.15694953508014142
Fold 5 IBS: 0.2316203069237443
[I 2024-04-14 01:13:17,479] Trial 74 finished with value: 0.18708881401949995 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5762811196680634, 'min_weight_fraction_leaf': 0.04721403021162478}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.16278536069617075
Fold 2 IBS: 0.22061911570320727
Fold 3 IBS: 0.15948095174532076
Fold 4 IBS: 0.1500453215492157
Fold 5 IBS: 0.23108140998200039
[I 2024-04-14 01:13:29,443] Trial 75 finished with value: 0.18480243193518295 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6487943567829829, 'min_weight_fraction_leaf': 0.011079149496446542}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1649931201311961
Fold 2 IBS: 0.2191098546301487
Fold 3 IBS: 0.1604180424655896
Fold 4 IBS: 0.15133070246635846
Fold 5 IBS: 0.23270813963892614
[I 2024-04-14 01:13:46,589] Trial 76 finished with value: 0.18571197186644378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 496, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6611270444897925, 'min_weight_fraction_leaf': 0.03472791790328323}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17454705567490922
Fold 2 IBS: 0.20946654124798095
Fold 3 IBS: 0.17107052561345987
Fold 4 IBS: 0.17205506925206807
Fold 5 IBS: 0.22301050367917757
[I 2024-04-14 01:13:58,284] Trial 77 finished with value: 0.19002993909351912 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5365605521283588, 'min_weight_fraction_leaf': 0.11295942956753599}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18204012108405643
Fold 2 IBS: 0.2063716852750058
Fold 3 IBS: 0.17875146851232082
Fold 4 IBS: 0.18921011660617745
Fold 5 IBS: 0.2162548711235392
[I 2024-04-14 01:14:09,132] Trial 78 finished with value: 0.19452565252021997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 427, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5917795612536799, 'min_weight_fraction_leaf': 0.2198684675175928}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17845532120437899
Fold 2 IBS: 0.20772503338895465
Fold 3 IBS: 0.17421627745462215
Fold 4 IBS: 0.18019949439245914
Fold 5 IBS: 0.22083458875793646
[I 2024-04-14 01:14:21,751] Trial 79 finished with value: 0.19228614303967032 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.49597522186369347, 'min_weight_fraction_leaf': 0.06112532202305438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16158996672320755
Fold 2 IBS: 0.21729610032334276
Fold 3 IBS: 0.157796999636179
Fold 4 IBS: 0.1472728675908385
Fold 5 IBS: 0.23183976837586612
[I 2024-04-14 01:14:32,565] Trial 80 finished with value: 0.18315914052988677 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6281972616252203, 'min_weight_fraction_leaf': 0.00848688046818526}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16157863775376022
Fold 2 IBS: 0.22087534780676452
Fold 3 IBS: 0.15999281456554124
Fold 4 IBS: 0.14853123619761843
Fold 5 IBS: 0.23150501980376892
[I 2024-04-14 01:14:42,814] Trial 81 finished with value: 0.18449661122549066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7386940991152582, 'min_weight_fraction_leaf': 0.01046274314610217}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16352260586628395
Fold 2 IBS: 0.22200502430399466
Fold 3 IBS: 0.15886916219783537
Fold 4 IBS: 0.14807572814886177
Fold 5 IBS: 0.2339085838911687
[I 2024-04-14 01:14:53,119] Trial 82 finished with value: 0.1852762208816289 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7162267948855195, 'min_weight_fraction_leaf': 0.032010312646594104}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16546027653935427
Fold 2 IBS: 0.2211659942343032
Fold 3 IBS: 0.16100661860428056
Fold 4 IBS: 0.15097334931915155
Fold 5 IBS: 0.2358306721546786
[I 2024-04-14 01:15:03,414] Trial 83 finished with value: 0.18688738217035364 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7326293257583885, 'min_weight_fraction_leaf': 0.04562346387387325}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285220423552985
Fold 2 IBS: 0.2188473500308101
Fold 3 IBS: 0.1599688920049345
Fold 4 IBS: 0.14885881691304034
Fold 5 IBS: 0.23161635394463342
[I 2024-04-14 01:15:13,006] Trial 84 finished with value: 0.18442872342578964 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7090996631118544, 'min_weight_fraction_leaf': 0.011358284348193259}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285549245105505
Fold 2 IBS: 0.21942277067272614
Fold 3 IBS: 0.15946829525657427
Fold 4 IBS: 0.14838517247840774
Fold 5 IBS: 0.23122387168068076
[I 2024-04-14 01:15:22,755] Trial 85 finished with value: 0.1842711205078888 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7186868789202818, 'min_weight_fraction_leaf': 0.01496729486923688}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16128591165678588
Fold 2 IBS: 0.21980011323918688
Fold 3 IBS: 0.15937248726208542
Fold 4 IBS: 0.1486127266622536
Fold 5 IBS: 0.2323048878882266
[I 2024-04-14 01:15:32,693] Trial 86 finished with value: 0.18427522534170765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7543993526497688, 'min_weight_fraction_leaf': 0.013808236520630852}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16094110571393064
Fold 2 IBS: 0.21986993252478362
Fold 3 IBS: 0.1588596843743244
Fold 4 IBS: 0.14614051224869679
Fold 5 IBS: 0.23352782586558365
[I 2024-04-14 01:15:42,168] Trial 87 finished with value: 0.1838678121454638 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7599338110461693, 'min_weight_fraction_leaf': 0.01151287364248438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16095650535504896
Fold 2 IBS: 0.21964363350705826
Fold 3 IBS: 0.15886397081421852
Fold 4 IBS: 0.14614666331841772
Fold 5 IBS: 0.23313729954057164
[I 2024-04-14 01:15:54,254] Trial 88 finished with value: 0.183749614507063 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 360, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7606093640745762, 'min_weight_fraction_leaf': 0.010471830721284079}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16110829576026084
Fold 2 IBS: 0.21851253412110366
Fold 3 IBS: 0.15675512925824683
Fold 4 IBS: 0.14727139463073632
Fold 5 IBS: 0.23209620967854572
[I 2024-04-14 01:16:06,143] Trial 89 finished with value: 0.18314871268977867 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7587282239351308, 'min_weight_fraction_leaf': 0.008176941543787496}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.18162653052097805
Fold 2 IBS: 0.20612651784753333
Fold 3 IBS: 0.1771784733434652
Fold 4 IBS: 0.18941755917999278
Fold 5 IBS: 0.21614311489575638
[I 2024-04-14 01:16:18,367] Trial 90 finished with value: 0.19409843915754516 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7635642567316503, 'min_weight_fraction_leaf': 0.280081595660318}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16186089564069253
Fold 2 IBS: 0.21899259491528042
Fold 3 IBS: 0.15921485444738478
Fold 4 IBS: 0.148193042465612
Fold 5 IBS: 0.23190417972474658
[I 2024-04-14 01:16:29,136] Trial 91 finished with value: 0.18403311343874326 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.789178452265885, 'min_weight_fraction_leaf': 0.011545143067658635}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16265353400501528
Fold 2 IBS: 0.2175575638863236
Fold 3 IBS: 0.16133894389326223
Fold 4 IBS: 0.15458872962543557
Fold 5 IBS: 0.229228321655463
[I 2024-04-14 01:16:39,208] Trial 92 finished with value: 0.18507341861309995 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7985486683510279, 'min_weight_fraction_leaf': 0.007901199895383132}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1620791424844971
Fold 2 IBS: 0.21900011819041879
Fold 3 IBS: 0.15920401655120014
Fold 4 IBS: 0.14637781084518398
Fold 5 IBS: 0.23282788799260146
[I 2024-04-14 01:16:49,804] Trial 93 finished with value: 0.1838977952127803 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7705275977783406, 'min_weight_fraction_leaf': 0.013704505872889598}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1793411990654569
Fold 2 IBS: 0.20613622174736498
Fold 3 IBS: 0.17275187695258565
Fold 4 IBS: 0.17818980825839892
Fold 5 IBS: 0.22022859697507743
[I 2024-04-14 01:17:00,155] Trial 94 finished with value: 0.19132954059977678 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7755480125040337, 'min_weight_fraction_leaf': 0.05063148942960361}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1610317396130936
Fold 2 IBS: 0.2202627419888432
Fold 3 IBS: 0.15951569709008712
Fold 4 IBS: 0.1458873166232896
Fold 5 IBS: 0.23482464408960785
[I 2024-04-14 01:17:11,086] Trial 95 finished with value: 0.18430442788098428 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 350, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7576152916362451, 'min_weight_fraction_leaf': 0.023770792047509592}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17066297262534935
Fold 2 IBS: 0.22975974207949945
Fold 3 IBS: 0.1519444360637532
Fold 4 IBS: 0.13950104633987118
Fold 5 IBS: 0.2439409705061117
[I 2024-04-14 01:17:23,212] Trial 96 finished with value: 0.18716183352291696 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7560665367452727, 'min_weight_fraction_leaf': 0.02298285611760403}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18361848353136237
Fold 2 IBS: 0.2052929877088459
Fold 3 IBS: 0.17656731308943907
Fold 4 IBS: 0.18399483123099875
Fold 5 IBS: 0.21866940095388543
[I 2024-04-14 01:17:33,182] Trial 97 finished with value: 0.1936286033029063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7936215885628722, 'min_weight_fraction_leaf': 0.0702592146341984}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16102070948187022
Fold 2 IBS: 0.22255035648510013
Fold 3 IBS: 0.1611617777057763
Fold 4 IBS: 0.14597987975871002
Fold 5 IBS: 0.23595320519699498
[I 2024-04-14 01:17:43,876] Trial 98 finished with value: 0.18533318572569035 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.817957524711727, 'min_weight_fraction_leaf': 0.0008689368092096427}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16218129609850532
Fold 2 IBS: 0.21864999525446885
Fold 3 IBS: 0.1599823914541389
Fold 4 IBS: 0.14944190039573815
Fold 5 IBS: 0.23537346983323632
[I 2024-04-14 01:17:53,877] Trial 99 finished with value: 0.1851258106072175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7505423882418932, 'min_weight_fraction_leaf': 0.027516392549616332}. Best is trial 53 with value: 0.18257594357755064.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.18257594357755064], datetime_start=datetime.datetime(2024, 4, 14, 1, 9, 2, 389151), datetime_complete=datetime.datetime(2024, 4, 14, 1, 9, 15, 823366), params={'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=53, value=None)


* Best Score for IBS:
 0.18257594357755064

In [70]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [71]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.794
train_ibs:  0.183

#### Test

In [72]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [73]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=12, max_features=None, max_leaf_nodes=6,
                   max_samples=0.7030590704740037, min_samples_leaf=6,
                   min_samples_split=13,
                   min_weight_fraction_leaf=0.020016091327628317,
                   n_estimators=273, random_state=123, warm_start=True)

C-index score: 0.618

ExtraSurvivalTrees(max_depth=13, max_features='log2', max_leaf_nodes=6,
                   max_samples=0.7048480399273186, min_samples_leaf=1,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.0010291888027469595,
                   n_estimators=485, random_state=123, warm_start=True)

IBS: 0.215

In [74]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [75]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 01:17:57,990] A new study created in memory with name: no-name-d6190f60-8ddb-4976-aa0f-21f1c3ad88ee

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:18:50,827] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:19:17,961] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:19:44,259] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:20:24,464] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:20:41,602] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:20:45,830] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:21:27,120] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:21:39,016] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:21:40,395] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 01:23:25,879] Trial 9 finished with value: 0.7334874350516556 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:26:09,004] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:29:11,991] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:31:50,052] Trial 12 finished with value: 0.703856671925322 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:33:06,654] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:34:50,374] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:36:24,890] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:37:29,044] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:39:38,441] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:42:31,123] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:42:37,961] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:43:39,807] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:45:52,994] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 01:47:57,092] Trial 22 finished with value: 0.7242619704042982 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:49:37,413] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:51:05,895] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:52:00,591] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:53:56,845] Trial 26 finished with value: 0.5421550134138162 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:55:52,966] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:57:26,757] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:58:32,999] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:59:50,290] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 02:02:23,327] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:04:39,796] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:13:47,380] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:31:12,088] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:38:02,952] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:56:29,778] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:56:32,486] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:57:11,000] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:59:08,170] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:00:54,979] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 03:00:55,355] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:01:08,116] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:01:21,694] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:01:51,767] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:02:06,524] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:02:19,940] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:03:08,918] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:03:31,096] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:28,928] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:33,252] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:04:33,819] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:34,672] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:04:44,241] Trial 53 finished with value: 0.7035675756915192 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:52,725] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:54,735] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:20,301] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:29,049] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:45,254] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:09:48,993] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:34,735] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:38,872] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:10:59,722] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:11:02,887] Trial 63 finished with value: 0.7163384910196757 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:11:09,445] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:11:19,571] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:13:52,066] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:13:53,989] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:14:29,768] Trial 68 finished with value: 0.6328510949834479 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:14:32,612] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:16:29,518] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:16:30,135] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:16:31,179] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:16:57,381] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:16:58,356] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:06,601] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:18:09,647] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:18:12,638] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:20:45,460] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:21:04,598] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:21:51,684] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 03:21:52,200] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:21:52,911] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:21:54,723] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:24:41,105] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:24:42,038] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:24:45,866] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:24:48,975] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:24:52,544] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:27:18,824] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:27:34,280] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:27:35,788] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:27:37,318] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:27:37,955] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:27:40,117] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:27:43,656] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 03:27:52,529] Trial 96 finished with value: 0.7453020253507325 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:28:01,803] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:28:10,368] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7083333333333334
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 03:28:11,408] Trial 99 finished with value: 0.7038145684617871 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.

[I 2024-04-14 03:28:11,498] A new study created in memory with name: no-name-c4e36049-2f2a-4e92-96a6-3fa81049cdf8

* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7453020253507325], datetime_start=datetime.datetime(2024, 4, 14, 3, 27, 43, 663089), datetime_complete=datetime.datetime(2024, 4, 14, 3, 27, 52, 528033), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7453020253507325

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:29:17,383] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:29:55,749] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:30:30,447] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:31:20,795] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:31:41,924] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:31:46,861] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:32:36,079] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:32:50,264] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:32:52,166] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21302115522395498
Fold 2 IBS: 0.22130101345683229
Fold 3 IBS: 0.20356574496128135
Fold 4 IBS: 0.22373082985786685
Fold 5 IBS: 0.21796021556320513
[I 2024-04-14 03:35:03,948] Trial 9 finished with value: 0.21591579181262813 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 03:38:28,535] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 03:42:24,502] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21383968411387158
Fold 2 IBS: 0.22156451448592526
Fold 3 IBS: 0.20440536466519849
Fold 4 IBS: 0.22459255869133457
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 03:45:40,021] Trial 12 finished with value: 0.21650016968139757 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 03:47:12,395] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:49:57,227] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:52:18,731] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:53:39,328] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:56:48,632] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:58:29,974] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:58:50,457] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:02:01,113] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 04:05:13,548] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21275233971420443
Fold 2 IBS: 0.22141006773816166

Fold 3 IBS: 0.20334575604936503
Fold 4 IBS: 0.2231342747566171
Fold 5 IBS: 0.2179288192033457
[I 2024-04-14 04:08:54,936] Trial 22 finished with value: 0.21571425149233878 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:11:43,584] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:13:31,259] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:15:08,825] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:17:40,230] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:17:55,192] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:18:50,885] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:21:10,122] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:22:09,328] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 04:25:10,682] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.2214475600367709
Fold 3 IBS: 0.2035963921195872
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.2179179888442139
[I 2024-04-14 04:28:09,505] Trial 32 finished with value: 0.21590224301714384 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:30:39,628] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:32:59,908] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:33:31,700] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:36:31,727] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:36:37,038] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:38:05,730] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 04:39:54,427] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 04:41:46,015] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2133737249398968
Fold 2 IBS: 0.22149810300618933
Fold 3 IBS: 0.20392418223551953
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21807108026974395
[I 2024-04-14 04:44:35,979] Trial 41 finished with value: 0.21616497963246242 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21306226677867723
Fold 2 IBS: 0.22147749486211882
Fold 3 IBS: 0.20359544985689815
Fold 4 IBS: 0.22359166073512057
Fold 5 IBS: 0.21793202518042964
[I 2024-04-14 04:47:47,213] Trial 42 finished with value: 0.21593177948264888 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:51:15,609] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:53:34,127] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21378011659547358
Fold 2 IBS: 0.22145278135911364
Fold 3 IBS: 0.20436255304908924
Fold 4 IBS: 0.22448271516750193
Fold 5 IBS: 0.2180782304104917
[I 2024-04-14 04:55:47,002] Trial 45 finished with value: 0.21643127931633402 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:57:57,034] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 04:58:57,778] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:58:58,663] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:59:30,744] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:02:12,999] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 05:05:08,560] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:08:11,996] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22136281903923083
Fold 3 IBS: 0.2023927630992915
Fold 4 IBS: 0.2219411019366781
Fold 5 IBS: 0.21777624808878387
[I 2024-04-14 05:10:46,106] Trial 53 finished with value: 0.2150432178150902 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:13:08,984] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:15:13,008] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:17:14,854] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:20:01,456] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:23:22,820] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:25:28,687] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 05:27:12,868] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:29:48,309] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 05:32:52,870] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:35:56,237] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21315225506544797
Fold 2 IBS: 0.22120521782494593
Fold 3 IBS: 0.20370415696975244
Fold 4 IBS: 0.22392954297429343
Fold 5 IBS: 0.21800569131579653
[I 2024-04-14 05:39:19,109] Trial 64 finished with value: 0.21599937283004728 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:41:42,665] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8687566763675275, 'learning_rate': 0.010290863736545098, 'dropout_rate': 0.20090531278751475, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.35267930800388836, 'max_features': 'auto', 'min_impurity_decrease': 2.9695254103704335e-06, 'validation_fraction': 0.9981673914604385, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:42:04,215] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9104313304151431, 'learning_rate': 0.014815622348446418, 'dropout_rate': 0.1415896279444537, 'n_estimators': 149, 'criterion': 'squared_error', 'ccp_alpha': 0.7060910424624821, 'min_weight_fraction_leaf': 0.2796836959018326, 'max_features': 'auto', 'min_impurity_decrease': 5.127880425748818e-06, 'validation_fraction': 0.916501041728546, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:44:27,624] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.802369464636257, 'learning_rate': 0.00417552385002208, 'dropout_rate': 0.3370707390697732, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.22284347226729986, 'max_features': 'sqrt', 'min_impurity_decrease': 7.319926345244562e-07, 'validation_fraction': 0.8373361504171383, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:47:26,985] Trial 68 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9271983184882995, 'learning_rate': 0.026761786505961737, 'dropout_rate': 0.23198968531289843, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.3246047057302614, 'max_features': 'auto', 'min_impurity_decrease': 2.8105707733985375e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:49:43,384] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9669065339055751, 'learning_rate': 0.010765506871731714, 'dropout_rate': 0.30527953045505896, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.8784198437522095, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:51:02,362] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.041826568167709126, 'dropout_rate': 0.5905404972480945, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.3744309428528772, 'max_features': None, 'min_impurity_decrease': 1.5635679037041744e-07, 'validation_fraction': 0.9186076475421031, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21310093398309657
Fold 2 IBS: 0.22107852954082238
Fold 3 IBS: 0.20363684344049715
Fold 4 IBS: 0.2235062321376155
Fold 5 IBS: 0.2179952952989321
[I 2024-04-14 05:54:23,413] Trial 71 finished with value: 0.21586356688019276 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.008268552307118088, 'dropout_rate': 0.18133086892644865, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.1936286226601749, 'max_features': 'log2', 'min_impurity_decrease': 9.627538760330365e-07, 'validation_fraction': 0.9695063743987746, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.2124258387603463
Fold 2 IBS: 0.22057958449066262
Fold 3 IBS: 0.20279757841484652
Fold 4 IBS: 0.222180058336135
Fold 5 IBS: 0.21771098701395403
[I 2024-04-14 05:57:48,135] Trial 72 finished with value: 0.21513880940318889 and parameters: {'subsample': 0.9765713621264592, 'learning_rate': 0.00878714781905863, 'dropout_rate': 0.12511582109542432, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.1603532575763104, 'max_features': 'log2', 'min_impurity_decrease': 4.6121007580567444e-07, 'validation_fraction': 0.9726077921006634, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 06:01:04,113] Trial 73 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9999531614476969, 'learning_rate': 0.017515788008347112, 'dropout_rate': 0.12067593932125548, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.1608125340894365, 'max_features': 'log2', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9762008597583516, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:04:21,598] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9378736061625563, 'learning_rate': 0.00962248608121305, 'dropout_rate': 0.17315149200510316, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.11427286298314121, 'max_features': 'log2', 'min_impurity_decrease': 7.393622885050152e-07, 'validation_fraction': 0.9760588067950509, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:07:07,883] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8548930681972974, 'learning_rate': 0.05554512018944124, 'dropout_rate': 0.14951765413144097, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.3275069627126754, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 'log2', 'min_impurity_decrease': 1.0058881333640878e-06, 'validation_fraction': 0.9013416300485078, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 06:10:17,081] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9721782395774373, 'learning_rate': 0.003194443723182592, 'dropout_rate': 0.12011548645109148, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.9325305665153546, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:13:24,838] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8921532985730489, 'learning_rate': 0.021931279910218017, 'dropout_rate': 0.19284931428290142, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.5905545096948588, 'min_weight_fraction_leaf': 0.07057220045251793, 'max_features': 'log2', 'min_impurity_decrease': 1.637559261311236e-05, 'validation_fraction': 0.8150762480319586, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 06:15:59,551] Trial 78 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.25883194688905886, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.9915392376256854, 'min_weight_fraction_leaf': 0.18968885272282524, 'max_features': 'log2', 'min_impurity_decrease': 3.9150597642462115e-06, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 06:18:16,469] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.01335084153769065, 'dropout_rate': 0.10072101837872541, 'n_estimators': 393, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28871198232416817, 'min_weight_fraction_leaf': 0.17483536292771176, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982218331650979, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:19:34,412] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.977148848015456, 'learning_rate': 0.004307663599041434, 'dropout_rate': 0.15920080431792163, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 1, 'min_impurity_decrease': 1.424247746508587e-06, 'validation_fraction': 0.8670066304726413, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21299867857890398
Fold 2 IBS: 0.2214477278201705
Fold 3 IBS: 0.20356620117857893
Fold 4 IBS: 0.22350168421901248
Fold 5 IBS: 0.21792379994243102
[I 2024-04-14 06:22:36,472] Trial 81 finished with value: 0.2158876183478194 and parameters: {'subsample': 0.9579178853393634, 'learning_rate': 0.007273589951884828, 'dropout_rate': 0.2054590932290375, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.02521700237735763, 'min_weight_fraction_leaf': 0.23721821844476393, 'max_features': 'auto', 'min_impurity_decrease': 2.628308399801263e-07, 'validation_fraction': 0.945876154428725, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21281996790006147
Fold 2 IBS: 0.22144914962179446
Fold 3 IBS: 0.2034201419570034
Fold 4 IBS: 0.22330541406123097
Fold 5 IBS: 0.21789799579435803
[I 2024-04-14 06:25:50,705] Trial 82 finished with value: 0.21577853386688967 and parameters: {'subsample': 0.9374850920793417, 'learning_rate': 0.009537962827339893, 'dropout_rate': 0.2311360143359113, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.01786403260693046, 'min_weight_fraction_leaf': 0.30128352038824946, 'max_features': 'auto', 'min_impurity_decrease': 2.672883759599648e-07, 'validation_fraction': 0.9419164447228301, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 06:28:57,640] Trial 83 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.008698584299413689, 'dropout_rate': 0.2878607631400676, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.42714757621714333, 'min_weight_fraction_leaf': 0.2701739605759479, 'max_features': 0.1, 'min_impurity_decrease': 4.793545557946714e-07, 'validation_fraction': 0.9339252824355873, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:31:57,079] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.016064279530571223, 'dropout_rate': 0.2326295808813899, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.7147702528804116, 'min_weight_fraction_leaf': 0.23638615893438736, 'max_features': 'auto', 'min_impurity_decrease': 3.019646046469693e-07, 'validation_fraction': 0.8979947940782089, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:34:27,114] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9376269876567488, 'learning_rate': 0.019091747704160993, 'dropout_rate': 0.20706945781506403, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.16619718561211044, 'min_weight_fraction_leaf': 0.15561996067062303, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9731668294064385, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:37:18,550] Trial 86 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8785484469699407, 'learning_rate': 0.012070502053282707, 'dropout_rate': 0.2505427438802027, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.1270526375680832, 'min_weight_fraction_leaf': 0.25781248698190756, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2713997001011194e-06, 'validation_fraction': 0.943859242495053, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:39:29,567] Trial 87 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9090955901211109, 'learning_rate': 0.006929208749359209, 'dropout_rate': 0.49308788025511585, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.32252019630070927, 'min_weight_fraction_leaf': 0.3051832272732572, 'max_features': 'log2', 'min_impurity_decrease': 7.049454515025671e-07, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:42:22,588] Trial 88 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9447987915285996, 'learning_rate': 0.014159070275535094, 'dropout_rate': 0.18102387516231752, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.5935000311483954, 'min_weight_fraction_leaf': 0.2151508441811604, 'max_features': 'auto', 'min_impurity_decrease': 3.72786238165322e-07, 'validation_fraction': 0.898328514849679, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21292314886383587
Fold 2 IBS: 0.2213935582997429
Fold 3 IBS: 0.20349492943164285
Fold 4 IBS: 0.2234443788901035
Fold 5 IBS: 0.2178743294294726
[I 2024-04-14 06:44:29,391] Trial 89 finished with value: 0.21582606898295956 and parameters: {'subsample': 0.9777744983689288, 'learning_rate': 0.01038357183462239, 'dropout_rate': 0.27697802684175754, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.019074305728520667, 'min_weight_fraction_leaf': 0.2917659918820059, 'max_features': 'auto', 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.855835665987138, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:45:12,042] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9728383671704387, 'learning_rate': 0.009918951595706415, 'dropout_rate': 0.8458602043820649, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.8331973858915148, 'min_weight_fraction_leaf': 0.2921200274675525, 'max_features': 'auto', 'min_impurity_decrease': 1.4263141271201017e-07, 'validation_fraction': 0.6746483744961582, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21336618881179586
Fold 2 IBS: 0.22114294232267198
Fold 3 IBS: 0.20384999569236736
Fold 4 IBS: 0.22375343637403386
Fold 5 IBS: 0.21796174726134912
[I 2024-04-14 06:47:07,722] Trial 91 finished with value: 0.21601486209244367 and parameters: {'subsample': 0.2845120808216636, 'learning_rate': 0.007013602341022412, 'dropout_rate': 0.2673714840258141, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.03785557112751456, 'min_weight_fraction_leaf': 0.28289624505615074, 'max_features': 'auto', 'min_impurity_decrease': 2.167221721970957e-07, 'validation_fraction': 0.8389190675336428, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:47:49,447] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.012214946715626797, 'dropout_rate': 0.21822342387423224, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.2716052866202, 'min_weight_fraction_leaf': 0.2516221825059295, 'max_features': 'auto', 'min_impurity_decrease': 5.164764561896499e-07, 'validation_fraction': 0.9118535684017283, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:49:47,303] Trial 93 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9215121808289675, 'learning_rate': 0.023968389847749173, 'dropout_rate': 0.3096195311954267, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.526845938693122, 'min_weight_fraction_leaf': 0.23408949316338243, 'max_features': 'auto', 'min_impurity_decrease': 3.3639036073651944e-07, 'validation_fraction': 0.9394031242668214, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:51:11,164] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9794737431495151, 'learning_rate': 0.002207391632430766, 'dropout_rate': 0.355864908714743, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.25602285176947265, 'min_weight_fraction_leaf': 0.1982598024964269, 'max_features': 'auto', 'min_impurity_decrease': 7.85301346539494e-07, 'validation_fraction': 0.8716461599738365, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:52:39,045] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8243603473818633, 'learning_rate': 0.016754070407166113, 'dropout_rate': 0.18244406164714, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.969239817362121, 'min_weight_fraction_leaf': 0.27320139306393876, 'max_features': None, 'min_impurity_decrease': 1.4323978100998562e-07, 'validation_fraction': 0.7967240220364479, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:54:39,642] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9567077577297926, 'learning_rate': 0.009321682904042736, 'dropout_rate': 0.24495589575382673, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 5.08611115752829, 'min_weight_fraction_leaf': 0.30649414543812215, 'max_features': 'auto', 'min_impurity_decrease': 1.2053286940776505e-06, 'validation_fraction': 0.7556909999934059, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:56:38,221] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8987436119584659, 'learning_rate': 0.0203626546956988, 'dropout_rate': 0.12954890528084062, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 1.5784834259170004, 'min_weight_fraction_leaf': 0.2550731647118252, 'max_features': 'auto', 'min_impurity_decrease': 1.890730180714205e-06, 'validation_fraction': 0.9772741387306807, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:58:08,955] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9426449416232375, 'learning_rate': 0.005258427870498378, 'dropout_rate': 0.29094318599258845, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.5297744472721807, 'min_weight_fraction_leaf': 0.2938783217761457, 'max_features': 1, 'min_impurity_decrease': 2.1824147145190313e-07, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21192565389705484
Fold 2 IBS: 0.22123776935159062

Fold 3 IBS: 0.20237857642828805
Fold 4 IBS: 0.22105646622231043
Fold 5 IBS: 0.21749535106188492
[I 2024-04-14 06:59:30,909] Trial 99 finished with value: 0.21481876339222578 and parameters: {'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 99 with value: 0.21481876339222578.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.21481876339222578], datetime_start=datetime.datetime(2024, 4, 14, 6, 58, 8, 973367), datetime_complete=datetime.datetime(2024, 4, 14, 6, 59, 30, 908215), params={'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for IBS:
 0.21481876339222578

In [76]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [77]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.745
train_ibs:  0.215

#### Test

In [78]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [79]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.603

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004422201299274769,
                                 criterion='squared_error',
                                 dropout_rate=0.2044520049398774,
                                 learning_rate=0.01377474153403631, max_depth=2,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=0.00015837847703956763,
                                 min_samples_leaf=13, min_samples_split=13,
                                 min_weight_fraction_leaf=0.13940114558509004,
                                 n_estimators=378, random_state=123,
                                 subsample=0.8569271041566342,
                                 validation_fraction=0.9580200141092102)

IBS: 0.22

In [80]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [81]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [82]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 06:59:48,298] A new study created in memory with name: no-name-51961c76-435c-4880-a528-143cf2823f41

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 06:59:50,224] Trial 0 finished with value: 0.7099982410993864 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.7099982410993864.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:00:02,535] Trial 1 finished with value: 0.6987518910706959 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.7099982410993864.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:00:04,950] Trial 2 finished with value: 0.7148731456066437 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7148731456066437.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:00:08,152] Trial 3 finished with value: 0.7197146276540082 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7197146276540082.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:00:12,977] Trial 4 finished with value: 0.7165602961390719 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.7197146276540082.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:00:18,677] Trial 5 finished with value: 0.7071907096360968 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.7197146276540082.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:00:21,370] Trial 6 finished with value: 0.6514945071044511 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.7197146276540082.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 07:00:21,933] Trial 7 finished with value: 0.7103040196207822 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 3 with value: 0.7197146276540082.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:00:24,971] Trial 8 finished with value: 0.715073680366002 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 3 with value: 0.7197146276540082.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:00:33,887] Trial 9 finished with value: 0.7123346302004813 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 3 with value: 0.7197146276540082.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:00:39,660] Trial 10 finished with value: 0.725297635505036 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.10867980814121556, 'n_estimators': 299, 'learning_rate': 0.09279671898160717}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:00:45,913] Trial 11 finished with value: 0.725297635505036 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.10580803679784617, 'n_estimators': 318, 'learning_rate': 0.09656492760401554}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:00:52,245] Trial 12 finished with value: 0.725297635505036 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.10707761209805167, 'n_estimators': 307, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:01:01,466] Trial 13 finished with value: 0.6945008724814421 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.20866416710667365, 'n_estimators': 377, 'learning_rate': 0.09915584389423529}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:01:09,726] Trial 14 finished with value: 0.6462473378141999 and parameters: {'subsample': 0.8619663815733164, 'dropout_rate': 0.28551472763591135, 'n_estimators': 363, 'learning_rate': 0.0025916531369806137}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 07:01:15,312] Trial 15 finished with value: 0.7262366026411862 and parameters: {'subsample': 0.8897480564271555, 'dropout_rate': 0.10006460023230275, 'n_estimators': 297, 'learning_rate': 0.08616677729964022}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:01:23,776] Trial 16 finished with value: 0.725746384146618 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.6816056386540454, 'n_estimators': 427, 'learning_rate': 0.08537615252975696}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:01:32,332] Trial 17 finished with value: 0.7173241035826639 and parameters: {'subsample': 0.17085174271948028, 'dropout_rate': 0.7574099126710454, 'n_estimators': 445, 'learning_rate': 0.08254853879823357}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:01:40,789] Trial 18 finished with value: 0.7146794965737474 and parameters: {'subsample': 0.2887829809667767, 'dropout_rate': 0.639771880482936, 'n_estimators': 430, 'learning_rate': 0.08277082740859594}. Best is trial 15 with value: 0.7262366026411862.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:01:46,968] Trial 19 finished with value: 0.7248730330152127 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9824925186694111, 'n_estimators': 400, 'learning_rate': 0.08685281684248895}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:01:50,582] Trial 20 finished with value: 0.7118300653783937 and parameters: {'subsample': 0.6343904688286152, 'dropout_rate': 0.7356300508281354, 'n_estimators': 258, 'learning_rate': 0.06551866052750378}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 07:01:57,483] Trial 21 finished with value: 0.712170835489255 and parameters: {'subsample': 0.869806843283716, 'dropout_rate': 0.21757574506034924, 'n_estimators': 305, 'learning_rate': 0.08800925744236729}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:02:04,589] Trial 22 finished with value: 0.7016930675412841 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.34432223409149726, 'n_estimators': 333, 'learning_rate': 0.07823625392212552}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:02:08,888] Trial 23 finished with value: 0.6342407169840496 and parameters: {'subsample': 0.9078014509774237, 'dropout_rate': 0.5370811404622287, 'n_estimators': 268, 'learning_rate': 0.09154831230637053}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:02:10,142] Trial 24 finished with value: 0.7128248262789126 and parameters: {'subsample': 0.6152663598595403, 'dropout_rate': 0.6537883290687992, 'n_estimators': 113, 'learning_rate': 0.07884375100099514}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:02:17,678] Trial 25 finished with value: 0.7099872123601056 and parameters: {'subsample': 0.4165440487204827, 'dropout_rate': 0.800590426896782, 'n_estimators': 417, 'learning_rate': 0.08913327305618396}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:02:21,682] Trial 26 finished with value: 0.7186052754624274 and parameters: {'subsample': 0.9210183375199745, 'dropout_rate': 0.17611470566601473, 'n_estimators': 243, 'learning_rate': 0.09929045093351788}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:02:21,899] Trial 27 finished with value: 0.63080934443503 and parameters: {'subsample': 0.8024452866861593, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.06071884280131438}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:02:23,633] Trial 28 finished with value: 0.6482081221279253 and parameters: {'subsample': 0.8110916401621946, 'dropout_rate': 0.419579278974342, 'n_estimators': 140, 'learning_rate': 0.044133858477801706}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:02:29,652] Trial 29 finished with value: 0.713892753449781 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.5869232734483284, 'n_estimators': 342, 'learning_rate': 0.07259811244248336}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:02:37,389] Trial 30 finished with value: 0.7119590254131118 and parameters: {'subsample': 0.6894188070141365, 'dropout_rate': 0.3577780272974884, 'n_estimators': 389, 'learning_rate': 0.09090172962730646}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:02:42,994] Trial 31 finished with value: 0.7234658112260286 and parameters: {'subsample': 0.9488701920274671, 'dropout_rate': 0.13781548445050457, 'n_estimators': 302, 'learning_rate': 0.0938689900802462}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:02:49,691] Trial 32 finished with value: 0.725297635505036 and parameters: {'subsample': 0.9482652891529738, 'dropout_rate': 0.10723492426029196, 'n_estimators': 331, 'learning_rate': 0.0833858653478739}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 07:02:53,545] Trial 33 finished with value: 0.712170835489255 and parameters: {'subsample': 0.7905795055488652, 'dropout_rate': 0.23483519890892354, 'n_estimators': 231, 'learning_rate': 0.09967352441907372}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5845070422535211
[I 2024-04-14 07:03:06,610] Trial 34 finished with value: 0.6916839710729914 and parameters: {'subsample': 0.9947385378234598, 'dropout_rate': 0.18115724294675206, 'n_estimators': 469, 'learning_rate': 0.07679917891658777}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:03:11,781] Trial 35 finished with value: 0.7196270926400026 and parameters: {'subsample': 0.8827826965859974, 'dropout_rate': 0.15171728965725764, 'n_estimators': 284, 'learning_rate': 0.09227806853696889}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:03:18,257] Trial 36 finished with value: 0.7137176834217698 and parameters: {'subsample': 0.7278936486503054, 'dropout_rate': 0.25308398062182663, 'n_estimators': 342, 'learning_rate': 0.07254420167756077}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:03:22,948] Trial 37 finished with value: 0.7105458000717588 and parameters: {'subsample': 0.2489626118965838, 'dropout_rate': 0.47096246897520044, 'n_estimators': 280, 'learning_rate': 0.0668430324478756}. Best is trial 15 with value: 0.7262366026411862.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:03:36,005] Trial 38 finished with value: 0.7271438285276995 and parameters: {'subsample': 0.8218636584157292, 'dropout_rate': 0.11312344832158804, 'n_estimators': 493, 'learning_rate': 0.08480737929792241}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:03:47,911] Trial 39 finished with value: 0.7014304624992673 and parameters: {'subsample': 0.7648933719827579, 'dropout_rate': 0.3117090493722728, 'n_estimators': 484, 'learning_rate': 0.06141565109530998}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:03:57,763] Trial 40 finished with value: 0.6462473378141999 and parameters: {'subsample': 0.8357936727249557, 'dropout_rate': 0.7207286574542481, 'n_estimators': 448, 'learning_rate': 0.0862455307648111}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:04:11,907] Trial 41 finished with value: 0.7243586683688858 and parameters: {'subsample': 0.9382593832299208, 'dropout_rate': 0.101981583779215, 'n_estimators': 495, 'learning_rate': 0.09492674417021844}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:04:21,674] Trial 42 finished with value: 0.7159267040338559 and parameters: {'subsample': 0.948038453424712, 'dropout_rate': 0.1742713405209531, 'n_estimators': 420, 'learning_rate': 0.08048028923988232}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:04:24,606] Trial 43 finished with value: 0.7186513854557204 and parameters: {'subsample': 0.9044278359623115, 'dropout_rate': 0.15177083462374474, 'n_estimators': 192, 'learning_rate': 0.07443779580352047}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:04:36,271] Trial 44 finished with value: 0.7152185782739489 and parameters: {'subsample': 0.3946040121687096, 'dropout_rate': 0.19730794332041796, 'n_estimators': 454, 'learning_rate': 0.0846983683712285}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:04:43,975] Trial 45 finished with value: 0.6391426777683633 and parameters: {'subsample': 0.9967173346372055, 'dropout_rate': 0.1042847283366114, 'n_estimators': 367, 'learning_rate': 0.02274904980797578}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 07:04:52,704] Trial 46 finished with value: 0.712056244198193 and parameters: {'subsample': 0.6829809398482648, 'dropout_rate': 0.25233626946817395, 'n_estimators': 400, 'learning_rate': 0.09603478013140934}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:04:56,655] Trial 47 finished with value: 0.6332603248271869 and parameters: {'subsample': 0.8503474976824501, 'dropout_rate': 0.5886912814732308, 'n_estimators': 214, 'learning_rate': 0.07117434704467443}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:05:02,569] Trial 48 finished with value: 0.63080934443503 and parameters: {'subsample': 0.9614279492208745, 'dropout_rate': 0.8389104570078317, 'n_estimators': 318, 'learning_rate': 0.05669244484673394}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:05:04,938] Trial 49 finished with value: 0.706164207485941 and parameters: {'subsample': 0.553248476164387, 'dropout_rate': 0.1304931000922671, 'n_estimators': 162, 'learning_rate': 0.00524351186486742}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:05:10,322] Trial 50 finished with value: 0.718716840575028 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.19934522152019857, 'n_estimators': 290, 'learning_rate': 0.08799304011242266}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:05:22,472] Trial 51 finished with value: 0.7234658112260286 and parameters: {'subsample': 0.9753117380889962, 'dropout_rate': 0.1330906779090382, 'n_estimators': 500, 'learning_rate': 0.09534149893073113}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:05:27,849] Trial 52 finished with value: 0.7243586683688858 and parameters: {'subsample': 0.9118458069517438, 'dropout_rate': 0.10420964526222254, 'n_estimators': 314, 'learning_rate': 0.09644756780714599}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:05:34,008] Trial 53 finished with value: 0.7044591739838612 and parameters: {'subsample': 0.8850293757480304, 'dropout_rate': 0.28507468513544487, 'n_estimators': 353, 'learning_rate': 0.08989908772307457}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 07:05:37,253] Trial 54 finished with value: 0.7152296966777765 and parameters: {'subsample': 0.45600415145964923, 'dropout_rate': 0.6963572258809141, 'n_estimators': 246, 'learning_rate': 0.08160837113132613}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:05:43,867] Trial 55 finished with value: 0.7237336207842511 and parameters: {'subsample': 0.19327954986268803, 'dropout_rate': 0.22568282690699498, 'n_estimators': 381, 'learning_rate': 0.08517626093941295}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:05:47,038] Trial 56 finished with value: 0.6987518910706959 and parameters: {'subsample': 0.821471413650482, 'dropout_rate': 0.5194091093440398, 'n_estimators': 265, 'learning_rate': 0.09256630856349378}. Best is trial 38 with value: 0.7271438285276995.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 07:05:49,826] Trial 57 finished with value: 0.7168148762041324 and parameters: {'subsample': 0.97656712322767, 'dropout_rate': 0.1680624778639973, 'n_estimators': 222, 'learning_rate': 0.09977909375387779}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:05:54,045] Trial 58 finished with value: 0.6332603248271869 and parameters: {'subsample': 0.9181476846040841, 'dropout_rate': 0.7689442998250557, 'n_estimators': 323, 'learning_rate': 0.07669505697201479}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:06:05,107] Trial 59 finished with value: 0.7234658112260286 and parameters: {'subsample': 0.7670148726639308, 'dropout_rate': 0.13208005737599937, 'n_estimators': 475, 'learning_rate': 0.08838291581372384}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:06:08,772] Trial 60 finished with value: 0.6332603248271869 and parameters: {'subsample': 0.8820233793254915, 'dropout_rate': 0.6121214744948075, 'n_estimators': 292, 'learning_rate': 0.035949420122523286}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:06:13,874] Trial 61 finished with value: 0.725297635505036 and parameters: {'subsample': 0.9502203520505428, 'dropout_rate': 0.11163073296617759, 'n_estimators': 328, 'learning_rate': 0.08273347075893082}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 07:06:19,207] Trial 62 finished with value: 0.6916378610796983 and parameters: {'subsample': 0.9950935067640093, 'dropout_rate': 0.21219849003304303, 'n_estimators': 347, 'learning_rate': 0.08434171595257935}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:06:23,758] Trial 63 finished with value: 0.7196270926400026 and parameters: {'subsample': 0.9341752779715827, 'dropout_rate': 0.15271577582548337, 'n_estimators': 303, 'learning_rate': 0.09652814002238395}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 07:06:31,632] Trial 64 finished with value: 0.7010617567745424 and parameters: {'subsample': 0.9609054658359324, 'dropout_rate': 0.18532182581950923, 'n_estimators': 433, 'learning_rate': 0.08054861030224268}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:06:35,414] Trial 65 finished with value: 0.7225268440898783 and parameters: {'subsample': 0.8958373098651384, 'dropout_rate': 0.13252132337966396, 'n_estimators': 268, 'learning_rate': 0.09139427319307745}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:06:41,101] Trial 66 finished with value: 0.703566316841004 and parameters: {'subsample': 0.8555388458048154, 'dropout_rate': 0.283278058297774, 'n_estimators': 364, 'learning_rate': 0.08751674362838242}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:06:46,188] Trial 67 finished with value: 0.7099568160786738 and parameters: {'subsample': 0.6474245784149503, 'dropout_rate': 0.8903115904226035, 'n_estimators': 410, 'learning_rate': 0.07682910160520641}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5845070422535211
[I 2024-04-14 07:06:52,839] Trial 68 finished with value: 0.7055638412028614 and parameters: {'subsample': 0.9283322082695971, 'dropout_rate': 0.23527117454766744, 'n_estimators': 390, 'learning_rate': 0.0925825190207951}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:06:56,119] Trial 69 finished with value: 0.7209945706187303 and parameters: {'subsample': 0.13633433716152804, 'dropout_rate': 0.9490666653031774, 'n_estimators': 238, 'learning_rate': 0.06566534839190481}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:07:04,566] Trial 70 finished with value: 0.7109515769791928 and parameters: {'subsample': 0.717389757248238, 'dropout_rate': 0.4038301097878197, 'n_estimators': 462, 'learning_rate': 0.09627873052121005}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:07:09,409] Trial 71 finished with value: 0.7244047783621788 and parameters: {'subsample': 0.9680957221347807, 'dropout_rate': 0.117967515733894, 'n_estimators': 334, 'learning_rate': 0.08218500123803454}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:07:14,281] Trial 72 finished with value: 0.7057057974894199 and parameters: {'subsample': 0.9986427863444438, 'dropout_rate': 0.1582427263276, 'n_estimators': 325, 'learning_rate': 0.0847992845889872}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:07:18,221] Trial 73 finished with value: 0.725297635505036 and parameters: {'subsample': 0.950182062840882, 'dropout_rate': 0.10508748864440495, 'n_estimators': 310, 'learning_rate': 0.08961005265805153}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:07:21,610] Trial 74 finished with value: 0.7149877368977057 and parameters: {'subsample': 0.9221170984778992, 'dropout_rate': 0.16985867455335918, 'n_estimators': 278, 'learning_rate': 0.07973969127975046}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:07:24,465] Trial 75 finished with value: 0.7206074847968653 and parameters: {'subsample': 0.8768675391585503, 'dropout_rate': 0.1306507559786499, 'n_estimators': 253, 'learning_rate': 0.08342880433285606}. Best is trial 38 with value: 0.7271438285276995.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:07:28,047] Trial 76 finished with value: 0.7244047783621788 and parameters: {'subsample': 0.7840430137499314, 'dropout_rate': 0.10065983710855575, 'n_estimators': 296, 'learning_rate': 0.06996959711162812}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5845070422535211
[I 2024-04-14 07:07:32,214] Trial 77 finished with value: 0.7131098026254052 and parameters: {'subsample': 0.8305731739623083, 'dropout_rate': 0.1891356618409777, 'n_estimators': 332, 'learning_rate': 0.07522742160944265}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 07:07:36,797] Trial 78 finished with value: 0.7186881255038523 and parameters: {'subsample': 0.9688826326053247, 'dropout_rate': 0.15879053498090168, 'n_estimators': 353, 'learning_rate': 0.09793313715603502}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:07:37,356] Trial 79 finished with value: 0.6935204803245794 and parameters: {'subsample': 0.9407227650576262, 'dropout_rate': 0.2149132995666178, 'n_estimators': 79, 'learning_rate': 0.0936066655729223}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:07:42,769] Trial 80 finished with value: 0.6514945071044511 and parameters: {'subsample': 0.8994001672458584, 'dropout_rate': 0.43904568029922514, 'n_estimators': 437, 'learning_rate': 0.08727818561148795}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:07:46,111] Trial 81 finished with value: 0.7233782762120231 and parameters: {'subsample': 0.9493866155281071, 'dropout_rate': 0.10107975360263313, 'n_estimators': 305, 'learning_rate': 0.09044572224755805}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:07:49,551] Trial 82 finished with value: 0.725297635505036 and parameters: {'subsample': 0.9764112346781065, 'dropout_rate': 0.12046053991629387, 'n_estimators': 313, 'learning_rate': 0.09031966458152571}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:07:52,448] Trial 83 finished with value: 0.7186928104764329 and parameters: {'subsample': 0.851169451607148, 'dropout_rate': 0.14874563302538926, 'n_estimators': 281, 'learning_rate': 0.07858014084602818}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 07:07:57,985] Trial 84 finished with value: 0.7244047783621788 and parameters: {'subsample': 0.9418122194231449, 'dropout_rate': 0.12527938813123965, 'n_estimators': 377, 'learning_rate': 0.09379129015853273}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:08:02,191] Trial 85 finished with value: 0.7224122527988165 and parameters: {'subsample': 0.5057928235941722, 'dropout_rate': 0.18979771830301784, 'n_estimators': 337, 'learning_rate': 0.08595196742896294}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 07:08:05,040] Trial 86 finished with value: 0.7243586683688858 and parameters: {'subsample': 0.9131046701661872, 'dropout_rate': 0.10106631352861013, 'n_estimators': 273, 'learning_rate': 0.08905477731923789}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:08:08,407] Trial 87 finished with value: 0.7195856676192901 and parameters: {'subsample': 0.8701057436797482, 'dropout_rate': 0.14554313527218526, 'n_estimators': 312, 'learning_rate': 0.0825600721271382}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:08:12,413] Trial 88 finished with value: 0.6923650181397053 and parameters: {'subsample': 0.9769341902888562, 'dropout_rate': 0.1658280340507466, 'n_estimators': 361, 'learning_rate': 0.04647359430999269}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:08:14,536] Trial 89 finished with value: 0.6332603248271869 and parameters: {'subsample': 0.9999345989056668, 'dropout_rate': 0.5133482290626339, 'n_estimators': 256, 'learning_rate': 0.09985584938001404}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:08:17,743] Trial 90 finished with value: 0.7266967162641002 and parameters: {'subsample': 0.26859331465546027, 'dropout_rate': 0.23906187834737808, 'n_estimators': 324, 'learning_rate': 0.09691083996917729}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:08:20,370] Trial 91 finished with value: 0.7212775031242987 and parameters: {'subsample': 0.20410111998285901, 'dropout_rate': 0.3516813710603792, 'n_estimators': 291, 'learning_rate': 0.09752941757727555}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:08:23,812] Trial 92 finished with value: 0.7181771272505177 and parameters: {'subsample': 0.444674248871581, 'dropout_rate': 0.11897091184674677, 'n_estimators': 325, 'learning_rate': 0.09368562648443055}. Best is trial 38 with value: 0.7271438285276995.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:08:27,635] Trial 93 finished with value: 0.7322020113414983 and parameters: {'subsample': 0.10609721872610565, 'dropout_rate': 0.20442131574078218, 'n_estimators': 351, 'learning_rate': 0.08985631890249023}. Best is trial 93 with value: 0.7322020113414983.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:08:32,769] Trial 94 finished with value: 0.7241000454542503 and parameters: {'subsample': 0.10371542090623288, 'dropout_rate': 0.6716064232961946, 'n_estimators': 483, 'learning_rate': 0.09460748960776301}. Best is trial 93 with value: 0.7322020113414983.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:08:35,788] Trial 95 finished with value: 0.7267094037975002 and parameters: {'subsample': 0.14151523796850238, 'dropout_rate': 0.24304138447215276, 'n_estimators': 351, 'learning_rate': 0.08643718439857205}. Best is trial 93 with value: 0.7322020113414983.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:08:38,594] Trial 96 finished with value: 0.7221436666207675 and parameters: {'subsample': 0.13624493589320427, 'dropout_rate': 0.2606543862399324, 'n_estimators': 349, 'learning_rate': 0.08594086569732917}. Best is trial 93 with value: 0.7322020113414983.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:08:41,692] Trial 97 finished with value: 0.7176921581044289 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.31372183756474226, 'n_estimators': 371, 'learning_rate': 0.09197089043056268}. Best is trial 93 with value: 0.7322020113414983.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:08:45,304] Trial 98 finished with value: 0.7247629882274309 and parameters: {'subsample': 0.168169033258256, 'dropout_rate': 0.24954151405045744, 'n_estimators': 399, 'learning_rate': 0.09811038118499595}. Best is trial 93 with value: 0.7322020113414983.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8227848101265823

[I 2024-04-14 07:08:48,338] A new study created in memory with name: no-name-150bdc90-ec24-4962-990c-264ced908e96

Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:08:48,333] Trial 99 finished with value: 0.7203459965892061 and parameters: {'subsample': 0.1322523657447192, 'dropout_rate': 0.22740372170561263, 'n_estimators': 357, 'learning_rate': 0.02059679867140307}. Best is trial 93 with value: 0.7322020113414983.


* Best trial for C-index:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.7322020113414983], datetime_start=datetime.datetime(2024, 4, 14, 7, 8, 23, 817390), datetime_complete=datetime.datetime(2024, 4, 14, 7, 8, 27, 635444), params={'subsample': 0.10609721872610565, 'dropout_rate': 0.20442131574078218, 'n_estimators': 351, 'learning_rate': 0.08985631890249023}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=93, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10609721872610565, 'dropout_rate': 0.20442131574078218, 'n_estimators': 351, 'learning_rate': 0.08985631890249023}


* Best Score for C-index:
 0.7322020113414983

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1813728488668672
Fold 2 IBS: 0.2681995723911614
Fold 3 IBS: 0.19491583632250825
Fold 4 IBS: 0.2591223857279743
Fold 5 IBS: 0.287607304180785
[I 2024-04-14 07:08:49,019] Trial 0 finished with value: 0.23824358949785923 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.19346132552880968
Fold 2 IBS: 0.333635239938422
Fold 3 IBS: 0.25841417567823277
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.33474769607672983
[I 2024-04-14 07:08:53,801] Trial 1 finished with value: 0.287222617640297 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.1850589314377048
Fold 2 IBS: 0.32284991583985745
Fold 3 IBS: 0.22642778350592282
Fold 4 IBS: 0.3131879440790452
Fold 5 IBS: 0.3204571034658354
[I 2024-04-14 07:08:55,208] Trial 2 finished with value: 0.27359633566567315 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.1905463052834996
Fold 2 IBS: 0.27639252154435356
Fold 3 IBS: 0.19977904610578312
Fold 4 IBS: 0.30964356157804196
Fold 5 IBS: 0.3057104839266166
[I 2024-04-14 07:08:56,789] Trial 3 finished with value: 0.256414383687659 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.18979017560460285
Fold 2 IBS: 0.28165603731910205
Fold 3 IBS: 0.20753177024015892
Fold 4 IBS: 0.3108415350225879
Fold 5 IBS: 0.3127562135989296
[I 2024-04-14 07:08:59,247] Trial 4 finished with value: 0.26051514635707623 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.19537572961200286
Fold 2 IBS: 0.35817891717310324
Fold 3 IBS: 0.2507632087812951
Fold 4 IBS: 0.3158522741556934
Fold 5 IBS: 0.33393252910961757
[I 2024-04-14 07:09:01,729] Trial 5 finished with value: 0.2908205317663425 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.18137830855281592
Fold 2 IBS: 0.24793283695787818
Fold 3 IBS: 0.18249630236911993
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.26458515064083027
[I 2024-04-14 07:09:02,757] Trial 6 finished with value: 0.22022100159798294 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.22022100159798294.
Fold 1 IBS: 0.1911629762343609
Fold 2 IBS: 0.20016441145421077
Fold 3 IBS: 0.1741036457562264
Fold 4 IBS: 0.20816262061005744
Fold 5 IBS: 0.2247983920371421
[I 2024-04-14 07:09:03,000] Trial 7 finished with value: 0.19967840921839952 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19967840921839952.
Fold 1 IBS: 0.17610273870091617
Fold 2 IBS: 0.2639224383921999
Fold 3 IBS: 0.192681424890099
Fold 4 IBS: 0.2572479682340138
Fold 5 IBS: 0.28852789950585367
[I 2024-04-14 07:09:04,254] Trial 8 finished with value: 0.2356964939446165 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19967840921839952.
Fold 1 IBS: 0.19894421380629848
Fold 2 IBS: 0.3574154634952448
Fold 3 IBS: 0.24952741981587587
Fold 4 IBS: 0.3158539314513873
Fold 5 IBS: 0.33189796891000267
[I 2024-04-14 07:09:07,745] Trial 9 finished with value: 0.29072779949576183 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19967840921839952.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22059842885155323
Fold 3 IBS: 0.2036146550646029
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21796899997630922
[I 2024-04-14 07:09:07,916] Trial 10 finished with value: 0.21599051849664241 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19967840921839952.
Fold 1 IBS: 0.21140722062572354
Fold 2 IBS: 0.21744929507518834
Fold 3 IBS: 0.2007975357492026
Fold 4 IBS: 0.22325500430754436
Fold 5 IBS: 0.21757531472963265
[I 2024-04-14 07:09:08,027] Trial 11 finished with value: 0.2140968740974583 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.19967840921839952.
Fold 1 IBS: 0.17937759801952274
Fold 2 IBS: 0.21509707158444255
Fold 3 IBS: 0.15931421963495104
Fold 4 IBS: 0.18616142584971984
Fold 5 IBS: 0.25130362272257034
[I 2024-04-14 07:09:08,306] Trial 12 finished with value: 0.1982507875622413 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.1982507875622413.
Fold 1 IBS: 0.18856179084766292
Fold 2 IBS: 0.23497263999650947
Fold 3 IBS: 0.1667562811999117
Fold 4 IBS: 0.19610874652061935
Fold 5 IBS: 0.27271801874741475
[I 2024-04-14 07:09:08,744] Trial 13 finished with value: 0.21182349546242368 and parameters: {'subsample': 0.11029739529314715, 'dropout_rate': 0.695526957994077, 'n_estimators': 86, 'learning_rate': 0.09856277651579823}. Best is trial 12 with value: 0.1982507875622413.
Fold 1 IBS: 0.1849839820205685
Fold 2 IBS: 0.20001253127789195
Fold 3 IBS: 0.16857461819050648
Fold 4 IBS: 0.20354941884450073
Fold 5 IBS: 0.23335112566427893
[I 2024-04-14 07:09:09,142] Trial 14 finished with value: 0.19809433519954933 and parameters: {'subsample': 0.2888452381430052, 'dropout_rate': 0.6348327022941171, 'n_estimators': 79, 'learning_rate': 0.035476350988955505}. Best is trial 14 with value: 0.19809433519954933.
Fold 1 IBS: 0.1943821720575859
Fold 2 IBS: 0.1962338941868033
Fold 3 IBS: 0.17710182742208266
Fold 4 IBS: 0.20214635127157912
Fold 5 IBS: 0.21903826977220867
[I 2024-04-14 07:09:09,688] Trial 15 finished with value: 0.1977805029420519 and parameters: {'subsample': 0.10269051002372756, 'dropout_rate': 0.8088719290273756, 'n_estimators': 112, 'learning_rate': 0.017180301525687395}. Best is trial 15 with value: 0.1977805029420519.
Fold 1 IBS: 0.18339250477464022
Fold 2 IBS: 0.20319258978575241
Fold 3 IBS: 0.1661619984420803
Fold 4 IBS: 0.2013829919684142
Fold 5 IBS: 0.2337934982839941
[I 2024-04-14 07:09:11,271] Trial 16 finished with value: 0.19758471665097627 and parameters: {'subsample': 0.25470623831733574, 'dropout_rate': 0.9733961081825167, 'n_estimators': 286, 'learning_rate': 0.010366544228476868}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.20331925863707082
Fold 2 IBS: 0.20612796313076953
Fold 3 IBS: 0.1895220578347265
Fold 4 IBS: 0.21450902469782163
Fold 5 IBS: 0.2168894520013089
[I 2024-04-14 07:09:12,987] Trial 17 finished with value: 0.20607355126033947 and parameters: {'subsample': 0.22261392631470556, 'dropout_rate': 0.9463943646454993, 'n_estimators': 300, 'learning_rate': 0.0029268848855236312}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.1744954041275079
Fold 2 IBS: 0.24064649492990658
Fold 3 IBS: 0.17012186647111502
Fold 4 IBS: 0.22213149299859028
Fold 5 IBS: 0.27267310730489913
[I 2024-04-14 07:09:15,202] Trial 18 finished with value: 0.2160136731664038 and parameters: {'subsample': 0.34158619983817823, 'dropout_rate': 0.8307549552245073, 'n_estimators': 346, 'learning_rate': 0.01597915504691595}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.174779052956043

Fold 2 IBS: 0.2201721111473965
Fold 3 IBS: 0.16049538705387162
Fold 4 IBS: 0.19883907409387722
Fold 5 IBS: 0.25214311294332836
[I 2024-04-14 07:09:17,718] Trial 19 finished with value: 0.20128574763890333 and parameters: {'subsample': 0.19466785612802578, 'dropout_rate': 0.9970233766526893, 'n_estimators': 400, 'learning_rate': 0.011950521021857646}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.1735392166010339
Fold 2 IBS: 0.24733020426410265
Fold 3 IBS: 0.17696939073794427
Fold 4 IBS: 0.23474400621151825
Fold 5 IBS: 0.2774794573590098
[I 2024-04-14 07:09:19,221] Trial 20 finished with value: 0.22201245503472178 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.8176525656681569, 'n_estimators': 260, 'learning_rate': 0.022981610123841693}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.17538793308166473
Fold 2 IBS: 0.22370044303047862
Fold 3 IBS: 0.16414051314890563
Fold 4 IBS: 0.2099845331024728
Fold 5 IBS: 0.25879976738777416
[I 2024-04-14 07:09:19,873] Trial 21 finished with value: 0.20640263795025918 and parameters: {'subsample': 0.29615132774278785, 'dropout_rate': 0.6080226687634136, 'n_estimators': 130, 'learning_rate': 0.03630028864822015}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.179607285311526
Fold 2 IBS: 0.20577208818195444
Fold 3 IBS: 0.16403406395768105
Fold 4 IBS: 0.19447516876461174
Fold 5 IBS: 0.2455004218673159
[I 2024-04-14 07:09:20,537] Trial 22 finished with value: 0.19787780561661783 and parameters: {'subsample': 0.1771198160121214, 'dropout_rate': 0.8280154195167686, 'n_estimators': 136, 'learning_rate': 0.03158788330069932}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.19369013138994712
Fold 2 IBS: 0.19576234815118884
Fold 3 IBS: 0.17573214666291945
Fold 4 IBS: 0.20448031625814103
Fold 5 IBS: 0.2198810523135934
[I 2024-04-14 07:09:21,272] Trial 23 finished with value: 0.19790919895515796 and parameters: {'subsample': 0.18841554890499232, 'dropout_rate': 0.7918377481141982, 'n_estimators': 147, 'learning_rate': 0.01275930416413329}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.17905557946404024
Fold 2 IBS: 0.2274511980832076
Fold 3 IBS: 0.16045959581974598
Fold 4 IBS: 0.19830926266580498
Fold 5 IBS: 0.26937703666424917
[I 2024-04-14 07:09:23,025] Trial 24 finished with value: 0.2069305345394096 and parameters: {'subsample': 0.10044041047323272, 'dropout_rate': 0.9849685591061821, 'n_estimators': 307, 'learning_rate': 0.024647086960817383}. Best is trial 16 with value: 0.19758471665097627.
Fold 1 IBS: 0.19213703502471707
Fold 2 IBS: 0.1948710190827194
Fold 3 IBS: 0.1738077619173112
Fold 4 IBS: 0.20284446404696221
Fold 5 IBS: 0.22208077383425118
[I 2024-04-14 07:09:24,380] Trial 25 finished with value: 0.1971482107811922 and parameters: {'subsample': 0.18537042314447869, 'dropout_rate': 0.7877636400904316, 'n_estimators': 239, 'learning_rate': 0.008500348756543277}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.19098025052262182
Fold 2 IBS: 0.20222098713946032
Fold 3 IBS: 0.17358201425984401
Fold 4 IBS: 0.20902662986871812
Fold 5 IBS: 0.22768314857870428
[I 2024-04-14 07:09:25,600] Trial 26 finished with value: 0.20069860607386972 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9048053477698211, 'n_estimators': 233, 'learning_rate': 0.009031593335834642}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.1835781854157711
Fold 2 IBS: 0.2908624147730039
Fold 3 IBS: 0.20781388177619087
Fold 4 IBS: 0.2856147922808121
Fold 5 IBS: 0.30115918512934253
[I 2024-04-14 07:09:28,250] Trial 27 finished with value: 0.2538056918750241 and parameters: {'subsample': 0.6300055793907031, 'dropout_rate': 0.9145814177501755, 'n_estimators': 405, 'learning_rate': 0.01897956954947822}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.19247726919241395
Fold 2 IBS: 0.19785595501576958
Fold 3 IBS: 0.17379558284926944
Fold 4 IBS: 0.2057564040894929
Fold 5 IBS: 0.22319648290591734
[I 2024-04-14 07:09:30,022] Trial 28 finished with value: 0.19861633881057264 and parameters: {'subsample': 0.24832294744598937, 'dropout_rate': 0.7806059987633581, 'n_estimators': 291, 'learning_rate': 0.006883013872012588}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.19968332536933295
Fold 2 IBS: 0.3441521682945542
Fold 3 IBS: 0.24183287914555465
Fold 4 IBS: 0.315084778759123
Fold 5 IBS: 0.3281901649523497
[I 2024-04-14 07:09:32,266] Trial 29 finished with value: 0.28578866330418295 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.5826192624716777, 'n_estimators': 332, 'learning_rate': 0.040509782405817096}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.1766052289579641
Fold 2 IBS: 0.22661304296888904
Fold 3 IBS: 0.16213080687162637
Fold 4 IBS: 0.20624398500627752
Fold 5 IBS: 0.2682833348533391
[I 2024-04-14 07:09:33,585] Trial 30 finished with value: 0.20797527973161922 and parameters: {'subsample': 0.16111518972434866, 'dropout_rate': 0.7682925414446407, 'n_estimators': 235, 'learning_rate': 0.027170045319751965}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.19444981603437012
Fold 2 IBS: 0.1963404084038773
Fold 3 IBS: 0.17604179769506978
Fold 4 IBS: 0.20557427302826878
Fold 5 IBS: 0.21870258367973403
[I 2024-04-14 07:09:34,068] Trial 31 finished with value: 0.198221775768264 and parameters: {'subsample': 0.19250279506370882, 'dropout_rate': 0.8783007185769502, 'n_estimators': 104, 'learning_rate': 0.017053381527027216}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.176980825762568
Fold 2 IBS: 0.22102439786353303
Fold 3 IBS: 0.16878530989050894
Fold 4 IBS: 0.2083602741691916
Fold 5 IBS: 0.25431297658491225
[I 2024-04-14 07:09:34,787] Trial 32 finished with value: 0.20589275685414274 and parameters: {'subsample': 0.31824771138775504, 'dropout_rate': 0.8417653232964004, 'n_estimators': 152, 'learning_rate': 0.02881843641704926}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.20356057343677417
Fold 2 IBS: 0.20576807283614684
Fold 3 IBS: 0.18905186341466138
Fold 4 IBS: 0.2136778687729837
Fold 5 IBS: 0.216317310690828
[I 2024-04-14 07:09:35,296] Trial 33 finished with value: 0.2056751378302788 and parameters: {'subsample': 0.1548910041422289, 'dropout_rate': 0.9423523198520738, 'n_estimators': 111, 'learning_rate': 0.008390503824508122}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.1813965524135046
Fold 2 IBS: 0.2032752300832063
Fold 3 IBS: 0.16495708675417825
Fold 4 IBS: 0.19994180417106044
Fold 5 IBS: 0.23998389727889244
[I 2024-04-14 07:09:36,249] Trial 34 finished with value: 0.19791091414016843 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.5051054684842515, 'n_estimators': 174, 'learning_rate': 0.020684756718428673}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.17833611436780458
Fold 2 IBS: 0.28093015832819973
Fold 3 IBS: 0.20454386789190426
Fold 4 IBS: 0.2961707966706035
Fold 5 IBS: 0.30269472846226836
[I 2024-04-14 07:09:37,323] Trial 35 finished with value: 0.25253513314415604 and parameters: {'subsample': 0.40513288908300327, 'dropout_rate': 0.7737125073472573, 'n_estimators': 207, 'learning_rate': 0.04478238246338995}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.20579021923028507
Fold 2 IBS: 0.20932153245546029
Fold 3 IBS: 0.1928316733529425
Fold 4 IBS: 0.21758686813413788
Fold 5 IBS: 0.21673077481539857
[I 2024-04-14 07:09:38,085] Trial 36 finished with value: 0.20845221359764485 and parameters: {'subsample': 0.2530965405154966, 'dropout_rate': 0.24408912236765595, 'n_estimators': 141, 'learning_rate': 0.004603344804346231}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.1947606935985878
Fold 2 IBS: 0.2831164839934093
Fold 3 IBS: 0.19846652673990053
Fold 4 IBS: 0.31007686999084766
Fold 5 IBS: 0.3108104777628533
[I 2024-04-14 07:09:39,393] Trial 37 finished with value: 0.2594462104171197 and parameters: {'subsample': 0.15811883339080096, 'dropout_rate': 0.9576634600760099, 'n_estimators': 249, 'learning_rate': 0.059207327336158105}. Best is trial 25 with value: 0.1971482107811922.
Fold 1 IBS: 0.18983783238058843
Fold 2 IBS: 0.19432715712519005

Fold 3 IBS: 0.17002706897662592
Fold 4 IBS: 0.19609017052810865
Fold 5 IBS: 0.2228501539633481
[I 2024-04-14 07:09:40,353] Trial 38 finished with value: 0.19462647659477222 and parameters: {'subsample': 0.1004632969526114, 'dropout_rate': 0.8707974888946499, 'n_estimators': 190, 'learning_rate': 0.013682382045643884}. Best is trial 38 with value: 0.19462647659477222.
Fold 1 IBS: 0.18405040743608886
Fold 2 IBS: 0.1984796262962242
Fold 3 IBS: 0.16110897911275487
Fold 4 IBS: 0.1860026613402482
Fold 5 IBS: 0.23377526281533342
[I 2024-04-14 07:09:41,942] Trial 39 finished with value: 0.19268338740012994 and parameters: {'subsample': 0.10729506851765452, 'dropout_rate': 0.8692930630849747, 'n_estimators': 278, 'learning_rate': 0.013812830432153408}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1836380458420524
Fold 2 IBS: 0.22701546500543537
Fold 3 IBS: 0.17208935795899977
Fold 4 IBS: 0.2120304687824635
Fold 5 IBS: 0.24956282584914827
[I 2024-04-14 07:09:43,487] Trial 40 finished with value: 0.20886723268761984 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.8736746561752836, 'n_estimators': 280, 'learning_rate': 0.011612622896134815}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18708257459636338
Fold 2 IBS: 0.1949585758770501
Fold 3 IBS: 0.16628015153623615
Fold 4 IBS: 0.19210940890450162
Fold 5 IBS: 0.2262282309338894
[I 2024-04-14 07:09:44,428] Trial 41 finished with value: 0.19333178836960813 and parameters: {'subsample': 0.10770584838475766, 'dropout_rate': 0.8696830603812036, 'n_estimators': 186, 'learning_rate': 0.016469176326247694}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18492377821454622
Fold 2 IBS: 0.20230124841347455
Fold 3 IBS: 0.16605584618072275
Fold 4 IBS: 0.19770994239756803
Fold 5 IBS: 0.2334266967946866
[I 2024-04-14 07:09:45,396] Trial 42 finished with value: 0.19688350240019964 and parameters: {'subsample': 0.21471538042054475, 'dropout_rate': 0.9244674176294541, 'n_estimators': 196, 'learning_rate': 0.01488815097187909}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18648562187335943
Fold 2 IBS: 0.26272714208950115
Fold 3 IBS: 0.19956383509903874
Fold 4 IBS: 0.2984711499150407
Fold 5 IBS: 0.3056037449873883
[I 2024-04-14 07:09:46,397] Trial 43 finished with value: 0.25057029879286563 and parameters: {'subsample': 0.13700515637618993, 'dropout_rate': 0.8759094781181256, 'n_estimators': 196, 'learning_rate': 0.06919215186728203}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18233370227496842
Fold 2 IBS: 0.20087977993623424
Fold 3 IBS: 0.1654278636357402
Fold 4 IBS: 0.20024936453671502
Fold 5 IBS: 0.2349559282121902
[I 2024-04-14 07:09:47,591] Trial 44 finished with value: 0.1967693277191696 and parameters: {'subsample': 0.21356249032499006, 'dropout_rate': 0.7494020767479845, 'n_estimators': 218, 'learning_rate': 0.015132707319227447}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18660645613571072
Fold 2 IBS: 0.2107971635613356
Fold 3 IBS: 0.1713569548672323
Fold 4 IBS: 0.20859997849126022
Fold 5 IBS: 0.23683553556349604
[I 2024-04-14 07:09:48,476] Trial 45 finished with value: 0.20283921772380697 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.7478335303234585, 'n_estimators': 178, 'learning_rate': 0.014796231788051827}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1745744751827036
Fold 2 IBS: 0.21776551003903968
Fold 3 IBS: 0.165998788252463
Fold 4 IBS: 0.2086687501704093
Fold 5 IBS: 0.2586491936075057
[I 2024-04-14 07:09:49,606] Trial 46 finished with value: 0.20513134345042427 and parameters: {'subsample': 0.21558009800179764, 'dropout_rate': 0.9147806973327633, 'n_estimators': 219, 'learning_rate': 0.022625916599912255}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.2014539143441285
Fold 2 IBS: 0.26152310067349677
Fold 3 IBS: 0.18593547788047848
Fold 4 IBS: 0.2872658713139566
Fold 5 IBS: 0.3060843757969445
[I 2024-04-14 07:09:50,862] Trial 47 finished with value: 0.24845254800180094 and parameters: {'subsample': 0.13030823615169787, 'dropout_rate': 0.1240463473883398, 'n_estimators': 199, 'learning_rate': 0.08063451221472408}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17250015643979705
Fold 2 IBS: 0.25190352945239125
Fold 3 IBS: 0.18323284582306654
Fold 4 IBS: 0.25433849186731855
Fold 5 IBS: 0.2853357693808103
[I 2024-04-14 07:09:52,527] Trial 48 finished with value: 0.22946215859267674 and parameters: {'subsample': 0.28966229494838114, 'dropout_rate': 0.6604314111556595, 'n_estimators': 267, 'learning_rate': 0.027763821111874188}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.20918546635492635
Fold 2 IBS: 0.21468388537608765
Fold 3 IBS: 0.19798182667601127
Fold 4 IBS: 0.21988033303022797
Fold 5 IBS: 0.21686450897289436
[I 2024-04-14 07:09:53,420] Trial 49 finished with value: 0.21171920408202954 and parameters: {'subsample': 0.13011509891815973, 'dropout_rate': 0.7305182772711464, 'n_estimators': 162, 'learning_rate': 0.002439359929650227}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17900999225541078
Fold 2 IBS: 0.22117900177116986
Fold 3 IBS: 0.16508004120843858
Fold 4 IBS: 0.20918121982924812
Fold 5 IBS: 0.25167670436719425
[I 2024-04-14 07:09:54,843] Trial 50 finished with value: 0.2052253918862923 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.42732372125147283, 'n_estimators': 190, 'learning_rate': 0.020201225675065167}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19317107831286814
Fold 2 IBS: 0.19659083602346178
Fold 3 IBS: 0.17500873464664715
Fold 4 IBS: 0.20622853865926383
Fold 5 IBS: 0.22164175943395995
[I 2024-04-14 07:09:56,214] Trial 51 finished with value: 0.19852818941524014 and parameters: {'subsample': 0.2110300563618658, 'dropout_rate': 0.8572374151159555, 'n_estimators': 236, 'learning_rate': 0.008049348949492514}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.21107557304290853
Fold 2 IBS: 0.21715325785299433
Fold 3 IBS: 0.2002431837233802
Fold 4 IBS: 0.22188383643125392
Fold 5 IBS: 0.21729597017123387
[I 2024-04-14 07:09:57,497] Trial 52 finished with value: 0.21353036424435415 and parameters: {'subsample': 0.15893827660824178, 'dropout_rate': 0.6756252274473317, 'n_estimators': 220, 'learning_rate': 0.0011158571980821753}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1830444401864184
Fold 2 IBS: 0.24107987550682053
Fold 3 IBS: 0.18102247918217043
Fold 4 IBS: 0.21918399828373406
Fold 5 IBS: 0.258459735736968
[I 2024-04-14 07:09:58,809] Trial 53 finished with value: 0.2165581057792223 and parameters: {'subsample': 0.7913904774662813, 'dropout_rate': 0.9217625536812734, 'n_estimators': 251, 'learning_rate': 0.014990186831450297}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19407570702649835
Fold 2 IBS: 0.19905872196692811
Fold 3 IBS: 0.17586908023949321
Fold 4 IBS: 0.2075108757703561
Fold 5 IBS: 0.22221025748507964
[I 2024-04-14 07:10:00,497] Trial 54 finished with value: 0.19974492849767106 and parameters: {'subsample': 0.2683778622843548, 'dropout_rate': 0.8070041147090473, 'n_estimators': 328, 'learning_rate': 0.005507109164112978}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.194110060712962
Fold 2 IBS: 0.19612503566227235
Fold 3 IBS: 0.17600256751416188
Fold 4 IBS: 0.2012392944577118
Fold 5 IBS: 0.21895122590623617
[I 2024-04-14 07:10:01,166] Trial 55 finished with value: 0.19728563685066886 and parameters: {'subsample': 0.10714522118359288, 'dropout_rate': 0.8580648707217642, 'n_estimators': 172, 'learning_rate': 0.011714527188959833}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17037303188779496
Fold 2 IBS: 0.2438940987953285
Fold 3 IBS: 0.16225075308591755
Fold 4 IBS: 0.21714906594955083
Fold 5 IBS: 0.2737264192961221
[I 2024-04-14 07:10:02,219] Trial 56 finished with value: 0.21347867380294278 and parameters: {'subsample': 0.19000616271212967, 'dropout_rate': 0.3060080718603104, 'n_estimators': 218, 'learning_rate': 0.03269748364132459}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1817069526222211

Fold 2 IBS: 0.2228601124917642
Fold 3 IBS: 0.16056105379124547
Fold 4 IBS: 0.19023440953991608
Fold 5 IBS: 0.26370761668054876
[I 2024-04-14 07:10:03,506] Trial 57 finished with value: 0.20381402902513912 and parameters: {'subsample': 0.10156433706067643, 'dropout_rate': 0.7395601360396487, 'n_estimators': 270, 'learning_rate': 0.025088218273015078}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17402968637702
Fold 2 IBS: 0.22306665859290922
Fold 3 IBS: 0.15697605831771821
Fold 4 IBS: 0.1966965099884976
Fold 5 IBS: 0.25416298400893117
[I 2024-04-14 07:10:04,967] Trial 58 finished with value: 0.20098637945701525 and parameters: {'subsample': 0.1445593583094237, 'dropout_rate': 0.9424651955543935, 'n_estimators': 307, 'learning_rate': 0.017444947774407398}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18236249235442123
Fold 2 IBS: 0.22619523389438162
Fold 3 IBS: 0.17099244042885403
Fold 4 IBS: 0.21187950439521488
Fold 5 IBS: 0.24997387585943787
[I 2024-04-14 07:10:05,998] Trial 59 finished with value: 0.2082807093864619 and parameters: {'subsample': 0.5384544407056292, 'dropout_rate': 0.8919715815033947, 'n_estimators': 251, 'learning_rate': 0.013489296506998726}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.201907466724292
Fold 2 IBS: 0.20407176292374665
Fold 3 IBS: 0.1864586183895679
Fold 4 IBS: 0.21347742549444962
Fold 5 IBS: 0.2168729306415216
[I 2024-04-14 07:10:06,729] Trial 60 finished with value: 0.20455764083471556 and parameters: {'subsample': 0.22734318129870051, 'dropout_rate': 0.8303186036159572, 'n_estimators': 186, 'learning_rate': 0.005534370983028001}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19584259481863264
Fold 2 IBS: 0.1979160650164417
Fold 3 IBS: 0.17965845506361824
Fold 4 IBS: 0.20432640880671163
Fold 5 IBS: 0.21807590917656758
[I 2024-04-14 07:10:07,342] Trial 61 finished with value: 0.19916388657639436 and parameters: {'subsample': 0.12137046613176489, 'dropout_rate': 0.8455627908842199, 'n_estimators': 160, 'learning_rate': 0.010635310544620052}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18222532975089348
Fold 2 IBS: 0.2057180347513806
Fold 3 IBS: 0.16173022649103402
Fold 4 IBS: 0.19353878707482464
Fold 5 IBS: 0.23580954768088036
[I 2024-04-14 07:10:07,964] Trial 62 finished with value: 0.19580438514980264 and parameters: {'subsample': 0.1777934967351855, 'dropout_rate': 0.9702237038105993, 'n_estimators': 169, 'learning_rate': 0.02099999582954724}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17563941472967123
Fold 2 IBS: 0.21625071828672024
Fold 3 IBS: 0.1596027028569664
Fold 4 IBS: 0.19316978614823557
Fold 5 IBS: 0.2485278897981323
[I 2024-04-14 07:10:08,753] Trial 63 finished with value: 0.19863810236394513 and parameters: {'subsample': 0.18722874140929732, 'dropout_rate': 0.9908280669358787, 'n_estimators': 203, 'learning_rate': 0.0216874175877477}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17674811672969684
Fold 2 IBS: 0.22123276326200383
Fold 3 IBS: 0.16397182731803897
Fold 4 IBS: 0.206923128737319
Fold 5 IBS: 0.25261659966044897
[I 2024-04-14 07:10:09,713] Trial 64 finished with value: 0.20429848714150153 and parameters: {'subsample': 0.26634884181564095, 'dropout_rate': 0.9523546423868906, 'n_estimators': 230, 'learning_rate': 0.01852414454495133}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1932862372645593
Fold 2 IBS: 0.19872259925800975
Fold 3 IBS: 0.1750658303229222
Fold 4 IBS: 0.20355404643638836
Fold 5 IBS: 0.22157566524623346
[I 2024-04-14 07:10:10,192] Trial 65 finished with value: 0.19844087570562263 and parameters: {'subsample': 0.21027044552578272, 'dropout_rate': 0.9231427192818, 'n_estimators': 133, 'learning_rate': 0.014750341777431968}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19353044541786635
Fold 2 IBS: 0.19566683036416152
Fold 3 IBS: 0.17346332327165384
Fold 4 IBS: 0.201879100522045
Fold 5 IBS: 0.22098333200498224
[I 2024-04-14 07:10:10,496] Trial 66 finished with value: 0.1971046063161418 and parameters: {'subsample': 0.1683248752381967, 'dropout_rate': 0.79604108558509, 'n_estimators': 82, 'learning_rate': 0.025055642086332992}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.20037275477760935
Fold 2 IBS: 0.20034721376608117
Fold 3 IBS: 0.18390434467902214
Fold 4 IBS: 0.20936892560300785
Fold 5 IBS: 0.21722624062450033
[I 2024-04-14 07:10:10,702] Trial 67 finished with value: 0.20224389589004416 and parameters: {'subsample': 0.166318611857215, 'dropout_rate': 0.9701731709482846, 'n_estimators': 52, 'learning_rate': 0.02456820613377737}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18840789864430507
Fold 2 IBS: 0.19828277493257002
Fold 3 IBS: 0.1715496467271948
Fold 4 IBS: 0.2051933884174115
Fold 5 IBS: 0.22830464260129513
[I 2024-04-14 07:10:10,985] Trial 68 finished with value: 0.1983476702645553 and parameters: {'subsample': 0.3041181342589987, 'dropout_rate': 0.8187585834189655, 'n_estimators': 77, 'learning_rate': 0.030916199173676225}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.21055156923309393
Fold 2 IBS: 0.21688618128002454
Fold 3 IBS: 0.2004061968741997
Fold 4 IBS: 0.22132622015590275
Fold 5 IBS: 0.21672330967466816
[I 2024-04-14 07:10:11,101] Trial 69 finished with value: 0.21317869544357784 and parameters: {'subsample': 0.13093051604859987, 'dropout_rate': 0.8887302859312511, 'n_estimators': 15, 'learning_rate': 0.018437631585203923}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1862016599031476
Fold 2 IBS: 0.19561645496186475
Fold 3 IBS: 0.16762312606448065
Fold 4 IBS: 0.20006085551200695
Fold 5 IBS: 0.23213412630940328
[I 2024-04-14 07:10:11,420] Trial 70 finished with value: 0.19632724455018064 and parameters: {'subsample': 0.23580882847670492, 'dropout_rate': 0.7566827876020148, 'n_estimators': 86, 'learning_rate': 0.0383006017021722}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1830066514505155
Fold 2 IBS: 0.19646857987965086
Fold 3 IBS: 0.16580663314542696
Fold 4 IBS: 0.19777738042749365
Fold 5 IBS: 0.2323163867911975
[I 2024-04-14 07:10:11,754] Trial 71 finished with value: 0.1950751263388569 and parameters: {'subsample': 0.23158307771781123, 'dropout_rate': 0.7592351832007285, 'n_estimators': 90, 'learning_rate': 0.03641403096926913}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19510151717398558
Fold 2 IBS: 0.20035464573709924
Fold 3 IBS: 0.17889034730999484
Fold 4 IBS: 0.21137817285693494
Fold 5 IBS: 0.22258688454751918
[I 2024-04-14 07:10:11,918] Trial 72 finished with value: 0.20166231352510672 and parameters: {'subsample': 0.36925171506252996, 'dropout_rate': 0.7630908501595675, 'n_estimators': 36, 'learning_rate': 0.044617865334130966}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17742004194402558
Fold 2 IBS: 0.21929645258281596
Fold 3 IBS: 0.16700242503936896
Fold 4 IBS: 0.21356364983454107
Fold 5 IBS: 0.25907690306154246
[I 2024-04-14 07:10:12,383] Trial 73 finished with value: 0.2072718944924588 and parameters: {'subsample': 0.2542053625197466, 'dropout_rate': 0.7117788702287307, 'n_estimators': 121, 'learning_rate': 0.0408820933677081}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18174683655327536
Fold 2 IBS: 0.19645873432931332
Fold 3 IBS: 0.16708750885609144
Fold 4 IBS: 0.19783078608286672
Fold 5 IBS: 0.23549723078685514
[I 2024-04-14 07:10:12,638] Trial 74 finished with value: 0.1957242193216804 and parameters: {'subsample': 0.22747904573706107, 'dropout_rate': 0.6128365123041772, 'n_estimators': 65, 'learning_rate': 0.0523779329668209}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17757759269081083
Fold 2 IBS: 0.2303129872167407
Fold 3 IBS: 0.1726346973593982
Fold 4 IBS: 0.21833922212297288
Fold 5 IBS: 0.26798642895759317
[I 2024-04-14 07:10:13,007] Trial 75 finished with value: 0.21337018566950317 and parameters: {'subsample': 0.27356905481999527, 'dropout_rate': 0.5920593224023094, 'n_estimators': 97, 'learning_rate': 0.05871254721241882}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18100338200096588
Fold 2 IBS: 0.21333992640900828
Fold 3 IBS: 0.1676455440702017
Fold 4 IBS: 0.20210995579582264
Fold 5 IBS: 0.24229391587482121
[I 2024-04-14 07:10:13,265] Trial 76 finished with value: 0.20127854483016394 and parameters: {'subsample': 0.3464934188332415, 'dropout_rate': 0.5578360217447056, 'n_estimators': 66, 'learning_rate': 0.051445894324390215}. Best is trial 39 with value: 0.19268338740012994.

Fold 1 IBS: 0.1828122761053612
Fold 2 IBS: 0.2038578816882634
Fold 3 IBS: 0.1690908973158653
Fold 4 IBS: 0.2029501739992507
Fold 5 IBS: 0.24491123804637963
[I 2024-04-14 07:10:13,610] Trial 77 finished with value: 0.20072449343102403 and parameters: {'subsample': 0.23806073249204993, 'dropout_rate': 0.6886627075609139, 'n_estimators': 92, 'learning_rate': 0.04696457264732694}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.2013436287263864
Fold 2 IBS: 0.19898281712072002
Fold 3 IBS: 0.18358524170353163
Fold 4 IBS: 0.20783372092143054
Fold 5 IBS: 0.21817179832580144
[I 2024-04-14 07:10:13,780] Trial 78 finished with value: 0.20198344135957397 and parameters: {'subsample': 0.14982582293807192, 'dropout_rate': 0.6315405819836285, 'n_estimators': 36, 'learning_rate': 0.03840067689527933}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17851295561805824
Fold 2 IBS: 0.21756143717488852
Fold 3 IBS: 0.16876763572866496
Fold 4 IBS: 0.2252965684734787
Fold 5 IBS: 0.2665166601947778
[I 2024-04-14 07:10:14,250] Trial 79 finished with value: 0.21133105143797365 and parameters: {'subsample': 0.19901889777722742, 'dropout_rate': 0.5293352070261712, 'n_estimators': 119, 'learning_rate': 0.05488928723565827}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18058699225611785
Fold 2 IBS: 0.24573587504625885
Fold 3 IBS: 0.18115294696638343
Fold 4 IBS: 0.2215072360272606
Fold 5 IBS: 0.26481359508078167
[I 2024-04-14 07:10:14,500] Trial 80 finished with value: 0.2187593290753605 and parameters: {'subsample': 0.7071642411805827, 'dropout_rate': 0.6477236365371342, 'n_estimators': 67, 'learning_rate': 0.06267654571655008}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1769902099680598
Fold 2 IBS: 0.25981471573207193
Fold 3 IBS: 0.17896576554001264
Fold 4 IBS: 0.26022614334979716
Fold 5 IBS: 0.2864382710711673
[I 2024-04-14 07:10:15,205] Trial 81 finished with value: 0.23248702113222178 and parameters: {'subsample': 0.2200409790777019, 'dropout_rate': 0.4585181807773151, 'n_estimators': 166, 'learning_rate': 0.05191285063438977}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1718776636408346
Fold 2 IBS: 0.22856365320496777
Fold 3 IBS: 0.17993367562260132
Fold 4 IBS: 0.2308982162689513
Fold 5 IBS: 0.27438795371530944
[I 2024-04-14 07:10:15,749] Trial 82 finished with value: 0.21713223249053284 and parameters: {'subsample': 0.1819393972575769, 'dropout_rate': 0.758775683698497, 'n_estimators': 142, 'learning_rate': 0.049391874135584206}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19414100727959022
Fold 2 IBS: 0.19525604587273543
Fold 3 IBS: 0.17365198408349045
Fold 4 IBS: 0.19852365584857093
Fold 5 IBS: 0.2217845756587796
[I 2024-04-14 07:10:15,996] Trial 83 finished with value: 0.19667145374863332 and parameters: {'subsample': 0.11672285551337075, 'dropout_rate': 0.9068898402617028, 'n_estimators': 64, 'learning_rate': 0.0349022610727838}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.2084657058628684
Fold 2 IBS: 0.21471007041237639
Fold 3 IBS: 0.19797414967098947
Fold 4 IBS: 0.21846572799144526
Fold 5 IBS: 0.21640935721964666
[I 2024-04-14 07:10:16,104] Trial 84 finished with value: 0.21120500223146524 and parameters: {'subsample': 0.11864779498736906, 'dropout_rate': 0.8965955221902271, 'n_estimators': 12, 'learning_rate': 0.0353397376668319}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1894451939298512
Fold 2 IBS: 0.19623637044836922
Fold 3 IBS: 0.17167306708793809
Fold 4 IBS: 0.19774546092378617
Fold 5 IBS: 0.21946118362451644
[I 2024-04-14 07:10:16,343] Trial 85 finished with value: 0.1949122552028922 and parameters: {'subsample': 0.10239361410651565, 'dropout_rate': 0.858283850732953, 'n_estimators': 60, 'learning_rate': 0.04154694343850068}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19783954425637942
Fold 2 IBS: 0.1972989860169545
Fold 3 IBS: 0.1816651777091398
Fold 4 IBS: 0.20504773917459568
Fold 5 IBS: 0.2200188258516866
[I 2024-04-14 07:10:16,520] Trial 86 finished with value: 0.20037405460175123 and parameters: {'subsample': 0.14248504823128444, 'dropout_rate': 0.8480924463738904, 'n_estimators': 39, 'learning_rate': 0.040712983682544925}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19145154936886724
Fold 2 IBS: 0.19413081097813856
Fold 3 IBS: 0.16935648822881033
Fold 4 IBS: 0.19553610819323594
Fold 5 IBS: 0.22083931935861748
[I 2024-04-14 07:10:16,770] Trial 87 finished with value: 0.1942628552255339 and parameters: {'subsample': 0.10469310531041581, 'dropout_rate': 0.9747454517667994, 'n_estimators': 67, 'learning_rate': 0.03709634946888359}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1797263772884548
Fold 2 IBS: 0.21084484415187188
Fold 3 IBS: 0.15649794566865405
Fold 4 IBS: 0.18695245452146092
Fold 5 IBS: 0.2472240520376702
[I 2024-04-14 07:10:17,142] Trial 88 finished with value: 0.19624913473362235 and parameters: {'subsample': 0.10175583079307021, 'dropout_rate': 0.9967981766274836, 'n_estimators': 106, 'learning_rate': 0.04850963724638746}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1787601171944693
Fold 2 IBS: 0.21296327774131432
Fold 3 IBS: 0.15741196803290897
Fold 4 IBS: 0.18791521561148822
Fold 5 IBS: 0.25041161937266776
[I 2024-04-14 07:10:17,539] Trial 89 finished with value: 0.19749243959056972 and parameters: {'subsample': 0.10370487109802552, 'dropout_rate': 0.9972470651495581, 'n_estimators': 113, 'learning_rate': 0.047297232378679985}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.17559287816304284
Fold 2 IBS: 0.230853932316274
Fold 3 IBS: 0.1580903880553524
Fold 4 IBS: 0.20656019899255873
Fold 5 IBS: 0.26225235961617493
[I 2024-04-14 07:10:17,904] Trial 90 finished with value: 0.20666995142868058 and parameters: {'subsample': 0.16918358716479995, 'dropout_rate': 0.9670860627958263, 'n_estimators': 103, 'learning_rate': 0.0566718447359847}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18889096712459735
Fold 2 IBS: 0.19405542007464796
Fold 3 IBS: 0.17291372929137203
Fold 4 IBS: 0.19738865848465584
Fold 5 IBS: 0.22300695585527416
[I 2024-04-14 07:10:18,124] Trial 91 finished with value: 0.19525114616610947 and parameters: {'subsample': 0.12956639975657927, 'dropout_rate': 0.9447857160967286, 'n_estimators': 56, 'learning_rate': 0.0419738022289947}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.18889347396574846
Fold 2 IBS: 0.19589709154429424
Fold 3 IBS: 0.17226228099488763
Fold 4 IBS: 0.1974003168978796
Fold 5 IBS: 0.22591891514189918
[I 2024-04-14 07:10:18,348] Trial 92 finished with value: 0.19607441570894185 and parameters: {'subsample': 0.14180457097008414, 'dropout_rate': 0.9374075080079437, 'n_estimators': 57, 'learning_rate': 0.043406855600598114}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1920192795547816
Fold 2 IBS: 0.1958395244959101
Fold 3 IBS: 0.17554560721857723
Fold 4 IBS: 0.19940494541449025
Fold 5 IBS: 0.2226832625218074
[I 2024-04-14 07:10:18,555] Trial 93 finished with value: 0.19709852384111332 and parameters: {'subsample': 0.14203792618328934, 'dropout_rate': 0.938325688953457, 'n_estimators': 51, 'learning_rate': 0.04181602642284024}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.2009015832536875
Fold 2 IBS: 0.20321544452380744
Fold 3 IBS: 0.18707649888103411
Fold 4 IBS: 0.21196679182045233
Fold 5 IBS: 0.21675059935719695
[I 2024-04-14 07:10:18,707] Trial 94 finished with value: 0.20398218356723566 and parameters: {'subsample': 0.12848401003591337, 'dropout_rate': 0.8728418448209894, 'n_estimators': 29, 'learning_rate': 0.03784083828401163}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1877313533825978
Fold 2 IBS: 0.19913439227020507
Fold 3 IBS: 0.16780107280733478
Fold 4 IBS: 0.19584432883183203
Fold 5 IBS: 0.22634352472103966
[I 2024-04-14 07:10:18,950] Trial 95 finished with value: 0.19537093440260186 and parameters: {'subsample': 0.155096444333444, 'dropout_rate': 0.971729794057401, 'n_estimators': 62, 'learning_rate': 0.04364929537640498}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.1922105734746585

Fold 2 IBS: 0.1951009945220422
Fold 3 IBS: 0.17267329733250292
Fold 4 IBS: 0.2002556006238113
Fold 5 IBS: 0.2218911890696791
[I 2024-04-14 07:10:19,223] Trial 96 finished with value: 0.19642633100453882 and parameters: {'subsample': 0.175508689577659, 'dropout_rate': 0.9804710762683706, 'n_estimators': 74, 'learning_rate': 0.029076088824093165}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19803585093790257
Fold 2 IBS: 0.1989508054455238
Fold 3 IBS: 0.18076595691737068
Fold 4 IBS: 0.20528537420756332
Fold 5 IBS: 0.2179445399381184
[I 2024-04-14 07:10:19,416] Trial 97 finished with value: 0.20019650548929574 and parameters: {'subsample': 0.15551496658123795, 'dropout_rate': 0.9605705949765594, 'n_estimators': 46, 'learning_rate': 0.033074107860401845}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.21341308393923883
Fold 2 IBS: 0.2208699224086299
Fold 3 IBS: 0.20400578640567724
Fold 4 IBS: 0.22447238838164785
Fold 5 IBS: 0.21796982004016388
[I 2024-04-14 07:10:19,502] Trial 98 finished with value: 0.21614620023507153 and parameters: {'subsample': 0.505768445926465, 'dropout_rate': 0.8993009167671364, 'n_estimators': 1, 'learning_rate': 0.04537684373346617}. Best is trial 39 with value: 0.19268338740012994.
Fold 1 IBS: 0.19618274593282548
Fold 2 IBS: 0.20642332939518176
Fold 3 IBS: 0.18014774402758635
Fold 4 IBS: 0.21435017344109752
Fold 5 IBS: 0.22340196762689238
[I 2024-04-14 07:10:19,642] Trial 99 finished with value: 0.20410119208471672 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.9248134776284089, 'n_estimators': 28, 'learning_rate': 0.05316255316391444}. Best is trial 39 with value: 0.19268338740012994.


* Best trial for IBS:
 FrozenTrial(number=39, state=TrialState.COMPLETE, values=[0.19268338740012994], datetime_start=datetime.datetime(2024, 4, 14, 7, 9, 40, 356454), datetime_complete=datetime.datetime(2024, 4, 14, 7, 9, 41, 942153), params={'subsample': 0.10729506851765452, 'dropout_rate': 0.8692930630849747, 'n_estimators': 278, 'learning_rate': 0.013812830432153408}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=39, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10729506851765452, 'dropout_rate': 0.8692930630849747, 'n_estimators': 278, 'learning_rate': 0.013812830432153408}


* Best Score for IBS:
 0.19268338740012994

In [83]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [84]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.732
train_ibs:  0.193

#### Test

In [85]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [86]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.20442131574078218,
                                              learning_rate=0.08985631890249023,
                                              n_estimators=351,
                                              random_state=123,
                                              subsample=0.10609721872610565)

C-index score: 0.528

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8692930630849747,
                                              learning_rate=0.013812830432153408,
                                              n_estimators=278,
                                              random_state=123,
                                              subsample=0.10729506851765452)

IBS: 0.266

In [87]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [88]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.826   1.0
ExtraSurvivalTrees               0.794   2.0
CoxPH                            0.758   4.0
CoxLasso                         0.758   4.0
CoxElastic                       0.758   4.0
GradientBoosting                 0.745   6.0
ComponentwiseGradientBoosting    0.732   7.0
CoxRidge                         0.680   8.0

In [89]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.183   1.5
ExtraSurvivalTrees             0.183   1.5
CoxLasso                       0.187   3.5
CoxElastic                     0.187   3.5
CoxPH                          0.188   5.0
ComponentwiseGradientBoosting  0.193   6.0
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [90]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.653   1.0
ExtraSurvivalTrees               0.618   2.0
GradientBoosting                 0.603   3.0
CoxLasso                         0.590   4.5
CoxElastic                       0.590   4.5
CoxPH                            0.585   6.0
CoxRidge                         0.534   7.0
ComponentwiseGradientBoosting    0.528   8.0

In [91]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.206   1.0
ExtraSurvivalTrees             0.215   2.0
GradientBoosting               0.220   3.0
CoxRidge                       0.221   4.0
ComponentwiseGradientBoosting  0.266   5.0
CoxLasso                       0.284   6.5
CoxElastic                     0.284   6.5
CoxPH                          0.288   8.0

In [92]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/standard/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

modified_file_names = ['d1_os_standard_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [93]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14