In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.preprocessing import StandardScaler
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 14)
y_train:  (139,)

(99, 16)

# Feature Selection: PLSR

In [14]:
selected_features = [ "hpv_related",
"oropharynx",
"uicc8_III-IV",
"cavum_oris",
"MTV",
"TLG",
"charlson",
"age" ]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [19]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [20]:
X_new

,hpv_related,oropharynx,uicc8_III-IV,cavum_oris,MTV,TLG,charlson,age
0,0.0,1,0.0,0,7.934,86.228420,0,54.238356
1,0.0,0,0.0,0,1.656,7.040100,1,54.539726
2,0.0,0,1.0,1,14.502,83.569669,1,59.019178
3,0.0,0,0.0,0,2.440,5.567091,1,70.726027
4,0.0,0,0.0,0,3.668,16.150550,1,67.865753
...,...,...,...,...,...,...,...,...
134,1.0,1,0.0,0,3.650,26.280140,0,60.435616
135,1.0,1,1.0,0,18.967,101.754834,0,68.794521
136,1.0,1,0.0,0,6.370,66.273201,1,57.498630
137,1.0,1,1.0,0,12.443,71.832443,1,65.684932
138,1.0,1,1.0,0,7.983,78.647696,0,61.676712

In [21]:
X_new_std

,hpv_related,oropharynx,uicc8_III-IV,cavum_oris,MTV,TLG,charlson,age
0,0.0,1,0.0,0,-0.296907,-0.179158,0,-0.776210
1,0.0,0,0.0,0,-0.763433,-0.587333,1,-0.737256
2,0.0,0,1.0,1,0.191169,-0.192863,1,-0.158251
3,0.0,0,0.0,0,-0.705173,-0.594926,1,1.354953
4,0.0,0,0.0,0,-0.613919,-0.540373,1,0.985240
...,...,...,...,...,...,...,...,...
134,1.0,1,0.0,0,-0.615257,-0.488161,0,0.024835
135,1.0,1,1.0,0,0.522969,-0.099128,0,1.105290
136,1.0,1,0.0,0,-0.413130,-0.282017,1,-0.354794
137,1.0,1,1.0,0,0.038162,-0.253362,1,0.703351
138,1.0,1,1.0,0,-0.293266,-0.218233,0,0.185257

In [22]:
MAASTRO_new

,hpv_related,oropharynx,uicc8_III-IV,cavum_oris,MTV,TLG,charlson,age
0,1,1,0,0,22.841,263.611623,1,55
1,0,1,1,0,5.660,36.980700,0,55
2,0,1,1,0,7.791,74.636342,1,55
3,0,0,1,0,7.908,46.791979,1,61
4,1,1,0,0,15.237,107.637514,1,70
...,...,...,...,...,...,...,...,...
94,0,0,1,0,6.110,144.490782,0,66
95,0,0,1,0,7.182,69.214868,1,63
96,1,1,1,0,16.483,102.594274,1,63
97,1,1,0,0,9.981,103.229492,0,54
98,0,0,1,0,3.495,28.553212,0,62

In [23]:
MAASTRO_new_std

,hpv_related,oropharynx,uicc8_III-IV,cavum_oris,MTV,TLG,charlson,age
0,1,1,0,0,0.810851,0.735160,1,-0.677762
1,0,1,1,0,-0.465891,-0.433005,0,-0.677762
2,0,1,1,0,-0.307534,-0.238909,1,-0.677762
3,0,0,1,0,-0.298839,-0.382433,1,0.097786
4,1,1,0,0,0.245788,-0.068806,1,1.261108
...,...,...,...,...,...,...,...,...
94,0,0,1,0,-0.432451,0.121154,0,0.744076
95,0,0,1,0,-0.352789,-0.266854,1,0.356302
96,1,1,1,0,0.338380,-0.094801,1,0.356302
97,1,1,0,0,-0.144792,-0.091527,0,-0.807020
98,0,0,1,0,-0.626775,-0.476444,0,0.227044

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [25]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:50:51,493] A new study created in memory with name: no-name-dbdd796a-d1db-4b76-bd28-b3019e00e21a

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848

[I 2024-04-13 23:50:52,485] A new study created in memory with name: no-name-74f33ede-7a79-4c5d-9558-e192f351efb7

Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:50:52,439] Trial 0 finished with value: 0.7580419822915472 and parameters: {}. Best is trial 0 with value: 0.7580419822915472.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7580419822915472], datetime_start=datetime.datetime(2024, 4, 13, 23, 50, 51, 609787), datetime_complete=datetime.datetime(2024, 4, 13, 23, 50, 52, 438223), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7580419822915472

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1841011974655529
Fold 2 IBS: 0.16232564718800943
Fold 3 IBS: 0.16363945158036763
Fold 4 IBS: 0.1454766840436639
Fold 5 IBS: 0.25454696204754557
[I 2024-04-13 23:50:53,672] Trial 0 finished with value: 0.18201798846502787 and parameters: {}. Best is trial 0 with value: 0.18201798846502787.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18201798846502787], datetime_start=datetime.datetime(2024, 4, 13, 23, 50, 52, 751330), datetime_complete=datetime.datetime(2024, 4, 13, 23, 50, 53, 671254), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18201798846502787

In [26]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [27]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.182

#### Test

In [28]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [29]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.621
IBS score: 0.261

In [30]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [31]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [32]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:50:56,033] A new study created in memory with name: no-name-704c7274-08b6-4823-a3ec-d2c537021e92

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5735930735930735
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.7352941176470589

[I 2024-04-13 23:50:56,542] A new study created in memory with name: no-name-92050c85-4218-48f2-9887-0a3bf81782a4

Fold 4 C-index: 0.7911392405063291
Fold 5 C-index: 0.6901408450704225
[I 2024-04-13 23:50:56,523] Trial 0 finished with value: 0.678569169649091 and parameters: {}. Best is trial 0 with value: 0.678569169649091.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.678569169649091], datetime_start=datetime.datetime(2024, 4, 13, 23, 50, 56, 72557), datetime_complete=datetime.datetime(2024, 4, 13, 23, 50, 56, 523394), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.678569169649091

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651907207446
Fold 2 IBS: 0.221577912661353
Fold 3 IBS: 0.20453594275105988
Fold 4 IBS: 0.22473802858598244
Fold 5 IBS: 0.2181243108260825
[I 2024-04-13 23:50:57,278] Trial 0 finished with value: 0.21659054277931045 and parameters: {}. Best is trial 0 with value: 0.21659054277931045.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054277931045], datetime_start=datetime.datetime(2024, 4, 13, 23, 50, 56, 688452), datetime_complete=datetime.datetime(2024, 4, 13, 23, 50, 57, 278492), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054277931045

In [33]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [34]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.679
train_ibs:  0.217

#### Test

In [35]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [36]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.647

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [37]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [38]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:50:57,864] A new study created in memory with name: no-name-c2b5a404-1880-4265-b4b4-8af68f51eade

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:50:59,815] Trial 0 finished with value: 0.7616105455699517 and parameters: {}. Best is trial 0 with value: 0.7616105455699517.

[I 2024-04-13 23:50:59,947] A new study created in memory with name: no-name-129a32f8-51b9-4865-b85b-25ed2de8b07d

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7616105455699517], datetime_start=datetime.datetime(2024, 4, 13, 23, 50, 57, 928788), datetime_complete=datetime.datetime(2024, 4, 13, 23, 50, 59, 815170), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7616105455699517

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.18447793741411198
Fold 2 IBS: 0.16484848693447857
Fold 3 IBS: 0.16251969838744912
Fold 4 IBS: 0.14389244536199547
Fold 5 IBS: 0.25277413959278777
[I 2024-04-13 23:51:01,726] Trial 0 finished with value: 0.18170254153816456 and parameters: {}. Best is trial 0 with value: 0.18170254153816456.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18170254153816456], datetime_start=datetime.datetime(2024, 4, 13, 23, 50, 59, 986605), datetime_complete=datetime.datetime(2024, 4, 13, 23, 51, 1, 725712), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18170254153816456

In [39]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [40]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.762
train_ibs:  0.182

#### Test

In [41]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [42]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.623

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.258

In [43]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [44]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:51:02,957] A new study created in memory with name: no-name-a0b9c934-78e3-428d-941b-b18016f3e466

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:04,494] Trial 0 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7607176884270945.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:51:05,826] Trial 1 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7607176884270945.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:51:07,053] Trial 2 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7607176884270945.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:08,025] Trial 3 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7607176884270945.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:09,238] Trial 4 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7607176884270945.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:51:10,443] Trial 5 finished with value: 0.7597787212909444 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7607176884270945.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:11,540] Trial 6 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:12,611] Trial 7 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:51:13,894] Trial 8 finished with value: 0.7597787212909444 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:51:15,708] Trial 9 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:17,735] Trial 10 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:20,196] Trial 11 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9981875333545975}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:23,168] Trial 12 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8230379330461087}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:51:25,961] Trial 13 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.05479180006479867}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:28,266] Trial 14 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8887005110166508}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:31,006] Trial 15 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.684568867978125}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:32,965] Trial 16 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.6050965337282124}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:34,987] Trial 17 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.830337351293805}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:36,464] Trial 18 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8760770624540267}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:37,753] Trial 19 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7667069175591638}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:39,830] Trial 20 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.6127580877814559}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:42,090] Trial 21 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9632315494528705}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:43,932] Trial 22 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9330597668033328}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:45,416] Trial 23 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8021540964020714}. Best is trial 6 with value: 0.7616105455699517.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:46,607] Trial 24 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9954177043436652}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:48,031] Trial 25 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.891573855041803}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:49,474] Trial 26 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.6628070200466962}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:50,928] Trial 27 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7392390880271466}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:52,386] Trial 28 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9098992645693764}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:51:53,232] Trial 29 finished with value: 0.6699583080853859 and parameters: {'l1_ratio': 0.016175696683504215}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:54,646] Trial 30 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8046265520719192}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:56,361] Trial 31 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9793496904597773}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:57,611] Trial 32 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9891329834464119}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:51:58,667] Trial 33 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8602844507263662}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:52:00,739] Trial 34 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.21553914253693035}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:02,208] Trial 35 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9340419076190084}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:04,023] Trial 36 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9998199123667609}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:05,503] Trial 37 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7671376716595687}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:52:07,250] Trial 38 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.30900749869662797}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:09,035] Trial 39 finished with value: 0.7597372962702318 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:52:11,045] Trial 40 finished with value: 0.7587983291340816 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:12,741] Trial 41 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9239368009217398}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:14,217] Trial 42 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8496524746504234}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:15,477] Trial 43 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8119687552544277}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:16,755] Trial 44 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9383913534820573}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:18,198] Trial 45 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.6949136613447529}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:19,815] Trial 46 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8743706209454807}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:21,569] Trial 47 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7567361722056829}. Best is trial 6 with value: 0.7616105455699517.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:22,985] Trial 48 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9468743846989455}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:24,457] Trial 49 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.6437567638801116}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:25,995] Trial 50 finished with value: 0.7597372962702318 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:27,406] Trial 51 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8844804007912933}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:29,718] Trial 52 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8311756464597346}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:31,246] Trial 53 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8996058061761224}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:32,350] Trial 54 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9630433112243934}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:33,633] Trial 55 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7914848845913222}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:34,898] Trial 56 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9047813349558873}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:36,283] Trial 57 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8539407551118643}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:37,834] Trial 58 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7308308637913911}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:39,376] Trial 59 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.950187703969787}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:40,518] Trial 60 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9731905844195062}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:42,037] Trial 61 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.6901901103147636}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:43,463] Trial 62 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8313480590194686}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:45,044] Trial 63 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.6604642738718455}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:47,843] Trial 64 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.5975413074014614}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:49,600] Trial 65 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9161189864492234}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:51,192] Trial 66 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.7108084648961989}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:52,661] Trial 67 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7873736681314538}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:52:54,431] Trial 68 finished with value: 0.7607591134478071 and parameters: {'l1_ratio': 0.5019386731317708}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:52:56,213] Trial 69 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:57,570] Trial 70 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9649165987909276}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:52:59,642] Trial 71 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9904637912345714}. Best is trial 6 with value: 0.7616105455699517.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:01,203] Trial 72 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8389039253978587}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:03,117] Trial 73 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8802512302862703}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:04,471] Trial 74 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7578988798484785}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:05,717] Trial 75 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9198005098902011}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:53:07,538] Trial 76 finished with value: 0.7588858641480872 and parameters: {'l1_ratio': 0.3870355975595541}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:08,723] Trial 77 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9970814609599292}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:09,894] Trial 78 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.6311836483175919}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:11,082] Trial 79 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:12,329] Trial 80 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8641439192534894}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:13,443] Trial 81 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9399352301048692}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:14,492] Trial 82 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8937829347060786}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:15,657] Trial 83 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.779732281256806}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:16,990] Trial 84 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.925781145603267}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:18,446] Trial 85 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9734788726392185}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:19,909] Trial 86 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.5820111522453231}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:21,181] Trial 87 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8608904571362473}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:23,102] Trial 88 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8068127324079318}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:25,605] Trial 89 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.9530817653814572}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:27,036] Trial 90 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7401467038788764}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:29,073] Trial 91 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.7109107580379483}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:30,759] Trial 92 finished with value: 0.7607176884270945 and parameters: {'l1_ratio': 0.6896867598764459}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:32,132] Trial 93 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7574175110817319}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:33,635] Trial 94 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8995968651985021}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:34,862] Trial 95 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8292977342924999}. Best is trial 6 with value: 0.7616105455699517.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:36,281] Trial 96 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.6651439791122344}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:37,594] Trial 97 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8746894730087278}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:38,934] Trial 98 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.7867224652205768}. Best is trial 6 with value: 0.7616105455699517.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853

[I 2024-04-13 23:53:40,288] A new study created in memory with name: no-name-a6e2fadf-4609-40f0-936f-20306b6183c8

Fold 5 C-index: 0.647887323943662
[I 2024-04-13 23:53:40,247] Trial 99 finished with value: 0.7616105455699517 and parameters: {'l1_ratio': 0.8384810671799993}. Best is trial 6 with value: 0.7616105455699517.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.7616105455699517], datetime_start=datetime.datetime(2024, 4, 13, 23, 51, 10, 448205), datetime_complete=datetime.datetime(2024, 4, 13, 23, 51, 11, 539657), params={'l1_ratio': 0.980766121964777}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.7616105455699517

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18453114438656854
Fold 2 IBS: 0.16524846540781152
Fold 3 IBS: 0.16240371602679218
Fold 4 IBS: 0.14396719787048534
Fold 5 IBS: 0.25249548312425735
[I 2024-04-13 23:53:42,802] Trial 0 finished with value: 0.181729201363183 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.181729201363183.
Fold 1 IBS: 0.18468460851287097
Fold 2 IBS: 0.1654620040344674
Fold 3 IBS: 0.16229687195493578
Fold 4 IBS: 0.14397721472972333
Fold 5 IBS: 0.25220067836759713
[I 2024-04-13 23:53:47,032] Trial 1 finished with value: 0.18172427551991893 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.18172427551991893.
Fold 1 IBS: 0.18470448380172774
Fold 2 IBS: 0.16529155765895748
Fold 3 IBS: 0.16221726179755092
Fold 4 IBS: 0.1439337100543988
Fold 5 IBS: 0.25205159057623044
[I 2024-04-13 23:53:49,216] Trial 2 finished with value: 0.18163972077777307 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.18460855039522736
Fold 2 IBS: 0.16532229230216558
Fold 3 IBS: 0.16239906850103059
Fold 4 IBS: 0.14392899468882953
Fold 5 IBS: 0.2522521720731841
[I 2024-04-13 23:53:52,296] Trial 3 finished with value: 0.1817022155920874 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.18455850612311314
Fold 2 IBS: 0.1651633018483501
Fold 3 IBS: 0.16245035832350263
Fold 4 IBS: 0.1438739884377563
Fold 5 IBS: 0.252580385691129
[I 2024-04-13 23:53:56,611] Trial 4 finished with value: 0.18172530808477022 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.1846106469910691
Fold 2 IBS: 0.1654682538885036
Fold 3 IBS: 0.16224906476388967
Fold 4 IBS: 0.14397572997720418
Fold 5 IBS: 0.252160617074117
[I 2024-04-13 23:53:59,379] Trial 5 finished with value: 0.18169286253895672 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.1844872408470913
Fold 2 IBS: 0.16489541481910602
Fold 3 IBS: 0.16248981816424946
Fold 4 IBS: 0.1438659587634692
Fold 5 IBS: 0.25271973097285705
[I 2024-04-13 23:54:01,060] Trial 6 finished with value: 0.1816916327133546 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.184584336614235
Fold 2 IBS: 0.16529351149327562
Fold 3 IBS: 0.1623790922882594
Fold 4 IBS: 0.14394593544877113
Fold 5 IBS: 0.25245055374826075
[I 2024-04-13 23:54:02,934] Trial 7 finished with value: 0.1817306859185604 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.18458858276092882
Fold 2 IBS: 0.16541232151788213
Fold 3 IBS: 0.1623171218373384
Fold 4 IBS: 0.14388065062422106
Fold 5 IBS: 0.2522908783661601
[I 2024-04-13 23:54:04,552] Trial 8 finished with value: 0.18169791102130609 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.18464292072029598
Fold 2 IBS: 0.16542261759258198
Fold 3 IBS: 0.16225840780249798
Fold 4 IBS: 0.14400432014538872
Fold 5 IBS: 0.25216972301533946
[I 2024-04-13 23:54:06,731] Trial 9 finished with value: 0.1816995978552208 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.18475866368043234
Fold 2 IBS: 0.16532685912260067
Fold 3 IBS: 0.16219942088528888
Fold 4 IBS: 0.14400295807870242
Fold 5 IBS: 0.2519900617823971
[I 2024-04-13 23:54:10,034] Trial 10 finished with value: 0.18165559270988427 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.21371564123711817
Fold 2 IBS: 0.2210461289279127
Fold 3 IBS: 0.2039966199577392
Fold 4 IBS: 0.22323679694160914
Fold 5 IBS: 0.251996516779589
[I 2024-04-13 23:54:11,926] Trial 11 finished with value: 0.22279834076879362 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.1847593347416989
Fold 2 IBS: 0.16532955916994474
Fold 3 IBS: 0.16219805474580906
Fold 4 IBS: 0.14400159469052515
Fold 5 IBS: 0.2519875580311396
[I 2024-04-13 23:54:15,018] Trial 12 finished with value: 0.1816552202758235 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.18471420924935314
Fold 2 IBS: 0.1654565561242042
Fold 3 IBS: 0.16221234680938995
Fold 4 IBS: 0.1439519100215972
Fold 5 IBS: 0.25203482833333296
[I 2024-04-13 23:54:17,626] Trial 13 finished with value: 0.1816739701075755 and parameters: {'l1_ratio': 0.18973443002790857}. Best is trial 2 with value: 0.18163972077777307.
Fold 1 IBS: 0.1847203817353946
Fold 2 IBS: 0.16527558191046346
Fold 3 IBS: 0.16219887876309788
Fold 4 IBS: 0.14393854876789458
Fold 5 IBS: 0.25201013135492956
[I 2024-04-13 23:54:22,748] Trial 14 finished with value: 0.18162870450635601 and parameters: {'l1_ratio': 0.18786252244562493}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18470351498066515
Fold 2 IBS: 0.16528748976768007
Fold 3 IBS: 0.16221132483848405
Fold 4 IBS: 0.14393583100181376
Fold 5 IBS: 0.25205551936068843
[I 2024-04-13 23:54:27,381] Trial 15 finished with value: 0.18163873598986627 and parameters: {'l1_ratio': 0.22728492373134654}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18464509021525982
Fold 2 IBS: 0.16556077733262295
Fold 3 IBS: 0.1622605760383917
Fold 4 IBS: 0.14394042783431008
Fold 5 IBS: 0.2521538195567269
[I 2024-04-13 23:54:30,716] Trial 16 finished with value: 0.18171213819546228 and parameters: {'l1_ratio': 0.30518868850921266}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18469974590944166
Fold 2 IBS: 0.16542507103576667
Fold 3 IBS: 0.1622409108976294
Fold 4 IBS: 0.14398320244023108
Fold 5 IBS: 0.252077612182465
[I 2024-04-13 23:54:33,669] Trial 17 finished with value: 0.18168530849310677 and parameters: {'l1_ratio': 0.17746878538762725}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18463616941730437
Fold 2 IBS: 0.16554895664088712
Fold 3 IBS: 0.1622954161819048
Fold 4 IBS: 0.14394933609608723
Fold 5 IBS: 0.2522093263474697
[I 2024-04-13 23:54:37,598] Trial 18 finished with value: 0.1817278409367306 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18458267407959653
Fold 2 IBS: 0.16548143743394622
Fold 3 IBS: 0.16235750745245933
Fold 4 IBS: 0.14385727416549796
Fold 5 IBS: 0.25238092067197376
[I 2024-04-13 23:54:39,659] Trial 19 finished with value: 0.18173196276069475 and parameters: {'l1_ratio': 0.5788194142882274}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.1847502715245056
Fold 2 IBS: 0.16538252842300538
Fold 3 IBS: 0.1622225421746314
Fold 4 IBS: 0.14400408893263827
Fold 5 IBS: 0.2520332432294087
[I 2024-04-13 23:54:42,262] Trial 20 finished with value: 0.18167853485683788 and parameters: {'l1_ratio': 0.1224880115209049}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18469740970239806
Fold 2 IBS: 0.165476156628116
Fold 3 IBS: 0.16225615994847845
Fold 4 IBS: 0.14396460001648767
Fold 5 IBS: 0.25211667827255463
[I 2024-04-13 23:54:45,086] Trial 21 finished with value: 0.18170220091360698 and parameters: {'l1_ratio': 0.2335832881544163}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.1847533936609927
Fold 2 IBS: 0.16518523055782752
Fold 3 IBS: 0.16221336934676558
Fold 4 IBS: 0.22240153669898136
Fold 5 IBS: 0.25201031675731284
[I 2024-04-13 23:54:48,211] Trial 22 finished with value: 0.197312769404376 and parameters: {'l1_ratio': 0.019591279397018047}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.1846714644750251
Fold 2 IBS: 0.1653760885989729
Fold 3 IBS: 0.16219709920106046
Fold 4 IBS: 0.1440159789292663
Fold 5 IBS: 0.25203889400762286
[I 2024-04-13 23:54:53,681] Trial 23 finished with value: 0.18165990504238955 and parameters: {'l1_ratio': 0.2675624193052421}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.184715639689124
Fold 2 IBS: 0.16541204649013327
Fold 3 IBS: 0.16220097365254305
Fold 4 IBS: 0.14396053159402594
Fold 5 IBS: 0.25200511452510294
[I 2024-04-13 23:54:56,071] Trial 24 finished with value: 0.18165886119018584 and parameters: {'l1_ratio': 0.14416996731229645}. Best is trial 14 with value: 0.18162870450635601.

Fold 1 IBS: 0.1846419084746135
Fold 2 IBS: 0.1652944985172605
Fold 3 IBS: 0.16228874983173466
Fold 4 IBS: 0.14392367586563456
Fold 5 IBS: 0.25220359364742023
[I 2024-04-13 23:54:58,056] Trial 25 finished with value: 0.1816704852673327 and parameters: {'l1_ratio': 0.36669581947150787}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18469363577411685
Fold 2 IBS: 0.1655319352864163
Fold 3 IBS: 0.16223724598073103
Fold 4 IBS: 0.1439481123428458
Fold 5 IBS: 0.2521007582494757
[I 2024-04-13 23:55:00,169] Trial 26 finished with value: 0.18170233752671713 and parameters: {'l1_ratio': 0.2526650212752227}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.1846028666869189
Fold 2 IBS: 0.16546047982658618
Fold 3 IBS: 0.16228397756521096
Fold 4 IBS: 0.14398240301244816
Fold 5 IBS: 0.2522301018918221
[I 2024-04-13 23:55:03,820] Trial 27 finished with value: 0.18171196579659724 and parameters: {'l1_ratio': 0.4698787873988891}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.18449400604879726
Fold 2 IBS: 0.1649218153022053
Fold 3 IBS: 0.1625660067962638
Fold 4 IBS: 0.14384386842298763
Fold 5 IBS: 0.2526735362306307
[I 2024-04-13 23:55:05,815] Trial 28 finished with value: 0.18169984656017696 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.1847022527298853
Fold 2 IBS: 0.165475599635838
Fold 3 IBS: 0.16224171713396157
Fold 4 IBS: 0.1439624397194934
Fold 5 IBS: 0.2520861279983263
[I 2024-04-13 23:55:08,381] Trial 29 finished with value: 0.18169362744350093 and parameters: {'l1_ratio': 0.21176076332307217}. Best is trial 14 with value: 0.18162870450635601.
Fold 1 IBS: 0.1847416825233198
Fold 2 IBS: 0.16525523452855795
Fold 3 IBS: 0.16224633663682364
Fold 4 IBS: 0.1439376855709062
Fold 5 IBS: 0.251870072479286
[I 2024-04-13 23:55:11,838] Trial 30 finished with value: 0.18161020234777872 and parameters: {'l1_ratio': 0.07983212362470739}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18473325769322474
Fold 2 IBS: 0.16528159055838318
Fold 3 IBS: 0.16224512897456173
Fold 4 IBS: 0.1439264365634391
Fold 5 IBS: 0.2520826733838911
[I 2024-04-13 23:55:14,571] Trial 31 finished with value: 0.18165381743469994 and parameters: {'l1_ratio': 0.09563502017676988}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847705530205998
Fold 2 IBS: 0.16527967398955057
Fold 3 IBS: 0.16219008339682503
Fold 4 IBS: 0.14400952429682742
Fold 5 IBS: 0.25196515569468536
[I 2024-04-13 23:55:17,073] Trial 32 finished with value: 0.18164299807969764 and parameters: {'l1_ratio': 0.04388065779803152}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18472650118968412
Fold 2 IBS: 0.1652845392286198
Fold 3 IBS: 0.16229190060509513
Fold 4 IBS: 0.14393226790976194
Fold 5 IBS: 0.2519767068963922
[I 2024-04-13 23:55:19,948] Trial 33 finished with value: 0.1816423831659106 and parameters: {'l1_ratio': 0.16990684183668314}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18465667917329134
Fold 2 IBS: 0.16530428540700967
Fold 3 IBS: 0.16223278135356828
Fold 4 IBS: 0.14391351048569961
Fold 5 IBS: 0.2521030101559742
[I 2024-04-13 23:55:21,716] Trial 34 finished with value: 0.18164205331510863 and parameters: {'l1_ratio': 0.29909857612392643}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18473145275852892
Fold 2 IBS: 0.16528997975962348
Fold 3 IBS: 0.16227920697484952
Fold 4 IBS: 0.14392792653304498
Fold 5 IBS: 0.25194886033698843
[I 2024-04-13 23:55:23,852] Trial 35 finished with value: 0.18163548527260706 and parameters: {'l1_ratio': 0.15392809581544425}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18473507491917493
Fold 2 IBS: 0.16533427877710422
Fold 3 IBS: 0.16225551709354677
Fold 4 IBS: 0.14390070033615426
Fold 5 IBS: 0.25209603364155975
[I 2024-04-13 23:55:26,061] Trial 36 finished with value: 0.18166432095350799 and parameters: {'l1_ratio': 0.137413062090172}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475500125923675
Fold 2 IBS: 0.1652836448184098
Fold 3 IBS: 0.1622229859146851
Fold 4 IBS: 0.1439173786125061
Fold 5 IBS: 0.2520206977433267
[I 2024-04-13 23:55:30,549] Trial 37 finished with value: 0.18163994166963288 and parameters: {'l1_ratio': 0.054080360666361016}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1845105743423744
Fold 2 IBS: 0.1649607287040008
Fold 3 IBS: 0.16249856166009574
Fold 4 IBS: 0.1439707509990181
Fold 5 IBS: 0.2526988953520969
[I 2024-04-13 23:55:33,782] Trial 38 finished with value: 0.1817279022115172 and parameters: {'l1_ratio': 0.8598478847078105}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18460473400522914
Fold 2 IBS: 0.16529860024118573
Fold 3 IBS: 0.16229917250177703
Fold 4 IBS: 0.14394041699130497
Fold 5 IBS: 0.2522755151301919
[I 2024-04-13 23:55:36,013] Trial 39 finished with value: 0.18168368777393776 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.21394470666367207
Fold 2 IBS: 0.2215268342023619
Fold 3 IBS: 0.20448435515040012
Fold 4 IBS: 0.2245934802096446
Fold 5 IBS: 0.2180743721277252
[I 2024-04-13 23:55:37,333] Trial 40 finished with value: 0.2165247496707608 and parameters: {'l1_ratio': 0.001132991623918722}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1846798082777439
Fold 2 IBS: 0.16538992424726412
Fold 3 IBS: 0.1622983797382742
Fold 4 IBS: 0.14400689346424728
Fold 5 IBS: 0.25219407021721646
[I 2024-04-13 23:55:40,580] Trial 41 finished with value: 0.1817138151889492 and parameters: {'l1_ratio': 0.24116391207823773}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18462681148193688
Fold 2 IBS: 0.16554968728330047
Fold 3 IBS: 0.16233145575494384
Fold 4 IBS: 0.1439437645874328
Fold 5 IBS: 0.2522890681636427
[I 2024-04-13 23:55:42,553] Trial 42 finished with value: 0.18174815745425135 and parameters: {'l1_ratio': 0.4110412455597975}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1846451368026805
Fold 2 IBS: 0.16559342919829087
Fold 3 IBS: 0.16226611004940716
Fold 4 IBS: 0.14392822782317727
Fold 5 IBS: 0.25216993613314037
[I 2024-04-13 23:55:44,278] Trial 43 finished with value: 0.18172056800133923 and parameters: {'l1_ratio': 0.33354613923169874}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18474324504442483
Fold 2 IBS: 0.16535368954118523
Fold 3 IBS: 0.1622368749221031
Fold 4 IBS: 0.14401127257669366
Fold 5 IBS: 0.2520595427189344
[I 2024-04-13 23:55:45,914] Trial 44 finished with value: 0.18168092496066826 and parameters: {'l1_ratio': 0.12383739608704253}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18470289226063047
Fold 2 IBS: 0.16545812456735118
Fold 3 IBS: 0.1622369046876038
Fold 4 IBS: 0.14396913148954552
Fold 5 IBS: 0.2520736127781401
[I 2024-04-13 23:55:47,676] Trial 45 finished with value: 0.1816881331566542 and parameters: {'l1_ratio': 0.19326060990066518}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.184753915847355
Fold 2 IBS: 0.16531658467771165
Fold 3 IBS: 0.16221036801035985
Fold 4 IBS: 0.14400163622863427
Fold 5 IBS: 0.2520051559652371
[I 2024-04-13 23:55:50,506] Trial 46 finished with value: 0.18165753214585958 and parameters: {'l1_ratio': 0.09256149213756812}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18467152732546424
Fold 2 IBS: 0.1654098383858512
Fold 3 IBS: 0.1623222192527778
Fold 4 IBS: 0.14400228311522711
Fold 5 IBS: 0.25204611040737557
[I 2024-04-13 23:55:53,412] Trial 47 finished with value: 0.1816903956973392 and parameters: {'l1_ratio': 0.29176366796418535}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18456143296494043
Fold 2 IBS: 0.16540926400554767
Fold 3 IBS: 0.16242730785579665
Fold 4 IBS: 0.1438901360389438
Fold 5 IBS: 0.2525253582137969
[I 2024-04-13 23:55:56,242] Trial 48 finished with value: 0.18176269981580512 and parameters: {'l1_ratio': 0.656728753620996}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18462986408228915
Fold 2 IBS: 0.16531549711645566
Fold 3 IBS: 0.1623363515610507
Fold 4 IBS: 0.14391850466085215

Fold 5 IBS: 0.25230593732216156
[I 2024-04-13 23:55:58,762] Trial 49 finished with value: 0.18170123094856183 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18470245288853446
Fold 2 IBS: 0.16542012670485762
Fold 3 IBS: 0.16223225976599265
Fold 4 IBS: 0.14398376501312177
Fold 5 IBS: 0.2520586853382567
[I 2024-04-13 23:56:02,356] Trial 50 finished with value: 0.18167945794215265 and parameters: {'l1_ratio': 0.16135214111227222}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18478452362497247
Fold 2 IBS: 0.16533923850932122
Fold 3 IBS: 0.16216272631119075
Fold 4 IBS: 0.14397924340216348
Fold 5 IBS: 0.2519158103076707
[I 2024-04-13 23:56:07,038] Trial 51 finished with value: 0.1816363084310637 and parameters: {'l1_ratio': 0.047112746267578}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18477217738020543
Fold 2 IBS: 0.16534260435166545
Fold 3 IBS: 0.16216796460414784
Fold 4 IBS: 0.1439794641997428
Fold 5 IBS: 0.25192732262451234
[I 2024-04-13 23:56:10,127] Trial 52 finished with value: 0.18163790663205476 and parameters: {'l1_ratio': 0.05682143567687864}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.184776537834374
Fold 2 IBS: 0.16530781343806772
Fold 3 IBS: 0.16217874679647398
Fold 4 IBS: 0.1439956792506804
Fold 5 IBS: 0.2519451984945941
[I 2024-04-13 23:56:12,550] Trial 53 finished with value: 0.1816407951628381 and parameters: {'l1_ratio': 0.04768782790375564}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847367455619132
Fold 2 IBS: 0.1652373142308594
Fold 3 IBS: 0.16225636672609786
Fold 4 IBS: 0.14394840512164883
Fold 5 IBS: 0.25188978365447245
[I 2024-04-13 23:56:14,710] Trial 54 finished with value: 0.18161372305899837 and parameters: {'l1_ratio': 0.0804646144391998}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18474558755002393
Fold 2 IBS: 0.16530543767661893
Fold 3 IBS: 0.16222396286919774
Fold 4 IBS: 0.1439077964477111
Fold 5 IBS: 0.2520257689824725
[I 2024-04-13 23:56:17,410] Trial 55 finished with value: 0.18164171070520485 and parameters: {'l1_ratio': 0.07120189667713113}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.184746303159818
Fold 2 IBS: 0.16535445138448115
Fold 3 IBS: 0.162228882259456
Fold 4 IBS: 0.1440096010370346
Fold 5 IBS: 0.25204278174488964
[I 2024-04-13 23:56:19,652] Trial 56 finished with value: 0.18167640391713585 and parameters: {'l1_ratio': 0.1124881037599342}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18477139317917288
Fold 2 IBS: 0.1652627526126731
Fold 3 IBS: 0.16218554715399014
Fold 4 IBS: 0.22179572387308455
Fold 5 IBS: 0.2519532164865034
[I 2024-04-13 23:56:22,771] Trial 57 finished with value: 0.1971937266610848 and parameters: {'l1_ratio': 0.025152623679174844}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475171307192165
Fold 2 IBS: 0.16528855251396526
Fold 3 IBS: 0.16223240848936687
Fold 4 IBS: 0.14391905264632784
Fold 5 IBS: 0.25204126071570254
[I 2024-04-13 23:56:26,808] Trial 58 finished with value: 0.18164659748745685 and parameters: {'l1_ratio': 0.07167090542239538}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1846951672489802
Fold 2 IBS: 0.16537234733906445
Fold 3 IBS: 0.16224581336788235
Fold 4 IBS: 0.1440051922023716
Fold 5 IBS: 0.25208077300099924
[I 2024-04-13 23:56:29,564] Trial 59 finished with value: 0.1816798586318596 and parameters: {'l1_ratio': 0.14913651562055352}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.21380935991633138
Fold 2 IBS: 0.22127678218536842
Fold 3 IBS: 0.20423116620254445
Fold 4 IBS: 0.22388694075077611
Fold 5 IBS: 0.21783169166273142
[I 2024-04-13 23:56:30,471] Trial 60 finished with value: 0.21620718814355033 and parameters: {'l1_ratio': 0.006815145977246639}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18470110486351118
Fold 2 IBS: 0.16547048106860893
Fold 3 IBS: 0.16224423125059034
Fold 4 IBS: 0.1439649378869947
Fold 5 IBS: 0.25209074192935177
[I 2024-04-13 23:56:33,271] Trial 61 finished with value: 0.18169429939981138 and parameters: {'l1_ratio': 0.21215884753114367}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475432554242352
Fold 2 IBS: 0.16538652378390634
Fold 3 IBS: 0.16221252720766596
Fold 4 IBS: 0.14400038737805804
Fold 5 IBS: 0.25201276417812135
[I 2024-04-13 23:56:35,968] Trial 62 finished with value: 0.18167330561803502 and parameters: {'l1_ratio': 0.11109271841386723}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18471433391178177
Fold 2 IBS: 0.1654571012870292
Fold 3 IBS: 0.16221207459088913
Fold 4 IBS: 0.1439516399952882
Fold 5 IBS: 0.2520343292863334
[I 2024-04-13 23:56:38,537] Trial 63 finished with value: 0.18167389581426435 and parameters: {'l1_ratio': 0.18969627193528962}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18478575041228046
Fold 2 IBS: 0.16533949319031863
Fold 3 IBS: 0.16215957570136968
Fold 4 IBS: 0.14397854694944673
Fold 5 IBS: 0.2519092034424852
[I 2024-04-13 23:56:40,790] Trial 64 finished with value: 0.18163451393918018 and parameters: {'l1_ratio': 0.042874724453767464}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847612842867781
Fold 2 IBS: 0.16524738182932602
Fold 3 IBS: 0.1622082488118465
Fold 4 IBS: 0.1439097043882783
Fold 5 IBS: 0.25199117886682665
[I 2024-04-13 23:56:43,978] Trial 65 finished with value: 0.18162355963661111 and parameters: {'l1_ratio': 0.04059064034102505}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475029355277411
Fold 2 IBS: 0.1652550923822674
Fold 3 IBS: 0.16222353858976754
Fold 4 IBS: 0.1439261429199055
Fold 5 IBS: 0.2520337536333701
[I 2024-04-13 23:56:46,684] Trial 66 finished with value: 0.18163776421561692 and parameters: {'l1_ratio': 0.0452982400305106}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847430386127249
Fold 2 IBS: 0.16527942120927538
Fold 3 IBS: 0.16224621413038637
Fold 4 IBS: 0.1439275953465743
Fold 5 IBS: 0.2520846543204452
[I 2024-04-13 23:56:49,538] Trial 67 finished with value: 0.18165618472388126 and parameters: {'l1_ratio': 0.09571598693668741}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18478828908131745
Fold 2 IBS: 0.16537315422882382
Fold 3 IBS: 0.16224305757175822
Fold 4 IBS: 0.22165589942913877
Fold 5 IBS: 0.25185328488809317
[I 2024-04-13 23:56:51,661] Trial 68 finished with value: 0.1971827370398263 and parameters: {'l1_ratio': 0.026467016455877967}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847439967125009
Fold 2 IBS: 0.16537103205589673
Fold 3 IBS: 0.1622372926779153
Fold 4 IBS: 0.1440043141781446
Fold 5 IBS: 0.2520626128369582
[I 2024-04-13 23:56:54,001] Trial 69 finished with value: 0.18168384969228316 and parameters: {'l1_ratio': 0.13550122611748075}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475213627808487
Fold 2 IBS: 0.16529026024993496
Fold 3 IBS: 0.16223155442104395
Fold 4 IBS: 0.14391594813298564
Fold 5 IBS: 0.2520396943418746
[I 2024-04-13 23:56:56,154] Trial 70 finished with value: 0.1816459186847848 and parameters: {'l1_ratio': 0.07162322934028346}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18478039761301304
Fold 2 IBS: 0.16535555933458937
Fold 3 IBS: 0.16214879855543496
Fold 4 IBS: 0.1439697904749011
Fold 5 IBS: 0.2518883440383542
[I 2024-04-13 23:56:58,523] Trial 71 finished with value: 0.18162857800325855 and parameters: {'l1_ratio': 0.038785789393142076}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.2138924854760772
Fold 2 IBS: 0.22143763018090556
Fold 3 IBS: 0.2043941889450486
Fold 4 IBS: 0.22434132293421982
Fold 5 IBS: 0.2179874672070191
[I 2024-04-13 23:56:59,257] Trial 72 finished with value: 0.21641061894865404 and parameters: {'l1_ratio': 0.003131691266785676}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475813111538972
Fold 2 IBS: 0.1653399953843988
Fold 3 IBS: 0.16222312062242758
Fold 4 IBS: 0.14401439509623257
Fold 5 IBS: 0.2520285620332205
[I 2024-04-13 23:57:01,561] Trial 73 finished with value: 0.18167284085033386 and parameters: {'l1_ratio': 0.09347046460879041}. Best is trial 30 with value: 0.18161020234777872.

Fold 1 IBS: 0.1846902594757335
Fold 2 IBS: 0.16536597636556824
Fold 3 IBS: 0.16225902288308378
Fold 4 IBS: 0.14388690304010943
Fold 5 IBS: 0.25210777682637997
[I 2024-04-13 23:57:03,682] Trial 74 finished with value: 0.181661987718175 and parameters: {'l1_ratio': 0.16467357394326002}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18476230415188769
Fold 2 IBS: 0.16522952890214168
Fold 3 IBS: 0.16220423073517465
Fold 4 IBS: 0.2214956757734565
Fold 5 IBS: 0.2519814159106742
[I 2024-04-13 23:57:05,605] Trial 75 finished with value: 0.19713463109466695 and parameters: {'l1_ratio': 0.027987763370412786}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475088015796817
Fold 2 IBS: 0.1653300916459578
Fold 3 IBS: 0.1622410024981052
Fold 4 IBS: 0.14389969927773982
Fold 5 IBS: 0.2520650150970549
[I 2024-04-13 23:57:07,663] Trial 76 finished with value: 0.18165733773536516 and parameters: {'l1_ratio': 0.11354223262588735}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18476532617140032
Fold 2 IBS: 0.16529522948319283
Fold 3 IBS: 0.16220484311351788
Fold 4 IBS: 0.14400915679592605
Fold 5 IBS: 0.25199067848013235
[I 2024-04-13 23:57:09,735] Trial 77 finished with value: 0.1816530468088339 and parameters: {'l1_ratio': 0.07015987599501794}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475838696027502
Fold 2 IBS: 0.16526775909594948
Fold 3 IBS: 0.16219342304933712
Fold 4 IBS: 0.14401512917227788
Fold 5 IBS: 0.25197052310914986
[I 2024-04-13 23:57:11,519] Trial 78 finished with value: 0.18164104427739786 and parameters: {'l1_ratio': 0.04012829357177}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18472626331998154
Fold 2 IBS: 0.16544251045469466
Fold 3 IBS: 0.16217579792524048
Fold 4 IBS: 0.14395050845344096
Fold 5 IBS: 0.2519560578455993
[I 2024-04-13 23:57:13,548] Trial 79 finished with value: 0.18165022759979138 and parameters: {'l1_ratio': 0.12936445773458088}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18467582567489357
Fold 2 IBS: 0.16540321392996488
Fold 3 IBS: 0.16230789914344565
Fold 4 IBS: 0.14400288951962498
Fold 5 IBS: 0.25201279158936507
[I 2024-04-13 23:57:15,698] Trial 80 finished with value: 0.1816805239714588 and parameters: {'l1_ratio': 0.26486376808668544}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475428242446396
Fold 2 IBS: 0.1652711451870366
Fold 3 IBS: 0.16222299241411653
Fold 4 IBS: 0.14391745747676565
Fold 5 IBS: 0.252018981570915
[I 2024-04-13 23:57:18,721] Trial 81 finished with value: 0.18163697181465954 and parameters: {'l1_ratio': 0.045013181313408285}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.213952845263778
Fold 2 IBS: 0.2215401148937326
Fold 3 IBS: 0.20449777109289374
Fold 4 IBS: 0.22463105214693588
Fold 5 IBS: 0.21808734415290612
[I 2024-04-13 23:57:19,480] Trial 82 finished with value: 0.21654182551004925 and parameters: {'l1_ratio': 0.0008376292550848208}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18476070311706738
Fold 2 IBS: 0.16533506326308428
Fold 3 IBS: 0.16219526968972806
Fold 4 IBS: 0.14399881513150672
Fold 5 IBS: 0.25198245336940567
[I 2024-04-13 23:57:21,539] Trial 83 finished with value: 0.18165446091415843 and parameters: {'l1_ratio': 0.08356335334611324}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847731963145405
Fold 2 IBS: 0.16530843277247118
Fold 3 IBS: 0.16218622054802045
Fold 4 IBS: 0.1440001109395138
Fold 5 IBS: 0.2519598088947373
[I 2024-04-13 23:57:24,757] Trial 84 finished with value: 0.18164555389385667 and parameters: {'l1_ratio': 0.05256871753668111}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847114853801287
Fold 2 IBS: 0.16546479335785164
Fold 3 IBS: 0.16221368297400146
Fold 4 IBS: 0.1439502015791808
Fold 5 IBS: 0.2520490494794641
[I 2024-04-13 23:57:26,757] Trial 85 finished with value: 0.18167784255412536 and parameters: {'l1_ratio': 0.20861002163685416}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18474037582200017
Fold 2 IBS: 0.1653702291155135
Fold 3 IBS: 0.1622468620574881
Fold 4 IBS: 0.14400623788230407
Fold 5 IBS: 0.2520826963332956
[I 2024-04-13 23:57:29,188] Trial 86 finished with value: 0.18168928024212028 and parameters: {'l1_ratio': 0.14925626198135558}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18473508856582163
Fold 2 IBS: 0.16524713427060372
Fold 3 IBS: 0.1622623603387183
Fold 4 IBS: 0.14394483637212074
Fold 5 IBS: 0.2519047160076596
[I 2024-04-13 23:57:32,280] Trial 87 finished with value: 0.18161882711098482 and parameters: {'l1_ratio': 0.09693514253297876}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18474066275545672
Fold 2 IBS: 0.1652795494749382
Fold 3 IBS: 0.16225243493400932
Fold 4 IBS: 0.14392851282105565
Fold 5 IBS: 0.2520977767178061
[I 2024-04-13 23:57:35,636] Trial 88 finished with value: 0.1816597873406532 and parameters: {'l1_ratio': 0.10528642727332173}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18469315574943607
Fold 2 IBS: 0.16537885855957352
Fold 3 IBS: 0.16225265827989588
Fold 4 IBS: 0.1440036394414304
Fold 5 IBS: 0.25209610699771007
[I 2024-04-13 23:57:38,559] Trial 89 finished with value: 0.18168488380560918 and parameters: {'l1_ratio': 0.16387285354810893}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.18475904335449367
Fold 2 IBS: 0.16532563760074595
Fold 3 IBS: 0.16221862919202545
Fold 4 IBS: 0.14401901153941796
Fold 5 IBS: 0.25201729535844614
[I 2024-04-13 23:57:41,124] Trial 90 finished with value: 0.18166792340902585 and parameters: {'l1_ratio': 0.07767338475672722}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847864756344163
Fold 2 IBS: 0.16531986194772946
Fold 3 IBS: 0.16215478421719706
Fold 4 IBS: 0.222092664055511
Fold 5 IBS: 0.2518963626533775
[I 2024-04-13 23:57:43,125] Trial 91 finished with value: 0.19725002970164626 and parameters: {'l1_ratio': 0.022399971149629556}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.184592639173445
Fold 2 IBS: 0.16548468309067987
Fold 3 IBS: 0.16231982992752583
Fold 4 IBS: 0.14398649172045289
Fold 5 IBS: 0.2523020193550229
[I 2024-04-13 23:57:45,327] Trial 92 finished with value: 0.1817371326534253 and parameters: {'l1_ratio': 0.5210631568623558}. Best is trial 30 with value: 0.18161020234777872.
Fold 1 IBS: 0.1847418692595349
Fold 2 IBS: 0.16523617235499571
Fold 3 IBS: 0.16224289979606007
Fold 4 IBS: 0.14394586082424085
Fold 5 IBS: 0.25185956921814184
[I 2024-04-13 23:57:47,669] Trial 93 finished with value: 0.1816052742905947 and parameters: {'l1_ratio': 0.06055283354521909}. Best is trial 93 with value: 0.1816052742905947.
Fold 1 IBS: 0.1847299337178942
Fold 2 IBS: 0.16525626185918915
Fold 3 IBS: 0.1622778330113729
Fold 4 IBS: 0.1439424000001386
Fold 5 IBS: 0.2519411138331727
[I 2024-04-13 23:57:50,121] Trial 94 finished with value: 0.1816295084843535 and parameters: {'l1_ratio': 0.12859071063478156}. Best is trial 93 with value: 0.1816052742905947.
Fold 1 IBS: 0.1847204566432651
Fold 2 IBS: 0.1653200743780988
Fold 3 IBS: 0.16228529373509645
Fold 4 IBS: 0.14391517638811496
Fold 5 IBS: 0.25196691251134373
[I 2024-04-13 23:57:52,316] Trial 95 finished with value: 0.18164158273118383 and parameters: {'l1_ratio': 0.18466570752195532}. Best is trial 93 with value: 0.1816052742905947.
Fold 1 IBS: 0.18453391988181078
Fold 2 IBS: 0.1653190759080958
Fold 3 IBS: 0.16241187817419178
Fold 4 IBS: 0.14393695327283632
Fold 5 IBS: 0.2525247547930586
[I 2024-04-13 23:57:54,648] Trial 96 finished with value: 0.18174531640599864 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 93 with value: 0.1816052742905947.
Fold 1 IBS: 0.1847335096493986
Fold 2 IBS: 0.1652846170843668
Fold 3 IBS: 0.16227267353527286
Fold 4 IBS: 0.1439293081350757
Fold 5 IBS: 0.2519333798309212
[I 2024-04-13 23:57:57,994] Trial 97 finished with value: 0.181630697647007 and parameters: {'l1_ratio': 0.14007107776615244}. Best is trial 93 with value: 0.1816052742905947.
Fold 1 IBS: 0.18471306624462938
Fold 2 IBS: 0.16537251365166328
Fold 3 IBS: 0.16220245803477118
Fold 4 IBS: 0.1439768924692811

Fold 5 IBS: 0.25200298551120875
[I 2024-04-13 23:58:00,658] Trial 98 finished with value: 0.18165358318231073 and parameters: {'l1_ratio': 0.12064011750017613}. Best is trial 93 with value: 0.1816052742905947.
Fold 1 IBS: 0.1847590492138749
Fold 2 IBS: 0.16533727031398002
Fold 3 IBS: 0.16219991339788398
Fold 4 IBS: 0.14399871750414447
Fold 5 IBS: 0.2519925543172047
[I 2024-04-13 23:58:03,370] Trial 99 finished with value: 0.18165750094941763 and parameters: {'l1_ratio': 0.09182782178528937}. Best is trial 93 with value: 0.1816052742905947.


* Best trial for IBS:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.1816052742905947], datetime_start=datetime.datetime(2024, 4, 13, 23, 57, 45, 336712), datetime_complete=datetime.datetime(2024, 4, 13, 23, 57, 47, 663191), params={'l1_ratio': 0.06055283354521909}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=93, value=None)


* Best Score for IBS:
 0.1816052742905947

In [45]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [46]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.762
train_ibs:  0.182

#### Test

In [47]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [48]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.980766121964777)

test_cindex : 0.623

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.06055283354521909)

test_ibs:  0.257

In [49]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [80]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:50:01,821] A new study created in memory with name: no-name-9dd939a2-b21b-4d99-9422-89f710f64d48

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:50:06,069] Trial 0 finished with value: 0.7374642476806279 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7374642476806279.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:50:10,169] Trial 1 finished with value: 0.7417933476328991 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7417933476328991.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:50:12,672] Trial 2 finished with value: 0.7449466136719683 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:14,067] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:15,569] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:50:21,791] Trial 5 finished with value: 0.7370918767756701 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:50:31,125] Trial 6 finished with value: 0.717975364994861 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:36,347] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:50:45,818] Trial 8 finished with value: 0.5286384976525822 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:50:50,339] Trial 9 finished with value: 0.7243820169034241 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:50,678] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:50:52,661] Trial 11 finished with value: 0.7360255859827844 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7377450980392157
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:50:54,346] Trial 12 finished with value: 0.7302513420966695 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8206827027986038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13254323337687263, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:56,952] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12557358503422417, 'warm_start': False}. Best is trial 2 with value: 0.7449466136719683.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.7300469483568075
[I 2024-04-14 12:50:57,551] Trial 14 finished with value: 0.78448790823644 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.8234674775526319, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17965973103920196, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.7394366197183099
[I 2024-04-14 12:50:58,126] Trial 15 finished with value: 0.7815967757911443 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.8805479398876049, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2038091856577342, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:58,284] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.44827686549014745, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3769624693898471, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.7300469483568075
[I 2024-04-14 12:50:58,815] Trial 17 finished with value: 0.777033470765249 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.8699768148803853, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2109291215895694, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:50:59,443] Trial 18 finished with value: 0.7647138144022418 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.7065727699530516
[I 2024-04-14 12:51:00,170] Trial 19 finished with value: 0.770401431837261 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.7102028208948052, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20814181636759924, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.6737089201877934
[I 2024-04-14 12:51:00,798] Trial 20 finished with value: 0.7668825157617788 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.5018171832362744, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08479692838686262, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7300469483568075
[I 2024-04-14 12:51:01,490] Trial 21 finished with value: 0.7749133505652702 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 79, 'oob_score': True, 'max_samples': 0.8559180518336, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20237344578116867, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6971830985915493
[I 2024-04-14 12:51:02,486] Trial 22 finished with value: 0.7772777242268566 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.8668980444038114, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2656107389686847, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:51:03,671] Trial 23 finished with value: 0.7665973402237926 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 126, 'oob_score': True, 'max_samples': 0.7725956179157487, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27274357491764534, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:51:04,074] Trial 24 finished with value: 0.7353972528734991 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 36, 'oob_score': True, 'max_samples': 0.665565318795521, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.25340023675443346, 'warm_start': True}. Best is trial 14 with value: 0.78448790823644.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:51:05,186] Trial 25 finished with value: 0.7961598700486046 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.9905575179118002, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1765027205557836, 'warm_start': True}. Best is trial 25 with value: 0.7961598700486046.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:51:06,606] Trial 26 finished with value: 0.7971355772328867 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.9975011000521463, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1793544990151499, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7018779342723005
[I 2024-04-14 12:51:08,213] Trial 27 finished with value: 0.7782285574443071 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.9935216820715808, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1639558245055341, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 12:51:09,868] Trial 28 finished with value: 0.7941103283320492 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9974148446210768, 'max_features': None, 'min_weight_fraction_leaf': 0.08169225267476016, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:51:11,657] Trial 29 finished with value: 0.7903497748148677 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9299090867463176, 'max_features': None, 'min_weight_fraction_leaf': 0.07933993102267647, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:51:12,911] Trial 30 finished with value: 0.7838038349912649 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9958592591261876, 'max_features': None, 'min_weight_fraction_leaf': 0.08786071130535064, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:51:14,391] Trial 31 finished with value: 0.7903497748148677 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9305854444171414, 'max_features': None, 'min_weight_fraction_leaf': 0.06660828348237688, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.

Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7112676056338029
[I 2024-04-14 12:51:16,208] Trial 32 finished with value: 0.7880052222675161 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.9241435345198769, 'max_features': None, 'min_weight_fraction_leaf': 0.005704708830120669, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7183098591549296
[I 2024-04-14 12:51:18,147] Trial 33 finished with value: 0.7853285377669115 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.7342970632385599, 'max_features': None, 'min_weight_fraction_leaf': 0.10250939595308128, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:51:21,467] Trial 34 finished with value: 0.7830650868023185 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.915430415766172, 'max_features': None, 'min_weight_fraction_leaf': 0.04858799135091821, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:51:23,526] Trial 35 finished with value: 0.7965083288943708 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 226, 'oob_score': True, 'max_samples': 0.9517255628510397, 'max_features': None, 'min_weight_fraction_leaf': 0.13042852589300377, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:51:25,460] Trial 36 finished with value: 0.7914835461243283 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.9909550079245623, 'max_features': None, 'min_weight_fraction_leaf': 0.14828709700048928, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.687793427230047
[I 2024-04-14 12:51:30,852] Trial 37 finished with value: 0.7761091861986695 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.7780313613072668, 'max_features': None, 'min_weight_fraction_leaf': 0.2301245357770187, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.6971830985915493
[I 2024-04-14 12:51:33,518] Trial 38 finished with value: 0.7776150614056867 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 293, 'oob_score': True, 'max_samples': 0.8920282134072196, 'max_features': None, 'min_weight_fraction_leaf': 0.10975855167395827, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:51:35,033] Trial 39 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1876174049262129, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 12:51:39,061] Trial 40 finished with value: 0.7943330445680923 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.8338411656267665, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13768564478674078, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 12:51:43,111] Trial 41 finished with value: 0.796315886360379 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.9480325449609365, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13744684312143918, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:51:46,786] Trial 42 finished with value: 0.7964380279170453 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.9507553646525975, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1505960010830525, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7018779342723005
[I 2024-04-14 12:51:50,633] Trial 43 finished with value: 0.785752408469182 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.946874254182162, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2293455277335382, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:51:53,602] Trial 44 finished with value: 0.7952162179398738 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.9543525577617925, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1756716540998339, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:51:55,461] Trial 45 finished with value: 0.7943723360833337 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 496, 'oob_score': False, 'max_samples': 0.6872343345153323, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11440071556228917, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:52:02,779] Trial 46 finished with value: 0.7480556909792881 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.9061151624668697, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1584117376743104, 'warm_start': False}. Best is trial 26 with value: 0.7971355772328867.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7065727699530516
[I 2024-04-14 12:52:04,518] Trial 47 finished with value: 0.7866694565960713 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 20, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.6046381486093608, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13127839443828754, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:52:13,406] Trial 48 finished with value: 0.7447739909753428 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 411, 'oob_score': True, 'max_samples': 0.7987023723930657, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1850055137002767, 'warm_start': False}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:52:15,245] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.9579088388117846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:52:16,945] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.1200736185519305, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.29921027900073766, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:52:21,469] Trial 51 finished with value: 0.7953037529538795 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.9605920388344767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1715267572507908, 'warm_start': True}. Best is trial 26 with value: 0.7971355772328867.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:52:27,202] Trial 52 finished with value: 0.8007721695138452 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 438, 'oob_score': True, 'max_samples': 0.8479395403922309, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1451522624096633, 'warm_start': True}. Best is trial 52 with value: 0.8007721695138452.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:52:33,239] Trial 53 finished with value: 0.7981696296486471 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 479, 'oob_score': True, 'max_samples': 0.8503988521325447, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14787992559038418, 'warm_start': True}. Best is trial 52 with value: 0.8007721695138452.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:52:37,198] Trial 54 finished with value: 0.7970527271914617 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.8388578991250121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1445567717424093, 'warm_start': True}. Best is trial 52 with value: 0.8007721695138452.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:52:40,675] Trial 55 finished with value: 0.8083069135043116 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 402, 'oob_score': True, 'max_samples': 0.8442853280038067, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.043272763549276644, 'warm_start': True}. Best is trial 55 with value: 0.8083069135043116.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:52:47,206] Trial 56 finished with value: 0.7380683157475051 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.7527783316725879, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04314727608475457, 'warm_start': False}. Best is trial 55 with value: 0.8083069135043116.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:52:50,133] Trial 57 finished with value: 0.8055436723547584 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.8339441872290747, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028671238940433906, 'warm_start': True}. Best is trial 55 with value: 0.8083069135043116.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:52:52,600] Trial 58 finished with value: 0.8044681949182856 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.8444556955317604, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022966022108241738, 'warm_start': True}. Best is trial 55 with value: 0.8083069135043116.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:52:54,038] Trial 59 finished with value: 0.8117562005190738 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 356, 'oob_score': False, 'max_samples': 0.6356557361515882, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012458336804366255, 'warm_start': True}. Best is trial 59 with value: 0.8117562005190738.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:52:58,482] Trial 60 finished with value: 0.7370389483043255 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 356, 'oob_score': False, 'max_samples': 0.5508151660317097, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0280839425472214, 'warm_start': False}. Best is trial 59 with value: 0.8117562005190738.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:52:59,631] Trial 61 finished with value: 0.8074486629041153 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.7873587581720837, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0033183176028544516, 'warm_start': True}. Best is trial 59 with value: 0.8117562005190738.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:53:00,761] Trial 62 finished with value: 0.8107758083622111 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.6360926848355443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007037942522186006, 'warm_start': True}. Best is trial 59 with value: 0.8117562005190738.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:53:02,312] Trial 63 finished with value: 0.8107758083622111 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.6437222036296154, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006534810027934122, 'warm_start': True}. Best is trial 59 with value: 0.8117562005190738.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:53:03,261] Trial 64 finished with value: 0.8109584286558267 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.6281188443760009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007230008961256887, 'warm_start': True}. Best is trial 59 with value: 0.8117562005190738.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:53:04,201] Trial 65 finished with value: 0.808058677205951 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.6282156254684211, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002454762789035612, 'warm_start': True}. Best is trial 59 with value: 0.8117562005190738.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:53:05,173] Trial 66 finished with value: 0.8138823710897347 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.6400260611186078, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009690253916566138, 'warm_start': True}. Best is trial 66 with value: 0.8138823710897347.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:53:06,025] Trial 67 finished with value: 0.8214163410141119 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.64489763430965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0018056666954531422, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:53:06,856] Trial 68 finished with value: 0.800249690226015 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.5657901575768084, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06660034156891091, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:53:07,673] Trial 69 finished with value: 0.8157584856824787 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 277, 'oob_score': False, 'max_samples': 0.6539800063695161, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04018651643392136, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:53:08,513] Trial 70 finished with value: 0.8108150998774525 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.5129798268311018, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0187586203370647, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 12:53:09,457] Trial 71 finished with value: 0.8119147682979577 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.5045212500597642, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.016044293191016065, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 12:53:10,802] Trial 72 finished with value: 0.8047986456612826 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.5216703130188548, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05739270610501532, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:53:11,788] Trial 73 finished with value: 0.809327642789883 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 277, 'oob_score': False, 'max_samples': 0.46209545693943666, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.036987534362706895, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:53:12,707] Trial 74 finished with value: 0.8091687611850847 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.5758909570881829, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01606735840207221, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:53:13,494] Trial 75 finished with value: 0.8142095042444927 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.6942026279404012, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01830237709022292, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:53:14,848] Trial 76 finished with value: 0.806765934627145 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.6942382958706024, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06167845635901249, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:53:15,858] Trial 77 finished with value: 0.8083224663307356 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.5240184794127251, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03368105077544726, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:53:16,865] Trial 78 finished with value: 0.8122169786811304 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.6673018959932915, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050257360168013146, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:53:17,939] Trial 79 finished with value: 0.8020007979690685 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.6711059536303813, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0966028034715678, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:53:21,906] Trial 80 finished with value: 0.7344483641849744 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.7228236995007038, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.049973040527189844, 'warm_start': False}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 12:53:22,864] Trial 81 finished with value: 0.8156237950617126 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.5906995178226834, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014628452892626823, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:53:23,705] Trial 82 finished with value: 0.8092419274554341 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.5874718560973374, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.016725757213021664, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:53:24,557] Trial 83 finished with value: 0.7992596142980767 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.6560129395230687, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07496318301050596, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:53:25,316] Trial 84 finished with value: 0.8166070525115993 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.622211132580016, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03513573292269464, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:53:26,087] Trial 85 finished with value: 0.8150706201377129 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.6992076600097027, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038237503343555135, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:53:26,865] Trial 86 finished with value: 0.8122682259422189 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.6969944062374953, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03464910697921324, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:53:27,704] Trial 87 finished with value: 0.814204819271912 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.6986325580668623, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05358666999276549, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:53:28,609] Trial 88 finished with value: 0.8030637263414417 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.6965813977816991, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0729288356461803, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:53:29,793] Trial 89 finished with value: 0.8148098347752526 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.7566026755042131, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.035389752991871304, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:53:30,669] Trial 90 finished with value: 0.8028886563134305 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'max_samples': 0.7437562862712784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09428912237189335, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:53:31,508] Trial 91 finished with value: 0.8143436015470062 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.7118498576826194, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0342566986407525, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:53:32,249] Trial 92 finished with value: 0.8100050927760203 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.7596480014042472, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05747947619566461, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:53:33,071] Trial 93 finished with value: 0.8209576580514699 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.7194168697903819, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.037685546546483865, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 12:53:33,787] Trial 94 finished with value: 0.8190775902736984 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.7257642902714595, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038003079275912593, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:53:34,483] Trial 95 finished with value: 0.8207192439934856 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.7163105212382224, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04108165381986016, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:53:35,142] Trial 96 finished with value: 0.8206046527024237 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.7242789884533413, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04024240667390669, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:53:35,864] Trial 97 finished with value: 0.8167245090956852 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.6128426563566747, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04408046501783188, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:53:36,452] Trial 98 finished with value: 0.8019716081865411 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.6131677677598052, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07257922829329011, 'warm_start': True}. Best is trial 67 with value: 0.8214163410141119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8649789029535865

[I 2024-04-14 12:53:38,589] A new study created in memory with name: no-name-f077b942-74c7-48f8-b89f-9c5b50ae6f5b

Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:53:38,577] Trial 99 finished with value: 0.7326212248785476 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.7252939469352987, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0433744847670862, 'warm_start': False}. Best is trial 67 with value: 0.8214163410141119.


* Best trial for C-index:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.8214163410141119], datetime_start=datetime.datetime(2024, 4, 14, 12, 53, 5, 186817), datetime_complete=datetime.datetime(2024, 4, 14, 12, 53, 6, 25038), params={'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.64489763430965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0018056666954531422, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=67, value=None)


* Best Score for C-index:
 0.8214163410141119

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1765425410693478
Fold 2 IBS: 0.24819831112027577
Fold 3 IBS: 0.16905619117689974
Fold 4 IBS: 0.15989013259586596
Fold 5 IBS: 0.2341343611371509
[I 2024-04-14 12:53:42,106] Trial 0 finished with value: 0.19756430741990802 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19756430741990802.
Fold 1 IBS: 0.1870340061909586
Fold 2 IBS: 0.19706230633017718
Fold 3 IBS: 0.17530606330964119
Fold 4 IBS: 0.1706424050847566
Fold 5 IBS: 0.2107518069699854
[I 2024-04-14 12:53:43,005] Trial 1 finished with value: 0.1881593175771038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1881593175771038.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-14 12:53:43,636] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1881593175771038.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-14 12:53:45,995] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1881593175771038.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-14 12:53:47,880] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1881593175771038.
Fold 1 IBS: 0.1814908280932156
Fold 2 IBS: 0.21118339517343693
Fold 3 IBS: 0.1668361456277034
Fold 4 IBS: 0.14876086772357566
Fold 5 IBS: 0.21934604459675225
[I 2024-04-14 12:53:50,547] Trial 5 finished with value: 0.18552345624293676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.17776335418738823
Fold 2 IBS: 0.2009604013972194
Fold 3 IBS: 0.16893715246185653
Fold 4 IBS: 0.1673046329626332
Fold 5 IBS: 0.223125735190684
[I 2024-04-14 12:53:53,201] Trial 6 finished with value: 0.1876182552399563 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.2110834623546096
Fold 2 IBS: 0.21761793738328675
Fold 3 IBS: 0.20366531069503524
Fold 4 IBS: 0.2192494915987301
Fold 5 IBS: 0.21527873796610802
[I 2024-04-14 12:53:56,220] Trial 7 finished with value: 0.21337898799955393 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-14 12:54:00,869] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.18294965611438302
Fold 2 IBS: 0.19797943310224636
Fold 3 IBS: 0.1732105185035738
Fold 4 IBS: 0.17571495826425115
Fold 5 IBS: 0.21141950424382666
[I 2024-04-14 12:54:01,864] Trial 9 finished with value: 0.18825481404565622 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-14 12:54:07,478] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.17625567248076215
Fold 2 IBS: 0.21428317699805313
Fold 3 IBS: 0.17138110677783402
Fold 4 IBS: 0.16674460263333116
Fold 5 IBS: 0.220417745427503
[I 2024-04-14 12:54:10,482] Trial 11 finished with value: 0.18981646086349668 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.17694927144847272
Fold 2 IBS: 0.20074114488563094
Fold 3 IBS: 0.1686244720383825
Fold 4 IBS: 0.16668549666658997
Fold 5 IBS: 0.22333848287680258
[I 2024-04-14 12:54:13,176] Trial 12 finished with value: 0.18726777358317576 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.18552345624293676.
Fold 1 IBS: 0.18263563976279182
Fold 2 IBS: 0.20497023190671426
Fold 3 IBS: 0.1703908797100092
Fold 4 IBS: 0.15590694703424848
Fold 5 IBS: 0.2134762472435216
[I 2024-04-14 12:54:15,016] Trial 13 finished with value: 0.18547598913145708 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.18392868993879666
Fold 2 IBS: 0.20387107735841797
Fold 3 IBS: 0.17166179820251476
Fold 4 IBS: 0.1618851085344132
Fold 5 IBS: 0.21176403020471524
[I 2024-04-14 12:54:16,618] Trial 14 finished with value: 0.18662214084777157 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.7340982458611074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11848568472491557}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.18325728115835663
Fold 2 IBS: 0.2024227995229229
Fold 3 IBS: 0.17163016130935274
Fold 4 IBS: 0.16594628701415273
Fold 5 IBS: 0.21123696268007747
[I 2024-04-14 12:54:18,398] Trial 15 finished with value: 0.18689869833697248 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 176, 'oob_score': False, 'max_samples': 0.6433402879135517, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07260059363971005}. Best is trial 13 with value: 0.18547598913145708.

Fold 1 IBS: 0.18117613320758266
Fold 2 IBS: 0.20671895796811615
Fold 3 IBS: 0.16975596971111143
Fold 4 IBS: 0.15238236415946904
Fold 5 IBS: 0.21862606782872482
[I 2024-04-14 12:54:21,888] Trial 16 finished with value: 0.18573189857500083 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7702473623171299, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00939201506667553}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.1892176732103934
Fold 2 IBS: 0.19741913112853085
Fold 3 IBS: 0.17594096494174094
Fold 4 IBS: 0.18186518475653926
Fold 5 IBS: 0.20847096667465248
[I 2024-04-14 12:54:23,433] Trial 17 finished with value: 0.19058278414237137 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.4182600161087171, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13640070966634157}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.1870131255455352
Fold 2 IBS: 0.19438878199999893
Fold 3 IBS: 0.170840233012318
Fold 4 IBS: 0.17625159369470345
Fold 5 IBS: 0.2105796063294819
[I 2024-04-14 12:54:23,940] Trial 18 finished with value: 0.1878146681164075 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.9690063146830306, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07731142289793183}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.17876636304786686
Fold 2 IBS: 0.21232047185850528
Fold 3 IBS: 0.17067187224950706
Fold 4 IBS: 0.16524044508270738
Fold 5 IBS: 0.21805505450046014
[I 2024-04-14 12:54:25,922] Trial 19 finished with value: 0.18901084134780935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.6209567227926299, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18131114927760594}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.18393343347502475
Fold 2 IBS: 0.19448099364363797
Fold 3 IBS: 0.17407694967339024
Fold 4 IBS: 0.173918487869169
Fold 5 IBS: 0.21019787046072624
[I 2024-04-14 12:54:27,163] Trial 20 finished with value: 0.18732154702438963 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.802088464198542, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.18111438722331707
Fold 2 IBS: 0.206910187671025
Fold 3 IBS: 0.16947802862555159
Fold 4 IBS: 0.15374684336915398
Fold 5 IBS: 0.21681334458950172
[I 2024-04-14 12:54:31,248] Trial 21 finished with value: 0.18561255829570988 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.7805759650965867, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011304728659679396}. Best is trial 13 with value: 0.18547598913145708.
Fold 1 IBS: 0.18052175624148536
Fold 2 IBS: 0.20697239323587857
Fold 3 IBS: 0.16889392201278078
Fold 4 IBS: 0.15125019269016846
Fold 5 IBS: 0.2173487460048099
[I 2024-04-14 12:54:35,697] Trial 22 finished with value: 0.1849974020370246 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.8533162629857436, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04763593467583403}. Best is trial 22 with value: 0.1849974020370246.
Fold 1 IBS: 0.18052663398392682
Fold 2 IBS: 0.20973061994027595
Fold 3 IBS: 0.16815047551963658
Fold 4 IBS: 0.14824691274258758
Fold 5 IBS: 0.21902138090501547
[I 2024-04-14 12:54:40,112] Trial 23 finished with value: 0.18513520461828847 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.925994927007364, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10649231085345325}. Best is trial 22 with value: 0.1849974020370246.
Fold 1 IBS: 0.1796787799048475
Fold 2 IBS: 0.2073973282365201
Fold 3 IBS: 0.1691404665299136
Fold 4 IBS: 0.15317069182351553
Fold 5 IBS: 0.216821580088766
[I 2024-04-14 12:54:44,240] Trial 24 finished with value: 0.18524176931671255 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.884719974003749, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12273625538909233}. Best is trial 22 with value: 0.1849974020370246.
Fold 1 IBS: 0.17805435705001987
Fold 2 IBS: 0.20802018955252746
Fold 3 IBS: 0.16752488279082925
Fold 4 IBS: 0.15052302951453786
Fold 5 IBS: 0.2164848145119478
[I 2024-04-14 12:54:48,611] Trial 25 finished with value: 0.18412145468397245 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9122425977981868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0448622369007813}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.1803736754340405
Fold 2 IBS: 0.20601113813373706
Fold 3 IBS: 0.1704635376098221
Fold 4 IBS: 0.15387902972084966
Fold 5 IBS: 0.21670273377491622
[I 2024-04-14 12:54:53,554] Trial 26 finished with value: 0.18548602293467312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.913356279536286, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04532455758176329}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18178808881412892
Fold 2 IBS: 0.2153822326475715
Fold 3 IBS: 0.16888389084782895
Fold 4 IBS: 0.1434682821598395
Fold 5 IBS: 0.22047054303462907
[I 2024-04-14 12:54:58,394] Trial 27 finished with value: 0.1859986075007996 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.9882340927492455, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04729227775330888}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.1794915175430337
Fold 2 IBS: 0.20774874256844872
Fold 3 IBS: 0.16962522908020775
Fold 4 IBS: 0.15614492209424738
Fold 5 IBS: 0.21526877243126816
[I 2024-04-14 12:55:01,877] Trial 28 finished with value: 0.18565583674344113 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.9296265163099574, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15568759023742668}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18337430790878684
Fold 2 IBS: 0.2187515022957401
Fold 3 IBS: 0.1716179422263352
Fold 4 IBS: 0.16661470284942817
Fold 5 IBS: 0.21815920193621272
[I 2024-04-14 12:55:06,122] Trial 29 finished with value: 0.1917035314433006 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.8654914434079262, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09310969677070244}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.1799814939931811
Fold 2 IBS: 0.20319626351764478
Fold 3 IBS: 0.1728944992404781
Fold 4 IBS: 0.17135551007054994
Fold 5 IBS: 0.21449875165645094
[I 2024-04-14 12:55:09,536] Trial 30 finished with value: 0.18838530369566098 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.702559468921227, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21579834457212488}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.17944446096511474
Fold 2 IBS: 0.2075178761763329
Fold 3 IBS: 0.16893044461305415
Fold 4 IBS: 0.15168618657424893

Fold 5 IBS: 0.21653408955576556
[I 2024-04-14 12:55:13,533] Trial 31 finished with value: 0.18482261157690327 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.8790885825126233, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10708995040974342}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18211270990315442
Fold 2 IBS: 0.21293412693121805
Fold 3 IBS: 0.16877883733430096
Fold 4 IBS: 0.1473017057119311
Fold 5 IBS: 0.2196556092852957
[I 2024-04-14 12:55:17,886] Trial 32 finished with value: 0.18615659783318006 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.9478519130685139, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03442061510351581}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18130817749522796
Fold 2 IBS: 0.20767042231170854
Fold 3 IBS: 0.16959391685402353
Fold 4 IBS: 0.14853413883498434
Fold 5 IBS: 0.21888870127604265
[I 2024-04-14 12:55:21,869] Trial 33 finished with value: 0.18519907135439742 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.83932540770328, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10013908494636117}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18081155520852213
Fold 2 IBS: 0.2071552659498613
Fold 3 IBS: 0.16985761087326753
Fold 4 IBS: 0.1585747736455902
Fold 5 IBS: 0.21633678437261072
[I 2024-04-14 12:55:25,661] Trial 34 finished with value: 0.18654719800997038 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8878735229014442, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1678730492824691}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18059095743292156
Fold 2 IBS: 0.21133814105747348
Fold 3 IBS: 0.16694216838149273
Fold 4 IBS: 0.14630917701310597
Fold 5 IBS: 0.22103678081939213
[I 2024-04-14 12:55:30,187] Trial 35 finished with value: 0.1852434449408772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.7209457085816128, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04617016290340701}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18785373252782728
Fold 2 IBS: 0.25705021612992357
Fold 3 IBS: 0.16952143467315922
Fold 4 IBS: 0.14213459087616387
Fold 5 IBS: 0.23326689204203344
[I 2024-04-14 12:55:35,656] Trial 36 finished with value: 0.1979653732498215 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.8262792448206581, 'max_features': None, 'min_weight_fraction_leaf': 0.14157572572524757}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18095369683384716
Fold 2 IBS: 0.2129330766833373
Fold 3 IBS: 0.16933694490623177
Fold 4 IBS: 0.1477684455148016
Fold 5 IBS: 0.22037476729665262
[I 2024-04-14 12:55:40,362] Trial 37 finished with value: 0.1862733862469741 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9366246283266213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10170238472077507}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18047752567216183
Fold 2 IBS: 0.20537273408398685
Fold 3 IBS: 0.1710939186311334
Fold 4 IBS: 0.16419790407148427
Fold 5 IBS: 0.21415633682387947
[I 2024-04-14 12:55:44,055] Trial 38 finished with value: 0.18705968385652916 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 446, 'oob_score': False, 'max_samples': 0.6024342581138471, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03769450829212376}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.18111194291334007
Fold 2 IBS: 0.26026612006355976
Fold 3 IBS: 0.16745028865848566
Fold 4 IBS: 0.1616520720880973
Fold 5 IBS: 0.23972059317537706
[I 2024-04-14 12:55:49,091] Trial 39 finished with value: 0.20204020337977197 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 425, 'oob_score': True, 'max_samples': 0.9915437844437803, 'max_features': None, 'min_weight_fraction_leaf': 0.24115524347733178}. Best is trial 25 with value: 0.18412145468397245.
Fold 1 IBS: 0.17987518667710933
Fold 2 IBS: 0.19944660743178824
Fold 3 IBS: 0.1709901332828782
Fold 4 IBS: 0.1621275729983858
Fold 5 IBS: 0.20565847554884062
[I 2024-04-14 12:55:52,003] Trial 40 finished with value: 0.18361959518780044 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.16382436256125943, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00248825843203139}. Best is trial 40 with value: 0.18361959518780044.
Fold 1 IBS: 0.2139417543029343
Fold 2 IBS: 0.2207344912060331
Fold 3 IBS: 0.20516452652973394
Fold 4 IBS: 0.22475248061555217
Fold 5 IBS: 0.2170054188508461
[I 2024-04-14 12:55:55,564] Trial 41 finished with value: 0.21631973430101992 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.10977881516685245, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06298124362196708}. Best is trial 40 with value: 0.18361959518780044.
Fold 1 IBS: 0.17834519946244679
Fold 2 IBS: 0.2004642617982364
Fold 3 IBS: 0.17029579359961491
Fold 4 IBS: 0.15746653793355408
Fold 5 IBS: 0.21268553971360052
[I 2024-04-14 12:55:58,494] Trial 42 finished with value: 0.18385146650149053 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 323, 'oob_score': False, 'max_samples': 0.21063752520092194, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0302594406458492}. Best is trial 40 with value: 0.18361959518780044.
Fold 1 IBS: 0.17950374586150278
Fold 2 IBS: 0.2054542259130081
Fold 3 IBS: 0.17141445191688154
Fold 4 IBS: 0.15125513282339162
Fold 5 IBS: 0.211043637859928
[I 2024-04-14 12:56:00,840] Trial 43 finished with value: 0.1837342388749424 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.20630400905589713, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.001287808397720941}. Best is trial 40 with value: 0.18361959518780044.
Fold 1 IBS: 0.1786377966115927
Fold 2 IBS: 0.20442201936585733
Fold 3 IBS: 0.17100783050581664
Fold 4 IBS: 0.14475017519488043
Fold 5 IBS: 0.21031260879925245
[I 2024-04-14 12:56:03,347] Trial 44 finished with value: 0.1818260860954799 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.19675274099712026, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.021712318484838747}. Best is trial 44 with value: 0.1818260860954799.
Fold 1 IBS: 0.18037512016957818
Fold 2 IBS: 0.20221059207736572
Fold 3 IBS: 0.17050028610900508
Fold 4 IBS: 0.14705308514197166
Fold 5 IBS: 0.2076780166075797
[I 2024-04-14 12:56:05,604] Trial 45 finished with value: 0.1815634200211001 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.1768569079500294, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.007862625324089361}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1790684969272146
Fold 2 IBS: 0.20711003707077838
Fold 3 IBS: 0.17216460405721706
Fold 4 IBS: 0.14632831721071532
Fold 5 IBS: 0.20650012149781294
[I 2024-04-14 12:56:07,848] Trial 46 finished with value: 0.18223431535274764 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.1873692143114088, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002630828916184458}. Best is trial 45 with value: 0.1815634200211001.

Fold 1 IBS: 0.17495436191336747
Fold 2 IBS: 0.21642383473182975
Fold 3 IBS: 0.16384945069352883
Fold 4 IBS: 0.1436363081374491
Fold 5 IBS: 0.20972010821870968
[I 2024-04-14 12:56:10,897] Trial 47 finished with value: 0.18171681273897697 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.2322220006496939, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.007963153823121693}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.2140400529445786
Fold 2 IBS: 0.22056189970139348
Fold 3 IBS: 0.20499151963199355
Fold 4 IBS: 0.22458997158755165
Fold 5 IBS: 0.2175710899843072
[I 2024-04-14 12:56:13,886] Trial 48 finished with value: 0.21635090676996488 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.21313526563727975, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17586703716161067
Fold 2 IBS: 0.21607926603451497
Fold 3 IBS: 0.17068289421826355
Fold 4 IBS: 0.143121025264353
Fold 5 IBS: 0.21394624542692622
[I 2024-04-14 12:56:17,171] Trial 49 finished with value: 0.18393929362113368 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.28937746021823385, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01749166598080426}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17776110070816226
Fold 2 IBS: 0.2077453076376041
Fold 3 IBS: 0.17127748230379286
Fold 4 IBS: 0.14859458783293242
Fold 5 IBS: 0.2062722745503208
[I 2024-04-14 12:56:20,607] Trial 50 finished with value: 0.1823301506065625 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 306, 'oob_score': True, 'max_samples': 0.15262685990049119, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002498924457612149}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1786472990358194
Fold 2 IBS: 0.20753939704211316
Fold 3 IBS: 0.17087791253105677
Fold 4 IBS: 0.1469882937393369
Fold 5 IBS: 0.2078631675022606
[I 2024-04-14 12:56:24,507] Trial 51 finished with value: 0.18238321397011736 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 315, 'oob_score': True, 'max_samples': 0.1617875616767638, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0010324531472149872}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17604972538957533
Fold 2 IBS: 0.21328116219893561
Fold 3 IBS: 0.16899894128920265
Fold 4 IBS: 0.1410312795300067
Fold 5 IBS: 0.218288028459129
[I 2024-04-14 12:56:28,373] Trial 52 finished with value: 0.18352982737336987 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.2944780091762996, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02226762102861183}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18671499661750793
Fold 2 IBS: 0.19581153033502965
Fold 3 IBS: 0.1752875235200677
Fold 4 IBS: 0.17916483529085822
Fold 5 IBS: 0.20639130414447376
[I 2024-04-14 12:56:32,364] Trial 53 finished with value: 0.18867403798158744 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.16318239729355083, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.060625778536648516}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1807880958686154
Fold 2 IBS: 0.21161549454737624
Fold 3 IBS: 0.16941980290824196
Fold 4 IBS: 0.15894253193550759
Fold 5 IBS: 0.21891247057244026
[I 2024-04-14 12:56:34,963] Trial 54 finished with value: 0.18793567916643628 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 190, 'oob_score': True, 'max_samples': 0.3632999540562435, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07759989252977602}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18096779583961084
Fold 2 IBS: 0.20837732753646565
Fold 3 IBS: 0.17142029710121823
Fold 4 IBS: 0.14993033742601874
Fold 5 IBS: 0.21294537667735097
[I 2024-04-14 12:56:38,418] Trial 55 finished with value: 0.18472822691613291 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.2539048067236002, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.022678838145908375}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1747401547313256
Fold 2 IBS: 0.20896805080604267
Fold 3 IBS: 0.1721150255471779
Fold 4 IBS: 0.1525983322892534
Fold 5 IBS: 0.20637511204453526
[I 2024-04-14 12:56:41,942] Trial 56 finished with value: 0.18295933508366696 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.14001768341487958, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0014371770825795768}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.21405389677578304
Fold 2 IBS: 0.22046455890455868
Fold 3 IBS: 0.20502237389812197
Fold 4 IBS: 0.22462359402720494
Fold 5 IBS: 0.2177754642860661
[I 2024-04-14 12:56:44,827] Trial 57 finished with value: 0.21638797757834696 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.24380363202162464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3781865060679536}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1817437298125766
Fold 2 IBS: 0.20842343998660634
Fold 3 IBS: 0.16823801815234354
Fold 4 IBS: 0.15454498714166562
Fold 5 IBS: 0.21544447030637034
[I 2024-04-14 12:56:47,225] Trial 58 finished with value: 0.1856789290799125 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.33285427066396645, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06222153755953749}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.175296324477639
Fold 2 IBS: 0.22579277130233708
Fold 3 IBS: 0.16660937383095165
Fold 4 IBS: 0.1409401288964402
Fold 5 IBS: 0.21934929409502693
[I 2024-04-14 12:56:49,854] Trial 59 finished with value: 0.18559757852047898 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 216, 'oob_score': True, 'max_samples': 0.48924513089459887, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02378365507504088}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.21398991396855938
Fold 2 IBS: 0.22048847486869563
Fold 3 IBS: 0.20536253790869324
Fold 4 IBS: 0.22494555619690937
Fold 5 IBS: 0.21723443598010544
[I 2024-04-14 12:56:53,279] Trial 60 finished with value: 0.2164041837845926 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.17378622228323415, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2886607381144328}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17203166786169813
Fold 2 IBS: 0.20871334806943811
Fold 3 IBS: 0.16899248188412652
Fold 4 IBS: 0.15853424092183796
Fold 5 IBS: 0.2042196242296455
[I 2024-04-14 12:56:56,792] Trial 61 finished with value: 0.18249827259334922 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.12726306143477256, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004072271551699679}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17723283367404688
Fold 2 IBS: 0.20016037145453042
Fold 3 IBS: 0.16901137703666577
Fold 4 IBS: 0.1545150049120191

Fold 5 IBS: 0.20788163499136067
[I 2024-04-14 12:57:00,050] Trial 62 finished with value: 0.18176024441372457 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.13095385188884462, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0017332514726945694}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1800536074338711
Fold 2 IBS: 0.20967741302207912
Fold 3 IBS: 0.16725955903309653
Fold 4 IBS: 0.14663083503834592
Fold 5 IBS: 0.21313464934329182
[I 2024-04-14 12:57:02,987] Trial 63 finished with value: 0.1833512127741369 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.25162324100280287, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02363064613843352}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.21400657323048353
Fold 2 IBS: 0.22060650898813897
Fold 3 IBS: 0.20499934200874667
Fold 4 IBS: 0.2246081254741279
Fold 5 IBS: 0.21746770441406485
[I 2024-04-14 12:57:05,986] Trial 64 finished with value: 0.21633765082311238 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.18668011680719016, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08155874790475678}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.19098709137691808
Fold 2 IBS: 0.1994852701015537
Fold 3 IBS: 0.182823285934765
Fold 4 IBS: 0.18886347929756506
Fold 5 IBS: 0.2050367225687577
[I 2024-04-14 12:57:09,780] Trial 65 finished with value: 0.1934391698559119 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.1423334865256598, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05909742720539081}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.21398135702700583
Fold 2 IBS: 0.220719339068164
Fold 3 IBS: 0.20507865971748823
Fold 4 IBS: 0.22453748519726197
Fold 5 IBS: 0.21765337655369602
[I 2024-04-14 12:57:13,970] Trial 66 finished with value: 0.21639404351272323 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.21973985773122928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4904781810386246}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18394167348806717
Fold 2 IBS: 0.20112132902746999
Fold 3 IBS: 0.1724819214901179
Fold 4 IBS: 0.1801532783247449
Fold 5 IBS: 0.20564152622368842
[I 2024-04-14 12:57:16,697] Trial 67 finished with value: 0.18866794571081766 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.10125726060185526, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03428468055295571}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17412764378343432
Fold 2 IBS: 0.20815679314714733
Fold 3 IBS: 0.17095790624874194
Fold 4 IBS: 0.15184643550669302
Fold 5 IBS: 0.21063531815836728
[I 2024-04-14 12:57:20,383] Trial 68 finished with value: 0.1831448193688768 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.28067110431218434, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014386965306668963}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18215971795079036
Fold 2 IBS: 0.20046391295967794
Fold 3 IBS: 0.17159519498956716
Fold 4 IBS: 0.16671489623510652
Fold 5 IBS: 0.2089730497203535
[I 2024-04-14 12:57:22,742] Trial 69 finished with value: 0.18598135437109908 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.18576927332867577, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05284048070019734}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1801797128032948
Fold 2 IBS: 0.21008699139619605
Fold 3 IBS: 0.1708062280978879
Fold 4 IBS: 0.14584417171099173
Fold 5 IBS: 0.218242373787815
[I 2024-04-14 12:57:26,262] Trial 70 finished with value: 0.1850318955592371 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.3510953040213296, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.036092003700609845}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17329106669458147
Fold 2 IBS: 0.20477645980244308
Fold 3 IBS: 0.17124955831589234
Fold 4 IBS: 0.15319309357671462
Fold 5 IBS: 0.20629714396493506
[I 2024-04-14 12:57:30,593] Trial 71 finished with value: 0.18176146447091332 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 292, 'oob_score': True, 'max_samples': 0.13735969854241348, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.389597807883066e-05}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1763457021102155
Fold 2 IBS: 0.20256754436666286
Fold 3 IBS: 0.1691891338367821
Fold 4 IBS: 0.1568875820111358
Fold 5 IBS: 0.2079587374486788
[I 2024-04-14 12:57:34,525] Trial 72 finished with value: 0.18258973995469502 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.14683188916838555, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001591913872570966}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17989187832416612
Fold 2 IBS: 0.20488781419213142
Fold 3 IBS: 0.17076718691431153
Fold 4 IBS: 0.14681405224393354
Fold 5 IBS: 0.21062929948263784
[I 2024-04-14 12:57:37,645] Trial 73 finished with value: 0.1825980462314361 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.19299455552434133, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.015548135270322274}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1809122251062721
Fold 2 IBS: 0.2059861601731184
Fold 3 IBS: 0.16883013298376276
Fold 4 IBS: 0.15341773269395692
Fold 5 IBS: 0.21563050881056428
[I 2024-04-14 12:57:39,539] Trial 74 finished with value: 0.1849553519535349 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 143, 'oob_score': True, 'max_samples': 0.2335726717436734, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.028106730951250714}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.2139450860244014
Fold 2 IBS: 0.2205186943064791
Fold 3 IBS: 0.20498166138263013
Fold 4 IBS: 0.22513856400064203
Fold 5 IBS: 0.21716548513038686
[I 2024-04-14 12:57:42,576] Trial 75 finished with value: 0.2163498981689079 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.12389646789719601, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08800201090840082}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17864972402219959
Fold 2 IBS: 0.21092222482673598
Fold 3 IBS: 0.16769759456224853
Fold 4 IBS: 0.15521580626984724
Fold 5 IBS: 0.21475905257892508
[I 2024-04-14 12:57:45,998] Trial 76 finished with value: 0.1854488804519913 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.16505481131164754, 'max_features': None, 'min_weight_fraction_leaf': 0.04360284039683277}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.21393929369491457
Fold 2 IBS: 0.2204131194458381
Fold 3 IBS: 0.20530798662137073
Fold 4 IBS: 0.22484881441119645
Fold 5 IBS: 0.21707247198314916
[I 2024-04-14 12:57:49,198] Trial 77 finished with value: 0.2163163372312938 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.11961813015541752, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06917861220622346}. Best is trial 45 with value: 0.1815634200211001.

Fold 1 IBS: 0.21402731898199354
Fold 2 IBS: 0.22070117517287685
Fold 3 IBS: 0.20511548294468487
Fold 4 IBS: 0.2245478065185114
Fold 5 IBS: 0.217888359190842
[I 2024-04-14 12:57:51,560] Trial 78 finished with value: 0.21645602856178173 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.2626685610811855, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014757495457958077}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1806026877192447
Fold 2 IBS: 0.20799751875386632
Fold 3 IBS: 0.16811000383356925
Fold 4 IBS: 0.15063751286152252
Fold 5 IBS: 0.21025312145554675
[I 2024-04-14 12:57:53,796] Trial 79 finished with value: 0.1835201689247499 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.15862553836501161, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005914919020195246}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18006512882504946
Fold 2 IBS: 0.21828239010314188
Fold 3 IBS: 0.17011995553362552
Fold 4 IBS: 0.14105006202820863
Fold 5 IBS: 0.21933539864639265
[I 2024-04-14 12:57:56,521] Trial 80 finished with value: 0.1857705870272836 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.40976679625409906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0364447560524294}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17501101480598966
Fold 2 IBS: 0.19878611009375738
Fold 3 IBS: 0.16975633929839246
Fold 4 IBS: 0.15755756928518516
Fold 5 IBS: 0.2073190452214067
[I 2024-04-14 12:57:59,894] Trial 81 finished with value: 0.18168601574094626 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 287, 'oob_score': True, 'max_samples': 0.134354458061236, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010065492170873184}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17754581893600496
Fold 2 IBS: 0.20230519434970887
Fold 3 IBS: 0.17195292496505707
Fold 4 IBS: 0.150163993606156
Fold 5 IBS: 0.2098198442264361
[I 2024-04-14 12:58:03,244] Trial 82 finished with value: 0.1823575552166726 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.19234512510754456, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.013570649011627304}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.21391807794360473
Fold 2 IBS: 0.2204652056184786
Fold 3 IBS: 0.2053057899374244
Fold 4 IBS: 0.22555192474787092
Fold 5 IBS: 0.21716672467603484
[I 2024-04-14 12:58:06,419] Trial 83 finished with value: 0.2164815445846827 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.10022768429637477, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05123330490105399}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17802919903022338
Fold 2 IBS: 0.20320012240191548
Fold 3 IBS: 0.17292163833669294
Fold 4 IBS: 0.15190205418029973
Fold 5 IBS: 0.20928522260503202
[I 2024-04-14 12:58:09,981] Trial 84 finished with value: 0.1830676473108327 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.19851125455822843, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014768509609939985}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18013736440000785
Fold 2 IBS: 0.20575460822555036
Fold 3 IBS: 0.17141769439678528
Fold 4 IBS: 0.1526213978497715
Fold 5 IBS: 0.2133098638590789
[I 2024-04-14 12:58:13,243] Trial 85 finished with value: 0.18464818574623876 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 267, 'oob_score': True, 'max_samples': 0.2213938098360282, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027753402068398512}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18811104141091242
Fold 2 IBS: 0.20268807807542738
Fold 3 IBS: 0.17623297816251998
Fold 4 IBS: 0.18427168645358236
Fold 5 IBS: 0.2080103291310232
[I 2024-04-14 12:58:16,499] Trial 86 finished with value: 0.1918628226466931 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.13600101669842116, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.039919233243829184}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.18156566794644763
Fold 2 IBS: 0.20204515040559326
Fold 3 IBS: 0.16988486428324182
Fold 4 IBS: 0.15572528077531558
Fold 5 IBS: 0.21020532364268352
[I 2024-04-14 12:58:19,667] Trial 87 finished with value: 0.18388525741065637 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.1824424521476345, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012849716264589934}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1851535361980291
Fold 2 IBS: 0.22184908628069788
Fold 3 IBS: 0.1725744330132203
Fold 4 IBS: 0.1420745016761497
Fold 5 IBS: 0.22101788856804924
[I 2024-04-14 12:58:22,107] Trial 88 finished with value: 0.18853388914722927 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.2312045833888045, 'max_features': None, 'min_weight_fraction_leaf': 0.027942975941487546}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17997054461230272
Fold 2 IBS: 0.20912971132881714
Fold 3 IBS: 0.16907566329704626
Fold 4 IBS: 0.1642923460763377
Fold 5 IBS: 0.21381211575646467
[I 2024-04-14 12:58:24,301] Trial 89 finished with value: 0.18725607621419368 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.31976806538014435, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0744578273764833}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.184721512932101
Fold 2 IBS: 0.19718973685415955
Fold 3 IBS: 0.17455951060773703
Fold 4 IBS: 0.17878644887935338
Fold 5 IBS: 0.20517327576208244
[I 2024-04-14 12:58:27,025] Trial 90 finished with value: 0.18808609700708667 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 207, 'oob_score': True, 'max_samples': 0.1425989642658093, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05386307125781323}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17839084873947125
Fold 2 IBS: 0.2132435345988867
Fold 3 IBS: 0.17027649262397215
Fold 4 IBS: 0.14335903875471173
Fold 5 IBS: 0.21526050694908297
[I 2024-04-14 12:58:31,869] Trial 91 finished with value: 0.18410608433322495 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.2724972104796945, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010436370879947874}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.17495351641498919
Fold 2 IBS: 0.21344975203915606
Fold 3 IBS: 0.17390730544641483
Fold 4 IBS: 0.14704223030119803
Fold 5 IBS: 0.20360742542056928
[I 2024-04-14 12:58:35,642] Trial 92 finished with value: 0.18259204592446548 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 307, 'oob_score': True, 'max_samples': 0.15570712846862958, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0007109308246209221}. Best is trial 45 with value: 0.1815634200211001.
Fold 1 IBS: 0.1788862656975729
Fold 2 IBS: 0.20111665761335334
Fold 3 IBS: 0.16888321038769805
Fold 4 IBS: 0.1492374254987549

Fold 5 IBS: 0.20690344572256106
[I 2024-04-14 12:58:37,438] Trial 93 finished with value: 0.18100540098398804 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.17462848601577474, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.022583095812189397}. Best is trial 93 with value: 0.18100540098398804.
Fold 1 IBS: 0.18217933960047325
Fold 2 IBS: 0.19851116575329222
Fold 3 IBS: 0.16573397532261386
Fold 4 IBS: 0.16479739333865168
Fold 5 IBS: 0.2091546360901032
[I 2024-04-14 12:58:39,363] Trial 94 finished with value: 0.18407530202102687 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.11867050486176221, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02004822428701594}. Best is trial 93 with value: 0.18100540098398804.
Fold 1 IBS: 0.18210665570530915
Fold 2 IBS: 0.2030849982206894
Fold 3 IBS: 0.1692683761212183
Fold 4 IBS: 0.1583086979106212
Fold 5 IBS: 0.21083871551618955
[I 2024-04-14 12:58:41,345] Trial 95 finished with value: 0.1847214886948055 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.20310947976175636, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04299887609296761}. Best is trial 93 with value: 0.18100540098398804.
Fold 1 IBS: 0.18118617392323483
Fold 2 IBS: 0.20275067073014197
Fold 3 IBS: 0.16931059715196095
Fold 4 IBS: 0.15243352706195598
Fold 5 IBS: 0.20964322725395873
[I 2024-04-14 12:58:43,089] Trial 96 finished with value: 0.1830648392242505 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 276, 'oob_score': False, 'max_samples': 0.17825310269550756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031064769930317686}. Best is trial 93 with value: 0.18100540098398804.
Fold 1 IBS: 0.176836728088081
Fold 2 IBS: 0.2166706152691494
Fold 3 IBS: 0.16440149778974655
Fold 4 IBS: 0.14378736209502052
Fold 5 IBS: 0.21467900101816711
[I 2024-04-14 12:58:45,035] Trial 97 finished with value: 0.18327504085203294 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.521538664132392, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01144784789131671}. Best is trial 93 with value: 0.18100540098398804.
Fold 1 IBS: 0.1848170713599718
Fold 2 IBS: 0.1998401801146307
Fold 3 IBS: 0.17316884887586176
Fold 4 IBS: 0.1705685923060159
Fold 5 IBS: 0.21184502821338166
[I 2024-04-14 12:58:46,752] Trial 98 finished with value: 0.18804794417397236 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.229668610069513, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06711783150072304}. Best is trial 93 with value: 0.18100540098398804.
Fold 1 IBS: 0.1837656791439776
Fold 2 IBS: 0.19992442043632824
Fold 3 IBS: 0.17033787974832185
Fold 4 IBS: 0.1652410878139218
Fold 5 IBS: 0.20968269401754697
[I 2024-04-14 12:58:48,695] Trial 99 finished with value: 0.18579035223201928 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.20158068259834722, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05205488394542502}. Best is trial 93 with value: 0.18100540098398804.


* Best trial for IBS:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.18100540098398804], datetime_start=datetime.datetime(2024, 4, 14, 12, 58, 35, 648258), datetime_complete=datetime.datetime(2024, 4, 14, 12, 58, 37, 437598), params={'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.17462848601577474, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.022583095812189397}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=93, value=None)


* Best Score for IBS:
 0.18100540098398804

In [81]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [82]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.821
train_ibs:  0.181

#### Test

In [83]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [84]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=20, max_features='auto', max_leaf_nodes=18,
                     max_samples=0.64489763430965, min_samples_leaf=1,
                     min_samples_split=10,
                     min_weight_fraction_leaf=0.0018056666954531422,
                     n_estimators=301, random_state=123, warm_start=True)

test_cindex:  0.683

RandomSurvivalForest(max_depth=9, max_features='log2', max_leaf_nodes=18,
                     max_samples=0.17462848601577474, min_samples_leaf=2,
                     min_samples_split=8,
                     min_weight_fraction_leaf=0.022583095812189397,
                     n_estimators=244, oob_score=True, random_state=123)

test_ibs:  0.201

In [85]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [86]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:58:49,890] A new study created in memory with name: no-name-d2d97d66-1d15-412f-b281-c37a52530cc3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6784037558685446
[I 2024-04-14 12:58:50,492] Trial 0 finished with value: 0.7787598038534689 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7787598038534689.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:51,882] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7787598038534689.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:58:54,861] Trial 2 finished with value: 0.7561199052547647 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7787598038534689.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6690140845070423
[I 2024-04-14 12:58:55,266] Trial 3 finished with value: 0.7694617913657626 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7787598038534689.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:56,324] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7787598038534689.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:57,620] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7787598038534689.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6737089201877934
[I 2024-04-14 12:58:58,430] Trial 6 finished with value: 0.7802868662821941 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.7802868662821941.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:59:00,189] Trial 7 finished with value: 0.7559338263498725 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.7802868662821941.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8602941176470589
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:59:00,298] Trial 8 finished with value: 0.7698679500568927 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.7802868662821941.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.7120535714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:59:03,866] Trial 9 finished with value: 0.755397747702624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.7802868662821941.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:59:05,180] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.7802868662821941.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:59:05,843] Trial 11 finished with value: 0.7671110922569647 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.7802868662821941.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:59:06,727] Trial 12 finished with value: 0.7832355192437597 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:59:07,571] Trial 13 finished with value: 0.7682189029844584 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:59:08,305] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:59:08,777] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.7832355192437597.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:59:09,631] Trial 16 finished with value: 0.7721988359964158 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6267605633802817
[I 2024-04-14 12:59:10,295] Trial 17 finished with value: 0.7590425969249918 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 12:59:10,624] Trial 18 finished with value: 0.7447831847126443 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:59:10,943] Trial 19 finished with value: 0.7798099848214948 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:59:11,449] Trial 20 finished with value: 0.7724697402583782 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:59:11,721] Trial 21 finished with value: 0.768890617135199 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.022958663817377156}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:59:11,973] Trial 22 finished with value: 0.770069917462763 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 85, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5833816310769062, 'min_weight_fraction_leaf': 0.08761267626836403}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:59:12,325] Trial 23 finished with value: 0.770765299081431 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.693714188909504, 'min_weight_fraction_leaf': 0.04814654754133644}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:59:12,713] Trial 24 finished with value: 0.7740775192230573 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4552125039171776, 'min_weight_fraction_leaf': 0.11651881132969055}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:59:13,596] Trial 25 finished with value: 0.7785301848660501 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.24513858603466832, 'min_weight_fraction_leaf': 0.004412430855635233}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:59:15,443] Trial 26 finished with value: 0.7576594469454421 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 208, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8893342713608914, 'min_weight_fraction_leaf': 0.04762335481390857}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7034313725490197
Fold 4 C-index: 0.6687763713080169
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 12:59:15,556] Trial 27 finished with value: 0.6720167728431102 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 1, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5183702854490568, 'min_weight_fraction_leaf': 0.0922591258144641}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:59:16,195] Trial 28 finished with value: 0.7673926850436766 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 314, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7205459764431101, 'min_weight_fraction_leaf': 0.15221571535635248}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6690140845070423
[I 2024-04-14 12:59:16,908] Trial 29 finished with value: 0.7747794376993248 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 399, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5921674629705332, 'min_weight_fraction_leaf': 0.10386261975214663}. Best is trial 12 with value: 0.7832355192437597.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6690140845070423
[I 2024-04-14 12:59:17,752] Trial 30 finished with value: 0.7846122286983481 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 30 with value: 0.7846122286983481.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:59:18,642] Trial 31 finished with value: 0.7861059424418075 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8597320351705271, 'min_weight_fraction_leaf': 0.03653370864131273}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:59:19,488] Trial 32 finished with value: 0.7837878528532598 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8497126078542253, 'min_weight_fraction_leaf': 0.07179554342829253}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6690140845070423
[I 2024-04-14 12:59:20,368] Trial 33 finished with value: 0.7838829381328699 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 454, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.848506007345319, 'min_weight_fraction_leaf': 0.07520052457980808}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:59:21,138] Trial 34 finished with value: 0.7804975146917063 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8381821235042005, 'min_weight_fraction_leaf': 0.06819764479676384}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:59:22,973] Trial 35 finished with value: 0.762614364434083 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.845188003971906, 'min_weight_fraction_leaf': 0.2603839838496317}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:59:25,534] Trial 36 finished with value: 0.7540086269438651 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 401, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9281304563646802, 'min_weight_fraction_leaf': 0.12234403644209754}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:59:26,350] Trial 37 finished with value: 0.7700650960071219 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8391339520990131, 'min_weight_fraction_leaf': 0.16855647223435075}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:59:27,002] Trial 38 finished with value: 0.7708197840555371 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 331, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7536815576651283, 'min_weight_fraction_leaf': 0.22752773294338688}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:59:31,537] Trial 39 finished with value: 0.7552978013844479 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7422995763960529, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:59:32,282] Trial 40 finished with value: 0.772991903734054 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8045006536350131, 'min_weight_fraction_leaf': 0.11284781288632736}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:59:33,300] Trial 41 finished with value: 0.7831404339641496 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9644824078037169, 'min_weight_fraction_leaf': 0.025454092526436694}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:59:34,115] Trial 42 finished with value: 0.7825747099760503 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9880585850715861, 'min_weight_fraction_leaf': 0.05321876117963818}. Best is trial 31 with value: 0.7861059424418075.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:59:35,210] Trial 43 finished with value: 0.7896433552350907 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9303044771385398, 'min_weight_fraction_leaf': 0.022073817105411248}. Best is trial 43 with value: 0.7896433552350907.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:59:35,966] Trial 44 finished with value: 0.7841664838190905 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9189156576452361, 'min_weight_fraction_leaf': 0.08794509624413283}. Best is trial 43 with value: 0.7896433552350907.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:36,818] Trial 45 finished with value: 0.7997258909398537 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9299897772255146, 'min_weight_fraction_leaf': 0.026154799193349114}. Best is trial 45 with value: 0.7997258909398537.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:59:37,603] Trial 46 finished with value: 0.7967529732196287 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9242693674891926, 'min_weight_fraction_leaf': 0.027787065914218603}. Best is trial 45 with value: 0.7997258909398537.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:59:40,252] Trial 47 finished with value: 0.7591241437092512 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 399, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9451319619891156, 'min_weight_fraction_leaf': 0.021353265361453693}. Best is trial 45 with value: 0.7997258909398537.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:42,004] Trial 48 finished with value: 0.7941936780546998 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 477, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7986195780539649, 'min_weight_fraction_leaf': 0.029361515716338396}. Best is trial 45 with value: 0.7997258909398537.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:43,768] Trial 49 finished with value: 0.7978255853630776 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 480, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7904245123803767, 'min_weight_fraction_leaf': 0.024818282869739198}. Best is trial 45 with value: 0.7997258909398537.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:59:45,574] Trial 50 finished with value: 0.7698099739822994 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8011524070042025, 'min_weight_fraction_leaf': 0.13289417747182505}. Best is trial 45 with value: 0.7997258909398537.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 12:59:47,248] Trial 51 finished with value: 0.7987645524992278 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 430, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8923848192061412, 'min_weight_fraction_leaf': 0.02605303460560804}. Best is trial 45 with value: 0.7997258909398537.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:59:48,901] Trial 52 finished with value: 0.8082818165111065 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 431, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8927281007545602, 'min_weight_fraction_leaf': 0.01776619104700211}. Best is trial 52 with value: 0.8082818165111065.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 12:59:50,544] Trial 53 finished with value: 0.8110866211506726 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7849550112236834, 'min_weight_fraction_leaf': 0.0010371572946973467}. Best is trial 53 with value: 0.8110866211506726.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:59:52,070] Trial 54 finished with value: 0.8184334242781539 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 380, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.899094401409131, 'min_weight_fraction_leaf': 0.00386845300436138}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:59:53,471] Trial 55 finished with value: 0.811130911464409 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 377, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8814766678431996, 'min_weight_fraction_leaf': 0.00616224304453462}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 12:59:54,863] Trial 56 finished with value: 0.8128942544456477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8814777675801926, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:59:56,174] Trial 57 finished with value: 0.8137410015952117 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9883506834818401, 'min_weight_fraction_leaf': 0.004939537955850866}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 12:59:57,408] Trial 58 finished with value: 0.7772455035840169 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 340, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9940344752023949, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 13:00:00,003] Trial 59 finished with value: 0.7615558462238038 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8761051951976248, 'min_weight_fraction_leaf': 4.185324625715758e-05}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 13:00:01,463] Trial 60 finished with value: 0.7667282338631168 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 371, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9630695603151677, 'min_weight_fraction_leaf': 0.3947065564933017}. Best is trial 54 with value: 0.8184334242781539.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 13:00:02,813] Trial 61 finished with value: 0.8026210958864493 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9521995704869407, 'min_weight_fraction_leaf': 0.009763216394042862}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 13:00:04,204] Trial 62 finished with value: 0.7933912212188722 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 341, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9622354895904272, 'min_weight_fraction_leaf': 0.05582419067859595}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 13:00:05,647] Trial 63 finished with value: 0.7931895472090197 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.896024987016081, 'min_weight_fraction_leaf': 0.0002700550574033615}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 13:00:06,821] Trial 64 finished with value: 0.7662529333075554 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 298, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8734830738620268, 'min_weight_fraction_leaf': 0.009209995259860394}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 13:00:08,150] Trial 65 finished with value: 0.7922915527983669 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 323, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9998751732268022, 'min_weight_fraction_leaf': 0.053061456773475846}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 13:00:09,593] Trial 66 finished with value: 0.7662796717862171 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 381, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8191681763739528, 'min_weight_fraction_leaf': 0.3057859351291992}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7183098591549296
[I 2024-04-14 13:00:10,536] Trial 67 finished with value: 0.7973018771602063 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 235, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7040452866645146, 'min_weight_fraction_leaf': 0.013421016960303}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 13:00:12,021] Trial 68 finished with value: 0.7905109757804482 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9127286936500697, 'min_weight_fraction_leaf': 0.04406668724760356}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 13:00:13,185] Trial 69 finished with value: 0.7665031942938118 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 293, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9640274746063139, 'min_weight_fraction_leaf': 0.05937997155769904}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 13:00:14,693] Trial 70 finished with value: 0.7905058385126527 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 353, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8749254524064956, 'min_weight_fraction_leaf': 0.014391089869384033}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 13:00:16,342] Trial 71 finished with value: 0.7914718619258593 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 408, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9391284228535596, 'min_weight_fraction_leaf': 0.03775775279792393}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 13:00:17,788] Trial 72 finished with value: 0.7959447857977532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9057662494278897, 'min_weight_fraction_leaf': 0.01337301300506743}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 13:00:19,556] Trial 73 finished with value: 0.797738050349072 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 438, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.771872373589377, 'min_weight_fraction_leaf': 0.0007697514357257601}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 13:00:21,279] Trial 74 finished with value: 0.818082693457616 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9442676326615123, 'min_weight_fraction_leaf': 0.0452697256598598}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 13:00:22,919] Trial 75 finished with value: 0.8088925626004952 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 416, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.821641794190366, 'min_weight_fraction_leaf': 0.04254787237366244}. Best is trial 54 with value: 0.8184334242781539.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 13:00:26,526] Trial 76 finished with value: 0.7445543239013948 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 412, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7405846004023726, 'min_weight_fraction_leaf': 0.08315279746109999}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 13:00:28,126] Trial 77 finished with value: 0.8024224281926582 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 391, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8675467851851476, 'min_weight_fraction_leaf': 0.06223777941238984}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 13:00:29,779] Trial 78 finished with value: 0.8076368778682157 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 371, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.04300549632712334}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 13:00:31,581] Trial 79 finished with value: 0.7798580983634154 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 360, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8318070518745933, 'min_weight_fraction_leaf': 0.09923349879252227}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 13:00:33,699] Trial 80 finished with value: 0.803304869776887 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 420, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8961974185204477, 'min_weight_fraction_leaf': 0.04297313220175665}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 13:00:35,669] Trial 81 finished with value: 0.8085682947387614 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6244012602648809, 'min_weight_fraction_leaf': 0.04037744896019475}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 13:00:37,203] Trial 82 finished with value: 0.7838415803605676 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 392, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5478501283963577, 'min_weight_fraction_leaf': 0.06380313051590172}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 13:00:38,563] Trial 83 finished with value: 0.813384992483841 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 325, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6786268572300944, 'min_weight_fraction_leaf': 0.035864705971648966}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 13:00:39,850] Trial 84 finished with value: 0.8070117630351709 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 324, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6741971700307295, 'min_weight_fraction_leaf': 0.039898952911915385}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 13:00:41,548] Trial 85 finished with value: 0.7784002200776581 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5969165531866604, 'min_weight_fraction_leaf': 0.07907277408568263}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 13:00:42,737] Trial 86 finished with value: 0.8040463955805504 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 311, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6239898562442413, 'min_weight_fraction_leaf': 0.034418920088748625}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 13:00:44,205] Trial 87 finished with value: 0.8108820818477961 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 361, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7254265335183697, 'min_weight_fraction_leaf': 0.01429889954419488}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 13:00:46,858] Trial 88 finished with value: 0.7519593675571332 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 264, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.777514346860392, 'min_weight_fraction_leaf': 0.01423841344989584}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 13:00:48,253] Trial 89 finished with value: 0.7825384222231333 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7360177425549991, 'min_weight_fraction_leaf': 0.057282599183646324}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 13:00:49,684] Trial 90 finished with value: 0.7941797616062585 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 357, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6761046677136725, 'min_weight_fraction_leaf': 0.03034496116782681}. Best is trial 54 with value: 0.8184334242781539.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 13:00:51,156] Trial 91 finished with value: 0.7959765270473901 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 380, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7000801572410766, 'min_weight_fraction_leaf': 0.011623204454033635}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 13:00:52,820] Trial 92 finished with value: 0.8061149527072858 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 417, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8148162743654095, 'min_weight_fraction_leaf': 0.052724953580741044}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 13:00:54,336] Trial 93 finished with value: 0.8145239524195876 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 397, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7606402876582411, 'min_weight_fraction_leaf': 0.03178880028915507}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 13:00:56,007] Trial 94 finished with value: 0.8013478976251516 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 400, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8247472891583476, 'min_weight_fraction_leaf': 0.020945146840995008}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 13:00:57,637] Trial 95 finished with value: 0.7932822194908207 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7254480908682001, 'min_weight_fraction_leaf': 0.0011860920007742033}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:00:59,390] Trial 96 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 448, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7590829557654986, 'min_weight_fraction_leaf': 0.4423900052068913}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 13:01:00,713] Trial 97 finished with value: 0.7920132116283523 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 326, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7553056603605662, 'min_weight_fraction_leaf': 0.07065823578059044}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6830985915492958
[I 2024-04-14 13:01:01,981] Trial 98 finished with value: 0.7794142469383416 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 277, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8600176398429402, 'min_weight_fraction_leaf': 0.09670248388961511}. Best is trial 54 with value: 0.8184334242781539.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861

[I 2024-04-14 13:01:03,545] A new study created in memory with name: no-name-8dbc26d1-101f-48b4-9812-95f31c348f74

Fold 5 C-index: 0.704225352112676
[I 2024-04-14 13:01:03,536] Trial 99 finished with value: 0.7951382347538604 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 393, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7830387686068494, 'min_weight_fraction_leaf': 0.032870514302435844}. Best is trial 54 with value: 0.8184334242781539.


* Best trial for C-index:
 FrozenTrial(number=54, state=TrialState.COMPLETE, values=[0.8184334242781539], datetime_start=datetime.datetime(2024, 4, 14, 12, 59, 50, 601309), datetime_complete=datetime.datetime(2024, 4, 14, 12, 59, 52, 69966), params={'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 380, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.899094401409131, 'min_weight_fraction_leaf': 0.00386845300436138}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=54, value=None)


* Best Score for C-index:
 0.8184334242781539

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16575995264305135
Fold 2 IBS: 0.21832080988082556
Fold 3 IBS: 0.16138017526547796
Fold 4 IBS: 0.15220184602231765
Fold 5 IBS: 0.2307828935116489
[I 2024-04-14 13:01:06,277] Trial 0 finished with value: 0.1856891354646643 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 13:01:09,945] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.1827582219968779
Fold 2 IBS: 0.20514316966675422
Fold 3 IBS: 0.1788379757757883
Fold 4 IBS: 0.18170811255366315
Fold 5 IBS: 0.21720361154119627
[I 2024-04-14 13:01:13,141] Trial 2 finished with value: 0.19313021830685598 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.18586062645492488
Fold 2 IBS: 0.20240111554156762
Fold 3 IBS: 0.17992309451786404
Fold 4 IBS: 0.18643229854448562
Fold 5 IBS: 0.21555689585675042
[I 2024-04-14 13:01:14,273] Trial 3 finished with value: 0.1940348061831185 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 13:01:16,923] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 13:01:18,288] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.16585979406469822
Fold 2 IBS: 0.21733368026877523
Fold 3 IBS: 0.16181358484893035
Fold 4 IBS: 0.15275458932674296
Fold 5 IBS: 0.23267651566135972
[I 2024-04-14 13:01:20,961] Trial 6 finished with value: 0.1860876328341013 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.17377246835780635
Fold 2 IBS: 0.20350664278310102
Fold 3 IBS: 0.17143506025534627
Fold 4 IBS: 0.17194259290614536
Fold 5 IBS: 0.21714898680654937
[I 2024-04-14 13:01:22,857] Trial 7 finished with value: 0.18756115022178968 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.18743944467441095
Fold 2 IBS: 0.20162288519716673
Fold 3 IBS: 0.1819338635232324
Fold 4 IBS: 0.19027216035830896
Fold 5 IBS: 0.21726273307809119
[I 2024-04-14 13:01:23,285] Trial 8 finished with value: 0.19570621736624205 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.1893067765706493
Fold 2 IBS: 0.20880860555132355
Fold 3 IBS: 0.18509921108397434
Fold 4 IBS: 0.19829893179669214
Fold 5 IBS: 0.21494789353639537
[I 2024-04-14 13:01:27,293] Trial 9 finished with value: 0.1992922837078069 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-14 13:01:30,606] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.17553817167336536
Fold 2 IBS: 0.2070399400946403
Fold 3 IBS: 0.1713572624971608
Fold 4 IBS: 0.17358862990061724
Fold 5 IBS: 0.22009896093663298
[I 2024-04-14 13:01:33,568] Trial 11 finished with value: 0.18952459302048336 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.16483732775590207
Fold 2 IBS: 0.22393116567120833
Fold 3 IBS: 0.15980775964267352
Fold 4 IBS: 0.14761015416320603
Fold 5 IBS: 0.23441451832138316
[I 2024-04-14 13:01:37,217] Trial 12 finished with value: 0.18612018511087464 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.16801177719542432
Fold 2 IBS: 0.2135718453499975
Fold 3 IBS: 0.16884261759436764
Fold 4 IBS: 0.1669194484390663
Fold 5 IBS: 0.22467220648011935
[I 2024-04-14 13:01:39,887] Trial 13 finished with value: 0.18840357901179502 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.21392135153673889
Fold 2 IBS: 0.22053974711120056
Fold 3 IBS: 0.20546725749442502
Fold 4 IBS: 0.22525423125410982
Fold 5 IBS: 0.21703041978554669
[I 2024-04-14 13:01:42,110] Trial 14 finished with value: 0.2164426014364042 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 0 with value: 0.1856891354646643.

Fold 1 IBS: 0.1712305355617498
Fold 2 IBS: 0.2063023849015153
Fold 3 IBS: 0.16543954656053939
Fold 4 IBS: 0.1597348171409652
Fold 5 IBS: 0.22581192576725984
[I 2024-04-14 13:01:44,926] Trial 15 finished with value: 0.1857038419864059 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 402, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.0788882352604838}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.18451556992570262
Fold 2 IBS: 0.2045054397029926
Fold 3 IBS: 0.18192516474515785
Fold 4 IBS: 0.1923273588439748
Fold 5 IBS: 0.21328421157164
[I 2024-04-14 13:01:46,336] Trial 16 finished with value: 0.19531154895789357 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8701427748240497, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.17143813257964383
Fold 2 IBS: 0.20516796343817573
Fold 3 IBS: 0.16707654612478015
Fold 4 IBS: 0.16336495419218508
Fold 5 IBS: 0.22499752490727412
[I 2024-04-14 13:01:48,824] Trial 17 finished with value: 0.1864090242484118 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.07716955022969746}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.17459400228245592
Fold 2 IBS: 0.20822117587880848
Fold 3 IBS: 0.1716700644563243
Fold 4 IBS: 0.17382744675062473
Fold 5 IBS: 0.22109798923429133
[I 2024-04-14 13:01:51,101] Trial 18 finished with value: 0.18988213572050097 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 225, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8995216684294449, 'min_weight_fraction_leaf': 0.21349189574353308}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.17179928019263596
Fold 2 IBS: 0.2634786317283715
Fold 3 IBS: 0.16445610059476368
Fold 4 IBS: 0.158477915140229
Fold 5 IBS: 0.2429307938199226
[I 2024-04-14 13:01:52,150] Trial 19 finished with value: 0.20022854429518455 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7125469453628018, 'min_weight_fraction_leaf': 0.16081479313831204}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.21398679450269367
Fold 2 IBS: 0.22121307837673201
Fold 3 IBS: 0.20497490417095188
Fold 4 IBS: 0.22472051167557724
Fold 5 IBS: 0.21855984540171117
[I 2024-04-14 13:01:54,276] Trial 20 finished with value: 0.21669102682553323 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4237640400772665, 'min_weight_fraction_leaf': 0.4096697647298415}. Best is trial 0 with value: 0.1856891354646643.
Fold 1 IBS: 0.16589648677471286
Fold 2 IBS: 0.21970374256538555
Fold 3 IBS: 0.15984660181930133
Fold 4 IBS: 0.14989432164248953
Fold 5 IBS: 0.23241878960150023
[I 2024-04-14 13:01:57,348] Trial 21 finished with value: 0.1855519884806779 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5857737079827544, 'min_weight_fraction_leaf': 0.05547980929430263}. Best is trial 21 with value: 0.1855519884806779.
Fold 1 IBS: 0.16651111446540182
Fold 2 IBS: 0.21402869559449839
Fold 3 IBS: 0.1636622073218127
Fold 4 IBS: 0.1559084573077494
Fold 5 IBS: 0.23083213146212958
[I 2024-04-14 13:02:00,066] Trial 22 finished with value: 0.18618852123031837 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6019084141689979, 'min_weight_fraction_leaf': 0.09089190372779699}. Best is trial 21 with value: 0.1855519884806779.
Fold 1 IBS: 0.16910841623658765
Fold 2 IBS: 0.2068856247072409
Fold 3 IBS: 0.1647013217756339
Fold 4 IBS: 0.1578910629062624
Fold 5 IBS: 0.2263397658460724
[I 2024-04-14 13:02:02,537] Trial 23 finished with value: 0.18498523829435945 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7318632778578418, 'min_weight_fraction_leaf': 0.052240306896251386}. Best is trial 23 with value: 0.18498523829435945.
Fold 1 IBS: 0.16688947156617465
Fold 2 IBS: 0.21896625009434703
Fold 3 IBS: 0.16287735560244418
Fold 4 IBS: 0.15528199253107577
Fold 5 IBS: 0.23202708803098915
[I 2024-04-14 13:02:04,986] Trial 24 finished with value: 0.18720843156500616 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8799005820083364, 'min_weight_fraction_leaf': 0.03809022831757289}. Best is trial 23 with value: 0.18498523829435945.
Fold 1 IBS: 0.18712129408915376
Fold 2 IBS: 0.2052940369211901
Fold 3 IBS: 0.18149436803819047
Fold 4 IBS: 0.1900380665969375
Fold 5 IBS: 0.2161872340905782
[I 2024-04-14 13:02:06,767] Trial 25 finished with value: 0.19602699994721 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 242, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5004935744446656, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 23 with value: 0.18498523829435945.
Fold 1 IBS: 0.16380782651146134
Fold 2 IBS: 0.20781775176941653
Fold 3 IBS: 0.16186084577693116
Fold 4 IBS: 0.15422419116650735
Fold 5 IBS: 0.22690901126598104
[I 2024-04-14 13:02:09,647] Trial 26 finished with value: 0.18292392529805948 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7515303179479255, 'min_weight_fraction_leaf': 0.04311046725313979}. Best is trial 26 with value: 0.18292392529805948.
Fold 1 IBS: 0.16664959849765767
Fold 2 IBS: 0.2060237335336931
Fold 3 IBS: 0.16283091712948844
Fold 4 IBS: 0.1598269131504082
Fold 5 IBS: 0.22478009501333016
[I 2024-04-14 13:02:12,412] Trial 27 finished with value: 0.18402225146491552 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 299, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.05057017493914473}. Best is trial 26 with value: 0.18292392529805948.
Fold 1 IBS: 0.16341540247569045
Fold 2 IBS: 0.20737562746315716
Fold 3 IBS: 0.1626727577164252
Fold 4 IBS: 0.15927969384574217
Fold 5 IBS: 0.22410586148861758
[I 2024-04-14 13:02:15,299] Trial 28 finished with value: 0.1833698685979265 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8439618696772396, 'min_weight_fraction_leaf': 0.03303754670139228}. Best is trial 26 with value: 0.18292392529805948.
Fold 1 IBS: 0.17298387150022718
Fold 2 IBS: 0.20629442739334874
Fold 3 IBS: 0.16806498530826247
Fold 4 IBS: 0.16667864487740638
Fold 5 IBS: 0.2240538371601007
[I 2024-04-14 13:02:17,985] Trial 29 finished with value: 0.1876151532478691 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 297, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.12677335567886427}. Best is trial 26 with value: 0.18292392529805948.

Fold 1 IBS: 0.1753265543826254
Fold 2 IBS: 0.2073287496181804
Fold 3 IBS: 0.17214889802085478
Fold 4 IBS: 0.17521730364804317
Fold 5 IBS: 0.22130334953577135
[I 2024-04-14 13:02:20,397] Trial 30 finished with value: 0.19026497104109502 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 256, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9487209920968901, 'min_weight_fraction_leaf': 0.18097362848347806}. Best is trial 26 with value: 0.18292392529805948.
Fold 1 IBS: 0.1635854354097278
Fold 2 IBS: 0.21121780051762484
Fold 3 IBS: 0.16113974292115463
Fold 4 IBS: 0.1505740975965663
Fold 5 IBS: 0.22708547819250702
[I 2024-04-14 13:02:23,307] Trial 31 finished with value: 0.18272051092751612 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 328, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7423239460992603, 'min_weight_fraction_leaf': 0.03227752077576594}. Best is trial 31 with value: 0.18272051092751612.
Fold 1 IBS: 0.16313740303960508
Fold 2 IBS: 0.20922084992063417
Fold 3 IBS: 0.16113817857991095
Fold 4 IBS: 0.15003269330736985
Fold 5 IBS: 0.22664539262587316
[I 2024-04-14 13:02:26,375] Trial 32 finished with value: 0.18203490349467866 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 312, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8282958003475155, 'min_weight_fraction_leaf': 0.039065822201168936}. Best is trial 32 with value: 0.18203490349467866.
Fold 1 IBS: 0.16227404356539335
Fold 2 IBS: 0.21047630419849894
Fold 3 IBS: 0.16016564215051732
Fold 4 IBS: 0.14791936577283815
Fold 5 IBS: 0.22712694724529287
[I 2024-04-14 13:02:29,604] Trial 33 finished with value: 0.1815924605865081 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9128553712662378, 'min_weight_fraction_leaf': 0.025226777284953546}. Best is trial 33 with value: 0.1815924605865081.
Fold 1 IBS: 0.17078796339075042
Fold 2 IBS: 0.20584105368552777
Fold 3 IBS: 0.16624324313839867
Fold 4 IBS: 0.1605070107286674
Fold 5 IBS: 0.22454766034744414
[I 2024-04-14 13:02:32,203] Trial 34 finished with value: 0.18558538625815765 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 221, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.10315396232399626}. Best is trial 33 with value: 0.1815924605865081.
Fold 1 IBS: 0.162227113076718
Fold 2 IBS: 0.21071686074018994
Fold 3 IBS: 0.16042415555451095
Fold 4 IBS: 0.14939052647886808
Fold 5 IBS: 0.22652129825703402
[I 2024-04-14 13:02:35,679] Trial 35 finished with value: 0.1818559908214642 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 343, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7466287556494016, 'min_weight_fraction_leaf': 0.024671952695714577}. Best is trial 33 with value: 0.1815924605865081.
Fold 1 IBS: 0.16185782689847442
Fold 2 IBS: 0.21252579516485443
Fold 3 IBS: 0.16118812944102476
Fold 4 IBS: 0.14860806490552805
Fold 5 IBS: 0.22740455744001198
[I 2024-04-14 13:02:39,724] Trial 36 finished with value: 0.18231687476997874 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 457, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9138057827640367, 'min_weight_fraction_leaf': 0.01955795079422839}. Best is trial 33 with value: 0.1815924605865081.
Fold 1 IBS: 0.1742865188420447
Fold 2 IBS: 0.2565138559306156
Fold 3 IBS: 0.16886187384194765
Fold 4 IBS: 0.16150386801711844
Fold 5 IBS: 0.24077857729934557
[I 2024-04-14 13:02:43,814] Trial 37 finished with value: 0.2003889387862144 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 459, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9229174988240751, 'min_weight_fraction_leaf': 0.2525629317042785}. Best is trial 33 with value: 0.1815924605865081.
Fold 1 IBS: 0.16050901642283077
Fold 2 IBS: 0.2124222268527601
Fold 3 IBS: 0.159963889188363
Fold 4 IBS: 0.14882744781189972
Fold 5 IBS: 0.22593659098857732
[I 2024-04-14 13:02:47,551] Trial 38 finished with value: 0.1815318342528862 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 387, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.989120340049722, 'min_weight_fraction_leaf': 0.020073568586648008}. Best is trial 38 with value: 0.1815318342528862.
Fold 1 IBS: 0.17383524780861348
Fold 2 IBS: 0.20907076452882936
Fold 3 IBS: 0.17239439110783783
Fold 4 IBS: 0.1752451500258919
Fold 5 IBS: 0.22116622157786062
[I 2024-04-14 13:02:51,043] Trial 39 finished with value: 0.19034235500980662 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 393, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9898766641536626, 'min_weight_fraction_leaf': 0.0734486405661364}. Best is trial 38 with value: 0.1815318342528862.
Fold 1 IBS: 0.18273598212027226
Fold 2 IBS: 0.20411374141268104
Fold 3 IBS: 0.17751226724183894
Fold 4 IBS: 0.18035694541316108
Fold 5 IBS: 0.21701807635924134
[I 2024-04-14 13:02:53,567] Trial 40 finished with value: 0.19234740250943894 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.812487196445757, 'min_weight_fraction_leaf': 0.10596011173853095}. Best is trial 38 with value: 0.1815318342528862.
Fold 1 IBS: 0.16139752881469777
Fold 2 IBS: 0.213424574941556
Fold 3 IBS: 0.16020191464598357
Fold 4 IBS: 0.14803483277794374
Fold 5 IBS: 0.2280872173085967
[I 2024-04-14 13:02:57,639] Trial 41 finished with value: 0.18222921369775555 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 439, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9328062578640754, 'min_weight_fraction_leaf': 0.02195098560622473}. Best is trial 38 with value: 0.1815318342528862.
Fold 1 IBS: 0.1601080768290464
Fold 2 IBS: 0.2124224037500771
Fold 3 IBS: 0.1614544509429899
Fold 4 IBS: 0.14950652875816858
Fold 5 IBS: 0.22508102603299507
[I 2024-04-14 13:03:01,657] Trial 42 finished with value: 0.18171449726265543 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9565494224588321, 'min_weight_fraction_leaf': 0.0014193751670380401}. Best is trial 38 with value: 0.1815318342528862.
Fold 1 IBS: 0.1613895047198844
Fold 2 IBS: 0.21102880556989018
Fold 3 IBS: 0.16093618192695464
Fold 4 IBS: 0.1494439506014481
Fold 5 IBS: 0.22487223543448695
[I 2024-04-14 13:03:05,183] Trial 43 finished with value: 0.18153413565053286 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 372, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9665171229222386, 'min_weight_fraction_leaf': 0.01045001389926427}. Best is trial 38 with value: 0.1815318342528862.
Fold 1 IBS: 0.16594065786654502
Fold 2 IBS: 0.20802971593133837
Fold 3 IBS: 0.16377567824276826
Fold 4 IBS: 0.15934070474949164
Fold 5 IBS: 0.22471757114937063
[I 2024-04-14 13:03:08,425] Trial 44 finished with value: 0.1843608655879028 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 361, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.999578221691947, 'min_weight_fraction_leaf': 0.06480702126608817}. Best is trial 38 with value: 0.1815318342528862.

Fold 1 IBS: 0.16018787401037188
Fold 2 IBS: 0.21157577684673273
Fold 3 IBS: 0.16062873421710938
Fold 4 IBS: 0.14895364309241638
Fold 5 IBS: 0.22578089787314537
[I 2024-04-14 13:03:12,701] Trial 45 finished with value: 0.18142538520795515 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 491, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9583231565912955, 'min_weight_fraction_leaf': 0.0029107293558666867}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.1677734556334294
Fold 2 IBS: 0.20073298892392583
Fold 3 IBS: 0.16790665630340973
Fold 4 IBS: 0.16323803409498044
Fold 5 IBS: 0.21692306693145388
[I 2024-04-14 13:03:17,065] Trial 46 finished with value: 0.1833148403774399 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 492, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9577353483237173, 'min_weight_fraction_leaf': 0.011893627926120066}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.17003220381024714
Fold 2 IBS: 0.20611992026717216
Fold 3 IBS: 0.1700310984198955
Fold 4 IBS: 0.17398195506074635
Fold 5 IBS: 0.22042158707165543
[I 2024-04-14 13:03:22,919] Trial 47 finished with value: 0.1881173529259433 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 421, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8760963978788562, 'min_weight_fraction_leaf': 0.011904610635108727}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.1674653424673555
Fold 2 IBS: 0.23617538658692583
Fold 3 IBS: 0.1510094250358766
Fold 4 IBS: 0.13913592347186152
Fold 5 IBS: 0.23292539154176756
[I 2024-04-14 13:03:28,432] Trial 48 finished with value: 0.1853422938207574 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9591813129033667, 'min_weight_fraction_leaf': 0.002662798090128847}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.18223966148837215
Fold 2 IBS: 0.2048771293710281
Fold 3 IBS: 0.17918687862957028
Fold 4 IBS: 0.1833548493015252
Fold 5 IBS: 0.21737869272934188
[I 2024-04-14 13:03:34,209] Trial 49 finished with value: 0.1934074423039675 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8939906165123098, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.16744004532159024
Fold 2 IBS: 0.2109455196114388
Fold 3 IBS: 0.16372926541700475
Fold 4 IBS: 0.15769385629126045
Fold 5 IBS: 0.22762143723614742
[I 2024-04-14 13:03:38,895] Trial 50 finished with value: 0.1854860247754883 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9959583946431058, 'min_weight_fraction_leaf': 0.08836682423561604}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.16951001519199957
Fold 2 IBS: 0.2038552400012285
Fold 3 IBS: 0.16984889557276142
Fold 4 IBS: 0.17513670869327544
Fold 5 IBS: 0.2193287442133556
[I 2024-04-14 13:03:42,895] Trial 51 finished with value: 0.1875359207345241 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7791408722934559, 'min_weight_fraction_leaf': 0.0006223358280206728}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.20454793833404442
Fold 2 IBS: 0.21399644660508485
Fold 3 IBS: 0.1980543339291697
Fold 4 IBS: 0.21672647729785918
Fold 5 IBS: 0.21577750216754793
[I 2024-04-14 13:03:46,204] Trial 52 finished with value: 0.20982053966674125 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9604952679977686, 'min_weight_fraction_leaf': 0.46068944029286296}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.16490312521282682
Fold 2 IBS: 0.2099877814025965
Fold 3 IBS: 0.163017632144063
Fold 4 IBS: 0.15357600567629756
Fold 5 IBS: 0.2277139091678503
[I 2024-04-14 13:03:49,701] Trial 53 finished with value: 0.18383969072072687 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.02341481195134219}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.17833791871311885
Fold 2 IBS: 0.20351675129141084
Fold 3 IBS: 0.17711043610104693
Fold 4 IBS: 0.1871168404594236
Fold 5 IBS: 0.2152821961211131
[I 2024-04-14 13:03:53,348] Trial 54 finished with value: 0.19227282853722266 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.851658959501558, 'min_weight_fraction_leaf': 0.32919512983681454}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.16463655959925727
Fold 2 IBS: 0.21160657152169263
Fold 3 IBS: 0.1626620720077751
Fold 4 IBS: 0.15266782324059847
Fold 5 IBS: 0.22934031925087112
[I 2024-04-14 13:03:57,115] Trial 55 finished with value: 0.1841826691240389 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9632233887793732, 'min_weight_fraction_leaf': 0.05888296888739131}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.16710083957398922
Fold 2 IBS: 0.20359420167475523
Fold 3 IBS: 0.16690810554362556
Fold 4 IBS: 0.15422108147820085
Fold 5 IBS: 0.2261626743782059
[I 2024-04-14 13:03:57,580] Trial 56 finished with value: 0.18359738052975536 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 36, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6340499753529142, 'min_weight_fraction_leaf': 0.025321649872275833}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.18183928386596956
Fold 2 IBS: 0.20329390037746892
Fold 3 IBS: 0.17631730291503317
Fold 4 IBS: 0.17946681036247183
Fold 5 IBS: 0.21650010881159548
[I 2024-04-14 13:04:00,784] Trial 57 finished with value: 0.19148348126650777 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 380, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9198648622919235, 'min_weight_fraction_leaf': 0.11451906966798243}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.17928834287763445
Fold 2 IBS: 0.2049422735274537
Fold 3 IBS: 0.17523668725230976
Fold 4 IBS: 0.17586362017123205
Fold 5 IBS: 0.21725865418836268
[I 2024-04-14 13:04:04,578] Trial 58 finished with value: 0.19051791560339854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 462, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8634609002015082, 'min_weight_fraction_leaf': 0.08391899567341524}. Best is trial 45 with value: 0.18142538520795515.
Fold 1 IBS: 0.16177146771151024
Fold 2 IBS: 0.211085572811698
Fold 3 IBS: 0.15934393967188537
Fold 4 IBS: 0.1478533066402371
Fold 5 IBS: 0.22351697744671287
[I 2024-04-14 13:04:07,640] Trial 59 finished with value: 0.18071425285640869 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 348, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7977445310979885, 'min_weight_fraction_leaf': 5.246908224487007e-05}. Best is trial 59 with value: 0.18071425285640869.

Fold 1 IBS: 0.16230315465603623
Fold 2 IBS: 0.22256653426146097
Fold 3 IBS: 0.1640671332820358
Fold 4 IBS: 0.16540280962956921
Fold 5 IBS: 0.2288950034663518
[I 2024-04-14 13:04:08,419] Trial 60 finished with value: 0.1886469270590908 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 74, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.36612707136592737, 'min_weight_fraction_leaf': 0.0019516995494000267}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.168038042421559
Fold 2 IBS: 0.2051256684585529
Fold 3 IBS: 0.16229862942852732
Fold 4 IBS: 0.15452249752369313
Fold 5 IBS: 0.22616041975575948
[I 2024-04-14 13:04:11,485] Trial 61 finished with value: 0.18322905151761837 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 357, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5223779429597124, 'min_weight_fraction_leaf': 0.041415006782480605}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16331468832890816
Fold 2 IBS: 0.2096980040739477
Fold 3 IBS: 0.16033260827631626
Fold 4 IBS: 0.1484232497741272
Fold 5 IBS: 0.2281482656379602
[I 2024-04-14 13:04:14,437] Trial 62 finished with value: 0.1819833632182519 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 343, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6737840757956169, 'min_weight_fraction_leaf': 0.02208468973324349}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16635386314253023
Fold 2 IBS: 0.20703699799447653
Fold 3 IBS: 0.16256995967907875
Fold 4 IBS: 0.1582010256730601
Fold 5 IBS: 0.22552932238340118
[I 2024-04-14 13:21:37,211] Trial 63 finished with value: 0.18393823377450938 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 404, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7898045653931718, 'min_weight_fraction_leaf': 0.05100166794825291}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16041459937462185
Fold 2 IBS: 0.21287704462124973
Fold 3 IBS: 0.1604304657079315
Fold 4 IBS: 0.14866457200046237
Fold 5 IBS: 0.22529653127772878
[I 2024-04-14 13:21:41,168] Trial 64 finished with value: 0.18153664259639885 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9725925566875869, 'min_weight_fraction_leaf': 0.016378111810524322}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.17069847623110174
Fold 2 IBS: 0.21085248026402328
Fold 3 IBS: 0.1668186515386585
Fold 4 IBS: 0.16316345886187686
Fold 5 IBS: 0.22605622974983847
[I 2024-04-14 13:21:44,355] Trial 65 finished with value: 0.18751785932909976 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9705722279414055, 'min_weight_fraction_leaf': 0.06288304815000326}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1717440088602235
Fold 2 IBS: 0.208328801496413
Fold 3 IBS: 0.16835935385270795
Fold 4 IBS: 0.16671588248600866
Fold 5 IBS: 0.22501607932154974
[I 2024-04-14 13:21:47,473] Trial 66 finished with value: 0.18803282520338058 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 481, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9014720583851338, 'min_weight_fraction_leaf': 0.14650375198019722}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1643704082559243
Fold 2 IBS: 0.21397107272545524
Fold 3 IBS: 0.16166099767967793
Fold 4 IBS: 0.15002998240848373
Fold 5 IBS: 0.22946839919797896
[I 2024-04-14 13:21:50,564] Trial 67 finished with value: 0.183900172053504 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 450, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9379470558583947, 'min_weight_fraction_leaf': 0.0005436865110748283}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.17694566429126635
Fold 2 IBS: 0.20502517827332606
Fold 3 IBS: 0.1730055978972822
Fold 4 IBS: 0.17821756612210454
Fold 5 IBS: 0.21733276518877032
[I 2024-04-14 13:21:53,714] Trial 68 finished with value: 0.19010535435454992 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.18504146569474889, 'min_weight_fraction_leaf': 0.04011977888833963}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16189833552020433
Fold 2 IBS: 0.21271561154853225
Fold 3 IBS: 0.159859165441921
Fold 4 IBS: 0.14839513379993505
Fold 5 IBS: 0.22593368884459825
[I 2024-04-14 13:21:56,450] Trial 69 finished with value: 0.18176038703103817 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9724391266477472, 'min_weight_fraction_leaf': 0.014291843365214878}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.17236170742231494
Fold 2 IBS: 0.2040034616372976
Fold 3 IBS: 0.17057514265640392
Fold 4 IBS: 0.17428149373849505
Fold 5 IBS: 0.21970754320938726
[I 2024-04-14 13:21:58,457] Trial 70 finished with value: 0.18818586973277973 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8830399430570695, 'min_weight_fraction_leaf': 0.050795507752286875}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16144114409738927
Fold 2 IBS: 0.21080405363180268
Fold 3 IBS: 0.16119060616182213
Fold 4 IBS: 0.15276133629464622
Fold 5 IBS: 0.22544897569134723
[I 2024-04-14 13:22:01,172] Trial 71 finished with value: 0.1823292231754015 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 421, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9797698047759577, 'min_weight_fraction_leaf': 0.013498595464325695}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1624808693916004
Fold 2 IBS: 0.2103940675369562
Fold 3 IBS: 0.1608080908956377
Fold 4 IBS: 0.15018161143350098
Fold 5 IBS: 0.22680643454470623
[I 2024-04-14 13:22:03,670] Trial 72 finished with value: 0.18213421476048025 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9252393583686376, 'min_weight_fraction_leaf': 0.0345787635241933}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1654766587653592
Fold 2 IBS: 0.20475221674233277
Fold 3 IBS: 0.1614205592987779
Fold 4 IBS: 0.18432915949794582
Fold 5 IBS: 0.2717527662271206
[I 2024-04-14 13:22:03,797] Trial 73 finished with value: 0.19754627210630726 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9988228951364923, 'min_weight_fraction_leaf': 0.015098320641014195}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16186996230710496
Fold 2 IBS: 0.21221002264531214
Fold 3 IBS: 0.1609327983523297
Fold 4 IBS: 0.14974913738002765
Fold 5 IBS: 0.22660404135066148
[I 2024-04-14 13:22:06,991] Trial 74 finished with value: 0.18227319240708723 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 466, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8339384870624152, 'min_weight_fraction_leaf': 0.0313603156723575}. Best is trial 59 with value: 0.18071425285640869.

Fold 1 IBS: 0.17451230590744263
Fold 2 IBS: 0.20100399290448753
Fold 3 IBS: 0.17156096463153092
Fold 4 IBS: 0.1718768459456622
Fold 5 IBS: 0.21682889436787772
[I 2024-04-14 13:37:30,480] Trial 75 finished with value: 0.1871566007514002 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9444744925227744, 'min_weight_fraction_leaf': 0.07181205233641544}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16363885977998363
Fold 2 IBS: 0.21080703897734426
Fold 3 IBS: 0.1638208483918266
Fold 4 IBS: 0.15977599581486032
Fold 5 IBS: 0.22548859529714996
[I 2024-04-14 13:37:33,597] Trial 76 finished with value: 0.18470626765223294 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 499, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9706091391614031, 'min_weight_fraction_leaf': 0.016607803130626222}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16371188623753913
Fold 2 IBS: 0.22236180123866284
Fold 3 IBS: 0.1584569335499698
Fold 4 IBS: 0.14344136788737072
Fold 5 IBS: 0.234463331165536
[I 2024-04-14 13:37:36,390] Trial 77 finished with value: 0.1844870640158157 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9129710100932363, 'min_weight_fraction_leaf': 0.047959009635324276}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.17313533611020301
Fold 2 IBS: 0.21102492242306334
Fold 3 IBS: 0.17253247029594002
Fold 4 IBS: 0.1751014021084408
Fold 5 IBS: 0.22101609139808467
[I 2024-04-14 13:37:39,346] Trial 78 finished with value: 0.19056204446714636 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 482, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8624263292984007, 'min_weight_fraction_leaf': 0.24123415050796002}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.2139784869411462
Fold 2 IBS: 0.22134571200471387
Fold 3 IBS: 0.20477004767555512
Fold 4 IBS: 0.22460854806964084
Fold 5 IBS: 0.2186270673901699
[I 2024-04-14 13:37:42,224] Trial 79 finished with value: 0.2166659724162452 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 450, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9449733536961591, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.164319880407943
Fold 2 IBS: 0.20878640213289096
Fold 3 IBS: 0.1605288038076057
Fold 4 IBS: 0.1502889048251452
Fold 5 IBS: 0.22638466643414465
[I 2024-04-14 13:37:43,658] Trial 80 finished with value: 0.1820617315215459 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 165, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9748522359700842, 'min_weight_fraction_leaf': 0.030716469729922865}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1626373331571812
Fold 2 IBS: 0.20785396861295236
Fold 3 IBS: 0.16104257032702204
Fold 4 IBS: 0.1524458868854606
Fold 5 IBS: 0.22411919373027528
[I 2024-04-14 13:37:46,055] Trial 81 finished with value: 0.18161979054257832 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 343, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7603603942329631, 'min_weight_fraction_leaf': 0.012077681033375864}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16171480766155946
Fold 2 IBS: 0.2084150259740611
Fold 3 IBS: 0.16199090578289577
Fold 4 IBS: 0.15247637745600123
Fold 5 IBS: 0.2238084768211117
[I 2024-04-14 13:37:48,443] Trial 82 finished with value: 0.18168111873912585 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 365, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8862000410250177, 'min_weight_fraction_leaf': 0.0008223018495513972}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16334225924073184
Fold 2 IBS: 0.2101272439381316
Fold 3 IBS: 0.1609436414542051
Fold 4 IBS: 0.15253082023045345
Fold 5 IBS: 0.22360313061009535
[I 2024-04-14 13:37:50,743] Trial 83 finished with value: 0.18210941909472345 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.815795581930713, 'min_weight_fraction_leaf': 0.0033684799666544854}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1700622156805333
Fold 2 IBS: 0.2041614420675726
Fold 3 IBS: 0.17009116559674642
Fold 4 IBS: 0.17410865574285483
Fold 5 IBS: 0.2196088012757139
[I 2024-04-14 13:37:53,286] Trial 84 finished with value: 0.18760645607268422 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 364, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8846222432249831, 'min_weight_fraction_leaf': 0.03108213206646897}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16788032844879255
Fold 2 IBS: 0.20628260018363984
Fold 3 IBS: 0.16350811037428825
Fold 4 IBS: 0.1618309471178598
Fold 5 IBS: 0.22402429679742408
[I 2024-04-14 13:37:55,695] Trial 85 finished with value: 0.1847052565844009 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7958426256601538, 'min_weight_fraction_leaf': 0.058765172025879144}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16636753172494914
Fold 2 IBS: 0.23656948331486585
Fold 3 IBS: 0.15028684583011565
Fold 4 IBS: 0.13803738438100627
Fold 5 IBS: 0.23121468285891777
[I 2024-04-14 13:37:58,507] Trial 86 finished with value: 0.18449518562197095 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 387, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.837924888583718, 'min_weight_fraction_leaf': 0.011853968411768017}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.17063589258602602
Fold 2 IBS: 0.2078462626408248
Fold 3 IBS: 0.16546043732482435
Fold 4 IBS: 0.1598714466052401
Fold 5 IBS: 0.2260920491043736
[I 2024-04-14 13:38:04,453] Trial 87 finished with value: 0.18598121765225778 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.911798858428698, 'min_weight_fraction_leaf': 0.04405166363685696}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1740880663485427
Fold 2 IBS: 0.20707246914102517
Fold 3 IBS: 0.17220803236685242
Fold 4 IBS: 0.17513189852530422
Fold 5 IBS: 0.2214380201933472
[I 2024-04-14 13:38:06,122] Trial 88 finished with value: 0.18998769731501436 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7188830553466486, 'min_weight_fraction_leaf': 0.021234501601072996}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16960797406588088
Fold 2 IBS: 0.2079862022857985
Fold 3 IBS: 0.16534734517800806
Fold 4 IBS: 0.1579868927504318
Fold 5 IBS: 0.22567576405927878
[I 2024-04-14 13:38:08,791] Trial 89 finished with value: 0.1853208356678796 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 374, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9482660157335048, 'min_weight_fraction_leaf': 0.09213840837193898}. Best is trial 59 with value: 0.18071425285640869.

Fold 1 IBS: 0.18505726472199197
Fold 2 IBS: 0.20422882801752185
Fold 3 IBS: 0.18218146544483949
Fold 4 IBS: 0.197363394678087
Fold 5 IBS: 0.21363202834995396
[I 2024-04-14 13:38:11,522] Trial 90 finished with value: 0.1964925962424789 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8685241268999454, 'min_weight_fraction_leaf': 0.36113729645899395}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16232027984914077
Fold 2 IBS: 0.21039259861689338
Fold 3 IBS: 0.16262694408072945
Fold 4 IBS: 0.15691427656551898
Fold 5 IBS: 0.2239182334907605
[I 2024-04-14 13:47:06,825] Trial 91 finished with value: 0.18323446652060862 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 400, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9804816076830855, 'min_weight_fraction_leaf': 0.013672752625702497}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1623936994252016
Fold 2 IBS: 0.21075841619999364
Fold 3 IBS: 0.16036596427659283
Fold 4 IBS: 0.15074563765572796
Fold 5 IBS: 0.22722194994436234
[I 2024-04-14 13:47:10,068] Trial 92 finished with value: 0.18229713350037566 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 416, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7587501492288132, 'min_weight_fraction_leaf': 0.008504080718130615}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16148919161516553
Fold 2 IBS: 0.20909254373283798
Fold 3 IBS: 0.16075945760458724
Fold 4 IBS: 0.14985669797766848
Fold 5 IBS: 0.22715702246741068
[I 2024-04-14 13:47:14,461] Trial 93 finished with value: 0.18167098267953397 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 280, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9274970987138261, 'min_weight_fraction_leaf': 0.02817696017761047}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16285442352615292
Fold 2 IBS: 0.20723262117356395
Fold 3 IBS: 0.16083195985354734
Fold 4 IBS: 0.15178365703424895
Fold 5 IBS: 0.2244587929504019
[I 2024-04-14 13:47:16,974] Trial 94 finished with value: 0.181432290907583 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 240, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.902552615825831, 'min_weight_fraction_leaf': 0.030311910161996615}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16348077861765248
Fold 2 IBS: 0.20853813876993743
Fold 3 IBS: 0.16141814507488433
Fold 4 IBS: 0.1512055971764909
Fold 5 IBS: 0.22719404947414973
[I 2024-04-14 13:47:18,979] Trial 95 finished with value: 0.18236734182262299 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8937743150996315, 'min_weight_fraction_leaf': 0.03874293655684248}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1651085095887286
Fold 2 IBS: 0.22128126470485035
Fold 3 IBS: 0.15931137985642482
Fold 4 IBS: 0.14750108493872444
Fold 5 IBS: 0.23402833203293283
[I 2024-04-14 13:47:20,757] Trial 96 finished with value: 0.18544611422433221 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 234, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9248240566897326, 'min_weight_fraction_leaf': 0.07497972124309156}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.16525642263367896
Fold 2 IBS: 0.20679736170194124
Fold 3 IBS: 0.1619698212732988
Fold 4 IBS: 0.15849227082060519
Fold 5 IBS: 0.223139833794636
[I 2024-04-14 13:47:22,499] Trial 97 finished with value: 0.183131142044832 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 190, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9039529180051251, 'min_weight_fraction_leaf': 0.027655334501311756}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.1660228772919933
Fold 2 IBS: 0.21062443175445833
Fold 3 IBS: 0.16233705145892968
Fold 4 IBS: 0.1536391084239179
Fold 5 IBS: 0.22724651683867383
[I 2024-04-14 13:47:25,003] Trial 98 finished with value: 0.18397399715359458 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 285, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8598604830543723, 'min_weight_fraction_leaf': 0.05663801354697763}. Best is trial 59 with value: 0.18071425285640869.
Fold 1 IBS: 0.17419222797626205
Fold 2 IBS: 0.20026567917962476
Fold 3 IBS: 0.16957801875425937
Fold 4 IBS: 0.17025525690329613
Fold 5 IBS: 0.2179576848448926
[I 2024-04-14 13:47:26,347] Trial 99 finished with value: 0.18644977353166697 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4622293227685943, 'min_weight_fraction_leaf': 0.024810731138183988}. Best is trial 59 with value: 0.18071425285640869.


* Best trial for IBS:
 FrozenTrial(number=59, state=TrialState.COMPLETE, values=[0.18071425285640869], datetime_start=datetime.datetime(2024, 4, 14, 13, 4, 4, 585935), datetime_complete=datetime.datetime(2024, 4, 14, 13, 4, 7, 638981), params={'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 348, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7977445310979885, 'min_weight_fraction_leaf': 5.246908224487007e-05}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=59, value=None)


* Best Score for IBS:
 0.18071425285640869

In [87]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [88]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.818
train_ibs:  0.181

#### Test

In [89]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [90]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=17, max_features=1, max_leaf_nodes=11,
                   max_samples=0.899094401409131, min_samples_leaf=1,
                   min_weight_fraction_leaf=0.00386845300436138,
                   n_estimators=380, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.607

ExtraSurvivalTrees(max_depth=3, max_features='auto', max_leaf_nodes=7,
                   max_samples=0.7977445310979885, min_samples_leaf=1,
                   min_samples_split=12,
                   min_weight_fraction_leaf=5.246908224487007e-05,
                   n_estimators=348, oob_score=True, random_state=123)

IBS: 0.21

In [91]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [92]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 13:47:27,975] A new study created in memory with name: no-name-cfe6785d-477b-4ca7-890b-c6fb8b39a8e0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:11:55,340] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:28:25,243] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:28:31,699] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:29:55,893] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:29:59,293] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:00,150] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:08,541] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:10,952] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:11,268] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 14:30:35,937] Trial 9 finished with value: 0.7322716318897614 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:36:01,258] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:47,851] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:37:30,256] Trial 12 finished with value: 0.7112309881650516 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:37:57,820] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:38:26,369] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:38:54,935] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:39:13,564] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:39:52,454] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:40:46,317] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:40:48,577] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:06,695] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:41:45,035] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 14:42:29,160] Trial 22 finished with value: 0.707889686065353 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:43:02,193] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:43:29,929] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:43:49,450] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:44:29,457] Trial 26 finished with value: 0.5421550134138162 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:45:22,159] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:02,051] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:28,996] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:56,326] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:47:50,103] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:41,452] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:16,284] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:57,298] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:06,018] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:49,230] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-14 14:50:50,436] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:06,195] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:34,653] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:13,856] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 14:52:14,040] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:52:18,275] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:22,751] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:34,304] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:39,101] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:43,403] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:00,104] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:07,367] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-14 14:53:26,597] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:28,052] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:53:28,357] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:28,669] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:53:32,430] Trial 53 finished with value: 0.7013896159000076 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:35,730] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:36,434] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:24,863] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:27,837] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:34,479] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:15,180] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:29,949] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-14 14:55:31,767] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:55:39,677] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:55:40,813] Trial 63 finished with value: 0.715358098862813 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:42,995] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:47,000] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:57,974] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:58,939] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:11,993] Trial 68 finished with value: 0.6289549910873441 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:12,962] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:52,760] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:57:53,024] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:57:53,351] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:58:02,183] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:58:02,541] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:58:05,177] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:58:25,569] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:58:26,484] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:59:15,499] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:59:22,082] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:59:37,870] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 14:59:38,072] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:59:38,300] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:59:38,884] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:00:27,412] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:00:27,743] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:00:28,764] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:00:29,690] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:00:30,866] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:01:08,636] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:01:12,511] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 15:01:12,883] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:01:13,300] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:01:13,503] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:01:14,094] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 15:01:15,069] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7322716318897614.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:01:17,326] Trial 96 finished with value: 0.7504074073266968 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7504074073266968.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:01:19,636] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7504074073266968.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 15:01:21,627] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7504074073266968.
Fold 1 C-index: 0.6515151515151515
Fold 2 C-index: 0.6383928571428571

[I 2024-04-14 15:01:21,908] A new study created in memory with name: no-name-84e9ddc2-6bc7-42ff-a444-aab467520c6f

Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 15:01:21,891] Trial 99 finished with value: 0.6748636085903267 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7504074073266968.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7504074073266968], datetime_start=datetime.datetime(2024, 4, 14, 15, 1, 15, 75452), datetime_complete=datetime.datetime(2024, 4, 14, 15, 1, 17, 325724), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7504074073266968

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:01:38,808] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:01:46,532] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:01:54,021] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:02:05,403] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:02:10,302] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:02:11,561] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:02:23,403] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:02:26,982] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:02:27,472] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21301905081620184
Fold 2 IBS: 0.22132334466352413
Fold 3 IBS: 0.20361207175544604
Fold 4 IBS: 0.2237545866133711
Fold 5 IBS: 0.21793593352546728
[I 2024-04-14 15:02:58,304] Trial 9 finished with value: 0.21592899747480207 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 15:03:45,489] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:04:40,087] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.2138394554380325
Fold 2 IBS: 0.22156449267228215
Fold 3 IBS: 0.20440421917640686
Fold 4 IBS: 0.22459228475797166
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 15:05:32,406] Trial 12 finished with value: 0.21649983569907022 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 15:06:02,812] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:06:47,889] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:07:26,850] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:07:50,695] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:08:44,629] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:09:12,408] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:09:16,910] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:10:06,114] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 15:10:59,903] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21592899747480207.
Fold 1 IBS: 0.21274696995404324
Fold 2 IBS: 0.22141702918594672

Fold 3 IBS: 0.20334487090004036
Fold 4 IBS: 0.22311935744001946
Fold 5 IBS: 0.21791022310639455
[I 2024-04-14 15:12:01,223] Trial 22 finished with value: 0.21570769011728888 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:12:58,338] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:13:36,237] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:14:04,602] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:14:54,820] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:14:59,808] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:15:16,829] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:16:00,257] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:16:17,239] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 15:17:12,802] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.2214475600367709
Fold 3 IBS: 0.20359640314421312
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.21789545644168284
[I 2024-04-14 15:18:10,041] Trial 32 finished with value: 0.21589773874156276 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:18:46,657] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:19:28,956] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:19:39,049] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:20:29,467] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:20:31,252] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:20:59,494] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:21:40,331] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:22:14,740] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21336856087375877
Fold 2 IBS: 0.22149810300618933
Fold 3 IBS: 0.20392471067362514
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21799037217752354
[I 2024-04-14 15:23:01,730] Trial 41 finished with value: 0.21614791088841184 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.2130552690521814
Fold 2 IBS: 0.22147749486211882
Fold 3 IBS: 0.20370128725160278
Fold 4 IBS: 0.22354848687764872
Fold 5 IBS: 0.21782729926210512
[I 2024-04-14 15:23:49,688] Trial 42 finished with value: 0.21592196746113138 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:24:44,524] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:25:30,333] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21369042722479478
Fold 2 IBS: 0.22142204383119019
Fold 3 IBS: 0.20428812830608178
Fold 4 IBS: 0.22435684363715924
Fold 5 IBS: 0.2180093984243402
[I 2024-04-14 15:26:11,058] Trial 45 finished with value: 0.21635336828471324 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:26:44,401] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:26:57,690] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:26:57,913] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:27:05,810] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:27:50,128] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 15:28:40,056] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:29:28,823] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21570769011728888.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22136281903923083
Fold 3 IBS: 0.20240438380881318
Fold 4 IBS: 0.22194086514149353
Fold 5 IBS: 0.21777686189712414
[I 2024-04-14 15:30:08,350] Trial 53 finished with value: 0.21504561735962566 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:30:50,552] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:31:24,590] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:31:59,449] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:32:41,486] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:33:43,374] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:34:19,922] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:34:51,729] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:35:39,005] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 15:36:40,804] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:37:43,182] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21283852891591884
Fold 2 IBS: 0.22121168014519327
Fold 3 IBS: 0.20350238414837962
Fold 4 IBS: 0.2235566700046848
Fold 5 IBS: 0.21792468774711235
[I 2024-04-14 15:38:45,173] Trial 64 finished with value: 0.2158067901922578 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21269460403694984
Fold 2 IBS: 0.22099824057914028
Fold 3 IBS: 0.2032443490807411
Fold 4 IBS: 0.22282507042550376
Fold 5 IBS: 0.21773498111135334
[I 2024-04-14 15:39:52,105] Trial 65 finished with value: 0.21549944904673768 and parameters: {'subsample': 0.9189183326723824, 'learning_rate': 0.00872213651685068, 'dropout_rate': 0.15744491147958184, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 0.0027457451635429023, 'min_weight_fraction_leaf': 0.218026428516915, 'max_features': 'log2', 'min_impurity_decrease': 3.884557803763542e-06, 'validation_fraction': 0.9772658166542009, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:40:48,935] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8639813037885321, 'learning_rate': 0.010366561182703663, 'dropout_rate': 0.2054023171521986, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.0590752315578722, 'min_weight_fraction_leaf': 0.1974211678184809, 'max_features': 'log2', 'min_impurity_decrease': 4.836772048236878e-06, 'validation_fraction': 0.9971715713668047, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:41:41,858] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.924711151270876, 'learning_rate': 0.009416377941785207, 'dropout_rate': 0.1662721971023693, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.6209101057240151, 'min_weight_fraction_leaf': 0.17934817748077603, 'max_features': 'log2', 'min_impurity_decrease': 3.102112447557567e-06, 'validation_fraction': 0.911923187481934, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 8}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:42:26,097] Trial 68 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8140014869251382, 'learning_rate': 0.014752651720825174, 'dropout_rate': 0.11923568819182435, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.2065728012666141, 'min_weight_fraction_leaf': 0.21218775276698854, 'max_features': 'log2', 'min_impurity_decrease': 1.4539585728269896e-05, 'validation_fraction': 0.8273349120190413, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:43:18,476] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9988924989656905, 'learning_rate': 0.02831436330338611, 'dropout_rate': 0.16724677379095765, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 3.9803027487021705, 'min_weight_fraction_leaf': 0.16278537089773978, 'max_features': 'log2', 'min_impurity_decrease': 1.2991862538035283e-06, 'validation_fraction': 0.974238719043193, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:43:45,690] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8990643394736435, 'learning_rate': 0.008813612810119076, 'dropout_rate': 0.5905404972480945, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 6.120501546200477, 'min_weight_fraction_leaf': 0.15260562743112346, 'max_features': 'log2', 'min_impurity_decrease': 7.713426989240967e-06, 'validation_fraction': 0.9231652645655831, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.2131570984624239
Fold 2 IBS: 0.22125145650170608
Fold 3 IBS: 0.20376436569962075
Fold 4 IBS: 0.22358164952119913
Fold 5 IBS: 0.21798966348530077
[I 2024-04-14 15:44:39,839] Trial 71 finished with value: 0.2159488467340501 and parameters: {'subsample': 0.9733969125354864, 'learning_rate': 0.004534805415780903, 'dropout_rate': 0.132474187624217, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.02682769133444822, 'min_weight_fraction_leaf': 0.1936286226601749, 'max_features': 'log2', 'min_impurity_decrease': 8.886845592590798e-07, 'validation_fraction': 0.9729187814085662, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:45:33,424] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9301573375470014, 'learning_rate': 0.003546549118661939, 'dropout_rate': 0.1933034526628665, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.3051396205214099, 'min_weight_fraction_leaf': 0.22121218007981025, 'max_features': 'log2', 'min_impurity_decrease': 1.4531877098171637e-06, 'validation_fraction': 0.9471253058954233, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 15:46:24,885] Trial 73 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.999953059550104, 'learning_rate': 0.016413333024245372, 'dropout_rate': 0.1494767846695832, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.8024489997023381, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'sqrt', 'min_impurity_decrease': 6.897864555007704e-07, 'validation_fraction': 0.8647043482635267, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:46:29,538] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9677492383027341, 'learning_rate': 0.007152092860070451, 'dropout_rate': 0.22741374895706717, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.35084579238043634, 'max_features': 'log2', 'min_impurity_decrease': 2.9943562650383953e-06, 'validation_fraction': 0.8935136450037395, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21271429347002044
Fold 2 IBS: 0.22142050786018577
Fold 3 IBS: 0.20308016236581294
Fold 4 IBS: 0.2224370026772829
Fold 5 IBS: 0.2178500986627367
[I 2024-04-14 15:47:28,571] Trial 75 finished with value: 0.21550041300720774 and parameters: {'subsample': 0.8825286004306149, 'learning_rate': 0.011275284948798047, 'dropout_rate': 0.24636984302682827, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.008819925578928337, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.9658955990718601, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:48:11,036] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8822084861636357, 'learning_rate': 0.022756306561370964, 'dropout_rate': 0.31336983386215705, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.8575030371262532, 'min_weight_fraction_leaf': 0.09504128680510565, 'max_features': None, 'min_impurity_decrease': 0.00034462183165821184, 'validation_fraction': 0.9276129852375451, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 53 with value: 0.21504561735962566.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:48:53,735] Trial 77 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9392590368987991, 'learning_rate': 0.011132229721027662, 'dropout_rate': 0.25203573700169807, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.33381590515318865, 'min_weight_fraction_leaf': 0.13051249394026804, 'max_features': 1, 'min_impurity_decrease': 7.70123021698274e-05, 'validation_fraction': 0.994934454010795, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:49:43,881] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8479726466301248, 'learning_rate': 0.04205291686981777, 'dropout_rate': 0.19830895403108711, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.6761477264897129, 'min_weight_fraction_leaf': 0.25364713658708027, 'max_features': 'auto', 'min_impurity_decrease': 0.0013458661001827122, 'validation_fraction': 0.8409381236879163, 'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:50:24,120] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9212007778521843, 'learning_rate': 0.018691773370111166, 'dropout_rate': 0.3401666755702263, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 1.3697303469982207, 'min_weight_fraction_leaf': 0.059436543656145036, 'max_features': 0.1, 'min_impurity_decrease': 4.409444341620953e-06, 'validation_fraction': 0.9714354901540546, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:50:58,595] Trial 80 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7969534216428152, 'learning_rate': 0.012583222435427047, 'dropout_rate': 0.28829477813771426, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.23485405917391566, 'max_features': 'auto', 'min_impurity_decrease': 6.230227949979902e-05, 'validation_fraction': 0.8858889560798657, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21327366041011542
Fold 2 IBS: 0.2214652687075112
Fold 3 IBS: 0.20384804288543604
Fold 4 IBS: 0.22387672832999023
Fold 5 IBS: 0.21797504874463694
[I 2024-04-14 15:51:40,518] Trial 81 finished with value: 0.21608774981553797 and parameters: {'subsample': 0.9722344486637098, 'learning_rate': 0.0037084225030570616, 'dropout_rate': 0.14904466424240095, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.025432112194026565, 'min_weight_fraction_leaf': 0.27646519093862765, 'max_features': 'auto', 'min_impurity_decrease': 2.61961103925368e-07, 'validation_fraction': 0.9431731904944002, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:52:15,312] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9448720976014137, 'learning_rate': 0.0538447232797746, 'dropout_rate': 0.2311360143359113, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.286660364444207, 'min_weight_fraction_leaf': 0.2885976911827929, 'max_features': 'auto', 'min_impurity_decrease': 0.08366939436473018, 'validation_fraction': 0.9622307477778195, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:52:58,674] Trial 83 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9046881322576289, 'learning_rate': 0.0073983454460704555, 'dropout_rate': 0.17220577471999526, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.6351743384287122, 'min_weight_fraction_leaf': 0.20706187101204562, 'max_features': 'auto', 'min_impurity_decrease': 0.0002249075769166659, 'validation_fraction': 0.9187090458278299, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:53:50,214] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9783982119260082, 'learning_rate': 0.009985920145385636, 'dropout_rate': 0.20939689519159663, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.20835125759711, 'min_weight_fraction_leaf': 0.3292923962058931, 'max_features': 'auto', 'min_impurity_decrease': 4.596257266663254e-07, 'validation_fraction': 0.9759866579556983, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504561735962566.
Fold 1 IBS: 0.210130947047483
Fold 2 IBS: 0.22152929132927757
Fold 3 IBS: 0.20084440770088158
Fold 4 IBS: 0.2198901289484443
Fold 5 IBS: 0.21760692558038056
[I 2024-04-14 15:54:07,086] Trial 85 finished with value: 0.2140003401212934 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.014554866476952134, 'dropout_rate': 0.10391090561180716, 'n_estimators': 265, 'criterion': 'squared_error', 'ccp_alpha': 0.011241474018604543, 'min_weight_fraction_leaf': 0.12733224205170357, 'max_features': 'auto', 'min_impurity_decrease': 1.8697047323397577e-06, 'validation_fraction': 0.9999275626013308, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:54:21,347] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8606137140909582, 'learning_rate': 0.08767662742937916, 'dropout_rate': 0.10513626119564579, 'n_estimators': 241, 'criterion': 'squared_error', 'ccp_alpha': 0.9972723133843666, 'min_weight_fraction_leaf': 0.12562792621841556, 'max_features': 'auto', 'min_impurity_decrease': 1.0043785970844547e-05, 'validation_fraction': 0.9069972250123114, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:54:37,446] Trial 87 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7492693301217667, 'learning_rate': 0.013995510320305746, 'dropout_rate': 0.12354996158381873, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4341718461308403, 'min_weight_fraction_leaf': 0.11226806281497859, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6520281006567596e-06, 'validation_fraction': 0.9988717362956292, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 85 with value: 0.2140003401212934.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 15:55:13,103] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8335693537780458, 'learning_rate': 0.025896998029808806, 'dropout_rate': 0.2592233887917012, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.998777407817298, 'min_weight_fraction_leaf': 0.06882085091143297, 'max_features': 'log2', 'min_impurity_decrease': 2.1900682995121406e-06, 'validation_fraction': 0.9382598277453086, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:55:23,912] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8801139289725153, 'learning_rate': 0.020383519809556987, 'dropout_rate': 0.17834614797528062, 'n_estimators': 209, 'criterion': 'squared_error', 'ccp_alpha': 0.6288168257140196, 'min_weight_fraction_leaf': 0.1838364799257016, 'max_features': 'auto', 'min_impurity_decrease': 3.99756238428e-06, 'validation_fraction': 0.8034906419904587, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:55:33,389] Trial 90 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9063467714031336, 'learning_rate': 0.015446119614603297, 'dropout_rate': 0.49901991527256273, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 2.4090644268425367, 'min_weight_fraction_leaf': 0.1395867989876331, 'max_features': 'auto', 'min_impurity_decrease': 2.2011519634799453e-05, 'validation_fraction': 0.8698393517024319, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.2128591122343161
Fold 2 IBS: 0.22142691927590935
Fold 3 IBS: 0.20345810208349668
Fold 4 IBS: 0.22336589150369232
Fold 5 IBS: 0.2179205991770419
[I 2024-04-14 15:56:25,641] Trial 91 finished with value: 0.2158061248548913 and parameters: {'subsample': 0.9540489140438861, 'learning_rate': 0.005831236591272541, 'dropout_rate': 0.14708835875280205, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.03795241787727033, 'min_weight_fraction_leaf': 0.3042489932965161, 'max_features': 'auto', 'min_impurity_decrease': 1.118647105999176e-06, 'validation_fraction': 0.9699154831592086, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:57:36,154] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.951860889195645, 'learning_rate': 0.007101713560747508, 'dropout_rate': 0.10091584870331681, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.19927212455432985, 'min_weight_fraction_leaf': 0.30595192978898894, 'max_features': 'auto', 'min_impurity_decrease': 1.1064396495665298e-06, 'validation_fraction': 0.9753757089288397, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:58:40,983] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.92180602311204, 'learning_rate': 0.017584949800848754, 'dropout_rate': 0.155352175491657, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.4610108245103026, 'min_weight_fraction_leaf': 0.25029878498224645, 'max_features': 'auto', 'min_impurity_decrease': 5.995680339686021e-06, 'validation_fraction': 0.9407929591551207, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21332722957119254
Fold 2 IBS: 0.22153950213362675
Fold 3 IBS: 0.20391981628635714
Fold 4 IBS: 0.22406454865056313
Fold 5 IBS: 0.217980411216748
[I 2024-04-14 15:59:18,672] Trial 94 finished with value: 0.21616630157169753 and parameters: {'subsample': 0.8793150927230791, 'learning_rate': 0.0027749992265539737, 'dropout_rate': 0.12764820329670162, 'n_estimators': 330, 'criterion': 'squared_error', 'ccp_alpha': 0.058163245004349426, 'min_weight_fraction_leaf': 0.2276941023602314, 'max_features': 'auto', 'min_impurity_decrease': 7.291508576058386e-07, 'validation_fraction': 0.9049661887509745, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 16:00:25,544] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9607117348561939, 'learning_rate': 0.012174074938611536, 'dropout_rate': 0.2185428700896648, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.7661738021343146, 'min_weight_fraction_leaf': 0.04194427014757368, 'max_features': None, 'min_impurity_decrease': 2.2434503326428074e-06, 'validation_fraction': 0.9999156284888805, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 16:00:27,240] Trial 96 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.936238883955148, 'learning_rate': 0.00973456374774443, 'dropout_rate': 0.23827215642775817, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 0.23613296469146558, 'min_weight_fraction_leaf': 0.2672850265092407, 'max_features': 'auto', 'min_impurity_decrease': 9.064174649500895e-07, 'validation_fraction': 0.9555544239307169, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 16:00:35,187] Trial 97 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.008255029347526567, 'dropout_rate': 0.8479620532477699, 'n_estimators': 295, 'criterion': 'friedman_mse', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.1636003712532283, 'max_features': 'auto', 'min_impurity_decrease': 3.679208144644871e-07, 'validation_fraction': 0.9257391585276332, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 85 with value: 0.2140003401212934.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 16:01:21,749] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9024599692364454, 'learning_rate': 0.005266504740966472, 'dropout_rate': 0.18638214668831496, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.9707354386571323, 'min_weight_fraction_leaf': 0.23894367903351932, 'max_features': 1, 'min_impurity_decrease': 3.0399930076335373e-06, 'validation_fraction': 0.9743184170175514, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 85 with value: 0.2140003401212934.

Fold 1 IBS: 0.21256519342739535
Fold 2 IBS: 0.22132501050202244
Fold 3 IBS: 0.2031414835960969
Fold 4 IBS: 0.22299974010438342
Fold 5 IBS: 0.21780142809241373
[I 2024-04-14 16:02:05,842] Trial 99 finished with value: 0.21556657114446237 and parameters: {'subsample': 0.9762156523558686, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2717132298988158, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.004394120129034387, 'min_weight_fraction_leaf': 0.28881659395589254, 'max_features': 'auto', 'min_impurity_decrease': 1.3534409368328512e-06, 'validation_fraction': 0.6748895535913024, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 17}. Best is trial 85 with value: 0.2140003401212934.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.2140003401212934], datetime_start=datetime.datetime(2024, 4, 14, 15, 53, 50, 224687), datetime_complete=datetime.datetime(2024, 4, 14, 15, 54, 7, 85282), params={'subsample': 0.8559905830599279, 'learning_rate': 0.014554866476952134, 'dropout_rate': 0.10391090561180716, 'n_estimators': 265, 'criterion': 'squared_error', 'ccp_alpha': 0.011241474018604543, 'min_weight_fraction_leaf': 0.12733224205170357, 'max_features': 'auto', 'min_impurity_decrease': 1.8697047323397577e-06, 'validation_fraction': 0.9999275626013308, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.2140003401212934

In [93]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [94]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.75
train_ibs:  0.214

#### Test

In [95]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [96]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.604

GradientBoostingSurvivalAnalysis(ccp_alpha=0.011241474018604543,
                                 criterion='squared_error',
                                 dropout_rate=0.10391090561180716,
                                 learning_rate=0.014554866476952134,
                                 max_depth=1, max_features='auto',
                                 max_leaf_nodes=18,
                                 min_impurity_decrease=1.8697047323397577e-06,
                                 min_samples_leaf=19, min_samples_split=20,
                                 min_weight_fraction_leaf=0.12733224205170357,
                                 n_estimators=265, random_state=123,
                                 subsample=0.8559905830599279,
                                 validation_fraction=0.9999275626013308)

IBS: 0.218

In [97]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [98]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:02:11,365] A new study created in memory with name: no-name-1f363243-09ce-4a93-996b-c114b770d2bd

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:02:12,195] Trial 0 finished with value: 0.6737318846686473 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6737318846686473.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:02:18,149] Trial 1 finished with value: 0.6830456101588432 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6830456101588432.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:19,344] Trial 2 finished with value: 0.6869782971901218 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6869782971901218.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:21,034] Trial 3 finished with value: 0.716285896236645 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.716285896236645.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:23,598] Trial 4 finished with value: 0.7231918346764628 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7231918346764628.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:02:26,831] Trial 5 finished with value: 0.6747194387812013 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7231918346764628.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:28,040] Trial 6 finished with value: 0.6105728407426441 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7231918346764628.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:28,289] Trial 7 finished with value: 0.7080352426955969 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7231918346764628.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:29,791] Trial 8 finished with value: 0.6913073015191262 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7231918346764628.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:33,856] Trial 9 finished with value: 0.712022648935423 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7231918346764628.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:02:37,902] Trial 10 finished with value: 0.7310808353471536 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.7310808353471536.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:02:42,525] Trial 11 finished with value: 0.7379541727791783 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7379541727791783.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:02:46,111] Trial 12 finished with value: 0.7397589407811294 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:49,828] Trial 13 finished with value: 0.679353493107157 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:02:52,969] Trial 14 finished with value: 0.7381857683591111 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:55,918] Trial 15 finished with value: 0.7259245186591469 and parameters: {'subsample': 0.2913523637503245, 'dropout_rate': 0.7098041576457912, 'n_estimators': 358, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:03:00,145] Trial 16 finished with value: 0.7276042798114075 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.7326988341376399, 'n_estimators': 427, 'learning_rate': 0.09672186349880336}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:04,198] Trial 17 finished with value: 0.716285896236645 and parameters: {'subsample': 0.39930407886471125, 'dropout_rate': 0.6120620500196721, 'n_estimators': 413, 'learning_rate': 0.08485124701632729}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:03:06,049] Trial 18 finished with value: 0.7353879206668973 and parameters: {'subsample': 0.14033791495138467, 'dropout_rate': 0.8058789888144481, 'n_estimators': 269, 'learning_rate': 0.08436585602805469}. Best is trial 12 with value: 0.7397589407811294.

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:09,247] Trial 19 finished with value: 0.7171516971024459 and parameters: {'subsample': 0.34314044045637715, 'dropout_rate': 0.981979648714702, 'n_estimators': 426, 'learning_rate': 0.09857240282031608}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:09,899] Trial 20 finished with value: 0.7251683128396499 and parameters: {'subsample': 0.2628688080573812, 'dropout_rate': 0.5777838682216713, 'n_estimators': 112, 'learning_rate': 0.0794193638388259}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:03:12,882] Trial 21 finished with value: 0.7370395376500979 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.21378460268571023, 'n_estimators': 316, 'learning_rate': 0.08901916938853777}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:03:15,887] Trial 22 finished with value: 0.7370756843799773 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.3041730696685961, 'n_estimators': 323, 'learning_rate': 0.09182714940833918}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:03:17,937] Trial 23 finished with value: 0.7302016824088102 and parameters: {'subsample': 0.1882001920901971, 'dropout_rate': 0.10003649369276552, 'n_estimators': 245, 'learning_rate': 0.06637801331934103}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:03:22,091] Trial 24 finished with value: 0.7338026514759942 and parameters: {'subsample': 0.2183748063632291, 'dropout_rate': 0.19012024616538375, 'n_estimators': 388, 'learning_rate': 0.0802723125714484}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:03:24,834] Trial 25 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.9684217810899436, 'dropout_rate': 0.7906653928060849, 'n_estimators': 334, 'learning_rate': 0.09163056701298726}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:26,785] Trial 26 finished with value: 0.7213711063851462 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.317052588620237, 'n_estimators': 245, 'learning_rate': 0.09971467815069429}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:29,864] Trial 27 finished with value: 0.7143803123690359 and parameters: {'subsample': 0.30343588867569526, 'dropout_rate': 0.4453876135455366, 'n_estimators': 297, 'learning_rate': 0.07668240729890828}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:36,090] Trial 28 finished with value: 0.6959140305743847 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.17474075028192648, 'n_estimators': 443, 'learning_rate': 0.042046235175604386}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:03:40,450] Trial 29 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.6427050751225806, 'n_estimators': 394, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:41,589] Trial 30 finished with value: 0.7187195912336312 and parameters: {'subsample': 0.21797436717278929, 'dropout_rate': 0.3791228383639579, 'n_estimators': 133, 'learning_rate': 0.09303893229955305}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 16:03:46,560] Trial 31 finished with value: 0.7352709163780263 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.31516050267976004, 'n_estimators': 348, 'learning_rate': 0.09062044606475557}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 16:03:50,093] Trial 32 finished with value: 0.7344270345214862 and parameters: {'subsample': 0.102000681955651, 'dropout_rate': 0.30244311791442025, 'n_estimators': 319, 'learning_rate': 0.09194646383389606}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:03:53,042] Trial 33 finished with value: 0.7371654201478643 and parameters: {'subsample': 0.16795940294767317, 'dropout_rate': 0.13713248579561, 'n_estimators': 285, 'learning_rate': 0.06992697841465893}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:56,280] Trial 34 finished with value: 0.7257506775461768 and parameters: {'subsample': 0.19415457088047122, 'dropout_rate': 0.12285933438817305, 'n_estimators': 282, 'learning_rate': 0.06960500288827107}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:03:58,143] Trial 35 finished with value: 0.7310559798239787 and parameters: {'subsample': 0.16710472630778297, 'dropout_rate': 0.23301770669189245, 'n_estimators': 232, 'learning_rate': 0.07264491128155415}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:04:00,901] Trial 36 finished with value: 0.7302316039788904 and parameters: {'subsample': 0.250554349489907, 'dropout_rate': 0.1720676081613501, 'n_estimators': 293, 'learning_rate': 0.08114720527912062}. Best is trial 12 with value: 0.7397589407811294.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:04:01,020] Trial 37 finished with value: 0.6178652583498918 and parameters: {'subsample': 0.31706282928919705, 'dropout_rate': 0.5033372405124903, 'n_estimators': 1, 'learning_rate': 0.06669997964929306}. Best is trial 12 with value: 0.7397589407811294.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:04:03,208] Trial 38 finished with value: 0.7433447380962142 and parameters: {'subsample': 0.1504722419513361, 'dropout_rate': 0.13272164755980653, 'n_estimators': 209, 'learning_rate': 0.060145822351412026}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:04:04,610] Trial 39 finished with value: 0.7177558397951962 and parameters: {'subsample': 0.25449269996477825, 'dropout_rate': 0.4352656711347185, 'n_estimators': 159, 'learning_rate': 0.01715036845928685}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:04:07,343] Trial 40 finished with value: 0.7337272132308733 and parameters: {'subsample': 0.15008465928971032, 'dropout_rate': 0.27073406810212547, 'n_estimators': 212, 'learning_rate': 0.06253415300532444}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:04:10,643] Trial 41 finished with value: 0.7338169489987603 and parameters: {'subsample': 0.1617409550330779, 'dropout_rate': 0.15122266698842426, 'n_estimators': 269, 'learning_rate': 0.04289291472507567}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:04:12,363] Trial 42 finished with value: 0.7267091506937787 and parameters: {'subsample': 0.22185909007062088, 'dropout_rate': 0.13661676516072546, 'n_estimators': 193, 'learning_rate': 0.052854252960145454}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:04:15,674] Trial 43 finished with value: 0.7373418865025709 and parameters: {'subsample': 0.13840274528511398, 'dropout_rate': 0.2146994580290394, 'n_estimators': 345, 'learning_rate': 0.058447410615200576}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:04:19,328] Trial 44 finished with value: 0.739054434517936 and parameters: {'subsample': 0.13326295226620088, 'dropout_rate': 0.19613675945996956, 'n_estimators': 368, 'learning_rate': 0.034905339922840325}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:04:23,172] Trial 45 finished with value: 0.6737318846686473 and parameters: {'subsample': 0.7634152448919623, 'dropout_rate': 0.1940972006728252, 'n_estimators': 378, 'learning_rate': 0.03400538573985265}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:04:28,492] Trial 46 finished with value: 0.7351032581463193 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.24912349810012271, 'n_estimators': 463, 'learning_rate': 0.024992652172925307}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:04:32,011] Trial 47 finished with value: 0.7154200953708442 and parameters: {'subsample': 0.4367287371870743, 'dropout_rate': 0.3534160384232155, 'n_estimators': 368, 'learning_rate': 0.008209618821055878}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:04:32,996] Trial 48 finished with value: 0.724231617678271 and parameters: {'subsample': 0.282950906586145, 'dropout_rate': 0.7029434264763865, 'n_estimators': 161, 'learning_rate': 0.03049175704883318}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:04:37,525] Trial 49 finished with value: 0.7078251586619834 and parameters: {'subsample': 0.5378859109436699, 'dropout_rate': 0.10625636287606482, 'n_estimators': 408, 'learning_rate': 0.04897928524498507}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:04:39,452] Trial 50 finished with value: 0.7162420582181234 and parameters: {'subsample': 0.3591093973511319, 'dropout_rate': 0.8482868200192901, 'n_estimators': 227, 'learning_rate': 0.09625011741401299}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:04:44,151] Trial 51 finished with value: 0.7364029193664208 and parameters: {'subsample': 0.1407283218547055, 'dropout_rate': 0.22104205221427253, 'n_estimators': 342, 'learning_rate': 0.03781667079781161}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:04:48,241] Trial 52 finished with value: 0.7302944957136487 and parameters: {'subsample': 0.18962767594906982, 'dropout_rate': 0.15484825866880525, 'n_estimators': 355, 'learning_rate': 0.05805636508723685}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 16:04:51,794] Trial 53 finished with value: 0.7369293518392787 and parameters: {'subsample': 0.12235314965386802, 'dropout_rate': 0.2786310061536884, 'n_estimators': 315, 'learning_rate': 0.08627882337790962}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:05:02,617] Trial 54 finished with value: 0.7249527646598923 and parameters: {'subsample': 0.24104796284904234, 'dropout_rate': 0.20342812979572866, 'n_estimators': 399, 'learning_rate': 0.04893045633977665}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:05:06,307] Trial 55 finished with value: 0.7258404845349541 and parameters: {'subsample': 0.18422963055752523, 'dropout_rate': 0.9595597368967024, 'n_estimators': 337, 'learning_rate': 0.09515001809621132}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:05:08,797] Trial 56 finished with value: 0.7281717139521168 and parameters: {'subsample': 0.1444623192750493, 'dropout_rate': 0.10581963580581032, 'n_estimators': 262, 'learning_rate': 0.05477030404321663}. Best is trial 38 with value: 0.7433447380962142.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:05:13,672] Trial 57 finished with value: 0.7378615004973772 and parameters: {'subsample': 0.10164071286601614, 'dropout_rate': 0.1726433853781347, 'n_estimators': 377, 'learning_rate': 0.04604346405894935}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:05:19,492] Trial 58 finished with value: 0.7249746836691532 and parameters: {'subsample': 0.20448031175010015, 'dropout_rate': 0.7611150577494128, 'n_estimators': 498, 'learning_rate': 0.03825681842082981}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:05:25,133] Trial 59 finished with value: 0.740436984085519 and parameters: {'subsample': 0.10183265607410649, 'dropout_rate': 0.16081769550058003, 'n_estimators': 420, 'learning_rate': 0.04678739112518952}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:05:30,320] Trial 60 finished with value: 0.7267603979548676 and parameters: {'subsample': 0.2307778470847467, 'dropout_rate': 0.5261708544682848, 'n_estimators': 437, 'learning_rate': 0.02581638493074427}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:05:34,507] Trial 61 finished with value: 0.7378885567744333 and parameters: {'subsample': 0.11320085735315102, 'dropout_rate': 0.17195154455331807, 'n_estimators': 381, 'learning_rate': 0.04055782990451259}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:05:40,074] Trial 62 finished with value: 0.7317852703894568 and parameters: {'subsample': 0.1686983222146541, 'dropout_rate': 0.15533419619422734, 'n_estimators': 422, 'learning_rate': 0.03951557855154298}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:05:43,503] Trial 63 finished with value: 0.7397761748178097 and parameters: {'subsample': 0.1308716913944263, 'dropout_rate': 0.14015234179102842, 'n_estimators': 307, 'learning_rate': 0.034565110426287064}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:05:45,947] Trial 64 finished with value: 0.6810394443762691 and parameters: {'subsample': 0.6301262021980502, 'dropout_rate': 0.5808876703585089, 'n_estimators': 303, 'learning_rate': 0.031835961557468984}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:05:48,818] Trial 65 finished with value: 0.7398222848111027 and parameters: {'subsample': 0.13444926612718122, 'dropout_rate': 0.13283899373874214, 'n_estimators': 326, 'learning_rate': 0.028524071329710424}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:05:51,557] Trial 66 finished with value: 0.7318871741471187 and parameters: {'subsample': 0.19010997139506086, 'dropout_rate': 0.13206594631703222, 'n_estimators': 308, 'learning_rate': 0.03560058744501941}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:05:54,994] Trial 67 finished with value: 0.7231078453845435 and parameters: {'subsample': 0.2823646720977438, 'dropout_rate': 0.24994481874116348, 'n_estimators': 360, 'learning_rate': 0.021450433380541537}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:06:01,775] Trial 68 finished with value: 0.7178267340907739 and parameters: {'subsample': 0.321654098990298, 'dropout_rate': 0.1950231478494629, 'n_estimators': 480, 'learning_rate': 0.028487992329477657}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:06:05,253] Trial 69 finished with value: 0.740696088237723 and parameters: {'subsample': 0.1334716596015306, 'dropout_rate': 0.13375730086967672, 'n_estimators': 330, 'learning_rate': 0.020578556543934458}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:06:09,337] Trial 70 finished with value: 0.7338659242850774 and parameters: {'subsample': 0.1589079769023451, 'dropout_rate': 0.13033442168372128, 'n_estimators': 327, 'learning_rate': 0.008759417682278697}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:06:12,979] Trial 71 finished with value: 0.7360231715662326 and parameters: {'subsample': 0.13112813702193857, 'dropout_rate': 0.15579325332256724, 'n_estimators': 286, 'learning_rate': 0.019469360272524223}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:06:17,928] Trial 72 finished with value: 0.7397271995314926 and parameters: {'subsample': 0.10376295607569559, 'dropout_rate': 0.2298465162044558, 'n_estimators': 452, 'learning_rate': 0.01570352953327129}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:06:22,258] Trial 73 finished with value: 0.7390245129478556 and parameters: {'subsample': 0.1819109163562955, 'dropout_rate': 0.22186182607397503, 'n_estimators': 452, 'learning_rate': 0.015744940350072067}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:06:26,208] Trial 74 finished with value: 0.7395711832197182 and parameters: {'subsample': 0.10096765999910234, 'dropout_rate': 0.18350004302095232, 'n_estimators': 410, 'learning_rate': 0.012641903268719206}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:06:32,367] Trial 75 finished with value: 0.7397784467925812 and parameters: {'subsample': 0.10152911690959183, 'dropout_rate': 0.10306714054853804, 'n_estimators': 469, 'learning_rate': 0.01246901277424265}. Best is trial 38 with value: 0.7433447380962142.

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:06:38,534] Trial 76 finished with value: 0.7267603979548676 and parameters: {'subsample': 0.20854319000340482, 'dropout_rate': 0.10065019420482439, 'n_estimators': 481, 'learning_rate': 0.011134623759074177}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:06:44,402] Trial 77 finished with value: 0.7339425176706122 and parameters: {'subsample': 0.16443810182525817, 'dropout_rate': 0.1366727040709939, 'n_estimators': 464, 'learning_rate': 0.02235525863801205}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:06:50,445] Trial 78 finished with value: 0.7307638382586863 and parameters: {'subsample': 0.12806592756410884, 'dropout_rate': 0.2365523065112569, 'n_estimators': 453, 'learning_rate': 0.0061942013328675685}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:06:52,591] Trial 79 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.921485886092989, 'dropout_rate': 0.2858527814849339, 'n_estimators': 259, 'learning_rate': 0.015828474815695357}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:07:00,431] Trial 80 finished with value: 0.7248795983895431 and parameters: {'subsample': 0.23747946815265347, 'dropout_rate': 0.12789907194746097, 'n_estimators': 432, 'learning_rate': 0.02822032639372251}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:07:05,696] Trial 81 finished with value: 0.7388470299220354 and parameters: {'subsample': 0.11300715805033669, 'dropout_rate': 0.17883030362375368, 'n_estimators': 409, 'learning_rate': 0.012098323710563099}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:07:10,497] Trial 82 finished with value: 0.740436984085519 and parameters: {'subsample': 0.1025398244352329, 'dropout_rate': 0.15824148450496742, 'n_estimators': 420, 'learning_rate': 0.01894147353816383}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:07:16,821] Trial 83 finished with value: 0.738983540222358 and parameters: {'subsample': 0.1523285066665904, 'dropout_rate': 0.1545509585770798, 'n_estimators': 492, 'learning_rate': 0.018684620403918512}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:07:22,940] Trial 84 finished with value: 0.7310070045376617 and parameters: {'subsample': 0.15335330032078198, 'dropout_rate': 0.12256873616404058, 'n_estimators': 467, 'learning_rate': 0.0036377412211100312}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:07:27,017] Trial 85 finished with value: 0.6727777530159862 and parameters: {'subsample': 0.7830835805399096, 'dropout_rate': 0.11873291879852044, 'n_estimators': 445, 'learning_rate': 0.014235344222877293}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:07:28,893] Trial 86 finished with value: 0.7343134888438917 and parameters: {'subsample': 0.13128320132607293, 'dropout_rate': 0.15336195765434013, 'n_estimators': 274, 'learning_rate': 0.02597634292613239}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:07:32,697] Trial 87 finished with value: 0.740644247658382 and parameters: {'subsample': 0.10122270957789498, 'dropout_rate': 0.2135212766313786, 'n_estimators': 395, 'learning_rate': 0.020105986478236897}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:07:36,199] Trial 88 finished with value: 0.7302121691883288 and parameters: {'subsample': 0.1767651086313396, 'dropout_rate': 0.10140858834066505, 'n_estimators': 391, 'learning_rate': 0.020854415146842838}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:07:40,205] Trial 89 finished with value: 0.7257892372738654 and parameters: {'subsample': 0.20206363252718762, 'dropout_rate': 0.3341614359646641, 'n_estimators': 422, 'learning_rate': 0.02876670522910784}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:07:42,038] Trial 90 finished with value: 0.7239246709640274 and parameters: {'subsample': 0.26859331465546027, 'dropout_rate': 0.21184771909585598, 'n_estimators': 237, 'learning_rate': 0.02443334964981007}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:07:43,716] Trial 91 finished with value: 0.7398763973652152 and parameters: {'subsample': 0.1231326533576678, 'dropout_rate': 0.17042953817703516, 'n_estimators': 207, 'learning_rate': 0.01773726873162489}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:07:44,990] Trial 92 finished with value: 0.7329782044100156 and parameters: {'subsample': 0.14608209890052398, 'dropout_rate': 0.16606882588232813, 'n_estimators': 184, 'learning_rate': 0.018474326694655013}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:07:46,336] Trial 93 finished with value: 0.7389294276682454 and parameters: {'subsample': 0.12047543787603822, 'dropout_rate': 0.41200689746521035, 'n_estimators': 210, 'learning_rate': 0.02314543179864227}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:07:47,092] Trial 94 finished with value: 0.6904415006533254 and parameters: {'subsample': 0.5074727573236094, 'dropout_rate': 0.19549049856634615, 'n_estimators': 140, 'learning_rate': 0.02010885700913518}. Best is trial 38 with value: 0.7433447380962142.

Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:07:50,032] Trial 95 finished with value: 0.7362469030546464 and parameters: {'subsample': 0.10070814134698941, 'dropout_rate': 0.1386144047091815, 'n_estimators': 332, 'learning_rate': 0.046224289726503595}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:07:51,515] Trial 96 finished with value: 0.7265634089175955 and parameters: {'subsample': 0.17273380342214345, 'dropout_rate': 0.11931380628750118, 'n_estimators': 207, 'learning_rate': 0.008815888299473959}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:07:53,612] Trial 97 finished with value: 0.7358981647165422 and parameters: {'subsample': 0.12636100215120372, 'dropout_rate': 0.2631311591503418, 'n_estimators': 290, 'learning_rate': 0.03184901175247192}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:07:55,064] Trial 98 finished with value: 0.7319412867012313 and parameters: {'subsample': 0.21535381388268782, 'dropout_rate': 0.14652621925749548, 'n_estimators': 226, 'learning_rate': 0.017624795956800034}. Best is trial 38 with value: 0.7433447380962142.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8396624472573839

[I 2024-04-14 16:07:57,571] A new study created in memory with name: no-name-40a1d58d-d7f6-4934-8de5-baec28322f53

Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:07:57,561] Trial 99 finished with value: 0.740908177806204 and parameters: {'subsample': 0.15807806801165766, 'dropout_rate': 0.1722062301905459, 'n_estimators': 312, 'learning_rate': 0.052443959168945425}. Best is trial 38 with value: 0.7433447380962142.


* Best trial for C-index:
 FrozenTrial(number=38, state=TrialState.COMPLETE, values=[0.7433447380962142], datetime_start=datetime.datetime(2024, 4, 14, 16, 4, 1, 30620), datetime_complete=datetime.datetime(2024, 4, 14, 16, 4, 3, 207544), params={'subsample': 0.1504722419513361, 'dropout_rate': 0.13272164755980653, 'n_estimators': 209, 'learning_rate': 0.060145822351412026}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=38, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.1504722419513361, 'dropout_rate': 0.13272164755980653, 'n_estimators': 209, 'learning_rate': 0.060145822351412026}


* Best Score for C-index:
 0.7433447380962142

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18616449924037068
Fold 2 IBS: 0.263946415780978
Fold 3 IBS: 0.1617903636180167
Fold 4 IBS: 0.2600787216130082
Fold 5 IBS: 0.23318480871469416
[I 2024-04-14 16:07:58,187] Trial 0 finished with value: 0.22103296179341356 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22103296179341356.
Fold 1 IBS: 0.20583867381980112
Fold 2 IBS: 0.3014080683205247
Fold 3 IBS: 0.17042892249188574
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.27370157532625616
[I 2024-04-14 16:08:03,084] Trial 1 finished with value: 0.25344637818755167 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22103296179341356.
Fold 1 IBS: 0.21323080019017498
Fold 2 IBS: 0.30090488415559263
Fold 3 IBS: 0.1653332066108254
Fold 4 IBS: 0.31368208313434126
Fold 5 IBS: 0.26490979029895373
[I 2024-04-14 16:08:04,038] Trial 2 finished with value: 0.2516121528779776 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22103296179341356.
Fold 1 IBS: 0.22255608795546167
Fold 2 IBS: 0.29867185430046916
Fold 3 IBS: 0.16607224064552437
Fold 4 IBS: 0.31117164271618164
Fold 5 IBS: 0.26803683949365764
[I 2024-04-14 16:08:05,335] Trial 3 finished with value: 0.2533017330222589 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22103296179341356.
Fold 1 IBS: 0.2243761409458102
Fold 2 IBS: 0.3006292211879915
Fold 3 IBS: 0.18415580705258608
Fold 4 IBS: 0.3129746976848504
Fold 5 IBS: 0.26908387741821566
[I 2024-04-14 16:08:07,310] Trial 4 finished with value: 0.2582439488578908 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22103296179341356.
Fold 1 IBS: 0.20363198729052503
Fold 2 IBS: 0.3014078956744048
Fold 3 IBS: 0.16987803315182726
Fold 4 IBS: 0.31585217062420684
Fold 5 IBS: 0.27369201709429525
[I 2024-04-14 16:08:09,242] Trial 5 finished with value: 0.2528924207670518 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22103296179341356.
Fold 1 IBS: 0.18310704731163763
Fold 2 IBS: 0.22574908076349612
Fold 3 IBS: 0.16688500534550946
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.21906832093288123
[I 2024-04-14 16:08:10,050] Trial 6 finished with value: 0.203904372764559 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.203904372764559.
Fold 1 IBS: 0.19238588895181394
Fold 2 IBS: 0.20303779786155224
Fold 3 IBS: 0.17884668693475606
Fold 4 IBS: 0.20856968304886764
Fold 5 IBS: 0.211118754013436
[I 2024-04-14 16:08:10,244] Trial 7 finished with value: 0.19879176216208516 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.1883547563157743
Fold 2 IBS: 0.27502505757765827
Fold 3 IBS: 0.1610534980201046
Fold 4 IBS: 0.26090944510806957
Fold 5 IBS: 0.2349744292756046
[I 2024-04-14 16:08:11,254] Trial 8 finished with value: 0.22406343725944228 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.225901321263773
Fold 2 IBS: 0.3014080117730072
Fold 3 IBS: 0.1827239722426296
Fold 4 IBS: 0.3158524919175079
Fold 5 IBS: 0.2759459715593507
[I 2024-04-14 16:08:14,535] Trial 9 finished with value: 0.26036635375125367 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22091211268741265
Fold 3 IBS: 0.20387901759065918
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21780913258638765
[I 2024-04-14 16:08:14,725] Trial 10 finished with value: 0.21607415429104124 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.2133947249090869
Fold 2 IBS: 0.22105802807283764
Fold 3 IBS: 0.2036691246434108
Fold 4 IBS: 0.22398071517140083
Fold 5 IBS: 0.21777799603810094
[I 2024-04-14 16:08:14,851] Trial 11 finished with value: 0.2159761177669674 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.21073457180663963
Fold 2 IBS: 0.297403850587758
Fold 3 IBS: 0.166240929591416
Fold 4 IBS: 0.2951010461548506
Fold 5 IBS: 0.25346374715090736
[I 2024-04-14 16:08:15,349] Trial 12 finished with value: 0.24458882905831433 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.19280005315897206
Fold 2 IBS: 0.2974213595064474
Fold 3 IBS: 0.17117639615033295
Fold 4 IBS: 0.30578737203308676
Fold 5 IBS: 0.25431185381872007
[I 2024-04-14 16:08:17,542] Trial 13 finished with value: 0.24429940693351188 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.19784216344977562
Fold 2 IBS: 0.20506180854560294
Fold 3 IBS: 0.18635045949578385
Fold 4 IBS: 0.21499223626865088
Fold 5 IBS: 0.21149042228501566
[I 2024-04-14 16:08:18,069] Trial 14 finished with value: 0.20314741800896577 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.21034404799392553
Fold 2 IBS: 0.21734365927334173
Fold 3 IBS: 0.20020119375698603
Fold 4 IBS: 0.22200456556272022
Fold 5 IBS: 0.21659611545289936
[I 2024-04-14 16:08:18,396] Trial 15 finished with value: 0.21329791640797455 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.20390076946850394
Fold 2 IBS: 0.2103474992415337
Fold 3 IBS: 0.19339791850328025
Fold 4 IBS: 0.21877297557249897
Fold 5 IBS: 0.21360848363027263
[I 2024-04-14 16:08:18,668] Trial 16 finished with value: 0.20800552928321786 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.18288342929944057
Fold 2 IBS: 0.23926430161132384
Fold 3 IBS: 0.16665249308120655
Fold 4 IBS: 0.2362841280803267
Fold 5 IBS: 0.22353483274970617
[I 2024-04-14 16:08:19,256] Trial 17 finished with value: 0.20972383696440078 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.19131272151145176
Fold 2 IBS: 0.24024111720982294
Fold 3 IBS: 0.16259717008092162
Fold 4 IBS: 0.22670032118705843
Fold 5 IBS: 0.22295397631420336
[I 2024-04-14 16:08:21,689] Trial 18 finished with value: 0.20876106126069166 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19879176216208516.
Fold 1 IBS: 0.19369144727442017
Fold 2 IBS: 0.20203527146615424
Fold 3 IBS: 0.1791566572354982

Fold 4 IBS: 0.2022095506401677
Fold 5 IBS: 0.2127622739815413
[I 2024-04-14 16:08:21,965] Trial 19 finished with value: 0.19797104011955632 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.20068725004069762
Fold 2 IBS: 0.20471613577420322
Fold 3 IBS: 0.1822100971019276
Fold 4 IBS: 0.2037658040680384
Fold 5 IBS: 0.21298081915188694
[I 2024-04-14 16:08:22,205] Trial 20 finished with value: 0.20087202122735076 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.19923087328677447
Fold 2 IBS: 0.20365798928368803
Fold 3 IBS: 0.1877487574780825
Fold 4 IBS: 0.20969793119821276
Fold 5 IBS: 0.21303933620208118
[I 2024-04-14 16:08:22,456] Trial 21 finished with value: 0.20267497748976782 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.21318161944289735
Fold 2 IBS: 0.22073279019144837
Fold 3 IBS: 0.20313821183683503
Fold 4 IBS: 0.22386245547893124
Fold 5 IBS: 0.2175077980822652
[I 2024-04-14 16:08:22,653] Trial 22 finished with value: 0.21568457500647545 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.19580251908676286
Fold 2 IBS: 0.234033112745325
Fold 3 IBS: 0.16646790695483146
Fold 4 IBS: 0.22513140435765808
Fold 5 IBS: 0.22623410400791188
[I 2024-04-14 16:08:23,383] Trial 23 finished with value: 0.20953380943049787 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.187838484906368
Fold 2 IBS: 0.2124184957753865
Fold 3 IBS: 0.16839399220873313
Fold 4 IBS: 0.21192615623352185
Fold 5 IBS: 0.21327382867550682
[I 2024-04-14 16:08:23,691] Trial 24 finished with value: 0.19877019155990325 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.18809348869110823
Fold 2 IBS: 0.2613406847101467
Fold 3 IBS: 0.16154029812386547
Fold 4 IBS: 0.2530341774375341
Fold 5 IBS: 0.22930188107334332
[I 2024-04-14 16:08:24,011] Trial 25 finished with value: 0.21866210600719954 and parameters: {'subsample': 0.41513882888547626, 'dropout_rate': 0.92193566363172, 'n_estimators': 70, 'learning_rate': 0.08579428551722094}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.20627067813338804
Fold 2 IBS: 0.2985918938567073
Fold 3 IBS: 0.16263813544153358
Fold 4 IBS: 0.3060194232926818
Fold 5 IBS: 0.2556802208583101
[I 2024-04-14 16:08:24,576] Trial 26 finished with value: 0.24584007031652416 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9863699266040719, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.2483520164403823
Fold 2 IBS: 0.30140793076134154
Fold 3 IBS: 0.2636275161109598
Fold 4 IBS: 0.31584901382864344
Fold 5 IBS: 0.2814970895229344
[I 2024-04-14 16:08:27,215] Trial 27 finished with value: 0.28214671333285224 and parameters: {'subsample': 0.26021450312326855, 'dropout_rate': 0.9019594475838296, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.19818933191244062
Fold 2 IBS: 0.30021973088050485
Fold 3 IBS: 0.16582318707762056
Fold 4 IBS: 0.3115140810699333
Fold 5 IBS: 0.26099002390515563
[I 2024-04-14 16:08:28,215] Trial 28 finished with value: 0.24734727096913098 and parameters: {'subsample': 0.5971669636685615, 'dropout_rate': 0.7292365612928325, 'n_estimators': 236, 'learning_rate': 0.046726352221374515}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.19756315738932123
Fold 2 IBS: 0.28472280021030205
Fold 3 IBS: 0.16185774322786736
Fold 4 IBS: 0.2711770044559298
Fold 5 IBS: 0.23947299482188275
[I 2024-04-14 16:08:28,565] Trial 29 finished with value: 0.23095874002106065 and parameters: {'subsample': 0.3457177033536965, 'dropout_rate': 0.528113503868086, 'n_estimators': 97, 'learning_rate': 0.08423642007181871}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.20620435261059059
Fold 2 IBS: 0.2710458939557432
Fold 3 IBS: 0.16612797448888714
Fold 4 IBS: 0.27724032379425617
Fold 5 IBS: 0.2400789372188414
[I 2024-04-14 16:08:29,029] Trial 30 finished with value: 0.2321394964136637 and parameters: {'subsample': 0.21287332299822773, 'dropout_rate': 0.8300645798351977, 'n_estimators': 136, 'learning_rate': 0.05802531255595394}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.20285082726456757
Fold 2 IBS: 0.20204126890368998
Fold 3 IBS: 0.18150797830168655
Fold 4 IBS: 0.20292924552991412
Fold 5 IBS: 0.21253378333371506
[I 2024-04-14 16:08:29,203] Trial 31 finished with value: 0.20037262066671463 and parameters: {'subsample': 0.15465256682910847, 'dropout_rate': 0.7665254119155692, 'n_estimators': 42, 'learning_rate': 0.04796619662341173}. Best is trial 19 with value: 0.19797104011955632.
Fold 1 IBS: 0.19439883237296693
Fold 2 IBS: 0.20372246868237415
Fold 3 IBS: 0.16959153862805113
Fold 4 IBS: 0.19617721002654626
Fold 5 IBS: 0.21631715152864392
[I 2024-04-14 16:08:29,459] Trial 32 finished with value: 0.19604144024771647 and parameters: {'subsample': 0.10342193656652618, 'dropout_rate': 0.9389584836732486, 'n_estimators': 75, 'learning_rate': 0.04909887443838165}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.1957614816272351
Fold 2 IBS: 0.2151234281284184
Fold 3 IBS: 0.16626291641534768
Fold 4 IBS: 0.19862721537247233
Fold 5 IBS: 0.2253870769017566
[I 2024-04-14 16:08:29,745] Trial 33 finished with value: 0.20023242368904604 and parameters: {'subsample': 0.10208424258330755, 'dropout_rate': 0.9403857915538653, 'n_estimators': 83, 'learning_rate': 0.06551759244107816}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.20388449364700292
Fold 2 IBS: 0.25240289511777414
Fold 3 IBS: 0.1657184619408839
Fold 4 IBS: 0.2381678868827621
Fold 5 IBS: 0.23019444607974637
[I 2024-04-14 16:08:30,145] Trial 34 finished with value: 0.21807363673363386 and parameters: {'subsample': 0.24704557287293782, 'dropout_rate': 0.8845153148697099, 'n_estimators': 117, 'learning_rate': 0.05431811963817772}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.22063638110374137
Fold 2 IBS: 0.30058952057488775
Fold 3 IBS: 0.18101482975356473
Fold 4 IBS: 0.31355071695292835
Fold 5 IBS: 0.26608749094869316
[I 2024-04-14 16:08:30,776] Trial 35 finished with value: 0.25637578786676307 and parameters: {'subsample': 0.28559921712927905, 'dropout_rate': 0.9999535847337064, 'n_estimators': 169, 'learning_rate': 0.07576486700752832}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.19368451412355756
Fold 2 IBS: 0.20352105079043875
Fold 3 IBS: 0.17987011632498276
Fold 4 IBS: 0.21110761478937795
Fold 5 IBS: 0.21187425603929855
[I 2024-04-14 16:08:31,026] Trial 36 finished with value: 0.2000115104135311 and parameters: {'subsample': 0.5482904864089116, 'dropout_rate': 0.2752164386068012, 'n_estimators': 56, 'learning_rate': 0.03480648546176091}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.2012745009597086
Fold 2 IBS: 0.20603077757432123
Fold 3 IBS: 0.18835433383213504
Fold 4 IBS: 0.21599518178990948
Fold 5 IBS: 0.21247831770711081
[I 2024-04-14 16:08:31,169] Trial 37 finished with value: 0.20482662237263707 and parameters: {'subsample': 0.44388445357645306, 'dropout_rate': 0.8514106000762348, 'n_estimators': 22, 'learning_rate': 0.05486252614066895}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.22419028360051443
Fold 2 IBS: 0.2924201189046871
Fold 3 IBS: 0.17290991289182306
Fold 4 IBS: 0.30862333457815316

Fold 5 IBS: 0.26662175943776306
[I 2024-04-14 16:08:32,174] Trial 38 finished with value: 0.25295308188258814 and parameters: {'subsample': 0.35903417688251527, 'dropout_rate': 0.13272164755980653, 'n_estimators': 193, 'learning_rate': 0.07288612365177065}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.1972909823247562
Fold 2 IBS: 0.20320053346101893
Fold 3 IBS: 0.17708674952568834
Fold 4 IBS: 0.20372925950742424
Fold 5 IBS: 0.2114049622527249
[I 2024-04-14 16:08:32,471] Trial 39 finished with value: 0.19854249741432253 and parameters: {'subsample': 0.20700382404468165, 'dropout_rate': 0.9399951930137062, 'n_estimators': 86, 'learning_rate': 0.026251810001924513}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.19417702817107751
Fold 2 IBS: 0.2078048226758091
Fold 3 IBS: 0.17035677829557183
Fold 4 IBS: 0.19793915275395146
Fold 5 IBS: 0.21558203755241076
[I 2024-04-14 16:08:33,076] Trial 40 finished with value: 0.19717196388976416 and parameters: {'subsample': 0.186264740642415, 'dropout_rate': 0.9444595771528164, 'n_estimators': 164, 'learning_rate': 0.02296123477331362}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.19778892442136892
Fold 2 IBS: 0.20189552290138074
Fold 3 IBS: 0.17863720461490437
Fold 4 IBS: 0.2026046719768525
Fold 5 IBS: 0.21181298546200442
[I 2024-04-14 16:08:33,454] Trial 41 finished with value: 0.1985478618753022 and parameters: {'subsample': 0.1839035633818336, 'dropout_rate': 0.9375500166641096, 'n_estimators': 108, 'learning_rate': 0.02097046727914029}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.1992228006892925
Fold 2 IBS: 0.20652872066700895
Fold 3 IBS: 0.1706497999420702
Fold 4 IBS: 0.19873167661412453
Fold 5 IBS: 0.21564186409285996
[I 2024-04-14 16:08:34,099] Trial 42 finished with value: 0.19815497240107122 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.9502839866610097, 'n_estimators': 172, 'learning_rate': 0.021669528246607672}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.20369267778989444
Fold 2 IBS: 0.24197059587821343
Fold 3 IBS: 0.16685770662068367
Fold 4 IBS: 0.22204963291006452
Fold 5 IBS: 0.23089051033195399
[I 2024-04-14 16:08:35,106] Trial 43 finished with value: 0.21309222470616201 and parameters: {'subsample': 0.16879775270556427, 'dropout_rate': 0.9401884291563184, 'n_estimators': 239, 'learning_rate': 0.027633234880330062}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.1993638182046059
Fold 2 IBS: 0.24516002414981797
Fold 3 IBS: 0.16527905404327356
Fold 4 IBS: 0.23557722602575498
Fold 5 IBS: 0.22793340115976507
[I 2024-04-14 16:08:36,346] Trial 44 finished with value: 0.21466270471664353 and parameters: {'subsample': 0.23033728297350095, 'dropout_rate': 0.8573033377127168, 'n_estimators': 274, 'learning_rate': 0.02246734757333361}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.20061413807912296
Fold 2 IBS: 0.21270389792563363
Fold 3 IBS: 0.1675440471927909
Fold 4 IBS: 0.19572713138778092
Fold 5 IBS: 0.22777779193127756
[I 2024-04-14 16:08:36,978] Trial 45 finished with value: 0.20087340130332118 and parameters: {'subsample': 0.10567550426945373, 'dropout_rate': 0.876434421184881, 'n_estimators': 167, 'learning_rate': 0.03605877651873948}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.1953698022817735
Fold 2 IBS: 0.2033236152798275
Fold 3 IBS: 0.1797085065892355
Fold 4 IBS: 0.2087304752597342
Fold 5 IBS: 0.21170735393860696
[I 2024-04-14 16:08:37,807] Trial 46 finished with value: 0.19976795066983555 and parameters: {'subsample': 0.2812957241517038, 'dropout_rate': 0.9617844883175679, 'n_estimators': 206, 'learning_rate': 0.009764736328478884}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.2017294602206921
Fold 2 IBS: 0.2080092402101696
Fold 3 IBS: 0.1688031316347514
Fold 4 IBS: 0.1971684106949414
Fold 5 IBS: 0.21721903375832413
[I 2024-04-14 16:08:38,409] Trial 47 finished with value: 0.19858585530377573 and parameters: {'subsample': 0.15284574765574857, 'dropout_rate': 0.8193966297270712, 'n_estimators': 155, 'learning_rate': 0.0273012980062123}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.1928175205104938
Fold 2 IBS: 0.2030950809742697
Fold 3 IBS: 0.17621829176680626
Fold 4 IBS: 0.20531144797917425
Fold 5 IBS: 0.21270874299360706
[I 2024-04-14 16:08:38,903] Trial 48 finished with value: 0.1980302168448702 and parameters: {'subsample': 0.3116857468966071, 'dropout_rate': 0.19701471782839963, 'n_estimators': 128, 'learning_rate': 0.01895953746006607}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.19025604382501451
Fold 2 IBS: 0.20921544236152814
Fold 3 IBS: 0.16946921372248597
Fold 4 IBS: 0.2056844734623707
Fold 5 IBS: 0.21358333241396235
[I 2024-04-14 16:08:39,798] Trial 49 finished with value: 0.19764170115707233 and parameters: {'subsample': 0.3184068433782157, 'dropout_rate': 0.23835111634576434, 'n_estimators': 180, 'learning_rate': 0.0181537697215976}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.19087658479408096
Fold 2 IBS: 0.21758471492798806
Fold 3 IBS: 0.16547245035942776
Fold 4 IBS: 0.20928710241384432
Fold 5 IBS: 0.21639789850151822
[I 2024-04-14 16:08:41,189] Trial 50 finished with value: 0.19992375019937186 and parameters: {'subsample': 0.3098092482319106, 'dropout_rate': 0.2258973781082202, 'n_estimators': 225, 'learning_rate': 0.01810994891290756}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.19406131735764298
Fold 2 IBS: 0.20158908836299005
Fold 3 IBS: 0.17908014800203373
Fold 4 IBS: 0.20325407250515765
Fold 5 IBS: 0.2133048409022858
[I 2024-04-14 16:08:42,172] Trial 51 finished with value: 0.19825789342602204 and parameters: {'subsample': 0.1422401972634589, 'dropout_rate': 0.19456677676702935, 'n_estimators': 189, 'learning_rate': 0.011932577411597124}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.2034685732024422
Fold 2 IBS: 0.20947980541521144
Fold 3 IBS: 0.1918310453065671
Fold 4 IBS: 0.2165090276084233
Fold 5 IBS: 0.2140375341234582
[I 2024-04-14 16:08:43,006] Trial 52 finished with value: 0.20706519713122046 and parameters: {'subsample': 0.31646646241728266, 'dropout_rate': 0.33691303844747666, 'n_estimators': 122, 'learning_rate': 0.0074570127989531925}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.1988200331120072
Fold 2 IBS: 0.2050858847694448
Fold 3 IBS: 0.1717510398363619
Fold 4 IBS: 0.20108817382214955
Fold 5 IBS: 0.2140769440402836
[I 2024-04-14 16:08:44,185] Trial 53 finished with value: 0.1981644151160494 and parameters: {'subsample': 0.1789709161645828, 'dropout_rate': 0.10429703996386479, 'n_estimators': 182, 'learning_rate': 0.018503864538777906}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.2083000121668235
Fold 2 IBS: 0.2828065986073804
Fold 3 IBS: 0.1632352646207681
Fold 4 IBS: 0.2819513362686181
Fold 5 IBS: 0.24244180605339646
[I 2024-04-14 16:08:46,465] Trial 54 finished with value: 0.23574700354339734 and parameters: {'subsample': 0.24637694913461222, 'dropout_rate': 0.4696570830043314, 'n_estimators': 270, 'learning_rate': 0.031426128544395436}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.2051596825154474
Fold 2 IBS: 0.21023080438903832
Fold 3 IBS: 0.19255850212354314
Fold 4 IBS: 0.214680391906038
Fold 5 IBS: 0.2149577596158842
[I 2024-04-14 16:08:47,303] Trial 55 finished with value: 0.20751742810999022 and parameters: {'subsample': 0.12706066367364094, 'dropout_rate': 0.32271525796131617, 'n_estimators': 137, 'learning_rate': 0.00667503859893398}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.21134015155375896
Fold 2 IBS: 0.21859351561560403
Fold 3 IBS: 0.20135151491396447
Fold 4 IBS: 0.22230102026020537
Fold 5 IBS: 0.2169241416447728
[I 2024-04-14 16:08:48,438] Trial 56 finished with value: 0.21410206879766108 and parameters: {'subsample': 0.22724015845705592, 'dropout_rate': 0.38192135323648757, 'n_estimators': 218, 'learning_rate': 0.0010228608879443608}. Best is trial 32 with value: 0.19604144024771647.
Fold 1 IBS: 0.19571763232342546
Fold 2 IBS: 0.19973514770333758
Fold 3 IBS: 0.17343505862338873
Fold 4 IBS: 0.19654186381422176

Fold 5 IBS: 0.213339381812701
[I 2024-04-14 16:08:49,118] Trial 57 finished with value: 0.19575381685541493 and parameters: {'subsample': 0.10313673325198738, 'dropout_rate': 0.421255149383966, 'n_estimators': 162, 'learning_rate': 0.018004642634063723}. Best is trial 57 with value: 0.19575381685541493.
Fold 1 IBS: 0.19280446652074382
Fold 2 IBS: 0.20352814494078572
Fold 3 IBS: 0.18000828642387096
Fold 4 IBS: 0.21218869787241948
Fold 5 IBS: 0.21078621095198513
[I 2024-04-14 16:08:49,521] Trial 58 finished with value: 0.19986316134196103 and parameters: {'subsample': 0.7591484265070766, 'dropout_rate': 0.17404595544613377, 'n_estimators': 108, 'learning_rate': 0.018185519971222298}. Best is trial 57 with value: 0.19575381685541493.
Fold 1 IBS: 0.19554473539337386
Fold 2 IBS: 0.20398169137465574
Fold 3 IBS: 0.16932903909533784
Fold 4 IBS: 0.19333352166708745
Fold 5 IBS: 0.2177867063000703
[I 2024-04-14 16:08:49,850] Trial 59 finished with value: 0.19599513876610503 and parameters: {'subsample': 0.10172073603384334, 'dropout_rate': 0.2746066066969284, 'n_estimators': 75, 'learning_rate': 0.05049465638915113}. Best is trial 57 with value: 0.19575381685541493.
Fold 1 IBS: 0.2313616619372404
Fold 2 IBS: 0.29923525716046867
Fold 3 IBS: 0.2184556205082481
Fold 4 IBS: 0.31113272211074966
Fold 5 IBS: 0.2681288330075612
[I 2024-04-14 16:08:51,551] Trial 60 finished with value: 0.26566281894485366 and parameters: {'subsample': 0.1282775782602436, 'dropout_rate': 0.43448883867214505, 'n_estimators': 310, 'learning_rate': 0.050522356662528564}. Best is trial 57 with value: 0.19575381685541493.
Fold 1 IBS: 0.19306327024431033
Fold 2 IBS: 0.20233366922807236
Fold 3 IBS: 0.17036139909844358
Fold 4 IBS: 0.19494025140877866
Fold 5 IBS: 0.21578175692695914
[I 2024-04-14 16:08:51,857] Trial 61 finished with value: 0.1952960693813128 and parameters: {'subsample': 0.11334850912591418, 'dropout_rate': 0.28530369627574803, 'n_estimators': 81, 'learning_rate': 0.04638609876136642}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.2076034178485681
Fold 2 IBS: 0.21429658141670935
Fold 3 IBS: 0.196120898121058
Fold 4 IBS: 0.21857353549643066
Fold 5 IBS: 0.21539206490628873
[I 2024-04-14 16:08:51,969] Trial 62 finished with value: 0.210397299557811 and parameters: {'subsample': 0.10595088493079285, 'dropout_rate': 0.2862649436650928, 'n_estimators': 12, 'learning_rate': 0.04628063915183863}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.1935303657813569
Fold 2 IBS: 0.199752903400393
Fold 3 IBS: 0.17478989516129412
Fold 4 IBS: 0.19825608497527838
Fold 5 IBS: 0.21265977600026392
[I 2024-04-14 16:08:52,235] Trial 63 finished with value: 0.1957978050637173 and parameters: {'subsample': 0.17916189171795813, 'dropout_rate': 0.22618414115243238, 'n_estimators': 70, 'learning_rate': 0.03722156923972461}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.1956515537473573
Fold 2 IBS: 0.20377319325971938
Fold 3 IBS: 0.17393097533115037
Fold 4 IBS: 0.19963720631407036
Fold 5 IBS: 0.21284957220150774
[I 2024-04-14 16:08:52,498] Trial 64 finished with value: 0.19716850017076104 and parameters: {'subsample': 0.20130986621438657, 'dropout_rate': 0.3259066391233286, 'n_estimators': 72, 'learning_rate': 0.03677464882984977}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.20038201837349384
Fold 2 IBS: 0.2042927042133778
Fold 3 IBS: 0.17023550550738767
Fold 4 IBS: 0.19262943622336476
Fold 5 IBS: 0.21488340326224456
[I 2024-04-14 16:08:52,752] Trial 65 finished with value: 0.1964846135159737 and parameters: {'subsample': 0.1891842550240412, 'dropout_rate': 0.30699901634768423, 'n_estimators': 69, 'learning_rate': 0.051012681300476426}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.18960364569402158
Fold 2 IBS: 0.20650343762908405
Fold 3 IBS: 0.1706209960941412
Fold 4 IBS: 0.19853007696162914
Fold 5 IBS: 0.21660071588877497
[I 2024-04-14 16:08:53,026] Trial 66 finished with value: 0.19637177445353018 and parameters: {'subsample': 0.13847920208425626, 'dropout_rate': 0.3023750310399727, 'n_estimators': 74, 'learning_rate': 0.05200166467272412}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.19772564675015877
Fold 2 IBS: 0.2041080921376836
Fold 3 IBS: 0.18570516369047202
Fold 4 IBS: 0.2072296233730369
Fold 5 IBS: 0.21314996547295761
[I 2024-04-14 16:08:53,164] Trial 67 finished with value: 0.20158369828486178 and parameters: {'subsample': 0.13749192120768583, 'dropout_rate': 0.41743727289281723, 'n_estimators': 28, 'learning_rate': 0.057548158814402166}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.1988630271632426
Fold 2 IBS: 0.2049399810476793
Fold 3 IBS: 0.17032486173169334
Fold 4 IBS: 0.19799608754123535
Fold 5 IBS: 0.2161858354079857
[I 2024-04-14 16:08:53,443] Trial 68 finished with value: 0.19766195857836727 and parameters: {'subsample': 0.1689246539142521, 'dropout_rate': 0.2934066010455614, 'n_estimators': 77, 'learning_rate': 0.05037400013902345}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.1951999614891381
Fold 2 IBS: 0.204493081458928
Fold 3 IBS: 0.171133892033508
Fold 4 IBS: 0.1985838432326094
Fold 5 IBS: 0.21923827277971294
[I 2024-04-14 16:08:53,797] Trial 69 finished with value: 0.19772981019877928 and parameters: {'subsample': 0.13154921608577017, 'dropout_rate': 0.36773319853752356, 'n_estimators': 95, 'learning_rate': 0.04479764382635027}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.19256452860392145
Fold 2 IBS: 0.20285885331868422
Fold 3 IBS: 0.17582846248289144
Fold 4 IBS: 0.20797521781767522
Fold 5 IBS: 0.21177623419430222
[I 2024-04-14 16:08:53,982] Trial 70 finished with value: 0.19820065928349492 and parameters: {'subsample': 0.26729636330730483, 'dropout_rate': 0.5124687289167638, 'n_estimators': 45, 'learning_rate': 0.05216997405012591}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.1979667394621376
Fold 2 IBS: 0.20384208743781324
Fold 3 IBS: 0.17496252651743532
Fold 4 IBS: 0.1997853665862999
Fold 5 IBS: 0.2130804239687356
[I 2024-04-14 16:08:54,225] Trial 71 finished with value: 0.19792742879448433 and parameters: {'subsample': 0.20032484226973402, 'dropout_rate': 0.3219789313862047, 'n_estimators': 65, 'learning_rate': 0.03851868044147631}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.19745744338519472
Fold 2 IBS: 0.202579544320405
Fold 3 IBS: 0.1716875459633376
Fold 4 IBS: 0.19640699777437343
Fold 5 IBS: 0.21402489181868728
[I 2024-04-14 16:08:54,493] Trial 72 finished with value: 0.1964312846523996 and parameters: {'subsample': 0.15787650486386842, 'dropout_rate': 0.2563962840781637, 'n_estimators': 70, 'learning_rate': 0.04858825304862183}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.19409041667980093
Fold 2 IBS: 0.21418494438070435
Fold 3 IBS: 0.16809854316042425
Fold 4 IBS: 0.20180056594002194
Fold 5 IBS: 0.2215318693520864
[I 2024-04-14 16:08:54,828] Trial 73 finished with value: 0.19994126790260758 and parameters: {'subsample': 0.14919782090187933, 'dropout_rate': 0.25045520267310317, 'n_estimators': 91, 'learning_rate': 0.05811240126534942}. Best is trial 61 with value: 0.1952960693813128.
Fold 1 IBS: 0.19232406214832323
Fold 2 IBS: 0.20225881747253238
Fold 3 IBS: 0.17572626055950774
Fold 4 IBS: 0.19205875040528667
Fold 5 IBS: 0.2135124000048291
[I 2024-04-14 16:08:55,074] Trial 74 finished with value: 0.1951760581180958 and parameters: {'subsample': 0.10089355489704338, 'dropout_rate': 0.21783955501483004, 'n_estimators': 60, 'learning_rate': 0.048030521288328076}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19959462304132355
Fold 2 IBS: 0.20579156155587813
Fold 3 IBS: 0.18515565040806217
Fold 4 IBS: 0.20412404849029875
Fold 5 IBS: 0.21351089850016883
[I 2024-04-14 16:08:55,241] Trial 75 finished with value: 0.2016353563991463 and parameters: {'subsample': 0.1026661015363873, 'dropout_rate': 0.20683148784012545, 'n_estimators': 34, 'learning_rate': 0.04794851018671188}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19085373411606432
Fold 2 IBS: 0.19910308387337164
Fold 3 IBS: 0.1803204315484361
Fold 4 IBS: 0.19934631945667425
Fold 5 IBS: 0.21393582191207397
[I 2024-04-14 16:08:55,458] Trial 76 finished with value: 0.19671187818132405 and parameters: {'subsample': 0.12538824117588243, 'dropout_rate': 0.34829268282242476, 'n_estimators': 54, 'learning_rate': 0.04391130430874742}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.20507992338528833
Fold 2 IBS: 0.21037230435895432

Fold 3 IBS: 0.1925557724764544
Fold 4 IBS: 0.2127816245380913
Fold 5 IBS: 0.2134268175780662
[I 2024-04-14 16:08:55,574] Trial 77 finished with value: 0.2068432884673709 and parameters: {'subsample': 0.2240545714205724, 'dropout_rate': 0.2677960442541683, 'n_estimators': 14, 'learning_rate': 0.062339761242765926}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19688995298276135
Fold 2 IBS: 0.21142148860933466
Fold 3 IBS: 0.16640432906604044
Fold 4 IBS: 0.20699514299097024
Fold 5 IBS: 0.22400216335201178
[I 2024-04-14 16:08:55,989] Trial 78 finished with value: 0.20114261540022368 and parameters: {'subsample': 0.15412816920461153, 'dropout_rate': 0.1645556222499458, 'n_estimators': 102, 'learning_rate': 0.05561449846981878}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19250802046649604
Fold 2 IBS: 0.19996534210019845
Fold 3 IBS: 0.17285018388546095
Fold 4 IBS: 0.19440265323113975
Fold 5 IBS: 0.21939539321623278
[I 2024-04-14 16:08:56,316] Trial 79 finished with value: 0.1958243185799056 and parameters: {'subsample': 0.12336526172727996, 'dropout_rate': 0.13630478514415645, 'n_estimators': 84, 'learning_rate': 0.048433324158945155}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.1968960204168822
Fold 2 IBS: 0.19837168548159934
Fold 3 IBS: 0.17194037677356974
Fold 4 IBS: 0.19667480366690374
Fold 5 IBS: 0.21723816710346258
[I 2024-04-14 16:08:56,691] Trial 80 finished with value: 0.1962242106884835 and parameters: {'subsample': 0.10223299446840077, 'dropout_rate': 0.14030017497322128, 'n_estimators': 83, 'learning_rate': 0.04134696335030616}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19248315049526918
Fold 2 IBS: 0.19896854627204988
Fold 3 IBS: 0.17383693956090937
Fold 4 IBS: 0.19487570275595162
Fold 5 IBS: 0.21761035269649168
[I 2024-04-14 16:08:57,052] Trial 81 finished with value: 0.19555493835613436 and parameters: {'subsample': 0.11771047020809867, 'dropout_rate': 0.13421931104643997, 'n_estimators': 87, 'learning_rate': 0.04200927057715574}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19826552538618075
Fold 2 IBS: 0.1993893864247793
Fold 3 IBS: 0.1745232031745843
Fold 4 IBS: 0.19926451191152714
Fold 5 IBS: 0.2155196430948856
[I 2024-04-14 16:08:57,442] Trial 82 finished with value: 0.1973924539983914 and parameters: {'subsample': 0.10310784096437117, 'dropout_rate': 0.1319883274935632, 'n_estimators': 87, 'learning_rate': 0.03349975089079242}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.20201072487781102
Fold 2 IBS: 0.2075785200181195
Fold 3 IBS: 0.16845661996927455
Fold 4 IBS: 0.18962168790616096
Fold 5 IBS: 0.22282214367798825
[I 2024-04-14 16:08:57,974] Trial 83 finished with value: 0.19809793928987085 and parameters: {'subsample': 0.1255373257207335, 'dropout_rate': 0.10795141858654457, 'n_estimators': 118, 'learning_rate': 0.04193008300215404}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.1976050315153014
Fold 2 IBS: 0.2055721446366437
Fold 3 IBS: 0.18345313387064976
Fold 4 IBS: 0.20803679157696015
Fold 5 IBS: 0.21275320368492343
[I 2024-04-14 16:08:58,196] Trial 84 finished with value: 0.20148406105689567 and parameters: {'subsample': 0.17443995523539252, 'dropout_rate': 0.1370357507515496, 'n_estimators': 44, 'learning_rate': 0.038020408961406814}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.18335218556611432
Fold 2 IBS: 0.2388642165361912
Fold 3 IBS: 0.16362937600606148
Fold 4 IBS: 0.23056204669676603
Fold 5 IBS: 0.22638306002215006
[I 2024-04-14 16:08:58,809] Trial 85 finished with value: 0.20855817696545662 and parameters: {'subsample': 0.6963182594533612, 'dropout_rate': 0.1793122118809201, 'n_estimators': 138, 'learning_rate': 0.040383985167900906}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.23714941752908217
Fold 2 IBS: 0.2999066033330674
Fold 3 IBS: 0.21848329289458812
Fold 4 IBS: 0.3133146376356959
Fold 5 IBS: 0.2719760715377571
[I 2024-04-14 16:09:02,451] Trial 86 finished with value: 0.2681660045860381 and parameters: {'subsample': 0.11720276470622348, 'dropout_rate': 0.21936929916464465, 'n_estimators': 413, 'learning_rate': 0.045047035385217434}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19477552440205922
Fold 2 IBS: 0.20393083445187027
Fold 3 IBS: 0.18079795447316777
Fold 4 IBS: 0.21033889048809512
Fold 5 IBS: 0.2114470131458187
[I 2024-04-14 16:09:02,733] Trial 87 finished with value: 0.20025804339220218 and parameters: {'subsample': 0.5120796183744225, 'dropout_rate': 0.14718069618548915, 'n_estimators': 59, 'learning_rate': 0.03113385911507125}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19717232160517084
Fold 2 IBS: 0.20070207442165844
Fold 3 IBS: 0.1703675223201901
Fold 4 IBS: 0.19629192990303646
Fold 5 IBS: 0.22085657947791848
[I 2024-04-14 16:09:03,332] Trial 88 finished with value: 0.19707808554559486 and parameters: {'subsample': 0.10168496533049154, 'dropout_rate': 0.15841734613370165, 'n_estimators': 100, 'learning_rate': 0.042889188264301506}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19597603961461868
Fold 2 IBS: 0.20407893772057378
Fold 3 IBS: 0.1673174279541399
Fold 4 IBS: 0.19480101916443715
Fold 5 IBS: 0.21551845830848104
[I 2024-04-14 16:09:03,703] Trial 89 finished with value: 0.1955383765524501 and parameters: {'subsample': 0.17484028701607895, 'dropout_rate': 0.2320571572911972, 'n_estimators': 82, 'learning_rate': 0.0480323670046158}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.20255078975992472
Fold 2 IBS: 0.20297220517524983
Fold 3 IBS: 0.1820836654127801
Fold 4 IBS: 0.20173571770246843
Fold 5 IBS: 0.21147765478442868
[I 2024-04-14 16:09:03,860] Trial 90 finished with value: 0.20016400656697036 and parameters: {'subsample': 0.17908239663459777, 'dropout_rate': 0.5967300530813309, 'n_estimators': 32, 'learning_rate': 0.055678558284557554}. Best is trial 74 with value: 0.1951760581180958.
Fold 1 IBS: 0.19105656971769255
Fold 2 IBS: 0.20082569362133576
Fold 3 IBS: 0.17315277517376343
Fold 4 IBS: 0.19556901689814352
Fold 5 IBS: 0.21259912474474255
[I 2024-04-14 16:09:04,108] Trial 91 finished with value: 0.19464063603113557 and parameters: {'subsample': 0.1526734943707138, 'dropout_rate': 0.23080692510197112, 'n_estimators': 57, 'learning_rate': 0.048810527071028224}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.1911672732822182
Fold 2 IBS: 0.20078883561113084
Fold 3 IBS: 0.1737813846509319
Fold 4 IBS: 0.19579100978671765
Fold 5 IBS: 0.21284049479035852
[I 2024-04-14 16:09:04,380] Trial 92 finished with value: 0.19487379962427143 and parameters: {'subsample': 0.14644797091970368, 'dropout_rate': 0.2202108008812578, 'n_estimators': 57, 'learning_rate': 0.04824822885174413}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.19440253830434298
Fold 2 IBS: 0.20411906151500223
Fold 3 IBS: 0.17541215343591768
Fold 4 IBS: 0.2018962419106499
Fold 5 IBS: 0.21283436339357234
[I 2024-04-14 16:09:04,609] Trial 93 finished with value: 0.19773287171189702 and parameters: {'subsample': 0.24612443927098196, 'dropout_rate': 0.23550391484649405, 'n_estimators': 52, 'learning_rate': 0.046657398068193426}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.2008616695309587
Fold 2 IBS: 0.23439422186024148
Fold 3 IBS: 0.16215937041051415
Fold 4 IBS: 0.21771074836028156
Fold 5 IBS: 0.22638450501297644
[I 2024-04-14 16:09:05,080] Trial 94 finished with value: 0.20830210303499447 and parameters: {'subsample': 0.20961134244109153, 'dropout_rate': 0.20967462180561508, 'n_estimators': 114, 'learning_rate': 0.05288865532892649}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.1959788020590952
Fold 2 IBS: 0.20102016727845815
Fold 3 IBS: 0.17331922313113668
Fold 4 IBS: 0.19780614256181794
Fold 5 IBS: 0.21266372918309923
[I 2024-04-14 16:09:05,332] Trial 95 finished with value: 0.19615761284272143 and parameters: {'subsample': 0.15952227833217297, 'dropout_rate': 0.1802953847482931, 'n_estimators': 61, 'learning_rate': 0.04892389255169499}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.20004868872082116
Fold 2 IBS: 0.20641773972386648
Fold 3 IBS: 0.18914623630778024

Fold 4 IBS: 0.20988660978839166
Fold 5 IBS: 0.21456843353041302
[I 2024-04-14 16:09:05,489] Trial 96 finished with value: 0.2040135416142545 and parameters: {'subsample': 0.14090987604874106, 'dropout_rate': 0.2471454520467835, 'n_estimators': 22, 'learning_rate': 0.05873889729527442}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.19110700040821932
Fold 2 IBS: 0.2020852390234278
Fold 3 IBS: 0.17881544416715775
Fold 4 IBS: 0.203756488490083
Fold 5 IBS: 0.21163899451939966
[I 2024-04-14 16:09:05,663] Trial 97 finished with value: 0.1974806333216575 and parameters: {'subsample': 0.19182777199313375, 'dropout_rate': 0.19407730384524952, 'n_estimators': 35, 'learning_rate': 0.06423903598156665}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.21294104213529513
Fold 2 IBS: 0.22063662299714767
Fold 3 IBS: 0.2036617330808848
Fold 4 IBS: 0.22387059770553963
Fold 5 IBS: 0.2177490125412687
[I 2024-04-14 16:09:05,786] Trial 98 finished with value: 0.2157718016920272 and parameters: {'subsample': 0.12667251816557912, 'dropout_rate': 0.1216381093256004, 'n_estimators': 1, 'learning_rate': 0.05427851762608612}. Best is trial 91 with value: 0.19464063603113557.
Fold 1 IBS: 0.19297382275975788
Fold 2 IBS: 0.21070115658738295
Fold 3 IBS: 0.1678195519107983
Fold 4 IBS: 0.20368470499856273
Fold 5 IBS: 0.2161126760466475
[I 2024-04-14 16:09:06,369] Trial 99 finished with value: 0.19825838246062988 and parameters: {'subsample': 0.23296037327099628, 'dropout_rate': 0.2678523465632644, 'n_estimators': 84, 'learning_rate': 0.045354931983187324}. Best is trial 91 with value: 0.19464063603113557.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.19464063603113557], datetime_start=datetime.datetime(2024, 4, 14, 16, 9, 3, 862639), datetime_complete=datetime.datetime(2024, 4, 14, 16, 9, 4, 108083), params={'subsample': 0.1526734943707138, 'dropout_rate': 0.23080692510197112, 'n_estimators': 57, 'learning_rate': 0.048810527071028224}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=91, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.1526734943707138, 'dropout_rate': 0.23080692510197112, 'n_estimators': 57, 'learning_rate': 0.048810527071028224}


* Best Score for IBS:
 0.19464063603113557

In [99]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [100]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.743
train_ibs:  0.195

#### Test

In [101]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [102]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.13272164755980653,
                                              learning_rate=0.060145822351412026,
                                              n_estimators=209,
                                              random_state=123,
                                              subsample=0.1504722419513361)

C-index score: 0.652

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.23080692510197112,
                                              learning_rate=0.048810527071028224,
                                              n_estimators=57, random_state=123,
                                              subsample=0.1526734943707138)

IBS: 0.206

In [103]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [104]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.821   1.0
ExtraSurvivalTrees               0.818   2.0
CoxLasso                         0.762   3.5
CoxElastic                       0.762   3.5
CoxPH                            0.758   5.0
GradientBoosting                 0.750   6.0
ComponentwiseGradientBoosting    0.743   7.0
CoxRidge                         0.679   8.0

In [105]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.181   1.5
ExtraSurvivalTrees             0.181   1.5
CoxPH                          0.182   4.0
CoxLasso                       0.182   4.0
CoxElastic                     0.182   4.0
ComponentwiseGradientBoosting  0.195   6.0
GradientBoosting               0.214   7.0
CoxRidge                       0.217   8.0

In [106]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.683   1.0
ComponentwiseGradientBoosting    0.652   2.0
CoxRidge                         0.647   3.0
CoxLasso                         0.623   4.5
CoxElastic                       0.623   4.5
CoxPH                            0.621   6.0
ExtraSurvivalTrees               0.607   7.0
GradientBoosting                 0.604   8.0

In [107]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.201   1.0
ComponentwiseGradientBoosting  0.206   2.0
ExtraSurvivalTrees             0.210   3.0
GradientBoosting               0.218   4.0
CoxRidge                       0.221   5.0
CoxElastic                     0.257   6.0
CoxLasso                       0.258   7.0
CoxPH                          0.261   8.0

In [108]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/standard/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

modified_file_names = ['d1_os_standard_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [109]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14