In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.preprocessing import StandardScaler
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

In [14]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [15]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [16]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [17]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

# Feature Selection: RENT

In [18]:
# Choose features from the result of RENT 
plsr = ["age",
"cavum_oris",
"hpv_related",
"uicc8_III-IV",
"oropharynx",
"pack_years",
"charlson"]

In [19]:
X_plsr = X.loc[:, plsr]
X_new = X_plsr.copy()

In [20]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, plsr]

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [23]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [24]:
X_new

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,54.238356,0,0.0,0.0,1,0.000000,0
1,54.539726,0,0.0,0.0,0,27.404795,1
2,59.019178,1,0.0,1.0,0,41.019178,1
3,70.726027,0,0.0,0.0,0,37.500000,1
4,67.865753,0,0.0,0.0,0,53.000000,1
...,...,...,...,...,...,...,...
134,60.435616,0,1.0,0.0,1,0.000000,0
135,68.794521,0,1.0,1.0,1,0.000000,0
136,57.498630,0,1.0,0.0,1,39.498630,1
137,65.684932,0,1.0,1.0,1,71.527397,1
138,61.676712,0,1.0,1.0,1,2.250000,0

In [25]:
X_new_std

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,-0.776210,0,0.0,0.0,1,-1.101176,0
1,-0.737256,0,0.0,0.0,0,0.105775,1
2,-0.158251,1,0.0,1.0,0,0.705374,1
3,1.354953,0,0.0,0.0,0,0.550384,1
4,0.985240,0,0.0,0.0,0,1.233028,1
...,...,...,...,...,...,...,...
134,0.024835,0,1.0,0.0,1,-1.101176,0
135,1.105290,0,1.0,1.0,1,-1.101176,0
136,-0.354794,0,1.0,0.0,1,0.638406,1
137,0.703351,0,1.0,1.0,1,2.049005,1
138,0.185257,0,1.0,1.0,1,-1.002083,0

In [26]:
MAASTRO_new

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,55,0,1,0,1,0,1
1,55,0,0,1,1,20,0
2,55,0,0,1,1,6,1
3,61,0,0,1,0,45,1
4,70,0,1,0,1,59,1
...,...,...,...,...,...,...,...
94,66,0,0,1,0,55,0
95,63,0,0,1,0,174,1
96,63,0,1,1,1,0,1
97,54,0,1,0,1,0,0
98,62,0,0,1,0,40,0

In [27]:
MAASTRO_new_std

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,-0.677762,0,1,0,1,-1.101176,1
1,-0.677762,0,0,1,1,-0.220344,0
2,-0.677762,0,0,1,1,-0.836927,1
3,0.097786,0,0,1,0,0.880696,1
4,1.261108,0,1,0,1,1.497278,1
...,...,...,...,...,...,...,...
94,0.744076,0,0,1,0,1.321112,0
95,0.356302,0,0,1,0,6.562062,1
96,0.356302,0,1,1,1,-1.101176,1
97,-0.807020,0,1,0,1,-1.101176,0
98,0.227044,0,0,1,0,0.660488,0

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [28]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:51:39,956] A new study created in memory with name: no-name-cbf25c65-c74d-4c3a-94b5-bfe740f9c4f1

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844

[I 2024-04-13 23:52:00,263] A new study created in memory with name: no-name-b1ec1ca6-bcec-4d08-bc7a-ff1d2bf91059

Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:52:00,250] Trial 0 finished with value: 0.760896852663171 and parameters: {}. Best is trial 0 with value: 0.760896852663171.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.760896852663171], datetime_start=datetime.datetime(2024, 4, 13, 23, 51, 40, 582110), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 0, 249534), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.760896852663171

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16131595626689033
Fold 2 IBS: 0.17652730860451066
Fold 3 IBS: 0.15314029222827888
Fold 4 IBS: 0.14780969255866613
Fold 5 IBS: 0.25578610957274617
[I 2024-04-13 23:52:01,552] Trial 0 finished with value: 0.17891587184621843 and parameters: {}. Best is trial 0 with value: 0.17891587184621843.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17891587184621843], datetime_start=datetime.datetime(2024, 4, 13, 23, 52, 0, 331420), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 1, 552282), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17891587184621843

In [29]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [30]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.761
train_ibs:  0.179

#### Test

In [31]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [32]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.568
IBS score: 0.279

In [33]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:52:02,152] A new study created in memory with name: no-name-380428d4-a552-4c41-bc80-4fb3069b47ef

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7720588235294118

[I 2024-04-13 23:52:02,726] A new study created in memory with name: no-name-5b59c2a6-76e6-4a55-84ff-31c4520fb118

Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.5633802816901409
[I 2024-04-13 23:52:02,718] Trial 0 finished with value: 0.691456622074104 and parameters: {}. Best is trial 0 with value: 0.691456622074104.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.691456622074104], datetime_start=datetime.datetime(2024, 4, 13, 23, 52, 2, 190450), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 2, 718249), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.691456622074104

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2139765166947049
Fold 2 IBS: 0.2215779101687221
Fold 3 IBS: 0.20453594089893293
Fold 4 IBS: 0.2247380328252742
Fold 5 IBS: 0.21812431423859643
[I 2024-04-13 23:52:03,847] Trial 0 finished with value: 0.2165905429652461 and parameters: {}. Best is trial 0 with value: 0.2165905429652461.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2165905429652461], datetime_start=datetime.datetime(2024, 4, 13, 23, 52, 2, 951086), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 3, 834196), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2165905429652461

In [36]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.691
train_ibs:  0.217

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:52:04,501] A new study created in memory with name: no-name-62052bd2-b1b1-4d4c-bf02-586dd4bb0818

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844

[I 2024-04-13 23:52:06,089] A new study created in memory with name: no-name-fd9f1e48-d7ee-4a16-ab41-2ed2a9489ebb

Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:06,077] Trial 0 finished with value: 0.7582867625323683 and parameters: {}. Best is trial 0 with value: 0.7582867625323683.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7582867625323683], datetime_start=datetime.datetime(2024, 4, 13, 23, 52, 4, 742774), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 6, 77116), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7582867625323683

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16153564154189293
Fold 2 IBS: 0.1842400309665049
Fold 3 IBS: 0.15275060525197218
Fold 4 IBS: 0.14653906831683322
Fold 5 IBS: 0.25395902869786563
[I 2024-04-13 23:52:07,820] Trial 0 finished with value: 0.17980487495501377 and parameters: {}. Best is trial 0 with value: 0.17980487495501377.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17980487495501377], datetime_start=datetime.datetime(2024, 4, 13, 23, 52, 6, 130136), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 7, 819606), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17980487495501377

In [42]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.18

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.571

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.275

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:52:08,865] A new study created in memory with name: no-name-148bd728-9baa-4f07-9741-da6a533446e8

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:10,629] Trial 0 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7582867625323683.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:12,586] Trial 1 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7582867625323683.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:14,511] Trial 2 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7582867625323683.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:15,704] Trial 3 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7582867625323683.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:17,138] Trial 4 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7582867625323683.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:18,902] Trial 5 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:20,140] Trial 6 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:21,894] Trial 7 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:23,341] Trial 8 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:25,068] Trial 9 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:27,059] Trial 10 finished with value: 0.7590920846612198 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:29,311] Trial 11 finished with value: 0.7410198615257056 and parameters: {'l1_ratio': 0.02533011697459009}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:31,076] Trial 12 finished with value: 0.7540287935219794 and parameters: {'l1_ratio': 0.04108903480556085}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:32,587] Trial 13 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.20377078100488127}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:34,124] Trial 14 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.1533169040563137}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:35,732] Trial 15 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.3708144157838703}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:37,267] Trial 16 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.9148898424009407}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:38,947] Trial 17 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.5048186339682378}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:40,451] Trial 18 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.5719400059215255}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:42,230] Trial 19 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.41209299729581184}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:43,549] Trial 20 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.7849253733721261}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:45,749] Trial 21 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.12633384089363162}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:48,531] Trial 22 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.3332344802741024}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:50,282] Trial 23 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.47914227797666115}. Best is trial 5 with value: 0.7591796196752254.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:51,871] Trial 24 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5910098988284204}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:53,639] Trial 25 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.29037524082647914}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:55,036] Trial 26 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.8401513352750697}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:56,453] Trial 27 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.6394538628912858}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:52:58,450] Trial 28 finished with value: 0.7590920846612198 and parameters: {'l1_ratio': 0.11358376306470029}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:00,626] Trial 29 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.45362990984659757}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:02,309] Trial 30 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.48644390666328385}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:04,098] Trial 31 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.42140606590902197}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:05,517] Trial 32 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.4311739148200147}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:07,511] Trial 33 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.3410387833740555}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:08,937] Trial 34 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.5253138801825318}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:10,154] Trial 35 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.43293287308347067}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:11,284] Trial 36 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.6173313460444607}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:12,563] Trial 37 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.22586745028563213}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:13,834] Trial 38 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.2997716476337262}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:15,044] Trial 39 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5540106638045234}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:16,422] Trial 40 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.7248416102727671}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:18,196] Trial 41 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.46895625138138225}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:19,588] Trial 42 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.4730624242917584}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:21,181] Trial 43 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.5236359679208719}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:23,342] Trial 44 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.44355023802065024}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:25,933] Trial 45 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.3722250331856307}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:27,584] Trial 46 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.6396695497207879}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844

Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:29,882] Trial 47 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.2634506000463872}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:31,464] Trial 48 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.5252656327220788}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:33,087] Trial 49 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.37543149390939745}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:34,557] Trial 50 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.3347529254862469}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:36,172] Trial 51 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.19992792652052588}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5915492957746479
[I 2024-04-13 23:53:36,605] Trial 52 finished with value: 0.6974950804241047 and parameters: {'l1_ratio': 0.009220434487373919}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:38,243] Trial 53 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.40483468365639486}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:40,169] Trial 54 finished with value: 0.7590920846612198 and parameters: {'l1_ratio': 0.05975289530248976}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:42,305] Trial 55 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.6751302644579473}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:45,362] Trial 56 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.46117231494938454}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:48,298] Trial 57 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.45720307302721197}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:50,366] Trial 58 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.5205486394804426}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:53,222] Trial 59 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5773341202794735}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:58,061] Trial 60 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.504900719695715}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:53:59,881] Trial 61 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.46410723554248157}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:01,526] Trial 62 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.40471518954279423}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:03,159] Trial 63 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.455324867103456}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:04,647] Trial 64 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.34586389297278936}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:06,586] Trial 65 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.4317125304449709}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:09,813] Trial 66 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5564844160260787}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:12,308] Trial 67 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.4877611698811145}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:14,584] Trial 68 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.6080205552120618}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:17,015] Trial 69 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.3894735544548289}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:20,951] Trial 70 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.4235067772176486}. Best is trial 5 with value: 0.7591796196752254.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:26,200] Trial 71 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.5017255780846035}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:29,231] Trial 72 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.5003057180585615}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:31,726] Trial 73 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.4594903929519768}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:34,018] Trial 74 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5485368708364513}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:38,122] Trial 75 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.3195930245803076}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:39,660] Trial 76 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.5032753473841217}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:41,842] Trial 77 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.3752709123430163}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:43,972] Trial 78 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5404983319875152}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:46,317] Trial 79 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5933865341035967}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:49,436] Trial 80 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.4417486985671995}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:53,244] Trial 81 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.4605578548673088}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:55,504] Trial 82 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.4729240094084271}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:57,423] Trial 83 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.41191339523127657}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:54:59,192] Trial 84 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.360792961449222}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:01,402] Trial 85 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.5086784530021397}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:04,173] Trial 86 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.46030328919932256}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:06,246] Trial 87 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.39203015495247795}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:08,401] Trial 88 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.26784264790917417}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:11,209] Trial 89 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.5734179456707129}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:13,454] Trial 90 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.48085403544182426}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:15,646] Trial 91 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.44876130957888927}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:17,660] Trial 92 finished with value: 0.7591796196752254 and parameters: {'l1_ratio': 0.42467083307110043}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:19,794] Trial 93 finished with value: 0.7573063703755055 and parameters: {'l1_ratio': 0.4807417473150888}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:21,103] Trial 94 finished with value: 0.7582867625323683 and parameters: {'l1_ratio': 0.5465776099831516}. Best is trial 5 with value: 0.7591796196752254.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:22,844] Trial 95 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.5266710888604075}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:24,623] Trial 96 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.39140498225474013}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:27,092] Trial 97 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.44646210292902566}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:30,443] Trial 98 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.4060208774799013}. Best is trial 5 with value: 0.7591796196752254.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844

[I 2024-04-13 23:55:34,278] A new study created in memory with name: no-name-4896df93-4048-4731-a801-575800827195

Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:55:34,196] Trial 99 finished with value: 0.7581992275183627 and parameters: {'l1_ratio': 0.31390035969929253}. Best is trial 5 with value: 0.7591796196752254.


* Best trial for C-index:
 FrozenTrial(number=5, state=TrialState.COMPLETE, values=[0.7591796196752254], datetime_start=datetime.datetime(2024, 4, 13, 23, 52, 17, 170512), datetime_complete=datetime.datetime(2024, 4, 13, 23, 52, 18, 901550), params={'l1_ratio': 0.4231641494784485}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=5, value=None)


* Best Score for C-index:
 0.7591796196752254

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16147755914048548
Fold 2 IBS: 0.18363855053607006
Fold 3 IBS: 0.1526190676839271
Fold 4 IBS: 0.14653952970577372
Fold 5 IBS: 0.2539331115447447
[I 2024-04-13 23:55:36,595] Trial 0 finished with value: 0.17964156372220025 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.17964156372220025.
Fold 1 IBS: 0.16137427153465642
Fold 2 IBS: 0.18267947672298618
Fold 3 IBS: 0.1524682185261851
Fold 4 IBS: 0.1464604748170855
Fold 5 IBS: 0.25375770370810097
[I 2024-04-13 23:55:40,244] Trial 1 finished with value: 0.1793480290618028 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.1793480290618028.
Fold 1 IBS: 0.16135847880812645
Fold 2 IBS: 0.1825925025988472
Fold 3 IBS: 0.15241456985698845
Fold 4 IBS: 0.14651501820866328
Fold 5 IBS: 0.2536446994907515
[I 2024-04-13 23:55:42,344] Trial 2 finished with value: 0.1793050537926754 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.16144293647957259
Fold 2 IBS: 0.18332253236704663
Fold 3 IBS: 0.15257845151714758
Fold 4 IBS: 0.14647578785616247
Fold 5 IBS: 0.2537637551301116
[I 2024-04-13 23:55:44,324] Trial 3 finished with value: 0.17951669267000817 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.16147768482058028
Fold 2 IBS: 0.18368561189141644
Fold 3 IBS: 0.15264359500307906
Fold 4 IBS: 0.14657884813886252
Fold 5 IBS: 0.25384795293285284
[I 2024-04-13 23:55:45,759] Trial 4 finished with value: 0.17964673855735822 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.16141491847861852
Fold 2 IBS: 0.18305718607927104
Fold 3 IBS: 0.15253286969326985
Fold 4 IBS: 0.14648877588576809
Fold 5 IBS: 0.25370658711114863
[I 2024-04-13 23:55:47,257] Trial 5 finished with value: 0.17944006744961521 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.16153554689586483
Fold 2 IBS: 0.18416248452522904
Fold 3 IBS: 0.15273480265124145
Fold 4 IBS: 0.14651432662765812
Fold 5 IBS: 0.25406354608309356
[I 2024-04-13 23:55:49,686] Trial 6 finished with value: 0.1798021413566174 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.16147748915024596
Fold 2 IBS: 0.1836136619650858
Fold 3 IBS: 0.15260614443804643
Fold 4 IBS: 0.14651872264082505
Fold 5 IBS: 0.2538951977717841
[I 2024-04-13 23:55:52,184] Trial 7 finished with value: 0.17962224319319745 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.16142824353290378
Fold 2 IBS: 0.18315215679781924
Fold 3 IBS: 0.15252646381917617
Fold 4 IBS: 0.14653319169680223
Fold 5 IBS: 0.2538090225754026
[I 2024-04-13 23:55:55,270] Trial 8 finished with value: 0.17948981568442082 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.1614034985930001
Fold 2 IBS: 0.18294478844054726
Fold 3 IBS: 0.1524783677489443
Fold 4 IBS: 0.14650816850244572
Fold 5 IBS: 0.25372055761314705
[I 2024-04-13 23:55:57,657] Trial 9 finished with value: 0.17941107617961688 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.1793050537926754.
Fold 1 IBS: 0.1613144909470763
Fold 2 IBS: 0.1797696036672151
Fold 3 IBS: 0.15237259311746537
Fold 4 IBS: 0.14643214182058945
Fold 5 IBS: 0.25361186740555114
[I 2024-04-13 23:56:01,830] Trial 10 finished with value: 0.17870013939157947 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.17870013939157947.
Fold 1 IBS: 0.21335381298037723
Fold 2 IBS: 0.2207435591327523
Fold 3 IBS: 0.20377585073298699
Fold 4 IBS: 0.22372715642199623
Fold 5 IBS: 0.21800593833236348
[I 2024-04-13 23:56:02,535] Trial 11 finished with value: 0.21592126352009525 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.17870013939157947.
Fold 1 IBS: 0.16131446577353464
Fold 2 IBS: 0.17977200904596993
Fold 3 IBS: 0.15237188574870877
Fold 4 IBS: 0.1464308497600429
Fold 5 IBS: 0.25360974878539755
[I 2024-04-13 23:56:06,777] Trial 12 finished with value: 0.17869979182273077 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.21380985730907298
Fold 2 IBS: 0.2213551237473767
Fold 3 IBS: 0.2043324128471473
Fold 4 IBS: 0.22446649482441097
Fold 5 IBS: 0.21809221284552432
[I 2024-04-13 23:56:08,018] Trial 13 finished with value: 0.21641122031470644 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16133295547998805
Fold 2 IBS: 0.18209293554134207
Fold 3 IBS: 0.15238415801514127
Fold 4 IBS: 0.146408788459275
Fold 5 IBS: 0.2536100230591831
[I 2024-04-13 23:56:10,580] Trial 14 finished with value: 0.1791657721109859 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16133325625689887
Fold 2 IBS: 0.18233463652876408
Fold 3 IBS: 0.15239340193335674
Fold 4 IBS: 0.14642561263779172
Fold 5 IBS: 0.2536268692797441
[I 2024-04-13 23:56:12,863] Trial 15 finished with value: 0.1792227553273111 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16132968975226777
Fold 2 IBS: 0.18226670815042478
Fold 3 IBS: 0.15239877154276704
Fold 4 IBS: 0.1464446040801373
Fold 5 IBS: 0.25365142055060974
[I 2024-04-13 23:56:15,350] Trial 16 finished with value: 0.17921823881524132 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.1613755665869265
Fold 2 IBS: 0.18270270251738083
Fold 3 IBS: 0.1524787191086481
Fold 4 IBS: 0.1464793040624763
Fold 5 IBS: 0.25378882251083984
[I 2024-04-13 23:56:17,766] Trial 17 finished with value: 0.17936502295725432 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.1613092183889593
Fold 2 IBS: 0.1797692870101791
Fold 3 IBS: 0.15239427756493276
Fold 4 IBS: 0.1464954807076844
Fold 5 IBS: 0.25370611165266777
[I 2024-04-13 23:56:20,225] Trial 18 finished with value: 0.17873487506488467 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16153563001020696
Fold 2 IBS: 0.18422983032674514
Fold 3 IBS: 0.1527448576184957
Fold 4 IBS: 0.14653007801305856
Fold 5 IBS: 0.2540925157746418
[I 2024-04-13 23:56:23,166] Trial 19 finished with value: 0.17982658234862964 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16136049653290127
Fold 2 IBS: 0.18257802941979284
Fold 3 IBS: 0.15245175114927753
Fold 4 IBS: 0.14646524866370386
Fold 5 IBS: 0.2537404803220301
[I 2024-04-13 23:56:27,207] Trial 20 finished with value: 0.17931920121754114 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16131482301538705
Fold 2 IBS: 0.17973776098325614
Fold 3 IBS: 0.15238196154897862
Fold 4 IBS: 0.14644923683808966
Fold 5 IBS: 0.25363989156129135
[I 2024-04-13 23:56:29,945] Trial 21 finished with value: 0.17870473478940055 and parameters: {'l1_ratio': 0.08499433228302328}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16131979627385182
Fold 2 IBS: 0.1798688278080688
Fold 3 IBS: 0.15238380728282597
Fold 4 IBS: 0.14644043952794136
Fold 5 IBS: 0.25362777884240556
[I 2024-04-13 23:56:32,929] Trial 22 finished with value: 0.1787281299470187 and parameters: {'l1_ratio': 0.10159828709381563}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16134886183627345
Fold 2 IBS: 0.18253317318446685
Fold 3 IBS: 0.15244913004724533
Fold 4 IBS: 0.14650103881187335
Fold 5 IBS: 0.2536094565122955
[I 2024-04-13 23:56:35,839] Trial 23 finished with value: 0.17928833207843092 and parameters: {'l1_ratio': 0.20450032756347597}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.1613851204876769
Fold 2 IBS: 0.18285665539228066
Fold 3 IBS: 0.1524784941425968
Fold 4 IBS: 0.14644121840495458
Fold 5 IBS: 0.25376507206449656
[I 2024-04-13 23:56:38,600] Trial 24 finished with value: 0.17938531209840108 and parameters: {'l1_ratio': 0.3389201479305571}. Best is trial 12 with value: 0.17869979182273077.

Fold 1 IBS: 0.16130347009927784
Fold 2 IBS: 0.17972938075739273
Fold 3 IBS: 0.15235581923762645
Fold 4 IBS: 0.22171990965951452
Fold 5 IBS: 0.25358621012215415
[I 2024-04-13 23:56:40,466] Trial 25 finished with value: 0.19373895797519314 and parameters: {'l1_ratio': 0.03981317955666948}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16134724753152271
Fold 2 IBS: 0.18250566604419238
Fold 3 IBS: 0.15239625807347582
Fold 4 IBS: 0.14651111937282857
Fold 5 IBS: 0.25361588939788765
[I 2024-04-13 23:56:42,833] Trial 26 finished with value: 0.1792752360839814 and parameters: {'l1_ratio': 0.18783928730207888}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.1614445278333994
Fold 2 IBS: 0.18340671073131992
Fold 3 IBS: 0.15257506097361084
Fold 4 IBS: 0.14654715180507763
Fold 5 IBS: 0.2538816754008691
[I 2024-04-13 23:56:45,256] Trial 27 finished with value: 0.17957102534885538 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16131680845088073
Fold 2 IBS: 0.17983711059120483
Fold 3 IBS: 0.15237196600197012
Fold 4 IBS: 0.14642519902103243
Fold 5 IBS: 0.25360468151057713
[I 2024-04-13 23:56:47,750] Trial 28 finished with value: 0.17871115311513305 and parameters: {'l1_ratio': 0.09146853847676947}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16151879206685182
Fold 2 IBS: 0.18401681156372754
Fold 3 IBS: 0.15271540158331698
Fold 4 IBS: 0.14660752229317073
Fold 5 IBS: 0.25397920996470535
[I 2024-04-13 23:56:49,882] Trial 29 finished with value: 0.17976754749435447 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16138329240905688
Fold 2 IBS: 0.1827792530462566
Fold 3 IBS: 0.1524961555694228
Fold 4 IBS: 0.14649099143504224
Fold 5 IBS: 0.2536538588050363
[I 2024-04-13 23:56:51,759] Trial 30 finished with value: 0.179360710252963 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16131600676466326
Fold 2 IBS: 0.17990938667966028
Fold 3 IBS: 0.15240485337758017
Fold 4 IBS: 0.1465001719645973
Fold 5 IBS: 0.2535408164364023
[I 2024-04-13 23:56:54,110] Trial 31 finished with value: 0.17873424704458066 and parameters: {'l1_ratio': 0.08869665043784933}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16131046205273722
Fold 2 IBS: 0.1798832636777538
Fold 3 IBS: 0.15238322269751464
Fold 4 IBS: 0.14646163268637996
Fold 5 IBS: 0.25365287297357236
[I 2024-04-13 23:56:56,386] Trial 32 finished with value: 0.17873829081759157 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16134326234472174
Fold 2 IBS: 0.1824578678304968
Fold 3 IBS: 0.1524310226735524
Fold 4 IBS: 0.1464725068135034
Fold 5 IBS: 0.25371972606889986
[I 2024-04-13 23:56:58,145] Trial 33 finished with value: 0.17928487714623484 and parameters: {'l1_ratio': 0.18182479242429683}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.1613588826892726
Fold 2 IBS: 0.18252990159587
Fold 3 IBS: 0.15242857700178808
Fold 4 IBS: 0.1464259508722304
Fold 5 IBS: 0.2536758550440974
[I 2024-04-13 23:57:00,137] Trial 34 finished with value: 0.17928383344065169 and parameters: {'l1_ratio': 0.23148463885526435}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.2139056783547871
Fold 2 IBS: 0.22148328628276842
Fold 3 IBS: 0.2044494192698514
Fold 4 IBS: 0.22462255798422465
Fold 5 IBS: 0.21811063098612976
[I 2024-04-13 23:57:00,883] Trial 35 finished with value: 0.21651431457555229 and parameters: {'l1_ratio': 0.0013526982279536137}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16136807100204126
Fold 2 IBS: 0.18267251279023958
Fold 3 IBS: 0.1524756491525209
Fold 4 IBS: 0.14650054110607272
Fold 5 IBS: 0.25364340735116736
[I 2024-04-13 23:57:02,638] Trial 36 finished with value: 0.17933203628040836 and parameters: {'l1_ratio': 0.26966204197246835}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16132247886184686
Fold 2 IBS: 0.17996292071099373
Fold 3 IBS: 0.15237938254839756
Fold 4 IBS: 0.14642538993497237
Fold 5 IBS: 0.25360808570691123
[I 2024-04-13 23:57:05,232] Trial 37 finished with value: 0.17873965155262436 and parameters: {'l1_ratio': 0.11013390149046806}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16139472486116924
Fold 2 IBS: 0.1829401374166086
Fold 3 IBS: 0.15249859357886894
Fold 4 IBS: 0.14645365929221862
Fold 5 IBS: 0.2538031764699075
[I 2024-04-13 23:57:06,966] Trial 38 finished with value: 0.17941805832375463 and parameters: {'l1_ratio': 0.3752900822742875}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16133694548623936
Fold 2 IBS: 0.1822867888118801
Fold 3 IBS: 0.1524302497553269
Fold 4 IBS: 0.1465016462516396
Fold 5 IBS: 0.253582299816225
[I 2024-04-13 23:57:08,975] Trial 39 finished with value: 0.1792275860242622 and parameters: {'l1_ratio': 0.15486970537243167}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.1614171688060561
Fold 2 IBS: 0.1831504283088384
Fold 3 IBS: 0.15255314920273433
Fold 4 IBS: 0.14649634224271862
Fold 5 IBS: 0.2537429547279752
[I 2024-04-13 23:57:10,547] Trial 40 finished with value: 0.17947200865766452 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 12 with value: 0.17869979182273077.
Fold 1 IBS: 0.16131161902933508
Fold 2 IBS: 0.17978044964235615
Fold 3 IBS: 0.15235195197709067
Fold 4 IBS: 0.14639964487767515
Fold 5 IBS: 0.2535547479166215
[I 2024-04-13 23:57:12,370] Trial 41 finished with value: 0.17867968268861573 and parameters: {'l1_ratio': 0.07444346186601063}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16130526375716214
Fold 2 IBS: 0.1797247363814267
Fold 3 IBS: 0.15238753278640166
Fold 4 IBS: 0.14647852350594906
Fold 5 IBS: 0.2536728268095157
[I 2024-04-13 23:57:14,815] Trial 42 finished with value: 0.17871377664809107 and parameters: {'l1_ratio': 0.05476041509421162}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.1613193665618389
Fold 2 IBS: 0.17991079443495034
Fold 3 IBS: 0.15237142886425792
Fold 4 IBS: 0.14641785544160202
Fold 5 IBS: 0.2535972434132888
[I 2024-04-13 23:57:17,355] Trial 43 finished with value: 0.1787233377431876 and parameters: {'l1_ratio': 0.09977551653118547}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16130244756563866
Fold 2 IBS: 0.17958368745139983
Fold 3 IBS: 0.15238555542918264
Fold 4 IBS: 0.22181880555812558
Fold 5 IBS: 0.25369405492094305
[I 2024-04-13 23:57:20,053] Trial 44 finished with value: 0.19375691018505795 and parameters: {'l1_ratio': 0.03834194526153677}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16134314009831754
Fold 2 IBS: 0.182448961419338
Fold 3 IBS: 0.15242696760983712
Fold 4 IBS: 0.14646518552426743
Fold 5 IBS: 0.2537076587242614
[I 2024-04-13 23:57:21,890] Trial 45 finished with value: 0.1792783826752043 and parameters: {'l1_ratio': 0.18074152502476082}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16149706069240763
Fold 2 IBS: 0.1837838998118202
Fold 3 IBS: 0.15264997203317493
Fold 4 IBS: 0.14654385564075315
Fold 5 IBS: 0.2539788861787873
[I 2024-04-13 23:57:24,086] Trial 46 finished with value: 0.17969073487138865 and parameters: {'l1_ratio': 0.7654012893264529}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16136811349596172
Fold 2 IBS: 0.18267620068591572
Fold 3 IBS: 0.15242847412273755
Fold 4 IBS: 0.14650353955401038
Fold 5 IBS: 0.253648732721623
[I 2024-04-13 23:57:26,325] Trial 47 finished with value: 0.17932501211604968 and parameters: {'l1_ratio': 0.27033217398012416}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16144319776051533
Fold 2 IBS: 0.18336730401910126
Fold 3 IBS: 0.15255452666996977
Fold 4 IBS: 0.1465137454741878
Fold 5 IBS: 0.2538212352820774
[I 2024-04-13 23:57:28,164] Trial 48 finished with value: 0.1795400018411703 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16132647856534948
Fold 2 IBS: 0.18210364195748494
Fold 3 IBS: 0.1524055407113539
Fold 4 IBS: 0.14646530612280537

Fold 5 IBS: 0.2536793531656018
[I 2024-04-13 23:57:30,932] Trial 49 finished with value: 0.1791960641045191 and parameters: {'l1_ratio': 0.12479818361037143}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.2126538011301309
Fold 2 IBS: 0.1796705082688478
Fold 3 IBS: 0.15234301113818527
Fold 4 IBS: 0.2226021280057045
Fold 5 IBS: 0.25355575417313825
[I 2024-04-13 23:57:33,768] Trial 50 finished with value: 0.2041650405432013 and parameters: {'l1_ratio': 0.02712774397400479}. Best is trial 41 with value: 0.17867968268861573.
Fold 1 IBS: 0.16130446979847196
Fold 2 IBS: 0.17962788080780573
Fold 3 IBS: 0.15234271611359756
Fold 4 IBS: 0.14639704505503323
Fold 5 IBS: 0.2535383625662432
[I 2024-04-13 23:57:37,281] Trial 51 finished with value: 0.17864209486823032 and parameters: {'l1_ratio': 0.05123710958654414}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16130838901537564
Fold 2 IBS: 0.17984096898703097
Fold 3 IBS: 0.15238003779253095
Fold 4 IBS: 0.14646021183483973
Fold 5 IBS: 0.25364736596027593
[I 2024-04-13 23:57:39,773] Trial 52 finished with value: 0.17872739471801063 and parameters: {'l1_ratio': 0.06491358733526804}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613332412310255
Fold 2 IBS: 0.18233361619875704
Fold 3 IBS: 0.15239293836489426
Fold 4 IBS: 0.14642476966617934
Fold 5 IBS: 0.25362572599184396
[I 2024-04-13 23:57:42,129] Trial 53 finished with value: 0.17922205829054003 and parameters: {'l1_ratio': 0.14537616011205629}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131610882777508
Fold 2 IBS: 0.17989970185932405
Fold 3 IBS: 0.15240754631364947
Fold 4 IBS: 0.14650502399959245
Fold 5 IBS: 0.2535493806900916
[I 2024-04-13 23:57:44,585] Trial 54 finished with value: 0.17873555233808652 and parameters: {'l1_ratio': 0.08905974936432337}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.21368777002689973
Fold 2 IBS: 0.22119178626946503
Fold 3 IBS: 0.20418333882288672
Fold 4 IBS: 0.22426814352499047
Fold 5 IBS: 0.2180688749798939
[I 2024-04-13 23:57:45,465] Trial 55 finished with value: 0.21627998272482718 and parameters: {'l1_ratio': 0.00558088369611881}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16133694248758043
Fold 2 IBS: 0.1822871009196629
Fold 3 IBS: 0.15243016187496491
Fold 4 IBS: 0.14650148870700538
Fold 5 IBS: 0.2535820211831183
[I 2024-04-13 23:57:47,519] Trial 56 finished with value: 0.1792275430344664 and parameters: {'l1_ratio': 0.1548493027013797}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16135419542166246
Fold 2 IBS: 0.18253972594040968
Fold 3 IBS: 0.15244587452126096
Fold 4 IBS: 0.1464718550324373
Fold 5 IBS: 0.2537405110832197
[I 2024-04-13 23:57:49,954] Trial 57 finished with value: 0.17931043239979802 and parameters: {'l1_ratio': 0.21897099299730738}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16145904803243602
Fold 2 IBS: 0.18350492050040185
Fold 3 IBS: 0.1525898177795648
Fold 4 IBS: 0.14653353691740642
Fold 5 IBS: 0.25388804006990595
[I 2024-04-13 23:57:51,772] Trial 58 finished with value: 0.179595072659943 and parameters: {'l1_ratio': 0.6328007058348859}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613266059562914
Fold 2 IBS: 0.18208973425667183
Fold 3 IBS: 0.15240939791027264
Fold 4 IBS: 0.1464723014387046
Fold 5 IBS: 0.2536908596554195
[I 2024-04-13 23:57:54,736] Trial 59 finished with value: 0.179197779843472 and parameters: {'l1_ratio': 0.125516498255384}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613069638212892
Fold 2 IBS: 0.17983112191061285
Fold 3 IBS: 0.1523705959640743
Fold 4 IBS: 0.14644456487400104
Fold 5 IBS: 0.2536188512014215
[I 2024-04-13 23:57:58,637] Trial 60 finished with value: 0.1787144195542798 and parameters: {'l1_ratio': 0.058405744698602644}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16130259267940047
Fold 2 IBS: 0.17974805189920814
Fold 3 IBS: 0.15235990430206214
Fold 4 IBS: 0.22145247115104164
Fold 5 IBS: 0.2535959485319739
[I 2024-04-13 23:58:01,119] Trial 61 finished with value: 0.1936917937127373 and parameters: {'l1_ratio': 0.04385755932932674}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131045148042236
Fold 2 IBS: 0.17988422995917608
Fold 3 IBS: 0.15238295669255508
Fold 4 IBS: 0.14646114782402944
Fold 5 IBS: 0.2536520789531661
[I 2024-04-13 23:58:04,333] Trial 62 finished with value: 0.1787381729818698 and parameters: {'l1_ratio': 0.07128393652780252}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613416811462742
Fold 2 IBS: 0.18244383434186703
Fold 3 IBS: 0.15243336425952939
Fold 4 IBS: 0.14649781746637147
Fold 5 IBS: 0.25358227990759014
[I 2024-04-13 23:58:07,890] Trial 63 finished with value: 0.17925979542432646 and parameters: {'l1_ratio': 0.16925445436766373}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613231210630415
Fold 2 IBS: 0.17989896584323517
Fold 3 IBS: 0.15239827640467685
Fold 4 IBS: 0.1464597830887328
Fold 5 IBS: 0.25366467704473367
[I 2024-04-13 23:58:10,834] Trial 64 finished with value: 0.17874896468888402 and parameters: {'l1_ratio': 0.11323622531631855}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16130026077155055
Fold 2 IBS: 0.17965284102344192
Fold 3 IBS: 0.15236105183798815
Fold 4 IBS: 0.2221541142786915
Fold 5 IBS: 0.25360632285756846
[I 2024-04-13 23:58:13,925] Trial 65 finished with value: 0.19381491815384813 and parameters: {'l1_ratio': 0.03344817134050178}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.21395607132182168
Fold 2 IBS: 0.22155061064399117
Fold 3 IBS: 0.2045109672608659
Fold 4 IBS: 0.22470469569999385
Fold 5 IBS: 0.21812035918777284
[I 2024-04-13 23:58:15,204] Trial 66 finished with value: 0.2165685408228891 and parameters: {'l1_ratio': 0.0003894512800389077}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16134830279547172
Fold 2 IBS: 0.18249067278204795
Fold 3 IBS: 0.15243529406626954
Fold 4 IBS: 0.14646618450974858
Fold 5 IBS: 0.253721289946737
[I 2024-04-13 23:58:18,458] Trial 67 finished with value: 0.17929234882005493 and parameters: {'l1_ratio': 0.19871531749958796}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613156376928285
Fold 2 IBS: 0.17994424028945818
Fold 3 IBS: 0.15240070281854043
Fold 4 IBS: 0.14648269451747456
Fold 5 IBS: 0.25369574801149164
[I 2024-04-13 23:58:21,276] Trial 68 finished with value: 0.17876780466595865 and parameters: {'l1_ratio': 0.0874104501434462}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16130421123757724
Fold 2 IBS: 0.17965127374147621
Fold 3 IBS: 0.15239098436791446
Fold 4 IBS: 0.14649824672026507
Fold 5 IBS: 0.25370053136391524
[I 2024-04-13 23:58:25,057] Trial 69 finished with value: 0.17870904948622962 and parameters: {'l1_ratio': 0.05073367450372726}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16136103092681747
Fold 2 IBS: 0.1826218854409916
Fold 3 IBS: 0.15246689622087892
Fold 4 IBS: 0.1465010163427136
Fold 5 IBS: 0.2536315095171294
[I 2024-04-13 23:58:27,293] Trial 70 finished with value: 0.17931646768970622 and parameters: {'l1_ratio': 0.24598960943285658}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613025049703597
Fold 2 IBS: 0.1796482440160159
Fold 3 IBS: 0.15238162855619738
Fold 4 IBS: 0.22133303252726955
Fold 5 IBS: 0.25367767750131603
[I 2024-04-13 23:58:29,608] Trial 71 finished with value: 0.1936686175142317 and parameters: {'l1_ratio': 0.045695583994929255}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16132623186177772
Fold 2 IBS: 0.18213047324975268
Fold 3 IBS: 0.1523981037648432
Fold 4 IBS: 0.14645180370848665
Fold 5 IBS: 0.25365713599438555
[I 2024-04-13 23:58:32,279] Trial 72 finished with value: 0.17919274971584914 and parameters: {'l1_ratio': 0.12343225894268404}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131208687353013
Fold 2 IBS: 0.17973651024413706
Fold 3 IBS: 0.15236484323968957
Fold 4 IBS: 0.1464232581148026
Fold 5 IBS: 0.25359347762772816
[I 2024-04-13 23:58:34,826] Trial 73 finished with value: 0.1786860352199775 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 51 with value: 0.17864209486823032.

Fold 1 IBS: 0.16131958581546293
Fold 2 IBS: 0.1798894318751477
Fold 3 IBS: 0.15237772825717347
Fold 4 IBS: 0.14642935548026983
Fold 5 IBS: 0.2536095439398616
[I 2024-04-13 23:58:38,407] Trial 74 finished with value: 0.1787251290735831 and parameters: {'l1_ratio': 0.10069635105041849}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131433492773814
Fold 2 IBS: 0.1797844922307758
Fold 3 IBS: 0.1523682154464997
Fold 4 IBS: 0.14642414274758808
Fold 5 IBS: 0.25359874998491827
[I 2024-04-13 23:58:41,552] Trial 75 finished with value: 0.178697987067504 and parameters: {'l1_ratio': 0.08329105235709114}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16129911359955093
Fold 2 IBS: 0.179562830569666
Fold 3 IBS: 0.1523762695331006
Fold 4 IBS: 0.2225025243442987
Fold 5 IBS: 0.25365554767915277
[I 2024-04-13 23:58:44,959] Trial 76 finished with value: 0.1938792571451538 and parameters: {'l1_ratio': 0.028512034772785286}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16133703561261972
Fold 2 IBS: 0.18227739797487524
Fold 3 IBS: 0.15238077155136506
Fold 4 IBS: 0.14650638596015222
Fold 5 IBS: 0.2535908590795982
[I 2024-04-13 23:58:48,767] Trial 77 finished with value: 0.1792184900357221 and parameters: {'l1_ratio': 0.1554857765328722}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1615187387682332
Fold 2 IBS: 0.1841204461852781
Fold 3 IBS: 0.15273746292179574
Fold 4 IBS: 0.1465879177988228
Fold 5 IBS: 0.25400160775285413
[I 2024-04-13 23:58:51,310] Trial 78 finished with value: 0.17979323468539682 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131084690070605
Fold 2 IBS: 0.17984795361700023
Fold 3 IBS: 0.1523929495295477
Fold 4 IBS: 0.14647870291079132
Fold 5 IBS: 0.25368185988012404
[I 2024-04-13 23:58:54,988] Trial 79 finished with value: 0.17874246256763388 and parameters: {'l1_ratio': 0.07236212705648226}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613519113691725
Fold 2 IBS: 0.1825403228447479
Fold 3 IBS: 0.15240173135061755
Fold 4 IBS: 0.14650690257458185
Fold 5 IBS: 0.2536198423776362
[I 2024-04-13 23:58:57,948] Trial 80 finished with value: 0.17928414210335122 and parameters: {'l1_ratio': 0.20550277116346655}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613163297698004
Fold 2 IBS: 0.17988300915269032
Fold 3 IBS: 0.15235846074268322
Fold 4 IBS: 0.14640049671226274
Fold 5 IBS: 0.253564144972907
[I 2024-04-13 23:59:02,385] Trial 81 finished with value: 0.17870448827006874 and parameters: {'l1_ratio': 0.08969153317217314}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16132835986492403
Fold 2 IBS: 0.1820542372895897
Fold 3 IBS: 0.15241925392340627
Fold 4 IBS: 0.14648949655056046
Fold 5 IBS: 0.2537202010262514
[I 2024-04-13 23:59:07,287] Trial 82 finished with value: 0.17920230973094636 and parameters: {'l1_ratio': 0.12738265686284173}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.21305045299866357
Fold 2 IBS: 0.22033479005750667
Fold 3 IBS: 0.20340608022172968
Fold 4 IBS: 0.22323809551263182
Fold 5 IBS: 0.2179499540298089
[I 2024-04-13 23:59:08,554] Trial 83 finished with value: 0.21559587456406812 and parameters: {'l1_ratio': 0.018556673131907286}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131494266560173
Fold 2 IBS: 0.17972623599358434
Fold 3 IBS: 0.15238535424654584
Fold 4 IBS: 0.14645541978580082
Fold 5 IBS: 0.25365002431162653
[I 2024-04-13 23:59:13,760] Trial 84 finished with value: 0.17870639540063185 and parameters: {'l1_ratio': 0.08542356455512168}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131386943864137
Fold 2 IBS: 0.17982864447036304
Fold 3 IBS: 0.15235524371066395
Fold 4 IBS: 0.14640039881751912
Fold 5 IBS: 0.2535597966568657
[I 2024-04-13 23:59:17,279] Trial 85 finished with value: 0.17869159061881063 and parameters: {'l1_ratio': 0.08173450901644205}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16143013218812396
Fold 2 IBS: 0.18326662103528069
Fold 3 IBS: 0.15253490868366124
Fold 4 IBS: 0.1465158883610474
Fold 5 IBS: 0.2537972054538515
[I 2024-04-13 23:59:19,856] Trial 86 finished with value: 0.17950895114439297 and parameters: {'l1_ratio': 0.5196302291802515}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16133237765382452
Fold 2 IBS: 0.18217204610071663
Fold 3 IBS: 0.15242511502011186
Fold 4 IBS: 0.14649232847247406
Fold 5 IBS: 0.2535574708293232
[I 2024-04-13 23:59:22,162] Trial 87 finished with value: 0.17919586761529005 and parameters: {'l1_ratio': 0.14000249345195406}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16134179903818607
Fold 2 IBS: 0.18243130251149467
Fold 3 IBS: 0.15243690667967583
Fold 4 IBS: 0.14650350203983875
Fold 5 IBS: 0.25359350686385607
[I 2024-04-13 23:59:25,442] Trial 88 finished with value: 0.1792614034266103 and parameters: {'l1_ratio': 0.17015278079199297}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613220235107081
Fold 2 IBS: 0.18000309291677052
Fold 3 IBS: 0.15236752036906817
Fold 4 IBS: 0.1464037306406701
Fold 5 IBS: 0.25358355509083225
[I 2024-04-13 23:59:28,012] Trial 89 finished with value: 0.17873598450560985 and parameters: {'l1_ratio': 0.10825682406886386}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131462696415938
Fold 2 IBS: 0.17975658606425918
Fold 3 IBS: 0.15237642206431137
Fold 4 IBS: 0.14643913250396168
Fold 5 IBS: 0.2536233289282328
[I 2024-04-13 23:59:31,470] Trial 90 finished with value: 0.1787020193049849 and parameters: {'l1_ratio': 0.08430109769673218}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.1613125667742459
Fold 2 IBS: 0.17969102226572772
Fold 3 IBS: 0.15237820360822535
Fold 4 IBS: 0.1464476662143686
Fold 5 IBS: 0.2536334854355238
[I 2024-04-13 23:59:35,677] Trial 91 finished with value: 0.17869258885961828 and parameters: {'l1_ratio': 0.07736175498535955}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131024517046358
Fold 2 IBS: 0.17967384571649
Fold 3 IBS: 0.15236735332945792
Fold 4 IBS: 0.14643266175746844
Fold 5 IBS: 0.25360541195659203
[I 2024-04-13 23:59:39,573] Trial 92 finished with value: 0.17867790358609442 and parameters: {'l1_ratio': 0.06965198671732087}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.21287592050848733
Fold 2 IBS: 0.22009888558212792
Fold 3 IBS: 0.20319353895831588
Fold 4 IBS: 0.22295776604377002
Fold 5 IBS: 0.25353083777328933
[I 2024-04-13 23:59:42,029] Trial 93 finished with value: 0.2225313897731981 and parameters: {'l1_ratio': 0.02227890181293246}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16131038260363548
Fold 2 IBS: 0.1796609300186158
Fold 3 IBS: 0.15237114272698493
Fold 4 IBS: 0.14643958794653908
Fold 5 IBS: 0.25361676196336636
[I 2024-04-13 23:59:45,522] Trial 94 finished with value: 0.1786797610518283 and parameters: {'l1_ratio': 0.07004261678421228}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.161306037462236
Fold 2 IBS: 0.1796585056150042
Fold 3 IBS: 0.15234567078466363
Fold 4 IBS: 0.146398833162665
Fold 5 IBS: 0.253543912477759
[I 2024-04-13 23:59:51,098] Trial 95 finished with value: 0.17865059190046556 and parameters: {'l1_ratio': 0.0563046753048849}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16148991622794479
Fold 2 IBS: 0.18375180246760442
Fold 3 IBS: 0.15263859113882935
Fold 4 IBS: 0.14652565586676233
Fold 5 IBS: 0.253945599691539
[I 2024-04-13 23:59:55,673] Trial 96 finished with value: 0.17967031307853598 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16130766348050124
Fold 2 IBS: 0.17970102383400907
Fold 3 IBS: 0.15234497833865046
Fold 4 IBS: 0.14639604166566986
Fold 5 IBS: 0.25354221006025235
[I 2024-04-13 23:59:59,489] Trial 97 finished with value: 0.17865838347581658 and parameters: {'l1_ratio': 0.06164945105719943}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16130973398529033
Fold 2 IBS: 0.17972159476431518
Fold 3 IBS: 0.15235335681246132
Fold 4 IBS: 0.14640703341245084

Fold 5 IBS: 0.2535633964402299
[I 2024-04-14 00:00:04,170] Trial 98 finished with value: 0.17867102308294952 and parameters: {'l1_ratio': 0.0682397155252202}. Best is trial 51 with value: 0.17864209486823032.
Fold 1 IBS: 0.16130916156891112
Fold 2 IBS: 0.1797745136142011
Fold 3 IBS: 0.1523983224136218
Fold 4 IBS: 0.14649286610500428
Fold 5 IBS: 0.25370183595794904
[I 2024-04-14 00:00:08,541] Trial 99 finished with value: 0.1787353399319375 and parameters: {'l1_ratio': 0.0667304121180121}. Best is trial 51 with value: 0.17864209486823032.


* Best trial for IBS:
 FrozenTrial(number=51, state=TrialState.COMPLETE, values=[0.17864209486823032], datetime_start=datetime.datetime(2024, 4, 13, 23, 57, 33, 815139), datetime_complete=datetime.datetime(2024, 4, 13, 23, 57, 37, 280204), params={'l1_ratio': 0.05123710958654414}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=51, value=None)


* Best Score for IBS:
 0.17864209486823032

In [48]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.759
train_ibs:  0.179

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.4231641494784485)

test_cindex : 0.571

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.05123710958654414)

test_ibs:  0.275

In [52]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [85]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:49:38,775] A new study created in memory with name: no-name-f05b2836-6c34-4d37-ac66-b8eca987a59c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:49:42,443] Trial 0 finished with value: 0.7281518440331286 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7281518440331286.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:49:44,943] Trial 1 finished with value: 0.7457480169493687 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 12:49:46,966] Trial 2 finished with value: 0.735155830513213 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:47,902] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:48,970] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:49:52,534] Trial 5 finished with value: 0.7472660785898178 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:49:56,299] Trial 6 finished with value: 0.7381544794046891 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:58,230] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 12:50:03,946] Trial 8 finished with value: 0.5206572769953052 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:50:08,383] Trial 9 finished with value: 0.7451609000218509 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:09,160] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:50:10,956] Trial 11 finished with value: 0.7377757428843917 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:50:15,979] Trial 12 finished with value: 0.7420971969477915 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:50:24,589] Trial 13 finished with value: 0.7365266504825564 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017530569165213797, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:50:26,978] Trial 14 finished with value: 0.7600266365278019 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.48589405900235655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17488909350671974, 'warm_start': True}. Best is trial 14 with value: 0.7600266365278019.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:28,034] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.3692598016141903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19402726021030228, 'warm_start': True}. Best is trial 14 with value: 0.7600266365278019.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:30,650] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.5327960974085133, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38557060567081813, 'warm_start': True}. Best is trial 14 with value: 0.7600266365278019.
Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:50:30,958] Trial 17 finished with value: 0.7892309398880706 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 10, 'oob_score': True, 'max_samples': 0.4160888955210671, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06727307964156963, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:31,907] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.17503204955528034, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.165096259780819, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:50:33,779] Trial 19 finished with value: 0.7559522827753771 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 125, 'oob_score': True, 'max_samples': 0.41063061032948006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09963343232395264, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:34,667] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.29917214033678546, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24858261413121135, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:50:37,051] Trial 21 finished with value: 0.7650079920053727 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.4202227424087738, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07827117442054096, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:50:38,043] Trial 22 finished with value: 0.7809788776772643 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.41838439074526307, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0666458280631612, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:50:39,249] Trial 23 finished with value: 0.761909393532612 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.3932594208559168, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06762138067737998, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:50:40,483] Trial 24 finished with value: 0.7578548603269246 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.29362935445915617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06066228805580226, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:50:41,588] Trial 25 finished with value: 0.7694514319893504 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 85, 'oob_score': True, 'max_samples': 0.23502644549798718, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00235449332701948, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:42,251] Trial 26 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.21022320161020103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13164567172053532, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:42,573] Trial 27 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.17910991023083944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014724641541276492, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:43,012] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 40, 'oob_score': True, 'max_samples': 0.11183446310324852, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002444034582697069, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:50:44,796] Trial 29 finished with value: 0.7775741604685764 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.34624300666434216, 'max_features': None, 'min_weight_fraction_leaf': 0.04703846961241064, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:47,365] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.3359229598579714, 'max_features': None, 'min_weight_fraction_leaf': 0.21535820339738693, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.

Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:50:48,819] Trial 31 finished with value: 0.7659152903896449 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.25074023423629904, 'max_features': None, 'min_weight_fraction_leaf': 0.04816721016288783, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:50:49,498] Trial 32 finished with value: 0.7843718803263862 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.5438109085992663, 'max_features': None, 'min_weight_fraction_leaf': 0.08648554774122166, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:50:50,607] Trial 33 finished with value: 0.7740147548914054 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.544101480226597, 'max_features': None, 'min_weight_fraction_leaf': 0.13964795626206533, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:50:51,447] Trial 34 finished with value: 0.7760559603588271 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 97, 'oob_score': True, 'max_samples': 0.4518556433747414, 'max_features': None, 'min_weight_fraction_leaf': 0.08699466312158283, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7347417840375586
[I 2024-04-14 12:50:51,836] Trial 35 finished with value: 0.821075806982058 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.5216655889434714, 'max_features': None, 'min_weight_fraction_leaf': 0.044982812395241205, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:50:52,217] Trial 36 finished with value: 0.7722469807506789 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 32, 'oob_score': True, 'max_samples': 0.6700160400996815, 'max_features': None, 'min_weight_fraction_leaf': 0.1426556640974837, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.6784037558685446
[I 2024-04-14 12:50:52,771] Trial 37 finished with value: 0.7873906957959766 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.5830642701570617, 'max_features': None, 'min_weight_fraction_leaf': 0.08356687905505909, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:50:53,276] Trial 38 finished with value: 0.7859622867850847 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.6815535626086774, 'max_features': None, 'min_weight_fraction_leaf': 0.10357596080807438, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:50:53,585] Trial 39 finished with value: 0.7850456909534103 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 28, 'oob_score': True, 'max_samples': 0.7097826087207546, 'max_features': None, 'min_weight_fraction_leaf': 0.11787330832903728, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7723004694835681
[I 2024-04-14 12:50:54,052] Trial 40 finished with value: 0.8256151813632308 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 57, 'oob_score': True, 'max_samples': 0.8420978362663503, 'max_features': None, 'min_weight_fraction_leaf': 0.03739385491872656, 'warm_start': True}. Best is trial 40 with value: 0.8256151813632308.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7535211267605634
[I 2024-04-14 12:50:54,559] Trial 41 finished with value: 0.8215139473997348 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.9990097687431341, 'max_features': None, 'min_weight_fraction_leaf': 0.03835542275521481, 'warm_start': True}. Best is trial 40 with value: 0.8256151813632308.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7676056338028169
[I 2024-04-14 12:50:54,884] Trial 42 finished with value: 0.8317529517114874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 22, 'oob_score': True, 'max_samples': 0.9854345464574438, 'max_features': None, 'min_weight_fraction_leaf': 0.030065593229884995, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:50:55,243] Trial 43 finished with value: 0.805884737138506 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.9910765017367337, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03822397715359825, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:50:55,842] Trial 44 finished with value: 0.8074873596823615 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 35, 'oob_score': True, 'max_samples': 0.9674422854509271, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03099581273343698, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:50:56,372] Trial 45 finished with value: 0.8110918415567981 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8546485810385884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.035451817405702565, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.625
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:50:58,296] Trial 46 finished with value: 0.7428514327009917 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.8685366583806222, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027234676496553298, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.744131455399061
[I 2024-04-14 12:50:58,706] Trial 47 finished with value: 0.8171341032725834 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.8684089446104679, 'max_features': None, 'min_weight_fraction_leaf': 0.04618465431156833, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 12:50:59,802] Trial 48 finished with value: 0.7458915026407004 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9166675132024303, 'max_features': None, 'min_weight_fraction_leaf': 0.39782702169399947, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:51:00,223] Trial 49 finished with value: 0.8202536040834915 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.7878171540040061, 'max_features': None, 'min_weight_fraction_leaf': 0.0009009708504232813, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:51:02,312] Trial 50 finished with value: 0.8181130647691741 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 356, 'oob_score': False, 'max_samples': 0.7899706436285319, 'max_features': None, 'min_weight_fraction_leaf': 0.006710204917764943, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:51:03,866] Trial 51 finished with value: 0.8172806863632663 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.7750707159461326, 'max_features': None, 'min_weight_fraction_leaf': 0.0008710587792558205, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 12:51:05,078] Trial 52 finished with value: 0.82066790309537 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 417, 'oob_score': False, 'max_samples': 0.8281135464935815, 'max_features': None, 'min_weight_fraction_leaf': 0.021483356033540256, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 12:51:06,333] Trial 53 finished with value: 0.8217024078063453 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.8291152952323888, 'max_features': None, 'min_weight_fraction_leaf': 0.031921658073411095, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:51:07,930] Trial 54 finished with value: 0.8274713535392276 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.9443966405068337, 'max_features': None, 'min_weight_fraction_leaf': 0.02588019976858258, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:51:09,176] Trial 55 finished with value: 0.8304447235546677 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.9461860404965909, 'max_features': None, 'min_weight_fraction_leaf': 0.05336607321645103, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6272321428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 12:51:13,212] Trial 56 finished with value: 0.7294502275334355 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.9504771378964706, 'max_features': None, 'min_weight_fraction_leaf': 0.29669443075161894, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:51:14,248] Trial 57 finished with value: 0.8221036118218825 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9974125372324327, 'max_features': None, 'min_weight_fraction_leaf': 0.06517220061887827, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:51:15,172] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.9056124925654404, 'max_features': None, 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:51:16,540] Trial 59 finished with value: 0.8199567511570018 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 325, 'oob_score': False, 'max_samples': 0.9347501839505428, 'max_features': None, 'min_weight_fraction_leaf': 0.06560214874955103, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.5892857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:51:20,711] Trial 60 finished with value: 0.730423526969257 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.8874254435807117, 'max_features': None, 'min_weight_fraction_leaf': 0.1189877126682585, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:51:22,317] Trial 61 finished with value: 0.8202057192429153 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9834494437668313, 'max_features': None, 'min_weight_fraction_leaf': 0.0573547525154411, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:51:24,013] Trial 62 finished with value: 0.8326345559536964 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 339, 'oob_score': False, 'max_samples': 0.8272875133535434, 'max_features': None, 'min_weight_fraction_leaf': 0.021834423884142258, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 12:51:25,956] Trial 63 finished with value: 0.8122955024081626 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.8329452765420907, 'max_features': None, 'min_weight_fraction_leaf': 0.07497271601770447, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 12:51:28,154] Trial 64 finished with value: 0.8093918874378062 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9368894740163626, 'max_features': None, 'min_weight_fraction_leaf': 0.09351386622613925, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:51:30,612] Trial 65 finished with value: 0.8326190031272723 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.7454841889145698, 'max_features': None, 'min_weight_fraction_leaf': 0.022536083830532825, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:51:31,994] Trial 66 finished with value: 0.8313609053971838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.7230484371829358, 'max_features': None, 'min_weight_fraction_leaf': 0.021500018947879146, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:51:33,461] Trial 67 finished with value: 0.8305170235406436 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.7393599850936642, 'max_features': None, 'min_weight_fraction_leaf': 0.024147535010390957, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 12:51:34,542] Trial 68 finished with value: 0.8452762458003509 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.7427007695988085, 'max_features': None, 'min_weight_fraction_leaf': 0.01779057408953172, 'warm_start': True}. Best is trial 68 with value: 0.8452762458003509.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:51:35,495] Trial 69 finished with value: 0.8496835536675003 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.7457884481689102, 'max_features': None, 'min_weight_fraction_leaf': 0.017318131927655057, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:51:36,776] Trial 70 finished with value: 0.8434202305373113 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.7347919547095044, 'max_features': None, 'min_weight_fraction_leaf': 0.020651216069239264, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:51:38,202] Trial 71 finished with value: 0.84883967181096 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 218, 'oob_score': False, 'max_samples': 0.7354619515845321, 'max_features': None, 'min_weight_fraction_leaf': 0.016803980885547094, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:51:39,294] Trial 72 finished with value: 0.8378948361302088 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.6304929288353576, 'max_features': None, 'min_weight_fraction_leaf': 0.013738560806839913, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:51:40,572] Trial 73 finished with value: 0.8383957655656632 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.6195015886070395, 'max_features': None, 'min_weight_fraction_leaf': 0.01505981838898209, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:51:41,514] Trial 74 finished with value: 0.8448087388247897 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.6199378596508701, 'max_features': None, 'min_weight_fraction_leaf': 0.008813491940142528, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:51:42,442] Trial 75 finished with value: 0.8284271407228996 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.6422952688306902, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.007943385677349297, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.

Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:51:43,340] Trial 76 finished with value: 0.8356249741505056 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.6150026911684802, 'max_features': None, 'min_weight_fraction_leaf': 0.012082946593644771, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:51:44,297] Trial 77 finished with value: 0.7599705217019304 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.5914589089574711, 'max_features': None, 'min_weight_fraction_leaf': 0.014685184397003228, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 12:51:45,257] Trial 78 finished with value: 0.8202670577380209 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.6274066209011758, 'max_features': None, 'min_weight_fraction_leaf': 0.05381552916573561, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:51:46,251] Trial 79 finished with value: 0.8478741006929684 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.6820548566666732, 'max_features': None, 'min_weight_fraction_leaf': 0.00967942569015243, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:51:49,588] Trial 80 finished with value: 0.7303866484518248 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 177, 'oob_score': False, 'max_samples': 0.6775857540438628, 'max_features': None, 'min_weight_fraction_leaf': 0.0773231750938129, 'warm_start': False}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:51:50,694] Trial 81 finished with value: 0.8451760232529454 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.705654254937387, 'max_features': None, 'min_weight_fraction_leaf': 0.011423196772596417, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:51:51,665] Trial 82 finished with value: 0.8266529747200911 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 234, 'oob_score': False, 'max_samples': 0.7024106575493354, 'max_features': None, 'min_weight_fraction_leaf': 0.04609671450162135, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:51:52,496] Trial 83 finished with value: 0.8154772752469601 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.5734722599298255, 'max_features': None, 'min_weight_fraction_leaf': 0.010125018270759366, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:51:53,310] Trial 84 finished with value: 0.8432058689940586 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.666309775124175, 'max_features': None, 'min_weight_fraction_leaf': 0.0026218583854184007, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:51:54,213] Trial 85 finished with value: 0.8470031625593721 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.6635405881192851, 'max_features': None, 'min_weight_fraction_leaf': 0.002344826629627635, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 12:51:55,030] Trial 86 finished with value: 0.8065029590095005 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.6526270280183535, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0020177600275221325, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:51:55,927] Trial 87 finished with value: 0.8139120605534877 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 170, 'oob_score': False, 'max_samples': 0.6930812988503632, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04046611420841914, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:51:56,768] Trial 88 finished with value: 0.8140807643986621 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.6570670022833975, 'max_features': None, 'min_weight_fraction_leaf': 0.05499149836556118, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:51:57,712] Trial 89 finished with value: 0.8416349685468119 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 189, 'oob_score': False, 'max_samples': 0.740597932752879, 'max_features': None, 'min_weight_fraction_leaf': 0.0346978319197411, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:51:58,844] Trial 90 finished with value: 0.7686498625771644 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.7290242468037214, 'max_features': None, 'min_weight_fraction_leaf': 0.2513921457170648, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.812206572769953
[I 2024-04-14 12:51:59,926] Trial 91 finished with value: 0.8486473677462687 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 184, 'oob_score': False, 'max_samples': 0.7549021412312438, 'max_features': None, 'min_weight_fraction_leaf': 0.0003353156461928454, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:52:01,234] Trial 92 finished with value: 0.843258483639489 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.7744489279015901, 'max_features': None, 'min_weight_fraction_leaf': 0.003312926413915166, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:52:02,423] Trial 93 finished with value: 0.8321012919503528 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 261, 'oob_score': False, 'max_samples': 0.7645840199325343, 'max_features': None, 'min_weight_fraction_leaf': 0.041343328705331334, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:52:03,550] Trial 94 finished with value: 0.855232407271082 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.7127178148051858, 'max_features': None, 'min_weight_fraction_leaf': 0.01586498778855871, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:52:04,685] Trial 95 finished with value: 0.8416834915379139 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.8079013616638635, 'max_features': None, 'min_weight_fraction_leaf': 0.031762515929408985, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:52:05,721] Trial 96 finished with value: 0.7758217737288599 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 137, 'oob_score': False, 'max_samples': 0.6909885888874797, 'max_features': None, 'min_weight_fraction_leaf': 0.18731988166300653, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:52:07,165] Trial 97 finished with value: 0.8433268264679574 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.7159257509447517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017328506018913566, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:52:08,000] Trial 98 finished with value: 0.8151855700869628 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 161, 'oob_score': False, 'max_samples': 0.760284301272186, 'max_features': None, 'min_weight_fraction_leaf': 0.07012484642850524, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6116071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823

[I 2024-04-14 12:52:11,929] A new study created in memory with name: no-name-3ba80f02-eb71-47f1-b95f-c3f8942d676e

Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:52:11,911] Trial 99 finished with value: 0.7345071219868683 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.7955506870578684, 'max_features': None, 'min_weight_fraction_leaf': 0.05139875752922479, 'warm_start': False}. Best is trial 94 with value: 0.855232407271082.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.855232407271082], datetime_start=datetime.datetime(2024, 4, 14, 12, 52, 2, 440618), datetime_complete=datetime.datetime(2024, 4, 14, 12, 52, 3, 549088), params={'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.7127178148051858, 'max_features': None, 'min_weight_fraction_leaf': 0.01586498778855871, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=94, value=None)


* Best Score for C-index:
 0.855232407271082

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16880360625985416
Fold 2 IBS: 0.24732433151635422
Fold 3 IBS: 0.1659072118315618
Fold 4 IBS: 0.1568116644950886
Fold 5 IBS: 0.23807687059812613
[I 2024-04-14 12:52:18,083] Trial 0 finished with value: 0.19538473694019698 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19538473694019698.
Fold 1 IBS: 0.16543513322609077
Fold 2 IBS: 0.20977957358344046
Fold 3 IBS: 0.1706303561657185
Fold 4 IBS: 0.16172607637443032
Fold 5 IBS: 0.22765702732918122
[I 2024-04-14 12:52:19,521] Trial 1 finished with value: 0.18704563333577223 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-14 12:52:21,125] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-14 12:52:27,279] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-14 12:52:32,248] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.15631707214386673
Fold 2 IBS: 0.2242742311664943
Fold 3 IBS: 0.16295157476672437
Fold 4 IBS: 0.14718772732955032
Fold 5 IBS: 0.2319828116610088
[I 2024-04-14 12:52:37,621] Trial 5 finished with value: 0.18454268341352892 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17185590557761352
Fold 2 IBS: 0.20103465197964324
Fold 3 IBS: 0.16459803471117013
Fold 4 IBS: 0.16143456485788238
Fold 5 IBS: 0.22772639076003676
[I 2024-04-14 12:52:41,726] Trial 6 finished with value: 0.1853299095772692 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.20761917964024726
Fold 2 IBS: 0.215551580537287
Fold 3 IBS: 0.19929872434455675
Fold 4 IBS: 0.2165802601490779
Fold 5 IBS: 0.21629941564703706
[I 2024-04-14 12:52:45,885] Trial 7 finished with value: 0.21106983206364122 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-14 12:52:52,842] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.1657342642026369
Fold 2 IBS: 0.2117847519725899
Fold 3 IBS: 0.17386517217632436
Fold 4 IBS: 0.1656320690177135
Fold 5 IBS: 0.22808746599083526
[I 2024-04-14 12:52:54,334] Trial 9 finished with value: 0.18902074467201999 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-14 12:53:01,447] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.16834827701348198
Fold 2 IBS: 0.2105625570851029
Fold 3 IBS: 0.17143938900361566
Fold 4 IBS: 0.16649569203235007
Fold 5 IBS: 0.22507759132080626
[I 2024-04-14 12:53:04,742] Trial 11 finished with value: 0.18838470129107138 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17137590171088243
Fold 2 IBS: 0.20079034220960656
Fold 3 IBS: 0.16417736688832213
Fold 4 IBS: 0.16117081707433228
Fold 5 IBS: 0.22799428371541863
[I 2024-04-14 12:53:07,643] Trial 12 finished with value: 0.18510174231971238 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.1607651825958809
Fold 2 IBS: 0.22174579782307546
Fold 3 IBS: 0.1649550027841188
Fold 4 IBS: 0.1531991644518084
Fold 5 IBS: 0.23307239842144356
[I 2024-04-14 12:53:09,711] Trial 13 finished with value: 0.18674750921526542 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.16690971688810288
Fold 2 IBS: 0.26006508023076974
Fold 3 IBS: 0.15642059173639022
Fold 4 IBS: 0.1435033675526236
Fold 5 IBS: 0.23748928499217753
[I 2024-04-14 12:53:13,985] Trial 14 finished with value: 0.19287760828001282 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.8286563887351183, 'max_features': None, 'min_weight_fraction_leaf': 0.09422981531813096}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17020016973897817
Fold 2 IBS: 0.21806226199654052
Fold 3 IBS: 0.1717651716228649
Fold 4 IBS: 0.1653338076108178
Fold 5 IBS: 0.22984629902145176
[I 2024-04-14 12:53:18,016] Trial 15 finished with value: 0.19104154199813062 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.6817544899569143, 'max_features': 'auto', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 5 with value: 0.18454268341352892.

Fold 1 IBS: 0.16429944092453677
Fold 2 IBS: 0.21977053735105737
Fold 3 IBS: 0.17110337054121788
Fold 4 IBS: 0.16302411703282363
Fold 5 IBS: 0.22782986562873245
[I 2024-04-14 12:53:20,742] Trial 16 finished with value: 0.1892054662956736 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24786833673530304}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.2140210250926074
Fold 2 IBS: 0.22165374242688704
Fold 3 IBS: 0.20482992077952775
Fold 4 IBS: 0.2248506856151436
Fold 5 IBS: 0.21866286292181575
[I 2024-04-14 12:53:22,460] Trial 17 finished with value: 0.2168036473671963 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3527363076520275}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.21398207456199575
Fold 2 IBS: 0.2210878885925555
Fold 3 IBS: 0.20500084248625938
Fold 4 IBS: 0.22467759051518113
Fold 5 IBS: 0.21837641563069746
[I 2024-04-14 12:53:26,027] Trial 18 finished with value: 0.21662496235733783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.16753738713947874
Fold 2 IBS: 0.26234248514438036
Fold 3 IBS: 0.16650041026644735
Fold 4 IBS: 0.14521562457631151
Fold 5 IBS: 0.23833905713496578
[I 2024-04-14 12:53:26,320] Trial 19 finished with value: 0.19598699285231674 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.7744054221786105, 'max_features': None, 'min_weight_fraction_leaf': 0.15294426956488405}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.2140058010941674
Fold 2 IBS: 0.22070271305097472
Fold 3 IBS: 0.20512571269324692
Fold 4 IBS: 0.2244581340346379
Fold 5 IBS: 0.2175740773836072
[I 2024-04-14 12:53:28,531] Trial 20 finished with value: 0.21637328765132682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': None, 'min_weight_fraction_leaf': 0.3111340864325056}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17010203492581122
Fold 2 IBS: 0.19545931456517315
Fold 3 IBS: 0.16505420285841496
Fold 4 IBS: 0.162036366008543
Fold 5 IBS: 0.22560745868664608
[I 2024-04-14 12:53:32,174] Trial 21 finished with value: 0.1836518754089177 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8774254573678859, 'max_features': None, 'min_weight_fraction_leaf': 0.38285115003898385}. Best is trial 21 with value: 0.1836518754089177.
Fold 1 IBS: 0.16858975944081775
Fold 2 IBS: 0.1887959819871508
Fold 3 IBS: 0.16607588423226846
Fold 4 IBS: 0.16617493745455414
Fold 5 IBS: 0.22880387054646664
[I 2024-04-14 12:53:35,813] Trial 22 finished with value: 0.18368808673225157 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8533162629857436, 'max_features': None, 'min_weight_fraction_leaf': 0.39473610054688535}. Best is trial 21 with value: 0.1836518754089177.
Fold 1 IBS: 0.16993490334905023
Fold 2 IBS: 0.18743907860924672
Fold 3 IBS: 0.16537727963411333
Fold 4 IBS: 0.16398158190840675
Fold 5 IBS: 0.22610918708699476
[I 2024-04-14 12:53:39,461] Trial 23 finished with value: 0.18256840611756237 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1691974301015811
Fold 2 IBS: 0.18763591528579984
Fold 3 IBS: 0.16630590486501148
Fold 4 IBS: 0.1648688267770149
Fold 5 IBS: 0.22705580400526276
[I 2024-04-14 12:53:43,455] Trial 24 finished with value: 0.183012776206934 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.911762237036045, 'max_features': None, 'min_weight_fraction_leaf': 0.4145963396824019}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17458509293896438
Fold 2 IBS: 0.18732389614959596
Fold 3 IBS: 0.1720385595590766
Fold 4 IBS: 0.17206638184046272
Fold 5 IBS: 0.23627026792126057
[I 2024-04-14 12:53:47,702] Trial 25 finished with value: 0.18845683968187205 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9270259482202138, 'max_features': None, 'min_weight_fraction_leaf': 0.44717127940994156}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1715342983017772
Fold 2 IBS: 0.20056722047631442
Fold 3 IBS: 0.16491283245976326
Fold 4 IBS: 0.1620343465169812
Fold 5 IBS: 0.22647312176686948
[I 2024-04-14 12:53:52,503] Trial 26 finished with value: 0.18510436390434112 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9129740059593043, 'max_features': None, 'min_weight_fraction_leaf': 0.3870919920523195}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1699990733958502
Fold 2 IBS: 0.18557893849483392
Fold 3 IBS: 0.16633066996451829
Fold 4 IBS: 0.16502841596463963
Fold 5 IBS: 0.22683004436910625
[I 2024-04-14 12:53:55,907] Trial 27 finished with value: 0.18275342843778963 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9882040097907008, 'max_features': None, 'min_weight_fraction_leaf': 0.45340256450947913}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17016221643396637
Fold 2 IBS: 0.18540296557411892
Fold 3 IBS: 0.16710214191696457
Fold 4 IBS: 0.16678323591071748
Fold 5 IBS: 0.22789974639547422
[I 2024-04-14 12:54:00,111] Trial 28 finished with value: 0.18347006124624832 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9741542767559068, 'max_features': None, 'min_weight_fraction_leaf': 0.450638299943646}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.213981238234591
Fold 2 IBS: 0.22129600200231184
Fold 3 IBS: 0.20476687908413987
Fold 4 IBS: 0.22462916295400534
Fold 5 IBS: 0.21851703166023365
[I 2024-04-14 12:54:03,660] Trial 29 finished with value: 0.21663806278705633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.773357424692515, 'max_features': None, 'min_weight_fraction_leaf': 0.4837438075147879}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1737873785599842
Fold 2 IBS: 0.19753704149828014
Fold 3 IBS: 0.16474278602254563
Fold 4 IBS: 0.16243873156676453
Fold 5 IBS: 0.22660859518105705
[I 2024-04-14 12:54:07,289] Trial 30 finished with value: 0.1850229065657263 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 377, 'oob_score': False, 'max_samples': 0.9986438777088522, 'max_features': None, 'min_weight_fraction_leaf': 0.42773069772809913}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17751338669623418
Fold 2 IBS: 0.18856087241291536
Fold 3 IBS: 0.17527262906800933
Fold 4 IBS: 0.17490246385178213
Fold 5 IBS: 0.23490629026498758
[I 2024-04-14 12:54:11,763] Trial 31 finished with value: 0.1902311284587857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.939658841329532, 'max_features': None, 'min_weight_fraction_leaf': 0.4524256463348925}. Best is trial 23 with value: 0.18256840611756237.

Fold 1 IBS: 0.21398563901141657
Fold 2 IBS: 0.22134596740550985
Fold 3 IBS: 0.2048025990579434
Fold 4 IBS: 0.22461415055237854
Fold 5 IBS: 0.21851803782809134
[I 2024-04-14 12:54:15,787] Trial 32 finished with value: 0.21665327877106794 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.7396444271446992, 'max_features': None, 'min_weight_fraction_leaf': 0.4501495537267681}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1881712152839018
Fold 2 IBS: 0.19602908273271186
Fold 3 IBS: 0.187050921824735
Fold 4 IBS: 0.18923643256610323
Fold 5 IBS: 0.21856358775020004
[I 2024-04-14 12:54:20,361] Trial 33 finished with value: 0.19581024803153038 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.9933327757837453, 'max_features': None, 'min_weight_fraction_leaf': 0.49338351231891625}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397810999123087
Fold 2 IBS: 0.22130875696604183
Fold 3 IBS: 0.2047621585928816
Fold 4 IBS: 0.2246288907097577
Fold 5 IBS: 0.21863208708031015
[I 2024-04-14 12:54:24,232] Trial 34 finished with value: 0.21666200066804442 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8938554646810188, 'max_features': None, 'min_weight_fraction_leaf': 0.45754449369723726}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397501954215553
Fold 2 IBS: 0.22130442891193944
Fold 3 IBS: 0.20482836466241144
Fold 4 IBS: 0.22464430529398755
Fold 5 IBS: 0.2263366391256349
[I 2024-04-14 12:54:29,238] Trial 35 finished with value: 0.21821775150722575 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.8179898225635556, 'max_features': None, 'min_weight_fraction_leaf': 0.406528295392146}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1704043619824355
Fold 2 IBS: 0.1996769947732447
Fold 3 IBS: 0.17293358110279214
Fold 4 IBS: 0.17522810502150687
Fold 5 IBS: 0.22035983910919235
[I 2024-04-14 12:54:34,646] Trial 36 finished with value: 0.1877205763978343 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9504880220263004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3678752707538403}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21398603848843456
Fold 2 IBS: 0.2212516593844012
Fold 3 IBS: 0.20480476599516775
Fold 4 IBS: 0.22467106118379263
Fold 5 IBS: 0.2186056754258949
[I 2024-04-14 12:54:38,571] Trial 37 finished with value: 0.2166638400955382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.6134779412492984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42910258289196446}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16894666579605158
Fold 2 IBS: 0.19374351857626196
Fold 3 IBS: 0.16515102637277138
Fold 4 IBS: 0.16283706893147565
Fold 5 IBS: 0.22711044098051275
[I 2024-04-14 12:54:41,575] Trial 38 finished with value: 0.18355774413141468 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.7324083825350811, 'max_features': None, 'min_weight_fraction_leaf': 0.3267902150060746}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.171282531867511
Fold 2 IBS: 0.25508848652905003
Fold 3 IBS: 0.1669250836383552
Fold 4 IBS: 0.15770675719213736
Fold 5 IBS: 0.23678921646135723
[I 2024-04-14 12:54:45,920] Trial 39 finished with value: 0.19755841513768216 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.8998447540408812, 'max_features': None, 'min_weight_fraction_leaf': 0.26335636534084506}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.2139718451769373
Fold 2 IBS: 0.22132290174406308
Fold 3 IBS: 0.2049379534123754
Fold 4 IBS: 0.2246651821236489
Fold 5 IBS: 0.21845691499847839
[I 2024-04-14 12:54:49,146] Trial 40 finished with value: 0.21667095949110057 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.5051356852082238, 'max_features': None, 'min_weight_fraction_leaf': 0.46950692236254693}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1721962878712996
Fold 2 IBS: 0.1867998174317839
Fold 3 IBS: 0.17047364354936667
Fold 4 IBS: 0.16869178324374284
Fold 5 IBS: 0.23042464053354605
[I 2024-04-14 12:54:52,217] Trial 41 finished with value: 0.1857172345259478 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.6950314186231272, 'max_features': None, 'min_weight_fraction_leaf': 0.3301730431422}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21398443372975648
Fold 2 IBS: 0.22133306215617224
Fold 3 IBS: 0.20478162661751423
Fold 4 IBS: 0.224616165333405
Fold 5 IBS: 0.21859375419206165
[I 2024-04-14 12:54:56,163] Trial 42 finished with value: 0.21666180840578192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.7359525705085804, 'max_features': None, 'min_weight_fraction_leaf': 0.4248133739979326}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1736208583095885
Fold 2 IBS: 0.2142799695808254
Fold 3 IBS: 0.16557686291518559
Fold 4 IBS: 0.16205491926644927
Fold 5 IBS: 0.22950893731135472
[I 2024-04-14 12:55:00,079] Trial 43 finished with value: 0.18900830947668068 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9424025262276309, 'max_features': None, 'min_weight_fraction_leaf': 0.3723018188063154}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17220312279887087
Fold 2 IBS: 0.18725195811040996
Fold 3 IBS: 0.1692113254426714
Fold 4 IBS: 0.16961224398342983
Fold 5 IBS: 0.22996231906173675
[I 2024-04-14 12:55:04,283] Trial 44 finished with value: 0.18564819387942375 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.86762300263298, 'max_features': None, 'min_weight_fraction_leaf': 0.4072940485682038}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17353029619868152
Fold 2 IBS: 0.1960823439514855
Fold 3 IBS: 0.17508121734079327
Fold 4 IBS: 0.17794858732068533
Fold 5 IBS: 0.2191881303895723
[I 2024-04-14 12:55:07,455] Trial 45 finished with value: 0.1883661150402436 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.8045246379242162, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32901914427946066}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1641095642199566
Fold 2 IBS: 0.22265946803961062
Fold 3 IBS: 0.16903299137029618
Fold 4 IBS: 0.15824030170824924
Fold 5 IBS: 0.22928987086599778
[I 2024-04-14 12:55:10,933] Trial 46 finished with value: 0.18866643924082208 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 363, 'oob_score': False, 'max_samples': 0.9607559032696665, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.211303506589669}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17189303802131756
Fold 2 IBS: 0.24494738775532268
Fold 3 IBS: 0.1666602138983221
Fold 4 IBS: 0.15996661850151628
Fold 5 IBS: 0.23743154462367178
[I 2024-04-14 12:55:13,876] Trial 47 finished with value: 0.1961797605600301 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.876896242953909, 'max_features': None, 'min_weight_fraction_leaf': 0.2817538668731424}. Best is trial 23 with value: 0.18256840611756237.

Fold 1 IBS: 0.1705674173139149
Fold 2 IBS: 0.1852617720416809
Fold 3 IBS: 0.16929920721077502
Fold 4 IBS: 0.16857228614310335
Fold 5 IBS: 0.23285081643644664
[I 2024-04-14 12:55:17,808] Trial 48 finished with value: 0.18531029982918418 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.9996528707471266, 'max_features': None, 'min_weight_fraction_leaf': 0.47380170342998185}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397420828984268
Fold 2 IBS: 0.22140730914697682
Fold 3 IBS: 0.2048165899556378
Fold 4 IBS: 0.22466454285026752
Fold 5 IBS: 0.2185528446348627
[I 2024-04-14 12:55:20,811] Trial 49 finished with value: 0.21668309897551746 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8459565404966409, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4242257306364142}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16902430601502333
Fold 2 IBS: 0.19338265075792843
Fold 3 IBS: 0.16486539224344463
Fold 4 IBS: 0.16147203223041565
Fold 5 IBS: 0.22765220951812717
[I 2024-04-14 12:55:24,637] Trial 50 finished with value: 0.18327931815298784 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.7982382644517961, 'max_features': None, 'min_weight_fraction_leaf': 0.35750036696317244}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16859461221748046
Fold 2 IBS: 0.19038638924084872
Fold 3 IBS: 0.16553825872694258
Fold 4 IBS: 0.16353660023264655
Fold 5 IBS: 0.22807647271719378
[I 2024-04-14 12:55:28,605] Trial 51 finished with value: 0.1832264666270224 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.8005649206872336, 'max_features': None, 'min_weight_fraction_leaf': 0.36691532058452314}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17293958401347873
Fold 2 IBS: 0.2192681783178068
Fold 3 IBS: 0.1659565471985156
Fold 4 IBS: 0.16202566536404225
Fold 5 IBS: 0.23130480410736612
[I 2024-04-14 12:55:34,358] Trial 52 finished with value: 0.1902989558002419 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9178460283734129, 'max_features': None, 'min_weight_fraction_leaf': 0.3557818682293127}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397828800315355
Fold 2 IBS: 0.2213044801251445
Fold 3 IBS: 0.20478578064864883
Fold 4 IBS: 0.2246281820625841
Fold 5 IBS: 0.2186066093064182
[I 2024-04-14 12:55:38,028] Trial 53 finished with value: 0.21666066802918982 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.8082070646632502, 'max_features': None, 'min_weight_fraction_leaf': 0.4060864243885318}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16929857607063142
Fold 2 IBS: 0.1855709592705922
Fold 3 IBS: 0.16590078913270798
Fold 4 IBS: 0.1644087579365555
Fold 5 IBS: 0.22603924109858942
[I 2024-04-14 12:55:41,902] Trial 54 finished with value: 0.1822436647018153 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.9565029369785671, 'max_features': None, 'min_weight_fraction_leaf': 0.43699319744655357}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2029441241859812
Fold 2 IBS: 0.20884651281655017
Fold 3 IBS: 0.19540591699611048
Fold 4 IBS: 0.2068895040199807
Fold 5 IBS: 0.218505374625429
[I 2024-04-14 12:55:44,901] Trial 55 finished with value: 0.20651828652881035 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.7759180607351711, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3850162625050211}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17387417382717657
Fold 2 IBS: 0.1967912473931568
Fold 3 IBS: 0.1754869137337466
Fold 4 IBS: 0.18059787836339708
Fold 5 IBS: 0.21820683103881933
[I 2024-04-14 12:55:48,512] Trial 56 finished with value: 0.18899140887125926 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.8899843079416504, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36599094159376067}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2139799225651981
Fold 2 IBS: 0.22127927639217232
Fold 3 IBS: 0.20485144900872682
Fold 4 IBS: 0.2246460458464435
Fold 5 IBS: 0.21852930609789148
[I 2024-04-14 12:55:51,949] Trial 57 finished with value: 0.2166571999820864 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.576438276587755, 'max_features': None, 'min_weight_fraction_leaf': 0.43635893837546796}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17480240560632257
Fold 2 IBS: 0.19615522167799648
Fold 3 IBS: 0.1763934683738566
Fold 4 IBS: 0.18169915729415803
Fold 5 IBS: 0.21709493251231066
[I 2024-04-14 12:55:56,980] Trial 58 finished with value: 0.18922903709292888 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9532859852286428, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.39848192471528204}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21397578197228534
Fold 2 IBS: 0.22105121992448867
Fold 3 IBS: 0.20474712700666953
Fold 4 IBS: 0.22460210382536355
Fold 5 IBS: 0.21846630950749174
[I 2024-04-14 12:55:57,905] Trial 59 finished with value: 0.21656850844725978 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.8354470540495106, 'max_features': None, 'min_weight_fraction_leaf': 0.4712438108607243}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1726127601700496
Fold 2 IBS: 0.23213992452417942
Fold 3 IBS: 0.16625971951919333
Fold 4 IBS: 0.16169924600658186
Fold 5 IBS: 0.23296316972000924
[I 2024-04-14 12:56:02,462] Trial 60 finished with value: 0.19313496398800267 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.918505174941936, 'max_features': None, 'min_weight_fraction_leaf': 0.34083396149253076}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17115985783827192
Fold 2 IBS: 0.18669540101486526
Fold 3 IBS: 0.1690037370937305
Fold 4 IBS: 0.16774797187785795
Fold 5 IBS: 0.2290404472831437
[I 2024-04-14 12:56:06,552] Trial 61 finished with value: 0.18472948302157385 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.9476308520028045, 'max_features': None, 'min_weight_fraction_leaf': 0.44612613879924584}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21397833720638162
Fold 2 IBS: 0.22133523964491808
Fold 3 IBS: 0.20478229195041203
Fold 4 IBS: 0.2246079755345025
Fold 5 IBS: 0.2186167177505955
[I 2024-04-14 12:56:10,772] Trial 62 finished with value: 0.21666411241736197 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9762049404553764, 'max_features': None, 'min_weight_fraction_leaf': 0.49754275023260003}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1744223841640345
Fold 2 IBS: 0.18700899459676598
Fold 3 IBS: 0.17217919062602105
Fold 4 IBS: 0.17202141747271338
Fold 5 IBS: 0.23216785220262717
[I 2024-04-14 12:56:15,087] Trial 63 finished with value: 0.1875599678124324 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.968031626078303, 'max_features': None, 'min_weight_fraction_leaf': 0.4618736342149034}. Best is trial 54 with value: 0.1822436647018153.

Fold 1 IBS: 0.17758210577267103
Fold 2 IBS: 0.18839515678161117
Fold 3 IBS: 0.17378027525748194
Fold 4 IBS: 0.17402263926693903
Fold 5 IBS: 0.23329928868140723
[I 2024-04-14 12:56:19,002] Trial 64 finished with value: 0.1894158931520221 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.8662053800926933, 'max_features': None, 'min_weight_fraction_leaf': 0.4182804957604697}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17735779335885185
Fold 2 IBS: 0.18791831745948914
Fold 3 IBS: 0.17437629608751362
Fold 4 IBS: 0.1754060616546171
Fold 5 IBS: 0.2347254760738243
[I 2024-04-14 12:56:22,530] Trial 65 finished with value: 0.18995678892685922 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9168825987611354, 'max_features': None, 'min_weight_fraction_leaf': 0.4432122195886301}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2139724421467841
Fold 2 IBS: 0.2214527792035684
Fold 3 IBS: 0.2048590624528698
Fold 4 IBS: 0.2245788896889019
Fold 5 IBS: 0.2185362799035361
[I 2024-04-14 12:56:26,992] Trial 66 finished with value: 0.21667989067913207 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.46781511608424425, 'max_features': None, 'min_weight_fraction_leaf': 0.3045521505569209}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398680109724927
Fold 2 IBS: 0.22135827072227557
Fold 3 IBS: 0.2048735104861736
Fold 4 IBS: 0.22472365818178486
Fold 5 IBS: 0.21862352189579365
[I 2024-04-14 12:56:30,855] Trial 67 finished with value: 0.2167131524766554 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 350, 'oob_score': False, 'max_samples': 0.6582583476676168, 'max_features': None, 'min_weight_fraction_leaf': 0.3804796765638992}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398754621893906
Fold 2 IBS: 0.220784415256965
Fold 3 IBS: 0.20495861786072853
Fold 4 IBS: 0.22449787181399974
Fold 5 IBS: 0.21784084447117796
[I 2024-04-14 12:56:34,975] Trial 68 finished with value: 0.21641385912436206 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.23482143077480938, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3934624841168519}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398687185517215
Fold 2 IBS: 0.22139575665018285
Fold 3 IBS: 0.2047910639890974
Fold 4 IBS: 0.2245872648354145
Fold 5 IBS: 0.21854958475231978
[I 2024-04-14 12:56:40,470] Trial 69 finished with value: 0.21666210841643735 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.7940255804653553, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4805897754538581}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2041191703983927
Fold 2 IBS: 0.20962737898277756
Fold 3 IBS: 0.19711142562638187
Fold 4 IBS: 0.20772967559861563
Fold 5 IBS: 0.2183057037055133
[I 2024-04-14 12:56:43,919] Trial 70 finished with value: 0.20737867086233625 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 17, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8487227557239918, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41490592987501546}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17259575541877814
Fold 2 IBS: 0.22029683841472378
Fold 3 IBS: 0.16571612203247052
Fold 4 IBS: 0.16231349383737712
Fold 5 IBS: 0.22994744909940326
[I 2024-04-14 12:56:47,724] Trial 71 finished with value: 0.19017393176055059 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.9046665199728599, 'max_features': None, 'min_weight_fraction_leaf': 0.3490138103045144}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398984891500278
Fold 2 IBS: 0.22132703559112848
Fold 3 IBS: 0.20485538942898837
Fold 4 IBS: 0.22468184149566728
Fold 5 IBS: 0.21854197240369455
[I 2024-04-14 12:56:50,636] Trial 72 finished with value: 0.2166792175668963 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.7417237460119614, 'max_features': None, 'min_weight_fraction_leaf': 0.4377532191740801}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17342415334654118
Fold 2 IBS: 0.2520286159476192
Fold 3 IBS: 0.16733908162702638
Fold 4 IBS: 0.15971476716385674
Fold 5 IBS: 0.2369472008097499
[I 2024-04-14 12:56:53,219] Trial 73 finished with value: 0.1978907637789587 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.9791771001513038, 'max_features': None, 'min_weight_fraction_leaf': 0.3151341872573396}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1523783018315216
Fold 2 IBS: 0.25752841787809405
Fold 3 IBS: 0.15865023022022903
Fold 4 IBS: 0.1469293709645116
Fold 5 IBS: 0.22884537022153476
[I 2024-04-14 12:56:57,806] Trial 74 finished with value: 0.18886633822317822 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.7597261021888175, 'max_features': None, 'min_weight_fraction_leaf': 0.028106730951250714}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17203138027431822
Fold 2 IBS: 0.18672618290031268
Fold 3 IBS: 0.17038726217502925
Fold 4 IBS: 0.16864095356589795
Fold 5 IBS: 0.2343085215113195
[I 2024-04-14 12:57:00,819] Trial 75 finished with value: 0.18641886008537553 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 323, 'oob_score': False, 'max_samples': 0.6919465218861461, 'max_features': None, 'min_weight_fraction_leaf': 0.3306551754510087}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1727138115840506
Fold 2 IBS: 0.21855719163630852
Fold 3 IBS: 0.16598015598426627
Fold 4 IBS: 0.16195355474343384
Fold 5 IBS: 0.23014794794296067
[I 2024-04-14 12:57:04,540] Trial 76 finished with value: 0.189870532378204 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.933109377361605, 'max_features': None, 'min_weight_fraction_leaf': 0.36359582317154915}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17070857985890084
Fold 2 IBS: 0.2654744432740884
Fold 3 IBS: 0.15749050693194808
Fold 4 IBS: 0.1458281671643887
Fold 5 IBS: 0.23993349327215213
[I 2024-04-14 12:57:07,859] Trial 77 finished with value: 0.19588703810029565 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.8922687338805234, 'max_features': None, 'min_weight_fraction_leaf': 0.1648569090893628}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17127175238988016
Fold 2 IBS: 0.23681907170241595
Fold 3 IBS: 0.16632945506132488
Fold 4 IBS: 0.15998000173876423
Fold 5 IBS: 0.2355786897961462
[I 2024-04-14 12:57:11,431] Trial 78 finished with value: 0.19399579413770632 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.8314975823537563, 'max_features': None, 'min_weight_fraction_leaf': 0.28987424398930645}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398696115622517
Fold 2 IBS: 0.22132775110717479
Fold 3 IBS: 0.2047844743795546
Fold 4 IBS: 0.22466419241471253
Fold 5 IBS: 0.218639565452965
[I 2024-04-14 12:57:15,289] Trial 79 finished with value: 0.21668058890212644 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.7147863835024943, 'max_features': None, 'min_weight_fraction_leaf': 0.45897134740659273}. Best is trial 54 with value: 0.1822436647018153.

Fold 1 IBS: 0.1754183266894564
Fold 2 IBS: 0.2119163985327653
Fold 3 IBS: 0.16611082563106694
Fold 4 IBS: 0.16255778819587066
Fold 5 IBS: 0.22916546086072462
[I 2024-04-14 12:57:17,485] Trial 80 finished with value: 0.18903375998197677 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9992480396864105, 'max_features': None, 'min_weight_fraction_leaf': 0.40510470687091726}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16993730570122387
Fold 2 IBS: 0.195387539069006
Fold 3 IBS: 0.1651714087990093
Fold 4 IBS: 0.16201193892631496
Fold 5 IBS: 0.22567140464684687
[I 2024-04-14 12:57:20,276] Trial 81 finished with value: 0.18363591942848018 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.8729504953795615, 'max_features': None, 'min_weight_fraction_leaf': 0.37901339934104195}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17059602798051093
Fold 2 IBS: 0.19576025349618845
Fold 3 IBS: 0.16527586886048148
Fold 4 IBS: 0.16216921896963785
Fold 5 IBS: 0.22563934477366224
[I 2024-04-14 12:57:22,925] Trial 82 finished with value: 0.1838881428160962 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.8793433759139604, 'max_features': None, 'min_weight_fraction_leaf': 0.37875540676023556}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1688164787241748
Fold 2 IBS: 0.18965430682325518
Fold 3 IBS: 0.16618614577597546
Fold 4 IBS: 0.1661442613630979
Fold 5 IBS: 0.22745311651470046
[I 2024-04-14 12:57:25,458] Trial 83 finished with value: 0.18365086184024076 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.8596640069096237, 'max_features': None, 'min_weight_fraction_leaf': 0.3926517547430121}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.213982517924714
Fold 2 IBS: 0.22134028753572813
Fold 3 IBS: 0.20486839792753697
Fold 4 IBS: 0.22465180979217697
Fold 5 IBS: 0.21856402394553515
[I 2024-04-14 12:57:28,496] Trial 84 finished with value: 0.21668140742513825 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.7978897939316169, 'max_features': None, 'min_weight_fraction_leaf': 0.43016329217079746}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16955786746443186
Fold 2 IBS: 0.1888109914576175
Fold 3 IBS: 0.165403814650411
Fold 4 IBS: 0.16378935148321216
Fold 5 IBS: 0.22551798003020745
[I 2024-04-14 12:57:32,383] Trial 85 finished with value: 0.182616001017176 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9358948791674491, 'max_features': None, 'min_weight_fraction_leaf': 0.4163843260750398}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2139659127114189
Fold 2 IBS: 0.2213058430062058
Fold 3 IBS: 0.2047998954201997
Fold 4 IBS: 0.2246551289755502
Fold 5 IBS: 0.2186437833442124
[I 2024-04-14 12:57:36,864] Trial 86 finished with value: 0.2166741126915174 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.9672107753485744, 'max_features': None, 'min_weight_fraction_leaf': 0.4839309447096827}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.18029523595045296
Fold 2 IBS: 0.19756882734748873
Fold 3 IBS: 0.18140356580749964
Fold 4 IBS: 0.187442503869447
Fold 5 IBS: 0.21589354656941978
[I 2024-04-14 12:57:41,006] Trial 87 finished with value: 0.19252073590886165 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.937791500744923, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41589566298884967}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1658833334845161
Fold 2 IBS: 0.21698059956725585
Fold 3 IBS: 0.17024180776620185
Fold 4 IBS: 0.1629144227091129
Fold 5 IBS: 0.22737649617013614
[I 2024-04-14 12:57:44,592] Trial 88 finished with value: 0.18867933193944458 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.9297067916046122, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2581006317330029}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17060519156572782
Fold 2 IBS: 0.18930502849920408
Fold 3 IBS: 0.1647821300478589
Fold 4 IBS: 0.16296071452652267
Fold 5 IBS: 0.22571370308607533
[I 2024-04-14 12:57:48,360] Trial 89 finished with value: 0.18267335354507777 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.9794054457739549, 'max_features': None, 'min_weight_fraction_leaf': 0.43792324727874116}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.18738975895838167
Fold 2 IBS: 0.200316373598964
Fold 3 IBS: 0.1858553433488537
Fold 4 IBS: 0.19295326279019026
Fold 5 IBS: 0.2178645385965687
[I 2024-04-14 12:57:49,994] Trial 90 finished with value: 0.19687585545859165 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.972970797060855, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4522473691813417}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16926655000191373
Fold 2 IBS: 0.18542452377204885
Fold 3 IBS: 0.16585353947869277
Fold 4 IBS: 0.16460153716121895
Fold 5 IBS: 0.22773118838132586
[I 2024-04-14 12:57:53,764] Trial 91 finished with value: 0.18257546775904004 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.9521862960288366, 'max_features': None, 'min_weight_fraction_leaf': 0.43852883097869544}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16892429762898473
Fold 2 IBS: 0.18646265672233156
Fold 3 IBS: 0.1654282006715355
Fold 4 IBS: 0.1642863887112045
Fold 5 IBS: 0.22770623766264497
[I 2024-04-14 12:57:57,576] Trial 92 finished with value: 0.18256155627934026 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.9594749224604052, 'max_features': None, 'min_weight_fraction_leaf': 0.4382959745060329}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1694038540499289
Fold 2 IBS: 0.18543879935671284
Fold 3 IBS: 0.16586969023548903
Fold 4 IBS: 0.16462913915674826
Fold 5 IBS: 0.22586792111306306
[I 2024-04-14 12:58:01,362] Trial 93 finished with value: 0.18224188078238843 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.951027581141039, 'max_features': None, 'min_weight_fraction_leaf': 0.434183032379547}. Best is trial 93 with value: 0.18224188078238843.
Fold 1 IBS: 0.16928255935057204
Fold 2 IBS: 0.18540640777204148
Fold 3 IBS: 0.1658202361732081
Fold 4 IBS: 0.1646058136763985
Fold 5 IBS: 0.22579726235858852
[I 2024-04-14 12:58:05,497] Trial 94 finished with value: 0.18218245586616172 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.9526180318811873, 'max_features': None, 'min_weight_fraction_leaf': 0.4336258803047899}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.16923916265142389
Fold 2 IBS: 0.18529265639052703
Fold 3 IBS: 0.16693367705651438
Fold 4 IBS: 0.16496792978619326
Fold 5 IBS: 0.22691047903734007
[I 2024-04-14 12:58:09,530] Trial 95 finished with value: 0.1826687809843997 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9482701576034527, 'max_features': None, 'min_weight_fraction_leaf': 0.43618730769703484}. Best is trial 94 with value: 0.18218245586616172.

Fold 1 IBS: 0.17691142196188117
Fold 2 IBS: 0.1884356638717461
Fold 3 IBS: 0.17473493092732248
Fold 4 IBS: 0.1743581409278057
Fold 5 IBS: 0.23455157057349743
[I 2024-04-14 12:58:13,521] Trial 96 finished with value: 0.18979834565245057 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.9548184208743441, 'max_features': None, 'min_weight_fraction_leaf': 0.46352447817689174}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.1720334166380091
Fold 2 IBS: 0.19310219127184633
Fold 3 IBS: 0.16467180888297991
Fold 4 IBS: 0.16215325103272105
Fold 5 IBS: 0.225731258677061
[I 2024-04-14 12:58:17,676] Trial 97 finished with value: 0.1835383853005235 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.9862595341313025, 'max_features': None, 'min_weight_fraction_leaf': 0.43210430346944234}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.1700673000394276
Fold 2 IBS: 0.18617467101403062
Fold 3 IBS: 0.16757525868013873
Fold 4 IBS: 0.16662978949249674
Fold 5 IBS: 0.2279242667055234
[I 2024-04-14 12:58:21,284] Trial 98 finished with value: 0.1836742571863234 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.9536448054185881, 'max_features': None, 'min_weight_fraction_leaf': 0.44518295335622443}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.21397475855510784
Fold 2 IBS: 0.2213213472048057
Fold 3 IBS: 0.20476273142913345
Fold 4 IBS: 0.22463568800419415
Fold 5 IBS: 0.21866074781038855
[I 2024-04-14 12:58:25,183] Trial 99 finished with value: 0.21667105460072594 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.9313705172208678, 'max_features': None, 'min_weight_fraction_leaf': 0.48244475073479054}. Best is trial 94 with value: 0.18218245586616172.


* Best trial for IBS:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.18218245586616172], datetime_start=datetime.datetime(2024, 4, 14, 12, 58, 1, 379059), datetime_complete=datetime.datetime(2024, 4, 14, 12, 58, 5, 496745), params={'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.9526180318811873, 'max_features': None, 'min_weight_fraction_leaf': 0.4336258803047899}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for IBS:
 0.18218245586616172

In [86]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [87]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.855
train_ibs:  0.182

#### Test

In [88]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [89]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=14, max_features=None, max_leaf_nodes=11,
                     max_samples=0.7127178148051858, min_samples_leaf=1,
                     min_samples_split=8,
                     min_weight_fraction_leaf=0.01586498778855871,
                     n_estimators=236, random_state=123, warm_start=True)

test_cindex:  0.643

RandomSurvivalForest(max_depth=2, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9526180318811873, min_samples_leaf=6,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.4336258803047899,
                     n_estimators=408, random_state=123)

test_ibs:  0.206

In [90]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [91]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [92]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:58:26,868] A new study created in memory with name: no-name-9a32973d-e195-4471-a6f4-ed8e972ebd65

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:27,792] Trial 0 finished with value: 0.7745879261443795 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:30,316] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:35,102] Trial 2 finished with value: 0.74921582480056 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:58:35,321] Trial 3 finished with value: 0.7668106824003204 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:36,324] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:37,383] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:38,008] Trial 6 finished with value: 0.7664150659615537 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:39,435] Trial 7 finished with value: 0.7616331450082747 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:39,561] Trial 8 finished with value: 0.7593018606857644 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7120535714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:42,629] Trial 9 finished with value: 0.7490908660462516 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:43,710] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6737089201877934
[I 2024-04-14 12:58:43,963] Trial 11 finished with value: 0.7734410842409543 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13639294401318086}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6941964285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:44,059] Trial 12 finished with value: 0.721690734532196 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 2, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9861268838969514, 'min_weight_fraction_leaf': 0.19160160653003072}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7433035714285714
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:58:44,315] Trial 13 finished with value: 0.7681118362797557 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.09287447212810436}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:44,529] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:45,030] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.38518225566002634}. Best is trial 0 with value: 0.7745879261443795.

Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:45,399] Trial 16 finished with value: 0.7829471027296476 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8988170687511211, 'min_weight_fraction_leaf': 0.1144909881867055}. Best is trial 16 with value: 0.7829471027296476.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:58:45,885] Trial 17 finished with value: 0.7903075269233125 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8640754037508087, 'min_weight_fraction_leaf': 0.07031499130910734}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:58:47,917] Trial 18 finished with value: 0.7395348597144817 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 257, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8895071108037167, 'min_weight_fraction_leaf': 0.0011589181071390564}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:58:48,294] Trial 19 finished with value: 0.7598333453018479 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.41695365388974803, 'min_weight_fraction_leaf': 0.18034377200013021}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:48,902] Trial 20 finished with value: 0.7807674841440166 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6674617762374991, 'min_weight_fraction_leaf': 0.07545444842690581}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:49,451] Trial 21 finished with value: 0.7776727023732231 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.05962726046385198}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:50,011] Trial 22 finished with value: 0.7830784757621748 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 199, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8771608646297815, 'min_weight_fraction_leaf': 0.10225905155944082}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:50,418] Trial 23 finished with value: 0.7851496206758364 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8802210933826596, 'min_weight_fraction_leaf': 0.11513537121280795}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:58:50,758] Trial 24 finished with value: 0.8035361410322084 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 178, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8280973992230685, 'min_weight_fraction_leaf': 0.039544913909338314}. Best is trial 24 with value: 0.8035361410322084.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:58:51,093] Trial 25 finished with value: 0.8076326900231233 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 164, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7316226562435669, 'min_weight_fraction_leaf': 0.033937366778186574}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:58:52,324] Trial 26 finished with value: 0.7518596934957065 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 154, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7208034772056066, 'min_weight_fraction_leaf': 0.029644882569539167}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 12:58:52,502] Trial 27 finished with value: 0.7603700938794618 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 84, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.030014352957988627}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:58:52,782] Trial 28 finished with value: 0.7636235600497999 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 166, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6118099528026927, 'min_weight_fraction_leaf': 0.15653961257940716}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:58:53,384] Trial 29 finished with value: 0.7613503804818579 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7417740935442027, 'min_weight_fraction_leaf': 0.21971840542663756}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:58:53,600] Trial 30 finished with value: 0.7585961222444212 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 60, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8287064817805315, 'min_weight_fraction_leaf': 0.2917886569515737}. Best is trial 25 with value: 0.8076326900231233.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:54,064] Trial 31 finished with value: 0.789727434191557 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9117101001226512, 'min_weight_fraction_leaf': 0.07589392630375186}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:54,648] Trial 32 finished with value: 0.7998784511940888 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9461941300895063, 'min_weight_fraction_leaf': 0.059917450695551475}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:58:55,158] Trial 33 finished with value: 0.8277557904796954 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9253318298362483, 'min_weight_fraction_leaf': 0.03545814398460863}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 12:58:55,507] Trial 34 finished with value: 0.8207865463159607 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9492142992192825, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:56,160] Trial 35 finished with value: 0.7965082826433545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 171, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7408527707592886, 'min_weight_fraction_leaf': 0.027557073332567256}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:56,981] Trial 36 finished with value: 0.7524488383742287 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 118, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9405179069693569, 'min_weight_fraction_leaf': 0.007687894074078279}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:57,386] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 191, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4720019534455855, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:57,674] Trial 38 finished with value: 0.7928763753349765 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8312601725260211, 'min_weight_fraction_leaf': 0.04442416941679308}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:58:59,127] Trial 39 finished with value: 0.7439658383126666 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 172, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9887286618847455, 'min_weight_fraction_leaf': 0.3676238651442645}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:59,894] Trial 40 finished with value: 0.7645366793940384 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.530081714362, 'min_weight_fraction_leaf': 0.08564159788365241}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:59:00,348] Trial 41 finished with value: 0.7975503824522079 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9630979224273323, 'min_weight_fraction_leaf': 0.05753755330386147}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:59:00,785] Trial 42 finished with value: 0.8197059316116923 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.936335968839529, 'min_weight_fraction_leaf': 0.0196273766061303}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 12:59:01,138] Trial 43 finished with value: 0.8065119240454575 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7820142238093898, 'min_weight_fraction_leaf': 0.01502244059442382}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7857142857142857
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:59:01,595] Trial 44 finished with value: 0.7843530124654604 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9277478422411788, 'min_weight_fraction_leaf': 0.01862377405598601}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:59:02,174] Trial 45 finished with value: 0.8071680483405862 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7801908997243348, 'min_weight_fraction_leaf': 0.003596095332568664}. Best is trial 33 with value: 0.8277557904796954.

Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:59:02,682] Trial 46 finished with value: 0.7771578201695108 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 296, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3546626066657711, 'min_weight_fraction_leaf': 0.04136165195538784}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:59:03,445] Trial 47 finished with value: 0.7420345847053712 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 106, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6036313637833004, 'min_weight_fraction_leaf': 0.14035378430654144}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:59:04,564] Trial 48 finished with value: 0.7911104360543549 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 325, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9981726809518219, 'min_weight_fraction_leaf': 0.09485011729041189}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7183098591549296
[I 2024-04-14 12:59:05,129] Trial 49 finished with value: 0.8145687781668691 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8520528511725862, 'min_weight_fraction_leaf': 0.005130204491028089}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:59:05,812] Trial 50 finished with value: 0.7598345729400207 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8517006580337982, 'min_weight_fraction_leaf': 0.05367186162265391}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:06,383] Trial 51 finished with value: 0.8082755334665999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7867769730122244, 'min_weight_fraction_leaf': 0.000567877460161197}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 12:59:06,989] Trial 52 finished with value: 0.816489818670138 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6993857292105528, 'min_weight_fraction_leaf': 0.0019627716877025497}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:59:07,594] Trial 53 finished with value: 0.792930487889089 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9018947927380415, 'min_weight_fraction_leaf': 0.0026886780958639556}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:59:08,188] Trial 54 finished with value: 0.801950095221479 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6857415391610537, 'min_weight_fraction_leaf': 0.018807937661752497}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:59:08,817] Trial 55 finished with value: 0.7734562026483229 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8526921799077428, 'min_weight_fraction_leaf': 0.0690156297051535}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:59:09,284] Trial 56 finished with value: 0.7911372233377703 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9287340946056967, 'min_weight_fraction_leaf': 0.048509967258659394}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:59:09,869] Trial 57 finished with value: 0.7628345469373019 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9641242469397642, 'min_weight_fraction_leaf': 0.10495833421992688}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7813852813852814
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:59:10,464] Trial 58 finished with value: 0.7742217809667181 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 264, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8013305653217244, 'min_weight_fraction_leaf': 0.08339466927336016}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:59:12,907] Trial 59 finished with value: 0.762559424611025 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7639334102320097, 'min_weight_fraction_leaf': 5.2123975336132444e-05}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:59:13,369] Trial 60 finished with value: 0.7524260845766856 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6968556353741848, 'min_weight_fraction_leaf': 0.1227005732829336}. Best is trial 33 with value: 0.8277557904796954.

Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:59:13,757] Trial 61 finished with value: 0.7927460479159167 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6192920945584268, 'min_weight_fraction_leaf': 0.028331502848269144}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:59:14,174] Trial 62 finished with value: 0.7901297749038513 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8587851429043888, 'min_weight_fraction_leaf': 0.03786024116571255}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:59:14,740] Trial 63 finished with value: 0.8018215874819757 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 195, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.902572914251135, 'min_weight_fraction_leaf': 0.02139829571380404}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:59:15,496] Trial 64 finished with value: 0.7619425976479832 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7397571765612656, 'min_weight_fraction_leaf': 0.06699693366368531}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:59:16,045] Trial 65 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8152768766632212, 'min_weight_fraction_leaf': 0.4134291052499814}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:59:16,409] Trial 66 finished with value: 0.7476285289355211 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 148, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9671004949877344, 'min_weight_fraction_leaf': 0.2772702088742331}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7943722943722944
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:59:16,902] Trial 67 finished with value: 0.7912429906159129 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7124789245232053, 'min_weight_fraction_leaf': 0.0397223511048666}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 12:59:17,654] Trial 68 finished with value: 0.8339253020775889 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7655598056446573, 'min_weight_fraction_leaf': 0.024444075764824668}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:59:18,489] Trial 69 finished with value: 0.814775589444517 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8785074378527057, 'min_weight_fraction_leaf': 0.01463438422425671}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:59:22,639] Trial 70 finished with value: 0.7525231438950724 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8806838182536976, 'min_weight_fraction_leaf': 0.05390111103124775}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:59:23,384] Trial 71 finished with value: 0.8174760798823492 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9147835512625551, 'min_weight_fraction_leaf': 0.021711085638457594}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:59:24,308] Trial 72 finished with value: 0.8249346090078683 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9341419337500907, 'min_weight_fraction_leaf': 0.017715787168804925}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 12:59:25,070] Trial 73 finished with value: 0.8155618578571318 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 419, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9206915345316207, 'min_weight_fraction_leaf': 0.0199096151844373}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:59:25,801] Trial 74 finished with value: 0.7956937290386422 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9223690642871444, 'min_weight_fraction_leaf': 0.027323163950626075}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:59:26,658] Trial 75 finished with value: 0.7933974489324085 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 425, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9633824901969965, 'min_weight_fraction_leaf': 0.07492570501709929}. Best is trial 68 with value: 0.8339253020775889.

Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:59:27,642] Trial 76 finished with value: 0.7865958181681074 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9445741584510846, 'min_weight_fraction_leaf': 0.04529598588507214}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:59:28,376] Trial 77 finished with value: 0.8275693066655989 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 385, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9177495621960954, 'min_weight_fraction_leaf': 0.0175914943830058}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:29,296] Trial 78 finished with value: 0.8039065188872353 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 389, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9999309599975079, 'min_weight_fraction_leaf': 0.06082418990255621}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 12:59:30,234] Trial 79 finished with value: 0.752101204811168 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.15501833559358602}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:59:31,380] Trial 80 finished with value: 0.7898209662315144 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8345492972234845, 'min_weight_fraction_leaf': 0.08687921144727206}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:59:32,323] Trial 81 finished with value: 0.8379466409572306 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9144351157674113, 'min_weight_fraction_leaf': 0.02101412026626872}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:59:33,158] Trial 82 finished with value: 0.8258377049339971 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9018142227663485, 'min_weight_fraction_leaf': 0.030243117812127265}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 12:59:34,085] Trial 83 finished with value: 0.8212887494987298 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8987511549772431, 'min_weight_fraction_leaf': 0.030708676849641337}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:59:35,125] Trial 84 finished with value: 0.815946338015911 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9712348786474978, 'min_weight_fraction_leaf': 0.03859567778983075}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:59:35,884] Trial 85 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 429, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.10698873156508726, 'min_weight_fraction_leaf': 0.20690811169877674}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 12:59:36,734] Trial 86 finished with value: 0.7683500624961893 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.888143001293517, 'min_weight_fraction_leaf': 0.047492110690733655}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:59:40,833] Trial 87 finished with value: 0.7476292753361251 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9811204002381699, 'min_weight_fraction_leaf': 0.015144189829260607}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:41,663] Trial 88 finished with value: 0.8052656989228859 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9375347651581424, 'min_weight_fraction_leaf': 0.06271623214415978}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:59:42,367] Trial 89 finished with value: 0.76219324949789 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 385, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9495185080796891, 'min_weight_fraction_leaf': 0.03327821020686611}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:59:43,057] Trial 90 finished with value: 0.7879114291788776 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8992892522112221, 'min_weight_fraction_leaf': 0.10106275880196715}. Best is trial 81 with value: 0.8379466409572306.

Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:59:43,776] Trial 91 finished with value: 0.8315679050838799 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9106660966863834, 'min_weight_fraction_leaf': 0.02781514243344381}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:59:44,592] Trial 92 finished with value: 0.8432300242257715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8652215671367193, 'min_weight_fraction_leaf': 0.012452248638747002}. Best is trial 92 with value: 0.8432300242257715.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:59:45,341] Trial 93 finished with value: 0.8432300242257715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.866955242071647, 'min_weight_fraction_leaf': 0.010049890541173948}. Best is trial 92 with value: 0.8432300242257715.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:59:46,149] Trial 94 finished with value: 0.8451079584980722 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8716108940255133, 'min_weight_fraction_leaf': 0.011609527241604658}. Best is trial 94 with value: 0.8451079584980722.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:59:46,916] Trial 95 finished with value: 0.8452444687983947 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8660570643802762, 'min_weight_fraction_leaf': 0.0114176313655637}. Best is trial 95 with value: 0.8452444687983947.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:59:47,760] Trial 96 finished with value: 0.8426419289331968 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8346852194839303, 'min_weight_fraction_leaf': 0.011973250765768627}. Best is trial 95 with value: 0.8452444687983947.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:59:48,541] Trial 97 finished with value: 0.8441419350848655 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8065462716711389, 'min_weight_fraction_leaf': 0.011063583331044763}. Best is trial 95 with value: 0.8452444687983947.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:59:49,363] Trial 98 finished with value: 0.8432709969512692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8030550782984262, 'min_weight_fraction_leaf': 0.009969371259572098}. Best is trial 95 with value: 0.8452444687983947.

[I 2024-04-14 12:59:50,129] A new study created in memory with name: no-name-187d0c1d-cdcf-49ef-8da4-f18050e48a4d

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.812206572769953
[I 2024-04-14 12:59:50,114] Trial 99 finished with value: 0.8475275642437399 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7657259832611387, 'min_weight_fraction_leaf': 0.007259167100140962}. Best is trial 99 with value: 0.8475275642437399.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.8475275642437399], datetime_start=datetime.datetime(2024, 4, 14, 12, 59, 49, 372558), datetime_complete=datetime.datetime(2024, 4, 14, 12, 59, 50, 114054), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7657259832611387, 'min_weight_fraction_leaf': 0.007259167100140962}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=99, value=None)


* Best Score for C-index:
 0.8475275642437399

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1634495256547181
Fold 2 IBS: 0.2207215628045014
Fold 3 IBS: 0.16345393335965422
Fold 4 IBS: 0.15807900971573238
Fold 5 IBS: 0.23372859122405484
[I 2024-04-14 12:59:52,518] Trial 0 finished with value: 0.18788652455173221 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 12:59:55,985] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.17758308948531826
Fold 2 IBS: 0.20689085226294357
Fold 3 IBS: 0.1754223431485378
Fold 4 IBS: 0.17751726525948885
Fold 5 IBS: 0.22185249393073614
[I 2024-04-14 12:59:59,062] Trial 2 finished with value: 0.19185320881740492 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.17878695086095409
Fold 2 IBS: 0.20726271618706082
Fold 3 IBS: 0.17784011679731462
Fold 4 IBS: 0.1775723120105269
Fold 5 IBS: 0.22068259102560173
[I 2024-04-14 13:00:00,149] Trial 3 finished with value: 0.19242893737629163 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 13:00:02,865] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 13:00:04,426] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.16370111758710457
Fold 2 IBS: 0.21987223286992366
Fold 3 IBS: 0.16496917801290514
Fold 4 IBS: 0.1588222771800454
Fold 5 IBS: 0.2351001359843554
[I 2024-04-14 13:00:07,210] Trial 6 finished with value: 0.18849298832686684 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.16353665733560305
Fold 2 IBS: 0.2110107862840051
Fold 3 IBS: 0.16686408187867838
Fold 4 IBS: 0.16172494829232667
Fold 5 IBS: 0.2256350896528721
[I 2024-04-14 13:00:09,222] Trial 7 finished with value: 0.18575431268869705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.18076192842718883
Fold 2 IBS: 0.20318073756732816
Fold 3 IBS: 0.17583427747236266
Fold 4 IBS: 0.1782527958014281
Fold 5 IBS: 0.22087176188525123
[I 2024-04-14 13:00:09,597] Trial 8 finished with value: 0.1917803002307118 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.18664290949595258
Fold 2 IBS: 0.2082110927214874
Fold 3 IBS: 0.1837409529358456
Fold 4 IBS: 0.19671407957723833
Fold 5 IBS: 0.21620854529635383
[I 2024-04-14 13:00:13,110] Trial 9 finished with value: 0.19830351600537555 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.2139976337400846
Fold 2 IBS: 0.22078850566211056
Fold 3 IBS: 0.20468678510920732
Fold 4 IBS: 0.2246562137512858
Fold 5 IBS: 0.21763185598455237
[I 2024-04-14 13:00:14,104] Trial 10 finished with value: 0.21635219884944812 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 98, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.21752764504502275, 'min_weight_fraction_leaf': 0.20722772178871404}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1616297345532555
Fold 2 IBS: 0.22477157982658855
Fold 3 IBS: 0.1628591795670332
Fold 4 IBS: 0.15347907270492941
Fold 5 IBS: 0.23632329428819998
[I 2024-04-14 13:00:16,365] Trial 11 finished with value: 0.18781257218800135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9798332536002032, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1598451980902628
Fold 2 IBS: 0.22567451798648389
Fold 3 IBS: 0.1613372135816081
Fold 4 IBS: 0.1527503434788428
Fold 5 IBS: 0.23634129086119499
[I 2024-04-14 13:00:18,686] Trial 12 finished with value: 0.18718971279967853 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 325, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9918679953533508, 'min_weight_fraction_leaf': 0.0011000669636376317}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16467084723870426
Fold 2 IBS: 0.2176412981294037
Fold 3 IBS: 0.16837867720229477
Fold 4 IBS: 0.1659362482405388
Fold 5 IBS: 0.23013568014439548
[I 2024-04-14 13:00:20,398] Trial 13 finished with value: 0.1893525501910674 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 230, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9797860832276054, 'min_weight_fraction_leaf': 0.16922765932800388}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1584759165156057
Fold 2 IBS: 0.22632609949403584
Fold 3 IBS: 0.16096919429847978
Fold 4 IBS: 0.14975247791796673
Fold 5 IBS: 0.2381029557244808
[I 2024-04-14 13:00:22,960] Trial 14 finished with value: 0.18672532879011378 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 353, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9137196108207343, 'min_weight_fraction_leaf': 0.060153931854044475}. Best is trial 7 with value: 0.18575431268869705.

Fold 1 IBS: 0.17001829960754553
Fold 2 IBS: 0.21114960801375182
Fold 3 IBS: 0.1680714029134848
Fold 4 IBS: 0.16577229376912112
Fold 5 IBS: 0.22377735237388288
[I 2024-04-14 13:00:25,737] Trial 15 finished with value: 0.1877577913355572 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 383, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8889618006305522, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.21400217070766633
Fold 2 IBS: 0.22100539917942766
Fold 3 IBS: 0.20500880185904657
Fold 4 IBS: 0.22489607038963122
Fold 5 IBS: 0.21842771716193188
[I 2024-04-14 13:00:27,543] Trial 16 finished with value: 0.21666803185954073 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 249, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.34623136307464575, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1714610200768086
Fold 2 IBS: 0.2535348499538688
Fold 3 IBS: 0.16708922017863614
Fold 4 IBS: 0.16097218140786684
Fold 5 IBS: 0.24047543618622114
[I 2024-04-14 13:00:28,856] Trial 17 finished with value: 0.1987065415606803 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 172, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.680642613858846, 'min_weight_fraction_leaf': 0.18837169005037474}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.15727222398111593
Fold 2 IBS: 0.22636873507694102
Fold 3 IBS: 0.16085031055264207
Fold 4 IBS: 0.14989663564301253
Fold 5 IBS: 0.2399011989692626
[I 2024-04-14 13:00:32,453] Trial 18 finished with value: 0.18685782084459485 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 278, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.890683333800088, 'min_weight_fraction_leaf': 0.04810695432871126}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.21393422737114717
Fold 2 IBS: 0.22070652500675628
Fold 3 IBS: 0.20517424231033535
Fold 4 IBS: 0.22472266626046555
Fold 5 IBS: 0.21698629200627595
[I 2024-04-14 13:00:35,411] Trial 19 finished with value: 0.21630479059099605 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 378, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.10730942678329708, 'min_weight_fraction_leaf': 0.11946047041251526}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.18672950016710899
Fold 2 IBS: 0.18938332474155176
Fold 3 IBS: 0.17421169595898747
Fold 4 IBS: 0.18793677804530293
Fold 5 IBS: 0.21778991805646736
[I 2024-04-14 13:00:35,578] Trial 20 finished with value: 0.19121024339388368 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 6, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8835873208001659, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.15681298167605615
Fold 2 IBS: 0.2271960747866135
Fold 3 IBS: 0.16070156544785022
Fold 4 IBS: 0.14896763064780782
Fold 5 IBS: 0.23914784020726454
[I 2024-04-14 13:00:38,266] Trial 21 finished with value: 0.18656521855311844 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 289, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8999640553775872, 'min_weight_fraction_leaf': 0.04716588401379651}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1592289985770573
Fold 2 IBS: 0.22391660419829243
Fold 3 IBS: 0.1626503856606286
Fold 4 IBS: 0.15555083464553174
Fold 5 IBS: 0.23457220531293152
[I 2024-04-14 13:00:41,643] Trial 22 finished with value: 0.18718380567888832 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8795160396221542, 'min_weight_fraction_leaf': 0.05190855638530002}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16448977781499782
Fold 2 IBS: 0.21570259714710632
Fold 3 IBS: 0.16594723348471818
Fold 4 IBS: 0.15991904995512302
Fold 5 IBS: 0.23342393771993838
[I 2024-04-14 13:00:44,171] Trial 23 finished with value: 0.18789651922437672 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 271, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.66555351612603, 'min_weight_fraction_leaf': 0.09969684717552962}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1667895131394715
Fold 2 IBS: 0.2111672239286755
Fold 3 IBS: 0.1673249965925457
Fold 4 IBS: 0.16435567812575633
Fold 5 IBS: 0.22436532479069474
[I 2024-04-14 13:00:46,383] Trial 24 finished with value: 0.18680054731542878 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9309715061102081, 'min_weight_fraction_leaf': 0.03661049811995851}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1646108674306539
Fold 2 IBS: 0.21505911732400712
Fold 3 IBS: 0.16632277504976264
Fold 4 IBS: 0.1639991387811288
Fold 5 IBS: 0.22970868480968595
[I 2024-04-14 13:00:48,144] Trial 25 finished with value: 0.1879401166790477 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 201, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8351422293659327, 'min_weight_fraction_leaf': 0.16172786458443078}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.17182749380843
Fold 2 IBS: 0.24743091699916395
Fold 3 IBS: 0.16832356578798716
Fold 4 IBS: 0.16182773001582368
Fold 5 IBS: 0.23807911639445214
[I 2024-04-14 13:00:51,431] Trial 26 finished with value: 0.19749776460117136 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 357, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.723442048171647, 'min_weight_fraction_leaf': 0.22955083164714912}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16270170377022197
Fold 2 IBS: 0.21885279863174525
Fold 3 IBS: 0.1604747506158197
Fold 4 IBS: 0.15589312229487554
Fold 5 IBS: 0.233984619675705
[I 2024-04-14 13:00:52,408] Trial 27 finished with value: 0.18638139899767348 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 128, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9382216081429866, 'min_weight_fraction_leaf': 0.09432766696317679}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16886841956994145
Fold 2 IBS: 0.21375557337826087
Fold 3 IBS: 0.1714933178886696
Fold 4 IBS: 0.17345862613841123
Fold 5 IBS: 0.22553760527316705
[I 2024-04-14 13:00:53,734] Trial 28 finished with value: 0.19062270844969004 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 134, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8472712874409023, 'min_weight_fraction_leaf': 0.10335375332904807}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16270185532709952
Fold 2 IBS: 0.21994261443718016
Fold 3 IBS: 0.16127647472475745
Fold 4 IBS: 0.1571589664918226
Fold 5 IBS: 0.2328495122786568
[I 2024-04-14 13:00:54,562] Trial 29 finished with value: 0.18678588465190332 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7351436146825867, 'min_weight_fraction_leaf': 0.08929387187435558}. Best is trial 7 with value: 0.18575431268869705.

Fold 1 IBS: 0.16288193492716865
Fold 2 IBS: 0.2145204309047712
Fold 3 IBS: 0.16344681522379592
Fold 4 IBS: 0.1607591766490642
Fold 5 IBS: 0.23285217315239765
[I 2024-04-14 13:00:55,322] Trial 30 finished with value: 0.18689210617143953 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 87, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9504933061433887, 'min_weight_fraction_leaf': 0.1352883886134873}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1522561822367273
Fold 2 IBS: 0.22165813527341477
Fold 3 IBS: 0.15806345503003275
Fold 4 IBS: 0.14643989125013568
Fold 5 IBS: 0.23525263253654355
[I 2024-04-14 13:00:57,109] Trial 31 finished with value: 0.18273405926537079 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9254246685599902, 'min_weight_fraction_leaf': 0.03593211426266471}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.152084228096772
Fold 2 IBS: 0.22338679434727662
Fold 3 IBS: 0.1592399130977972
Fold 4 IBS: 0.14639330672692666
Fold 5 IBS: 0.23427790617525826
[I 2024-04-14 13:00:58,549] Trial 32 finished with value: 0.18307642968880614 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 194, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8345378470592087, 'min_weight_fraction_leaf': 0.035230873471267764}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15380255879912433
Fold 2 IBS: 0.22181666026356436
Fold 3 IBS: 0.15705843385114202
Fold 4 IBS: 0.14721631258548995
Fold 5 IBS: 0.2338932564033125
[I 2024-04-14 13:01:00,142] Trial 33 finished with value: 0.18275744438052663 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 188, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8258297946312451, 'min_weight_fraction_leaf': 0.026110711916289307}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16205520207895716
Fold 2 IBS: 0.21385077584076523
Fold 3 IBS: 0.1706352761032662
Fold 4 IBS: 0.17133887157807096
Fold 5 IBS: 0.22690608447450347
[I 2024-04-14 13:01:01,775] Trial 34 finished with value: 0.1889572420151126 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8278794226549628, 'min_weight_fraction_leaf': 0.025466420115565977}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1522965326564986
Fold 2 IBS: 0.22209122076352877
Fold 3 IBS: 0.15849077495543015
Fold 4 IBS: 0.1458628906600359
Fold 5 IBS: 0.23585540742953134
[I 2024-04-14 13:01:03,652] Trial 35 finished with value: 0.18291936529300495 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 219, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6150980762772024, 'min_weight_fraction_leaf': 0.02487125392124865}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16169475241976686
Fold 2 IBS: 0.2168496018008369
Fold 3 IBS: 0.16242406959288777
Fold 4 IBS: 0.15514556293471984
Fold 5 IBS: 0.23504817437319558
[I 2024-04-14 13:01:05,029] Trial 36 finished with value: 0.18623243222428137 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 157, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6184306005543774, 'min_weight_fraction_leaf': 0.06555595087029042}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.21400195954884413
Fold 2 IBS: 0.22153443838080922
Fold 3 IBS: 0.20488071601118957
Fold 4 IBS: 0.2247084450075908
Fold 5 IBS: 0.21844619763715448
[I 2024-04-14 13:01:06,479] Trial 37 finished with value: 0.21671435131711764 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4657687648677202, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1558201715273734
Fold 2 IBS: 0.21762918288292568
Fold 3 IBS: 0.16186255500360855
Fold 4 IBS: 0.15614141377459878
Fold 5 IBS: 0.23635811168272997
[I 2024-04-14 13:01:08,247] Trial 38 finished with value: 0.18556228697424726 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 224, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.021082336124271187}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16709619511888768
Fold 2 IBS: 0.20717502377437425
Fold 3 IBS: 0.16588698156023982
Fold 4 IBS: 0.15929610941773517
Fold 5 IBS: 0.22970985966686808
[I 2024-04-14 13:01:08,830] Trial 39 finished with value: 0.185832833907621 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5170603136817243, 'min_weight_fraction_leaf': 0.07850341492135832}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15535306786987405
Fold 2 IBS: 0.21968220141827496
Fold 3 IBS: 0.15817361001927507
Fold 4 IBS: 0.1500191949330929
Fold 5 IBS: 0.23811441381413023
[I 2024-04-14 13:01:10,121] Trial 40 finished with value: 0.18426849761092945 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 166, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6193719603364062, 'min_weight_fraction_leaf': 0.026060732225759387}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15525917425921365
Fold 2 IBS: 0.21959565973354
Fold 3 IBS: 0.1579184197036489
Fold 4 IBS: 0.1499338299909122
Fold 5 IBS: 0.238221550884136
[I 2024-04-14 13:01:11,449] Trial 41 finished with value: 0.18418572691429014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 169, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6256149415751115, 'min_weight_fraction_leaf': 0.02449027643146977}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15078559029270888
Fold 2 IBS: 0.22274109803457892
Fold 3 IBS: 0.1585513727674162
Fold 4 IBS: 0.14641316263224702
Fold 5 IBS: 0.23535565723438484
[I 2024-04-14 13:01:13,065] Trial 42 finished with value: 0.18276937619226716 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 213, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7203447396327514, 'min_weight_fraction_leaf': 0.0015088944882710696}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.17374544997287594
Fold 2 IBS: 0.2061968924844769
Fold 3 IBS: 0.17281750596449846
Fold 4 IBS: 0.18307213900280708
Fold 5 IBS: 0.21711811614435095
[I 2024-04-14 13:01:14,692] Trial 43 finished with value: 0.19059002071380185 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 218, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7447038358575387, 'min_weight_fraction_leaf': 0.27764552944355786}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16406093006581368
Fold 2 IBS: 0.21499120889996837
Fold 3 IBS: 0.16536711596153658
Fold 4 IBS: 0.16197817418246774
Fold 5 IBS: 0.23133183232652665
[I 2024-04-14 13:01:16,537] Trial 44 finished with value: 0.1875458522872626 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 251, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.704529879921064, 'min_weight_fraction_leaf': 0.11873435420263456}. Best is trial 31 with value: 0.18273405926537079.

Fold 1 IBS: 0.154877427493089
Fold 2 IBS: 0.2119381972371029
Fold 3 IBS: 0.16230571380133155
Fold 4 IBS: 0.15585982768129883
Fold 5 IBS: 0.23020111518690609
[I 2024-04-14 13:01:17,613] Trial 45 finished with value: 0.18303645627994566 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 139, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7784599232837964, 'min_weight_fraction_leaf': 0.0038388411371728937}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1807341100446867
Fold 2 IBS: 0.20797545001135234
Fold 3 IBS: 0.17776524098244717
Fold 4 IBS: 0.18082034578648548
Fold 5 IBS: 0.22062001984045795
[I 2024-04-14 13:01:18,767] Trial 46 finished with value: 0.19358303333308596 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 138, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7835655363480928, 'min_weight_fraction_leaf': 0.012753322482536189}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.17357198284816136
Fold 2 IBS: 0.2076463796451187
Fold 3 IBS: 0.17165012622183687
Fold 4 IBS: 0.17167595706828814
Fold 5 IBS: 0.22234280598800027
[I 2024-04-14 13:01:22,331] Trial 47 finished with value: 0.18937745035428108 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5769040196663563, 'min_weight_fraction_leaf': 0.06629554430454714}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1776031563236035
Fold 2 IBS: 0.20715044966565485
Fold 3 IBS: 0.1741935756429268
Fold 4 IBS: 0.17625883720668134
Fold 5 IBS: 0.22185225847744403
[I 2024-04-14 13:01:23,908] Trial 48 finished with value: 0.1914116554632621 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7889727038638424, 'min_weight_fraction_leaf': 0.0024058613061327646}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.2140273796553489
Fold 2 IBS: 0.22164355262784735
Fold 3 IBS: 0.20485005087992433
Fold 4 IBS: 0.22478667236309535
Fold 5 IBS: 0.2185719225359654
[I 2024-04-14 13:01:25,433] Trial 49 finished with value: 0.21677591561243625 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 183, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.691739557624784, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15548669193123835
Fold 2 IBS: 0.21990220358017945
Fold 3 IBS: 0.16360047479288634
Fold 4 IBS: 0.1563346755585229
Fold 5 IBS: 0.23717706454740067
[I 2024-04-14 13:01:26,182] Trial 50 finished with value: 0.18650022208204553 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 90, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7668034916331786, 'min_weight_fraction_leaf': 0.003320042867536673}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15627339813164665
Fold 2 IBS: 0.22498174666133097
Fold 3 IBS: 0.16220735085232846
Fold 4 IBS: 0.14912647182487654
Fold 5 IBS: 0.2376450410667353
[I 2024-04-14 13:01:27,599] Trial 51 finished with value: 0.18604680170738358 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 144, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8252061287283556, 'min_weight_fraction_leaf': 0.04949342957471389}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15659883389607573
Fold 2 IBS: 0.22047290642541456
Fold 3 IBS: 0.1630699661650437
Fold 4 IBS: 0.15695721562566778
Fold 5 IBS: 0.23229697140734873
[I 2024-04-14 13:01:29,451] Trial 52 finished with value: 0.18587917870391008 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 241, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8037463915769376, 'min_weight_fraction_leaf': 0.03358842069468584}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16374041515527638
Fold 2 IBS: 0.2194256628341777
Fold 3 IBS: 0.16253411822788286
Fold 4 IBS: 0.15761805594663011
Fold 5 IBS: 0.23407720659165393
[I 2024-04-14 13:01:31,526] Trial 53 finished with value: 0.1874790917511242 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 186, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7476134901339011, 'min_weight_fraction_leaf': 0.08146609479604885}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15667446587656828
Fold 2 IBS: 0.22259170068516151
Fold 3 IBS: 0.16027821329780895
Fold 4 IBS: 0.149898570567792
Fold 5 IBS: 0.23658634721466398
[I 2024-04-14 13:01:33,619] Trial 54 finished with value: 0.18520585952839894 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 210, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8622593333790171, 'min_weight_fraction_leaf': 0.03984454525206663}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16327473957676134
Fold 2 IBS: 0.23793741115902334
Fold 3 IBS: 0.15053184132363184
Fold 4 IBS: 0.14316701516036756
Fold 5 IBS: 0.24831073015833066
[I 2024-04-14 13:01:34,658] Trial 55 finished with value: 0.18864434747562292 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 114, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5835542910574787, 'min_weight_fraction_leaf': 0.05960637598557158}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15801374020627632
Fold 2 IBS: 0.22263594010741847
Fold 3 IBS: 0.1601823126838589
Fold 4 IBS: 0.14861579443004172
Fold 5 IBS: 0.23891130968989982
[I 2024-04-14 13:01:36,948] Trial 56 finished with value: 0.18567181942349903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 305, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6487362571584319, 'min_weight_fraction_leaf': 0.01779271930046888}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.17721006055316293
Fold 2 IBS: 0.20739633530595358
Fold 3 IBS: 0.1750934765714907
Fold 4 IBS: 0.17633166264985042
Fold 5 IBS: 0.22245946466694386
[I 2024-04-14 13:01:38,935] Trial 57 finished with value: 0.1916981999494803 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 262, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7062791073111182, 'min_weight_fraction_leaf': 0.10871806767374792}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16847265453919935
Fold 2 IBS: 0.2137302894041514
Fold 3 IBS: 0.17041856076770165
Fold 4 IBS: 0.16994282276424133
Fold 5 IBS: 0.22561414584176495
[I 2024-04-14 13:01:40,161] Trial 58 finished with value: 0.18963569466341174 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 154, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.1414379463860349}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1520987816995429
Fold 2 IBS: 0.22538594222039326
Fold 3 IBS: 0.15848369927445602
Fold 4 IBS: 0.14522784389823484
Fold 5 IBS: 0.2376527406797429
[I 2024-04-14 13:01:41,692] Trial 59 finished with value: 0.18376980155447398 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 177, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8101006803604213, 'min_weight_fraction_leaf': 5.7497736778936576e-05}. Best is trial 31 with value: 0.18273405926537079.

Fold 1 IBS: 0.1667377112785077
Fold 2 IBS: 0.21139971336963634
Fold 3 IBS: 0.16719610422116873
Fold 4 IBS: 0.16444742789928804
Fold 5 IBS: 0.22433929414894066
[I 2024-04-14 13:01:43,336] Trial 60 finished with value: 0.18682405018350828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 233, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9208992051748564, 'min_weight_fraction_leaf': 0.04194475489343627}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15339272842252286
Fold 2 IBS: 0.22875929926363106
Fold 3 IBS: 0.15824814328892167
Fold 4 IBS: 0.14551047397439773
Fold 5 IBS: 0.23751514003516505
[I 2024-04-14 13:01:44,750] Trial 61 finished with value: 0.1846851569969277 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 182, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8077284317253199, 'min_weight_fraction_leaf': 0.0006022708509563421}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1531401068257667
Fold 2 IBS: 0.22284906609817628
Fold 3 IBS: 0.15962162064637261
Fold 4 IBS: 0.14675610783249
Fold 5 IBS: 0.23583191058017725
[I 2024-04-14 13:01:46,498] Trial 62 finished with value: 0.18363976239659657 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 203, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8625178350822468, 'min_weight_fraction_leaf': 0.01696754675050992}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1610834021733162
Fold 2 IBS: 0.22086338525240415
Fold 3 IBS: 0.16236228725378696
Fold 4 IBS: 0.1515522563818741
Fold 5 IBS: 0.23680568002031074
[I 2024-04-14 13:01:48,005] Trial 63 finished with value: 0.18653340221633843 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 207, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8622451667885025, 'min_weight_fraction_leaf': 0.06810442573344055}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15409680839983858
Fold 2 IBS: 0.2246057860471813
Fold 3 IBS: 0.15853349670725211
Fold 4 IBS: 0.14772663167931482
Fold 5 IBS: 0.23906549765623225
[I 2024-04-14 13:01:50,155] Trial 64 finished with value: 0.18480564409796382 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 286, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9774551144004276, 'min_weight_fraction_leaf': 0.032811899933904855}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15876817257161227
Fold 2 IBS: 0.2337194086132522
Fold 3 IBS: 0.15156379070347947
Fold 4 IBS: 0.1436732108857659
Fold 5 IBS: 0.24518317596592573
[I 2024-04-14 13:01:52,146] Trial 65 finished with value: 0.1865815517480071 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 254, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9556644596936762, 'min_weight_fraction_leaf': 0.04883609768643495}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15479653570424312
Fold 2 IBS: 0.22540014506157335
Fold 3 IBS: 0.15728703741772068
Fold 4 IBS: 0.14646377091078305
Fold 5 IBS: 0.23433900686523373
[I 2024-04-14 13:01:53,894] Trial 66 finished with value: 0.18365729919191082 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 228, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9061006292109164, 'min_weight_fraction_leaf': 0.01908254070151858}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1726183642606273
Fold 2 IBS: 0.21020146818228028
Fold 3 IBS: 0.17257201371972314
Fold 4 IBS: 0.16617980308164432
Fold 5 IBS: 0.22155798482236494
[I 2024-04-14 13:01:54,803] Trial 67 finished with value: 0.188625926813328 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7664140967912066, 'min_weight_fraction_leaf': 0.07799415348547353}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15906353773281454
Fold 2 IBS: 0.22118269249527334
Fold 3 IBS: 0.16077385786347104
Fold 4 IBS: 0.15116824719229166
Fold 5 IBS: 0.23645145511246304
[I 2024-04-14 13:01:56,336] Trial 68 finished with value: 0.18572795807926273 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8429328898653983, 'min_weight_fraction_leaf': 0.06106194405494651}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15312391663953767
Fold 2 IBS: 0.22710307424261464
Fold 3 IBS: 0.15977752814265386
Fold 4 IBS: 0.14492224287947064
Fold 5 IBS: 0.23636375415289873
[I 2024-04-14 13:01:57,635] Trial 69 finished with value: 0.18425810321143513 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 157, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8699683499475267, 'min_weight_fraction_leaf': 0.014982379758998384}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1698912280155125
Fold 2 IBS: 0.21328832848113072
Fold 3 IBS: 0.1718396678417333
Fold 4 IBS: 0.17209395401833588
Fold 5 IBS: 0.22630147205526466
[I 2024-04-14 13:01:59,428] Trial 70 finished with value: 0.1906829300823954 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 219, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6441662068912183, 'min_weight_fraction_leaf': 0.034967060084702115}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15429001961275463
Fold 2 IBS: 0.22596034800169917
Fold 3 IBS: 0.15684431253808698
Fold 4 IBS: 0.14640686810147274
Fold 5 IBS: 0.23498409076302662
[I 2024-04-14 13:02:01,199] Trial 71 finished with value: 0.18369712780340802 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9109992173441673, 'min_weight_fraction_leaf': 0.017379344628651688}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15721123499115444
Fold 2 IBS: 0.22420625053604556
Fold 3 IBS: 0.1609330693357165
Fold 4 IBS: 0.14884076327365278
Fold 5 IBS: 0.23831241859402336
[I 2024-04-14 13:02:03,243] Trial 72 finished with value: 0.18590074734611856 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 271, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8855407360417882, 'min_weight_fraction_leaf': 0.051245242416170705}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15277218005266113
Fold 2 IBS: 0.2240665791099297
Fold 3 IBS: 0.15811031095474104
Fold 4 IBS: 0.14680663239264824
Fold 5 IBS: 0.23265508413820515
[I 2024-04-14 13:02:04,862] Trial 73 finished with value: 0.18288215732963703 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9973771850648571, 'min_weight_fraction_leaf': 0.018555322731373097}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16297491172262576
Fold 2 IBS: 0.22062900217624173
Fold 3 IBS: 0.16274476161358134
Fold 4 IBS: 0.15453446188660103
Fold 5 IBS: 0.23396466160210022
[I 2024-04-14 13:02:06,499] Trial 74 finished with value: 0.18696955980023003 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9957605480055599, 'min_weight_fraction_leaf': 0.09026272413315149}. Best is trial 31 with value: 0.18273405926537079.

Fold 1 IBS: 0.15528894958073775
Fold 2 IBS: 0.21984680247745453
Fold 3 IBS: 0.15900685739714732
Fold 4 IBS: 0.14859781459794244
Fold 5 IBS: 0.23493449886479167
[I 2024-04-14 13:02:08,119] Trial 75 finished with value: 0.18353498458361475 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 162, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9532062735167633, 'min_weight_fraction_leaf': 0.030316433196080697}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1635808951920651
Fold 2 IBS: 0.20759879371938625
Fold 3 IBS: 0.16635458220500324
Fold 4 IBS: 0.1603635273963648
Fold 5 IBS: 0.2261410117149779
[I 2024-04-14 13:02:09,467] Trial 76 finished with value: 0.18480776204555946 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 128, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9660526429770501, 'min_weight_fraction_leaf': 0.0368089845979563}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.158751943435866
Fold 2 IBS: 0.22270261737826613
Fold 3 IBS: 0.1599837271324172
Fold 4 IBS: 0.15154393792606322
Fold 5 IBS: 0.2359564987679915
[I 2024-04-14 13:02:11,160] Trial 77 finished with value: 0.18578774492812083 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 161, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9584440636641491, 'min_weight_fraction_leaf': 0.05854659326851727}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1778233184873607
Fold 2 IBS: 0.2087412211571078
Fold 3 IBS: 0.17584802592926493
Fold 4 IBS: 0.17838177300207506
Fold 5 IBS: 0.22167925055265206
[I 2024-04-14 13:02:12,590] Trial 78 finished with value: 0.1924947178256921 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 142, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9995542851198572, 'min_weight_fraction_leaf': 0.1606840994476136}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16510953096154146
Fold 2 IBS: 0.2159639911025736
Fold 3 IBS: 0.16350160380457593
Fold 4 IBS: 0.16258843264187522
Fold 5 IBS: 0.22782948351147597
[I 2024-04-14 13:02:14,226] Trial 79 finished with value: 0.18699860840440846 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 173, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.074977184471631}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1512442018000724
Fold 2 IBS: 0.21632787605364548
Fold 3 IBS: 0.15935480265871577
Fold 4 IBS: 0.14734065466186042
Fold 5 IBS: 0.23740446748885152
[I 2024-04-14 13:02:14,933] Trial 80 finished with value: 0.18233440053262912 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 54, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9404771836526359, 'min_weight_fraction_leaf': 0.028434588483853534}. Best is trial 80 with value: 0.18233440053262912.
Fold 1 IBS: 0.15814675249772703
Fold 2 IBS: 0.20623206140937875
Fold 3 IBS: 0.15264146144969137
Fold 4 IBS: 0.1478349558608874
Fold 5 IBS: 0.237417758357945
[I 2024-04-14 13:02:15,364] Trial 81 finished with value: 0.1804545979151259 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9277129016361768, 'min_weight_fraction_leaf': 0.026154087319717897}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.17306642243599527
Fold 2 IBS: 0.20774766683862186
Fold 3 IBS: 0.15278129851922917
Fold 4 IBS: 0.14517727608090308
Fold 5 IBS: 0.23467651295982736
[I 2024-04-14 13:02:15,611] Trial 82 finished with value: 0.18268983536691535 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 8, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9333539319914951, 'min_weight_fraction_leaf': 0.009939968541497122}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.18889776607631728
Fold 2 IBS: 0.20425961405428697
Fold 3 IBS: 0.18068709507786104
Fold 4 IBS: 0.1575612464070665
Fold 5 IBS: 0.2988849748340575
[I 2024-04-14 13:02:15,792] Trial 83 finished with value: 0.20605813928991784 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 1, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.934514818741637, 'min_weight_fraction_leaf': 0.00812664677099249}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.20908231309181677
Fold 2 IBS: 0.21608557742548307
Fold 3 IBS: 0.20454948491486202
Fold 4 IBS: 0.22134543931687387
Fold 5 IBS: 0.21740554176549653
[I 2024-04-14 13:02:16,096] Trial 84 finished with value: 0.21369367130290645 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 17, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9006247216886643, 'min_weight_fraction_leaf': 0.4361528058995905}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16494947752218342
Fold 2 IBS: 0.2122691619956505
Fold 3 IBS: 0.16945255650930177
Fold 4 IBS: 0.16912977245388428
Fold 5 IBS: 0.22786981847875684
[I 2024-04-14 13:02:16,669] Trial 85 finished with value: 0.18873415739195537 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 46, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9330414647675185, 'min_weight_fraction_leaf': 0.19956019852118093}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15434181648270756
Fold 2 IBS: 0.21167748367587746
Fold 3 IBS: 0.15913412492995563
Fold 4 IBS: 0.14963242372193358
Fold 5 IBS: 0.23398242314303047
[I 2024-04-14 13:02:17,167] Trial 86 finished with value: 0.18175365439070096 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 35, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9775574041795743, 'min_weight_fraction_leaf': 0.025436198783908143}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15755954419068613
Fold 2 IBS: 0.20459180020629983
Fold 3 IBS: 0.15861950523187016
Fold 4 IBS: 0.15057932275187044
Fold 5 IBS: 0.23753856534808457
[I 2024-04-14 13:02:17,624] Trial 87 finished with value: 0.18177774754576223 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9857208572979869, 'min_weight_fraction_leaf': 0.047412450094911254}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.1713190051621762
Fold 2 IBS: 0.20663814704028693
Fold 3 IBS: 0.1719571649593095
Fold 4 IBS: 0.17201855450568557
Fold 5 IBS: 0.22773034399499317
[I 2024-04-14 13:02:18,018] Trial 88 finished with value: 0.18993264313249028 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 26, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9755600293092102, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15551362179043182
Fold 2 IBS: 0.21678382942929414
Fold 3 IBS: 0.15983542734498854
Fold 4 IBS: 0.1516385605702977
Fold 5 IBS: 0.2377747929425704
[I 2024-04-14 13:02:18,833] Trial 89 finished with value: 0.18430924641551652 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 72, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.93970419245073, 'min_weight_fraction_leaf': 0.05032187607137201}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.1753851382435368

Fold 2 IBS: 0.2063565222747697
Fold 3 IBS: 0.17003588715814522
Fold 4 IBS: 0.17777116278712887
Fold 5 IBS: 0.22022528125047466
[I 2024-04-14 13:02:19,318] Trial 90 finished with value: 0.18995479834281107 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 37, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9997596356740963, 'min_weight_fraction_leaf': 0.3292134206382089}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15458861367684845
Fold 2 IBS: 0.21750786042177303
Fold 3 IBS: 0.15767300132028467
Fold 4 IBS: 0.15084191777051614
Fold 5 IBS: 0.23638504482176886
[I 2024-04-14 13:02:20,044] Trial 91 finished with value: 0.18339928760223825 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.916420719730876, 'min_weight_fraction_leaf': 0.026018345165367416}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16926244801703716
Fold 2 IBS: 0.2066676766691297
Fold 3 IBS: 0.17008790964473064
Fold 4 IBS: 0.1820524596700145
Fold 5 IBS: 0.22610108366092097
[I 2024-04-14 13:02:20,358] Trial 92 finished with value: 0.19083431553236657 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 17, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.964752731171567, 'min_weight_fraction_leaf': 0.01250391523792243}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15809148003468684
Fold 2 IBS: 0.20958670734958446
Fold 3 IBS: 0.15840991467714924
Fold 4 IBS: 0.1507811899477792
Fold 5 IBS: 0.23549291506179715
[I 2024-04-14 13:02:20,847] Trial 93 finished with value: 0.18247244141419938 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 35, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8884053060973408, 'min_weight_fraction_leaf': 0.041256881684444274}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15797743739508543
Fold 2 IBS: 0.2116993770730125
Fold 3 IBS: 0.161819653131566
Fold 4 IBS: 0.15392702939042302
Fold 5 IBS: 0.23712263715887472
[I 2024-04-14 13:02:21,365] Trial 94 finished with value: 0.18450922682979234 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 36, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8932538311633453, 'min_weight_fraction_leaf': 0.04536309386296798}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16268328889908273
Fold 2 IBS: 0.2137299364042898
Fold 3 IBS: 0.16175964623736974
Fold 4 IBS: 0.15947622173026346
Fold 5 IBS: 0.23382367473762608
[I 2024-04-14 13:02:22,185] Trial 95 finished with value: 0.18629455360172636 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 71, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9798682573522689, 'min_weight_fraction_leaf': 0.08848051751764807}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.1738378029124256
Fold 2 IBS: 0.20291251147912878
Fold 3 IBS: 0.16988018099799151
Fold 4 IBS: 0.17884930227942303
Fold 5 IBS: 0.2279595208667826
[I 2024-04-14 13:02:22,492] Trial 96 finished with value: 0.1906878637071503 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 16, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9286121890215923, 'min_weight_fraction_leaf': 0.07027555068916512}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16334795326480145
Fold 2 IBS: 0.21098948637616388
Fold 3 IBS: 0.16348277314048718
Fold 4 IBS: 0.16036816603309584
Fold 5 IBS: 0.2349696440519836
[I 2024-04-14 13:02:23,069] Trial 97 finished with value: 0.1866316045733064 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 54, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9433581891891712, 'min_weight_fraction_leaf': 0.05578633304726292}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16099953749641463
Fold 2 IBS: 0.20578172388126173
Fold 3 IBS: 0.15926165405907902
Fold 4 IBS: 0.15308207272671334
Fold 5 IBS: 0.23653164161080956
[I 2024-04-14 13:02:23,492] Trial 98 finished with value: 0.18313132595485565 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 31, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8905712013384897, 'min_weight_fraction_leaf': 0.04141197253924776}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15246893987163504
Fold 2 IBS: 0.21792955284744994
Fold 3 IBS: 0.15667467626084478
Fold 4 IBS: 0.1515829511569252
Fold 5 IBS: 0.23629786824582152
[I 2024-04-14 13:02:24,093] Trial 99 finished with value: 0.1829907976765353 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 43, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8472749022928616, 'min_weight_fraction_leaf': 0.02766234914998976}. Best is trial 81 with value: 0.1804545979151259.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.1804545979151259], datetime_start=datetime.datetime(2024, 4, 14, 13, 2, 14, 944243), datetime_complete=datetime.datetime(2024, 4, 14, 13, 2, 15, 364067), params={'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9277129016361768, 'min_weight_fraction_leaf': 0.026154087319717897}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=81, value=None)


* Best Score for IBS:
 0.1804545979151259

In [93]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [94]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.848
train_ibs:  0.18

#### Test

In [95]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [96]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=10, max_features=None, max_leaf_nodes=17,
                   max_samples=0.7657259832611387, min_samples_leaf=1,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.007259167100140962,
                   n_estimators=358, random_state=123, warm_start=True)

C-index score: 0.61

ExtraSurvivalTrees(max_depth=5, max_leaf_nodes=17,
                   max_samples=0.9277129016361768, min_samples_leaf=1,
                   min_samples_split=16,
                   min_weight_fraction_leaf=0.026154087319717897,
                   n_estimators=27, oob_score=True, random_state=123)

IBS: 0.23

In [97]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [98]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 13:02:24,950] A new study created in memory with name: no-name-634d57e3-44db-4212-9920-d8b077810fed

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:39,856] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:47,293] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:54,741] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:06,303] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:10,895] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:12,036] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:25,876] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:30,753] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:31,563] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 13:04:02,384] Trial 9 finished with value: 0.7308620854904466 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 13:21:59,197] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:37:58,419] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 13:54:52,730] Trial 12 finished with value: 0.7099172779859281 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:28:31,503] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:08,794] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:31,460] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:35:26,378] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:05,137] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:53,055] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:54,976] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:37:12,838] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:37:58,592] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 14:38:37,133] Trial 22 finished with value: 0.7242619704042982 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:39:08,979] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:39:38,159] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:39:54,383] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:40:32,175] Trial 26 finished with value: 0.5440329476861168 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:07,896] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:35,580] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:55,576] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:42:22,559] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:43:14,439] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:44:02,584] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:44:37,310] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:45:35,530] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:45:46,384] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:37,138] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:38,317] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:54,539] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:20,967] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:04,016] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 14:48:04,217] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:48:08,927] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:14,455] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:26,178] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:33,172] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:38,429] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:01,629] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:08,861] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:28,483] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:30,141] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:49:30,409] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:30,708] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:49:34,444] Trial 53 finished with value: 0.6986656149072055 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:37,416] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:38,155] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:29,730] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:33,675] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:39,883] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:26,501] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:41,822] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:43,133] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:51:49,653] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:51:50,807] Trial 63 finished with value: 0.7163384910196757 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:52,953] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:56,838] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:46,842] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:47,492] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:58,280] Trial 68 finished with value: 0.6328510949834479 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:59,168] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:36,915] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:53:37,124] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:53:37,456] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:45,732] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:46,053] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:48,625] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:08,131] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:09,105] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:57,207] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:03,609] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:17,910] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 14:55:18,059] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:55:18,311] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:18,890] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:21,057] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:21,453] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:22,587] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:23,575] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:24,717] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:13,120] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:17,156] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:57:17,586] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:18,001] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:18,202] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:18,908] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:57:19,834] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 14:57:22,177] Trial 96 finished with value: 0.7397496129726304 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7397496129726304.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:24,525] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7397496129726304.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:26,700] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7397496129726304.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.7433035714285714

[I 2024-04-14 14:57:26,985] A new study created in memory with name: no-name-7101a72f-6b1b-4dda-9af2-efff2404303d

Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6220657276995305
[I 2024-04-14 14:57:26,962] Trial 99 finished with value: 0.7362621731256239 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7397496129726304.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7397496129726304], datetime_start=datetime.datetime(2024, 4, 14, 14, 57, 19, 868883), datetime_complete=datetime.datetime(2024, 4, 14, 14, 57, 22, 177312), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7397496129726304

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:57:42,100] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:57:49,718] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:57:57,166] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:58:08,781] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:58:13,686] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:58:14,954] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:58:26,952] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:58:30,628] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:58:31,173] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21300086551681388
Fold 2 IBS: 0.22130101345683229
Fold 3 IBS: 0.20356009608364972
Fold 4 IBS: 0.223737338897546
Fold 5 IBS: 0.21796045724591795
[I 2024-04-14 14:59:01,288] Trial 9 finished with value: 0.21591195424015197 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 14:59:48,689] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:00:42,868] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.2138394660896716
Fold 2 IBS: 0.22156451448592526
Fold 3 IBS: 0.20440536466519849
Fold 4 IBS: 0.22459255869133457
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 15:01:28,312] Trial 12 finished with value: 0.21650012607655755 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 15:01:52,361] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:02:30,969] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:03:04,659] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:03:23,233] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:04:07,967] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:04:31,951] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:04:36,422] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:05:22,526] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 15:06:20,578] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21274017409214452
Fold 2 IBS: 0.22141099171063053

Fold 3 IBS: 0.20335117088275953
Fold 4 IBS: 0.22312834911084292
Fold 5 IBS: 0.2179288192033457
[I 2024-04-14 15:07:17,291] Trial 22 finished with value: 0.21571190099994464 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:08:06,193] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:08:40,251] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:09:10,099] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:09:52,183] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:09:56,497] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:10:12,406] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:10:53,797] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:11:10,667] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 15:12:04,268] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.2214475600367709
Fold 3 IBS: 0.20359712028328325
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.2179179888442139
[I 2024-04-14 15:13:03,478] Trial 32 finished with value: 0.21590238864988304 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:13:46,622] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:14:28,347] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:14:40,667] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:15:41,420] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:15:43,125] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:16:08,131] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:16:40,854] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:17:19,355] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.2133737249398968
Fold 2 IBS: 0.22149810300618933
Fold 3 IBS: 0.2039253275544007
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21807108026974395
[I 2024-04-14 15:18:14,685] Trial 41 finished with value: 0.21616520869623862 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21306076700870485
Fold 2 IBS: 0.22147749486211882
Fold 3 IBS: 0.20359741169509465
Fold 4 IBS: 0.2235915022761023
Fold 5 IBS: 0.2179320496417716
[I 2024-04-14 15:19:08,872] Trial 42 finished with value: 0.21593184509675845 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:20:09,158] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:20:51,649] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21364321685567275
Fold 2 IBS: 0.22142448507128704
Fold 3 IBS: 0.20425326961779583
Fold 4 IBS: 0.22431353914927907
Fold 5 IBS: 0.21808668272206289
[I 2024-04-14 15:21:39,520] Trial 45 finished with value: 0.21634423868321956 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:22:20,221] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:22:36,701] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:22:36,999] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:22:45,843] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:23:28,090] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 15:24:14,693] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:25:06,555] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22136281903923083
Fold 3 IBS: 0.20241247448818608
Fold 4 IBS: 0.2219411019366781
Fold 5 IBS: 0.21777624808878387
[I 2024-04-14 15:25:57,274] Trial 53 finished with value: 0.21504716009286912 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:26:35,849] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:27:07,942] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:27:42,167] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:28:27,777] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:29:24,845] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:29:57,766] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:30:26,775] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:31:09,431] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 15:32:01,977] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:32:50,102] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.2129979350841566
Fold 2 IBS: 0.2212280479447545
Fold 3 IBS: 0.20348955609618546
Fold 4 IBS: 0.22374381655427747
Fold 5 IBS: 0.21801501746323726
[I 2024-04-14 15:33:52,540] Trial 64 finished with value: 0.21589487462852225 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:34:54,344] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9189183326723824, 'learning_rate': 0.011096659410828054, 'dropout_rate': 0.15744491147958184, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 1.1124245211667088, 'min_weight_fraction_leaf': 0.21730511044745757, 'max_features': 'log2', 'min_impurity_decrease': 4.00127934674698e-06, 'validation_fraction': 0.998233299727277, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:35:59,995] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9998769156045215, 'learning_rate': 0.008782667792366316, 'dropout_rate': 0.12972298735589705, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.7134499429690735, 'min_weight_fraction_leaf': 0.19311178079767077, 'max_features': 'log2', 'min_impurity_decrease': 1.142816958470248e-06, 'validation_fraction': 0.9729459657934212, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:36:51,016] Trial 67 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8640185330574577, 'learning_rate': 0.015997347081349804, 'dropout_rate': 0.18369926136498038, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.3491418081323188, 'max_features': 'log2', 'min_impurity_decrease': 2.9677822215329938e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:37:38,782] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8052124560044422, 'learning_rate': 0.027698938792055094, 'dropout_rate': 0.3183724976622295, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2920470355270516, 'min_weight_fraction_leaf': 0.16901934601360036, 'max_features': 'log2', 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:38:21,865] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.022661198063658503, 'dropout_rate': 0.15177883474257473, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 5.781491720141274, 'min_weight_fraction_leaf': 0.3709922257167516, 'max_features': 'sqrt', 'min_impurity_decrease': 7.4830347845666965e-06, 'validation_fraction': 0.8281891917990171, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:38:35,910] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.0031189928817958587, 'dropout_rate': 0.5905404972480945, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.3188535514715946, 'max_features': 'log2', 'min_impurity_decrease': 1.1928111158414438e-06, 'validation_fraction': 0.8771634368243094, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21281861880669364
Fold 2 IBS: 0.22147036875244297
Fold 3 IBS: 0.20342132281483385
Fold 4 IBS: 0.223306383872192
Fold 5 IBS: 0.21789594373420879
[I 2024-04-14 15:39:35,791] Trial 71 finished with value: 0.21578252759607425 and parameters: {'subsample': 0.9303280421214478, 'learning_rate': 0.00867928513859834, 'dropout_rate': 0.2114071609099808, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.2830289864785245, 'max_features': 'auto', 'min_impurity_decrease': 2.8309589446706505e-07, 'validation_fraction': 0.9341930519363522, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21264377959603953
Fold 2 IBS: 0.22145456521669551
Fold 3 IBS: 0.20325758942159297
Fold 4 IBS: 0.22308382132272495
Fold 5 IBS: 0.21784549875213116
[I 2024-04-14 15:40:26,936] Trial 72 finished with value: 0.2156570508618368 and parameters: {'subsample': 0.9301573375470014, 'learning_rate': 0.011204053201905661, 'dropout_rate': 0.23553989617782028, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004820830813732985, 'min_weight_fraction_leaf': 0.2737805456341038, 'max_features': 'auto', 'min_impurity_decrease': 3.6620964530112787e-07, 'validation_fraction': 0.9737030143041076, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:40:32,593] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9298981705927085, 'learning_rate': 0.010195438618282406, 'dropout_rate': 0.23585972620145051, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.27451237461517963, 'max_features': 'auto', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9203017882586108, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:41:18,850] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8776896116214433, 'learning_rate': 0.014494378748744683, 'dropout_rate': 0.28898081809802034, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.37345543486587357, 'min_weight_fraction_leaf': 0.20816976567601184, 'max_features': 'auto', 'min_impurity_decrease': 2.611979113511538e-07, 'validation_fraction': 0.9762608022070116, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:41:59,616] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8972316596616344, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.34962098273262876, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 1.2014771498456696, 'min_weight_fraction_leaf': 0.2901314285672209, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.8483032778113153, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:42:48,561] Trial 76 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9427845846760775, 'learning_rate': 0.040991201384238105, 'dropout_rate': 0.2075245331259492, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.934389124127465, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.

Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:43:26,046] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6527746876723795, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.2556920821676466, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.5896250392603071, 'min_weight_fraction_leaf': 0.22988050749684658, 'max_features': 1, 'min_impurity_decrease': 1.4995945809430595e-05, 'validation_fraction': 0.8950354974332698, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:44:15,351] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.1812306278517568, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.2911423302160594, 'min_weight_fraction_leaf': 0.2568526167512072, 'max_features': 'auto', 'min_impurity_decrease': 6.881976645342321e-07, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:44:58,820] Trial 79 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9711804489125221, 'learning_rate': 0.008977463652006058, 'dropout_rate': 0.10045868399742758, 'n_estimators': 408, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8456191926639984, 'min_weight_fraction_leaf': 0.28189763106059557, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982937136983077, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:45:40,105] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8535702305805324, 'learning_rate': 0.013008132772511784, 'dropout_rate': 0.23306750004092583, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 5.501302028342128e-06, 'validation_fraction': 0.8033655207154786, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21328441825357652
Fold 2 IBS: 0.22144767701711832
Fold 3 IBS: 0.2038537340831823
Fold 4 IBS: 0.22389243027837222
Fold 5 IBS: 0.2179733655894191
[I 2024-04-14 15:46:31,527] Trial 81 finished with value: 0.2160903250443337 and parameters: {'subsample': 0.9784145478438975, 'learning_rate': 0.00415560855116564, 'dropout_rate': 0.16880106444935875, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.025432112194026565, 'min_weight_fraction_leaf': 0.32661813483692875, 'max_features': 'auto', 'min_impurity_decrease': 4.1696350773463576e-07, 'validation_fraction': 0.9618626661496192, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21313529710939624
Fold 2 IBS: 0.2214959526155037
Fold 3 IBS: 0.20372727007596517
Fold 4 IBS: 0.2237011172817945
Fold 5 IBS: 0.2179583294148407
[I 2024-04-14 15:47:37,342] Trial 82 finished with value: 0.21600359329950006 and parameters: {'subsample': 0.9292256563323309, 'learning_rate': 0.005938788819943272, 'dropout_rate': 0.20112867357024375, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.01786403260693046, 'min_weight_fraction_leaf': 0.2694686872154886, 'max_features': 'auto', 'min_impurity_decrease': 1.4936787149467238e-07, 'validation_fraction': 0.9322976146952479, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:48:27,408] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.997030710636302, 'learning_rate': 0.017347504146358047, 'dropout_rate': 0.12875284011164154, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.42770746896829764, 'min_weight_fraction_leaf': 0.30582130984370137, 'max_features': 'auto', 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.9763733963887893, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:49:13,518] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9699238743776749, 'learning_rate': 0.009959638401621597, 'dropout_rate': 0.305574256636177, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.262145494050454, 'min_weight_fraction_leaf': 0.23583033266274414, 'max_features': 'auto', 'min_impurity_decrease': 7.781008937605048e-07, 'validation_fraction': 0.8657748182811282, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:49:54,562] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9039638029331271, 'learning_rate': 0.0037679534600800306, 'dropout_rate': 0.15830961459250859, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.9670160633661875, 'min_weight_fraction_leaf': 0.22273143316885707, 'max_features': 'auto', 'min_impurity_decrease': 1.549053164841614e-07, 'validation_fraction': 0.9112741324892579, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:50:41,179] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9330830727147826, 'learning_rate': 0.00786307119428408, 'dropout_rate': 0.2679588154714714, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.6251717679448328, 'min_weight_fraction_leaf': 0.34273533762708086, 'max_features': 'auto', 'min_impurity_decrease': 1.94114481416941e-06, 'validation_fraction': 0.9710286882527703, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:50:50,805] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8202668472614781, 'learning_rate': 0.012273440310927393, 'dropout_rate': 0.49308788025511585, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.2337543925553926, 'min_weight_fraction_leaf': 0.2565004395308679, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00023480828622143336, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:51:18,817] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8800231052433968, 'learning_rate': 0.015424283294721588, 'dropout_rate': 0.20093805843087115, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.351539840282731, 'min_weight_fraction_leaf': 0.28958635214901884, 'max_features': 'auto', 'min_impurity_decrease': 2.329078771156988e-07, 'validation_fraction': 0.939344740485312, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:51:49,189] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9819209167757807, 'learning_rate': 0.020219241696711625, 'dropout_rate': 0.2428130031440519, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.5765552790097783, 'min_weight_fraction_leaf': 0.18311512377308206, 'max_features': 'auto', 'min_impurity_decrease': 5.126619309081385e-07, 'validation_fraction': 0.8909484827188601, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:51:58,757] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6196341847942087, 'learning_rate': 0.006689654877596743, 'dropout_rate': 0.8458602043820649, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.5932807780543458, 'min_weight_fraction_leaf': 0.20408203732171998, 'max_features': None, 'min_impurity_decrease': 0.0012769637169882761, 'validation_fraction': 0.8340062857341481, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21354560132435954
Fold 2 IBS: 0.22152311434279084
Fold 3 IBS: 0.20412434040298866
Fold 4 IBS: 0.22420753466621227
Fold 5 IBS: 0.21802246276346793
[I 2024-04-14 15:52:37,985] Trial 91 finished with value: 0.21628461069996385 and parameters: {'subsample': 0.9519061011910324, 'learning_rate': 0.003286435592844394, 'dropout_rate': 0.21804174357954037, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.037605992845398076, 'min_weight_fraction_leaf': 0.2518132577788482, 'max_features': 'auto', 'min_impurity_decrease': 2.167221721970957e-07, 'validation_fraction': 0.9509830628877887, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21228604216711322
Fold 2 IBS: 0.2210505145073144
Fold 3 IBS: 0.2029838755299775
Fold 4 IBS: 0.22264411729074315
Fold 5 IBS: 0.21786028421349793
[I 2024-04-14 15:53:29,925] Trial 92 finished with value: 0.21536496674172928 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.007580646944168386, 'dropout_rate': 0.1248497169759688, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.04676515809970792, 'min_weight_fraction_leaf': 0.24126121445524454, 'max_features': 'auto', 'min_impurity_decrease': 1.41179952896197e-07, 'validation_fraction': 0.9803593350541797, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:54:26,680] Trial 93 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5074494668833536, 'learning_rate': 0.010358551431621075, 'dropout_rate': 0.11851429853955366, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.386541225183722, 'min_weight_fraction_leaf': 0.28001284523923786, 'max_features': 'auto', 'min_impurity_decrease': 1.2653383309827397e-07, 'validation_fraction': 0.979813726530939, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:55:14,401] Trial 94 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4696467705452906, 'learning_rate': 0.012513597466310221, 'dropout_rate': 0.1368992177740068, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.8568623495412244, 'min_weight_fraction_leaf': 0.3103128063965126, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9107078483961247, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21395579375917034
Fold 2 IBS: 0.22156669674580007
Fold 3 IBS: 0.2045252270179711
Fold 4 IBS: 0.22472200503768064
Fold 5 IBS: 0.21811291772715782
[I 2024-04-14 15:56:17,206] Trial 95 finished with value: 0.216576528057556 and parameters: {'subsample': 0.5795813627066926, 'learning_rate': 0.0011500826880246348, 'dropout_rate': 0.15371309107333708, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.12848433868181566, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 'auto', 'min_impurity_decrease': 2.9339240471384527e-07, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:57:15,663] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5510219457804204, 'learning_rate': 0.017505885682568743, 'dropout_rate': 0.1723932907588553, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5519118282179587, 'min_weight_fraction_leaf': 0.27203175602825513, 'max_features': 'log2', 'min_impurity_decrease': 1.4367172438359607e-07, 'validation_fraction': 0.6783354896202222, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 15:58:14,190] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.529148797369217, 'learning_rate': 0.009070651237536868, 'dropout_rate': 0.22319654132501116, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 1.0614519036494967, 'min_weight_fraction_leaf': 0.14961516639891254, 'max_features': 'auto', 'min_impurity_decrease': 1.3572955342683883e-06, 'validation_fraction': 0.9307441942928913, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:59:36,318] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9166190498458621, 'learning_rate': 0.005876010120169104, 'dropout_rate': 0.1928526990947004, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.2351987698633502, 'min_weight_fraction_leaf': 0.24763944144203606, 'max_features': 1, 'min_impurity_decrease': 3.0003509704748335e-06, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.

Fold 1 IBS: 0.21252354672208404
Fold 2 IBS: 0.22052727078684145
Fold 3 IBS: 0.20320794231873263
Fold 4 IBS: 0.2228335466693306
Fold 5 IBS: 0.21782914318597227
[I 2024-04-14 16:00:27,913] Trial 99 finished with value: 0.21538428993659223 and parameters: {'subsample': 0.24286963781937687, 'learning_rate': 0.01358129947690588, 'dropout_rate': 0.25496540816023416, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.004367160733265784, 'min_weight_fraction_leaf': 0.2624099419664444, 'max_features': 'auto', 'min_impurity_decrease': 5.321953542697131e-07, 'validation_fraction': 0.9620562032012763, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.21504716009286912], datetime_start=datetime.datetime(2024, 4, 14, 15, 25, 6, 566505), datetime_complete=datetime.datetime(2024, 4, 14, 15, 25, 57, 272952), params={'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=53, value=None)


* Best Score for IBS:
 0.21504716009286912

In [99]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [100]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.74
train_ibs:  0.215

#### Test

In [101]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [102]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.612

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009625013743012712,
                                 criterion='squared_error',
                                 dropout_rate=0.1897783294507234,
                                 learning_rate=0.015420772490455037,
                                 max_features='auto', max_leaf_nodes=14,
                                 min_impurity_decrease=5.869825897765074e-07,
                                 min_samples_leaf=13, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29880213170319914,
                                 n_estimators=430, random_state=123,
                                 subsample=0.9101431135071837,
                                 validation_fraction=0.9964423942006735)

IBS: 0.22

In [103]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [104]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [105]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:00:40,064] A new study created in memory with name: no-name-eceb31d0-e282-45c5-8cd5-4b90d8246572

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:00:41,024] Trial 0 finished with value: 0.7099982410993864 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.7099982410993864.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:00:47,475] Trial 1 finished with value: 0.6987518910706959 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.7099982410993864.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:00:48,626] Trial 2 finished with value: 0.7140073447408429 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7140073447408429.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:00:50,527] Trial 3 finished with value: 0.72144622938561 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.72144622938561.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:00:53,072] Trial 4 finished with value: 0.7191576987364744 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.72144622938561.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:00:56,383] Trial 5 finished with value: 0.7071907096360968 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.72144622938561.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:00:57,684] Trial 6 finished with value: 0.6514945071044511 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.72144622938561.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 16:00:57,930] Trial 7 finished with value: 0.7129014222181848 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 3 with value: 0.72144622938561.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:00:59,551] Trial 8 finished with value: 0.715073680366002 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 3 with value: 0.72144622938561.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:01:04,278] Trial 9 finished with value: 0.7132004310662822 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 3 with value: 0.72144622938561.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 16:01:07,367] Trial 10 finished with value: 0.725297635505036 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.10867980814121556, 'n_estimators': 299, 'learning_rate': 0.09279671898160717}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 16:01:10,587] Trial 11 finished with value: 0.725297635505036 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.10580803679784617, 'n_estimators': 318, 'learning_rate': 0.09656492760401554}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 16:01:13,961] Trial 12 finished with value: 0.725297635505036 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.10707761209805167, 'n_estimators': 307, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:01:18,626] Trial 13 finished with value: 0.6945008724814421 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.20866416710667365, 'n_estimators': 377, 'learning_rate': 0.09915584389423529}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:01:23,198] Trial 14 finished with value: 0.6462473378141999 and parameters: {'subsample': 0.8619663815733164, 'dropout_rate': 0.28551472763591135, 'n_estimators': 363, 'learning_rate': 0.0025916531369806137}. Best is trial 10 with value: 0.725297635505036.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:01:26,046] Trial 15 finished with value: 0.7262366026411862 and parameters: {'subsample': 0.8897480564271555, 'dropout_rate': 0.10006460023230275, 'n_estimators': 297, 'learning_rate': 0.08616677729964022}. Best is trial 15 with value: 0.7262366026411862.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:01:30,021] Trial 16 finished with value: 0.736821447083185 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.6816056386540454, 'n_estimators': 427, 'learning_rate': 0.08537615252975696}. Best is trial 16 with value: 0.736821447083185.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:01:34,624] Trial 17 finished with value: 0.7268479131064735 and parameters: {'subsample': 0.17085174271948028, 'dropout_rate': 0.7574099126710454, 'n_estimators': 445, 'learning_rate': 0.08254853879823357}. Best is trial 16 with value: 0.736821447083185.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:01:39,053] Trial 18 finished with value: 0.7312822772506788 and parameters: {'subsample': 0.13920564377019537, 'dropout_rate': 0.7033122086799477, 'n_estimators': 430, 'learning_rate': 0.08262492929485413}. Best is trial 16 with value: 0.736821447083185.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:01:42,766] Trial 19 finished with value: 0.7380039655451153 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9936895487898989, 'n_estimators': 431, 'learning_rate': 0.07862475807967083}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:01:46,275] Trial 20 finished with value: 0.7169203481000173 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.7933084651006226, 'n_estimators': 401, 'learning_rate': 0.06551866052750378}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:01:49,582] Trial 21 finished with value: 0.732660103539625 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.9754161103921428, 'n_estimators': 430, 'learning_rate': 0.08197456727164983}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:01:52,993] Trial 22 finished with value: 0.7380039655451153 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.9876283936024775, 'n_estimators': 421, 'learning_rate': 0.07859249467412184}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:01:57,799] Trial 23 finished with value: 0.7222965446733969 and parameters: {'subsample': 0.22230530170428542, 'dropout_rate': 0.9287077072869183, 'n_estimators': 486, 'learning_rate': 0.07571626486257846}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:01,205] Trial 24 finished with value: 0.7117458703687637 and parameters: {'subsample': 0.362387091270998, 'dropout_rate': 0.9895706751033624, 'n_estimators': 399, 'learning_rate': 0.08999578022953586}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:04,028] Trial 25 finished with value: 0.711920940396775 and parameters: {'subsample': 0.3540902744474155, 'dropout_rate': 0.8380692536452337, 'n_estimators': 339, 'learning_rate': 0.04384746864637883}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:02:09,755] Trial 26 finished with value: 0.7369360383742469 and parameters: {'subsample': 0.10335890957570726, 'dropout_rate': 0.6761897620564178, 'n_estimators': 444, 'learning_rate': 0.06164181207722111}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:02:14,968] Trial 27 finished with value: 0.7259821122406726 and parameters: {'subsample': 0.19715238894533332, 'dropout_rate': 0.6340112818214192, 'n_estimators': 451, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.568075117370892
[I 2024-04-14 16:02:16,958] Trial 28 finished with value: 0.7141524219778836 and parameters: {'subsample': 0.26815029698295934, 'dropout_rate': 0.7757313938259267, 'n_estimators': 257, 'learning_rate': 0.04304880607219153}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:02:17,200] Trial 29 finished with value: 0.7120211629441806 and parameters: {'subsample': 0.2996334106217784, 'dropout_rate': 0.9066495791359706, 'n_estimators': 28, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:02:17,763] Trial 30 finished with value: 0.7281215123044955 and parameters: {'subsample': 0.18969332704524633, 'dropout_rate': 0.5880894405700312, 'n_estimators': 93, 'learning_rate': 0.07566402238578854}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 16:02:21,790] Trial 31 finished with value: 0.7343236762686727 and parameters: {'subsample': 0.11905003223898131, 'dropout_rate': 0.711779334663885, 'n_estimators': 402, 'learning_rate': 0.06874134683487756}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:02:27,595] Trial 32 finished with value: 0.7369360383742469 and parameters: {'subsample': 0.10562961489860558, 'dropout_rate': 0.8291455285739325, 'n_estimators': 494, 'learning_rate': 0.08792546145114796}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:02:32,235] Trial 33 finished with value: 0.7267747468361241 and parameters: {'subsample': 0.16503297687519164, 'dropout_rate': 0.8235186433440982, 'n_estimators': 489, 'learning_rate': 0.07847275491942962}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:02:36,715] Trial 34 finished with value: 0.7214307438075961 and parameters: {'subsample': 0.21925245904357338, 'dropout_rate': 0.9475812542558525, 'n_estimators': 456, 'learning_rate': 0.06793259569505218}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:42,409] Trial 35 finished with value: 0.7127262625256264 and parameters: {'subsample': 0.4103407415711651, 'dropout_rate': 0.9996115905090341, 'n_estimators': 489, 'learning_rate': 0.0722933125675966}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 16:02:47,495] Trial 36 finished with value: 0.7128966475810572 and parameters: {'subsample': 0.30994102215755653, 'dropout_rate': 0.8738874973796504, 'n_estimators': 499, 'learning_rate': 0.08944355500938028}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:02:50,715] Trial 37 finished with value: 0.7118300653783937 and parameters: {'subsample': 0.634990342096257, 'dropout_rate': 0.7358174577846046, 'n_estimators': 381, 'learning_rate': 0.05621431261796065}. Best is trial 19 with value: 0.7380039655451153.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:02:53,883] Trial 38 finished with value: 0.7379307992747658 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.4920103977585895, 'n_estimators': 342, 'learning_rate': 0.0787855279203912}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:02:57,111] Trial 39 finished with value: 0.7217919798513094 and parameters: {'subsample': 0.22913341588947253, 'dropout_rate': 0.48327859647662685, 'n_estimators': 344, 'learning_rate': 0.07135359751067862}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:03:01,985] Trial 40 finished with value: 0.7279699528314543 and parameters: {'subsample': 0.15678968873354251, 'dropout_rate': 0.3788557193902431, 'n_estimators': 410, 'learning_rate': 0.06401735583833311}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:03:06,882] Trial 41 finished with value: 0.7369360383742469 and parameters: {'subsample': 0.1044600331519512, 'dropout_rate': 0.5223787370483411, 'n_estimators': 461, 'learning_rate': 0.07919758907075584}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:03:08,616] Trial 42 finished with value: 0.7271260709749142 and parameters: {'subsample': 0.15556873719503106, 'dropout_rate': 0.42265289977126685, 'n_estimators': 232, 'learning_rate': 0.09006329088126515}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:03:13,362] Trial 43 finished with value: 0.723303993107316 and parameters: {'subsample': 0.25452846893787723, 'dropout_rate': 0.6176715828207425, 'n_estimators': 470, 'learning_rate': 0.05693452502959143}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:03:16,974] Trial 44 finished with value: 0.736821447083185 and parameters: {'subsample': 0.10226783590912428, 'dropout_rate': 0.8724342327631989, 'n_estimators': 435, 'learning_rate': 0.07716588766421156}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:03:19,283] Trial 45 finished with value: 0.7254406689011526 and parameters: {'subsample': 0.19438769521144972, 'dropout_rate': 0.9462373811823376, 'n_estimators': 340, 'learning_rate': 0.09286625927673108}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:03:22,988] Trial 46 finished with value: 0.7271674959956268 and parameters: {'subsample': 0.14485404068604799, 'dropout_rate': 0.3111267876343467, 'n_estimators': 376, 'learning_rate': 0.07199415517036555}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:03:26,714] Trial 47 finished with value: 0.7088046938981755 and parameters: {'subsample': 0.4290690615926759, 'dropout_rate': 0.8248707138495918, 'n_estimators': 418, 'learning_rate': 0.08572785058635488}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 16:03:33,156] Trial 48 finished with value: 0.7128966475810572 and parameters: {'subsample': 0.3116857468966071, 'dropout_rate': 0.5078753361408778, 'n_estimators': 465, 'learning_rate': 0.027763821111874188}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:03:34,197] Trial 49 finished with value: 0.7147585543155819 and parameters: {'subsample': 0.5525163475807153, 'dropout_rate': 0.5650510345968978, 'n_estimators': 162, 'learning_rate': 0.04897928524498507}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:03:37,924] Trial 50 finished with value: 0.7345062965622885 and parameters: {'subsample': 0.13318912932470306, 'dropout_rate': 0.4432311087867536, 'n_estimators': 359, 'learning_rate': 0.09908361867719767}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:03:44,895] Trial 51 finished with value: 0.7369360383742469 and parameters: {'subsample': 0.10369235886762933, 'dropout_rate': 0.5254222713677715, 'n_estimators': 473, 'learning_rate': 0.07960179559677169}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:03:50,712] Trial 52 finished with value: 0.7261480404573699 and parameters: {'subsample': 0.18321627544350266, 'dropout_rate': 0.48883340978002526, 'n_estimators': 447, 'learning_rate': 0.08020124978167709}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:03:52,948] Trial 53 finished with value: 0.7260776498154976 and parameters: {'subsample': 0.14045793182899935, 'dropout_rate': 0.6664843837374899, 'n_estimators': 276, 'learning_rate': 0.08663549918697531}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:03:59,050] Trial 54 finished with value: 0.7231457048207701 and parameters: {'subsample': 0.22042467251295894, 'dropout_rate': 0.598071901287773, 'n_estimators': 500, 'learning_rate': 0.06618255083791162}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:04:03,268] Trial 55 finished with value: 0.7286358993669593 and parameters: {'subsample': 0.13390484999770624, 'dropout_rate': 0.5593587534677644, 'n_estimators': 386, 'learning_rate': 0.008691620412125275}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:04:08,599] Trial 56 finished with value: 0.7268259940972126 and parameters: {'subsample': 0.1767571716520151, 'dropout_rate': 0.9066583347278534, 'n_estimators': 422, 'learning_rate': 0.09340808805923091}. Best is trial 19 with value: 0.7380039655451153.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:04:13,368] Trial 57 finished with value: 0.7378893742540533 and parameters: {'subsample': 0.10152071700768778, 'dropout_rate': 0.9654332519933311, 'n_estimators': 472, 'learning_rate': 0.07436180553506441}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:04:16,639] Trial 58 finished with value: 0.6505141149475884 and parameters: {'subsample': 0.7591484265070766, 'dropout_rate': 0.968193376933818, 'n_estimators': 441, 'learning_rate': 0.074136150262346}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:04:18,813] Trial 59 finished with value: 0.7192038087297675 and parameters: {'subsample': 0.24831529695541027, 'dropout_rate': 0.9238920647260879, 'n_estimators': 325, 'learning_rate': 0.08322655251020356}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:04:22,889] Trial 60 finished with value: 0.7240822589591114 and parameters: {'subsample': 0.20604784836255208, 'dropout_rate': 0.862744103616718, 'n_estimators': 472, 'learning_rate': 0.06286077704499698}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:04:26,650] Trial 61 finished with value: 0.732660103539625 and parameters: {'subsample': 0.11348118401506707, 'dropout_rate': 0.970379847864969, 'n_estimators': 460, 'learning_rate': 0.07083291736259273}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:04:31,861] Trial 62 finished with value: 0.7270770956885972 and parameters: {'subsample': 0.164728982811017, 'dropout_rate': 0.45312825532195217, 'n_estimators': 481, 'learning_rate': 0.07866487864548685}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:04:35,571] Trial 63 finished with value: 0.7380039655451153 and parameters: {'subsample': 0.10614193769660749, 'dropout_rate': 0.9488846394603185, 'n_estimators': 447, 'learning_rate': 0.08824425494012118}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:04:39,383] Trial 64 finished with value: 0.7276727412467767 and parameters: {'subsample': 0.13923559950429637, 'dropout_rate': 0.8957891621801076, 'n_estimators': 413, 'learning_rate': 0.08878811547207124}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.568075117370892
[I 2024-04-14 16:04:43,594] Trial 65 finished with value: 0.7136892821765086 and parameters: {'subsample': 0.2827043633025912, 'dropout_rate': 0.7999028267442422, 'n_estimators': 391, 'learning_rate': 0.09488642571579502}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:04:47,485] Trial 66 finished with value: 0.7380039655451153 and parameters: {'subsample': 0.10041734071097298, 'dropout_rate': 0.9432298767814716, 'n_estimators': 438, 'learning_rate': 0.0837451388261299}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:04:50,727] Trial 67 finished with value: 0.725179655404845 and parameters: {'subsample': 0.17990496703625825, 'dropout_rate': 0.9393197921588501, 'n_estimators': 365, 'learning_rate': 0.0841076036704165}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:04:57,305] Trial 68 finished with value: 0.72805748784546 and parameters: {'subsample': 0.15435942943322142, 'dropout_rate': 0.9745731119411685, 'n_estimators': 430, 'learning_rate': 0.07640656684389122}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:05:05,300] Trial 69 finished with value: 0.7325137709989262 and parameters: {'subsample': 0.1308625315864297, 'dropout_rate': 0.9966818840060571, 'n_estimators': 445, 'learning_rate': 0.052595847243253016}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:05:08,998] Trial 70 finished with value: 0.7218063485949656 and parameters: {'subsample': 0.2365694890587422, 'dropout_rate': 0.9598439500673247, 'n_estimators': 408, 'learning_rate': 0.06897378769509797}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:05:13,744] Trial 71 finished with value: 0.7369360383742469 and parameters: {'subsample': 0.10668055558010346, 'dropout_rate': 0.8449920663731697, 'n_estimators': 452, 'learning_rate': 0.08769540536024202}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:05:18,639] Trial 72 finished with value: 0.7259821122406726 and parameters: {'subsample': 0.1980388022879676, 'dropout_rate': 0.8924130359469317, 'n_estimators': 482, 'learning_rate': 0.08141982101816211}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 16:05:22,797] Trial 73 finished with value: 0.7307626632558727 and parameters: {'subsample': 0.12547900028151493, 'dropout_rate': 0.9218275103951624, 'n_estimators': 438, 'learning_rate': 0.07442319023204992}. Best is trial 19 with value: 0.7380039655451153.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:05:25,341] Trial 74 finished with value: 0.7396404819971067 and parameters: {'subsample': 0.10086780506047602, 'dropout_rate': 0.9424190164894708, 'n_estimators': 287, 'learning_rate': 0.0837489942480439}. Best is trial 74 with value: 0.7396404819971067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:05:27,830] Trial 75 finished with value: 0.7270770956885972 and parameters: {'subsample': 0.16429649592855558, 'dropout_rate': 0.9355165821138591, 'n_estimators': 303, 'learning_rate': 0.09079453470783766}. Best is trial 74 with value: 0.7396404819971067.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:05:29,388] Trial 76 finished with value: 0.7313460735758671 and parameters: {'subsample': 0.1258228705185852, 'dropout_rate': 0.999762761251892, 'n_estimators': 226, 'learning_rate': 0.08385579121141573}. Best is trial 74 with value: 0.7396404819971067.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:05:33,649] Trial 77 finished with value: 0.7399429718726175 and parameters: {'subsample': 0.1001094180478445, 'dropout_rate': 0.17771784288698328, 'n_estimators': 396, 'learning_rate': 0.06006835823961436}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:05:36,166] Trial 78 finished with value: 0.7334722441465281 and parameters: {'subsample': 0.20434936047009788, 'dropout_rate': 0.14647063839230917, 'n_estimators': 279, 'learning_rate': 0.08170173411088184}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:05:40,545] Trial 79 finished with value: 0.7350621983100117 and parameters: {'subsample': 0.15683604113992922, 'dropout_rate': 0.2276489054004992, 'n_estimators': 353, 'learning_rate': 0.07727902397487113}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:05:45,208] Trial 80 finished with value: 0.7035202068477109 and parameters: {'subsample': 0.8321289633684164, 'dropout_rate': 0.27634437206158513, 'n_estimators': 393, 'learning_rate': 0.09172938138754551}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:05:47,154] Trial 81 finished with value: 0.7315748038627758 and parameters: {'subsample': 0.12672577425518924, 'dropout_rate': 0.959259452810161, 'n_estimators': 316, 'learning_rate': 0.04963814745924382}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:05:50,300] Trial 82 finished with value: 0.7359556462173842 and parameters: {'subsample': 0.10245889679834769, 'dropout_rate': 0.8827986943373289, 'n_estimators': 420, 'learning_rate': 0.059464782461924715}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 16:05:54,088] Trial 83 finished with value: 0.7362574043053419 and parameters: {'subsample': 0.15145622741479567, 'dropout_rate': 0.19237609395384048, 'n_estimators': 372, 'learning_rate': 0.0692402614218835}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:05:57,290] Trial 84 finished with value: 0.726984423406796 and parameters: {'subsample': 0.17740366223574017, 'dropout_rate': 0.9198508876088273, 'n_estimators': 401, 'learning_rate': 0.06542976718625844}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:06:00,509] Trial 85 finished with value: 0.7366849367828623 and parameters: {'subsample': 0.10229302201379117, 'dropout_rate': 0.7492686817464098, 'n_estimators': 334, 'learning_rate': 0.046118625370362286}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 16:06:03,120] Trial 86 finished with value: 0.7334527381350764 and parameters: {'subsample': 0.13112090359727074, 'dropout_rate': 0.33499666640662656, 'n_estimators': 289, 'learning_rate': 0.039444837269605126}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:06:07,077] Trial 87 finished with value: 0.7226335897330779 and parameters: {'subsample': 0.20579900225543918, 'dropout_rate': 0.9827373678157874, 'n_estimators': 429, 'learning_rate': 0.08564238963907483}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:06:12,248] Trial 88 finished with value: 0.7109372082355365 and parameters: {'subsample': 0.6350482367083102, 'dropout_rate': 0.8501285972963792, 'n_estimators': 455, 'learning_rate': 0.0744839995334948}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 16:06:14,051] Trial 89 finished with value: 0.7152758066710695 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.8036886089440476, 'n_estimators': 257, 'learning_rate': 0.05844241830839629}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:06:16,296] Trial 90 finished with value: 0.7245430371211679 and parameters: {'subsample': 0.14609676538738847, 'dropout_rate': 0.951010136325844, 'n_estimators': 349, 'learning_rate': 0.08047599238676414}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 16:06:20,596] Trial 91 finished with value: 0.7351894771344736 and parameters: {'subsample': 0.12070374007632043, 'dropout_rate': 0.6518162891078353, 'n_estimators': 493, 'learning_rate': 0.098342094702385}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:06:24,269] Trial 92 finished with value: 0.7278063862540753 and parameters: {'subsample': 0.17495286331785417, 'dropout_rate': 0.7740053565175792, 'n_estimators': 477, 'learning_rate': 0.08767992653877743}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:06:27,854] Trial 93 finished with value: 0.7360431812313898 and parameters: {'subsample': 0.10120210764794153, 'dropout_rate': 0.8989510852993025, 'n_estimators': 467, 'learning_rate': 0.05490805584564135}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 16:06:31,317] Trial 94 finished with value: 0.7307626632558727 and parameters: {'subsample': 0.12339871671175176, 'dropout_rate': 0.9782025553343453, 'n_estimators': 415, 'learning_rate': 0.08449423233872323}. Best is trial 77 with value: 0.7399429718726175.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:06:35,194] Trial 95 finished with value: 0.7258870269610623 and parameters: {'subsample': 0.14884282725297018, 'dropout_rate': 0.9154623886240678, 'n_estimators': 460, 'learning_rate': 0.09521863138262218}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:06:39,207] Trial 96 finished with value: 0.7378018392400477 and parameters: {'subsample': 0.10075173766758054, 'dropout_rate': 0.7205731357496207, 'n_estimators': 439, 'learning_rate': 0.07199128560218693}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:06:42,947] Trial 97 finished with value: 0.7262626317484319 and parameters: {'subsample': 0.18642360406868505, 'dropout_rate': 0.9383607908918866, 'n_estimators': 438, 'learning_rate': 0.07301994242795604}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:06:46,719] Trial 98 finished with value: 0.7259089459703232 and parameters: {'subsample': 0.16539180022119665, 'dropout_rate': 0.7014213804835303, 'n_estimators': 385, 'learning_rate': 0.06678763942696254}. Best is trial 77 with value: 0.7399429718726175.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.5485232067510548

[I 2024-04-14 16:06:50,901] A new study created in memory with name: no-name-4d8086c0-91a2-4ccd-8ec8-c93629893add

Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:06:50,888] Trial 99 finished with value: 0.6342407169840496 and parameters: {'subsample': 0.9486139007337078, 'dropout_rate': 0.38325321954913594, 'n_estimators': 404, 'learning_rate': 0.06363613685026742}. Best is trial 77 with value: 0.7399429718726175.


* Best trial for C-index:
 FrozenTrial(number=77, state=TrialState.COMPLETE, values=[0.7399429718726175], datetime_start=datetime.datetime(2024, 4, 14, 16, 5, 29, 397366), datetime_complete=datetime.datetime(2024, 4, 14, 16, 5, 33, 649024), params={'subsample': 0.1001094180478445, 'dropout_rate': 0.17771784288698328, 'n_estimators': 396, 'learning_rate': 0.06006835823961436}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=77, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.1001094180478445, 'dropout_rate': 0.17771784288698328, 'n_estimators': 396, 'learning_rate': 0.06006835823961436}


* Best Score for C-index:
 0.7399429718726175

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1813728488668672
Fold 2 IBS: 0.2681995723911614
Fold 3 IBS: 0.19491583632250825
Fold 4 IBS: 0.2591223857279743
Fold 5 IBS: 0.287607304180785
[I 2024-04-14 16:06:51,607] Trial 0 finished with value: 0.23824358949785923 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.19346132552880968
Fold 2 IBS: 0.333635239938422
Fold 3 IBS: 0.25841417567823277
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.33474769607672983
[I 2024-04-14 16:06:59,637] Trial 1 finished with value: 0.287222617640297 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.18509020697087622
Fold 2 IBS: 0.32284991583985745
Fold 3 IBS: 0.22642778350592282
Fold 4 IBS: 0.3131879440790452
Fold 5 IBS: 0.3204571034658354
[I 2024-04-14 16:07:00,968] Trial 2 finished with value: 0.2736025907723074 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.18779306792980804
Fold 2 IBS: 0.27639252154435356
Fold 3 IBS: 0.19977904610578312
Fold 4 IBS: 0.30964356157804196
Fold 5 IBS: 0.3057104839266166
[I 2024-04-14 16:07:02,907] Trial 3 finished with value: 0.25586373621692066 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.1915566066286855
Fold 2 IBS: 0.28165603731910205
Fold 3 IBS: 0.20753177024015892
Fold 4 IBS: 0.3108415350225879
Fold 5 IBS: 0.3127562135989296
[I 2024-04-14 16:07:05,296] Trial 4 finished with value: 0.26086843256189274 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.19537572961200286
Fold 2 IBS: 0.35817891717310324
Fold 3 IBS: 0.2507632087812951
Fold 4 IBS: 0.3158522741556934
Fold 5 IBS: 0.33393252910961757
[I 2024-04-14 16:07:07,887] Trial 5 finished with value: 0.2908205317663425 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.23824358949785923.
Fold 1 IBS: 0.18137830855281592
Fold 2 IBS: 0.24793283695787818
Fold 3 IBS: 0.18249630236911993
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.26458515064083027
[I 2024-04-14 16:07:08,888] Trial 6 finished with value: 0.22022100159798294 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.22022100159798294.
Fold 1 IBS: 0.19109737566864776
Fold 2 IBS: 0.20016441145421077
Fold 3 IBS: 0.1741036457562264
Fold 4 IBS: 0.20816262061005744
Fold 5 IBS: 0.2247983920371421
[I 2024-04-14 16:07:09,190] Trial 7 finished with value: 0.19966528910525688 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19966528910525688.
Fold 1 IBS: 0.17599599328053214
Fold 2 IBS: 0.2639224383921999
Fold 3 IBS: 0.192681424890099
Fold 4 IBS: 0.2572479682340138
Fold 5 IBS: 0.28852789950585367
[I 2024-04-14 16:07:10,754] Trial 8 finished with value: 0.23567514486053973 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19966528910525688.
Fold 1 IBS: 0.20472968510215103
Fold 2 IBS: 0.3574154634952448
Fold 3 IBS: 0.24952741981587587
Fold 4 IBS: 0.3158539314513873
Fold 5 IBS: 0.33189796891000267
[I 2024-04-14 16:07:14,850] Trial 9 finished with value: 0.2918848937549323 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19966528910525688.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22059842885155323
Fold 3 IBS: 0.2036146550646029
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21796899997630922
[I 2024-04-14 16:07:15,039] Trial 10 finished with value: 0.21599051849664241 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19966528910525688.
Fold 1 IBS: 0.21140722062572354
Fold 2 IBS: 0.21744929507518834
Fold 3 IBS: 0.2007975357492026
Fold 4 IBS: 0.22325500430754436
Fold 5 IBS: 0.21757531472963265
[I 2024-04-14 16:07:15,179] Trial 11 finished with value: 0.2140968740974583 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.19966528910525688.
Fold 1 IBS: 0.17124828210300275
Fold 2 IBS: 0.21509707158444255
Fold 3 IBS: 0.15931421963495104
Fold 4 IBS: 0.1862729877009222
Fold 5 IBS: 0.25130362272257034
[I 2024-04-14 16:07:15,448] Trial 12 finished with value: 0.19664723674917778 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.19664723674917778.
Fold 1 IBS: 0.1660922663012339
Fold 2 IBS: 0.23497263999650947
Fold 3 IBS: 0.16770395450487383
Fold 4 IBS: 0.19542528094999304
Fold 5 IBS: 0.27271801874741475
[I 2024-04-14 16:07:15,936] Trial 13 finished with value: 0.20738243210000498 and parameters: {'subsample': 0.11029739529314715, 'dropout_rate': 0.695526957994077, 'n_estimators': 86, 'learning_rate': 0.09856277651579823}. Best is trial 12 with value: 0.19664723674917778.
Fold 1 IBS: 0.18441033948468438
Fold 2 IBS: 0.20001253127789195
Fold 3 IBS: 0.16857461819050648
Fold 4 IBS: 0.20354941884450073
Fold 5 IBS: 0.23335112566427893
[I 2024-04-14 16:07:16,372] Trial 14 finished with value: 0.1979796066923725 and parameters: {'subsample': 0.2888452381430052, 'dropout_rate': 0.6348327022941171, 'n_estimators': 79, 'learning_rate': 0.035476350988955505}. Best is trial 12 with value: 0.19664723674917778.
Fold 1 IBS: 0.19167955429088052
Fold 2 IBS: 0.1962338941868033
Fold 3 IBS: 0.17718841259709725
Fold 4 IBS: 0.2015538637246263
Fold 5 IBS: 0.21903826977220867
[I 2024-04-14 16:07:16,933] Trial 15 finished with value: 0.19713879891432323 and parameters: {'subsample': 0.10269051002372756, 'dropout_rate': 0.8088719290273756, 'n_estimators': 112, 'learning_rate': 0.017180301525687395}. Best is trial 12 with value: 0.19664723674917778.
Fold 1 IBS: 0.18686883587021624
Fold 2 IBS: 0.193691356815167
Fold 3 IBS: 0.17003094658109136
Fold 4 IBS: 0.1963840399909629
Fold 5 IBS: 0.22178339729244204
[I 2024-04-14 16:07:19,274] Trial 16 finished with value: 0.1937517153099759 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 279, 'learning_rate': 0.008849016864295123}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.20056166778665402
Fold 2 IBS: 0.20341589771239557
Fold 3 IBS: 0.18686368987816832
Fold 4 IBS: 0.21223043597709115
Fold 5 IBS: 0.21699325978518277
[I 2024-04-14 16:07:21,188] Trial 17 finished with value: 0.20401299022789837 and parameters: {'subsample': 0.2050425035399529, 'dropout_rate': 0.9222227086072663, 'n_estimators': 294, 'learning_rate': 0.0036826000404672626}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.2520520016331023
Fold 2 IBS: 0.3519911199130833
Fold 3 IBS: 0.2499810763987998
Fold 4 IBS: 0.31586714541348115
Fold 5 IBS: 0.333030405842313
[I 2024-04-14 16:07:23,220] Trial 18 finished with value: 0.3005843498401559 and parameters: {'subsample': 0.3674262467329663, 'dropout_rate': 0.9693482856032436, 'n_estimators': 336, 'learning_rate': 0.0851241515162967}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.16853983267367703

Fold 2 IBS: 0.2354300841917142
Fold 3 IBS: 0.16162421990807277
Fold 4 IBS: 0.21881379377656782
Fold 5 IBS: 0.2684022959740717
[I 2024-04-14 16:07:25,516] Trial 19 finished with value: 0.2105620453048207 and parameters: {'subsample': 0.16667191735421055, 'dropout_rate': 0.995336953668152, 'n_estimators': 400, 'learning_rate': 0.0164716167796114}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.23230314629982232
Fold 2 IBS: 0.3472907284410055
Fold 3 IBS: 0.24260871569057887
Fold 4 IBS: 0.3158666317843052
Fold 5 IBS: 0.3305681079680327
[I 2024-04-14 16:07:27,147] Trial 20 finished with value: 0.29372746603674893 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.7933084651006226, 'n_estimators': 307, 'learning_rate': 0.0817175642960023}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.1867095271065796
Fold 2 IBS: 0.1938189738975239
Fold 3 IBS: 0.17171699702984686
Fold 4 IBS: 0.19765663176182818
Fold 5 IBS: 0.2217748556695782
[I 2024-04-14 16:07:27,698] Trial 21 finished with value: 0.19433539709307138 and parameters: {'subsample': 0.11014863416226671, 'dropout_rate': 0.8063201983942048, 'n_estimators': 135, 'learning_rate': 0.01797338959196447}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.19689967861609645
Fold 2 IBS: 0.19955717185546204
Fold 3 IBS: 0.18111493789845068
Fold 4 IBS: 0.2092963819109702
Fold 5 IBS: 0.21728369810384407
[I 2024-04-14 16:07:28,176] Trial 22 finished with value: 0.20083037367696469 and parameters: {'subsample': 0.19248201672248066, 'dropout_rate': 0.8234108975822259, 'n_estimators': 119, 'learning_rate': 0.011819375854030013}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.17165384572171308
Fold 2 IBS: 0.23991249991044802
Fold 3 IBS: 0.17483856716319865
Fold 4 IBS: 0.23321826576910004
Fold 5 IBS: 0.274976186351202
[I 2024-04-14 16:07:29,622] Trial 23 finished with value: 0.21891987298313237 and parameters: {'subsample': 0.26371324009764935, 'dropout_rate': 0.5895996601395932, 'n_estimators': 232, 'learning_rate': 0.027350217488462242}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.16396637570913558
Fold 2 IBS: 0.2175765891450497
Fold 3 IBS: 0.16045575500404088
Fold 4 IBS: 0.19071662158869557
Fold 5 IBS: 0.26242048723247247
[I 2024-04-14 16:07:30,435] Trial 24 finished with value: 0.1990271657358788 and parameters: {'subsample': 0.10031593524282066, 'dropout_rate': 0.7652919670925054, 'n_estimators': 151, 'learning_rate': 0.04338790451384301}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.20716120235152355
Fold 2 IBS: 0.21175357902753247
Fold 3 IBS: 0.19479768733179006
Fold 4 IBS: 0.21829433205307777
Fold 5 IBS: 0.21620070498050745
[I 2024-04-14 16:07:30,708] Trial 25 finished with value: 0.20964150114888627 and parameters: {'subsample': 0.19322710041723, 'dropout_rate': 0.8657417745920969, 'n_estimators': 52, 'learning_rate': 0.010614246367470062}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.17597630300043302
Fold 2 IBS: 0.27593212019582813
Fold 3 IBS: 0.19014264726628857
Fold 4 IBS: 0.29109985410904143
Fold 5 IBS: 0.29774885277794033
[I 2024-04-14 16:07:32,098] Trial 26 finished with value: 0.24617995546990631 and parameters: {'subsample': 0.3035210373469147, 'dropout_rate': 0.9269050653193316, 'n_estimators': 245, 'learning_rate': 0.037598193265478724}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.1813514956265256
Fold 2 IBS: 0.19521875985661272
Fold 3 IBS: 0.1653305693666438
Fold 4 IBS: 0.19559396932062825
Fold 5 IBS: 0.23201056395563857
[I 2024-04-14 16:07:32,884] Trial 27 finished with value: 0.19390107162520978 and parameters: {'subsample': 0.16351183385205548, 'dropout_rate': 0.617221808630949, 'n_estimators': 149, 'learning_rate': 0.020996611742583823}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.17941106861347955
Fold 2 IBS: 0.20226573466035702
Fold 3 IBS: 0.1653732558568532
Fold 4 IBS: 0.1998489980251948
Fold 5 IBS: 0.23890569907963172
[I 2024-04-14 16:07:33,655] Trial 28 finished with value: 0.19716095124710323 and parameters: {'subsample': 0.23131169694169362, 'dropout_rate': 0.5816359665311226, 'n_estimators': 154, 'learning_rate': 0.02350384816799895}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.18577019541898715
Fold 2 IBS: 0.22941595585627755
Fold 3 IBS: 0.1772590705828925
Fold 4 IBS: 0.2141339425704712
Fold 5 IBS: 0.24776175251061422
[I 2024-04-14 16:07:35,313] Trial 29 finished with value: 0.21086818338784852 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.5215467852428345, 'n_estimators': 272, 'learning_rate': 0.01140291013923438}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.18311515515678187
Fold 2 IBS: 0.28827810160153167
Fold 3 IBS: 0.209176093334867
Fold 4 IBS: 0.284653288023798
Fold 5 IBS: 0.29931729715829875
[I 2024-04-14 16:07:38,530] Trial 30 finished with value: 0.25290798705505546 and parameters: {'subsample': 0.6631051739276518, 'dropout_rate': 0.6190526532143903, 'n_estimators': 415, 'learning_rate': 0.01816681666811427}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.20484622464488117
Fold 2 IBS: 0.2095414226948121
Fold 3 IBS: 0.1918862270388781
Fold 4 IBS: 0.2161472971057234
Fold 5 IBS: 0.21631825627015988
[I 2024-04-14 16:07:39,092] Trial 31 finished with value: 0.2077478855508909 and parameters: {'subsample': 0.15497553050776378, 'dropout_rate': 0.748720565290365, 'n_estimators': 113, 'learning_rate': 0.0065154280035889175}. Best is trial 16 with value: 0.1937517153099759.
Fold 1 IBS: 0.18066748625501913
Fold 2 IBS: 0.1953357044172125
Fold 3 IBS: 0.1645147112206549
Fold 4 IBS: 0.19449543785062076
Fold 5 IBS: 0.23216173263287276
[I 2024-04-14 16:07:39,877] Trial 32 finished with value: 0.193435014475276 and parameters: {'subsample': 0.15376407139189344, 'dropout_rate': 0.845319184160475, 'n_estimators': 134, 'learning_rate': 0.024513442210510737}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.17729615944307384
Fold 2 IBS: 0.21675630679264887
Fold 3 IBS: 0.167865433104899
Fold 4 IBS: 0.208704513453123
Fold 5 IBS: 0.25025299735444284
[I 2024-04-14 16:07:40,746] Trial 33 finished with value: 0.20417508202963752 and parameters: {'subsample': 0.31593930714701857, 'dropout_rate': 0.8506702896224428, 'n_estimators': 145, 'learning_rate': 0.027997278046075002}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.17738631472071778
Fold 2 IBS: 0.2138455190837193
Fold 3 IBS: 0.16250581098415381
Fold 4 IBS: 0.20012550274292673
Fold 5 IBS: 0.24426836884518893
[I 2024-04-14 16:07:41,752] Trial 34 finished with value: 0.1996263032753413 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.9425816130159088, 'n_estimators': 186, 'learning_rate': 0.020684756718428673}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.1952728404094179
Fold 2 IBS: 0.2022923805304332
Fold 3 IBS: 0.17876884221027042
Fold 4 IBS: 0.21135839842613077
Fold 5 IBS: 0.22327851723808015
[I 2024-04-14 16:07:43,326] Trial 35 finished with value: 0.20219419576286649 and parameters: {'subsample': 0.42784695286827157, 'dropout_rate': 0.43975685710717877, 'n_estimators': 216, 'learning_rate': 0.007388367220883029}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.1698568826711768
Fold 2 IBS: 0.2221602607670185
Fold 3 IBS: 0.15994841962264494
Fold 4 IBS: 0.19192925845644765
Fold 5 IBS: 0.2549261821207725
[I 2024-04-14 16:07:44,193] Trial 36 finished with value: 0.19976420072761206 and parameters: {'subsample': 0.16803166512201972, 'dropout_rate': 0.24408912236765595, 'n_estimators': 129, 'learning_rate': 0.04225859536542059}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.17835132828284767
Fold 2 IBS: 0.25718995975545916
Fold 3 IBS: 0.18727768218670995
Fold 4 IBS: 0.2331260439626846
Fold 5 IBS: 0.2755523637181051
[I 2024-04-14 16:07:44,646] Trial 37 finished with value: 0.2262994755811613 and parameters: {'subsample': 0.5954959434166642, 'dropout_rate': 0.8871014043159935, 'n_estimators': 88, 'learning_rate': 0.059207327336158105}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.1735958572171929
Fold 2 IBS: 0.22573836294500974

Fold 3 IBS: 0.1644847044499737
Fold 4 IBS: 0.21105160502473713
Fold 5 IBS: 0.25612451029896155
[I 2024-04-14 16:07:45,482] Trial 38 finished with value: 0.206199007987175 and parameters: {'subsample': 0.23557094034920928, 'dropout_rate': 0.9772185725180188, 'n_estimators': 170, 'learning_rate': 0.028634921614009247}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.18527875729076687
Fold 2 IBS: 0.206842479595501
Fold 3 IBS: 0.1684391799542552
Fold 4 IBS: 0.20310310442935434
Fold 5 IBS: 0.23670810681271148
[I 2024-04-14 16:07:46,594] Trial 39 finished with value: 0.20007432561651778 and parameters: {'subsample': 0.34419137871914335, 'dropout_rate': 0.7641491998417398, 'n_estimators': 203, 'learning_rate': 0.013931445007643331}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.17416970091294498
Fold 2 IBS: 0.2527135803516107
Fold 3 IBS: 0.18506003766329993
Fold 4 IBS: 0.24375993453341516
Fold 5 IBS: 0.2807864950347834
[I 2024-04-14 16:07:48,370] Trial 40 finished with value: 0.22729794969921083 and parameters: {'subsample': 0.42036516122633183, 'dropout_rate': 0.3251168231161491, 'n_estimators': 266, 'learning_rate': 0.02358277366325051}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.19421727193170643
Fold 2 IBS: 0.1969414796660492
Fold 3 IBS: 0.1793374723952296
Fold 4 IBS: 0.20493394185828134
Fold 5 IBS: 0.2200003200390803
[I 2024-04-14 16:07:48,691] Trial 41 finished with value: 0.19908609717806938 and parameters: {'subsample': 0.13871576206845374, 'dropout_rate': 0.6695393055406006, 'n_estimators': 52, 'learning_rate': 0.0331241344344775}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.1702371408628154
Fold 2 IBS: 0.20720888123919629
Fold 3 IBS: 0.16125474807425216
Fold 4 IBS: 0.18492731312954422
Fold 5 IBS: 0.2522958722195073
[I 2024-04-14 16:07:49,129] Trial 42 finished with value: 0.1951847911050631 and parameters: {'subsample': 0.1555924802021592, 'dropout_rate': 0.8592682052103442, 'n_estimators': 73, 'learning_rate': 0.06911254892370094}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.16904770048609663
Fold 2 IBS: 0.2092155329126555
Fold 3 IBS: 0.16251275194585388
Fold 4 IBS: 0.18925817629758646
Fold 5 IBS: 0.2613676628358447
[I 2024-04-14 16:07:49,605] Trial 43 finished with value: 0.19828036489560744 and parameters: {'subsample': 0.16111743938632528, 'dropout_rate': 0.841297831671249, 'n_estimators': 90, 'learning_rate': 0.0634052604793496}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.18085241233640775
Fold 2 IBS: 0.2765591078803387
Fold 3 IBS: 0.20852365713832716
Fold 4 IBS: 0.30677244609314663
Fold 5 IBS: 0.30673697177359904
[I 2024-04-14 16:07:50,553] Trial 44 finished with value: 0.2558889190443639 and parameters: {'subsample': 0.25343420053256144, 'dropout_rate': 0.8812273299197759, 'n_estimators': 176, 'learning_rate': 0.06523605428553468}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.1721545090947868
Fold 2 IBS: 0.2741687723688007
Fold 3 IBS: 0.1750633216469091
Fold 4 IBS: 0.2867977658373365
Fold 5 IBS: 0.2929162456388098
[I 2024-04-14 16:07:51,234] Trial 45 finished with value: 0.24022012291732858 and parameters: {'subsample': 0.19719053175861329, 'dropout_rate': 0.9504868051826713, 'n_estimators': 136, 'learning_rate': 0.07358829455007394}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.20131818266287807
Fold 2 IBS: 0.20696568410191643
Fold 3 IBS: 0.1900231724107972
Fold 4 IBS: 0.21391404277983386
Fold 5 IBS: 0.21560873962430452
[I 2024-04-14 16:07:51,420] Trial 46 finished with value: 0.20556596431594604 and parameters: {'subsample': 0.13212481320887529, 'dropout_rate': 0.9036764717128756, 'n_estimators': 17, 'learning_rate': 0.05378014293554952}. Best is trial 32 with value: 0.193435014475276.
Fold 1 IBS: 0.1766229000204669
Fold 2 IBS: 0.1964539452071014
Fold 3 IBS: 0.16445901469408597
Fold 4 IBS: 0.18586367320399907
Fold 5 IBS: 0.2253941579088676
[I 2024-04-14 16:07:51,851] Trial 47 finished with value: 0.1897587382069042 and parameters: {'subsample': 0.1011626756141227, 'dropout_rate': 0.1240463473883398, 'n_estimators': 73, 'learning_rate': 0.04961644208307468}. Best is trial 47 with value: 0.1897587382069042.
Fold 1 IBS: 0.19726303925801764
Fold 2 IBS: 0.1992700788269522
Fold 3 IBS: 0.18156334485968925
Fold 4 IBS: 0.20454862586219233
Fold 5 IBS: 0.21750664987707555
[I 2024-04-14 16:07:52,061] Trial 48 finished with value: 0.20003034773678538 and parameters: {'subsample': 0.1004359647341087, 'dropout_rate': 0.13945177030101905, 'n_estimators': 33, 'learning_rate': 0.046830831897685256}. Best is trial 47 with value: 0.1897587382069042.
Fold 1 IBS: 0.2084054348805477
Fold 2 IBS: 0.21295980212072763
Fold 3 IBS: 0.19679105128937172
Fold 4 IBS: 0.2194848507803251
Fold 5 IBS: 0.21690747356194126
[I 2024-04-14 16:07:53,373] Trial 49 finished with value: 0.21090972252658266 and parameters: {'subsample': 0.2123229058210784, 'dropout_rate': 0.47698684156509324, 'n_estimators': 224, 'learning_rate': 0.0020041983937945443}. Best is trial 47 with value: 0.1897587382069042.
Fold 1 IBS: 0.17835627226256293
Fold 2 IBS: 0.2147089999513402
Fold 3 IBS: 0.15959111521885813
Fold 4 IBS: 0.20290458415337947
Fold 5 IBS: 0.24905102093995712
[I 2024-04-14 16:07:53,876] Trial 50 finished with value: 0.2009223985052196 and parameters: {'subsample': 0.27343382537926025, 'dropout_rate': 0.2489711718641361, 'n_estimators': 103, 'learning_rate': 0.039049872076932335}. Best is trial 47 with value: 0.1897587382069042.
Fold 1 IBS: 0.16676378510756867
Fold 2 IBS: 0.20001926217245228
Fold 3 IBS: 0.15834674505690424
Fold 4 IBS: 0.1791051151602608
Fold 5 IBS: 0.24347324517932953
[I 2024-04-14 16:07:54,250] Trial 51 finished with value: 0.18954163053530312 and parameters: {'subsample': 0.1430160477007083, 'dropout_rate': 0.10128185135623688, 'n_estimators': 72, 'learning_rate': 0.07041069746675602}. Best is trial 51 with value: 0.18954163053530312.
Fold 1 IBS: 0.16949057179280644
Fold 2 IBS: 0.21022496654361295
Fold 3 IBS: 0.15787179836101056
Fold 4 IBS: 0.19233924676547612
Fold 5 IBS: 0.24157115574251992
[I 2024-04-14 16:07:54,618] Trial 52 finished with value: 0.19429954784108522 and parameters: {'subsample': 0.13260647418667632, 'dropout_rate': 0.17994579761280768, 'n_estimators': 68, 'learning_rate': 0.08043623121452935}. Best is trial 51 with value: 0.18954163053530312.
Fold 1 IBS: 0.16860446453146705
Fold 2 IBS: 0.20333426455526632
Fold 3 IBS: 0.15496510957441834
Fold 4 IBS: 0.17829335933326718
Fold 5 IBS: 0.24065505706684293
[I 2024-04-14 16:07:54,982] Trial 53 finished with value: 0.18917045101225236 and parameters: {'subsample': 0.18457062310520533, 'dropout_rate': 0.10188563743505225, 'n_estimators': 68, 'learning_rate': 0.07845638174276695}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.19404154162019294
Fold 2 IBS: 0.20117934950140887
Fold 3 IBS: 0.1839629576131534
Fold 4 IBS: 0.20712375025583504
Fold 5 IBS: 0.21795442094907355
[I 2024-04-14 16:07:55,161] Trial 54 finished with value: 0.20085240398793275 and parameters: {'subsample': 0.182980759066888, 'dropout_rate': 0.10198423356484736, 'n_estimators': 16, 'learning_rate': 0.08948442597243661}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.2131310327243351
Fold 2 IBS: 0.22051566092565564
Fold 3 IBS: 0.20378404202862607
Fold 4 IBS: 0.22409645595336913
Fold 5 IBS: 0.21793401275715563
[I 2024-04-14 16:07:55,280] Trial 55 finished with value: 0.21589224087782832 and parameters: {'subsample': 0.2200420761079345, 'dropout_rate': 0.20144398485583834, 'n_estimators': 1, 'learning_rate': 0.05923418086309766}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18536044255216208
Fold 2 IBS: 0.19312501678878427
Fold 3 IBS: 0.16633488170376642
Fold 4 IBS: 0.19555108840254903
Fold 5 IBS: 0.22619584983291227
[I 2024-04-14 16:07:55,512] Trial 56 finished with value: 0.19331345585603482 and parameters: {'subsample': 0.3177919256762519, 'dropout_rate': 0.10730417090600565, 'n_estimators': 36, 'learning_rate': 0.07977869091862749}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18804254545751878
Fold 2 IBS: 0.19381191894902225
Fold 3 IBS: 0.1712487319685125
Fold 4 IBS: 0.19764980229729429
Fold 5 IBS: 0.22489617159629918
[I 2024-04-14 16:07:55,737] Trial 57 finished with value: 0.19512983405372938 and parameters: {'subsample': 0.3249298568930724, 'dropout_rate': 0.11134262466123389, 'n_estimators': 32, 'learning_rate': 0.07742335922946252}. Best is trial 53 with value: 0.18917045101225236.

Fold 1 IBS: 0.17625443541490904
Fold 2 IBS: 0.21448734172456063
Fold 3 IBS: 0.159694803303589
Fold 4 IBS: 0.19917983886935933
Fold 5 IBS: 0.24753611571578277
[I 2024-04-14 16:07:56,077] Trial 58 finished with value: 0.19943050700564013 and parameters: {'subsample': 0.2868686808366677, 'dropout_rate': 0.2032153865804448, 'n_estimators': 65, 'learning_rate': 0.06902571928702043}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.20677608349073381
Fold 2 IBS: 0.2755720028953149
Fold 3 IBS: 0.2188752151078084
Fold 4 IBS: 0.3174407719124043
Fold 5 IBS: 0.3329212341311742
[I 2024-04-14 16:07:58,586] Trial 59 finished with value: 0.27031706150748713 and parameters: {'subsample': 0.1311152882733824, 'dropout_rate': 0.1402923749214668, 'n_estimators': 308, 'learning_rate': 0.0868909336659619}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1749843583986033
Fold 2 IBS: 0.2596945560423311
Fold 3 IBS: 0.17459495798534216
Fold 4 IBS: 0.27092585930374996
Fold 5 IBS: 0.2887870084941695
[I 2024-04-14 16:07:59,094] Trial 60 finished with value: 0.2337973480448392 and parameters: {'subsample': 0.3953479863107713, 'dropout_rate': 0.30421317168763967, 'n_estimators': 98, 'learning_rate': 0.07901155223513284}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17556883788435698
Fold 2 IBS: 0.19540699948699938
Fold 3 IBS: 0.16245803489381222
Fold 4 IBS: 0.18802147854317666
Fold 5 IBS: 0.23177631943529592
[I 2024-04-14 16:07:59,360] Trial 61 finished with value: 0.19064633404872824 and parameters: {'subsample': 0.18340258130308226, 'dropout_rate': 0.16213685884485707, 'n_estimators': 43, 'learning_rate': 0.08449161008383906}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.16713955628858457
Fold 2 IBS: 0.21254056224575799
Fold 3 IBS: 0.15745915584114797
Fold 4 IBS: 0.19350919211703008
Fold 5 IBS: 0.25210669585693674
[I 2024-04-14 16:07:59,685] Trial 62 finished with value: 0.1965510324698915 and parameters: {'subsample': 0.18794206459466292, 'dropout_rate': 0.16652560475406564, 'n_estimators': 60, 'learning_rate': 0.09467564319421562}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18184170182192216
Fold 2 IBS: 0.19187663573826594
Fold 3 IBS: 0.1659571591157526
Fold 4 IBS: 0.185402493469717
Fold 5 IBS: 0.23306406225747658
[I 2024-04-14 16:07:59,972] Trial 63 finished with value: 0.19162841048062684 and parameters: {'subsample': 0.12643051046832973, 'dropout_rate': 0.2205178594196074, 'n_estimators': 40, 'learning_rate': 0.08464918259701915}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1835666203100399
Fold 2 IBS: 0.19460783693026865
Fold 3 IBS: 0.1669660643252237
Fold 4 IBS: 0.19491055124617573
Fold 5 IBS: 0.225487617160099
[I 2024-04-14 16:08:00,309] Trial 64 finished with value: 0.1931077379943614 and parameters: {'subsample': 0.24365502112201767, 'dropout_rate': 0.2126006339987134, 'n_estimators': 39, 'learning_rate': 0.07652451494358439}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18390627458180586
Fold 2 IBS: 0.19405089964407435
Fold 3 IBS: 0.16771118894864687
Fold 4 IBS: 0.19586406965712355
Fold 5 IBS: 0.22762689782929738
[I 2024-04-14 16:08:00,535] Trial 65 finished with value: 0.19383186613218958 and parameters: {'subsample': 0.25983865081736307, 'dropout_rate': 0.22620684328290605, 'n_estimators': 35, 'learning_rate': 0.08266960824040906}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1991009853610107
Fold 2 IBS: 0.20095726826150337
Fold 3 IBS: 0.18544179377161055
Fold 4 IBS: 0.20782541312928923
Fold 5 IBS: 0.2175638000146501
[I 2024-04-14 16:08:00,705] Trial 66 finished with value: 0.2021778521076128 and parameters: {'subsample': 0.21198036637774992, 'dropout_rate': 0.28719537591744226, 'n_estimators': 17, 'learning_rate': 0.07657667672729926}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1763905055406328
Fold 2 IBS: 0.20496852263451934
Fold 3 IBS: 0.15874886191548754
Fold 4 IBS: 0.18717081574690314
Fold 5 IBS: 0.23864229080316046
[I 2024-04-14 16:08:00,991] Trial 67 finished with value: 0.19318419932814063 and parameters: {'subsample': 0.24926445136110992, 'dropout_rate': 0.13837738363312804, 'n_estimators': 51, 'learning_rate': 0.08717644103438375}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.16442256592475268
Fold 2 IBS: 0.2155950871559165
Fold 3 IBS: 0.15895067510291466
Fold 4 IBS: 0.18802493505218948
Fold 5 IBS: 0.24973221029276454
[I 2024-04-14 16:08:01,385] Trial 68 finished with value: 0.19534509470570754 and parameters: {'subsample': 0.12893382950045745, 'dropout_rate': 0.13096722297208158, 'n_estimators': 77, 'learning_rate': 0.09109752901091675}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18436533900160942
Fold 2 IBS: 0.21533695575240316
Fold 3 IBS: 0.16495066389321014
Fold 4 IBS: 0.21043647354648587
Fold 5 IBS: 0.2407699802110437
[I 2024-04-14 16:08:01,675] Trial 69 finished with value: 0.20317188248095047 and parameters: {'subsample': 0.8584661298748817, 'dropout_rate': 0.1917893633297669, 'n_estimators': 44, 'learning_rate': 0.08488921394722074}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17858486195635986
Fold 2 IBS: 0.21615329843487405
Fold 3 IBS: 0.15950813390215446
Fold 4 IBS: 0.19272968978360525
Fold 5 IBS: 0.24589019016402647
[I 2024-04-14 16:08:02,087] Trial 70 finished with value: 0.19857323484820402 and parameters: {'subsample': 0.2512015802119099, 'dropout_rate': 0.3876457045962623, 'n_estimators': 57, 'learning_rate': 0.07225253676918902}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1800092528211933
Fold 2 IBS: 0.2090719516690425
Fold 3 IBS: 0.16061672462238558
Fold 4 IBS: 0.19756012604088363
Fold 5 IBS: 0.24024309774292651
[I 2024-04-14 16:08:02,452] Trial 71 finished with value: 0.1975002305792863 and parameters: {'subsample': 0.5300843058226148, 'dropout_rate': 0.1609516724333739, 'n_estimators': 39, 'learning_rate': 0.09951719085485963}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.21229829523373847
Fold 2 IBS: 0.21988767890776287
Fold 3 IBS: 0.20320326508390127
Fold 4 IBS: 0.2239511215531914
Fold 5 IBS: 0.21781725187767495
[I 2024-04-14 16:08:02,674] Trial 72 finished with value: 0.2154315225312538 and parameters: {'subsample': 0.2903481923761249, 'dropout_rate': 0.12007762600944968, 'n_estimators': 1, 'learning_rate': 0.08858240668428875}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.19584519271414166
Fold 2 IBS: 0.19662600783364972
Fold 3 IBS: 0.17948778110221633
Fold 4 IBS: 0.20031054415540991
Fold 5 IBS: 0.2182615645220796
[I 2024-04-14 16:08:02,901] Trial 73 finished with value: 0.19810621806549944 and parameters: {'subsample': 0.18121728090468855, 'dropout_rate': 0.22111005618640125, 'n_estimators': 21, 'learning_rate': 0.08336995219973156}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.16982858833315212
Fold 2 IBS: 0.23468991997676836
Fold 3 IBS: 0.158762723867783
Fold 4 IBS: 0.21242069105774464
Fold 5 IBS: 0.26873624424389386
[I 2024-04-14 16:08:03,295] Trial 74 finished with value: 0.2088876334958684 and parameters: {'subsample': 0.3424770277855649, 'dropout_rate': 0.16227899006309393, 'n_estimators': 80, 'learning_rate': 0.09407223207264027}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17297488754192844
Fold 2 IBS: 0.24101325682379413
Fold 3 IBS: 0.161812985263414
Fold 4 IBS: 0.26208452660937526
Fold 5 IBS: 0.2815152627652065
[I 2024-04-14 16:08:03,851] Trial 75 finished with value: 0.22388018380074365 and parameters: {'subsample': 0.2407949994973695, 'dropout_rate': 0.27413056142615055, 'n_estimators': 105, 'learning_rate': 0.07578019454508679}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17572332872372284
Fold 2 IBS: 0.1968453409856635
Fold 3 IBS: 0.1604295659360857
Fold 4 IBS: 0.18448430403106755
Fold 5 IBS: 0.2322579376134524
[I 2024-04-14 16:08:04,131] Trial 76 finished with value: 0.1899480954579984 and parameters: {'subsample': 0.2044990020936603, 'dropout_rate': 0.10076464308571223, 'n_estimators': 49, 'learning_rate': 0.08053467326583472}. Best is trial 53 with value: 0.18917045101225236.

Fold 1 IBS: 0.17659749400643285
Fold 2 IBS: 0.20287239360600032
Fold 3 IBS: 0.15841071050681252
Fold 4 IBS: 0.18458264033581556
Fold 5 IBS: 0.23899965212870403
[I 2024-04-14 16:08:04,445] Trial 77 finished with value: 0.19229257811675307 and parameters: {'subsample': 0.20832899863841498, 'dropout_rate': 0.14156682139259733, 'n_estimators': 51, 'learning_rate': 0.08592392402640006}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1636303349328578
Fold 2 IBS: 0.22857784006418638
Fold 3 IBS: 0.1605793070639578
Fold 4 IBS: 0.18309179597728542
Fold 5 IBS: 0.2739548394022102
[I 2024-04-14 16:08:05,101] Trial 78 finished with value: 0.2019668234880995 and parameters: {'subsample': 0.12123242375860951, 'dropout_rate': 0.22328006044976534, 'n_estimators': 117, 'learning_rate': 0.07196105986543508}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.16739080446957846
Fold 2 IBS: 0.22120867741229525
Fold 3 IBS: 0.1564177245718657
Fold 4 IBS: 0.19727210170171616
Fold 5 IBS: 0.2623766638283002
[I 2024-04-14 16:08:05,597] Trial 79 finished with value: 0.20093319439675117 and parameters: {'subsample': 0.1757977207019255, 'dropout_rate': 0.1816534353853971, 'n_estimators': 92, 'learning_rate': 0.06693318630109664}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17748234142984987
Fold 2 IBS: 0.19621343594579432
Fold 3 IBS: 0.16258372503017543
Fold 4 IBS: 0.1881153214584955
Fold 5 IBS: 0.23383586841658982
[I 2024-04-14 16:08:05,974] Trial 80 finished with value: 0.191646138456181 and parameters: {'subsample': 0.14152100065882545, 'dropout_rate': 0.15269949153645482, 'n_estimators': 69, 'learning_rate': 0.049921844717064054}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17800728933188067
Fold 2 IBS: 0.1993017037213301
Fold 3 IBS: 0.16303478855224846
Fold 4 IBS: 0.1844575732448239
Fold 5 IBS: 0.23387337527945343
[I 2024-04-14 16:08:06,459] Trial 81 finished with value: 0.19173494602594732 and parameters: {'subsample': 0.15029641825330856, 'dropout_rate': 0.15473811817777972, 'n_estimators': 71, 'learning_rate': 0.05057837981440412}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1766212196883554
Fold 2 IBS: 0.1992201733243675
Fold 3 IBS: 0.16246892282826897
Fold 4 IBS: 0.18269090208698394
Fold 5 IBS: 0.23056618373591767
[I 2024-04-14 16:08:06,845] Trial 82 finished with value: 0.19031348033277867 and parameters: {'subsample': 0.15030358216102271, 'dropout_rate': 0.1456078999733469, 'n_estimators': 66, 'learning_rate': 0.05587777244792722}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17447442748992936
Fold 2 IBS: 0.19454474472750893
Fold 3 IBS: 0.16203056397165716
Fold 4 IBS: 0.1850151530518493
Fold 5 IBS: 0.23538740008538583
[I 2024-04-14 16:08:07,161] Trial 83 finished with value: 0.1902904578652661 and parameters: {'subsample': 0.14386484862421683, 'dropout_rate': 0.10182357190195951, 'n_estimators': 70, 'learning_rate': 0.05734722491961167}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.2356469847267253
Fold 2 IBS: 0.27615843263937684
Fold 3 IBS: 0.21739036257783842
Fold 4 IBS: 0.31648673693489743
Fold 5 IBS: 0.33122512749137173
[I 2024-04-14 16:08:11,877] Trial 84 finished with value: 0.27538152887404194 and parameters: {'subsample': 0.1474985852157063, 'dropout_rate': 0.10220860061586601, 'n_estimators': 494, 'learning_rate': 0.05364261686519893}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17811479160558813
Fold 2 IBS: 0.19992379148771394
Fold 3 IBS: 0.16078828646327784
Fold 4 IBS: 0.18886381498027144
Fold 5 IBS: 0.23350077507433817
[I 2024-04-14 16:08:12,251] Trial 85 finished with value: 0.1922382919222379 and parameters: {'subsample': 0.11688186199103459, 'dropout_rate': 0.1782553587553815, 'n_estimators': 83, 'learning_rate': 0.046118625370362286}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.16556159741252793
Fold 2 IBS: 0.22441542080667545
Fold 3 IBS: 0.15639613776884412
Fold 4 IBS: 0.2024560255153077
Fold 5 IBS: 0.25816399472816565
[I 2024-04-14 16:08:12,820] Trial 86 finished with value: 0.2013986352463042 and parameters: {'subsample': 0.1722572818096484, 'dropout_rate': 0.12356899602152925, 'n_estimators': 123, 'learning_rate': 0.057331333254271234}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.2150622748979152
Fold 2 IBS: 0.27072055091445274
Fold 3 IBS: 0.21068139471566583
Fold 4 IBS: 0.31497536195965414
Fold 5 IBS: 0.32417635636793896
[I 2024-04-14 16:08:17,955] Trial 87 finished with value: 0.2671231877711254 and parameters: {'subsample': 0.1011151359469829, 'dropout_rate': 0.1493502905400993, 'n_estimators': 472, 'learning_rate': 0.048425102428839975}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17640863946186336
Fold 2 IBS: 0.19614577860160887
Fold 3 IBS: 0.16267929744373316
Fold 4 IBS: 0.18999139207819005
Fold 5 IBS: 0.2320627681679039
[I 2024-04-14 16:08:18,289] Trial 88 finished with value: 0.19145757515065984 and parameters: {'subsample': 0.20080699828400864, 'dropout_rate': 0.1190701840217818, 'n_estimators': 62, 'learning_rate': 0.05606501535209838}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.19584167242217917
Fold 2 IBS: 0.20032782605933153
Fold 3 IBS: 0.18409232946837853
Fold 4 IBS: 0.20895490744773831
Fold 5 IBS: 0.2170463433705249
[I 2024-04-14 16:08:18,484] Trial 89 finished with value: 0.20125261575363051 and parameters: {'subsample': 0.1959461514939379, 'dropout_rate': 0.12376024494470075, 'n_estimators': 25, 'learning_rate': 0.05463186435174873}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.168554810481817
Fold 2 IBS: 0.21878241263022852
Fold 3 IBS: 0.15742067576251673
Fold 4 IBS: 0.1909121329080649
Fold 5 IBS: 0.2520803069402816
[I 2024-04-14 16:08:19,016] Trial 90 finished with value: 0.19755006774458178 and parameters: {'subsample': 0.22463799044321225, 'dropout_rate': 0.10184332440552968, 'n_estimators': 103, 'learning_rate': 0.05993410618895171}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.17885085034151246
Fold 2 IBS: 0.19807561433211526
Fold 3 IBS: 0.16273927944739283
Fold 4 IBS: 0.18551853411915184
Fold 5 IBS: 0.23396083715071678
[I 2024-04-14 16:08:19,320] Trial 91 finished with value: 0.19182902307817784 and parameters: {'subsample': 0.14946294609769428, 'dropout_rate': 0.16994050774984643, 'n_estimators': 61, 'learning_rate': 0.056940701897258014}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18081278759927133
Fold 2 IBS: 0.1994842964735639
Fold 3 IBS: 0.16302269690322507
Fold 4 IBS: 0.19321383414302545
Fold 5 IBS: 0.23196991494747476
[I 2024-04-14 16:08:19,744] Trial 92 finished with value: 0.1937007060133121 and parameters: {'subsample': 0.1781710356287671, 'dropout_rate': 0.18793622763929008, 'n_estimators': 67, 'learning_rate': 0.05206454299182245}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1665531725392152
Fold 2 IBS: 0.20894922599976265
Fold 3 IBS: 0.15804561713131163
Fold 4 IBS: 0.18666578907012443
Fold 5 IBS: 0.2430436919183764
[I 2024-04-14 16:08:20,434] Trial 93 finished with value: 0.19265149933175804 and parameters: {'subsample': 0.1187815636045847, 'dropout_rate': 0.13225198163688667, 'n_estimators': 89, 'learning_rate': 0.06096230425007871}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1833624248194524
Fold 2 IBS: 0.20031903111525967
Fold 3 IBS: 0.16381061312990267
Fold 4 IBS: 0.19345949762219866
Fold 5 IBS: 0.22888556901372928
[I 2024-04-14 16:08:20,913] Trial 94 finished with value: 0.19396742714010853 and parameters: {'subsample': 0.1562352767024428, 'dropout_rate': 0.2461010358248669, 'n_estimators': 77, 'learning_rate': 0.04237679965564273}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18329055872171077
Fold 2 IBS: 0.19418959670411348
Fold 3 IBS: 0.16747472276801725
Fold 4 IBS: 0.1921103726821279
Fold 5 IBS: 0.2264812751675906
[I 2024-04-14 16:08:21,187] Trial 95 finished with value: 0.19270930520871202 and parameters: {'subsample': 0.20353808156573844, 'dropout_rate': 0.15229505256980558, 'n_estimators': 46, 'learning_rate': 0.06421140106159287}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.20370247890423027

Fold 2 IBS: 0.2124197904403002
Fold 3 IBS: 0.19452025866502365
Fold 4 IBS: 0.21624395545790184
Fold 5 IBS: 0.21727988373559398
[I 2024-04-14 16:08:21,350] Trial 96 finished with value: 0.20883327344060998 and parameters: {'subsample': 0.14027395841703735, 'dropout_rate': 0.121620990717481, 'n_estimators': 14, 'learning_rate': 0.0457852425641791}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.19746651082582445
Fold 2 IBS: 0.20323222090294873
Fold 3 IBS: 0.1846720080714762
Fold 4 IBS: 0.21031490576039452
Fold 5 IBS: 0.2178337569161985
[I 2024-04-14 16:08:21,536] Trial 97 finished with value: 0.20270388049536853 and parameters: {'subsample': 0.16905792666412153, 'dropout_rate': 0.1895528405665567, 'n_estimators': 26, 'learning_rate': 0.049285110803541435}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.1762371567159911
Fold 2 IBS: 0.24559502511753464
Fold 3 IBS: 0.1641582028784399
Fold 4 IBS: 0.2375544451681581
Fold 5 IBS: 0.2722735472612508
[I 2024-04-14 16:08:22,062] Trial 98 finished with value: 0.21916367542827492 and parameters: {'subsample': 0.6256495106817341, 'dropout_rate': 0.16380325695073605, 'n_estimators': 108, 'learning_rate': 0.06272299374808082}. Best is trial 53 with value: 0.18917045101225236.
Fold 1 IBS: 0.18929621978363909
Fold 2 IBS: 0.20435583187243914
Fold 3 IBS: 0.17163103261265797
Fold 4 IBS: 0.20858097965364078
Fold 5 IBS: 0.2277138245400703
[I 2024-04-14 16:08:22,425] Trial 99 finished with value: 0.20031557769248948 and parameters: {'subsample': 0.7154962721440006, 'dropout_rate': 0.10063896239082133, 'n_estimators': 60, 'learning_rate': 0.03920627858987755}. Best is trial 53 with value: 0.18917045101225236.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.18917045101225236], datetime_start=datetime.datetime(2024, 4, 14, 16, 7, 54, 621718), datetime_complete=datetime.datetime(2024, 4, 14, 16, 7, 54, 982322), params={'subsample': 0.18457062310520533, 'dropout_rate': 0.10188563743505225, 'n_estimators': 68, 'learning_rate': 0.07845638174276695}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=53, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.18457062310520533, 'dropout_rate': 0.10188563743505225, 'n_estimators': 68, 'learning_rate': 0.07845638174276695}


* Best Score for IBS:
 0.18917045101225236

In [106]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [107]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.74
train_ibs:  0.189

#### Test

In [108]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [109]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.17771784288698328,
                                              learning_rate=0.06006835823961436,
                                              n_estimators=396,
                                              random_state=123,
                                              subsample=0.1001094180478445)

C-index score: 0.53

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10188563743505225,
                                              learning_rate=0.07845638174276695,
                                              n_estimators=68, random_state=123,
                                              subsample=0.18457062310520533)

IBS: 0.256

In [110]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [111]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.855   1.0
ExtraSurvivalTrees               0.848   2.0
CoxPH                            0.761   3.0
CoxElastic                       0.759   4.0
CoxLasso                         0.758   5.0
GradientBoosting                 0.740   6.5
ComponentwiseGradientBoosting    0.740   6.5
CoxRidge                         0.691   8.0

In [112]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxPH                          0.179   1.5
CoxElastic                     0.179   1.5
CoxLasso                       0.180   3.5
ExtraSurvivalTrees             0.180   3.5
Randomsurvivalforest           0.182   5.0
ComponentwiseGradientBoosting  0.189   6.0
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [113]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.643   1.0
GradientBoosting                 0.612   2.0
ExtraSurvivalTrees               0.610   3.0
CoxLasso                         0.571   4.5
CoxElastic                       0.571   4.5
CoxPH                            0.568   6.0
CoxRidge                         0.534   7.0
ComponentwiseGradientBoosting    0.530   8.0

In [114]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.206   1.0
GradientBoosting               0.220   2.0
CoxRidge                       0.221   3.0
ExtraSurvivalTrees             0.230   4.0
ComponentwiseGradientBoosting  0.256   5.0
CoxLasso                       0.275   6.5
CoxElastic                     0.275   6.5
CoxPH                          0.279   8.0

In [115]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/standard/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

modified_file_names = ['d1_os_standard_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [116]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14