In [77]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler

In [78]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [79]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [80]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [81]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [82]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [83]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [84]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [85]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [86]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [87]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [88]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [89]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [90]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [91]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [92]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [93]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [94]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [95]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.828413,0.487448,0.350904,0.000000
1,0.645006,0.388474,0.123069,0.000000
2,0.269537,0.513756,0.428640,0.066875
3,0.608721,0.273786,0.135806,0.000000
4,0.090323,0.792905,0.254489,0.386334
...,...,...,...,...
134,0.773882,0.425425,0.233413,0.000000
135,0.719008,0.796326,0.337469,0.000000
136,0.518897,0.336186,0.279727,0.000000
137,0.722831,0.825142,0.400455,0.000000
138,0.718191,0.719948,0.198096,0.000000

In [96]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [97]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.562115,0.636436,0.454371,0.050863
1,0.567520,0.084927,0.346729,0.324583
2,0.436277,0.314068,0.380947,0.110937
3,0.303383,0.235395,0.403660,0.000000
4,0.455879,0.443841,0.511695,0.000000
...,...,...,...,...
94,0.572648,0.525159,0.248406,0.000000
95,0.459472,0.292451,0.468005,0.000000
96,0.497683,0.139149,0.459798,0.000000
97,0.732079,0.366955,0.387810,0.000000
98,0.575748,0.262347,0.279146,0.000000

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [98]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:11,408] A new study created in memory with name: no-name-53d07cf2-a062-430e-a59f-b4d43c0bc3bd

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-15 13:33:11,573] A new study created in memory with name: no-name-28011d16-af58-4456-a8ef-f7dcf82e5b93

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:11,569] Trial 0 finished with value: 0.6885812252956434 and parameters: {}. Best is trial 0 with value: 0.6885812252956434.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6885812252956434], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 11, 446106), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 11, 569468), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6885812252956434

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2444511312501396
Fold 2 IBS: 0.19124878012978014
Fold 3 IBS: 0.2066529776721608
Fold 4 IBS: 0.19438765965098845
Fold 5 IBS: 0.19775948988265402
[I 2024-04-15 13:33:11,763] Trial 0 finished with value: 0.20690000771714462 and parameters: {}. Best is trial 0 with value: 0.20690000771714462.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20690000771714462], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 11, 597857), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 11, 763641), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20690000771714462

In [99]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [100]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.689
train_ibs:  0.207

#### Test

In [101]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [102]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.532
IBS score: 0.29

In [103]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [104]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [105]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:11,886] A new study created in memory with name: no-name-771e5ef1-264f-4fff-8ce3-4335089a5a0a

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.5446808510638298
Fold 4 C-index: 0.7243346007604563

[I 2024-04-15 13:33:11,991] A new study created in memory with name: no-name-659aa205-7bd7-49b2-84bb-3323b19007af

Fold 5 C-index: 0.6545064377682404
[I 2024-04-15 13:33:11,988] Trial 0 finished with value: 0.6476911903586672 and parameters: {}. Best is trial 0 with value: 0.6476911903586672.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6476911903586672], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 11, 916034), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 11, 988073), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6476911903586672

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709895823235
Fold 2 IBS: 0.23203988238189202
Fold 3 IBS: 0.22898186794169834
Fold 4 IBS: 0.24197476877861912
Fold 5 IBS: 0.2293955911760588
[I 2024-04-15 13:33:12,122] Trial 0 finished with value: 0.23592784184730015 and parameters: {}. Best is trial 0 with value: 0.23592784184730015.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784184730015], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 12, 25431), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 12, 122303), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784184730015

In [106]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [107]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.648
train_ibs:  0.236

#### Test

In [108]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [109]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [110]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [111]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:12,254] A new study created in memory with name: no-name-e6cba13a-2bdf-48df-a818-4c2ad3f45165

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872

[I 2024-04-15 13:33:12,480] A new study created in memory with name: no-name-b5702b19-36ab-4c81-bd31-f98138e9d60d

Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:12,474] Trial 0 finished with value: 0.6910259146234387 and parameters: {}. Best is trial 0 with value: 0.6910259146234387.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6910259146234387], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 12, 284693), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 12, 474642), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6910259146234387

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24327474589214967
Fold 2 IBS: 0.19124193562772077
Fold 3 IBS: 0.20659154302819144
Fold 4 IBS: 0.19431608966437242
Fold 5 IBS: 0.1985649880350335
[I 2024-04-15 13:33:12,721] Trial 0 finished with value: 0.20679786044949355 and parameters: {}. Best is trial 0 with value: 0.20679786044949355.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20679786044949355], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 12, 515995), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 12, 721195), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20679786044949355

In [112]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [113]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.691
train_ibs:  0.207

#### Test

In [114]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [115]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.288

In [116]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [117]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:12,891] A new study created in memory with name: no-name-01fc6c22-aef1-431c-a898-837d737eea3a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:13,113] Trial 0 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:13,392] Trial 1 finished with value: 0.6925763022203378 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:13,529] Trial 2 finished with value: 0.6634233210699454 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:13,719] Trial 3 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:13,887] Trial 4 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:14,090] Trial 5 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:14,235] Trial 6 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:14,405] Trial 7 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:14,592] Trial 8 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:14,847] Trial 9 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 13:33:14,987] Trial 10 finished with value: 0.6591966128500061 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:15,171] Trial 11 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9201080639320232}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:15,347] Trial 12 finished with value: 0.6687465149862952 and parameters: {'l1_ratio': 0.2673642615442958}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 13:33:15,462] Trial 13 finished with value: 0.6607686193974597 and parameters: {'l1_ratio': 0.0077734502164144015}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:15,673] Trial 14 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6491253666199541}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:15,898] Trial 15 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.820763570686791}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:16,061] Trial 16 finished with value: 0.6687465149862952 and parameters: {'l1_ratio': 0.28231336480419766}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:16,246] Trial 17 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5632480038685016}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:16,419] Trial 18 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:33:16,479] Trial 19 finished with value: 0.6577225191275006 and parameters: {'l1_ratio': 0.1494206751758108}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:16,640] Trial 20 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3233028475837619}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:16,810] Trial 21 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5622777690744459}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:16,993] Trial 22 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5331849871831229}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:17,138] Trial 23 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6499003388704403}. Best is trial 1 with value: 0.6925763022203378.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:17,285] Trial 24 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3856495824719821}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:17,438] Trial 25 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8000279351376395}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:17,585] Trial 26 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.43696099753129897}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:17,736] Trial 27 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5969497812757416}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:17,921] Trial 28 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7573102579397951}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:33:17,992] Trial 29 finished with value: 0.6617065828725205 and parameters: {'l1_ratio': 0.18481656054890608}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:18,141] Trial 30 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3294713808933716}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:18,349] Trial 31 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7032584980203591}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:18,547] Trial 32 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7635787813571397}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:18,684] Trial 33 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9061337786354179}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:18,816] Trial 34 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5000225785522213}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:18,939] Trial 35 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7114643040644401}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,061] Trial 36 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6180670107796105}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,192] Trial 37 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.45489737543976694}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,319] Trial 38 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8598478847078105}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,433] Trial 39 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7304824129775314}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,540] Trial 40 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9946867502518267}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,675] Trial 41 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4287851816179317}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,822] Trial 42 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.36983822541108524}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:19,941] Trial 43 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6593157802327292}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:20,025] Trial 44 finished with value: 0.6634233210699454 and parameters: {'l1_ratio': 0.22398271644938825}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:20,149] Trial 45 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:20,287] Trial 46 finished with value: 0.6925763022203378 and parameters: {'l1_ratio': 0.28435427399729335}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 13:33:20,363] Trial 47 finished with value: 0.6591966128500061 and parameters: {'l1_ratio': 0.09816421970438904}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734

Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:20,533] Trial 48 finished with value: 0.6687465149862952 and parameters: {'l1_ratio': 0.2629781061488513}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 13:33:20,601] Trial 49 finished with value: 0.6607686193974597 and parameters: {'l1_ratio': 0.005040986123852953}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:20,791] Trial 50 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:21,088] Trial 51 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.29612836561483324}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:21,384] Trial 52 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.345263636579629}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:21,501] Trial 53 finished with value: 0.6634233210699454 and parameters: {'l1_ratio': 0.22305038053665238}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:21,670] Trial 54 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4683516979738161}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:21,878] Trial 55 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.40796770836376417}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:22,056] Trial 56 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5348068348499613}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:22,233] Trial 57 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6810107592090933}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:33:22,334] Trial 58 finished with value: 0.6617065828725205 and parameters: {'l1_ratio': 0.15943922435683724}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:22,465] Trial 59 finished with value: 0.6687465149862952 and parameters: {'l1_ratio': 0.25791627129284084}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:22,661] Trial 60 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.357792062603722}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:22,823] Trial 61 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9971193647889539}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:22,978] Trial 62 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8541732009658233}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:23,149] Trial 63 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3172859166737711}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:23,379] Trial 64 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9205663171806863}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:23,551] Trial 65 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5786834797386848}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:23,698] Trial 66 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7632662481673134}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:23,830] Trial 67 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9546530799943637}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:23,959] Trial 68 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6329887731681333}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:24,107] Trial 69 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.497018069514667}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:24,269] Trial 70 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.40589920141435076}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:24,402] Trial 71 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7943443028315524}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877

Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:24,557] Trial 72 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8377758269482638}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:24,724] Trial 73 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6947435097383032}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:24,932] Trial 74 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7419959508923244}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:25,078] Trial 75 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6756534066501407}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 13:33:25,172] Trial 76 finished with value: 0.6599718066484557 and parameters: {'l1_ratio': 0.060427199925031955}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:25,420] Trial 77 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5600928221097465}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:25,587] Trial 78 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6317821511880367}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:25,737] Trial 79 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7171976373603456}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:25,832] Trial 80 finished with value: 0.6634233210699454 and parameters: {'l1_ratio': 0.20601580810919382}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:25,983] Trial 81 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.45722535174750273}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:26,147] Trial 82 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5233803160109376}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:26,291] Trial 83 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4900498403177628}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:26,417] Trial 84 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8892496262501571}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:26,566] Trial 85 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3064634234356415}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:26,707] Trial 86 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.38373358247881845}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:26,844] Trial 87 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.42644475732404274}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:26,985] Trial 88 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5442736935441954}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:27,117] Trial 89 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5890853218918972}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:27,243] Trial 90 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7797464722784435}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:27,384] Trial 91 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.34110764327127996}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:27,519] Trial 92 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4708995243924413}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:27,625] Trial 93 finished with value: 0.6687465149862952 and parameters: {'l1_ratio': 0.2527263231504453}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:27,766] Trial 94 finished with value: 0.6925763022203378 and parameters: {'l1_ratio': 0.29171158716817186}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:27,905] Trial 95 finished with value: 0.6925763022203378 and parameters: {'l1_ratio': 0.2840130542524089}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:33:27,972] Trial 96 finished with value: 0.6617065828725205 and parameters: {'l1_ratio': 0.18210266400668104}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734

Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:28,094] Trial 97 finished with value: 0.6925763022203378 and parameters: {'l1_ratio': 0.2848640622236047}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:28,221] Trial 98 finished with value: 0.6925763022203378 and parameters: {'l1_ratio': 0.2843919350911006}. Best is trial 1 with value: 0.6925763022203378.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6808510638297872

[I 2024-04-15 13:33:28,357] A new study created in memory with name: no-name-626e8e86-2006-42c5-ac19-5bb36141e101

Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:28,352] Trial 99 finished with value: 0.6925763022203378 and parameters: {'l1_ratio': 0.28611688219005543}. Best is trial 1 with value: 0.6925763022203378.


* Best trial for C-index:
 FrozenTrial(number=1, state=TrialState.COMPLETE, values=[0.6925763022203378], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 13, 115264), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 13, 392500), params={'l1_ratio': 0.28621072101688444}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=1, value=None)


* Best Score for C-index:
 0.6925763022203378

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24346704604704877
Fold 2 IBS: 0.19111872569472418
Fold 3 IBS: 0.20600858708655184
Fold 4 IBS: 0.1941307581219963
Fold 5 IBS: 0.19818777104825638
[I 2024-04-15 13:33:28,519] Trial 0 finished with value: 0.2065825775997155 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2065825775997155.
Fold 1 IBS: 0.2436561534893646
Fold 2 IBS: 0.22555923310558854
Fold 3 IBS: 0.20542452204756903
Fold 4 IBS: 0.19394964500544354
Fold 5 IBS: 0.1979325614057397
[I 2024-04-15 13:33:28,660] Trial 1 finished with value: 0.2133044230107411 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.2065825775997155.
Fold 1 IBS: 0.24369121579073802
Fold 2 IBS: 0.22695059901402637
Fold 3 IBS: 0.22875723206890197
Fold 4 IBS: 0.23582102158769938
Fold 5 IBS: 0.19789779493852902
[I 2024-04-15 13:33:28,766] Trial 2 finished with value: 0.22662357267997896 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.2065825775997155.
Fold 1 IBS: 0.24358841027247194
Fold 2 IBS: 0.1910689492848215
Fold 3 IBS: 0.2057766805136806
Fold 4 IBS: 0.19405854064932443
Fold 5 IBS: 0.1980887580182906
[I 2024-04-15 13:33:28,915] Trial 3 finished with value: 0.20651626774771784 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.20651626774771784.
Fold 1 IBS: 0.24349875293607634
Fold 2 IBS: 0.19112169512135274
Fold 3 IBS: 0.20607045215182898
Fold 4 IBS: 0.19413144242186595
Fold 5 IBS: 0.19818691448874434
[I 2024-04-15 13:33:29,056] Trial 4 finished with value: 0.20660185142397366 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 3 with value: 0.20651626774771784.
Fold 1 IBS: 0.24359819724718929
Fold 2 IBS: 0.19102430078860902
Fold 3 IBS: 0.2056586234167161
Fold 4 IBS: 0.19399244904142246
Fold 5 IBS: 0.19801653463050664
[I 2024-04-15 13:33:29,206] Trial 5 finished with value: 0.2064580210248887 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 5 with value: 0.2064580210248887.
Fold 1 IBS: 0.24335545798842206
Fold 2 IBS: 0.19123329897999874
Fold 3 IBS: 0.20654734788901066
Fold 4 IBS: 0.19430298626028736
Fold 5 IBS: 0.19853482376124854
[I 2024-04-15 13:33:29,337] Trial 6 finished with value: 0.20679478297579346 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 5 with value: 0.2064580210248887.
Fold 1 IBS: 0.2434501697101265
Fold 2 IBS: 0.1911122199349228
Fold 3 IBS: 0.20597588302059666
Fold 4 IBS: 0.19411985143327914
Fold 5 IBS: 0.19818824692413556
[I 2024-04-15 13:33:29,483] Trial 7 finished with value: 0.20656927420461213 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 5 with value: 0.2064580210248887.
Fold 1 IBS: 0.24362789423784617
Fold 2 IBS: 0.19105149522613576
Fold 3 IBS: 0.2056988060372193
Fold 4 IBS: 0.19400428360277788
Fold 5 IBS: 0.19803666899311542
[I 2024-04-15 13:33:29,631] Trial 8 finished with value: 0.2064838296194189 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 5 with value: 0.2064580210248887.
Fold 1 IBS: 0.24361180499342744
Fold 2 IBS: 0.19101655051729743
Fold 3 IBS: 0.20562668586155233
Fold 4 IBS: 0.19398200647296007
Fold 5 IBS: 0.1979963485373367
[I 2024-04-15 13:33:29,779] Trial 9 finished with value: 0.20644667927651478 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 9 with value: 0.20644667927651478.
Fold 1 IBS: 0.24579036515474298
Fold 2 IBS: 0.22988987612836911
Fold 3 IBS: 0.22886652187145956
Fold 4 IBS: 0.23933060974581402
Fold 5 IBS: 0.22754742095595776
[I 2024-04-15 13:33:29,846] Trial 10 finished with value: 0.23428495877126868 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 9 with value: 0.20644667927651478.
Fold 1 IBS: 0.24364703796178697
Fold 2 IBS: 0.19101902017426925
Fold 3 IBS: 0.20554850507888492
Fold 4 IBS: 0.19395295742318905
Fold 5 IBS: 0.19797680201814155
[I 2024-04-15 13:33:29,998] Trial 11 finished with value: 0.20642886453125434 and parameters: {'l1_ratio': 0.3734960813237434}. Best is trial 11 with value: 0.20642886453125434.
Fold 1 IBS: 0.24362511027302294
Fold 2 IBS: 0.19099873743403406
Fold 3 IBS: 0.20555143828974243
Fold 4 IBS: 0.19395655597567374
Fold 5 IBS: 0.19796200205743025
[I 2024-04-15 13:33:30,164] Trial 12 finished with value: 0.2064187688059807 and parameters: {'l1_ratio': 0.3312630748631684}. Best is trial 12 with value: 0.2064187688059807.
Fold 1 IBS: 0.2470988984099833
Fold 2 IBS: 0.231824865743009
Fold 3 IBS: 0.22896921216127397
Fold 4 IBS: 0.24170763198947345
Fold 5 IBS: 0.2292090123068581
[I 2024-04-15 13:33:30,234] Trial 13 finished with value: 0.23576192412211955 and parameters: {'l1_ratio': 0.009953525145330822}. Best is trial 12 with value: 0.2064187688059807.
Fold 1 IBS: 0.24372047913948394
Fold 2 IBS: 0.2267334154891387
Fold 3 IBS: 0.2287518395783406
Fold 4 IBS: 0.23556713469941312
Fold 5 IBS: 0.1979100995029003
[I 2024-04-15 13:33:30,341] Trial 14 finished with value: 0.22653659368185536 and parameters: {'l1_ratio': 0.23625082181647747}. Best is trial 12 with value: 0.2064187688059807.
Fold 1 IBS: 0.2436692747795524
Fold 2 IBS: 0.19100699324430745
Fold 3 IBS: 0.20549468523797548
Fold 4 IBS: 0.19393538577773975
Fold 5 IBS: 0.19794498668160992
[I 2024-04-15 13:33:30,511] Trial 15 finished with value: 0.206410265144237 and parameters: {'l1_ratio': 0.3193904340156382}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24369475576419083
Fold 2 IBS: 0.22820468715307435
Fold 3 IBS: 0.2287960332982719
Fold 4 IBS: 0.23730225415482556
Fold 5 IBS: 0.22612691319800074
[I 2024-04-15 13:33:30,598] Trial 16 finished with value: 0.2328249287136727 and parameters: {'l1_ratio': 0.17257048013641663}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24352690629895735
Fold 2 IBS: 0.19107700282444887
Fold 3 IBS: 0.20581682680473168
Fold 4 IBS: 0.19404439790944475
Fold 5 IBS: 0.1980879728556227
[I 2024-04-15 13:33:30,771] Trial 17 finished with value: 0.20651062133864104 and parameters: {'l1_ratio': 0.5638983100794804}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24363933412578184
Fold 2 IBS: 0.19099451142034268
Fold 3 IBS: 0.20553480541263566
Fold 4 IBS: 0.19395150131141084
Fold 5 IBS: 0.19794669775821172
[I 2024-04-15 13:33:30,980] Trial 18 finished with value: 0.20641337000567656 and parameters: {'l1_ratio': 0.3073564564111171}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.2453537049445623
Fold 2 IBS: 0.2292278472973773
Fold 3 IBS: 0.22883652488575718
Fold 4 IBS: 0.23852884627687085
Fold 5 IBS: 0.22698625797573505
[I 2024-04-15 13:33:31,056] Trial 19 finished with value: 0.23378663627606056 and parameters: {'l1_ratio': 0.1275121346517459}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.2433791854514087
Fold 2 IBS: 0.19120481314076349
Fold 3 IBS: 0.2064120356301871
Fold 4 IBS: 0.19426468540372907
Fold 5 IBS: 0.19849838963599947
[I 2024-04-15 13:33:31,195] Trial 20 finished with value: 0.20675182185241758 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24362857106845062
Fold 2 IBS: 0.19100017534637032
Fold 3 IBS: 0.20555799807194697
Fold 4 IBS: 0.19395900237431415
Fold 5 IBS: 0.1979618054090644
[I 2024-04-15 13:33:31,418] Trial 21 finished with value: 0.20642151045402932 and parameters: {'l1_ratio': 0.33268751643603356}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24369868959111277
Fold 2 IBS: 0.19098951601079678
Fold 3 IBS: 0.20551203439412224
Fold 4 IBS: 0.1939429943809015
Fold 5 IBS: 0.19794739544615841
[I 2024-04-15 13:33:31,648] Trial 22 finished with value: 0.20641812596461834 and parameters: {'l1_ratio': 0.3027602170102355}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24361248136203417
Fold 2 IBS: 0.19104502231416085
Fold 3 IBS: 0.20566666343649573
Fold 4 IBS: 0.19402462327679987
Fold 5 IBS: 0.19803738859251094
[I 2024-04-15 13:33:31,853] Trial 23 finished with value: 0.2064772357964003 and parameters: {'l1_ratio': 0.4720557046621332}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24680624923912303
Fold 2 IBS: 0.23139785682478836
Fold 3 IBS: 0.22894477208068548
Fold 4 IBS: 0.2411790224532862
Fold 5 IBS: 0.2288397489428622
[I 2024-04-15 13:33:31,924] Trial 24 finished with value: 0.23543352990814906 and parameters: {'l1_ratio': 0.02961969462146219}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24371790214586422

Fold 2 IBS: 0.22675322787093563
Fold 3 IBS: 0.2287523143790381
Fold 4 IBS: 0.23559026194922902
Fold 5 IBS: 0.1979102750890993
[I 2024-04-15 13:33:32,118] Trial 25 finished with value: 0.22654479628683327 and parameters: {'l1_ratio': 0.2354015085405634}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.2437260804372543
Fold 2 IBS: 0.22802890772770576
Fold 3 IBS: 0.2287898443018471
Fold 4 IBS: 0.23709312224879853
Fold 5 IBS: 0.22598028522086833
[I 2024-04-15 13:33:32,350] Trial 26 finished with value: 0.2327236479872948 and parameters: {'l1_ratio': 0.1802457489939742}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24355884024356472
Fold 2 IBS: 0.19107607756683415
Fold 3 IBS: 0.20580695943058178
Fold 4 IBS: 0.1940669657408476
Fold 5 IBS: 0.19811918663666345
[I 2024-04-15 13:33:32,526] Trial 27 finished with value: 0.20652560592369834 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 15 with value: 0.206410265144237.
Fold 1 IBS: 0.24369023977189563
Fold 2 IBS: 0.19098569914217464
Fold 3 IBS: 0.20549461468891922
Fold 4 IBS: 0.1939364857026815
Fold 5 IBS: 0.19793059016395306
[I 2024-04-15 13:33:32,711] Trial 28 finished with value: 0.2064075258939248 and parameters: {'l1_ratio': 0.2993283502508602}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.24362755359084057
Fold 2 IBS: 0.19103656874972688
Fold 3 IBS: 0.20562862371296578
Fold 4 IBS: 0.194013226922654
Fold 5 IBS: 0.19801506154597545
[I 2024-04-15 13:33:32,901] Trial 29 finished with value: 0.20646420690443254 and parameters: {'l1_ratio': 0.4384701571835793}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.2434893783634529
Fold 2 IBS: 0.19110370031566473
Fold 3 IBS: 0.20593946789354442
Fold 4 IBS: 0.19410959750470363
Fold 5 IBS: 0.19815107784677666
[I 2024-04-15 13:33:33,071] Trial 30 finished with value: 0.2065586443848285 and parameters: {'l1_ratio': 0.6506168853966119}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.24369517097278637
Fold 2 IBS: 0.1909879256629596
Fold 3 IBS: 0.20550477846256132
Fold 4 IBS: 0.1939402833795135
Fold 5 IBS: 0.19793031105963219
[I 2024-04-15 13:33:33,295] Trial 31 finished with value: 0.20641169390749062 and parameters: {'l1_ratio': 0.3013220087820099}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.2437018817916121
Fold 2 IBS: 0.22577295642972822
Fold 3 IBS: 0.22873313106211887
Fold 4 IBS: 0.1939317681989306
Fold 5 IBS: 0.19793406507828806
[I 2024-04-15 13:33:33,453] Trial 32 finished with value: 0.21801476051213559 and parameters: {'l1_ratio': 0.2771705397587284}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.2436428402194261
Fold 2 IBS: 0.1910172647571866
Fold 3 IBS: 0.20553982606087187
Fold 4 IBS: 0.19398571257223682
Fold 5 IBS: 0.19797702620528598
[I 2024-04-15 13:33:33,691] Trial 33 finished with value: 0.20643253396300146 and parameters: {'l1_ratio': 0.3715219502155773}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.24369272582947715
Fold 2 IBS: 0.2282155686196726
Fold 3 IBS: 0.22879642409526105
Fold 4 IBS: 0.237315216031063
Fold 5 IBS: 0.22613599999763098
[I 2024-04-15 13:33:33,905] Trial 34 finished with value: 0.23283118691462096 and parameters: {'l1_ratio': 0.17209473006093354}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.24367967440606447
Fold 2 IBS: 0.2265248860699335
Fold 3 IBS: 0.22874705404240434
Fold 4 IBS: 0.23532412613389844
Fold 5 IBS: 0.197908358607842
[I 2024-04-15 13:33:34,073] Trial 35 finished with value: 0.22643681985202857 and parameters: {'l1_ratio': 0.245176972469606}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.24609353877661072
Fold 2 IBS: 0.23034438938867868
Fold 3 IBS: 0.2288887134461535
Fold 4 IBS: 0.23988457076532552
Fold 5 IBS: 0.22793491764968296
[I 2024-04-15 13:33:34,166] Trial 36 finished with value: 0.2346292260052903 and parameters: {'l1_ratio': 0.07755657280239842}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.24342588582824073
Fold 2 IBS: 0.1911572785879456
Fold 3 IBS: 0.20618835680731465
Fold 4 IBS: 0.1941864883423039
Fold 5 IBS: 0.19832437231693834
[I 2024-04-15 13:33:34,326] Trial 37 finished with value: 0.20665647637654866 and parameters: {'l1_ratio': 0.8013809955909406}. Best is trial 28 with value: 0.2064075258939248.
Fold 1 IBS: 0.24368043400349923
Fold 2 IBS: 0.19100239691583656
Fold 3 IBS: 0.2054744216124536
Fold 4 IBS: 0.19392893980140266
Fold 5 IBS: 0.1979311497252607
[I 2024-04-15 13:33:34,516] Trial 38 finished with value: 0.20640346841169058 and parameters: {'l1_ratio': 0.29543822482619353}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24364277798565562
Fold 2 IBS: 0.1910429606087198
Fold 3 IBS: 0.20566029631315297
Fold 4 IBS: 0.1939915942211594
Fold 5 IBS: 0.1980143190087055
[I 2024-04-15 13:33:34,686] Trial 39 finished with value: 0.20647038962747866 and parameters: {'l1_ratio': 0.44683149679361134}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24353755248922557
Fold 2 IBS: 0.1910632462051485
Fold 3 IBS: 0.2057529756373032
Fold 4 IBS: 0.1940226295193587
Fold 5 IBS: 0.19806107844397805
[I 2024-04-15 13:33:34,880] Trial 40 finished with value: 0.2064874964590028 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24366934927681236
Fold 2 IBS: 0.19100702439934975
Fold 3 IBS: 0.20549483876754213
Fold 4 IBS: 0.19393544305914595
Fold 5 IBS: 0.19794498249479764
[I 2024-04-15 13:33:35,087] Trial 41 finished with value: 0.20641032759952957 and parameters: {'l1_ratio': 0.31942150097804134}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436033886515159
Fold 2 IBS: 0.1910130483282028
Fold 3 IBS: 0.20561067138790617
Fold 4 IBS: 0.1939760574527494
Fold 5 IBS: 0.19799679686008562
[I 2024-04-15 13:33:35,252] Trial 42 finished with value: 0.20643999253609197 and parameters: {'l1_ratio': 0.38821423483473705}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24366179173711175
Fold 2 IBS: 0.225509670764272
Fold 3 IBS: 0.20543609650175385
Fold 4 IBS: 0.19395363632332827
Fold 5 IBS: 0.1979322302756625
[I 2024-04-15 13:33:35,409] Trial 43 finished with value: 0.21329868512042566 and parameters: {'l1_ratio': 0.2883038479170603}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24369042451746087
Fold 2 IBS: 0.2274223846703942
Fold 3 IBS: 0.22877033493892696
Fold 4 IBS: 0.23637526657553237
Fold 5 IBS: 0.1978888894203404
[I 2024-04-15 13:33:35,526] Trial 44 finished with value: 0.22682946002453094 and parameters: {'l1_ratio': 0.2065870163402241}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24361487152196482
Fold 2 IBS: 0.19100560820091708
Fold 3 IBS: 0.20557988609042618
Fold 4 IBS: 0.1939659235494675
Fold 5 IBS: 0.19797854835380854
[I 2024-04-15 13:33:35,697] Trial 45 finished with value: 0.2064289675433168 and parameters: {'l1_ratio': 0.35886184107639624}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24358751845337898
Fold 2 IBS: 0.1910198568278485
Fold 3 IBS: 0.2056382666072696
Fold 4 IBS: 0.19398490354065853
Fold 5 IBS: 0.19799373781555263
[I 2024-04-15 13:33:35,862] Trial 46 finished with value: 0.2064448566489417 and parameters: {'l1_ratio': 0.4178465972493743}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24546323136850004
Fold 2 IBS: 0.22939475964737183
Fold 3 IBS: 0.22884381861886935
Fold 4 IBS: 0.23873040451608374
Fold 5 IBS: 0.22712736917002535
[I 2024-04-15 13:33:35,933] Trial 47 finished with value: 0.23391191666417005 and parameters: {'l1_ratio': 0.12009766830555532}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24370314345193675
Fold 2 IBS: 0.22576167214787304
Fold 3 IBS: 0.228732963327752
Fold 4 IBS: 0.19393274008199027
Fold 5 IBS: 0.1979339818769961
[I 2024-04-15 13:33:36,056] Trial 48 finished with value: 0.21801290017730962 and parameters: {'l1_ratio': 0.2776484276846111}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.243612078243957
Fold 2 IBS: 0.1910610815920077
Fold 3 IBS: 0.20574221184240488
Fold 4 IBS: 0.1940486151965619
Fold 5 IBS: 0.19806130310404318
[I 2024-04-15 13:33:36,229] Trial 49 finished with value: 0.20650505799579494 and parameters: {'l1_ratio': 0.5172813558648697}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24363359948822083
Fold 2 IBS: 0.1910022664612067

Fold 3 IBS: 0.2055675332348129
Fold 4 IBS: 0.19396255820054176
Fold 5 IBS: 0.1979615210358094
[I 2024-04-15 13:33:36,413] Trial 50 finished with value: 0.20642549568411833 and parameters: {'l1_ratio': 0.3347781725956745}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436267647873312
Fold 2 IBS: 0.1909994247303081
Fold 3 IBS: 0.2055545740659544
Fold 4 IBS: 0.19395772544342527
Fold 5 IBS: 0.19796190795053162
[I 2024-04-15 13:33:36,593] Trial 51 finished with value: 0.20642007939551013 and parameters: {'l1_ratio': 0.33194260491009325}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24371349079799468
Fold 2 IBS: 0.2262549590373793
Fold 3 IBS: 0.2287414448160795
Fold 4 IBS: 0.19392825456918603
Fold 5 IBS: 0.197921385531121
[I 2024-04-15 13:33:36,758] Trial 52 finished with value: 0.2181119069503521 and parameters: {'l1_ratio': 0.25669632246926505}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436833011970229
Fold 2 IBS: 0.22746792328057966
Fold 3 IBS: 0.2287716976379011
Fold 4 IBS: 0.23642895880528375
Fold 5 IBS: 0.1978893316114223
[I 2024-04-15 13:33:36,892] Trial 53 finished with value: 0.22684824250644192 and parameters: {'l1_ratio': 0.20461679469893446}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2437037473733977
Fold 2 IBS: 0.19099180287424153
Fold 3 IBS: 0.20552246264435145
Fold 4 IBS: 0.1939468903986871
Fold 5 IBS: 0.1979470719063931
[I 2024-04-15 13:33:37,073] Trial 54 finished with value: 0.20642239503941417 and parameters: {'l1_ratio': 0.3048493703575314}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24365628105233705
Fold 2 IBS: 0.19101699161892308
Fold 3 IBS: 0.20562512884087208
Fold 4 IBS: 0.1939800332521691
Fold 5 IBS: 0.19799405381912683
[I 2024-04-15 13:33:37,240] Trial 55 finished with value: 0.20645449771668564 and parameters: {'l1_ratio': 0.41447904447233064}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24501311163356648
Fold 2 IBS: 0.2287049188064231
Fold 3 IBS: 0.2288149007711654
Fold 4 IBS: 0.2378999935575287
Fold 5 IBS: 0.2265458212242961
[I 2024-04-15 13:33:37,316] Trial 56 finished with value: 0.23339574919859593 and parameters: {'l1_ratio': 0.15062396310111906}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24364514291490988
Fold 2 IBS: 0.19099692685828953
Fold 3 IBS: 0.20554580486896876
Fold 4 IBS: 0.1939556100561524
Fold 5 IBS: 0.1979463613623962
[I 2024-04-15 13:33:37,490] Trial 57 finished with value: 0.20641796921214337 and parameters: {'l1_ratio': 0.30962275173765286}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436711090944452
Fold 2 IBS: 0.19099820331885978
Fold 3 IBS: 0.20554602272442254
Fold 4 IBS: 0.19395331616676406
Fold 5 IBS: 0.19795945017109418
[I 2024-04-15 13:33:37,654] Trial 58 finished with value: 0.20642562029511718 and parameters: {'l1_ratio': 0.3512032264093591}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2435993754141703
Fold 2 IBS: 0.19103953450714148
Fold 3 IBS: 0.20563937804580174
Fold 4 IBS: 0.1940153437248533
Fold 5 IBS: 0.19803801223019785
[I 2024-04-15 13:33:37,824] Trial 59 finished with value: 0.2064663287844329 and parameters: {'l1_ratio': 0.46470933555270993}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24372399768895667
Fold 2 IBS: 0.227195500067204
Fold 3 IBS: 0.228763800316785
Fold 4 IBS: 0.2361082654601227
Fold 5 IBS: 0.19790003891218513
[I 2024-04-15 13:33:37,975] Trial 60 finished with value: 0.22673832048905074 and parameters: {'l1_ratio': 0.21638531727342925}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24364274420548368
Fold 2 IBS: 0.1909959290558054
Fold 3 IBS: 0.20554126193050773
Fold 4 IBS: 0.19395391312321825
Fold 5 IBS: 0.19794650001668695
[I 2024-04-15 13:33:38,150] Trial 61 finished with value: 0.2064160696663404 and parameters: {'l1_ratio': 0.30868303274016934}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24371805726997478
Fold 2 IBS: 0.22621655509102084
Fold 3 IBS: 0.22874070146693895
Fold 4 IBS: 0.19393177460329558
Fold 5 IBS: 0.19792108047696458
[I 2024-04-15 13:33:38,280] Trial 62 finished with value: 0.21810563378163894 and parameters: {'l1_ratio': 0.2583320804553656}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24362278923843747
Fold 2 IBS: 0.1910211305911053
Fold 3 IBS: 0.20555568412208025
Fold 4 IBS: 0.19398977698375777
Fold 5 IBS: 0.19799577016862144
[I 2024-04-15 13:33:38,447] Trial 63 finished with value: 0.20643703022080043 and parameters: {'l1_ratio': 0.39746956799055455}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24369074922127362
Fold 2 IBS: 0.19098592904352676
Fold 3 IBS: 0.2054956644461199
Fold 4 IBS: 0.1939368779551279
Fold 5 IBS: 0.19793056125824846
[I 2024-04-15 13:33:38,620] Trial 64 finished with value: 0.20640795638485931 and parameters: {'l1_ratio': 0.2995331443939786}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24364067638305453
Fold 2 IBS: 0.1910163604841981
Fold 3 IBS: 0.2055353539266178
Fold 4 IBS: 0.19398417988880964
Fold 5 IBS: 0.19797714220329418
[I 2024-04-15 13:33:38,781] Trial 65 finished with value: 0.20643074257719488 and parameters: {'l1_ratio': 0.3705121118759005}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24371781604997197
Fold 2 IBS: 0.22621859597000157
Fold 3 IBS: 0.2287407406235409
Fold 4 IBS: 0.1939315886182236
Fold 5 IBS: 0.19792109655229814
[I 2024-04-15 13:33:38,989] Trial 66 finished with value: 0.21810596756280726 and parameters: {'l1_ratio': 0.25824517195500296}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24371526272499563
Fold 2 IBS: 0.22769441625915907
Fold 3 IBS: 0.22877872447281403
Fold 4 IBS: 0.23669650428307176
Fold 5 IBS: 0.19787919389756134
[I 2024-04-15 13:33:39,123] Trial 67 finished with value: 0.22695282032752034 and parameters: {'l1_ratio': 0.19479961939683577}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24511035867750083
Fold 2 IBS: 0.2288548419256648
Fold 3 IBS: 0.22882090643479464
Fold 4 IBS: 0.23807987395930283
Fold 5 IBS: 0.22667183409996164
[I 2024-04-15 13:33:39,196] Trial 68 finished with value: 0.23350756301944492 and parameters: {'l1_ratio': 0.14401579991535457}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2462716666604628
Fold 2 IBS: 0.2306095948351588
Fold 3 IBS: 0.22890223337321638
Fold 4 IBS: 0.2402090848696544
Fold 5 IBS: 0.22816183608692575
[I 2024-04-15 13:33:39,265] Trial 69 finished with value: 0.23483088316508366 and parameters: {'l1_ratio': 0.06556425130530535}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2437065205312698
Fold 2 IBS: 0.22683917165029868
Fold 3 IBS: 0.22875441397623253
Fold 4 IBS: 0.23569066299769126
Fold 5 IBS: 0.1978968632670383
[I 2024-04-15 13:33:39,376] Trial 70 finished with value: 0.2265775264845061 and parameters: {'l1_ratio': 0.2317147771325052}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24367546215340466
Fold 2 IBS: 0.19100958248737626
Fold 3 IBS: 0.20550744128846465
Fold 4 IBS: 0.19394014481364605
Fold 5 IBS: 0.19794464013951515
[I 2024-04-15 13:33:39,600] Trial 71 finished with value: 0.20641545417648138 and parameters: {'l1_ratio': 0.3219905892665191}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24369316297957605
Fold 2 IBS: 0.1909971029675244
Fold 3 IBS: 0.20554397872191893
Fold 4 IBS: 0.1939537738711069
Fold 5 IBS: 0.19796222668308458
[I 2024-04-15 13:33:39,797] Trial 72 finished with value: 0.20643004904464218 and parameters: {'l1_ratio': 0.329656763263143}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24370550136217736
Fold 2 IBS: 0.2257404783955907
Fold 3 IBS: 0.22873265168561602
Fold 4 IBS: 0.1939345567742598
Fold 5 IBS: 0.19793382670090456
[I 2024-04-15 13:33:39,938] Trial 73 finished with value: 0.2180094029837097 and parameters: {'l1_ratio': 0.2785458049703867}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.243616598644086
Fold 2 IBS: 0.1910185480147518
Fold 3 IBS: 0.205635813114875
Fold 4 IBS: 0.1939853967239014
Fold 5 IBS: 0.19799609519205214
[I 2024-04-15 13:33:40,107] Trial 74 finished with value: 0.20645049033793325 and parameters: {'l1_ratio': 0.39447082884451984}. Best is trial 38 with value: 0.20640346841169058.

Fold 1 IBS: 0.24366472796576338
Fold 2 IBS: 0.1910152609366343
Fold 3 IBS: 0.20553283565862954
Fold 4 IBS: 0.19394840577468178
Fold 5 IBS: 0.1979597961934454
[I 2024-04-15 13:33:40,285] Trial 75 finished with value: 0.2064242053058309 and parameters: {'l1_ratio': 0.34830106369663216}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24364576255356746
Fold 2 IBS: 0.19099718469457486
Fold 3 IBS: 0.20554697858455104
Fold 4 IBS: 0.19395604846742018
Fold 5 IBS: 0.19794632560411193
[I 2024-04-15 13:33:40,461] Trial 76 finished with value: 0.2064184599808451 and parameters: {'l1_ratio': 0.3098663919454113}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24369113096869818
Fold 2 IBS: 0.22695120380877024
Fold 3 IBS: 0.228757247658077
Fold 4 IBS: 0.2358217297094029
Fold 5 IBS: 0.19789780014323363
[I 2024-04-15 13:33:40,569] Trial 77 finished with value: 0.2266238224576364 and parameters: {'l1_ratio': 0.22690277246993334}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24370384569852635
Fold 2 IBS: 0.22575537439124968
Fold 3 IBS: 0.22873287026037253
Fold 4 IBS: 0.1939332810928605
Fold 5 IBS: 0.19793393561817735
[I 2024-04-15 13:33:40,695] Trial 78 finished with value: 0.21801186141223727 and parameters: {'l1_ratio': 0.27791510865143626}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24362247455797975
Fold 2 IBS: 0.19103444084790613
Fold 3 IBS: 0.205618070114835
Fold 4 IBS: 0.19400962840513827
Fold 5 IBS: 0.19801531245532591
[I 2024-04-15 13:33:40,867] Trial 79 finished with value: 0.20645998527623705 and parameters: {'l1_ratio': 0.4357468969211574}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.243560219132458
Fold 2 IBS: 0.19103937515963726
Fold 3 IBS: 0.2057195102904563
Fold 4 IBS: 0.1940119197628212
Fold 5 IBS: 0.1980362140968318
[I 2024-04-15 13:33:41,032] Trial 80 finished with value: 0.2064734476884409 and parameters: {'l1_ratio': 0.4868984507225738}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436534395197499
Fold 2 IBS: 0.19100038193835747
Fold 3 IBS: 0.20546208164618499
Fold 4 IBS: 0.1939614820602585
Fold 5 IBS: 0.19794588459265944
[I 2024-04-15 13:33:41,213] Trial 81 finished with value: 0.20640465395144206 and parameters: {'l1_ratio': 0.312915675113097}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24363129976992676
Fold 2 IBS: 0.19101244671343873
Fold 3 IBS: 0.20551598800188306
Fold 4 IBS: 0.19397754151893593
Fold 5 IBS: 0.19797764828027575
[I 2024-04-15 13:33:41,428] Trial 82 finished with value: 0.20642298485689206 and parameters: {'l1_ratio': 0.3661961597767318}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436335668681228
Fold 2 IBS: 0.19100225288867603
Fold 3 IBS: 0.20556747136346132
Fold 4 IBS: 0.19396253512844808
Fold 5 IBS: 0.19796152287542673
[I 2024-04-15 13:33:41,617] Trial 83 finished with value: 0.20642546982482698 and parameters: {'l1_ratio': 0.33476452925904066}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24371780087604283
Fold 2 IBS: 0.22621872430551423
Fold 3 IBS: 0.22874074308710735
Fold 4 IBS: 0.1939315769190019
Fold 5 IBS: 0.197921097563661
[I 2024-04-15 13:33:41,755] Trial 84 finished with value: 0.21810598855026547 and parameters: {'l1_ratio': 0.25823970686013115}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24369887043299668
Fold 2 IBS: 0.19098959778456703
Fold 3 IBS: 0.20551240740011129
Fold 4 IBS: 0.19394313374173028
Fold 5 IBS: 0.1979473838372794
[I 2024-04-15 13:33:41,933] Trial 85 finished with value: 0.20641827863933693 and parameters: {'l1_ratio': 0.3028344908418993}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24366483400919398
Fold 2 IBS: 0.1910075169784476
Fold 3 IBS: 0.2055853473886674
Fold 4 IBS: 0.19396664870889982
Fold 5 IBS: 0.19797586401760747
[I 2024-04-15 13:33:42,105] Trial 86 finished with value: 0.20644004222056322 and parameters: {'l1_ratio': 0.38209309097805816}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24371234161361835
Fold 2 IBS: 0.2256782445646752
Fold 3 IBS: 0.22873176223977915
Fold 4 IBS: 0.1939398268896394
Fold 5 IBS: 0.19793337910611314
[I 2024-04-15 13:33:42,235] Trial 87 finished with value: 0.21799911088276508 and parameters: {'l1_ratio': 0.28117956451895915}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24371540471580505
Fold 2 IBS: 0.22809052595059684
Fold 3 IBS: 0.22879198711550328
Fold 4 IBS: 0.2371663772250701
Fold 5 IBS: 0.2260316501371047
[I 2024-04-15 13:33:42,336] Trial 88 finished with value: 0.232759189028816 and parameters: {'l1_ratio': 0.17755737756840495}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24365365275543688
Fold 2 IBS: 0.19103405615966865
Fold 3 IBS: 0.2056196691014258
Fold 4 IBS: 0.19397800913716204
Fold 5 IBS: 0.19799418595470245
[I 2024-04-15 13:33:42,544] Trial 89 finished with value: 0.20645591462167917 and parameters: {'l1_ratio': 0.41309407585833935}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24367421266635342
Fold 2 IBS: 0.19100905934131254
Fold 3 IBS: 0.20550486455578015
Fold 4 IBS: 0.19393918351836295
Fold 5 IBS: 0.1979447099259934
[I 2024-04-15 13:33:42,746] Trial 90 finished with value: 0.20641440600156047 and parameters: {'l1_ratio': 0.3214622462741656}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436759026256324
Fold 2 IBS: 0.1910097669407224
Fold 3 IBS: 0.20550834973587523
Fold 4 IBS: 0.19394048372176628
Fold 5 IBS: 0.19794461556170925
[I 2024-04-15 13:33:43,044] Trial 91 finished with value: 0.2064158237171411 and parameters: {'l1_ratio': 0.32217723908610385}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2436141326058737
Fold 2 IBS: 0.1910053011723974
Fold 3 IBS: 0.2055784833648783
Fold 4 IBS: 0.19396540137409768
Fold 5 IBS: 0.19797858923895606
[I 2024-04-15 13:33:43,617] Trial 92 finished with value: 0.2064283815512406 and parameters: {'l1_ratio': 0.35853854987307665}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24367038189546278
Fold 2 IBS: 0.22659488753855728
Fold 3 IBS: 0.22874861710839714
Fold 4 IBS: 0.23540561801484258
Fold 5 IBS: 0.19790892517274736
[I 2024-04-15 13:33:43,807] Trial 93 finished with value: 0.22646568594600142 and parameters: {'l1_ratio': 0.2421831896464229}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.2434066856723031
Fold 2 IBS: 0.1911811393236062
Fold 3 IBS: 0.20630088323502183
Fold 4 IBS: 0.19422159921541796
Fold 5 IBS: 0.19844059425985416
[I 2024-04-15 13:33:44,020] Trial 94 finished with value: 0.20671018034124064 and parameters: {'l1_ratio': 0.8606850154038875}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24366886313819572
Fold 2 IBS: 0.2254464783234192
Fold 3 IBS: 0.20545062399515204
Fold 4 IBS: 0.1939200455961539
Fold 5 IBS: 0.19793181781674668
[I 2024-04-15 13:33:44,334] Trial 95 finished with value: 0.2132835657739335 and parameters: {'l1_ratio': 0.29097082541926317}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24350409321217364
Fold 2 IBS: 0.19108785336132073
Fold 3 IBS: 0.2058658559660466
Fold 4 IBS: 0.19408678388500794
Fold 5 IBS: 0.19811810673756378
[I 2024-04-15 13:33:44,589] Trial 96 finished with value: 0.20653253863242252 and parameters: {'l1_ratio': 0.6030924300037979}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24365168810990306
Fold 2 IBS: 0.19100980714666746
Fold 3 IBS: 0.20550591898958515
Fold 4 IBS: 0.1939383815590206
Fold 5 IBS: 0.19796051128586079
[I 2024-04-15 13:33:44,854] Trial 97 finished with value: 0.2064132614182074 and parameters: {'l1_ratio': 0.34251113745924405}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24364827186288399
Fold 2 IBS: 0.19100838080032667
Fold 3 IBS: 0.20549887413103965
Fold 4 IBS: 0.1939729424406885
Fold 5 IBS: 0.1979607004048841
[I 2024-04-15 13:33:45,034] Trial 98 finished with value: 0.2064178339279646 and parameters: {'l1_ratio': 0.3410246190042779}. Best is trial 38 with value: 0.20640346841169058.
Fold 1 IBS: 0.24357375703657366
Fold 2 IBS: 0.19102885067456205
Fold 3 IBS: 0.20567554760675558
Fold 4 IBS: 0.1939972342813788
Fold 5 IBS: 0.19801396714464628
[I 2024-04-15 13:33:45,223] Trial 99 finished with value: 0.2064578713487833 and parameters: {'l1_ratio': 0.4509618008169656}. Best is trial 38 with value: 0.20640346841169058.


* Best trial for IBS:
 FrozenTrial(number=38, state=TrialState.COMPLETE, values=[0.20640346841169058], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 34, 328722), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 34, 515979), params={'l1_ratio': 0.29543822482619353}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=38, value=None)


* Best Score for IBS:
 0.20640346841169058

In [118]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [119]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.693
train_ibs:  0.206

#### Test

In [120]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [121]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.28621072101688444)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.29543822482619353)

test_ibs:  0.288

In [122]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [123]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:45,426] A new study created in memory with name: no-name-d11239e4-f9dd-492d-b0f6-fbffe68afd73

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 13:33:47,569] Trial 0 finished with value: 0.6977075894586338 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6977075894586338.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:48,976] Trial 1 finished with value: 0.7128781680014569 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:33:50,423] Trial 2 finished with value: 0.7078951516958202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:33:50,748] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:33:51,208] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:33:52,855] Trial 5 finished with value: 0.7140624838621864 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:54,599] Trial 6 finished with value: 0.7101780788884746 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:33:55,516] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-15 13:33:57,734] Trial 8 finished with value: 0.5257510729613734 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:33:58,833] Trial 9 finished with value: 0.7039036721293016 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:33:58,992] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:33:59,514] Trial 11 finished with value: 0.7271736918163124 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:33:59,965] Trial 12 finished with value: 0.7217535824914708 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8064195611120726, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:34:00,449] Trial 13 finished with value: 0.7230396596037402 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.8350722272141606, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13041468920781069, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6845493562231759
[I 2024-04-15 13:34:00,740] Trial 14 finished with value: 0.7401429490839831 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9806297626114981, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18121651510792322, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:34:01,043] Trial 15 finished with value: 0.7359974816455777 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9916077098875709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2050785814281292, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7914893617021277

Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7060085836909872
[I 2024-04-15 13:34:01,112] Trial 16 finished with value: 0.7424649927687818 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.9632036286697128, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19855793167729388, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 13:34:01,169] Trial 17 finished with value: 0.7187276534642637 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.9920927723346319, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6115879828326181
[I 2024-04-15 13:34:01,258] Trial 18 finished with value: 0.6821795609651563 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.4733682176858589, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18440565612965779, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 13:34:01,396] Trial 19 finished with value: 0.6909365199154465 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.8996903695627709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3933604732001355, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6974248927038627
[I 2024-04-15 13:34:01,798] Trial 20 finished with value: 0.731849318014498 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.7099567102313042, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2573277491349737, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:34:02,109] Trial 21 finished with value: 0.7351391125468653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9578709493710758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19090506657387685, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:34:02,300] Trial 22 finished with value: 0.7341648725242437 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.9967334344648481, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22971555033034935, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:34:02,650] Trial 23 finished with value: 0.7461784934529897 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.8688645990573083, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1729801266340484, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:34:03,013] Trial 24 finished with value: 0.7410139181199299 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.866350879679609, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07068946136637579, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 13:34:03,507] Trial 25 finished with value: 0.7568542957468967 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.8561321352006472, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07248837432829829, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:34:04,013] Trial 26 finished with value: 0.7469421068076121 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.766734838708136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07999208951911986, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:34:04,463] Trial 27 finished with value: 0.7510925047188961 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.7750769539334444, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06326441457712315, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:34:04,989] Trial 28 finished with value: 0.7651955962327717 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.6847169156044919, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003364807635412012, 'warm_start': True}. Best is trial 28 with value: 0.7651955962327717.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 13:34:05,698] Trial 29 finished with value: 0.7751733627229969 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.04113891562651206, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 13:34:06,487] Trial 30 finished with value: 0.7736629125252518 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.6833587310905035, 'max_features': None, 'min_weight_fraction_leaf': 0.008532800179007469, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:34:07,286] Trial 31 finished with value: 0.7735002862697369 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.6547593902381754, 'max_features': None, 'min_weight_fraction_leaf': 0.01653304213676029, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:34:08,114] Trial 32 finished with value: 0.7726671170454932 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.7011070731694715, 'max_features': None, 'min_weight_fraction_leaf': 0.002655419277963856, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-15 13:34:08,935] Trial 33 finished with value: 0.761951377352432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.4871505413082745, 'max_features': None, 'min_weight_fraction_leaf': 0.0037092008636243484, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:34:10,360] Trial 34 finished with value: 0.7772994105576999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5424853541641252, 'max_features': None, 'min_weight_fraction_leaf': 0.04005993867513943, 'warm_start': True}. Best is trial 34 with value: 0.7772994105576999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:34:11,544] Trial 35 finished with value: 0.7939453846462785 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5281329979576042, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.7939453846462785.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:34:12,591] Trial 36 finished with value: 0.7988094200063037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5475428261493075, 'max_features': None, 'min_weight_fraction_leaf': 0.04248766950155104, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8081395348837209
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:34:13,741] Trial 37 finished with value: 0.7438212214010235 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.537628436907505, 'max_features': None, 'min_weight_fraction_leaf': 0.13505191950972878, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:34:14,854] Trial 38 finished with value: 0.7773251612620597 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4079124058970714, 'max_features': None, 'min_weight_fraction_leaf': 0.043050318879278446, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:34:15,998] Trial 39 finished with value: 0.734846885715039 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': None, 'min_weight_fraction_leaf': 0.10012332890216755, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7381974248927039
[I 2024-04-15 13:34:17,000] Trial 40 finished with value: 0.7649536724571295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.38596283150687494, 'max_features': None, 'min_weight_fraction_leaf': 0.04061455540701541, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 13:34:18,001] Trial 41 finished with value: 0.7941370621081079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.5853104884542844, 'max_features': None, 'min_weight_fraction_leaf': 0.045291071200096567, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:34:18,910] Trial 42 finished with value: 0.736998260411046 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 466, 'oob_score': True, 'max_samples': 0.5547327087340422, 'max_features': None, 'min_weight_fraction_leaf': 0.15119679094835453, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:34:19,791] Trial 43 finished with value: 0.7838881672008012 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.43155969103520636, 'max_features': None, 'min_weight_fraction_leaf': 0.043472744875657617, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:34:20,646] Trial 44 finished with value: 0.7399894649828315 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.4005082288778946, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:34:21,055] Trial 45 finished with value: 0.7241222823816911 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.25182885979889597, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08391169894605255, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:34:23,272] Trial 46 finished with value: 0.7058457110259935 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.43126650753033136, 'max_features': None, 'min_weight_fraction_leaf': 0.05341940290949464, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:34:23,659] Trial 47 finished with value: 0.761821383227146 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.30342154143659733, 'max_features': None, 'min_weight_fraction_leaf': 0.03559822522548907, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:34:25,689] Trial 48 finished with value: 0.7117273483913299 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 435, 'oob_score': True, 'max_samples': 0.5993264662444304, 'max_features': None, 'min_weight_fraction_leaf': 0.1243065372654003, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:26,596] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.5188442477983979, 'max_features': None, 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:34:27,047] Trial 50 finished with value: 0.737899316580976 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.5847268231512849, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15227204260709018, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 13:34:28,116] Trial 51 finished with value: 0.7814971781238983 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.43199709338607994, 'max_features': None, 'min_weight_fraction_leaf': 0.03149759470389267, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 13:34:29,240] Trial 52 finished with value: 0.7567762597419098 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4387556889483383, 'max_features': None, 'min_weight_fraction_leaf': 0.09297907262518232, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 13:34:30,200] Trial 53 finished with value: 0.7986572561005724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.4978232271491865, 'max_features': None, 'min_weight_fraction_leaf': 0.033781036150152696, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:34:30,984] Trial 54 finished with value: 0.8175044273559141 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.4961608781156207, 'max_features': None, 'min_weight_fraction_leaf': 0.025003317155411986, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.759656652360515
[I 2024-04-15 13:34:31,734] Trial 55 finished with value: 0.7750834494179615 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.5021698171984055, 'max_features': None, 'min_weight_fraction_leaf': 0.06062440846922696, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:34:33,502] Trial 56 finished with value: 0.692159003960772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.6431467441559697, 'max_features': None, 'min_weight_fraction_leaf': 0.021762770810368127, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 13:34:34,600] Trial 57 finished with value: 0.7775457629433687 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.5757175357123006, 'max_features': None, 'min_weight_fraction_leaf': 0.05830794943324037, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:35,538] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.4648579376135416, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.30295661673067836, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:34:35,877] Trial 59 finished with value: 0.742832764389526 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.34319505493069397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08248014261229168, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:34:38,421] Trial 60 finished with value: 0.7094998068077641 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.6211328199713557, 'max_features': None, 'min_weight_fraction_leaf': 0.11070844936873359, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 13:34:39,737] Trial 61 finished with value: 0.8036986552407976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.5153677562911374, 'max_features': None, 'min_weight_fraction_leaf': 0.031485629345332306, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:34:41,066] Trial 62 finished with value: 0.8182757698225179 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.5112289023564809, 'max_features': None, 'min_weight_fraction_leaf': 0.02095528969051655, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:34:42,353] Trial 63 finished with value: 0.8111521115785895 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.5100900270084606, 'max_features': None, 'min_weight_fraction_leaf': 0.018150109857069722, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7510729613733905
[I 2024-04-15 13:34:43,492] Trial 64 finished with value: 0.7700709580629541 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.4955086388573719, 'max_features': None, 'min_weight_fraction_leaf': 0.06782578020859786, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:34:44,544] Trial 65 finished with value: 0.8185942843287751 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.572806842914682, 'max_features': None, 'min_weight_fraction_leaf': 0.02226915354245074, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:45,637] Trial 66 finished with value: 0.8160847545835782 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.5576081908424206, 'max_features': None, 'min_weight_fraction_leaf': 0.016475143309745643, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:34:46,689] Trial 67 finished with value: 0.8101126972372172 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.561957978855049, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.018288170265703986, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:47,572] Trial 68 finished with value: 0.8183234527679148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.6097336917403036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02099611885947379, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8454935622317596
[I 2024-04-15 13:34:48,343] Trial 69 finished with value: 0.8272146463529724 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7318335045229435, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017419775688352082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:34:49,099] Trial 70 finished with value: 0.8158063208975717 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.6243013523451256, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020464714362005143, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:50,204] Trial 71 finished with value: 0.824114421989065 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.7330924737377311, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016575501718897302, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:34:51,890] Trial 72 finished with value: 0.8125646918339378 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7326351452640015, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0027592484745489945, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:34:52,815] Trial 73 finished with value: 0.8078669641918867 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 262, 'oob_score': True, 'max_samples': 0.6560932996857387, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01505215827140816, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:34:53,831] Trial 74 finished with value: 0.8229478737470439 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.8040957518239317, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024607026709667742, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6931330472103004
[I 2024-04-15 13:34:55,322] Trial 75 finished with value: 0.7297534394801531 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.8244077376700942, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2738762867283342, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:34:56,342] Trial 76 finished with value: 0.8005224502929792 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.7779027631332152, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06198954175038082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:34:57,243] Trial 77 finished with value: 0.8054911364827252 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.7444363178817063, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00391494572036042, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:34:58,252] Trial 78 finished with value: 0.7766506135263602 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.7964582770234238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08072526041027032, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 13:34:58,687] Trial 79 finished with value: 0.7952779202339323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.618087421106259, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02724887288178213, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6716738197424893
[I 2024-04-15 13:35:00,233] Trial 80 finished with value: 0.7109603094858263 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.6608918473113886, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22754786457763954, 'warm_start': False}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:35:01,161] Trial 81 finished with value: 0.823191212472951 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 334, 'oob_score': True, 'max_samples': 0.7181496469643299, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01833632174034757, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:35:02,037] Trial 82 finished with value: 0.8055458278408263 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.718648090454236, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05194443679311898, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:35:03,037] Trial 83 finished with value: 0.812684350596275 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.7502215626294254, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011526440379393736, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:35:04,042] Trial 84 finished with value: 0.8232844098456795 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.8395867498100796, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024617503790133055, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 13:35:05,073] Trial 85 finished with value: 0.7921991713994829 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 368, 'oob_score': True, 'max_samples': 0.8857836580094625, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07264997820097252, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:35:06,003] Trial 86 finished with value: 0.8224086969713147 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9236490757653891, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05091910924778117, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:35:06,744] Trial 87 finished with value: 0.7444219877257969 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.8360547528312109, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05159081964644253, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:35:07,607] Trial 88 finished with value: 0.8299957447925681 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6373390557939914
[I 2024-04-15 13:35:08,381] Trial 89 finished with value: 0.6984552187416074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9606865260369674, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42980933716176023, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:35:09,369] Trial 90 finished with value: 0.8168638261621636 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.8970982407350513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0033122441195345426, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:35:10,158] Trial 91 finished with value: 0.8288039966760785 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.8500705105869577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02769924772148816, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 13:35:10,975] Trial 92 finished with value: 0.828952436236799 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.9318910170313084, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03466207519046283, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:35:11,792] Trial 93 finished with value: 0.8246721711870638 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.9237402520498113, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051627897348460114, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 13:35:12,586] Trial 94 finished with value: 0.7774842065936604 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.9315755472196319, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09044268069913194, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:35:13,393] Trial 95 finished with value: 0.8149658464044028 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.9428489419934195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05519942461860093, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:35:14,026] Trial 96 finished with value: 0.7343217686472692 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 18, 'n_estimators': 255, 'oob_score': True, 'max_samples': 0.8550701905177472, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07090475670535565, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7553648068669528
[I 2024-04-15 13:35:14,428] Trial 97 finished with value: 0.7709719977986227 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.9118193987076412, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.035787567288930885, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:35:15,134] Trial 98 finished with value: 0.7298807893419987 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9222109032849816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04727690829808437, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415

[I 2024-04-15 13:35:17,197] A new study created in memory with name: no-name-b48dc639-f381-4a46-8f85-3ec4b56ea519

Fold 5 C-index: 0.6759656652360515
[I 2024-04-15 13:35:17,192] Trial 99 finished with value: 0.7070161831399606 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.9759793763474963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3521412865651261, 'warm_start': False}. Best is trial 88 with value: 0.8299957447925681.


* Best trial for C-index:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.8299957447925681], datetime_start=datetime.datetime(2024, 4, 15, 13, 35, 6, 747981), datetime_complete=datetime.datetime(2024, 4, 15, 13, 35, 7, 606737), params={'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=88, value=None)


* Best Score for C-index:
 0.8299957447925681

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22407713995563355
Fold 2 IBS: 0.17470488039835566
Fold 3 IBS: 0.2398383923527903
Fold 4 IBS: 0.20906561324773706
Fold 5 IBS: 0.2195728796491891
[I 2024-04-15 13:35:19,154] Trial 0 finished with value: 0.21345178112074117 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21345178112074117.
Fold 1 IBS: 0.21616660020333003
Fold 2 IBS: 0.17486525786616586
Fold 3 IBS: 0.2107106205384323
Fold 4 IBS: 0.20216950628891073
Fold 5 IBS: 0.21532298657498944
[I 2024-04-15 13:35:19,638] Trial 1 finished with value: 0.20384699429436565 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-15 13:35:20,016] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-15 13:35:21,276] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-15 13:35:22,485] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24936759596080646
Fold 2 IBS: 0.17264271046131205
Fold 3 IBS: 0.20421070451417014
Fold 4 IBS: 0.21666312222005965
Fold 5 IBS: 0.21221582754312004
[I 2024-04-15 13:35:23,900] Trial 5 finished with value: 0.2110199921398937 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21621830894948232
Fold 2 IBS: 0.18912437295998735
Fold 3 IBS: 0.25661481391845226
Fold 4 IBS: 0.20519890764061255
Fold 5 IBS: 0.21737176566006436
[I 2024-04-15 13:35:25,230] Trial 6 finished with value: 0.21690563382571976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.239725565259837
Fold 2 IBS: 0.22117477833066543
Fold 3 IBS: 0.22403481418923998
Fold 4 IBS: 0.2325927375141085
Fold 5 IBS: 0.22473498221278954
[I 2024-04-15 13:35:26,922] Trial 7 finished with value: 0.22845257550132808 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-15 13:35:29,705] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22659514067603376
Fold 2 IBS: 0.17851765630325647
Fold 3 IBS: 0.2013246121030424
Fold 4 IBS: 0.20963921105379285
Fold 5 IBS: 0.2203202485023523
[I 2024-04-15 13:35:30,320] Trial 9 finished with value: 0.2072793737276956 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-15 13:35:31,143] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2540107203940081
Fold 2 IBS: 0.19018193572283806
Fold 3 IBS: 0.2693108522338297
Fold 4 IBS: 0.2204494801684996
Fold 5 IBS: 0.22801293569526146
[I 2024-04-15 13:35:31,236] Trial 11 finished with value: 0.23239318484288743 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9899815471614337, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23986882649245242
Fold 2 IBS: 0.17667107107700725
Fold 3 IBS: 0.19675890006825608
Fold 4 IBS: 0.21136980755566645
Fold 5 IBS: 0.21659638264865502
[I 2024-04-15 13:35:31,900] Trial 12 finished with value: 0.20825299756840746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.838341657174724, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007007532608717559}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22478082430068405
Fold 2 IBS: 0.17185450852530715
Fold 3 IBS: 0.21027987039395774
Fold 4 IBS: 0.20018219852324562
Fold 5 IBS: 0.21753825326760137
[I 2024-04-15 13:35:32,470] Trial 13 finished with value: 0.2049271310021592 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.964999799603621, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2691953450690723}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21998167437826233
Fold 2 IBS: 0.18978207675252776
Fold 3 IBS: 0.2156881327568739
Fold 4 IBS: 0.20498945225014242
Fold 5 IBS: 0.2158332545660207
[I 2024-04-15 13:35:32,862] Trial 14 finished with value: 0.2092549181407654 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7347591488544951, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2812321272168262}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24379041704605284
Fold 2 IBS: 0.16804912162483507
Fold 3 IBS: 0.2051845606137616
Fold 4 IBS: 0.20906885042686352
Fold 5 IBS: 0.2130970650630231
[I 2024-04-15 13:35:33,865] Trial 15 finished with value: 0.20783800295490723 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9966433181385008, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13541305845514623}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.24681956605569497
Fold 2 IBS: 0.23227093172764388
Fold 3 IBS: 0.22941903729651647
Fold 4 IBS: 0.24121738904572626
Fold 5 IBS: 0.2302321253386658
[I 2024-04-15 13:35:34,997] Trial 16 finished with value: 0.2359918098928495 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 162, 'oob_score': False, 'max_samples': 0.32587405036023415, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3357318242102959}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2231111330848275
Fold 2 IBS: 0.17656419065238982
Fold 3 IBS: 0.20901589415087424
Fold 4 IBS: 0.20307733734686217
Fold 5 IBS: 0.21545535438507316
[I 2024-04-15 13:35:38,040] Trial 17 finished with value: 0.20544478192400537 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8324456438302156, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2527008941020278}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23532815608885377
Fold 2 IBS: 0.1837655560742492
Fold 3 IBS: 0.20262687562645237
Fold 4 IBS: 0.2122206984989701
Fold 5 IBS: 0.2166747901565821
[I 2024-04-15 13:35:38,531] Trial 18 finished with value: 0.21012321528902148 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.6751019433313558, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11276726622420546}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22863054693293589
Fold 2 IBS: 0.1963315773237213
Fold 3 IBS: 0.21471249390143013
Fold 4 IBS: 0.219881142418457
Fold 5 IBS: 0.22152453289806817
[I 2024-04-15 13:35:38,705] Trial 19 finished with value: 0.21621605869492252 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.756071359635432, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32595449578288455}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22537941330506062
Fold 2 IBS: 0.19227308793145745
Fold 3 IBS: 0.21265991721222577
Fold 4 IBS: 0.20917597176350836
Fold 5 IBS: 0.21687868662201695
[I 2024-04-15 13:35:39,359] Trial 20 finished with value: 0.21127341536685385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.6036734235439312, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23857721033918533}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22324770605725813
Fold 2 IBS: 0.18253846781709399
Fold 3 IBS: 0.2045169037430424
Fold 4 IBS: 0.20783876653003266
Fold 5 IBS: 0.2175938501921847
[I 2024-04-15 13:35:42,190] Trial 21 finished with value: 0.20714713886792238 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.8230570050888841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2722629100041059}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24383129660582778
Fold 2 IBS: 0.16931429481145502
Fold 3 IBS: 0.20516950235518827
Fold 4 IBS: 0.20489042671888189
Fold 5 IBS: 0.21168593869445076
[I 2024-04-15 13:35:45,009] Trial 22 finished with value: 0.20697829183716077 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.9080266581136552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1738640799325239}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22798058234299892
Fold 2 IBS: 0.17066187178067507
Fold 3 IBS: 0.20762316176929713
Fold 4 IBS: 0.20163711855316047
Fold 5 IBS: 0.21357666387653937
[I 2024-04-15 13:35:47,207] Trial 23 finished with value: 0.20429587966453416 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.918144892067728, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22593418563490295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2333417951219333
Fold 2 IBS: 0.1700982573355749
Fold 3 IBS: 0.20661966502631599
Fold 4 IBS: 0.20215860951935866
Fold 5 IBS: 0.21369121522055837
[I 2024-04-15 13:35:49,346] Trial 24 finished with value: 0.20518190844474823 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.9261452409044857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2150416825146331}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2302095064014022
Fold 2 IBS: 0.20489193018995322
Fold 3 IBS: 0.22229468418463336
Fold 4 IBS: 0.22315856362376232
Fold 5 IBS: 0.22270247922464476
[I 2024-04-15 13:35:51,765] Trial 25 finished with value: 0.22065143272487914 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7754756321225551, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37858736351418476}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622588582203958
Fold 2 IBS: 0.23225616799196488
Fold 3 IBS: 0.22961130014021525
Fold 4 IBS: 0.24150610351006122
Fold 5 IBS: 0.23015340332834447
[I 2024-04-15 13:35:55,397] Trial 26 finished with value: 0.23595057215852505 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 410, 'oob_score': True, 'max_samples': 0.44732517583857423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30573135880353774}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24371312366354173
Fold 2 IBS: 0.17009470168949176
Fold 3 IBS: 0.20387614537935278
Fold 4 IBS: 0.2063297018706307
Fold 5 IBS: 0.21225767577269047
[I 2024-04-15 13:35:57,442] Trial 27 finished with value: 0.20725426967514146 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.9264498293472653, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16408374861729386}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24230033744905524
Fold 2 IBS: 0.1700083907734053
Fold 3 IBS: 0.20307970499577657
Fold 4 IBS: 0.21056222306350966
Fold 5 IBS: 0.21225464745768113
[I 2024-04-15 13:35:59,192] Trial 28 finished with value: 0.20764106074788558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.6539680943502474, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11167707604899824}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24611993726989195
Fold 2 IBS: 0.23218890990534718
Fold 3 IBS: 0.23048044870725193
Fold 4 IBS: 0.2410683146218637
Fold 5 IBS: 0.2299160122305334
[I 2024-04-15 13:36:02,013] Trial 29 finished with value: 0.23595472454697766 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.11354273074199811, 'max_features': None, 'min_weight_fraction_leaf': 0.23506901120045084}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22660818914056846
Fold 2 IBS: 0.17199394890259848
Fold 3 IBS: 0.20974235645980502
Fold 4 IBS: 0.20527990803227994
Fold 5 IBS: 0.2142164886689667
[I 2024-04-15 13:36:03,210] Trial 30 finished with value: 0.2055681782408437 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 164, 'oob_score': False, 'max_samples': 0.7841568813969919, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19739729582328963}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23708578217070322
Fold 2 IBS: 0.17051603032060797
Fold 3 IBS: 0.2048697308529193
Fold 4 IBS: 0.20307497656561538
Fold 5 IBS: 0.21255249060044212
[I 2024-04-15 13:36:05,261] Trial 31 finished with value: 0.20561980210205758 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 339, 'oob_score': False, 'max_samples': 0.9431792460514251, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20474531091370285}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.22612682993385486
Fold 2 IBS: 0.17223298934748948
Fold 3 IBS: 0.20782358499736456
Fold 4 IBS: 0.20181112716562463
Fold 5 IBS: 0.21350833459590543
[I 2024-04-15 13:36:07,643] Trial 32 finished with value: 0.2043005732080478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.8753375341925101, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2230974552568295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22177687649658975
Fold 2 IBS: 0.17630377861515312
Fold 3 IBS: 0.2122309287307206
Fold 4 IBS: 0.2017574245411477
Fold 5 IBS: 0.21470545803951144
[I 2024-04-15 13:36:09,873] Trial 33 finished with value: 0.20535489328462447 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.8780403780133842, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26554839348030423}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2347950025150411
Fold 2 IBS: 0.16799406158735225
Fold 3 IBS: 0.2119268936202999
Fold 4 IBS: 0.1995017747896286
Fold 5 IBS: 0.21645738910312
[I 2024-04-15 13:36:10,627] Trial 34 finished with value: 0.2061350243230884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.9713620300267395, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22449252311835874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2184171866823885
Fold 2 IBS: 0.18340292802030164
Fold 3 IBS: 0.24622741065146023
Fold 4 IBS: 0.21030733491515133
Fold 5 IBS: 0.218874594617978
[I 2024-04-15 13:36:11,962] Trial 35 finished with value: 0.21544589097745592 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.8006724007383993, 'max_features': None, 'min_weight_fraction_leaf': 0.2991859225334826}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24658618602469104
Fold 2 IBS: 0.2321884009769192
Fold 3 IBS: 0.2295721257429426
Fold 4 IBS: 0.24149932745394134
Fold 5 IBS: 0.23037083343869663
[I 2024-04-15 13:36:13,423] Trial 36 finished with value: 0.23604337472743814 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.7142345385665702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24597601805501332
Fold 2 IBS: 0.16679544014249023
Fold 3 IBS: 0.2291560830967934
Fold 4 IBS: 0.21774129632473188
Fold 5 IBS: 0.21808816775530818
[I 2024-04-15 13:36:16,481] Trial 37 finished with value: 0.21555140107486742 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.8893387526179963, 'max_features': None, 'min_weight_fraction_leaf': 0.05558599763353947}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22361789070615487
Fold 2 IBS: 0.17833589878764333
Fold 3 IBS: 0.20797628674399748
Fold 4 IBS: 0.20706581092390064
Fold 5 IBS: 0.21475624911298768
[I 2024-04-15 13:36:19,877] Trial 38 finished with value: 0.2063504272549368 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.48823423037203917, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10676050487618188}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2465964694944807
Fold 2 IBS: 0.23221073187531344
Fold 3 IBS: 0.22950988130319463
Fold 4 IBS: 0.241408499161141
Fold 5 IBS: 0.23022625655373033
[I 2024-04-15 13:36:21,962] Trial 39 finished with value: 0.235990367677572 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.5771239750792474, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3646319374122424}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21647863712170887
Fold 2 IBS: 0.17199966700669284
Fold 3 IBS: 0.19869719848871478
Fold 4 IBS: 0.20796789999763218
Fold 5 IBS: 0.21625226939504177
[I 2024-04-15 13:36:22,241] Trial 40 finished with value: 0.2022791344019581 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.7017810474930685, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15131446570826318}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22134427216375058
Fold 2 IBS: 0.1760712729646329
Fold 3 IBS: 0.19474566426704223
Fold 4 IBS: 0.21163414366897387
Fold 5 IBS: 0.21799528858603973
[I 2024-04-15 13:36:22,491] Trial 41 finished with value: 0.20435812833008785 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6851330046079013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1415472492884433}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21730762926082742
Fold 2 IBS: 0.17880052942015828
Fold 3 IBS: 0.19466820609343688
Fold 4 IBS: 0.20919417870986243
Fold 5 IBS: 0.2175415352637051
[I 2024-04-15 13:36:22,733] Trial 42 finished with value: 0.20350241574959801 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.6932739851311275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14781080589948162}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2266914017789978
Fold 2 IBS: 0.18902598179814228
Fold 3 IBS: 0.1886797492652457
Fold 4 IBS: 0.21746952054591362
Fold 5 IBS: 0.21485690053973838
[I 2024-04-15 13:36:22,978] Trial 43 finished with value: 0.20734471078560754 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 26, 'oob_score': False, 'max_samples': 0.6230606164996372, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17300117076396285}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2263300301352394
Fold 2 IBS: 0.17228759968501195
Fold 3 IBS: 0.20727538565975506
Fold 4 IBS: 0.20619156167481315
Fold 5 IBS: 0.2151350980475268
[I 2024-04-15 13:36:23,623] Trial 44 finished with value: 0.20544393504046926 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.5383399306130238, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07137280133151601}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2195259426238762
Fold 2 IBS: 0.17176930604867915
Fold 3 IBS: 0.21264489605286027
Fold 4 IBS: 0.2026960468857599
Fold 5 IBS: 0.2155061220972602
[I 2024-04-15 13:36:24,307] Trial 45 finished with value: 0.20442846274168716 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7211266599729008, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08955966829076284}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.24664109906894663
Fold 2 IBS: 0.23211151536965932
Fold 3 IBS: 0.22921725039634813
Fold 4 IBS: 0.24155332248199884
Fold 5 IBS: 0.2300252715829934
[I 2024-04-15 13:36:25,436] Trial 46 finished with value: 0.23590969177998927 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.4955610125060993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22677458805979425
Fold 2 IBS: 0.18128534484285147
Fold 3 IBS: 0.20359451039074664
Fold 4 IBS: 0.21860313764199735
Fold 5 IBS: 0.21528256346964708
[I 2024-04-15 13:36:25,656] Trial 47 finished with value: 0.20910802888100735 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.6381469780315093, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15711696604627562}. Best is trial 40 with value: 0.2022791344019581.

Fold 1 IBS: 0.23790435513187447
Fold 2 IBS: 0.16917310562036944
Fold 3 IBS: 0.2032724536335342
Fold 4 IBS: 0.20275263571784216
Fold 5 IBS: 0.21198800508925086
[I 2024-04-15 13:36:28,186] Trial 48 finished with value: 0.20501811103857426 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.862646612475437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18882619674434536}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21643739431200149
Fold 2 IBS: 0.18002210069568697
Fold 3 IBS: 0.20963559196115233
Fold 4 IBS: 0.20201711337877098
Fold 5 IBS: 0.21711926927169345
[I 2024-04-15 13:36:28,734] Trial 49 finished with value: 0.20504629392386103 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.712240935894755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03279359667752256}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21970666197039673
Fold 2 IBS: 0.17845771406023855
Fold 3 IBS: 0.20885143473324186
Fold 4 IBS: 0.20319913155933902
Fold 5 IBS: 0.2153595741585475
[I 2024-04-15 13:36:30,192] Trial 50 finished with value: 0.2051149032963527 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.581277730850803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13970814386185937}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21850000381456347
Fold 2 IBS: 0.17736923091725895
Fold 3 IBS: 0.20498374840747066
Fold 4 IBS: 0.2021359588037073
Fold 5 IBS: 0.21987202711845588
[I 2024-04-15 13:36:30,501] Trial 51 finished with value: 0.20457219381229125 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.6824265755354791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13000278013180866}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21997861326285056
Fold 2 IBS: 0.17510133496874586
Fold 3 IBS: 0.20782135929983414
Fold 4 IBS: 0.20318340455059253
Fold 5 IBS: 0.21807100804623603
[I 2024-04-15 13:36:30,854] Trial 52 finished with value: 0.20483114402565183 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 39, 'oob_score': False, 'max_samples': 0.7595422741248538, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1492553835770421}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.20187641777839058
Fold 2 IBS: 0.21697708771949703
Fold 3 IBS: 0.2594495566549233
Fold 4 IBS: 0.2052587865188469
Fold 5 IBS: 0.22918402151273276
[I 2024-04-15 13:36:30,972] Trial 53 finished with value: 0.22254917403687813 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7063377467137641, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12053402761378912}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2163446023224957
Fold 2 IBS: 0.17212550764211373
Fold 3 IBS: 0.21160944290207245
Fold 4 IBS: 0.20512480185219015
Fold 5 IBS: 0.2160354664693132
[I 2024-04-15 13:36:31,549] Trial 54 finished with value: 0.20424796423763705 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.6746935555292785, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0904689651104114}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22967201163797166
Fold 2 IBS: 0.17176959330058167
Fold 3 IBS: 0.20224897452635443
Fold 4 IBS: 0.20289718637619525
Fold 5 IBS: 0.21350582751457162
[I 2024-04-15 13:36:32,807] Trial 55 finished with value: 0.2040187186711349 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 135, 'oob_score': False, 'max_samples': 0.8028424541436651, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18708342016220178}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2329914623588844
Fold 2 IBS: 0.1709218692606976
Fold 3 IBS: 0.2022628895427006
Fold 4 IBS: 0.2037428253059489
Fold 5 IBS: 0.21379783296488847
[I 2024-04-15 13:36:34,202] Trial 56 finished with value: 0.204743375886624 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.8015891614775278, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08443475399948225}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22222933862075872
Fold 2 IBS: 0.17307243696245472
Fold 3 IBS: 0.2076841617030592
Fold 4 IBS: 0.20227550999755373
Fold 5 IBS: 0.21586625145405466
[I 2024-04-15 13:36:35,464] Trial 57 finished with value: 0.2042255397475762 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.6308231363037688, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04742769018003304}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2456168604122806
Fold 2 IBS: 0.1720780186944042
Fold 3 IBS: 0.1939891166776255
Fold 4 IBS: 0.21652289584699036
Fold 5 IBS: 0.21111767529637926
[I 2024-04-15 13:36:36,524] Trial 58 finished with value: 0.207864913385536 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.6079842908829092, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04294499138204588}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22124664269345137
Fold 2 IBS: 0.17562069103113492
Fold 3 IBS: 0.2089041573304958
Fold 4 IBS: 0.20473650596918874
Fold 5 IBS: 0.2141094172536013
[I 2024-04-15 13:36:38,442] Trial 59 finished with value: 0.20492348285557443 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.6538044546332764, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02711344752535265}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2181513360924439
Fold 2 IBS: 0.17768472605175628
Fold 3 IBS: 0.21223044737111443
Fold 4 IBS: 0.20136958313815562
Fold 5 IBS: 0.21615046674907337
[I 2024-04-15 13:36:39,234] Trial 60 finished with value: 0.20511731188050875 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 84, 'oob_score': True, 'max_samples': 0.7478284186818124, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006650389537996307}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23118626942195483
Fold 2 IBS: 0.1702053994866854
Fold 3 IBS: 0.2129030925098888
Fold 4 IBS: 0.19903740475703263
Fold 5 IBS: 0.2136572303984417
[I 2024-04-15 13:36:39,868] Trial 61 finished with value: 0.20539787931480066 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.830509938904831, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1023742346219489}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2205940046318535
Fold 2 IBS: 0.17584334134448318
Fold 3 IBS: 0.20675620555477245
Fold 4 IBS: 0.20426009333569892
Fold 5 IBS: 0.216570869801864
[I 2024-04-15 13:36:40,738] Trial 62 finished with value: 0.20480490293373438 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 102, 'oob_score': True, 'max_samples': 0.6818329215138573, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18242157905770487}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23169425244220557
Fold 2 IBS: 0.17140668425310054
Fold 3 IBS: 0.19908163234934842
Fold 4 IBS: 0.20893662933440016

Fold 5 IBS: 0.21281753768850425
[I 2024-04-15 13:36:41,577] Trial 63 finished with value: 0.20478734721351177 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.5771231216606082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05763095148942208}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21904071817956408
Fold 2 IBS: 0.17322770907939164
Fold 3 IBS: 0.21071337338690455
Fold 4 IBS: 0.20198953222034577
Fold 5 IBS: 0.21531568867352077
[I 2024-04-15 13:36:42,040] Trial 64 finished with value: 0.20405740430794536 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.6331344922813995, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1612709153840626}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2211019166635484
Fold 2 IBS: 0.17526371579768263
Fold 3 IBS: 0.20774379356238173
Fold 4 IBS: 0.20424362266236684
Fold 5 IBS: 0.21480184651012801
[I 2024-04-15 13:36:42,768] Trial 65 finished with value: 0.2046309790392215 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.6350728460096916, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1631502901267459}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22198736886877768
Fold 2 IBS: 0.19061491871912364
Fold 3 IBS: 0.21827968226635633
Fold 4 IBS: 0.2052006534517124
Fold 5 IBS: 0.21613440335803383
[I 2024-04-15 13:36:43,308] Trial 66 finished with value: 0.21044340533280076 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.5218576422719642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19995250145835095}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2179075292069881
Fold 2 IBS: 0.18413396774995214
Fold 3 IBS: 0.20963049043297036
Fold 4 IBS: 0.20746418192466917
Fold 5 IBS: 0.21676539015107638
[I 2024-04-15 13:36:43,649] Trial 67 finished with value: 0.20718031189313124 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 52, 'oob_score': False, 'max_samples': 0.6169103339039868, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0952902999587806}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2265700266034037
Fold 2 IBS: 0.18276032311436483
Fold 3 IBS: 0.2042864418492306
Fold 4 IBS: 0.20936741747437496
Fold 5 IBS: 0.21564455337157445
[I 2024-04-15 13:36:43,878] Trial 68 finished with value: 0.20772575248258968 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.7428544401290184, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07523325642012642}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2317749634162734
Fold 2 IBS: 0.1684381693450842
Fold 3 IBS: 0.23424060778843453
Fold 4 IBS: 0.21328093521325694
Fold 5 IBS: 0.21962511519703135
[I 2024-04-15 13:36:44,675] Trial 69 finished with value: 0.2134719581920161 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.6630802195286096, 'max_features': None, 'min_weight_fraction_leaf': 0.12509688782986045}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21940762796898436
Fold 2 IBS: 0.17406140071679074
Fold 3 IBS: 0.21074986909040594
Fold 4 IBS: 0.20255362262736462
Fold 5 IBS: 0.2145647222877615
[I 2024-04-15 13:36:45,327] Trial 70 finished with value: 0.20426744853826145 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.6927913414061104, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1491330560760582}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22012016394475659
Fold 2 IBS: 0.17475427785134492
Fold 3 IBS: 0.21014966656305184
Fold 4 IBS: 0.20376747945979912
Fold 5 IBS: 0.21541417348684497
[I 2024-04-15 13:36:46,057] Trial 71 finished with value: 0.2048411522611595 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.6845803813000064, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1523838280114369}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2216865262329327
Fold 2 IBS: 0.17268198910660865
Fold 3 IBS: 0.21309572839002539
Fold 4 IBS: 0.20002188205239937
Fold 5 IBS: 0.2166664932944772
[I 2024-04-15 13:36:46,511] Trial 72 finished with value: 0.20483052381528868 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7721996477240339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17006714738018724}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2204717268372329
Fold 2 IBS: 0.18965023421922483
Fold 3 IBS: 0.21023281503750718
Fold 4 IBS: 0.20732383670369434
Fold 5 IBS: 0.21359155179608108
[I 2024-04-15 13:36:46,880] Trial 73 finished with value: 0.20825403291874806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 44, 'oob_score': False, 'max_samples': 0.60377148666791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12161104496600006}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2191586477412759
Fold 2 IBS: 0.17078013242114562
Fold 3 IBS: 0.20927963366535351
Fold 4 IBS: 0.20258237972300233
Fold 5 IBS: 0.2149257258484936
[I 2024-04-15 13:36:47,383] Trial 74 finished with value: 0.2033453038798542 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7304174393685703, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18556210671805792}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21830414363737688
Fold 2 IBS: 0.17720271112298439
Fold 3 IBS: 0.20697150533408146
Fold 4 IBS: 0.20250876743216076
Fold 5 IBS: 0.2152601673419393
[I 2024-04-15 13:36:48,082] Trial 75 finished with value: 0.20404945897370858 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.6468801596739339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18546007907051182}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22430380108574707
Fold 2 IBS: 0.18306897497858327
Fold 3 IBS: 0.20464475027408288
Fold 4 IBS: 0.21223544052441004
Fold 5 IBS: 0.21727837802511207
[I 2024-04-15 13:36:49,007] Trial 76 finished with value: 0.20830626897758706 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.7294723925670973, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24992337115768753}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22302173389184585
Fold 2 IBS: 0.1887176942510202
Fold 3 IBS: 0.20967732423927182
Fold 4 IBS: 0.20791001510644727
Fold 5 IBS: 0.21680578739397888
[I 2024-04-15 13:36:49,752] Trial 77 finished with value: 0.2092265109765128 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2128668242174557}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2239900710700344
Fold 2 IBS: 0.1698615839561287
Fold 3 IBS: 0.2095547190098964
Fold 4 IBS: 0.2012069680997044
Fold 5 IBS: 0.21613576683580699
[I 2024-04-15 13:36:50,353] Trial 78 finished with value: 0.20414982179431415 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.798025512896543, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.187406229874218}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22242518635376562
Fold 2 IBS: 0.17356537149199874
Fold 3 IBS: 0.19348965127184473
Fold 4 IBS: 0.20729301862706373

Fold 5 IBS: 0.21518309439089522
[I 2024-04-15 13:36:50,592] Trial 79 finished with value: 0.2023912644271136 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.7940170614934956, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19696931079449848}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2449767955817733
Fold 2 IBS: 0.172095460075217
Fold 3 IBS: 0.21463433607213933
Fold 4 IBS: 0.21510140082957746
Fold 5 IBS: 0.21527266884222518
[I 2024-04-15 13:36:50,846] Trial 80 finished with value: 0.21241613228018644 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 28, 'oob_score': False, 'max_samples': 0.8170871700419534, 'max_features': None, 'min_weight_fraction_leaf': 0.21125680575069572}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22348296120259534
Fold 2 IBS: 0.16980207668047606
Fold 3 IBS: 0.21009370900921706
Fold 4 IBS: 0.20191156961895484
Fold 5 IBS: 0.21613576683580699
[I 2024-04-15 13:36:51,567] Trial 81 finished with value: 0.20428521666941007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7971516901362177, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18138610915926726}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2561856444522722
Fold 2 IBS: 0.1673967931519715
Fold 3 IBS: 0.20047088391888304
Fold 4 IBS: 0.21074651924541707
Fold 5 IBS: 0.2099772553369716
[I 2024-04-15 13:36:51,796] Trial 82 finished with value: 0.20895541922110308 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.8399824689482805, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19201377617331056}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22426305056629034
Fold 2 IBS: 0.18300755389928863
Fold 3 IBS: 0.20718971819956258
Fold 4 IBS: 0.20479720064549958
Fold 5 IBS: 0.21619343342523623
[I 2024-04-15 13:36:52,213] Trial 83 finished with value: 0.20709019134717543 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.7653436422440136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24531020078321944}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22467801181967628
Fold 2 IBS: 0.17100965075590382
Fold 3 IBS: 0.20899248385281644
Fold 4 IBS: 0.20131690199114788
Fold 5 IBS: 0.21546837157592233
[I 2024-04-15 13:36:52,801] Trial 84 finished with value: 0.20429308399909335 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.7307213180337556, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16397999497171722}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22483109101566637
Fold 2 IBS: 0.17542630441342943
Fold 3 IBS: 0.207300694612249
Fold 4 IBS: 0.20406653897060492
Fold 5 IBS: 0.2158305961193959
[I 2024-04-15 13:36:53,893] Trial 85 finished with value: 0.2054910450262691 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.7826456215522579, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22924983418535252}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22386484118726915
Fold 2 IBS: 0.17019457614889205
Fold 3 IBS: 0.19033990305706086
Fold 4 IBS: 0.20853944070357402
Fold 5 IBS: 0.21728171951643854
[I 2024-04-15 13:36:54,167] Trial 86 finished with value: 0.20204409612264693 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.20601078792005195
Fold 2 IBS: 0.21451972742974615
Fold 3 IBS: 0.24528820767892662
Fold 4 IBS: 0.22453641785090767
Fold 5 IBS: 0.23206174675939142
[I 2024-04-15 13:36:54,269] Trial 87 finished with value: 0.22448337752780478 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.6512094554417259, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20485933323937144}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.24762671522415539
Fold 2 IBS: 0.1715658463060267
Fold 3 IBS: 0.19148117469966647
Fold 4 IBS: 0.20997063572215197
Fold 5 IBS: 0.2129063439446945
[I 2024-04-15 13:36:54,503] Trial 88 finished with value: 0.206710143179339 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.7081631748214322, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.135797779820887}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.25058563680774437
Fold 2 IBS: 0.2338641464063254
Fold 3 IBS: 0.22952356547794778
Fold 4 IBS: 0.24193138867022507
Fold 5 IBS: 0.23265095037320685
[I 2024-04-15 13:36:54,685] Trial 89 finished with value: 0.2377111375470899 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.15094844814066605, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25791328124207724}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22061007889537348
Fold 2 IBS: 0.1708591714745691
Fold 3 IBS: 0.21077158373683536
Fold 4 IBS: 0.20117937734899835
Fold 5 IBS: 0.2131852975039104
[I 2024-04-15 13:36:55,182] Trial 90 finished with value: 0.20332110179193735 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7073303179127854, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17438023467720193}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22104227565411022
Fold 2 IBS: 0.1722308353188776
Fold 3 IBS: 0.21218986505215992
Fold 4 IBS: 0.2005308528950858
Fold 5 IBS: 0.21558296667096527
[I 2024-04-15 13:36:55,658] Trial 91 finished with value: 0.20431535911823975 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.7458306090358743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17711861957316688}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2188852968200289
Fold 2 IBS: 0.1741200249949188
Fold 3 IBS: 0.2102249823823517
Fold 4 IBS: 0.20502686094713804
Fold 5 IBS: 0.21682970835459212
[I 2024-04-15 13:36:55,971] Trial 92 finished with value: 0.20501737469980594 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.6974990002375354, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16157211463362758}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22524471349246272
Fold 2 IBS: 0.18187848730423692
Fold 3 IBS: 0.20172697428993133
Fold 4 IBS: 0.20497913158718492
Fold 5 IBS: 0.2205671313428573
[I 2024-04-15 13:36:56,256] Trial 93 finished with value: 0.20687928760333466 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.6611862408590626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1916422380825528}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22083768503980603
Fold 2 IBS: 0.1797588530429119
Fold 3 IBS: 0.2079648062250091
Fold 4 IBS: 0.20291373702977164
Fold 5 IBS: 0.21635495382740025
[I 2024-04-15 13:36:56,770] Trial 94 finished with value: 0.2055660070329798 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.713903532939743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22122568041634558}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.26932513184118945

Fold 2 IBS: 0.1697323509215535
Fold 3 IBS: 0.20905255797983618
Fold 4 IBS: 0.2258672184082545
Fold 5 IBS: 0.2152407835992728
[I 2024-04-15 13:36:56,997] Trial 95 finished with value: 0.21784360855002127 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.8547756485942715, 'max_features': None, 'min_weight_fraction_leaf': 0.17594983744388534}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22065985212578162
Fold 2 IBS: 0.1724043068676393
Fold 3 IBS: 0.212876495767763
Fold 4 IBS: 0.20196603399913246
Fold 5 IBS: 0.21590968295775706
[I 2024-04-15 13:36:57,348] Trial 96 finished with value: 0.2047632743436147 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.7614906038154946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.140922870660813}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2124870890419155
Fold 2 IBS: 0.1839728942989018
Fold 3 IBS: 0.20401760145240125
Fold 4 IBS: 0.2083031273260043
Fold 5 IBS: 0.2181106808859397
[I 2024-04-15 13:36:57,620] Trial 97 finished with value: 0.20537827860103253 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.6469848321883379, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20645813530532972}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.21598257747339383
Fold 2 IBS: 0.19029660089884604
Fold 3 IBS: 0.21934243199729314
Fold 4 IBS: 0.20794860179398514
Fold 5 IBS: 0.21465156821990095
[I 2024-04-15 13:36:57,941] Trial 98 finished with value: 0.2096443560766838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.5974486750517274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2337807792851884}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22905634179711468
Fold 2 IBS: 0.16952063124242736
Fold 3 IBS: 0.20512675662267585
Fold 4 IBS: 0.2057771072122423
Fold 5 IBS: 0.21371077936387817
[I 2024-04-15 13:36:58,872] Trial 99 finished with value: 0.20463832324766768 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 185, 'oob_score': False, 'max_samples': 0.7373842810679355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15101502561347407}. Best is trial 86 with value: 0.20204409612264693.


* Best trial for IBS:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.20204409612264693], datetime_start=datetime.datetime(2024, 4, 15, 13, 36, 53, 898221), datetime_complete=datetime.datetime(2024, 4, 15, 13, 36, 54, 166680), params={'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=86, value=None)


* Best Score for IBS:
 0.20204409612264693

In [124]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [125]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.83
train_ibs:  0.202

#### Test

In [126]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [127]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=18, max_leaf_nodes=11,
                     max_samples=0.9059465751594485, min_samples_leaf=1,
                     min_weight_fraction_leaf=0.029068528038335394,
                     n_estimators=318, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.544

RandomSurvivalForest(max_depth=13, max_features='log2', max_leaf_nodes=11,
                     max_samples=0.7105780352803006, min_samples_leaf=11,
                     min_samples_split=13,
                     min_weight_fraction_leaf=0.2021626029496649,
                     n_estimators=31, random_state=123)

test_ibs:  0.247

In [128]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [129]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:36:59,432] A new study created in memory with name: no-name-88b4cc1f-7ed9-4999-853d-2cf37282b8a3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:36:59,931] Trial 0 finished with value: 0.7329375617815092 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:01,115] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:03,125] Trial 2 finished with value: 0.7178460229393517 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.8
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:37:03,319] Trial 3 finished with value: 0.7317208004250113 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:04,042] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:04,870] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:05,366] Trial 6 finished with value: 0.7321370246874943 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:37:06,699] Trial 7 finished with value: 0.7075673219865799 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:06,783] Trial 8 finished with value: 0.7362139149697521 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6545064377682404
[I 2024-04-15 13:37:09,680] Trial 9 finished with value: 0.6956580572700294 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:09,855] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.26413466171660194, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6802575107296137
[I 2024-04-15 13:37:09,943] Trial 11 finished with value: 0.7002022988770951 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 5, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:10,154] Trial 12 finished with value: 0.7233216044410213 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 108, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.21197644982784386}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:10,601] Trial 13 finished with value: 0.7227860885168853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 336, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7132669067566587, 'min_weight_fraction_leaf': 0.09682728258065251}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.7538759689922481
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 13:37:11,058] Trial 14 finished with value: 0.6875118831760492 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.3790277944184374}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:11,224] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.25853971878279847, 'min_weight_fraction_leaf': 0.1136143317234711}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:11,732] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.12362405012814498, 'min_weight_fraction_leaf': 0.18949444225079395}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:12,241] Trial 17 finished with value: 0.7333650628805521 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8640754037508087, 'min_weight_fraction_leaf': 0.08300984976320161}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:13,978] Trial 18 finished with value: 0.7138187212932231 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.893843387841617, 'min_weight_fraction_leaf': 0.0012901863864347718}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6587982832618026
[I 2024-04-15 13:37:14,259] Trial 19 finished with value: 0.7057594207270395 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 173, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6462028944794036, 'min_weight_fraction_leaf': 0.24752940142621416}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:37:14,567] Trial 20 finished with value: 0.7323582709861934 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 214, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9046520586847226, 'min_weight_fraction_leaf': 0.15604495917089234}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:15,115] Trial 21 finished with value: 0.733056653279694 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8264846465847887, 'min_weight_fraction_leaf': 0.06531032832143097}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:15,652] Trial 22 finished with value: 0.7346870590959979 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8554939338437892, 'min_weight_fraction_leaf': 0.05912077213864973}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:16,208] Trial 23 finished with value: 0.7352841948632597 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 487, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6813559412681637, 'min_weight_fraction_leaf': 0.03807965277622394}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:16,852] Trial 24 finished with value: 0.7320605873920041 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7101858188995143, 'min_weight_fraction_leaf': 0.03414106493059247}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:17,403] Trial 25 finished with value: 0.727965007825656 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:37:19,621] Trial 26 finished with value: 0.7097917064892874 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7363157908211037, 'min_weight_fraction_leaf': 0.030609355115257964}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:20,046] Trial 27 finished with value: 0.7289930115925871 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.05966804358984962}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:20,610] Trial 28 finished with value: 0.727700523625848 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9547761993685097, 'min_weight_fraction_leaf': 0.18010884975569444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6716738197424893
[I 2024-04-15 13:37:20,724] Trial 29 finished with value: 0.7278903944963211 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 53, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6672466493035638, 'min_weight_fraction_leaf': 0.09570676535902678}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:37:21,155] Trial 30 finished with value: 0.7283637613256518 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.21525035641182588}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:21,502] Trial 31 finished with value: 0.7301852441402965 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8780867392507613, 'min_weight_fraction_leaf': 0.08053342835298444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:21,929] Trial 32 finished with value: 0.7270669981840107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8465161672872993, 'min_weight_fraction_leaf': 0.13728708040036253}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:22,462] Trial 33 finished with value: 0.7291276715364954 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7791575185731888, 'min_weight_fraction_leaf': 0.08782522649871717}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:22,989] Trial 34 finished with value: 0.732991669441196 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.0321950347302904}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:24,234] Trial 35 finished with value: 0.7285589865120596 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 462, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7484887897698851, 'min_weight_fraction_leaf': 0.11179394316240188}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 13:37:24,902] Trial 36 finished with value: 0.704782939479291 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 120, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5819516222091663, 'min_weight_fraction_leaf': 0.05929252020100452}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:25,193] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6894294877112123, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 13:37:25,593] Trial 38 finished with value: 0.6969977793569042 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6176423630852546, 'min_weight_fraction_leaf': 0.27842662148070446}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:37:27,105] Trial 39 finished with value: 0.7145032975216214 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4114486681290081, 'min_weight_fraction_leaf': 0.006316515579589441}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:27,571] Trial 40 finished with value: 0.7394420414645654 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.070818312691936}. Best is trial 40 with value: 0.7394420414645654.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:27,980] Trial 41 finished with value: 0.7402388542135694 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7929235954297236, 'min_weight_fraction_leaf': 0.06753409188567513}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:28,356] Trial 42 finished with value: 0.7385473158906132 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7814167764920316, 'min_weight_fraction_leaf': 0.053138807692614115}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 13:37:28,748] Trial 43 finished with value: 0.7526793316239683 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 342, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.0237916514620877}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:29,129] Trial 44 finished with value: 0.7517156174445475 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7903494194560798, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 13:37:29,510] Trial 45 finished with value: 0.75724249310961 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9975014761881965, 'min_weight_fraction_leaf': 0.01820664676789947}. Best is trial 45 with value: 0.75724249310961.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:29,834] Trial 46 finished with value: 0.7516108231937302 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9833287122666867, 'min_weight_fraction_leaf': 0.02167204729301097}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:37:30,936] Trial 47 finished with value: 0.7072551380763006 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 277, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9938409184868892, 'min_weight_fraction_leaf': 0.012424414465270794}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:31,629] Trial 48 finished with value: 0.736994195055912 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 315, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9943389290512517, 'min_weight_fraction_leaf': 0.024122723628498613}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6201716738197425
[I 2024-04-15 13:37:31,967] Trial 49 finished with value: 0.6871506500322846 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.943836768280026, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:37:32,251] Trial 50 finished with value: 0.738757879065195 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9218905769996524, 'min_weight_fraction_leaf': 0.017081546823995417}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:32,623] Trial 51 finished with value: 0.7587815706706135 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8006618362151878, 'min_weight_fraction_leaf': 0.0006942403087633227}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:33,169] Trial 52 finished with value: 0.7475219816321547 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7294591746589625, 'min_weight_fraction_leaf': 0.0016358111792067614}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:33,539] Trial 53 finished with value: 0.7566629550916705 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5353674654541881, 'min_weight_fraction_leaf': 0.0026771789807350996}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:37:33,858] Trial 54 finished with value: 0.7352011465498318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5280559833057176, 'min_weight_fraction_leaf': 0.039551718738544406}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:37:34,276] Trial 55 finished with value: 0.7336828402532702 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3722344587434572, 'min_weight_fraction_leaf': 0.019345288070128742}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:37:34,751] Trial 56 finished with value: 0.7370042171283777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5400588998582563, 'min_weight_fraction_leaf': 0.04313419866698206}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:37:35,182] Trial 57 finished with value: 0.7325789664550014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5822470231276546, 'min_weight_fraction_leaf': 0.10820490172022261}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:37:35,518] Trial 58 finished with value: 0.7420782648330935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.47947757991973655, 'min_weight_fraction_leaf': 0.019676870735375367}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:37:37,955] Trial 59 finished with value: 0.7082120978166874 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 402, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9629602149520176, 'min_weight_fraction_leaf': 5.104770246312437e-05}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:38,279] Trial 60 finished with value: 0.7315255752386033 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 266, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.04917170213673687}. Best is trial 51 with value: 0.7587815706706135.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:37:38,664] Trial 61 finished with value: 0.7467905765647049 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7262478375780741, 'min_weight_fraction_leaf': 0.0014391069076949321}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:39,099] Trial 62 finished with value: 0.7475583381073945 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8176070633016336, 'min_weight_fraction_leaf': 0.017513460534447932}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:39,528] Trial 63 finished with value: 0.7466925367529218 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9048655808252274, 'min_weight_fraction_leaf': 0.026324306931491667}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:40,162] Trial 64 finished with value: 0.7370190980741596 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8235728807014974, 'min_weight_fraction_leaf': 0.07647889290633725}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:40,518] Trial 65 finished with value: 0.7475730756320799 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8717939599515069, 'min_weight_fraction_leaf': 0.046903678085942646}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:40,910] Trial 66 finished with value: 0.7482897431748442 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8797774907667472, 'min_weight_fraction_leaf': 0.048960653209137665}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:41,186] Trial 67 finished with value: 0.7393805115631469 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9729538475019345, 'min_weight_fraction_leaf': 0.09677508382156286}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 13:37:41,516] Trial 68 finished with value: 0.7053000937674134 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9142124434676113, 'min_weight_fraction_leaf': 0.3293312145420018}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:37:41,858] Trial 69 finished with value: 0.7350965386026626 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8817438215622965, 'min_weight_fraction_leaf': 0.034436173984274676}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7381974248927039
[I 2024-04-15 13:37:42,279] Trial 70 finished with value: 0.7613284744465487 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470771316919997, 'min_weight_fraction_leaf': 0.05299254826291741}. Best is trial 70 with value: 0.7613284744465487.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7424892703862661
[I 2024-04-15 13:37:42,736] Trial 71 finished with value: 0.7638673522542814 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:43,196] Trial 72 finished with value: 0.7530816328485426 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9438070806786616, 'min_weight_fraction_leaf': 0.0719219098849957}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:43,650] Trial 73 finished with value: 0.7529399312925945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9476534872163854, 'min_weight_fraction_leaf': 0.07948506430889707}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:37:44,134] Trial 74 finished with value: 0.7416078997115878 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9315744574283523, 'min_weight_fraction_leaf': 0.12730293993691283}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:44,594] Trial 75 finished with value: 0.7537662190909693 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9538212906403223, 'min_weight_fraction_leaf': 0.07947418064331738}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:37:46,897] Trial 76 finished with value: 0.7089732912239908 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503206330661996, 'min_weight_fraction_leaf': 0.08332855281149479}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:47,396] Trial 77 finished with value: 0.736222548982041 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9563764400770771, 'min_weight_fraction_leaf': 0.15158139627292644}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:47,833] Trial 78 finished with value: 0.7474677305513714 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9184606416275723, 'min_weight_fraction_leaf': 0.10966234237102679}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:48,240] Trial 79 finished with value: 0.7513105165834996 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8509706901999897, 'min_weight_fraction_leaf': 0.07437080570205526}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:37:48,702] Trial 80 finished with value: 0.7250348087736878 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9986660238693948, 'min_weight_fraction_leaf': 0.16662237313004993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 13:37:49,200] Trial 81 finished with value: 0.7572071277415792 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9698042200030538, 'min_weight_fraction_leaf': 0.059098984023617004}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:49,742] Trial 82 finished with value: 0.7514553752203057 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9681006428937893, 'min_weight_fraction_leaf': 0.09188576940897883}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 13:37:50,234] Trial 83 finished with value: 0.7580508863024411 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.900953067564881, 'min_weight_fraction_leaf': 0.06238575631317688}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 13:37:50,792] Trial 84 finished with value: 0.7603690354420299 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981565134422631, 'min_weight_fraction_leaf': 0.055911383060435194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:51,320] Trial 85 finished with value: 0.7514701127449911 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8908313295588716, 'min_weight_fraction_leaf': 0.05754237849545954}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:37:51,797] Trial 86 finished with value: 0.7604986057242595 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9139139944038005, 'min_weight_fraction_leaf': 0.06479300875481753}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:37:52,297] Trial 87 finished with value: 0.7619731232898213 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.908648262335172, 'min_weight_fraction_leaf': 0.055676683204352095}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:54,767] Trial 88 finished with value: 0.7081331135870429 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 457, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8593524715534154, 'min_weight_fraction_leaf': 0.20522107340967194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:37:55,318] Trial 89 finished with value: 0.7612669180968402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9096225926270616, 'min_weight_fraction_leaf': 0.06086475861021993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:56,249] Trial 90 finished with value: 0.7482861622509297 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9036341058690905, 'min_weight_fraction_leaf': 0.10323471635782432}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 13:37:56,912] Trial 91 finished with value: 0.7579312275401037 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.930984837991578, 'min_weight_fraction_leaf': 0.06281312587463944}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:37:57,609] Trial 92 finished with value: 0.7465445210352575 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.837687225987731, 'min_weight_fraction_leaf': 0.03575880044104557}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 13:37:58,241] Trial 93 finished with value: 0.7562581510868437 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9274363792849041, 'min_weight_fraction_leaf': 0.0661014687608754}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:37:58,904] Trial 94 finished with value: 0.7581413668716293 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8978558580565509, 'min_weight_fraction_leaf': 0.04353249947872927}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:37:59,662] Trial 95 finished with value: 0.7464935540221674 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8979178686532339, 'min_weight_fraction_leaf': 0.09188808281710414}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:38:00,270] Trial 96 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8782096526369123, 'min_weight_fraction_leaf': 0.4423900052068913}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:38:00,753] Trial 97 finished with value: 0.707119307000758 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 467, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7568822772464855, 'min_weight_fraction_leaf': 0.12390809358298693}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 13:38:01,305] Trial 98 finished with value: 0.7595501798994153 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8379792984882093, 'min_weight_fraction_leaf': 0.04873278208701805}. Best is trial 71 with value: 0.7638673522542814.

[I 2024-04-15 13:38:01,789] A new study created in memory with name: no-name-1b0ec444-e7d8-462c-a786-ff07938798de

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:38:01,783] Trial 99 finished with value: 0.7454360752058654 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8115869270579641, 'min_weight_fraction_leaf': 0.046153664833883515}. Best is trial 71 with value: 0.7638673522542814.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.7638673522542814], datetime_start=datetime.datetime(2024, 4, 15, 13, 37, 42, 281352), datetime_complete=datetime.datetime(2024, 4, 15, 13, 37, 42, 736240), params={'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for C-index:
 0.7638673522542814

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23536610912753758
Fold 2 IBS: 0.20145762246413637
Fold 3 IBS: 0.20393081537250338
Fold 4 IBS: 0.21602715770992703
Fold 5 IBS: 0.2123183673596273
[I 2024-04-15 13:38:03,170] Trial 0 finished with value: 0.21382001440674636 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-15 13:38:05,222] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24081748643654036
Fold 2 IBS: 0.21713451086140778
Fold 3 IBS: 0.21706845078329945
Fold 4 IBS: 0.22785653322218774
Fold 5 IBS: 0.2212935208368412
[I 2024-04-15 13:38:07,022] Trial 2 finished with value: 0.22483410042805532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24130149411697235
Fold 2 IBS: 0.2155958186901399
Fold 3 IBS: 0.21794780991257648
Fold 4 IBS: 0.2281735359031675
Fold 5 IBS: 0.2213413510348227
[I 2024-04-15 13:38:07,691] Trial 3 finished with value: 0.22487200193153578 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-15 13:38:09,366] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-15 13:38:10,246] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23588196908877218
Fold 2 IBS: 0.20300039081654195
Fold 3 IBS: 0.2032173161135722
Fold 4 IBS: 0.21660656247722504
Fold 5 IBS: 0.21313591685519812
[I 2024-04-15 13:38:12,374] Trial 6 finished with value: 0.21436843107026188 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23825239046762217
Fold 2 IBS: 0.20781792017117767
Fold 3 IBS: 0.20896423148161078
Fold 4 IBS: 0.2197851504145311
Fold 5 IBS: 0.21653670443025383
[I 2024-04-15 13:38:13,668] Trial 7 finished with value: 0.2182712793930391 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23441021296278977
Fold 2 IBS: 0.21668396635030526
Fold 3 IBS: 0.22051379811268176
Fold 4 IBS: 0.22841790837130418
Fold 5 IBS: 0.21971786351985503
[I 2024-04-15 13:38:13,970] Trial 8 finished with value: 0.2239487498633872 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24426590657878128
Fold 2 IBS: 0.22769375627843935
Fold 3 IBS: 0.22591830688186657
Fold 4 IBS: 0.23810899013034692
Fold 5 IBS: 0.22806252164373667
[I 2024-04-15 13:38:16,629] Trial 9 finished with value: 0.23280989630263416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-15 13:38:18,804] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.2366414313349858
Fold 2 IBS: 0.21027597932345765
Fold 3 IBS: 0.21371008388168403
Fold 4 IBS: 0.22126964028612253
Fold 5 IBS: 0.2183525448310651
[I 2024-04-15 13:38:20,808] Trial 11 finished with value: 0.22004993593146302 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23579256852371847
Fold 2 IBS: 0.19568412454984113
Fold 3 IBS: 0.20040747067699977
Fold 4 IBS: 0.21186400025265303
Fold 5 IBS: 0.20966969871024252
[I 2024-04-15 13:38:23,103] Trial 12 finished with value: 0.210683572542691 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2370011165638282
Fold 2 IBS: 0.21123276228104673
Fold 3 IBS: 0.21121286711017057
Fold 4 IBS: 0.2241696763859363
Fold 5 IBS: 0.21822141136063145
[I 2024-04-15 13:38:25,265] Trial 13 finished with value: 0.22036756674032265 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23685780568086942
Fold 2 IBS: 0.2126468337858846
Fold 3 IBS: 0.2143772281757236
Fold 4 IBS: 0.22443452861645802
Fold 5 IBS: 0.21899252589159815
[I 2024-04-15 13:38:27,113] Trial 14 finished with value: 0.22146178443010672 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.210683572542691.

Fold 1 IBS: 0.23656743298208832
Fold 2 IBS: 0.21264947915533935
Fold 3 IBS: 0.21321328704497466
Fold 4 IBS: 0.22340910553399146
Fold 5 IBS: 0.21947803887476586
[I 2024-04-15 13:38:28,279] Trial 15 finished with value: 0.22106346871823193 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24483198345747628
Fold 2 IBS: 0.2302859276502996
Fold 3 IBS: 0.2285602592982639
Fold 4 IBS: 0.24045635643173324
Fold 5 IBS: 0.22930909941169325
[I 2024-04-15 13:38:30,586] Trial 16 finished with value: 0.23468872524989326 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2357109983223001
Fold 2 IBS: 0.20494805543099556
Fold 3 IBS: 0.21371005693600734
Fold 4 IBS: 0.21914551084001152
Fold 5 IBS: 0.21764479743708764
[I 2024-04-15 13:38:32,059] Trial 17 finished with value: 0.21823188379328046 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-15 13:38:32,778] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23569889105742511
Fold 2 IBS: 0.21036165282675318
Fold 3 IBS: 0.2110188939735362
Fold 4 IBS: 0.2231729444607325
Fold 5 IBS: 0.21764713763142923
[I 2024-04-15 13:38:34,621] Trial 19 finished with value: 0.21957990398997523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2260422981383027
Fold 2 IBS: 0.21628115911706547
Fold 3 IBS: 0.22894435879157846
Fold 4 IBS: 0.22705631591030262
Fold 5 IBS: 0.2234837877858094
[I 2024-04-15 13:38:34,758] Trial 20 finished with value: 0.22436158394861172 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23626217363246013
Fold 2 IBS: 0.20265333339770739
Fold 3 IBS: 0.2030759075715199
Fold 4 IBS: 0.21605001910251603
Fold 5 IBS: 0.2129636719520293
[I 2024-04-15 13:38:36,689] Trial 21 finished with value: 0.21420102113124656 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23496608578657435
Fold 2 IBS: 0.1999430054098381
Fold 3 IBS: 0.201275593836101
Fold 4 IBS: 0.21418253302811457
Fold 5 IBS: 0.21127196072648274
[I 2024-04-15 13:38:38,769] Trial 22 finished with value: 0.21232783575742217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23555557011049139
Fold 2 IBS: 0.19236878946561603
Fold 3 IBS: 0.19926908881992766
Fold 4 IBS: 0.21084942333238568
Fold 5 IBS: 0.2081240396802252
[I 2024-04-15 13:38:40,845] Trial 23 finished with value: 0.20923338228172916 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23607695303226134
Fold 2 IBS: 0.203493581017792
Fold 3 IBS: 0.20360358222095004
Fold 4 IBS: 0.21361938713575862
Fold 5 IBS: 0.2127155595148638
[I 2024-04-15 13:38:43,007] Trial 24 finished with value: 0.21390181258432514 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23810448610418447
Fold 2 IBS: 0.20850297794887437
Fold 3 IBS: 0.20884091287918746
Fold 4 IBS: 0.21832663743927483
Fold 5 IBS: 0.2167935048771244
[I 2024-04-15 13:38:44,830] Trial 25 finished with value: 0.2181137038497291 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2366073194702186
Fold 2 IBS: 0.2094968403110053
Fold 3 IBS: 0.20963379712724098
Fold 4 IBS: 0.2223187457140648
Fold 5 IBS: 0.21676394473697067
[I 2024-04-15 13:38:47,595] Trial 26 finished with value: 0.21896412947190008 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23608107276763018
Fold 2 IBS: 0.21036141351373328
Fold 3 IBS: 0.21169155072466916
Fold 4 IBS: 0.22331018888988935
Fold 5 IBS: 0.2177506938697703
[I 2024-04-15 13:38:50,782] Trial 27 finished with value: 0.21983898395313844 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23715637039941884
Fold 2 IBS: 0.2120572412765648
Fold 3 IBS: 0.21620854589832805
Fold 4 IBS: 0.2250681900188581
Fold 5 IBS: 0.22134392576904316
[I 2024-04-15 13:38:52,679] Trial 28 finished with value: 0.22236685467244258 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24167838631766778
Fold 2 IBS: 0.22069051827263042
Fold 3 IBS: 0.22031739328406955
Fold 4 IBS: 0.23288818140652423
Fold 5 IBS: 0.22471508602895093
[I 2024-04-15 13:38:54,023] Trial 29 finished with value: 0.22805791306196857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.2369623605519169
Fold 2 IBS: 0.2015664827514855
Fold 3 IBS: 0.2044196732107329
Fold 4 IBS: 0.2152719150958778
Fold 5 IBS: 0.2123358137500061
[I 2024-04-15 13:38:56,389] Trial 30 finished with value: 0.21411124907200385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23451695205118067
Fold 2 IBS: 0.19751010562426458
Fold 3 IBS: 0.2027198084019687
Fold 4 IBS: 0.21411412044401185
Fold 5 IBS: 0.2111761169753505
[I 2024-04-15 13:38:59,313] Trial 31 finished with value: 0.21200742069935527 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.923666057752446, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2351025999648965
Fold 2 IBS: 0.1949158359424477
Fold 3 IBS: 0.20111115549804756
Fold 4 IBS: 0.21180546961424107
Fold 5 IBS: 0.20942511704648153
[I 2024-04-15 13:39:01,764] Trial 32 finished with value: 0.2104720356132229 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.939007534925735, 'min_weight_fraction_leaf': 0.056106269226335825}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2359807363001553
Fold 2 IBS: 0.20390144524422224
Fold 3 IBS: 0.20692223621119946
Fold 4 IBS: 0.2180339829065641
Fold 5 IBS: 0.21348267427916112
[I 2024-04-15 13:39:04,285] Trial 33 finished with value: 0.21566421498826044 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9138848353483187, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23760045008166628
Fold 2 IBS: 0.1836854003772293
Fold 3 IBS: 0.20658859037809638
Fold 4 IBS: 0.21356225516393262
Fold 5 IBS: 0.2080473806120064
[I 2024-04-15 13:39:07,198] Trial 34 finished with value: 0.2098968153225862 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.06204686171902169}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23705554587631616
Fold 2 IBS: 0.18409383187630057
Fold 3 IBS: 0.20774926569595484
Fold 4 IBS: 0.21266700404602018
Fold 5 IBS: 0.20816809551656013
[I 2024-04-15 13:39:10,663] Trial 35 finished with value: 0.2099467486022304 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8327847526324277, 'min_weight_fraction_leaf': 0.055940476394666754}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23566967538262615
Fold 2 IBS: 0.18498818375621254
Fold 3 IBS: 0.2076181431218228
Fold 4 IBS: 0.21248969655065036
Fold 5 IBS: 0.20727223939702627
[I 2024-04-15 13:39:14,110] Trial 36 finished with value: 0.20960758764166765 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827098326399153, 'min_weight_fraction_leaf': 0.07015937717166007}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2322804097655011
Fold 2 IBS: 0.1904595107494953
Fold 3 IBS: 0.20654496901893055
Fold 4 IBS: 0.21029065871150715
Fold 5 IBS: 0.20940168079092789
[I 2024-04-15 13:39:19,317] Trial 37 finished with value: 0.20979544580727238 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8333567609683693, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23402986510699297
Fold 2 IBS: 0.20551834233097463
Fold 3 IBS: 0.21448459324894656
Fold 4 IBS: 0.21983535419793537
Fold 5 IBS: 0.21738979632924899
[I 2024-04-15 13:39:21,969] Trial 38 finished with value: 0.2182515902428197 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 349, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.823414916934049, 'min_weight_fraction_leaf': 0.22365568672391764}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23303653525127266
Fold 2 IBS: 0.19614443640526336
Fold 3 IBS: 0.20759014709806334
Fold 4 IBS: 0.21278979581525073
Fold 5 IBS: 0.2115153572009253
[I 2024-04-15 13:39:25,175] Trial 39 finished with value: 0.21221525435415506 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7688812089462244, 'min_weight_fraction_leaf': 0.13832319540130408}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24085544671476855
Fold 2 IBS: 0.21881433431452443
Fold 3 IBS: 0.2205550472397075
Fold 4 IBS: 0.23189796849220526
Fold 5 IBS: 0.22387717931221346
[I 2024-04-15 13:39:28,839] Trial 40 finished with value: 0.22719999521468384 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7387886455857571, 'min_weight_fraction_leaf': 0.2794340971992336}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23558729160195155
Fold 2 IBS: 0.18499721054651033
Fold 3 IBS: 0.2078176191769497
Fold 4 IBS: 0.21254959703326678
Fold 5 IBS: 0.20740208695361273
[I 2024-04-15 13:39:32,589] Trial 41 finished with value: 0.20967076106245824 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 459, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8304297502532995, 'min_weight_fraction_leaf': 0.06567312882813131}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23638956396269079
Fold 2 IBS: 0.18490789291091672
Fold 3 IBS: 0.20644644482157795
Fold 4 IBS: 0.21257693995308247
Fold 5 IBS: 0.20732761178411305
[I 2024-04-15 13:39:36,692] Trial 42 finished with value: 0.20952969068647617 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 450, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7982039779530783, 'min_weight_fraction_leaf': 0.07186658790260646}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23274337848255236
Fold 2 IBS: 0.1929272244249927
Fold 3 IBS: 0.20732501652108193
Fold 4 IBS: 0.21144242883441275
Fold 5 IBS: 0.20983249626579628
[I 2024-04-15 13:39:40,599] Trial 43 finished with value: 0.21085410890576722 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 440, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.1211117088142}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2410193325812047
Fold 2 IBS: 0.2226476644714021
Fold 3 IBS: 0.22105022637397118
Fold 4 IBS: 0.23115256969605635
Fold 5 IBS: 0.2240981533222132
[I 2024-04-15 13:39:44,062] Trial 44 finished with value: 0.2279935892889695 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6979907483981592, 'min_weight_fraction_leaf': 0.16526223863734468}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.23247724033039832
Fold 2 IBS: 0.18748554961121114
Fold 3 IBS: 0.2090170455982855
Fold 4 IBS: 0.207742375469341
Fold 5 IBS: 0.20889347688505747
[I 2024-04-15 13:39:45,175] Trial 45 finished with value: 0.2091231375788587 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8505483502716148, 'min_weight_fraction_leaf': 0.09794633817349793}. Best is trial 45 with value: 0.2091231375788587.
Fold 1 IBS: 0.2314286160573986
Fold 2 IBS: 0.1860889745854672
Fold 3 IBS: 0.20638267011548084
Fold 4 IBS: 0.20884587453459477
Fold 5 IBS: 0.20805701088484838
[I 2024-04-15 13:39:46,285] Trial 46 finished with value: 0.20816062923555795 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7709286828220481, 'min_weight_fraction_leaf': 0.07995724348415684}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23766776108374213
Fold 2 IBS: 0.21002348979145327
Fold 3 IBS: 0.21765068090817657
Fold 4 IBS: 0.22280193059668152
Fold 5 IBS: 0.21940264282312605
[I 2024-04-15 13:39:47,268] Trial 47 finished with value: 0.22150930104063588 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 127, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7682715671327377, 'min_weight_fraction_leaf': 0.08646740062265149}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23713247312937227
Fold 2 IBS: 0.1864152472719121
Fold 3 IBS: 0.20569921628056348
Fold 4 IBS: 0.21202213139980625
Fold 5 IBS: 0.2062034346638877
[I 2024-04-15 13:39:48,902] Trial 48 finished with value: 0.20949450054910837 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 186, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8579998757196492, 'min_weight_fraction_leaf': 0.022631912267245}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2401019704407054
Fold 2 IBS: 0.20664694277509515
Fold 3 IBS: 0.20269468295254925
Fold 4 IBS: 0.2190769330154152
Fold 5 IBS: 0.21529320315539308
[I 2024-04-15 13:39:50,580] Trial 49 finished with value: 0.2167627464678316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 176, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.535541626399398, 'min_weight_fraction_leaf': 0.02410725915835375}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23775614182380903
Fold 2 IBS: 0.20743414808900665
Fold 3 IBS: 0.20687718864416932
Fold 4 IBS: 0.21905338149069295
Fold 5 IBS: 0.21496321205066113
[I 2024-04-15 13:39:51,384] Trial 50 finished with value: 0.21721681441966784 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 90, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8724086164488271, 'min_weight_fraction_leaf': 0.04430715227744478}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23333408320563848
Fold 2 IBS: 0.18618334408777154
Fold 3 IBS: 0.2054922876895997
Fold 4 IBS: 0.2095428614888614
Fold 5 IBS: 0.2081255374544523
[I 2024-04-15 13:39:52,719] Trial 51 finished with value: 0.2085356227852647 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 157, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7607239465677439, 'min_weight_fraction_leaf': 0.0768704777706238}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23294009669574758
Fold 2 IBS: 0.18886644911422001
Fold 3 IBS: 0.20450870840640553
Fold 4 IBS: 0.2098663013569692
Fold 5 IBS: 0.2093242311139224
[I 2024-04-15 13:39:54,532] Trial 52 finished with value: 0.2091011573374529 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 215, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6812726944311738, 'min_weight_fraction_leaf': 0.0924784870388018}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23340127695530247
Fold 2 IBS: 0.19037609007747622
Fold 3 IBS: 0.20443462122815134
Fold 4 IBS: 0.20971338145144297
Fold 5 IBS: 0.20931781265162946
[I 2024-04-15 13:39:56,416] Trial 53 finished with value: 0.2094486364728005 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 224, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6963870551875947, 'min_weight_fraction_leaf': 0.10563773255020543}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23338966290283988
Fold 2 IBS: 0.19138513453127515
Fold 3 IBS: 0.20331794017233815
Fold 4 IBS: 0.21130675152530337
Fold 5 IBS: 0.2105461957704023
[I 2024-04-15 13:39:58,724] Trial 54 finished with value: 0.20998913698043178 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6719877047239909, 'min_weight_fraction_leaf': 0.0997398012429799}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23593555870849725
Fold 2 IBS: 0.20801826761705877
Fold 3 IBS: 0.20827021219395564
Fold 4 IBS: 0.21956943852396218
Fold 5 IBS: 0.21586303213321972
[I 2024-04-15 13:40:00,097] Trial 55 finished with value: 0.21753130183533873 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7290878996075589, 'min_weight_fraction_leaf': 0.1329691849961646}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24666819701072148
Fold 2 IBS: 0.23210773115939679
Fold 3 IBS: 0.22932364190291274
Fold 4 IBS: 0.24152405514050876
Fold 5 IBS: 0.2303157661686399
[I 2024-04-15 13:40:01,804] Trial 56 finished with value: 0.23598787827643591 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5975963219999111, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23492638070785768
Fold 2 IBS: 0.21240221048192362
Fold 3 IBS: 0.2168912407987811
Fold 4 IBS: 0.22754745889623634
Fold 5 IBS: 0.22089364796872285
[I 2024-04-15 13:40:03,007] Trial 57 finished with value: 0.22253218777070433 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 128, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6735255380721511, 'min_weight_fraction_leaf': 0.18708850621022327}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23531750054242687
Fold 2 IBS: 0.2077683628397722
Fold 3 IBS: 0.21364739027613322
Fold 4 IBS: 0.21979565810435922
Fold 5 IBS: 0.21840068135164575
[I 2024-04-15 13:40:05,228] Trial 58 finished with value: 0.21898591862286745 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 238, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.15746351073381912}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24661384524722246
Fold 2 IBS: 0.23215291198462218
Fold 3 IBS: 0.22952739882394438
Fold 4 IBS: 0.24152565273881768
Fold 5 IBS: 0.2303053694496521
[I 2024-04-15 13:40:07,260] Trial 59 finished with value: 0.23602503564885174 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.75796811576398, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2376464824369693

Fold 2 IBS: 0.21593994734134395
Fold 3 IBS: 0.22177987321764975
Fold 4 IBS: 0.22790863488656224
Fold 5 IBS: 0.2205529164521157
[I 2024-04-15 13:40:07,918] Trial 60 finished with value: 0.22476557086692814 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 74, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6041879821929975, 'min_weight_fraction_leaf': 0.1056236625824671}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23781793031064252
Fold 2 IBS: 0.1862495208476139
Fold 3 IBS: 0.20248456745784213
Fold 4 IBS: 0.21234711020159586
Fold 5 IBS: 0.2076972639565933
[I 2024-04-15 13:40:09,451] Trial 61 finished with value: 0.20931927855485752 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 197, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7101126073432302, 'min_weight_fraction_leaf': 0.013226300887269365}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2382367270174128
Fold 2 IBS: 0.18483164704435992
Fold 3 IBS: 0.20455018380786597
Fold 4 IBS: 0.2115954964542311
Fold 5 IBS: 0.20832518097782782
[I 2024-04-15 13:40:11,006] Trial 62 finished with value: 0.20950784706033954 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7066561911530848, 'min_weight_fraction_leaf': 0.012902964688040898}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23653797420874464
Fold 2 IBS: 0.18352585769961322
Fold 3 IBS: 0.20365755657663714
Fold 4 IBS: 0.20917655609037722
Fold 5 IBS: 0.20729793495414095
[I 2024-04-15 13:40:12,154] Trial 63 finished with value: 0.20803917590590265 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 148, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6435418239181828, 'min_weight_fraction_leaf': 0.046981576659506384}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.2376440714946851
Fold 2 IBS: 0.18154571059609376
Fold 3 IBS: 0.20148827866234856
Fold 4 IBS: 0.21485752658604737
Fold 5 IBS: 0.21193720419679402
[I 2024-04-15 13:40:13,186] Trial 64 finished with value: 0.20949455830719374 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6558453673842368, 'min_weight_fraction_leaf': 0.0017360883857289438}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24069140178630108
Fold 2 IBS: 0.21023884738343832
Fold 3 IBS: 0.20819592567054473
Fold 4 IBS: 0.22032685614631106
Fold 5 IBS: 0.2181378139835771
[I 2024-04-15 13:40:14,284] Trial 65 finished with value: 0.21951816899403448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6369381520536594, 'min_weight_fraction_leaf': 0.04630739996813268}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24662572908345176
Fold 2 IBS: 0.2321190214638095
Fold 3 IBS: 0.22943780141623776
Fold 4 IBS: 0.2415441728621753
Fold 5 IBS: 0.2302929916244345
[I 2024-04-15 13:40:15,813] Trial 66 finished with value: 0.23600394329002175 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 190, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7534591387104144, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23761253968101
Fold 2 IBS: 0.19333058518344354
Fold 3 IBS: 0.19763843228218964
Fold 4 IBS: 0.2100557032515617
Fold 5 IBS: 0.208391029584297
[I 2024-04-15 13:40:16,810] Trial 67 finished with value: 0.20940565799650038 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 111, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7140591797427468, 'min_weight_fraction_leaf': 0.0380146506503018}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23568784825771597
Fold 2 IBS: 0.19836028806772887
Fold 3 IBS: 0.20225664393852164
Fold 4 IBS: 0.21479439327398367
Fold 5 IBS: 0.21109075078575282
[I 2024-04-15 13:40:18,168] Trial 68 finished with value: 0.21243798486474058 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 168, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7866638182428198, 'min_weight_fraction_leaf': 0.08748663516762165}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23356744505088914
Fold 2 IBS: 0.1834363879714103
Fold 3 IBS: 0.207688591468538
Fold 4 IBS: 0.20411915061999797
Fold 5 IBS: 0.21081229591952125
[I 2024-04-15 13:40:18,855] Trial 69 finished with value: 0.20792477420607133 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 78, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6633577858466918, 'min_weight_fraction_leaf': 0.05378179190948057}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23425832559812115
Fold 2 IBS: 0.1874883919439577
Fold 3 IBS: 0.20956087508825158
Fold 4 IBS: 0.20966146089051388
Fold 5 IBS: 0.21197029878987708
[I 2024-04-15 13:40:19,284] Trial 70 finished with value: 0.21058787046214428 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 46, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.609138718062076, 'min_weight_fraction_leaf': 0.08081693575379295}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23180288969924676
Fold 2 IBS: 0.18284953833260828
Fold 3 IBS: 0.20816697020659303
Fold 4 IBS: 0.20634477989340283
Fold 5 IBS: 0.2066720406825964
[I 2024-04-15 13:40:19,838] Trial 71 finished with value: 0.20716724376288945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24034476073822214
Fold 2 IBS: 0.18987915865551205
Fold 3 IBS: 0.2035631310131893
Fold 4 IBS: 0.21033288060199645
Fold 5 IBS: 0.20723055719361239
[I 2024-04-15 13:40:20,508] Trial 72 finished with value: 0.21027009764050644 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 64, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5683034340032609, 'min_weight_fraction_leaf': 0.04646174961182159}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2299054630450867
Fold 2 IBS: 0.19773469146740125
Fold 3 IBS: 0.19034097643724923
Fold 4 IBS: 0.22944964628361184
Fold 5 IBS: 0.2389286128541861
[I 2024-04-15 13:40:20,645] Trial 73 finished with value: 0.217271878017507 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.054429859852659815}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2303167286243434
Fold 2 IBS: 0.19516700665987674
Fold 3 IBS: 0.20660685643983331
Fold 4 IBS: 0.20899892281373353
Fold 5 IBS: 0.2066488418873486
[I 2024-04-15 13:40:20,976] Trial 74 finished with value: 0.20954767128502713 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 29, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7480880522886367, 'min_weight_fraction_leaf': 0.07511258593340842}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23693321208405524
Fold 2 IBS: 0.19000973925047765
Fold 3 IBS: 0.20243881773088923
Fold 4 IBS: 0.2110667431713562
Fold 5 IBS: 0.20765848231427028
[I 2024-04-15 13:40:21,903] Trial 75 finished with value: 0.20962139891020973 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.49599352625156035, 'min_weight_fraction_leaf': 0.03138093454428739}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2375162774090104
Fold 2 IBS: 0.21696007860868566
Fold 3 IBS: 0.2199964189465905
Fold 4 IBS: 0.2298197447784768
Fold 5 IBS: 0.2208032877666601
[I 2024-04-15 13:40:22,612] Trial 76 finished with value: 0.2250191615018847 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 81, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6498539620686062, 'min_weight_fraction_leaf': 0.1107936452967258}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.234645557683981
Fold 2 IBS: 0.19308386846985393
Fold 3 IBS: 0.21042866351417217
Fold 4 IBS: 0.213955157478479
Fold 5 IBS: 0.20941746392682734
[I 2024-04-15 13:40:23,117] Trial 77 finished with value: 0.21230614221466268 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 53, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6219886854752814, 'min_weight_fraction_leaf': 0.0881530598041391}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23208979344503086
Fold 2 IBS: 0.19134551959096457
Fold 3 IBS: 0.20969730607101159
Fold 4 IBS: 0.21155535213663088
Fold 5 IBS: 0.21094666727963496
[I 2024-04-15 13:40:24,489] Trial 78 finished with value: 0.21112692770465458 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8975377298130277, 'min_weight_fraction_leaf': 0.05792949206602531}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24656769908913287
Fold 2 IBS: 0.23207473314584195
Fold 3 IBS: 0.22956209752209408
Fold 4 IBS: 0.24131766392563656
Fold 5 IBS: 0.22974225690563504
[I 2024-04-15 13:40:25,350] Trial 79 finished with value: 0.2358528901176681 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.15079098086778978}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23398194286521523
Fold 2 IBS: 0.2042478759118354
Fold 3 IBS: 0.2149027538028443
Fold 4 IBS: 0.21138634120370936
Fold 5 IBS: 0.21509744244742898
[I 2024-04-15 13:40:25,729] Trial 80 finished with value: 0.21592327124620664 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 34, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.680202266270148, 'min_weight_fraction_leaf': 0.13027280080194392}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23821133340721135
Fold 2 IBS: 0.18697626156811917
Fold 3 IBS: 0.2025556131339658
Fold 4 IBS: 0.21248041803374165
Fold 5 IBS: 0.21006237384648405
[I 2024-04-15 13:40:27,083] Trial 81 finished with value: 0.2100571999979044 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7059723708255974, 'min_weight_fraction_leaf': 0.011081957753211642}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2354434465673004
Fold 2 IBS: 0.18590060696281396
Fold 3 IBS: 0.20237660521219805
Fold 4 IBS: 0.21289282208945418
Fold 5 IBS: 0.2079334303868527
[I 2024-04-15 13:40:28,775] Trial 82 finished with value: 0.20890938224372385 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7322939853383122, 'min_weight_fraction_leaf': 0.030199179896950257}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2391213827919915
Fold 2 IBS: 0.18339377899057588
Fold 3 IBS: 0.20630651107397327
Fold 4 IBS: 0.21414237142238046
Fold 5 IBS: 0.20709539863236437
[I 2024-04-15 13:40:30,544] Trial 83 finished with value: 0.2100118885822571 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 249, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8082167579651034, 'min_weight_fraction_leaf': 0.030688122459232033}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2338134437703758
Fold 2 IBS: 0.18585229495562317
Fold 3 IBS: 0.20232554114967682
Fold 4 IBS: 0.20935878852735582
Fold 5 IBS: 0.20693004752390112
[I 2024-04-15 13:40:31,888] Trial 84 finished with value: 0.20765602318538656 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7722055241934203, 'min_weight_fraction_leaf': 0.06706989383850837}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2325404292841733
Fold 2 IBS: 0.2037796259632883
Fold 3 IBS: 0.21285222741885748
Fold 4 IBS: 0.21748519543805853
Fold 5 IBS: 0.21558014668487166
[I 2024-04-15 13:40:33,409] Trial 85 finished with value: 0.21644752495784986 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 209, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8080700094351241, 'min_weight_fraction_leaf': 0.07313973736441735}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23185610825625882
Fold 2 IBS: 0.1883838499173774
Fold 3 IBS: 0.2069558256748436
Fold 4 IBS: 0.2056460896941882
Fold 5 IBS: 0.20834833869947297
[I 2024-04-15 13:40:34,757] Trial 86 finished with value: 0.2082380424484282 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 179, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7797829686997926, 'min_weight_fraction_leaf': 0.0930692046392031}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23732262587143452
Fold 2 IBS: 0.18516284894711776
Fold 3 IBS: 0.20293194154297275
Fold 4 IBS: 0.20976950466294828
Fold 5 IBS: 0.20684702854669929
[I 2024-04-15 13:40:36,580] Trial 87 finished with value: 0.2084067899142345 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 182, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7347045490916186, 'min_weight_fraction_leaf': 0.0569064501216709}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23610457243620386
Fold 2 IBS: 0.1843646040116617
Fold 3 IBS: 0.2038780530044773
Fold 4 IBS: 0.2105249290335657
Fold 5 IBS: 0.20647024537168604
[I 2024-04-15 13:40:38,420] Trial 88 finished with value: 0.20826848077151894 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7454117372266992, 'min_weight_fraction_leaf': 0.05974548060098256}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23977374886110586
Fold 2 IBS: 0.20834445745005828
Fold 3 IBS: 0.2081295030562698
Fold 4 IBS: 0.22184631620912326
Fold 5 IBS: 0.21759905094032755
[I 2024-04-15 13:40:40,420] Trial 89 finished with value: 0.21913861530337697 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7540347885452335, 'min_weight_fraction_leaf': 0.06459414509901623}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23900229487413618
Fold 2 IBS: 0.1829989350900894
Fold 3 IBS: 0.20504008460974205
Fold 4 IBS: 0.21135329415618298
Fold 5 IBS: 0.20658610615550185
[I 2024-04-15 13:40:41,642] Trial 90 finished with value: 0.20899614297713048 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 95, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7812194815989179, 'min_weight_fraction_leaf': 0.052583924158953604}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23336269917153504
Fold 2 IBS: 0.18793910685243745
Fold 3 IBS: 0.20227191981491185
Fold 4 IBS: 0.2126322523584538
Fold 5 IBS: 0.20891055719221097
[I 2024-04-15 13:40:43,329] Trial 91 finished with value: 0.2090233070779098 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7343789509732842, 'min_weight_fraction_leaf': 0.034512973636926236}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23849245554801698
Fold 2 IBS: 0.18514480626810045
Fold 3 IBS: 0.2021086406752317
Fold 4 IBS: 0.21479834430066197
Fold 5 IBS: 0.20909254443799166
[I 2024-04-15 13:40:44,642] Trial 92 finished with value: 0.20992735824600056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7636505288647887, 'min_weight_fraction_leaf': 0.022561082303242087}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23712661813293098
Fold 2 IBS: 0.1851768236866079
Fold 3 IBS: 0.20432880761759306
Fold 4 IBS: 0.2118089074273193
Fold 5 IBS: 0.20725293903536335
[I 2024-04-15 13:40:46,396] Trial 93 finished with value: 0.20913881917996288 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 195, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.780594325886568, 'min_weight_fraction_leaf': 0.06660760570218983}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23313202103339004
Fold 2 IBS: 0.19197759007192453
Fold 3 IBS: 0.2044094595924962
Fold 4 IBS: 0.20966584275861216
Fold 5 IBS: 0.211313413556971
[I 2024-04-15 13:40:47,406] Trial 94 finished with value: 0.21009966540267877 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 120, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5855639769841374, 'min_weight_fraction_leaf': 0.08355403368257994}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23520267938727427
Fold 2 IBS: 0.20116425107298522
Fold 3 IBS: 0.20510259876427595
Fold 4 IBS: 0.2176827586444227
Fold 5 IBS: 0.21292731974141504
[I 2024-04-15 13:40:48,809] Trial 95 finished with value: 0.21441592152207462 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8103082949117716, 'min_weight_fraction_leaf': 0.11381886996294271}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2366963489001733
Fold 2 IBS: 0.1837117121259892
Fold 3 IBS: 0.20226694531049833
Fold 4 IBS: 0.21335021541537497
Fold 5 IBS: 0.20661189736952593
[I 2024-04-15 13:40:50,116] Trial 96 finished with value: 0.20852742382431236 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7312350213287773, 'min_weight_fraction_leaf': 0.04898698424961209}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23608027081908015
Fold 2 IBS: 0.1835953504200279
Fold 3 IBS: 0.20150615985904316
Fold 4 IBS: 0.2102069690328971
Fold 5 IBS: 0.20748897405413733
[I 2024-04-15 13:40:51,396] Trial 97 finished with value: 0.20777554483703714 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 153, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6968965471814753, 'min_weight_fraction_leaf': 0.0505916256520447}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23389009461942958
Fold 2 IBS: 0.18577086451211336
Fold 3 IBS: 0.20307358104865128
Fold 4 IBS: 0.2086430242358467
Fold 5 IBS: 0.2076497222974857
[I 2024-04-15 13:40:52,576] Trial 98 finished with value: 0.20780545734270534 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6887726496402962, 'min_weight_fraction_leaf': 0.04771137682412141}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2434837934214731
Fold 2 IBS: 0.2272775037538945
Fold 3 IBS: 0.2265372467505086
Fold 4 IBS: 0.23746702398923994
Fold 5 IBS: 0.22710567134340368
[I 2024-04-15 13:40:53,636] Trial 99 finished with value: 0.23237424785170396 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 137, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6897878932245053, 'min_weight_fraction_leaf': 0.3195640033653079}. Best is trial 71 with value: 0.20716724376288945.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.20716724376288945], datetime_start=datetime.datetime(2024, 4, 15, 13, 40, 19, 288128), datetime_complete=datetime.datetime(2024, 4, 15, 13, 40, 19, 837670), params={'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.20716724376288945

In [130]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [131]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.764
train_ibs:  0.207

#### Test

In [132]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [133]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_features=None, max_leaf_nodes=13,
                   max_samples=0.9529576562335005, min_samples_split=15,
                   min_weight_fraction_leaf=0.05156899271012762,
                   n_estimators=376, random_state=123, warm_start=True)

C-index score: 0.543

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=17,
                   max_samples=0.6638490929451707, min_samples_leaf=2,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.052914450220883674,
                   n_estimators=60, oob_score=True, random_state=123)

IBS: 0.256

In [134]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [135]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:40:54,327] A new study created in memory with name: no-name-7cbfa91a-27d6-4980-8745-28ba33eaea14

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:04,641] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:10,108] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:15,690] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:24,757] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:28,795] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:29,678] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:39,606] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:42,859] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:43,259] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:42:08,020] Trial 9 finished with value: 0.7079199845805899 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 13:42:44,949] Trial 10 finished with value: 0.6677145778312712 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:43:35,753] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 13:44:07,682] Trial 12 finished with value: 0.6859221467184631 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:44:21,526] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:44:43,521] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:45:02,907] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:46:28,149] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:46:57,905] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:47:28,702] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:47:29,991] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:47:41,579] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 13:48:07,542] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 13:48:31,656] Trial 22 finished with value: 0.658086559263577 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:48:58,247] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:49:15,853] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:49:37,985] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:49:48,237] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:50:17,307] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:50:19,326] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:50:48,899] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:51:01,769] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-15 13:52:01,585] Trial 31 finished with value: 0.6020563220294257 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:53:04,538] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:53:48,682] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:54:38,422] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 13:55:17,446] Trial 35 finished with value: 0.6743933936379024 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:55:42,333] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:56:03,540] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:56:21,057] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:56:38,396] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:56:58,571] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-15 13:58:03,118] Trial 41 finished with value: 0.6433893503184027 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:58:40,108] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:27,390] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:41,675] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:00:38,765] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 14:00:45,823] Trial 46 finished with value: 0.6994229841114794 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:00:58,054] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:00:58,351] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:01:07,327] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:01:46,425] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:02:17,153] Trial 51 finished with value: 0.6921806327884186 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:02:32,697] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:03:15,564] Trial 53 finished with value: 0.7081084979356779 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:03:51,879] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:03:58,575] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:04:32,709] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6416309012875536
[I 2024-04-15 14:04:37,483] Trial 57 finished with value: 0.7057479712796905 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:04:42,459] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:04:49,503] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:04:58,517] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:05:12,040] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 14:05:36,334] Trial 62 finished with value: 0.712727180870049 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6630901287553648
[I 2024-04-15 14:05:53,933] Trial 63 finished with value: 0.7108187349167132 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:06:14,661] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.4297477654076297, 'learning_rate': 0.043910428099002294, 'dropout_rate': 0.8352402756430523, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4263511298787651, 'min_weight_fraction_leaf': 0.3160966031078735, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9463535838530875, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6416309012875536
[I 2024-04-15 14:06:41,597] Trial 65 finished with value: 0.6902478805446599 and parameters: {'subsample': 0.30781242416514565, 'learning_rate': 0.05113323137902576, 'dropout_rate': 0.7239851485767856, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0027463439227063506, 'min_weight_fraction_leaf': 0.26877432545564617, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0017887993094304819, 'validation_fraction': 0.761339316000577, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:06:56,718] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.48922080655608885, 'learning_rate': 0.035347527077929, 'dropout_rate': 0.8893092269739165, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5356537836856377, 'min_weight_fraction_leaf': 0.29863354085488475, 'max_features': 'sqrt', 'min_impurity_decrease': 0.012061434840147687, 'validation_fraction': 0.9051978098851384, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:20,835] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4210285565476828, 'learning_rate': 0.06591045167415374, 'dropout_rate': 0.8060412975360456, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7762639994874865, 'min_weight_fraction_leaf': 0.25473199100313054, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00610717642726731, 'validation_fraction': 0.8093169248034847, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:29,513] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.36755564370451066, 'learning_rate': 0.05068902572826714, 'dropout_rate': 0.9726834213374217, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1308236536377811, 'min_weight_fraction_leaf': 0.3065580571022596, 'max_features': 'sqrt', 'min_impurity_decrease': 0.021693222709295752, 'validation_fraction': 0.715818151257265, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:41,631] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5142803470563067, 'learning_rate': 0.03243373478476426, 'dropout_rate': 0.9137837647742049, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28985235680036014, 'min_weight_fraction_leaf': 0.4054829396615446, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001581139753892363, 'validation_fraction': 0.329118980782965, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:56,115] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.45559432833731667, 'learning_rate': 0.0700250470025932, 'dropout_rate': 0.8524549437406417, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6643601052078473, 'min_weight_fraction_leaf': 0.2388136010393243, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00031481444052736005, 'validation_fraction': 0.9166648433104408, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6373390557939914
[I 2024-04-15 14:08:20,398] Trial 71 finished with value: 0.6914213405066317 and parameters: {'subsample': 0.3096152191637527, 'learning_rate': 0.05014029765368843, 'dropout_rate': 0.72942553198655, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027173150322083957, 'min_weight_fraction_leaf': 0.28439521854539385, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002459385698607316, 'validation_fraction': 0.9631122514300272, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:47,804] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.2984794016129376, 'learning_rate': 0.04184406116938292, 'dropout_rate': 0.6550072165726977, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791436061459352, 'min_weight_fraction_leaf': 0.28556030062342436, 'max_features': 'sqrt', 'min_impurity_decrease': 4.3401892914387e-05, 'validation_fraction': 0.9667204228379752, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:52,276] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.24177977569589332, 'learning_rate': 0.06081438305266998, 'dropout_rate': 0.7352912026497521, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3565493126455575, 'min_weight_fraction_leaf': 0.2641618003854867, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005565263987110645, 'validation_fraction': 0.8591928424609534, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:09:07,688] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.41766913987966564, 'learning_rate': 0.04837445328457708, 'dropout_rate': 0.7848778465425879, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9796884706123067, 'min_weight_fraction_leaf': 0.3487238233672823, 'max_features': 0.1, 'min_impurity_decrease': 0.060142707029694174, 'validation_fraction': 0.9742035251830021, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:09:20,795] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.14697123662254313, 'learning_rate': 0.056288895309512615, 'dropout_rate': 0.9249274443508626, 'n_estimators': 491, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3014105775868996, 'min_weight_fraction_leaf': 0.2756234570388064, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5125842579708578e-05, 'validation_fraction': 0.9436471609372878, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:10:04,916] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.33597481611005453, 'learning_rate': 0.03785525432874416, 'dropout_rate': 0.5640100673453201, 'n_estimators': 465, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6095307820420031, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 0.009484910777116757, 'validation_fraction': 0.9018697914265744, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:10:54,034] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.3970316343863033, 'learning_rate': 0.02702816788183442, 'dropout_rate': 0.44124671276745586, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.38254401959264994, 'max_features': 1, 'min_impurity_decrease': 0.0031143423876080715, 'validation_fraction': 0.9903409642142473, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6545064377682404
[I 2024-04-15 14:11:39,930] Trial 78 finished with value: 0.6992944115505685 and parameters: {'subsample': 0.22930387168853233, 'learning_rate': 0.05145553889741248, 'dropout_rate': 0.5044517635709308, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.24788146923782178, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010045782837561419, 'validation_fraction': 0.8244464183531952, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:12:30,329] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.5787844954317829, 'learning_rate': 0.046320469166095994, 'dropout_rate': 0.4903660577547442, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8369274241395267, 'min_weight_fraction_leaf': 0.3217471182217138, 'max_features': 'sqrt', 'min_impurity_decrease': 6.262467662262306e-05, 'validation_fraction': 0.822046932546052, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:12:59,515] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.6081624319156314, 'n_estimators': 427, 'criterion': 'friedman_mse', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.20197769506016003, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010150765068526006, 'validation_fraction': 0.7818118403834172, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:13:32,842] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.18443408707190798, 'learning_rate': 0.05259966681355033, 'dropout_rate': 0.6449369275082966, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23050623823206434, 'min_weight_fraction_leaf': 0.25144155938407586, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013502467549795782, 'validation_fraction': 0.8730600269587929, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:14:35,605] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.21084564139781542, 'learning_rate': 0.0557198718851306, 'dropout_rate': 0.5142046015087244, 'n_estimators': 464, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017868752517803354, 'min_weight_fraction_leaf': 0.22672177077398445, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00028049277519258663, 'validation_fraction': 0.9277470449701044, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:15:34,832] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.4945458790853893, 'learning_rate': 0.05895862835575055, 'dropout_rate': 0.7558273871774451, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.501498258850682, 'min_weight_fraction_leaf': 0.28306768635206997, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04144166385519717, 'validation_fraction': 0.8951513356732839, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5708154506437768
[I 2024-04-15 14:17:06,686] Trial 84 finished with value: 0.5444860535940432 and parameters: {'subsample': 0.3659778071469274, 'learning_rate': 0.0502270627847683, 'dropout_rate': 0.6818395627907664, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2606567709484204, 'min_weight_fraction_leaf': 0.2982881980338302, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006662326950079798, 'validation_fraction': 0.8368533116927852, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:18:35,704] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.26399210031385845, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.5847508382404618, 'n_estimators': 406, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9671659583078602, 'min_weight_fraction_leaf': 0.24391254579161395, 'max_features': 'log2', 'min_impurity_decrease': 0.000147849817010694, 'validation_fraction': 0.9991453937475061, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:18:45,969] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10060967717953817, 'learning_rate': 0.020768593047903114, 'dropout_rate': 0.4508818797021682, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.625182110561999, 'min_weight_fraction_leaf': 0.2761510567632799, 'max_features': 1, 'min_impurity_decrease': 0.0023479607608161597, 'validation_fraction': 0.7423283408922972, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5319148936170213
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5708154506437768
[I 2024-04-15 14:20:38,158] Trial 87 finished with value: 0.5635118483198402 and parameters: {'subsample': 0.43950121810340115, 'learning_rate': 0.0648732804536445, 'dropout_rate': 0.34957168713474945, 'n_estimators': 475, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2369430535237365, 'min_weight_fraction_leaf': 0.3096474641971687, 'max_features': 0.1, 'min_impurity_decrease': 4.850175263275894e-05, 'validation_fraction': 0.951557506428991, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:21:02,169] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.21193910478383937, 'learning_rate': 0.06177410341848358, 'dropout_rate': 0.8846843251251039, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.2807191828912141, 'min_weight_fraction_leaf': 0.36091713798964337, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0185550531810504e-05, 'validation_fraction': 0.8545724907452001, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:21:47,130] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.3182195088282702, 'learning_rate': 0.038485790496188235, 'dropout_rate': 0.5004748125823506, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5179293303896771, 'min_weight_fraction_leaf': 0.3315564489154308, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00046699939753012373, 'validation_fraction': 0.9294234431035183, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:22:32,467] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.2762755336662733, 'learning_rate': 0.05273046932737523, 'dropout_rate': 0.5437417743878508, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.8405822272736876, 'min_weight_fraction_leaf': 0.43576713073659407, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8767498848039622, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6459227467811158
[I 2024-04-15 14:23:18,896] Trial 91 finished with value: 0.6948185874130767 and parameters: {'subsample': 0.3126184078929269, 'learning_rate': 0.051134988454074756, 'dropout_rate': 0.7292690956696949, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03786277950879616, 'min_weight_fraction_leaf': 0.2673649069566119, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009910717111428719, 'validation_fraction': 0.7562406049799346, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 14:23:32,480] Trial 92 finished with value: 0.6989359122811389 and parameters: {'subsample': 0.335844111701364, 'learning_rate': 0.05038873458029908, 'dropout_rate': 0.9571283850291226, 'n_estimators': 449, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046820443269266425, 'min_weight_fraction_leaf': 0.2690679137012573, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0008839215080019705, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:23:51,800] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.33719220910486725, 'learning_rate': 0.05705464633480763, 'dropout_rate': 0.9535384595922254, 'n_estimators': 458, 'criterion': 'friedman_mse', 'ccp_alpha': 0.46107702292048336, 'min_weight_fraction_leaf': 0.21683645486742856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.862155169827754e-06, 'validation_fraction': 0.6649080237925696, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5665236051502146
[I 2024-04-15 14:24:07,133] Trial 94 finished with value: 0.5133047210300429 and parameters: {'subsample': 0.3795391698153348, 'learning_rate': 0.05424992354992036, 'dropout_rate': 0.998020448184449, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.25606469361498857, 'min_weight_fraction_leaf': 0.41683364220226815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002584853980433294, 'validation_fraction': 0.7006781615049952, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:24:23,903] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8984320859036168, 'learning_rate': 0.04600776760199582, 'dropout_rate': 0.9375007175299167, 'n_estimators': 432, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6620944039517677, 'min_weight_fraction_leaf': 0.25977850599919555, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001020092546254454, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:24:41,858] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.9444669238877774, 'learning_rate': 0.03476407177203711, 'dropout_rate': 0.9688789578178828, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5985394199987468, 'min_weight_fraction_leaf': 0.4570304925648464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009757952163430444, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:25:20,476] Trial 97 finished with value: 0.6983542268255716 and parameters: {'subsample': 0.40802503425948106, 'learning_rate': 0.060600248591443, 'dropout_rate': 0.8994280356510341, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.16755337346680707, 'min_weight_fraction_leaf': 0.24511190648995798, 'max_features': 'sqrt', 'min_impurity_decrease': 8.96572949971136e-05, 'validation_fraction': 0.627628127325836, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:26:05,604] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.40520020589260825, 'learning_rate': 0.06969431851683794, 'dropout_rate': 0.852867621588153, 'n_estimators': 377, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.23289524687485436, 'max_features': 'sqrt', 'min_impurity_decrease': 9.215043781245307e-05, 'validation_fraction': 0.6236577327109031, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-15 14:26:39,554] A new study created in memory with name: no-name-b460c65e-2ff9-4003-b5ca-869495d88326

Fold 5 C-index: 0.5
[I 2024-04-15 14:26:39,515] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.04234673286327711, 'dropout_rate': 0.8983226388952166, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.0709913910444209, 'min_weight_fraction_leaf': 0.25005718600704474, 'max_features': 'log2', 'min_impurity_decrease': 0.0001309255892076454, 'validation_fraction': 0.6560219357259244, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.


* Best trial for C-index:
 FrozenTrial(number=62, state=TrialState.COMPLETE, values=[0.712727180870049], datetime_start=datetime.datetime(2024, 4, 15, 14, 5, 12, 49652), datetime_complete=datetime.datetime(2024, 4, 15, 14, 5, 36, 332969), params={'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=62, value=None)


* Best Score for C-index:
 0.712727180870049

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:27:48,373] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:28:29,000] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:29:03,368] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 14:30:02,567] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:30:21,245] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:30:28,213] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:31:20,357] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:31:37,324] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:31:39,764] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24603560357944756
Fold 2 IBS: 0.2303451757578765
Fold 3 IBS: 0.22864210229423013
Fold 4 IBS: 0.24084923849388645
Fold 5 IBS: 0.22856534560034253
[I 2024-04-15 14:33:20,062] Trial 9 finished with value: 0.2348874931451566 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316595760132136
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-15 14:36:01,751] Trial 10 finished with value: 0.2356341548121131 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 14:38:12,405] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24715496002116139
Fold 2 IBS: 0.23184438819341896
Fold 3 IBS: 0.2289550256511867
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-15 14:40:26,376] Trial 12 finished with value: 0.23582687970453725 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:41:28,475] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:42:57,379] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:44:17,273] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:44:56,441] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:46:44,215] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:47:38,404] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:47:47,396] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:49:22,925] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24711009086064675
Fold 2 IBS: 0.23198651484788396
Fold 3 IBS: 0.22892152217671352
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-15 14:51:13,652] Trial 21 finished with value: 0.23582876076562656 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.2461444810014907
Fold 2 IBS: 0.2300302068927662
Fold 3 IBS: 0.22866943981867105

Fold 4 IBS: 0.24076805673249593
Fold 5 IBS: 0.2286244137483669
[I 2024-04-15 14:53:00,490] Trial 22 finished with value: 0.23484731963875816 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:54:26,944] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:55:21,981] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:56:14,810] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:57:32,664] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:57:40,474] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 14:58:09,544] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:59:27,831] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:00:01,864] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2469488707078328
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-15 15:01:36,038] Trial 31 finished with value: 0.23566408867478444 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2462866194872135
Fold 2 IBS: 0.23015814957230293
Fold 3 IBS: 0.22867627879341337
Fold 4 IBS: 0.24075894829353398
Fold 5 IBS: 0.22871397901804405
[I 2024-04-15 15:03:06,810] Trial 32 finished with value: 0.23491879503290156 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:04:14,988] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:05:30,985] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:05:46,341] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:07:28,199] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:07:31,732] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:08:38,006] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:10:09,165] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:11:50,186] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24665512418855506
Fold 2 IBS: 0.23079937875838777
Fold 3 IBS: 0.22859112956406855
Fold 4 IBS: 0.2411732320853091
Fold 5 IBS: 0.2289343835210694
[I 2024-04-15 15:13:59,155] Trial 41 finished with value: 0.23523064962347795 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24633993932293982
Fold 2 IBS: 0.23025272242517308
Fold 3 IBS: 0.22801274485299367
Fold 4 IBS: 0.24081637601730027
Fold 5 IBS: 0.22872083072116958
[I 2024-04-15 15:16:30,641] Trial 42 finished with value: 0.2348285226679153 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:19:08,210] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:21:00,478] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24693882344056556
Fold 2 IBS: 0.23145350422053343
Fold 3 IBS: 0.22860307836669258
Fold 4 IBS: 0.24146437703078477
Fold 5 IBS: 0.22909817747073397
[I 2024-04-15 15:23:02,823] Trial 45 finished with value: 0.23551159210586206 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:24:57,035] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:25:42,881] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:25:43,472] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:26:04,415] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:28:22,784] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24695366408679845
Fold 2 IBS: 0.23146997904187452
Fold 3 IBS: 0.2285885733926773
Fold 4 IBS: 0.24149615706388644
Fold 5 IBS: 0.22910431519663427
[I 2024-04-15 15:29:58,673] Trial 51 finished with value: 0.2355225377563742 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:31:56,396] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24641855308804925
Fold 2 IBS: 0.23048568622584525
Fold 3 IBS: 0.2278623120416157
Fold 4 IBS: 0.24068876716298668
Fold 5 IBS: 0.22857688144644517
[I 2024-04-15 15:33:22,973] Trial 53 finished with value: 0.2348064399929884 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:35:20,590] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:36:55,671] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:38:28,058] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:39:54,878] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:42:03,365] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:43:42,583] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:44:33,863] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:45:48,635] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2468810203480293
Fold 2 IBS: 0.2311990963376084
Fold 3 IBS: 0.228454108036685
Fold 4 IBS: 0.24124096112643856
Fold 5 IBS: 0.22895207624265332
[I 2024-04-15 15:46:53,341] Trial 62 finished with value: 0.23534545241828292 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:48:05,445] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2465043054793762
Fold 2 IBS: 0.23031643211780425
Fold 3 IBS: 0.2279578986949742
Fold 4 IBS: 0.24045858876874635
Fold 5 IBS: 0.22854526131961184
[I 2024-04-15 15:49:06,457] Trial 64 finished with value: 0.23475649727610257 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-15 15:49:59,679] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:51:01,372] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:51:40,487] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:53:14,654] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:54:35,835] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:55:40,705] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.2469128753364667
Fold 2 IBS: 0.23120680886119857
Fold 3 IBS: 0.2284490521729702
Fold 4 IBS: 0.2412928489959067
Fold 5 IBS: 0.22897078571077217
[I 2024-04-15 15:56:43,988] Trial 71 finished with value: 0.23536647421546286 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24699640897951017
Fold 2 IBS: 0.23151620221444727
Fold 3 IBS: 0.22861416387399014
Fold 4 IBS: 0.24155860571648258
Fold 5 IBS: 0.22912133061238216
[I 2024-04-15 15:57:29,350] Trial 72 finished with value: 0.23556134227936246 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:57:36,929] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:59:47,383] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:00:36,402] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:01:36,561] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:02:53,900] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:03:31,657] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:04:58,434] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:05:36,201] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24689956409794034
Fold 2 IBS: 0.23118732433711728
Fold 3 IBS: 0.22843302311048683
Fold 4 IBS: 0.24126338444926765
Fold 5 IBS: 0.22894778512748845
[I 2024-04-15 16:06:33,714] Trial 81 finished with value: 0.23534621622446011 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:07:41,319] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:08:56,737] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898150255235122
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293932698055425
[I 2024-04-15 16:09:40,057] Trial 84 finished with value: 0.23592730576033555 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24536364898371674
Fold 2 IBS: 0.22661035397022303
Fold 3 IBS: 0.226596757813156
Fold 4 IBS: 0.2389442424082662
Fold 5 IBS: 0.22754912881625142
[I 2024-04-15 16:11:14,704] Trial 85 finished with value: 0.23301282639832266 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:12:52,316] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8908016266221349, 'learning_rate': 0.020782252048892114, 'dropout_rate': 0.20248417164561996, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.025928909209021245, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:13:25,415] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953409887733455, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:15:17,066] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.0030671608519508686, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.27772784044341225, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:17:01,351] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9240076064991638, 'learning_rate': 0.036372907201929795, 'dropout_rate': 0.16604269499086277, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.6288732373244443, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.8456629128553931, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:18:38,773] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.22333957383529762, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24648485188041894
Fold 2 IBS: 0.2305073947731919
Fold 3 IBS: 0.22795134549192056
Fold 4 IBS: 0.24057179186781263
Fold 5 IBS: 0.22853359304710397
[I 2024-04-15 16:20:12,860] Trial 91 finished with value: 0.23480979541208963 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.01642165444052923, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.901410266511097, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:21:49,514] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.012238074680872561, 'dropout_rate': 0.2583752131981347, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 2.0262506829884978e-07, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:23:23,016] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9444060832329966, 'learning_rate': 0.017856303491279684, 'dropout_rate': 0.30303355573944185, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.011908761872398903, 'max_features': 'auto', 'min_impurity_decrease': 6.055732421263935e-07, 'validation_fraction': 0.864284511598723, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:24:57,427] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8821760782294449, 'learning_rate': 0.005785552173633914, 'dropout_rate': 0.28058975756978766, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.8506324992317083, 'min_weight_fraction_leaf': 0.04622694094641695, 'max_features': None, 'min_impurity_decrease': 1.3402986834437386e-07, 'validation_fraction': 0.8985100287316004, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:26:50,292] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9761707513926794, 'learning_rate': 0.019567902784876703, 'dropout_rate': 0.3201948574529592, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.0386964570043107, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9417888137501867, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24641425402466968
Fold 2 IBS: 0.22943554006463165
Fold 3 IBS: 0.22871680820224374
Fold 4 IBS: 0.24077011514188554
Fold 5 IBS: 0.22840019828947677
[I 2024-04-15 16:28:30,802] Trial 96 finished with value: 0.2347473831445815 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.01055205151962401, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.09708890262536518, 'max_features': 'auto', 'min_impurity_decrease': 3.7395479538673736e-07, 'validation_fraction': 0.992337544991608, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:30:10,357] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.010954886262406833, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 1.603167122698403, 'min_weight_fraction_leaf': 0.06013220413302209, 'max_features': 'auto', 'min_impurity_decrease': 3.972456306049239e-07, 'validation_fraction': 0.9976245698846969, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:31:15,152] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8505038223267275, 'learning_rate': 0.013402809510359784, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 0.25666428673598457, 'min_weight_fraction_leaf': 0.1129024126904408, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.9625603744870045, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:32:48,689] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.06808689488183181, 'dropout_rate': 0.25443633448028735, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5386043790221791, 'min_weight_fraction_leaf': 0.03403879613376609, 'max_features': 'auto', 'min_impurity_decrease': 8.69596280226011e-07, 'validation_fraction': 0.9221483446288596, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23301282639832266], datetime_start=datetime.datetime(2024, 4, 15, 16, 9, 40, 66714), datetime_complete=datetime.datetime(2024, 4, 15, 16, 11, 14, 702735), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23301282639832266

In [136]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [137]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.713
train_ibs:  0.233

#### Test

In [138]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [139]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.022737959076050005,
                                 dropout_rate=0.8285090704895912,
                                 learning_rate=0.0513322635401625, max_depth=2,
                                 max_features='sqrt', max_leaf_nodes=10,
                                 min_impurity_decrease=0.002070496973827786,
                                 min_samples_leaf=15, min_samples_split=19,
                                 min_weight_fraction_leaf=0.3101145382804477,
                                 n_estimators=485, random_state=123,
                                 subsample=0.45214538811231725,
                                 validation_fraction=0.9071319756271838)

C-index score: 0.532

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.229

In [140]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [141]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 16:33:17,622] A new study created in memory with name: no-name-fafcec89-1782-4783-a48b-4fe0e440c784

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:33:19,237] Trial 0 finished with value: 0.6238037606018434 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6238037606018434.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:33:33,043] Trial 1 finished with value: 0.6238037606018434 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6238037606018434.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 16:33:36,245] Trial 2 finished with value: 0.6332339005050803 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6332339005050803.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:33:39,838] Trial 3 finished with value: 0.634852725877557 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.634852725877557.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:33:44,927] Trial 4 finished with value: 0.6465065560325141 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6465065560325141.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:33:50,674] Trial 5 finished with value: 0.6271321458896547 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6465065560325141.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:33:53,196] Trial 6 finished with value: 0.6230285668033938 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6465065560325141.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:33:53,733] Trial 7 finished with value: 0.6379676877661498 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6465065560325141.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:33:57,053] Trial 8 finished with value: 0.6362366358870958 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6465065560325141.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:34:06,306] Trial 9 finished with value: 0.6371604126673625 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6465065560325141.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:34:12,700] Trial 10 finished with value: 0.6606990941258173 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6606990941258173.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:34:19,890] Trial 11 finished with value: 0.6649436969513003 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6649436969513003.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:34:26,207] Trial 12 finished with value: 0.663118329605474 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.6649436969513003.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:34:35,529] Trial 13 finished with value: 0.6222533730049442 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.6649436969513003.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:34:43,222] Trial 14 finished with value: 0.6686270138087715 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 14 with value: 0.6686270138087715.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:34:50,193] Trial 15 finished with value: 0.653221725876987 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.7098041576457912, 'n_estimators': 365, 'learning_rate': 0.08616677729964022}. Best is trial 14 with value: 0.6686270138087715.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:34:59,380] Trial 16 finished with value: 0.659989308008922 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.7326988341376399, 'n_estimators': 423, 'learning_rate': 0.08463638125592773}. Best is trial 14 with value: 0.6686270138087715.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:35:09,882] Trial 17 finished with value: 0.6456198299784748 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.6125221083505048, 'n_estimators': 413, 'learning_rate': 0.08749976591807801}. Best is trial 14 with value: 0.6686270138087715.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:35:15,179] Trial 18 finished with value: 0.6482345778175449 and parameters: {'subsample': 0.35888747153360906, 'dropout_rate': 0.8058789888144481, 'n_estimators': 324, 'learning_rate': 0.09062397105934869}. Best is trial 14 with value: 0.6686270138087715.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:35:22,767] Trial 19 finished with value: 0.6679528899161283 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9820749239416067, 'n_estimators': 431, 'learning_rate': 0.08300323114610605}. Best is trial 14 with value: 0.6686270138087715.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:35:31,962] Trial 20 finished with value: 0.6540975657381868 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.7933084651006226, 'n_estimators': 438, 'learning_rate': 0.0796244585080611}. Best is trial 14 with value: 0.6686270138087715.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:35:39,310] Trial 21 finished with value: 0.6687644401898177 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.9754161103921428, 'n_estimators': 387, 'learning_rate': 0.09637537942321125}. Best is trial 21 with value: 0.6687644401898177.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:35:46,467] Trial 22 finished with value: 0.6706655505801468 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.9893004819878006, 'n_estimators': 396, 'learning_rate': 0.09976063116358903}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:35:52,674] Trial 23 finished with value: 0.6585150872995815 and parameters: {'subsample': 0.1850567218204376, 'dropout_rate': 0.9573423083551811, 'n_estimators': 376, 'learning_rate': 0.09934010655642313}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:35:56,705] Trial 24 finished with value: 0.6600181052415667 and parameters: {'subsample': 0.20380943129128443, 'dropout_rate': 0.8927165518290331, 'n_estimators': 268, 'learning_rate': 0.0997124061814819}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:36:05,264] Trial 25 finished with value: 0.647974462580138 and parameters: {'subsample': 0.41518848496569194, 'dropout_rate': 0.9918223572405526, 'n_estimators': 464, 'learning_rate': 0.06445808027772273}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:36:12,611] Trial 26 finished with value: 0.6483682798535801 and parameters: {'subsample': 0.2958189169734158, 'dropout_rate': 0.7986467346238929, 'n_estimators': 394, 'learning_rate': 0.0917099648600269}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:36:18,019] Trial 27 finished with value: 0.6222533730049442 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.9170179076508909, 'n_estimators': 342, 'learning_rate': 0.07492547164422446}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.5965665236051502
[I 2024-04-15 16:36:22,503] Trial 28 finished with value: 0.6296632945854058 and parameters: {'subsample': 0.6095590802808257, 'dropout_rate': 0.8528818052986153, 'n_estimators': 290, 'learning_rate': 0.04202399206134448}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:36:22,879] Trial 29 finished with value: 0.6222533730049442 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.6199412831293672, 'n_estimators': 28, 'learning_rate': 0.07992321223421696}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:36:26,410] Trial 30 finished with value: 0.6632996717043549 and parameters: {'subsample': 0.15736775526254157, 'dropout_rate': 0.7457374535389898, 'n_estimators': 244, 'learning_rate': 0.09319357330919621}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:36:35,449] Trial 31 finished with value: 0.6671924336423641 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.9931918342399367, 'n_estimators': 449, 'learning_rate': 0.08166797607699186}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:36:45,544] Trial 32 finished with value: 0.6706039942304384 and parameters: {'subsample': 0.102000681955651, 'dropout_rate': 0.9359886879105771, 'n_estimators': 489, 'learning_rate': 0.09339124286731738}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:36:54,093] Trial 33 finished with value: 0.6591386680221909 and parameters: {'subsample': 0.22215986403186463, 'dropout_rate': 0.9331291439730837, 'n_estimators': 485, 'learning_rate': 0.09373382190739717}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:37:00,809] Trial 34 finished with value: 0.6497955547510624 and parameters: {'subsample': 0.31478192981222664, 'dropout_rate': 0.8419653637896015, 'n_estimators': 403, 'learning_rate': 0.06958595449186536}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:37:02,046] Trial 35 finished with value: 0.6659323141489686 and parameters: {'subsample': 0.16650812596288117, 'dropout_rate': 0.945218770342364, 'n_estimators': 124, 'learning_rate': 0.09455703838649862}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:37:13,978] Trial 36 finished with value: 0.6549340190301236 and parameters: {'subsample': 0.24952743476459022, 'dropout_rate': 0.5057820537511932, 'n_estimators': 496, 'learning_rate': 0.0733002365552525}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:37:19,458] Trial 37 finished with value: 0.6615902387758551 and parameters: {'subsample': 0.15264381063613053, 'dropout_rate': 0.8522976407331874, 'n_estimators': 348, 'learning_rate': 0.059207327336158105}. Best is trial 22 with value: 0.6706655505801468.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:37:26,661] Trial 38 finished with value: 0.6616522189686197 and parameters: {'subsample': 0.23557094034920928, 'dropout_rate': 0.777571897600354, 'n_estimators': 393, 'learning_rate': 0.07844703170656485}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:37:36,238] Trial 39 finished with value: 0.6488576077102631 and parameters: {'subsample': 0.31440461040323664, 'dropout_rate': 0.6881141432789704, 'n_estimators': 459, 'learning_rate': 0.01033884503473171}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:37:39,062] Trial 40 finished with value: 0.6406219491613179 and parameters: {'subsample': 0.4315561410698563, 'dropout_rate': 0.8887286631915676, 'n_estimators': 245, 'learning_rate': 0.08895397896247655}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:37:45,785] Trial 41 finished with value: 0.6671924336423641 and parameters: {'subsample': 0.10437662902118044, 'dropout_rate': 0.9903568245541834, 'n_estimators': 432, 'learning_rate': 0.09521918107071164}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:37:53,104] Trial 42 finished with value: 0.664606720575347 and parameters: {'subsample': 0.15473768272058921, 'dropout_rate': 0.9475523537918924, 'n_estimators': 425, 'learning_rate': 0.08321961722955908}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:38:01,424] Trial 43 finished with value: 0.6606769243453718 and parameters: {'subsample': 0.13613017047488835, 'dropout_rate': 0.9989156275131367, 'n_estimators': 495, 'learning_rate': 0.09942037976755917}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:38:13,326] Trial 44 finished with value: 0.6671851283734389 and parameters: {'subsample': 0.1023646265230407, 'dropout_rate': 0.4454251840454448, 'n_estimators': 460, 'learning_rate': 0.08714761847621738}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:38:20,232] Trial 45 finished with value: 0.661745983605501 and parameters: {'subsample': 0.19317043995957506, 'dropout_rate': 0.8895664074349547, 'n_estimators': 394, 'learning_rate': 0.09404396589113483}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:38:26,312] Trial 46 finished with value: 0.6632342640228005 and parameters: {'subsample': 0.18068596149934607, 'dropout_rate': 0.8296004506713203, 'n_estimators': 340, 'learning_rate': 0.08956754653079327}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:38:32,269] Trial 47 finished with value: 0.6238037606018434 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.9539658845576164, 'n_estimators': 381, 'learning_rate': 0.06820381773185234}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:38:42,575] Trial 48 finished with value: 0.6321625318502055 and parameters: {'subsample': 0.5997115110609152, 'dropout_rate': 0.9056829442011933, 'n_estimators': 478, 'learning_rate': 0.027763821111874188}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:38:52,264] Trial 49 finished with value: 0.6615680689954097 and parameters: {'subsample': 0.13745453782857242, 'dropout_rate': 0.6406402397657515, 'n_estimators': 443, 'learning_rate': 0.04361258259711658}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:38:59,758] Trial 50 finished with value: 0.6581862803129275 and parameters: {'subsample': 0.22472246171781585, 'dropout_rate': 0.5767499157726772, 'n_estimators': 358, 'learning_rate': 0.08386253729921406}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:39:08,096] Trial 51 finished with value: 0.6671924336423641 and parameters: {'subsample': 0.10362897608381406, 'dropout_rate': 0.971820591080397, 'n_estimators': 445, 'learning_rate': 0.08276254510722597}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:39:16,685] Trial 52 finished with value: 0.6637842841088181 and parameters: {'subsample': 0.13383579716458174, 'dropout_rate': 0.921537994514298, 'n_estimators': 416, 'learning_rate': 0.07677729343067873}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:39:25,505] Trial 53 finished with value: 0.6602172149591561 and parameters: {'subsample': 0.18560065202743314, 'dropout_rate': 0.9775527881204777, 'n_estimators': 454, 'learning_rate': 0.09733685362329184}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:39:37,041] Trial 54 finished with value: 0.6679166604277237 and parameters: {'subsample': 0.1292381025296356, 'dropout_rate': 0.3571755626038756, 'n_estimators': 420, 'learning_rate': 0.08973373624477281}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:39:49,119] Trial 55 finished with value: 0.6638824937899874 and parameters: {'subsample': 0.15026519006674177, 'dropout_rate': 0.2626407750827734, 'n_estimators': 411, 'learning_rate': 0.08983279429938366}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:39:57,742] Trial 56 finished with value: 0.6514322747290827 and parameters: {'subsample': 0.27041927101890395, 'dropout_rate': 0.32162536175845224, 'n_estimators': 376, 'learning_rate': 0.09687731713556048}. Best is trial 22 with value: 0.6706655505801468.

Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:40:12,102] Trial 57 finished with value: 0.6615865144308442 and parameters: {'subsample': 0.2066370680399511, 'dropout_rate': 0.16588785750113677, 'n_estimators': 477, 'learning_rate': 0.08569286911852897}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:40:18,904] Trial 58 finished with value: 0.6648204572650483 and parameters: {'subsample': 0.17416143586357416, 'dropout_rate': 0.36573681723837637, 'n_estimators': 326, 'learning_rate': 0.09116228831045586}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:40:29,346] Trial 59 finished with value: 0.6680145732526718 and parameters: {'subsample': 0.1348802707273966, 'dropout_rate': 0.44028340958889167, 'n_estimators': 427, 'learning_rate': 0.09993815761691235}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:40:35,952] Trial 60 finished with value: 0.6555969863219959 and parameters: {'subsample': 0.24841063685317663, 'dropout_rate': 0.49657889694079194, 'n_estimators': 310, 'learning_rate': 0.037667655525589566}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:40:46,443] Trial 61 finished with value: 0.6671562041539594 and parameters: {'subsample': 0.12973261256039142, 'dropout_rate': 0.4506107125647254, 'n_estimators': 425, 'learning_rate': 0.09990940529526243}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:40:55,615] Trial 62 finished with value: 0.6655083275751681 and parameters: {'subsample': 0.12885555702292248, 'dropout_rate': 0.41293181100049164, 'n_estimators': 401, 'learning_rate': 0.0966461414464128}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:41:05,006] Trial 63 finished with value: 0.6613874047132547 and parameters: {'subsample': 0.20831751889658867, 'dropout_rate': 0.29369875529918454, 'n_estimators': 383, 'learning_rate': 0.09173745530056542}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:41:15,855] Trial 64 finished with value: 0.6646173263462268 and parameters: {'subsample': 0.10179131347843295, 'dropout_rate': 0.3782143193149822, 'n_estimators': 435, 'learning_rate': 0.08701176719865163}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:41:23,889] Trial 65 finished with value: 0.6639041127405418 and parameters: {'subsample': 0.16457030332707762, 'dropout_rate': 0.3180560231559292, 'n_estimators': 366, 'learning_rate': 0.09646526569509951}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:41:36,059] Trial 66 finished with value: 0.6591093199596552 and parameters: {'subsample': 0.13281041593140952, 'dropout_rate': 0.5550202278561857, 'n_estimators': 472, 'learning_rate': 0.09283472134323789}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:41:39,742] Trial 67 finished with value: 0.6557603068284983 and parameters: {'subsample': 0.2902151621354211, 'dropout_rate': 0.4284346573874135, 'n_estimators': 203, 'learning_rate': 0.09490401293367616}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:41:42,170] Trial 68 finished with value: 0.6615216740134428 and parameters: {'subsample': 0.182783707866624, 'dropout_rate': 0.86891932652296, 'n_estimators': 147, 'learning_rate': 0.05223391520106252}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:41:50,407] Trial 69 finished with value: 0.6572301253761017 and parameters: {'subsample': 0.22091368276882345, 'dropout_rate': 0.7722471825084228, 'n_estimators': 412, 'learning_rate': 0.08784687300196163}. Best is trial 22 with value: 0.6706655505801468.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:41:51,304] Trial 70 finished with value: 0.6727843595445964 and parameters: {'subsample': 0.15638119002439485, 'dropout_rate': 0.4771581011016842, 'n_estimators': 79, 'learning_rate': 0.09979840577928892}. Best is trial 70 with value: 0.6727843595445964.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:41:52,353] Trial 71 finished with value: 0.6702781138670927 and parameters: {'subsample': 0.1547458177005656, 'dropout_rate': 0.48010927280862115, 'n_estimators': 84, 'learning_rate': 0.09996673647561895}. Best is trial 70 with value: 0.6727843595445964.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 16:41:53,155] Trial 72 finished with value: 0.6739727571947215 and parameters: {'subsample': 0.15426584909876156, 'dropout_rate': 0.5046601725161014, 'n_estimators': 62, 'learning_rate': 0.09998161351585051}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:41:53,901] Trial 73 finished with value: 0.6392458952505956 and parameters: {'subsample': 0.33269899509565115, 'dropout_rate': 0.522228201630752, 'n_estimators': 65, 'learning_rate': 0.09934997924750641}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:41:54,905] Trial 74 finished with value: 0.6644619447714739 and parameters: {'subsample': 0.16355813192072213, 'dropout_rate': 0.48317905969919556, 'n_estimators': 78, 'learning_rate': 0.09654530021372357}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:41:55,262] Trial 75 finished with value: 0.6306122712401413 and parameters: {'subsample': 0.6882223870109341, 'dropout_rate': 0.5799729523313646, 'n_estimators': 20, 'learning_rate': 0.09985317802326342}. Best is trial 72 with value: 0.6739727571947215.

Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:41:56,574] Trial 76 finished with value: 0.6594279614527472 and parameters: {'subsample': 0.20335500047276844, 'dropout_rate': 0.46859311976951457, 'n_estimators': 93, 'learning_rate': 0.0942512625288357}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:41:57,183] Trial 77 finished with value: 0.6537710517120169 and parameters: {'subsample': 0.23738113595184007, 'dropout_rate': 0.5340794382591971, 'n_estimators': 39, 'learning_rate': 0.09761211807897123}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:41:58,887] Trial 78 finished with value: 0.6625423725114488 and parameters: {'subsample': 0.1530914617626657, 'dropout_rate': 0.39620630360775916, 'n_estimators': 125, 'learning_rate': 0.09163912002804776}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 16:42:00,011] Trial 79 finished with value: 0.6611708671157295 and parameters: {'subsample': 0.11913718959156779, 'dropout_rate': 0.5718686920662251, 'n_estimators': 97, 'learning_rate': 0.09321245397705999}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 16:42:00,708] Trial 80 finished with value: 0.6364105457302165 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.4787728529747134, 'n_estimators': 61, 'learning_rate': 0.09771937223576754}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:42:00,820] Trial 81 finished with value: 0.6481132085818374 and parameters: {'subsample': 0.18742935897276408, 'dropout_rate': 0.5177014821609018, 'n_estimators': 9, 'learning_rate': 0.09998205611568732}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:42:02,706] Trial 82 finished with value: 0.6672177605036678 and parameters: {'subsample': 0.11905557651805837, 'dropout_rate': 0.9622515247466068, 'n_estimators': 161, 'learning_rate': 0.09534330057175579}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 16:42:03,369] Trial 83 finished with value: 0.6323975741999786 and parameters: {'subsample': 0.5369819933817884, 'dropout_rate': 0.9412843311703987, 'n_estimators': 62, 'learning_rate': 0.09252527281067688}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:42:07,822] Trial 84 finished with value: 0.6695649608495711 and parameters: {'subsample': 0.14789353466167496, 'dropout_rate': 0.4251910620827108, 'n_estimators': 264, 'learning_rate': 0.08063234843954259}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:42:11,475] Trial 85 finished with value: 0.6639042397273768 and parameters: {'subsample': 0.1521263788448379, 'dropout_rate': 0.4119861830087574, 'n_estimators': 233, 'learning_rate': 0.056648795951364773}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:42:16,108] Trial 86 finished with value: 0.6222533730049442 and parameters: {'subsample': 0.992873343787547, 'dropout_rate': 0.4334599650405949, 'n_estimators': 278, 'learning_rate': 0.015683786418193443}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:42:17,393] Trial 87 finished with value: 0.6683913171583928 and parameters: {'subsample': 0.1731384740882462, 'dropout_rate': 0.4670302261021519, 'n_estimators': 105, 'learning_rate': 0.08089971520494037}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:42:18,635] Trial 88 finished with value: 0.6518955814734744 and parameters: {'subsample': 0.2553655186038719, 'dropout_rate': 0.6081765199156515, 'n_estimators': 100, 'learning_rate': 0.06976337825188361}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:42:19,276] Trial 89 finished with value: 0.6735555321418139 and parameters: {'subsample': 0.177199484105048, 'dropout_rate': 0.46157727847244007, 'n_estimators': 47, 'learning_rate': 0.08800902519920796}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:42:20,266] Trial 90 finished with value: 0.6641726513409176 and parameters: {'subsample': 0.19665484908952885, 'dropout_rate': 0.6507504279857488, 'n_estimators': 79, 'learning_rate': 0.08682121061253528}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:42:20,877] Trial 91 finished with value: 0.6702596091148451 and parameters: {'subsample': 0.17128820087187452, 'dropout_rate': 0.46520233469698213, 'n_estimators': 39, 'learning_rate': 0.07921550330940585}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:42:21,531] Trial 92 finished with value: 0.6692926537502826 and parameters: {'subsample': 0.15579039138392559, 'dropout_rate': 0.49706819400878616, 'n_estimators': 49, 'learning_rate': 0.08426055991289705}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:42:22,078] Trial 93 finished with value: 0.6687749689382727 and parameters: {'subsample': 0.1536395640837683, 'dropout_rate': 0.49834455834178254, 'n_estimators': 40, 'learning_rate': 0.08473623841875641}. Best is trial 72 with value: 0.6739727571947215.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:42:22,554] Trial 94 finished with value: 0.6788825332361077 and parameters: {'subsample': 0.15060954939051235, 'dropout_rate': 0.4957349175953175, 'n_estimators': 34, 'learning_rate': 0.0746944239704296}. Best is trial 94 with value: 0.6788825332361077.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:42:22,954] Trial 95 finished with value: 0.6617527986326982 and parameters: {'subsample': 0.2204658688157468, 'dropout_rate': 0.54075068857864, 'n_estimators': 25, 'learning_rate': 0.07083660464706047}. Best is trial 94 with value: 0.6788825332361077.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:42:23,645] Trial 96 finished with value: 0.6651425098126683 and parameters: {'subsample': 0.1768459546193365, 'dropout_rate': 0.4581850400636413, 'n_estimators': 52, 'learning_rate': 0.06413325090254297}. Best is trial 94 with value: 0.6788825332361077.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:42:24,502] Trial 97 finished with value: 0.6594573701034461 and parameters: {'subsample': 0.2825875542570781, 'dropout_rate': 0.510292873579134, 'n_estimators': 78, 'learning_rate': 0.0776066979603849}. Best is trial 94 with value: 0.6788825332361077.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.3404255319148936
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 16:42:24,756] Trial 98 finished with value: 0.6038535671639929 and parameters: {'subsample': 0.23720433623658999, 'dropout_rate': 0.4894709539243596, 'n_estimators': 1, 'learning_rate': 0.07973512041600855}. Best is trial 94 with value: 0.6788825332361077.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.774468085106383

[I 2024-04-15 16:42:25,389] A new study created in memory with name: no-name-ba0804ca-8e0c-45ee-8427-39f5105a6927

Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:42:25,377] Trial 99 finished with value: 0.6842029939146556 and parameters: {'subsample': 0.14488143846919227, 'dropout_rate': 0.4136725222049048, 'n_estimators': 46, 'learning_rate': 0.07578621907115225}. Best is trial 99 with value: 0.6842029939146556.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.6842029939146556], datetime_start=datetime.datetime(2024, 4, 15, 16, 42, 24, 766356), datetime_complete=datetime.datetime(2024, 4, 15, 16, 42, 25, 377302), params={'subsample': 0.14488143846919227, 'dropout_rate': 0.4136725222049048, 'n_estimators': 46, 'learning_rate': 0.07578621907115225}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=99, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.14488143846919227, 'dropout_rate': 0.4136725222049048, 'n_estimators': 46, 'learning_rate': 0.07578621907115225}


* Best Score for C-index:
 0.6842029939146556

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.25743063664610333
Fold 2 IBS: 0.1869435419694585
Fold 3 IBS: 0.23066689078693747
Fold 4 IBS: 0.22902982775384303
Fold 5 IBS: 0.22204595538875738
[I 2024-04-15 16:42:26,798] Trial 0 finished with value: 0.22522337050901994 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.3737646855274175
Fold 2 IBS: 0.16526672590116237
Fold 3 IBS: 0.2914187515159566
Fold 4 IBS: 0.29641000647065047
Fold 5 IBS: 0.30622282374557835
[I 2024-04-15 16:42:40,639] Trial 1 finished with value: 0.28661659863215305 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.2894167730855773
Fold 2 IBS: 0.1673647949369864
Fold 3 IBS: 0.22589174969929982
Fold 4 IBS: 0.24018572095086071
Fold 5 IBS: 0.22964083875845195
[I 2024-04-15 16:42:42,994] Trial 2 finished with value: 0.23049997548623521 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.29909139024212766
Fold 2 IBS: 0.16508483621481965
Fold 3 IBS: 0.23103152127480236
Fold 4 IBS: 0.24849077365144842
Fold 5 IBS: 0.23479213004822339
[I 2024-04-15 16:42:46,089] Trial 3 finished with value: 0.2356981302862843 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.29895969243521786
Fold 2 IBS: 0.17099931023067722
Fold 3 IBS: 0.21663221653839473
Fold 4 IBS: 0.2322683602183381
Fold 5 IBS: 0.22783041980792992
[I 2024-04-15 16:42:50,451] Trial 4 finished with value: 0.22933799984611153 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.33263641411531625
Fold 2 IBS: 0.15381988642878835
Fold 3 IBS: 0.2614336048429884
Fold 4 IBS: 0.27266458839120405
Fold 5 IBS: 0.2706723857083513
[I 2024-04-15 16:42:56,177] Trial 5 finished with value: 0.25824537589732965 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.24894755508266628
Fold 2 IBS: 0.20033694714548572
Fold 3 IBS: 0.22952771270088154
Fold 4 IBS: 0.22959196505391513
Fold 5 IBS: 0.2223251585136378
[I 2024-04-15 16:42:58,608] Trial 6 finished with value: 0.22614586769931727 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.24532071745543751
Fold 2 IBS: 0.21907230065222635
Fold 3 IBS: 0.2266137755795569
Fold 4 IBS: 0.23444955953220797
Fold 5 IBS: 0.22469131480944785
[I 2024-04-15 16:42:59,148] Trial 7 finished with value: 0.2300295336057753 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 0 with value: 0.22522337050901994.
Fold 1 IBS: 0.26096141865891076
Fold 2 IBS: 0.18800368789935357
Fold 3 IBS: 0.22517226938646862
Fold 4 IBS: 0.22721230640919718
Fold 5 IBS: 0.22108600386913824
[I 2024-04-15 16:43:02,090] Trial 8 finished with value: 0.2244871372446137 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 8 with value: 0.2244871372446137.
Fold 1 IBS: 0.3394447524847492
Fold 2 IBS: 0.15651184422122108
Fold 3 IBS: 0.2493659937652677
Fold 4 IBS: 0.27425937296860126
Fold 5 IBS: 0.2744830118323018
[I 2024-04-15 16:43:10,499] Trial 9 finished with value: 0.2588129950544282 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 8 with value: 0.2244871372446137.
Fold 1 IBS: 0.2460259431673939
Fold 2 IBS: 0.22773332496009027
Fold 3 IBS: 0.22881426272857427
Fold 4 IBS: 0.23966173133228597
Fold 5 IBS: 0.22804294828294194
[I 2024-04-15 16:43:15,465] Trial 10 finished with value: 0.23405564209425728 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.6778199652121663, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 8 with value: 0.2244871372446137.
Fold 1 IBS: 0.24599627681522396
Fold 2 IBS: 0.2275974354439764
Fold 3 IBS: 0.22880459889730725
Fold 4 IBS: 0.23963784322011175
Fold 5 IBS: 0.22802054334596616
[I 2024-04-15 16:43:15,849] Trial 11 finished with value: 0.23401133954451708 and parameters: {'subsample': 0.9277275137801013, 'dropout_rate': 0.2936367839076394, 'n_estimators': 19, 'learning_rate': 0.029244469049093436}. Best is trial 8 with value: 0.2244871372446137.
Fold 1 IBS: 0.26222071257965757
Fold 2 IBS: 0.19088546080159324
Fold 3 IBS: 0.20254614210829316
Fold 4 IBS: 0.2202325114128362
Fold 5 IBS: 0.21465428827956445
[I 2024-04-15 16:43:17,042] Trial 12 finished with value: 0.21810782303638893 and parameters: {'subsample': 0.17298802250354745, 'dropout_rate': 0.6252957097820372, 'n_estimators': 92, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.21810782303638893.
Fold 1 IBS: 0.2695674309107436
Fold 2 IBS: 0.18452700385035528
Fold 3 IBS: 0.20868534787020732
Fold 4 IBS: 0.21639432639529144
Fold 5 IBS: 0.21393490280880748
[I 2024-04-15 16:43:18,313] Trial 13 finished with value: 0.21862180236708104 and parameters: {'subsample': 0.11500009154107056, 'dropout_rate': 0.6597972259787923, 'n_estimators': 109, 'learning_rate': 0.09856277651579823}. Best is trial 12 with value: 0.21810782303638893.
Fold 1 IBS: 0.268225171516335
Fold 2 IBS: 0.18592108072717475
Fold 3 IBS: 0.2150608039317379
Fold 4 IBS: 0.21694848521196883
Fold 5 IBS: 0.21353394295364245
[I 2024-04-15 16:43:19,443] Trial 14 finished with value: 0.21993789686817178 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7088601911332494, 'n_estimators': 100, 'learning_rate': 0.09980514090256132}. Best is trial 12 with value: 0.21810782303638893.
Fold 1 IBS: 0.26346803551271997
Fold 2 IBS: 0.18502607212855612
Fold 3 IBS: 0.2027778308468064
Fold 4 IBS: 0.21235974096982024
Fold 5 IBS: 0.21267878280650332
[I 2024-04-15 16:43:20,605] Trial 15 finished with value: 0.21526209245288125 and parameters: {'subsample': 0.10124041097494478, 'dropout_rate': 0.7762772864861316, 'n_estimators': 98, 'learning_rate': 0.0994821444513409}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.24636831456017966
Fold 2 IBS: 0.23112018298462722
Fold 3 IBS: 0.22829102163254633
Fold 4 IBS: 0.23984895124164596
Fold 5 IBS: 0.22836848747157124
[I 2024-04-15 16:43:20,895] Trial 16 finished with value: 0.23479939157811408 and parameters: {'subsample': 0.25470623831733574, 'dropout_rate': 0.8188220104688464, 'n_estimators': 4, 'learning_rate': 0.08820363883892024}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2564489701450566
Fold 2 IBS: 0.19871156718748154
Fold 3 IBS: 0.21863066153097763
Fold 4 IBS: 0.21928658227398065
Fold 5 IBS: 0.2178933240216195
[I 2024-04-15 16:43:21,788] Trial 17 finished with value: 0.2221942210318232 and parameters: {'subsample': 0.22261392631470556, 'dropout_rate': 0.7752424129648651, 'n_estimators': 75, 'learning_rate': 0.08474323464506435}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.28578949235897605
Fold 2 IBS: 0.1768867956316924
Fold 3 IBS: 0.22037141231776833
Fold 4 IBS: 0.23360584586347086
Fold 5 IBS: 0.2277699377795826
[I 2024-04-15 16:43:23,295] Trial 18 finished with value: 0.22888469679029805 and parameters: {'subsample': 0.3616133093305952, 'dropout_rate': 0.9407064154310003, 'n_estimators': 139, 'learning_rate': 0.08628044919033}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.36571606883570673

Fold 2 IBS: 0.16248142823028444
Fold 3 IBS: 0.23157700988647345
Fold 4 IBS: 0.284982956349929
Fold 5 IBS: 0.29378159734341147
[I 2024-04-15 16:43:28,725] Trial 19 finished with value: 0.267707812129161 and parameters: {'subsample': 0.36536815139162093, 'dropout_rate': 0.9906028341543912, 'n_estimators': 341, 'learning_rate': 0.09290979487234556}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.24752088807102174
Fold 2 IBS: 0.2068435694297299
Fold 3 IBS: 0.21900644273712963
Fold 4 IBS: 0.22620957065689154
Fold 5 IBS: 0.21957258967822554
[I 2024-04-15 16:43:29,416] Trial 20 finished with value: 0.22383061211459965 and parameters: {'subsample': 0.18630970568769156, 'dropout_rate': 0.5777838682216713, 'n_estimators': 56, 'learning_rate': 0.07928709660452238}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2788012622923502
Fold 2 IBS: 0.1792818207436949
Fold 3 IBS: 0.20339051276781625
Fold 4 IBS: 0.21868518088381278
Fold 5 IBS: 0.21558058459652885
[I 2024-04-15 16:43:31,422] Trial 21 finished with value: 0.2191478722568406 and parameters: {'subsample': 0.11005861303267118, 'dropout_rate': 0.6006646820354332, 'n_estimators': 141, 'learning_rate': 0.09620867738924162}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.25928173764361817
Fold 2 IBS: 0.18751350000994588
Fold 3 IBS: 0.20665085592871177
Fold 4 IBS: 0.21330776192509543
Fold 5 IBS: 0.2127675652827081
[I 2024-04-15 16:43:32,844] Trial 22 finished with value: 0.21590428415801588 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.7504834423184644, 'n_estimators': 89, 'learning_rate': 0.09978990020253742}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.25048812108977536
Fold 2 IBS: 0.20245435936144768
Fold 3 IBS: 0.21634642877356053
Fold 4 IBS: 0.22346252717772924
Fold 5 IBS: 0.21818936954529616
[I 2024-04-15 16:43:33,685] Trial 23 finished with value: 0.2221881611895618 and parameters: {'subsample': 0.1850567218204376, 'dropout_rate': 0.7681659633439728, 'n_estimators': 66, 'learning_rate': 0.08296216960279851}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.327938060611646
Fold 2 IBS: 0.16518954936347977
Fold 3 IBS: 0.20544951952628132
Fold 4 IBS: 0.2604336544740784
Fold 5 IBS: 0.2562292936848665
[I 2024-04-15 16:43:37,871] Trial 24 finished with value: 0.2430480155320704 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.7586373059387486, 'n_estimators': 252, 'learning_rate': 0.09084272476660961}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2860548119802378
Fold 2 IBS: 0.17733478014793227
Fold 3 IBS: 0.19304674912202832
Fold 4 IBS: 0.22493951224064251
Fold 5 IBS: 0.21874402976375043
[I 2024-04-15 16:43:40,046] Trial 25 finished with value: 0.22002397665091827 and parameters: {'subsample': 0.165350832395609, 'dropout_rate': 0.8636269703319668, 'n_estimators': 147, 'learning_rate': 0.09940699200975617}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.253198043219016
Fold 2 IBS: 0.19963075200988833
Fold 3 IBS: 0.2164071649727226
Fold 4 IBS: 0.22623380996294326
Fold 5 IBS: 0.21957765191340053
[I 2024-04-15 16:43:41,368] Trial 26 finished with value: 0.22300948441559415 and parameters: {'subsample': 0.30246178993156847, 'dropout_rate': 0.5230683536894172, 'n_estimators': 91, 'learning_rate': 0.06492312198748737}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.24693109548807213
Fold 2 IBS: 0.23193091895668166
Fold 3 IBS: 0.2287068999789541
Fold 4 IBS: 0.24183346323691887
Fold 5 IBS: 0.22932696283978407
[I 2024-04-15 16:43:41,827] Trial 27 finished with value: 0.2357458681000822 and parameters: {'subsample': 0.41837107426637904, 'dropout_rate': 0.6340112818214192, 'n_estimators': 1, 'learning_rate': 0.07832939188793381}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.308867820410103
Fold 2 IBS: 0.17635721331324314
Fold 3 IBS: 0.18451369216979538
Fold 4 IBS: 0.2334649208372725
Fold 5 IBS: 0.22071803871214984
[I 2024-04-15 16:43:45,174] Trial 28 finished with value: 0.2247843370885128 and parameters: {'subsample': 0.1014788335359539, 'dropout_rate': 0.8128551255505723, 'n_estimators': 226, 'learning_rate': 0.0927042873351209}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.24479197532132663
Fold 2 IBS: 0.21901378720644785
Fold 3 IBS: 0.22270034882126938
Fold 4 IBS: 0.23250905014166248
Fold 5 IBS: 0.22367104935101376
[I 2024-04-15 16:43:45,762] Trial 29 finished with value: 0.22853724216834398 and parameters: {'subsample': 0.18366232237162633, 'dropout_rate': 0.7235485614758795, 'n_estimators': 37, 'learning_rate': 0.06046208382653473}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.27370634388171283
Fold 2 IBS: 0.17526327945815107
Fold 3 IBS: 0.22929744847409467
Fold 4 IBS: 0.2323293057443618
Fold 5 IBS: 0.226050844675939
[I 2024-04-15 16:43:47,153] Trial 30 finished with value: 0.22732944444685188 and parameters: {'subsample': 0.6252569440476443, 'dropout_rate': 0.6043319092880473, 'n_estimators': 121, 'learning_rate': 0.07689707236592859}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2706057744773959
Fold 2 IBS: 0.1841367899871727
Fold 3 IBS: 0.19915316020466045
Fold 4 IBS: 0.21894606514236606
Fold 5 IBS: 0.2150720236745999
[I 2024-04-15 16:43:48,642] Trial 31 finished with value: 0.217582762697239 and parameters: {'subsample': 0.14046720135620275, 'dropout_rate': 0.6645239025568339, 'n_estimators': 114, 'learning_rate': 0.09355583077597998}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.29307259759659626
Fold 2 IBS: 0.17070652899215805
Fold 3 IBS: 0.19782847325933173
Fold 4 IBS: 0.228157820293657
Fold 5 IBS: 0.22623130211218836
[I 2024-04-15 16:43:50,749] Trial 32 finished with value: 0.22319934445078632 and parameters: {'subsample': 0.2432594094791461, 'dropout_rate': 0.7328369697279866, 'n_estimators': 160, 'learning_rate': 0.09049447956353474}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.25708432381706736
Fold 2 IBS: 0.2070178036851445
Fold 3 IBS: 0.2085612233902919
Fold 4 IBS: 0.2234415451761625
Fold 5 IBS: 0.21748040886584125
[I 2024-04-15 16:43:52,541] Trial 33 finished with value: 0.2227170609869015 and parameters: {'subsample': 0.16499587533380747, 'dropout_rate': 0.48095898939081394, 'n_estimators': 89, 'learning_rate': 0.07050347652521735}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2758296278723121
Fold 2 IBS: 0.1784940457069144
Fold 3 IBS: 0.20930520876496034
Fold 4 IBS: 0.2290262096467195
Fold 5 IBS: 0.22147183651902475
[I 2024-04-15 16:43:54,136] Trial 34 finished with value: 0.22282538570198623 and parameters: {'subsample': 0.3104531754105267, 'dropout_rate': 0.818875178825874, 'n_estimators': 124, 'learning_rate': 0.08508506388175441}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.30438192047560747
Fold 2 IBS: 0.16720707513261246
Fold 3 IBS: 0.21112305051344948
Fold 4 IBS: 0.23429345371848542
Fold 5 IBS: 0.23380272690973636
[I 2024-04-15 16:43:56,832] Trial 35 finished with value: 0.23016164534997824 and parameters: {'subsample': 0.21854243907412046, 'dropout_rate': 0.431281292365383, 'n_estimators': 183, 'learning_rate': 0.09456342205253263}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.24541651090718788
Fold 2 IBS: 0.21645089411270785
Fold 3 IBS: 0.21349525757203472
Fold 4 IBS: 0.229002001523571
Fold 5 IBS: 0.2200588311807341
[I 2024-04-15 16:43:57,536] Trial 36 finished with value: 0.2248846990592471 and parameters: {'subsample': 0.1478952270746442, 'dropout_rate': 0.49750738148226387, 'n_estimators': 44, 'learning_rate': 0.08114706773013947}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2628416358318189
Fold 2 IBS: 0.1925992989610014
Fold 3 IBS: 0.21544937127637104
Fold 4 IBS: 0.22229156903769465
Fold 5 IBS: 0.22004062335062774
[I 2024-04-15 16:43:58,504] Trial 37 finished with value: 0.22264449969150274 and parameters: {'subsample': 0.28894459852396026, 'dropout_rate': 0.6224304218749513, 'n_estimators': 78, 'learning_rate': 0.09972883480731262}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2884647347411864

Fold 2 IBS: 0.16568635078205915
Fold 3 IBS: 0.24223275737531913
Fold 4 IBS: 0.24198856107842706
Fold 5 IBS: 0.23125525026287133
[I 2024-04-15 16:44:01,070] Trial 38 finished with value: 0.23392553084797263 and parameters: {'subsample': 0.8179022915704841, 'dropout_rate': 0.13272164755980653, 'n_estimators': 173, 'learning_rate': 0.07288612365177065}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.26884425511609517
Fold 2 IBS: 0.18085364921596053
Fold 3 IBS: 0.22859592533332296
Fold 4 IBS: 0.23048206101105526
Fold 5 IBS: 0.22253306981677642
[I 2024-04-15 16:44:03,768] Trial 39 finished with value: 0.22626179209864206 and parameters: {'subsample': 0.5876128987174842, 'dropout_rate': 0.6881141432789704, 'n_estimators': 202, 'learning_rate': 0.04072308299949521}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.25223248598618175
Fold 2 IBS: 0.1981682459164092
Fold 3 IBS: 0.22489322453006372
Fold 4 IBS: 0.22770122870313958
Fold 5 IBS: 0.22048695288589282
[I 2024-04-15 16:44:12,108] Trial 40 finished with value: 0.22469642760433742 and parameters: {'subsample': 0.41967291752982594, 'dropout_rate': 0.8868315563937723, 'n_estimators': 434, 'learning_rate': 0.012303020389202987}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.26309218734408024
Fold 2 IBS: 0.18444646275035254
Fold 3 IBS: 0.20447088814519113
Fold 4 IBS: 0.21182482718390022
Fold 5 IBS: 0.21307384387633324
[I 2024-04-15 16:44:13,520] Trial 41 finished with value: 0.2153816418599715 and parameters: {'subsample': 0.10480160106279328, 'dropout_rate': 0.6517059416030769, 'n_estimators': 103, 'learning_rate': 0.09538539487804591}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.2613306082752865
Fold 2 IBS: 0.18675744649222992
Fold 3 IBS: 0.19642286746784293
Fold 4 IBS: 0.21982754486991232
Fold 5 IBS: 0.21494534974115426
[I 2024-04-15 16:44:15,166] Trial 42 finished with value: 0.21585676336928517 and parameters: {'subsample': 0.15503357671213702, 'dropout_rate': 0.571795356852417, 'n_estimators': 110, 'learning_rate': 0.08881193980163264}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.27050378998486335
Fold 2 IBS: 0.18414419207610885
Fold 3 IBS: 0.19743435607447263
Fold 4 IBS: 0.2184347968037148
Fold 5 IBS: 0.21491515066355546
[I 2024-04-15 16:44:16,963] Trial 43 finished with value: 0.217086457120543 and parameters: {'subsample': 0.13661735606279404, 'dropout_rate': 0.5614281957092329, 'n_estimators': 121, 'learning_rate': 0.0882046384417017}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.24536689978901663
Fold 2 IBS: 0.213955487579207
Fold 3 IBS: 0.22289556033816316
Fold 4 IBS: 0.2262988999521249
Fold 5 IBS: 0.22140072944396416
[I 2024-04-15 16:44:17,680] Trial 44 finished with value: 0.22598351542049516 and parameters: {'subsample': 0.21479435326696206, 'dropout_rate': 0.56148947300117, 'n_estimators': 35, 'learning_rate': 0.08871386062188924}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.28889322031725456
Fold 2 IBS: 0.1890633667413267
Fold 3 IBS: 0.1893245370956
Fold 4 IBS: 0.21575894851549834
Fold 5 IBS: 0.21393680720185498
[I 2024-04-15 16:44:20,313] Trial 45 finished with value: 0.2193953759743069 and parameters: {'subsample': 0.12895658063997273, 'dropout_rate': 0.4191127385889543, 'n_estimators': 157, 'learning_rate': 0.08856312052602192}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.33325270419754194
Fold 2 IBS: 0.17059670287660395
Fold 3 IBS: 0.20015682215167094
Fold 4 IBS: 0.24765914206750708
Fold 5 IBS: 0.24462890722207603
[I 2024-04-15 16:44:25,115] Trial 46 finished with value: 0.23925885570308 and parameters: {'subsample': 0.2058952485028721, 'dropout_rate': 0.379737106689918, 'n_estimators': 281, 'learning_rate': 0.08280310656569682}. Best is trial 15 with value: 0.21526209245288125.
Fold 1 IBS: 0.25986333494437674
Fold 2 IBS: 0.18412124328793641
Fold 3 IBS: 0.19754297982848593
Fold 4 IBS: 0.21469036266486788
Fold 5 IBS: 0.21310642617715736
[I 2024-04-15 16:44:26,738] Trial 47 finished with value: 0.21386486938056484 and parameters: {'subsample': 0.10114780361455303, 'dropout_rate': 0.5510900629065184, 'n_estimators': 130, 'learning_rate': 0.07680726984979644}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.3187844546215169
Fold 2 IBS: 0.1897902208506012
Fold 3 IBS: 0.1835413210401853
Fold 4 IBS: 0.219764538856449
Fold 5 IBS: 0.2213576893049447
[I 2024-04-15 16:44:30,463] Trial 48 finished with value: 0.22664764493473938 and parameters: {'subsample': 0.1004172298398558, 'dropout_rate': 0.19701471782839963, 'n_estimators': 235, 'learning_rate': 0.07587811337664938}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2876647214087646
Fold 2 IBS: 0.1752896370240274
Fold 3 IBS: 0.20267411982327252
Fold 4 IBS: 0.22589914873987804
Fold 5 IBS: 0.22384199732541127
[I 2024-04-15 16:44:33,417] Trial 49 finished with value: 0.22307392486427075 and parameters: {'subsample': 0.2513474618305809, 'dropout_rate': 0.5194926134685146, 'n_estimators': 192, 'learning_rate': 0.06615495649623622}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.24447840481896677
Fold 2 IBS: 0.2218222253586399
Fold 3 IBS: 0.22444266543633393
Fold 4 IBS: 0.23470173606182032
Fold 5 IBS: 0.224332699900626
[I 2024-04-15 16:44:33,839] Trial 50 finished with value: 0.22995554631527737 and parameters: {'subsample': 0.15063826427560123, 'dropout_rate': 0.4567283594870261, 'n_estimators': 20, 'learning_rate': 0.09616414318774881}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2718634807958951
Fold 2 IBS: 0.18551598013169374
Fold 3 IBS: 0.19803789121907134
Fold 4 IBS: 0.21820285780371793
Fold 5 IBS: 0.2146625577129793
[I 2024-04-15 16:44:35,458] Trial 51 finished with value: 0.2176565535326715 and parameters: {'subsample': 0.14250840644913393, 'dropout_rate': 0.554122623255588, 'n_estimators': 130, 'learning_rate': 0.0874255885036978}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2662963442846178
Fold 2 IBS: 0.18338088870135555
Fold 3 IBS: 0.20798051597677789
Fold 4 IBS: 0.21880553221948681
Fold 5 IBS: 0.21629163269226853
[I 2024-04-15 16:44:36,749] Trial 52 finished with value: 0.21855098277490131 and parameters: {'subsample': 0.19979515560317362, 'dropout_rate': 0.7008366484905185, 'n_estimators': 109, 'learning_rate': 0.09172528817373055}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2539818168358363
Fold 2 IBS: 0.20638262795422255
Fold 3 IBS: 0.20377751038897007
Fold 4 IBS: 0.22530359437134556
Fold 5 IBS: 0.21730498165217646
[I 2024-04-15 16:44:37,828] Trial 53 finished with value: 0.22135010624051019 and parameters: {'subsample': 0.1396852588641998, 'dropout_rate': 0.3118867166286988, 'n_estimators': 72, 'learning_rate': 0.09531737870593446}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2604127873125711
Fold 2 IBS: 0.192698187384336
Fold 3 IBS: 0.21154758426635745
Fold 4 IBS: 0.2215973652112951
Fold 5 IBS: 0.21998886669292042
[I 2024-04-15 16:44:39,084] Trial 54 finished with value: 0.22124895817349605 and parameters: {'subsample': 0.2709470118511948, 'dropout_rate': 0.646368950650848, 'n_estimators': 97, 'learning_rate': 0.0816868796755705}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.24851516132233895
Fold 2 IBS: 0.20181550271323118
Fold 3 IBS: 0.2153346955134661
Fold 4 IBS: 0.21911152555790223
Fold 5 IBS: 0.21544658977165845
[I 2024-04-15 16:44:39,901] Trial 55 finished with value: 0.22004469497571938 and parameters: {'subsample': 0.1072818855403775, 'dropout_rate': 0.5880597078169252, 'n_estimators': 53, 'learning_rate': 0.09976815010736317}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2734161420600179
Fold 2 IBS: 0.17991546730455601
Fold 3 IBS: 0.21491679600029492
Fold 4 IBS: 0.2275292967071688
Fold 5 IBS: 0.22023008906905503
[I 2024-04-15 16:44:42,136] Trial 56 finished with value: 0.22320155822821852 and parameters: {'subsample': 0.3357335263727171, 'dropout_rate': 0.7925598471459256, 'n_estimators': 169, 'learning_rate': 0.056640513653763394}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.28290209997455784

Fold 2 IBS: 0.17919879330131924
Fold 3 IBS: 0.2050086120162017
Fold 4 IBS: 0.22428306549427526
Fold 5 IBS: 0.22102485528177307
[I 2024-04-15 16:44:43,938] Trial 57 finished with value: 0.22248348521362543 and parameters: {'subsample': 0.2338181818493688, 'dropout_rate': 0.739335033868409, 'n_estimators': 140, 'learning_rate': 0.08612518078950988}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.24532980269644922
Fold 2 IBS: 0.21348845040668132
Fold 3 IBS: 0.21698840746960918
Fold 4 IBS: 0.2290327004310601
Fold 5 IBS: 0.22136971692396645
[I 2024-04-15 16:44:44,825] Trial 58 finished with value: 0.22524181558555326 and parameters: {'subsample': 0.1753055549049239, 'dropout_rate': 0.5462080102365253, 'n_estimators': 79, 'learning_rate': 0.04319115334522856}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.26773329286909525
Fold 2 IBS: 0.18016692292798644
Fold 3 IBS: 0.234355334121409
Fold 4 IBS: 0.23081623904249735
Fold 5 IBS: 0.22403143533879394
[I 2024-04-15 16:44:46,006] Trial 59 finished with value: 0.22742064485995642 and parameters: {'subsample': 0.7488754310335448, 'dropout_rate': 0.8513558113018265, 'n_estimators': 114, 'learning_rate': 0.07245833370112886}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.25312032539683127
Fold 2 IBS: 0.2110696541770987
Fold 3 IBS: 0.20512870905453698
Fold 4 IBS: 0.22350794455471887
Fold 5 IBS: 0.21691944413326122
[I 2024-04-15 16:44:46,690] Trial 60 finished with value: 0.22194921546328938 and parameters: {'subsample': 0.12817824806408212, 'dropout_rate': 0.9429952825348574, 'n_estimators': 60, 'learning_rate': 0.09693202691956025}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2604555895774993
Fold 2 IBS: 0.18926313318791785
Fold 3 IBS: 0.1991959903638023
Fold 4 IBS: 0.2198072903970885
Fold 5 IBS: 0.21479852875686006
[I 2024-04-15 16:44:47,911] Trial 61 finished with value: 0.2167041064566336 and parameters: {'subsample': 0.1571044691051347, 'dropout_rate': 0.6612696929658357, 'n_estimators': 102, 'learning_rate': 0.09362422773671918}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.26123945891187456
Fold 2 IBS: 0.19129010418953923
Fold 3 IBS: 0.2042121907563902
Fold 4 IBS: 0.21841135373682033
Fold 5 IBS: 0.2153104654299584
[I 2024-04-15 16:44:48,988] Trial 62 finished with value: 0.21809271460491653 and parameters: {'subsample': 0.16526004073747577, 'dropout_rate': 0.6831927696805206, 'n_estimators': 98, 'learning_rate': 0.09062939442878018}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.29057118570036294
Fold 2 IBS: 0.17881412185906445
Fold 3 IBS: 0.19836638710004767
Fold 4 IBS: 0.2269644249576109
Fold 5 IBS: 0.2187178212578145
[I 2024-04-15 16:44:50,850] Trial 63 finished with value: 0.2226867881749801 and parameters: {'subsample': 0.19810551693770173, 'dropout_rate': 0.5875845995398626, 'n_estimators': 152, 'learning_rate': 0.09356058438163949}. Best is trial 47 with value: 0.21386486938056484.
Fold 1 IBS: 0.2614811304618058
Fold 2 IBS: 0.18298332944440135
Fold 3 IBS: 0.19672756574416403
Fold 4 IBS: 0.21457227351287447
Fold 5 IBS: 0.21309214636896145
[I 2024-04-15 16:44:52,378] Trial 64 finished with value: 0.21377128910644144 and parameters: {'subsample': 0.1018358506487617, 'dropout_rate': 0.6273608789636065, 'n_estimators': 130, 'learning_rate': 0.07987356089292716}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.24669394111734602
Fold 2 IBS: 0.2194516356959204
Fold 3 IBS: 0.22707051359918098
Fold 4 IBS: 0.23304506679352646
Fold 5 IBS: 0.2238727096720876
[I 2024-04-15 16:44:52,841] Trial 65 finished with value: 0.23002677337561228 and parameters: {'subsample': 0.11454736494875868, 'dropout_rate': 0.6212181785160468, 'n_estimators': 28, 'learning_rate': 0.08441417610665058}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2624293461350268
Fold 2 IBS: 0.18287243767056113
Fold 3 IBS: 0.19624752413205931
Fold 4 IBS: 0.21535214990866838
Fold 5 IBS: 0.21308503484999639
[I 2024-04-15 16:44:54,606] Trial 66 finished with value: 0.21399729853926241 and parameters: {'subsample': 0.10041734071097298, 'dropout_rate': 0.6573308369532493, 'n_estimators': 134, 'learning_rate': 0.07799999477443136}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.32609025290027027
Fold 2 IBS: 0.1770702998161267
Fold 3 IBS: 0.18182460365996175
Fold 4 IBS: 0.24678235722074948
Fold 5 IBS: 0.2278730129144236
[I 2024-04-15 16:45:00,291] Trial 67 finished with value: 0.23192810530230634 and parameters: {'subsample': 0.10274768880340551, 'dropout_rate': 0.7603395509601902, 'n_estimators': 321, 'learning_rate': 0.07928495152349067}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.27193441804655005
Fold 2 IBS: 0.18269080372151603
Fold 3 IBS: 0.20725637620742304
Fold 4 IBS: 0.22143122972157087
Fold 5 IBS: 0.21670238695591135
[I 2024-04-15 16:45:02,430] Trial 68 finished with value: 0.22000304293059422 and parameters: {'subsample': 0.18559555691379287, 'dropout_rate': 0.7152172926454878, 'n_estimators': 137, 'learning_rate': 0.0769350544245956}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.25644635273345534
Fold 2 IBS: 0.1904295705874662
Fold 3 IBS: 0.23145564883122888
Fold 4 IBS: 0.22879508114812777
Fold 5 IBS: 0.2219971028171558
[I 2024-04-15 16:45:03,745] Trial 69 finished with value: 0.22582475122348677 and parameters: {'subsample': 0.8584661298748817, 'dropout_rate': 0.5135673967031601, 'n_estimators': 88, 'learning_rate': 0.06802986770936134}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.3120545487177503
Fold 2 IBS: 0.16917790103915792
Fold 3 IBS: 0.20277863111389208
Fold 4 IBS: 0.23507891260972724
Fold 5 IBS: 0.23302030522951986
[I 2024-04-15 16:45:07,891] Trial 70 finished with value: 0.23042205974200947 and parameters: {'subsample': 0.23624636551788758, 'dropout_rate': 0.6437467311850233, 'n_estimators': 216, 'learning_rate': 0.08052635978158398}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.26507345687005135
Fold 2 IBS: 0.18728720786619432
Fold 3 IBS: 0.20105093079133668
Fold 4 IBS: 0.2187393824454762
Fold 5 IBS: 0.2155854470691561
[I 2024-04-15 16:45:09,377] Trial 71 finished with value: 0.21754728500844292 and parameters: {'subsample': 0.1641541332450986, 'dropout_rate': 0.6676911970114947, 'n_estimators': 105, 'learning_rate': 0.09537306743090214}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2749346683806907
Fold 2 IBS: 0.18801160060179564
Fold 3 IBS: 0.195103919739047
Fold 4 IBS: 0.22185326070326444
Fold 5 IBS: 0.21464109733324246
[I 2024-04-15 16:45:11,073] Trial 72 finished with value: 0.21890890935160803 and parameters: {'subsample': 0.13012762620005208, 'dropout_rate': 0.6077357490896412, 'n_estimators': 126, 'learning_rate': 0.09231537791691011}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2508043963051417
Fold 2 IBS: 0.19720210447756722
Fold 3 IBS: 0.21026467478019856
Fold 4 IBS: 0.21714193137021764
Fold 5 IBS: 0.2137051636846443
[I 2024-04-15 16:45:11,960] Trial 73 finished with value: 0.21782365412355387 and parameters: {'subsample': 0.10318166669829494, 'dropout_rate': 0.7979404651705745, 'n_estimators': 66, 'learning_rate': 0.09764603151967015}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.3276146894287148
Fold 2 IBS: 0.1742158548848541
Fold 3 IBS: 0.1931462373608733
Fold 4 IBS: 0.245451324481155
Fold 5 IBS: 0.2417092113888488
[I 2024-04-15 16:45:19,340] Trial 74 finished with value: 0.2364274635088892 and parameters: {'subsample': 0.16459288973973532, 'dropout_rate': 0.7431736251636212, 'n_estimators': 386, 'learning_rate': 0.06140947285195686}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.29042972537659967
Fold 2 IBS: 0.16635098440471527
Fold 3 IBS: 0.23913775632816794
Fold 4 IBS: 0.24130750978349114
Fold 5 IBS: 0.23379326889670268
[I 2024-04-15 16:45:21,482] Trial 75 finished with value: 0.2342038489579353 and parameters: {'subsample': 0.6882223870109341, 'dropout_rate': 0.7026146254659053, 'n_estimators': 164, 'learning_rate': 0.0753385642062396}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2661793747266373
Fold 2 IBS: 0.18320198893527134

Fold 3 IBS: 0.2223499924704868
Fold 4 IBS: 0.22918954012063755
Fold 5 IBS: 0.22213633441222166
[I 2024-04-15 16:45:22,479] Trial 76 finished with value: 0.22461144613305092 and parameters: {'subsample': 0.5082505552286973, 'dropout_rate': 0.6607618331895327, 'n_estimators': 86, 'learning_rate': 0.0903014808523554}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.25740504494540467
Fold 2 IBS: 0.19342129698931473
Fold 3 IBS: 0.21098496634161182
Fold 4 IBS: 0.22225634861586105
Fold 5 IBS: 0.22035227228676424
[I 2024-04-15 16:45:23,783] Trial 77 finished with value: 0.2208839858357913 and parameters: {'subsample': 0.27488589720840634, 'dropout_rate': 0.8406275531062745, 'n_estimators': 107, 'learning_rate': 0.07058122348214978}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.277002774105818
Fold 2 IBS: 0.18852706892829543
Fold 3 IBS: 0.194491072102534
Fold 4 IBS: 0.22239803029622562
Fold 5 IBS: 0.2139914009023427
[I 2024-04-15 16:45:25,852] Trial 78 finished with value: 0.21928206926704313 and parameters: {'subsample': 0.12847352803007375, 'dropout_rate': 0.6372878048920665, 'n_estimators': 149, 'learning_rate': 0.08486992241026425}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.3116907143167974
Fold 2 IBS: 0.17039083955493836
Fold 3 IBS: 0.1946467950909797
Fold 4 IBS: 0.23188417381244886
Fold 5 IBS: 0.22639936716507097
[I 2024-04-15 16:45:28,475] Trial 79 finished with value: 0.22700237798804707 and parameters: {'subsample': 0.20487878232066137, 'dropout_rate': 0.5805913567816469, 'n_estimators': 188, 'learning_rate': 0.09782359970295712}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.24770940835176983
Fold 2 IBS: 0.20536217143345015
Fold 3 IBS: 0.21219688241626994
Fold 4 IBS: 0.22552781381912695
Fold 5 IBS: 0.21787604688575715
[I 2024-04-15 16:45:29,156] Trial 80 finished with value: 0.22173446458127483 and parameters: {'subsample': 0.1553696617740383, 'dropout_rate': 0.7767244154648001, 'n_estimators': 54, 'learning_rate': 0.09373787329421118}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2725442166570023
Fold 2 IBS: 0.18962136584121403
Fold 3 IBS: 0.19639637552206538
Fold 4 IBS: 0.22065442171282523
Fold 5 IBS: 0.21447354089809598
[I 2024-04-15 16:45:30,808] Trial 81 finished with value: 0.2187379841262406 and parameters: {'subsample': 0.13179674886753154, 'dropout_rate': 0.526254762713732, 'n_estimators': 127, 'learning_rate': 0.08800201183412654}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.27272902249842873
Fold 2 IBS: 0.18184163212233334
Fold 3 IBS: 0.2083884280439702
Fold 4 IBS: 0.22198061845312178
Fold 5 IBS: 0.21647583134269352
[I 2024-04-15 16:45:32,709] Trial 82 finished with value: 0.2202831064921095 and parameters: {'subsample': 0.1805282383395969, 'dropout_rate': 0.5727940422065299, 'n_estimators': 120, 'learning_rate': 0.08966972398800833}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.27576909040184994
Fold 2 IBS: 0.18964238686133944
Fold 3 IBS: 0.19379052150889423
Fold 4 IBS: 0.21740486732137806
Fold 5 IBS: 0.2146423020495417
[I 2024-04-15 16:45:34,772] Trial 83 finished with value: 0.21824983362860068 and parameters: {'subsample': 0.14847490105859593, 'dropout_rate': 0.4910744878475883, 'n_estimators': 139, 'learning_rate': 0.08277543113917435}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.25325792345563414
Fold 2 IBS: 0.2073841928659444
Fold 3 IBS: 0.2065247461017622
Fold 4 IBS: 0.2223938339769281
Fold 5 IBS: 0.2172548144444513
[I 2024-04-15 16:45:36,071] Trial 84 finished with value: 0.22136310216894403 and parameters: {'subsample': 0.12788036457612426, 'dropout_rate': 0.45923804117518247, 'n_estimators': 78, 'learning_rate': 0.07825876837762108}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.28117090969124875
Fold 2 IBS: 0.17953199233842257
Fold 3 IBS: 0.18576038904445905
Fold 4 IBS: 0.22291459399248323
Fold 5 IBS: 0.21364216843321426
[I 2024-04-15 16:45:38,779] Trial 85 finished with value: 0.2166040106999656 and parameters: {'subsample': 0.10232567180327527, 'dropout_rate': 0.606812141388168, 'n_estimators': 174, 'learning_rate': 0.08651884090978393}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.3103826129950483
Fold 2 IBS: 0.17454532904897496
Fold 3 IBS: 0.20373417690166284
Fold 4 IBS: 0.23782786048585844
Fold 5 IBS: 0.23203103630259062
[I 2024-04-15 16:45:41,509] Trial 86 finished with value: 0.23170420314682705 and parameters: {'subsample': 0.21828167837840337, 'dropout_rate': 0.6115941410557637, 'n_estimators': 177, 'learning_rate': 0.0997657520794785}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.24488871242144586
Fold 2 IBS: 0.21067218051236392
Fold 3 IBS: 0.21799068089832443
Fold 4 IBS: 0.22619221935015038
Fold 5 IBS: 0.2200691382335462
[I 2024-04-15 16:45:42,798] Trial 87 finished with value: 0.22396258628316615 and parameters: {'subsample': 0.1008558471436472, 'dropout_rate': 0.6812262002370577, 'n_estimators': 102, 'learning_rate': 0.03538673247962338}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.24948349276521897
Fold 2 IBS: 0.20596405727298178
Fold 3 IBS: 0.2141843970543099
Fold 4 IBS: 0.2247776367662097
Fold 5 IBS: 0.21941617129130997
[I 2024-04-15 16:45:45,684] Trial 88 finished with value: 0.22276515103000608 and parameters: {'subsample': 0.18681979365726456, 'dropout_rate': 0.6425792350869551, 'n_estimators': 200, 'learning_rate': 0.024099543252977373}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.28519473958792696
Fold 2 IBS: 0.16778449691903535
Fold 3 IBS: 0.24151375744270726
Fold 4 IBS: 0.23888775831548079
Fold 5 IBS: 0.22966371094390906
[I 2024-04-15 16:45:47,537] Trial 89 finished with value: 0.2326088926418119 and parameters: {'subsample': 0.9981197080532995, 'dropout_rate': 0.5362474933775084, 'n_estimators': 132, 'learning_rate': 0.08527332924448187}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.27991018923665345
Fold 2 IBS: 0.1841140484260564
Fold 3 IBS: 0.2030537912524251
Fold 4 IBS: 0.22121120628189186
Fold 5 IBS: 0.21344877546927227
[I 2024-04-15 16:45:49,458] Trial 90 finished with value: 0.22034760213325982 and parameters: {'subsample': 0.11983733601042068, 'dropout_rate': 0.7211266599729008, 'n_estimators': 149, 'learning_rate': 0.09198438616787277}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.270748422277377
Fold 2 IBS: 0.1848222966832823
Fold 3 IBS: 0.19477340115895964
Fold 4 IBS: 0.2206550372477377
Fold 5 IBS: 0.21524037767309245
[I 2024-04-15 16:45:51,012] Trial 91 finished with value: 0.21724790700808985 and parameters: {'subsample': 0.1520250160636756, 'dropout_rate': 0.561714784946168, 'n_estimators': 120, 'learning_rate': 0.08755233712077223}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.27126099122887737
Fold 2 IBS: 0.1837269036030211
Fold 3 IBS: 0.1988924166625221
Fold 4 IBS: 0.2190207216003715
Fold 5 IBS: 0.21489559732614147
[I 2024-04-15 16:45:52,736] Trial 92 finished with value: 0.21755932608418674 and parameters: {'subsample': 0.14086699629456115, 'dropout_rate': 0.5897752947503649, 'n_estimators': 114, 'learning_rate': 0.09486148749030689}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2604632664843399
Fold 2 IBS: 0.19087958272712324
Fold 3 IBS: 0.2165404953011349
Fold 4 IBS: 0.2170688719514933
Fold 5 IBS: 0.2142509157067325
[I 2024-04-15 16:45:54,043] Trial 93 finished with value: 0.21984062643416474 and parameters: {'subsample': 0.12096838859453274, 'dropout_rate': 0.5029683581703119, 'n_estimators': 89, 'learning_rate': 0.09771058570452545}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2808154253433974
Fold 2 IBS: 0.17866735740368186
Fold 3 IBS: 0.19280989299603923
Fold 4 IBS: 0.22305525701134515
Fold 5 IBS: 0.21702811672295713
[I 2024-04-15 16:45:56,351] Trial 94 finished with value: 0.21847520989548413 and parameters: {'subsample': 0.16794947479238442, 'dropout_rate': 0.6155270613300127, 'n_estimators': 162, 'learning_rate': 0.08273429057419085}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2553637078900231
Fold 2 IBS: 0.19307038172793087

Fold 3 IBS: 0.21986105610033166
Fold 4 IBS: 0.2276997235984686
Fold 5 IBS: 0.22160135268525796
[I 2024-04-15 16:45:57,225] Trial 95 finished with value: 0.22351924440040244 and parameters: {'subsample': 0.42816774104053495, 'dropout_rate': 0.6592977171583894, 'n_estimators': 66, 'learning_rate': 0.08693594801790488}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2584339011242822
Fold 2 IBS: 0.18911990790146938
Fold 3 IBS: 0.2077096426176724
Fold 4 IBS: 0.21360194311540062
Fold 5 IBS: 0.2132732733635253
[I 2024-04-15 16:45:58,486] Trial 96 finished with value: 0.21642773362447 and parameters: {'subsample': 0.1011542092953201, 'dropout_rate': 0.5430817802699582, 'n_estimators': 95, 'learning_rate': 0.08940359717281336}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.24834494946011265
Fold 2 IBS: 0.20875197279971033
Fold 3 IBS: 0.22691667170598823
Fold 4 IBS: 0.22507367471955336
Fold 5 IBS: 0.2199783342066774
[I 2024-04-15 16:45:59,146] Trial 97 finished with value: 0.2258131205784084 and parameters: {'subsample': 0.11690685554552094, 'dropout_rate': 0.6962633812737409, 'n_estimators': 46, 'learning_rate': 0.09061228486326302}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.25263078972502423
Fold 2 IBS: 0.20452608002390926
Fold 3 IBS: 0.21350786470227262
Fold 4 IBS: 0.22311693369961505
Fold 5 IBS: 0.21768894146516835
[I 2024-04-15 16:46:00,123] Trial 98 finished with value: 0.2222941219231979 and parameters: {'subsample': 0.19047030862637412, 'dropout_rate': 0.7465754561100503, 'n_estimators': 72, 'learning_rate': 0.08062035216684603}. Best is trial 64 with value: 0.21377128910644144.
Fold 1 IBS: 0.2466258799556372
Fold 2 IBS: 0.20703017585385372
Fold 3 IBS: 0.21376522588572128
Fold 4 IBS: 0.22455623658096685
Fold 5 IBS: 0.21819155537026333
[I 2024-04-15 16:46:01,303] Trial 99 finished with value: 0.2220338147292885 and parameters: {'subsample': 0.10121177911308754, 'dropout_rate': 0.47278156825542, 'n_estimators': 97, 'learning_rate': 0.052443959168945425}. Best is trial 64 with value: 0.21377128910644144.


* Best trial for IBS:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.21377128910644144], datetime_start=datetime.datetime(2024, 4, 15, 16, 44, 50, 858183), datetime_complete=datetime.datetime(2024, 4, 15, 16, 44, 52, 378274), params={'subsample': 0.1018358506487617, 'dropout_rate': 0.6273608789636065, 'n_estimators': 130, 'learning_rate': 0.07987356089292716}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=64, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.1018358506487617, 'dropout_rate': 0.6273608789636065, 'n_estimators': 130, 'learning_rate': 0.07987356089292716}


* Best Score for IBS:
 0.21377128910644144

In [142]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [143]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.684
train_ibs:  0.214

#### Test

In [144]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [145]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.4136725222049048,
                                              learning_rate=0.07578621907115225,
                                              n_estimators=46, random_state=123,
                                              subsample=0.14488143846919227)

C-index score: 0.539

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6273608789636065,
                                              learning_rate=0.07987356089292716,
                                              n_estimators=130,
                                              random_state=123,
                                              subsample=0.1018358506487617)

IBS: 0.24

In [146]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [147]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.830   1.0
ExtraSurvivalTrees               0.764   2.0
GradientBoosting                 0.713   3.0
CoxElastic                       0.693   4.0
CoxLasso                         0.691   5.0
CoxPH                            0.689   6.0
ComponentwiseGradientBoosting    0.684   7.0
CoxRidge                         0.648   8.0

In [148]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.202   1.0
CoxElastic                     0.206   2.0
CoxPH                          0.207   4.0
CoxLasso                       0.207   4.0
ExtraSurvivalTrees             0.207   4.0
ComponentwiseGradientBoosting  0.214   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [149]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.544   1.0
ExtraSurvivalTrees               0.543   2.0
ComponentwiseGradientBoosting    0.539   3.0
CoxPH                            0.532   6.0
CoxRidge                         0.532   6.0
CoxLasso                         0.532   6.0
CoxElastic                       0.532   6.0
GradientBoosting                 0.532   6.0

In [150]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ComponentwiseGradientBoosting  0.240   3.0
Randomsurvivalforest           0.247   4.0
ExtraSurvivalTrees             0.256   5.0
CoxLasso                       0.288   6.5
CoxElastic                     0.288   6.5
CoxPH                          0.290   8.0

In [153]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/minmax/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_minmax_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [154]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-15