In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.08
LBP_003_PET                                                      0.00 0.99      0.01
LBP_012_CT                                                       0.01 0.91      0.13
LBP_012_PET                                                      0.00 0.98      0.03
LBP_021_CT                                                       0.01 0.94      0.09
LBP_021_PET                                                      0.02 0.90      0.16
LBP_030_CT                                                       0.00 0.97      0.04
LBP_030_PET                                                      0.00 0.99      0.01
LBP_102_CT                                                       0.00 0.96      0.07
LBP_102_PET                                                      0.02 0.88      0.19
LBP_111_CT                                                       0.01 0.93      0.10
LBP_111_PET                                                      0.07 0.79      0.33
LBP_120_CT                                                       0.01 0.91      0.14
LBP_120_PET                                                      0.00 0.96      0.07
LBP_201_CT                                                       0.00 0.97      0.04
LBP_201_PET                                                      0.00 0.95      0.08
LBP_210_CT                                                       0.00 1.00      0.00
LBP_210_PET                                                      0.00 0.96      0.06
LBP_300_CT                                                       0.00 0.98      0.03
LBP_300_PET                                                      0.01 0.94      0.09
first_order_10Percentile_CT                                      0.01 0.94      0.09
first_order_10Percentile_PET                                     0.00 1.00      0.01
first_order_90Percentile_CT                                      0.00 0.98      0.03
first_order_90Percentile_PET                                     0.00 0.99      0.01
first_order_Energy_CT                                            0.00 1.00      0.00
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 0.98      0.03
first_order_Entropy_CT_c16                                       0.00 0.98      0.03
first_order_Entropy_PET_b2                                       0.00 0.99      0.01
first_order_Entropy_PET_c04                                      0.00 0.96      0.06
first_order_InterquartileRange_CT                                0.00 0.94      0.08
first_order_InterquartileRange_PET                               0.00 1.00      0.00
first_order_Kurtosis_CT                                          0.00 0.99      0.02
first_order_Kurtosis_PET                                         0.01 0.93      0.10
first_order_Maximum_CT                                           0.01 0.93      0.11
first_order_Maximum_PET                                          0.00 1.00      0.01
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.01
first_order_MeanAbsoluteDeviation_PET                            0.00 1.00      0.00
first_order_Mean_CT                                              0.00 0.99      0.01
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 1.00      0.01
first_order_Median_PET                                           0.00 1.00      0.00
first_order_Minimum_CT                                           0.00 0.98      0.03
first_order_Minimum_PET                                          0.02 0.89      0.17
first_order_Range_CT                                             0.00 0.96      0.06
first_order_Range_PET                                            0.00 0.99      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.95      0.08
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 0.99      0.02
first_order_RootMeanSquared_CT                                   0.00 0.99      0.01
first_order_RootMeanSquared_PET                                  0.00 1.00      0.00
first_order_Skewness_CT                                          0.05 0.83      0.27
first_order_Skewness_PET                                         0.00 0.95      0.07
first_order_TotalEnergy_CT                                       0.00 1.00      0.00
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.95      0.07
first_order_Uniformity_CT_c16                                    0.00 0.98      0.03
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 0.99      0.02
first_order_Variance_CT                                          0.00 0.99      0.02
first_order_Variance_PET                                         0.00 0.99      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.98      0.02
glcm_ClusterProminence_d_1_CT_b20                                0.00 0.98      0.02
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.95      0.07
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.98      0.03
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.95      0.07
glcm_ClusterShade_d_1_CT_c16                                     0.01 0.93      0.10
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.95      0.08
glcm_ClusterShade_d_1_PET_c04                                    0.01 0.94      0.10
glcm_ClusterTendency_d_1_CT_b20                                  0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.98      0.03
glcm_ClusterTendency_d_1_PET_b2                                  0.00 1.00      0.00
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.98      0.03
glcm_Contrast_d_1_CT_b20                                         0.00 0.97      0.04
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 0.99      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.96      0.06
glcm_Correlation_d_1_CT_c16                                      0.01 0.92      0.13
glcm_Correlation_d_1_PET_b2                                      0.00 0.99      0.02
glcm_Correlation_d_1_PET_c04                                     0.00 0.95      0.07
glcm_DifferenceAverage_d_1_CT_b20                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.98      0.03
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.99      0.02
glcm_Id_d_1_CT_b20                                               0.00 1.00      0.00
glcm_Id_d_1_CT_c16                                               0.00 0.98      0.02
glcm_Id_d_1_PET_b2                                               0.00 0.99      0.02
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_c16                                              0.00 0.98      0.03
glcm_Idm_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Idmn_d_1_CT_c16                                             0.00 0.98      0.03
glcm_Idmn_d_1_PET_b2                                             0.00 0.96      0.05
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idn_d_1_CT_c16                                              0.00 0.98      0.03
glcm_Idn_d_1_PET_b2                                              0.00 0.98      0.03
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_b20                                             0.01 0.93      0.10
glcm_Imc1_d_1_CT_c16                                             0.00 1.00      0.01
glcm_Imc1_d_1_PET_b2                                             0.00 0.95      0.08
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Imc2_d_1_CT_b20                                             0.01 0.92      0.12
glcm_Imc2_d_1_CT_c16                                             0.01 0.94      0.10
glcm_Imc2_d_1_PET_b2                                             0.00 0.98      0.03
glcm_Imc2_d_1_PET_c04                                            0.00 0.97      0.04
glcm_InverseVariance_d_1_CT_b20                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_PET_b2                                  0.00 0.97      0.04
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.00
glcm_JointAverage_d_1_CT_b20                                     0.00 0.98      0.03
glcm_JointAverage_d_1_CT_c16                                     0.00 1.00      0.00
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 0.99      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.99      0.02
glcm_JointEnergy_d_1_CT_c16                                      0.00 0.99      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.00 0.99      0.01
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_CT_b20                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.98      0.03
glcm_MCC_d_1_CT_b20                                              0.02 0.89      0.16
glcm_MCC_d_1_CT_c16                                              0.00 0.96      0.06
glcm_MCC_d_1_PET_b2                                              0.00 0.97      0.05
glcm_MCC_d_1_PET_c04                                             0.00 0.97      0.05
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.97      0.05
glcm_MaximumProbability_d_1_CT_c16                               0.00 0.98      0.03
glcm_MaximumProbability_d_1_PET_b2                               0.01 0.91      0.14
glcm_MaximumProbability_d_1_PET_c04                              0.01 0.92      0.12
glcm_SumAverage_d_1_CT_b20                                       0.00 0.98      0.03
glcm_SumAverage_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.99      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.97      0.05
glcm_SumSquares_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumSquares_d_1_CT_c16                                       0.00 0.98      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumSquares_d_1_PET_c04                                      0.00 0.98      0.03
gldm_DependenceEntropy_d_1_CT_b20                                0.01 0.94      0.09
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.98      0.02
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.98      0.04
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.00
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.98      0.02
gldm_DependenceVariance_d_1_CT_c16                               0.00 0.96      0.06
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.97      0.05
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.95      0.07
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.97      0.04
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.95      0.08
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.99      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.03
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.96      0.05
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.01 0.94      0.09
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.96      0.06
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.98      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.97      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.01 0.94      0.09
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.95      0.08
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.96      0.06
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.96      0.05
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.01 0.92      0.13
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.02 0.90      0.15
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.02 0.89      0.17
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.97      0.04
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.96      0.06
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.95      0.07
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.98      0.04
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.99      0.01
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.97      0.04
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.01
glrlm_GrayLevelVariance_PET_c04                                  0.00 0.97      0.05
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.00 1.00      0.00
glrlm_HighGrayLevelRunEmphasis_CT_c16                            0.00 1.00      0.01
glrlm_HighGrayLevelRunEmphasis_PET_b2                            0.00 0.99      0.02
glrlm_HighGrayLevelRunEmphasis_PET_c04                           0.00 0.96      0.06
glrlm_LongRunEmphasis_CT_b20                                     0.00 1.00      0.00
glrlm_LongRunEmphasis_CT_c16                                     0.00 0.96      0.06

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic      p  -log2(p)
LBP_003_CT                                                       0.20   0.65      0.62
LBP_003_PET                                                      0.43   0.51      0.96
LBP_012_CT                                                       0.19   0.66      0.59
LBP_012_PET                                                      0.18   0.67      0.57
LBP_021_CT                                                       0.94   0.33      1.59
LBP_021_PET                                                      0.01   0.93      0.10
LBP_030_CT                                                       0.00   0.94      0.08
LBP_030_PET                                                      0.03   0.86      0.21
LBP_102_CT                                                       0.05   0.83      0.27
LBP_102_PET                                                      0.09   0.77      0.38
LBP_111_CT                                                       0.14   0.71      0.49
LBP_111_PET                                                      0.38   0.54      0.89
LBP_120_CT                                                       0.27   0.61      0.72
LBP_120_PET                                                      0.09   0.76      0.40
LBP_201_CT                                                       0.30   0.58      0.78
LBP_201_PET                                                      0.58   0.45      1.16
LBP_210_CT                                                       0.69   0.41      1.30
LBP_210_PET                                                      0.00   0.97      0.04
LBP_300_CT                                                       0.20   0.66      0.60
LBP_300_PET                                                      0.00   0.94      0.08
first_order_10Percentile_CT                                      0.00   0.95      0.08
first_order_10Percentile_PET                                     0.08   0.77      0.37
first_order_90Percentile_CT                                      2.85   0.09      3.46
first_order_90Percentile_PET                                     0.00   0.95      0.07
first_order_Energy_CT                                            0.01   0.93      0.11
first_order_Energy_PET                                           0.08   0.77      0.37
first_order_Entropy_CT_b20                                       0.00   0.99      0.01
first_order_Entropy_CT_c16                                       0.08   0.78      0.37
first_order_Entropy_PET_b2                                       0.00   0.99      0.01
first_order_Entropy_PET_c04                                      0.01   0.93      0.11
first_order_InterquartileRange_CT                                0.79   0.37      1.42
first_order_InterquartileRange_PET                               0.00   0.97      0.04
first_order_Kurtosis_CT                                          0.30   0.58      0.77
first_order_Kurtosis_PET                                         0.04   0.84      0.26
first_order_Maximum_CT                                           0.13   0.72      0.48
first_order_Maximum_PET                                          0.00   0.95      0.08
first_order_MeanAbsoluteDeviation_CT                             0.06   0.81      0.30
first_order_MeanAbsoluteDeviation_PET                            0.00   0.95      0.07
first_order_Mean_CT                                              0.01   0.93      0.10
first_order_Mean_PET                                             0.01   0.94      0.09
first_order_Median_CT                                            0.19   0.66      0.59
first_order_Median_PET                                           0.01   0.92      0.12
first_order_Minimum_CT                                           0.06   0.81      0.31
first_order_Minimum_PET                                          0.64   0.42      1.24
first_order_Range_CT                                             0.16   0.69      0.55
first_order_Range_PET                                            0.00   0.98      0.03
first_order_RobustMeanAbsoluteDeviation_CT                       0.11   0.74      0.43
first_order_RobustMeanAbsoluteDeviation_PET                      0.00   0.96      0.07
first_order_RootMeanSquared_CT                                   0.02   0.89      0.17
first_order_RootMeanSquared_PET                                  0.00   0.97      0.05
first_order_Skewness_CT                                          0.10   0.76      0.40
first_order_Skewness_PET                                         0.00   0.95      0.08
first_order_TotalEnergy_CT                                       0.01   0.93      0.11
first_order_TotalEnergy_PET                                      0.08   0.77      0.37
first_order_Uniformity_CT_b20                                    0.01   0.93      0.10
first_order_Uniformity_CT_c16                                    0.03   0.85      0.23
first_order_Uniformity_PET_b2                                    0.13   0.72      0.47
first_order_Uniformity_PET_c04                                   0.07   0.79      0.34
first_order_Variance_CT                                          0.01   0.94      0.09
first_order_Variance_PET                                         0.00   0.96      0.06
glcm_Autocorrelation_d_1_CT_b20                                  0.13   0.72      0.48
glcm_Autocorrelation_d_1_CT_c16                                  0.00   0.99      0.02
glcm_Autocorrelation_d_1_PET_b2                                  0.03   0.86      0.22
glcm_Autocorrelation_d_1_PET_c04                                 0.01   0.93      0.10
glcm_ClusterProminence_d_1_CT_b20                                0.03   0.86      0.22
glcm_ClusterProminence_d_1_CT_c16                                0.00   0.98      0.02
glcm_ClusterProminence_d_1_PET_b2                                0.15   0.69      0.53
glcm_ClusterProminence_d_1_PET_c04                               0.21   0.65      0.62
glcm_ClusterShade_d_1_CT_b20                                     1.58   0.21      2.26
glcm_ClusterShade_d_1_CT_c16                                     0.00   0.96      0.06
glcm_ClusterShade_d_1_PET_b2                                     0.35   0.55      0.85
glcm_ClusterShade_d_1_PET_c04                                    0.17   0.68      0.55
glcm_ClusterTendency_d_1_CT_b20                                  0.01   0.93      0.10
glcm_ClusterTendency_d_1_CT_c16                                  0.03   0.86      0.21
glcm_ClusterTendency_d_1_PET_b2                                  0.01   0.94      0.09
glcm_ClusterTendency_d_1_PET_c04                                 0.09   0.76      0.39
glcm_Contrast_d_1_CT_b20                                         0.02   0.89      0.17
glcm_Contrast_d_1_CT_c16                                         0.03   0.86      0.22
glcm_Contrast_d_1_PET_b2                                         0.01   0.92      0.13
glcm_Contrast_d_1_PET_c04                                        0.01   0.93      0.10
glcm_Correlation_d_1_CT_b20                                      0.61   0.43      1.20
glcm_Correlation_d_1_CT_c16                                      0.67   0.41      1.27
glcm_Correlation_d_1_PET_b2                                      0.03   0.85      0.23
glcm_Correlation_d_1_PET_c04                                     0.00   0.96      0.06
glcm_DifferenceAverage_d_1_CT_b20                                0.00   0.99      0.01
glcm_DifferenceAverage_d_1_CT_c16                                0.00   0.98      0.04
glcm_DifferenceAverage_d_1_PET_b2                                0.00   0.96      0.07
glcm_DifferenceAverage_d_1_PET_c04                               0.00   0.96      0.06
glcm_DifferenceEntropy_d_1_CT_b20                                0.00   0.96      0.06
glcm_DifferenceEntropy_d_1_CT_c16                                0.01   0.93      0.11
glcm_DifferenceEntropy_d_1_PET_b2                                0.03   0.85      0.23
glcm_DifferenceEntropy_d_1_PET_c04                               0.18   0.67      0.57
glcm_DifferenceVariance_d_1_CT_b20                               0.04   0.84      0.25
glcm_DifferenceVariance_d_1_CT_c16                               0.05   0.82      0.29
glcm_DifferenceVariance_d_1_PET_b2                               0.08   0.78      0.35
glcm_DifferenceVariance_d_1_PET_c04                              0.12   0.73      0.45
glcm_Id_d_1_CT_b20                                               0.00   0.95      0.07
glcm_Id_d_1_CT_c16                                               0.00   0.98      0.03
glcm_Id_d_1_PET_b2                                               0.02   0.90      0.15
glcm_Id_d_1_PET_c04                                              0.01   0.90      0.15
glcm_Idm_d_1_CT_b20                                              0.00   0.95      0.07
glcm_Idm_d_1_CT_c16                                              0.00   0.99      0.01
glcm_Idm_d_1_PET_b2                                              0.01   0.92      0.12
glcm_Idm_d_1_PET_c04                                             0.01   0.92      0.11
glcm_Idmn_d_1_CT_b20                                             0.03   0.87      0.20
glcm_Idmn_d_1_CT_c16                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_b2                                             0.08   0.78      0.35
glcm_Idmn_d_1_PET_c04                                            0.01   0.94      0.09
glcm_Idn_d_1_CT_b20                                              0.02   0.89      0.16
glcm_Idn_d_1_CT_c16                                              0.00   0.99      0.01
glcm_Idn_d_1_PET_b2                                              0.17   0.68      0.56
glcm_Idn_d_1_PET_c04                                             0.01   0.94      0.09
glcm_Imc1_d_1_CT_b20                                             0.87   0.35      1.51
glcm_Imc1_d_1_CT_c16                                             0.02   0.88      0.18
glcm_Imc1_d_1_PET_b2                                             0.06   0.80      0.32
glcm_Imc1_d_1_PET_c04                                            0.08   0.78      0.36
glcm_Imc2_d_1_CT_b20                                             0.06   0.81      0.30
glcm_Imc2_d_1_CT_c16                                             0.60   0.44      1.19
glcm_Imc2_d_1_PET_b2                                             0.09   0.76      0.39
glcm_Imc2_d_1_PET_c04                                            0.02   0.88      0.19
glcm_InverseVariance_d_1_CT_b20                                  0.13   0.72      0.47
glcm_InverseVariance_d_1_CT_c16                                  0.05   0.83      0.27
glcm_InverseVariance_d_1_PET_b2                                  0.07   0.80      0.33
glcm_InverseVariance_d_1_PET_c04                                 0.07   0.79      0.34
glcm_JointAverage_d_1_CT_b20                                     0.08   0.78      0.36
glcm_JointAverage_d_1_CT_c16                                     0.02   0.89      0.16
glcm_JointAverage_d_1_PET_b2                                     0.01   0.90      0.15
glcm_JointAverage_d_1_PET_c04                                    0.00   0.95      0.08
glcm_JointEnergy_d_1_CT_b20                                      0.03   0.87      0.20
glcm_JointEnergy_d_1_CT_c16                                      0.03   0.87      0.21
glcm_JointEnergy_d_1_PET_b2                                      0.18   0.67      0.57
glcm_JointEnergy_d_1_PET_c04                                     0.01   0.92      0.12
glcm_JointEntropy_d_1_CT_b20                                     0.00   0.95      0.07
glcm_JointEntropy_d_1_CT_c16                                     0.07   0.78      0.35
glcm_JointEntropy_d_1_PET_b2                                     0.00   0.98      0.02
glcm_JointEntropy_d_1_PET_c04                                    0.00   0.97      0.04
glcm_MCC_d_1_CT_b20                                              0.00   0.99      0.02
glcm_MCC_d_1_CT_c16                                              0.10   0.75      0.41
glcm_MCC_d_1_PET_b2                                              0.01   0.93      0.10
glcm_MCC_d_1_PET_c04                                             0.02   0.88      0.19
glcm_MaximumProbability_d_1_CT_b20                               0.02   0.89      0.17
glcm_MaximumProbability_d_1_CT_c16                               0.10   0.75      0.42
glcm_MaximumProbability_d_1_PET_b2                               0.14   0.71      0.49
glcm_MaximumProbability_d_1_PET_c04                              0.03   0.86      0.22
glcm_SumAverage_d_1_CT_b20                                       0.08   0.78      0.36
glcm_SumAverage_d_1_CT_c16                                       0.02   0.89      0.16
glcm_SumAverage_d_1_PET_b2                                       0.01   0.90      0.15
glcm_SumAverage_d_1_PET_c04                                      0.00   0.95      0.08
glcm_SumEntropy_d_1_CT_b20                                       0.00   0.95      0.08
glcm_SumEntropy_d_1_CT_c16                                       0.08   0.78      0.36
glcm_SumEntropy_d_1_PET_b2                                       0.00   0.99      0.02
glcm_SumEntropy_d_1_PET_c04                                      0.00   0.96      0.06
glcm_SumSquares_d_1_CT_b20                                       0.00   0.95      0.08
glcm_SumSquares_d_1_CT_c16                                       0.02   0.89      0.17
glcm_SumSquares_d_1_PET_b2                                       0.01   0.94      0.09
glcm_SumSquares_d_1_PET_c04                                      0.09   0.77      0.39
gldm_DependenceEntropy_d_1_CT_b20                                0.14   0.71      0.49
gldm_DependenceEntropy_d_1_CT_c16                                0.18   0.67      0.58
gldm_DependenceEntropy_d_1_PET_b2                                0.03   0.87      0.19
gldm_DependenceEntropy_d_1_PET_c04                               0.04   0.84      0.26
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.12   0.73      0.45
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.08   0.78      0.37
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.38   0.54      0.90
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.18   0.67      0.57
gldm_DependenceNonUniformity_d_1_CT_b20                          0.03   0.87      0.20
gldm_DependenceNonUniformity_d_1_CT_c16                          2.71   0.10      3.33
gldm_DependenceNonUniformity_d_1_PET_b2                          0.04   0.85      0.23
gldm_DependenceNonUniformity_d_1_PET_c04                         0.15   0.70      0.51
gldm_DependenceVariance_d_1_CT_b20                               0.31   0.57      0.80
gldm_DependenceVariance_d_1_CT_c16                               0.21   0.65      0.63
gldm_DependenceVariance_d_1_PET_b2                               0.80   0.37      1.43
gldm_DependenceVariance_d_1_PET_c04                              1.04   0.31      1.70
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.42   0.52      0.96
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.33   0.57      0.82
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.27   0.61      0.72
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00   0.97      0.04
gldm_GrayLevelVariance_d_1_CT_b20                                0.01   0.94      0.09
gldm_GrayLevelVariance_d_1_CT_c16                                0.00   0.97      0.05
gldm_GrayLevelVariance_d_1_PET_b2                                0.00   0.96      0.06
gldm_GrayLevelVariance_d_1_PET_c04                               0.05   0.82      0.28
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.14   0.70      0.51
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00   0.99      0.02
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.03   0.86      0.22
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.02   0.89      0.16
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.02   0.90      0.16
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.04   0.84      0.25
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.10   0.75      0.41
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.02   0.88      0.19
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.77   0.38      1.40
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.04   0.84      0.25
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.13   0.72      0.48
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00   0.99      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.05   0.82      0.29
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.04   0.85      0.24
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.12   0.73      0.45
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.56   0.45      1.14
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.06   0.81      0.30
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00   1.00      0.00
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.01   0.94      0.09
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.50   0.48      1.07
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.02   0.88      0.19
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.10   0.75      0.41
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.05   0.83      0.27
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.02   0.89      0.17
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.39   0.53      0.91
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.05   0.82      0.29
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.09   0.77      0.38
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01   0.93      0.10
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00   0.95      0.07
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.18   0.67      0.57
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.14   0.70      0.51
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00   0.98      0.03
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.02   0.89      0.17
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.59   0.44      1.18
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.02   0.89      0.16
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.03   0.86      0.22
glrlm_GrayLevelNonUniformity_CT_b20                              0.02   0.90      0.15
glrlm_GrayLevelNonUniformity_CT_c16                              1.03   0.31      1.68
glrlm_GrayLevelNonUniformity_PET_b2                              0.06   0.80      0.31
glrlm_GrayLevelNonUniformity_PET_c04                             0.01   0.94      0.09
glrlm_GrayLevelVariance_CT_b20                                   0.06   0.80      0.32
glrlm_GrayLevelVariance_CT_c16                                   0.04   0.85      0.24
glrlm_GrayLevelVariance_PET_b2                                   0.01   0.91      0.13
glrlm_GrayLevelVariance_PET_c04                                  0.04   0.85      0.24
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.07   0.79      0.34

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['glszm_GrayLevelNonUniformity_PET_c04',
       'glszm_LargeAreaEmphasis_CT_c16',
       'glszm_LargeAreaLowGrayLevelEmphasis_CT_c16',
       'glszm_ZoneVariance_CT_c16', 'ngtdm_Busyness_d_1_PET_b2'],
      dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [18]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data[vif_data['VIF'] > 100000]

                           feature           VIF
0                 shape_Elongation  2.096355e+11
1                   shape_Flatness  3.609232e+11
2            shape_LeastAxisLength  2.691126e+12
3            shape_MajorAxisLength  7.524811e+12
4    shape_Maximum2DDiameterColumn  2.124339e+13
..                             ...           ...
369                    LBP_111_PET  5.922282e+11
370                    LBP_120_PET  3.305758e+11
371                    LBP_201_PET  1.508996e+12
372                    LBP_210_PET  1.369708e+12
373                    LBP_300_PET  7.392136e+09

[374 rows x 2 columns]

# Standardization

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

# Standardize non-categorical and then concat with the categorical
scaler = MinMaxScaler()  
X_std = scaler.fit_transform(X)
X_std = pd.DataFrame(X_std, columns=X_columns, index=X_index)

In [25]:
# Standardize the numeric part 
X_MAASTRO_column = X_MAASTRO.columns
X_MAASTRO_index = X_MAASTRO.index

X_MAASTRO_std = scaler.transform(X_MAASTRO)

# Change the standardized part into a dataframe 
X_MAASTRO_std = pd.DataFrame(X_MAASTRO_std, columns=X_MAASTRO_column, index=X_MAASTRO_index)

In [26]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [27]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:03:31,386] A new study created in memory with name: no-name-81a1b89b-2310-4d71-a58a-af9f11c1bc7c

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-14 16:03:31,827] Trial 0 failed with parameters: {} because of the following error: LinAlgError('Matrix is singular.').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_37071/1714754791.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 449, in fit
    delta = solve(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 220, in solve
    _solve_check(n, info)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[W 2024-04-14 16:03:31,832] Trial 0 failed with value None.

LinAlgError: Matrix is singular.

In [28]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [29]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [30]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [31]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

LinAlgError: Matrix is singular.

In [32]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [33]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [34]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:16:37,901] A new study created in memory with name: no-name-ead7a42c-724d-4eac-86a2-6a313e49da25

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-14 16:16:38,073] A new study created in memory with name: no-name-9ea83c54-b92c-48ad-a307-17d6b54efb30

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6158798283261803
[I 2024-04-14 16:16:38,067] Trial 0 finished with value: 0.5957320931913246 and parameters: {}. Best is trial 0 with value: 0.5957320931913246.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5957320931913246], datetime_start=datetime.datetime(2024, 4, 14, 16, 16, 37, 922709), datetime_complete=datetime.datetime(2024, 4, 14, 16, 16, 38, 67103), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5957320931913246

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709975125414
Fold 2 IBS: 0.23203988383665525
Fold 3 IBS: 0.22898186801315143
Fold 4 IBS: 0.24197477015984858
Fold 5 IBS: 0.22939559219095101
[I 2024-04-14 16:16:38,267] Trial 0 finished with value: 0.23592784279037207 and parameters: {}. Best is trial 0 with value: 0.23592784279037207.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784279037207], datetime_start=datetime.datetime(2024, 4, 14, 16, 16, 38, 100377), datetime_complete=datetime.datetime(2024, 4, 14, 16, 16, 38, 267307), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784279037207

In [35]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [36]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.596
train_ibs:  0.236

#### Test

In [37]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [38]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.51

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [39]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [40]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:16:41,714] A new study created in memory with name: no-name-87a61a6e-865e-4449-b5d0-909350624c9d

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.40239043824701193
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.37446808510638296
Fold 4 C-index: 0.38022813688212925

[I 2024-04-14 16:16:43,123] A new study created in memory with name: no-name-71d35dfb-01e2-4338-a6ad-742361194801

Fold 5 C-index: 0.5793991416309013
[I 2024-04-14 16:16:43,117] Trial 0 finished with value: 0.4682273929314246 and parameters: {}. Best is trial 0 with value: 0.4682273929314246.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.4682273929314246], datetime_start=datetime.datetime(2024, 4, 14, 16, 16, 41, 747800), datetime_complete=datetime.datetime(2024, 4, 14, 16, 16, 43, 117545), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.4682273929314246

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.5098830107005321
Fold 2 IBS: 0.3372965635980787
Fold 3 IBS: 0.4733678688584834
Fold 4 IBS: 0.5026474555138712
Fold 5 IBS: 0.3423885899507013
[I 2024-04-14 16:16:44,733] Trial 0 finished with value: 0.43311669772433337 and parameters: {}. Best is trial 0 with value: 0.43311669772433337.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.43311669772433337], datetime_start=datetime.datetime(2024, 4, 14, 16, 16, 43, 156238), datetime_complete=datetime.datetime(2024, 4, 14, 16, 16, 44, 733045), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.43311669772433337

In [41]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [42]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.468
train_ibs:  0.433

#### Test

In [43]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [44]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.522

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.423

In [45]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [46]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:16:45,448] A new study created in memory with name: no-name-33e8e44c-b065-4209-a3fd-8c4b182aa266

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.5813953488372093
Fold 3 C-index: 0.40425531914893614
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.5536480686695279
[I 2024-04-14 16:16:46,284] Trial 0 finished with value: 0.4774202884366745 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.4774202884366745.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:46,563] Trial 1 finished with value: 0.6110695760918012 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6110695760918012.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:46,720] Trial 2 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.43829787234042555
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.5536480686695279
[I 2024-04-14 16:16:47,309] Trial 3 finished with value: 0.5166179444124481 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.4
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.5536480686695279
[I 2024-04-14 16:16:48,052] Trial 4 finished with value: 0.47654760565633286 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5057034220532319
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 16:16:48,505] Trial 5 finished with value: 0.553170003833014 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.3617021276595745
Fold 4 C-index: 0.38783269961977185
Fold 5 C-index: 0.5622317596566524
[I 2024-04-14 16:16:49,697] Trial 6 finished with value: 0.4661520758417536 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.5813953488372093
Fold 3 C-index: 0.40425531914893614
Fold 4 C-index: 0.44106463878326996
Fold 5 C-index: 0.5579399141630901
[I 2024-04-14 16:16:50,422] Trial 7 finished with value: 0.4797995700829155 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.5665236051502146
[I 2024-04-14 16:16:50,810] Trial 8 finished with value: 0.5484366404150008 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 16:16:51,170] Trial 9 finished with value: 0.5873178232019262 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:16:51,329] Trial 10 finished with value: 0.6385523277334502 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:16:51,509] Trial 11 finished with value: 0.6385523277334502 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:16:51,686] Trial 12 finished with value: 0.6385523277334502 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:16:51,851] Trial 13 finished with value: 0.6428441732270123 and parameters: {'l1_ratio': 0.18977351772466045}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:52,022] Trial 14 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.24249236510312352}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:16:52,179] Trial 15 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.2245403429070307}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:16:52,456] Trial 16 finished with value: 0.6119279451905136 and parameters: {'l1_ratio': 0.31408489302885545}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:16:52,631] Trial 17 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.14799833455264066}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:52,900] Trial 18 finished with value: 0.6102727633427972 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4063745019920319
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.4425531914893617
Fold 4 C-index: 0.4790874524714829
Fold 5 C-index: 0.5536480686695279
[I 2024-04-14 16:16:53,524] Trial 19 finished with value: 0.5181931080407599 and parameters: {'l1_ratio': 0.5476641842948985}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:53,701] Trial 20 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2312342395344777}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:53,865] Trial 21 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.23674640483253295}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:16:54,068] Trial 22 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.13725479295058035}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:16:54,223] Trial 23 finished with value: 0.6385523277334502 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 2 with value: 0.6437388988009645.

Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5793991416309013
[I 2024-04-14 16:16:54,603] Trial 24 finished with value: 0.5898313741483551 and parameters: {'l1_ratio': 0.36894274155306017}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:54,879] Trial 25 finished with value: 0.6110695760918012 and parameters: {'l1_ratio': 0.28250483325041786}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5057034220532319
Fold 5 C-index: 0.575107296137339
[I 2024-04-14 16:16:55,374] Trial 26 finished with value: 0.5540283729317265 and parameters: {'l1_ratio': 0.43696099753129897}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 16:16:55,558] Trial 27 finished with value: 0.640269065930875 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:16:55,750] Trial 28 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.20823054591112547}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.3829787234042553
Fold 4 C-index: 0.39543726235741444
Fold 5 C-index: 0.5579399141630901
[I 2024-04-14 16:16:56,836] Trial 29 finished with value: 0.4679907821962618 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.4
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5579399141630901
[I 2024-04-14 16:16:57,647] Trial 30 finished with value: 0.48354071894508444 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:57,819] Trial 31 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.24354183082267372}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:58,019] Trial 32 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.27357119396913165}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:16:58,206] Trial 33 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.14710196556370791}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:58,502] Trial 34 finished with value: 0.6102727633427972 and parameters: {'l1_ratio': 0.33515677546102496}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:16:58,699] Trial 35 finished with value: 0.6419858041282999 and parameters: {'l1_ratio': 0.18495979229130063}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:16:58,895] Trial 36 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2653819061144756}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5095057034220533
Fold 5 C-index: 0.575107296137339
[I 2024-04-14 16:16:59,406] Trial 37 finished with value: 0.5531952037074828 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4063745019920319
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.44680851063829785
Fold 4 C-index: 0.49049429657794674
Fold 5 C-index: 0.5579399141630901
[I 2024-04-14 16:17:00,044] Trial 38 finished with value: 0.5221839097905523 and parameters: {'l1_ratio': 0.5262072332986051}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5793991416309013
[I 2024-04-14 16:17:00,400] Trial 39 finished with value: 0.5890345613993511 and parameters: {'l1_ratio': 0.3832648927387554}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.5930232558139535
Fold 3 C-index: 0.3872340425531915
Fold 4 C-index: 0.4068441064638783
Fold 5 C-index: 0.5450643776824035
[I 2024-04-14 16:17:01,411] Trial 40 finished with value: 0.46850486965009575 and parameters: {'l1_ratio': 0.7990252115442547}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:01,596] Trial 41 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2461752244867114}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:17:01,880] Trial 42 finished with value: 0.6119279451905136 and parameters: {'l1_ratio': 0.3080689231364965}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:17:02,109] Trial 43 finished with value: 0.6385523277334502 and parameters: {'l1_ratio': 0.05384567791809544}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:02,328] Trial 44 finished with value: 0.6428441732270123 and parameters: {'l1_ratio': 0.18620708798360056}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:17:02,508] Trial 45 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.13312248769736157}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:02,686] Trial 46 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.24475679048800753}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4063745019920319
Fold 2 C-index: 0.5930232558139535
Fold 3 C-index: 0.39574468085106385
Fold 4 C-index: 0.467680608365019
Fold 5 C-index: 0.5536480686695279
[I 2024-04-14 16:17:03,404] Trial 47 finished with value: 0.48329422313831916 and parameters: {'l1_ratio': 0.6170398835911917}. Best is trial 2 with value: 0.6437388988009645.

Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5793991416309013
[I 2024-04-14 16:17:03,763] Trial 48 finished with value: 0.5898313741483551 and parameters: {'l1_ratio': 0.3557590214625724}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:17:03,959] Trial 49 finished with value: 0.6385523277334502 and parameters: {'l1_ratio': 0.04567662268230008}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 16:17:04,343] Trial 50 finished with value: 0.5889114486999342 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:04,602] Trial 51 finished with value: 0.6110695760918012 and parameters: {'l1_ratio': 0.284459287504535}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:04,759] Trial 52 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.2225918073443785}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:17:04,906] Trial 53 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.16504314926261965}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 16:17:05,073] Trial 54 finished with value: 0.640269065930875 and parameters: {'l1_ratio': 0.10735131952985189}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:17:05,338] Trial 55 finished with value: 0.6119279451905136 and parameters: {'l1_ratio': 0.3079723338599511}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:05,518] Trial 56 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.24886686697579286}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:05,683] Trial 57 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.20471680368223738}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:05,985] Trial 58 finished with value: 0.6102727633427972 and parameters: {'l1_ratio': 0.3275312184715565}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 16:17:06,541] Trial 59 finished with value: 0.5508159220612419 and parameters: {'l1_ratio': 0.4707308203364923}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 16:17:06,902] Trial 60 finished with value: 0.5881146359509302 and parameters: {'l1_ratio': 0.4072132771067458}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:07,082] Trial 61 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2700591338853734}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:07,263] Trial 62 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.26468856103499583}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:17:07,426] Trial 63 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.16778479613929995}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:07,620] Trial 64 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.2191028382809566}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:17:07,869] Trial 65 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.12594139655515607}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:08,228] Trial 66 finished with value: 0.6110695760918012 and parameters: {'l1_ratio': 0.2946261248312133}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5793991416309013
[I 2024-04-14 16:17:08,723] Trial 67 finished with value: 0.5898313741483551 and parameters: {'l1_ratio': 0.3653331829586496}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:08,890] Trial 68 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.23251301137071226}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:17:09,058] Trial 69 finished with value: 0.6419858041282999 and parameters: {'l1_ratio': 0.18520144856788037}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:17:09,327] Trial 70 finished with value: 0.6119279451905136 and parameters: {'l1_ratio': 0.3419098266614614}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:09,517] Trial 71 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2700888314371204}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745

Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:09,712] Trial 72 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.23735828206252538}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4063745019920319
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.37446808510638296
Fold 4 C-index: 0.3650190114068441
Fold 5 C-index: 0.5665236051502146
[I 2024-04-14 16:17:11,218] Trial 73 finished with value: 0.46418246708768385 and parameters: {'l1_ratio': 0.992464045531057}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:17:11,424] Trial 74 finished with value: 0.6385523277334502 and parameters: {'l1_ratio': 0.05992256234771054}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:11,644] Trial 75 finished with value: 0.6436409859760163 and parameters: {'l1_ratio': 0.2005492533148954}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:11,847] Trial 76 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2554620403615323}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:17:12,069] Trial 77 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.16427454954604553}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:17:12,392] Trial 78 finished with value: 0.6119279451905136 and parameters: {'l1_ratio': 0.29649263034718215}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 16:17:12,587] Trial 79 finished with value: 0.640269065930875 and parameters: {'l1_ratio': 0.10460005447621551}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:17:12,908] Trial 80 finished with value: 0.6119279451905136 and parameters: {'l1_ratio': 0.3155124754657808}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:13,129] Trial 81 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2403256531030177}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.4103585657370518
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5793991416309013
[I 2024-04-14 16:17:13,587] Trial 82 finished with value: 0.5890345613993511 and parameters: {'l1_ratio': 0.3831689711631408}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:13,787] Trial 83 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.21018882876628167}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:13,990] Trial 84 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2573710296948649}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:17:14,221] Trial 85 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.13543500663785443}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:17:14,429] Trial 86 finished with value: 0.6419858041282999 and parameters: {'l1_ratio': 0.17587922247855245}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:14,803] Trial 87 finished with value: 0.6110695760918012 and parameters: {'l1_ratio': 0.2926151691963885}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:15,101] Trial 88 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.22610362070582635}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:15,465] Trial 89 finished with value: 0.6102727633427972 and parameters: {'l1_ratio': 0.3385068348223662}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:17:15,650] Trial 90 finished with value: 0.6411274350295875 and parameters: {'l1_ratio': 0.15381809349791908}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:15,825] Trial 91 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2540906253586118}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:15,993] Trial 92 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.23792564317494352}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:16,169] Trial 93 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.2740724733569772}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:16,348] Trial 94 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.20170830698689074}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:16,509] Trial 95 finished with value: 0.6437388988009645 and parameters: {'l1_ratio': 0.24750159858130572}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954

Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:17:16,797] Trial 96 finished with value: 0.6119279451905136 and parameters: {'l1_ratio': 0.3217293879932935}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:17,104] Trial 97 finished with value: 0.6110695760918012 and parameters: {'l1_ratio': 0.2806915997488599}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:17:17,379] Trial 98 finished with value: 0.6087154943200289 and parameters: {'l1_ratio': 0.35418663889266844}. Best is trial 2 with value: 0.6437388988009645.
Fold 1 C-index: 0.5856573705179283

[I 2024-04-14 16:17:17,621] A new study created in memory with name: no-name-85628d31-23e7-483b-b8bf-c8e04b570d4c

Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:17:17,615] Trial 99 finished with value: 0.6428805297022521 and parameters: {'l1_ratio': 0.21829597982539897}. Best is trial 2 with value: 0.6437388988009645.


* Best trial for C-index:
 FrozenTrial(number=2, state=TrialState.COMPLETE, values=[0.6437388988009645], datetime_start=datetime.datetime(2024, 4, 14, 16, 16, 46, 566862), datetime_complete=datetime.datetime(2024, 4, 14, 16, 16, 46, 720404), params={'l1_ratio': 0.22692876841884668}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=2, value=None)


* Best Score for C-index:
 0.6437388988009645

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.49645356464358287
Fold 2 IBS: 0.30808905655404734
Fold 3 IBS: 0.36277782336061554
Fold 4 IBS: 0.4089481533297419
Fold 5 IBS: 0.3412191759164054
[I 2024-04-14 16:17:18,606] Trial 0 finished with value: 0.3834975547608786 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.3834975547608786.
Fold 1 IBS: 0.4508594624119911
Fold 2 IBS: 0.2298052971832474
Fold 3 IBS: 0.22882247544561968
Fold 4 IBS: 0.23850171003694137
Fold 5 IBS: 0.2268433170424036
[I 2024-04-14 16:17:18,930] Trial 1 finished with value: 0.2749664524240406 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.2749664524240406.
Fold 1 IBS: 0.24564380086531118
Fold 2 IBS: 0.2303205034122087
Fold 3 IBS: 0.2288540127794953
Fold 4 IBS: 0.23918299331599008
Fold 5 IBS: 0.22739419016239
[I 2024-04-14 16:17:19,201] Trial 2 finished with value: 0.23427910010707906 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.48264387626089456
Fold 2 IBS: 0.22706989862243904
Fold 3 IBS: 0.3428548457659772
Fold 4 IBS: 0.38540904369273105
Fold 5 IBS: 0.32244430158724435
[I 2024-04-14 16:17:20,049] Trial 3 finished with value: 0.35208439318585727 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.49806714263554347
Fold 2 IBS: 0.30977193115210433
Fold 3 IBS: 0.36629941339755273
Fold 4 IBS: 0.4133967662370882
Fold 5 IBS: 0.3439487038189989
[I 2024-04-14 16:17:21,143] Trial 4 finished with value: 0.3862967914482575 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.4700047851477821
Fold 2 IBS: 0.22848858943347425
Fold 3 IBS: 0.22875919403291411
Fold 4 IBS: 0.37018891140867577
Fold 5 IBS: 0.3018471801781831
[I 2024-04-14 16:17:21,878] Trial 5 finished with value: 0.3198577320402059 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.5113775633602236
Fold 2 IBS: 0.329771326846705
Fold 3 IBS: 0.4534481555668159
Fold 4 IBS: 0.5021353065595731
Fold 5 IBS: 0.357292386713565
[I 2024-04-14 16:17:23,206] Trial 6 finished with value: 0.4308049478093765 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.4953422601913192
Fold 2 IBS: 0.307232985507833
Fold 3 IBS: 0.36134222026683394
Fold 4 IBS: 0.40649234867303
Fold 5 IBS: 0.34024857338898057
[I 2024-04-14 16:17:24,166] Trial 7 finished with value: 0.38213167760559935 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.4760636111176885
Fold 2 IBS: 0.227873080690423
Fold 3 IBS: 0.22873943078267583
Fold 4 IBS: 0.37596220794451624
Fold 5 IBS: 0.3105439678174916
[I 2024-04-14 16:17:24,943] Trial 8 finished with value: 0.3238364596705591 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.4666580433121223
Fold 2 IBS: 0.22880315974453586
Fold 3 IBS: 0.22877184773604378
Fold 4 IBS: 0.23732651359974316
Fold 5 IBS: 0.2972118426463854
[I 2024-04-14 16:17:25,438] Trial 9 finished with value: 0.2917542814077661 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.246661653665381
Fold 2 IBS: 0.23143769903094505
Fold 3 IBS: 0.2289342282193068
Fold 4 IBS: 0.24090756690605528
Fold 5 IBS: 0.22867109289700316
[I 2024-04-14 16:17:25,672] Trial 10 finished with value: 0.2353224481437383 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.24716175422637268
Fold 2 IBS: 0.23195355275092647
Fold 3 IBS: 0.22897491837211664
Fold 4 IBS: 0.24181575025914032
Fold 5 IBS: 0.22929031634505423
[I 2024-04-14 16:17:25,885] Trial 11 finished with value: 0.23583925839072206 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.24666226472542302
Fold 2 IBS: 0.23143833922201537
Fold 3 IBS: 0.22893427773533118
Fold 4 IBS: 0.24090865249028387
Fold 5 IBS: 0.228671852363438
[I 2024-04-14 16:17:26,088] Trial 12 finished with value: 0.23532307730729823 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.24591109814047346
Fold 2 IBS: 0.23062827525244442
Fold 3 IBS: 0.22887446089708935
Fold 4 IBS: 0.23961953663301983
Fold 5 IBS: 0.2277320066304452
[I 2024-04-14 16:17:26,328] Trial 13 finished with value: 0.23455307551069443 and parameters: {'l1_ratio': 0.18977351772466045}. Best is trial 2 with value: 0.23427910010707906.
Fold 1 IBS: 0.2455310311418162
Fold 2 IBS: 0.2301881867851082
Fold 3 IBS: 0.2288455835640097
Fold 4 IBS: 0.2390023583076393
Fold 5 IBS: 0.2272510792592305
[I 2024-04-14 16:17:26,560] Trial 14 finished with value: 0.2341636478115608 and parameters: {'l1_ratio': 0.24249236510312352}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.2456610624215045
Fold 2 IBS: 0.23034062870989044
Fold 3 IBS: 0.22885531422938818
Fold 4 IBS: 0.239210828749445
Fold 5 IBS: 0.22741606453892366
[I 2024-04-14 16:17:26,759] Trial 15 finished with value: 0.23429677972983037 and parameters: {'l1_ratio': 0.2245403429070307}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.4558462508849545
Fold 2 IBS: 0.22955218994590146
Fold 3 IBS: 0.22880829409382528
Fold 4 IBS: 0.23818752299947302
Fold 5 IBS: 0.22657838700700994
[I 2024-04-14 16:17:27,068] Trial 16 finished with value: 0.27579452898623286 and parameters: {'l1_ratio': 0.31408489302885545}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.2462088447857958
Fold 2 IBS: 0.2309572947383729
Fold 3 IBS: 0.2288978515281473
Fold 4 IBS: 0.240119590384616
Fold 5 IBS: 0.22810612112657586
[I 2024-04-14 16:17:27,312] Trial 17 finished with value: 0.23485794051270154 and parameters: {'l1_ratio': 0.14799833455264066}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.4597577123106736
Fold 2 IBS: 0.22932128716980396
Fold 3 IBS: 0.22879615459066216
Fold 4 IBS: 0.23791162744043284
Fold 5 IBS: 0.2263394638701018
[I 2024-04-14 16:17:27,615] Trial 18 finished with value: 0.27642524907633487 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.4822287161471945
Fold 2 IBS: 0.22711363711055835
Fold 3 IBS: 0.34230783062491427
Fold 4 IBS: 0.3846896469480975
Fold 5 IBS: 0.3218322346371569
[I 2024-04-14 16:17:28,297] Trial 19 finished with value: 0.3516344130935843 and parameters: {'l1_ratio': 0.5476641842948985}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.24561265521283573
Fold 2 IBS: 0.23028410416267026
Fold 3 IBS: 0.22885167185616992
Fold 4 IBS: 0.23913289352502093
Fold 5 IBS: 0.22735470041289327
[I 2024-04-14 16:17:28,495] Trial 20 finished with value: 0.23424720503391802 and parameters: {'l1_ratio': 0.2312342395344777}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.24557272432267305
Fold 2 IBS: 0.2302372756180387
Fold 3 IBS: 0.22884868481709764
Fold 4 IBS: 0.23906889707040382
Fold 5 IBS: 0.2273040319897977
[I 2024-04-14 16:17:28,693] Trial 21 finished with value: 0.23420632276360215 and parameters: {'l1_ratio': 0.23674640483253295}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.24637387005498215
Fold 2 IBS: 0.23113371360147467
Fold 3 IBS: 0.22891102168613112
Fold 4 IBS: 0.2404029450231213
Fold 5 IBS: 0.22831254980119456
[I 2024-04-14 16:17:28,903] Trial 22 finished with value: 0.23502682003338077 and parameters: {'l1_ratio': 0.12469232350040972}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.2472305922729725
Fold 2 IBS: 0.23202322571420206
Fold 3 IBS: 0.22898052370383556
Fold 4 IBS: 0.24194393876010198
Fold 5 IBS: 0.2293752406382832
[I 2024-04-14 16:17:29,099] Trial 23 finished with value: 0.2359107042178791 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 14 with value: 0.2341636478115608.
Fold 1 IBS: 0.24538218280060495
Fold 2 IBS: 0.23001133854962522
Fold 3 IBS: 0.22883466914579215
Fold 4 IBS: 0.23876715794421993
Fold 5 IBS: 0.22706161666195307
[I 2024-04-14 16:17:29,288] Trial 24 finished with value: 0.23401139302043905 and parameters: {'l1_ratio': 0.2629237523336605}. Best is trial 24 with value: 0.23401139302043905.

Fold 1 IBS: 0.466398795642302
Fold 2 IBS: 0.22882772639684487
Fold 3 IBS: 0.22877290473956685
Fold 4 IBS: 0.2373532638825162
Fold 5 IBS: 0.29681562006401563
[I 2024-04-14 16:17:29,727] Trial 25 finished with value: 0.29163366214504916 and parameters: {'l1_ratio': 0.38971525832834536}. Best is trial 24 with value: 0.23401139302043905.
Fold 1 IBS: 0.45186227275074664
Fold 2 IBS: 0.22976130645640724
Fold 3 IBS: 0.2288199466463936
Fold 4 IBS: 0.2384461837034837
Fold 5 IBS: 0.2267970258922456
[I 2024-04-14 16:17:30,053] Trial 26 finished with value: 0.2751373470898554 and parameters: {'l1_ratio': 0.2911123931485357}. Best is trial 24 with value: 0.23401139302043905.
Fold 1 IBS: 0.47624166338835305
Fold 2 IBS: 0.22784726392344626
Fold 3 IBS: 0.22873875445233233
Fold 4 IBS: 0.37634204248349573
Fold 5 IBS: 0.3109773857303955
[I 2024-04-14 16:17:30,581] Trial 27 finished with value: 0.3240294219956046 and parameters: {'l1_ratio': 0.48333206147305935}. Best is trial 24 with value: 0.23401139302043905.
Fold 1 IBS: 0.5102659223134544
Fold 2 IBS: 0.3306244981136817
Fold 3 IBS: 0.44525978594069093
Fold 4 IBS: 0.5013476631262496
Fold 5 IBS: 0.35507356509155413
[I 2024-04-14 16:17:31,961] Trial 28 finished with value: 0.42851428691712606 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 24 with value: 0.23401139302043905.
Fold 1 IBS: 0.24616943519836426
Fold 2 IBS: 0.23091495458180347
Fold 3 IBS: 0.22889472556472798
Fold 4 IBS: 0.24005257481703288
Fold 5 IBS: 0.22805672929573884
[I 2024-04-14 16:17:32,203] Trial 29 finished with value: 0.2348176838915335 and parameters: {'l1_ratio': 0.15354880795613854}. Best is trial 24 with value: 0.23401139302043905.
Fold 1 IBS: 0.4908418488620373
Fold 2 IBS: 0.3026094403007821
Fold 3 IBS: 0.3545659493646344
Fold 4 IBS: 0.39758330756374916
Fold 5 IBS: 0.3352464240285839
[I 2024-04-14 16:17:33,046] Trial 30 finished with value: 0.3761693940239574 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 24 with value: 0.23401139302043905.
Fold 1 IBS: 0.2455234084140341
Fold 2 IBS: 0.2301791906141777
Fold 3 IBS: 0.22884501856368852
Fold 4 IBS: 0.23899022427326394
Fold 5 IBS: 0.22724139260822837
[I 2024-04-14 16:17:33,265] Trial 31 finished with value: 0.23415584689467855 and parameters: {'l1_ratio': 0.24354183082267372}. Best is trial 24 with value: 0.23401139302043905.
Fold 1 IBS: 0.24537274097564638
Fold 2 IBS: 0.23000003729563545
Fold 3 IBS: 0.2288339855998424
Fold 4 IBS: 0.2387523633900144
Fold 5 IBS: 0.22704957721035013
[I 2024-04-14 16:17:33,486] Trial 32 finished with value: 0.23400174089429776 and parameters: {'l1_ratio': 0.2642152854612092}. Best is trial 32 with value: 0.23400174089429776.
Fold 1 IBS: 0.45988289153138506
Fold 2 IBS: 0.2293134295642292
Fold 3 IBS: 0.2287957552536686
Fold 4 IBS: 0.23790241075139745
Fold 5 IBS: 0.2263313757220446
[I 2024-04-14 16:17:33,901] Trial 33 finished with value: 0.276445172564545 and parameters: {'l1_ratio': 0.33967020776393025}. Best is trial 32 with value: 0.23400174089429776.
Fold 1 IBS: 0.24668060868158456
Fold 2 IBS: 0.23145754691274809
Fold 3 IBS: 0.22893576457254924
Fold 4 IBS: 0.2409412693390501
Fold 5 IBS: 0.228694647988226
[I 2024-04-14 16:17:34,125] Trial 34 finished with value: 0.2353419674988316 and parameters: {'l1_ratio': 0.08112681909214389}. Best is trial 32 with value: 0.23400174089429776.
Fold 1 IBS: 0.4712943138313767
Fold 2 IBS: 0.22837438938807073
Fold 3 IBS: 0.22875501530206643
Fold 4 IBS: 0.37125852904342505
Fold 5 IBS: 0.30355026172181376
[I 2024-04-14 16:17:34,700] Trial 35 finished with value: 0.32064650185735055 and parameters: {'l1_ratio': 0.4341659024174019}. Best is trial 32 with value: 0.23400174089429776.
Fold 1 IBS: 0.24536008330812317
Fold 2 IBS: 0.22998487143014032
Fold 3 IBS: 0.22883307096547525
Fold 4 IBS: 0.23873255320884862
Fold 5 IBS: 0.2270334330596376
[I 2024-04-14 16:17:34,963] Trial 36 finished with value: 0.23398880239444497 and parameters: {'l1_ratio': 0.26594584591028053}. Best is trial 36 with value: 0.23398880239444497.
Fold 1 IBS: 0.505605747847115
Fold 2 IBS: 0.3226506369203931
Fold 3 IBS: 0.4048077734731911
Fold 4 IBS: 0.46599943024959645
Fold 5 IBS: 0.3545129593882952
[I 2024-04-14 16:17:35,964] Trial 37 finished with value: 0.4107153095757182 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 36 with value: 0.23398880239444497.
Fold 1 IBS: 0.24528880954331372
Fold 2 IBS: 0.22989914656029273
Fold 3 IBS: 0.22882795866454625
Fold 4 IBS: 0.23862150525438963
Fold 5 IBS: 0.22694243991433222
[I 2024-04-14 16:17:36,181] Trial 38 finished with value: 0.2339159719873749 and parameters: {'l1_ratio': 0.2756715601318073}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.4615762559602143
Fold 2 IBS: 0.22920059135785378
Fold 3 IBS: 0.2287901225934976
Fold 4 IBS: 0.23777126424636263
Fold 5 IBS: 0.22621551418679106
[I 2024-04-14 16:17:36,525] Trial 39 finished with value: 0.2767107496689439 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.4816487841531768
Fold 2 IBS: 0.22717722604881793
Fold 3 IBS: 0.34145175587691734
Fold 4 IBS: 0.383803412420489
Fold 5 IBS: 0.3208535510282121
[I 2024-04-14 16:17:37,239] Trial 40 finished with value: 0.3509869459055227 and parameters: {'l1_ratio': 0.542264488740761}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.44928478164863245
Fold 2 IBS: 0.22987670273979657
Fold 3 IBS: 0.22882663649940863
Fold 4 IBS: 0.238592689265085
Fold 5 IBS: 0.22691868877686616
[I 2024-04-14 16:17:37,634] Trial 41 finished with value: 0.27469989978595777 and parameters: {'l1_ratio': 0.27820220089078046}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.24590971097805842
Fold 2 IBS: 0.23062669955463316
Fold 3 IBS: 0.22887435328436218
Fold 4 IBS: 0.2396172408289336
Fold 5 IBS: 0.22773025841976835
[I 2024-04-14 16:17:37,859] Trial 42 finished with value: 0.23455165261315117 and parameters: {'l1_ratio': 0.18996723622963846}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.2453426012099436
Fold 2 IBS: 0.22996389609328918
Fold 3 IBS: 0.2288318110044902
Fold 4 IBS: 0.23870523640777333
Fold 5 IBS: 0.22701112784376803
[I 2024-04-14 16:17:38,059] Trial 43 finished with value: 0.23397093451185288 and parameters: {'l1_ratio': 0.2683343678677668}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.47073381693821137
Fold 2 IBS: 0.22842818634898004
Fold 3 IBS: 0.2287569556677416
Fold 4 IBS: 0.3707211892226343
Fold 5 IBS: 0.3028381235281518
[I 2024-04-14 16:17:38,600] Trial 44 finished with value: 0.3202956543411438 and parameters: {'l1_ratio': 0.42899928582577485}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.4641825428942446
Fold 2 IBS: 0.22900786159052475
Fold 3 IBS: 0.22878095080796876
Fold 4 IBS: 0.23755234167680206
Fold 5 IBS: 0.2940174036813108
[I 2024-04-14 16:17:39,061] Trial 45 finished with value: 0.29070822013017017 and parameters: {'l1_ratio': 0.37145793322536885}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.24592986533260244
Fold 2 IBS: 0.2306495709530543
Fold 3 IBS: 0.22887591819120498
Fold 4 IBS: 0.2396506280014406
Fold 5 IBS: 0.2277556535911776
[I 2024-04-14 16:17:39,358] Trial 46 finished with value: 0.23457232721389598 and parameters: {'l1_ratio': 0.1871517904727446}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.45413571244626294
Fold 2 IBS: 0.22964643072855764
Fold 3 IBS: 0.2288134694053458
Fold 4 IBS: 0.23830302498934042
Fold 5 IBS: 0.2266766378864187
[I 2024-04-14 16:17:39,748] Trial 47 finished with value: 0.27551505509118507 and parameters: {'l1_ratio': 0.30379857097623475}. Best is trial 38 with value: 0.2339159719873749.
Fold 1 IBS: 0.24528549063453303
Fold 2 IBS: 0.22989514115114126
Fold 3 IBS: 0.22882772220764128
Fold 4 IBS: 0.2386163548694844
Fold 5 IBS: 0.2269381990377842
[I 2024-04-14 16:17:40,008] Trial 48 finished with value: 0.2339125815801168 and parameters: {'l1_ratio': 0.2761236619004883}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4727550387895351
Fold 2 IBS: 0.22823203432492298
Fold 3 IBS: 0.22875012616468834
Fold 4 IBS: 0.37257734172154866
Fold 5 IBS: 0.30550699697936906
[I 2024-04-14 16:17:40,790] Trial 49 finished with value: 0.32156430759601284 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 48 with value: 0.2339125815801168.

Fold 1 IBS: 0.24637482995821008
Fold 2 IBS: 0.2311347354827766
Fold 3 IBS: 0.22891109863503797
Fold 4 IBS: 0.24040460607923667
Fold 5 IBS: 0.22831374870955315
[I 2024-04-14 16:17:41,053] Trial 50 finished with value: 0.2350278037729629 and parameters: {'l1_ratio': 0.12455647091111496}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.45336290866765294
Fold 2 IBS: 0.2296841697272185
Fold 3 IBS: 0.22881557701400743
Fold 4 IBS: 0.2383497652205923
Fold 5 IBS: 0.2267161104254823
[I 2024-04-14 16:17:41,469] Trial 51 finished with value: 0.2753857062109907 and parameters: {'l1_ratio': 0.29964893239692797}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24594423385734104
Fold 2 IBS: 0.23066584735776324
Fold 3 IBS: 0.2288770356389336
Fold 4 IBS: 0.23967447114034615
Fold 5 IBS: 0.22777375198236005
[I 2024-04-14 16:17:41,707] Trial 52 finished with value: 0.23458706799534879 and parameters: {'l1_ratio': 0.18514345548822425}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.44911712978992613
Fold 2 IBS: 0.22988470885194626
Fold 3 IBS: 0.22882710735897951
Fold 4 IBS: 0.23860295628779138
Fold 5 IBS: 0.2269271578594099
[I 2024-04-14 16:17:42,118] Trial 53 finished with value: 0.2746718120296106 and parameters: {'l1_ratio': 0.27730021752709894}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24695108438078645
Fold 2 IBS: 0.23173833366653587
Fold 3 IBS: 0.22895778575804474
Fold 4 IBS: 0.24142741762351522
Fold 5 IBS: 0.2290298571403701
[I 2024-04-14 16:17:42,366] Trial 54 finished with value: 0.2356208957138505 and parameters: {'l1_ratio': 0.042426644073695285}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.2454252316570623
Fold 2 IBS: 0.23006273994955012
Fold 3 IBS: 0.22883779936941848
Fold 4 IBS: 0.23883480738962257
Fold 5 IBS: 0.22711648432919984
[I 2024-04-14 16:17:42,612] Trial 55 finished with value: 0.23405541253897066 and parameters: {'l1_ratio': 0.2570282675143364}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24575858011976587
Fold 2 IBS: 0.23045367976915673
Fold 3 IBS: 0.22886271859186957
Fold 4 IBS: 0.23936900688165644
Fold 5 IBS: 0.22753948764845225
[I 2024-04-14 16:17:42,867] Trial 56 finished with value: 0.23439669460218018 and parameters: {'l1_ratio': 0.21101783011398473}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.46739765047205056
Fold 2 IBS: 0.22873483250426993
Fold 3 IBS: 0.22876895956917334
Fold 4 IBS: 0.23725260503780216
Fold 5 IBS: 0.29814365483615224
[I 2024-04-14 16:17:43,502] Trial 57 finished with value: 0.2920595404838896 and parameters: {'l1_ratio': 0.3989954133062651}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24620816179465393
Fold 2 IBS: 0.23095656162657274
Fold 3 IBS: 0.22889779728522058
Fold 4 IBS: 0.24011842682036033
Fold 5 IBS: 0.2281052654539853
[I 2024-04-14 16:17:43,801] Trial 58 finished with value: 0.2348572425961586 and parameters: {'l1_ratio': 0.14809457918275226}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4585941449808782
Fold 2 IBS: 0.22939340772928096
Fold 3 IBS: 0.2287998625976342
Fold 4 IBS: 0.23799674336355658
Fold 5 IBS: 0.2264138268594822
[I 2024-04-14 16:17:44,220] Trial 59 finished with value: 0.2762395971061664 and parameters: {'l1_ratio': 0.331174573266952}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24532935486722032
Fold 2 IBS: 0.22994798050722665
Fold 3 IBS: 0.2288308588875232
Fold 4 IBS: 0.2386845721965649
Fold 5 IBS: 0.22699422096242572
[I 2024-04-14 16:17:44,471] Trial 60 finished with value: 0.23395739748419214 and parameters: {'l1_ratio': 0.27014289931267665}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24536433983345568
Fold 2 IBS: 0.2299899733871363
Fold 3 IBS: 0.22883337831756684
Fold 4 IBS: 0.2387392120011517
Fold 5 IBS: 0.22703886254770683
[I 2024-04-14 16:17:44,913] Trial 61 finished with value: 0.23399315321740347 and parameters: {'l1_ratio': 0.26536400302031443}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24576168267018206
Fold 2 IBS: 0.2304572584543004
Fold 3 IBS: 0.22886295555678596
Fold 4 IBS: 0.23937406510180062
Fold 5 IBS: 0.22754341012124246
[I 2024-04-14 16:17:45,459] Trial 62 finished with value: 0.23439987438086227 and parameters: {'l1_ratio': 0.2105868078535715}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.46201031016964933
Fold 2 IBS: 0.22917098349587967
Fold 3 IBS: 0.22878867647692921
Fold 4 IBS: 0.2377372215665696
Fold 5 IBS: 0.2915419289355723
[I 2024-04-14 16:17:46,322] Trial 63 finished with value: 0.28984982412892 and parameters: {'l1_ratio': 0.35461922821630465}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4544212181073538
Fold 2 IBS: 0.22963046742360976
Fold 3 IBS: 0.22881258392443787
Fold 4 IBS: 0.23828333868402266
Fold 5 IBS: 0.22665996358275922
[I 2024-04-14 16:17:46,763] Trial 64 finished with value: 0.27556151434443665 and parameters: {'l1_ratio': 0.30554856987226653}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4665780581678236
Fold 2 IBS: 0.22881137685576958
Fold 3 IBS: 0.2287722001960146
Fold 4 IBS: 0.23733545060948402
Fold 5 IBS: 0.2971117912652906
[I 2024-04-14 16:17:47,598] Trial 65 finished with value: 0.29172177541887645 and parameters: {'l1_ratio': 0.3913551698440265}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.245416352527275
Fold 2 IBS: 0.23005215491141526
Fold 3 IBS: 0.22883715192448398
Fold 4 IBS: 0.23882083053468667
Fold 5 IBS: 0.22710517383333823
[I 2024-04-14 16:17:48,050] Trial 66 finished with value: 0.23404633274623982 and parameters: {'l1_ratio': 0.25824517195500296}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24654640805007638
Fold 2 IBS: 0.23131655161119227
Fold 3 IBS: 0.2289249054890868
Fold 4 IBS: 0.24070389271761738
Fold 5 IBS: 0.22852772185350528
[I 2024-04-14 16:17:48,423] Trial 67 finished with value: 0.23520389594429564 and parameters: {'l1_ratio': 0.10022359348974141}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24606616765991893
Fold 2 IBS: 0.23080299158194162
Fold 3 IBS: 0.22888657491390635
Fold 4 IBS: 0.23987816662106923
Fold 5 IBS: 0.22792712551633007
[I 2024-04-14 16:17:48,758] Trial 68 finished with value: 0.23471220525863323 and parameters: {'l1_ratio': 0.1680634428276812}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24569212302330293
Fold 2 IBS: 0.23037675604719451
Fold 3 IBS: 0.2288576631845299
Fold 4 IBS: 0.239261040106026
Fold 5 IBS: 0.2274554046918815
[I 2024-04-14 16:17:49,095] Trial 69 finished with value: 0.23432859741058695 and parameters: {'l1_ratio': 0.22023861151089497}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.45751255812214175
Fold 2 IBS: 0.22945463740280939
Fold 3 IBS: 0.22880307064491157
Fold 4 IBS: 0.23806975333471705
Fold 5 IBS: 0.22647714420184575
[I 2024-04-14 16:17:49,791] Trial 70 finished with value: 0.2760634327412851 and parameters: {'l1_ratio': 0.3246198999865568}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.2453008288923848
Fold 2 IBS: 0.22991364201033088
Fold 3 IBS: 0.22882881620037154
Fold 4 IBS: 0.23864017266423557
Fold 5 IBS: 0.226957795398405
[I 2024-04-14 16:17:50,287] Trial 71 finished with value: 0.23392825103314557 and parameters: {'l1_ratio': 0.27403369270315947}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4498115659032343
Fold 2 IBS: 0.22985276846755237
Fold 3 IBS: 0.22882523403941252
Fold 4 IBS: 0.2385620760477069
Fold 5 IBS: 0.22689339260517524
[I 2024-04-14 16:17:51,345] Trial 72 finished with value: 0.2747890074126163 and parameters: {'l1_ratio': 0.28089379058414143}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24550737037836928
Fold 2 IBS: 0.23016024144535802
Fold 3 IBS: 0.22884383187438842
Fold 4 IBS: 0.23896472606327368
Fold 5 IBS: 0.22722100670382714
[I 2024-04-14 16:17:52,155] Trial 73 finished with value: 0.23413943529304332 and parameters: {'l1_ratio': 0.24574879600444333}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.46302842310511494
Fold 2 IBS: 0.2291032817826554
Fold 3 IBS: 0.2287854201173726
Fold 4 IBS: 0.23765994467186932
Fold 5 IBS: 0.2926085955903513
[I 2024-04-14 16:17:53,082] Trial 74 finished with value: 0.29023713305347265 and parameters: {'l1_ratio': 0.36164377615729193}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24576948233390114

Fold 2 IBS: 0.23046625016103817
Fold 3 IBS: 0.22886355164113878
Fold 4 IBS: 0.23938678822922885
Fold 5 IBS: 0.22755326987902014
[I 2024-04-14 16:17:53,599] Trial 75 finished with value: 0.23440786844886544 and parameters: {'l1_ratio': 0.20950302481432298}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4580818271335593
Fold 2 IBS: 0.2294254508419846
Fold 3 IBS: 0.22880153462379343
Fold 4 IBS: 0.2380348649875556
Fold 5 IBS: 0.22644694102617802
[I 2024-04-14 16:17:54,184] Trial 76 finished with value: 0.27615812372261417 and parameters: {'l1_ratio': 0.32774984782502226}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.474858623807836
Fold 2 IBS: 0.22801368333023353
Fold 3 IBS: 0.22874333579261105
Fold 4 IBS: 0.374315539258652
Fold 5 IBS: 0.3086153091428531
[I 2024-04-14 16:17:54,997] Trial 77 finished with value: 0.32290929826643716 and parameters: {'l1_ratio': 0.4680890068967426}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4997659336752999
Fold 2 IBS: 0.31252879889133206
Fold 3 IBS: 0.371152863597635
Fold 4 IBS: 0.4216222404435959
Fold 5 IBS: 0.34740737050367004
[I 2024-04-14 16:17:56,596] Trial 78 finished with value: 0.3904954414223066 and parameters: {'l1_ratio': 0.7521153303890067}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24528889364317633
Fold 2 IBS: 0.2298992480402283
Fold 3 IBS: 0.22882796465816144
Fold 4 IBS: 0.23862163578707835
Fold 5 IBS: 0.22694254737223013
[I 2024-04-14 16:17:56,868] Trial 79 finished with value: 0.23391605790017495 and parameters: {'l1_ratio': 0.2756601031279141}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.47956597318950384
Fold 2 IBS: 0.2274122898175949
Fold 3 IBS: 0.3371148650693835
Fold 4 IBS: 0.3808536129954605
Fold 5 IBS: 0.31744735287720294
[I 2024-04-14 16:17:57,724] Trial 80 finished with value: 0.34847881878982917 and parameters: {'l1_ratio': 0.5220200844032834}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24531884274376353
Fold 2 IBS: 0.2299353364051233
Fold 3 IBS: 0.228830104892702
Fold 4 IBS: 0.23866819420681198
Fold 5 IBS: 0.22698080018186467
[I 2024-04-14 16:17:58,023] Trial 81 finished with value: 0.23394665568605308 and parameters: {'l1_ratio': 0.2715773396401889}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4516038078470057
Fold 2 IBS: 0.22977235665635615
Fold 3 IBS: 0.22882057936265038
Fold 4 IBS: 0.2384600944316319
Fold 5 IBS: 0.22680864386379307
[I 2024-04-14 16:17:58,377] Trial 82 finished with value: 0.2750930964322874 and parameters: {'l1_ratio': 0.2898834120069339}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24557329820855173
Fold 2 IBS: 0.23023794992388028
Fold 3 IBS: 0.2288487276313622
Fold 4 IBS: 0.23906981495477161
Fold 5 IBS: 0.22730476051376608
[I 2024-04-14 16:17:58,726] Trial 83 finished with value: 0.2342069102464664 and parameters: {'l1_ratio': 0.23666724654151097}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4540606431278316
Fold 2 IBS: 0.22964978843117298
Fold 3 IBS: 0.22881365611290067
Fold 4 IBS: 0.2383071721538969
Fold 5 IBS: 0.22668014681539306
[I 2024-04-14 16:17:59,136] Trial 84 finished with value: 0.275502281328239 and parameters: {'l1_ratio': 0.3034300806059097}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.48882976121466254
Fold 2 IBS: 0.3002507955828665
Fold 3 IBS: 0.35123414534634206
Fold 4 IBS: 0.39404721459287684
Fold 5 IBS: 0.3319005815370452
[I 2024-04-14 16:18:00,227] Trial 85 finished with value: 0.37325249965475865 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.46525203985304475
Fold 2 IBS: 0.2289253996189093
Fold 3 IBS: 0.2287772033795693
Fold 4 IBS: 0.23746056074355823
Fold 5 IBS: 0.29526559638213734
[I 2024-04-14 16:18:00,795] Trial 86 finished with value: 0.29113615999544373 and parameters: {'l1_ratio': 0.3798590809239262}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4689343856639166
Fold 2 IBS: 0.22858584842660618
Fold 3 IBS: 0.22876292934510425
Fold 4 IBS: 0.23709390589492893
Fold 5 IBS: 0.30030858699500335
[I 2024-04-14 16:18:01,313] Trial 87 finished with value: 0.2927371312651118 and parameters: {'l1_ratio': 0.4136919391584562}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24637835177781606
Fold 2 IBS: 0.23113848425855435
Fold 3 IBS: 0.22891138098622638
Fold 4 IBS: 0.24041070165301345
Fold 5 IBS: 0.22831814724521687
[I 2024-04-14 16:18:01,553] Trial 88 finished with value: 0.23503141318416546 and parameters: {'l1_ratio': 0.12405800944674578}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.2453640090893747
Fold 2 IBS: 0.2299895770222555
Fold 3 IBS: 0.2288333544273761
Fold 4 IBS: 0.23873869448579432
Fold 5 IBS: 0.22703844068023563
[I 2024-04-14 16:18:01,835] Trial 89 finished with value: 0.23399281514100725 and parameters: {'l1_ratio': 0.2654092178851629}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24609609259374574
Fold 2 IBS: 0.23083595183991293
Fold 3 IBS: 0.22888893047349126
Fold 4 IBS: 0.2399285281778332
Fold 5 IBS: 0.22796470918224201
[I 2024-04-14 16:18:02,070] Trial 90 finished with value: 0.234742842453445 and parameters: {'l1_ratio': 0.16386189804236453}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24534367800168044
Fold 2 IBS: 0.2299651890197338
Fold 3 IBS: 0.22883188849952207
Fold 4 IBS: 0.2387069174837489
Fold 5 IBS: 0.22701250197145353
[I 2024-04-14 16:18:02,346] Trial 91 finished with value: 0.23397203499522776 and parameters: {'l1_ratio': 0.26818730445101396}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24589871615742545
Fold 2 IBS: 0.23061420287350967
Fold 3 IBS: 0.22887350086850022
Fold 4 IBS: 0.23959905586749278
Fold 5 IBS: 0.2277164006493463
[I 2024-04-14 16:18:02,598] Trial 92 finished with value: 0.2345403752832549 and parameters: {'l1_ratio': 0.19150229756611026}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.2455218073123615
Fold 2 IBS: 0.23017730019517985
Fold 3 IBS: 0.2288448999689877
Fold 4 IBS: 0.23898767682855657
Fold 5 IBS: 0.22723935778275622
[I 2024-04-14 16:18:02,844] Trial 93 finished with value: 0.23415420841756837 and parameters: {'l1_ratio': 0.24376222175995632}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4554988171162863
Fold 2 IBS: 0.22957109449323163
Fold 3 IBS: 0.2288093221404785
Fold 4 IBS: 0.23821055468397154
Fold 5 IBS: 0.22659806017872564
[I 2024-04-14 16:18:03,297] Trial 94 finished with value: 0.2757375697225387 and parameters: {'l1_ratio': 0.3120301204236529}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24530479962739957
Fold 2 IBS: 0.22991842729158174
Fold 3 IBS: 0.22882909991307473
Fold 4 IBS: 0.23864634497271617
Fold 5 IBS: 0.22696286731944298
[I 2024-04-14 16:18:03,556] Trial 95 finished with value: 0.23393230782484306 and parameters: {'l1_ratio': 0.27349240057999824}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4606334126754762
Fold 2 IBS: 0.22926192492608768
Fold 3 IBS: 0.22879316051176646
Fold 4 IBS: 0.23784227053554283
Fold 5 IBS: 0.226278425234528
[I 2024-04-14 16:18:03,954] Trial 96 finished with value: 0.2765618387766802 and parameters: {'l1_ratio': 0.3451020956159598}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.24565219658665338
Fold 2 IBS: 0.23033029628180585
Fold 3 IBS: 0.22885464542477774
Fold 4 IBS: 0.2391965258342625
Fold 5 IBS: 0.2274048305141175
[I 2024-04-14 16:18:04,259] Trial 97 finished with value: 0.2342876989283234 and parameters: {'l1_ratio': 0.22576727833410568}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.44941371134540226
Fold 2 IBS: 0.2298712043007479
Fold 3 IBS: 0.22882631362449393
Fold 4 IBS: 0.23858564586599773
Fold 5 IBS: 0.22691287453600695
[I 2024-04-14 16:18:04,597] Trial 98 finished with value: 0.27472194993452975 and parameters: {'l1_ratio': 0.27882118970220404}. Best is trial 48 with value: 0.2339125815801168.
Fold 1 IBS: 0.4558304663109354
Fold 2 IBS: 0.22955308931517346
Fold 3 IBS: 0.22880834288676397
Fold 4 IBS: 0.23818861716057918
Fold 5 IBS: 0.22657932254268692
[I 2024-04-14 16:18:04,942] Trial 99 finished with value: 0.2757919676432278 and parameters: {'l1_ratio': 0.3139872365605584}. Best is trial 48 with value: 0.2339125815801168.


* Best trial for IBS:
 FrozenTrial(number=48, state=TrialState.COMPLETE, values=[0.2339125815801168], datetime_start=datetime.datetime(2024, 4, 14, 16, 17, 39, 753794), datetime_complete=datetime.datetime(2024, 4, 14, 16, 17, 40, 8470), params={'l1_ratio': 0.2761236619004883}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=48, value=None)


* Best Score for IBS:
 0.2339125815801168

In [47]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.644
train_ibs:  0.234

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [50]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.22692876841884668)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.2761236619004883)

test_ibs:  0.228

In [51]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [52]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:18:05,164] A new study created in memory with name: no-name-dd0da468-e944-4bd8-bc91-7f0e07c2f0aa

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 16:18:23,752] Trial 0 finished with value: 0.676580931087897 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5278969957081545
[I 2024-04-14 16:18:27,243] Trial 1 finished with value: 0.6145677177800518 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5579399141630901
[I 2024-04-14 16:18:29,977] Trial 2 finished with value: 0.6308271798641135 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:18:30,660] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:18:31,480] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5665236051502146
[I 2024-04-14 16:18:35,914] Trial 5 finished with value: 0.622775959906744 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:18:51,377] Trial 6 finished with value: 0.6579539434813163 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:18:52,715] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 16:18:57,196] Trial 8 finished with value: 0.49957081545064375 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5536480686695279
[I 2024-04-14 16:19:00,391] Trial 9 finished with value: 0.6104647324062334 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:19:00,765] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 16:19:10,976] Trial 11 finished with value: 0.6380986965147648 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:19:15,662] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:19:23,160] Trial 13 finished with value: 0.6817713699215188 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 13 with value: 0.6817713699215188.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:19:23,753] Trial 14 finished with value: 0.7086971170202203 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17530903073562382, 'warm_start': True}. Best is trial 14 with value: 0.7086971170202203.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7224334600760456

Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:19:24,300] Trial 15 finished with value: 0.7109217554965979 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.8147833133306369, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2047601680710191, 'warm_start': True}. Best is trial 15 with value: 0.7109217554965979.
Fold 1 C-index: 0.3804780876494024
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7936170212765957
Fold 4 C-index: 0.5836501901140685
Fold 5 C-index: 0.6351931330472103
[I 2024-04-14 16:19:24,466] Trial 16 finished with value: 0.6406031902934244 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.8484814588885312, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3777228897992014, 'warm_start': True}. Best is trial 15 with value: 0.7109217554965979.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 16:19:25,671] Trial 17 finished with value: 0.7155779596484929 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 107, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10458249310616385, 'warm_start': True}. Best is trial 17 with value: 0.7155779596484929.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.5965665236051502
[I 2024-04-14 16:19:26,778] Trial 18 finished with value: 0.6632701708683197 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09529552899934571, 'warm_start': True}. Best is trial 17 with value: 0.7155779596484929.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6394849785407726
[I 2024-04-14 16:19:27,350] Trial 19 finished with value: 0.7020033533743641 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.9945705745432233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24472699218520227, 'warm_start': True}. Best is trial 17 with value: 0.7155779596484929.
Fold 1 C-index: 0.5517928286852589
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.7489270386266095
[I 2024-04-14 16:19:27,959] Trial 20 finished with value: 0.7328268614402537 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.8574334183065578, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07885915209462858, 'warm_start': True}. Best is trial 20 with value: 0.7328268614402537.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7170212765957447
Fold 4 C-index: 0.6368821292775665
Fold 5 C-index: 0.7618025751072961
[I 2024-04-14 16:19:28,240] Trial 21 finished with value: 0.6632690568465429 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.8545770614457692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09753632164229144, 'warm_start': True}. Best is trial 20 with value: 0.7328268614402537.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 16:19:29,188] Trial 22 finished with value: 0.7608017484332823 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.8604261826280419, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08663018400156977, 'warm_start': True}. Best is trial 22 with value: 0.7608017484332823.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 16:19:30,413] Trial 23 finished with value: 0.7690660772280372 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 143, 'oob_score': True, 'max_samples': 0.9111182603715849, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06775827262990264, 'warm_start': True}. Best is trial 23 with value: 0.7690660772280372.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 16:19:31,450] Trial 24 finished with value: 0.7440693913894477 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.7068738515617914, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06115139138000203, 'warm_start': True}. Best is trial 23 with value: 0.7690660772280372.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 16:19:32,778] Trial 25 finished with value: 0.735486376947699 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 209, 'oob_score': True, 'max_samples': 0.6708962013511481, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0017411537171054953, 'warm_start': True}. Best is trial 23 with value: 0.7690660772280372.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 16:19:33,847] Trial 26 finished with value: 0.7721338228968404 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 167, 'oob_score': True, 'max_samples': 0.7144410113537528, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 16:19:35,055] Trial 27 finished with value: 0.7476542281578183 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 157, 'oob_score': True, 'max_samples': 0.5528028338055412, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04810535800309272, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 16:19:37,052] Trial 28 finished with value: 0.7592273219385095 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.8976414176869512, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13041139349208092, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7467811158798283
[I 2024-04-14 16:19:38,208] Trial 29 finished with value: 0.7370554139892926 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.7263542747152932, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18410661850855684, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 16:19:39,021] Trial 30 finished with value: 0.7767046870461737 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.6865809791097957, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03407840564085754, 'warm_start': True}. Best is trial 30 with value: 0.7767046870461737.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 16:19:40,121] Trial 31 finished with value: 0.7783309446744106 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 128, 'oob_score': True, 'max_samples': 0.6864172872570439, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03390831993382872, 'warm_start': True}. Best is trial 31 with value: 0.7783309446744106.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 16:19:40,672] Trial 32 finished with value: 0.8018360760420356 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.6860834762921624, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003201421386592976, 'warm_start': True}. Best is trial 32 with value: 0.8018360760420356.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 16:19:41,477] Trial 33 finished with value: 0.805697747786916 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.6828915837605897, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0037369805268133924, 'warm_start': True}. Best is trial 33 with value: 0.805697747786916.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:19:42,244] Trial 34 finished with value: 0.7792583288268815 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.542088684219824, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0026049394827949023, 'warm_start': True}. Best is trial 33 with value: 0.805697747786916.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:19:42,754] Trial 35 finished with value: 0.7858857842084914 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 47, 'oob_score': False, 'max_samples': 0.5555279946718963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.001812981934077619, 'warm_start': True}. Best is trial 33 with value: 0.805697747786916.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 16:19:43,056] Trial 36 finished with value: 0.8075337373378838 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.5580112420241825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 16:19:43,483] Trial 37 finished with value: 0.7911337353360948 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 38, 'oob_score': False, 'max_samples': 0.5346071202976119, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0015659966401229835, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:19:43,921] Trial 38 finished with value: 0.7097937461377273 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 77, 'oob_score': False, 'max_samples': 0.49592272736753257, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13661004358388135, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 16:19:44,294] Trial 39 finished with value: 0.7523069216002374 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.3660594506190667, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01464079927542979, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 16:19:44,738] Trial 40 finished with value: 0.7978554397858052 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 76, 'oob_score': False, 'max_samples': 0.630075046347036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.032995406893159815, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 16:19:44,994] Trial 41 finished with value: 0.7954545391890099 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6089301708150049, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03239043057256452, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 16:19:45,360] Trial 42 finished with value: 0.7900284630218224 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.6236464814282915, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04019337508392253, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 16:19:45,613] Trial 43 finished with value: 0.7968528898670126 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.5833432046167292, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0672059269880178, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 16:19:46,062] Trial 44 finished with value: 0.7956563985786629 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.592324540739651, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0698334924574171, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 16:19:46,378] Trial 45 finished with value: 0.7787873435446434 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 24, 'oob_score': False, 'max_samples': 0.6535784977460134, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11176553291943035, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.48068669527896996
[I 2024-04-14 16:19:48,572] Trial 46 finished with value: 0.6019647246667115 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.49745394949188, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01840181593129722, 'warm_start': False}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 16:19:49,153] Trial 47 finished with value: 0.7920508675682754 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 58, 'oob_score': False, 'max_samples': 0.39353418519468975, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05831156231976059, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5493562231759657
[I 2024-04-14 16:19:53,870] Trial 48 finished with value: 0.6212283825700716 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.7485926717501767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025057546057149736, 'warm_start': False}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7854077253218884
[I 2024-04-14 16:19:54,249] Trial 49 finished with value: 0.7499632029110537 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 96, 'oob_score': False, 'max_samples': 0.44115969234395064, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07830679890132161, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5278969957081545
[I 2024-04-14 16:19:54,435] Trial 50 finished with value: 0.634974394907875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.5750261144135627, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2842118200978194, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8454935622317596
[I 2024-04-14 16:19:54,871] Trial 51 finished with value: 0.8103215750536024 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 64, 'oob_score': False, 'max_samples': 0.6518086495175582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06690852785164401, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-14 16:19:55,254] Trial 52 finished with value: 0.7414732765608105 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.6411231404770097, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1564447852352071, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 16:19:55,666] Trial 53 finished with value: 0.788946918859357 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 87, 'oob_score': False, 'max_samples': 0.7860889554493278, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.123351058509179, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:19:55,953] Trial 54 finished with value: 0.782875907006704 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.5150686738177901, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053088835715916965, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:19:56,168] Trial 55 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.6361416430949213, 'max_features': None, 'min_weight_fraction_leaf': 0.3351189537838004, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 16:19:58,331] Trial 56 finished with value: 0.6034429601570507 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.5881468887320035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02222550540296471, 'warm_start': False}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8841201716738197
[I 2024-04-14 16:19:59,636] Trial 57 finished with value: 0.8086048191505656 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.7551123413533153, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08480065168490414, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:20:00,813] Trial 58 finished with value: 0.8045488801271503 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 260, 'oob_score': False, 'max_samples': 0.7600961767539095, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09207383624105397, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8927038626609443
[I 2024-04-14 16:20:07,911] Trial 59 finished with value: 0.8256990555886009 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.750348183174299, 'max_features': None, 'min_weight_fraction_leaf': 0.09298348876429541, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 16:20:45,678] Trial 60 finished with value: 0.6442124609537101 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.8199593234466896, 'max_features': None, 'min_weight_fraction_leaf': 0.0919394379990903, 'warm_start': False}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 16:20:49,727] Trial 61 finished with value: 0.8164789015817648 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.747371871755714, 'max_features': None, 'min_weight_fraction_leaf': 0.15822689229615128, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 16:20:54,661] Trial 62 finished with value: 0.8106113416299996 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.7508496958357301, 'max_features': None, 'min_weight_fraction_leaf': 0.16362054636651252, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:20:59,944] Trial 63 finished with value: 0.8115712044775746 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.7999745159041743, 'max_features': None, 'min_weight_fraction_leaf': 0.1633521636265725, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 16:21:03,671] Trial 64 finished with value: 0.7974621961967492 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.8114338741724807, 'max_features': None, 'min_weight_fraction_leaf': 0.22569702962880955, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:21:08,773] Trial 65 finished with value: 0.8071636949746172 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.7388230594642389, 'max_features': None, 'min_weight_fraction_leaf': 0.17201508827628242, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 16:21:15,979] Trial 66 finished with value: 0.8098870984103786 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.7914494461409277, 'max_features': None, 'min_weight_fraction_leaf': 0.1566811915615436, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 16:21:24,119] Trial 67 finished with value: 0.8082681460510669 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.7957500332085724, 'max_features': None, 'min_weight_fraction_leaf': 0.15586517360511226, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 16:21:29,163] Trial 68 finished with value: 0.8059464159875638 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.8874038406594102, 'max_features': None, 'min_weight_fraction_leaf': 0.18482051372177483, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:21:34,922] Trial 69 finished with value: 0.8016545869282632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.9454077003760599, 'max_features': None, 'min_weight_fraction_leaf': 0.21033678746200793, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 16:21:40,764] Trial 70 finished with value: 0.801561500108108 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.8334615557424903, 'max_features': None, 'min_weight_fraction_leaf': 0.23015303679951366, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 16:21:48,849] Trial 71 finished with value: 0.8073659882213546 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.7819388953984404, 'max_features': None, 'min_weight_fraction_leaf': 0.16118102881068472, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 16:21:58,995] Trial 72 finished with value: 0.8099629684417163 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.8068219116706009, 'max_features': None, 'min_weight_fraction_leaf': 0.15407145216490215, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:22:08,238] Trial 73 finished with value: 0.8175612834163142 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.7256003056056536, 'max_features': None, 'min_weight_fraction_leaf': 0.12137920431643712, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 16:22:16,594] Trial 74 finished with value: 0.816083889191854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.7174141590887053, 'max_features': None, 'min_weight_fraction_leaf': 0.12120920520274087, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:22:25,751] Trial 75 finished with value: 0.8136066947206648 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.7201088555626758, 'max_features': None, 'min_weight_fraction_leaf': 0.11957211852477087, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 16:22:35,317] Trial 76 finished with value: 0.7947253493979941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.7187465920082139, 'max_features': None, 'min_weight_fraction_leaf': 0.11137236004826448, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:22:43,312] Trial 77 finished with value: 0.8180614974658367 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 446, 'oob_score': False, 'max_samples': 0.7070247918663345, 'max_features': None, 'min_weight_fraction_leaf': 0.14086452948561107, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:22:44,263] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.13573153603784233, 'max_features': None, 'min_weight_fraction_leaf': 0.1254707213967799, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 16:22:52,416] Trial 79 finished with value: 0.8088334709259224 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.7055544636254668, 'max_features': None, 'min_weight_fraction_leaf': 0.1438720473833855, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:23:37,155] Trial 80 finished with value: 0.6725169483906671 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.7358185782998974, 'max_features': None, 'min_weight_fraction_leaf': 0.14042977991983294, 'warm_start': False}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 16:23:42,466] Trial 81 finished with value: 0.7854052107108721 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.6631147653826805, 'max_features': None, 'min_weight_fraction_leaf': 0.1904717547052109, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:23:54,012] Trial 82 finished with value: 0.8127192744156378 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 477, 'oob_score': False, 'max_samples': 0.7037801351415406, 'max_features': None, 'min_weight_fraction_leaf': 0.11857594294537367, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 16:24:05,507] Trial 83 finished with value: 0.8174957323136635 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.7740013537175402, 'max_features': None, 'min_weight_fraction_leaf': 0.11819437402906258, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 16:24:16,788] Trial 84 finished with value: 0.8208785121033545 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.7036421072362206, 'max_features': None, 'min_weight_fraction_leaf': 0.1042771231927323, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:24:27,490] Trial 85 finished with value: 0.8150733561874102 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.7011682877791858, 'max_features': None, 'min_weight_fraction_leaf': 0.12093318207567501, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 16:24:38,182] Trial 86 finished with value: 0.7907013482538201 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.768478848703175, 'max_features': None, 'min_weight_fraction_leaf': 0.09728336363025743, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:24:50,452] Trial 87 finished with value: 0.8159639335732953 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.6734418984579824, 'max_features': None, 'min_weight_fraction_leaf': 0.10951503187780728, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 16:25:00,399] Trial 88 finished with value: 0.8168223026720078 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.6840555102318722, 'max_features': None, 'min_weight_fraction_leaf': 0.10827303094470545, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 16:25:10,684] Trial 89 finished with value: 0.8168079889903787 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.6709910468612088, 'max_features': None, 'min_weight_fraction_leaf': 0.1045774891959252, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8884120171673819
[I 2024-04-14 16:25:21,647] Trial 90 finished with value: 0.8168658374293377 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.838525259855138, 'max_features': None, 'min_weight_fraction_leaf': 0.13447535807610542, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8927038626609443
[I 2024-04-14 16:25:32,191] Trial 91 finished with value: 0.8185062817523688 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8357079391333091, 'max_features': None, 'min_weight_fraction_leaf': 0.1364606565599496, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8969957081545065
[I 2024-04-14 16:25:44,145] Trial 92 finished with value: 0.8153188873352564 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.8775642867911538, 'max_features': None, 'min_weight_fraction_leaf': 0.10265171206389755, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8927038626609443
[I 2024-04-14 16:25:56,858] Trial 93 finished with value: 0.8177094690033648 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.8394095427190678, 'max_features': None, 'min_weight_fraction_leaf': 0.1364458020046664, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 16:26:06,601] Trial 94 finished with value: 0.8013608143135451 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.824344684327448, 'max_features': None, 'min_weight_fraction_leaf': 0.13770030876187686, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 16:26:25,392] Trial 95 finished with value: 0.7844615394050323 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9288120518629511, 'max_features': None, 'min_weight_fraction_leaf': 0.07821825258479492, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8884120171673819
[I 2024-04-14 16:26:37,338] Trial 96 finished with value: 0.8192014573314138 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.8514625493035038, 'max_features': None, 'min_weight_fraction_leaf': 0.13414945701968128, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 16:26:43,607] Trial 97 finished with value: 0.7489816005463226 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8434868595158881, 'max_features': None, 'min_weight_fraction_leaf': 0.14492739581576755, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 16:26:50,295] Trial 98 finished with value: 0.7602419102840589 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.8738054139469061, 'max_features': None, 'min_weight_fraction_leaf': 0.17836759932331153, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7376425855513308

[I 2024-04-14 16:27:35,133] A new study created in memory with name: no-name-baa4cd9f-0e92-41f2-9912-f1defb980083

Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:27:35,106] Trial 99 finished with value: 0.6869965240260854 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.9620550310373028, 'max_features': None, 'min_weight_fraction_leaf': 0.19969443485488828, 'warm_start': False}. Best is trial 59 with value: 0.8256990555886009.


* Best trial for C-index:
 FrozenTrial(number=59, state=TrialState.COMPLETE, values=[0.8256990555886009], datetime_start=datetime.datetime(2024, 4, 14, 16, 20, 0, 834642), datetime_complete=datetime.datetime(2024, 4, 14, 16, 20, 7, 909875), params={'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.750348183174299, 'max_features': None, 'min_weight_fraction_leaf': 0.09298348876429541, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=59, value=None)


* Best Score for C-index:
 0.8256990555886009

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23245200278670178
Fold 2 IBS: 0.18828390646958612
Fold 3 IBS: 0.23334467461111885
Fold 4 IBS: 0.21778957635724466
Fold 5 IBS: 0.21705588757529487
[I 2024-04-14 16:27:55,432] Trial 0 finished with value: 0.21778520955998926 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.25592429781872555
Fold 2 IBS: 0.20485946689623255
Fold 3 IBS: 0.20325171229153138
Fold 4 IBS: 0.24041573411367198
Fold 5 IBS: 0.25038826226064514
[I 2024-04-14 16:27:56,443] Trial 1 finished with value: 0.2309678946761613 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-14 16:27:57,072] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-14 16:27:59,166] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-14 16:28:01,177] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.25997212633964667
Fold 2 IBS: 0.20744288918642237
Fold 3 IBS: 0.2026423630798751
Fold 4 IBS: 0.24621003177873702
Fold 5 IBS: 0.237011163115402
[I 2024-04-14 16:28:05,193] Trial 5 finished with value: 0.2306557147000166 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.23236003007728315
Fold 2 IBS: 0.19904794428914027
Fold 3 IBS: 0.2494015884645073
Fold 4 IBS: 0.23109264114474826
Fold 5 IBS: 0.22160234738320955
[I 2024-04-14 16:28:17,034] Trial 6 finished with value: 0.22670091027177772 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24628707455739712
Fold 2 IBS: 0.22937877730479375
Fold 3 IBS: 0.22655238574634068
Fold 4 IBS: 0.24172342609580938
Fold 5 IBS: 0.23189500202696955
[I 2024-04-14 16:28:19,817] Trial 7 finished with value: 0.2351673331462621 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-14 16:28:24,240] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.25810294443230747
Fold 2 IBS: 0.2105121842174571
Fold 3 IBS: 0.20852352181394615
Fold 4 IBS: 0.24808816916849533
Fold 5 IBS: 0.24280046557837362
[I 2024-04-14 16:28:25,561] Trial 9 finished with value: 0.2336054570421159 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-14 16:28:31,219] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.22732835810482938
Fold 2 IBS: 0.19079277733443636
Fold 3 IBS: 0.2460778769636713
Fold 4 IBS: 0.2245008378197277
Fold 5 IBS: 0.2215817428686409
[I 2024-04-14 16:28:52,995] Trial 11 finished with value: 0.22205631861826114 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.9485893528798968, 'max_features': None, 'min_weight_fraction_leaf': 0.34713111632234195}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.22928305075941044
Fold 2 IBS: 0.18390550450704865
Fold 3 IBS: 0.24184864739150974
Fold 4 IBS: 0.22721384125903
Fold 5 IBS: 0.2215142296748877
[I 2024-04-14 16:29:39,728] Trial 12 finished with value: 0.2207530547183773 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.99460329717513, 'max_features': None, 'min_weight_fraction_leaf': 0.3273519300270286}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2508721712006982
Fold 2 IBS: 0.18403052310984114
Fold 3 IBS: 0.22524806555157315
Fold 4 IBS: 0.2215375179423824
Fold 5 IBS: 0.21525449299601435
[I 2024-04-14 16:30:55,269] Trial 13 finished with value: 0.21938855416010186 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.7795899048785642, 'max_features': None, 'min_weight_fraction_leaf': 0.16534086975223722}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2516414806872797
Fold 2 IBS: 0.207919811215394
Fold 3 IBS: 0.20785133968101643
Fold 4 IBS: 0.24817665948778048
Fold 5 IBS: 0.24584658651359093
[I 2024-04-14 16:31:03,828] Trial 14 finished with value: 0.2322871755170123 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.7714173351535261, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1619227173876303}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2675562059035232
Fold 2 IBS: 0.2029191070252219
Fold 3 IBS: 0.21176889229056248
Fold 4 IBS: 0.2393182562209325
Fold 5 IBS: 0.22264059167098002
[I 2024-04-14 16:32:10,123] Trial 15 finished with value: 0.22884061062224403 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.7857370506104712, 'max_features': None, 'min_weight_fraction_leaf': 9.381036713218549e-05}. Best is trial 0 with value: 0.21778520955998926.

Fold 1 IBS: 0.23154807585127796
Fold 2 IBS: 0.1879172902903685
Fold 3 IBS: 0.23486102549308419
Fold 4 IBS: 0.21616191576692922
Fold 5 IBS: 0.21737749792431385
[I 2024-04-14 16:32:44,536] Trial 16 finished with value: 0.21757316106519475 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.7160627225800851, 'max_features': None, 'min_weight_fraction_leaf': 0.2245547459670535}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.23450516079975595
Fold 2 IBS: 0.19048662251174223
Fold 3 IBS: 0.2339738904395174
Fold 4 IBS: 0.23100926323007592
Fold 5 IBS: 0.22282971688978198
[I 2024-04-14 16:33:14,367] Trial 17 finished with value: 0.22256093077417466 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.6871243940599472, 'max_features': None, 'min_weight_fraction_leaf': 0.2285855344271941}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.2544410854280207
Fold 2 IBS: 0.2117548681497262
Fold 3 IBS: 0.21266590914826713
Fold 4 IBS: 0.2556574634571033
Fold 5 IBS: 0.24120325516243565
[I 2024-04-14 16:33:19,837] Trial 18 finished with value: 0.2351445162691106 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08924573043815814}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.254758121825725
Fold 2 IBS: 0.21417743305921627
Fold 3 IBS: 0.21411301096749435
Fold 4 IBS: 0.25657503763721423
Fold 5 IBS: 0.24360746349718543
[I 2024-04-14 16:33:23,860] Trial 19 finished with value: 0.23664621339736708 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.6061595584833309, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22791611456767383}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.24668838755067432
Fold 2 IBS: 0.2323223694774956
Fold 3 IBS: 0.22952287763530818
Fold 4 IBS: 0.24145505906170697
Fold 5 IBS: 0.23037434075470525
[I 2024-04-14 16:33:29,388] Trial 20 finished with value: 0.23607260689597806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.4458729287336371, 'max_features': None, 'min_weight_fraction_leaf': 0.3007687013181908}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.2600372893651329
Fold 2 IBS: 0.18660694396206917
Fold 3 IBS: 0.22280211686218124
Fold 4 IBS: 0.22733720642931526
Fold 5 IBS: 0.2142115361440169
[I 2024-04-14 16:35:02,660] Trial 21 finished with value: 0.2221990185525431 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.7968542041631069, 'max_features': None, 'min_weight_fraction_leaf': 0.14088312030047453}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.24129503101406552
Fold 2 IBS: 0.18675635766667778
Fold 3 IBS: 0.22479751637881812
Fold 4 IBS: 0.23492723723713654
Fold 5 IBS: 0.22502053471551914
[I 2024-04-14 16:35:56,917] Trial 22 finished with value: 0.2225593354024434 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.7333978805634859, 'max_features': None, 'min_weight_fraction_leaf': 0.2049420412000723}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.26293055578958485
Fold 2 IBS: 0.19090188804613092
Fold 3 IBS: 0.22069752168236184
Fold 4 IBS: 0.23410928124121494
Fold 5 IBS: 0.21916676212266545
[I 2024-04-14 16:37:01,881] Trial 23 finished with value: 0.22556120177639158 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8558877999962695, 'max_features': None, 'min_weight_fraction_leaf': 0.12237281401289234}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.22563558164705028
Fold 2 IBS: 0.18227352293648272
Fold 3 IBS: 0.23768446836088766
Fold 4 IBS: 0.21655250003019877
Fold 5 IBS: 0.2164162038266061
[I 2024-04-14 16:37:47,413] Trial 24 finished with value: 0.2157124553602451 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8436689400574193, 'max_features': None, 'min_weight_fraction_leaf': 0.244242289743401}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.2255150380761434
Fold 2 IBS: 0.183222039023694
Fold 3 IBS: 0.24116960170707816
Fold 4 IBS: 0.21501969498726592
Fold 5 IBS: 0.21539376411213979
[I 2024-04-14 16:38:30,787] Trial 25 finished with value: 0.21606402758126425 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.8781861106771913, 'max_features': None, 'min_weight_fraction_leaf': 0.25578130205333305}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.22614078469457516
Fold 2 IBS: 0.1833696404798902
Fold 3 IBS: 0.24200095974014624
Fold 4 IBS: 0.21359509347332828
Fold 5 IBS: 0.21445882005066608
[I 2024-04-14 16:39:24,973] Trial 26 finished with value: 0.21591305968772118 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8790368112638932, 'max_features': None, 'min_weight_fraction_leaf': 0.25879667379312365}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.2520590907345142
Fold 2 IBS: 0.21140680302204304
Fold 3 IBS: 0.2135506894174242
Fold 4 IBS: 0.25062056418219003
Fold 5 IBS: 0.24445478891921904
[I 2024-04-14 16:39:35,003] Trial 27 finished with value: 0.2344183872550781 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 463, 'oob_score': True, 'max_samples': 0.8959637112797967, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2611199851941091}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.24813242490959445
Fold 2 IBS: 0.20755477056701319
Fold 3 IBS: 0.21299031512560426
Fold 4 IBS: 0.246653939670713
Fold 5 IBS: 0.24277921161361501
[I 2024-04-14 16:39:45,195] Trial 28 finished with value: 0.231622132377308 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.957086450216675, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3146636471285875}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.2342715209035425
Fold 2 IBS: 0.20354279932350952
Fold 3 IBS: 0.25561389987555283
Fold 4 IBS: 0.23678875016407627
Fold 5 IBS: 0.22653209465985072
[I 2024-04-14 16:40:13,880] Trial 29 finished with value: 0.23134981298530638 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.8498266742400898, 'max_features': None, 'min_weight_fraction_leaf': 0.37494346942158263}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.22979863524090197
Fold 2 IBS: 0.18212512500007025
Fold 3 IBS: 0.23579662743958177
Fold 4 IBS: 0.21698273620013098
Fold 5 IBS: 0.21134554976530948
[I 2024-04-14 16:40:53,883] Trial 30 finished with value: 0.21520973472919888 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9975403100242013, 'max_features': None, 'min_weight_fraction_leaf': 0.2599744768668571}. Best is trial 30 with value: 0.21520973472919888.
Fold 1 IBS: 0.22767673562456642
Fold 2 IBS: 0.18250151839395365
Fold 3 IBS: 0.2346862111366068
Fold 4 IBS: 0.21417509966385215
Fold 5 IBS: 0.21210846579813294
[I 2024-04-14 16:41:40,813] Trial 31 finished with value: 0.2142296061234224 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.9626750941879966, 'max_features': None, 'min_weight_fraction_leaf': 0.26115274999390314}. Best is trial 31 with value: 0.2142296061234224.

Fold 1 IBS: 0.223671117899065
Fold 2 IBS: 0.18242513973526725
Fold 3 IBS: 0.2389733570256732
Fold 4 IBS: 0.21132681423071092
Fold 5 IBS: 0.2129200403370242
[I 2024-04-14 16:42:24,833] Trial 32 finished with value: 0.2138632938455481 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9673759674409311, 'max_features': None, 'min_weight_fraction_leaf': 0.27417727195073677}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2573672754798652
Fold 2 IBS: 0.1902152831375234
Fold 3 IBS: 0.2272585883751577
Fold 4 IBS: 0.22496428138050273
Fold 5 IBS: 0.2133258411787376
[I 2024-04-14 16:43:12,356] Trial 33 finished with value: 0.2226262539103573 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.9964442664551478, 'max_features': None, 'min_weight_fraction_leaf': 0.1855920796843306}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22522414670411478
Fold 2 IBS: 0.18326674769112986
Fold 3 IBS: 0.2387346895291688
Fold 4 IBS: 0.2137747409250764
Fold 5 IBS: 0.2165670671101404
[I 2024-04-14 16:43:34,899] Trial 34 finished with value: 0.21551347839192606 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.9279710918176601, 'max_features': None, 'min_weight_fraction_leaf': 0.2867300145495075}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.251659132950299
Fold 2 IBS: 0.21573975281463745
Fold 3 IBS: 0.21830007825376807
Fold 4 IBS: 0.2471377111202043
Fold 5 IBS: 0.24099856704491995
[I 2024-04-14 16:43:40,239] Trial 35 finished with value: 0.2347670484367658 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9536728448516014, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3909359479764509}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2334362354514201
Fold 2 IBS: 0.21078608255075681
Fold 3 IBS: 0.2561650954496425
Fold 4 IBS: 0.2412311316030896
Fold 5 IBS: 0.23143582224241235
[I 2024-04-14 16:43:49,862] Trial 36 finished with value: 0.2346108734594643 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.9283967702859293, 'max_features': None, 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24997063012030987
Fold 2 IBS: 0.2078386271594619
Fold 3 IBS: 0.20989448943460737
Fold 4 IBS: 0.24318967810983624
Fold 5 IBS: 0.238822753205723
[I 2024-04-14 16:43:55,160] Trial 37 finished with value: 0.2299432356059877 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.9519656907534663, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2901382904665285}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2242535688456211
Fold 2 IBS: 0.1835976049907044
Fold 3 IBS: 0.24006744858339077
Fold 4 IBS: 0.2235128017867808
Fold 5 IBS: 0.22345167433335356
[I 2024-04-14 16:44:18,290] Trial 38 finished with value: 0.21897661970797017 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.9965207390496469, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23157459496934288
Fold 2 IBS: 0.18765821400732335
Fold 3 IBS: 0.23782361687183054
Fold 4 IBS: 0.22923755805304355
Fold 5 IBS: 0.2226986259210817
[I 2024-04-14 16:44:45,190] Trial 39 finished with value: 0.22179852196452438 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 315, 'oob_score': True, 'max_samples': 0.8226899286526288, 'max_features': None, 'min_weight_fraction_leaf': 0.27840143846809673}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24772435188079012
Fold 2 IBS: 0.23218742086626878
Fold 3 IBS: 0.23060758736791892
Fold 4 IBS: 0.24175508770731288
Fold 5 IBS: 0.23204474443418183
[I 2024-04-14 16:44:45,866] Trial 40 finished with value: 0.2368638384512945 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.16382436256125943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36813487751721063}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22646081504264082
Fold 2 IBS: 0.18352119126570954
Fold 3 IBS: 0.23607995696737102
Fold 4 IBS: 0.21251526662938883
Fold 5 IBS: 0.21424323342983828
[I 2024-04-14 16:45:24,161] Trial 41 finished with value: 0.2145640926669897 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9105281334242562, 'max_features': None, 'min_weight_fraction_leaf': 0.24475563110472928}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22512255917446478
Fold 2 IBS: 0.18727107285974057
Fold 3 IBS: 0.23758193335679487
Fold 4 IBS: 0.22054856422751146
Fold 5 IBS: 0.21988197787741465
[I 2024-04-14 16:45:54,880] Trial 42 finished with value: 0.21808122149918527 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.9045942155546295, 'max_features': None, 'min_weight_fraction_leaf': 0.293296028878736}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22785829875013436
Fold 2 IBS: 0.1842888166183638
Fold 3 IBS: 0.23563786567766842
Fold 4 IBS: 0.21517434047682332
Fold 5 IBS: 0.21460776387587385
[I 2024-04-14 16:46:26,672] Trial 43 finished with value: 0.21551341707977273 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 226, 'oob_score': True, 'max_samples': 0.9160948796372946, 'max_features': None, 'min_weight_fraction_leaf': 0.2388357123656987}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23810518869034208
Fold 2 IBS: 0.1843721717295676
Fold 3 IBS: 0.23342725534028747
Fold 4 IBS: 0.21779527198626983
Fold 5 IBS: 0.21338570246212432
[I 2024-04-14 16:47:12,401] Trial 44 finished with value: 0.21741711804171823 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9988079160976218, 'max_features': None, 'min_weight_fraction_leaf': 0.23133379029564993}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24904499381879106
Fold 2 IBS: 0.20204509565526388
Fold 3 IBS: 0.20022838751714556
Fold 4 IBS: 0.23851054900878854
Fold 5 IBS: 0.23279491046703293
[I 2024-04-14 16:47:16,853] Trial 45 finished with value: 0.22452478729340442 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.9588472996756688, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18865904360845076}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24662415636936666
Fold 2 IBS: 0.23216017809371517
Fold 3 IBS: 0.22953538377216462
Fold 4 IBS: 0.24149330032507219
Fold 5 IBS: 0.23025831018946888
[I 2024-04-14 16:47:21,527] Trial 46 finished with value: 0.23601426574995749 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.8112705796698418, 'max_features': None, 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.25552189189917673
Fold 2 IBS: 0.21243741065140562
Fold 3 IBS: 0.20983624353493957
Fold 4 IBS: 0.2501169181827278
Fold 5 IBS: 0.24162763102811574
[I 2024-04-14 16:47:25,655] Trial 47 finished with value: 0.2339080190592731 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.5997619529984042, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20625108164370973}. Best is trial 32 with value: 0.2138632938455481.

Fold 1 IBS: 0.23136140224576346
Fold 2 IBS: 0.1874927380948624
Fold 3 IBS: 0.2417750554443432
Fold 4 IBS: 0.2265069844402473
Fold 5 IBS: 0.2218959262967509
[I 2024-04-14 16:47:55,978] Trial 48 finished with value: 0.22180642130439346 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.9047670799898727, 'max_features': None, 'min_weight_fraction_leaf': 0.31310643491678164}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23542420632037062
Fold 2 IBS: 0.21022618815946087
Fold 3 IBS: 0.24786241576097612
Fold 4 IBS: 0.24693634633915879
Fold 5 IBS: 0.2275366959349153
[I 2024-04-14 16:48:04,150] Trial 49 finished with value: 0.23359717050297632 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 126, 'oob_score': True, 'max_samples': 0.7434493023402162, 'max_features': None, 'min_weight_fraction_leaf': 0.34264283218926966}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23364784563499447
Fold 2 IBS: 0.18098882068519936
Fold 3 IBS: 0.2350992433083844
Fold 4 IBS: 0.21486677801910797
Fold 5 IBS: 0.2122163265393306
[I 2024-04-14 16:48:38,700] Trial 50 finished with value: 0.21536380283740336 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.966289849683488, 'max_features': None, 'min_weight_fraction_leaf': 0.24268176580480855}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22436028360824464
Fold 2 IBS: 0.18390356277663142
Fold 3 IBS: 0.24040787615783354
Fold 4 IBS: 0.2104444204732873
Fold 5 IBS: 0.2135145412249106
[I 2024-04-14 16:49:16,895] Trial 51 finished with value: 0.2145261368481815 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.9661981965193748, 'max_features': None, 'min_weight_fraction_leaf': 0.27303633084997875}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2252632186123346
Fold 2 IBS: 0.18280170060531284
Fold 3 IBS: 0.2396686796063755
Fold 4 IBS: 0.21225825839404486
Fold 5 IBS: 0.21297157585520618
[I 2024-04-14 16:49:53,887] Trial 52 finished with value: 0.2145926866146548 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.9702010352389128, 'max_features': None, 'min_weight_fraction_leaf': 0.26818547406558596}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22521714505468243
Fold 2 IBS: 0.182881821769254
Fold 3 IBS: 0.23887251200621484
Fold 4 IBS: 0.21098252365766934
Fold 5 IBS: 0.21218782440315603
[I 2024-04-14 16:50:29,532] Trial 53 finished with value: 0.2140283653781953 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': None, 'min_weight_fraction_leaf': 0.2659202981850255}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2288718138261306
Fold 2 IBS: 0.18971765755649445
Fold 3 IBS: 0.2436361411190432
Fold 4 IBS: 0.22404777390437705
Fold 5 IBS: 0.22115647006408712
[I 2024-04-14 16:50:56,910] Trial 54 finished with value: 0.22148597129402647 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.8733859823018522, 'max_features': None, 'min_weight_fraction_leaf': 0.3170010700434733}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24707867175507572
Fold 2 IBS: 0.20400595446700628
Fold 3 IBS: 0.20812199158224806
Fold 4 IBS: 0.24190537559582556
Fold 5 IBS: 0.23834032306907496
[I 2024-04-14 16:51:05,386] Trial 55 finished with value: 0.22789046329384616 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.9265797304840281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27178576234176444}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23358367222638146
Fold 2 IBS: 0.18201458388431307
Fold 3 IBS: 0.23354682388930173
Fold 4 IBS: 0.21827492745636595
Fold 5 IBS: 0.2174501839109653
[I 2024-04-14 16:51:38,682] Trial 56 finished with value: 0.2169740382734655 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.8271936729281781, 'max_features': None, 'min_weight_fraction_leaf': 0.21285363084866435}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24664286749698494
Fold 2 IBS: 0.23225796139026453
Fold 3 IBS: 0.23001805269887293
Fold 4 IBS: 0.2412163600405613
Fold 5 IBS: 0.23037050773431045
[I 2024-04-14 16:51:42,955] Trial 57 finished with value: 0.23610114987219885 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 253, 'oob_score': True, 'max_samples': 0.26646127666984304, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17410739253633356}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.21999582778399657
Fold 2 IBS: 0.18387448686713245
Fold 3 IBS: 0.2408870330246256
Fold 4 IBS: 0.2166454642557191
Fold 5 IBS: 0.21730499351649227
[I 2024-04-14 16:52:17,897] Trial 58 finished with value: 0.2157415610895932 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.9686958687236764, 'max_features': None, 'min_weight_fraction_leaf': 0.30665516095412265}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24647772834133322
Fold 2 IBS: 0.23233396372684292
Fold 3 IBS: 0.2294105260186355
Fold 4 IBS: 0.24141830856202007
Fold 5 IBS: 0.23032989167367704
[I 2024-04-14 16:52:20,699] Trial 59 finished with value: 0.23599408366450175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.46177802758610575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.276444308199004}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23433608338988485
Fold 2 IBS: 0.18086918993235046
Fold 3 IBS: 0.23079999563465167
Fold 4 IBS: 0.21893548105514982
Fold 5 IBS: 0.21460155169943457
[I 2024-04-14 16:52:52,142] Trial 60 finished with value: 0.21590846034229427 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.88571367758948, 'max_features': None, 'min_weight_fraction_leaf': 0.21876290259338138}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2271430274533492
Fold 2 IBS: 0.1825162975453381
Fold 3 IBS: 0.23705040332469834
Fold 4 IBS: 0.21597892749853137
Fold 5 IBS: 0.21278677650981948
[I 2024-04-14 16:53:30,486] Trial 61 finished with value: 0.21509508646634729 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.9830894754716849, 'max_features': None, 'min_weight_fraction_leaf': 0.2553034187460287}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2292111984043628
Fold 2 IBS: 0.18182025355984485
Fold 3 IBS: 0.2362968817681646
Fold 4 IBS: 0.21421475225136127
Fold 5 IBS: 0.21149289369260849
[I 2024-04-14 16:54:06,373] Trial 62 finished with value: 0.21460719593526845 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.9708671292273213, 'max_features': None, 'min_weight_fraction_leaf': 0.243826357699726}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.26397277962706595
Fold 2 IBS: 0.19043375797576154
Fold 3 IBS: 0.22492565723072697
Fold 4 IBS: 0.23088387847598388
Fold 5 IBS: 0.2172622642768575
[I 2024-04-14 16:55:02,974] Trial 63 finished with value: 0.22549566751727917 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.9279480291246802, 'max_features': None, 'min_weight_fraction_leaf': 0.14120968912579035}. Best is trial 32 with value: 0.2138632938455481.

Fold 1 IBS: 0.23011155909129694
Fold 2 IBS: 0.18057364325153813
Fold 3 IBS: 0.23750151803668482
Fold 4 IBS: 0.21433948253554103
Fold 5 IBS: 0.21274097244510462
[I 2024-04-14 16:55:34,082] Trial 64 finished with value: 0.2150534350720331 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.9368121127684691, 'max_features': None, 'min_weight_fraction_leaf': 0.24195064098385735}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22994947133324334
Fold 2 IBS: 0.1928070595691341
Fold 3 IBS: 0.24608508712178995
Fold 4 IBS: 0.22580322695561086
Fold 5 IBS: 0.2205885428532394
[I 2024-04-14 16:55:58,960] Trial 65 finished with value: 0.2230466775666035 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.8670083844909762, 'max_features': None, 'min_weight_fraction_leaf': 0.32908421267758453}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22282130602573708
Fold 2 IBS: 0.1825701777954383
Fold 3 IBS: 0.24054010901980605
Fold 4 IBS: 0.21149946893211913
Fold 5 IBS: 0.21290931251383843
[I 2024-04-14 16:56:35,292] Trial 66 finished with value: 0.21406807485738782 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.9739982448849115, 'max_features': None, 'min_weight_fraction_leaf': 0.27071128725769533}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22590163939661623
Fold 2 IBS: 0.18763036929293417
Fold 3 IBS: 0.23854879484973543
Fold 4 IBS: 0.22056476346670456
Fold 5 IBS: 0.22367179941618776
[I 2024-04-14 16:57:06,770] Trial 67 finished with value: 0.21926347328443568 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.9017852762499756, 'max_features': None, 'min_weight_fraction_leaf': 0.29638943195223827}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23136468046650185
Fold 2 IBS: 0.19058356934507797
Fold 3 IBS: 0.23833656743867954
Fold 4 IBS: 0.2260246145182696
Fold 5 IBS: 0.22338377590240932
[I 2024-04-14 16:57:29,109] Trial 68 finished with value: 0.22193864153418766 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.7696006508928359, 'max_features': None, 'min_weight_fraction_leaf': 0.26921258161170186}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2527256482936472
Fold 2 IBS: 0.21679849351270158
Fold 3 IBS: 0.21558977655347453
Fold 4 IBS: 0.24870257487026431
Fold 5 IBS: 0.24051841598268586
[I 2024-04-14 16:57:33,580] Trial 69 finished with value: 0.2348669818425547 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 241, 'oob_score': True, 'max_samples': 0.8533920767500149, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3499623676247436}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.25019298453625666
Fold 2 IBS: 0.20750360226472647
Fold 3 IBS: 0.20963562065872504
Fold 4 IBS: 0.24625738052286109
Fold 5 IBS: 0.245388802984381
[I 2024-04-14 16:57:39,944] Trial 70 finished with value: 0.23179567819339003 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.9455441938181584, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19781823294342465}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23916946073214723
Fold 2 IBS: 0.1832292263840008
Fold 3 IBS: 0.23266918697690725
Fold 4 IBS: 0.21704804409245781
Fold 5 IBS: 0.2114516013799994
[I 2024-04-14 16:58:24,422] Trial 71 finished with value: 0.2167135039131025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.9723894444805646, 'max_features': None, 'min_weight_fraction_leaf': 0.22155373862891511}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22202847435988357
Fold 2 IBS: 0.18246590811570426
Fold 3 IBS: 0.24166105453781217
Fold 4 IBS: 0.212036850127337
Fold 5 IBS: 0.21320739007819955
[I 2024-04-14 16:59:16,697] Trial 72 finished with value: 0.2142799354437873 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.9699475769300351, 'max_features': None, 'min_weight_fraction_leaf': 0.28091267570651296}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22381886258218625
Fold 2 IBS: 0.18341926141721807
Fold 3 IBS: 0.23660704072083516
Fold 4 IBS: 0.212065367907901
Fold 5 IBS: 0.2141596670219456
[I 2024-04-14 16:59:50,215] Trial 73 finished with value: 0.21401403993001722 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 209, 'oob_score': True, 'max_samples': 0.9437791774466985, 'max_features': None, 'min_weight_fraction_leaf': 0.2821774369800084}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22477243133843341
Fold 2 IBS: 0.18774509568370273
Fold 3 IBS: 0.23965261185226014
Fold 4 IBS: 0.21922686154498106
Fold 5 IBS: 0.21886501300305408
[I 2024-04-14 17:00:16,848] Trial 74 finished with value: 0.21805240268448628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.895983842618794, 'max_features': None, 'min_weight_fraction_leaf': 0.28336470892687904}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22159535901907498
Fold 2 IBS: 0.18203242370099715
Fold 3 IBS: 0.2396122755727472
Fold 4 IBS: 0.2119122627533289
Fold 5 IBS: 0.22253785258960063
[I 2024-04-14 17:00:24,713] Trial 75 finished with value: 0.21553803472714977 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.9389659866027312, 'max_features': None, 'min_weight_fraction_leaf': 0.3050734094630049}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2264441828875602
Fold 2 IBS: 0.1853863661466383
Fold 3 IBS: 0.2359088651478127
Fold 4 IBS: 0.213294084617616
Fold 5 IBS: 0.21449974952765222
[I 2024-04-14 17:00:48,481] Trial 76 finished with value: 0.2151066496654559 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.9176234080585466, 'max_features': None, 'min_weight_fraction_leaf': 0.25300132487456545}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22821719305891985
Fold 2 IBS: 0.19508870828251132
Fold 3 IBS: 0.24578664455005625
Fold 4 IBS: 0.23032276258951812
Fold 5 IBS: 0.22195983270626185
[I 2024-04-14 17:01:04,805] Trial 77 finished with value: 0.2242750282374535 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.8309240388435434, 'max_features': None, 'min_weight_fraction_leaf': 0.3232036043987994}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22380265214933034
Fold 2 IBS: 0.1828661444783246
Fold 3 IBS: 0.23976935208368666
Fold 4 IBS: 0.21451776173442463
Fold 5 IBS: 0.21232014327526896
[I 2024-04-14 17:01:41,383] Trial 78 finished with value: 0.21465521074420707 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.9974834884011105, 'max_features': None, 'min_weight_fraction_leaf': 0.285120853971619}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24662475161103709
Fold 2 IBS: 0.23221194862348535
Fold 3 IBS: 0.2293559897432884
Fold 4 IBS: 0.24148847398075313
Fold 5 IBS: 0.23037769738743746
[I 2024-04-14 17:01:44,175] Trial 79 finished with value: 0.23601177226920028 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.5136803098501763, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2997540729188399}. Best is trial 32 with value: 0.2138632938455481.

Fold 1 IBS: 0.23374541142463764
Fold 2 IBS: 0.19941476694876598
Fold 3 IBS: 0.24370640781635464
Fold 4 IBS: 0.23069544004770481
Fold 5 IBS: 0.2221664668271361
[I 2024-04-14 17:02:03,825] Trial 80 finished with value: 0.22594569861291985 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.6585925147157417, 'max_features': None, 'min_weight_fraction_leaf': 0.2649590538103387}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22301744452662423
Fold 2 IBS: 0.18261690178298304
Fold 3 IBS: 0.24046916847175354
Fold 4 IBS: 0.21144194863813523
Fold 5 IBS: 0.21301702675170428
[I 2024-04-14 17:02:36,282] Trial 81 finished with value: 0.21411249803424007 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 273, 'oob_score': True, 'max_samples': 0.9753152468491701, 'max_features': None, 'min_weight_fraction_leaf': 0.2752380404753649}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23432065838648555
Fold 2 IBS: 0.17935299106705255
Fold 3 IBS: 0.23287366162210554
Fold 4 IBS: 0.21357871998202235
Fold 5 IBS: 0.2127544406967326
[I 2024-04-14 17:03:13,967] Trial 82 finished with value: 0.21457609435087974 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.9421283607559255, 'max_features': None, 'min_weight_fraction_leaf': 0.2317891236270332}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2217481350639258
Fold 2 IBS: 0.1833441422718802
Fold 3 IBS: 0.24075077787234164
Fold 4 IBS: 0.21240573900177895
Fold 5 IBS: 0.212962145560917
[I 2024-04-14 17:03:41,223] Trial 83 finished with value: 0.21424218795416872 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.975128242811779, 'max_features': None, 'min_weight_fraction_leaf': 0.2805682898149209}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2303654148623288
Fold 2 IBS: 0.18632824544920742
Fold 3 IBS: 0.2418858668034646
Fold 4 IBS: 0.22539197899863944
Fold 5 IBS: 0.22219697313636344
[I 2024-04-14 17:04:02,520] Trial 84 finished with value: 0.2212336958500007 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.976393308446703, 'max_features': None, 'min_weight_fraction_leaf': 0.34127480974218166}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2217260340853898
Fold 2 IBS: 0.18277239975247972
Fold 3 IBS: 0.23833388730571414
Fold 4 IBS: 0.21017761467579527
Fold 5 IBS: 0.21345934539251293
[I 2024-04-14 17:04:31,035] Trial 85 finished with value: 0.21329385624237837 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.9536038002194676, 'max_features': None, 'min_weight_fraction_leaf': 0.28476239825926203}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.23346654290971627
Fold 2 IBS: 0.2002991033036751
Fold 3 IBS: 0.2512808526691761
Fold 4 IBS: 0.2347653219215522
Fold 5 IBS: 0.22181496462461447
[I 2024-04-14 17:04:48,808] Trial 86 finished with value: 0.2283253570857468 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.878162296740506, 'max_features': None, 'min_weight_fraction_leaf': 0.3634165889388582}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.2223728654927925
Fold 2 IBS: 0.18294920002029924
Fold 3 IBS: 0.2389860108327765
Fold 4 IBS: 0.21502599980642048
Fold 5 IBS: 0.21482469988941083
[I 2024-04-14 17:05:17,830] Trial 87 finished with value: 0.21483175520833991 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.9460445626426491, 'max_features': None, 'min_weight_fraction_leaf': 0.29153530938454547}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.25189061751540737
Fold 2 IBS: 0.21341558529621427
Fold 3 IBS: 0.2142420257944259
Fold 4 IBS: 0.2482136617352358
Fold 5 IBS: 0.24599208057977232
[I 2024-04-14 17:05:21,898] Trial 88 finished with value: 0.23475079418421113 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.9990689395046066, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31471651143310175}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.2500584415952907
Fold 2 IBS: 0.2031681904585751
Fold 3 IBS: 0.20589935356803593
Fold 4 IBS: 0.2415552908214951
Fold 5 IBS: 0.23589468400039715
[I 2024-04-14 17:05:26,013] Trial 89 finished with value: 0.22731519208875878 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.9170021204025709, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.25666952715359104}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.22122037857176746
Fold 2 IBS: 0.18393521442358685
Fold 3 IBS: 0.2391260037900019
Fold 4 IBS: 0.21395254322224747
Fold 5 IBS: 0.2134193298258829
[I 2024-04-14 17:05:58,218] Trial 90 finished with value: 0.2143306939666973 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.9820252833893551, 'max_features': None, 'min_weight_fraction_leaf': 0.2818679584030278}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.21897748548504423
Fold 2 IBS: 0.18188133545279256
Fold 3 IBS: 0.24000841253595037
Fold 4 IBS: 0.21074024798269958
Fold 5 IBS: 0.21382333454548527
[I 2024-04-14 17:06:22,522] Trial 91 finished with value: 0.21308616320039436 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9824332970054127, 'max_features': None, 'min_weight_fraction_leaf': 0.296758543375246}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.22239428604592235
Fold 2 IBS: 0.18362529902872812
Fold 3 IBS: 0.2380366548108467
Fold 4 IBS: 0.21518991075013066
Fold 5 IBS: 0.21578530509812716
[I 2024-04-14 17:06:41,790] Trial 92 finished with value: 0.21500629114675102 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.9578561789486436, 'max_features': None, 'min_weight_fraction_leaf': 0.30080999173299644}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.22288421426915914
Fold 2 IBS: 0.18356297300725574
Fold 3 IBS: 0.24008642933734997
Fold 4 IBS: 0.21300636044035706
Fold 5 IBS: 0.21479301188940397
[I 2024-04-14 17:07:10,681] Trial 93 finished with value: 0.21486659778870515 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 311, 'oob_score': True, 'max_samples': 0.9355442766768195, 'max_features': None, 'min_weight_fraction_leaf': 0.2800908308674908}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.28145174414363894
Fold 2 IBS: 0.19567185164243353
Fold 3 IBS: 0.2208118929008425
Fold 4 IBS: 0.2577007636885228
Fold 5 IBS: 0.23128096437104487
[I 2024-04-14 17:08:26,958] Trial 94 finished with value: 0.2373834433492965 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.8922990907187959, 'max_features': None, 'min_weight_fraction_leaf': 0.03451598429298541}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.2287195348815148
Fold 2 IBS: 0.185333284394746
Fold 3 IBS: 0.2407456148569622
Fold 4 IBS: 0.22444917263154276
Fold 5 IBS: 0.22301098555165416
[I 2024-04-14 17:08:43,231] Trial 95 finished with value: 0.22045171846328399 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.9810881228054685, 'max_features': None, 'min_weight_fraction_leaf': 0.3378600017645348}. Best is trial 91 with value: 0.21308616320039436.

Fold 1 IBS: 0.23083721945133412
Fold 2 IBS: 0.18442690744496573
Fold 3 IBS: 0.2372912055911599
Fold 4 IBS: 0.22822622495739184
Fold 5 IBS: 0.22366315254862057
[I 2024-04-14 17:08:57,560] Trial 96 finished with value: 0.22088894199869444 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 231, 'oob_score': True, 'max_samples': 0.9522685325324347, 'max_features': None, 'min_weight_fraction_leaf': 0.32080383117786954}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.2265678317463007
Fold 2 IBS: 0.18314595561796107
Fold 3 IBS: 0.2376073017283759
Fold 4 IBS: 0.21337826003109
Fold 5 IBS: 0.21787901230329237
[I 2024-04-14 17:09:09,556] Trial 97 finished with value: 0.21571567228540403 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.9189184529013809, 'max_features': None, 'min_weight_fraction_leaf': 0.2643468339626171}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.22122707712088582
Fold 2 IBS: 0.1831407811386645
Fold 3 IBS: 0.23729164843763267
Fold 4 IBS: 0.21684432910179788
Fold 5 IBS: 0.2181910343145583
[I 2024-04-14 17:09:33,349] Trial 98 finished with value: 0.21533897402270785 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.9822414266350423, 'max_features': None, 'min_weight_fraction_leaf': 0.3083148619586106}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.2469573580849604
Fold 2 IBS: 0.23227887605176312
Fold 3 IBS: 0.2296871483873879
Fold 4 IBS: 0.2412464104562029
Fold 5 IBS: 0.23029875993927082
[I 2024-04-14 17:09:37,203] Trial 99 finished with value: 0.236093710583917 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.3740305964247548, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2907257900715026}. Best is trial 91 with value: 0.21308616320039436.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.21308616320039436], datetime_start=datetime.datetime(2024, 4, 14, 17, 5, 58, 284348), datetime_complete=datetime.datetime(2024, 4, 14, 17, 6, 22, 521426), params={'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9824332970054127, 'max_features': None, 'min_weight_fraction_leaf': 0.296758543375246}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=91, value=None)


* Best Score for IBS:
 0.21308616320039436

In [53]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [54]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.213

#### Test

In [55]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [56]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=10,
                     max_samples=0.750348183174299, min_samples_leaf=2,
                     min_samples_split=16,
                     min_weight_fraction_leaf=0.09298348876429541,
                     n_estimators=267, random_state=123, warm_start=True)

test_cindex:  0.516

RandomSurvivalForest(max_depth=5, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9824332970054127, min_samples_split=10,
                     min_weight_fraction_leaf=0.296758543375246,
                     n_estimators=236, oob_score=True, random_state=123)

test_ibs:  0.258

In [57]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [58]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [59]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 17:09:58,003] A new study created in memory with name: no-name-9ad15175-278c-4899-ae2b-306527a5cceb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 17:09:59,439] Trial 0 finished with value: 0.6917221983343996 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6917221983343996.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:04,073] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6917221983343996.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5321888412017167
[I 2024-04-14 17:10:11,071] Trial 2 finished with value: 0.5962293873367364 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6917221983343996.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 17:10:11,677] Trial 3 finished with value: 0.7116124583117144 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:13,922] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:16,513] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 17:10:17,429] Trial 6 finished with value: 0.6995413025653047 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.4866920152091255
Fold 5 C-index: 0.44206008583690987
[I 2024-04-14 17:10:19,655] Trial 7 finished with value: 0.5323002394051266 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 17:10:19,869] Trial 8 finished with value: 0.7123582035090831 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.4206008583690987
[I 2024-04-14 17:10:24,371] Trial 9 finished with value: 0.5601421749368429 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:24,663] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.26413466171660194, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 17:10:24,947] Trial 11 finished with value: 0.6860067758400761 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6437768240343348
[I 2024-04-14 17:10:25,366] Trial 12 finished with value: 0.6935371374703161 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 147, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-14 17:10:25,753] Trial 13 finished with value: 0.682899730638463 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:25,942] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 24, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:26,478] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 193, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.40889055344541997}. Best is trial 8 with value: 0.7123582035090831.

Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6394849785407726
[I 2024-04-14 17:10:26,836] Trial 16 finished with value: 0.678961934888575 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.884183184043622, 'min_weight_fraction_leaf': 0.10581506507448754}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:27,297] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.37217752523657055, 'min_weight_fraction_leaf': 0.19947678741058694}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 17:10:30,201] Trial 18 finished with value: 0.5851562203756214 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6674013857794929, 'min_weight_fraction_leaf': 0.0023155280568105674}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5665236051502146
[I 2024-04-14 17:10:30,538] Trial 19 finished with value: 0.639680291939225 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 61, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.35588501080184637}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 17:10:30,704] Trial 20 finished with value: 0.7286697682430041 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7140167187076433, 'min_weight_fraction_leaf': 0.28881891871571913}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5930232558139535
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6931330472103004
[I 2024-04-14 17:10:30,852] Trial 21 finished with value: 0.6281398340612074 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 1, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.72756654854298, 'min_weight_fraction_leaf': 0.2803571345451082}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5622317596566524
[I 2024-04-14 17:10:31,320] Trial 22 finished with value: 0.6463647316394202 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 126, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5949128885273827, 'min_weight_fraction_leaf': 0.21042356171274518}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-14 17:10:31,581] Trial 23 finished with value: 0.6393477164536583 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 20, 'n_estimators': 42, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.838041538709398, 'min_weight_fraction_leaf': 0.3244245165936095}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 17:10:32,166] Trial 24 finished with value: 0.6624368746572411 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6696269191810152, 'min_weight_fraction_leaf': 0.07834890281902418}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6266094420600858
[I 2024-04-14 17:10:32,486] Trial 25 finished with value: 0.6530529611997009 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 80, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9355023621313151, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.48406374501992033
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.2936170212765957
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.4742489270386266
[I 2024-04-14 17:10:32,779] Trial 26 finished with value: 0.4432795042637509 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 10, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7635558184229367, 'min_weight_fraction_leaf': 0.28408553405121756}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:33,057] Trial 27 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 52, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6191211952156661, 'min_weight_fraction_leaf': 0.37494346942158263}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.5836909871244635
[I 2024-04-14 17:10:33,639] Trial 28 finished with value: 0.6872248373859204 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4809640343327969, 'min_weight_fraction_leaf': 0.1961828142250625}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5836909871244635
[I 2024-04-14 17:10:34,061] Trial 29 finished with value: 0.6455250442442004 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 123, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7417740935442027, 'min_weight_fraction_leaf': 0.12619621560869665}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:34,736] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8156771314324496, 'min_weight_fraction_leaf': 0.4834576132281108}. Best is trial 20 with value: 0.7286697682430041.

Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 17:10:35,625] Trial 31 finished with value: 0.6801145932920232 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5225620293165905, 'min_weight_fraction_leaf': 0.0017285001202470562}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6437768240343348
[I 2024-04-14 17:10:36,550] Trial 32 finished with value: 0.6731579798996079 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.40903497082495127, 'min_weight_fraction_leaf': 0.04964430400379123}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6180257510729614
[I 2024-04-14 17:10:37,744] Trial 33 finished with value: 0.6707561487837669 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 496, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5725190768430576, 'min_weight_fraction_leaf': 0.09286432163882712}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5665236051502146
[I 2024-04-14 17:10:39,432] Trial 34 finished with value: 0.651579065949819 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 311, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.692312467902129, 'min_weight_fraction_leaf': 0.2580540326462687}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9098712446351931
[I 2024-04-14 17:10:41,326] Trial 35 finished with value: 0.8273038477014083 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6139772671629777, 'min_weight_fraction_leaf': 0.031778205287574995}. Best is trial 35 with value: 0.8273038477014083.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6437768240343348
[I 2024-04-14 17:10:50,310] Trial 36 finished with value: 0.6480077574259477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6351952857540998, 'min_weight_fraction_leaf': 0.03700974784326052}. Best is trial 35 with value: 0.8273038477014083.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9055793991416309
[I 2024-04-14 17:10:52,025] Trial 37 finished with value: 0.8314649783704071 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9232804028192897, 'min_weight_fraction_leaf': 0.07315854643139896}. Best is trial 37 with value: 0.8314649783704071.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9184549356223176
[I 2024-04-14 17:10:54,486] Trial 38 finished with value: 0.8435364145387766 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.0720411751470438}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6094420600858369
[I 2024-04-14 17:11:08,717] Trial 39 finished with value: 0.6593295748203326 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 395, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9312981316255384, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-14 17:11:12,281] Trial 40 finished with value: 0.8372310545873379 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8565277718167947, 'min_weight_fraction_leaf': 0.025228712838995082}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-14 17:11:16,281] Trial 41 finished with value: 0.8427438869787027 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9314016557131928, 'min_weight_fraction_leaf': 0.02357229400551586}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:11:20,320] Trial 42 finished with value: 0.8452322380506629 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9931832032289135, 'min_weight_fraction_leaf': 0.021857102585575633}. Best is trial 42 with value: 0.8452322380506629.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:11:23,549] Trial 43 finished with value: 0.845177419705727 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 336, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9418670280136737, 'min_weight_fraction_leaf': 0.02619307363235266}. Best is trial 42 with value: 0.8452322380506629.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.944206008583691
[I 2024-04-14 17:11:28,503] Trial 44 finished with value: 0.8475319253205553 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9996718065698121, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 44 with value: 0.8475319253205553.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:11:32,610] Trial 45 finished with value: 0.8554052970665053 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9994357381031855, 'min_weight_fraction_leaf': 0.05293553566639882}. Best is trial 45 with value: 0.8554052970665053.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9356223175965666
[I 2024-04-14 17:11:36,099] Trial 46 finished with value: 0.8460640087589031 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9959608873895133, 'min_weight_fraction_leaf': 0.05633429748553375}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6351931330472103
[I 2024-04-14 17:11:47,924] Trial 47 finished with value: 0.6726723699158018 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 384, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9960245199191953, 'min_weight_fraction_leaf': 0.10909382046675528}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:11:57,196] Trial 48 finished with value: 0.8538116715684974 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 427, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9987007340889653, 'min_weight_fraction_leaf': 0.05223913002386616}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.927038626609442
[I 2024-04-14 17:12:04,107] Trial 49 finished with value: 0.8443804699558598 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9838637316061305, 'min_weight_fraction_leaf': 0.055846795385322806}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9356223175965666
[I 2024-04-14 17:12:09,001] Trial 50 finished with value: 0.8468392025573527 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9969024404165039, 'min_weight_fraction_leaf': 0.05441612766959897}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9055793991416309
[I 2024-04-14 17:12:13,307] Trial 51 finished with value: 0.8426018949867666 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 450, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9988785512322712, 'min_weight_fraction_leaf': 0.09586311629563926}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.927038626609442
[I 2024-04-14 17:12:17,057] Trial 52 finished with value: 0.8460499654852054 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 408, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9603679595472577, 'min_weight_fraction_leaf': 0.06068477683436807}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-14 17:12:20,200] Trial 53 finished with value: 0.8493455916559528 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.05734643060318976}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8454935622317596
[I 2024-04-14 17:12:23,091] Trial 54 finished with value: 0.7972039323711585 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8997172683692978, 'min_weight_fraction_leaf': 0.15252836878533196}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 17:12:25,184] Trial 55 finished with value: 0.6622275124096364 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9099574607745866, 'min_weight_fraction_leaf': 0.11358880135617166}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9484978540772532
[I 2024-04-14 17:12:29,023] Trial 56 finished with value: 0.8564559108911997 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9671125170349901, 'min_weight_fraction_leaf': 0.05014189723990748}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 17:12:31,518] Trial 57 finished with value: 0.7420733376800305 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 497, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8480419506123976, 'min_weight_fraction_leaf': 0.08434869363890837}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9527896995708155
[I 2024-04-14 17:12:35,402] Trial 58 finished with value: 0.8562924469636007 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9618123713667476, 'min_weight_fraction_leaf': 0.04422578178543493}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5321888412017167
[I 2024-04-14 17:12:41,241] Trial 59 finished with value: 0.5983611985032647 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9640017924847067, 'min_weight_fraction_leaf': 0.010404728780784564}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9527896995708155
[I 2024-04-14 17:12:44,937] Trial 60 finished with value: 0.8549743684786726 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8853359821635006, 'min_weight_fraction_leaf': 0.04449622014546582}. Best is trial 56 with value: 0.8564559108911997.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.944206008583691
[I 2024-04-14 17:12:48,651] Trial 61 finished with value: 0.8485600725085831 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 427, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8869448008091242, 'min_weight_fraction_leaf': 0.04303373540903084}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 17:12:52,446] Trial 62 finished with value: 0.8236094248173009 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 427, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8809845326168647, 'min_weight_fraction_leaf': 0.0946809905397768}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.944206008583691
[I 2024-04-14 17:12:58,374] Trial 63 finished with value: 0.8524213039761458 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9613756594129235, 'min_weight_fraction_leaf': 0.04313732124940366}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-14 17:13:02,392] Trial 64 finished with value: 0.849139303656273 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 468, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9643305378246444, 'min_weight_fraction_leaf': 0.040999627212704635}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9055793991416309
[I 2024-04-14 17:13:06,430] Trial 65 finished with value: 0.8299214721993768 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 480, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8332638017309197, 'min_weight_fraction_leaf': 0.009769007432165765}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7510729613733905
[I 2024-04-14 17:13:09,925] Trial 66 finished with value: 0.7410452410661378 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 460, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.06559182297622389}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5879828326180258
[I 2024-04-14 17:13:12,201] Trial 67 finished with value: 0.6577298855923839 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 415, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9579652192705116, 'min_weight_fraction_leaf': 0.14244476766374436}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 17:13:14,977] Trial 68 finished with value: 0.743033894778593 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7943070081319523, 'min_weight_fraction_leaf': 0.08362003429822154}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 17:13:17,279] Trial 69 finished with value: 0.7347432644495872 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 386, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9076237691477275, 'min_weight_fraction_leaf': 0.11232995852145324}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:13:22,643] Trial 70 finished with value: 0.8469223778576156 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8593570128906675, 'min_weight_fraction_leaf': 0.04617252859484205}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9313304721030042
[I 2024-04-14 17:13:29,757] Trial 71 finished with value: 0.8524822994819349 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 463, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9564301458275928, 'min_weight_fraction_leaf': 0.04053709699857146}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9429657794676806
Fold 5 C-index: 0.9527896995708155
[I 2024-04-14 17:13:37,732] Trial 72 finished with value: 0.8585484724893282 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9533554910566981, 'min_weight_fraction_leaf': 0.01276054813110837}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:13:45,051] Trial 73 finished with value: 0.8516425292537818 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 486, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.953199330453136, 'min_weight_fraction_leaf': 0.000811259515634365}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.9186046511627907
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.9527896995708155
[I 2024-04-14 17:13:55,407] Trial 74 finished with value: 0.8489293113396391 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 457, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9540701793746674, 'min_weight_fraction_leaf': 0.018624119914381707}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9570815450643777
[I 2024-04-14 17:14:06,144] Trial 75 finished with value: 0.8547603778153011 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 489, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9193672578433386, 'min_weight_fraction_leaf': 0.03687267406592508}. Best is trial 72 with value: 0.8585484724893282.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-14 17:14:28,452] Trial 76 finished with value: 0.649409325772972 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 488, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9158386587581989, 'min_weight_fraction_leaf': 0.0343251877694847}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9055793991416309
[I 2024-04-14 17:14:32,860] Trial 77 finished with value: 0.829830864643354 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8258345559974801, 'min_weight_fraction_leaf': 0.01395770005472189}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:14:35,508] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8681542805446814, 'min_weight_fraction_leaf': 0.4401997700779695}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5209125475285171
Fold 5 C-index: 0.5150214592274678
[I 2024-04-14 17:14:37,301] Trial 79 finished with value: 0.5769641655871446 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.2054681425917101, 'min_weight_fraction_leaf': 0.07414727613797192}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8884120171673819
[I 2024-04-14 17:14:41,494] Trial 80 finished with value: 0.8328267085854719 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 483, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9737878727725551, 'min_weight_fraction_leaf': 0.10081614006934195}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9570815450643777
[I 2024-04-14 17:14:46,535] Trial 81 finished with value: 0.857947628811317 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9353221320314016, 'min_weight_fraction_leaf': 0.03644151510428387}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.9108527131782945
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.9484978540772532
[I 2024-04-14 17:14:51,774] Trial 82 finished with value: 0.8569333714618624 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9351113009157849, 'min_weight_fraction_leaf': 0.03389522493578406}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-14 17:14:56,102] Trial 83 finished with value: 0.8436158654940284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9244943232738438, 'min_weight_fraction_leaf': 0.0645148338511949}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.944206008583691
[I 2024-04-14 17:15:01,237] Trial 84 finished with value: 0.8388929744398268 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7689103930415312, 'min_weight_fraction_leaf': 0.031240511172206175}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9098712446351931
[I 2024-04-14 17:15:05,352] Trial 85 finished with value: 0.8418707703412766 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9360008079217836, 'min_weight_fraction_leaf': 0.08022431143441006}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.944206008583691
[I 2024-04-14 17:15:08,746] Trial 86 finished with value: 0.8268296912264951 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 452, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8956736273636096, 'min_weight_fraction_leaf': 0.0021008342672814567}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-14 17:15:13,301] Trial 87 finished with value: 0.8542139122049083 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 393, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9757492788830231, 'min_weight_fraction_leaf': 0.013177844731090037}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 17:15:20,838] Trial 88 finished with value: 0.6020819734957581 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 401, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.869230052481604, 'min_weight_fraction_leaf': 0.013527919217184471}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9484978540772532
[I 2024-04-14 17:15:26,933] Trial 89 finished with value: 0.8573032503759761 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 489, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9796761451834832, 'min_weight_fraction_leaf': 0.029477074249114846}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8927038626609443
[I 2024-04-14 17:15:31,636] Trial 90 finished with value: 0.801853783072581 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 491, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9148186606025017, 'min_weight_fraction_leaf': 0.026231482250007713}. Best is trial 72 with value: 0.8585484724893282.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9484978540772532
[I 2024-04-14 17:15:36,959] Trial 91 finished with value: 0.851631796496067 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 476, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.977330549698534, 'min_weight_fraction_leaf': 0.034170399509268666}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9527896995708155
[I 2024-04-14 17:15:42,400] Trial 92 finished with value: 0.8428668726912847 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 454, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9372815834366508, 'min_weight_fraction_leaf': 0.013175088098699696}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.944206008583691
[I 2024-04-14 17:15:47,150] Trial 93 finished with value: 0.8524498043525692 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 467, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9806300653083163, 'min_weight_fraction_leaf': 0.04785150205265768}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:15:51,725] Trial 94 finished with value: 0.8539749920749997 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9370811219597744, 'min_weight_fraction_leaf': 0.020386589499688558}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-14 17:15:58,371] Trial 95 finished with value: 0.849139303656273 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8886989249819622, 'min_weight_fraction_leaf': 0.06855096582137163}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6394849785407726
[I 2024-04-14 17:16:02,456] Trial 96 finished with value: 0.6975795340855144 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 416, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9719284600548868, 'min_weight_fraction_leaf': 0.3157465264411285}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9055793991416309
[I 2024-04-14 17:16:09,972] Trial 97 finished with value: 0.8395632269725679 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 441, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9434948894242242, 'min_weight_fraction_leaf': 0.08853389895678439}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9313304721030042
[I 2024-04-14 17:16:18,176] Trial 98 finished with value: 0.8444815398616662 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 484, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9141730094207001, 'min_weight_fraction_leaf': 0.058717588979820705}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289

[I 2024-04-14 17:16:23,640] A new study created in memory with name: no-name-c7640c36-0626-4d37-b40c-8a66b6be885b

Fold 5 C-index: 0.9399141630901288
[I 2024-04-14 17:16:23,618] Trial 99 finished with value: 0.8444564769880605 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 405, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8453744927035851, 'min_weight_fraction_leaf': 0.03335954291144526}. Best is trial 72 with value: 0.8585484724893282.


* Best trial for C-index:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.8585484724893282], datetime_start=datetime.datetime(2024, 4, 14, 17, 13, 29, 779471), datetime_complete=datetime.datetime(2024, 4, 14, 17, 13, 37, 730243), params={'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9533554910566981, 'min_weight_fraction_leaf': 0.01276054813110837}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=72, value=None)


* Best Score for C-index:
 0.8585484724893282

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2516164991390209
Fold 2 IBS: 0.21850178124833985
Fold 3 IBS: 0.22086347781939733
Fold 4 IBS: 0.25088267027111183
Fold 5 IBS: 0.24153593571525953
[I 2024-04-14 17:16:28,638] Trial 0 finished with value: 0.23668007283862588 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.23668007283862588.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-14 17:16:37,567] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.250106789783813
Fold 2 IBS: 0.21284765330505998
Fold 3 IBS: 0.21432751401307024
Fold 4 IBS: 0.24895944813780088
Fold 5 IBS: 0.2434714195977076
[I 2024-04-14 17:16:44,665] Trial 2 finished with value: 0.23394256496749036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.25014536571335444
Fold 2 IBS: 0.2113825578010961
Fold 3 IBS: 0.2134335092754675
Fold 4 IBS: 0.25164350041840367
Fold 5 IBS: 0.2449472628259721
[I 2024-04-14 17:16:46,549] Trial 3 finished with value: 0.23431043920685876 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-14 17:16:51,109] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-14 17:16:54,215] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.25064410298449685
Fold 2 IBS: 0.21757261651937224
Fold 3 IBS: 0.21918674755082743
Fold 4 IBS: 0.24972493455649708
Fold 5 IBS: 0.24144716407743633
[I 2024-04-14 17:17:01,601] Trial 6 finished with value: 0.23571511313772597 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.2479608891120626
Fold 2 IBS: 0.22976152459854426
Fold 3 IBS: 0.22811801807306573
Fold 4 IBS: 0.24587396817268928
Fold 5 IBS: 0.2330748936121747
[I 2024-04-14 17:17:04,955] Trial 7 finished with value: 0.23695785871370728 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.2513075212583926
Fold 2 IBS: 0.21665466723740523
Fold 3 IBS: 0.2264150377759085
Fold 4 IBS: 0.24248571033147254
Fold 5 IBS: 0.24134107470803876
[I 2024-04-14 17:17:06,051] Trial 8 finished with value: 0.23564080226224351 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.2461078943343972
Fold 2 IBS: 0.23137874592699662
Fold 3 IBS: 0.22925096730946307
Fold 4 IBS: 0.24170305166953843
Fold 5 IBS: 0.23068341476751855
[I 2024-04-14 17:17:14,981] Trial 9 finished with value: 0.23582481480158277 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24599657914821219
Fold 2 IBS: 0.2321657424483506
Fold 3 IBS: 0.22973713994824324
Fold 4 IBS: 0.24123229752265593
Fold 5 IBS: 0.2305361660938366
[I 2024-04-14 17:17:23,432] Trial 10 finished with value: 0.2359335850322597 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24910663464632776
Fold 2 IBS: 0.21511500290964194
Fold 3 IBS: 0.21734691382471302
Fold 4 IBS: 0.2533192917655032
Fold 5 IBS: 0.24122186829493705
[I 2024-04-14 17:17:25,142] Trial 11 finished with value: 0.2352219422882246 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.25020483090588064
Fold 2 IBS: 0.2135745158819406
Fold 3 IBS: 0.21597697745716077
Fold 4 IBS: 0.2500325282615297
Fold 5 IBS: 0.24036191068102103
[I 2024-04-14 17:17:27,838] Trial 12 finished with value: 0.23403015263750654 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24742900358706432
Fold 2 IBS: 0.2296101524085416
Fold 3 IBS: 0.22194366434060078
Fold 4 IBS: 0.23373705912685125
Fold 5 IBS: 0.23557268199165743
[I 2024-04-14 17:17:28,174] Trial 13 finished with value: 0.2336585122909431 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.06483165374536849}. Best is trial 13 with value: 0.2336585122909431.
Fold 1 IBS: 0.24738256882467896
Fold 2 IBS: 0.2320970408821112
Fold 3 IBS: 0.22943176061214976
Fold 4 IBS: 0.24177377883723775
Fold 5 IBS: 0.22985649095814709
[I 2024-04-14 17:17:28,701] Trial 14 finished with value: 0.23610832802286494 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.3027798907108762, 'min_weight_fraction_leaf': 0.19322689159720335}. Best is trial 13 with value: 0.2336585122909431.

Fold 1 IBS: 0.247026504078842
Fold 2 IBS: 0.2195206957705492
Fold 3 IBS: 0.2123172789815588
Fold 4 IBS: 0.2479867211511746
Fold 5 IBS: 0.2387573651090091
[I 2024-04-14 17:17:33,536] Trial 15 finished with value: 0.23312171301822673 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 268, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3482433053809723, 'min_weight_fraction_leaf': 0.004357064532752621}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24701033455749313
Fold 2 IBS: 0.2322992796906955
Fold 3 IBS: 0.22982735187201522
Fold 4 IBS: 0.24119172674202158
Fold 5 IBS: 0.23034831988724866
[I 2024-04-14 17:17:36,944] Trial 16 finished with value: 0.23613540254989482 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.34033861208912675, 'min_weight_fraction_leaf': 0.010320253267333261}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24753685844322235
Fold 2 IBS: 0.23209067824437812
Fold 3 IBS: 0.22941552751394542
Fold 4 IBS: 0.24137850216356824
Fold 5 IBS: 0.23006657825042381
[I 2024-04-14 17:17:38,621] Trial 17 finished with value: 0.2360976289231076 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 97, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.13353756561046431, 'min_weight_fraction_leaf': 0.4058065513996202}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24661438736241653
Fold 2 IBS: 0.23234201038304025
Fold 3 IBS: 0.22985935061537058
Fold 4 IBS: 0.2412142155510644
Fold 5 IBS: 0.23028965352741476
[I 2024-04-14 17:17:44,557] Trial 18 finished with value: 0.2360639234878613 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.3062501142134034, 'min_weight_fraction_leaf': 0.16590566942711585}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24625016006407022
Fold 2 IBS: 0.2294322066721454
Fold 3 IBS: 0.22885619585099656
Fold 4 IBS: 0.24190838192064892
Fold 5 IBS: 0.23156021011301853
[I 2024-04-14 17:17:47,037] Trial 19 finished with value: 0.23560143092417593 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 224, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.38202098659284595, 'min_weight_fraction_leaf': 0.046399006012705586}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24701935315672957
Fold 2 IBS: 0.24163403136964587
Fold 3 IBS: 0.22856287289614435
Fold 4 IBS: 0.2454158941909801
Fold 5 IBS: 0.22954960363738028
[I 2024-04-14 17:17:47,341] Trial 20 finished with value: 0.23843635105017605 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.22426994530779043, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2526987825761896
Fold 2 IBS: 0.20999617961817782
Fold 3 IBS: 0.2128012813411989
Fold 4 IBS: 0.24657290453581146
Fold 5 IBS: 0.24462337536444018
[I 2024-04-14 17:17:51,941] Trial 21 finished with value: 0.2333385046871636 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 298, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.07272507805207075}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2506668391572938
Fold 2 IBS: 0.21369268617763446
Fold 3 IBS: 0.21491668461840335
Fold 4 IBS: 0.24630407943716084
Fold 5 IBS: 0.24359099128644837
[I 2024-04-14 17:17:57,813] Trial 22 finished with value: 0.23383425613538816 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 307, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.43242783612550895, 'min_weight_fraction_leaf': 0.0870783750535344}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24639083235051112
Fold 2 IBS: 0.22875193272128705
Fold 3 IBS: 0.22701295893713738
Fold 4 IBS: 0.24158101805780013
Fold 5 IBS: 0.23075841301544256
[I 2024-04-14 17:18:03,507] Trial 23 finished with value: 0.23489903101643567 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 378, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.242935508884002, 'min_weight_fraction_leaf': 0.017058739448196664}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2466493632370186
Fold 2 IBS: 0.23218552875928486
Fold 3 IBS: 0.23035547489183533
Fold 4 IBS: 0.24089209066138523
Fold 5 IBS: 0.22931154604505666
[I 2024-04-14 17:18:07,167] Trial 24 finished with value: 0.2358788007189161 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 296, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.10658832795558945, 'min_weight_fraction_leaf': 0.09530734460374185}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2467045001129852
Fold 2 IBS: 0.23155617370579895
Fold 3 IBS: 0.22842966261666695
Fold 4 IBS: 0.2422095447426687
Fold 5 IBS: 0.2309733003608245
[I 2024-04-14 17:18:10,110] Trial 25 finished with value: 0.23597463630778887 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 229, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.04225085916833678}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24769388743290444
Fold 2 IBS: 0.223306248864412
Fold 3 IBS: 0.2234714023372094
Fold 4 IBS: 0.2483602602835835
Fold 5 IBS: 0.2343651435093372
[I 2024-04-14 17:18:13,182] Trial 26 finished with value: 0.2354393884854893 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5144377302955965, 'min_weight_fraction_leaf': 0.1711529803703364}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24655735930845069
Fold 2 IBS: 0.2322899069166581
Fold 3 IBS: 0.22962367540212245
Fold 4 IBS: 0.24142631754770405
Fold 5 IBS: 0.23015599331072079
[I 2024-04-14 17:18:17,661] Trial 27 finished with value: 0.23601065049713119 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.3606369716299986, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24743161351882595
Fold 2 IBS: 0.2105713848998565
Fold 3 IBS: 0.20850503871762688
Fold 4 IBS: 0.2464580313440729
Fold 5 IBS: 0.23766007235751133
[I 2024-04-14 17:18:21,276] Trial 28 finished with value: 0.2301252281675787 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 282, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4073796738200135, 'min_weight_fraction_leaf': 0.11808925884789895}. Best is trial 28 with value: 0.2301252281675787.
Fold 1 IBS: 0.23563608464325242
Fold 2 IBS: 0.19755231981376395
Fold 3 IBS: 0.20491272478230244
Fold 4 IBS: 0.22191144397261592
Fold 5 IBS: 0.22534015775427496
[I 2024-04-14 17:18:27,555] Trial 29 finished with value: 0.21707054619324193 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.1053491006372442}. Best is trial 29 with value: 0.21707054619324193.

Fold 1 IBS: 0.23497354688702718
Fold 2 IBS: 0.1976009711176378
Fold 3 IBS: 0.20496554854896726
Fold 4 IBS: 0.22195679558988315
Fold 5 IBS: 0.22437156955219212
[I 2024-04-14 17:18:34,733] Trial 30 finished with value: 0.21677368633914149 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 351, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8683525444021144, 'min_weight_fraction_leaf': 0.10877158322577073}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23741283004501632
Fold 2 IBS: 0.19660814788429976
Fold 3 IBS: 0.208320965032862
Fold 4 IBS: 0.22424875267364808
Fold 5 IBS: 0.22365262373167072
[I 2024-04-14 17:18:41,703] Trial 31 finished with value: 0.2180486638734994 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8840623748471775, 'min_weight_fraction_leaf': 0.11910827766006235}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23867714353974298
Fold 2 IBS: 0.19613128503421842
Fold 3 IBS: 0.2065931615501951
Fold 4 IBS: 0.22620631569035407
Fold 5 IBS: 0.2244866720296608
[I 2024-04-14 17:18:47,736] Trial 32 finished with value: 0.2184189155688343 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 345, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9077709187790539, 'min_weight_fraction_leaf': 0.12326015484904061}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23750771451305383
Fold 2 IBS: 0.19887399124028698
Fold 3 IBS: 0.20802968662686863
Fold 4 IBS: 0.2321566030510833
Fold 5 IBS: 0.22656014841579197
[I 2024-04-14 17:18:53,593] Trial 33 finished with value: 0.22062562876941696 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 342, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8925851586807815, 'min_weight_fraction_leaf': 0.2177627113802293}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23602386733728492
Fold 2 IBS: 0.19703622328171574
Fold 3 IBS: 0.2080201955186778
Fold 4 IBS: 0.22565993281913133
Fold 5 IBS: 0.2264791911765019
[I 2024-04-14 17:19:00,484] Trial 34 finished with value: 0.21864388202666235 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.867135793861854, 'min_weight_fraction_leaf': 0.1628359603566048}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.239828670509377
Fold 2 IBS: 0.19423711438702101
Fold 3 IBS: 0.20557458285988647
Fold 4 IBS: 0.2221757496887524
Fold 5 IBS: 0.2277228560229509
[I 2024-04-14 17:19:07,830] Trial 35 finished with value: 0.21790779469359758 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8859357847621543, 'min_weight_fraction_leaf': 0.10801386112857586}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.236846255147437
Fold 2 IBS: 0.19741593771399701
Fold 3 IBS: 0.20176247981803738
Fold 4 IBS: 0.22648215967510524
Fold 5 IBS: 0.22131281080369278
[I 2024-04-14 17:19:15,263] Trial 36 finished with value: 0.2167639286316539 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 367, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7298125752042516, 'min_weight_fraction_leaf': 0.1067447453344346}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.24883806926954466
Fold 2 IBS: 0.22058928037323192
Fold 3 IBS: 0.2236201837711479
Fold 4 IBS: 0.24969298739504742
Fold 5 IBS: 0.23941939594400463
[I 2024-04-14 17:19:21,152] Trial 37 finished with value: 0.23643198335059532 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 448, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7251034382726446, 'min_weight_fraction_leaf': 0.09932761153057225}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.24254225881644262
Fold 2 IBS: 0.20924537127093926
Fold 3 IBS: 0.21388826462529725
Fold 4 IBS: 0.24163914739217005
Fold 5 IBS: 0.23436529764135527
[I 2024-04-14 17:19:26,774] Trial 38 finished with value: 0.2283360679492409 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8329175102327004, 'min_weight_fraction_leaf': 0.271489448036016}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23623751781761546
Fold 2 IBS: 0.19762564906135713
Fold 3 IBS: 0.20376748048384277
Fold 4 IBS: 0.2329799057171115
Fold 5 IBS: 0.2239426849990595
[I 2024-04-14 17:19:33,454] Trial 39 finished with value: 0.2189106476157973 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7214836794390458, 'min_weight_fraction_leaf': 0.15059751625410336}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23581677499948878
Fold 2 IBS: 0.20071634171128946
Fold 3 IBS: 0.20905634885165603
Fold 4 IBS: 0.23169075913239115
Fold 5 IBS: 0.22957242789722054
[I 2024-04-14 17:19:40,802] Trial 40 finished with value: 0.2213705305184092 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9262907745467319, 'min_weight_fraction_leaf': 0.22713324232248497}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.234951517307267
Fold 2 IBS: 0.2009582778749222
Fold 3 IBS: 0.20481196017912617
Fold 4 IBS: 0.2213589391492352
Fold 5 IBS: 0.22329994132329942
[I 2024-04-14 17:19:47,074] Trial 41 finished with value: 0.21707612716677 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8538474652324489, 'min_weight_fraction_leaf': 0.1108816675075643}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23472132563835466
Fold 2 IBS: 0.19810232111644868
Fold 3 IBS: 0.2078448660289595
Fold 4 IBS: 0.22651608628151707
Fold 5 IBS: 0.2252022991722336
[I 2024-04-14 17:19:53,431] Trial 42 finished with value: 0.21847737964750272 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8346872721633387, 'min_weight_fraction_leaf': 0.18586114486156524}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23676367561248174
Fold 2 IBS: 0.19660880411130277
Fold 3 IBS: 0.20141730960350246
Fold 4 IBS: 0.22944095726074634
Fold 5 IBS: 0.2205473063642598
[I 2024-04-14 17:20:02,426] Trial 43 finished with value: 0.2169556105904586 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 360, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7414559808390317, 'min_weight_fraction_leaf': 0.09878426797929674}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2500123198027997
Fold 2 IBS: 0.22061417393937463
Fold 3 IBS: 0.2226746084800549
Fold 4 IBS: 0.24928716600585524
Fold 5 IBS: 0.23925280304851704
[I 2024-04-14 17:20:08,024] Trial 44 finished with value: 0.23636821425532029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 404, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9992966624466928, 'min_weight_fraction_leaf': 0.05800083397743003}. Best is trial 36 with value: 0.2167639286316539.

Fold 1 IBS: 0.23322825812700776
Fold 2 IBS: 0.19980996308476648
Fold 3 IBS: 0.20366753393387363
Fold 4 IBS: 0.23327551134614005
Fold 5 IBS: 0.2261815525696507
[I 2024-04-14 17:20:14,305] Trial 45 finished with value: 0.2192325638122877 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 369, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7548177510477919, 'min_weight_fraction_leaf': 0.13669728117144694}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2465213089401209
Fold 2 IBS: 0.23046298845066793
Fold 3 IBS: 0.22971391168769142
Fold 4 IBS: 0.24253981917172043
Fold 5 IBS: 0.23157320473775703
[I 2024-04-14 17:20:18,320] Trial 46 finished with value: 0.23616224659759152 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8165105316363324, 'min_weight_fraction_leaf': 0.09410347152882448}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2392285685744128
Fold 2 IBS: 0.20301532499210856
Fold 3 IBS: 0.21068375666229217
Fold 4 IBS: 0.233734811370916
Fold 5 IBS: 0.23077502902161473
[I 2024-04-14 17:20:26,007] Trial 47 finished with value: 0.22348749812426885 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6150842738658111, 'min_weight_fraction_leaf': 0.14204359491488883}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2505808877528506
Fold 2 IBS: 0.21787837074644673
Fold 3 IBS: 0.21955621291869448
Fold 4 IBS: 0.2479106478038418
Fold 5 IBS: 0.24079437785769506
[I 2024-04-14 17:20:32,328] Trial 48 finished with value: 0.23534409941590573 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 423, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.698306943286806, 'min_weight_fraction_leaf': 0.02988689193434292}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.24656651844666427
Fold 2 IBS: 0.1973040995587005
Fold 3 IBS: 0.2000632083680002
Fold 4 IBS: 0.23461042669889007
Fold 5 IBS: 0.22362250203152442
[I 2024-04-14 17:20:41,527] Trial 49 finished with value: 0.2204333510207559 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7809927058547124, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23490052998563946
Fold 2 IBS: 0.19727678918732186
Fold 3 IBS: 0.20205967319247634
Fold 4 IBS: 0.22662398315892893
Fold 5 IBS: 0.22361282902817
[I 2024-04-14 17:20:46,861] Trial 50 finished with value: 0.21689476091050733 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 282, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9532766072292076, 'min_weight_fraction_leaf': 0.18032639031378228}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23322434497515637
Fold 2 IBS: 0.19675858311595756
Fold 3 IBS: 0.20434076674333107
Fold 4 IBS: 0.2270264675864422
Fold 5 IBS: 0.22363090695751162
[I 2024-04-14 17:20:52,798] Trial 51 finished with value: 0.21699621387567974 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 317, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.18156728352333845}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2358482394775375
Fold 2 IBS: 0.1993862869046167
Fold 3 IBS: 0.20591034366560787
Fold 4 IBS: 0.22644548764098435
Fold 5 IBS: 0.22426799582500884
[I 2024-04-14 17:20:57,178] Trial 52 finished with value: 0.21837167070275107 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 243, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.956892699604465, 'min_weight_fraction_leaf': 0.208464530420868}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2347102601084114
Fold 2 IBS: 0.19492132792654773
Fold 3 IBS: 0.20372340864817398
Fold 4 IBS: 0.22451053611946223
Fold 5 IBS: 0.22574160580247377
[I 2024-04-14 17:21:02,335] Trial 53 finished with value: 0.21672142772101383 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.17857938204264587}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2507202946006097
Fold 2 IBS: 0.21425933646897768
Fold 3 IBS: 0.22023122312992002
Fold 4 IBS: 0.24896399653157794
Fold 5 IBS: 0.24243791934696968
[I 2024-04-14 17:21:06,003] Trial 54 finished with value: 0.23532255401561103 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9561942993760734, 'min_weight_fraction_leaf': 0.18508357462091207}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24252706399447918
Fold 2 IBS: 0.2072249626266686
Fold 3 IBS: 0.21255447229272564
Fold 4 IBS: 0.23701845963835796
Fold 5 IBS: 0.23702019287199932
[I 2024-04-14 17:21:09,387] Trial 55 finished with value: 0.22726903028484613 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 201, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9239898991962526, 'min_weight_fraction_leaf': 0.2797861686064933}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2466322813274835
Fold 2 IBS: 0.22690874233166022
Fold 3 IBS: 0.22703003374851932
Fold 4 IBS: 0.24446208681134918
Fold 5 IBS: 0.23232754049354626
[I 2024-04-14 17:21:13,265] Trial 56 finished with value: 0.23547213694251173 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9759496491827552, 'min_weight_fraction_leaf': 0.3230607190970375}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23737375961186943
Fold 2 IBS: 0.19791239976321015
Fold 3 IBS: 0.20367326309929848
Fold 4 IBS: 0.22278621870777932
Fold 5 IBS: 0.22534031507623634
[I 2024-04-14 17:21:18,019] Trial 57 finished with value: 0.21741719125167874 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9332290664977184, 'min_weight_fraction_leaf': 0.1574532042482963}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24655767659985756
Fold 2 IBS: 0.23216890541138882
Fold 3 IBS: 0.22956973979229836
Fold 4 IBS: 0.2414720097528081
Fold 5 IBS: 0.23027659366606912
[I 2024-04-14 17:21:22,716] Trial 58 finished with value: 0.23600898504448437 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 324, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7570423536286393, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24451651620865986
Fold 2 IBS: 0.21029443193844233
Fold 3 IBS: 0.21268401432755918
Fold 4 IBS: 0.241118850609694
Fold 5 IBS: 0.23692605047125703
[I 2024-04-14 17:21:26,105] Trial 59 finished with value: 0.22910797271112243 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 202, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7892943400374715, 'min_weight_fraction_leaf': 0.2531462312418419}. Best is trial 53 with value: 0.21672142772101383.

Fold 1 IBS: 0.24675120399960646
Fold 2 IBS: 0.2238312246331017
Fold 3 IBS: 0.22373605345231745
Fold 4 IBS: 0.24763583159134048
Fold 5 IBS: 0.2361001387256771
[I 2024-04-14 17:21:29,640] Trial 60 finished with value: 0.23561089048040867 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 259, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5876523474241502, 'min_weight_fraction_leaf': 0.18336534674120722}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24544383395694797
Fold 2 IBS: 0.19103401818321838
Fold 3 IBS: 0.1977979215082493
Fold 4 IBS: 0.2360015957855052
Fold 5 IBS: 0.22738640071735247
[I 2024-04-14 17:21:39,810] Trial 61 finished with value: 0.21953275403025466 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 363, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9817888741599827, 'min_weight_fraction_leaf': 0.08034824287701624}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23702043041145554
Fold 2 IBS: 0.1982882587017249
Fold 3 IBS: 0.20404836661294448
Fold 4 IBS: 0.22738765999634022
Fold 5 IBS: 0.22466910472549614
[I 2024-04-14 17:21:45,557] Trial 62 finished with value: 0.21828276408959227 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 309, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8169431607503741, 'min_weight_fraction_leaf': 0.14045762430272518}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23528690602923447
Fold 2 IBS: 0.20067887083049787
Fold 3 IBS: 0.20619313061129296
Fold 4 IBS: 0.22935101641955274
Fold 5 IBS: 0.22778974684575007
[I 2024-04-14 17:21:52,484] Trial 63 finished with value: 0.21985993414726565 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 384, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8541325292759324, 'min_weight_fraction_leaf': 0.20634205490826563}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24785243089638537
Fold 2 IBS: 0.191819411621147
Fold 3 IBS: 0.19595373736651736
Fold 4 IBS: 0.23396960581056234
Fold 5 IBS: 0.22817124135051
[I 2024-04-14 17:22:00,956] Trial 64 finished with value: 0.21955328540902438 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9474372485784143, 'min_weight_fraction_leaf': 0.05967166684837456}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2482913412046415
Fold 2 IBS: 0.2200836170862754
Fold 3 IBS: 0.22300947282774128
Fold 4 IBS: 0.24894456005276414
Fold 5 IBS: 0.23878529350646063
[I 2024-04-14 17:22:05,909] Trial 65 finished with value: 0.2358228569355766 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 335, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9068094061449172, 'min_weight_fraction_leaf': 0.23316652574301272}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23342652751464346
Fold 2 IBS: 0.20244094695682738
Fold 3 IBS: 0.2105886037120247
Fold 4 IBS: 0.2334597367833201
Fold 5 IBS: 0.23125038856804886
[I 2024-04-14 17:22:11,442] Trial 66 finished with value: 0.22223324070697292 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 355, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6873372044383822, 'min_weight_fraction_leaf': 0.17618672192654974}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.235741181115283
Fold 2 IBS: 0.19600302220181715
Fold 3 IBS: 0.20506229623259442
Fold 4 IBS: 0.22552096551242218
Fold 5 IBS: 0.22527819459965537
[I 2024-04-14 17:22:16,612] Trial 67 finished with value: 0.21752113193235445 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8641466001482349, 'min_weight_fraction_leaf': 0.16024471468098603}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2380009615179774
Fold 2 IBS: 0.2053057958310263
Fold 3 IBS: 0.20693833652356367
Fold 4 IBS: 0.23343099085304939
Fold 5 IBS: 0.23051644642343777
[I 2024-04-14 17:22:21,134] Trial 68 finished with value: 0.2228385062298109 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 313, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7454821099429565, 'min_weight_fraction_leaf': 0.1315028130600445}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23667050870598896
Fold 2 IBS: 0.19707337732587207
Fold 3 IBS: 0.20506243352245881
Fold 4 IBS: 0.22989927387001974
Fold 5 IBS: 0.2247802288452282
[I 2024-04-14 17:22:28,483] Trial 69 finished with value: 0.21869716445391357 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 227, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9115851507518807, 'min_weight_fraction_leaf': 0.19881342365516072}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24755217694573514
Fold 2 IBS: 0.23067103498005345
Fold 3 IBS: 0.22919268224306755
Fold 4 IBS: 0.24330350374086074
Fold 5 IBS: 0.23206289633690777
[I 2024-04-14 17:22:32,256] Trial 70 finished with value: 0.2365564588493249 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 296, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9734470555075896, 'min_weight_fraction_leaf': 0.1037315705497979}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23557800438634688
Fold 2 IBS: 0.19925421339611335
Fold 3 IBS: 0.2043473925891944
Fold 4 IBS: 0.22213902871913044
Fold 5 IBS: 0.2235128361033631
[I 2024-04-14 17:22:38,937] Trial 71 finished with value: 0.21696629503882964 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8402458676885415, 'min_weight_fraction_leaf': 0.11593845358143434}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23358834179947885
Fold 2 IBS: 0.19925797694578165
Fold 3 IBS: 0.20631707475676808
Fold 4 IBS: 0.22712164828983641
Fold 5 IBS: 0.22686739135241812
[I 2024-04-14 17:22:46,378] Trial 72 finished with value: 0.2186304866288566 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 359, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8022020419002074, 'min_weight_fraction_leaf': 0.12654108414074106}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23989628535126872
Fold 2 IBS: 0.19504918561347076
Fold 3 IBS: 0.20766848585539088
Fold 4 IBS: 0.2243318781250735
Fold 5 IBS: 0.2254076136840937
[I 2024-04-14 17:22:53,916] Trial 73 finished with value: 0.21847068972585953 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8883744161104976, 'min_weight_fraction_leaf': 0.08624238462675754}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24330205884039094
Fold 2 IBS: 0.1960859798288803
Fold 3 IBS: 0.20204615415341717
Fold 4 IBS: 0.22282852954588567
Fold 5 IBS: 0.22527092770084384
[I 2024-04-14 17:23:06,729] Trial 74 finished with value: 0.21790673001388358 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.868573691117867, 'min_weight_fraction_leaf': 0.11520344080447015}. Best is trial 53 with value: 0.21672142772101383.

Fold 1 IBS: 0.23878866729576506
Fold 2 IBS: 0.19862339947767513
Fold 3 IBS: 0.20582989519828723
Fold 4 IBS: 0.2244448023517984
Fold 5 IBS: 0.2249714920857591
[I 2024-04-14 17:23:12,672] Trial 75 finished with value: 0.218531651281857 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8355109212222066, 'min_weight_fraction_leaf': 0.1496381039654338}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24638426866097177
Fold 2 IBS: 0.22911008901873028
Fold 3 IBS: 0.22825388044344033
Fold 4 IBS: 0.2429147576831134
Fold 5 IBS: 0.2310867513895085
[I 2024-04-14 17:23:16,940] Trial 76 finished with value: 0.23554994943915286 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 402, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9497940527687874, 'min_weight_fraction_leaf': 0.3913116453285941}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23745526394695224
Fold 2 IBS: 0.19742171438125147
Fold 3 IBS: 0.20372559975892518
Fold 4 IBS: 0.22904263568439634
Fold 5 IBS: 0.22173120591021678
[I 2024-04-14 17:23:25,159] Trial 77 finished with value: 0.2178752839363484 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 416, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7166829789978312, 'min_weight_fraction_leaf': 0.050744524856922685}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24927476126128845
Fold 2 IBS: 0.208231400065323
Fold 3 IBS: 0.21411329384109026
Fold 4 IBS: 0.249376195146158
Fold 5 IBS: 0.24369864008356293
[I 2024-04-14 17:23:29,315] Trial 78 finished with value: 0.23293885807948453 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 341, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9995929035384165, 'min_weight_fraction_leaf': 0.08440337592244582}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24494208697141254
Fold 2 IBS: 0.2116349766712215
Fold 3 IBS: 0.21075545248518937
Fold 4 IBS: 0.24418992316803034
Fold 5 IBS: 0.23595455504395807
[I 2024-04-14 17:23:33,506] Trial 79 finished with value: 0.22949539886796236 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 260, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.03438361115836926}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2487177645255871
Fold 2 IBS: 0.2182024376115983
Fold 3 IBS: 0.22324181474860025
Fold 4 IBS: 0.24889042191015426
Fold 5 IBS: 0.2404752027074224
[I 2024-04-14 17:23:37,909] Trial 80 finished with value: 0.2359055283006725 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 303, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8351802467114298, 'min_weight_fraction_leaf': 0.17374014764047482}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2343225314915598
Fold 2 IBS: 0.20080169245493515
Fold 3 IBS: 0.2040616253448912
Fold 4 IBS: 0.2209705540772439
Fold 5 IBS: 0.22381309225452964
[I 2024-04-14 17:23:43,900] Trial 81 finished with value: 0.21679389912463196 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8534956380037706, 'min_weight_fraction_leaf': 0.10880420004471991}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23759152349495194
Fold 2 IBS: 0.19592371029252753
Fold 3 IBS: 0.2072471173483897
Fold 4 IBS: 0.22594602303280678
Fold 5 IBS: 0.22405057142534987
[I 2024-04-14 17:23:50,458] Trial 82 finished with value: 0.21815178911880512 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8879430516495728, 'min_weight_fraction_leaf': 0.09459448625969206}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.239412006571268
Fold 2 IBS: 0.19774448699778083
Fold 3 IBS: 0.20522840650133722
Fold 4 IBS: 0.22445007414910306
Fold 5 IBS: 0.2261834150707348
[I 2024-04-14 17:23:58,060] Trial 83 finished with value: 0.21860367785804477 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 319, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9171078906725617, 'min_weight_fraction_leaf': 0.1052694178484323}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23361013902960837
Fold 2 IBS: 0.2015645158386313
Fold 3 IBS: 0.20413401003241938
Fold 4 IBS: 0.2321092758761283
Fold 5 IBS: 0.22764703849196896
[I 2024-04-14 17:24:05,815] Trial 84 finished with value: 0.21981299585375128 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 389, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7724021984938093, 'min_weight_fraction_leaf': 0.12058904937847048}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23757837283796351
Fold 2 IBS: 0.19324227600096808
Fold 3 IBS: 0.20280434329037092
Fold 4 IBS: 0.22354307385378738
Fold 5 IBS: 0.22801046653333804
[I 2024-04-14 17:24:15,938] Trial 85 finished with value: 0.21703570650328557 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9360967058275064, 'min_weight_fraction_leaf': 0.07268375412116553}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.25429852555911403
Fold 2 IBS: 0.21033125981735631
Fold 3 IBS: 0.2144457109771278
Fold 4 IBS: 0.25078928838120385
Fold 5 IBS: 0.244029243928168
[I 2024-04-14 17:24:21,498] Trial 86 finished with value: 0.234778805732594 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9642478723292717, 'min_weight_fraction_leaf': 0.020071342516688462}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23900122947698701
Fold 2 IBS: 0.19238827530037164
Fold 3 IBS: 0.20210857686800815
Fold 4 IBS: 0.22317247828149858
Fold 5 IBS: 0.22737872525252992
[I 2024-04-14 17:24:27,141] Trial 87 finished with value: 0.21680985703587904 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 287, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9378062713463992, 'min_weight_fraction_leaf': 0.06921252518565787}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24066267374743672
Fold 2 IBS: 0.20005464365592593
Fold 3 IBS: 0.20543574720731855
Fold 4 IBS: 0.22529042844516578
Fold 5 IBS: 0.2226325847112706
[I 2024-04-14 17:24:31,938] Trial 88 finished with value: 0.21881521555342354 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 270, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8097938703537855, 'min_weight_fraction_leaf': 0.13303674175829286}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2397255226432569
Fold 2 IBS: 0.19674577421997944
Fold 3 IBS: 0.2025535870258632
Fold 4 IBS: 0.2233994107103644
Fold 5 IBS: 0.22740149185929429
[I 2024-04-14 17:24:37,408] Trial 89 finished with value: 0.21796515729175164 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9038411335483634, 'min_weight_fraction_leaf': 0.14792768782183083}. Best is trial 53 with value: 0.21672142772101383.

Fold 1 IBS: 0.23711736196146355
Fold 2 IBS: 0.20354697260954158
Fold 3 IBS: 0.20782994592008056
Fold 4 IBS: 0.235467444322929
Fold 5 IBS: 0.23168859841356962
[I 2024-04-14 17:24:41,233] Trial 90 finished with value: 0.22313006464551685 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6267661705142946, 'min_weight_fraction_leaf': 0.049594043056366624}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24102633692552217
Fold 2 IBS: 0.19520843787050352
Fold 3 IBS: 0.20356979583511886
Fold 4 IBS: 0.2204498673203032
Fold 5 IBS: 0.22696028171118432
[I 2024-04-14 17:24:46,980] Trial 91 finished with value: 0.21744294393252642 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 304, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8764516242063105, 'min_weight_fraction_leaf': 0.06949247400851687}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2394456581845208
Fold 2 IBS: 0.19363296608081376
Fold 3 IBS: 0.20277200709317306
Fold 4 IBS: 0.22459551055765914
Fold 5 IBS: 0.22830612979748444
[I 2024-04-14 17:24:53,531] Trial 92 finished with value: 0.21775045434273022 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 318, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9282849654122768, 'min_weight_fraction_leaf': 0.09312093974775566}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24107663649118255
Fold 2 IBS: 0.19451636127706823
Fold 3 IBS: 0.1965711492060419
Fold 4 IBS: 0.22584943389286724
Fold 5 IBS: 0.22823990209005682
[I 2024-04-14 17:25:01,755] Trial 93 finished with value: 0.21725069659144336 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 364, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9366248318254733, 'min_weight_fraction_leaf': 0.07652785525625173}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24105686216374922
Fold 2 IBS: 0.19505291248840148
Fold 3 IBS: 0.19640882194624412
Fold 4 IBS: 0.2288940107406708
Fold 5 IBS: 0.22369797769916688
[I 2024-04-14 17:25:08,569] Trial 94 finished with value: 0.2170221170076465 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9884082516680452, 'min_weight_fraction_leaf': 0.0623917804702583}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24521510672904306
Fold 2 IBS: 0.19763188756514105
Fold 3 IBS: 0.19644604520830475
Fold 4 IBS: 0.22987163229002092
Fold 5 IBS: 0.22005226494605112
[I 2024-04-14 17:25:13,238] Trial 95 finished with value: 0.2178433873477122 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 217, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9876449779297782, 'min_weight_fraction_leaf': 0.05978166741958252}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.25390879773808833
Fold 2 IBS: 0.20687842930434625
Fold 3 IBS: 0.2105713027702558
Fold 4 IBS: 0.24770741927210513
Fold 5 IBS: 0.23922035669807637
[I 2024-04-14 17:25:17,280] Trial 96 finished with value: 0.23165726115657437 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9703508162412989, 'min_weight_fraction_leaf': 0.11329960994550745}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24645066542896663
Fold 2 IBS: 0.2314637521915939
Fold 3 IBS: 0.22914834885622082
Fold 4 IBS: 0.24244123532590717
Fold 5 IBS: 0.23154120313830437
[I 2024-04-14 17:25:21,002] Trial 97 finished with value: 0.2362090409881986 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8954049778074968, 'min_weight_fraction_leaf': 0.222319312129305}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2515735242888121
Fold 2 IBS: 0.22016600057696184
Fold 3 IBS: 0.22601740987096489
Fold 4 IBS: 0.24872270235850708
Fold 5 IBS: 0.2409968879406772
[I 2024-04-14 17:25:25,443] Trial 98 finished with value: 0.23749530500718463 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9456683815838285, 'min_weight_fraction_leaf': 0.024625018226061307}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24664731493553269
Fold 2 IBS: 0.23211622389871048
Fold 3 IBS: 0.2295272988305809
Fold 4 IBS: 0.24142243220002224
Fold 5 IBS: 0.22985380863864716
[I 2024-04-14 17:25:26,999] Trial 99 finished with value: 0.2359134157006987 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 101, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4622293227685943, 'min_weight_fraction_leaf': 0.260015152988917}. Best is trial 53 with value: 0.21672142772101383.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.21672142772101383], datetime_start=datetime.datetime(2024, 4, 14, 17, 20, 57, 184117), datetime_complete=datetime.datetime(2024, 4, 14, 17, 21, 2, 334599), params={'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.17857938204264587}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=53, value=None)


* Best Score for IBS:
 0.21672142772101383

In [60]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.859
train_ibs:  0.217

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=13, max_features=None, max_leaf_nodes=19,
                   max_samples=0.9533554910566981,
                   min_weight_fraction_leaf=0.01276054813110837,
                   n_estimators=487, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.506

ExtraSurvivalTrees(max_depth=6, max_features=None, max_leaf_nodes=18,
                   max_samples=0.9463423717095281, min_samples_leaf=4,
                   min_samples_split=14,
                   min_weight_fraction_leaf=0.17857938204264587,
                   n_estimators=273, oob_score=True, random_state=123)

IBS: 0.245

In [64]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 17:25:32,661] A new study created in memory with name: no-name-fd8763ef-1ea4-4848-a9eb-338f6a4be5a7

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:26:21,431] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:26:48,155] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:27:08,598] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:27:47,474] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:28:02,120] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:28:05,694] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:28:26,182] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:28:31,629] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:28:32,493] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 17:29:41,348] Trial 9 finished with value: 0.6859109422281264 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 17:31:24,818] Trial 10 finished with value: 0.670852196836783 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:33:17,347] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 17:35:19,625] Trial 12 finished with value: 0.685273555299404 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:36:02,905] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:37:09,230] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:38:16,123] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:38:52,021] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:40:00,900] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:41:54,539] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:42:02,257] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:42:43,213] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 17:44:16,766] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5987124463519313
[I 2024-04-14 17:45:45,244] Trial 22 finished with value: 0.6138909350684226 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:47:55,319] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:49:02,322] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:50:24,369] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:50:52,648] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:52:35,586] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:52:41,633] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:53:50,489] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:54:14,082] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5228136882129277
Fold 5 C-index: 0.6351931330472103
[I 2024-04-14 17:55:52,748] Trial 31 finished with value: 0.6148509290802949 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5836909871244635
[I 2024-04-14 17:57:35,426] Trial 32 finished with value: 0.5167381974248928 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.01975114074478268, 'dropout_rate': 0.17764317230563348, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.49980582609797874, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:59:17,226] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.6760798631992874, 'learning_rate': 0.016733063081788083, 'dropout_rate': 0.32837909362399287, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.42989559468897276, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:00:17,336] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6141580711713768, 'learning_rate': 0.010212728719320904, 'dropout_rate': 0.22658656718653286, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6478790211492356, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7336723985898187, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:01:32,296] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9093298201937425, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.15867077544658675, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 1.263860610757792, 'min_weight_fraction_leaf': 0.36922342323313606, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.90817362499676, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:03:00,945] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7085026268591493, 'learning_rate': 0.0070965351182087025, 'dropout_rate': 0.39089708764550957, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.452111635340179, 'max_features': 'auto', 'min_impurity_decrease': 8.009608651276614e-06, 'validation_fraction': 0.5741608239655631, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:03:43,550] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6150384198855655, 'learning_rate': 0.02319411108605052, 'dropout_rate': 0.518754641115737, 'n_estimators': 397, 'criterion': 'squared_error', 'ccp_alpha': 9.043731037372849, 'min_weight_fraction_leaf': 0.40980674893510094, 'max_features': None, 'min_impurity_decrease': 1.1019559650868866e-07, 'validation_fraction': 0.6250400217604171, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:04:07,238] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.7981565979476395, 'learning_rate': 0.015044404820943004, 'dropout_rate': 0.7673236646699829, 'n_estimators': 302, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5437276444738438, 'min_weight_fraction_leaf': 0.4820963556426466, 'max_features': 'auto', 'min_impurity_decrease': 2.617381555138236e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:04:51,779] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9493559030245647, 'learning_rate': 0.03768032434341392, 'dropout_rate': 0.2987814397752575, 'n_estimators': 359, 'criterion': 'squared_error', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.3277651563969065, 'max_features': 1, 'min_impurity_decrease': 9.83157196897088e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:06:53,298] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.8741100230454082, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 1.1160120003737553, 'min_weight_fraction_leaf': 0.2956774610913858, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.2951344544764216, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5170212765957447
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.5965665236051502
[I 2024-04-14 18:08:34,271] Trial 41 finished with value: 0.6053907873126554 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.007986867821304467, 'dropout_rate': 0.20634597744974018, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.45606967048955926, 'max_features': 'auto', 'min_impurity_decrease': 3.8623524982852286e-07, 'validation_fraction': 0.941559602035689, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:09:57,253] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.012554593902792077, 'dropout_rate': 0.21228719021921444, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.434317240875134, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:11:25,320] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.006577526474875964, 'dropout_rate': 0.3530314967142242, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.47972082857650694, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8059232630259225, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:11:42,227] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.0259748376463175, 'dropout_rate': 0.6859431566383477, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4067118597267765, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:12:55,063] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.7354678955974852, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.14371429216714185, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.14716081727614433, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.48497854077253216
[I 2024-04-14 18:13:05,992] Trial 46 finished with value: 0.605323983519897 and parameters: {'subsample': 0.8425251610032892, 'learning_rate': 0.0053639186505709605, 'dropout_rate': 0.9694253886674298, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.2574882493705594, 'max_features': 'log2', 'min_impurity_decrease': 1.016919779492087e-07, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:13:45,012] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.9243504330346544, 'learning_rate': 0.0011967557478414943, 'dropout_rate': 0.26105839347264326, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.09478753269749979, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0900852926156961e-06, 'validation_fraction': 0.885979815139411, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:13:45,417] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.6629098068705582, 'learning_rate': 0.03206553467408159, 'dropout_rate': 0.4306027387774125, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 1.649438874428751, 'min_weight_fraction_leaf': 0.4531732166106651, 'max_features': None, 'min_impurity_decrease': 1.3827158635733464e-05, 'validation_fraction': 0.9933742654917034, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:15:08,633] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.5594663300427036, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.20150817069458604, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 0.37876808539513185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 2.4898164587398135e-06, 'validation_fraction': 0.8334504114679286, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:17:28,163] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8200406111838637, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.1332989943240106, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 3.941625975561508, 'min_weight_fraction_leaf': 0.19624715321365332, 'max_features': 'auto', 'min_impurity_decrease': 5.669547081135241e-07, 'validation_fraction': 0.4330566028790252, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6008583690987125
[I 2024-04-14 18:19:42,388] Trial 51 finished with value: 0.6018179418009 and parameters: {'subsample': 0.9104229481605087, 'learning_rate': 0.008746876340866865, 'dropout_rate': 0.21819919656654377, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04663074560267056, 'min_weight_fraction_leaf': 0.4658711277635662, 'max_features': 'auto', 'min_impurity_decrease': 3.7719550144765347e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:22:03,138] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.8779706491076079, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.2964247652315011, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.938875857608422, 'min_weight_fraction_leaf': 0.4498850843205848, 'max_features': 'auto', 'min_impurity_decrease': 2.069194057796043e-07, 'validation_fraction': 0.9290323568738834, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:23:53,679] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.8000935140072126, 'learning_rate': 0.011589642842612286, 'dropout_rate': 0.18159949067544315, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.35651077580386414, 'min_weight_fraction_leaf': 0.37041988544171633, 'max_features': 'auto', 'min_impurity_decrease': 3.9659385891088e-07, 'validation_fraction': 0.871716173290517, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:24:30,859] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9719469162642941, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.8266353856620614, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.3650290068083506, 'min_weight_fraction_leaf': 0.4054310128883196, 'max_features': 'auto', 'min_impurity_decrease': 0.009274431072766336, 'validation_fraction': 0.9110985556757252, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:26:35,148] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9036490757662792, 'learning_rate': 0.004559295521962164, 'dropout_rate': 0.2464144102989256, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 2.0967888913642825, 'min_weight_fraction_leaf': 0.44190432010777553, 'max_features': 'auto', 'min_impurity_decrease': 1.193431534143351e-06, 'validation_fraction': 0.7942250610339133, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:27:59,390] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8543724704763108, 'learning_rate': 0.0012362877185655196, 'dropout_rate': 0.19475454848391177, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.924263075836695, 'min_weight_fraction_leaf': 0.4778661374912658, 'max_features': 1, 'min_impurity_decrease': 1.6304555456718902e-07, 'validation_fraction': 0.9992342826522478, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.75
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6587982832618026
[I 2024-04-14 18:28:52,450] Trial 57 finished with value: 0.6603913832851868 and parameters: {'subsample': 0.9387462021362047, 'learning_rate': 0.013448102685141811, 'dropout_rate': 0.5891903890315894, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 0.0019551426651700787, 'min_weight_fraction_leaf': 0.4208222206696523, 'max_features': 'auto', 'min_impurity_decrease': 6.36446366123735e-07, 'validation_fraction': 0.8907139307996623, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:29:15,518] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.9577150108799986, 'learning_rate': 0.09671804411942064, 'dropout_rate': 0.6195846181212514, 'n_estimators': 283, 'criterion': 'squared_error', 'ccp_alpha': 0.44937133507930177, 'min_weight_fraction_leaf': 0.33458212087172423, 'max_features': 0.1, 'min_impurity_decrease': 6.523326131696827e-07, 'validation_fraction': 0.8852115531926663, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:29:59,434] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9323642065585147, 'learning_rate': 0.04692015604549857, 'dropout_rate': 0.5460527407257292, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 1.5096456306059212, 'min_weight_fraction_leaf': 0.28930456038905916, 'max_features': 'log2', 'min_impurity_decrease': 1.6927224987120254e-07, 'validation_fraction': 0.6759708730248685, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:30:08,345] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.019818701956304124, 'dropout_rate': 0.6506047265765441, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.7976673158326983, 'min_weight_fraction_leaf': 0.42349373681810587, 'max_features': 'auto', 'min_impurity_decrease': 2.260183580683562e-06, 'validation_fraction': 0.9643361967122663, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:31:44,886] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.9892683986696426, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.12609792583962923, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 0.22783102537036656, 'min_weight_fraction_leaf': 0.38482014716301177, 'max_features': 'auto', 'min_impurity_decrease': 3.121762528354459e-07, 'validation_fraction': 0.9345303802773877, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6008583690987125
[I 2024-04-14 18:32:51,334] Trial 62 finished with value: 0.5973525260391381 and parameters: {'subsample': 0.8958668704209188, 'learning_rate': 0.013709338127145103, 'dropout_rate': 0.2719048491375873, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.4675490501789938, 'max_features': 'auto', 'min_impurity_decrease': 4.99059031535833e-07, 'validation_fraction': 0.9609388942489451, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:33:42,410] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.5099147728251798, 'learning_rate': 0.0047635225598756225, 'dropout_rate': 0.727101025098758, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.733686110808502, 'min_weight_fraction_leaf': 0.2162503097374653, 'max_features': 'auto', 'min_impurity_decrease': 0.00014811012865046226, 'validation_fraction': 0.7684320660585116, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:35:13,777] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7725061675644463, 'learning_rate': 0.01632247935160366, 'dropout_rate': 0.36503843263594504, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.30086752542772716, 'min_weight_fraction_leaf': 0.40104192592323706, 'max_features': 'auto', 'min_impurity_decrease': 8.287392060214126e-07, 'validation_fraction': 0.9093711333441808, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:35:55,310] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.009066186689461582, 'dropout_rate': 0.5697334421431232, 'n_estimators': 387, 'criterion': 'squared_error', 'ccp_alpha': 1.122844774015951, 'min_weight_fraction_leaf': 0.4962117179962737, 'max_features': 'auto', 'min_impurity_decrease': 4.054579781585349e-06, 'validation_fraction': 0.8558728454820717, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:36:58,669] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8365620544513689, 'learning_rate': 0.022681518299337303, 'dropout_rate': 0.16537519129703201, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.407723936090512, 'min_weight_fraction_leaf': 0.36517701571895683, 'max_features': 'sqrt', 'min_impurity_decrease': 3.241998861905611e-07, 'validation_fraction': 0.8185744726344024, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:38:26,585] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.44818442084795884, 'learning_rate': 0.02921952990739149, 'dropout_rate': 0.2271926570620947, 'n_estimators': 467, 'criterion': 'friedman_mse', 'ccp_alpha': 2.0384900012151963, 'min_weight_fraction_leaf': 0.4211338177916157, 'max_features': 'auto', 'min_impurity_decrease': 1.4298913454728315e-06, 'validation_fraction': 0.9660497725288214, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:38:54,221] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8579390753189435, 'learning_rate': 0.012783334675124321, 'dropout_rate': 0.499258057656232, 'n_estimators': 312, 'criterion': 'squared_error', 'ccp_alpha': 0.830279801910747, 'min_weight_fraction_leaf': 0.4607084781284311, 'max_features': 'auto', 'min_impurity_decrease': 1.3568513606672929e-07, 'validation_fraction': 0.8925211397709236, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:39:48,352] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.786466176479288, 'learning_rate': 0.004018882145822068, 'dropout_rate': 0.42050912513013483, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 8.536647141347391, 'min_weight_fraction_leaf': 0.3485339928251229, 'max_features': None, 'min_impurity_decrease': 5.412716052848312e-07, 'validation_fraction': 0.7027283531430607, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:41:01,883] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.15767213087481324, 'learning_rate': 0.007763574063312924, 'dropout_rate': 0.25122666812491895, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.010224165039626776, 'min_weight_fraction_leaf': 0.4372642442127546, 'max_features': 'auto', 'min_impurity_decrease': 1.8015545575134766e-07, 'validation_fraction': 0.9975125715299878, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 18:41:09,303] Trial 71 finished with value: 0.6004387694866352 and parameters: {'subsample': 0.8358376197961069, 'learning_rate': 0.004078027515854746, 'dropout_rate': 0.983511325860669, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.22910735706669474, 'max_features': 'log2', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9238748566717793, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:42:36,762] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9375804576067359, 'learning_rate': 0.0058069950532190755, 'dropout_rate': 0.16033065274696134, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6374908647868113, 'min_weight_fraction_leaf': 0.25925643779102236, 'max_features': 'log2', 'min_impurity_decrease': 1.043158296301398e-07, 'validation_fraction': 0.8408360882819792, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:42:52,315] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8663908775735847, 'learning_rate': 0.011688605820590949, 'dropout_rate': 0.9088405719505623, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.35065330932074357, 'min_weight_fraction_leaf': 0.24913433692567943, 'max_features': 'log2', 'min_impurity_decrease': 2.3764830721846887e-07, 'validation_fraction': 0.7766959064031379, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:43:06,031] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8954410632257164, 'learning_rate': 0.014713787785871615, 'dropout_rate': 0.8981498158391491, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.2548318594901287, 'min_weight_fraction_leaf': 0.17777174503118776, 'max_features': 'log2', 'min_impurity_decrease': 1.0237452134280835e-07, 'validation_fraction': 0.8712977301815288, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:44:17,373] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9693250170531542, 'learning_rate': 0.01944317613486205, 'dropout_rate': 0.3038950153557599, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.6002519915120403, 'min_weight_fraction_leaf': 0.27549593099040687, 'max_features': 'log2', 'min_impurity_decrease': 3.6437095962407636e-07, 'validation_fraction': 0.9333459733339855, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:44:48,257] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.8173404738572, 'learning_rate': 0.0014971421569913942, 'dropout_rate': 0.7985729747352956, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.2619251873249981, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 8.414265888676054e-07, 'validation_fraction': 0.9767098938730961, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:45:38,048] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7148940452980046, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.18937615988954143, 'n_estimators': 354, 'criterion': 'friedman_mse', 'ccp_alpha': 5.674168126071088, 'min_weight_fraction_leaf': 0.31372829413515113, 'max_features': 1, 'min_impurity_decrease': 2.0331516960635478e-07, 'validation_fraction': 0.8511405274059844, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:46:46,886] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.9972717132364954, 'learning_rate': 0.007518224603684854, 'dropout_rate': 0.10395224545815006, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 0.9954262036399765, 'min_weight_fraction_leaf': 0.20635279622001615, 'max_features': 'auto', 'min_impurity_decrease': 1.5953477935293164e-06, 'validation_fraction': 0.6208576267160641, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:47:55,598] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.640991020374617, 'learning_rate': 0.011217338838150685, 'dropout_rate': 0.3451514745217959, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.7138964750214933, 'min_weight_fraction_leaf': 0.2677913041979459, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8952644729851477, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:50:12,244] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.9241882336726334, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.20677435633856203, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.5902338753800525, 'min_weight_fraction_leaf': 0.4829675934647317, 'max_features': 'auto', 'min_impurity_decrease': 5.164460817361601e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6072961373390557
[I 2024-04-14 18:51:48,951] Trial 81 finished with value: 0.6053868642702614 and parameters: {'subsample': 0.9108542466963718, 'learning_rate': 0.009036269358876279, 'dropout_rate': 0.2796761891642441, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.4662820828873332, 'max_features': 'auto', 'min_impurity_decrease': 2.9616670039909406e-07, 'validation_fraction': 0.9436075044523529, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:53:48,377] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.8954792239433687, 'learning_rate': 0.004994374572973224, 'dropout_rate': 0.28119692682400105, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.2056104964041935, 'min_weight_fraction_leaf': 0.4154239703802, 'max_features': 'auto', 'min_impurity_decrease': 2.9347899125300254e-07, 'validation_fraction': 0.9415229967670153, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:55:36,952] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9453772015100563, 'learning_rate': 0.009142733646143604, 'dropout_rate': 0.22968230522988387, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.2036067284143, 'min_weight_fraction_leaf': 0.4480797785663371, 'max_features': 'auto', 'min_impurity_decrease': 2.4573289499864505e-07, 'validation_fraction': 0.8223778282619079, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:57:29,687] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.5840337378720031, 'learning_rate': 0.015683881096783557, 'dropout_rate': 0.3151491574193926, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.7892822718895267, 'min_weight_fraction_leaf': 0.43172585763109367, 'max_features': 'auto', 'min_impurity_decrease': 7.293866823339784e-05, 'validation_fraction': 0.9793171369033844, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5513307984790875

Fold 5 C-index: 0.5278969957081545
[I 2024-04-14 18:59:21,934] Trial 85 finished with value: 0.5817146767908369 and parameters: {'subsample': 0.8381406217696484, 'learning_rate': 0.06093323136306206, 'dropout_rate': 0.1485334587119987, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.011704477637461151, 'min_weight_fraction_leaf': 0.4720691906397277, 'max_features': 'sqrt', 'min_impurity_decrease': 9.978332296088644e-07, 'validation_fraction': 0.8663419975882438, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 18:59:32,356] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9706110926288294, 'learning_rate': 0.006257959338637904, 'dropout_rate': 0.3709658975304737, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.4978431536243799, 'min_weight_fraction_leaf': 0.45571733166164224, 'max_features': 'auto', 'min_impurity_decrease': 6.864266251098488e-07, 'validation_fraction': 0.9093181873424959, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:00:10,372] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.8719223063133476, 'learning_rate': 0.002880550222483567, 'dropout_rate': 0.2586755827269289, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 1.4238187376704579, 'min_weight_fraction_leaf': 0.3956887351012149, 'max_features': 'auto', 'min_impurity_decrease': 4.4582432432077124e-07, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:00:47,350] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.6830569710663442, 'learning_rate': 0.013709264558994303, 'dropout_rate': 0.8329903830094019, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 7.594079981917785, 'min_weight_fraction_leaf': 0.4856994098099038, 'max_features': 'auto', 'min_impurity_decrease': 1.3753252796604584e-07, 'validation_fraction': 0.9437956828508486, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:02:34,927] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.9129716272996254, 'learning_rate': 0.01699516784590996, 'dropout_rate': 0.18087235155064957, 'n_estimators': 414, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0191863395708485, 'min_weight_fraction_leaf': 0.15271636525917553, 'max_features': None, 'min_impurity_decrease': 1.947282338748394e-07, 'validation_fraction': 0.9659767731435556, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:04:26,535] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3551831112058997, 'learning_rate': 0.025984012094512135, 'dropout_rate': 0.12431503564534369, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.46673345025014124, 'min_weight_fraction_leaf': 0.24508638469664973, 'max_features': 'log2', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.29585084927667094, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:06:21,235] Trial 91 finished with value: 0.5 and parameters: {'subsample': 0.9121196916160231, 'learning_rate': 0.00897631455122704, 'dropout_rate': 0.21471821026192198, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.15965147655044054, 'min_weight_fraction_leaf': 0.46014660015317294, 'max_features': 'auto', 'min_impurity_decrease': 4.686018614915845e-07, 'validation_fraction': 0.3711905229919747, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:09:14,418] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.9534560134117849, 'learning_rate': 0.010356392157077806, 'dropout_rate': 0.2434088678374627, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.4415538255516217, 'max_features': 'auto', 'min_impurity_decrease': 3.39700671440376e-07, 'validation_fraction': 0.9391344731614609, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:10:56,117] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8926387307309837, 'learning_rate': 0.02102195955922062, 'dropout_rate': 0.21937611154635933, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.740874637434609, 'min_weight_fraction_leaf': 0.46926642495244203, 'max_features': 'auto', 'min_impurity_decrease': 1.3508552154161032e-07, 'validation_fraction': 0.9813983205957684, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:13:26,403] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.7555668093579782, 'learning_rate': 0.006490504575483759, 'dropout_rate': 0.17187474927510435, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.45248827707479033, 'min_weight_fraction_leaf': 0.4920238106734352, 'max_features': 'auto', 'min_impurity_decrease': 0.0015502959014071815, 'validation_fraction': 0.9010561440394491, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 8}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6673819742489271
[I 2024-04-14 19:16:05,868] Trial 95 finished with value: 0.6210137072528205 and parameters: {'subsample': 0.8523472503218436, 'learning_rate': 0.001063095567599786, 'dropout_rate': 0.32831410504800185, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.10883007468655126, 'min_weight_fraction_leaf': 0.4282230464947944, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:18:03,422] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.8435591355754584, 'learning_rate': 0.001251397162175833, 'dropout_rate': 0.3220878484956735, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.1977179096404618, 'min_weight_fraction_leaf': 0.4298592452698292, 'max_features': 1, 'min_impurity_decrease': 0.013680622942575243, 'validation_fraction': 0.9282173289832502, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:20:35,393] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8016053705978137, 'learning_rate': 0.003043162873853767, 'dropout_rate': 0.28303211035592896, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.2266992831326749, 'min_weight_fraction_leaf': 0.38392378237476354, 'max_features': 'auto', 'min_impurity_decrease': 0.0032862083702029487, 'validation_fraction': 0.9760032356861055, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:21:39,010] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8807317856071605, 'learning_rate': 0.00486407919341159, 'dropout_rate': 0.7211132442775035, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.876834202811247, 'min_weight_fraction_leaf': 0.4141510024046317, 'max_features': 0.1, 'min_impurity_decrease': 0.02298105889633881, 'validation_fraction': 0.9988710478147662, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.7112403100775194
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.5190114068441065

[I 2024-04-14 19:24:21,472] A new study created in memory with name: no-name-4507ac03-fce4-4027-8ace-0023c04c070e

Fold 5 C-index: 0.5901287553648069
[I 2024-04-14 19:24:21,414] Trial 99 finished with value: 0.5931411109869128 and parameters: {'subsample': 0.976275086451668, 'learning_rate': 0.012543335169828506, 'dropout_rate': 0.4577965489047534, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.00445672697292614, 'min_weight_fraction_leaf': 0.44456609279565923, 'max_features': 'auto', 'min_impurity_decrease': 0.0006104601971180063, 'validation_fraction': 0.9508877900290706, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.


* Best trial for C-index:
 FrozenTrial(number=9, state=TrialState.COMPLETE, values=[0.6859109422281264], datetime_start=datetime.datetime(2024, 4, 14, 17, 28, 32, 503474), datetime_complete=datetime.datetime(2024, 4, 14, 17, 29, 41, 346369), params={'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=9, value=None)


* Best Score for C-index:
 0.6859109422281264

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:25:13,046] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:25:34,066] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:26:04,635] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 19:27:20,782] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:27:49,865] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:27:56,011] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:28:30,447] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:28:38,655] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:28:39,831] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24609430579024427
Fold 2 IBS: 0.23040965656253537
Fold 3 IBS: 0.22864821526489268
Fold 4 IBS: 0.24089718710215188
Fold 5 IBS: 0.22863384669808964
[I 2024-04-14 19:30:32,466] Trial 9 finished with value: 0.2349366422835828 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316615258034594
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164904353219824
Fold 5 IBS: 0.2291762528827903
[I 2024-04-14 19:33:52,425] Trial 10 finished with value: 0.2356345378562359 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 19:37:27,507] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.247138870216024
Fold 2 IBS: 0.23184986270655478
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.2418709994354467
Fold 5 IBS: 0.22931420379900197
[I 2024-04-14 19:40:24,187] Trial 12 finished with value: 0.23582580107138096 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:41:30,584] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:43:49,025] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:45:14,312] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:46:25,622] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:48:31,220] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:49:29,532] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:49:41,263] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:51:42,197] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24707615266280916
Fold 2 IBS: 0.2319847418263816
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.24189505261981767
Fold 5 IBS: 0.22923216203360366
[I 2024-04-14 19:53:47,499] Trial 21 finished with value: 0.23582195939603873 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24649489189484391
Fold 2 IBS: 0.23082360160625934
Fold 3 IBS: 0.2287726368290018

Fold 4 IBS: 0.24123178555157707
Fold 5 IBS: 0.22878244652881227
[I 2024-04-14 19:56:10,178] Trial 22 finished with value: 0.2352210724820989 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-14 19:58:24,530] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:59:46,535] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:01:02,351] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:02:11,341] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:02:19,122] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:02:40,412] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:03:51,094] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:05:42,753] Trial 30 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24669405450794213
Fold 2 IBS: 0.23161054906241668
Fold 3 IBS: 0.22885749682655868
Fold 4 IBS: 0.2415375526987621
Fold 5 IBS: 0.22900046780800146
[I 2024-04-14 20:07:42,799] Trial 31 finished with value: 0.23554002418073622 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24558927769654496
Fold 2 IBS: 0.23023682871310253
Fold 3 IBS: 0.22940781736456844
Fold 4 IBS: 0.24024202122958146
Fold 5 IBS: 0.22844870595001
[I 2024-04-14 20:09:48,586] Trial 32 finished with value: 0.2347849301907615 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115

Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:10:59,312] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:12:20,993] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:12:48,546] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:14:20,967] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:14:31,448] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:15:07,208] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:16:00,726] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:17:20,514] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24564975054404245
Fold 2 IBS: 0.22980985720122352
Fold 3 IBS: 0.22862944699148766
Fold 4 IBS: 0.24021072098294424
Fold 5 IBS: 0.228413740712783
[I 2024-04-14 20:20:01,670] Trial 41 finished with value: 0.23454270328649618 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.2457772971067935
Fold 2 IBS: 0.23000299564240484
Fold 3 IBS: 0.2283274561934457
Fold 4 IBS: 0.24023228941042038
Fold 5 IBS: 0.22843286628628326
[I 2024-04-14 20:22:56,909] Trial 42 finished with value: 0.23455458092786952 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:25:30,845] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711

Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:27:36,385] Trial 44 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:28:07,711] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24711544189088316
Fold 2 IBS: 0.23191168662951947
Fold 3 IBS: 0.22890472697929887
Fold 4 IBS: 0.24185408977590042
Fold 5 IBS: 0.22932654563425428
[I 2024-04-14 20:29:45,856] Trial 46 finished with value: 0.23582249818197126 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:30:40,476] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:30:41,105] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:31:10,970] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:32:25,322] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24627850817996183
Fold 2 IBS: 0.2309014040449158
Fold 3 IBS: 0.22910566527183993
Fold 4 IBS: 0.24089118983895721
Fold 5 IBS: 0.22880091863597468
[I 2024-04-14 20:34:29,496] Trial 51 finished with value: 0.2351955371943299 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24650271358250436
Fold 2 IBS: 0.23102415345536428
Fold 3 IBS: 0.22863853234442286
Fold 4 IBS: 0.2411028633234996
Fold 5 IBS: 0.22892194464198923
[I 2024-04-14 20:36:51,142] Trial 52 finished with value: 0.23523804146955607 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:38:44,291] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:40:39,381] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118

Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:42:12,054] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:43:29,102] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:44:44,757] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:46:17,836] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:47:29,087] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:48:26,371] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.246792274967983
Fold 2 IBS: 0.23161964216377484
Fold 3 IBS: 0.22888176928337703
Fold 4 IBS: 0.24155890986096298
Fold 5 IBS: 0.22907544730443408
[I 2024-04-14 20:50:39,007] Trial 61 finished with value: 0.2355856087161064 and parameters: {'subsample': 0.9918985385533109, 'learning_rate': 0.005743016439014149, 'dropout_rate': 0.28747233681343587, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.16038675829082302, 'max_features': 'auto', 'min_impurity_decrease': 2.9513412376244623e-06, 'validation_fraction': 0.9751691260171886, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24556197891151196
Fold 2 IBS: 0.22971971502308358
Fold 3 IBS: 0.2284720848338911
Fold 4 IBS: 0.23983435075087522
Fold 5 IBS: 0.22821110501120903
[I 2024-04-14 20:52:47,798] Trial 62 finished with value: 0.2343598469061142 and parameters: {'subsample': 0.9574333176186867, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.18564670695369828, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 7.301362864132341e-06, 'validation_fraction': 0.9275594296798731, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:53:25,844] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9611556459137681, 'learning_rate': 0.009885633504393494, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.40714661625851756, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:54:59,880] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9996724029846231, 'learning_rate': 0.02055321577299183, 'dropout_rate': 0.19552211208698841, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.21641604442433082, 'max_features': 'log2', 'min_impurity_decrease': 7.250192360253865e-06, 'validation_fraction': 0.9272295835693174, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:56:58,632] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.919652344200739, 'learning_rate': 0.014473083324943868, 'dropout_rate': 0.16799591889422819, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.351957844105687, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118

Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:58:48,872] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8489175059797514, 'learning_rate': 0.008448226967076113, 'dropout_rate': 0.12725750793823018, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.893877768639663, 'min_weight_fraction_leaf': 0.2702972473075093, 'max_features': 'auto', 'min_impurity_decrease': 7.586810829424823e-05, 'validation_fraction': 0.8971088342813041, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:00:23,632] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9594402941587806, 'learning_rate': 0.0039206688180527, 'dropout_rate': 0.25338876644885766, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1787054950134963, 'min_weight_fraction_leaf': 0.29081789854917856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.005146223539456e-06, 'validation_fraction': 0.9662549030476638, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:02:22,649] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.885928079608526, 'learning_rate': 0.01958784726286755, 'dropout_rate': 0.3188313005563145, 'n_estimators': 463, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.24383256255051056, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.99982951588149, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724158711521824
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:04:14,396] Trial 69 finished with value: 0.23592674084605642 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.011561561592981577, 'dropout_rate': 0.2251092355441408, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.30419922755720963, 'min_weight_fraction_leaf': 0.1929901790072115, 'max_features': 'auto', 'min_impurity_decrease': 1.6729804035130242e-06, 'validation_fraction': 0.8450602738806452, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.2451491152796615
Fold 2 IBS: 0.22927148757582394
Fold 3 IBS: 0.22855190516165128
Fold 4 IBS: 0.23973639516624012
Fold 5 IBS: 0.2277940457619145
[I 2024-04-14 21:05:42,858] Trial 70 finished with value: 0.2341005897890583 and parameters: {'subsample': 0.7327319228005876, 'learning_rate': 0.016866948400001296, 'dropout_rate': 0.17898373444054652, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.01005746855001105, 'min_weight_fraction_leaf': 0.3640638074298326, 'max_features': None, 'min_impurity_decrease': 9.787021311876353e-06, 'validation_fraction': 0.7926074734474466, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24549206821547404
Fold 2 IBS: 0.23024967197031007
Fold 3 IBS: 0.22871431230048478
Fold 4 IBS: 0.2407512171757705
Fold 5 IBS: 0.22802577910859287
[I 2024-04-14 21:07:00,159] Trial 71 finished with value: 0.23464660975412643 and parameters: {'subsample': 0.6580825781997457, 'learning_rate': 0.016629440896307336, 'dropout_rate': 0.17328978363215145, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.4078164122376511, 'max_features': None, 'min_impurity_decrease': 3.981143358338061e-06, 'validation_fraction': 0.9287047300321795, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.2455926669408777
Fold 2 IBS: 0.23018285219722445
Fold 3 IBS: 0.2286735121245035
Fold 4 IBS: 0.24063817521529354
Fold 5 IBS: 0.22817935594806837
[I 2024-04-14 21:08:06,504] Trial 72 finished with value: 0.2346533124851935 and parameters: {'subsample': 0.6433252951647072, 'learning_rate': 0.015406216424115876, 'dropout_rate': 0.174165060267479, 'n_estimators': 372, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.4068999670923105, 'max_features': None, 'min_impurity_decrease': 9.143853678722166e-06, 'validation_fraction': 0.8050869160635631, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:09:24,785] Trial 73 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6415805639130162, 'learning_rate': 0.016957190070749008, 'dropout_rate': 0.1022557442615895, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.7340527434897883, 'min_weight_fraction_leaf': 0.41441154927232665, 'max_features': None, 'min_impurity_decrease': 2.8366918098535655e-05, 'validation_fraction': 0.8120762455660575, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:10:42,548] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5890037439982243, 'learning_rate': 0.02388572819447024, 'dropout_rate': 0.14309816759091956, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.33550183960235097, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': None, 'min_impurity_decrease': 1.1962100920927531e-05, 'validation_fraction': 0.6568048355299513, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:11:48,030] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6875143177223235, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.18219557324018512, 'n_estimators': 365, 'criterion': 'squared_error', 'ccp_alpha': 0.6626240923578504, 'min_weight_fraction_leaf': 0.3667876525646178, 'max_features': None, 'min_impurity_decrease': 8.996538110684365e-06, 'validation_fraction': 0.7854387247082943, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:13:01,265] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6310903661182281, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.16070017323462005, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.43428922098282363, 'max_features': None, 'min_impurity_decrease': 4.880048865700701e-06, 'validation_fraction': 0.7567620429516432, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:13:51,430] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7234820637720293, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.19884799526452568, 'n_estimators': 302, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.4027406894595495, 'max_features': None, 'min_impurity_decrease': 5.35591590419612e-07, 'validation_fraction': 0.8758106078120852, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.2341005897890583.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:14:49,993] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6708593402641205, 'learning_rate': 0.02742354559286264, 'dropout_rate': 0.12642193192647372, 'n_estimators': 329, 'criterion': 'squared_error', 'ccp_alpha': 0.2456295975030462, 'min_weight_fraction_leaf': 0.3629864105918121, 'max_features': None, 'min_impurity_decrease': 0.00015140034318578482, 'validation_fraction': 0.6173345703129903, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.2422361212718552
Fold 2 IBS: 0.22571122387519038
Fold 3 IBS: 0.22923653706299701
Fold 4 IBS: 0.2398268927530749
Fold 5 IBS: 0.2262157333144423
[I 2024-04-14 21:16:04,958] Trial 79 finished with value: 0.23264530165551198 and parameters: {'subsample': 0.6068487747881667, 'learning_rate': 0.08690058608305122, 'dropout_rate': 0.2202274723306249, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 0.0067848986270052205, 'min_weight_fraction_leaf': 0.442958513823715, 'max_features': None, 'min_impurity_decrease': 3.159003046563375e-05, 'validation_fraction': 0.6916250922837899, 'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.23264530165551198.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:17:28,759] Trial 80 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7431452433208791, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.22085807342340602, 'n_estimators': 416, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0208718228969498, 'min_weight_fraction_leaf': 0.4578321580005691, 'max_features': None, 'min_impurity_decrease': 6.219311571999601e-05, 'validation_fraction': 0.8063818584332632, 'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 1}. Best is trial 79 with value: 0.23264530165551198.
Fold 1 IBS: 0.24125284361122407
Fold 2 IBS: 0.22420513730110872
Fold 3 IBS: 0.22885288425326455
Fold 4 IBS: 0.23690618478087347
Fold 5 IBS: 0.22511743194475423
[I 2024-04-14 21:18:55,753] Trial 81 finished with value: 0.23126689637824502 and parameters: {'subsample': 0.6143582554906275, 'learning_rate': 0.09196546766753708, 'dropout_rate': 0.17154122956253648, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.025343486133480444, 'min_weight_fraction_leaf': 0.422923580742715, 'max_features': None, 'min_impurity_decrease': 3.0516618185477245e-05, 'validation_fraction': 0.6839523176227551, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:19:56,881] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6156671358096751, 'learning_rate': 0.09024426530842436, 'dropout_rate': 0.17324784818426983, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.5340758841421452, 'min_weight_fraction_leaf': 0.44660441203015316, 'max_features': None, 'min_impurity_decrease': 3.596173256287884e-05, 'validation_fraction': 0.6862764853454645, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:21:26,991] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.59035693752921, 'learning_rate': 0.08769222490327029, 'dropout_rate': 0.13695127070120913, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.29851318725213727, 'min_weight_fraction_leaf': 0.4224884983147852, 'max_features': None, 'min_impurity_decrease': 1.7043338510624665e-05, 'validation_fraction': 0.708718433392457, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:22:55,726] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5692772731117001, 'learning_rate': 0.09337007500374273, 'dropout_rate': 0.19406549234317277, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 0.7908292561402825, 'min_weight_fraction_leaf': 0.3834871581332913, 'max_features': None, 'min_impurity_decrease': 2.8122570662289344e-05, 'validation_fraction': 0.9095186934735143, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.2424477259260394
Fold 2 IBS: 0.22638240973032056
Fold 3 IBS: 0.22825860156887076
Fold 4 IBS: 0.23805120772877988
Fold 5 IBS: 0.22643734649583214
[I 2024-04-14 21:23:07,602] Trial 85 finished with value: 0.23231545828996855 and parameters: {'subsample': 0.6445419753261435, 'learning_rate': 0.06087928731142127, 'dropout_rate': 0.24518342938103005, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.011216734292662366, 'min_weight_fraction_leaf': 0.4043905469812696, 'max_features': None, 'min_impurity_decrease': 1.493590751470447e-05, 'validation_fraction': 0.5742595190050698, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:23:20,374] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5345448615448432, 'learning_rate': 0.06299476346040861, 'dropout_rate': 0.16060697827295928, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.62448544277789, 'min_weight_fraction_leaf': 0.4834818041059262, 'max_features': None, 'min_impurity_decrease': 1.4511890623038534e-05, 'validation_fraction': 0.531307128627143, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24212442159072736
Fold 2 IBS: 0.22535780949238718
Fold 3 IBS: 0.22839243624354327
Fold 4 IBS: 0.2376426744658837
Fold 5 IBS: 0.22566811629124223
[I 2024-04-14 21:24:25,145] Trial 87 finished with value: 0.23183709161675675 and parameters: {'subsample': 0.6482886513725954, 'learning_rate': 0.08056151243791008, 'dropout_rate': 0.2600398597942537, 'n_estimators': 374, 'criterion': 'squared_error', 'ccp_alpha': 0.01745937818789605, 'min_weight_fraction_leaf': 0.40356411913419793, 'max_features': None, 'min_impurity_decrease': 9.949241277389102e-06, 'validation_fraction': 0.5582433992805256, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:24:31,127] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6879348852579991, 'learning_rate': 0.08209035744510738, 'dropout_rate': 0.24522201083374043, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.2983993026610602, 'min_weight_fraction_leaf': 0.3774672254272644, 'max_features': None, 'min_impurity_decrease': 5.4011226362110275e-06, 'validation_fraction': 0.568843188657281, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:24:42,226] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6555693108457097, 'learning_rate': 0.08348043724232247, 'dropout_rate': 0.1018982518393906, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.3922659564335438, 'max_features': None, 'min_impurity_decrease': 1.84353439530822e-05, 'validation_fraction': 0.4550485507485021, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:25:00,614] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6142534760575815, 'learning_rate': 0.07977183656340979, 'dropout_rate': 0.21675268812215465, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.43931856433894717, 'max_features': None, 'min_impurity_decrease': 4.509029295159726e-05, 'validation_fraction': 0.6255054030515286, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 8}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24098581972087948
Fold 2 IBS: 0.22316717801046412
Fold 3 IBS: 0.22816422552337945
Fold 4 IBS: 0.23597578008775205
Fold 5 IBS: 0.22473523040311924
[I 2024-04-14 21:26:06,543] Trial 91 finished with value: 0.23060564674911882 and parameters: {'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24718434152159066
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22893463205005193
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22935673483794422
[I 2024-04-14 21:27:08,829] Trial 92 finished with value: 0.23589807288135617 and parameters: {'subsample': 0.5057005214243391, 'learning_rate': 0.09883062819528839, 'dropout_rate': 0.2685922627272655, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.19747740396734947, 'min_weight_fraction_leaf': 0.4679716753672616, 'max_features': None, 'min_impurity_decrease': 1.0671241077127033e-05, 'validation_fraction': 0.5950373519486988, 'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:28:22,404] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5538299448336005, 'learning_rate': 0.0868661642219975, 'dropout_rate': 0.20334468934521452, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.5267007889739713, 'min_weight_fraction_leaf': 0.42336750014808644, 'max_features': None, 'min_impurity_decrease': 8.867094040313709e-05, 'validation_fraction': 0.520690018337254, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:28:38,354] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5702665640439277, 'learning_rate': 0.09449632562825357, 'dropout_rate': 0.13870793304287105, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.8492587817200913, 'min_weight_fraction_leaf': 0.348550363613902, 'max_features': None, 'min_impurity_decrease': 6.826272330503328e-06, 'validation_fraction': 0.5659130589721448, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:29:36,326] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7076939032161012, 'learning_rate': 0.09136733918164754, 'dropout_rate': 0.18672112900745633, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.561945255260577, 'min_weight_fraction_leaf': 0.40234945062950195, 'max_features': None, 'min_impurity_decrease': 2.5588389290979514e-05, 'validation_fraction': 0.4537896994588092, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:30:22,054] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6655863757457166, 'learning_rate': 0.08941626520289533, 'dropout_rate': 0.2411336203156454, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.23565160101206817, 'min_weight_fraction_leaf': 0.42995214161407835, 'max_features': None, 'min_impurity_decrease': 3.937366373268103e-06, 'validation_fraction': 0.6733503587022674, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 16}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:30:23,315] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5830397464244746, 'learning_rate': 0.09649030637314325, 'dropout_rate': 0.1548001251941624, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 1.0632556006826448, 'min_weight_fraction_leaf': 0.4466142202394081, 'max_features': 1, 'min_impurity_decrease': 9.319522810040033e-06, 'validation_fraction': 0.49048790135092346, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:31:40,098] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6220799571230118, 'learning_rate': 0.08529012031921517, 'dropout_rate': 0.2588962329024949, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3323104826759427, 'min_weight_fraction_leaf': 0.4570033067989539, 'max_features': None, 'min_impurity_decrease': 1.5778942534009964e-05, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 3}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:32:04,104] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.07813501740629669, 'dropout_rate': 0.30318261654818046, 'n_estimators': 242, 'criterion': 'squared_error', 'ccp_alpha': 1.7079733343503498, 'min_weight_fraction_leaf': 0.32269779176244495, 'max_features': 0.1, 'min_impurity_decrease': 1.276230329676773e-06, 'validation_fraction': 0.36954438153697, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.23060564674911882.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.23060564674911882], datetime_start=datetime.datetime(2024, 4, 14, 21, 25, 0, 622112), datetime_complete=datetime.datetime(2024, 4, 14, 21, 26, 6, 542765), params={'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.23060564674911882

In [66]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.686
train_ibs:  0.231

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.07426378544613033,
                                 criterion='squared_error',
                                 dropout_rate=0.28125955124323376,
                                 learning_rate=0.013102111413618,
                                 max_features='auto', max_leaf_nodes=16,
                                 min_impurity_decrease=1.4994028685178666e-07,
                                 min_samples_leaf=10,
                                 min_weight_fraction_leaf=0.27579636299120275,
                                 n_estimators=406, random_state=123,
                                 subsample=0.6059965408578151,
                                 validation_fraction=0.6359003593513561)

C-index score: 0.518

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03787089343697578,
                                 criterion='squared_error',
                                 dropout_rate=0.18479264516541616,
                                 learning_rate=0.09426091382038485, max_depth=2,
                                 max_leaf_nodes=6,
                                 min_impurity_decrease=7.4293259533530295e-06,
                                 min_samples_leaf=7, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4036747584607865,
                                 n_estimators=390, random_state=123,
                                 subsample=0.579213280645811,
                                 validation_fraction=0.5325834925366492)

IBS: 0.23

In [70]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [71]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [72]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 21:32:34,002] A new study created in memory with name: no-name-43934bc3-ce57-42b5-9517-7f78e14e2d11

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5446808510638298
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:32:40,828] Trial 0 finished with value: 0.5527485138412043 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5527485138412043.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:33:17,050] Trial 1 finished with value: 0.5519227768727208 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.5527485138412043.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:33:32,077] Trial 2 finished with value: 0.5624399976284654 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.5624399976284654.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.44106463878326996
Fold 5 C-index: 0.5064377682403434
[I 2024-04-14 21:33:46,602] Trial 3 finished with value: 0.5525125203346043 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.5624399976284654.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:34:04,838] Trial 4 finished with value: 0.5601426033190571 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 2 with value: 0.5624399976284654.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5150214592274678
[I 2024-04-14 21:34:33,025] Trial 5 finished with value: 0.552121462747254 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 2 with value: 0.5624399976284654.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5446808510638298
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:34:45,934] Trial 6 finished with value: 0.5527052759400956 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 2 with value: 0.5624399976284654.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.4372623574144487
Fold 5 C-index: 0.5321888412017167
[I 2024-04-14 21:34:49,012] Trial 7 finished with value: 0.5628275007401912 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.5628275007401912.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:35:03,785] Trial 8 finished with value: 0.5607773835249888 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.5628275007401912.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:35:40,416] Trial 9 finished with value: 0.5550180717611204 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.5628275007401912.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:35:42,406] Trial 10 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:35:42,808] Trial 11 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:35:46,904] Trial 12 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:35:47,372] Trial 13 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.7324371247382785, 'n_estimators': 3, 'learning_rate': 0.007730532223257889}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:35:53,874] Trial 14 finished with value: 0.5600935950042645 and parameters: {'subsample': 0.8619663815733164, 'dropout_rate': 0.9788958362896205, 'n_estimators': 102, 'learning_rate': 0.09964313305557901}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:35:55,055] Trial 15 finished with value: 0.5577031567572525 and parameters: {'subsample': 0.8897480564271555, 'dropout_rate': 0.7907695329663884, 'n_estimators': 13, 'learning_rate': 0.0020295313566686345}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:36:17,273] Trial 16 finished with value: 0.5596350675663478 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.6024217769414767, 'n_estimators': 293, 'learning_rate': 0.08820363883892024}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5278969957081545
[I 2024-04-14 21:36:24,292] Trial 17 finished with value: 0.5624913385202017 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 99, 'learning_rate': 0.017248404573838205}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5150214592274678
[I 2024-04-14 21:36:48,513] Trial 18 finished with value: 0.5538778414876118 and parameters: {'subsample': 0.6236867669661592, 'dropout_rate': 0.8129791758744914, 'n_estimators': 336, 'learning_rate': 0.08269288753998026}. Best is trial 10 with value: 0.5648744714982884.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:36:58,035] Trial 19 finished with value: 0.5584999695062565 and parameters: {'subsample': 0.8350722272141606, 'dropout_rate': 0.9949834936920623, 'n_estimators': 134, 'learning_rate': 0.036212385990032875}. Best is trial 10 with value: 0.5648744714982884.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:02,497] Trial 20 finished with value: 0.5656712842472924 and parameters: {'subsample': 0.9139336698304192, 'dropout_rate': 0.6485024664008028, 'n_estimators': 61, 'learning_rate': 0.017331004877487094}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:06,664] Trial 21 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.952235198850602, 'dropout_rate': 0.6348160376507914, 'n_estimators': 64, 'learning_rate': 0.01359953789503817}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:07,031] Trial 22 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.925986120267062, 'dropout_rate': 0.7574824382188379, 'n_estimators': 2, 'learning_rate': 0.0017219364207917663}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:11,106] Trial 23 finished with value: 0.5553343374607949 and parameters: {'subsample': 0.7976927124866411, 'dropout_rate': 0.5091024685115088, 'n_estimators': 63, 'learning_rate': 0.023697800010162032}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:23,572] Trial 24 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9243004910961382, 'dropout_rate': 0.6765112542858653, 'n_estimators': 133, 'learning_rate': 0.013367442333115934}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:27,759] Trial 25 finished with value: 0.558478350555702 and parameters: {'subsample': 0.8090056214736048, 'dropout_rate': 0.8308749817927443, 'n_estimators': 42, 'learning_rate': 0.039844622636515586}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:38,795] Trial 26 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9958790429869763, 'dropout_rate': 0.5707562654379044, 'n_estimators': 87, 'learning_rate': 0.024080757723140073}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:50,016] Trial 27 finished with value: 0.5632808460002804 and parameters: {'subsample': 0.9079435489386305, 'dropout_rate': 0.9020442419409058, 'n_estimators': 154, 'learning_rate': 0.030307532796347948}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:52,245] Trial 28 finished with value: 0.5548736369673704 and parameters: {'subsample': 0.6692336821130495, 'dropout_rate': 0.7188416121680791, 'n_estimators': 33, 'learning_rate': 0.011688059322658779}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:37:58,198] Trial 29 finished with value: 0.5576489056764693 and parameters: {'subsample': 0.7912448504145874, 'dropout_rate': 0.4175950896276197, 'n_estimators': 90, 'learning_rate': 0.06046208382653473}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.4600760456273764
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:38:15,762] Trial 30 finished with value: 0.5529977264515101 and parameters: {'subsample': 0.5936384513688024, 'dropout_rate': 0.6488076006868507, 'n_estimators': 242, 'learning_rate': 0.0466330793412643}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:38:21,688] Trial 31 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9887925631922994, 'dropout_rate': 0.7073420850200933, 'n_estimators': 68, 'learning_rate': 0.09269964744227656}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:38:24,605] Trial 32 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9515456378310003, 'dropout_rate': 0.7694905745846496, 'n_estimators': 36, 'learning_rate': 0.0996485424783721}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:38:33,697] Trial 33 finished with value: 0.5616329694214892 and parameters: {'subsample': 0.8604456834692097, 'dropout_rate': 0.5270256213733028, 'n_estimators': 134, 'learning_rate': 0.08441835992205494}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:38:35,421] Trial 34 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9963772319317616, 'dropout_rate': 0.6946124206633987, 'n_estimators': 23, 'learning_rate': 0.0704186861674015}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:38:40,008] Trial 35 finished with value: 0.553838200944679 and parameters: {'subsample': 0.7053994068737189, 'dropout_rate': 0.616147598070681, 'n_estimators': 63, 'learning_rate': 0.08097243966295013}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:10,439] Trial 36 finished with value: 0.5552584674294574 and parameters: {'subsample': 0.7527724803090833, 'dropout_rate': 0.45936238080967423, 'n_estimators': 421, 'learning_rate': 0.089556399826433}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:18,475] Trial 37 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9418473908880376, 'dropout_rate': 0.8374055765137145, 'n_estimators': 113, 'learning_rate': 0.07677405503763898}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.6744186046511628

Fold 3 C-index: 0.3872340425531915
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.6008583690987125
[I 2024-04-14 21:39:18,814] Trial 38 finished with value: 0.5185776732437984 and parameters: {'subsample': 0.3866096773460963, 'dropout_rate': 0.3010386389757013, 'n_estimators': 1, 'learning_rate': 0.06351044805702724}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:31,103] Trial 39 finished with value: 0.5576272867259149 and parameters: {'subsample': 0.8328204942141013, 'dropout_rate': 0.8890898259545601, 'n_estimators': 168, 'learning_rate': 0.0969464828585424}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:36,331] Trial 40 finished with value: 0.563259227049726 and parameters: {'subsample': 0.8986446486678774, 'dropout_rate': 0.1585668555692103, 'n_estimators': 78, 'learning_rate': 0.007049618565017432}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:38,259] Trial 41 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9994962321376948, 'dropout_rate': 0.7390864202123838, 'n_estimators': 26, 'learning_rate': 0.01967671626309114}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:38,580] Trial 42 finished with value: 0.5648744714982884 and parameters: {'subsample': 0.9583138414760716, 'dropout_rate': 0.7317748131450376, 'n_estimators': 1, 'learning_rate': 0.009485852037742007}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:41,606] Trial 43 finished with value: 0.5640992776998388 and parameters: {'subsample': 0.9594135942894225, 'dropout_rate': 0.6686046188359859, 'n_estimators': 47, 'learning_rate': 0.005082923674803326}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:39:43,037] Trial 44 finished with value: 0.5640776587492844 and parameters: {'subsample': 0.894753045184345, 'dropout_rate': 0.5791041008697428, 'n_estimators': 21, 'learning_rate': 0.0172196274964002}. Best is trial 20 with value: 0.5656712842472924.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.5064377682403434
[I 2024-04-14 21:39:56,476] Trial 45 finished with value: 0.5695979266625014 and parameters: {'subsample': 0.12780258661132204, 'dropout_rate': 0.7893741129870863, 'n_estimators': 203, 'learning_rate': 0.029621428102078778}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:40:08,793] Trial 46 finished with value: 0.5659115133123351 and parameters: {'subsample': 0.14228367425517763, 'dropout_rate': 0.7983782719337911, 'n_estimators': 187, 'learning_rate': 0.02900937605640456}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:40:25,054] Trial 47 finished with value: 0.5611086104589622 and parameters: {'subsample': 0.15691736786929125, 'dropout_rate': 0.9300042878121526, 'n_estimators': 206, 'learning_rate': 0.02803247414153675}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 21:40:43,088] Trial 48 finished with value: 0.5618669007590771 and parameters: {'subsample': 0.22660911860351332, 'dropout_rate': 0.8037153323157736, 'n_estimators': 246, 'learning_rate': 0.035676142291946336}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:41:01,189] Trial 49 finished with value: 0.5607660570548316 and parameters: {'subsample': 0.2535939390289473, 'dropout_rate': 0.8559914578437632, 'n_estimators': 272, 'learning_rate': 0.05493253231680785}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 21:41:17,405] Trial 50 finished with value: 0.5569554957441377 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.9501582476866339, 'n_estimators': 226, 'learning_rate': 0.027183201403154097}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:41:31,564] Trial 51 finished with value: 0.5598626776603608 and parameters: {'subsample': 0.11363146727029128, 'dropout_rate': 0.7774672066736446, 'n_estimators': 189, 'learning_rate': 0.042317509615855856}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:41:56,372] Trial 52 finished with value: 0.560450342185048 and parameters: {'subsample': 0.18563741796771815, 'dropout_rate': 0.7863760117023808, 'n_estimators': 329, 'learning_rate': 0.018434239225521766}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.5064377682403434
[I 2024-04-14 21:42:08,895] Trial 53 finished with value: 0.5559851969950691 and parameters: {'subsample': 0.3185066051347939, 'dropout_rate': 0.6502138742146315, 'n_estimators': 165, 'learning_rate': 0.0364885257658466}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5150214592274678
[I 2024-04-14 21:42:15,989] Trial 54 finished with value: 0.55412018910631 and parameters: {'subsample': 0.4063821242195994, 'dropout_rate': 0.699216794602179, 'n_estimators': 105, 'learning_rate': 0.04893045633977665}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 21:42:19,199] Trial 55 finished with value: 0.5464131250783344 and parameters: {'subsample': 0.15818417465613624, 'dropout_rate': 0.7567555885828444, 'n_estimators': 49, 'learning_rate': 0.09304040472328005}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.44106463878326996
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:42:40,135] Trial 56 finished with value: 0.5562315658149994 and parameters: {'subsample': 0.45063993751084946, 'dropout_rate': 0.6124944137985119, 'n_estimators': 297, 'learning_rate': 0.03228651744185966}. Best is trial 45 with value: 0.5695979266625014.

Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:42:51,328] Trial 57 finished with value: 0.5654264770648157 and parameters: {'subsample': 0.19754759182634346, 'dropout_rate': 0.8672507660963715, 'n_estimators': 142, 'learning_rate': 0.020570994628935912}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.4892703862660944
[I 2024-04-14 21:43:04,723] Trial 58 finished with value: 0.5634817049303217 and parameters: {'subsample': 0.18380027617701572, 'dropout_rate': 0.8655883481390085, 'n_estimators': 187, 'learning_rate': 0.021570486814933662}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.4600760456273764
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:43:13,954] Trial 59 finished with value: 0.5682825814153751 and parameters: {'subsample': 0.12801144520140487, 'dropout_rate': 0.8236257550887308, 'n_estimators': 151, 'learning_rate': 0.026703694844736357}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 21:43:27,244] Trial 60 finished with value: 0.5611701668086706 and parameters: {'subsample': 0.13342950482091567, 'dropout_rate': 0.9373989180429689, 'n_estimators': 157, 'learning_rate': 0.014516573779591911}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.4892703862660944
[I 2024-04-14 21:43:44,915] Trial 61 finished with value: 0.5660859904196085 and parameters: {'subsample': 0.1958466154630909, 'dropout_rate': 0.8736082489793588, 'n_estimators': 225, 'learning_rate': 0.027387848141367126}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.44106463878326996
Fold 5 C-index: 0.48497854077253216
[I 2024-04-14 21:44:02,612] Trial 62 finished with value: 0.552758262573569 and parameters: {'subsample': 0.2165700553492545, 'dropout_rate': 0.8195102821644112, 'n_estimators': 231, 'learning_rate': 0.02646561386448569}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.5107296137339056
[I 2024-04-14 21:44:17,748] Trial 63 finished with value: 0.5595268786952642 and parameters: {'subsample': 0.2813395381974224, 'dropout_rate': 0.8729721769476583, 'n_estimators': 217, 'learning_rate': 0.03237482419728113}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 21:44:27,632] Trial 64 finished with value: 0.5692151390029954 and parameters: {'subsample': 0.2066527640257746, 'dropout_rate': 0.838367094727635, 'n_estimators': 141, 'learning_rate': 0.022919029013708552}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:44:38,025] Trial 65 finished with value: 0.565118297921507 and parameters: {'subsample': 0.19858245307456904, 'dropout_rate': 0.9216323924604358, 'n_estimators': 149, 'learning_rate': 0.021399979528935843}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.467680608365019
Fold 5 C-index: 0.4892703862660944
[I 2024-04-14 21:44:52,971] Trial 66 finished with value: 0.5633689111595916 and parameters: {'subsample': 0.14736823929305498, 'dropout_rate': 0.8401801864547923, 'n_estimators': 194, 'learning_rate': 0.024966202910767683}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:45:03,186] Trial 67 finished with value: 0.5670053650381383 and parameters: {'subsample': 0.24891598889450917, 'dropout_rate': 0.9757519629413337, 'n_estimators': 122, 'learning_rate': 0.016268819016259838}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:45:11,427] Trial 68 finished with value: 0.5685410151103522 and parameters: {'subsample': 0.24797520734133, 'dropout_rate': 0.9678102587123965, 'n_estimators': 124, 'learning_rate': 0.015383319060469537}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:45:19,800] Trial 69 finished with value: 0.5684619879981564 and parameters: {'subsample': 0.2568313910961259, 'dropout_rate': 0.9685866606772888, 'n_estimators': 119, 'learning_rate': 0.03841898605191387}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.5150214592274678
[I 2024-04-14 21:45:29,083] Trial 70 finished with value: 0.5630290468393613 and parameters: {'subsample': 0.2790626738498267, 'dropout_rate': 0.9651977730684743, 'n_estimators': 126, 'learning_rate': 0.036302713293624174}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:45:39,390] Trial 71 finished with value: 0.5670053650381383 and parameters: {'subsample': 0.2435958120872314, 'dropout_rate': 0.978708005200783, 'n_estimators': 120, 'learning_rate': 0.030866149059894335}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 21:45:47,148] Trial 72 finished with value: 0.5685236713346997 and parameters: {'subsample': 0.2317385413325796, 'dropout_rate': 0.9712281429349049, 'n_estimators': 107, 'learning_rate': 0.033816290479812744}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:45:55,106] Trial 73 finished with value: 0.5670053650381383 and parameters: {'subsample': 0.24824912898484444, 'dropout_rate': 0.9945214406458355, 'n_estimators': 121, 'learning_rate': 0.0391366178459259}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.4600760456273764
Fold 5 C-index: 0.5107296137339056
[I 2024-04-14 21:46:02,717] Trial 74 finished with value: 0.5658575755220346 and parameters: {'subsample': 0.303691206550079, 'dropout_rate': 0.9675596393586718, 'n_estimators': 96, 'learning_rate': 0.0440037783264632}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.44106463878326996

Fold 5 C-index: 0.5021459227467812
[I 2024-04-14 21:46:10,845] Trial 75 finished with value: 0.5661442627016238 and parameters: {'subsample': 0.24074478776797287, 'dropout_rate': 0.9016181428963833, 'n_estimators': 112, 'learning_rate': 0.03100383657804165}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.44106463878326996
Fold 5 C-index: 0.5150214592274678
[I 2024-04-14 21:46:18,115] Trial 76 finished with value: 0.5587342141343272 and parameters: {'subsample': 0.34756027510282617, 'dropout_rate': 0.9972638386058171, 'n_estimators': 83, 'learning_rate': 0.03413018545658287}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.47639484978540775
[I 2024-04-14 21:46:29,426] Trial 77 finished with value: 0.5566613169919754 and parameters: {'subsample': 0.10058571485725418, 'dropout_rate': 0.9192118898049368, 'n_estimators': 144, 'learning_rate': 0.04027670782929123}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5107296137339056
[I 2024-04-14 21:46:41,792] Trial 78 finished with value: 0.5619135925972653 and parameters: {'subsample': 0.2810670297558328, 'dropout_rate': 0.9712230611913137, 'n_estimators': 176, 'learning_rate': 0.014613255025635642}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:46:49,826] Trial 79 finished with value: 0.5587297526557774 and parameters: {'subsample': 0.16406889274305014, 'dropout_rate': 0.9454521899524222, 'n_estimators': 124, 'learning_rate': 0.009868134793758362}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.4600760456273764
Fold 5 C-index: 0.48068669527896996
[I 2024-04-14 21:47:02,925] Trial 80 finished with value: 0.552796785022458 and parameters: {'subsample': 0.11840892432134514, 'dropout_rate': 0.8903149025507398, 'n_estimators': 156, 'learning_rate': 0.023594620292035545}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.4978540772532189
[I 2024-04-14 21:47:10,944] Trial 81 finished with value: 0.5677484775362501 and parameters: {'subsample': 0.23074880145468354, 'dropout_rate': 0.9983597763427171, 'n_estimators': 117, 'learning_rate': 0.05191285063438977}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.4372623574144487
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:47:18,288] Trial 82 finished with value: 0.5537687955780128 and parameters: {'subsample': 0.22245798214998702, 'dropout_rate': 0.9554512620502295, 'n_estimators': 105, 'learning_rate': 0.05774716841770277}. Best is trial 45 with value: 0.5695979266625014.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.5107296137339056
[I 2024-04-14 21:47:23,707] Trial 83 finished with value: 0.5708222569448099 and parameters: {'subsample': 0.29431891839649454, 'dropout_rate': 0.9744798438127548, 'n_estimators': 74, 'learning_rate': 0.04966191198944692}. Best is trial 83 with value: 0.5708222569448099.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.4714828897338403
Fold 5 C-index: 0.5064377682403434
[I 2024-04-14 21:47:29,552] Trial 84 finished with value: 0.5722894692414464 and parameters: {'subsample': 0.3029301571115034, 'dropout_rate': 0.996097903864056, 'n_estimators': 82, 'learning_rate': 0.0650026738566215}. Best is trial 84 with value: 0.5722894692414464.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.5150214592274678
[I 2024-04-14 21:47:35,101] Trial 85 finished with value: 0.5561879040708346 and parameters: {'subsample': 0.3699477131537762, 'dropout_rate': 0.9188547544102114, 'n_estimators': 75, 'learning_rate': 0.06772210918360616}. Best is trial 84 with value: 0.5722894692414464.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:47:41,748] Trial 86 finished with value: 0.5604289095381416 and parameters: {'subsample': 0.30698304928306214, 'dropout_rate': 0.9971508145154011, 'n_estimators': 91, 'learning_rate': 0.05238740101089796}. Best is trial 84 with value: 0.5722894692414464.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.49356223175965663
[I 2024-04-14 21:47:50,372] Trial 87 finished with value: 0.557824437745207 and parameters: {'subsample': 0.17104940182003037, 'dropout_rate': 0.9451941506565779, 'n_estimators': 137, 'learning_rate': 0.06559088056864305}. Best is trial 84 with value: 0.5722894692414464.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.4448669201520912
Fold 5 C-index: 0.48497854077253216
[I 2024-04-14 21:48:01,193] Trial 88 finished with value: 0.5534970998967789 and parameters: {'subsample': 0.21628563504292136, 'dropout_rate': 0.9061082396170369, 'n_estimators': 172, 'learning_rate': 0.04647359430999269}. Best is trial 84 with value: 0.5722894692414464.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:48:05,819] Trial 89 finished with value: 0.5601396161075853 and parameters: {'subsample': 0.27094554341850247, 'dropout_rate': 0.8452235336265254, 'n_estimators': 74, 'learning_rate': 0.050099939094955526}. Best is trial 84 with value: 0.5722894692414464.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.467680608365019
Fold 5 C-index: 0.5278969957081545
[I 2024-04-14 21:48:09,731] Trial 90 finished with value: 0.5743463408956828 and parameters: {'subsample': 0.29674446367626733, 'dropout_rate': 0.9344474955171548, 'n_estimators': 60, 'learning_rate': 0.04596750793143277}. Best is trial 90 with value: 0.5743463408956828.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.467680608365019
Fold 5 C-index: 0.5364806866952789
[I 2024-04-14 21:48:13,536] Trial 91 finished with value: 0.5759872090617699 and parameters: {'subsample': 0.29594145182269294, 'dropout_rate': 0.9360434819399824, 'n_estimators': 56, 'learning_rate': 0.04684319528289335}. Best is trial 91 with value: 0.5759872090617699.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:48:18,188] Trial 92 finished with value: 0.5486124795759596 and parameters: {'subsample': 0.3346915910591542, 'dropout_rate': 0.888760749719491, 'n_estimators': 62, 'learning_rate': 0.057370458650942605}. Best is trial 91 with value: 0.5759872090617699.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5321888412017167
[I 2024-04-14 21:48:22,146] Trial 93 finished with value: 0.5604066127708611 and parameters: {'subsample': 0.39457393101015664, 'dropout_rate': 0.9237207187264491, 'n_estimators': 54, 'learning_rate': 0.045252364605242755}. Best is trial 91 with value: 0.5759872090617699.

Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.4790874524714829
Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:48:25,323] Trial 94 finished with value: 0.5780190519822742 and parameters: {'subsample': 0.30359910909282395, 'dropout_rate': 0.944388489444451, 'n_estimators': 38, 'learning_rate': 0.0413681807904896}. Best is trial 94 with value: 0.5780190519822742.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.4790874524714829
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:48:28,038] Trial 95 finished with value: 0.5698156017205017 and parameters: {'subsample': 0.2910896133726829, 'dropout_rate': 0.9533965609375651, 'n_estimators': 33, 'learning_rate': 0.04183819466344819}. Best is trial 94 with value: 0.5780190519822742.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.5278969957081545
[I 2024-04-14 21:48:31,013] Trial 96 finished with value: 0.5757155133805361 and parameters: {'subsample': 0.299476673080799, 'dropout_rate': 0.941391534723049, 'n_estimators': 40, 'learning_rate': 0.042752890770932396}. Best is trial 94 with value: 0.5780190519822742.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5446808510638298
Fold 4 C-index: 0.4790874524714829
Fold 5 C-index: 0.51931330472103
[I 2024-04-14 21:48:32,250] Trial 97 finished with value: 0.5461375545491344 and parameters: {'subsample': 0.29796314193331974, 'dropout_rate': 0.9348852616077201, 'n_estimators': 16, 'learning_rate': 0.048956605916953305}. Best is trial 94 with value: 0.5780190519822742.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.46387832699619774
Fold 5 C-index: 0.5278969957081545
[I 2024-04-14 21:48:34,698] Trial 98 finished with value: 0.5681433893876158 and parameters: {'subsample': 0.4208554542044463, 'dropout_rate': 0.9464371072817763, 'n_estimators': 35, 'learning_rate': 0.04316674289457706}. Best is trial 94 with value: 0.5780190519822742.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.43346007604562736

[I 2024-04-14 21:48:37,427] A new study created in memory with name: no-name-f9d72bd8-497d-43d0-b751-9a5fb761bd7d

Fold 5 C-index: 0.5236051502145923
[I 2024-04-14 21:48:37,411] Trial 99 finished with value: 0.560350306269002 and parameters: {'subsample': 0.36833539158269923, 'dropout_rate': 0.9036386635678965, 'n_estimators': 44, 'learning_rate': 0.046889018930076846}. Best is trial 94 with value: 0.5780190519822742.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.5780190519822742], datetime_start=datetime.datetime(2024, 4, 14, 21, 48, 22, 152955), datetime_complete=datetime.datetime(2024, 4, 14, 21, 48, 25, 322616), params={'subsample': 0.30359910909282395, 'dropout_rate': 0.944388489444451, 'n_estimators': 38, 'learning_rate': 0.0413681807904896}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=94, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.30359910909282395, 'dropout_rate': 0.944388489444451, 'n_estimators': 38, 'learning_rate': 0.0413681807904896}


* Best Score for C-index:
 0.5780190519822742

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.25829930734959416
Fold 2 IBS: 0.2191736700181163
Fold 3 IBS: 0.2334616302194225
Fold 4 IBS: 0.3156049246800978
Fold 5 IBS: 0.23985596953072597
[I 2024-04-14 21:48:45,414] Trial 0 finished with value: 0.25327910035959134 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.25327910035959134.
Fold 1 IBS: 0.3800732083196276
Fold 2 IBS: 0.3274966268822977
Fold 3 IBS: 0.29417760633253887
Fold 4 IBS: 0.45813012993757535
Fold 5 IBS: 0.3609624365433569
[I 2024-04-14 21:49:22,350] Trial 1 finished with value: 0.36416800160307927 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.25327910035959134.
Fold 1 IBS: 0.30107613546224865
Fold 2 IBS: 0.24772151625817843
Fold 3 IBS: 0.22894510304072746
Fold 4 IBS: 0.3924352805533158
Fold 5 IBS: 0.2874930035783972
[I 2024-04-14 21:49:34,637] Trial 2 finished with value: 0.29153420777857353 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.25327910035959134.
Fold 1 IBS: 0.3041611117608914
Fold 2 IBS: 0.25288952796334463
Fold 3 IBS: 0.2362037407440042
Fold 4 IBS: 0.40902096164785273
Fold 5 IBS: 0.28847700107546503
[I 2024-04-14 21:49:46,803] Trial 3 finished with value: 0.29815046863831157 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.25327910035959134.
Fold 1 IBS: 0.3147186434801709
Fold 2 IBS: 0.2524050590445521
Fold 3 IBS: 0.21417562840974563
Fold 4 IBS: 0.40270643821894775
Fold 5 IBS: 0.2922135061550794
[I 2024-04-14 21:50:04,870] Trial 4 finished with value: 0.2952438550616992 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.25327910035959134.
Fold 1 IBS: 0.34794741870936186
Fold 2 IBS: 0.28430441245516075
Fold 3 IBS: 0.2629760169015054
Fold 4 IBS: 0.4423863933871498
Fold 5 IBS: 0.332214725725076
[I 2024-04-14 21:50:30,896] Trial 5 finished with value: 0.33396579343565075 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.25327910035959134.
Fold 1 IBS: 0.2500247367583315
Fold 2 IBS: 0.21847406316975002
Fold 3 IBS: 0.23009136327085145
Fold 4 IBS: 0.2963101650792324
Fold 5 IBS: 0.23149687914295028
[I 2024-04-14 21:50:43,601] Trial 6 finished with value: 0.24527944148422315 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.24527944148422315.
Fold 1 IBS: 0.2461151395783537
Fold 2 IBS: 0.22356182664402283
Fold 3 IBS: 0.22598986957027253
Fold 4 IBS: 0.2702198897904832
Fold 5 IBS: 0.22895457719792328
[I 2024-04-14 21:50:46,691] Trial 7 finished with value: 0.23896826055621112 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23896826055621112.
Fold 1 IBS: 0.2643806370551602
Fold 2 IBS: 0.21896287836891176
Fold 3 IBS: 0.22429752349003604
Fold 4 IBS: 0.3224490067293914
Fold 5 IBS: 0.24466827449333517
[I 2024-04-14 21:50:59,505] Trial 8 finished with value: 0.2549516640273669 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23896826055621112.
Fold 1 IBS: 0.35970228958267786
Fold 2 IBS: 0.28874053141857886
Fold 3 IBS: 0.24642200461649627
Fold 4 IBS: 0.44588080907707706
Fold 5 IBS: 0.33753922077210335
[I 2024-04-14 21:51:33,082] Trial 9 finished with value: 0.33565697109338666 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23896826055621112.
Fold 1 IBS: 0.2471351060657296
Fold 2 IBS: 0.23185612979714287
Fold 3 IBS: 0.2289649286355643
Fold 4 IBS: 0.24232908392234695
Fold 5 IBS: 0.22937481082443303
[I 2024-04-14 21:51:34,644] Trial 10 finished with value: 0.2359320118490434 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.2359320118490434.
Fold 1 IBS: 0.2467901743838015
Fold 2 IBS: 0.2312610102295463
Fold 3 IBS: 0.22891540752506118
Fold 4 IBS: 0.2435823646581995
Fold 5 IBS: 0.22931387983027346
[I 2024-04-14 21:51:35,038] Trial 11 finished with value: 0.2359725673253764 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 10 with value: 0.2359320118490434.
Fold 1 IBS: 0.2520734802833299
Fold 2 IBS: 0.21883085356569026
Fold 3 IBS: 0.2308369059215008
Fold 4 IBS: 0.3032655884181797
Fold 5 IBS: 0.23746330108492886
[I 2024-04-14 21:51:38,181] Trial 12 finished with value: 0.2484940258547259 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.2359320118490434.
Fold 1 IBS: 0.24718630204653388
Fold 2 IBS: 0.23194141656176934
Fold 3 IBS: 0.22897264676761656
Fold 4 IBS: 0.2421652281208591
Fold 5 IBS: 0.22938449859722432
[I 2024-04-14 21:51:38,601] Trial 13 finished with value: 0.23593001841880062 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.7324371247382785, 'n_estimators': 3, 'learning_rate': 0.007730532223257889}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.24663994670449504
Fold 2 IBS: 0.2309185881368052
Fold 3 IBS: 0.2288899176966145
Fold 4 IBS: 0.2443701510703482
Fold 5 IBS: 0.22928932854721248
[I 2024-04-14 21:51:44,489] Trial 14 finished with value: 0.23602158643109505 and parameters: {'subsample': 0.8637836787170821, 'dropout_rate': 0.9788958362896205, 'n_estimators': 102, 'learning_rate': 0.0025916531369806137}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.24719785985549475
Fold 2 IBS: 0.23195333359707634
Fold 3 IBS: 0.22897410952780164
Fold 4 IBS: 0.24214072062375647
Fold 5 IBS: 0.22938654843365547
[I 2024-04-14 21:51:45,501] Trial 15 finished with value: 0.2359305144075569 and parameters: {'subsample': 0.8912920435266729, 'dropout_rate': 0.7994004963170612, 'n_estimators': 13, 'learning_rate': 0.0015537236853158376}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.2586654050122548
Fold 2 IBS: 0.21393721595526288
Fold 3 IBS: 0.21246458424293763
Fold 4 IBS: 0.3038419261545794
Fold 5 IBS: 0.23523943765242675
[I 2024-04-14 21:52:06,299] Trial 16 finished with value: 0.24482971380349233 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.8270228189409228, 'n_estimators': 315, 'learning_rate': 0.017212997372337172}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.24522836788907057
Fold 2 IBS: 0.22711481582773868
Fold 3 IBS: 0.22872429531237493
Fold 4 IBS: 0.25681296743984755
Fold 5 IBS: 0.22906258010486774
[I 2024-04-14 21:52:12,281] Trial 17 finished with value: 0.23738860531477993 and parameters: {'subsample': 0.8614054028098825, 'dropout_rate': 0.6004730897368156, 'n_estimators': 99, 'learning_rate': 0.01245288911484009}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.2491771797739477
Fold 2 IBS: 0.21910842827073745
Fold 3 IBS: 0.2298338279197275
Fold 4 IBS: 0.2951308864896073
Fold 5 IBS: 0.23160185621760387
[I 2024-04-14 21:52:18,947] Trial 18 finished with value: 0.2449704357343248 and parameters: {'subsample': 0.8597800373764937, 'dropout_rate': 0.7964804939751499, 'n_estimators': 119, 'learning_rate': 0.03489214489588591}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.25225910025730985

Fold 2 IBS: 0.217623028684295
Fold 3 IBS: 0.22928372477732015
Fold 4 IBS: 0.30100053255938797
Fold 5 IBS: 0.2325559394582789
[I 2024-04-14 21:52:54,667] Trial 19 finished with value: 0.24654446514731837 and parameters: {'subsample': 0.650899739648275, 'dropout_rate': 0.9954484919483726, 'n_estimators': 400, 'learning_rate': 0.011730584939170362}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.244884130972059
Fold 2 IBS: 0.22525640865538507
Fold 3 IBS: 0.2287419458584932
Fold 4 IBS: 0.26450177998590696
Fold 5 IBS: 0.2290688156699557
[I 2024-04-14 21:52:59,279] Trial 20 finished with value: 0.23849061622836 and parameters: {'subsample': 0.9010126869682862, 'dropout_rate': 0.6173032374045795, 'n_estimators': 67, 'learning_rate': 0.0257290746252228}. Best is trial 13 with value: 0.23593001841880062.
Fold 1 IBS: 0.2472013998837189
Fold 2 IBS: 0.2319637496979315
Fold 3 IBS: 0.2289750350168313
Fold 4 IBS: 0.24211711207007558
Fold 5 IBS: 0.22938745518196135
[I 2024-04-14 21:53:01,405] Trial 21 finished with value: 0.2359289503701037 and parameters: {'subsample': 0.9343846884001734, 'dropout_rate': 0.7514483038714346, 'n_estimators': 11, 'learning_rate': 0.0016108337344105245}. Best is trial 21 with value: 0.2359289503701037.
Fold 1 IBS: 0.24724171541775777
Fold 2 IBS: 0.23202908635346117
Fold 3 IBS: 0.22898090776828964
Fold 4 IBS: 0.2419946990997831
Fold 5 IBS: 0.22939448464111775
[I 2024-04-14 21:53:01,979] Trial 22 finished with value: 0.2359281786560819 and parameters: {'subsample': 0.8051066436583272, 'dropout_rate': 0.7849083992914515, 'n_estimators': 2, 'learning_rate': 0.001288195328092727}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2451468373711382
Fold 2 IBS: 0.22570608589363322
Fold 3 IBS: 0.2287230153875578
Fold 4 IBS: 0.2628518443823824
Fold 5 IBS: 0.22904805082222449
[I 2024-04-14 21:53:13,545] Trial 23 finished with value: 0.23829516677138723 and parameters: {'subsample': 0.7960032419366929, 'dropout_rate': 0.7647225723640668, 'n_estimators': 135, 'learning_rate': 0.011690418826121547}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24557998286271468
Fold 2 IBS: 0.22722474502341258
Fold 3 IBS: 0.22762591694570194
Fold 4 IBS: 0.2568876346150458
Fold 5 IBS: 0.229069103529256
[I 2024-04-14 21:53:18,373] Trial 24 finished with value: 0.2372774765952262 and parameters: {'subsample': 0.6159523319227614, 'dropout_rate': 0.8919984776035661, 'n_estimators': 60, 'learning_rate': 0.019745129742150442}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24702969896553287
Fold 2 IBS: 0.23167263913826375
Fold 3 IBS: 0.22895050762076927
Fold 4 IBS: 0.24267374938524364
Fold 5 IBS: 0.22935762527744927
[I 2024-04-14 21:53:19,486] Trial 25 finished with value: 0.23593684407745177 and parameters: {'subsample': 0.9302723371622602, 'dropout_rate': 0.6164454236417651, 'n_estimators': 10, 'learning_rate': 0.008500348756543277}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24507199950193015
Fold 2 IBS: 0.22291705765821465
Fold 3 IBS: 0.22889719443184872
Fold 4 IBS: 0.2752601432898987
Fold 5 IBS: 0.22935670019551196
[I 2024-04-14 21:53:24,546] Trial 26 finished with value: 0.24030061901548083 and parameters: {'subsample': 0.9410835899028251, 'dropout_rate': 0.9365425863488012, 'n_estimators': 72, 'learning_rate': 0.033335519665507754}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2605832453508163
Fold 2 IBS: 0.22005447179237794
Fold 3 IBS: 0.23300815682557388
Fold 4 IBS: 0.31874720575705145
Fold 5 IBS: 0.24391494351996065
[I 2024-04-14 21:53:37,001] Trial 27 finished with value: 0.25526160464915604 and parameters: {'subsample': 0.8067838665321584, 'dropout_rate': 0.5288134738174257, 'n_estimators': 151, 'learning_rate': 0.043467308912439384}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24658051041194032
Fold 2 IBS: 0.23079913121518428
Fold 3 IBS: 0.22887898770228357
Fold 4 IBS: 0.2445850325919612
Fold 5 IBS: 0.2292890342444154
[I 2024-04-14 21:53:39,338] Trial 28 finished with value: 0.23602653923315695 and parameters: {'subsample': 0.8072189290138386, 'dropout_rate': 0.6650172386686171, 'n_estimators': 33, 'learning_rate': 0.008840283601572695}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24531909625309514
Fold 2 IBS: 0.22500491043449258
Fold 3 IBS: 0.22879294685579474
Fold 4 IBS: 0.26646524991166953
Fold 5 IBS: 0.22904741175343654
[I 2024-04-14 21:53:45,310] Trial 29 finished with value: 0.2389259230416977 and parameters: {'subsample': 0.6997683231046966, 'dropout_rate': 0.8464392486282114, 'n_estimators': 97, 'learning_rate': 0.018290562960426554}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24548769349547087
Fold 2 IBS: 0.22575904449071554
Fold 3 IBS: 0.22835660385828727
Fold 4 IBS: 0.26299442926276073
Fold 5 IBS: 0.22907217017994919
[I 2024-04-14 21:54:09,628] Trial 30 finished with value: 0.23833398825743674 and parameters: {'subsample': 0.5936384513688024, 'dropout_rate': 0.7617601277562117, 'n_estimators': 248, 'learning_rate': 0.006154467049609045}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2471994862703269
Fold 2 IBS: 0.23196386834328164
Fold 3 IBS: 0.22897510966638335
Fold 4 IBS: 0.2421201723273417
Fold 5 IBS: 0.22938761590226509
[I 2024-04-14 21:54:10,815] Trial 31 finished with value: 0.23592925050191976 and parameters: {'subsample': 0.9110614094922455, 'dropout_rate': 0.7887178087585408, 'n_estimators': 7, 'learning_rate': 0.002555164233159292}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2471444207116307
Fold 2 IBS: 0.2318562254856736
Fold 3 IBS: 0.22896501508572023
Fold 4 IBS: 0.24232746130927343
Fold 5 IBS: 0.22937455808932594
[I 2024-04-14 21:54:11,390] Trial 32 finished with value: 0.23593353613632476 and parameters: {'subsample': 0.9350095586246314, 'dropout_rate': 0.7475107094388963, 'n_estimators': 3, 'learning_rate': 0.014780658573762621}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24531985438239726
Fold 2 IBS: 0.22385721628367675
Fold 3 IBS: 0.22876695457195625
Fold 4 IBS: 0.27234229011986166
Fold 5 IBS: 0.2290745934254288
[I 2024-04-14 21:54:25,507] Trial 33 finished with value: 0.2398721817566641 and parameters: {'subsample': 0.7560767218607624, 'dropout_rate': 0.8304059646836774, 'n_estimators': 82, 'learning_rate': 0.025471433810268517}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2466020237261186
Fold 2 IBS: 0.230862472523405
Fold 3 IBS: 0.22888373989837746
Fold 4 IBS: 0.24456671055244264
Fold 5 IBS: 0.22929191682327002
[I 2024-04-14 21:54:30,401] Trial 34 finished with value: 0.23604137270472272 and parameters: {'subsample': 0.8076526462736512, 'dropout_rate': 0.6685834679387015, 'n_estimators': 40, 'learning_rate': 0.00695271520970007}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24709967506731287
Fold 2 IBS: 0.2317958061108409
Fold 3 IBS: 0.22895969371691224
Fold 4 IBS: 0.24245460576397443
Fold 5 IBS: 0.22936795397928136
[I 2024-04-14 21:54:34,412] Trial 35 finished with value: 0.23593554692766436 and parameters: {'subsample': 0.9435953072349615, 'dropout_rate': 0.4895850417242549, 'n_estimators': 38, 'learning_rate': 0.0015208060539196792}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24603926444764349
Fold 2 IBS: 0.22132165880117743
Fold 3 IBS: 0.2292131934976118
Fold 4 IBS: 0.2820921878384818
Fold 5 IBS: 0.229563054642594
[I 2024-04-14 21:54:43,206] Trial 36 finished with value: 0.24164587184550174 and parameters: {'subsample': 0.8706944286938898, 'dropout_rate': 0.9357329092844269, 'n_estimators': 129, 'learning_rate': 0.022377618063917252}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2470515894440715
Fold 2 IBS: 0.23171445405548724
Fold 3 IBS: 0.22895142527235182
Fold 4 IBS: 0.24261576936176546
Fold 5 IBS: 0.22935895245569765
[I 2024-04-14 21:54:43,592] Trial 37 finished with value: 0.2359384381178747 and parameters: {'subsample': 0.9930263057981803, 'dropout_rate': 0.3917773398227318, 'n_estimators': 1, 'learning_rate': 0.07677405503763898}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2510477677705373
Fold 2 IBS: 0.21780102174044222

Fold 3 IBS: 0.22982813627745377
Fold 4 IBS: 0.2982564284360105
Fold 5 IBS: 0.23151273581044918
[I 2024-04-14 21:54:49,911] Trial 38 finished with value: 0.2456892180069786 and parameters: {'subsample': 0.7343497854758639, 'dropout_rate': 0.13272164755980653, 'n_estimators': 79, 'learning_rate': 0.060691705645777076}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.25017095026188413
Fold 2 IBS: 0.21870305039650859
Fold 3 IBS: 0.23036639060624442
Fold 4 IBS: 0.29742908883540964
Fold 5 IBS: 0.23185851227205606
[I 2024-04-14 21:55:01,337] Trial 39 finished with value: 0.24570559847442058 and parameters: {'subsample': 0.8328204942141013, 'dropout_rate': 0.5841264351271549, 'n_estimators': 159, 'learning_rate': 0.02762747332143923}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2449422956152037
Fold 2 IBS: 0.22636241594032222
Fold 3 IBS: 0.22872398892904824
Fold 4 IBS: 0.259545522434371
Fold 5 IBS: 0.2290526113095854
[I 2024-04-14 21:55:03,481] Trial 40 finished with value: 0.23772536684570608 and parameters: {'subsample': 0.9127827103754563, 'dropout_rate': 0.27073406810212547, 'n_estimators': 34, 'learning_rate': 0.04197716213787766}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24681824045782233
Fold 2 IBS: 0.23131779029986346
Fold 3 IBS: 0.2289205510199754
Fold 4 IBS: 0.2434375421222896
Fold 5 IBS: 0.229325366706286
[I 2024-04-14 21:55:05,568] Trial 41 finished with value: 0.23596389812124735 and parameters: {'subsample': 0.9082340762251746, 'dropout_rate': 0.7989466074893848, 'n_estimators': 31, 'learning_rate': 0.005518020675566812}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24648899480234604
Fold 2 IBS: 0.23071009638941042
Fold 3 IBS: 0.2288723533141219
Fold 4 IBS: 0.2448871989985603
Fold 5 IBS: 0.22925851643024264
[I 2024-04-14 21:55:09,552] Trial 42 finished with value: 0.23604343198693628 and parameters: {'subsample': 0.9613763711419805, 'dropout_rate': 0.8749823632430358, 'n_estimators': 56, 'learning_rate': 0.0056556753738165105}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24713246017609755
Fold 2 IBS: 0.23183008029025257
Fold 3 IBS: 0.22896425728208813
Fold 4 IBS: 0.2423729236834109
Fold 5 IBS: 0.229376443934418
[I 2024-04-14 21:55:11,449] Trial 43 finished with value: 0.23593523307325343 and parameters: {'subsample': 0.7719539480101442, 'dropout_rate': 0.7972644452921213, 'n_estimators': 21, 'learning_rate': 0.002266741847279516}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24714847478966195
Fold 2 IBS: 0.23185632275101634
Fold 3 IBS: 0.22896608109470765
Fold 4 IBS: 0.24233850138249335
Fold 5 IBS: 0.2293802716296193
[I 2024-04-14 21:55:11,960] Trial 44 finished with value: 0.23593793032949972 and parameters: {'subsample': 0.8907474389992294, 'dropout_rate': 0.6658318654214992, 'n_estimators': 3, 'learning_rate': 0.014435380429869693}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24624727609709612
Fold 2 IBS: 0.22354156850606616
Fold 3 IBS: 0.22699566504248558
Fold 4 IBS: 0.27378311202758293
Fold 5 IBS: 0.22937011338644955
[I 2024-04-14 21:55:29,842] Trial 45 finished with value: 0.2399875470119361 and parameters: {'subsample': 0.371646708495304, 'dropout_rate': 0.7166439259082522, 'n_estimators': 196, 'learning_rate': 0.010807489762057339}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.26662404229321995
Fold 2 IBS: 0.22401025739324343
Fold 3 IBS: 0.23422167107468742
Fold 4 IBS: 0.33263401285156236
Fold 5 IBS: 0.2569617243575376
[I 2024-04-14 21:56:02,414] Trial 46 finished with value: 0.26289034159405017 and parameters: {'subsample': 0.8416995620320751, 'dropout_rate': 0.9343994572700158, 'n_estimators': 454, 'learning_rate': 0.01691485690544572}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.26388338796587435
Fold 2 IBS: 0.22345643948629426
Fold 3 IBS: 0.23397660143629745
Fold 4 IBS: 0.3288367552111866
Fold 5 IBS: 0.2602464206784312
[I 2024-04-14 21:56:10,665] Trial 47 finished with value: 0.2620799209556168 and parameters: {'subsample': 0.997837170627353, 'dropout_rate': 0.7707873932088828, 'n_estimators': 89, 'learning_rate': 0.08375106931479852}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24689058299239516
Fold 2 IBS: 0.23144142721282762
Fold 3 IBS: 0.22892951234612935
Fold 4 IBS: 0.24319656500471706
Fold 5 IBS: 0.2293303106384794
[I 2024-04-14 21:56:18,555] Trial 48 finished with value: 0.2359576796389097 and parameters: {'subsample': 0.9618248457957298, 'dropout_rate': 0.7029434264763865, 'n_estimators': 53, 'learning_rate': 0.0026769919093740354}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.258241211623527
Fold 2 IBS: 0.21828816566882872
Fold 3 IBS: 0.23190566281305197
Fold 4 IBS: 0.3135759037173455
Fold 5 IBS: 0.23960642533483165
[I 2024-04-14 21:56:45,532] Trial 49 finished with value: 0.25232347383151693 and parameters: {'subsample': 0.7001631537562438, 'dropout_rate': 0.8484426358329088, 'n_estimators': 301, 'learning_rate': 0.02012574297315375}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24718474666891396
Fold 2 IBS: 0.23190005174009215
Fold 3 IBS: 0.22898250717838628
Fold 4 IBS: 0.24224859856212647
Fold 5 IBS: 0.2293832801810181
[I 2024-04-14 21:56:47,577] Trial 50 finished with value: 0.23593983686610737 and parameters: {'subsample': 0.5423952364803822, 'dropout_rate': 0.8047908792946044, 'n_estimators': 21, 'learning_rate': 0.001457336195514032}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2469359627756229
Fold 2 IBS: 0.2314904845540136
Fold 3 IBS: 0.22893514197175852
Fold 4 IBS: 0.24307330512882586
Fold 5 IBS: 0.22933993101861724
[I 2024-04-14 21:56:50,419] Trial 51 finished with value: 0.2359549650897676 and parameters: {'subsample': 0.8885462028836437, 'dropout_rate': 0.7359177443178953, 'n_estimators': 20, 'learning_rate': 0.006440843652567473}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24710329539120046
Fold 2 IBS: 0.23180501147602023
Fold 3 IBS: 0.22896052580830595
Fold 4 IBS: 0.2424375625884035
Fold 5 IBS: 0.22936918176215923
[I 2024-04-14 21:56:54,355] Trial 52 finished with value: 0.2359351154052179 and parameters: {'subsample': 0.9718755980123966, 'dropout_rate': 0.6873140529565501, 'n_estimators': 52, 'learning_rate': 0.0010699775114741997}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24660903566696094
Fold 2 IBS: 0.23093448994331864
Fold 3 IBS: 0.22889112303986475
Fold 4 IBS: 0.24431312457182214
Fold 5 IBS: 0.22930054126622085
[I 2024-04-14 21:56:56,463] Trial 53 finished with value: 0.23600966289763745 and parameters: {'subsample': 0.9260384317173942, 'dropout_rate': 0.6413200021749954, 'n_estimators': 25, 'learning_rate': 0.010572986864423853}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24598133543022468
Fold 2 IBS: 0.22947793389796903
Fold 3 IBS: 0.22881634804237527
Fold 4 IBS: 0.24838349999015716
Fold 5 IBS: 0.22917911399318266
[I 2024-04-14 21:57:06,476] Trial 54 finished with value: 0.23636764627078177 and parameters: {'subsample': 0.8413661639211198, 'dropout_rate': 0.901367840507173, 'n_estimators': 107, 'learning_rate': 0.005832088933072355}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2462336503707045
Fold 2 IBS: 0.22848827163270266
Fold 3 IBS: 0.2284591716111095
Fold 4 IBS: 0.25158340410201074
Fold 5 IBS: 0.22926269932507068
[I 2024-04-14 21:57:13,742] Trial 55 finished with value: 0.2368054394083196 and parameters: {'subsample': 0.4138621583207399, 'dropout_rate': 0.7697023820122927, 'n_estimators': 68, 'learning_rate': 0.012590501123370072}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24720814173808922
Fold 2 IBS: 0.23197596273324472
Fold 3 IBS: 0.22897574824436448
Fold 4 IBS: 0.24209754071475462
Fold 5 IBS: 0.2293882611770121
[I 2024-04-14 21:57:14,672] Trial 56 finished with value: 0.23592913092149304 and parameters: {'subsample': 0.9989530893051872, 'dropout_rate': 0.5787039864241283, 'n_estimators': 1, 'learning_rate': 0.01505652631278697}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.246942553350122
Fold 2 IBS: 0.23095136875769873
Fold 3 IBS: 0.22874664593485872

Fold 4 IBS: 0.24395238716462248
Fold 5 IBS: 0.22923813377952493
[I 2024-04-14 21:57:18,574] Trial 57 finished with value: 0.23596621779736537 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.5678085837943805, 'n_estimators': 15, 'learning_rate': 0.014955776210569753}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24628949870709554
Fold 2 IBS: 0.23031437654668757
Fold 3 IBS: 0.22884653819375786
Fold 4 IBS: 0.2458696334873806
Fold 5 IBS: 0.22922612427093866
[I 2024-04-14 21:57:24,397] Trial 58 finished with value: 0.23610923424117206 and parameters: {'subsample': 0.9550218144832968, 'dropout_rate': 0.6272447801163561, 'n_estimators': 45, 'learning_rate': 0.009156932045437691}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.28328758722421493
Fold 2 IBS: 0.2394754061855135
Fold 3 IBS: 0.24015286871265207
Fold 4 IBS: 0.37157961788423793
Fold 5 IBS: 0.28334915962344304
[I 2024-04-14 21:57:54,680] Trial 59 finished with value: 0.2835689279260123 and parameters: {'subsample': 0.8884037531717154, 'dropout_rate': 0.5065802886056728, 'n_estimators': 385, 'learning_rate': 0.028019028327482088}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24571361751326634
Fold 2 IBS: 0.22242188290417161
Fold 3 IBS: 0.22897962097721017
Fold 4 IBS: 0.2779048378310915
Fold 5 IBS: 0.22923553530791965
[I 2024-04-14 21:57:59,239] Trial 60 finished with value: 0.24085109890673184 and parameters: {'subsample': 0.7843776695537386, 'dropout_rate': 0.454804903114274, 'n_estimators': 68, 'learning_rate': 0.037667655525589566}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2472238568608318
Fold 2 IBS: 0.2320038060704722
Fold 3 IBS: 0.22897838620496808
Fold 4 IBS: 0.24204609231910046
Fold 5 IBS: 0.2293914345208916
[I 2024-04-14 21:57:59,716] Trial 61 finished with value: 0.2359287151952528 and parameters: {'subsample': 0.969376589828422, 'dropout_rate': 0.7347372596478586, 'n_estimators': 2, 'learning_rate': 0.004439386834777157}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24719882750351277
Fold 2 IBS: 0.23195682702549383
Fold 3 IBS: 0.2289739545283409
Fold 4 IBS: 0.24212878835271104
Fold 5 IBS: 0.22938651413955227
[I 2024-04-14 21:58:00,353] Trial 62 finished with value: 0.23592898230992215 and parameters: {'subsample': 0.968734878810526, 'dropout_rate': 0.7346598949261548, 'n_estimators': 4, 'learning_rate': 0.004761399604301435}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24717689985844385
Fold 2 IBS: 0.23192566938849352
Fold 3 IBS: 0.22897116780825147
Fold 4 IBS: 0.24219494896474378
Fold 5 IBS: 0.2293826059173247
[I 2024-04-14 21:58:01,264] Trial 63 finished with value: 0.23593025838745146 and parameters: {'subsample': 0.9969859083534098, 'dropout_rate': 0.6980861897354655, 'n_estimators': 6, 'learning_rate': 0.004484346226185939}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24634310257936395
Fold 2 IBS: 0.23043787258160425
Fold 3 IBS: 0.22885391238337724
Fold 4 IBS: 0.245557173568766
Fold 5 IBS: 0.2292335935764709
[I 2024-04-14 21:58:05,007] Trial 64 finished with value: 0.23608513093791647 and parameters: {'subsample': 0.9656937910239556, 'dropout_rate': 0.7293852049830536, 'n_estimators': 41, 'learning_rate': 0.009346554751318318}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24717263421622265
Fold 2 IBS: 0.23192075562477793
Fold 3 IBS: 0.2289700312712698
Fold 4 IBS: 0.24221510660656845
Fold 5 IBS: 0.22938283633739887
[I 2024-04-14 21:58:06,281] Trial 65 finished with value: 0.23593227281124754 and parameters: {'subsample': 0.918099364596505, 'dropout_rate': 0.8186347686090838, 'n_estimators': 2, 'learning_rate': 0.01525362222957736}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2511577797408346
Fold 2 IBS: 0.218722767876066
Fold 3 IBS: 0.23051744460239845
Fold 4 IBS: 0.3013708920476612
Fold 5 IBS: 0.23562453620361928
[I 2024-04-14 21:58:37,497] Trial 66 finished with value: 0.24747868409411594 and parameters: {'subsample': 0.9489150299631838, 'dropout_rate': 0.6501995104782343, 'n_estimators': 239, 'learning_rate': 0.02032598418133674}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.2467963031073254
Fold 2 IBS: 0.23122901189213563
Fold 3 IBS: 0.22891367997830572
Fold 4 IBS: 0.24363380607821217
Fold 5 IBS: 0.2293227040603126
[I 2024-04-14 21:58:40,264] Trial 67 finished with value: 0.23597910102325828 and parameters: {'subsample': 0.8687565409529565, 'dropout_rate': 0.7759705981969152, 'n_estimators': 23, 'learning_rate': 0.008321478019630575}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24675300294121394
Fold 2 IBS: 0.2312094386747451
Fold 3 IBS: 0.2289100690884874
Fold 4 IBS: 0.24370102757456416
Fold 5 IBS: 0.22930557078700392
[I 2024-04-14 21:58:43,757] Trial 68 finished with value: 0.23597582181320292 and parameters: {'subsample': 0.999139860842733, 'dropout_rate': 0.8540273501817605, 'n_estimators': 44, 'learning_rate': 0.004479646742163051}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24542652626709813
Fold 2 IBS: 0.22793572422350575
Fold 3 IBS: 0.2287831736923138
Fold 4 IBS: 0.2537519163755514
Fold 5 IBS: 0.2290977918319083
[I 2024-04-14 21:58:50,847] Trial 69 finished with value: 0.23699902647807547 and parameters: {'subsample': 0.8322038116600627, 'dropout_rate': 0.6860207545770559, 'n_estimators': 81, 'learning_rate': 0.012530563377500652}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24546175696948153
Fold 2 IBS: 0.22830557592384546
Fold 3 IBS: 0.22874596790367943
Fold 4 IBS: 0.2519229416372398
Fold 5 IBS: 0.22913715192858827
[I 2024-04-14 21:58:52,317] Trial 70 finished with value: 0.23671467887256686 and parameters: {'subsample': 0.928002917687583, 'dropout_rate': 0.21112935486850254, 'n_estimators': 17, 'learning_rate': 0.05424608271430476}. Best is trial 22 with value: 0.2359281786560819.
Fold 1 IBS: 0.24723509115114733
Fold 2 IBS: 0.23202170617267442
Fold 3 IBS: 0.22898044944410886
Fold 4 IBS: 0.24200994206195842
Fold 5 IBS: 0.22939360229544412
[I 2024-04-14 21:58:52,862] Trial 71 finished with value: 0.23592815822506666 and parameters: {'subsample': 0.9753212085395895, 'dropout_rate': 0.7458924291806431, 'n_estimators': 1, 'learning_rate': 0.004281887435048049}. Best is trial 71 with value: 0.23592815822506666.
Fold 1 IBS: 0.24723589357820433
Fold 2 IBS: 0.23202313793731594
Fold 3 IBS: 0.22898047820504194
Fold 4 IBS: 0.24200575764517787
Fold 5 IBS: 0.22939374912291582
[I 2024-04-14 21:58:53,414] Trial 72 finished with value: 0.23592780329773116 and parameters: {'subsample': 0.9724617244505214, 'dropout_rate': 0.7437486470042536, 'n_estimators': 1, 'learning_rate': 0.003934655264956236}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24695743183325852
Fold 2 IBS: 0.23155685044168256
Fold 3 IBS: 0.2289389926199486
Fold 4 IBS: 0.2429386805215652
Fold 5 IBS: 0.22934237778305488
[I 2024-04-14 21:58:55,773] Trial 73 finished with value: 0.23594686663990191 and parameters: {'subsample': 0.9753160040898945, 'dropout_rate': 0.753302246499145, 'n_estimators': 28, 'learning_rate': 0.0040738777256668175}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.2461120326108522
Fold 2 IBS: 0.2299602827270894
Fold 3 IBS: 0.2288232784977683
Fold 4 IBS: 0.2468072928937083
Fold 5 IBS: 0.2292002709322948
[I 2024-04-14 21:59:01,321] Trial 74 finished with value: 0.23618063153234262 and parameters: {'subsample': 0.9453899595947731, 'dropout_rate': 0.8230048207686377, 'n_estimators': 60, 'learning_rate': 0.008303194919236088}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24685822840671157
Fold 2 IBS: 0.23138830745159147
Fold 3 IBS: 0.2289260885820978
Fold 4 IBS: 0.24327882792784639
Fold 5 IBS: 0.22933124978171285
[I 2024-04-14 21:59:04,265] Trial 75 finished with value: 0.235956540429992 and parameters: {'subsample': 0.9077435332574455, 'dropout_rate': 0.8770367381764188, 'n_estimators': 34, 'learning_rate': 0.004529450881606685}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24675080884838094
Fold 2 IBS: 0.2311291712953388
Fold 3 IBS: 0.22890502938629095
Fold 4 IBS: 0.24386073188742308

Fold 5 IBS: 0.22930085302882294
[I 2024-04-14 21:59:05,742] Trial 76 finished with value: 0.23598931888925131 and parameters: {'subsample': 0.8768270122303635, 'dropout_rate': 0.7823662573901398, 'n_estimators': 17, 'learning_rate': 0.012589096150523053}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24602578706773542
Fold 2 IBS: 0.22971738000994765
Fold 3 IBS: 0.22880853470293033
Fold 4 IBS: 0.24732034248158946
Fold 5 IBS: 0.22918171521875855
[I 2024-04-14 21:59:07,014] Trial 77 finished with value: 0.23621075189619228 and parameters: {'subsample': 0.9659229260875638, 'dropout_rate': 0.7381012419968711, 'n_estimators': 11, 'learning_rate': 0.049658881246843596}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24552879084745355
Fold 2 IBS: 0.2285216831547308
Fold 3 IBS: 0.22875495950380775
Fold 4 IBS: 0.2512936333683752
Fold 5 IBS: 0.2291099378899557
[I 2024-04-14 21:59:10,577] Trial 78 finished with value: 0.23664180095286458 and parameters: {'subsample': 0.9314784615772665, 'dropout_rate': 0.6101035145560073, 'n_estimators': 50, 'learning_rate': 0.017167041574698387}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24723152808071577
Fold 2 IBS: 0.23200611097399015
Fold 3 IBS: 0.22897937228833498
Fold 4 IBS: 0.2420326639278885
Fold 5 IBS: 0.22939250009515985
[I 2024-04-14 21:59:10,933] Trial 79 finished with value: 0.23592843507321787 and parameters: {'subsample': 0.8530643247557187, 'dropout_rate': 0.5442725439283399, 'n_estimators': 1, 'learning_rate': 0.00744192741222355}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24672301653918763
Fold 2 IBS: 0.23114811367480184
Fold 3 IBS: 0.22890591431982366
Fold 4 IBS: 0.2438254372627326
Fold 5 IBS: 0.22930017325865332
[I 2024-04-14 21:59:12,948] Trial 80 finished with value: 0.2359805310110398 and parameters: {'subsample': 0.9732580725554854, 'dropout_rate': 0.544032602974961, 'n_estimators': 30, 'learning_rate': 0.007039353779474462}. Best is trial 72 with value: 0.23592780329773116.
Fold 1 IBS: 0.24723747052170153
Fold 2 IBS: 0.2320256626116833
Fold 3 IBS: 0.22898069379549463
Fold 4 IBS: 0.2419996636991777
Fold 5 IBS: 0.2293941999121991
[I 2024-04-14 21:59:13,326] Trial 81 finished with value: 0.23592753810805128 and parameters: {'subsample': 0.9053231560128981, 'dropout_rate': 0.3796513018058376, 'n_estimators': 1, 'learning_rate': 0.003225987542685412}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24702880639736483
Fold 2 IBS: 0.23164048961922495
Fold 3 IBS: 0.22894444009828216
Fold 4 IBS: 0.2427481507528047
Fold 5 IBS: 0.22935499583450678
[I 2024-04-14 21:59:14,448] Trial 82 finished with value: 0.23594337654043668 and parameters: {'subsample': 0.8489517338201277, 'dropout_rate': 0.2751963508288852, 'n_estimators': 9, 'learning_rate': 0.010353062314987012}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.2472233511392794
Fold 2 IBS: 0.23199584551593727
Fold 3 IBS: 0.22899350082265482
Fold 4 IBS: 0.24205121003016933
Fold 5 IBS: 0.22939082911741485
[I 2024-04-14 21:59:15,278] Trial 83 finished with value: 0.23593094732509115 and parameters: {'subsample': 0.5104385117001161, 'dropout_rate': 0.3606309396488173, 'n_estimators': 3, 'learning_rate': 0.0035462445447917643}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24646917470667812
Fold 2 IBS: 0.23063998867202545
Fold 3 IBS: 0.2288654583612216
Fold 4 IBS: 0.24511119012432203
Fold 5 IBS: 0.2292710238273913
[I 2024-04-14 21:59:18,335] Trial 84 finished with value: 0.23607136713832771 and parameters: {'subsample': 0.815564068583909, 'dropout_rate': 0.4347541191889555, 'n_estimators': 44, 'learning_rate': 0.007680362828500376}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24696190646700109
Fold 2 IBS: 0.23156983081306462
Fold 3 IBS: 0.2289383501990615
Fold 4 IBS: 0.24293704432298943
Fold 5 IBS: 0.22934684683853956
[I 2024-04-14 21:59:20,409] Trial 85 finished with value: 0.23595079572813127 and parameters: {'subsample': 0.8980144215295089, 'dropout_rate': 0.34867871709855314, 'n_estimators': 29, 'learning_rate': 0.0038641873924232617}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24724451186919708
Fold 2 IBS: 0.2320346646330337
Fold 3 IBS: 0.2289814464452781
Fold 4 IBS: 0.24198418904903887
Fold 5 IBS: 0.22939504737875704
[I 2024-04-14 21:59:20,759] Trial 86 finished with value: 0.23592797187506095 and parameters: {'subsample': 0.9381796825432934, 'dropout_rate': 0.3067916032495142, 'n_estimators': 1, 'learning_rate': 0.0012157797749798162}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24521485456902714
Fold 2 IBS: 0.22730744157337932
Fold 3 IBS: 0.22872271734070324
Fold 4 IBS: 0.2554568402638496
Fold 5 IBS: 0.22907492503706053
[I 2024-04-14 21:59:22,125] Trial 87 finished with value: 0.23715535575680396 and parameters: {'subsample': 0.86574192376622, 'dropout_rate': 0.3175591241610788, 'n_estimators': 18, 'learning_rate': 0.06559088056864305}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.2471692456893023
Fold 2 IBS: 0.23166191560587598
Fold 3 IBS: 0.22875184243084962
Fold 4 IBS: 0.24276364239004802
Fold 5 IBS: 0.22942046502057228
[I 2024-04-14 21:59:26,590] Trial 88 finished with value: 0.23595342222732962 and parameters: {'subsample': 0.25285489198415234, 'dropout_rate': 0.41587287831527564, 'n_estimators': 63, 'learning_rate': 0.0013321891071490864}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.2464411336101551
Fold 2 IBS: 0.2306027527382121
Fold 3 IBS: 0.22886627608859147
Fold 4 IBS: 0.24513247268613395
Fold 5 IBS: 0.22925440429425864
[I 2024-04-14 21:59:49,884] Trial 89 finished with value: 0.23605940788347027 and parameters: {'subsample': 0.9450773482205609, 'dropout_rate': 0.23759419161670864, 'n_estimators': 297, 'learning_rate': 0.001146859226016428}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24666650902599224
Fold 2 IBS: 0.2310429483111688
Fold 3 IBS: 0.22889818643762444
Fold 4 IBS: 0.2440831582575066
Fold 5 IBS: 0.22929655120675618
[I 2024-04-14 21:59:52,674] Trial 90 finished with value: 0.23599747064780968 and parameters: {'subsample': 0.9152094155896509, 'dropout_rate': 0.30747254385959993, 'n_estimators': 39, 'learning_rate': 0.006074717217283475}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24721818189132572
Fold 2 IBS: 0.23199660225563437
Fold 3 IBS: 0.22897828298681
Fold 4 IBS: 0.24205505683697023
Fold 5 IBS: 0.2293908357145491
[I 2024-04-14 21:59:53,060] Trial 91 finished with value: 0.23592779193705787 and parameters: {'subsample': 0.9711563480249188, 'dropout_rate': 0.19356123866550598, 'n_estimators': 1, 'learning_rate': 0.010170857018729856}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.2468152818294796
Fold 2 IBS: 0.23131560396141712
Fold 3 IBS: 0.22891906593137523
Fold 4 IBS: 0.24346980676770308
Fold 5 IBS: 0.2293183264483011
[I 2024-04-14 21:59:54,336] Trial 92 finished with value: 0.23596761698765523 and parameters: {'subsample': 0.9797476220385768, 'dropout_rate': 0.19245804163576646, 'n_estimators': 16, 'learning_rate': 0.010710354537044615}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24668585661515566
Fold 2 IBS: 0.23106904461711295
Fold 3 IBS: 0.22889950511077223
Fold 4 IBS: 0.24402598425058153
Fold 5 IBS: 0.22930518150821522
[I 2024-04-14 21:59:56,451] Trial 93 finished with value: 0.23599711442036755 and parameters: {'subsample': 0.8845808176954925, 'dropout_rate': 0.20805100187616282, 'n_estimators': 31, 'learning_rate': 0.007430043665252137}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24712945341986975
Fold 2 IBS: 0.23183516249990266
Fold 3 IBS: 0.22896444807043811
Fold 4 IBS: 0.24237065904183
Fold 5 IBS: 0.2293749208863921
[I 2024-04-14 21:59:57,594] Trial 94 finished with value: 0.23593492878368655 and parameters: {'subsample': 0.9422442367718005, 'dropout_rate': 0.18619257295551966, 'n_estimators': 13, 'learning_rate': 0.0036495029597569235}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24647530705449758
Fold 2 IBS: 0.23066924028348762
Fold 3 IBS: 0.22887161499426478
Fold 4 IBS: 0.2449391057979653

Fold 5 IBS: 0.22928162319464118
[I 2024-04-14 21:59:59,644] Trial 95 finished with value: 0.2360473782649713 and parameters: {'subsample': 0.9263734948124571, 'dropout_rate': 0.7166910143860685, 'n_estimators': 26, 'learning_rate': 0.012609107231273231}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24646324144717863
Fold 2 IBS: 0.23065220891764882
Fold 3 IBS: 0.2288695374800145
Fold 4 IBS: 0.2450357850312088
Fold 5 IBS: 0.22926607450001513
[I 2024-04-14 22:00:04,672] Trial 96 finished with value: 0.2360573694752132 and parameters: {'subsample': 0.9009724346080058, 'dropout_rate': 0.7497063849503668, 'n_estimators': 56, 'learning_rate': 0.0059409799616813586}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24696794468000824
Fold 2 IBS: 0.23157500045630858
Fold 3 IBS: 0.22894051312961808
Fold 4 IBS: 0.24292659425614868
Fold 5 IBS: 0.22934542332213265
[I 2024-04-14 22:00:06,328] Trial 97 finished with value: 0.23595109516884322 and parameters: {'subsample': 0.9756890922028284, 'dropout_rate': 0.1437665485108484, 'n_estimators': 11, 'learning_rate': 0.010030604213388214}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24724115078989378
Fold 2 IBS: 0.23202741967352528
Fold 3 IBS: 0.2289786556033348
Fold 4 IBS: 0.24199996940972593
Fold 5 IBS: 0.22939501174818983
[I 2024-04-14 22:00:06,783] Trial 98 finished with value: 0.2359284414449339 and parameters: {'subsample': 0.6038338998685381, 'dropout_rate': 0.3833511468074837, 'n_estimators': 1, 'learning_rate': 0.003232638799132136}. Best is trial 81 with value: 0.23592753810805128.
Fold 1 IBS: 0.24702081702602088
Fold 2 IBS: 0.23155629107989814
Fold 3 IBS: 0.22889480583356378
Fold 4 IBS: 0.24300251583607665
Fold 5 IBS: 0.2293607700132696
[I 2024-04-14 22:00:09,950] Trial 99 finished with value: 0.23596703995776586 and parameters: {'subsample': 0.6019670179061509, 'dropout_rate': 0.38858740825658117, 'n_estimators': 39, 'learning_rate': 0.0029369107340728147}. Best is trial 81 with value: 0.23592753810805128.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.23592753810805128], datetime_start=datetime.datetime(2024, 4, 14, 21, 59, 12, 961957), datetime_complete=datetime.datetime(2024, 4, 14, 21, 59, 13, 326508), params={'subsample': 0.9053231560128981, 'dropout_rate': 0.3796513018058376, 'n_estimators': 1, 'learning_rate': 0.003225987542685412}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.9053231560128981, 'dropout_rate': 0.3796513018058376, 'n_estimators': 1, 'learning_rate': 0.003225987542685412}


* Best Score for IBS:
 0.23592753810805128

In [73]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [74]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.578
train_ibs:  0.236

#### Test

In [75]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [76]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.944388489444451,
                                              learning_rate=0.0413681807904896,
                                              n_estimators=38, random_state=123,
                                              subsample=0.30359910909282395)

C-index score: 0.597

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3796513018058376,
                                              learning_rate=0.003225987542685412,
                                              n_estimators=1, random_state=123,
                                              subsample=0.9053231560128981)

IBS: 0.229

In [77]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [78]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.859   1.0
Randomsurvivalforest             0.826   2.0
GradientBoosting                 0.686   3.0
CoxElastic                       0.644   4.0
CoxRidge                         0.596   5.0
ComponentwiseGradientBoosting    0.578   6.0
CoxLasso                         0.468   7.0

In [79]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.213   1.0
ExtraSurvivalTrees             0.217   2.0
GradientBoosting               0.231   3.0
CoxElastic                     0.234   4.0
CoxRidge                       0.236   5.5
ComponentwiseGradientBoosting  0.236   5.5
CoxLasso                       0.433   7.0

In [80]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.597   1.0
CoxElastic                       0.532   2.0
CoxLasso                         0.522   3.0
GradientBoosting                 0.518   4.0
Randomsurvivalforest             0.516   5.0
CoxRidge                         0.510   6.0
ExtraSurvivalTrees               0.506   7.0

In [81]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxElastic                     0.228   1.0
CoxRidge                       0.229   2.5
ComponentwiseGradientBoosting  0.229   2.5
GradientBoosting               0.230   4.0
ExtraSurvivalTrees             0.245   5.0
Randomsurvivalforest           0.258   6.0
CoxLasso                       0.423   7.0

In [86]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/minmax/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_minmax_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [87]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-16