In [85]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler

In [86]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [87]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [88]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [89]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [90]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [91]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [92]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [93]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [94]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [95]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [96]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [97]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [98]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [99]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [100]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [101]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

# Feature Selection

In [102]:
# Choose features from the result of Cox PLSR in R
plsr = [
"shape_MajorAxisLength",
"shape_Elongation",
"glszm_LargeAreaLowGrayLevelEmphasis_CT_c16",
"shape_Sphericity",
"shape_MinorAxisLength",
"shape_SurfaceVolumeRatio",
"LBP_201_PET",
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2",
"shape_Flatness",
"glszm_GrayLevelNonUniformityNormalized_PET_c04"
]

In [103]:
X_plsr = X.loc[:, plsr]
X_new = X_plsr.copy()

In [104]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, plsr]

# Standardization

In [105]:
# Copy the original X for later 
original_X = X.copy()

In [106]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [107]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [108]:
X_new

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,42.073251,0.600926,7442.066260,0.761164,25.282894,0.251218,0.000062,0.000959,0.535140,0.140496
1,24.613845,0.841579,238.870676,0.697049,20.714498,0.489853,0.000349,0.002776,0.367109,0.180556
2,48.030294,0.772821,12957.157420,0.565792,37.118833,0.278467,0.000000,0.001179,0.597785,0.251029
3,25.589900,0.847727,233.632355,0.684364,21.693241,0.474018,0.000000,0.002748,0.405730,0.190083
4,34.684750,0.831483,121.921768,0.503142,28.839789,0.563135,0.000399,0.002309,0.442406,0.160494
...,...,...,...,...,...,...,...,...,...,...
134,33.069705,0.680294,1528.464999,0.742102,22.497115,0.322021,0.000000,0.001347,0.523608,0.285714
135,41.043692,0.758193,41182.958565,0.722918,31.119023,0.227705,0.000079,0.000850,0.735524,0.200000
136,36.618802,0.770113,3964.057173,0.652963,28.200620,0.298398,0.000000,0.001111,0.648063,0.173469
137,45.870392,0.628897,5243.112516,0.724255,28.847736,0.252893,0.000054,0.000935,0.492193,0.263889
138,30.363259,0.892637,2169.952628,0.722633,27.103353,0.290461,0.000000,0.000629,0.756267,0.260331

In [109]:
X_new_std

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,0.350904,0.461898,0.005519,0.828413,0.236549,0.263957,0.088609,0.138260,0.499075,0.031357
1,0.123069,0.829873,0.000158,0.645006,0.167245,0.707641,0.501821,0.522853,0.220565,0.112421
2,0.428640,0.724738,0.009624,0.269537,0.416103,0.314620,0.000000,0.184826,0.602909,0.255029
3,0.135806,0.839273,0.000154,0.608721,0.182093,0.678200,0.000000,0.516826,0.284579,0.131700
4,0.254489,0.814436,0.000071,0.090323,0.290508,0.843892,0.572624,0.424002,0.345369,0.071825
...,...,...,...,...,...,...,...,...,...,...
134,0.233413,0.583257,0.001118,0.773882,0.194288,0.395598,0.000000,0.220460,0.479962,0.325218
135,0.337469,0.702369,0.030632,0.719008,0.325084,0.220239,0.113114,0.115152,0.831212,0.151769
136,0.279727,0.720597,0.002931,0.518897,0.280811,0.351677,0.000000,0.170483,0.686245,0.098082
137,0.400455,0.504667,0.003883,0.722831,0.290628,0.267071,0.077871,0.133243,0.427891,0.281053
138,0.198096,0.907943,0.001595,0.718191,0.264165,0.336919,0.000000,0.068498,0.865592,0.273852

In [110]:
MAASTRO_new

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,50.002093,0.765178,9404.025346,0.668072,38.260495,0.215184,0.000026,0.000768,0.610062,0.232422
1,41.753334,0.776540,16468.863361,0.669961,32.423122,0.276092,0.000167,0.001213,0.504616,0.339506
2,44.375483,0.697164,3829.811759,0.624081,30.936983,0.298887,0.000000,0.001176,0.478604,0.171875
3,46.115989,0.574636,2212.056593,0.577624,26.499895,0.361096,0.000080,0.001192,0.446059,0.166667
4,54.394967,0.633419,20185.616389,0.630933,34.454789,0.251519,0.000035,0.000766,0.480378,0.301020
...,...,...,...,...,...,...,...,...,...,...
94,34.218615,0.882411,18006.593217,0.671754,30.194871,0.307574,0.000078,0.001137,0.577884,0.202216
95,51.046869,0.535802,1303.136099,0.632189,27.351039,0.289922,0.000054,0.000962,0.455642,0.157025
96,50.417953,0.716610,8928.353080,0.645548,36.130031,0.228184,0.000028,0.000621,0.631485,0.460317
97,44.901412,0.665145,13835.684015,0.727488,29.865942,0.223872,0.000000,0.000947,0.628338,0.314879
98,36.574294,0.616262,1301.796144,0.672838,22.539345,0.347373,0.000112,0.001661,0.469139,0.182222

In [111]:
MAASTRO_new_std

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,0.454371,0.713050,0.006979,0.562115,0.433423,0.196961,0.037694,0.097918,0.623259,0.217377
1,0.346729,0.730423,0.012238,0.567520,0.344868,0.310203,0.240548,0.192033,0.448482,0.434071
2,0.380947,0.609052,0.002831,0.436277,0.322323,0.352585,0.000000,0.184231,0.405367,0.094855
3,0.403660,0.421699,0.001627,0.303383,0.255011,0.468248,0.114827,0.187680,0.351425,0.084316
4,0.511695,0.511582,0.015004,0.455879,0.375689,0.264517,0.050658,0.097424,0.408308,0.356191
...,...,...,...,...,...,...,...,...,...,...
94,0.248406,0.892307,0.013382,0.572648,0.311065,0.368738,0.111676,0.175997,0.569924,0.156253
95,0.468005,0.362320,0.000950,0.459472,0.267923,0.335917,0.078027,0.138832,0.367308,0.064805
96,0.459798,0.638788,0.006625,0.497683,0.401103,0.221130,0.040540,0.066663,0.658767,0.678542
97,0.387810,0.560093,0.010278,0.732079,0.306075,0.213114,0.000000,0.135787,0.653551,0.384235
98,0.279146,0.485348,0.000949,0.575748,0.194928,0.442734,0.161501,0.286841,0.389679,0.115794

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [112]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:21,120] A new study created in memory with name: no-name-51b7705f-4a87-4318-8792-b9b03eabda1e

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-15 13:33:21,408] A new study created in memory with name: no-name-14f97856-9afa-4a2f-bd7c-99a26d4822dd

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:33:21,402] Trial 0 finished with value: 0.7028948264777959 and parameters: {}. Best is trial 0 with value: 0.7028948264777959.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7028948264777959], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 21, 184048), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 21, 401117), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7028948264777959

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.26188816761455536
Fold 2 IBS: 0.17457592134628114
Fold 3 IBS: 0.15644372418899147
Fold 4 IBS: 0.2105625191550176
Fold 5 IBS: 0.191398831336509
[I 2024-04-15 13:33:21,615] Trial 0 finished with value: 0.1989738327282709 and parameters: {}. Best is trial 0 with value: 0.1989738327282709.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1989738327282709], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 21, 433092), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 21, 615521), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1989738327282709

In [113]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [114]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.703
train_ibs:  0.199

#### Test

In [115]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [116]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.528
IBS score: 0.309

In [117]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [118]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [119]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:21,732] A new study created in memory with name: no-name-598da623-6695-45e5-ad25-01251f054d69

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-15 13:33:21,826] A new study created in memory with name: no-name-77ad6b98-1049-4390-9b38-fc99124b28f1

Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6841085271317829
Fold 3 C-index: 0.5319148936170213
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6502145922746781
[I 2024-04-15 13:33:21,820] Trial 0 finished with value: 0.6316800325806103 and parameters: {}. Best is trial 0 with value: 0.6316800325806103.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6316800325806103], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 21, 752009), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 21, 820189), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6316800325806103

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709891124252
Fold 2 IBS: 0.23203988190746228
Fold 3 IBS: 0.2289818679949847
Fold 4 IBS: 0.24197476918755945
Fold 5 IBS: 0.22939559123303355
[I 2024-04-15 13:33:21,938] Trial 0 finished with value: 0.2359278418468565 and parameters: {}. Best is trial 0 with value: 0.2359278418468565.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2359278418468565], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 21, 853074), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 21, 938630), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2359278418468565

In [120]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [121]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.632
train_ibs:  0.236

#### Test

In [122]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [123]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.531

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [124]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [125]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:22,041] A new study created in memory with name: no-name-9896c6a1-30e0-4d09-9062-e63afc143e02

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8

[I 2024-04-15 13:33:22,268] A new study created in memory with name: no-name-1a5e2a5f-d66a-42f7-8887-a5c97ecd9094

Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:22,263] Trial 0 finished with value: 0.7011706560246108 and parameters: {}. Best is trial 0 with value: 0.7011706560246108.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7011706560246108], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 22, 62023), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 22, 263580), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7011706560246108

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2618548971908547
Fold 2 IBS: 0.17535907857190686
Fold 3 IBS: 0.15772602324118667
Fold 4 IBS: 0.21093897607088266
Fold 5 IBS: 0.19001858270911773
[I 2024-04-15 13:33:22,515] Trial 0 finished with value: 0.19917951155678973 and parameters: {}. Best is trial 0 with value: 0.19917951155678973.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19917951155678973], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 22, 293805), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 22, 515423), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19917951155678973

In [126]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [127]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.701
train_ibs:  0.199

#### Test

In [128]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [129]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.528

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.308

In [130]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [131]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:33:22,673] A new study created in memory with name: no-name-6155cf04-86dc-42be-b6cc-540eb479f36e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:22,899] Trial 0 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7028727836841854.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:23,145] Trial 1 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:23,413] Trial 2 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:23,608] Trial 3 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:23,791] Trial 4 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:23,983] Trial 5 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:24,138] Trial 6 finished with value: 0.7011706560246108 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:24,324] Trial 7 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:24,524] Trial 8 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:24,763] Trial 9 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:24,838] Trial 10 finished with value: 0.6454414667378566 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.7037238475139727.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:25,079] Trial 11 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2694535558091148}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:25,349] Trial 12 finished with value: 0.648803485277134 and parameters: {'l1_ratio': 0.21257181845809592}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:25,417] Trial 13 finished with value: 0.6469771168100706 and parameters: {'l1_ratio': 0.007125118463963187}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:25,654] Trial 14 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2799002900234457}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:25,861] Trial 15 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.3318175594239037}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:25,949] Trial 16 finished with value: 0.6359013327003632 and parameters: {'l1_ratio': 0.15124412316173128}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:26,149] Trial 17 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.5311144373644456}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:26,205] Trial 18 finished with value: 0.6469771168100706 and parameters: {'l1_ratio': 0.03268458553030726}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:26,387] Trial 19 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.34446003329366204}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:26,472] Trial 20 finished with value: 0.6359013327003632 and parameters: {'l1_ratio': 0.15523641724239506}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:26,665] Trial 21 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2733589608767589}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:26,853] Trial 22 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.275237213942644}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:27,033] Trial 23 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.427622193982516}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:27,081] Trial 24 finished with value: 0.644666272939407 and parameters: {'l1_ratio': 0.13218810941910744}. Best is trial 11 with value: 0.7045206602629766.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:27,252] Trial 25 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6016458784897931}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:27,421] Trial 26 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.24991176779209634}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:27,600] Trial 27 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.35074027786718637}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:27,652] Trial 28 finished with value: 0.646201923011621 and parameters: {'l1_ratio': 0.07486953246354136}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:27,731] Trial 29 finished with value: 0.6366765264988128 and parameters: {'l1_ratio': 0.18075602395385282}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:27,948] Trial 30 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.30248103661051284}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:28,105] Trial 31 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.24354183082267372}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:28,296] Trial 32 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2799675719409404}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:28,472] Trial 33 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.3747768207999646}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:28,646] Trial 34 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4613244161689204}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:28,784] Trial 35 finished with value: 0.6479524214473468 and parameters: {'l1_ratio': 0.21772002383252356}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:28,977] Trial 36 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.2827897224777738}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:29,130] Trial 37 finished with value: 0.7011706560246108 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:29,292] Trial 38 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.5656671528281025}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:29,340] Trial 39 finished with value: 0.6454414667378566 and parameters: {'l1_ratio': 0.0854820291395414}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:29,523] Trial 40 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4064797529407133}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:29,714] Trial 41 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.31925855200093667}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:29,894] Trial 42 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.3005899681660959}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:30,009] Trial 43 finished with value: 0.6418267410910875 and parameters: {'l1_ratio': 0.19971749845649905}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:30,198] Trial 44 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.26872123626066835}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:30,377] Trial 45 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4326322226577207}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:30,554] Trial 46 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4954019844924079}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:30,737] Trial 47 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.3756371011948657}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:30,860] Trial 48 finished with value: 0.6366765264988128 and parameters: {'l1_ratio': 0.16956959855657594}. Best is trial 11 with value: 0.7045206602629766.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:31,072] Trial 49 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.31096634412376933}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:31,129] Trial 50 finished with value: 0.644666272939407 and parameters: {'l1_ratio': 0.12981789694574747}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:31,347] Trial 51 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2579449037128121}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:31,549] Trial 52 finished with value: 0.6479524214473468 and parameters: {'l1_ratio': 0.2225918073443785}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:31,799] Trial 53 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.28453416667649345}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:32,060] Trial 54 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.3486048659066972}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:32,379] Trial 55 finished with value: 0.648803485277134 and parameters: {'l1_ratio': 0.21234357390697153}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:32,594] Trial 56 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.45950561200188966}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:32,799] Trial 57 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.38204392751387833}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:32,855] Trial 58 finished with value: 0.644666272939407 and parameters: {'l1_ratio': 0.11904600659951162}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:32,919] Trial 59 finished with value: 0.6469771168100706 and parameters: {'l1_ratio': 0.05479127023303945}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:33,016] Trial 60 finished with value: 0.6366765264988128 and parameters: {'l1_ratio': 0.17974286497280306}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:33,247] Trial 61 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.31118857180269366}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:33,481] Trial 62 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2978879243139311}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:33,759] Trial 63 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.35835727930662503}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:34,108] Trial 64 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.25050849312349327}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:34,335] Trial 65 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.32308920812286784}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:34,527] Trial 66 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6856026801686635}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:34,698] Trial 67 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.7392393754397737}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:34,930] Trial 68 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2757282075562005}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:35,129] Trial 69 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.24013541972888192}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:35,322] Trial 70 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.406989450719428}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:35,522] Trial 71 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2736043243126882}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:35,732] Trial 72 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.33898917429804437}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087

Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:35,820] Trial 73 finished with value: 0.6366765264988128 and parameters: {'l1_ratio': 0.18606441127784684}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:35,995] Trial 74 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.22882699319099878}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:36,188] Trial 75 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.29270674768937965}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:36,398] Trial 76 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2609685899836869}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:36,482] Trial 77 finished with value: 0.6359013327003632 and parameters: {'l1_ratio': 0.1538369872912866}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:36,613] Trial 78 finished with value: 0.6418267410910875 and parameters: {'l1_ratio': 0.2074998117953252}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:36,851] Trial 79 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.3627733864001181}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:37,051] Trial 80 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.3108604744513396}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:37,248] Trial 81 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.26900993977300336}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:37,435] Trial 82 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.24928447136289628}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:37,618] Trial 83 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.3333692412034647}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:37,790] Trial 84 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.23228980773986613}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:37,902] Trial 85 finished with value: 0.6366765264988128 and parameters: {'l1_ratio': 0.19623610454732096}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:38,116] Trial 86 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.3944248401331686}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:38,301] Trial 87 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.2935760423585119}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:38,360] Trial 88 finished with value: 0.644666272939407 and parameters: {'l1_ratio': 0.11112266966621692}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:38,548] Trial 89 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4460474083713629}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:38,634] Trial 90 finished with value: 0.6366765264988128 and parameters: {'l1_ratio': 0.16720828711459296}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:38,819] Trial 91 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.29602367693764875}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:39,103] Trial 92 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.2626323544857595}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:39,307] Trial 93 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.3274508568199346}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:39,551] Trial 94 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.30523088145311067}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:39,776] Trial 95 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.36451960851925624}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:39,920] Trial 96 finished with value: 0.6471919651735825 and parameters: {'l1_ratio': 0.22404528401871152}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:40,103] Trial 97 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6242322112672503}. Best is trial 11 with value: 0.7045206602629766.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:33:40,313] Trial 98 finished with value: 0.7037238475139727 and parameters: {'l1_ratio': 0.28304195370163826}. Best is trial 11 with value: 0.7045206602629766.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021

[I 2024-04-15 13:33:40,375] A new study created in memory with name: no-name-b9b99125-7a0d-4927-9672-d457ed16bce9

Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:33:40,369] Trial 99 finished with value: 0.644666272939407 and parameters: {'l1_ratio': 0.1419109421212874}. Best is trial 11 with value: 0.7045206602629766.


* Best trial for C-index:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.7045206602629766], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 24, 840020), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 25, 79766), params={'l1_ratio': 0.2694535558091148}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=11, value=None)


* Best Score for C-index:
 0.7045206602629766

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.26112506117169937
Fold 2 IBS: 0.17539322866078413
Fold 3 IBS: 0.15749720573738968
Fold 4 IBS: 0.210901523737872
Fold 5 IBS: 0.18993209550030718
[I 2024-04-15 13:33:40,583] Trial 0 finished with value: 0.19896982296161048 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.19896982296161048.
Fold 1 IBS: 0.2608554376088747
Fold 2 IBS: 0.17516304746695047
Fold 3 IBS: 0.15722660100172273
Fold 4 IBS: 0.2108811839542744
Fold 5 IBS: 0.18996281056969944
[I 2024-04-15 13:33:40,794] Trial 1 finished with value: 0.19881781612030436 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.2608411182829978
Fold 2 IBS: 0.17510633367570527
Fold 3 IBS: 0.22888934703897795
Fold 4 IBS: 0.2108739930332697
Fold 5 IBS: 0.18995494728414902
[I 2024-04-15 13:33:40,978] Trial 2 finished with value: 0.21313314786301993 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.2610169821390721
Fold 2 IBS: 0.17540632856902016
Fold 3 IBS: 0.15739831270715512
Fold 4 IBS: 0.210903012021006
Fold 5 IBS: 0.1899721012562321
[I 2024-04-15 13:33:41,189] Trial 3 finished with value: 0.1989393473384971 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.2611932227742993
Fold 2 IBS: 0.17534353987333956
Fold 3 IBS: 0.15745259964909972
Fold 4 IBS: 0.21091969147328501
Fold 5 IBS: 0.18999248713375677
[I 2024-04-15 13:33:41,420] Trial 4 finished with value: 0.1989803081807561 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.2609266275156333
Fold 2 IBS: 0.1752405318927083
Fold 3 IBS: 0.15733699875506685
Fold 4 IBS: 0.21091871779093227
Fold 5 IBS: 0.1899775353099474
[I 2024-04-15 13:33:41,639] Trial 5 finished with value: 0.19888008225285764 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.26178543023256606
Fold 2 IBS: 0.1752838870200499
Fold 3 IBS: 0.1577643132672613
Fold 4 IBS: 0.21094969253921553
Fold 5 IBS: 0.18997110195644676
[I 2024-04-15 13:33:41,834] Trial 6 finished with value: 0.19915088500310793 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.2611489003465161
Fold 2 IBS: 0.1753100548620053
Fold 3 IBS: 0.15741814830415898
Fold 4 IBS: 0.21090953585481062
Fold 5 IBS: 0.19000572295301604
[I 2024-04-15 13:33:42,012] Trial 7 finished with value: 0.19895847246410142 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.26096249607860045
Fold 2 IBS: 0.17526138281981796
Fold 3 IBS: 0.15729004721754786
Fold 4 IBS: 0.21089800098521405
Fold 5 IBS: 0.18997551347637742
[I 2024-04-15 13:33:42,207] Trial 8 finished with value: 0.19887748811551156 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.2609504796773552
Fold 2 IBS: 0.1752104527893202
Fold 3 IBS: 0.15724872857456504
Fold 4 IBS: 0.21090934659002628
Fold 5 IBS: 0.1899762116686488
[I 2024-04-15 13:33:42,445] Trial 9 finished with value: 0.1988590438599831 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.24574106625286365
Fold 2 IBS: 0.22945681161749595
Fold 3 IBS: 0.22892153816034494
Fold 4 IBS: 0.23975630510294846
Fold 5 IBS: 0.22759744040227006
[I 2024-04-15 13:33:42,536] Trial 10 finished with value: 0.2342946323071846 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.19881781612030436.
Fold 1 IBS: 0.260863917110021
Fold 2 IBS: 0.1751348486536706
Fold 3 IBS: 0.15720385443933207
Fold 4 IBS: 0.2108996707315747
Fold 5 IBS: 0.18996568806058076
[I 2024-04-15 13:33:42,780] Trial 11 finished with value: 0.19881359579903582 and parameters: {'l1_ratio': 0.2694535558091148}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608495860325745
Fold 2 IBS: 0.1750841602855989
Fold 3 IBS: 0.22888982907748237
Fold 4 IBS: 0.237193116490385
Fold 5 IBS: 0.1899758311286211
[I 2024-04-15 13:33:43,091] Trial 12 finished with value: 0.21839850460293236 and parameters: {'l1_ratio': 0.21257181845809592}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.24713768071148
Fold 2 IBS: 0.2318523522963886
Fold 3 IBS: 0.22897660040539544
Fold 4 IBS: 0.24181297363729448
Fold 5 IBS: 0.2292661497818706
[I 2024-04-15 13:33:43,310] Trial 13 finished with value: 0.2358091513664858 and parameters: {'l1_ratio': 0.007125118463963187}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609106580661007
Fold 2 IBS: 0.17517396126175977
Fold 3 IBS: 0.15717001981519443
Fold 4 IBS: 0.21088957860251964
Fold 5 IBS: 0.18993272925633922
[I 2024-04-15 13:33:43,816] Trial 14 finished with value: 0.19881538940038274 and parameters: {'l1_ratio': 0.2799002900234457}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608811493616054
Fold 2 IBS: 0.17521148763818448
Fold 3 IBS: 0.15724804028999576
Fold 4 IBS: 0.2108774093545421
Fold 5 IBS: 0.18995723211578913
[I 2024-04-15 13:33:44,199] Trial 15 finished with value: 0.19883506375202337 and parameters: {'l1_ratio': 0.3318175594239037}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608081627169915
Fold 2 IBS: 0.22804890692983854
Fold 3 IBS: 0.22890098381758364
Fold 4 IBS: 0.2385596765178366
Fold 5 IBS: 0.22660614743563873
[I 2024-04-15 13:33:44,378] Trial 16 finished with value: 0.23658477548357779 and parameters: {'l1_ratio': 0.15124412316173128}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609555533605555
Fold 2 IBS: 0.1753522451574907
Fold 3 IBS: 0.15735301984580632
Fold 4 IBS: 0.21088542930405005
Fold 5 IBS: 0.190016915654175
[I 2024-04-15 13:33:44,748] Trial 17 finished with value: 0.19891263266441553 and parameters: {'l1_ratio': 0.5311144373644456}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.24674492729561723
Fold 2 IBS: 0.23117951131758724
Fold 3 IBS: 0.22895879124490784
Fold 4 IBS: 0.24123300934048408
Fold 5 IBS: 0.2288000675373896
[I 2024-04-15 13:33:44,837] Trial 18 finished with value: 0.2353832613471972 and parameters: {'l1_ratio': 0.03268458553030726}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26093075585509273
Fold 2 IBS: 0.17519358432641718
Fold 3 IBS: 0.15721324154652724
Fold 4 IBS: 0.21089552934864836
Fold 5 IBS: 0.19000468351987918
[I 2024-04-15 13:33:45,071] Trial 19 finished with value: 0.19884755891931297 and parameters: {'l1_ratio': 0.34446003329366204}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26083735604130087
Fold 2 IBS: 0.22794323017161286
Fold 3 IBS: 0.22889983242783296
Fold 4 IBS: 0.23847029860206934
Fold 5 IBS: 0.2265314951204235
[I 2024-04-15 13:33:45,186] Trial 20 finished with value: 0.23653644247264793 and parameters: {'l1_ratio': 0.15523641724239506}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608817806003539
Fold 2 IBS: 0.1751857672889257
Fold 3 IBS: 0.15719124612545252
Fold 4 IBS: 0.21089841827353292
Fold 5 IBS: 0.18998320568306068
[I 2024-04-15 13:33:45,494] Trial 21 finished with value: 0.19882808359426515 and parameters: {'l1_ratio': 0.2733589608767589}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26085187864359155
Fold 2 IBS: 0.17516436997819088
Fold 3 IBS: 0.15722910289950656
Fold 4 IBS: 0.21088221346218763
Fold 5 IBS: 0.1899591977100478
[I 2024-04-15 13:33:45,740] Trial 22 finished with value: 0.19881735253870486 and parameters: {'l1_ratio': 0.28542083307623833}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26089541734118316
Fold 2 IBS: 0.17529511004811052
Fold 3 IBS: 0.15730556266669452
Fold 4 IBS: 0.2109051206824016
Fold 5 IBS: 0.19002139746159352
[I 2024-04-15 13:33:45,994] Trial 23 finished with value: 0.19888452163999665 and parameters: {'l1_ratio': 0.43675156276892446}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609989882919725
Fold 2 IBS: 0.17531126588687437
Fold 3 IBS: 0.15740958959133508
Fold 4 IBS: 0.21090742941509735
Fold 5 IBS: 0.18997631276153154
[I 2024-04-15 13:33:46,218] Trial 24 finished with value: 0.19892071718936216 and parameters: {'l1_ratio': 0.5910098988284204}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2450886791106046
Fold 2 IBS: 0.2283320925194477
Fold 3 IBS: 0.22890434686930097
Fold 4 IBS: 0.238799508255609
Fold 5 IBS: 0.22680604216972253
[I 2024-04-15 13:33:46,301] Trial 25 finished with value: 0.23358613378493698 and parameters: {'l1_ratio': 0.14054263101216027}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608538083357651
Fold 2 IBS: 0.1751221104252334

Fold 3 IBS: 0.2288900588406883
Fold 4 IBS: 0.21087561155991283
Fold 5 IBS: 0.18995391936920947
[I 2024-04-15 13:33:46,518] Trial 26 finished with value: 0.21313910170616182 and parameters: {'l1_ratio': 0.24616747074631654}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609127279468582
Fold 2 IBS: 0.17520014353853527
Fold 3 IBS: 0.15722538997452715
Fold 4 IBS: 0.2108677192427991
Fold 5 IBS: 0.18998633402187168
[I 2024-04-15 13:33:46,737] Trial 27 finished with value: 0.1988384629449183 and parameters: {'l1_ratio': 0.3397747316535139}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2460590185192229
Fold 2 IBS: 0.23000317310124618
Fold 3 IBS: 0.22893198666557424
Fold 4 IBS: 0.24022330373865497
Fold 5 IBS: 0.2279802197234489
[I 2024-04-15 13:33:46,806] Trial 28 finished with value: 0.23463954034962944 and parameters: {'l1_ratio': 0.07729981217319248}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26151157669893454
Fold 2 IBS: 0.17534939140852926
Fold 3 IBS: 0.15758045090068917
Fold 4 IBS: 0.2109298119370807
Fold 5 IBS: 0.18995658346644795
[I 2024-04-15 13:33:46,985] Trial 29 finished with value: 0.19906556288233632 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26103626482634884
Fold 2 IBS: 0.17533485800372223
Fold 3 IBS: 0.15743672108738044
Fold 4 IBS: 0.21091607155552086
Fold 5 IBS: 0.18996330492880092
[I 2024-04-15 13:33:47,187] Trial 30 finished with value: 0.19893744408035463 and parameters: {'l1_ratio': 0.6252677847863235}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26092034575130174
Fold 2 IBS: 0.17519745512643708
Fold 3 IBS: 0.15725881976313064
Fold 4 IBS: 0.2108857485448049
Fold 5 IBS: 0.19002210357442234
[I 2024-04-15 13:33:47,407] Trial 31 finished with value: 0.19885689455201935 and parameters: {'l1_ratio': 0.3013220087820099}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608014248490127
Fold 2 IBS: 0.22740157522676416
Fold 3 IBS: 0.22889483714447856
Fold 4 IBS: 0.23801326918392332
Fold 5 IBS: 0.2261484149028818
[I 2024-04-15 13:33:47,509] Trial 32 finished with value: 0.2362519042614121 and parameters: {'l1_ratio': 0.17568885485567806}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608939583557352
Fold 2 IBS: 0.1751626345921327
Fold 3 IBS: 0.22889085815187626
Fold 4 IBS: 0.21089330215531518
Fold 5 IBS: 0.18999478486469223
[I 2024-04-15 13:33:47,700] Trial 33 finished with value: 0.21316710762395036 and parameters: {'l1_ratio': 0.25444217774648437}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609550612397616
Fold 2 IBS: 0.17519109903503244
Fold 3 IBS: 0.1572269721720945
Fold 4 IBS: 0.21089720106788024
Fold 5 IBS: 0.1899834431386451
[I 2024-04-15 13:33:47,925] Trial 34 finished with value: 0.19885075533068278 and parameters: {'l1_ratio': 0.36930267499447855}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609224546029574
Fold 2 IBS: 0.1753106682690044
Fold 3 IBS: 0.15731747095676102
Fold 4 IBS: 0.21091024557726934
Fold 5 IBS: 0.1900299379491185
[I 2024-04-15 13:33:48,181] Trial 35 finished with value: 0.19889815547102213 and parameters: {'l1_ratio': 0.467762195125322}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26089489336815974
Fold 2 IBS: 0.22661252218569206
Fold 3 IBS: 0.22889037997659237
Fold 4 IBS: 0.2373510283314062
Fold 5 IBS: 0.18993799150907464
[I 2024-04-15 13:33:48,326] Trial 36 finished with value: 0.228737363074185 and parameters: {'l1_ratio': 0.20545053472298308}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26092197577963455
Fold 2 IBS: 0.17519680388633968
Fold 3 IBS: 0.15725757701968426
Fold 4 IBS: 0.21088524096574665
Fold 5 IBS: 0.18992808639208125
[I 2024-04-15 13:33:48,564] Trial 37 finished with value: 0.19883793680869727 and parameters: {'l1_ratio': 0.30171831483333933}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26091700247962357
Fold 2 IBS: 0.17524397454518495
Fold 3 IBS: 0.15726274334953924
Fold 4 IBS: 0.2108807613163258
Fold 5 IBS: 0.18996661243751847
[I 2024-04-15 13:33:48,821] Trial 38 finished with value: 0.19885421882563842 and parameters: {'l1_ratio': 0.41998087355589575}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.24580961137587815
Fold 2 IBS: 0.22957467768290132
Fold 3 IBS: 0.22892368006824168
Fold 4 IBS: 0.23985693605895558
Fold 5 IBS: 0.2276801160052307
[I 2024-04-15 13:33:48,946] Trial 39 finished with value: 0.2343690042382415 and parameters: {'l1_ratio': 0.09353153364519104}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26095230750364323
Fold 2 IBS: 0.175208343348853
Fold 3 IBS: 0.15724768821220456
Fold 4 IBS: 0.2109087771723505
Fold 5 IBS: 0.18997806046178217
[I 2024-04-15 13:33:49,222] Trial 40 finished with value: 0.1988590353397667 and parameters: {'l1_ratio': 0.3926934040040484}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609083262627453
Fold 2 IBS: 0.17517490592817955
Fold 3 IBS: 0.15717164665687886
Fold 4 IBS: 0.21089031069466316
Fold 5 IBS: 0.18993019887119186
[I 2024-04-15 13:33:49,786] Trial 41 finished with value: 0.19881507768273174 and parameters: {'l1_ratio': 0.27936373110641877}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26089441990364526
Fold 2 IBS: 0.22661482327431579
Fold 3 IBS: 0.22889038794067812
Fold 4 IBS: 0.23735295301821252
Fold 5 IBS: 0.18993746482311502
[I 2024-04-15 13:33:49,955] Trial 42 finished with value: 0.22873800979199332 and parameters: {'l1_ratio': 0.20536379974972163}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608679142365448
Fold 2 IBS: 0.17513335610580433
Fold 3 IBS: 0.15720102407524744
Fold 4 IBS: 0.21090282005764568
Fold 5 IBS: 0.18996981791380282
[I 2024-04-15 13:33:50,193] Trial 43 finished with value: 0.198814986477809 and parameters: {'l1_ratio': 0.2703191019889935}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26086781455776836
Fold 2 IBS: 0.175158458076696
Fold 3 IBS: 0.1572178967507265
Fold 4 IBS: 0.21090205215265254
Fold 5 IBS: 0.1899754183375783
[I 2024-04-15 13:33:50,417] Trial 44 finished with value: 0.19882432797508437 and parameters: {'l1_ratio': 0.2889913550136534}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608808635590539
Fold 2 IBS: 0.1751113253104089
Fold 3 IBS: 0.22889055754011361
Fold 4 IBS: 0.2108974940031728
Fold 5 IBS: 0.1899810303708066
[I 2024-04-15 13:33:50,608] Trial 45 finished with value: 0.21315225415671116 and parameters: {'l1_ratio': 0.2516779574049648}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609492176212821
Fold 2 IBS: 0.17531345472097612
Fold 3 IBS: 0.157332937768705
Fold 4 IBS: 0.21087964526237024
Fold 5 IBS: 0.19002491325302753
[I 2024-04-15 13:33:50,799] Trial 46 finished with value: 0.19890003372527218 and parameters: {'l1_ratio': 0.4996893730938835}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609304621420064
Fold 2 IBS: 0.17522357257833931
Fold 3 IBS: 0.15727168119063184
Fold 4 IBS: 0.21088676054276984
Fold 5 IBS: 0.19001515132914004
[I 2024-04-15 13:33:51,026] Trial 47 finished with value: 0.19886552555657747 and parameters: {'l1_ratio': 0.3237705697904471}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2613256589993667
Fold 2 IBS: 0.17529152923157648
Fold 3 IBS: 0.15751295718510266
Fold 4 IBS: 0.2109050330595479
Fold 5 IBS: 0.18997209340490126
[I 2024-04-15 13:33:51,224] Trial 48 finished with value: 0.199001454376099 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609538275631491
Fold 2 IBS: 0.17519277222033056
Fold 3 IBS: 0.15722781890860282
Fold 4 IBS: 0.2108975796973228
Fold 5 IBS: 0.1899821811127284
[I 2024-04-15 13:33:51,426] Trial 49 finished with value: 0.19885083590042676 and parameters: {'l1_ratio': 0.36896478711820985}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608873498749395
Fold 2 IBS: 0.2270379875715332
Fold 3 IBS: 0.22889235792697268
Fold 4 IBS: 0.23770756663386897
Fold 5 IBS: 0.22589090334275425
[I 2024-04-15 13:33:51,526] Trial 50 finished with value: 0.23608323307001372 and parameters: {'l1_ratio': 0.1894076215547323}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.24531708848570905
Fold 2 IBS: 0.2287265506660224
Fold 3 IBS: 0.22890969131957203
Fold 4 IBS: 0.23913432667958662
Fold 5 IBS: 0.2270840812788184
[I 2024-04-15 13:33:51,588] Trial 51 finished with value: 0.2338343476859417 and parameters: {'l1_ratio': 0.12562848870933518}. Best is trial 11 with value: 0.19881359579903582.

Fold 1 IBS: 0.2609029813562119
Fold 2 IBS: 0.17511565022015008
Fold 3 IBS: 0.2288894029427478
Fold 4 IBS: 0.23697131495704718
Fold 5 IBS: 0.18993427092693696
[I 2024-04-15 13:33:51,769] Trial 52 finished with value: 0.2183627240806188 and parameters: {'l1_ratio': 0.2225918073443785}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609141656879759
Fold 2 IBS: 0.17517254220289363
Fold 3 IBS: 0.15724486047677114
Fold 4 IBS: 0.2108884783517394
Fold 5 IBS: 0.18993653853858755
[I 2024-04-15 13:33:51,982] Trial 53 finished with value: 0.19883131705159354 and parameters: {'l1_ratio': 0.2807107457107132}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609360704247251
Fold 2 IBS: 0.17523747495901695
Fold 3 IBS: 0.1573298007379569
Fold 4 IBS: 0.21091565587339614
Fold 5 IBS: 0.18998586173744106
[I 2024-04-15 13:33:52,254] Trial 54 finished with value: 0.19888097274650723 and parameters: {'l1_ratio': 0.42607274095914727}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.24646523032420437
Fold 2 IBS: 0.23070010014282571
Fold 3 IBS: 0.2289471806760494
Fold 4 IBS: 0.24082085031531986
Fold 5 IBS: 0.22846668885773688
[I 2024-04-15 13:33:52,323] Trial 55 finished with value: 0.23508001006322723 and parameters: {'l1_ratio': 0.05087714659735412}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26095988204364173
Fold 2 IBS: 0.17519163199080426
Fold 3 IBS: 0.15730348193264432
Fold 4 IBS: 0.21089817353328805
Fold 5 IBS: 0.18999981986189327
[I 2024-04-15 13:33:52,513] Trial 56 finished with value: 0.1988705978724543 and parameters: {'l1_ratio': 0.37063683913998846}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608544207616044
Fold 2 IBS: 0.17510118739559102
Fold 3 IBS: 0.22888935069718377
Fold 4 IBS: 0.2108998424072945
Fold 5 IBS: 0.1899678508265396
[I 2024-04-15 13:33:52,702] Trial 57 finished with value: 0.2131425304176427 and parameters: {'l1_ratio': 0.22945237658173784}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608926374654757
Fold 2 IBS: 0.1751769599518402
Fold 3 IBS: 0.15721910419413979
Fold 4 IBS: 0.21090230052858938
Fold 5 IBS: 0.18998191278922702
[I 2024-04-15 13:33:52,943] Trial 58 finished with value: 0.1988345829858544 and parameters: {'l1_ratio': 0.3143488475655357}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609999278746239
Fold 2 IBS: 0.1753156326868826
Fold 3 IBS: 0.15740987319831126
Fold 4 IBS: 0.21090754469411344
Fold 5 IBS: 0.18995583517034126
[I 2024-04-15 13:33:53,130] Trial 59 finished with value: 0.19891776272485448 and parameters: {'l1_ratio': 0.5458174011494372}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2453829630036645
Fold 2 IBS: 0.22884016672171262
Fold 3 IBS: 0.22891137020408084
Fold 4 IBS: 0.23923091937403188
Fold 5 IBS: 0.2271640727336496
[I 2024-04-15 13:33:53,195] Trial 60 finished with value: 0.2339058984074279 and parameters: {'l1_ratio': 0.12133111029502691}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26090709541866547
Fold 2 IBS: 0.17517540498499704
Fold 3 IBS: 0.15717250587868115
Fold 4 IBS: 0.21089069734128876
Fold 5 IBS: 0.19002803924838527
[I 2024-04-15 13:33:53,393] Trial 61 finished with value: 0.19883474857440353 and parameters: {'l1_ratio': 0.27908122122780094}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26083252805992474
Fold 2 IBS: 0.22727608343279662
Fold 3 IBS: 0.2288939007081543
Fold 4 IBS: 0.23790765446470577
Fold 5 IBS: 0.22605956550904924
[I 2024-04-15 13:33:53,489] Trial 62 finished with value: 0.23619394643492614 and parameters: {'l1_ratio': 0.18042479293853414}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608568557878599
Fold 2 IBS: 0.17516252108542663
Fold 3 IBS: 0.15722560495382124
Fold 4 IBS: 0.2108807740259953
Fold 5 IBS: 0.1899642510550631
[I 2024-04-15 13:33:53,676] Trial 63 finished with value: 0.19881800138163322 and parameters: {'l1_ratio': 0.28652651283053815}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.26091384047448163
Fold 2 IBS: 0.17519974955182457
Fold 3 IBS: 0.15722461952695282
Fold 4 IBS: 0.210867408306003
Fold 5 IBS: 0.18998746462101748
[I 2024-04-15 13:33:53,853] Trial 64 finished with value: 0.19883861649605591 and parameters: {'l1_ratio': 0.34006074111226847}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608597793924961
Fold 2 IBS: 0.17511981572736326
Fold 3 IBS: 0.22889015664430545
Fold 4 IBS: 0.2108740157184024
Fold 5 IBS: 0.18996014191775332
[I 2024-04-15 13:33:54,014] Trial 65 finished with value: 0.21314078188006408 and parameters: {'l1_ratio': 0.2473740837507581}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609736873535129
Fold 2 IBS: 0.17519238313909827
Fold 3 IBS: 0.15731308034521424
Fold 4 IBS: 0.21090196595417438
Fold 5 IBS: 0.18999736766090874
[I 2024-04-15 13:33:54,189] Trial 66 finished with value: 0.19887569689058174 and parameters: {'l1_ratio': 0.3989867664366977}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608797206685391
Fold 2 IBS: 0.17524493838781766
Fold 3 IBS: 0.1572717556050336
Fold 4 IBS: 0.21089041709812317
Fold 5 IBS: 0.18993283528618568
[I 2024-04-15 13:33:54,699] Trial 67 finished with value: 0.19884393340913983 and parameters: {'l1_ratio': 0.35221152674139977}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2608171369773373
Fold 2 IBS: 0.22768872805840018
Fold 3 IBS: 0.22889729463887504
Fold 4 IBS: 0.23825532788048037
Fold 5 IBS: 0.22635158966624536
[I 2024-04-15 13:33:54,828] Trial 68 finished with value: 0.23640201544426764 and parameters: {'l1_ratio': 0.16484838775832544}. Best is trial 11 with value: 0.19881359579903582.
Fold 1 IBS: 0.2609155706646056
Fold 2 IBS: 0.17515362411832897
Fold 3 IBS: 0.15716233430436216
Fold 4 IBS: 0.21088642052851997
Fold 5 IBS: 0.18993753803978575
[I 2024-04-15 13:33:55,055] Trial 69 finished with value: 0.19881109753112047 and parameters: {'l1_ratio': 0.25912065698588627}. Best is trial 69 with value: 0.19881109753112047.
Fold 1 IBS: 0.26090100090307783
Fold 2 IBS: 0.17513702917286236
Fold 3 IBS: 0.22888959398217026
Fold 4 IBS: 0.2108849580277905
Fold 5 IBS: 0.18993853566237878
[I 2024-04-15 13:33:55,250] Trial 70 finished with value: 0.21315022354965593 and parameters: {'l1_ratio': 0.2386922319575323}. Best is trial 69 with value: 0.19881109753112047.
Fold 1 IBS: 0.26087280626127785
Fold 2 IBS: 0.1751895158301007
Fold 3 IBS: 0.15719756724239276
Fold 4 IBS: 0.2109012649611471
Fold 5 IBS: 0.18997390770691105
[I 2024-04-15 13:33:55,503] Trial 71 finished with value: 0.19882701240036588 and parameters: {'l1_ratio': 0.27138492353441573}. Best is trial 69 with value: 0.19881109753112047.
Fold 1 IBS: 0.26096175253799625
Fold 2 IBS: 0.17524609517661438
Fold 3 IBS: 0.15734253180616814
Fold 4 IBS: 0.21092065454560094
Fold 5 IBS: 0.19000157502702483
[I 2024-04-15 13:33:55,691] Trial 72 finished with value: 0.19889452181868092 and parameters: {'l1_ratio': 0.45683381797875783}. Best is trial 69 with value: 0.19881109753112047.
Fold 1 IBS: 0.26088393875540483
Fold 2 IBS: 0.17518011218416912
Fold 3 IBS: 0.15722517359355923
Fold 4 IBS: 0.21090505371993143
Fold 5 IBS: 0.1899737087763918
[I 2024-04-15 13:33:55,903] Trial 73 finished with value: 0.1988335974058913 and parameters: {'l1_ratio': 0.31225133637658387}. Best is trial 69 with value: 0.19881109753112047.
Fold 1 IBS: 0.26088657160641404
Fold 2 IBS: 0.1751225596372161
Fold 3 IBS: 0.22888949264004346
Fold 4 IBS: 0.23704109496019252
Fold 5 IBS: 0.18991616398222438
[I 2024-04-15 13:33:56,050] Trial 74 finished with value: 0.2183711765652181 and parameters: {'l1_ratio': 0.21943719876206802}. Best is trial 69 with value: 0.19881109753112047.
Fold 1 IBS: 0.2608478509894583
Fold 2 IBS: 0.1751408675540254
Fold 3 IBS: 0.15721491586255135
Fold 4 IBS: 0.21087675190331343
Fold 5 IBS: 0.18994932963716052
[I 2024-04-15 13:33:56,253] Trial 75 finished with value: 0.19880594318930178 and parameters: {'l1_ratio': 0.2660168592917107}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2609043555418178
Fold 2 IBS: 0.17515828890109805
Fold 3 IBS: 0.15717027351991927
Fold 4 IBS: 0.21088998581011303
Fold 5 IBS: 0.19000571545154785
[I 2024-04-15 13:33:56,471] Trial 76 finished with value: 0.19882572384489922 and parameters: {'l1_ratio': 0.25667453108735133}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608247539004306
Fold 2 IBS: 0.22693522652797693
Fold 3 IBS: 0.22889178788827225
Fold 4 IBS: 0.23762133243552036

Fold 5 IBS: 0.22581807649536825
[I 2024-04-15 13:33:56,563] Trial 77 finished with value: 0.23601823544951367 and parameters: {'l1_ratio': 0.19328346899350535}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608997001884041
Fold 2 IBS: 0.1751744113251068
Fold 3 IBS: 0.15721450525553415
Fold 4 IBS: 0.21089631616353507
Fold 5 IBS: 0.18998366753711324
[I 2024-04-15 13:33:56,776] Trial 78 finished with value: 0.19883372009393868 and parameters: {'l1_ratio': 0.3160690426163704}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26179949727647756
Fold 2 IBS: 0.1753873088968012
Fold 3 IBS: 0.15775663412474292
Fold 4 IBS: 0.21094749759571413
Fold 5 IBS: 0.18997802322605103
[I 2024-04-15 13:33:56,946] Trial 79 finished with value: 0.19917379222395737 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608099364957766
Fold 2 IBS: 0.22804261450619429
Fold 3 IBS: 0.22890091367027132
Fold 4 IBS: 0.23855435273029887
Fold 5 IBS: 0.2266017031811134
[I 2024-04-15 13:33:57,040] Trial 80 finished with value: 0.23658190411673088 and parameters: {'l1_ratio': 0.15148185887414514}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26087637447626894
Fold 2 IBS: 0.17515530389399728
Fold 3 IBS: 0.15721189943552372
Fold 4 IBS: 0.21089934266865362
Fold 5 IBS: 0.18998395498268933
[I 2024-04-15 13:33:57,227] Trial 81 finished with value: 0.19882537509142656 and parameters: {'l1_ratio': 0.29093891686961554}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608991502366547
Fold 2 IBS: 0.17523789806669426
Fold 3 IBS: 0.15725786541629055
Fold 4 IBS: 0.21088469477038357
Fold 5 IBS: 0.18995281175261872
[I 2024-04-15 13:33:57,428] Trial 82 finished with value: 0.19884648404852834 and parameters: {'l1_ratio': 0.3573134761094947}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26096804765666715
Fold 2 IBS: 0.17519723026053488
Fold 3 IBS: 0.15731649321733826
Fold 4 IBS: 0.21090371057992913
Fold 5 IBS: 0.18999456687268032
[I 2024-04-15 13:33:57,609] Trial 83 finished with value: 0.19887600971742997 and parameters: {'l1_ratio': 0.3973589651721161}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26088445989376685
Fold 2 IBS: 0.1751846684521909
Fold 3 IBS: 0.15718936334005393
Fold 4 IBS: 0.2108975699165389
Fold 5 IBS: 0.18998598548595833
[I 2024-04-15 13:33:57,802] Trial 84 finished with value: 0.1988284094177018 and parameters: {'l1_ratio': 0.27395308254747874}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608826506860495
Fold 2 IBS: 0.17521094718465793
Fold 3 IBS: 0.15724698602925802
Fold 4 IBS: 0.21087698448972061
Fold 5 IBS: 0.18995874558407794
[I 2024-04-15 13:33:57,992] Trial 85 finished with value: 0.1988352627947528 and parameters: {'l1_ratio': 0.33218847491866843}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26085070034210617
Fold 2 IBS: 0.17508372718262127
Fold 3 IBS: 0.22888981647196022
Fold 4 IBS: 0.23718865365309907
Fold 5 IBS: 0.1899769960110478
[I 2024-04-15 13:33:58,131] Trial 86 finished with value: 0.2183979787321669 and parameters: {'l1_ratio': 0.21277322486397962}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26090553166210784
Fold 2 IBS: 0.17515113608032765
Fold 3 IBS: 0.15723294618266903
Fold 4 IBS: 0.21088451653140136
Fold 5 IBS: 0.18992527748291652
[I 2024-04-15 13:33:58,311] Trial 87 finished with value: 0.1988198815878845 and parameters: {'l1_ratio': 0.2604470826939767}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2609127991160271
Fold 2 IBS: 0.17520047691808222
Fold 3 IBS: 0.15726484853883757
Fold 4 IBS: 0.21088810200505625
Fold 5 IBS: 0.19001599662545107
[I 2024-04-15 13:33:58,485] Trial 88 finished with value: 0.19885644464069085 and parameters: {'l1_ratio': 0.29949875258383035}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608381555626487
Fold 2 IBS: 0.17510748841409188
Fold 3 IBS: 0.22888934981898876
Fold 4 IBS: 0.21087485891304195
Fold 5 IBS: 0.18995186759467692
[I 2024-04-15 13:33:58,640] Trial 89 finished with value: 0.21313234406068965 and parameters: {'l1_ratio': 0.22637323260302358}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26117540306912407
Fold 2 IBS: 0.17535598612208014
Fold 3 IBS: 0.15746388766817282
Fold 4 IBS: 0.21092380890691895
Fold 5 IBS: 0.18997689035203144
[I 2024-04-15 13:33:58,794] Trial 90 finished with value: 0.1989791952236655 and parameters: {'l1_ratio': 0.7135825642664739}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2609130295657997
Fold 2 IBS: 0.17515467907256624
Fold 3 IBS: 0.1571641300251278
Fold 4 IBS: 0.2108872272614049
Fold 5 IBS: 0.18993474581101213
[I 2024-04-15 13:33:58,985] Trial 91 finished with value: 0.19881076234718215 and parameters: {'l1_ratio': 0.25856289795402265}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2609113418253418
Fold 2 IBS: 0.17513269221766883
Fold 3 IBS: 0.22888970242999643
Fold 4 IBS: 0.210881689729306
Fold 5 IBS: 0.18992956261455182
[I 2024-04-15 13:33:59,146] Trial 92 finished with value: 0.21314899776337298 and parameters: {'l1_ratio': 0.24083342047966283}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608179906000031
Fold 2 IBS: 0.22696462793417174
Fold 3 IBS: 0.22889194503574664
Fold 4 IBS: 0.23764599757628097
Fold 5 IBS: 0.22583891522821112
[I 2024-04-15 13:33:59,230] Trial 93 finished with value: 0.23603189527488272 and parameters: {'l1_ratio': 0.19217460186934573}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2609114189961983
Fold 2 IBS: 0.17520103072905188
Fold 3 IBS: 0.15718758943615532
Fold 4 IBS: 0.2108885330246923
Fold 5 IBS: 0.19001457310730943
[I 2024-04-15 13:33:59,410] Trial 94 finished with value: 0.19884062905868144 and parameters: {'l1_ratio': 0.2991673567591271}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608538297545054
Fold 2 IBS: 0.17513861794115373
Fold 3 IBS: 0.1572106799627516
Fold 4 IBS: 0.2108750223198316
Fold 5 IBS: 0.18995802844856918
[I 2024-04-15 13:33:59,593] Trial 95 finished with value: 0.1988072356853623 and parameters: {'l1_ratio': 0.26728957225047867}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.24518411264862067
Fold 2 IBS: 0.22849700550109656
Fold 3 IBS: 0.22890648890876958
Fold 4 IBS: 0.23893938395434253
Fold 5 IBS: 0.22692234222055607
[I 2024-04-15 13:33:59,655] Trial 96 finished with value: 0.23368986664667712 and parameters: {'l1_ratio': 0.1343084889624756}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2609656116293956
Fold 2 IBS: 0.17528377783169818
Fold 3 IBS: 0.15729851103952905
Fold 4 IBS: 0.21089639420214557
Fold 5 IBS: 0.19000569327172676
[I 2024-04-15 13:33:59,835] Trial 97 finished with value: 0.19888999759489903 and parameters: {'l1_ratio': 0.372233123488934}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.26087171175385127
Fold 2 IBS: 0.17521489507948534
Fold 3 IBS: 0.15725466884118278
Fold 4 IBS: 0.2108800854222527
Fold 5 IBS: 0.18994772798178755
[I 2024-04-15 13:34:00,014] Trial 98 finished with value: 0.1988338178157119 and parameters: {'l1_ratio': 0.32950131288417683}. Best is trial 75 with value: 0.19880594318930178.
Fold 1 IBS: 0.2608499704860642
Fold 2 IBS: 0.22755989991767495
Fold 3 IBS: 0.2288961383413034
Fold 4 IBS: 0.23814666490262001
Fold 5 IBS: 0.2262604610342254
[I 2024-04-15 13:34:00,117] Trial 99 finished with value: 0.2363426269363776 and parameters: {'l1_ratio': 0.16971246587457917}. Best is trial 75 with value: 0.19880594318930178.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.19880594318930178], datetime_start=datetime.datetime(2024, 4, 15, 13, 33, 56, 51444), datetime_complete=datetime.datetime(2024, 4, 15, 13, 33, 56, 253330), params={'l1_ratio': 0.2660168592917107}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=75, value=None)


* Best Score for IBS:
 0.19880594318930178

In [132]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [133]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.705
train_ibs:  0.199

#### Test

In [134]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [135]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.2694535558091148)

test_cindex : 0.528

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.2660168592917107)

test_ibs:  0.308

In [136]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [137]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:34:00,281] A new study created in memory with name: no-name-f111fe4a-899d-4385-8aef-527663b79904

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6931330472103004
[I 2024-04-15 13:34:01,838] Trial 0 finished with value: 0.7048122494993283 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:34:02,880] Trial 1 finished with value: 0.7045401103615428 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:34:03,738] Trial 2 finished with value: 0.7038559215138825 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:04,013] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:04,387] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 13:34:05,825] Trial 5 finished with value: 0.7065789011065878 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:34:07,354] Trial 6 finished with value: 0.6939192369651451 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:08,030] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:34:10,555] Trial 8 finished with value: 0.5330472103004291 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:34:11,855] Trial 9 finished with value: 0.7056557357443756 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:12,011] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:34:12,563] Trial 11 finished with value: 0.7022979418058652 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.9866547731576396, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018098423978521135, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:34:14,770] Trial 12 finished with value: 0.7013323984593981 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.8392165520631284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08506650508113567, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:34:16,310] Trial 13 finished with value: 0.6893270242731889 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.4760095384782845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:34:16,775] Trial 14 finished with value: 0.7773044783671873 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1584235940276062, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:34:17,201] Trial 15 finished with value: 0.7770080066545406 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.834513235692611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1695220400209786, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:34:17,511] Trial 16 finished with value: 0.7738213229226775 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.804668454581114, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17004822192434552, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:34:17,848] Trial 17 finished with value: 0.77214163545148 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.8699768148803853, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19387458942106575, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:17,940] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.7252075252214651, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 13:34:18,339] Trial 19 finished with value: 0.7465432746830285 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.9892276103612732, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1022133684431561, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:34:18,517] Trial 20 finished with value: 0.6896452628649035 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.5018171832362744, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24858261413121135, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:34:18,813] Trial 21 finished with value: 0.7747954994518816 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 128, 'oob_score': True, 'max_samples': 0.804171251859245, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:34:19,165] Trial 22 finished with value: 0.7755485234698857 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.7798651905375668, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14609188473654175, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:19,616] Trial 23 finished with value: 0.7838056739825504 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.6915006463773689, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12906697502800496, 'warm_start': True}. Best is trial 23 with value: 0.7838056739825504.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7510729613733905
[I 2024-04-15 13:34:20,082] Trial 24 finished with value: 0.7333004851794984 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.665565318795521, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22028324508793534, 'warm_start': True}. Best is trial 23 with value: 0.7838056739825504.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:20,617] Trial 25 finished with value: 0.7890416108092421 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.8918499102545804, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12502301449842818, 'warm_start': True}. Best is trial 25 with value: 0.7890416108092421.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:34:21,129] Trial 26 finished with value: 0.7940149960169461 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.9083119442021096, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 26 with value: 0.7940149960169461.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:34:21,648] Trial 27 finished with value: 0.7977677253229423 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.9274965245988948, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07009172976674138, 'warm_start': True}. Best is trial 27 with value: 0.7977677253229423.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:34:22,203] Trial 28 finished with value: 0.7837974275708264 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9976967175247285, 'max_features': None, 'min_weight_fraction_leaf': 0.08365358326712247, 'warm_start': True}. Best is trial 27 with value: 0.7977677253229423.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:34:22,965] Trial 29 finished with value: 0.7689052524199285 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 345, 'oob_score': True, 'max_samples': 0.9233414940787997, 'max_features': None, 'min_weight_fraction_leaf': 0.05878599020799078, 'warm_start': True}. Best is trial 27 with value: 0.7977677253229423.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 13:34:24,166] Trial 30 finished with value: 0.8187091599688708 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.9090216144690085, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07553359551188188, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:34:24,813] Trial 31 finished with value: 0.8090492137339151 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 307, 'oob_score': True, 'max_samples': 0.9009241102826697, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05767674949496584, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 13:34:25,461] Trial 32 finished with value: 0.8155619897931056 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 307, 'oob_score': True, 'max_samples': 0.9444789533658244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.061863348049174115, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:34:26,118] Trial 33 finished with value: 0.8115597345863208 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.7498140550902006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.058944101870636915, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:34:26,820] Trial 34 finished with value: 0.8107481843126315 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.7487201934411643, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05921397662742622, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:34:27,625] Trial 35 finished with value: 0.7774715232187005 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7407146247417623, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 13:34:28,423] Trial 36 finished with value: 0.8133086810709184 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.7626906097546058, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:29,401] Trial 37 finished with value: 0.7773627506492027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.6803527389169053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0029686221632765145, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:34:30,063] Trial 38 finished with value: 0.7758345328327488 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.5461815105682866, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11197515656308907, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:30,794] Trial 39 finished with value: 0.7967098226635841 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03746275234525784, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:31,688] Trial 40 finished with value: 0.7838025169016922 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.6285384337372241, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0016715706905124292, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:32,423] Trial 41 finished with value: 0.7994188859694267 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.767837172322005, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04107376710762661, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 13:34:33,111] Trial 42 finished with value: 0.8075965955408677 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.7198761567997874, 'max_features': None, 'min_weight_fraction_leaf': 0.06655767953419574, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8454935622317596
[I 2024-04-15 13:34:34,044] Trial 43 finished with value: 0.7935626689220804 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.5830624244187974, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03072132927204803, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:34:34,767] Trial 44 finished with value: 0.792243879751903 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.849283225599428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:35,201] Trial 45 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.7835335824282312, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4225092978230698, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 13:34:37,418] Trial 46 finished with value: 0.7095675932149055 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.9694479552382526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07708626038126316, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:34:38,035] Trial 47 finished with value: 0.7901000143340811 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.938566277881707, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13552684969677012, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 13:34:40,201] Trial 48 finished with value: 0.702758852119058 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.8593063971491026, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018767066815307473, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:34:41,017] Trial 49 finished with value: 0.790030635415705 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.810571778428794, 'max_features': None, 'min_weight_fraction_leaf': 0.05280316176834379, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:34:41,564] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.1200736185519305, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10823226660656002, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 13:34:42,409] Trial 51 finished with value: 0.8066776611996556 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.8845583885496642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.051704705274191215, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 13:34:43,353] Trial 52 finished with value: 0.8179846363272901 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9389508399123877, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026222660443315594, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 13:34:44,233] Trial 53 finished with value: 0.8132980917343 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.9634175796095735, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016212313831113056, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:34:45,145] Trial 54 finished with value: 0.8043701178309467 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.960656376063002, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02538198771575413, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:34:45,925] Trial 55 finished with value: 0.783914853960843 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.95971543405748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004128426819979457, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 13:34:48,454] Trial 56 finished with value: 0.7085351708519758 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 384, 'oob_score': True, 'max_samples': 0.9500997490374486, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02615027370538182, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 13:34:49,312] Trial 57 finished with value: 0.7324089772745679 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.8232445639619075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32552397591019333, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 13:34:50,421] Trial 58 finished with value: 0.8050110423292084 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.8753505408569753, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08839970870738312, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:34:51,590] Trial 59 finished with value: 0.7807352821123983 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.9918040219312247, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19118259682554753, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 13:34:54,338] Trial 60 finished with value: 0.7091889537434665 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.9070990540146153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2884043121771884, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 13:34:55,780] Trial 61 finished with value: 0.814880687618372 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 319, 'oob_score': True, 'max_samples': 0.7615399939782056, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04186680436111091, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:34:56,917] Trial 62 finished with value: 0.8026386421088365 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.860154468718914, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018996988817560154, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:34:57,779] Trial 63 finished with value: 0.8130875285597183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 293, 'oob_score': True, 'max_samples': 0.650059130929082, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03985507545277717, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:34:58,628] Trial 64 finished with value: 0.812236464729931 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.648848020334941, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0370572148748974, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 13:34:59,349] Trial 65 finished with value: 0.7439994647953215 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.7085331758294136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07493747527848026, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:35:00,262] Trial 66 finished with value: 0.8113234207073792 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.5503522334237032, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014990122277374727, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 13:35:00,989] Trial 67 finished with value: 0.8109118016753551 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.9287743458652018, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09650876105157191, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 13:35:01,905] Trial 68 finished with value: 0.8097774617205067 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.7846300394640543, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04429491696707287, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:35:02,937] Trial 69 finished with value: 0.797629748112005 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.8287968234410008, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07311553142208801, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:35:03,801] Trial 70 finished with value: 0.7790433863450577 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.613470597922394, 'max_features': None, 'min_weight_fraction_leaf': 0.1220007168733092, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 13:35:04,667] Trial 71 finished with value: 0.8212219902160223 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.6600979014487112, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.034810079140300265, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:35:05,508] Trial 72 finished with value: 0.7986584296956625 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.679366759155893, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012981940650464333, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:35:06,366] Trial 73 finished with value: 0.8002915687497681 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.5818969350992149, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030324237180112363, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 13:35:07,245] Trial 74 finished with value: 0.8106833438952299 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.6605397044772018, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.044728991821657724, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:35:07,967] Trial 75 finished with value: 0.7869022845540203 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.43192925271620286, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004132732502672452, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:35:09,015] Trial 76 finished with value: 0.7961809812508033 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 380, 'oob_score': True, 'max_samples': 0.9092696799351757, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0655411250434925, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8841201716738197
[I 2024-04-15 13:35:09,656] Trial 77 finished with value: 0.8259959952982054 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.9704274765808761, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031933517179332606, 'warm_start': True}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 13:35:09,971] Trial 78 finished with value: 0.7239202782995913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.9634807471249888, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.36634172681308474, 'warm_start': True}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 13:35:10,531] Trial 79 finished with value: 0.8076877703610432 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.9796010144096535, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08340966492391791, 'warm_start': True}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:35:11,627] Trial 80 finished with value: 0.6692722328483665 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.9967289700499299, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4514075579267288, 'warm_start': False}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:35:12,361] Trial 81 finished with value: 0.8266369197964671 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.9278309282278278, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031185763946052, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:35:13,082] Trial 82 finished with value: 0.8197949957404997 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 254, 'oob_score': True, 'max_samples': 0.8845418214747346, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026579185254879713, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8841201716738197
[I 2024-04-15 13:35:13,763] Trial 83 finished with value: 0.8245757288134271 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.8884822038631196, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02817023990682517, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8841201716738197
[I 2024-04-15 13:35:14,465] Trial 84 finished with value: 0.8258179372670176 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.9342956222659774, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05206662664124263, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 13:35:15,099] Trial 85 finished with value: 0.8042543104004551 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.9343697525340412, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.052450844892942015, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8884120171673819
[I 2024-04-15 13:35:15,833] Trial 86 finished with value: 0.8292332222001028 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.9074598841382039, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06260583991007246, 'warm_start': True}. Best is trial 86 with value: 0.8292332222001028.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9184549356223176
[I 2024-04-15 13:35:16,451] Trial 87 finished with value: 0.8446990286160186 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.8948299547976223, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03150292204046534, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 13:35:17,113] Trial 88 finished with value: 0.8219978882794878 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 214, 'oob_score': True, 'max_samples': 0.8859534162261831, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07009154752888405, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 13:35:17,737] Trial 89 finished with value: 0.8076150574105638 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.88356616516019, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08891146848350209, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:35:18,381] Trial 90 finished with value: 0.760404993251153 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 245, 'oob_score': True, 'max_samples': 0.8450915216955311, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2441821280246807, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:35:19,161] Trial 91 finished with value: 0.8195457666959325 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.8945235910735918, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06727167400022452, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8841201716738197
[I 2024-04-15 13:35:19,743] Trial 92 finished with value: 0.8227181367461665 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.8656940158187053, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06051685306548257, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8841201716738197
[I 2024-04-15 13:35:20,407] Trial 93 finished with value: 0.8283099962497271 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.8607147952683254, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05002466956085034, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 13:35:20,880] Trial 94 finished with value: 0.8161518038571807 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.8039671034590891, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05511376982757581, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 13:35:21,509] Trial 95 finished with value: 0.813265459604071 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.9180299751003221, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0976022167745263, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8884120171673819
[I 2024-04-15 13:35:22,086] Trial 96 finished with value: 0.827556845244888 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 159, 'oob_score': True, 'max_samples': 0.8201484101508788, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05047968764730313, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:35:22,538] Trial 97 finished with value: 0.7789361418828648 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8658967681300396, 'max_features': None, 'min_weight_fraction_leaf': 0.1428162647896823, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:35:23,084] Trial 98 finished with value: 0.7928921095190898 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.845906981829974, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11585566276285697, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6808510638297872

[I 2024-04-15 13:35:23,869] A new study created in memory with name: no-name-ff4375f5-aeb4-475c-b143-74655fa5c8ad

Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:35:23,862] Trial 99 finished with value: 0.7098377911129411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.821888296728338, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07696848402070876, 'warm_start': False}. Best is trial 87 with value: 0.8446990286160186.


* Best trial for C-index:
 FrozenTrial(number=87, state=TrialState.COMPLETE, values=[0.8446990286160186], datetime_start=datetime.datetime(2024, 4, 15, 13, 35, 15, 840103), datetime_complete=datetime.datetime(2024, 4, 15, 13, 35, 16, 450859), params={'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.8948299547976223, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03150292204046534, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=87, value=None)


* Best Score for C-index:
 0.8446990286160186

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22247227240535786
Fold 2 IBS: 0.18232664910750715
Fold 3 IBS: 0.2420580936789368
Fold 4 IBS: 0.2087871302790621
Fold 5 IBS: 0.21380523601862628
[I 2024-04-15 13:35:25,848] Trial 0 finished with value: 0.21388987629789802 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21388987629789802.
Fold 1 IBS: 0.22190200921656902
Fold 2 IBS: 0.18520497930133592
Fold 3 IBS: 0.2096554024234873
Fold 4 IBS: 0.20450583850411352
Fold 5 IBS: 0.20942035062626901
[I 2024-04-15 13:35:26,430] Trial 1 finished with value: 0.20613771601435493 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-15 13:35:26,799] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-15 13:35:27,970] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-15 13:35:29,223] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24349089504197247
Fold 2 IBS: 0.18718721338407
Fold 3 IBS: 0.20904030011349778
Fold 4 IBS: 0.19549836093110387
Fold 5 IBS: 0.20053012489350203
[I 2024-04-15 13:35:30,814] Trial 5 finished with value: 0.20714937887282922 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2112386460322564
Fold 2 IBS: 0.19508671635593208
Fold 3 IBS: 0.2539054626067449
Fold 4 IBS: 0.20596568095253565
Fold 5 IBS: 0.217860530835901
[I 2024-04-15 13:35:32,295] Trial 6 finished with value: 0.21681140735667398 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24089525456291452
Fold 2 IBS: 0.22612078074442202
Fold 3 IBS: 0.2282442357538558
Fold 4 IBS: 0.23490470640743932
Fold 5 IBS: 0.22514225661339773
[I 2024-04-15 13:35:34,011] Trial 7 finished with value: 0.2310614468164059 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-15 13:35:37,295] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22582896185315818
Fold 2 IBS: 0.18894634804682173
Fold 3 IBS: 0.2057784489559595
Fold 4 IBS: 0.2180447704779101
Fold 5 IBS: 0.2172744627174237
[I 2024-04-15 13:35:38,175] Trial 9 finished with value: 0.21117459841025465 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-15 13:35:39,121] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.27655340997373795
Fold 2 IBS: 0.20285589585360056
Fold 3 IBS: 0.1947393615356906
Fold 4 IBS: 0.25388874005881606
Fold 5 IBS: 0.2535773052181159
[I 2024-04-15 13:35:39,273] Trial 11 finished with value: 0.23632294252799219 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23661533269825294
Fold 2 IBS: 0.1897008690599795
Fold 3 IBS: 0.2099087326943024
Fold 4 IBS: 0.19797945389979577
Fold 5 IBS: 0.202316033023455
[I 2024-04-15 13:35:41,139] Trial 12 finished with value: 0.2073040842751571 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11583591034272536}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2248425881164494
Fold 2 IBS: 0.190961258650741
Fold 3 IBS: 0.21755351923447738
Fold 4 IBS: 0.2072423012270404
Fold 5 IBS: 0.2069603718270392
[I 2024-04-15 13:35:43,955] Trial 13 finished with value: 0.20951200781114948 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 489, 'oob_score': False, 'max_samples': 0.6258340703868753, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22334594057849727
Fold 2 IBS: 0.19531155973733316
Fold 3 IBS: 0.21478959068896128
Fold 4 IBS: 0.21326266865850366
Fold 5 IBS: 0.20996090428619574
[I 2024-04-15 13:35:44,858] Trial 14 finished with value: 0.21133413278989818 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 149, 'oob_score': False, 'max_samples': 0.3884265985399165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11968759270144667}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22218471099765655
Fold 2 IBS: 0.1908222695690612
Fold 3 IBS: 0.21809938496011258
Fold 4 IBS: 0.20522426138911296
Fold 5 IBS: 0.20529160871621235
[I 2024-04-15 13:35:47,120] Trial 15 finished with value: 0.2083244471264311 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 333, 'oob_score': False, 'max_samples': 0.9873764111748721, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 1 with value: 0.20613771601435493.

Fold 1 IBS: 0.22741079396568517
Fold 2 IBS: 0.19671898923275805
Fold 3 IBS: 0.21466613517706562
Fold 4 IBS: 0.21926376344435916
Fold 5 IBS: 0.21171233186655944
[I 2024-04-15 13:35:48,313] Trial 16 finished with value: 0.21395440273728544 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.656467758901384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18189213917493566}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23758559549732755
Fold 2 IBS: 0.19145243463776812
Fold 3 IBS: 0.2137404379947349
Fold 4 IBS: 0.19571197094726786
Fold 5 IBS: 0.21474767853149498
[I 2024-04-15 13:35:48,656] Trial 17 finished with value: 0.21064762352171867 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 43, 'oob_score': False, 'max_samples': 0.8368873118701377, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06960366441289781}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23049259545720302
Fold 2 IBS: 0.20911691627017634
Fold 3 IBS: 0.2181721573366182
Fold 4 IBS: 0.21742568141810073
Fold 5 IBS: 0.2146352649005535
[I 2024-04-15 13:35:51,973] Trial 18 finished with value: 0.2179685230765304 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.21062982570611943, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.059365270422688146}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2264952801409006
Fold 2 IBS: 0.19955387088265925
Fold 3 IBS: 0.21739580733146385
Fold 4 IBS: 0.21856008991312992
Fold 5 IBS: 0.21313745994875308
[I 2024-04-15 13:35:54,755] Trial 19 finished with value: 0.21502850164338133 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.44408982315616696, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15043236342899463}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22812558527558263
Fold 2 IBS: 0.2016157145341236
Fold 3 IBS: 0.22002757230540262
Fold 4 IBS: 0.21836889218778097
Fold 5 IBS: 0.2140609143058242
[I 2024-04-15 13:35:55,852] Trial 20 finished with value: 0.21643973572174283 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 10, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.6287093569089685, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2396569085937919
Fold 2 IBS: 0.1910935837619349
Fold 3 IBS: 0.20880750569491974
Fold 4 IBS: 0.19588658540225293
Fold 5 IBS: 0.20208571260715374
[I 2024-04-15 13:35:57,752] Trial 21 finished with value: 0.20750605921201065 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.7760640896680125, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10796776799958208}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24740452329365578
Fold 2 IBS: 0.19069021977636783
Fold 3 IBS: 0.2125162975535963
Fold 4 IBS: 0.19615654983751615
Fold 5 IBS: 0.2042061405444355
[I 2024-04-15 13:35:59,771] Trial 22 finished with value: 0.2101947462011143 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.7910357296881861, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09662675583218894}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22771180153358486
Fold 2 IBS: 0.1908352856941038
Fold 3 IBS: 0.21056708435357757
Fold 4 IBS: 0.2039901093622608
Fold 5 IBS: 0.20215750442919442
[I 2024-04-15 13:36:02,046] Trial 23 finished with value: 0.2070523570745443 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.6990339812704174, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1539276858922122}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22444999885353673
Fold 2 IBS: 0.19161037291839192
Fold 3 IBS: 0.21372027568608407
Fold 4 IBS: 0.20699175781965262
Fold 5 IBS: 0.20399814810887068
[I 2024-04-15 13:36:04,033] Trial 24 finished with value: 0.2081541106773072 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.6715158604870778, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17191377003527608}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2300079810993901
Fold 2 IBS: 0.1905197898562083
Fold 3 IBS: 0.21017312235899321
Fold 4 IBS: 0.20636975804390315
Fold 5 IBS: 0.2052533781333476
[I 2024-04-15 13:36:06,730] Trial 25 finished with value: 0.20846480589836847 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.4804330704768072, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.041861849873669}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23041211905686212
Fold 2 IBS: 0.1987362490696931
Fold 3 IBS: 0.21977713526103848
Fold 4 IBS: 0.21517449955996573
Fold 5 IBS: 0.21826042042959132
[I 2024-04-15 13:36:07,823] Trial 26 finished with value: 0.21647208467543014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.5822513269079284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2332968426644862}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23415060118389855
Fold 2 IBS: 0.21272733854973816
Fold 3 IBS: 0.22645044277955098
Fold 4 IBS: 0.22259343512812918
Fold 5 IBS: 0.2152765633037375
[I 2024-04-15 13:36:10,144] Trial 27 finished with value: 0.22223967618901086 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.6977079452893333, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.31708355026774127}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23484870840624567
Fold 2 IBS: 0.18805373119166738
Fold 3 IBS: 0.21154546188079174
Fold 4 IBS: 0.19762071527137068
Fold 5 IBS: 0.20406253262826174
[I 2024-04-15 13:36:11,756] Trial 28 finished with value: 0.20722622987566744 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9030031356045858, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1514673448473745}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23098177402027859
Fold 2 IBS: 0.18326163821587102
Fold 3 IBS: 0.24298539875752923
Fold 4 IBS: 0.2087613858468209
Fold 5 IBS: 0.21044567928546803
[I 2024-04-15 13:36:14,027] Trial 29 finished with value: 0.21528717522519356 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 366, 'oob_score': False, 'max_samples': 0.7193977487980262, 'max_features': None, 'min_weight_fraction_leaf': 0.20016896711794063}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23343277722766048
Fold 2 IBS: 0.21179728899149092
Fold 3 IBS: 0.22526528502716633
Fold 4 IBS: 0.22149097258042505
Fold 5 IBS: 0.21460986909372803
[I 2024-04-15 13:36:17,378] Trial 30 finished with value: 0.22131923858409416 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22041946341162919}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23695479431722785
Fold 2 IBS: 0.19071257279151949
Fold 3 IBS: 0.21043824770270952
Fold 4 IBS: 0.19761806088243694
Fold 5 IBS: 0.20380760347832808
[I 2024-04-15 13:36:18,895] Trial 31 finished with value: 0.20790625583444436 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.9237409555651629, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14463230245566638}. Best is trial 1 with value: 0.20613771601435493.

Fold 1 IBS: 0.22871119834201115
Fold 2 IBS: 0.18629984266823443
Fold 3 IBS: 0.2136333562391605
Fold 4 IBS: 0.20508306074253652
Fold 5 IBS: 0.20460862507387245
[I 2024-04-15 13:36:21,372] Trial 32 finished with value: 0.20766721661316295 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.8321993039875358, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16244513867075333}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2450153519251981
Fold 2 IBS: 0.19177067560329883
Fold 3 IBS: 0.2050380118625506
Fold 4 IBS: 0.19783492315190962
Fold 5 IBS: 0.20502773397972165
[I 2024-04-15 13:36:22,848] Trial 33 finished with value: 0.20893733930453579 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.9881033887741655, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08859622451822674}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22749955148715942
Fold 2 IBS: 0.18624882711058469
Fold 3 IBS: 0.21078360191851478
Fold 4 IBS: 0.200331508207223
Fold 5 IBS: 0.20926660288320456
[I 2024-04-15 13:36:23,917] Trial 34 finished with value: 0.2068260183213373 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.5815698435586507, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12599071395328157}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24678040122780803
Fold 2 IBS: 0.18195759296226327
Fold 3 IBS: 0.23828026858559573
Fold 4 IBS: 0.2153550814520749
Fold 5 IBS: 0.21329119905325156
[I 2024-04-15 13:36:24,775] Trial 35 finished with value: 0.2191329086561987 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.5833988262520585, 'max_features': None, 'min_weight_fraction_leaf': 0.0342605819155805}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23083039213409773
Fold 2 IBS: 0.18085640624529303
Fold 3 IBS: 0.19206984685001427
Fold 4 IBS: 0.22614045465776608
Fold 5 IBS: 0.20714300993579865
[I 2024-04-15 13:36:24,936] Trial 36 finished with value: 0.20740802196459396 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.5229942126902646, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12653534095242983}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2675396820612739
Fold 2 IBS: 0.18492417970666833
Fold 3 IBS: 0.22653206265577877
Fold 4 IBS: 0.20478422844892483
Fold 5 IBS: 0.21138914533998968
[I 2024-04-15 13:36:25,514] Trial 37 finished with value: 0.2190338596425271 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.6110303802482602, 'max_features': None, 'min_weight_fraction_leaf': 0.08313017968513577}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23193050651882594
Fold 2 IBS: 0.20346085746399578
Fold 3 IBS: 0.21958564173291276
Fold 4 IBS: 0.2215875193534143
Fold 5 IBS: 0.21474869623317375
[I 2024-04-15 13:36:26,965] Trial 38 finished with value: 0.2182626442604645 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.5399793822518019, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20783355153995484}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22723758437947836
Fold 2 IBS: 0.19685733236334332
Fold 3 IBS: 0.2260072038662561
Fold 4 IBS: 0.20783349829441977
Fold 5 IBS: 0.21539359722558588
[I 2024-04-15 13:36:27,930] Trial 39 finished with value: 0.2146658432258167 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 81, 'oob_score': True, 'max_samples': 0.6616268224727397, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2641597430185727}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2464411620206046
Fold 2 IBS: 0.23208919673298345
Fold 3 IBS: 0.22939828491770947
Fold 4 IBS: 0.24163774673370553
Fold 5 IBS: 0.23017045101980416
[I 2024-04-15 13:36:29,053] Trial 40 finished with value: 0.23594736828496146 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.7131209218929478, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3772343263698569}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23473304858494798
Fold 2 IBS: 0.1866035871208093
Fold 3 IBS: 0.20826926079165517
Fold 4 IBS: 0.20463633969823483
Fold 5 IBS: 0.2047547926961405
[I 2024-04-15 13:36:31,172] Trial 41 finished with value: 0.20779940577835757 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.8701681705385872, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1343317776607293}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22656893321210875
Fold 2 IBS: 0.18723606830894912
Fold 3 IBS: 0.21109703496481325
Fold 4 IBS: 0.20987021696001218
Fold 5 IBS: 0.20601426227941114
[I 2024-04-15 13:36:32,753] Trial 42 finished with value: 0.2081573031450589 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.7897901557863907, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18070686065748254}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24744295325946178
Fold 2 IBS: 0.2320992006684519
Fold 3 IBS: 0.2299147319431908
Fold 4 IBS: 0.24125655639883625
Fold 5 IBS: 0.22977215463601064
[I 2024-04-15 13:36:33,421] Trial 43 finished with value: 0.23609711938119027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.36202851108062717, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.237873852425811
Fold 2 IBS: 0.1911858625927698
Fold 3 IBS: 0.21217447541650147
Fold 4 IBS: 0.19464668557010967
Fold 5 IBS: 0.20526412831793428
[I 2024-04-15 13:36:36,570] Trial 44 finished with value: 0.2082290008646252 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.9332193354742175, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10471530729487721}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2308383850787664
Fold 2 IBS: 0.1883757876211021
Fold 3 IBS: 0.21146318355642707
Fold 4 IBS: 0.20701750028297367
Fold 5 IBS: 0.20270601079373723
[I 2024-04-15 13:36:38,374] Trial 45 finished with value: 0.2080801734666013 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.7426761003495893, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05179398828063411}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23814136700249025
Fold 2 IBS: 0.19047555395027155
Fold 3 IBS: 0.21285211041644087
Fold 4 IBS: 0.19449171857639905
Fold 5 IBS: 0.20306331832172417
[I 2024-04-15 13:36:40,812] Trial 46 finished with value: 0.20780481365346515 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.6888021858587338, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019519921400110954}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23278469063178084
Fold 2 IBS: 0.18344460559174183
Fold 3 IBS: 0.21950571831113413
Fold 4 IBS: 0.24306339804016053
Fold 5 IBS: 0.21829232309628968
[I 2024-04-15 13:36:41,013] Trial 47 finished with value: 0.21941814713422142 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.5796439752373613, 'max_features': None, 'min_weight_fraction_leaf': 0.15867994777177402}. Best is trial 1 with value: 0.20613771601435493.

Fold 1 IBS: 0.2464013758053453
Fold 2 IBS: 0.23207408714903174
Fold 3 IBS: 0.22939892327646114
Fold 4 IBS: 0.2415689721009919
Fold 5 IBS: 0.23043319376810475
[I 2024-04-15 13:36:41,793] Trial 48 finished with value: 0.23597531041998696 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.6344615640154665, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24633584274807316
Fold 2 IBS: 0.23218539826865298
Fold 3 IBS: 0.22972627891694997
Fold 4 IBS: 0.2411567932158465
Fold 5 IBS: 0.2301175121753443
[I 2024-04-15 13:36:42,710] Trial 49 finished with value: 0.2359043650649734 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.2700643631363231, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12690725040328102}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22805778621159317
Fold 2 IBS: 0.185599953677471
Fold 3 IBS: 0.21897300321074908
Fold 4 IBS: 0.19433397592691898
Fold 5 IBS: 0.2065854337466597
[I 2024-04-15 13:36:42,975] Trial 50 finished with value: 0.20671003055467838 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 30, 'oob_score': False, 'max_samples': 0.8720141909177958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07495127057764972}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23243327001803338
Fold 2 IBS: 0.18941306403608543
Fold 3 IBS: 0.21918339193212566
Fold 4 IBS: 0.20045338249946848
Fold 5 IBS: 0.20335769782277796
[I 2024-04-15 13:36:43,260] Trial 51 finished with value: 0.2089681612616982 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.8823837118861377, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0676426611884569}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2361464454069328
Fold 2 IBS: 0.18250031051752705
Fold 3 IBS: 0.2090720657878296
Fold 4 IBS: 0.19679404106447074
Fold 5 IBS: 0.20349326858684608
[I 2024-04-15 13:36:43,737] Trial 52 finished with value: 0.2056012262727213 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.8227879143305075, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07825337635432089}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23885607750473734
Fold 2 IBS: 0.1848517569348757
Fold 3 IBS: 0.21163247963526902
Fold 4 IBS: 0.2001279282395039
Fold 5 IBS: 0.20182477381846523
[I 2024-04-15 13:36:44,326] Trial 53 finished with value: 0.20745860322657023 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 64, 'oob_score': False, 'max_samples': 0.8247386802784168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07686213578570306}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2417598447201395
Fold 2 IBS: 0.19379954646629008
Fold 3 IBS: 0.20059068455113124
Fold 4 IBS: 0.21343137209210217
Fold 5 IBS: 0.20739078882382453
[I 2024-04-15 13:36:44,973] Trial 54 finished with value: 0.2113944473306975 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.7523093632558471, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02761362577898832}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2435282613998248
Fold 2 IBS: 0.18461090145364523
Fold 3 IBS: 0.21130163008138786
Fold 4 IBS: 0.19773718095053663
Fold 5 IBS: 0.20528201919418199
[I 2024-04-15 13:36:45,457] Trial 55 finished with value: 0.20849199861591527 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 53, 'oob_score': False, 'max_samples': 0.8127631568998966, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10094495624247499}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23630716566501458
Fold 2 IBS: 0.19123236708831395
Fold 3 IBS: 0.20543373510057844
Fold 4 IBS: 0.20614543950307668
Fold 5 IBS: 0.2081136731187162
[I 2024-04-15 13:36:45,755] Trial 56 finished with value: 0.20944647609514 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6518007964702662, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.045191591449920396}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23645790592894317
Fold 2 IBS: 0.18766760229554244
Fold 3 IBS: 0.20971274141638638
Fold 4 IBS: 0.20693796142165954
Fold 5 IBS: 0.20571283305580854
[I 2024-04-15 13:36:46,667] Trial 57 finished with value: 0.20929780882366802 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 120, 'oob_score': False, 'max_samples': 0.6003360228940852, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11719096619167582}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23558890831528975
Fold 2 IBS: 0.18765488713793946
Fold 3 IBS: 0.20841015286377512
Fold 4 IBS: 0.20279934898314664
Fold 5 IBS: 0.20556011235640959
[I 2024-04-15 13:36:48,412] Trial 58 finished with value: 0.2080026819313121 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.9463423717095281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18529100559417558}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24810660030204534
Fold 2 IBS: 0.18659537930442788
Fold 3 IBS: 0.20638895469149965
Fold 4 IBS: 0.19672141355116166
Fold 5 IBS: 0.20692156250277413
[I 2024-04-15 13:36:49,562] Trial 59 finished with value: 0.20894678207038173 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.8547564638582521, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.082046556845009}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24853640495704013
Fold 2 IBS: 0.18885633347272196
Fold 3 IBS: 0.20365354876519
Fold 4 IBS: 0.19803748416241668
Fold 5 IBS: 0.20661458917629735
[I 2024-04-15 13:36:50,219] Trial 60 finished with value: 0.20913967210673326 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 94, 'oob_score': False, 'max_samples': 0.7660501894449964, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01168656559831241}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22877799740609422
Fold 2 IBS: 0.18217625474761148
Fold 3 IBS: 0.21499889813461354
Fold 4 IBS: 0.2022199042093769
Fold 5 IBS: 0.21203512415931286
[I 2024-04-15 13:36:50,650] Trial 61 finished with value: 0.2080416357314018 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.8882410633772397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14539711658704613}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22754590235990318
Fold 2 IBS: 0.18884153233624934
Fold 3 IBS: 0.2189820762077244
Fold 4 IBS: 0.20521480488223304
Fold 5 IBS: 0.21663257940086067
[I 2024-04-15 13:36:50,905] Trial 62 finished with value: 0.21144337903739413 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 26, 'oob_score': False, 'max_samples': 0.7986798716288218, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.061373327150469156}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23473331365511063
Fold 2 IBS: 0.18972921303376702
Fold 3 IBS: 0.21324292263684766
Fold 4 IBS: 0.1958213954118823
Fold 5 IBS: 0.20450440606793152
[I 2024-04-15 13:36:53,271] Trial 63 finished with value: 0.20760625016110784 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.9690103699749839, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16697994987339515}. Best is trial 52 with value: 0.2056012262727213.

Fold 1 IBS: 0.2263102371899488
Fold 2 IBS: 0.1935254758393429
Fold 3 IBS: 0.20737484396299696
Fold 4 IBS: 0.2086187676158567
Fold 5 IBS: 0.20696146438052143
[I 2024-04-15 13:36:54,923] Trial 64 finished with value: 0.2085581577977334 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.5041409232103772, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1346031511543957}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23692845343363148
Fold 2 IBS: 0.19041679735965694
Fold 3 IBS: 0.21008157321222845
Fold 4 IBS: 0.1987406581683996
Fold 5 IBS: 0.20283869466958301
[I 2024-04-15 13:36:56,947] Trial 65 finished with value: 0.2078012353686999 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.689407190096443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09569536169262748}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2255506657367698
Fold 2 IBS: 0.18805519263346854
Fold 3 IBS: 0.2140249543406543
Fold 4 IBS: 0.204793062748871
Fold 5 IBS: 0.2049034354586081
[I 2024-04-15 13:36:58,379] Trial 66 finished with value: 0.20746546218367432 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.906641395754475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22031559160924333}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24258554415106987
Fold 2 IBS: 0.18586608211580108
Fold 3 IBS: 0.20633005021889933
Fold 4 IBS: 0.20779200270329232
Fold 5 IBS: 0.20375949906916596
[I 2024-04-15 13:36:59,210] Trial 67 finished with value: 0.20926663565164572 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.7268429170353262, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10950641230663803}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2744717974664921
Fold 2 IBS: 0.18531476493261076
Fold 3 IBS: 0.2376281621978531
Fold 4 IBS: 0.2076758997152183
Fold 5 IBS: 0.21122359325090623
[I 2024-04-15 13:37:01,718] Trial 68 finished with value: 0.2232628435126161 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.8456686301837488, 'max_features': None, 'min_weight_fraction_leaf': 0.15110142201065135}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22989789397046154
Fold 2 IBS: 0.20557290568176295
Fold 3 IBS: 0.2205542450665648
Fold 4 IBS: 0.21801691051265681
Fold 5 IBS: 0.21304411377419208
[I 2024-04-15 13:37:03,597] Trial 69 finished with value: 0.2174172138011276 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.5570102260852274, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0010125423146907786}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23260433244255335
Fold 2 IBS: 0.2053937803587354
Fold 3 IBS: 0.21933048484950973
Fold 4 IBS: 0.21987041520976924
Fold 5 IBS: 0.21331744179953746
[I 2024-04-15 13:37:04,808] Trial 70 finished with value: 0.21810329093202102 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.47050660582184156, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1864414628763665}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24058155183437327
Fold 2 IBS: 0.18810548775721886
Fold 3 IBS: 0.20800901901815527
Fold 4 IBS: 0.20075174580328325
Fold 5 IBS: 0.20329932911538148
[I 2024-04-15 13:37:05,925] Trial 71 finished with value: 0.20814942670568243 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 211, 'oob_score': False, 'max_samples': 0.7681995329120036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11591991777378008}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2305091643085561
Fold 2 IBS: 0.19104698324307837
Fold 3 IBS: 0.21062449364741084
Fold 4 IBS: 0.20048937087490803
Fold 5 IBS: 0.20221331981575683
[I 2024-04-15 13:37:07,697] Trial 72 finished with value: 0.20697666637794204 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.707944231424585, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1352852442587333}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23856798991286943
Fold 2 IBS: 0.18966254783831424
Fold 3 IBS: 0.21288374749651073
Fold 4 IBS: 0.19550453830736692
Fold 5 IBS: 0.20119154003907394
[I 2024-04-15 13:37:09,383] Trial 73 finished with value: 0.20756207271882707 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.6783022835853422, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09454160680625662}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23346466154567588
Fold 2 IBS: 0.18915130481355927
Fold 3 IBS: 0.20898169048315382
Fold 4 IBS: 0.2061597989588016
Fold 5 IBS: 0.20265748674922124
[I 2024-04-15 13:37:10,527] Trial 74 finished with value: 0.2080829885100824 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.6355542023201384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1361826784325361}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.21840369971447826
Fold 2 IBS: 0.1838999491090235
Fold 3 IBS: 0.21836405609135384
Fold 4 IBS: 0.20249510240131743
Fold 5 IBS: 0.2081026177358157
[I 2024-04-15 13:37:10,858] Trial 75 finished with value: 0.20625308501039777 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.7227252643897649, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20055904339717942}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23049776586861626
Fold 2 IBS: 0.1968054951080838
Fold 3 IBS: 0.20983615907626868
Fold 4 IBS: 0.2213557455632088
Fold 5 IBS: 0.21198428796963106
[I 2024-04-15 13:37:12,236] Trial 76 finished with value: 0.21409589071716173 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7163522458845774, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.239658391299781}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2153379292303241
Fold 2 IBS: 0.18734937683851036
Fold 3 IBS: 0.2194856036215662
Fold 4 IBS: 0.21172307250951736
Fold 5 IBS: 0.21189997754796933
[I 2024-04-15 13:37:12,633] Trial 77 finished with value: 0.2091591919495775 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 46, 'oob_score': True, 'max_samples': 0.6648801840846614, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20053264417943462}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22080186193533002
Fold 2 IBS: 0.18679719875579373
Fold 3 IBS: 0.2135369535018638
Fold 4 IBS: 0.20857331045798186
Fold 5 IBS: 0.2079988293734741
[I 2024-04-15 13:37:13,293] Trial 78 finished with value: 0.2075416308048887 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 87, 'oob_score': False, 'max_samples': 0.6154987453242609, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17669063739201887}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2531712135550899
Fold 2 IBS: 0.23298694791088354
Fold 3 IBS: 0.22932958454282865
Fold 4 IBS: 0.2417074467970325
Fold 5 IBS: 0.23326542379819543
[I 2024-04-15 13:37:13,476] Trial 79 finished with value: 0.23809212332080598 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2593946514256877}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2141097932587844
Fold 2 IBS: 0.20953167979731777
Fold 3 IBS: 0.25602778622576694
Fold 4 IBS: 0.2273921618025962
Fold 5 IBS: 0.2321408254663515
[I 2024-04-15 13:37:13,582] Trial 80 finished with value: 0.2278404493101634 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7067242004030547, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3136324910319987}. Best is trial 52 with value: 0.2056012262727213.

Fold 1 IBS: 0.2300650150874554
Fold 2 IBS: 0.18010561006896428
Fold 3 IBS: 0.21441487116790292
Fold 4 IBS: 0.19757686931100543
Fold 5 IBS: 0.21275664692284824
[I 2024-04-15 13:37:14,024] Trial 81 finished with value: 0.20698380251163523 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.9023474857295949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16360107456547565}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23002497302639052
Fold 2 IBS: 0.18368245768130084
Fold 3 IBS: 0.20926256560956186
Fold 4 IBS: 0.20438983840996378
Fold 5 IBS: 0.21178805819403893
[I 2024-04-15 13:37:14,482] Trial 82 finished with value: 0.20782957858425122 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 66, 'oob_score': False, 'max_samples': 0.8041501696371655, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15566497227824816}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22525709023484097
Fold 2 IBS: 0.19031985367511442
Fold 3 IBS: 0.21545971292146093
Fold 4 IBS: 0.19621095051088705
Fold 5 IBS: 0.21784011145862167
[I 2024-04-15 13:37:14,826] Trial 83 finished with value: 0.20901754376018503 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.952138352048073, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16893964738099349}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22378096685445067
Fold 2 IBS: 0.1895053205284943
Fold 3 IBS: 0.20767776897298412
Fold 4 IBS: 0.20842593830082462
Fold 5 IBS: 0.20729577060869708
[I 2024-04-15 13:37:15,460] Trial 84 finished with value: 0.20733715305309017 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.7439251995058213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19442028971918945}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22314221501288856
Fold 2 IBS: 0.18950789991402148
Fold 3 IBS: 0.2158972480377118
Fold 4 IBS: 0.2085916183097106
Fold 5 IBS: 0.2124363950065684
[I 2024-04-15 13:37:15,891] Trial 85 finished with value: 0.2099150752561802 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.6452432470638817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21060208526832816}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2684729630224285
Fold 2 IBS: 0.19094079625717164
Fold 3 IBS: 0.22511728519830407
Fold 4 IBS: 0.20124427414478216
Fold 5 IBS: 0.2088391487984959
[I 2024-04-15 13:37:16,850] Trial 86 finished with value: 0.2189228934842365 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.5769304718540522, 'max_features': None, 'min_weight_fraction_leaf': 0.07346222327282463}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.21886595354416274
Fold 2 IBS: 0.18770809838968058
Fold 3 IBS: 0.21776025071920802
Fold 4 IBS: 0.2191458494090725
Fold 5 IBS: 0.21727579328961993
[I 2024-04-15 13:37:17,046] Trial 87 finished with value: 0.21215118907034874 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.7819434632545296, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1262182423341996}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24762560270294712
Fold 2 IBS: 0.18712823463764675
Fold 3 IBS: 0.2209286915679543
Fold 4 IBS: 0.20450078818049727
Fold 5 IBS: 0.19930264931480454
[I 2024-04-15 13:37:17,335] Trial 88 finished with value: 0.21189719328076997 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.8734278783104157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05289369627992575}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2293730833939139
Fold 2 IBS: 0.18230440143406296
Fold 3 IBS: 0.21107718025893016
Fold 4 IBS: 0.19919668388653236
Fold 5 IBS: 0.21032363359663525
[I 2024-04-15 13:37:17,707] Trial 89 finished with value: 0.20645499651401492 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.8205331330759632, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1418352263930421}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2306626342614295
Fold 2 IBS: 0.18277073279130304
Fold 3 IBS: 0.2106550096038014
Fold 4 IBS: 0.19789664662095205
Fold 5 IBS: 0.21281412569624256
[I 2024-04-15 13:37:18,089] Trial 90 finished with value: 0.2069598297947457 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.844174565944255, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14102554699439274}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22769112001606934
Fold 2 IBS: 0.18102675167183196
Fold 3 IBS: 0.21420312024832305
Fold 4 IBS: 0.19898358439464284
Fold 5 IBS: 0.21291519072190637
[I 2024-04-15 13:37:18,452] Trial 91 finished with value: 0.20696395341055474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.8292666432692936, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16644860786667023}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.21911251502993664
Fold 2 IBS: 0.18307233229493716
Fold 3 IBS: 0.21120632961768868
Fold 4 IBS: 0.2039789385653001
Fold 5 IBS: 0.21197518823031072
[I 2024-04-15 13:37:18,823] Trial 92 finished with value: 0.2058690607476347 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.8555425487679464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22831629554484761}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2234673384623202
Fold 2 IBS: 0.1821986392218098
Fold 3 IBS: 0.21481467224495482
Fold 4 IBS: 0.2069361756909747
Fold 5 IBS: 0.20999150887909127
[I 2024-04-15 13:37:19,192] Trial 93 finished with value: 0.20748166689983014 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.8129378318781638, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23048998631129713}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22099075591469905
Fold 2 IBS: 0.19058239584335612
Fold 3 IBS: 0.21539998805635147
Fold 4 IBS: 0.20918961907349512
Fold 5 IBS: 0.21392406089234697
[I 2024-04-15 13:37:19,632] Trial 94 finished with value: 0.21001736395604978 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 82, 'oob_score': False, 'max_samples': 0.8327213695553917, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28897270320550766}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22859558861712112
Fold 2 IBS: 0.178762191008013
Fold 3 IBS: 0.21407289298806645
Fold 4 IBS: 0.1973726421624764
Fold 5 IBS: 0.2121487830307864
[I 2024-04-15 13:37:19,996] Trial 95 finished with value: 0.20619041956129264 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.8447220475438465, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13472277274289662}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22385859901871702
Fold 2 IBS: 0.18749154864023293
Fold 3 IBS: 0.215405777089575
Fold 4 IBS: 0.19883810395439896
Fold 5 IBS: 0.21146953699788537
[I 2024-04-15 13:37:20,361] Trial 96 finished with value: 0.20741271314016183 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 58, 'oob_score': False, 'max_samples': 0.8577528441109724, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18660062214819917}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2206463816639038

Fold 2 IBS: 0.18415089303949564
Fold 3 IBS: 0.2084960116600641
Fold 4 IBS: 0.20343560492304824
Fold 5 IBS: 0.20851133716775203
[I 2024-04-15 13:37:20,984] Trial 97 finished with value: 0.20504804569085272 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.8475291147257535, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20904972733074298}. Best is trial 97 with value: 0.20504804569085272.
Fold 1 IBS: 0.22137385042757987
Fold 2 IBS: 0.18840071162084657
Fold 3 IBS: 0.20838987304883333
Fold 4 IBS: 0.20228899120347085
Fold 5 IBS: 0.21075747268896797
[I 2024-04-15 13:37:21,610] Trial 98 finished with value: 0.20624217979793974 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.9260520619562637, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2513983980188341}. Best is trial 97 with value: 0.20504804569085272.
Fold 1 IBS: 0.21992273761412498
Fold 2 IBS: 0.1886985928564911
Fold 3 IBS: 0.2096707172324783
Fold 4 IBS: 0.20387319214065205
Fold 5 IBS: 0.21008621708122602
[I 2024-04-15 13:37:22,288] Trial 99 finished with value: 0.20645029138499452 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 98, 'oob_score': True, 'max_samples': 0.9224169389480626, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2505708058914136}. Best is trial 97 with value: 0.20504804569085272.


* Best trial for IBS:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.20504804569085272], datetime_start=datetime.datetime(2024, 4, 15, 13, 37, 20, 362927), datetime_complete=datetime.datetime(2024, 4, 15, 13, 37, 20, 984581), params={'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.8475291147257535, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20904972733074298}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=97, value=None)


* Best Score for IBS:
 0.20504804569085272

In [138]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [139]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.845
train_ibs:  0.205

#### Test

In [140]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [141]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=17, max_features='log2', max_leaf_nodes=14,
                     max_samples=0.8948299547976223, min_samples_leaf=2,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.03150292204046534,
                     n_estimators=213, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.521

RandomSurvivalForest(max_depth=3, max_features='log2', max_leaf_nodes=10,
                     max_samples=0.8475291147257535, min_samples_leaf=7,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.20904972733074298,
                     n_estimators=95, oob_score=True, random_state=123)

test_ibs:  0.248

In [142]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [143]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [144]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:37:22,898] A new study created in memory with name: no-name-d1a10811-e460-401c-b2a4-d27cd06feaaa

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:37:23,352] Trial 0 finished with value: 0.7503380732219547 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:24,502] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:37:27,039] Trial 2 finished with value: 0.6800680971098857 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 13:37:27,308] Trial 3 finished with value: 0.6785996809541028 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:27,994] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:28,766] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:37:29,189] Trial 6 finished with value: 0.7513235497730262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7467811158798283
[I 2024-04-15 13:37:30,172] Trial 7 finished with value: 0.6919069260387125 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.7306201550387597
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:37:30,233] Trial 8 finished with value: 0.7102796856574409 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 13:37:32,350] Trial 9 finished with value: 0.6410217732844281 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:33,345] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7532188841201717
[I 2024-04-15 13:37:33,750] Trial 11 finished with value: 0.719951703739174 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:37:34,388] Trial 12 finished with value: 0.7665885346648663 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:37:35,062] Trial 13 finished with value: 0.7335841742499907 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:35,503] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:35,853] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.7665885346648663.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 13:37:36,439] Trial 16 finished with value: 0.7223376647099076 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:37:36,904] Trial 17 finished with value: 0.7176426303552769 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.45617529880478086
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6872340425531915
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6716738197424893
[I 2024-04-15 13:37:37,138] Trial 18 finished with value: 0.6303715412895651 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 13:37:37,317] Trial 19 finished with value: 0.736143950309 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 13:37:37,695] Trial 20 finished with value: 0.7306611602311586 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 13:37:38,176] Trial 21 finished with value: 0.7420520149240719 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:37:38,575] Trial 22 finished with value: 0.7610441882373165 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8844026166095639, 'min_weight_fraction_leaf': 0.08688290860444149}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:37:39,115] Trial 23 finished with value: 0.7585342182148019 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.882373739187446, 'min_weight_fraction_leaf': 0.012868164547398506}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:37:39,817] Trial 24 finished with value: 0.7703255353389682 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8872409155608235, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 13:37:40,222] Trial 25 finished with value: 0.7336138162365781 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 309, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9949916074323628, 'min_weight_fraction_leaf': 0.09165915851143527}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7553648068669528
[I 2024-04-15 13:37:42,634] Trial 26 finished with value: 0.6962682445689629 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8751983869140558, 'min_weight_fraction_leaf': 0.047587407578096305}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 13:37:42,881] Trial 27 finished with value: 0.7330076663260743 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 202, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 13:37:43,236] Trial 28 finished with value: 0.7445805074044459 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9451664896451075, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:37:43,649] Trial 29 finished with value: 0.7543258448777239 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7184746104211617, 'min_weight_fraction_leaf': 0.07308871236755035}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 13:37:43,924] Trial 30 finished with value: 0.7443508545078521 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.11302310596200714}. Best is trial 24 with value: 0.7703255353389682.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:37:44,410] Trial 31 finished with value: 0.7598850722510556 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9135692082875294, 'min_weight_fraction_leaf': 0.03048028383469985}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 13:37:44,940] Trial 32 finished with value: 0.7497695648179512 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9370962123126668, 'min_weight_fraction_leaf': 0.049067586957051254}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:37:45,420] Trial 33 finished with value: 0.7528989938232977 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7138561909733563, 'min_weight_fraction_leaf': 0.08163103394835805}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 13:37:45,904] Trial 34 finished with value: 0.7510292604682907 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.845516995136671, 'min_weight_fraction_leaf': 0.028265200297625945}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 13:37:46,852] Trial 35 finished with value: 0.7395599794574828 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 417, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9400074533502404, 'min_weight_fraction_leaf': 0.06271242126132281}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.759656652360515
[I 2024-04-15 13:37:48,748] Trial 36 finished with value: 0.6974698213724116 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 482, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9972156373133719, 'min_weight_fraction_leaf': 0.127039149502548}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:37:49,103] Trial 37 finished with value: 0.7512618500022212 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7981935205122315, 'min_weight_fraction_leaf': 0.09593702929582507}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 13:37:49,507] Trial 38 finished with value: 0.7480090378895263 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.02222474597769994}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 13:37:51,709] Trial 39 finished with value: 0.6593872759924035 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5170840385542366, 'min_weight_fraction_leaf': 0.16663317312622763}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 13:37:51,887] Trial 40 finished with value: 0.7169049452659841 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 146, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7431830894771643, 'min_weight_fraction_leaf': 0.05525956604312231}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:37:52,386] Trial 41 finished with value: 0.7619310412781907 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8723164546475863, 'min_weight_fraction_leaf': 0.004141659689301247}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:37:53,037] Trial 42 finished with value: 0.7776447223765721 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8355854149043529, 'min_weight_fraction_leaf': 0.031641115802858916}. Best is trial 42 with value: 0.7776447223765721.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:37:53,578] Trial 43 finished with value: 0.7791730671798607 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8248853396475693, 'min_weight_fraction_leaf': 0.022073817105411248}. Best is trial 43 with value: 0.7791730671798607.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:37:54,076] Trial 44 finished with value: 0.7508132807825151 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6729278091345884, 'min_weight_fraction_leaf': 0.020796365994372488}. Best is trial 43 with value: 0.7791730671798607.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:37:54,659] Trial 45 finished with value: 0.7799707276149772 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5998350649536632, 'min_weight_fraction_leaf': 0.004189572339664063}. Best is trial 45 with value: 0.7799707276149772.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:37:55,118] Trial 46 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 425, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.579000826136298, 'min_weight_fraction_leaf': 0.29510475784112217}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.759656652360515
[I 2024-04-15 13:37:57,400] Trial 47 finished with value: 0.7000204230450678 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6009235078772265, 'min_weight_fraction_leaf': 0.05035737763653817}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:37:58,686] Trial 48 finished with value: 0.7719957251193016 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 481, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4774852616943502, 'min_weight_fraction_leaf': 0.0030643948751397435}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:37:59,984] Trial 49 finished with value: 0.690791396045542 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4273472569795538, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 13:38:01,050] Trial 50 finished with value: 0.7382528906361088 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.49402812735141344, 'min_weight_fraction_leaf': 0.0632245786962973}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 13:38:02,130] Trial 51 finished with value: 0.7428200304404313 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 499, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.2489831732375976, 'min_weight_fraction_leaf': 0.0005722956691509512}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:38:03,185] Trial 52 finished with value: 0.7682006220325706 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 480, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45928398992040387, 'min_weight_fraction_leaf': 0.036551688685847315}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:38:04,243] Trial 53 finished with value: 0.7686961206298732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.42214192449799365, 'min_weight_fraction_leaf': 0.034015659139177284}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:38:05,184] Trial 54 finished with value: 0.7535579563481994 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 431, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.41513610987014904, 'min_weight_fraction_leaf': 0.02284427593190501}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:38:06,166] Trial 55 finished with value: 0.7054303373849022 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 452, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3513361735766896, 'min_weight_fraction_leaf': 0.06760747962074701}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:38:07,029] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5174679188452345, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:38:07,987] Trial 57 finished with value: 0.7542566628867486 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7619437489466176, 'min_weight_fraction_leaf': 0.0407505426374218}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:38:10,670] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 467, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.28101469689358977, 'min_weight_fraction_leaf': 0.4204236378509412}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:38:12,055] Trial 59 finished with value: 0.7396770084527329 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 484, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.38015716638911, 'min_weight_fraction_leaf': 0.02005389901726501}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 13:38:12,361] Trial 60 finished with value: 0.7368182011884782 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 74, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.10939920085201921}. Best is trial 45 with value: 0.7799707276149772.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:38:13,687] Trial 61 finished with value: 0.7682006220325706 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 481, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4625777004396452, 'min_weight_fraction_leaf': 0.039166639676877606}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:38:15,011] Trial 62 finished with value: 0.7729299478150901 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5364852453438473, 'min_weight_fraction_leaf': 0.03801770294767894}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:38:16,252] Trial 63 finished with value: 0.7849537439206138 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 442, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5344584161283484, 'min_weight_fraction_leaf': 0.0002732443076643165}. Best is trial 63 with value: 0.7849537439206138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 13:38:17,493] Trial 64 finished with value: 0.8222903552251639 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 444, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.546787796418659, 'min_weight_fraction_leaf': 0.011917675243562732}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:38:18,816] Trial 65 finished with value: 0.7890105041818515 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5250438016612026, 'min_weight_fraction_leaf': 0.011213412313927024}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:38:19,983] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5545678380606688, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:38:21,139] Trial 67 finished with value: 0.7875112105848775 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 366, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5214369604412972, 'min_weight_fraction_leaf': 0.013476336133043445}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 13:38:21,934] Trial 68 finished with value: 0.74877294810037 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6582110361515794, 'min_weight_fraction_leaf': 0.08398927364833789}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 13:38:22,949] Trial 69 finished with value: 0.8220407023375402 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 365, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5906341058203064, 'min_weight_fraction_leaf': 0.01345854547135509}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 13:38:23,887] Trial 70 finished with value: 0.8215041318127779 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5891348159442482, 'min_weight_fraction_leaf': 0.015516761884048515}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 13:38:24,818] Trial 71 finished with value: 0.8190883667044625 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 353, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5807169476519992, 'min_weight_fraction_leaf': 0.010585814688353384}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:38:25,758] Trial 72 finished with value: 0.8215619802517372 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 350, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5736011457847143, 'min_weight_fraction_leaf': 0.01499327802887988}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 13:38:26,797] Trial 73 finished with value: 0.8206819922024705 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5774873773238861, 'min_weight_fraction_leaf': 0.01525821862054313}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:38:27,712] Trial 74 finished with value: 0.757744710734723 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 349, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5762811196680634, 'min_weight_fraction_leaf': 0.05738463591775203}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:38:28,720] Trial 75 finished with value: 0.8341042659728318 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 366, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6897650869142653, 'min_weight_fraction_leaf': 0.01699295724662715}. Best is trial 75 with value: 0.8341042659728318.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 13:38:30,497] Trial 76 finished with value: 0.6932114115412891 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 282, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6276249804527939, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:38:31,445] Trial 77 finished with value: 0.7736179879945961 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6860106604269457, 'min_weight_fraction_leaf': 0.05402303529207179}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 13:38:32,347] Trial 78 finished with value: 0.813949181726124 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 315, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5980986566216576, 'min_weight_fraction_leaf': 0.015874867623379977}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:38:33,250] Trial 79 finished with value: 0.8148075508248365 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 319, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5974077353274219, 'min_weight_fraction_leaf': 0.016952934933519306}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:38:34,293] Trial 80 finished with value: 0.7634124402696214 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 369, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6964413979919954, 'min_weight_fraction_leaf': 0.0668445758500843}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 13:38:35,226] Trial 81 finished with value: 0.8043264560867819 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6028287214634628, 'min_weight_fraction_leaf': 0.019698090759364247}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:38:36,126] Trial 82 finished with value: 0.825520700701192 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6447745636875917, 'min_weight_fraction_leaf': 0.014088129044148126}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:38:36,996] Trial 83 finished with value: 0.7737596895505442 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6613249054381096, 'min_weight_fraction_leaf': 0.049382122632357986}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:38:37,793] Trial 84 finished with value: 0.7912265923084251 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 262, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6376718422078788, 'min_weight_fraction_leaf': 0.02767427873036585}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:38:38,630] Trial 85 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5668354615852755, 'min_weight_fraction_leaf': 0.3673468061584153}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:38:39,471] Trial 86 finished with value: 0.738227266918584 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 319, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5038018885310944, 'min_weight_fraction_leaf': 0.09739016972229436}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 13:38:40,186] Trial 87 finished with value: 0.8310225034786207 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 238, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5549694654820233, 'min_weight_fraction_leaf': 0.01192590165034482}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 13:38:41,739] Trial 88 finished with value: 0.6788431676940953 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 243, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5553686095650655, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:38:42,500] Trial 89 finished with value: 0.734022260482132 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 299, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6175752618294499, 'min_weight_fraction_leaf': 0.04505581233836201}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:38:43,067] Trial 90 finished with value: 0.7937581648472324 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 206, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6438026560737754, 'min_weight_fraction_leaf': 0.031112110300211236}. Best is trial 75 with value: 0.8341042659728318.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 13:38:44,011] Trial 91 finished with value: 0.8215114370817034 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 357, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5809298740197136, 'min_weight_fraction_leaf': 0.0093453186611939}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:38:44,976] Trial 92 finished with value: 0.7914367316399507 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 341, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5799350621984959, 'min_weight_fraction_leaf': 0.010109548479063073}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 13:38:46,109] Trial 93 finished with value: 0.8302689286307254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 378, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5462779986734955, 'min_weight_fraction_leaf': 0.011947741376939065}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:38:47,107] Trial 94 finished with value: 0.785895542293259 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 375, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5430402594252137, 'min_weight_fraction_leaf': 0.02952432304402158}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:38:48,177] Trial 95 finished with value: 0.7627277106060983 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6968183041958589, 'min_weight_fraction_leaf': 0.060125990052631834}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:38:49,060] Trial 96 finished with value: 0.6917606537229914 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 234, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4906008497769984, 'min_weight_fraction_leaf': 0.04390780435102282}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:38:50,530] Trial 97 finished with value: 0.836555836726496 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.678838159065027, 'min_weight_fraction_leaf': 0.011359003866057657}. Best is trial 97 with value: 0.836555836726496.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 13:38:52,016] Trial 98 finished with value: 0.8302025462762238 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 391, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6738963889937724, 'min_weight_fraction_leaf': 0.0008363114070352451}. Best is trial 97 with value: 0.836555836726496.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.779467680608365

[I 2024-04-15 13:38:53,447] A new study created in memory with name: no-name-09be2e39-b0bf-405e-b36c-c6533aa8d9a7

Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:38:53,437] Trial 99 finished with value: 0.7580279704255228 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 389, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7385473779596855, 'min_weight_fraction_leaf': 0.02767948623325216}. Best is trial 97 with value: 0.836555836726496.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.836555836726496], datetime_start=datetime.datetime(2024, 4, 15, 13, 38, 49, 66201), datetime_complete=datetime.datetime(2024, 4, 15, 13, 38, 50, 529041), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.678838159065027, 'min_weight_fraction_leaf': 0.011359003866057657}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=97, value=None)


* Best Score for C-index:
 0.836555836726496

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23585685825736938
Fold 2 IBS: 0.2109839412282044
Fold 3 IBS: 0.21412659740794365
Fold 4 IBS: 0.21875528396418892
Fold 5 IBS: 0.21015182465139992
[I 2024-04-15 13:38:55,767] Trial 0 finished with value: 0.21797490110182122 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-15 13:38:59,531] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.2439819669765653
Fold 2 IBS: 0.2256456519845257
Fold 3 IBS: 0.22435648382447151
Fold 4 IBS: 0.23651721203568418
Fold 5 IBS: 0.2256208789540953
[I 2024-04-15 13:39:02,409] Trial 2 finished with value: 0.23122443875506843 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24532302893581745
Fold 2 IBS: 0.22600621799098158
Fold 3 IBS: 0.22638117048276798
Fold 4 IBS: 0.23824717142575275
Fold 5 IBS: 0.22593765243453734
[I 2024-04-15 13:39:03,427] Trial 3 finished with value: 0.23237904825397143 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-15 13:39:05,687] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-15 13:39:06,894] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.23401431845594178
Fold 2 IBS: 0.2093895811788793
Fold 3 IBS: 0.21530466495540002
Fold 4 IBS: 0.22104034767557193
Fold 5 IBS: 0.2128862532028971
[I 2024-04-15 13:39:09,349] Trial 6 finished with value: 0.21852703309373803 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.2409758305274641
Fold 2 IBS: 0.22176120105738192
Fold 3 IBS: 0.21997447641870563
Fold 4 IBS: 0.23197184876210186
Fold 5 IBS: 0.22085790811033054
[I 2024-04-15 13:39:10,941] Trial 7 finished with value: 0.2271082529751968 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24197053717762343
Fold 2 IBS: 0.22568522350748885
Fold 3 IBS: 0.22831266845131742
Fold 4 IBS: 0.23836792873299817
Fold 5 IBS: 0.22580413242447955
[I 2024-04-15 13:39:11,232] Trial 8 finished with value: 0.2320280980587815 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.2455652407518667
Fold 2 IBS: 0.23128441262450836
Fold 3 IBS: 0.22851660174776597
Fold 4 IBS: 0.24004255252880102
Fold 5 IBS: 0.22917223868673675
[I 2024-04-15 13:39:14,483] Trial 9 finished with value: 0.23491620926793577 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-15 13:39:18,624] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.23989277486634217
Fold 2 IBS: 0.22039591160187819
Fold 3 IBS: 0.22144486292617946
Fold 4 IBS: 0.22950231089972453
Fold 5 IBS: 0.221411730203088
[I 2024-04-15 13:39:21,064] Trial 11 finished with value: 0.22652951809944244 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.23077854275051773
Fold 2 IBS: 0.20498021525881208
Fold 3 IBS: 0.2091231517550083
Fold 4 IBS: 0.21219961560856726
Fold 5 IBS: 0.20523261190946868
[I 2024-04-15 13:39:24,030] Trial 12 finished with value: 0.21246282745647482 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2399650355604067
Fold 2 IBS: 0.21970154426905525
Fold 3 IBS: 0.22052880969997987
Fold 4 IBS: 0.22739994581399575
Fold 5 IBS: 0.21762661776907255
[I 2024-04-15 13:39:26,969] Trial 13 finished with value: 0.225044390622502 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2395431683896394
Fold 2 IBS: 0.21991165641706717
Fold 3 IBS: 0.22159606621372913
Fold 4 IBS: 0.22912694554889002
Fold 5 IBS: 0.21830961583916977
[I 2024-04-15 13:39:29,262] Trial 14 finished with value: 0.22569749048169913 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.21246282745647482.

Fold 1 IBS: 0.239828937780681
Fold 2 IBS: 0.21927859682244577
Fold 3 IBS: 0.22111060791027468
Fold 4 IBS: 0.22856613100551462
Fold 5 IBS: 0.21733565361795007
[I 2024-04-15 13:39:31,001] Trial 15 finished with value: 0.22522398542737326 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24596769858534037
Fold 2 IBS: 0.23138029339401794
Fold 3 IBS: 0.22859763070366051
Fold 4 IBS: 0.2405233873643777
Fold 5 IBS: 0.22936993903611647
[I 2024-04-15 13:39:34,319] Trial 16 finished with value: 0.23516778981670255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2310996610925315
Fold 2 IBS: 0.21281064961959256
Fold 3 IBS: 0.21867877900720747
Fold 4 IBS: 0.21901790329240847
Fold 5 IBS: 0.21204446102199587
[I 2024-04-15 13:39:36,744] Trial 17 finished with value: 0.21873029080674716 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-15 13:39:37,857] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23976258020108482
Fold 2 IBS: 0.21799715613788434
Fold 3 IBS: 0.22035961287850053
Fold 4 IBS: 0.22741466680115968
Fold 5 IBS: 0.21711078965147532
[I 2024-04-15 13:39:40,469] Trial 19 finished with value: 0.22452896113402093 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24945993364630784
Fold 2 IBS: 0.2320560179118942
Fold 3 IBS: 0.22673116653025222
Fold 4 IBS: 0.2404686527240072
Fold 5 IBS: 0.23045901092377374
[I 2024-04-15 13:39:40,635] Trial 20 finished with value: 0.235834956347247 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2355359290627521
Fold 2 IBS: 0.2104144345624633
Fold 3 IBS: 0.21473790413974397
Fold 4 IBS: 0.2209616352932694
Fold 5 IBS: 0.2126553073905229
[I 2024-04-15 13:39:43,436] Trial 21 finished with value: 0.21886104208975032 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2334127051026625
Fold 2 IBS: 0.21168460603965406
Fold 3 IBS: 0.21509284382409244
Fold 4 IBS: 0.22023068530196063
Fold 5 IBS: 0.2131988375077777
[I 2024-04-15 13:39:45,956] Trial 22 finished with value: 0.21872393555522945 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23572210435413657
Fold 2 IBS: 0.2099016121079893
Fold 3 IBS: 0.2140533564878653
Fold 4 IBS: 0.21938633770711632
Fold 5 IBS: 0.21095805029752102
[I 2024-04-15 13:39:48,368] Trial 23 finished with value: 0.21800429219092568 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2363014019421983
Fold 2 IBS: 0.21151765242656453
Fold 3 IBS: 0.21496359766273918
Fold 4 IBS: 0.21979892605046858
Fold 5 IBS: 0.2101002042724613
[I 2024-04-15 13:39:50,768] Trial 24 finished with value: 0.21853635647088637 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24183584565606747
Fold 2 IBS: 0.22191932808356524
Fold 3 IBS: 0.21944496840875904
Fold 4 IBS: 0.2322139551642192
Fold 5 IBS: 0.2218484279847713
[I 2024-04-15 13:39:52,540] Trial 25 finished with value: 0.22745250505947645 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23945873759332073
Fold 2 IBS: 0.21815447359223267
Fold 3 IBS: 0.2203321305940219
Fold 4 IBS: 0.22652804709513938
Fold 5 IBS: 0.2171264729964799
[I 2024-04-15 13:39:55,827] Trial 26 finished with value: 0.22431997237423892 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8454924050883471, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24023940683059092
Fold 2 IBS: 0.22083547380828175
Fold 3 IBS: 0.2218275700826917
Fold 4 IBS: 0.2314840515800722
Fold 5 IBS: 0.2203402431820872
[I 2024-04-15 13:39:57,505] Trial 27 finished with value: 0.22694534909674474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23380923853384486
Fold 2 IBS: 0.2166521850791028
Fold 3 IBS: 0.22055403220785802
Fold 4 IBS: 0.22386128935143673
Fold 5 IBS: 0.21494560741650007
[I 2024-04-15 13:40:00,495] Trial 28 finished with value: 0.2219644705177485 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.10561943508937117}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24350097269026458
Fold 2 IBS: 0.22931066532348535
Fold 3 IBS: 0.2274935255592419
Fold 4 IBS: 0.236721348319726
Fold 5 IBS: 0.22667406766101417
[I 2024-04-15 13:40:03,678] Trial 29 finished with value: 0.23274011591074642 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.21246282745647482.

Fold 1 IBS: 0.23852023407558698
Fold 2 IBS: 0.22085127198360574
Fold 3 IBS: 0.22246208066369713
Fold 4 IBS: 0.22864256467493396
Fold 5 IBS: 0.21968838126903262
[I 2024-04-15 13:40:06,412] Trial 30 finished with value: 0.22603290653337127 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23299946909800737
Fold 2 IBS: 0.20723625804859605
Fold 3 IBS: 0.21221943785442013
Fold 4 IBS: 0.2177017964639846
Fold 5 IBS: 0.20854416781687213
[I 2024-04-15 13:40:08,734] Trial 31 finished with value: 0.21574022585637603 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362712139580162, 'min_weight_fraction_leaf': 0.0012002559281581464}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23329576386854547
Fold 2 IBS: 0.20864866291155204
Fold 3 IBS: 0.21077397107349774
Fold 4 IBS: 0.2160699109888221
Fold 5 IBS: 0.21065826025368684
[I 2024-04-15 13:40:11,158] Trial 32 finished with value: 0.21588931381922083 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6227992821807525, 'min_weight_fraction_leaf': 0.07179554342829253}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24306153681199408
Fold 2 IBS: 0.22512404676788447
Fold 3 IBS: 0.22331772565995167
Fold 4 IBS: 0.23524719585690623
Fold 5 IBS: 0.224780617699734
[I 2024-04-15 13:40:13,524] Trial 33 finished with value: 0.2303062245592941 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 417, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6246674823350934, 'min_weight_fraction_leaf': 0.04929766610098481}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23698248236362535
Fold 2 IBS: 0.21618699235488542
Fold 3 IBS: 0.2178869077744494
Fold 4 IBS: 0.22262991707187765
Fold 5 IBS: 0.21381894139135835
[I 2024-04-15 13:40:16,196] Trial 34 finished with value: 0.22150104819123922 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8180483921418293, 'min_weight_fraction_leaf': 0.12662220369343266}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2310199794772503
Fold 2 IBS: 0.2024023719139507
Fold 3 IBS: 0.20669880623128378
Fold 4 IBS: 0.21092184504583145
Fold 5 IBS: 0.20560444264311953
[I 2024-04-15 13:40:17,994] Trial 35 finished with value: 0.21132948906228716 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 292, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.525544897367368, 'min_weight_fraction_leaf': 0.03874252122688228}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23001935349254238
Fold 2 IBS: 0.20485403814848732
Fold 3 IBS: 0.20682929538329672
Fold 4 IBS: 0.21591978157548516
Fold 5 IBS: 0.20626930124225762
[I 2024-04-15 13:40:19,634] Trial 36 finished with value: 0.21277835396841382 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 292, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.39581174032589594, 'min_weight_fraction_leaf': 0.031238193058764258}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23154981216684778
Fold 2 IBS: 0.2064096224008439
Fold 3 IBS: 0.208465263650005
Fold 4 IBS: 0.21691466100790038
Fold 5 IBS: 0.20633283892563786
[I 2024-04-15 13:40:21,074] Trial 37 finished with value: 0.213934439630247 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 216, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3907069630963366, 'min_weight_fraction_leaf': 0.030440421568832744}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23206947465441122
Fold 2 IBS: 0.2078551531476867
Fold 3 IBS: 0.21089757368337175
Fold 4 IBS: 0.22336843190578887
Fold 5 IBS: 0.21283383989106805
[I 2024-04-15 13:40:22,305] Trial 38 finished with value: 0.21740489465646534 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 199, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40232445463607813, 'min_weight_fraction_leaf': 0.022216332318415407}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23986526356765303
Fold 2 IBS: 0.22169871700287505
Fold 3 IBS: 0.22505665482896112
Fold 4 IBS: 0.2346684878456743
Fold 5 IBS: 0.22485697735227608
[I 2024-04-15 13:40:23,354] Trial 39 finished with value: 0.22922922011948793 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.28424052756646667, 'min_weight_fraction_leaf': 0.03401048379052402}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23787018625762488
Fold 2 IBS: 0.22182147769003757
Fold 3 IBS: 0.2242994999503461
Fold 4 IBS: 0.22950528863950773
Fold 5 IBS: 0.2215174511653471
[I 2024-04-15 13:40:24,933] Trial 40 finished with value: 0.22700278074057265 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 228, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4201868988545198, 'min_weight_fraction_leaf': 0.11561130788218002}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2372966707916344
Fold 2 IBS: 0.2028847016290367
Fold 3 IBS: 0.2015470375001461
Fold 4 IBS: 0.2212712313321188
Fold 5 IBS: 0.20888581099089984
[I 2024-04-15 13:40:26,605] Trial 41 finished with value: 0.21437709044876718 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 302, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5148221916816225, 'min_weight_fraction_leaf': 0.001151469558608545}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23434538123965318
Fold 2 IBS: 0.20853594804436915
Fold 3 IBS: 0.21092606279332207
Fold 4 IBS: 0.21997450427899343
Fold 5 IBS: 0.21032487309350506
[I 2024-04-15 13:40:28,431] Trial 42 finished with value: 0.2168213538899686 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 286, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.49736600647348106, 'min_weight_fraction_leaf': 0.06070225490406626}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23464644546128038
Fold 2 IBS: 0.20586610504904418
Fold 3 IBS: 0.21108954233849955
Fold 4 IBS: 0.22369852785781755
Fold 5 IBS: 0.21317929922286188
[I 2024-04-15 13:40:29,485] Trial 43 finished with value: 0.21769598398590068 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 178, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.35047561051666104, 'min_weight_fraction_leaf': 0.02619033998019891}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24333051067575723
Fold 2 IBS: 0.22501668698749652
Fold 3 IBS: 0.2227059709800223
Fold 4 IBS: 0.23657634956076623
Fold 5 IBS: 0.22479296948207325
[I 2024-04-15 13:40:31,064] Trial 44 finished with value: 0.2304844975372231 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 285, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5356329292060192, 'min_weight_fraction_leaf': 0.048808228983234156}. Best is trial 35 with value: 0.21132948906228716.

Fold 1 IBS: 0.23535635522895523
Fold 2 IBS: 0.19710426247292917
Fold 3 IBS: 0.20557962919622366
Fold 4 IBS: 0.21419277453695665
Fold 5 IBS: 0.20885872177069337
[I 2024-04-15 13:40:32,350] Trial 45 finished with value: 0.2122183486411516 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 226, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4468362954201356, 'min_weight_fraction_leaf': 0.022410036988178828}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23697226819401304
Fold 2 IBS: 0.21729894679225342
Fold 3 IBS: 0.21924579151831378
Fold 4 IBS: 0.22736263277866023
Fold 5 IBS: 0.21648723912795567
[I 2024-04-15 13:40:33,725] Trial 46 finished with value: 0.2234733756822392 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4404091377971465, 'min_weight_fraction_leaf': 0.0879920966146258}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2461763063865299
Fold 2 IBS: 0.23210038584430207
Fold 3 IBS: 0.22962662262622974
Fold 4 IBS: 0.2411075523095139
Fold 5 IBS: 0.23017348027867315
[I 2024-04-15 13:40:34,617] Trial 47 finished with value: 0.23583686948904975 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 151, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.22405207438014219, 'min_weight_fraction_leaf': 0.15203659778952378}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24666742425905117
Fold 2 IBS: 0.23236914915160214
Fold 3 IBS: 0.22960567029225595
Fold 4 IBS: 0.24127144751807053
Fold 5 IBS: 0.23014903819747332
[I 2024-04-15 13:40:36,337] Trial 48 finished with value: 0.23601254588369064 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 177, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.36038261603340377, 'min_weight_fraction_leaf': 0.4232459400228781}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24430819200769513
Fold 2 IBS: 0.22679228560405634
Fold 3 IBS: 0.22458075787871798
Fold 4 IBS: 0.23381361065171355
Fold 5 IBS: 0.22509732827993834
[I 2024-04-15 13:40:37,195] Trial 49 finished with value: 0.23091843488442426 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 114, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.20295168361746668, 'min_weight_fraction_leaf': 0.028375312606034528}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24702382172674314
Fold 2 IBS: 0.232318745884667
Fold 3 IBS: 0.22978154274033197
Fold 4 IBS: 0.24116379679743785
Fold 5 IBS: 0.23057060543248775
[I 2024-04-15 13:40:39,159] Trial 50 finished with value: 0.23617170251633351 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 247, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.310704861435272, 'min_weight_fraction_leaf': 0.3163091534745454}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2371997639542927
Fold 2 IBS: 0.20287492980460803
Fold 3 IBS: 0.2010534314204571
Fold 4 IBS: 0.2199161264829775
Fold 5 IBS: 0.2091644231071567
[I 2024-04-15 13:40:41,809] Trial 51 finished with value: 0.21404173495389842 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 307, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5262968044798497, 'min_weight_fraction_leaf': 0.0005502265382308967}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23340285748939266
Fold 2 IBS: 0.2103004750100177
Fold 3 IBS: 0.21254949012757765
Fold 4 IBS: 0.22125709350379033
Fold 5 IBS: 0.21405910491883784
[I 2024-04-15 13:40:44,114] Trial 52 finished with value: 0.21831380420992322 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.45046128931810375, 'min_weight_fraction_leaf': 0.062433906006724466}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23951518069671124
Fold 2 IBS: 0.21511489478979384
Fold 3 IBS: 0.21427307540212315
Fold 4 IBS: 0.23114523284371163
Fold 5 IBS: 0.2177754388998862
[I 2024-04-15 13:40:45,649] Trial 53 finished with value: 0.22356476452644522 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 219, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5802842056975928, 'min_weight_fraction_leaf': 0.0228463676344103}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2294603060430549
Fold 2 IBS: 0.20648137990863727
Fold 3 IBS: 0.2073507344488135
Fold 4 IBS: 0.21201412462921795
Fold 5 IBS: 0.20518046511594823
[I 2024-04-15 13:40:47,319] Trial 54 finished with value: 0.21209740202913435 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 268, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.45786130845956585, 'min_weight_fraction_leaf': 0.04070739223145016}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23601480280360246
Fold 2 IBS: 0.21588512872171312
Fold 3 IBS: 0.21817367585432837
Fold 4 IBS: 0.22656110143576336
Fold 5 IBS: 0.2162967711713978
[I 2024-04-15 13:40:48,976] Trial 55 finished with value: 0.22258629599736102 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4641737804722843, 'min_weight_fraction_leaf': 0.08551025986155897}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23210499549350713
Fold 2 IBS: 0.19692965285403322
Fold 3 IBS: 0.2064340374063009
Fold 4 IBS: 0.20506141318697788
Fold 5 IBS: 0.1971187636853533
[I 2024-04-15 13:40:51,058] Trial 56 finished with value: 0.20752977252523447 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 341, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.37757258938870664, 'min_weight_fraction_leaf': 0.03960758211129986}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23845889782290072
Fold 2 IBS: 0.22481512830252323
Fold 3 IBS: 0.224556794519945
Fold 4 IBS: 0.23192837150634746
Fold 5 IBS: 0.22105761643448346
[I 2024-04-15 13:40:52,666] Trial 57 finished with value: 0.22816336171723997 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 269, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.27663853585083453, 'min_weight_fraction_leaf': 0.05590915506760377}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23509899171357032
Fold 2 IBS: 0.21878922018241584
Fold 3 IBS: 0.22304312110383104
Fold 4 IBS: 0.22405272437913187
Fold 5 IBS: 0.21494923878801575
[I 2024-04-15 13:40:55,177] Trial 58 finished with value: 0.22318665923339295 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5540450495358851, 'min_weight_fraction_leaf': 0.09986603842125079}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2288010200574269
Fold 2 IBS: 0.20499639396831307
Fold 3 IBS: 0.21690288880359831
Fold 4 IBS: 0.2124003661803745
Fold 5 IBS: 0.20449517441903264
[I 2024-04-15 13:40:56,710] Trial 59 finished with value: 0.21351916868574908 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3509389761390235, 'min_weight_fraction_leaf': 0.07465720864035902}. Best is trial 56 with value: 0.20752977252523447.

Fold 1 IBS: 0.24665906141024754
Fold 2 IBS: 0.23238673943832674
Fold 3 IBS: 0.22958317859156768
Fold 4 IBS: 0.24137956784118675
Fold 5 IBS: 0.23028136399594556
[I 2024-04-15 13:40:58,556] Trial 60 finished with value: 0.23605798225545485 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 323, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.43142720229784703, 'min_weight_fraction_leaf': 0.48740241401755297}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2321959013757636
Fold 2 IBS: 0.2007164455461997
Fold 3 IBS: 0.20770062793391472
Fold 4 IBS: 0.20602392627423452
Fold 5 IBS: 0.19819621614422855
[I 2024-04-15 13:40:59,691] Trial 61 finished with value: 0.20896662345486822 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 193, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.34253183106774565, 'min_weight_fraction_leaf': 0.042959104672555634}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24129092702164456
Fold 2 IBS: 0.1940864249892709
Fold 3 IBS: 0.20445239603158735
Fold 4 IBS: 0.20177530657660103
Fold 5 IBS: 0.19641445065405433
[I 2024-04-15 13:41:01,249] Trial 62 finished with value: 0.20760390105463164 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4829578594466043, 'min_weight_fraction_leaf': 0.015417748095042628}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2438600498093446
Fold 2 IBS: 0.19339888761579696
Fold 3 IBS: 0.20511027589080238
Fold 4 IBS: 0.2020267512866158
Fold 5 IBS: 0.19974957277674807
[I 2024-04-15 13:41:02,455] Trial 63 finished with value: 0.20882910747586156 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 199, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4803020994632342, 'min_weight_fraction_leaf': 0.0178205092103982}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24555187702625741
Fold 2 IBS: 0.19258549198278238
Fold 3 IBS: 0.2081841849780967
Fold 4 IBS: 0.19873785239924144
Fold 5 IBS: 0.2026167159542672
[I 2024-04-15 13:41:03,495] Trial 64 finished with value: 0.20953522446812906 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 181, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4774266418532833, 'min_weight_fraction_leaf': 0.015960985611362433}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23775380834030116
Fold 2 IBS: 0.19861672834479435
Fold 3 IBS: 0.20921122217299923
Fold 4 IBS: 0.20268236981529783
Fold 5 IBS: 0.19463272538546011
[I 2024-04-15 13:41:04,601] Trial 65 finished with value: 0.20857937081177055 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 187, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.486147787500794, 'min_weight_fraction_leaf': 0.045698123637175965}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2501009906307814
Fold 2 IBS: 0.19560469256423904
Fold 3 IBS: 0.2013531178434995
Fold 4 IBS: 0.20240548396604943
Fold 5 IBS: 0.19742923218386338
[I 2024-04-15 13:41:05,747] Trial 66 finished with value: 0.20937870343768655 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 172, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5957538083039283, 'min_weight_fraction_leaf': 0.016756492980836386}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24073623571542466
Fold 2 IBS: 0.19904536378768864
Fold 3 IBS: 0.2072772055909507
Fold 4 IBS: 0.20431096174337093
Fold 5 IBS: 0.19751429463626025
[I 2024-04-15 13:41:06,873] Trial 67 finished with value: 0.20977681229473905 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 190, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5970548145736715, 'min_weight_fraction_leaf': 0.015632853202988805}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23489637068098582
Fold 2 IBS: 0.193544326767571
Fold 3 IBS: 0.21092412883744385
Fold 4 IBS: 0.2002444197679992
Fold 5 IBS: 0.20189264522954573
[I 2024-04-15 13:41:07,682] Trial 68 finished with value: 0.20830037825670913 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 124, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5534520440577227, 'min_weight_fraction_leaf': 0.06629333378490466}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23931787579206773
Fold 2 IBS: 0.19084396852936297
Fold 3 IBS: 0.2144928305905132
Fold 4 IBS: 0.19753590970221943
Fold 5 IBS: 0.19667239381712792
[I 2024-04-15 13:41:08,217] Trial 69 finished with value: 0.20777259568625825 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 80, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6808825798677897, 'min_weight_fraction_leaf': 0.06555713548594481}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23171524768921273
Fold 2 IBS: 0.19751283454034116
Fold 3 IBS: 0.21284229688671272
Fold 4 IBS: 0.20495487374716068
Fold 5 IBS: 0.20475925584287327
[I 2024-04-15 13:41:08,866] Trial 70 finished with value: 0.21035690174126015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 81, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7031805053141511, 'min_weight_fraction_leaf': 0.12952844171116187}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24048053796318772
Fold 2 IBS: 0.1905442518290532
Fold 3 IBS: 0.21394807021334242
Fold 4 IBS: 0.1968562583018759
Fold 5 IBS: 0.20101728345045664
[I 2024-04-15 13:41:09,250] Trial 71 finished with value: 0.20856928035158315 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 51, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.676678599385812, 'min_weight_fraction_leaf': 0.06780430049274452}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2347687448942329
Fold 2 IBS: 0.19207087212945004
Fold 3 IBS: 0.2087059109834091
Fold 4 IBS: 0.1993046128273454
Fold 5 IBS: 0.20260855491451796
[I 2024-04-15 13:41:09,659] Trial 72 finished with value: 0.2074917391497911 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 57, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7134910869727897, 'min_weight_fraction_leaf': 0.0694822375534185}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23816508193559668
Fold 2 IBS: 0.19181748584543223
Fold 3 IBS: 0.21845896954436658
Fold 4 IBS: 0.1993979863461671
Fold 5 IBS: 0.1982536936258922
[I 2024-04-15 13:41:10,059] Trial 73 finished with value: 0.20921864345949098 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 51, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.0645866992350865}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23508193319089465
Fold 2 IBS: 0.20740453808064727
Fold 3 IBS: 0.2244228921767311
Fold 4 IBS: 0.2115513627397087
Fold 5 IBS: 0.20330070970220407
[I 2024-04-15 13:41:10,220] Trial 74 finished with value: 0.21635228717803717 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 10, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7365855471939977, 'min_weight_fraction_leaf': 0.11029683626238679}. Best is trial 72 with value: 0.2074917391497911.

Fold 1 IBS: 0.2355921510352545
Fold 2 IBS: 0.18988955633106214
Fold 3 IBS: 0.2175269995788695
Fold 4 IBS: 0.1993059384582704
Fold 5 IBS: 0.19950554004549564
[I 2024-04-15 13:41:10,696] Trial 75 finished with value: 0.20836403708979043 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 62, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6761462774417768, 'min_weight_fraction_leaf': 0.07610410535003291}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2331646523531711
Fold 2 IBS: 0.19585793938278617
Fold 3 IBS: 0.21617307743244904
Fold 4 IBS: 0.20830690666506493
Fold 5 IBS: 0.2045693433216475
[I 2024-04-15 13:41:11,107] Trial 76 finished with value: 0.21161438383102374 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 52, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7683896711777872, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23185803913727424
Fold 2 IBS: 0.1927053846142274
Fold 3 IBS: 0.21437990964313605
Fold 4 IBS: 0.20539476908050203
Fold 5 IBS: 0.20030669041348295
[I 2024-04-15 13:41:11,624] Trial 77 finished with value: 0.20892895857772453 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 86, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6772401875471966, 'min_weight_fraction_leaf': 0.09086495963124246}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2270528425436531
Fold 2 IBS: 0.20370693909806606
Fold 3 IBS: 0.21607794076802184
Fold 4 IBS: 0.21234078175322665
Fold 5 IBS: 0.20551197188342696
[I 2024-04-15 13:41:11,895] Trial 78 finished with value: 0.21293809520927892 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 33, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7174939715412089, 'min_weight_fraction_leaf': 0.15014407446734546}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2312106184137957
Fold 2 IBS: 0.1961557598326469
Fold 3 IBS: 0.21123889666002982
Fold 4 IBS: 0.20277393276288513
Fold 5 IBS: 0.20081089749241096
[I 2024-04-15 13:41:12,586] Trial 79 finished with value: 0.2084380210323537 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 108, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7578020159401693, 'min_weight_fraction_leaf': 0.09730158058764991}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23213572502402638
Fold 2 IBS: 0.19667369083068653
Fold 3 IBS: 0.2115226655645497
Fold 4 IBS: 0.2045619286298977
Fold 5 IBS: 0.20173177276721538
[I 2024-04-15 13:41:13,258] Trial 80 finished with value: 0.20932515656327513 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 73, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7979785314961634, 'min_weight_fraction_leaf': 0.11792446058995482}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23445318807843726
Fold 2 IBS: 0.1951572863760429
Fold 3 IBS: 0.2149660694153711
Fold 4 IBS: 0.20509036683078255
Fold 5 IBS: 0.2042614516727649
[I 2024-04-15 13:41:14,017] Trial 81 finished with value: 0.21078567247467977 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 113, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8295924251336164, 'min_weight_fraction_leaf': 0.09809524482500852}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24192987931784726
Fold 2 IBS: 0.19219909233140817
Fold 3 IBS: 0.20848213760886697
Fold 4 IBS: 0.19898144280286179
Fold 5 IBS: 0.2019881573718024
[I 2024-04-15 13:41:14,926] Trial 82 finished with value: 0.2087161418865573 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 130, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7036492405946972, 'min_weight_fraction_leaf': 0.053381019620523905}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.22986388794534468
Fold 2 IBS: 0.21179429717870366
Fold 3 IBS: 0.21642801921738683
Fold 4 IBS: 0.22351663563840726
Fold 5 IBS: 0.21359141032237122
[I 2024-04-15 13:41:15,573] Trial 83 finished with value: 0.2190388500604427 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 94, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7605047675747114, 'min_weight_fraction_leaf': 0.2113346050152473}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23494715234361263
Fold 2 IBS: 0.19543709284877217
Fold 3 IBS: 0.21414705144727122
Fold 4 IBS: 0.20223153004395855
Fold 5 IBS: 0.20029382839151266
[I 2024-04-15 13:41:16,049] Trial 84 finished with value: 0.20941133101502546 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 65, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6555570970853588, 'min_weight_fraction_leaf': 0.08005891040211782}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24640023232104058
Fold 2 IBS: 0.20948308532194032
Fold 3 IBS: 0.21812591127612121
Fold 4 IBS: 0.202827254816637
Fold 5 IBS: 0.20665107372351849
[I 2024-04-15 13:41:16,358] Trial 85 finished with value: 0.2166975114918515 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 28, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7818442849676701, 'min_weight_fraction_leaf': 0.06296555688051952}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24689816456522876
Fold 2 IBS: 0.23119434850668188
Fold 3 IBS: 0.22764888220532994
Fold 4 IBS: 0.24146149236347472
Fold 5 IBS: 0.22996493860216796
[I 2024-04-15 13:41:17,067] Trial 86 finished with value: 0.23543356524857667 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 99, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.563811671779571, 'min_weight_fraction_leaf': 0.27909147913563276}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.236011373107941
Fold 2 IBS: 0.1985884074612493
Fold 3 IBS: 0.20780546781507445
Fold 4 IBS: 0.2010388764949602
Fold 5 IBS: 0.19713896823850197
[I 2024-04-15 13:41:18,033] Trial 87 finished with value: 0.2081166186235454 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 127, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6062813764421088, 'min_weight_fraction_leaf': 0.06500929470204342}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.235645944677044
Fold 2 IBS: 0.22141885901720673
Fold 3 IBS: 0.2207856197944425
Fold 4 IBS: 0.2274282881509803
Fold 5 IBS: 0.2171444297396915
[I 2024-04-15 13:41:18,574] Trial 88 finished with value: 0.224484628275873 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 63, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6109295734326579, 'min_weight_fraction_leaf': 0.1387676132958523}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23784860552840467
Fold 2 IBS: 0.19256619074642353
Fold 3 IBS: 0.21706996017379332
Fold 4 IBS: 0.19359579678495026
Fold 5 IBS: 0.19769481439808093
[I 2024-04-15 13:41:18,923] Trial 89 finished with value: 0.20775507352633055 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 40, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6729644923369325, 'min_weight_fraction_leaf': 0.07107523629976642}. Best is trial 72 with value: 0.2074917391497911.

Fold 1 IBS: 0.2310593691941199
Fold 2 IBS: 0.19290862866485556
Fold 3 IBS: 0.2259889263099397
Fold 4 IBS: 0.20574406592712768
Fold 5 IBS: 0.2036881105655048
[I 2024-04-15 13:41:19,263] Trial 90 finished with value: 0.21187782013230955 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 33, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6403451257560147, 'min_weight_fraction_leaf': 0.1070974205302174}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2401929507969826
Fold 2 IBS: 0.19402821024539957
Fold 3 IBS: 0.20959009756624364
Fold 4 IBS: 0.19925984870201024
Fold 5 IBS: 0.20019981509015003
[I 2024-04-15 13:41:20,169] Trial 91 finished with value: 0.2086541844801572 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6946924227216443, 'min_weight_fraction_leaf': 0.0691242091082612}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.22426201251922548
Fold 2 IBS: 0.20173365162942716
Fold 3 IBS: 0.22153956363961586
Fold 4 IBS: 0.19772548496651532
Fold 5 IBS: 0.20156108716753926
[I 2024-04-15 13:41:20,405] Trial 92 finished with value: 0.20936435998446462 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 23, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.67119389738411, 'min_weight_fraction_leaf': 0.0860360074958936}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23958587311487037
Fold 2 IBS: 0.19482142117809761
Fold 3 IBS: 0.20810860401827652
Fold 4 IBS: 0.20236991734706367
Fold 5 IBS: 0.20184750385355607
[I 2024-04-15 13:41:20,851] Trial 93 finished with value: 0.20934666390237283 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 61, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7203099531168516, 'min_weight_fraction_leaf': 0.07072043377458338}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23555684453740186
Fold 2 IBS: 0.19463692638306926
Fold 3 IBS: 0.21467835573939015
Fold 4 IBS: 0.19665081190705
Fold 5 IBS: 0.19807333303702296
[I 2024-04-15 13:41:21,675] Trial 94 finished with value: 0.20791925432078684 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 112, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6600067234493434, 'min_weight_fraction_leaf': 0.051204943590137345}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24725948885611485
Fold 2 IBS: 0.19577116275491813
Fold 3 IBS: 0.205693837657292
Fold 4 IBS: 0.20167078820690593
Fold 5 IBS: 0.19954646837579296
[I 2024-04-15 13:41:22,530] Trial 95 finished with value: 0.20998834917020476 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 112, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7494081940450164, 'min_weight_fraction_leaf': 0.049579977587926705}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24563774132454982
Fold 2 IBS: 0.2308792614731597
Fold 3 IBS: 0.22856339226732242
Fold 4 IBS: 0.2408496187728765
Fold 5 IBS: 0.22919426695438144
[I 2024-04-15 13:41:23,285] Trial 96 finished with value: 0.23502485615845797 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 122, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6169317504839195, 'min_weight_fraction_leaf': 0.03573079381567339}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24489162520079863
Fold 2 IBS: 0.22508252682921956
Fold 3 IBS: 0.22585906470442285
Fold 4 IBS: 0.23761976540509713
Fold 5 IBS: 0.225309631739468
[I 2024-04-15 13:41:24,149] Trial 97 finished with value: 0.23175252277580122 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 143, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5463268102121571, 'min_weight_fraction_leaf': 0.09247910817936378}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.22901002816464855
Fold 2 IBS: 0.21300670110379213
Fold 3 IBS: 0.21846007326572212
Fold 4 IBS: 0.22159690447263233
Fold 5 IBS: 0.21511330242953064
[I 2024-04-15 13:41:24,828] Trial 98 finished with value: 0.21943740188726518 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 88, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5769172890423364, 'min_weight_fraction_leaf': 0.16576392984791938}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23670674888424822
Fold 2 IBS: 0.2052143070073981
Fold 3 IBS: 0.2105884842412907
Fold 4 IBS: 0.2176003799486971
Fold 5 IBS: 0.20502853904646207
[I 2024-04-15 13:41:26,086] Trial 99 finished with value: 0.21502769182561923 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 162, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6311261654761119, 'min_weight_fraction_leaf': 0.056550705829223946}. Best is trial 72 with value: 0.2074917391497911.


* Best trial for IBS:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.2074917391497911], datetime_start=datetime.datetime(2024, 4, 15, 13, 41, 9, 254582), datetime_complete=datetime.datetime(2024, 4, 15, 13, 41, 9, 659380), params={'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 57, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7134910869727897, 'min_weight_fraction_leaf': 0.0694822375534185}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=72, value=None)


* Best Score for IBS:
 0.2074917391497911

In [145]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [146]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.837
train_ibs:  0.207

#### Test

In [147]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [148]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=18, max_features='auto', max_leaf_nodes=17,
                   max_samples=0.678838159065027, min_samples_leaf=1,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.011359003866057657,
                   n_estimators=362, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.509

ExtraSurvivalTrees(max_depth=7, max_features=None, max_leaf_nodes=15,
                   max_samples=0.7134910869727897, min_samples_split=2,
                   min_weight_fraction_leaf=0.0694822375534185, n_estimators=57,
                   random_state=123)

IBS: 0.259

In [149]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [150]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:41:26,880] A new study created in memory with name: no-name-75a771ca-4606-4acf-9ea6-209839ffefaf

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:38,597] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:45,776] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:41:52,050] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:42:01,847] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:42:05,833] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:42:06,834] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:42:15,520] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:42:18,364] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:42:18,747] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:42:42,802] Trial 9 finished with value: 0.6970416816836329 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 13:43:23,746] Trial 10 finished with value: 0.6727533375211936 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:44:08,753] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 13:44:39,434] Trial 12 finished with value: 0.6915084901128223 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:44:53,825] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:46:33,308] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:46:51,781] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:47:03,526] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:47:26,027] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:47:59,509] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:48:00,806] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:48:12,272] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 13:48:38,491] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 13:49:03,236] Trial 22 finished with value: 0.6443581285716469 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:49:29,177] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:49:47,705] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:50:09,243] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:50:21,134] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:51:16,744] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:51:20,695] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:52:07,941] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:52:19,576] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-15 13:53:18,669] Trial 31 finished with value: 0.6101958569131466 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:54:23,983] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:55:19,099] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:56:10,078] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 13:56:44,390] Trial 35 finished with value: 0.6743933936379024 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:57:14,358] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:57:32,408] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:57:45,341] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:58:02,176] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:58:16,973] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6072961373390557
[I 2024-04-15 13:59:06,025] Trial 41 finished with value: 0.6396344950460795 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:47,631] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:00:40,985] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:00:56,206] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:02:01,198] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6802575107296137
[I 2024-04-15 14:02:08,332] Trial 46 finished with value: 0.699938783040987 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:02:18,931] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:02:19,134] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:02:25,738] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:03:02,198] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.7103004291845494
[I 2024-04-15 14:03:42,711] Trial 51 finished with value: 0.6891110661966153 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:04:01,605] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.7274678111587983
[I 2024-04-15 14:04:39,616] Trial 53 finished with value: 0.7103874182865171 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:05:20,668] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:05:28,359] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:06:04,636] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 14:06:09,307] Trial 57 finished with value: 0.6890047854219209 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:06:14,419] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:06:21,530] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:06:30,256] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:06:40,779] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 14:07:08,218] Trial 62 finished with value: 0.6974150909475259 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 14:07:28,924] Trial 63 finished with value: 0.6931669071981286 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:48,451] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.45557149928260715, 'learning_rate': 0.0340031673751867, 'dropout_rate': 0.8352402756430523, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4320841878399444, 'min_weight_fraction_leaf': 0.262263288003764, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:14,627] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.3438614405023237, 'learning_rate': 0.04403843282374086, 'dropout_rate': 0.7239851485767856, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9229393860301199, 'min_weight_fraction_leaf': 0.309698162609194, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0050503952773476865, 'validation_fraction': 0.9403459263609858, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:48,430] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.42720539699387877, 'learning_rate': 0.04104596376062255, 'dropout_rate': 0.6411641048875296, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5401195366715463, 'min_weight_fraction_leaf': 0.29863354085488475, 'max_features': 'sqrt', 'min_impurity_decrease': 0.014480191125608608, 'validation_fraction': 0.3085811036906729, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:09:07,379] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.5298851484353428, 'learning_rate': 0.027755653943344206, 'dropout_rate': 0.8089836729353025, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.26956754513635534, 'max_features': 'sqrt', 'min_impurity_decrease': 0.03775558722634611, 'validation_fraction': 0.9048601585941811, 'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:09:23,102] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.4876582694676368, 'learning_rate': 0.0657073123865678, 'dropout_rate': 0.8674995854284298, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 1.2002568362719879, 'min_weight_fraction_leaf': 0.32112921786322346, 'max_features': 1, 'min_impurity_decrease': 0.0017458997835306613, 'validation_fraction': 0.9998752778339147, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:09:39,281] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.9484129728256304, 'learning_rate': 0.06052072438720544, 'dropout_rate': 0.9166855139279758, 'n_estimators': 497, 'criterion': 'friedman_mse', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.28207507977380614, 'max_features': 'log2', 'min_impurity_decrease': 0.011832872184829375, 'validation_fraction': 0.953568420125366, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 14:10:32,273] Trial 70 finished with value: 0.6883943964411052 and parameters: {'subsample': 0.9023508276539349, 'learning_rate': 0.0700250470025932, 'dropout_rate': 0.4501645913744281, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.010068295219290181, 'min_weight_fraction_leaf': 0.41145613042238655, 'max_features': 0.1, 'min_impurity_decrease': 5.018301342173549e-05, 'validation_fraction': 0.7628778309539805, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7188841201716738
[I 2024-04-15 14:10:34,692] Trial 71 finished with value: 0.6952508762004349 and parameters: {'subsample': 0.4100186979142205, 'learning_rate': 0.04906470091498086, 'dropout_rate': 0.9728666594478519, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.23722839553187366, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0011019552130728865, 'validation_fraction': 0.9163857609630027, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:10:38,651] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.31530142016495843, 'learning_rate': 0.0512544853130206, 'dropout_rate': 0.7755480242253493, 'n_estimators': 151, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7530156413438767, 'min_weight_fraction_leaf': 0.2383940530318115, 'max_features': 'sqrt', 'min_impurity_decrease': 1.146086435542451e-05, 'validation_fraction': 0.9193282408968059, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:10:47,086] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.37329268328825294, 'learning_rate': 0.03701842361020617, 'dropout_rate': 0.4981563025706776, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.35666680166132303, 'min_weight_fraction_leaf': 0.24913433692567943, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013992830933391351, 'validation_fraction': 0.8591928424609534, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:10:48,850] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.2750560204205196, 'learning_rate': 0.04837445328457708, 'dropout_rate': 0.9582497574656967, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2638211102311142, 'min_weight_fraction_leaf': 0.38512775736188853, 'max_features': 'sqrt', 'min_impurity_decrease': 7.041464247923928e-06, 'validation_fraction': 0.9758954223995437, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:10:51,187] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.4404072237856687, 'learning_rate': 0.01994639562660709, 'dropout_rate': 0.5736138356445972, 'n_estimators': 99, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9317881303500567, 'min_weight_fraction_leaf': 0.2756234570388064, 'max_features': 'sqrt', 'min_impurity_decrease': 0.007503470003484048, 'validation_fraction': 0.9024163935083236, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:11:04,799] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.4918260327899229, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.35567267340087927, 'n_estimators': 198, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6097069779418983, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 0.023728799495950186, 'validation_fraction': 0.23951296722702176, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:11:21,194] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.42468600594731076, 'learning_rate': 0.014667395469136795, 'dropout_rate': 0.9118766474669582, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 5.674168126071088, 'min_weight_fraction_leaf': 0.2227746203792833, 'max_features': 'log2', 'min_impurity_decrease': 0.09875135917494669, 'validation_fraction': 0.9453177103288871, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 14:11:49,089] Trial 78 finished with value: 0.7114957764128979 and parameters: {'subsample': 0.5109023203910539, 'learning_rate': 0.03158550801216725, 'dropout_rate': 0.7413014948736192, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25025224628887144, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.8776959526028103, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:12:18,161] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.525173705501519, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.7358383866611962, 'n_estimators': 463, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3699011999189556, 'min_weight_fraction_leaf': 0.24753153974472775, 'max_features': 1, 'min_impurity_decrease': 1.7270049584147727e-05, 'validation_fraction': 0.7980717773125984, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:12:23,393] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.567277013704589, 'learning_rate': 0.0051737974312490425, 'dropout_rate': 0.8482250914454597, 'n_estimators': 234, 'criterion': 'squared_error', 'ccp_alpha': 1.0339954917997785, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 3.5709870090356114e-05, 'validation_fraction': 0.8784998948355119, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 14:12:43,775] Trial 81 finished with value: 0.7051288500977226 and parameters: {'subsample': 0.47503146759741444, 'learning_rate': 0.04319851444329214, 'dropout_rate': 0.7985055948276671, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.02620579447326436, 'min_weight_fraction_leaf': 0.25486217792887067, 'max_features': 'sqrt', 'min_impurity_decrease': 7.44382247583082e-05, 'validation_fraction': 0.9164360167013661, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:13:00,699] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.507685743919513, 'learning_rate': 0.04335900283106986, 'dropout_rate': 0.7955521476520806, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.29362607241963007, 'min_weight_fraction_leaf': 0.25819868071808755, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0114662083757234e-05, 'validation_fraction': 0.9013011255329684, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:13:17,528] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.5797745049666166, 'learning_rate': 0.0340824703981913, 'dropout_rate': 0.8789638175767511, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.6334696669297977, 'min_weight_fraction_leaf': 0.23189942173022937, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00011732864998245735, 'validation_fraction': 0.9231747707728767, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:13:38,389] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.4834541725153398, 'learning_rate': 0.023289638797856414, 'dropout_rate': 0.8328682293021811, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.26471956407136726, 'min_weight_fraction_leaf': 0.28189314017013245, 'max_features': 0.1, 'min_impurity_decrease': 5.731123744574336e-06, 'validation_fraction': 0.717424917124647, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:14:18,025] Trial 85 finished with value: 0.7029378184245214 and parameters: {'subsample': 0.46442416471302606, 'learning_rate': 0.03868120982137072, 'dropout_rate': 0.7555010939901714, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.21534553835140724, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002588366582089363, 'validation_fraction': 0.9754525788007801, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:14:41,024] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.4091031897854096, 'learning_rate': 0.03892699649828304, 'dropout_rate': 0.8966021251568653, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.4776199103579195, 'min_weight_fraction_leaf': 0.318990902266928, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002571816882616244, 'validation_fraction': 0.8611496501916631, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 14:16:03,262] Trial 87 finished with value: 0.700696106580423 and parameters: {'subsample': 0.46817200009967197, 'learning_rate': 0.04661767243536595, 'dropout_rate': 0.7376705742886068, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.04557647433264077, 'min_weight_fraction_leaf': 0.21448093853857778, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002513028199602771, 'validation_fraction': 0.361331630037412, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:17:41,761] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4734273359806112, 'learning_rate': 0.045317430108268164, 'dropout_rate': 0.6792015208901604, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.8373996404369569, 'min_weight_fraction_leaf': 0.2076554276967961, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00025922792722789, 'validation_fraction': 0.3782276435223031, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 9}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:18:59,844] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.5076059777658789, 'learning_rate': 0.05189362500314046, 'dropout_rate': 0.7514447580456498, 'n_estimators': 465, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5180606603106581, 'min_weight_fraction_leaf': 0.19106605392928014, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0007921505458300624, 'validation_fraction': 0.46777134963559586, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:19:55,830] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.5480227718329489, 'learning_rate': 0.04805596762658106, 'dropout_rate': 0.7066716225655056, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 1.2032615919351914, 'min_weight_fraction_leaf': 0.13639914209671022, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005203217678609466, 'validation_fraction': 0.34750901152193453, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 14:20:44,536] Trial 91 finished with value: 0.7042923968057858 and parameters: {'subsample': 0.4534948921776258, 'learning_rate': 0.03502795963916463, 'dropout_rate': 0.755627753350719, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038324466824448115, 'min_weight_fraction_leaf': 0.25345276007887213, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014354070633778947, 'validation_fraction': 0.2513534386677809, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-15 14:21:36,337] Trial 92 finished with value: 0.6654869537195273 and parameters: {'subsample': 0.45901870291397145, 'learning_rate': 0.04220683468610277, 'dropout_rate': 0.7610995478393064, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20198938667373578, 'min_weight_fraction_leaf': 0.22974950694765456, 'max_features': 'sqrt', 'min_impurity_decrease': 8.610273210310798e-05, 'validation_fraction': 0.21295376016707165, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 14:22:11,656] Trial 93 finished with value: 0.6632943660515618 and parameters: {'subsample': 0.37244305499635777, 'learning_rate': 0.03895285718662616, 'dropout_rate': 0.7875609691891403, 'n_estimators': 474, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20205334259952537, 'min_weight_fraction_leaf': 0.24888065753134778, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000148363188299076, 'validation_fraction': 0.1299685001128385, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:22:46,753] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.43627908901840756, 'learning_rate': 0.04630380294028844, 'dropout_rate': 0.7208290031417008, 'n_estimators': 414, 'criterion': 'friedman_mse', 'ccp_alpha': 0.686936086932398, 'min_weight_fraction_leaf': 0.2141369130694551, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012504880596450284, 'validation_fraction': 0.2791478692094214, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:23:36,840] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.6285859050928441, 'learning_rate': 0.029038357232304236, 'dropout_rate': 0.6568164122517353, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 0.48602027021543714, 'min_weight_fraction_leaf': 0.16911337556412148, 'max_features': 'log2', 'min_impurity_decrease': 0.0002586731710309203, 'validation_fraction': 0.17068432884242818, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:24:26,108] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.11163353775210327, 'learning_rate': 0.03624893859534497, 'dropout_rate': 0.7401851281056467, 'n_estimators': 461, 'criterion': 'friedman_mse', 'ccp_alpha': 0.031023726124332976, 'min_weight_fraction_leaf': 0.24106600300562744, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010175709743728148, 'validation_fraction': 0.4508353689784418, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:25:27,395] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.5066101762585695, 'learning_rate': 0.05098430577340745, 'dropout_rate': 0.8032993914079254, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 1.5924588674838394, 'min_weight_fraction_leaf': 0.2916743459566873, 'max_features': 'sqrt', 'min_impurity_decrease': 1.869990366510041e-05, 'validation_fraction': 0.24332889241821454, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:27:10,775] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5419886775293563, 'learning_rate': 0.032225735364336795, 'dropout_rate': 0.6104661709305399, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.26209852400972233, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006021755492414387, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-15 14:28:25,054] A new study created in memory with name: no-name-02fde0de-a0a9-4649-a025-ed95e7db64f0

Fold 5 C-index: 0.5
[I 2024-04-15 14:28:25,013] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.39063437722207883, 'learning_rate': 0.025815091055183734, 'dropout_rate': 0.8234328591249713, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.9385820631937101, 'min_weight_fraction_leaf': 0.22455882002189229, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968275718083171e-05, 'validation_fraction': 0.35073001527955794, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.


* Best trial for C-index:
 FrozenTrial(number=78, state=TrialState.COMPLETE, values=[0.7114957764128979], datetime_start=datetime.datetime(2024, 4, 15, 14, 11, 21, 202095), datetime_complete=datetime.datetime(2024, 4, 15, 14, 11, 49, 88246), params={'subsample': 0.5109023203910539, 'learning_rate': 0.03158550801216725, 'dropout_rate': 0.7413014948736192, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25025224628887144, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.8776959526028103, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=78, value=None)


* Best Score for C-index:
 0.7114957764128979

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:29:26,654] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:30:10,430] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:30:41,510] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 14:31:38,553] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:31:55,336] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:31:58,147] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:32:29,610] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:32:42,734] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:32:46,693] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24601188999971108
Fold 2 IBS: 0.23037210839917271
Fold 3 IBS: 0.22866399971848883
Fold 4 IBS: 0.24084688533435283
Fold 5 IBS: 0.22855937522449543
[I 2024-04-15 14:34:37,589] Trial 9 finished with value: 0.23489085173524415 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316615258034594
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-15 14:36:56,642] Trial 10 finished with value: 0.2356345447701623 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 14:39:20,058] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24715496002116139
Fold 2 IBS: 0.23184677797440564
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-15 14:41:32,309] Trial 12 finished with value: 0.23582736637047277 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:42:23,448] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:43:55,638] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:45:08,454] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:45:49,930] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:47:41,213] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:48:37,204] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:48:45,856] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:50:29,947] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24711009086064675
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-15 14:52:11,043] Trial 21 finished with value: 0.2358286550709061 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24631246902459264
Fold 2 IBS: 0.2301553946746369

Fold 3 IBS: 0.22860967046558744
Fold 4 IBS: 0.24066583979891498
Fold 5 IBS: 0.22847752254891643
[I 2024-04-15 14:53:56,888] Trial 22 finished with value: 0.23484417930252968 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:55:24,029] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:56:21,332] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:57:12,676] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:58:33,792] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 14:58:43,310] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 14:59:14,258] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:00:35,035] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:01:05,647] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.2469488707078328
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-15 15:02:39,229] Trial 31 finished with value: 0.23566408867478444 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.246666566986516
Fold 2 IBS: 0.23029138500538826
Fold 3 IBS: 0.2286104923116217
Fold 4 IBS: 0.2410306602915697
Fold 5 IBS: 0.22850948233448493
[I 2024-04-15 15:04:10,290] Trial 32 finished with value: 0.2350217173859161 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:05:21,891] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:06:38,825] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:06:57,128] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:09:05,199] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:09:11,268] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:10:23,407] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:12:03,499] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:13:32,414] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24691393295703395
Fold 2 IBS: 0.2308768926750243
Fold 3 IBS: 0.228693200751399
Fold 4 IBS: 0.24135578760651089
Fold 5 IBS: 0.2287912990304231
[I 2024-04-15 15:15:43,532] Trial 41 finished with value: 0.23532622260407826 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24669917045535314
Fold 2 IBS: 0.23039435703397623
Fold 3 IBS: 0.2286021142717964
Fold 4 IBS: 0.24108271788424998
Fold 5 IBS: 0.22850441164399574
[I 2024-04-15 15:18:18,927] Trial 42 finished with value: 0.23505655425787428 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:20:57,958] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:23:06,034] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24703887799052987
Fold 2 IBS: 0.23168875432685665
Fold 3 IBS: 0.22882805766925127
Fold 4 IBS: 0.241715763548256
Fold 5 IBS: 0.22920687339343254
[I 2024-04-15 15:25:02,995] Trial 45 finished with value: 0.23569566538566528 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:26:57,464] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:27:44,636] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:27:45,291] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:28:10,579] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:30:10,006] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.2462241972912113
Fold 2 IBS: 0.23077640891357248
Fold 3 IBS: 0.22882696907450273
Fold 4 IBS: 0.24135463401709267
Fold 5 IBS: 0.22888526357862624
[I 2024-04-15 15:32:14,961] Trial 51 finished with value: 0.23521349457500107 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:34:28,048] Trial 52 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24480295453274456
Fold 2 IBS: 0.22862007958956948
Fold 3 IBS: 0.22846906978601278
Fold 4 IBS: 0.23968740831242308
Fold 5 IBS: 0.22752375735775052
[I 2024-04-15 15:36:20,593] Trial 53 finished with value: 0.2338206539157001 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:38:07,488] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658996

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:39:36,984] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:41:01,224] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:42:58,647] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:45:14,906] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:46:43,994] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:47:55,440] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:49:31,543] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24574433264597934
Fold 2 IBS: 0.22927538950456844
Fold 3 IBS: 0.22873745223732048
Fold 4 IBS: 0.24073941337728164
Fold 5 IBS: 0.22810179683765522
[I 2024-04-15 15:51:30,020] Trial 62 finished with value: 0.23451967692056103 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:53:30,764] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.2466083692887466
Fold 2 IBS: 0.2306207063514776
Fold 3 IBS: 0.22847735216630757
Fold 4 IBS: 0.24115036494545394
Fold 5 IBS: 0.22887214566068675
[I 2024-04-15 15:55:50,342] Trial 64 finished with value: 0.23514578768253452 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:57:55,780] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8687566763675275, 'learning_rate': 0.009621975442769493, 'dropout_rate': 0.20090531278751475, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.21730511044745757, 'max_features': 'log2', 'min_impurity_decrease': 4.00127934674698e-06, 'validation_fraction': 0.998233299727277, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:59:47,603] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9998769156045215, 'learning_rate': 0.010488456761899951, 'dropout_rate': 0.32975112844548055, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.7134499429690735, 'min_weight_fraction_leaf': 0.19311178079767077, 'max_features': 'log2', 'min_impurity_decrease': 1.142816958470248e-06, 'validation_fraction': 0.916501041728546, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:01:21,704] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9237031040797604, 'learning_rate': 0.015997347081349804, 'dropout_rate': 0.1311947431151216, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.17471126075382626, 'max_features': 'log2', 'min_impurity_decrease': 2.9677822215329938e-06, 'validation_fraction': 0.8373361504171383, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:03:07,380] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8052124560044422, 'learning_rate': 0.027698938792055094, 'dropout_rate': 0.17163882429043748, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2902860030111922, 'min_weight_fraction_leaf': 0.2065206798225065, 'max_features': 'log2', 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:04:23,178] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.022661198063658503, 'dropout_rate': 0.29902706401252577, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 5.781491720141274, 'min_weight_fraction_leaf': 0.15344398719269492, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3987639087801584e-06, 'validation_fraction': 0.9734079114890423, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 20}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:05:21,767] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.008582797188938113, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.13005036354311128, 'max_features': 'log2', 'min_impurity_decrease': 7.713426989240967e-06, 'validation_fraction': 0.8771634368243094, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24660813053143274
Fold 2 IBS: 0.2313740896010414
Fold 3 IBS: 0.22888346736781262
Fold 4 IBS: 0.24154385958499447
Fold 5 IBS: 0.22907992714862077
[I 2024-04-15 16:06:54,629] Trial 71 finished with value: 0.23549789484678038 and parameters: {'subsample': 0.929404609689833, 'learning_rate': 0.004424988061063654, 'dropout_rate': 0.23482693737269283, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 'auto', 'min_impurity_decrease': 2.8309589446706505e-07, 'validation_fraction': 0.9695063743987746, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24443957359768934
Fold 2 IBS: 0.22898066177897697
Fold 3 IBS: 0.2286359719656182
Fold 4 IBS: 0.24035046542118138
Fold 5 IBS: 0.2281079279567809
[I 2024-04-15 16:08:48,050] Trial 72 finished with value: 0.23410292014404935 and parameters: {'subsample': 0.9711381132608441, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.16033065274696134, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.28323130225405224, 'max_features': 'auto', 'min_impurity_decrease': 4.6121007580567444e-07, 'validation_fraction': 0.9257122264827732, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:09:02,535] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9610645917359522, 'learning_rate': 0.014025237603958317, 'dropout_rate': 0.16734553890018478, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.2729437922989923, 'max_features': 'auto', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9151475421106045, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:11:07,783] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8982215127429586, 'learning_rate': 0.011469834124160947, 'dropout_rate': 0.1993916634953806, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.25576647956503945, 'max_features': 'auto', 'min_impurity_decrease': 7.393622885050152e-07, 'validation_fraction': 0.8125896097974837, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:12:55,063] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8548930681972974, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.25603892151293595, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 1.194698393798027, 'min_weight_fraction_leaf': 0.227857291707919, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.9391263043864969, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:14:23,186] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9721277657554889, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.12783725032075846, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.8995225231338432, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:16:04,441] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9372636724132823, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.2214138929394412, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5872217111247551, 'min_weight_fraction_leaf': 0.2869095730072229, 'max_features': 1, 'min_impurity_decrease': 1.637559261311236e-05, 'validation_fraction': 0.8634632458479912, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:18:09,209] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.1032133459374581, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.3013998603131079, 'min_weight_fraction_leaf': 0.32139197698764493, 'max_features': 'auto', 'min_impurity_decrease': 5.258405165208321e-06, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:19:16,423] Trial 79 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9734119542324268, 'learning_rate': 0.00746613709211405, 'dropout_rate': 0.4920375503223646, 'n_estimators': 460, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8367973848765441, 'min_weight_fraction_leaf': 0.2996410468063834, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.93241471973226, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-15 16:20:05,663] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.880944209495621, 'learning_rate': 0.01757839546882116, 'dropout_rate': 0.1506586822025462, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.2351229170019059, 'max_features': 'auto', 'min_impurity_decrease': 2.0904779043950468e-07, 'validation_fraction': 0.985038184908284, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24676102336178163
Fold 2 IBS: 0.23092626118770207
Fold 3 IBS: 0.22884445831372108
Fold 4 IBS: 0.24139059004884203
Fold 5 IBS: 0.22894502692454705
[I 2024-04-15 16:22:08,000] Trial 81 finished with value: 0.23537347196731875 and parameters: {'subsample': 0.9953153224638304, 'learning_rate': 0.00415560855116564, 'dropout_rate': 0.1483184577320775, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.02521700237735763, 'min_weight_fraction_leaf': 0.25226618405818907, 'max_features': 'auto', 'min_impurity_decrease': 4.4684913792581215e-07, 'validation_fraction': 0.9678293267367657, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24673460160879498
Fold 2 IBS: 0.2312605158627123
Fold 3 IBS: 0.22877711474094156
Fold 4 IBS: 0.24147939872518737
Fold 5 IBS: 0.2289894752898651
[I 2024-04-15 16:23:52,675] Trial 82 finished with value: 0.23544822124550024 and parameters: {'subsample': 0.9139425050983833, 'learning_rate': 0.003095076319203989, 'dropout_rate': 0.18592812333507946, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.01766512408236868, 'min_weight_fraction_leaf': 0.27798560564966124, 'max_features': 'auto', 'min_impurity_decrease': 2.5718979151862506e-07, 'validation_fraction': 0.9466831295624905, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:25:36,332] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.008698584299413689, 'dropout_rate': 0.2159451606802952, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.43227235536812275, 'min_weight_fraction_leaf': 0.30582130984370137, 'max_features': 'auto', 'min_impurity_decrease': 1.4239613599957663e-07, 'validation_fraction': 0.8917283975361172, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:27:48,836] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9427477095506464, 'learning_rate': 0.013253369992371197, 'dropout_rate': 0.28698354158028666, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.2626782112744739, 'min_weight_fraction_leaf': 0.37366502204692825, 'max_features': 'auto', 'min_impurity_decrease': 9.351118010000074e-07, 'validation_fraction': 0.9794585372583974, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:29:48,849] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.975912726079302, 'learning_rate': 0.007475044296417039, 'dropout_rate': 0.15830961459250859, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.9666121832540018, 'min_weight_fraction_leaf': 0.21662805225917264, 'max_features': 'auto', 'min_impurity_decrease': 1.605110937110208e-07, 'validation_fraction': 0.9998997107949049, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:31:37,338] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.998032487033103, 'learning_rate': 0.01532810679048379, 'dropout_rate': 0.23799870869674608, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 1.4471152192323817, 'min_weight_fraction_leaf': 0.34273533762708086, 'max_features': 'sqrt', 'min_impurity_decrease': 2.348014993384585e-06, 'validation_fraction': 0.9194096150774934, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:33:00,717] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9164505822984168, 'learning_rate': 0.010518689458761585, 'dropout_rate': 0.18127430624736812, 'n_estimators': 386, 'criterion': 'squared_error', 'ccp_alpha': 0.6191599526075152, 'min_weight_fraction_leaf': 0.19734229255387364, 'max_features': 'auto', 'min_impurity_decrease': 5.635415445839132e-07, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:34:24,770] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5839343488674055, 'learning_rate': 0.005616464421601462, 'dropout_rate': 0.35953503133089737, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.3179664432907911, 'min_weight_fraction_leaf': 0.28749157637391265, 'max_features': 'auto', 'min_impurity_decrease': 3.335913971167387e-07, 'validation_fraction': 0.9542099213957375, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24665149166978298
Fold 2 IBS: 0.23100341911248753
Fold 3 IBS: 0.22874931175992053
Fold 4 IBS: 0.241449076384833
Fold 5 IBS: 0.22889139804833578
[I 2024-04-15 16:36:40,782] Trial 89 finished with value: 0.23534893939507198 and parameters: {'subsample': 0.9747597567605316, 'learning_rate': 0.0023221821235695954, 'dropout_rate': 0.12129931807719876, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.0187843407424986, 'min_weight_fraction_leaf': 0.27088299579805813, 'max_features': None, 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.8471649366493529, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:37:08,192] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8177896619586076, 'learning_rate': 0.025220139306170144, 'dropout_rate': 0.8458602043820649, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.5942787933242142, 'min_weight_fraction_leaf': 0.2526148431947255, 'max_features': 'auto', 'min_impurity_decrease': 0.00038999127447584, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898151309365794
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:38:46,630] Trial 91 finished with value: 0.2359277725171069 and parameters: {'subsample': 0.9509971840289189, 'learning_rate': 0.006250411110020785, 'dropout_rate': 0.2673714840258141, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.15431692617854653, 'min_weight_fraction_leaf': 0.24422274988904982, 'max_features': 'auto', 'min_impurity_decrease': 1.9176785824147386e-06, 'validation_fraction': 0.9656926905530724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:39:21,734] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.010420830230366905, 'dropout_rate': 0.2515504536642298, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.9241378948044482, 'min_weight_fraction_leaf': 0.23688053465240513, 'max_features': 'auto', 'min_impurity_decrease': 1.29569417753367e-06, 'validation_fraction': 0.9347724982483091, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:41:09,259] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9579265056005781, 'learning_rate': 0.005644515103436926, 'dropout_rate': 0.20759879422315985, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.21922288268105994, 'max_features': 'auto', 'min_impurity_decrease': 2.659018541949647e-06, 'validation_fraction': 0.9030263302405803, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:43:08,669] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8907857729292054, 'learning_rate': 0.01175213801479497, 'dropout_rate': 0.16486788507480765, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.2574700533601738, 'min_weight_fraction_leaf': 0.18108974600339167, 'max_features': 'auto', 'min_impurity_decrease': 2.379032042731447e-07, 'validation_fraction': 0.8736447132173984, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:44:30,247] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9455952167309377, 'learning_rate': 0.0011500826880246348, 'dropout_rate': 0.3201948574529592, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 1.2548600964987282, 'min_weight_fraction_leaf': 0.26353524052393096, 'max_features': 'log2', 'min_impurity_decrease': 8.22276697752205e-07, 'validation_fraction': 0.5342538893491903, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:45:53,312] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9798648277744092, 'learning_rate': 0.020033817173644677, 'dropout_rate': 0.27495368719691143, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7011862464885574, 'min_weight_fraction_leaf': 0.3195542671542451, 'max_features': 'auto', 'min_impurity_decrease': 5.186503543953528e-06, 'validation_fraction': 0.6783354896202222, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:47:28,499] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9344119758186928, 'learning_rate': 0.01702180833811468, 'dropout_rate': 0.22429524454783162, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.16853016350793706, 'min_weight_fraction_leaf': 0.22792544673999854, 'max_features': 1, 'min_impurity_decrease': 5.480220886635845e-07, 'validation_fraction': 0.9725840318690578, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:48:43,188] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9075182186822651, 'learning_rate': 0.013589188110358917, 'dropout_rate': 0.1959593061485241, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 0.987310061750523, 'min_weight_fraction_leaf': 0.20559490580314585, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.2951928169891771, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24701754842447565

Fold 2 IBS: 0.23172776185253358
Fold 3 IBS: 0.22878554072857857
Fold 4 IBS: 0.2416676429021851
Fold 5 IBS: 0.2290838777915168
[I 2024-04-15 16:50:38,203] Trial 99 finished with value: 0.23565647433985792 and parameters: {'subsample': 0.24286963781937687, 'learning_rate': 0.008804936390818944, 'dropout_rate': 0.14353784252843382, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.004530258324353442, 'min_weight_fraction_leaf': 0.29607175965989646, 'max_features': 0.1, 'min_impurity_decrease': 1.9888370412270107e-06, 'validation_fraction': 0.9539243209909428, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.2338206539157001], datetime_start=datetime.datetime(2024, 4, 15, 15, 34, 28, 59632), datetime_complete=datetime.datetime(2024, 4, 15, 15, 36, 20, 582002), params={'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=53, value=None)


* Best Score for IBS:
 0.2338206539157001

In [151]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [152]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.711
train_ibs:  0.234

#### Test

In [153]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [154]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.02313127962403605,
                                 criterion='squared_error',
                                 dropout_rate=0.7413014948736192,
                                 learning_rate=0.03158550801216725,
                                 max_features='sqrt', max_leaf_nodes=20,
                                 min_impurity_decrease=1.9076132907505136e-05,
                                 min_samples_leaf=11, min_samples_split=18,
                                 min_weight_fraction_leaf=0.25025224628887144,
                                 n_estimators=449, random_state=123,
                                 subsample=0.5109023203910539,
                                 validation_fraction=0.8776959526028103)

C-index score: 0.517

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009625013743012712,
                                 criterion='squared_error',
                                 dropout_rate=0.1897783294507234,
                                 learning_rate=0.015420772490455037,
                                 max_features='auto', max_leaf_nodes=14,
                                 min_impurity_decrease=5.869825897765074e-07,
                                 min_samples_leaf=13, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29880213170319914,
                                 n_estimators=430, random_state=123,
                                 subsample=0.9101431135071837,
                                 validation_fraction=0.9964423942006735)

IBS: 0.229

In [155]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [156]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [157]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 16:51:03,020] A new study created in memory with name: no-name-c16cb83d-ab68-4766-a594-ec37963197b2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.5107296137339056
[I 2024-04-15 16:51:04,418] Trial 0 finished with value: 0.5698891894151084 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5698891894151084.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.4978540772532189
[I 2024-04-15 16:51:15,538] Trial 1 finished with value: 0.5665388883205213 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.5698891894151084.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.4866920152091255
Fold 5 C-index: 0.5793991416309013
[I 2024-04-15 16:51:17,655] Trial 2 finished with value: 0.5929857717951144 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.5929857717951144.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.5793991416309013
[I 2024-04-15 16:51:20,572] Trial 3 finished with value: 0.597084651863417 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.597084651863417.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5095057034220533
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:51:24,918] Trial 4 finished with value: 0.6197129922130152 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6197129922130152.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.5107296137339056
[I 2024-04-15 16:51:30,396] Trial 5 finished with value: 0.5724060244292303 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6197129922130152.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.5107296137339056
[I 2024-04-15 16:51:32,995] Trial 6 finished with value: 0.5699039269397936 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6197129922130152.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.4828897338403042
Fold 5 C-index: 0.5793991416309013
[I 2024-04-15 16:51:33,812] Trial 7 finished with value: 0.5989363371777559 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6197129922130152.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.575107296137339
[I 2024-04-15 16:51:37,409] Trial 8 finished with value: 0.5969767005317418 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6197129922130152.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5095057034220533
Fold 5 C-index: 0.5836909871244635
[I 2024-04-15 16:51:46,499] Trial 9 finished with value: 0.5984611296171956 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6197129922130152.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:51:52,296] Trial 10 finished with value: 0.6284547551301432 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6284547551301432.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:51:59,115] Trial 11 finished with value: 0.6374285731855723 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6374285731855723.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:52:05,731] Trial 12 finished with value: 0.6389569179888609 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6389569179888609.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.4592274678111588
[I 2024-04-15 16:52:13,801] Trial 13 finished with value: 0.5558012163864231 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6389569179888609.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:52:20,165] Trial 14 finished with value: 0.6391016496388321 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 14 with value: 0.6391016496388321.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.5057034220532319
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:52:27,957] Trial 15 finished with value: 0.6096450848923747 and parameters: {'subsample': 0.2913523637503245, 'dropout_rate': 0.7098041576457912, 'n_estimators': 358, 'learning_rate': 0.08616677729964022}. Best is trial 14 with value: 0.6391016496388321.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5247148288973384
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:52:38,117] Trial 16 finished with value: 0.63055942028235 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.7326988341376399, 'n_estimators': 427, 'learning_rate': 0.09672186349880336}. Best is trial 14 with value: 0.6391016496388321.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 16:52:47,180] Trial 17 finished with value: 0.6046657929317489 and parameters: {'subsample': 0.39930407886471125, 'dropout_rate': 0.6120620500196721, 'n_estimators': 413, 'learning_rate': 0.08485124701632729}. Best is trial 14 with value: 0.6391016496388321.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:52:51,305] Trial 18 finished with value: 0.6425425582894422 and parameters: {'subsample': 0.14033791495138467, 'dropout_rate': 0.8058789888144481, 'n_estimators': 269, 'learning_rate': 0.08436585602805469}. Best is trial 18 with value: 0.6425425582894422.

Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.4866920152091255
Fold 5 C-index: 0.5793991416309013
[I 2024-04-15 16:52:54,162] Trial 19 finished with value: 0.5989215996530706 and parameters: {'subsample': 0.34314044045637715, 'dropout_rate': 0.9952300589118265, 'n_estimators': 248, 'learning_rate': 0.08042171957478578}. Best is trial 18 with value: 0.6425425582894422.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:52:55,326] Trial 20 finished with value: 0.6109805071529554 and parameters: {'subsample': 0.26117394341526556, 'dropout_rate': 0.8166141686494631, 'n_estimators': 112, 'learning_rate': 0.06551866052750378}. Best is trial 18 with value: 0.6425425582894422.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:53:00,185] Trial 21 finished with value: 0.6241228881331433 and parameters: {'subsample': 0.1237887713514979, 'dropout_rate': 0.7847568159653954, 'n_estimators': 305, 'learning_rate': 0.09466708801336095}. Best is trial 18 with value: 0.6425425582894422.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:53:08,325] Trial 22 finished with value: 0.6449944258993277 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.6070410556827018, 'n_estimators': 417, 'learning_rate': 0.09947651677688762}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:53:17,631] Trial 23 finished with value: 0.6304831264079562 and parameters: {'subsample': 0.2009103460304391, 'dropout_rate': 0.6286055768912979, 'n_estimators': 443, 'learning_rate': 0.08178533992595556}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5247148288973384
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:53:25,584] Trial 24 finished with value: 0.6304762449820872 and parameters: {'subsample': 0.21578919320920098, 'dropout_rate': 0.5690070729435628, 'n_estimators': 401, 'learning_rate': 0.09003468010738351}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 16:53:28,874] Trial 25 finished with value: 0.6043360347882677 and parameters: {'subsample': 0.41518848496569194, 'dropout_rate': 0.9368303910253752, 'n_estimators': 257, 'learning_rate': 0.09939953445435756}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:53:35,610] Trial 26 finished with value: 0.6410541673195691 and parameters: {'subsample': 0.10335890957570726, 'dropout_rate': 0.7710807407466631, 'n_estimators': 345, 'learning_rate': 0.08004450663761903}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:53:45,639] Trial 27 finished with value: 0.6090657167438215 and parameters: {'subsample': 0.29886665575418997, 'dropout_rate': 0.8057541268141934, 'n_estimators': 452, 'learning_rate': 0.07832654668650665}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.5057034220532319
Fold 5 C-index: 0.5450643776824035
[I 2024-04-15 16:53:52,866] Trial 28 finished with value: 0.5876713890102249 and parameters: {'subsample': 0.5995218654578806, 'dropout_rate': 0.8551707338497903, 'n_estimators': 392, 'learning_rate': 0.07529990760195726}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.4592274678111588
[I 2024-04-15 16:53:54,146] Trial 29 finished with value: 0.5519989350176018 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.7572779652866316, 'n_estimators': 105, 'learning_rate': 0.06046208382653473}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:53:58,662] Trial 30 finished with value: 0.6359401657814377 and parameters: {'subsample': 0.15713536588053945, 'dropout_rate': 0.6622318084652269, 'n_estimators': 276, 'learning_rate': 0.04416249111749597}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:54:05,057] Trial 31 finished with value: 0.6366791465257441 and parameters: {'subsample': 0.10801745825087444, 'dropout_rate': 0.7098368939662143, 'n_estimators': 348, 'learning_rate': 0.09051558882314262}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:54:11,436] Trial 32 finished with value: 0.6346441300901201 and parameters: {'subsample': 0.17191276277652373, 'dropout_rate': 0.5409099169321357, 'n_estimators': 336, 'learning_rate': 0.0909932676415223}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:54:19,747] Trial 33 finished with value: 0.6230339452450664 and parameters: {'subsample': 0.24405335102414993, 'dropout_rate': 0.48095898939081394, 'n_estimators': 385, 'learning_rate': 0.07030315664354014}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:54:23,386] Trial 34 finished with value: 0.6344883688262126 and parameters: {'subsample': 0.19038813125354787, 'dropout_rate': 0.6685834679387015, 'n_estimators': 231, 'learning_rate': 0.09241991287538294}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:54:35,051] Trial 35 finished with value: 0.6047884817881097 and parameters: {'subsample': 0.33602259281936153, 'dropout_rate': 0.6013180235260388, 'n_estimators': 476, 'learning_rate': 0.08253228518177608}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:54:40,831] Trial 36 finished with value: 0.6336366271796995 and parameters: {'subsample': 0.1478952270746442, 'dropout_rate': 0.8530958525199838, 'n_estimators': 285, 'learning_rate': 0.07407010376678294}. Best is trial 22 with value: 0.6449944258993277.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:54:49,057] Trial 37 finished with value: 0.6189303661588055 and parameters: {'subsample': 0.23757075657728957, 'dropout_rate': 0.47096246897520044, 'n_estimators': 341, 'learning_rate': 0.08664244690217021}. Best is trial 22 with value: 0.6449944258993277.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:54:57,174] Trial 38 finished with value: 0.6452341672670587 and parameters: {'subsample': 0.1004921614604077, 'dropout_rate': 0.9230355657351519, 'n_estimators': 427, 'learning_rate': 0.06351044805702724}. Best is trial 38 with value: 0.6452341672670587.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.5209125475285171
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:54:59,063] Trial 39 finished with value: 0.6153302851897602 and parameters: {'subsample': 0.2895346602735268, 'dropout_rate': 0.9803625318253736, 'n_estimators': 145, 'learning_rate': 0.0574622782928275}. Best is trial 38 with value: 0.6452341672670587.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.5493562231759657
[I 2024-04-15 16:55:07,599] Trial 40 finished with value: 0.5860060416689463 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.914947717264729, 'n_estimators': 434, 'learning_rate': 0.07217129758110293}. Best is trial 38 with value: 0.6452341672670587.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:55:18,781] Trial 41 finished with value: 0.6438792256309014 and parameters: {'subsample': 0.10784129527709645, 'dropout_rate': 0.7916763246407665, 'n_estimators': 487, 'learning_rate': 0.06520411617131289}. Best is trial 38 with value: 0.6452341672670587.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:55:28,985] Trial 42 finished with value: 0.6305038976723981 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.8756152004440086, 'n_estimators': 490, 'learning_rate': 0.06911254892370094}. Best is trial 38 with value: 0.6452341672670587.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:55:39,653] Trial 43 finished with value: 0.6465375082273016 and parameters: {'subsample': 0.1059568524246166, 'dropout_rate': 0.8205962369387412, 'n_estimators': 466, 'learning_rate': 0.06210541418811967}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:55:48,586] Trial 44 finished with value: 0.6353175597317758 and parameters: {'subsample': 0.16242789119917195, 'dropout_rate': 0.960470338660746, 'n_estimators': 462, 'learning_rate': 0.06368220079876237}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5209125475285171
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:55:59,394] Trial 45 finished with value: 0.6272673914697784 and parameters: {'subsample': 0.22209950232408754, 'dropout_rate': 0.8192555812859592, 'n_estimators': 490, 'learning_rate': 0.05161307272277839}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:56:09,005] Trial 46 finished with value: 0.6368887185931169 and parameters: {'subsample': 0.1541445182525969, 'dropout_rate': 0.8884970399103027, 'n_estimators': 426, 'learning_rate': 0.04255829021754075}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.4592274678111588
[I 2024-04-15 16:56:09,583] Trial 47 finished with value: 0.5558012163864231 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.9300042878121526, 'n_estimators': 43, 'learning_rate': 0.055819126761793035}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:56:20,812] Trial 48 finished with value: 0.6465375082273016 and parameters: {'subsample': 0.1004172298398558, 'dropout_rate': 0.8394658701129177, 'n_estimators': 463, 'learning_rate': 0.03952603204634069}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:56:35,740] Trial 49 finished with value: 0.6322536918431081 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.843921687114186, 'n_estimators': 500, 'learning_rate': 0.028794294070502602}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.5171102661596958
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:56:48,240] Trial 50 finished with value: 0.6144796452030292 and parameters: {'subsample': 0.28174452746796325, 'dropout_rate': 0.31148051762486684, 'n_estimators': 463, 'learning_rate': 0.013209670524177694}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:56:55,640] Trial 51 finished with value: 0.6458454897291148 and parameters: {'subsample': 0.10358905492176312, 'dropout_rate': 0.8977399729764916, 'n_estimators': 416, 'learning_rate': 0.03813145356542676}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:57:03,195] Trial 52 finished with value: 0.6374364292843887 and parameters: {'subsample': 0.11139902167561912, 'dropout_rate': 0.8943989640918646, 'n_estimators': 411, 'learning_rate': 0.04064383403281223}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:57:11,605] Trial 53 finished with value: 0.6378455513466686 and parameters: {'subsample': 0.1402527257867318, 'dropout_rate': 0.9460235186674478, 'n_estimators': 476, 'learning_rate': 0.037817199838231806}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5247148288973384
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:57:19,253] Trial 54 finished with value: 0.6322831668924789 and parameters: {'subsample': 0.1948619656128998, 'dropout_rate': 0.404365072664145, 'n_estimators': 373, 'learning_rate': 0.04754163927903017}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.5064377682403434
[I 2024-04-15 16:57:26,926] Trial 55 finished with value: 0.5674588137689422 and parameters: {'subsample': 0.6765664077905448, 'dropout_rate': 0.7542225670774081, 'n_estimators': 449, 'learning_rate': 0.0333516708944732}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:57:35,019] Trial 56 finished with value: 0.6408331253609425 and parameters: {'subsample': 0.13628669041188105, 'dropout_rate': 0.8374326866924717, 'n_estimators': 420, 'learning_rate': 0.02477499974920626}. Best is trial 43 with value: 0.6465375082273016.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:57:44,083] Trial 57 finished with value: 0.6441287515316899 and parameters: {'subsample': 0.10566463073014822, 'dropout_rate': 0.9047108636626874, 'n_estimators': 441, 'learning_rate': 0.04798016901911015}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5171102661596958
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:57:51,687] Trial 58 finished with value: 0.6230734588011644 and parameters: {'subsample': 0.23913331956379727, 'dropout_rate': 0.971588190954568, 'n_estimators': 440, 'learning_rate': 0.04810427452068166}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:57:58,057] Trial 59 finished with value: 0.6441038485134425 and parameters: {'subsample': 0.10168540499149635, 'dropout_rate': 0.9069308154660749, 'n_estimators': 381, 'learning_rate': 0.0356337778712602}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.5209125475285171
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:58:05,385] Trial 60 finished with value: 0.6206106208941558 and parameters: {'subsample': 0.19844533442573623, 'dropout_rate': 0.9967803796107192, 'n_estimators': 396, 'learning_rate': 0.015170331564064304}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:58:13,167] Trial 61 finished with value: 0.6447081196802432 and parameters: {'subsample': 0.1298042890137772, 'dropout_rate': 0.910665369928389, 'n_estimators': 375, 'learning_rate': 0.0373488515772777}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:58:20,494] Trial 62 finished with value: 0.6406988560607545 and parameters: {'subsample': 0.13406136795768975, 'dropout_rate': 0.882086679789304, 'n_estimators': 415, 'learning_rate': 0.038393456474437114}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.5247148288973384
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 16:58:28,578] Trial 63 finished with value: 0.6307330761518009 and parameters: {'subsample': 0.17583140669490926, 'dropout_rate': 0.9319110411708875, 'n_estimators': 458, 'learning_rate': 0.04784303673785909}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 16:58:35,727] Trial 64 finished with value: 0.6390548308138091 and parameters: {'subsample': 0.13995022181610695, 'dropout_rate': 0.8308576159907903, 'n_estimators': 405, 'learning_rate': 0.0321510753007136}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 16:58:43,818] Trial 65 finished with value: 0.5994248437966163 and parameters: {'subsample': 0.4594375904536786, 'dropout_rate': 0.8718752413200271, 'n_estimators': 434, 'learning_rate': 0.053043947781164114}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:58:52,526] Trial 66 finished with value: 0.6404465527682623 and parameters: {'subsample': 0.10040829471299163, 'dropout_rate': 0.9574560875096148, 'n_estimators': 469, 'learning_rate': 0.04522415652073666}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.5171102661596958
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:58:58,016] Trial 67 finished with value: 0.6273290748063218 and parameters: {'subsample': 0.21224396231055864, 'dropout_rate': 0.9095177546796844, 'n_estimators': 365, 'learning_rate': 0.05906928791032918}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.5057034220532319
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:59:07,073] Trial 68 finished with value: 0.6080115219952126 and parameters: {'subsample': 0.3228722257631875, 'dropout_rate': 0.6880808975439309, 'n_estimators': 448, 'learning_rate': 0.028852535991408287}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.5209125475285171
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:59:14,278] Trial 69 finished with value: 0.6177932929661551 and parameters: {'subsample': 0.25147818860362403, 'dropout_rate': 0.7751920823486016, 'n_estimators': 394, 'learning_rate': 0.01959917926525689}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.4592274678111588
[I 2024-04-15 16:59:24,007] Trial 70 finished with value: 0.5558012163864231 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.1806794570956778, 'n_estimators': 419, 'learning_rate': 0.039685562428453926}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:59:29,632] Trial 71 finished with value: 0.6447081196802432 and parameters: {'subsample': 0.13153115553030514, 'dropout_rate': 0.9105948001048708, 'n_estimators': 377, 'learning_rate': 0.035906435940888194}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:59:34,830] Trial 72 finished with value: 0.6337787525787038 and parameters: {'subsample': 0.169297604814513, 'dropout_rate': 0.8635800427613638, 'n_estimators': 322, 'learning_rate': 0.03580866582603964}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:59:41,488] Trial 73 finished with value: 0.6367442837993669 and parameters: {'subsample': 0.13299817779829182, 'dropout_rate': 0.9302503921522597, 'n_estimators': 375, 'learning_rate': 0.027601260331017022}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:59:52,081] Trial 74 finished with value: 0.6407204750113089 and parameters: {'subsample': 0.12954519013596127, 'dropout_rate': 0.5262869999122965, 'n_estimators': 445, 'learning_rate': 0.041441704411968164}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:59:58,108] Trial 75 finished with value: 0.6337529854400823 and parameters: {'subsample': 0.18155473327217617, 'dropout_rate': 0.7355475718440965, 'n_estimators': 360, 'learning_rate': 0.034467086607900405}. Best is trial 43 with value: 0.6465375082273016.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5171102661596958
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 17:00:04,289] Trial 76 finished with value: 0.6248806775677773 and parameters: {'subsample': 0.21853807802617867, 'dropout_rate': 0.9995101648902105, 'n_estimators': 430, 'learning_rate': 0.04444915192953196}. Best is trial 43 with value: 0.6465375082273016.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 17:00:04,660] Trial 77 finished with value: 0.6474981923126991 and parameters: {'subsample': 0.10051745578141419, 'dropout_rate': 0.8053356883307206, 'n_estimators': 22, 'learning_rate': 0.0546539002707277}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 17:00:05,061] Trial 78 finished with value: 0.6335793295706313 and parameters: {'subsample': 0.15562104411824268, 'dropout_rate': 0.8083209938882616, 'n_estimators': 23, 'learning_rate': 0.050000182031887726}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5247148288973384
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 17:00:05,935] Trial 79 finished with value: 0.626836073178763 and parameters: {'subsample': 0.1271323959650669, 'dropout_rate': 0.7924422234386488, 'n_estimators': 79, 'learning_rate': 0.056682181955103106}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.5171102661596958
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 17:00:08,322] Trial 80 finished with value: 0.6161202165128952 and parameters: {'subsample': 0.27237562004428684, 'dropout_rate': 0.8382143620977124, 'n_estimators': 199, 'learning_rate': 0.06326352650085158}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6223175965665236
[I 2024-04-15 17:00:15,419] Trial 81 finished with value: 0.6373821782036054 and parameters: {'subsample': 0.1129629066581815, 'dropout_rate': 0.9124715182602301, 'n_estimators': 404, 'learning_rate': 0.05361995044062902}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 17:00:17,405] Trial 82 finished with value: 0.6361862377451468 and parameters: {'subsample': 0.1570317741089906, 'dropout_rate': 0.8719721473326215, 'n_estimators': 161, 'learning_rate': 0.03748746602449565}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:00:26,393] Trial 83 finished with value: 0.6474106148506994 and parameters: {'subsample': 0.10212575348060401, 'dropout_rate': 0.8939604081010644, 'n_estimators': 480, 'learning_rate': 0.03086701653183924}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 17:00:34,098] Trial 84 finished with value: 0.6385808077459643 and parameters: {'subsample': 0.12814558024981723, 'dropout_rate': 0.9544898739460603, 'n_estimators': 482, 'learning_rate': 0.03138077272586817}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 17:00:43,201] Trial 85 finished with value: 0.6323152481928165 and parameters: {'subsample': 0.1860639006849153, 'dropout_rate': 0.8589792448259468, 'n_estimators': 497, 'learning_rate': 0.022329149574263442}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 17:00:51,671] Trial 86 finished with value: 0.6362513750187695 and parameters: {'subsample': 0.15124890699698262, 'dropout_rate': 0.8255732621163049, 'n_estimators': 468, 'learning_rate': 0.06630313380105933}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 17:00:59,778] Trial 87 finished with value: 0.645762314428852 and parameters: {'subsample': 0.1008766035126651, 'dropout_rate': 0.7532902683376137, 'n_estimators': 454, 'learning_rate': 0.026662453993212498}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:01:08,163] Trial 88 finished with value: 0.64659906457701 and parameters: {'subsample': 0.10164217843589951, 'dropout_rate': 0.7530164720025808, 'n_estimators': 458, 'learning_rate': 0.02540582023362391}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 17:01:17,027] Trial 89 finished with value: 0.6465375082273016 and parameters: {'subsample': 0.10060916380762815, 'dropout_rate': 0.6415185321145359, 'n_estimators': 456, 'learning_rate': 0.004801151376730657}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 17:01:25,285] Trial 90 finished with value: 0.633937374067248 and parameters: {'subsample': 0.16852713802023245, 'dropout_rate': 0.6415533308474685, 'n_estimators': 456, 'learning_rate': 0.021099742572702765}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 17:01:34,209] Trial 91 finished with value: 0.6376175174095997 and parameters: {'subsample': 0.11646572663799076, 'dropout_rate': 0.592956296229185, 'n_estimators': 472, 'learning_rate': 0.005596213314986886}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 17:01:45,682] Trial 92 finished with value: 0.63758116093436 and parameters: {'subsample': 0.11062796523624938, 'dropout_rate': 0.6887590913927871, 'n_estimators': 485, 'learning_rate': 0.01192851134958112}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 17:01:53,266] Trial 93 finished with value: 0.6465375082273016 and parameters: {'subsample': 0.10282833227771578, 'dropout_rate': 0.752493111618369, 'n_estimators': 456, 'learning_rate': 0.019127674637257917}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.575107296137339
[I 2024-04-15 17:02:00,912] Trial 94 finished with value: 0.5928583839207955 and parameters: {'subsample': 0.520664370526249, 'dropout_rate': 0.7459355006832995, 'n_estimators': 476, 'learning_rate': 0.024682734371104124}. Best is trial 77 with value: 0.6474981923126991.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 17:02:08,660] Trial 95 finished with value: 0.644965501679848 and parameters: {'subsample': 0.10056105191412253, 'dropout_rate': 0.716113453569274, 'n_estimators': 459, 'learning_rate': 0.0021073886017303435}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 17:02:15,203] Trial 96 finished with value: 0.6392142999884658 and parameters: {'subsample': 0.15319865258065393, 'dropout_rate': 0.7712979923020926, 'n_estimators': 428, 'learning_rate': 0.01906043497111388}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 17:02:22,642] Trial 97 finished with value: 0.6321705165428453 and parameters: {'subsample': 0.19814434026977656, 'dropout_rate': 0.7604424657361102, 'n_estimators': 455, 'learning_rate': 0.006684255493428593}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.4574468085106383
Fold 4 C-index: 0.41825095057034223
Fold 5 C-index: 0.5708154506437768
[I 2024-04-15 17:02:22,818] Trial 98 finished with value: 0.5458609050166956 and parameters: {'subsample': 0.23133249403135034, 'dropout_rate': 0.7872853945702789, 'n_estimators': 1, 'learning_rate': 0.026680503724648433}. Best is trial 77 with value: 0.6474981923126991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.4752851711026616

[I 2024-04-15 17:02:30,873] A new study created in memory with name: no-name-02473b78-c88f-4804-96c8-e5ccceb0c313

Fold 5 C-index: 0.4678111587982833
[I 2024-04-15 17:02:30,862] Trial 99 finished with value: 0.557517954583848 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.8087326116065646, 'n_estimators': 498, 'learning_rate': 0.015603370940631547}. Best is trial 77 with value: 0.6474981923126991.


* Best trial for C-index:
 FrozenTrial(number=77, state=TrialState.COMPLETE, values=[0.6474981923126991], datetime_start=datetime.datetime(2024, 4, 15, 17, 0, 4, 296055), datetime_complete=datetime.datetime(2024, 4, 15, 17, 0, 4, 660121), params={'subsample': 0.10051745578141419, 'dropout_rate': 0.8053356883307206, 'n_estimators': 22, 'learning_rate': 0.0546539002707277}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=77, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10051745578141419, 'dropout_rate': 0.8053356883307206, 'n_estimators': 22, 'learning_rate': 0.0546539002707277}


* Best Score for C-index:
 0.6474981923126991

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.25667723517586666
Fold 2 IBS: 0.2203953477462989
Fold 3 IBS: 0.23066689078693747
Fold 4 IBS: 0.28009083718074307
Fold 5 IBS: 0.23862927652102053
[I 2024-04-15 17:02:32,233] Trial 0 finished with value: 0.24529191748217333 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.24529191748217333.
Fold 1 IBS: 0.3734226727073782
Fold 2 IBS: 0.3302107421998369
Fold 3 IBS: 0.2914266028419895
Fold 4 IBS: 2.5138075192499708e+149
Fold 5 IBS: 0.36600635899359735
[I 2024-04-15 17:02:44,116] Trial 1 finished with value: 5.0276150384999415e+148 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.24529191748217333.
Fold 1 IBS: 0.28575701982381
Fold 2 IBS: 0.24345991086986432
Fold 3 IBS: 0.2267306379673026
Fold 4 IBS: 0.3304198793342806
Fold 5 IBS: 0.2727965831843253
[I 2024-04-15 17:02:46,320] Trial 2 finished with value: 0.2718328062359166 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.24529191748217333.
Fold 1 IBS: 0.29467668119257745
Fold 2 IBS: 0.2480491541840493
Fold 3 IBS: 0.22406246206076266
Fold 4 IBS: 0.3350558660579585
Fold 5 IBS: 0.2790994364941007
[I 2024-04-15 17:02:49,075] Trial 3 finished with value: 0.27618871999788974 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.24529191748217333.
Fold 1 IBS: 0.29270354444699886
Fold 2 IBS: 0.22939968199595337
Fold 3 IBS: 0.2053181215684721
Fold 4 IBS: 0.3185773928328228
Fold 5 IBS: 0.26844161536606803
[I 2024-04-15 17:02:53,347] Trial 4 finished with value: 0.26288807124206304 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.24529191748217333.
Fold 1 IBS: 0.33259051169639914
Fold 2 IBS: 0.2885114079188753
Fold 3 IBS: 0.2614454312148868
Fold 4 IBS: 0.36761025001448056
Fold 5 IBS: 0.3295005204494657
[I 2024-04-15 17:02:58,181] Trial 5 finished with value: 0.3159316242588215 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.24529191748217333.
Fold 1 IBS: 0.24877552677002018
Fold 2 IBS: 0.219031139536118
Fold 3 IBS: 0.22952771270088154
Fold 4 IBS: 0.2625156643707422
Fold 5 IBS: 0.23096933844600998
[I 2024-04-15 17:03:00,431] Trial 6 finished with value: 0.2381638763647544 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2381638763647544.
Fold 1 IBS: 0.24568903561026953
Fold 2 IBS: 0.22250156538138458
Fold 3 IBS: 0.22487048999158954
Fold 4 IBS: 0.24916128587204245
Fold 5 IBS: 0.22796049523669365
[I 2024-04-15 17:03:00,925] Trial 7 finished with value: 0.23403657441839595 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23403657441839595.
Fold 1 IBS: 0.25781884868176747
Fold 2 IBS: 0.21620473772910365
Fold 3 IBS: 0.22298380397606032
Fold 4 IBS: 0.28146400317230874
Fold 5 IBS: 0.23927430873115949
[I 2024-04-15 17:03:03,406] Trial 8 finished with value: 0.24354914045807993 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23403657441839595.
Fold 1 IBS: 0.3421750471474315
Fold 2 IBS: 0.2868191941466379
Fold 3 IBS: 0.24705100416313042
Fold 4 IBS: 0.3675604069262056
Fold 5 IBS: 0.331764376513956
[I 2024-04-15 17:03:10,731] Trial 9 finished with value: 0.3150740057794723 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23403657441839595.
Fold 1 IBS: 0.2471351060657296
Fold 2 IBS: 0.2318544922573484
Fold 3 IBS: 0.2289649286355643
Fold 4 IBS: 0.24207148586216132
Fold 5 IBS: 0.2293870432783957
[I 2024-04-15 17:03:11,144] Trial 10 finished with value: 0.23588261121983986 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23403657441839595.
Fold 1 IBS: 0.2467901743838015
Fold 2 IBS: 0.2312610102295463
Fold 3 IBS: 0.22891540752506118
Fold 4 IBS: 0.24240092596077853
Fold 5 IBS: 0.22935952598026746
[I 2024-04-15 17:03:11,474] Trial 11 finished with value: 0.235745408815891 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23403657441839595.
Fold 1 IBS: 0.24361709501746984
Fold 2 IBS: 0.21055242080368805
Fold 3 IBS: 0.21618843499346657
Fold 4 IBS: 0.2585333534750037
Fold 5 IBS: 0.22428981178254853
[I 2024-04-15 17:03:12,161] Trial 12 finished with value: 0.23063622321443536 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.2531968207134257
Fold 2 IBS: 0.19980881399871414
Fold 3 IBS: 0.21883065367908544
Fold 4 IBS: 0.27855782962237274
Fold 5 IBS: 0.22060250453586663
[I 2024-04-15 17:03:13,084] Trial 13 finished with value: 0.23419932450989292 and parameters: {'subsample': 0.11029739529314715, 'dropout_rate': 0.695526957994077, 'n_estimators': 86, 'learning_rate': 0.09856277651579823}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.24677703054722558
Fold 2 IBS: 0.22064453504657525
Fold 3 IBS: 0.22300937838971677
Fold 4 IBS: 0.25207706021954346
Fold 5 IBS: 0.2268967912730172
[I 2024-04-15 17:03:14,104] Trial 14 finished with value: 0.23388095909521564 and parameters: {'subsample': 0.2888452381430052, 'dropout_rate': 0.6348327022941171, 'n_estimators': 79, 'learning_rate': 0.035476350988955505}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.24533442855549842
Fold 2 IBS: 0.22312307870487189
Fold 3 IBS: 0.21854605913533523
Fold 4 IBS: 0.24557353592149236
Fold 5 IBS: 0.22598551989760823
[I 2024-04-15 17:03:15,310] Trial 15 finished with value: 0.2317125244429612 and parameters: {'subsample': 0.10269051002372756, 'dropout_rate': 0.8088719290273756, 'n_estimators': 112, 'learning_rate': 0.017180301525687395}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.24418594446206257
Fold 2 IBS: 0.22204366201156137
Fold 3 IBS: 0.2202730985690266
Fold 4 IBS: 0.2493419339437409
Fold 5 IBS: 0.22516572153284797
[I 2024-04-15 17:03:18,610] Trial 16 finished with value: 0.23220207210384788 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 279, 'learning_rate': 0.008849016864295123}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.24531447767029577
Fold 2 IBS: 0.22344427124957103
Fold 3 IBS: 0.22771683574266935
Fold 4 IBS: 0.24590915546875652
Fold 5 IBS: 0.22780495639739795
[I 2024-04-15 17:03:19,971] Trial 17 finished with value: 0.23403793930573807 and parameters: {'subsample': 0.20486489858272047, 'dropout_rate': 0.8330054375968005, 'n_estimators': 127, 'learning_rate': 0.012921570002964877}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.36384849169681804
Fold 2 IBS: 0.29297944851563373
Fold 3 IBS: 0.2247207529248139
Fold 4 IBS: 0.37651878534509203
Fold 5 IBS: 0.3436080691806825
[I 2024-04-15 17:03:24,728] Trial 18 finished with value: 0.320335109532608 and parameters: {'subsample': 0.3674262467329663, 'dropout_rate': 0.8096950255181005, 'n_estimators': 336, 'learning_rate': 0.0851241515162967}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.2448762945862029

Fold 2 IBS: 0.22173151919127074
Fold 3 IBS: 0.2240083997893821
Fold 4 IBS: 0.2464359496761848
Fold 5 IBS: 0.2271016662961729
[I 2024-04-15 17:03:26,007] Trial 19 finished with value: 0.2328307659078427 and parameters: {'subsample': 0.16667191735421055, 'dropout_rate': 0.994814822896155, 'n_estimators': 132, 'learning_rate': 0.016543957974820042}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.24582901698106285
Fold 2 IBS: 0.2225691567522993
Fold 3 IBS: 0.22660865453347748
Fold 4 IBS: 0.24909665057919317
Fold 5 IBS: 0.2278922684637406
[I 2024-04-15 17:03:26,636] Trial 20 finished with value: 0.23439914946195467 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.5777838682216713, 'n_estimators': 54, 'learning_rate': 0.03973446561107324}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.24634790271407495
Fold 2 IBS: 0.2298528724561472
Fold 3 IBS: 0.22670230474026679
Fold 4 IBS: 0.24295667622798126
Fold 5 IBS: 0.2285820944108233
[I 2024-04-15 17:03:30,829] Trial 21 finished with value: 0.2348883701098587 and parameters: {'subsample': 0.11014863416226671, 'dropout_rate': 0.9754161103921428, 'n_estimators': 314, 'learning_rate': 0.0016108337344105245}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.26895123031358936
Fold 2 IBS: 0.20650952373238365
Fold 3 IBS: 0.20521780013164115
Fold 4 IBS: 0.29115555506677876
Fold 5 IBS: 0.24086579759312987
[I 2024-04-15 17:03:37,577] Trial 22 finished with value: 0.24253998136750457 and parameters: {'subsample': 0.23857869356389952, 'dropout_rate': 0.786165129132064, 'n_estimators': 419, 'learning_rate': 0.02494417373251419}. Best is trial 12 with value: 0.23063622321443536.
Fold 1 IBS: 0.24535594215291656
Fold 2 IBS: 0.21703193819714864
Fold 3 IBS: 0.21460635664048425
Fold 4 IBS: 0.2508125039113153
Fold 5 IBS: 0.22483200140485923
[I 2024-04-15 17:03:40,753] Trial 23 finished with value: 0.23052774846134477 and parameters: {'subsample': 0.16691301270561476, 'dropout_rate': 0.8934201699606112, 'n_estimators': 256, 'learning_rate': 0.013693154749890787}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.2517636284211971
Fold 2 IBS: 0.21278532050901092
Fold 3 IBS: 0.2176331971189051
Fold 4 IBS: 0.26572186633626166
Fold 5 IBS: 0.22929825329254766
[I 2024-04-15 17:03:43,527] Trial 24 finished with value: 0.23544045313558448 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.7652919670925054, 'n_estimators': 231, 'learning_rate': 0.024097412678429634}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.24497499246411208
Fold 2 IBS: 0.21977387889572406
Fold 3 IBS: 0.22040792144123345
Fold 4 IBS: 0.24997517693633622
Fold 5 IBS: 0.22631969393535503
[I 2024-04-15 17:03:45,112] Trial 25 finished with value: 0.23229033273455216 and parameters: {'subsample': 0.1799226972010436, 'dropout_rate': 0.8916290142712974, 'n_estimators': 154, 'learning_rate': 0.017437187361754786}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.25279395774375285
Fold 2 IBS: 0.20324846144220204
Fold 3 IBS: 0.2039886518967233
Fold 4 IBS: 0.2700425928211592
Fold 5 IBS: 0.22729064892340797
[I 2024-04-15 17:03:46,097] Trial 26 finished with value: 0.23147286256544905 and parameters: {'subsample': 0.1625477469200986, 'dropout_rate': 0.607871694065333, 'n_estimators': 92, 'learning_rate': 0.08424196338144659}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.3427635322417735
Fold 2 IBS: 0.2326096770883646
Fold 3 IBS: 0.19085707000343233
Fold 4 IBS: 0.33655870421952366
Fold 5 IBS: 0.2992757528629021
[I 2024-04-15 17:03:50,736] Trial 27 finished with value: 0.28041294728319927 and parameters: {'subsample': 0.18440648064765508, 'dropout_rate': 0.6159661694877357, 'n_estimators': 294, 'learning_rate': 0.08605613393144518}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.37189530477775296
Fold 2 IBS: 0.29074520347817906
Fold 3 IBS: 0.23828442112611403
Fold 4 IBS: 0.37550389714570737
Fold 5 IBS: 0.34728578654166137
[I 2024-04-15 17:03:56,771] Trial 28 finished with value: 0.324742922613883 and parameters: {'subsample': 0.3267564321862687, 'dropout_rate': 0.5170553005838203, 'n_estimators': 363, 'learning_rate': 0.08318990790688839}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.2672417572604392
Fold 2 IBS: 0.22366171956706513
Fold 3 IBS: 0.21387501619857885
Fold 4 IBS: 0.3034080588056835
Fold 5 IBS: 0.25231085742529297
[I 2024-04-15 17:03:57,763] Trial 29 finished with value: 0.25209948185141196 and parameters: {'subsample': 0.43340260475996684, 'dropout_rate': 0.3961659985117076, 'n_estimators': 97, 'learning_rate': 0.0989265686549639}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.29838850214057266
Fold 2 IBS: 0.25717010102791765
Fold 3 IBS: 0.2382565526984567
Fold 4 IBS: 0.34053220876717905
Fold 5 IBS: 0.29011350039682116
[I 2024-04-15 17:04:00,629] Trial 30 finished with value: 0.2848921730061894 and parameters: {'subsample': 0.5936384513688024, 'dropout_rate': 0.9169054369551878, 'n_estimators': 232, 'learning_rate': 0.06354770598840508}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.2452229398931622
Fold 2 IBS: 0.21097457968903774
Fold 3 IBS: 0.22176720296144686
Fold 4 IBS: 0.2584189435050366
Fold 5 IBS: 0.22631713289880598
[I 2024-04-15 17:04:01,229] Trial 31 finished with value: 0.23254015978949788 and parameters: {'subsample': 0.1548281298984664, 'dropout_rate': 0.7605959148769734, 'n_estimators': 55, 'learning_rate': 0.07812979450833542}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.2698949324811658
Fold 2 IBS: 0.20761944378529337
Fold 3 IBS: 0.22835981442858047
Fold 4 IBS: 0.28252052818385326
Fold 5 IBS: 0.24254616487775812
[I 2024-04-15 17:04:02,373] Trial 32 finished with value: 0.24618817675133017 and parameters: {'subsample': 0.2432594094791461, 'dropout_rate': 0.6377712362987691, 'n_estimators': 110, 'learning_rate': 0.09243146186321595}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.24572702417712908
Fold 2 IBS: 0.22537819568605025
Fold 3 IBS: 0.22739114590469892
Fold 4 IBS: 0.24478111240986355
Fold 5 IBS: 0.22780478882712873
[I 2024-04-15 17:04:04,025] Trial 33 finished with value: 0.23421645340097408 and parameters: {'subsample': 0.21905912844844005, 'dropout_rate': 0.831129642694275, 'n_estimators': 154, 'learning_rate': 0.008390503824508122}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.24717786988870546
Fold 2 IBS: 0.23106464907961247
Fold 3 IBS: 0.2292482750881719
Fold 4 IBS: 0.2420856834951268
Fold 5 IBS: 0.22927116513497356
[I 2024-04-15 17:04:04,254] Trial 34 finished with value: 0.23576952853731803 and parameters: {'subsample': 0.14514897107627275, 'dropout_rate': 0.4707375628889984, 'n_estimators': 5, 'learning_rate': 0.04555197845451091}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.24999468066308686
Fold 2 IBS: 0.219083650885635
Fold 3 IBS: 0.23013460322979584
Fold 4 IBS: 0.2647015699341755
Fold 5 IBS: 0.23210973938563786
[I 2024-04-15 17:04:04,903] Trial 35 finished with value: 0.23920484881966622 and parameters: {'subsample': 0.8513360553133628, 'dropout_rate': 0.7525058057546873, 'n_estimators': 70, 'learning_rate': 0.0649387197681886}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.2908420865429164
Fold 2 IBS: 0.21772996330928368
Fold 3 IBS: 0.22270413475134276
Fold 4 IBS: 0.3069165199334545
Fold 5 IBS: 0.2604342691427033
[I 2024-04-15 17:04:06,988] Trial 36 finished with value: 0.2597253947359401 and parameters: {'subsample': 0.24602247034825603, 'dropout_rate': 0.5847496282810936, 'n_estimators': 183, 'learning_rate': 0.07410397433525882}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.2456192460387314
Fold 2 IBS: 0.2226067366959931
Fold 3 IBS: 0.22558457156856646
Fold 4 IBS: 0.2494062256285554
Fold 5 IBS: 0.2265672960398013
[I 2024-04-15 17:04:07,444] Trial 37 finished with value: 0.2339568151943295 and parameters: {'subsample': 0.13692998038808646, 'dropout_rate': 0.673899239108191, 'n_estimators': 32, 'learning_rate': 0.05621431261796065}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.258583923970022

Fold 2 IBS: 0.20902953968424892
Fold 3 IBS: 0.2176051201013263
Fold 4 IBS: 0.2734109979240352
Fold 5 IBS: 0.23255560033240433
[I 2024-04-15 17:04:11,381] Trial 38 finished with value: 0.23823703640240734 and parameters: {'subsample': 0.28142644997062893, 'dropout_rate': 0.26191278993485095, 'n_estimators': 253, 'learning_rate': 0.028968935059673087}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.27956409436548896
Fold 2 IBS: 0.2081148213434298
Fold 3 IBS: 0.21550561997048281
Fold 4 IBS: 0.30174781335524775
Fold 5 IBS: 0.2521330714304219
[I 2024-04-15 17:04:13,022] Trial 39 finished with value: 0.25141308409301427 and parameters: {'subsample': 0.19853845181024166, 'dropout_rate': 0.8550264503945254, 'n_estimators': 145, 'learning_rate': 0.09403098424740443}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.26770221085682805
Fold 2 IBS: 0.22837089778981953
Fold 3 IBS: 0.2288833433633006
Fold 4 IBS: 0.3030990070849948
Fold 5 IBS: 0.254317418785605
[I 2024-04-15 17:04:14,121] Trial 40 finished with value: 0.25647457557610964 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.9296589784739994, 'n_estimators': 109, 'learning_rate': 0.0801554354764448}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.24429873948836714
Fold 2 IBS: 0.22269107407858296
Fold 3 IBS: 0.22078436754670103
Fold 4 IBS: 0.24899364475223132
Fold 5 IBS: 0.22530099298034809
[I 2024-04-15 17:04:17,941] Trial 41 finished with value: 0.2324137637692461 and parameters: {'subsample': 0.10444549569082516, 'dropout_rate': 0.9388784820256767, 'n_estimators': 302, 'learning_rate': 0.007521962753838467}. Best is trial 23 with value: 0.23052774846134477.
Fold 1 IBS: 0.24533642304311318
Fold 2 IBS: 0.21081485600576536
Fold 3 IBS: 0.21445355391538634
Fold 4 IBS: 0.25748189245473496
Fold 5 IBS: 0.22299360741854735
[I 2024-04-15 17:04:21,181] Trial 42 finished with value: 0.23021606656750943 and parameters: {'subsample': 0.10945556729486496, 'dropout_rate': 0.871976342308257, 'n_estimators': 266, 'learning_rate': 0.018907297235425224}. Best is trial 42 with value: 0.23021606656750943.
Fold 1 IBS: 0.24569539132322732
Fold 2 IBS: 0.2167907902038079
Fold 3 IBS: 0.21668994440471837
Fold 4 IBS: 0.2533434278200589
Fold 5 IBS: 0.22503973679345127
[I 2024-04-15 17:04:23,371] Trial 43 finished with value: 0.23151185810905278 and parameters: {'subsample': 0.15053250102233282, 'dropout_rate': 0.8791993491158414, 'n_estimators': 202, 'learning_rate': 0.018024837845780108}. Best is trial 42 with value: 0.23021606656750943.
Fold 1 IBS: 0.24941377390858027
Fold 2 IBS: 0.20837963202690846
Fold 3 IBS: 0.20170092497010614
Fold 4 IBS: 0.2603509004738513
Fold 5 IBS: 0.22477783322069386
[I 2024-04-15 17:04:25,517] Trial 44 finished with value: 0.22892461292002797 and parameters: {'subsample': 0.17479615634093615, 'dropout_rate': 0.8889571284656569, 'n_estimators': 201, 'learning_rate': 0.029145450039674267}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.2555224001677802
Fold 2 IBS: 0.20509493145006483
Fold 3 IBS: 0.21595072398881474
Fold 4 IBS: 0.2639767107107126
Fold 5 IBS: 0.2267299001177209
[I 2024-04-15 17:04:28,192] Trial 45 finished with value: 0.23345493328701866 and parameters: {'subsample': 0.22433039587889622, 'dropout_rate': 0.7351905812033399, 'n_estimators': 225, 'learning_rate': 0.030636191307402853}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.2710766088101246
Fold 2 IBS: 0.21723334321614968
Fold 3 IBS: 0.21389224458561953
Fold 4 IBS: 0.2963867575077432
Fold 5 IBS: 0.2480683089651772
[I 2024-04-15 17:04:32,165] Trial 46 finished with value: 0.24933145261696282 and parameters: {'subsample': 0.34218169198937776, 'dropout_rate': 0.14648424644002478, 'n_estimators': 263, 'learning_rate': 0.03904499595809513}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.25065853269102256
Fold 2 IBS: 0.21625859187451
Fold 3 IBS: 0.222455210311939
Fold 4 IBS: 0.2626767230849609
Fold 5 IBS: 0.23050759284490951
[I 2024-04-15 17:04:34,175] Trial 47 finished with value: 0.23651133016146844 and parameters: {'subsample': 0.4151334983551951, 'dropout_rate': 0.8550821527734562, 'n_estimators': 181, 'learning_rate': 0.026968927757969725}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.2533623466164728
Fold 2 IBS: 0.2106060619046985
Fold 3 IBS: 0.2186629582775047
Fold 4 IBS: 0.26633864964604537
Fold 5 IBS: 0.22861399956094994
[I 2024-04-15 17:04:38,581] Trial 48 finished with value: 0.23551680320113424 and parameters: {'subsample': 0.2739439111552987, 'dropout_rate': 0.5204870232670515, 'n_estimators': 277, 'learning_rate': 0.021323744665812876}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.24811124601808401
Fold 2 IBS: 0.2193736123759157
Fold 3 IBS: 0.22958026576912335
Fold 4 IBS: 0.25977878763223783
Fold 5 IBS: 0.23058616649419703
[I 2024-04-15 17:04:44,663] Trial 49 finished with value: 0.23748601565791158 and parameters: {'subsample': 0.8118729209082775, 'dropout_rate': 0.7113138604644814, 'n_estimators': 344, 'learning_rate': 0.01162621523864678}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.3259412568153866
Fold 2 IBS: 0.23367637358373475
Fold 3 IBS: 0.19406555006589732
Fold 4 IBS: 0.3359045716043334
Fold 5 IBS: 0.2875614167669376
[I 2024-04-15 17:04:47,803] Trial 50 finished with value: 0.27542983376725794 and parameters: {'subsample': 0.18371302843789558, 'dropout_rate': 0.9501582476866339, 'n_estimators': 247, 'learning_rate': 0.08965913316297708}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.24670715755274575
Fold 2 IBS: 0.21331175061714283
Fold 3 IBS: 0.21366790851076914
Fold 4 IBS: 0.2569450823466606
Fold 5 IBS: 0.2243310418532781
[I 2024-04-15 17:04:50,449] Trial 51 finished with value: 0.23099258817611928 and parameters: {'subsample': 0.14595010608317469, 'dropout_rate': 0.8931718566179312, 'n_estimators': 209, 'learning_rate': 0.021867550367933235}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.24586762308645985
Fold 2 IBS: 0.2274797893529895
Fold 3 IBS: 0.22457686184654832
Fold 4 IBS: 0.24430786662331735
Fold 5 IBS: 0.2279694692262578
[I 2024-04-15 17:04:52,739] Trial 52 finished with value: 0.23404032202711456 and parameters: {'subsample': 0.13585020951618046, 'dropout_rate': 0.800200404069689, 'n_estimators': 202, 'learning_rate': 0.004866092204822609}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.2524512386737445
Fold 2 IBS: 0.20603151860984883
Fold 3 IBS: 0.2164901239223486
Fold 4 IBS: 0.26231359338505894
Fold 5 IBS: 0.22532699432196246
[I 2024-04-15 17:04:54,556] Trial 53 finished with value: 0.23252269378259266 and parameters: {'subsample': 0.21263858007306308, 'dropout_rate': 0.8733810874139999, 'n_estimators': 171, 'learning_rate': 0.03564254941420347}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.24638896739312277
Fold 2 IBS: 0.2133219893371707
Fold 3 IBS: 0.21097136326368457
Fold 4 IBS: 0.2553196272764187
Fold 5 IBS: 0.22418118496206624
[I 2024-04-15 17:04:58,737] Trial 54 finished with value: 0.23003662644649264 and parameters: {'subsample': 0.1686069415128497, 'dropout_rate': 0.8988648405119773, 'n_estimators': 321, 'learning_rate': 0.014034946579839912}. Best is trial 44 with value: 0.22892461292002797.
Fold 1 IBS: 0.25464283086237693
Fold 2 IBS: 0.19859901359505835
Fold 3 IBS: 0.199336510476801
Fold 4 IBS: 0.2652136407117281
Fold 5 IBS: 0.22300472962349818
[I 2024-04-15 17:05:05,005] Trial 55 finished with value: 0.22815934505389251 and parameters: {'subsample': 0.13320026386793474, 'dropout_rate': 0.9024981518691466, 'n_estimators': 400, 'learning_rate': 0.02064354477956014}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2501340211095423
Fold 2 IBS: 0.2111253742763255
Fold 3 IBS: 0.21375307104563418
Fold 4 IBS: 0.2592019227971746
Fold 5 IBS: 0.22669452847067648
[I 2024-04-15 17:05:09,778] Trial 56 finished with value: 0.2321817835398706 and parameters: {'subsample': 0.26144504837391863, 'dropout_rate': 0.9957338612480511, 'n_estimators': 387, 'learning_rate': 0.013053921958857148}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2542982302800793

Fold 2 IBS: 0.21067485967648128
Fold 3 IBS: 0.21763914316320562
Fold 4 IBS: 0.2712255729662503
Fold 5 IBS: 0.2311915839344514
[I 2024-04-15 17:05:15,745] Trial 57 finished with value: 0.23700587800409362 and parameters: {'subsample': 0.3042256220165622, 'dropout_rate': 0.9501334595910584, 'n_estimators': 441, 'learning_rate': 0.014668471268377385}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2742477520549114
Fold 2 IBS: 0.2351969031539527
Fold 3 IBS: 0.23614663779050837
Fold 4 IBS: 0.31875757966455087
Fold 5 IBS: 0.2648770528469447
[I 2024-04-15 17:05:23,580] Trial 58 finished with value: 0.2658451851021736 and parameters: {'subsample': 0.6810537336561748, 'dropout_rate': 0.8338894164672775, 'n_estimators': 498, 'learning_rate': 0.020347294424858286}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.26015314902761866
Fold 2 IBS: 0.19334674882444652
Fold 3 IBS: 0.21209235293552248
Fold 4 IBS: 0.27679842900506585
Fold 5 IBS: 0.22618148220055354
[I 2024-04-15 17:05:28,125] Trial 59 finished with value: 0.2337144323986414 and parameters: {'subsample': 0.11847620635305703, 'dropout_rate': 0.9125717599234038, 'n_estimators': 327, 'learning_rate': 0.032601783361055806}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.24735102659427088
Fold 2 IBS: 0.21342439367048657
Fold 3 IBS: 0.21150223005592236
Fold 4 IBS: 0.2555338436800749
Fold 5 IBS: 0.22537212100004686
[I 2024-04-15 17:05:35,482] Trial 60 finished with value: 0.23063672300016033 and parameters: {'subsample': 0.19792367601826735, 'dropout_rate': 0.7841465628464368, 'n_estimators': 421, 'learning_rate': 0.010682440047852675}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2454989863611632
Fold 2 IBS: 0.22203411517491514
Fold 3 IBS: 0.2199739051826057
Fold 4 IBS: 0.2477147918150922
Fold 5 IBS: 0.22679861249018646
[I 2024-04-15 17:05:42,154] Trial 61 finished with value: 0.23240408220479253 and parameters: {'subsample': 0.18858642406218357, 'dropout_rate': 0.7901840877903554, 'n_estimators': 401, 'learning_rate': 0.005425636117267223}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2487422995313541
Fold 2 IBS: 0.21065999428185206
Fold 3 IBS: 0.21164900245629126
Fold 4 IBS: 0.25805441929331674
Fold 5 IBS: 0.22531173531827453
[I 2024-04-15 17:05:50,142] Trial 62 finished with value: 0.23088349017621773 and parameters: {'subsample': 0.20883329722312463, 'dropout_rate': 0.8365991999273402, 'n_estimators': 456, 'learning_rate': 0.010939616046593374}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2693282387953417
Fold 2 IBS: 0.20157019749438043
Fold 3 IBS: 0.19977797228334945
Fold 4 IBS: 0.2843094247865838
Fold 5 IBS: 0.23513580048491994
[I 2024-04-15 17:05:56,438] Trial 63 finished with value: 0.23802432676891505 and parameters: {'subsample': 0.1691869683520294, 'dropout_rate': 0.9655198781734357, 'n_estimators': 426, 'learning_rate': 0.02651988939969155}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.24940226912005872
Fold 2 IBS: 0.20422705682456452
Fold 3 IBS: 0.2163282046921309
Fold 4 IBS: 0.26149734637765465
Fold 5 IBS: 0.22285341510883286
[I 2024-04-15 17:06:01,715] Trial 64 finished with value: 0.23086165842464834 and parameters: {'subsample': 0.12398182652129709, 'dropout_rate': 0.8988455032716139, 'n_estimators': 355, 'learning_rate': 0.01922999806255859}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2563087599051478
Fold 2 IBS: 0.20733638068794444
Fold 3 IBS: 0.21389495795367364
Fold 4 IBS: 0.2721048074863749
Fold 5 IBS: 0.229401426568936
[I 2024-04-15 17:06:09,693] Trial 65 finished with value: 0.23580926652041537 and parameters: {'subsample': 0.24924580596862142, 'dropout_rate': 0.8120323868737009, 'n_estimators': 471, 'learning_rate': 0.015089950790943836}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.24572345913469945
Fold 2 IBS: 0.22832817187289317
Fold 3 IBS: 0.22476358624079282
Fold 4 IBS: 0.24392808487777867
Fold 5 IBS: 0.22773463658067056
[I 2024-04-15 17:06:13,701] Trial 66 finished with value: 0.23409558774136693 and parameters: {'subsample': 0.1007594451046917, 'dropout_rate': 0.8529892914465014, 'n_estimators': 298, 'learning_rate': 0.0029923918393679593}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2452819458099162
Fold 2 IBS: 0.2173322612103441
Fold 3 IBS: 0.21489367126456288
Fold 4 IBS: 0.25128778373751987
Fold 5 IBS: 0.22496186091639375
[I 2024-04-15 17:06:18,360] Trial 67 finished with value: 0.23075150458774735 and parameters: {'subsample': 0.1691583158082354, 'dropout_rate': 0.7714357709409072, 'n_estimators': 319, 'learning_rate': 0.0107785564064455}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.32693454325158583
Fold 2 IBS: 0.23654785707850534
Fold 3 IBS: 0.19691190081940674
Fold 4 IBS: 0.3394919996376038
Fold 5 IBS: 0.2939275604485383
[I 2024-04-15 17:06:23,743] Trial 68 finished with value: 0.278762772247128 and parameters: {'subsample': 0.21613799678151646, 'dropout_rate': 0.9262800164669269, 'n_estimators': 371, 'learning_rate': 0.0582375351466085}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2474347151182745
Fold 2 IBS: 0.20770237693370872
Fold 3 IBS: 0.2077908113363639
Fold 4 IBS: 0.25820696390790926
Fold 5 IBS: 0.22375895678647226
[I 2024-04-15 17:06:26,884] Trial 69 finished with value: 0.2289787648165457 and parameters: {'subsample': 0.13878826984957143, 'dropout_rate': 0.6742877948812134, 'n_estimators': 241, 'learning_rate': 0.023513240396387244}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2733252426989991
Fold 2 IBS: 0.18996468132739436
Fold 3 IBS: 0.19776211181841902
Fold 4 IBS: 0.28389972694913573
Fold 5 IBS: 0.23843221165104858
[I 2024-04-15 17:06:30,824] Trial 70 finished with value: 0.23667679488899934 and parameters: {'subsample': 0.13413701169148334, 'dropout_rate': 0.681320127237085, 'n_estimators': 274, 'learning_rate': 0.04811915704295519}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.261558344232367
Fold 2 IBS: 0.20136938024673648
Fold 3 IBS: 0.20076347945723086
Fold 4 IBS: 0.2757589317667252
Fold 5 IBS: 0.230988024951375
[I 2024-04-15 17:06:37,697] Trial 71 finished with value: 0.2340876321308869 and parameters: {'subsample': 0.18852832603688738, 'dropout_rate': 0.7256400945678027, 'n_estimators': 393, 'learning_rate': 0.02258733249904587}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.24545905345412034
Fold 2 IBS: 0.2165457278462933
Fold 3 IBS: 0.21380672113444776
Fold 4 IBS: 0.25131783359431437
Fold 5 IBS: 0.22473945982204405
[I 2024-04-15 17:06:41,311] Trial 72 finished with value: 0.230373759170244 and parameters: {'subsample': 0.16390700130403818, 'dropout_rate': 0.8734137373127314, 'n_estimators': 248, 'learning_rate': 0.014592344284561654}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2492334541791998
Fold 2 IBS: 0.20783312096139359
Fold 3 IBS: 0.20440891314283036
Fold 4 IBS: 0.26062575336576915
Fold 5 IBS: 0.224001125033001
[I 2024-04-15 17:06:44,365] Trial 73 finished with value: 0.22922047333643877 and parameters: {'subsample': 0.16300062710877586, 'dropout_rate': 0.8935147128616124, 'n_estimators': 238, 'learning_rate': 0.02571789888698594}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.250313578446336
Fold 2 IBS: 0.20848546668544385
Fold 3 IBS: 0.21891662316012855
Fold 4 IBS: 0.2605630119639453
Fold 5 IBS: 0.22390122217625122
[I 2024-04-15 17:06:47,209] Trial 74 finished with value: 0.23243598048642097 and parameters: {'subsample': 0.16804268285966187, 'dropout_rate': 0.9778293645723873, 'n_estimators': 236, 'learning_rate': 0.02502249046663426}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.25520458311662636
Fold 2 IBS: 0.1973961834567842
Fold 3 IBS: 0.20223307499335683
Fold 4 IBS: 0.26580498901428506
Fold 5 IBS: 0.22418511051732348
[I 2024-04-15 17:06:50,332] Trial 75 finished with value: 0.22896478821967517 and parameters: {'subsample': 0.12890106316734348, 'dropout_rate': 0.8757830980986167, 'n_estimators': 258, 'learning_rate': 0.034166703818280485}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.2518309984847892

Fold 2 IBS: 0.20129330865003595
Fold 3 IBS: 0.20362472919472707
Fold 4 IBS: 0.2626098142394568
Fold 5 IBS: 0.2234413565259519
[I 2024-04-15 17:06:52,878] Trial 76 finished with value: 0.22856004141899217 and parameters: {'subsample': 0.12716991111328405, 'dropout_rate': 0.8819176940152852, 'n_estimators': 221, 'learning_rate': 0.034294132126290275}. Best is trial 55 with value: 0.22815934505389251.
Fold 1 IBS: 0.24827865332853621
Fold 2 IBS: 0.2038933620779173
Fold 3 IBS: 0.19837888063049405
Fold 4 IBS: 0.26528696281097486
Fold 5 IBS: 0.21959816902304333
[I 2024-04-15 17:06:55,351] Trial 77 finished with value: 0.22708720557419318 and parameters: {'subsample': 0.10014056994120417, 'dropout_rate': 0.9142637089723192, 'n_estimators': 220, 'learning_rate': 0.03412951382964767}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2581570605057351
Fold 2 IBS: 0.2083035476250874
Fold 3 IBS: 0.21537598020680318
Fold 4 IBS: 0.2744742401793649
Fold 5 IBS: 0.22772230289799217
[I 2024-04-15 17:06:57,778] Trial 78 finished with value: 0.23680662628299656 and parameters: {'subsample': 0.2314920020716499, 'dropout_rate': 0.920524876830655, 'n_estimators': 221, 'learning_rate': 0.03423913410424081}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2516942979679773
Fold 2 IBS: 0.20256113546833582
Fold 3 IBS: 0.19656632559640114
Fold 4 IBS: 0.26238874441697996
Fold 5 IBS: 0.2233395835199357
[I 2024-04-15 17:06:59,875] Trial 79 finished with value: 0.22731001739392598 and parameters: {'subsample': 0.13011224811178443, 'dropout_rate': 0.9611136103278767, 'n_estimators': 192, 'learning_rate': 0.03990154521917111}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.25096374177619973
Fold 2 IBS: 0.20390859629193983
Fold 3 IBS: 0.20748789188553726
Fold 4 IBS: 0.26352185507824877
Fold 5 IBS: 0.22266115131009842
[I 2024-04-15 17:07:01,692] Trial 80 finished with value: 0.22970864726840481 and parameters: {'subsample': 0.14120172981504953, 'dropout_rate': 0.9617724254267231, 'n_estimators': 170, 'learning_rate': 0.040014005291058266}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2529824763113105
Fold 2 IBS: 0.20150575535752527
Fold 3 IBS: 0.19500209604098528
Fold 4 IBS: 0.2645637390568673
Fold 5 IBS: 0.22370604225656404
[I 2024-04-15 17:07:03,718] Trial 81 finished with value: 0.22755202180465045 and parameters: {'subsample': 0.13370443015825967, 'dropout_rate': 0.9631532852458881, 'n_estimators': 191, 'learning_rate': 0.04270886786892768}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2514598334438908
Fold 2 IBS: 0.20388962517512024
Fold 3 IBS: 0.20073311145846448
Fold 4 IBS: 0.26704336412314145
Fold 5 IBS: 0.2221760162133305
[I 2024-04-15 17:07:05,788] Trial 82 finished with value: 0.2290603900827895 and parameters: {'subsample': 0.12305483524027712, 'dropout_rate': 0.9867434081911146, 'n_estimators': 189, 'learning_rate': 0.04230581283148195}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2518105912205101
Fold 2 IBS: 0.2037703115019244
Fold 3 IBS: 0.20037216427943172
Fold 4 IBS: 0.2672039853772332
Fold 5 IBS: 0.22216979380321192
[I 2024-04-15 17:07:07,907] Trial 83 finished with value: 0.22906536923646229 and parameters: {'subsample': 0.1213435985969141, 'dropout_rate': 0.9724151608553365, 'n_estimators': 190, 'learning_rate': 0.042499897110325265}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.25071818551685754
Fold 2 IBS: 0.20357663376868354
Fold 3 IBS: 0.19772364464048245
Fold 4 IBS: 0.26101678893669755
Fold 5 IBS: 0.22317975497415476
[I 2024-04-15 17:07:09,983] Trial 84 finished with value: 0.22724300156737515 and parameters: {'subsample': 0.12757029918279186, 'dropout_rate': 0.9965719639669659, 'n_estimators': 192, 'learning_rate': 0.0378842541149074}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.24970628011170573
Fold 2 IBS: 0.2032004876623891
Fold 3 IBS: 0.2011841480049807
Fold 4 IBS: 0.26828348357115245
Fold 5 IBS: 0.21939171390495577
[I 2024-04-15 17:07:12,474] Trial 85 finished with value: 0.22835322265103675 and parameters: {'subsample': 0.10335682651567442, 'dropout_rate': 0.9294297710760699, 'n_estimators': 212, 'learning_rate': 0.037182953108740646}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.24529492371060183
Fold 2 IBS: 0.20998269576458384
Fold 3 IBS: 0.20498081564255446
Fold 4 IBS: 0.25658396101571235
Fold 5 IBS: 0.2230978143287238
[I 2024-04-15 17:07:14,089] Trial 86 finished with value: 0.22798804209243526 and parameters: {'subsample': 0.10945143529278945, 'dropout_rate': 0.9466587881139311, 'n_estimators': 159, 'learning_rate': 0.03686596574318843}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.24887729557205907
Fold 2 IBS: 0.20233280393738742
Fold 3 IBS: 0.20439750888205702
Fold 4 IBS: 0.270836044935482
Fold 5 IBS: 0.21995225543062466
[I 2024-04-15 17:07:15,857] Trial 87 finished with value: 0.229279181751522 and parameters: {'subsample': 0.1011626954666495, 'dropout_rate': 0.9416922157268935, 'n_estimators': 161, 'learning_rate': 0.04965837299117283}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2526456733877812
Fold 2 IBS: 0.21925916494092057
Fold 3 IBS: 0.23087542435862982
Fold 4 IBS: 0.2693842874587484
Fold 5 IBS: 0.23426079819192414
[I 2024-04-15 17:07:17,169] Trial 88 finished with value: 0.24128506966760083 and parameters: {'subsample': 0.961201962500049, 'dropout_rate': 0.9971334272790294, 'n_estimators': 138, 'learning_rate': 0.037746208726550594}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.271661768027955
Fold 2 IBS: 0.2307966465038689
Fold 3 IBS: 0.22288436204967252
Fold 4 IBS: 0.310518077747559
Fold 5 IBS: 0.2590496158499074
[I 2024-04-15 17:07:19,369] Trial 89 finished with value: 0.2589820940357926 and parameters: {'subsample': 0.5132290304538794, 'dropout_rate': 0.9353341345185033, 'n_estimators': 213, 'learning_rate': 0.04618091995284568}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.24660400429519047
Fold 2 IBS: 0.21050333705315233
Fold 3 IBS: 0.20935458595236908
Fold 4 IBS: 0.2545288995631308
Fold 5 IBS: 0.22520013826571894
[I 2024-04-15 17:07:21,448] Trial 90 finished with value: 0.22923819302591233 and parameters: {'subsample': 0.14911735772012988, 'dropout_rate': 0.10184332440552968, 'n_estimators': 159, 'learning_rate': 0.028548360631165136}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2453219712530965
Fold 2 IBS: 0.2153374516180863
Fold 3 IBS: 0.20892133774723134
Fold 4 IBS: 0.2508759224560941
Fold 5 IBS: 0.22418935769632123
[I 2024-04-15 17:07:22,721] Trial 91 finished with value: 0.2289292081541659 and parameters: {'subsample': 0.11791491337787216, 'dropout_rate': 0.9561669334466318, 'n_estimators': 128, 'learning_rate': 0.036718786269543446}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2453273778364188
Fold 2 IBS: 0.21496122114183264
Fold 3 IBS: 0.20860803717580068
Fold 4 IBS: 0.25092771009782133
Fold 5 IBS: 0.2244562280451655
[I 2024-04-15 17:07:23,953] Trial 92 finished with value: 0.2288561148594078 and parameters: {'subsample': 0.12564165577850628, 'dropout_rate': 0.9572892308244014, 'n_estimators': 127, 'learning_rate': 0.03734473020516682}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.24634299682089944
Fold 2 IBS: 0.20799011654168323
Fold 3 IBS: 0.20862374622266772
Fold 4 IBS: 0.2623081051206873
Fold 5 IBS: 0.22037789638667213
[I 2024-04-15 17:07:26,183] Trial 93 finished with value: 0.22912857221852195 and parameters: {'subsample': 0.10158287018419104, 'dropout_rate': 0.9194769573112632, 'n_estimators': 199, 'learning_rate': 0.03121985132051676}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.25506647033771396
Fold 2 IBS: 0.2050039627785591
Fold 3 IBS: 0.20533176286980656
Fold 4 IBS: 0.26788418911492
Fold 5 IBS: 0.22783581126411856
[I 2024-04-15 17:07:28,301] Trial 94 finished with value: 0.23222443927302364 and parameters: {'subsample': 0.19300821618034103, 'dropout_rate': 0.974114337525115, 'n_estimators': 194, 'learning_rate': 0.04001656596013403}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.26249902924898455

Fold 2 IBS: 0.20016155565967836
Fold 3 IBS: 0.20218202531884416
Fold 4 IBS: 0.275671025771449
Fold 5 IBS: 0.22901703205885907
[I 2024-04-15 17:07:30,793] Trial 95 finished with value: 0.23390613361156304 and parameters: {'subsample': 0.15168078965598952, 'dropout_rate': 0.9535660044358101, 'n_estimators': 218, 'learning_rate': 0.04493719007093705}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2514998144114763
Fold 2 IBS: 0.20245881264210183
Fold 3 IBS: 0.1961952401625281
Fold 4 IBS: 0.26267543656746617
Fold 5 IBS: 0.2232416912945307
[I 2024-04-15 17:07:32,653] Trial 96 finished with value: 0.22721419901562062 and parameters: {'subsample': 0.13212499627568827, 'dropout_rate': 0.9975956966964254, 'n_estimators': 180, 'learning_rate': 0.042065011804907855}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.25603551368208766
Fold 2 IBS: 0.19900110185711675
Fold 3 IBS: 0.19314049792382357
Fold 4 IBS: 0.2681421752303816
Fold 5 IBS: 0.224723580690284
[I 2024-04-15 17:07:34,540] Trial 97 finished with value: 0.2282085738767387 and parameters: {'subsample': 0.12882301436539273, 'dropout_rate': 0.991251816958071, 'n_estimators': 175, 'learning_rate': 0.05277325841632065}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2535478733730904
Fold 2 IBS: 0.20210681419912976
Fold 3 IBS: 0.2019732399243851
Fold 4 IBS: 0.2650949748138141
Fold 5 IBS: 0.22517937649206524
[I 2024-04-15 17:07:36,008] Trial 98 finished with value: 0.22958045576049693 and parameters: {'subsample': 0.14989318573726598, 'dropout_rate': 0.9971585849466167, 'n_estimators': 147, 'learning_rate': 0.05347933041975234}. Best is trial 77 with value: 0.22708720557419318.
Fold 1 IBS: 0.2638109951818618
Fold 2 IBS: 0.2067304208100919
Fold 3 IBS: 0.21340780755606326
Fold 4 IBS: 0.28271897811949165
Fold 5 IBS: 0.23211085545061055
[I 2024-04-15 17:07:37,921] Trial 99 finished with value: 0.23975581142362384 and parameters: {'subsample': 0.22763346770981624, 'dropout_rate': 0.9337822786370614, 'n_estimators': 176, 'learning_rate': 0.052443959168945425}. Best is trial 77 with value: 0.22708720557419318.


* Best trial for IBS:
 FrozenTrial(number=77, state=TrialState.COMPLETE, values=[0.22708720557419318], datetime_start=datetime.datetime(2024, 4, 15, 17, 6, 52, 884151), datetime_complete=datetime.datetime(2024, 4, 15, 17, 6, 55, 351163), params={'subsample': 0.10014056994120417, 'dropout_rate': 0.9142637089723192, 'n_estimators': 220, 'learning_rate': 0.03412951382964767}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=77, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10014056994120417, 'dropout_rate': 0.9142637089723192, 'n_estimators': 220, 'learning_rate': 0.03412951382964767}


* Best Score for IBS:
 0.22708720557419318

In [158]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [159]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.647
train_ibs:  0.227

#### Test

In [160]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [161]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8053356883307206,
                                              learning_rate=0.0546539002707277,
                                              n_estimators=22, random_state=123,
                                              subsample=0.10051745578141419)

C-index score: 0.559

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9142637089723192,
                                              learning_rate=0.03412951382964767,
                                              n_estimators=220,
                                              random_state=123,
                                              subsample=0.10014056994120417)

IBS: 0.227

In [162]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [163]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.845   1.0
ExtraSurvivalTrees               0.837   2.0
GradientBoosting                 0.711   3.0
CoxElastic                       0.705   4.0
CoxPH                            0.703   5.0
CoxLasso                         0.701   6.0
ComponentwiseGradientBoosting    0.647   7.0
CoxRidge                         0.632   8.0

In [164]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxPH                          0.199   2.0
CoxLasso                       0.199   2.0
CoxElastic                     0.199   2.0
Randomsurvivalforest           0.205   4.0
ExtraSurvivalTrees             0.207   5.0
ComponentwiseGradientBoosting  0.227   6.0
GradientBoosting               0.234   7.0
CoxRidge                       0.236   8.0

In [165]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.559   1.0
CoxRidge                         0.531   2.0
CoxPH                            0.528   4.0
CoxLasso                         0.528   4.0
CoxElastic                       0.528   4.0
Randomsurvivalforest             0.521   6.0
GradientBoosting                 0.517   7.0
ExtraSurvivalTrees               0.509   8.0

In [166]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.227   1.0
CoxRidge                       0.229   2.5
GradientBoosting               0.229   2.5
Randomsurvivalforest           0.248   4.0
ExtraSurvivalTrees             0.259   5.0
CoxLasso                       0.308   6.5
CoxElastic                     0.308   6.5
CoxPH                          0.309   8.0

In [169]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/minmax/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_minmax_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [170]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-15