In [1]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [14]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [17]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [18]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [19]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.828413,0.487448,0.350904,0.000000
1,0.645006,0.388474,0.123069,0.000000
2,0.269537,0.513756,0.428640,0.066875
3,0.608721,0.273786,0.135806,0.000000
4,0.090323,0.792905,0.254489,0.386334
...,...,...,...,...
134,0.773882,0.425425,0.233413,0.000000
135,0.719008,0.796326,0.337469,0.000000
136,0.518897,0.336186,0.279727,0.000000
137,0.722831,0.825142,0.400455,0.000000
138,0.718191,0.719948,0.198096,0.000000

In [20]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [21]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.562115,0.636436,0.454371,0.050863
1,0.567520,0.084927,0.346729,0.324583
2,0.436277,0.314068,0.380947,0.110937
3,0.303383,0.235395,0.403660,0.000000
4,0.455879,0.443841,0.511695,0.000000
...,...,...,...,...
94,0.572648,0.525159,0.248406,0.000000
95,0.459472,0.292451,0.468005,0.000000
96,0.497683,0.139149,0.459798,0.000000
97,0.732079,0.366955,0.387810,0.000000
98,0.575748,0.262347,0.279146,0.000000

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [22]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:17:34,098] A new study created in memory with name: no-name-3175c5c7-c5a5-40ed-a2b0-bebc277cccce

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734

[I 2024-04-15 14:17:50,421] A new study created in memory with name: no-name-aaa320ef-24a0-4ff5-9286-87c68c1fd205

Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:17:50,402] Trial 0 finished with value: 0.7358264523738474 and parameters: {}. Best is trial 0 with value: 0.7358264523738474.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7358264523738474], datetime_start=datetime.datetime(2024, 4, 15, 14, 17, 34, 564424), datetime_complete=datetime.datetime(2024, 4, 15, 14, 17, 50, 401184), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7358264523738474

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.17932951816141288
Fold 2 IBS: 0.15173912855888322
Fold 3 IBS: 0.17662964771229905
Fold 4 IBS: 0.15303709600503954
Fold 5 IBS: 0.19681553106978886
[I 2024-04-15 14:17:51,576] Trial 0 finished with value: 0.17151018430148474 and parameters: {}. Best is trial 0 with value: 0.17151018430148474.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17151018430148474], datetime_start=datetime.datetime(2024, 4, 15, 14, 17, 50, 456858), datetime_complete=datetime.datetime(2024, 4, 15, 14, 17, 51, 575091), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17151018430148474

In [23]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [24]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.172

#### Test

In [25]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [26]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.567
IBS score: 0.259

In [27]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [28]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [29]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:17:52,217] A new study created in memory with name: no-name-73cb4d2d-81c5-45ac-9ff5-27d5aa11b00b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7130801687763713

[I 2024-04-15 14:17:52,654] A new study created in memory with name: no-name-81626e37-6f22-4534-be33-75166cebf5d3

Fold 5 C-index: 0.7394366197183099
[I 2024-04-15 14:17:52,645] Trial 0 finished with value: 0.7215233793439578 and parameters: {}. Best is trial 0 with value: 0.7215233793439578.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7215233793439578], datetime_start=datetime.datetime(2024, 4, 15, 14, 17, 52, 310531), datetime_complete=datetime.datetime(2024, 4, 15, 14, 17, 52, 642988), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7215233793439578

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652066529
Fold 2 IBS: 0.22157791508266436
Fold 3 IBS: 0.20453594548791937
Fold 4 IBS: 0.2247380394966658
Fold 5 IBS: 0.21812431321836134
[I 2024-04-15 14:17:53,153] Trial 0 finished with value: 0.21659054679018022 and parameters: {}. Best is trial 0 with value: 0.21659054679018022.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054679018022], datetime_start=datetime.datetime(2024, 4, 15, 14, 17, 52, 713904), datetime_complete=datetime.datetime(2024, 4, 15, 14, 17, 53, 153135), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054679018022

In [30]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.722
train_ibs:  0.217

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.565

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:17:53,580] A new study created in memory with name: no-name-0672198d-bb1d-4887-9ff6-d81adbb8b5c8

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961

[I 2024-04-15 14:17:54,827] A new study created in memory with name: no-name-e495d8c5-6698-42d4-985b-0203c88fd869

Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:17:54,785] Trial 0 finished with value: 0.7357337800920462 and parameters: {}. Best is trial 0 with value: 0.7357337800920462.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7357337800920462], datetime_start=datetime.datetime(2024, 4, 15, 14, 17, 53, 842285), datetime_complete=datetime.datetime(2024, 4, 15, 14, 17, 54, 785355), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7357337800920462

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.17978486969064494
Fold 2 IBS: 0.15091426109195713
Fold 3 IBS: 0.17579948353248076
Fold 4 IBS: 0.15359370021287927
Fold 5 IBS: 0.19563635363486537
[I 2024-04-15 14:17:55,858] Trial 0 finished with value: 0.17114573363256547 and parameters: {}. Best is trial 0 with value: 0.17114573363256547.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17114573363256547], datetime_start=datetime.datetime(2024, 4, 15, 14, 17, 54, 931933), datetime_complete=datetime.datetime(2024, 4, 15, 14, 17, 55, 855428), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17114573363256547

In [36]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.171

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.257

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:17:57,077] A new study created in memory with name: no-name-5e28e438-45d3-494a-ba9b-5771ac6c7556

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:17:58,885] Trial 0 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:00,526] Trial 1 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:02,152] Trial 2 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:03,396] Trial 3 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:04,383] Trial 4 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:05,545] Trial 5 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:06,918] Trial 6 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:08,622] Trial 7 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:10,125] Trial 8 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:11,919] Trial 9 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:13,436] Trial 10 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7367141722489089.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:14,700] Trial 11 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:16,263] Trial 12 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.7247092940361127}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:17,294] Trial 13 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8333864003872741}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:18,318] Trial 14 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8660862471290933}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-15 14:18:18,668] Trial 15 finished with value: 0.7220539092879896 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:19,591] Trial 16 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8390796519651111}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:20,558] Trial 17 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6035699700874588}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:21,498] Trial 18 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:22,455] Trial 19 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.9243748204828461}. Best is trial 11 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:23,580] Trial 20 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6127580877814559}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:24,951] Trial 21 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6165131932877641}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:26,039] Trial 22 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.5942594027410317}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:27,138] Trial 23 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6499003388704403}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125

Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:28,085] Trial 24 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.4980983035246007}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:28,957] Trial 25 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.7784745121749661}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:29,839] Trial 26 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:30,803] Trial 27 finished with value: 0.7367412285259652 and parameters: {'l1_ratio': 0.5595065419317113}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:31,599] Trial 28 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.7482317310914901}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:32,529] Trial 29 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6476942936298222}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:33,511] Trial 30 finished with value: 0.7316289621004077 and parameters: {'l1_ratio': 0.10244326369707601}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:34,893] Trial 31 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.8871221013224053}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:35,959] Trial 32 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8058899652138217}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:36,831] Trial 33 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6505921241203195}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:38,043] Trial 34 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.9183122694964778}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:39,240] Trial 35 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.5405357611753291}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:40,337] Trial 36 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.7241768963887948}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:41,703] Trial 37 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:42,596] Trial 38 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6728095274336536}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:43,611] Trial 39 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.7802308333130804}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:44,847] Trial 40 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6052040729810806}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:45,978] Trial 41 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6310213577672552}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:47,151] Trial 42 finished with value: 0.7367412285259652 and parameters: {'l1_ratio': 0.5575687174353907}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:48,212] Trial 43 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6984559933743164}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:49,430] Trial 44 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.43097251053392843}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:51,062] Trial 45 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.5223501370467667}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:52,115] Trial 46 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.5800567853666072}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:53,046] Trial 47 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8464782493835346}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173

Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:53,882] Trial 48 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.7406555774839976}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:55,206] Trial 49 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.37275461898476625}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:56,438] Trial 50 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.2311229033161103}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:57,804] Trial 51 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8706168012856845}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:58,639] Trial 52 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.9613802438107986}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:18:59,507] Trial 53 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8178549501191649}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:00,530] Trial 54 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.7688864417731469}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:01,686] Trial 55 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6064547390893693}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:02,613] Trial 56 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6006626104143585}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:03,406] Trial 57 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6791735258875246}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:04,269] Trial 58 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.4897423110737053}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:05,109] Trial 59 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.595903648069982}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:05,920] Trial 60 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.7056326782501279}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:06,924] Trial 61 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6313041468138058}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:07,730] Trial 62 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.904269476955136}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:08,736] Trial 63 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.5228038846620794}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:09,685] Trial 64 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8597196804752802}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:10,694] Trial 65 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.968152439117005}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:11,988] Trial 66 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.8062114433781463}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:12,885] Trial 67 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.9415445204645163}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:13,793] Trial 68 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.7593096812987605}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:14,532] Trial 69 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.655234928062169}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:15,241] Trial 70 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6190167670320361}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:16,107] Trial 71 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6107409928174975}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:16,950] Trial 72 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6176204492943045}. Best is trial 20 with value: 0.7376070293917663.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:17,730] Trial 73 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6238439878566394}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:18,530] Trial 74 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6160629002141824}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:19,249] Trial 75 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.5711185957176977}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:20,107] Trial 76 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.5499771358255129}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:20,852] Trial 77 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6193124042393106}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:21,612] Trial 78 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6735357991949137}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:22,542] Trial 79 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.4668869341924287}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:23,371] Trial 80 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.525436624655741}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:24,161] Trial 81 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6120661596941436}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:24,933] Trial 82 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6333396563700718}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:25,805] Trial 83 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.5787293659078497}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:26,583] Trial 84 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6716189083032378}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:27,402] Trial 85 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.5869234565605262}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:28,218] Trial 86 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.7153877529764424}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:29,183] Trial 87 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.5123011409413758}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:30,001] Trial 88 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.5476850216276596}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:30,723] Trial 89 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6487152215453645}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:31,402] Trial 90 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6961217905048874}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:32,292] Trial 91 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6134901111828666}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:33,550] Trial 92 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6181680263477138}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:34,924] Trial 93 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6326971596579269}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:35,892] Trial 94 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.5674362247380961}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:36,976] Trial 95 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6578282111940101}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:37,880] Trial 96 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.5968025250618899}. Best is trial 20 with value: 0.7376070293917663.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:38,695] Trial 97 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.7300251643415032}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:39,501] Trial 98 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.6863332623854053}. Best is trial 20 with value: 0.7376070293917663.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 14:19:40,172] Trial 99 finished with value: 0.7376070293917663 and parameters: {'l1_ratio': 0.6258864424687237}. Best is trial 20 with value: 0.7376070293917663.

[I 2024-04-15 14:19:40,231] A new study created in memory with name: no-name-0820df18-06a6-481e-9cad-542d2082f9fc

* Best trial for C-index:
 FrozenTrial(number=20, state=TrialState.COMPLETE, values=[0.7376070293917663], datetime_start=datetime.datetime(2024, 4, 15, 14, 18, 22, 481026), datetime_complete=datetime.datetime(2024, 4, 15, 14, 18, 23, 579805), params={'l1_ratio': 0.6127580877814559}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=20, value=None)


* Best Score for C-index:
 0.7376070293917663

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17939857143571256
Fold 2 IBS: 0.15109163708960624
Fold 3 IBS: 0.1763396348009305
Fold 4 IBS: 0.1537043254337406
Fold 5 IBS: 0.1956773341873156
[I 2024-04-15 14:19:41,053] Trial 0 finished with value: 0.17124230058946108 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.17124230058946108.
Fold 1 IBS: 0.1789996220483504
Fold 2 IBS: 0.1512509959799121
Fold 3 IBS: 0.17676137368432185
Fold 4 IBS: 0.15380226909628456
Fold 5 IBS: 0.1958162328928413
[I 2024-04-15 14:19:41,966] Trial 1 finished with value: 0.17132609874034205 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.17124230058946108.
Fold 1 IBS: 0.17896259000470527
Fold 2 IBS: 0.15127585271929875
Fold 3 IBS: 0.17680557714583164
Fold 4 IBS: 0.1538303954940592
Fold 5 IBS: 0.19574833931247274
[I 2024-04-15 14:19:42,993] Trial 2 finished with value: 0.17132455093527352 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.17124230058946108.
Fold 1 IBS: 0.17923532929144262
Fold 2 IBS: 0.15118361587954374
Fold 3 IBS: 0.17650617122859166
Fold 4 IBS: 0.15378785443397044
Fold 5 IBS: 0.1957512126627454
[I 2024-04-15 14:19:43,837] Trial 3 finished with value: 0.1712928366992588 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.17124230058946108.
Fold 1 IBS: 0.17942234520959252
Fold 2 IBS: 0.1511078391641422
Fold 3 IBS: 0.1762949735838248
Fold 4 IBS: 0.1537170259000063
Fold 5 IBS: 0.1957247556443146
[I 2024-04-15 14:19:44,606] Trial 4 finished with value: 0.1712533879003761 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.17124230058946108.
Fold 1 IBS: 0.17910953350265157
Fold 2 IBS: 0.15120407761832688
Fold 3 IBS: 0.1766407798971487
Fold 4 IBS: 0.15380467917280014
Fold 5 IBS: 0.19570777189268987
[I 2024-04-15 14:19:45,432] Trial 5 finished with value: 0.17129336841672343 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.17124230058946108.
Fold 1 IBS: 0.17976799194016657
Fold 2 IBS: 0.1509727862312897
Fold 3 IBS: 0.17588285557789157
Fold 4 IBS: 0.15358590071523037
Fold 5 IBS: 0.19570749533824713
[I 2024-04-15 14:19:46,296] Trial 6 finished with value: 0.17118340596056508 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.17118340596056508.
Fold 1 IBS: 0.1793782233933579
Fold 2 IBS: 0.15108316001778907
Fold 3 IBS: 0.1763479789752799
Fold 4 IBS: 0.15372205442723397
Fold 5 IBS: 0.1957525310480944
[I 2024-04-15 14:19:47,137] Trial 7 finished with value: 0.17125678957235105 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.17118340596056508.
Fold 1 IBS: 0.17915890529705858
Fold 2 IBS: 0.1511694585164992
Fold 3 IBS: 0.1765830605084235
Fold 4 IBS: 0.1537551351772123
Fold 5 IBS: 0.19576899895714983
[I 2024-04-15 14:19:47,847] Trial 8 finished with value: 0.1712871116912687 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.17118340596056508.
Fold 1 IBS: 0.1790829328582217
Fold 2 IBS: 0.15121521918167524
Fold 3 IBS: 0.17666965582500757
Fold 4 IBS: 0.15381410650846802
Fold 5 IBS: 0.19571160249460395
[I 2024-04-15 14:19:48,532] Trial 9 finished with value: 0.1712987033735953 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.17118340596056508.
Fold 1 IBS: 0.17977116700212412
Fold 2 IBS: 0.1509749389545041
Fold 3 IBS: 0.17588059543563786
Fold 4 IBS: 0.1536116514600708
Fold 5 IBS: 0.19571375865403084
[I 2024-04-15 14:19:49,128] Trial 10 finished with value: 0.17119042230127354 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.17118340596056508.
Fold 1 IBS: 0.1797824659190772
Fold 2 IBS: 0.15091253161009172
Fold 3 IBS: 0.17580134109250053
Fold 4 IBS: 0.15359808870537262
Fold 5 IBS: 0.19563123383797468
[I 2024-04-15 14:19:49,742] Trial 11 finished with value: 0.17114513223300334 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17978037500741656
Fold 2 IBS: 0.15098115505768414
Fold 3 IBS: 0.17580295863745007
Fold 4 IBS: 0.1536019091294718
Fold 5 IBS: 0.195626777840099
[I 2024-04-15 14:19:50,338] Trial 12 finished with value: 0.1711586351344243 and parameters: {'l1_ratio': 0.9948264745658929}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.21356639806700448
Fold 2 IBS: 0.22090652915897313
Fold 3 IBS: 0.203952748153347
Fold 4 IBS: 0.2241309114591571
Fold 5 IBS: 0.2174749207286243
[I 2024-04-15 14:19:50,574] Trial 13 finished with value: 0.2160063015134212 and parameters: {'l1_ratio': 0.03152521162798527}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1796454787071554
Fold 2 IBS: 0.1509821652086734
Fold 3 IBS: 0.17600555426822623
Fold 4 IBS: 0.15364378255708938
Fold 5 IBS: 0.19564366370069872
[I 2024-04-15 14:19:51,144] Trial 14 finished with value: 0.17118412888836862 and parameters: {'l1_ratio': 0.8887005110166508}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17957399201016241
Fold 2 IBS: 0.15101686100910844
Fold 3 IBS: 0.17608954573772995
Fold 4 IBS: 0.1536681550994458
Fold 5 IBS: 0.19566286956445614
[I 2024-04-15 14:19:51,755] Trial 15 finished with value: 0.17120228468418056 and parameters: {'l1_ratio': 0.8435258665171791}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17953610996508954
Fold 2 IBS: 0.15105213977317003
Fold 3 IBS: 0.17616220788633255
Fold 4 IBS: 0.1536816086240593
Fold 5 IBS: 0.19569139229683769
[I 2024-04-15 14:19:52,424] Trial 16 finished with value: 0.17122469170909782 and parameters: {'l1_ratio': 0.8046771700892117}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17977205759600381
Fold 2 IBS: 0.15097553973279104
Fold 3 IBS: 0.17587996553074786
Fold 4 IBS: 0.1536100332166716
Fold 5 IBS: 0.19571550497147885
[I 2024-04-15 14:19:53,008] Trial 17 finished with value: 0.17119062020953862 and parameters: {'l1_ratio': 0.9853615392538034}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17950350686105312
Fold 2 IBS: 0.1510438699391902
Fold 3 IBS: 0.17617104628274105
Fold 4 IBS: 0.15370030561060105
Fold 5 IBS: 0.1956670924812682
[I 2024-04-15 14:19:53,604] Trial 18 finished with value: 0.17121716423497074 and parameters: {'l1_ratio': 0.7922918930288001}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17929358605733065
Fold 2 IBS: 0.15113139757623997
Fold 3 IBS: 0.17644662930232294
Fold 4 IBS: 0.15374367770881345
Fold 5 IBS: 0.1956880641945906
[I 2024-04-15 14:19:54,227] Trial 19 finished with value: 0.17126067096785952 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.179638938325806
Fold 2 IBS: 0.15097772381850752
Fold 3 IBS: 0.1760637348052146
Fold 4 IBS: 0.15365398427738622
Fold 5 IBS: 0.19573425858399326
[I 2024-04-15 14:19:54,815] Trial 20 finished with value: 0.17121372796218154 and parameters: {'l1_ratio': 0.8818811135844746}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17975214019825822
Fold 2 IBS: 0.1509621135448001
Fold 3 IBS: 0.17589413203656906
Fold 4 IBS: 0.1536124552142339
Fold 5 IBS: 0.19567630637102634
[I 2024-04-15 14:19:55,355] Trial 21 finished with value: 0.1711794294729775 and parameters: {'l1_ratio': 0.9632315494528705}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17966814317197582
Fold 2 IBS: 0.15099766345206042
Fold 3 IBS: 0.1759890184990741
Fold 4 IBS: 0.15364897280484383
Fold 5 IBS: 0.19568939801304652
[I 2024-04-15 14:19:55,990] Trial 22 finished with value: 0.17119863918820014 and parameters: {'l1_ratio': 0.9130757617488995}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17977437594535312
Fold 2 IBS: 0.15097710409289483
Fold 3 IBS: 0.17580760854051117
Fold 4 IBS: 0.15360582322185695
Fold 5 IBS: 0.19572004885188943
[I 2024-04-15 14:19:56,607] Trial 23 finished with value: 0.1711769921305011 and parameters: {'l1_ratio': 0.9879856951002318}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1794973255673741
Fold 2 IBS: 0.15103950868513769
Fold 3 IBS: 0.17621492053595764
Fold 4 IBS: 0.1537102210906867
Fold 5 IBS: 0.19565421958904183
[I 2024-04-15 14:19:57,314] Trial 24 finished with value: 0.1712232390936396 and parameters: {'l1_ratio': 0.7858694646230915}. Best is trial 11 with value: 0.17114513223300334.

Fold 1 IBS: 0.17965742075121308
Fold 2 IBS: 0.15099032513038543
Fold 3 IBS: 0.17599680129377795
Fold 4 IBS: 0.15366012000797843
Fold 5 IBS: 0.1956677392109295
[I 2024-04-15 14:19:57,989] Trial 25 finished with value: 0.1711944812788569 and parameters: {'l1_ratio': 0.901420099010056}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1794389650554732
Fold 2 IBS: 0.15106763780110619
Fold 3 IBS: 0.1762793396084056
Fold 4 IBS: 0.15373105430206635
Fold 5 IBS: 0.19566872499552762
[I 2024-04-15 14:19:58,615] Trial 26 finished with value: 0.1712371443525158 and parameters: {'l1_ratio': 0.7417169602645222}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1793411272124821
Fold 2 IBS: 0.1511109403370602
Fold 3 IBS: 0.1763970994799986
Fold 4 IBS: 0.15372820534565287
Fold 5 IBS: 0.19567773958708665
[I 2024-04-15 14:19:59,245] Trial 27 finished with value: 0.1712510223924561 and parameters: {'l1_ratio': 0.6494728799686162}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17957119212531575
Fold 2 IBS: 0.15101491552786717
Fold 3 IBS: 0.17609163450128715
Fold 4 IBS: 0.15367258506833778
Fold 5 IBS: 0.19565713070132548
[I 2024-04-15 14:19:59,842] Trial 28 finished with value: 0.17120149158482667 and parameters: {'l1_ratio': 0.8405678753809458}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.21376714179654435
Fold 2 IBS: 0.2212354021231866
Fold 3 IBS: 0.20423805053003097
Fold 4 IBS: 0.22442845152658839
Fold 5 IBS: 0.21779278476281916
[I 2024-04-15 14:20:00,140] Trial 29 finished with value: 0.2162923661478339 and parameters: {'l1_ratio': 0.016175696683504215}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17967421303603448
Fold 2 IBS: 0.15100182253969202
Fold 3 IBS: 0.1759846125598597
Fold 4 IBS: 0.15363864928921325
Fold 5 IBS: 0.1957015639519673
[I 2024-04-15 14:20:00,730] Trial 30 finished with value: 0.17120017227535334 and parameters: {'l1_ratio': 0.9197818493705627}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17977305201453142
Fold 2 IBS: 0.1509762106613804
Fold 3 IBS: 0.17587926251220984
Fold 4 IBS: 0.1536082269587509
Fold 5 IBS: 0.19571745435770663
[I 2024-04-15 14:20:01,329] Trial 31 finished with value: 0.17119084130091583 and parameters: {'l1_ratio': 0.9864858075876226}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17968384400140294
Fold 2 IBS: 0.15100843764017938
Fold 3 IBS: 0.1759776487354667
Fold 4 IBS: 0.15362232414726734
Fold 5 IBS: 0.19572082359489093
[I 2024-04-15 14:20:01,885] Trial 32 finished with value: 0.17120261562384148 and parameters: {'l1_ratio': 0.930580777401446}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1797832630042389
Fold 2 IBS: 0.15091310498410396
Fold 3 IBS: 0.1758007248922528
Fold 4 IBS: 0.15359663306785323
Fold 5 IBS: 0.19563293189975783
[I 2024-04-15 14:20:02,477] Trial 33 finished with value: 0.17114533156964135 and parameters: {'l1_ratio': 0.9981458715067252}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1789176760300347
Fold 2 IBS: 0.15128156433472564
Fold 3 IBS: 0.1768322523799303
Fold 4 IBS: 0.15388643987607645
Fold 5 IBS: 0.19581874765856352
[I 2024-04-15 14:20:03,280] Trial 34 finished with value: 0.1713473360558661 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17956698184161216
Fold 2 IBS: 0.1510119920476166
Fold 3 IBS: 0.17609478103206938
Fold 4 IBS: 0.1536792564045023
Fold 5 IBS: 0.19564849185920732
[I 2024-04-15 14:20:03,960] Trial 35 finished with value: 0.17120030063700153 and parameters: {'l1_ratio': 0.8361501509216206}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1797844565878395
Fold 2 IBS: 0.1509139637940836
Fold 3 IBS: 0.1757998026129921
Fold 4 IBS: 0.15359445413029638
Fold 5 IBS: 0.19563547399046252
[I 2024-04-15 14:20:04,594] Trial 36 finished with value: 0.17114563022313484 and parameters: {'l1_ratio': 0.9995227662750971}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17943459062900852
Fold 2 IBS: 0.15106450818067335
Fold 3 IBS: 0.17628240748108523
Fold 4 IBS: 0.15369030924282767
Fold 5 IBS: 0.1956594886144216
[I 2024-04-15 14:20:05,128] Trial 37 finished with value: 0.1712262608296033 and parameters: {'l1_ratio': 0.7372592669124193}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17959150838327761
Fold 2 IBS: 0.1510290356291885
Fold 3 IBS: 0.1760765947917184
Fold 4 IBS: 0.15364060133354737
Fold 5 IBS: 0.19569873099683313
[I 2024-04-15 14:20:05,710] Trial 38 finished with value: 0.171207294226913 and parameters: {'l1_ratio': 0.86237399701415}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17903424918990293
Fold 2 IBS: 0.15123257110378857
Fold 3 IBS: 0.1767218958517158
Fold 4 IBS: 0.15378538435897146
Fold 5 IBS: 0.19580489192372577
[I 2024-04-15 14:20:06,501] Trial 39 finished with value: 0.1713157984856209 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17973234709199348
Fold 2 IBS: 0.1509488354298223
Fold 3 IBS: 0.17590830679261824
Fold 4 IBS: 0.15363870031246712
Fold 5 IBS: 0.1956370373628008
[I 2024-04-15 14:20:07,074] Trial 40 finished with value: 0.17117304539794037 and parameters: {'l1_ratio': 0.9420040489102279}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17973547933246792
Fold 2 IBS: 0.15095093400058393
Fold 3 IBS: 0.17590605008829052
Fold 4 IBS: 0.15363344808504292
Fold 5 IBS: 0.19564324678114814
[I 2024-04-15 14:20:07,755] Trial 41 finished with value: 0.17117383165750671 and parameters: {'l1_ratio': 0.9453153656134119}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17972436428606856
Fold 2 IBS: 0.15101029459569482
Fold 3 IBS: 0.17597570196838183
Fold 4 IBS: 0.15361775753371654
Fold 5 IBS: 0.19572621445207875
[I 2024-04-15 14:20:08,465] Trial 42 finished with value: 0.1712108665671881 and parameters: {'l1_ratio': 0.9336443472987838}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17924298807784173
Fold 2 IBS: 0.15114459130371888
Fold 3 IBS: 0.17649708322692897
Fold 4 IBS: 0.15376875036002985
Fold 5 IBS: 0.19577639175839306
[I 2024-04-15 14:20:09,150] Trial 43 finished with value: 0.17128596094538245 and parameters: {'l1_ratio': 0.5623630226022138}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1797802795446687
Fold 2 IBS: 0.15098109056166611
Fold 3 IBS: 0.17580303252657212
Fold 4 IBS: 0.15360208362409772
Fold 5 IBS: 0.1956265743399147
[I 2024-04-15 14:20:09,878] Trial 44 finished with value: 0.17115861211938388 and parameters: {'l1_ratio': 0.9947170440864863}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1796364345351729
Fold 2 IBS: 0.15103963509434304
Fold 3 IBS: 0.1760654167152551
Fold 4 IBS: 0.15365791255531566
Fold 5 IBS: 0.19572960487884256
[I 2024-04-15 14:20:10,495] Trial 45 finished with value: 0.17122580075578586 and parameters: {'l1_ratio': 0.8792807549877475}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17977493560326202
Fold 2 IBS: 0.15097748183090476
Fold 3 IBS: 0.1758071741756737
Fold 4 IBS: 0.1536048074623866
Fold 5 IBS: 0.19572114531828386
[I 2024-04-15 14:20:11,087] Trial 46 finished with value: 0.17117710887810217 and parameters: {'l1_ratio': 0.98862079467032}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17978413965795886
Fold 2 IBS: 0.15091373573034603
Fold 3 IBS: 0.17580004745244557
Fold 4 IBS: 0.15359503260743132
Fold 5 IBS: 0.19563479906982342
[I 2024-04-15 14:20:11,676] Trial 47 finished with value: 0.17114555090360103 and parameters: {'l1_ratio': 0.9991568750151278}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17954301221738692
Fold 2 IBS: 0.15105663141824896
Fold 3 IBS: 0.17615746626765866
Fold 4 IBS: 0.15367151033919701
Fold 5 IBS: 0.19570453129366785
[I 2024-04-15 14:20:12,419] Trial 48 finished with value: 0.1712266303072319 and parameters: {'l1_ratio': 0.8115205184716434}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1794779006321135
Fold 2 IBS: 0.15108436032351105
Fold 3 IBS: 0.17622840676149215
Fold 4 IBS: 0.153693426276937
Fold 5 IBS: 0.19571773113097551
[I 2024-04-15 14:20:13,057] Trial 49 finished with value: 0.17124036502500584 and parameters: {'l1_ratio': 0.7662088837079067}. Best is trial 11 with value: 0.17114513223300334.

Fold 1 IBS: 0.1791599317538455
Fold 2 IBS: 0.151207053531672
Fold 3 IBS: 0.1765943472302714
Fold 4 IBS: 0.15377042990701825
Fold 5 IBS: 0.1957469037582549
[I 2024-04-15 14:20:13,943] Trial 50 finished with value: 0.17129573323621242 and parameters: {'l1_ratio': 0.47241766561900594}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17973942654319142
Fold 2 IBS: 0.15095358038819007
Fold 3 IBS: 0.1759032111479001
Fold 4 IBS: 0.15363386793868994
Fold 5 IBS: 0.1956511902619194
[I 2024-04-15 14:20:14,594] Trial 51 finished with value: 0.17117625525597818 and parameters: {'l1_ratio': 0.9495136153828908}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17977528625638908
Fold 2 IBS: 0.15097771852124492
Fold 3 IBS: 0.17580690208447577
Fold 4 IBS: 0.1536041711478401
Fold 5 IBS: 0.19572183222058723
[I 2024-04-15 14:20:15,159] Trial 52 finished with value: 0.17117718204610743 and parameters: {'l1_ratio': 0.9890190374631385}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.179652100118344
Fold 2 IBS: 0.15098668725642267
Fold 3 IBS: 0.17600069464517598
Fold 4 IBS: 0.153633439879778
Fold 5 IBS: 0.19565702307391664
[I 2024-04-15 14:20:15,822] Trial 53 finished with value: 0.17118598899472748 and parameters: {'l1_ratio': 0.89571854443464}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1797437260627566
Fold 2 IBS: 0.15095646523199072
Fold 3 IBS: 0.17590012507131098
Fold 4 IBS: 0.1536266157441761
Fold 5 IBS: 0.1956596942064932
[I 2024-04-15 14:20:16,454] Trial 54 finished with value: 0.17117732526334553 and parameters: {'l1_ratio': 0.9541190951832292}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17959289520912206
Fold 2 IBS: 0.15103000299815034
Fold 3 IBS: 0.17607557016039627
Fold 4 IBS: 0.1536382732779754
Fold 5 IBS: 0.19570155706599723
[I 2024-04-15 14:20:17,006] Trial 55 finished with value: 0.17120765974232827 and parameters: {'l1_ratio': 0.8638971223963612}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17978073820305174
Fold 2 IBS: 0.15098140044771052
Fold 3 IBS: 0.17580267755138232
Fold 4 IBS: 0.15360124530600874
Fold 5 IBS: 0.19562755202728974
[I 2024-04-15 14:20:17,809] Trial 56 finished with value: 0.1711587227070886 and parameters: {'l1_ratio': 0.9952429820612867}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17966385641774543
Fold 2 IBS: 0.1509947303000996
Fold 3 IBS: 0.17599213371211786
Fold 4 IBS: 0.15365626609812297
Fold 5 IBS: 0.1956808051661775
[I 2024-04-15 14:20:18,601] Trial 57 finished with value: 0.17119755833885267 and parameters: {'l1_ratio': 0.9083918983957515}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17955362556531188
Fold 2 IBS: 0.15106354559195317
Fold 3 IBS: 0.1761501642063562
Fold 4 IBS: 0.15365588716667347
Fold 5 IBS: 0.19572480354961078
[I 2024-04-15 14:20:19,474] Trial 58 finished with value: 0.1712296052159811 and parameters: {'l1_ratio': 0.8222199401929633}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1797434506808069
Fold 2 IBS: 0.15095628038911574
Fold 3 IBS: 0.17590032253818721
Fold 4 IBS: 0.1536270799714412
Fold 5 IBS: 0.19565914984288146
[I 2024-04-15 14:20:20,204] Trial 59 finished with value: 0.17117725668448652 and parameters: {'l1_ratio': 0.9538230932511079}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17936921363686623
Fold 2 IBS: 0.15113030691015902
Fold 3 IBS: 0.17635450071850967
Fold 4 IBS: 0.1537358633276195
Fold 5 IBS: 0.19573445362665717
[I 2024-04-15 14:20:20,994] Trial 60 finished with value: 0.17126486764396232 and parameters: {'l1_ratio': 0.6759896496482954}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17978386370372484
Fold 2 IBS: 0.15091353716790065
Fold 3 IBS: 0.1758002606671103
Fold 4 IBS: 0.153595536347715
Fold 5 IBS: 0.1956342113646685
[I 2024-04-15 14:20:21,606] Trial 61 finished with value: 0.17114548185022388 and parameters: {'l1_ratio': 0.9988384587582241}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.1796671034734443
Fold 2 IBS: 0.1509969508350752
Fold 3 IBS: 0.1759897745127453
Fold 4 IBS: 0.15365074306369153
Fold 5 IBS: 0.19568731197373934
[I 2024-04-15 14:20:22,922] Trial 62 finished with value: 0.17119837677173916 and parameters: {'l1_ratio': 0.9119347081912967}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17975814041571833
Fold 2 IBS: 0.15096614976089878
Fold 3 IBS: 0.17588985344116487
Fold 4 IBS: 0.15360238502861284
Fold 5 IBS: 0.19568812848756006
[I 2024-04-15 14:20:23,745] Trial 63 finished with value: 0.17118093142679097 and parameters: {'l1_ratio': 0.9698115893325118}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17963127358041497
Fold 2 IBS: 0.1510363282756184
Fold 3 IBS: 0.17606889027354844
Fold 4 IBS: 0.15366602260258952
Fold 5 IBS: 0.1957200007287218
[I 2024-04-15 14:20:25,140] Trial 64 finished with value: 0.17122450309217863 and parameters: {'l1_ratio': 0.8739577564577954}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17975144114645636
Fold 2 IBS: 0.15096164359768302
Fold 3 IBS: 0.17589463132549654
Fold 4 IBS: 0.15361362993939964
Fold 5 IBS: 0.1956749277341613
[I 2024-04-15 14:20:26,137] Trial 65 finished with value: 0.17117925474863938 and parameters: {'l1_ratio': 0.9624694078387075}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17896568998835136
Fold 2 IBS: 0.15127820782952067
Fold 3 IBS: 0.17680330979314737
Fold 4 IBS: 0.1538241598041551
Fold 5 IBS: 0.19575518266801273
[I 2024-04-15 14:20:27,434] Trial 66 finished with value: 0.17132531001663745 and parameters: {'l1_ratio': 0.2283450959509596}. Best is trial 11 with value: 0.17114513223300334.
Fold 1 IBS: 0.17978165648719477
Fold 2 IBS: 0.15091194947485892
Fold 3 IBS: 0.1758019670874323
Fold 4 IBS: 0.15359956732090638
Fold 5 IBS: 0.19562950911899055
[I 2024-04-15 14:20:28,363] Trial 67 finished with value: 0.1711449298978766 and parameters: {'l1_ratio': 0.9962972630546856}. Best is trial 67 with value: 0.1711449298978766.
Fold 1 IBS: 0.17967802363590155
Fold 2 IBS: 0.15100443849455927
Fold 3 IBS: 0.17598185331025304
Fold 4 IBS: 0.1536321827201126
Fold 5 IBS: 0.19570919062897102
[I 2024-04-15 14:20:29,182] Trial 68 finished with value: 0.1712011377579595 and parameters: {'l1_ratio': 0.9240311007928832}. Best is trial 67 with value: 0.1711449298978766.
Fold 1 IBS: 0.17978346478851912
Fold 2 IBS: 0.15091325015391796
Fold 3 IBS: 0.17580056893688925
Fold 4 IBS: 0.15359626463592332
Fold 5 IBS: 0.19563336171380377
[I 2024-04-15 14:20:29,929] Trial 69 finished with value: 0.1711453820458107 and parameters: {'l1_ratio': 0.9983784392233123}. Best is trial 67 with value: 0.1711449298978766.
Fold 1 IBS: 0.1797534059854007
Fold 2 IBS: 0.1509629646418919
Fold 3 IBS: 0.17589322839682803
Fold 4 IBS: 0.15361032891586346
Fold 5 IBS: 0.1956788020008814
[I 2024-04-15 14:20:30,633] Trial 70 finished with value: 0.1711797459881731 and parameters: {'l1_ratio': 0.9646139342241089}. Best is trial 67 with value: 0.1711449298978766.
Fold 1 IBS: 0.17978107150284015
Fold 2 IBS: 0.15091152880441652
Fold 3 IBS: 0.17580241964562215
Fold 4 IBS: 0.15360063620105172
Fold 5 IBS: 0.19562826242517198
[I 2024-04-15 14:20:31,256] Trial 71 finished with value: 0.17114478371582048 and parameters: {'l1_ratio': 0.9956254432215501}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.179783055800307
Fold 2 IBS: 0.1509129559230525
Fold 3 IBS: 0.17580088505209093
Fold 4 IBS: 0.1535970114233918
Fold 5 IBS: 0.19563249051840242
[I 2024-04-15 14:20:31,855] Trial 72 finished with value: 0.1711452797434489 and parameters: {'l1_ratio': 0.9979071447485004}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.2129738614386151
Fold 2 IBS: 0.21993446645249917
Fold 3 IBS: 0.17690126331140527
Fold 4 IBS: 0.22325004715182356
Fold 5 IBS: 0.1958019876113778
[I 2024-04-15 14:20:32,367] Trial 73 finished with value: 0.2057723251931442 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.1796796842013321
Fold 2 IBS: 0.1510055790316904
Fold 3 IBS: 0.1759806525069107
Fold 4 IBS: 0.1536293677610594
Fold 5 IBS: 0.19571251153795724
[I 2024-04-15 14:20:33,143] Trial 74 finished with value: 0.17120155900778994 and parameters: {'l1_ratio': 0.9258923934690237}. Best is trial 71 with value: 0.17114478371582048.

Fold 1 IBS: 0.17964920996955602
Fold 2 IBS: 0.15098471273560565
Fold 3 IBS: 0.17600281382450383
Fold 4 IBS: 0.15363795085093587
Fold 5 IBS: 0.1956511950989893
[I 2024-04-15 14:20:33,888] Trial 75 finished with value: 0.17118517649591816 and parameters: {'l1_ratio': 0.8926447980757628}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17975440942456136
Fold 2 IBS: 0.15096363948106567
Fold 3 IBS: 0.17589251244197426
Fold 4 IBS: 0.1536086440474439
Fold 5 IBS: 0.19568077974829168
[I 2024-04-15 14:20:34,587] Trial 76 finished with value: 0.17117999702866737 and parameters: {'l1_ratio': 0.9657119709985041}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17958298235895545
Fold 2 IBS: 0.15102311499889745
Fold 3 IBS: 0.17608285904146911
Fold 4 IBS: 0.15365396277963647
Fold 5 IBS: 0.19568126430542182
[I 2024-04-15 14:20:35,258] Trial 77 finished with value: 0.17120483669687606 and parameters: {'l1_ratio': 0.8531345030167654}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17972439289200312
Fold 2 IBS: 0.15101031258890574
Fold 3 IBS: 0.1759756831221456
Fold 4 IBS: 0.15361771331916588
Fold 5 IBS: 0.19572626665424306
[I 2024-04-15 14:20:35,797] Trial 78 finished with value: 0.1712108737152927 and parameters: {'l1_ratio': 0.9336741019260839}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17965524991016857
Fold 2 IBS: 0.15098884038701785
Fold 3 IBS: 0.1759983885495606
Fold 4 IBS: 0.15362852973090985
Fold 5 IBS: 0.19566336899671416
[I 2024-04-15 14:20:36,370] Trial 79 finished with value: 0.17118687551487421 and parameters: {'l1_ratio': 0.8990870830951367}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17978410912682447
Fold 2 IBS: 0.15091371376102386
Fold 3 IBS: 0.17580007104078504
Fold 4 IBS: 0.1535950883379734
Fold 5 IBS: 0.1956347340491065
[I 2024-04-15 14:20:37,062] Trial 80 finished with value: 0.17114554326314263 and parameters: {'l1_ratio': 0.9991216382049871}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17975133919513164
Fold 2 IBS: 0.1509615750645899
Fold 3 IBS: 0.17589470415716194
Fold 4 IBS: 0.15361380129031282
Fold 5 IBS: 0.19567472664773253
[I 2024-04-15 14:20:37,689] Trial 81 finished with value: 0.17117922927098578 and parameters: {'l1_ratio': 0.9623583326869487}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17976229892583928
Fold 2 IBS: 0.1509689496970269
Fold 3 IBS: 0.17588689543400512
Fold 4 IBS: 0.15359541930461515
Fold 5 IBS: 0.1956963101571846
[I 2024-04-15 14:20:38,680] Trial 82 finished with value: 0.17118197470373422 and parameters: {'l1_ratio': 0.9744125954880615}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17967609782231464
Fold 2 IBS: 0.15100311620694654
Fold 3 IBS: 0.17598324715229913
Fold 4 IBS: 0.15363544961125566
Fold 5 IBS: 0.19570533730826992
[I 2024-04-15 14:20:39,510] Trial 83 finished with value: 0.17120064962021714 and parameters: {'l1_ratio': 0.921879788344501}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17978342099074046
Fold 2 IBS: 0.15091321864381077
Fold 3 IBS: 0.17580060278610396
Fold 4 IBS: 0.15359634460269952
Fold 5 IBS: 0.19563326842348372
[I 2024-04-15 14:20:40,099] Trial 84 finished with value: 0.1711453710893677 and parameters: {'l1_ratio': 0.9983279526837933}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17973477543415575
Fold 2 IBS: 0.15095046228564343
Fold 3 IBS: 0.17590655692764431
Fold 4 IBS: 0.1536346278320474
Fold 5 IBS: 0.19564185184353486
[I 2024-04-15 14:20:40,668] Trial 85 finished with value: 0.17117365486460517 and parameters: {'l1_ratio': 0.9445696786081975}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17978219779669766
Fold 2 IBS: 0.15091233876575583
Fold 3 IBS: 0.17580154842209567
Fold 4 IBS: 0.15359857844518146
Fold 5 IBS: 0.19563066256850445
[I 2024-04-15 14:20:41,487] Trial 86 finished with value: 0.17114506519964703 and parameters: {'l1_ratio': 0.996919550984205}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.1797610591386626
Fold 2 IBS: 0.1509681147238188
Fold 3 IBS: 0.17588777668724515
Fold 4 IBS: 0.15359749485922014
Fold 5 IBS: 0.19569387194057705
[I 2024-04-15 14:20:42,163] Trial 87 finished with value: 0.17118166346990477 and parameters: {'l1_ratio': 0.9730373764475295}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.1796325193404531
Fold 2 IBS: 0.15103712629488475
Fold 3 IBS: 0.17606805099134223
Fold 4 IBS: 0.1536640633972197
Fold 5 IBS: 0.19572232045221308
[I 2024-04-15 14:20:43,062] Trial 88 finished with value: 0.17122481609522258 and parameters: {'l1_ratio': 0.8752380945622052}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17973651116513475
Fold 2 IBS: 0.1509516255675367
Fold 3 IBS: 0.17590530743761637
Fold 4 IBS: 0.15363171844635928
Fold 5 IBS: 0.19564529108911854
[I 2024-04-15 14:20:43,795] Trial 89 finished with value: 0.17117409074115314 and parameters: {'l1_ratio': 0.9464100808770963}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.1797836769814166
Fold 2 IBS: 0.1509134028201211
Fold 3 IBS: 0.17580040495319418
Fold 4 IBS: 0.1535958772282537
Fold 5 IBS: 0.19563381367497454
[I 2024-04-15 14:20:44,487] Trial 90 finished with value: 0.17114543513159203 and parameters: {'l1_ratio': 0.9986230941157217}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.1797626648925111
Fold 2 IBS: 0.15096919620446564
Fold 3 IBS: 0.17588663540255
Fold 4 IBS: 0.15359480681904913
Fold 5 IBS: 0.19569702971927844
[I 2024-04-15 14:20:45,174] Trial 91 finished with value: 0.17118206660757088 and parameters: {'l1_ratio': 0.9748191118659203}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17972698541541363
Fold 2 IBS: 0.15101194354232766
Fold 3 IBS: 0.1759121778325124
Fold 4 IBS: 0.1536137083134565
Fold 5 IBS: 0.19573099575792013
[I 2024-04-15 14:20:45,913] Trial 92 finished with value: 0.17119916217232606 and parameters: {'l1_ratio': 0.936376731257241}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17976185262762118
Fold 2 IBS: 0.1509686491020298
Fold 3 IBS: 0.17588721260619308
Fold 4 IBS: 0.1535961663493141
Fold 5 IBS: 0.1956954325469832
[I 2024-04-15 14:20:46,703] Trial 93 finished with value: 0.1711818626464283 and parameters: {'l1_ratio': 0.9739171999545797}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17966483368773395
Fold 2 IBS: 0.1509953997017316
Fold 3 IBS: 0.175991421959431
Fold 4 IBS: 0.15365460003079853
Fold 5 IBS: 0.1956827677680982
[I 2024-04-15 14:20:47,454] Trial 94 finished with value: 0.17119780462955866 and parameters: {'l1_ratio': 0.9094578869039874}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17978421788640034
Fold 2 IBS: 0.15091379202205646
Fold 3 IBS: 0.17579998701476762
Fold 4 IBS: 0.1535948898145844
Fold 5 IBS: 0.1956349656669288
[I 2024-04-15 14:20:48,257] Trial 95 finished with value: 0.17114557048094753 and parameters: {'l1_ratio': 0.9992471693779538}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.1797835547035804
Fold 2 IBS: 0.15091331484399872
Fold 3 IBS: 0.1758004994480564
Fold 4 IBS: 0.15359610047135355
Fold 5 IBS: 0.1956335532317684
[I 2024-04-15 14:20:48,976] Trial 96 finished with value: 0.1711454045397515 and parameters: {'l1_ratio': 0.998482098447956}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.1797360252188705
Fold 2 IBS: 0.1509512998412857
Fold 3 IBS: 0.17590565714543896
Fold 4 IBS: 0.15363253253219078
Fold 5 IBS: 0.1956443283881786
[I 2024-04-15 14:20:50,163] Trial 97 finished with value: 0.1711739686251929 and parameters: {'l1_ratio': 0.945894278779799}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17904566892625592
Fold 2 IBS: 0.1512410545681786
Fold 3 IBS: 0.17671369661824565
Fold 4 IBS: 0.15382453099244642
Fold 5 IBS: 0.19573715652512602
[I 2024-04-15 14:20:51,488] Trial 98 finished with value: 0.17131242152605053 and parameters: {'l1_ratio': 0.3410246190042779}. Best is trial 71 with value: 0.17114478371582048.
Fold 1 IBS: 0.17956932742488643
Fold 2 IBS: 0.15101362044384964
Fold 3 IBS: 0.17609302724532094
Fold 4 IBS: 0.1536755382884527
Fold 5 IBS: 0.19565330598100428
[I 2024-04-15 14:20:52,333] Trial 99 finished with value: 0.1712009638767028 and parameters: {'l1_ratio': 0.8386068305115117}. Best is trial 71 with value: 0.17114478371582048.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.17114478371582048], datetime_start=datetime.datetime(2024, 4, 15, 14, 20, 30, 686322), datetime_complete=datetime.datetime(2024, 4, 15, 14, 20, 31, 256744), params={'l1_ratio': 0.9956254432215501}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.17114478371582048

In [42]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.738
train_ibs:  0.171

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6127580877814559)

test_cindex : 0.567

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.9956254432215501)

test_ibs:  0.257

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:20:53,002] A new study created in memory with name: no-name-919fe68e-b370-4610-af64-62e471857823

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 14:20:59,625] Trial 0 finished with value: 0.7575203363732566 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 14:21:04,738] Trial 1 finished with value: 0.750478431579118 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:21:09,002] Trial 2 finished with value: 0.7520712510356254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:21:12,076] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:21:13,888] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7934272300469484
[I 2024-04-15 14:21:21,128] Trial 5 finished with value: 0.7462602486577217 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7746478873239436
[I 2024-04-15 14:21:26,977] Trial 6 finished with value: 0.7576976783760393 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:21:32,109] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6901408450704225
[I 2024-04-15 14:21:42,626] Trial 8 finished with value: 0.5380281690140845 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 14:21:46,935] Trial 9 finished with value: 0.748452073539184 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:21:47,539] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.40740851493126695, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:21:54,576] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.11379276107227315, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:22:04,670] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 14:22:08,792] Trial 13 finished with value: 0.7581182539062076 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 13 with value: 0.7581182539062076.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.8075117370892019
[I 2024-04-15 14:22:10,204] Trial 14 finished with value: 0.7907144637948861 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0992244164616675, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 14:22:11,107] Trial 15 finished with value: 0.7816150812624114 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.8147833133306369, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7746478873239436
[I 2024-04-15 14:22:11,362] Trial 16 finished with value: 0.765813594477808 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.8484814588885312, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08082385841318356, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.8028169014084507
[I 2024-04-15 14:22:12,408] Trial 17 finished with value: 0.7851258260885514 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16544550098450153, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7981220657276995
[I 2024-04-15 14:22:13,493] Trial 18 finished with value: 0.7834440402483949 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13294582901895255, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 14:22:14,970] Trial 19 finished with value: 0.7742809868075984 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9945705745432233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09964492104707659, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:22:15,658] Trial 20 finished with value: 0.7628622503029641 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.8673418291441284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37827446502466894, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7934272300469484
[I 2024-04-15 14:22:16,800] Trial 21 finished with value: 0.7872501961326841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.9624638447657676, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.8051643192488263
[I 2024-04-15 14:22:17,146] Trial 22 finished with value: 0.7873570802451841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.9336744347879812, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19282610776605333, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7488262910798122
[I 2024-04-15 14:22:17,482] Trial 23 finished with value: 0.7541962121280221 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.6843026151576985, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2504370920378234, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7981220657276995
[I 2024-04-15 14:22:18,091] Trial 24 finished with value: 0.7858778057568998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 50, 'oob_score': True, 'max_samples': 0.8085053499703132, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17035312846001988, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7981220657276995
[I 2024-04-15 14:22:19,763] Trial 25 finished with value: 0.7899316539935477 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.9171920870810285, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07664126778540013, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-15 14:22:21,367] Trial 26 finished with value: 0.7817663440763265 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.8983378428295576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06306617081281016, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7981220657276995
[I 2024-04-15 14:22:23,799] Trial 27 finished with value: 0.7856141531151757 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.7989579262543244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09596584472346859, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-15 14:22:26,017] Trial 28 finished with value: 0.7853982513847043 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.5360953547457009, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014347840876196644, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.755868544600939
[I 2024-04-15 14:22:26,775] Trial 29 finished with value: 0.7695772354631409 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.6977978899499365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2196223213316708, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8262910798122066
[I 2024-04-15 14:22:27,963] Trial 30 finished with value: 0.7981448890436417 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 82, 'oob_score': True, 'max_samples': 0.7311645169232817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.059569167808063095, 'warm_start': True}. Best is trial 30 with value: 0.7981448890436417.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8356807511737089
[I 2024-04-15 14:22:28,974] Trial 31 finished with value: 0.7982641653072841 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.745146001885883, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05174429879930956, 'warm_start': True}. Best is trial 31 with value: 0.7982641653072841.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7742616033755274
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:22:29,872] Trial 32 finished with value: 0.8032544311992128 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.7397628776532771, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04641084093066284, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:22:30,767] Trial 33 finished with value: 0.7999277380363321 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.7321956680996766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0042513284435347215, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8169014084507042
[I 2024-04-15 14:22:31,630] Trial 34 finished with value: 0.7980620370159766 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 74, 'oob_score': True, 'max_samples': 0.7190350277691129, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002617826444773601, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8544600938967136
[I 2024-04-15 14:22:32,207] Trial 35 finished with value: 0.8195885025512174 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.6491391650041388, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04473837361201603, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-15 14:22:33,483] Trial 36 finished with value: 0.8149421898615685 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6500614805101094, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.042163225365865975, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8450704225352113
[I 2024-04-15 14:22:34,720] Trial 37 finished with value: 0.8201548198575692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.6316988824284715, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03372830367211485, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 14:22:36,033] Trial 38 finished with value: 0.7864200685622795 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6475925530300135, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1261541633669147, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8169014084507042
[I 2024-04-15 14:22:37,557] Trial 39 finished with value: 0.7994601394099836 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.5500795764120797, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0407216828679674, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8215962441314554
[I 2024-04-15 14:22:38,902] Trial 40 finished with value: 0.8144744547521597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.5974594004293988, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03731085344043298, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8356807511737089
[I 2024-04-15 14:22:40,637] Trial 41 finished with value: 0.8146670383091891 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.5688957234666421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.038323603584419504, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8450704225352113
[I 2024-04-15 14:22:42,253] Trial 42 finished with value: 0.8217769675659046 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.565436601526051, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03253349071458341, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8403755868544601
[I 2024-04-15 14:22:43,749] Trial 43 finished with value: 0.8194179790264864 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.5414105158165579, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02824952898790397, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 14:22:45,504] Trial 44 finished with value: 0.7844759249669818 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.4812619709263958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0734121445676241, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 14:22:47,641] Trial 45 finished with value: 0.7812420451089397 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.4132359110524421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10574093555624242, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.7793427230046949
[I 2024-04-15 14:22:54,796] Trial 46 finished with value: 0.742796454430003 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 277, 'oob_score': False, 'max_samples': 0.6435530257070258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02588599089196765, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8075117370892019
[I 2024-04-15 14:22:56,886] Trial 47 finished with value: 0.8020413535841735 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.513428105668999, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005073560345181239, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 14:23:01,745] Trial 48 finished with value: 0.7605416340753064 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.4250487747986099, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07826456635516901, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:23:03,676] Trial 49 finished with value: 0.7646180284055469 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.3288612699820465, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11977607788857622, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-15 14:23:05,432] Trial 50 finished with value: 0.7516085439508142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.6056621314066971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27891660351802283, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-15 14:23:07,358] Trial 51 finished with value: 0.8156329206993581 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.5653247525904954, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024675273648228607, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8497652582159625
[I 2024-04-15 14:23:08,756] Trial 52 finished with value: 0.8105679483498613 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.668807800129283, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023886857070088842, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:23:11,444] Trial 53 finished with value: 0.8092844755529726 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.5049892673780266, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0302062450326431, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7934272300469484
[I 2024-04-15 14:23:12,956] Trial 54 finished with value: 0.7837218500992189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 223, 'oob_score': False, 'max_samples': 0.5694355594036941, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08503386755881623, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:23:14,672] Trial 55 finished with value: 0.8023260161047514 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.6230580876154783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06106714571926695, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7793427230046949
[I 2024-04-15 14:23:19,186] Trial 56 finished with value: 0.7505163979885541 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.37386377532060755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020276597591653404, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6995305164319249
[I 2024-04-15 14:23:20,451] Trial 57 finished with value: 0.7370660000414045 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 265, 'oob_score': False, 'max_samples': 0.673626054002652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.32552397591019333, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:23:22,009] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.5859997242165991, 'max_features': None, 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 14:23:23,083] Trial 59 finished with value: 0.7738001567018483 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.4578032212133656, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14288340865089383, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:23:28,244] Trial 60 finished with value: 0.7576418826254305 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.5248616932098589, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09178626486905285, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8356807511737089
[I 2024-04-15 14:23:29,378] Trial 61 finished with value: 0.8121405300073643 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.5673407402421513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04324260858798204, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:23:30,502] Trial 62 finished with value: 0.8048963624250977 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.6136771186690915, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.061141393518585746, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:23:31,464] Trial 63 finished with value: 0.8129059673027221 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.5632723911430406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03896879562886681, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-15 14:23:32,934] Trial 64 finished with value: 0.8200972064136438 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.4849644523201697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015459623887936643, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8450704225352113
[I 2024-04-15 14:23:34,869] Trial 65 finished with value: 0.8200556403698938 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.4915234805630325, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01325985667696578, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8215962441314554
[I 2024-04-15 14:23:36,700] Trial 66 finished with value: 0.7991290530701981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.44421584072665865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01688809895377827, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.9014084507042254
[I 2024-04-15 14:23:38,926] Trial 67 finished with value: 0.8455736642377335 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8873239436619719
[I 2024-04-15 14:23:42,105] Trial 68 finished with value: 0.8406053556611222 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'max_samples': 0.49738412507640734, 'max_features': None, 'min_weight_fraction_leaf': 0.002433553898016293, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8826291079812206
[I 2024-04-15 14:23:45,271] Trial 69 finished with value: 0.8316567836473476 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.38288786338976266, 'max_features': None, 'min_weight_fraction_leaf': 0.010924103557748996, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-15 14:23:48,319] Trial 70 finished with value: 0.8325253087831349 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.3768797583243322, 'max_features': None, 'min_weight_fraction_leaf': 0.007358190561024822, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8450704225352113
[I 2024-04-15 14:23:50,587] Trial 71 finished with value: 0.8074401022098655 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.2977376592001145, 'max_features': None, 'min_weight_fraction_leaf': 0.007777034521166985, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.863849765258216
[I 2024-04-15 14:23:53,497] Trial 72 finished with value: 0.8207621073356813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3758248033560092, 'max_features': None, 'min_weight_fraction_leaf': 0.0021403509786410697, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-15 14:23:57,373] Trial 73 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.37703659520841803, 'max_features': None, 'min_weight_fraction_leaf': 0.0030355880739053242, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-15 14:24:01,347] Trial 74 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.37759120849945615, 'max_features': None, 'min_weight_fraction_leaf': 0.005738060589732854, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8356807511737089
[I 2024-04-15 14:24:04,205] Trial 75 finished with value: 0.8064988630989438 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3512499599110515, 'max_features': None, 'min_weight_fraction_leaf': 0.0016091095350437782, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:24:06,998] Trial 76 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.2200825864677213, 'max_features': None, 'min_weight_fraction_leaf': 0.3808353622830714, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8075117370892019
[I 2024-04-15 14:24:11,027] Trial 77 finished with value: 0.7898601663797173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.38697496089808264, 'max_features': None, 'min_weight_fraction_leaf': 0.0678874889911297, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8356807511737089
[I 2024-04-15 14:24:13,655] Trial 78 finished with value: 0.7983796631750157 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.2971389951907717, 'max_features': None, 'min_weight_fraction_leaf': 0.0014283193772283813, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-15 14:24:15,859] Trial 79 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.3832306547359522, 'max_features': None, 'min_weight_fraction_leaf': 0.001325860823554314, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7746478873239436
[I 2024-04-15 14:24:22,726] Trial 80 finished with value: 0.7638486802036979 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.2259926589326255, 'max_features': None, 'min_weight_fraction_leaf': 0.051988057609908274, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-15 14:24:24,984] Trial 81 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.3902826764643792, 'max_features': None, 'min_weight_fraction_leaf': 0.01424010512203431, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8262910798122066
[I 2024-04-15 14:24:27,608] Trial 82 finished with value: 0.8037666314114749 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.35665467332899853, 'max_features': None, 'min_weight_fraction_leaf': 0.02723621966149422, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8075117370892019
[I 2024-04-15 14:24:29,844] Trial 83 finished with value: 0.7910748783864995 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.27364682713049737, 'max_features': None, 'min_weight_fraction_leaf': 0.003437924737021262, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.812206572769953
[I 2024-04-15 14:24:32,725] Trial 84 finished with value: 0.7981013668372744 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.42217891643501637, 'max_features': None, 'min_weight_fraction_leaf': 0.05691895142137581, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8497652582159625
[I 2024-04-15 14:24:36,050] Trial 85 finished with value: 0.8142696016233687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.44215445453616553, 'max_features': None, 'min_weight_fraction_leaf': 0.015948474032128478, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-15 14:24:38,948] Trial 86 finished with value: 0.8039740360073753 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 467, 'oob_score': False, 'max_samples': 0.34536985759892425, 'max_features': None, 'min_weight_fraction_leaf': 0.03379453130696234, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8262910798122066
[I 2024-04-15 14:24:41,902] Trial 87 finished with value: 0.8009672435320422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3948765985014735, 'max_features': None, 'min_weight_fraction_leaf': 0.049452906101561514, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8262910798122066
[I 2024-04-15 14:24:44,648] Trial 88 finished with value: 0.7958162763557586 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.3168310392190445, 'max_features': None, 'min_weight_fraction_leaf': 0.011197201541028177, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8450704225352113
[I 2024-04-15 14:24:48,404] Trial 89 finished with value: 0.8188472945459484 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.46056239467229443, 'max_features': None, 'min_weight_fraction_leaf': 0.02927897429150622, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8732394366197183
[I 2024-04-15 14:24:52,447] Trial 90 finished with value: 0.8280743039205017 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3677724129924504, 'max_features': None, 'min_weight_fraction_leaf': 0.0015288688784384722, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-15 14:24:57,731] Trial 91 finished with value: 0.8315449166262722 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.37527324355860175, 'max_features': None, 'min_weight_fraction_leaf': 0.00032873883511814225, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:25:02,410] Trial 92 finished with value: 0.8152302082764418 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.36969362389667315, 'max_features': None, 'min_weight_fraction_leaf': 0.020344390663164187, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8215962441314554
[I 2024-04-15 14:25:05,392] Trial 93 finished with value: 0.8013473051581448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.3234854377137636, 'max_features': None, 'min_weight_fraction_leaf': 0.034235535617443455, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8826291079812206
[I 2024-04-15 14:25:09,176] Trial 94 finished with value: 0.8317597304647398 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.40292152817878885, 'max_features': None, 'min_weight_fraction_leaf': 0.0013715257783006587, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8309859154929577
[I 2024-04-15 14:25:13,886] Trial 95 finished with value: 0.8054182483946754 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.43651122516239244, 'max_features': None, 'min_weight_fraction_leaf': 0.0516435889873805, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7934272300469484
[I 2024-04-15 14:25:17,281] Trial 96 finished with value: 0.781897576085816 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.40560294670004454, 'max_features': None, 'min_weight_fraction_leaf': 0.0001044161694674754, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-15 14:25:20,838] Trial 97 finished with value: 0.8076329995928095 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.33588267636278435, 'max_features': None, 'min_weight_fraction_leaf': 0.019808016366776694, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-15 14:25:35,910] Trial 98 finished with value: 0.7563224015679627 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.4120109800767605, 'max_features': None, 'min_weight_fraction_leaf': 0.0696147483073608, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815

[I 2024-04-15 14:25:42,880] A new study created in memory with name: no-name-87a03c49-1939-4a78-b582-7823bccb59d5

Fold 5 C-index: 0.8403755868544601
[I 2024-04-15 14:25:42,804] Trial 99 finished with value: 0.81879604728486 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.4642145775222535, 'max_features': None, 'min_weight_fraction_leaf': 0.04423293101031651, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.


* Best trial for C-index:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.8455736642377335], datetime_start=datetime.datetime(2024, 4, 15, 14, 23, 36, 716534), datetime_complete=datetime.datetime(2024, 4, 15, 14, 23, 38, 924657), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=67, value=None)


* Best Score for C-index:
 0.8455736642377335

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16912942286746
Fold 2 IBS: 0.15736700168879125
Fold 3 IBS: 0.17596810644035646
Fold 4 IBS: 0.21476462245142444
Fold 5 IBS: 0.18140709105634753
[I 2024-04-15 14:25:57,164] Trial 0 finished with value: 0.17972724890087594 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.17972724890087594.
Fold 1 IBS: 0.1695457408702072
Fold 2 IBS: 0.15431589011481192
Fold 3 IBS: 0.17931251537071569
Fold 4 IBS: 0.19778743079510175
Fold 5 IBS: 0.1838708756319808
[I 2024-04-15 14:26:01,503] Trial 1 finished with value: 0.1769664905565635 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-15 14:26:03,646] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-15 14:26:13,151] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-15 14:26:18,434] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.18261661077179908
Fold 2 IBS: 0.14215438755582593
Fold 3 IBS: 0.19825307809201306
Fold 4 IBS: 0.1894541695729735
Fold 5 IBS: 0.17258301646825175
[I 2024-04-15 14:26:26,526] Trial 5 finished with value: 0.17701225249217267 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.1793072949109339
Fold 2 IBS: 0.17146943238736864
Fold 3 IBS: 0.1801865051168754
Fold 4 IBS: 0.2169078691801737
Fold 5 IBS: 0.1927889640697635
[I 2024-04-15 14:26:34,642] Trial 6 finished with value: 0.18813201313302302 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.20628331122669447
Fold 2 IBS: 0.20810768242984765
Fold 3 IBS: 0.196178000210441
Fold 4 IBS: 0.21720909429106852
Fold 5 IBS: 0.2120048382129915
[I 2024-04-15 14:26:42,571] Trial 7 finished with value: 0.2079565852742086 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-15 14:26:58,230] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17251108291109596
Fold 2 IBS: 0.16372104609445076
Fold 3 IBS: 0.1752499545194017
Fold 4 IBS: 0.19923941269775702
Fold 5 IBS: 0.1807428948937162
[I 2024-04-15 14:27:02,208] Trial 9 finished with value: 0.17829287822328432 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2138914608019449
Fold 2 IBS: 0.22021134435777845
Fold 3 IBS: 0.20482550997958907
Fold 4 IBS: 0.22548051560881624
Fold 5 IBS: 0.21733795012904839
[I 2024-04-15 14:27:07,856] Trial 10 finished with value: 0.2163493561754354 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17089799911696577
Fold 2 IBS: 0.1343759168934981
Fold 3 IBS: 0.18019414575478068
Fold 4 IBS: 0.19691489378360008
Fold 5 IBS: 0.17134875048281803
[I 2024-04-15 14:27:08,243] Trial 11 finished with value: 0.17074634120633253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1938573372077058
Fold 2 IBS: 0.15264524705837576
Fold 3 IBS: 0.1835875292339129
Fold 4 IBS: 0.19186721611439267
Fold 5 IBS: 0.17242006747034438
[I 2024-04-15 14:27:09,074] Trial 12 finished with value: 0.17887547941694631 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.7748822387405266, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020197386275102834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1753396733634442
Fold 2 IBS: 0.14659590196214217
Fold 3 IBS: 0.18564941996432435
Fold 4 IBS: 0.19697957764971377
Fold 5 IBS: 0.1760898132139911
[I 2024-04-15 14:27:13,599] Trial 13 finished with value: 0.17613087723072313 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 110, 'oob_score': False, 'max_samples': 0.9282504676473301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18437150857335638
Fold 2 IBS: 0.13940627158607374
Fold 3 IBS: 0.19735408203235827
Fold 4 IBS: 0.19502160042084687
Fold 5 IBS: 0.17327657876201488
[I 2024-04-15 14:27:19,695] Trial 14 finished with value: 0.17788600827493004 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.9418551640023243, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1903120334095733
Fold 2 IBS: 0.13604392965192902
Fold 3 IBS: 0.20770281014511405
Fold 4 IBS: 0.21649791040859048
Fold 5 IBS: 0.17399213158709487
[I 2024-04-15 14:27:20,320] Trial 15 finished with value: 0.18490976304046036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.9969315225031997, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10400906232299456}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.17234717281067394
Fold 2 IBS: 0.168695961879054
Fold 3 IBS: 0.17428134482390595
Fold 4 IBS: 0.20512326820357737
Fold 5 IBS: 0.1858777602458117
[I 2024-04-15 14:27:23,020] Trial 16 finished with value: 0.1812651015926046 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.8254434867518305, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27558800117237026}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1701072167867666
Fold 2 IBS: 0.15066297678714172
Fold 3 IBS: 0.18453320195882447
Fold 4 IBS: 0.19299945063741186
Fold 5 IBS: 0.17720564069954053
[I 2024-04-15 14:27:44,426] Trial 17 finished with value: 0.17510169737393705 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.7509985501856506, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0026257659295356476}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18294194940487038
Fold 2 IBS: 0.14058077366331193
Fold 3 IBS: 0.19786106053237812
Fold 4 IBS: 0.19006278490632897
Fold 5 IBS: 0.17207512016650234
[I 2024-04-15 14:28:08,431] Trial 18 finished with value: 0.17670433773467834 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16955416166590404
Fold 2 IBS: 0.15212211732759853
Fold 3 IBS: 0.18191729427832115
Fold 4 IBS: 0.1920689530206985
Fold 5 IBS: 0.1791048456801592
[I 2024-04-15 14:28:26,011] Trial 19 finished with value: 0.1749534743945363 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6173177066935658, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1243900714081905}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17714686876701324
Fold 2 IBS: 0.16932933496556507
Fold 3 IBS: 0.17717541750009574
Fold 4 IBS: 0.19713572873566637
Fold 5 IBS: 0.1888282875493155
[I 2024-04-15 14:28:38,563] Trial 20 finished with value: 0.18192312750353118 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.3628004877999946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13255231046532823}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16913535340838307
Fold 2 IBS: 0.15272782624748996
Fold 3 IBS: 0.18157422278730082
Fold 4 IBS: 0.19159866778115425
Fold 5 IBS: 0.18035473161483767
[I 2024-04-15 14:28:53,249] Trial 21 finished with value: 0.17507816036783316 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6011378896362364, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04460079180106673}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17030810384993947
Fold 2 IBS: 0.15141739726332304
Fold 3 IBS: 0.18252438545010272
Fold 4 IBS: 0.19011356122343498
Fold 5 IBS: 0.178289463693237
[I 2024-04-15 14:29:07,231] Trial 22 finished with value: 0.17453058229600743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.6303687757401123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10192378722318633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17546673577503152
Fold 2 IBS: 0.15775731851311675
Fold 3 IBS: 0.1781524236691594
Fold 4 IBS: 0.18862200168076865
Fold 5 IBS: 0.1781929228483396
[I 2024-04-15 14:29:18,325] Trial 23 finished with value: 0.1756382804972832 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.47299192016675806, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11363003519604899}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17094376831357636
Fold 2 IBS: 0.1646895387119759
Fold 3 IBS: 0.1747842391429866
Fold 4 IBS: 0.19494361629603088
Fold 5 IBS: 0.1866353242437713
[I 2024-04-15 14:29:29,842] Trial 24 finished with value: 0.1783992973416682 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 20, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.6280222894166756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17647963073148}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16901499831887323
Fold 2 IBS: 0.1608317214516487
Fold 3 IBS: 0.1762379772561786
Fold 4 IBS: 0.19348054932052614
Fold 5 IBS: 0.18439435643852217
[I 2024-04-15 14:29:51,431] Trial 25 finished with value: 0.1767919205571498 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.4737896318177208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09514387992502697}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16929634538840924
Fold 2 IBS: 0.15790827738905253
Fold 3 IBS: 0.17685741513951483
Fold 4 IBS: 0.1967559497411602
Fold 5 IBS: 0.185385205701487
[I 2024-04-15 14:30:06,697] Trial 26 finished with value: 0.17724063867192474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.8171469856554013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23317683759042168}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17086891563968248
Fold 2 IBS: 0.1631508903913892
Fold 3 IBS: 0.17528408462417908
Fold 4 IBS: 0.19656070086825392
Fold 5 IBS: 0.1871180876095544
[I 2024-04-15 14:30:17,340] Trial 27 finished with value: 0.1785965358266118 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.69231778632942, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05016618054550538}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21403025999388117
Fold 2 IBS: 0.22062977018591617
Fold 3 IBS: 0.20516689505844507
Fold 4 IBS: 0.22458172975885837
Fold 5 IBS: 0.21781943709735221
[I 2024-04-15 14:30:24,311] Trial 28 finished with value: 0.21644561841889062 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.26154064534881144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1313308679038699}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1728058934917983
Fold 2 IBS: 0.16613273087140148
Fold 3 IBS: 0.1752425051862629
Fold 4 IBS: 0.19545037913945612
Fold 5 IBS: 0.18577836193667824
[I 2024-04-15 14:30:37,433] Trial 29 finished with value: 0.17908197412511942 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.590452735593326, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1894700331250358}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18009129126221046
Fold 2 IBS: 0.16991867934953306
Fold 3 IBS: 0.18118166421743642
Fold 4 IBS: 0.21329354235589876
Fold 5 IBS: 0.19503330809108468
[I 2024-04-15 14:30:50,174] Trial 30 finished with value: 0.18790369705523266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.2125304486051036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17449717368418352
Fold 2 IBS: 0.15873065763573396
Fold 3 IBS: 0.17799356833494584
Fold 4 IBS: 0.18990025142492684

Fold 5 IBS: 0.17698987901902175
[I 2024-04-15 14:31:06,830] Trial 31 finished with value: 0.1756223060197624 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.6141886010044044, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.050889504115644586}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17921499719523448
Fold 2 IBS: 0.14457659998302025
Fold 3 IBS: 0.18892068480933402
Fold 4 IBS: 0.1881785321534129
Fold 5 IBS: 0.17366220512930025
[I 2024-04-15 14:31:23,107] Trial 32 finished with value: 0.17491060385406038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.7145937356077748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.040680386261001684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17839650482493216
Fold 2 IBS: 0.14376103753095715
Fold 3 IBS: 0.19179232168292484
Fold 4 IBS: 0.19114956333888955
Fold 5 IBS: 0.17341358371378018
[I 2024-04-15 14:31:39,855] Trial 33 finished with value: 0.17570260221829676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7166906016039446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09227781345982045}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16932356014486769
Fold 2 IBS: 0.15500446673627225
Fold 3 IBS: 0.17911021415557007
Fold 4 IBS: 0.1924434421788033
Fold 5 IBS: 0.1827561791077991
[I 2024-04-15 14:31:50,442] Trial 34 finished with value: 0.17572757246466247 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6617651070453551, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03171407678135554}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17172138717448102
Fold 2 IBS: 0.1489493130650319
Fold 3 IBS: 0.18425400801471595
Fold 4 IBS: 0.1932643172167075
Fold 5 IBS: 0.17711273715249415
[I 2024-04-15 14:31:58,369] Trial 35 finished with value: 0.1750603525246861 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.7113768772571837, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15846671523399145}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17419660096638498
Fold 2 IBS: 0.14719187785917906
Fold 3 IBS: 0.18565125612910302
Fold 4 IBS: 0.19257551123464545
Fold 5 IBS: 0.17764557195591085
[I 2024-04-15 14:32:01,786] Trial 36 finished with value: 0.17545216362904464 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 165, 'oob_score': False, 'max_samples': 0.5150316876314238, 'max_features': None, 'min_weight_fraction_leaf': 0.07821728657119803}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16964600099214439
Fold 2 IBS: 0.15385862052455887
Fold 3 IBS: 0.18067679456916436
Fold 4 IBS: 0.19330218283868858
Fold 5 IBS: 0.18067145906944948
[I 2024-04-15 14:32:06,294] Trial 37 finished with value: 0.17563101159880112 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6558408084386204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026524892218781126}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21398210519775457
Fold 2 IBS: 0.22147310463890008
Fold 3 IBS: 0.20484795914030776
Fold 4 IBS: 0.22469082739864527
Fold 5 IBS: 0.21847043318447362
[I 2024-04-15 14:32:15,317] Trial 38 finished with value: 0.21669288591201624 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.5446753536916582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20739916362370578
Fold 2 IBS: 0.1396518555288153
Fold 3 IBS: 0.20101553841044428
Fold 4 IBS: 0.18775948197861053
Fold 5 IBS: 0.17175126099969984
[I 2024-04-15 14:32:25,076] Trial 39 finished with value: 0.18151546010825514 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.7867614811876313, 'max_features': None, 'min_weight_fraction_leaf': 0.11443308942980066}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18099751369940803
Fold 2 IBS: 0.14073570153984705
Fold 3 IBS: 0.19394522353389632
Fold 4 IBS: 0.1899027663588423
Fold 5 IBS: 0.17323048606648403
[I 2024-04-15 14:32:31,161] Trial 40 finished with value: 0.17576233823969556 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.5666383752254781, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07880882141692147}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1711305979532741
Fold 2 IBS: 0.14944644009789185
Fold 3 IBS: 0.1838255715011791
Fold 4 IBS: 0.19303788294761579
Fold 5 IBS: 0.17769110415876982
[I 2024-04-15 14:32:43,056] Trial 41 finished with value: 0.17502631933174614 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 312, 'oob_score': True, 'max_samples': 0.7412385222820266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16945209847062737}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1766253375339953
Fold 2 IBS: 0.14548886613385514
Fold 3 IBS: 0.18810559860305523
Fold 4 IBS: 0.18904619197923261
Fold 5 IBS: 0.17490826493381245
[I 2024-04-15 14:32:58,481] Trial 42 finished with value: 0.17483485183679015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.8639712154486969, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16678569984405386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2139789554890857
Fold 2 IBS: 0.22135558660927104
Fold 3 IBS: 0.2047725162249457
Fold 4 IBS: 0.22463102393551193
Fold 5 IBS: 0.21859845040133852
[I 2024-04-15 14:33:14,325] Trial 43 finished with value: 0.2166673065320306 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.8907059888796497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18785889346357237
Fold 2 IBS: 0.15285827950678846
Fold 3 IBS: 0.18232508298547248
Fold 4 IBS: 0.18846580968340798
Fold 5 IBS: 0.17332117086709029
[I 2024-04-15 14:33:27,986] Trial 44 finished with value: 0.17696584730126633 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.846059951367212, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14736137547860684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1824125215519607
Fold 2 IBS: 0.142066615195965
Fold 3 IBS: 0.1952477350951836
Fold 4 IBS: 0.19275254902170263
Fold 5 IBS: 0.17385783785418485
[I 2024-04-15 14:33:36,400] Trial 45 finished with value: 0.17726745174379938 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.7898763610119546, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11906682715479999}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16985840962071383
Fold 2 IBS: 0.16096525914717788
Fold 3 IBS: 0.18227104026957164
Fold 4 IBS: 0.20281275724564665
Fold 5 IBS: 0.1850460571787144
[I 2024-04-15 14:33:37,527] Trial 46 finished with value: 0.18019070469236487 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.6496915230774891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08221811754778048}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16980857091041326
Fold 2 IBS: 0.15719115142034723
Fold 3 IBS: 0.1767449129839921
Fold 4 IBS: 0.19510331227382113
Fold 5 IBS: 0.1831755952242518
[I 2024-04-15 14:33:46,859] Trial 47 finished with value: 0.17640470856256513 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.8914383434724882, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24824101632322468}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19349637716238946
Fold 2 IBS: 0.18021514079410297
Fold 3 IBS: 0.1797766992061227
Fold 4 IBS: 0.20805913242700583
Fold 5 IBS: 0.19958771263889286
[I 2024-04-15 14:33:59,129] Trial 48 finished with value: 0.19222701244570276 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.9967788477130068, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2029239852759813
Fold 2 IBS: 0.13716491759028818
Fold 3 IBS: 0.2084231173473227
Fold 4 IBS: 0.19129569538138264
Fold 5 IBS: 0.16960756021085094
[I 2024-04-15 14:34:10,750] Trial 49 finished with value: 0.18188305516116512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.6825737614746896, 'max_features': None, 'min_weight_fraction_leaf': 0.020427001696118233}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1847999347983001
Fold 2 IBS: 0.15364870601921565
Fold 3 IBS: 0.1822009992001216
Fold 4 IBS: 0.18809108511963865
Fold 5 IBS: 0.17414367995939478
[I 2024-04-15 14:34:14,924] Trial 50 finished with value: 0.17657688101933416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8644699746287099, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06989429005204871}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17038930280276898
Fold 2 IBS: 0.15348758465747694
Fold 3 IBS: 0.18016675506323593
Fold 4 IBS: 0.1938593087420373
Fold 5 IBS: 0.18099103292628088
[I 2024-04-15 14:34:32,780] Trial 51 finished with value: 0.17577879683836 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.727895633786626, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18327602934679604}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17451701150431106
Fold 2 IBS: 0.14671503382427162
Fold 3 IBS: 0.18683750953876657
Fold 4 IBS: 0.19257094181568649
Fold 5 IBS: 0.17615300496682904
[I 2024-04-15 14:34:47,679] Trial 52 finished with value: 0.17535870032997297 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.7478990221520405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14624323581313917}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17559006537700683
Fold 2 IBS: 0.16972487299848873
Fold 3 IBS: 0.17529653726657532
Fold 4 IBS: 0.19855196165239603
Fold 5 IBS: 0.1851918744321701
[I 2024-04-15 14:35:09,237] Trial 53 finished with value: 0.1808710623453274 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.8074226422105014, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27324344422148944}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17595680778437212
Fold 2 IBS: 0.17008267991566167
Fold 3 IBS: 0.17604437670258266
Fold 4 IBS: 0.19769140576353486
Fold 5 IBS: 0.18734084278780233
[I 2024-04-15 14:35:25,700] Trial 54 finished with value: 0.18142322259079072 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.5775945927656037, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2001668400822587}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16773815898136948
Fold 2 IBS: 0.1576076816374329
Fold 3 IBS: 0.17803399667907918
Fold 4 IBS: 0.19725085339663992
Fold 5 IBS: 0.18451260927365026
[I 2024-04-15 14:35:27,672] Trial 55 finished with value: 0.17702865999363437 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.6303629140203428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16685382022581927}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18003668325471714
Fold 2 IBS: 0.14323357247265056
Fold 3 IBS: 0.19283157086976438
Fold 4 IBS: 0.192092008764836
Fold 5 IBS: 0.17436160978254575
[I 2024-04-15 14:35:34,027] Trial 56 finished with value: 0.17651108902890275 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.7623102674577037, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09861841429774906}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17302493479017875
Fold 2 IBS: 0.1667969562590488
Fold 3 IBS: 0.17568508570553082
Fold 4 IBS: 0.1958388085038477
Fold 5 IBS: 0.18612204667403598
[I 2024-04-15 14:35:46,443] Trial 57 finished with value: 0.1794935663865284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.6746410572190499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19693288454187685
Fold 2 IBS: 0.16031608536235142
Fold 3 IBS: 0.18209014838073903
Fold 4 IBS: 0.18830938207544887
Fold 5 IBS: 0.1722123575079718
[I 2024-04-15 14:35:54,068] Trial 58 finished with value: 0.1799721715736776 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.9493525765812034, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.033039474629030334}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17638204755824788
Fold 2 IBS: 0.14724121981954666
Fold 3 IBS: 0.18830472263321374
Fold 4 IBS: 0.18908125561308473
Fold 5 IBS: 0.17501568142226698
[I 2024-04-15 14:35:56,662] Trial 59 finished with value: 0.175204985409272 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.706317491452594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.011952641009515354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17441654996325617
Fold 2 IBS: 0.16879198972806275
Fold 3 IBS: 0.1747308489003251
Fold 4 IBS: 0.19678299634235394
Fold 5 IBS: 0.18428329935051413
[I 2024-04-15 14:35:59,778] Trial 60 finished with value: 0.1798011368569024 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.4446079220615766, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13552790545628873}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1726966416095679
Fold 2 IBS: 0.14791648216625575
Fold 3 IBS: 0.18587926582625136
Fold 4 IBS: 0.19250544947641468
Fold 5 IBS: 0.1767138327798232
[I 2024-04-15 14:36:08,833] Trial 61 finished with value: 0.17514233437166257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.7350539425199517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15353880193597452}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1784711929725387
Fold 2 IBS: 0.14471049906571562
Fold 3 IBS: 0.19083362219368874
Fold 4 IBS: 0.19321298173368606

Fold 5 IBS: 0.17601995444169838
[I 2024-04-15 14:36:15,907] Trial 62 finished with value: 0.1766496500814655 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.6969767031486694, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11947149985769817}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17325965795999854
Fold 2 IBS: 0.16035062956465257
Fold 3 IBS: 0.17539882197990753
Fold 4 IBS: 0.193362443315604
Fold 5 IBS: 0.1796554283287958
[I 2024-04-15 14:36:23,106] Trial 63 finished with value: 0.17640539622979168 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 311, 'oob_score': True, 'max_samples': 0.6304198495967799, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16702154024396243}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17417602273955624
Fold 2 IBS: 0.1480464954861786
Fold 3 IBS: 0.1861637654245361
Fold 4 IBS: 0.19307278746213727
Fold 5 IBS: 0.17661238768457427
[I 2024-04-15 14:36:28,523] Trial 64 finished with value: 0.1756142917593965 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.8416513210854921, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16738759238643802}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1822613083064998
Fold 2 IBS: 0.1416365045076241
Fold 3 IBS: 0.1960788715196419
Fold 4 IBS: 0.19275645033338762
Fold 5 IBS: 0.1744182820015701
[I 2024-04-15 14:36:34,078] Trial 65 finished with value: 0.17743028333374472 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.7722883894951643, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0665684368743143}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17389086197303102
Fold 2 IBS: 0.16790129559912909
Fold 3 IBS: 0.1751507252355886
Fold 4 IBS: 0.19750324318227722
Fold 5 IBS: 0.18620949704754197
[I 2024-04-15 14:36:41,114] Trial 66 finished with value: 0.18013112460751357 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.5947629158546897, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20025339037463216}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17423384494498612
Fold 2 IBS: 0.14631335780890575
Fold 3 IBS: 0.18861958817402585
Fold 4 IBS: 0.19245950764813075
Fold 5 IBS: 0.175067247621942
[I 2024-04-15 14:36:50,033] Trial 67 finished with value: 0.1753387092395981 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.7217571884559283, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13013771636318264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17535705050457914
Fold 2 IBS: 0.15778179636614245
Fold 3 IBS: 0.17763073839385685
Fold 4 IBS: 0.19018833285814207
Fold 5 IBS: 0.17770479034207873
[I 2024-04-15 14:36:54,913] Trial 68 finished with value: 0.17573254169295985 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.5191868058797825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.047795726630053076}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17480337133090915
Fold 2 IBS: 0.16874159329787056
Fold 3 IBS: 0.17579652970954177
Fold 4 IBS: 0.1923367638029231
Fold 5 IBS: 0.18690613654154167
[I 2024-04-15 14:37:03,821] Trial 69 finished with value: 0.17971687893655724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.18576927332867577, 'max_features': 'log2', 'min_weight_fraction_leaf': 7.114682696795181e-05}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20781268631997615
Fold 2 IBS: 0.13838860575441492
Fold 3 IBS: 0.21122911345717027
Fold 4 IBS: 0.19170717046621447
Fold 5 IBS: 0.16987800654423307
[I 2024-04-15 14:37:13,659] Trial 70 finished with value: 0.18380311650840175 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.8126013453538647, 'max_features': None, 'min_weight_fraction_leaf': 0.10415283732963354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16897127550996938
Fold 2 IBS: 0.15333527019800122
Fold 3 IBS: 0.18108923812924368
Fold 4 IBS: 0.19125151911620464
Fold 5 IBS: 0.1804095239747975
[I 2024-04-15 14:37:21,800] Trial 71 finished with value: 0.17501136538564327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.5965842869794661, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04020616684856252}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16942384334835775
Fold 2 IBS: 0.1534316341977167
Fold 3 IBS: 0.18126076316917372
Fold 4 IBS: 0.1918304245116947
Fold 5 IBS: 0.1797086597106947
[I 2024-04-15 14:37:29,760] Trial 72 finished with value: 0.17513106498752753 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.64967240812612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042859490745800255}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17483538806839433
Fold 2 IBS: 0.15903414917848718
Fold 3 IBS: 0.178305987368802
Fold 4 IBS: 0.18895015857840794
Fold 5 IBS: 0.17674514740069427
[I 2024-04-15 14:37:38,849] Trial 73 finished with value: 0.17557416611895713 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 468, 'oob_score': False, 'max_samples': 0.614601651625123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08656637647813382}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685354387079355
Fold 2 IBS: 0.1519242369397579
Fold 3 IBS: 0.18329403645197254
Fold 4 IBS: 0.19121480234741198
Fold 5 IBS: 0.17959179151928248
[I 2024-04-15 14:37:47,472] Trial 74 finished with value: 0.17491206119327207 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.564394176347414, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0639505821191327}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16870518179470842
Fold 2 IBS: 0.1524006924636778
Fold 3 IBS: 0.1824052463489283
Fold 4 IBS: 0.19198874945374883
Fold 5 IBS: 0.17971814686012724
[I 2024-04-15 14:37:55,729] Trial 75 finished with value: 0.1750436033842381 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.5549716215197416, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06244978633063567}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17388421751906138
Fold 2 IBS: 0.1679541870820109
Fold 3 IBS: 0.17539898304019086
Fold 4 IBS: 0.1953143658823387
Fold 5 IBS: 0.18647747737304407
[I 2024-04-15 14:38:03,725] Trial 76 finished with value: 0.1798058461793292 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.5288500192319384, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016585234890071264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17761169418416847
Fold 2 IBS: 0.16895784550549822
Fold 3 IBS: 0.17542226135379532
Fold 4 IBS: 0.19549660202075014
Fold 5 IBS: 0.18743069872463708
[I 2024-04-15 14:38:11,295] Trial 77 finished with value: 0.18098382035776983 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.3800215746179153, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03735564012092016}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16818314645426713
Fold 2 IBS: 0.15369061634554518
Fold 3 IBS: 0.18213459050433092
Fold 4 IBS: 0.19123211966917278
Fold 5 IBS: 0.17979973767912885
[I 2024-04-15 14:38:20,595] Trial 78 finished with value: 0.17500804213048896 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.4897248144615137, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053996872945124036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1682237549262069
Fold 2 IBS: 0.15295334400832536
Fold 3 IBS: 0.18214608764478374
Fold 4 IBS: 0.19238806563941324
Fold 5 IBS: 0.18028732465861996
[I 2024-04-15 14:38:30,295] Trial 79 finished with value: 0.17519971537546983 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.49575398669591153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06405554874562534}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17507598055558485
Fold 2 IBS: 0.16867091079334554
Fold 3 IBS: 0.1744565827712509
Fold 4 IBS: 0.1954950968251498
Fold 5 IBS: 0.18635102171872073
[I 2024-04-15 14:38:38,900] Trial 80 finished with value: 0.18000991853281037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.43759421275648835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0533463490707784}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1714174399032279
Fold 2 IBS: 0.14887499618081926
Fold 3 IBS: 0.1849640281040515
Fold 4 IBS: 0.1899572218408997
Fold 5 IBS: 0.17713400076306418
[I 2024-04-15 14:38:50,610] Trial 81 finished with value: 0.17446953735841247 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5784234487575245, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10829522154445037}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16877649511183368
Fold 2 IBS: 0.1546883871779083
Fold 3 IBS: 0.18056083236056208
Fold 4 IBS: 0.19133957386634493
Fold 5 IBS: 0.18162520349661385
[I 2024-04-15 14:39:01,051] Trial 82 finished with value: 0.17539809840265258 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5722759399876282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10440976094597362}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685240734239476
Fold 2 IBS: 0.15222241351006804
Fold 3 IBS: 0.1822020345828932
Fold 4 IBS: 0.19079185577835267
Fold 5 IBS: 0.17960640446910925
[I 2024-04-15 14:39:10,943] Trial 83 finished with value: 0.17466935635287414 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.5451307479888213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0724192455670338}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17338079162104056
Fold 2 IBS: 0.15920893592551924
Fold 3 IBS: 0.17825449140901586
Fold 4 IBS: 0.18925769833312683
Fold 5 IBS: 0.17742455682194408
[I 2024-04-15 14:39:22,269] Trial 84 finished with value: 0.17550529482212932 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.5442180702857965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07567351514027787}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1690383568215189
Fold 2 IBS: 0.15230702588653305
Fold 3 IBS: 0.1822765777502009
Fold 4 IBS: 0.19170674176025757
Fold 5 IBS: 0.18006279876989542
[I 2024-04-15 14:39:33,454] Trial 85 finished with value: 0.17507830019768117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.5030563110008609, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09285296477077623}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17784444889141396
Fold 2 IBS: 0.14568494632276702
Fold 3 IBS: 0.18681231725936967
Fold 4 IBS: 0.18938575035357394
Fold 5 IBS: 0.17417653028434565
[I 2024-04-15 14:39:41,528] Trial 86 finished with value: 0.17478079862229406 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.6227373925109708, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11680143459253466}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17320771484108127
Fold 2 IBS: 0.1471439015418838
Fold 3 IBS: 0.1868119711290211
Fold 4 IBS: 0.191522355137527
Fold 5 IBS: 0.17549663792817793
[I 2024-04-15 14:39:50,259] Trial 87 finished with value: 0.17483651611553824 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.6363957788305546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1264522778930551}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.177279146128294
Fold 2 IBS: 0.14462990587422714
Fold 3 IBS: 0.18982364231541823
Fold 4 IBS: 0.19123959493668208
Fold 5 IBS: 0.17462972301152646
[I 2024-04-15 14:40:00,823] Trial 88 finished with value: 0.17552040245322958 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.643212285009443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11042020211203352}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18172829377621072
Fold 2 IBS: 0.15455308362712544
Fold 3 IBS: 0.18079631963918813
Fold 4 IBS: 0.1866909754534505
Fold 5 IBS: 0.17486062534932048
[I 2024-04-15 14:40:10,090] Trial 89 finished with value: 0.17572585956905906 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 379, 'oob_score': False, 'max_samples': 0.6745160130358284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13729294470437828}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17159615871766515
Fold 2 IBS: 0.1492340100734715
Fold 3 IBS: 0.18525391328974408
Fold 4 IBS: 0.19170238188043215
Fold 5 IBS: 0.17723852207113783
[I 2024-04-15 14:40:18,919] Trial 90 finished with value: 0.17500499720649015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6100442323266079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08381032204107067}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17439132896823156
Fold 2 IBS: 0.1476318214680082
Fold 3 IBS: 0.1865038949155308
Fold 4 IBS: 0.19098341263244506
Fold 5 IBS: 0.17516827480713895
[I 2024-04-15 14:40:26,241] Trial 91 finished with value: 0.17493574655827088 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.6220455817398846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12351605327621175}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17132240828700077
Fold 2 IBS: 0.14948366004568905
Fold 3 IBS: 0.1849774655279456
Fold 4 IBS: 0.19091977764974633
Fold 5 IBS: 0.17791613386648897
[I 2024-04-15 14:40:34,419] Trial 92 finished with value: 0.17492388907537415 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.5773252805729456, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1260508695586116}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17523723037867286
Fold 2 IBS: 0.1453570091149411
Fold 3 IBS: 0.18962747105019612
Fold 4 IBS: 0.19107181469212342

Fold 5 IBS: 0.1747309238915691
[I 2024-04-15 14:40:41,282] Trial 93 finished with value: 0.1752048898255005 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.5630698614554802, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0944985972942633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17026943747099219
Fold 2 IBS: 0.15255352423829832
Fold 3 IBS: 0.18160069813968083
Fold 4 IBS: 0.19096533404342483
Fold 5 IBS: 0.1822030877543707
[I 2024-04-15 14:40:50,088] Trial 94 finished with value: 0.17551841632935336 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.5751544947591161, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14409687866880386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17475332961241374
Fold 2 IBS: 0.14521126379405494
Fold 3 IBS: 0.18914044635556457
Fold 4 IBS: 0.19026828870845303
Fold 5 IBS: 0.1744104734429843
[I 2024-04-15 14:40:58,748] Trial 95 finished with value: 0.1747567603826941 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.5892575789175918, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11211324848978509}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21400356610903593
Fold 2 IBS: 0.22204327857369352
Fold 3 IBS: 0.20415553733700337
Fold 4 IBS: 0.2250379696399111
Fold 5 IBS: 0.21815296605159928
[I 2024-04-15 14:41:00,244] Trial 96 finished with value: 0.21667866354224863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.46700128900375126, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35031312034195705}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.173562295845494
Fold 2 IBS: 0.14742220750236526
Fold 3 IBS: 0.18545169450924154
Fold 4 IBS: 0.18866406353263676
Fold 5 IBS: 0.17639414796763403
[I 2024-04-15 14:41:13,623] Trial 97 finished with value: 0.1742988818714743 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.5401266728628165, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11341150154917841}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.179800528231758
Fold 2 IBS: 0.15504407580671617
Fold 3 IBS: 0.18062194922738495
Fold 4 IBS: 0.18693465453878075
Fold 5 IBS: 0.17539368811607456
[I 2024-04-15 14:41:22,424] Trial 98 finished with value: 0.1755589791841429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.5436809153821575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10940615561612807}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18678959754522786
Fold 2 IBS: 0.14275774495321747
Fold 3 IBS: 0.19217915320067025
Fold 4 IBS: 0.18335908765764633
Fold 5 IBS: 0.17253698272333465
[I 2024-04-15 14:41:31,355] Trial 99 finished with value: 0.1755245132160193 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.694819405505868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07480505292477731}. Best is trial 11 with value: 0.17074634120633253.


* Best trial for IBS:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.17074634120633253], datetime_start=datetime.datetime(2024, 4, 15, 14, 27, 7, 880943), datetime_complete=datetime.datetime(2024, 4, 15, 14, 27, 8, 242824), params={'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=11, value=None)


* Best Score for IBS:
 0.17074634120633253

In [48]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.846
train_ibs:  0.171

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=12,
                     max_samples=0.48042970450395145, min_samples_leaf=1,
                     min_samples_split=4,
                     min_weight_fraction_leaf=0.0025914663927405594,
                     n_estimators=289, random_state=123, warm_start=True)

test_cindex:  0.602

RandomSurvivalForest(max_depth=1, max_features='auto', max_leaf_nodes=18,
                     max_samples=0.7351810575897255, min_samples_leaf=11,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.008231293935378081,
                     n_estimators=2, random_state=123)

test_ibs:  0.233

In [52]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:41:32,990] A new study created in memory with name: no-name-60fe6f95-0441-431a-bf7e-5e30f72567f1

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-15 14:41:34,450] Trial 0 finished with value: 0.763120153205612 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:41:38,828] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:41:47,121] Trial 2 finished with value: 0.7549111845989632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:41:47,758] Trial 3 finished with value: 0.7581427541761773 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:41:50,323] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:41:53,406] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:41:54,987] Trial 6 finished with value: 0.7620861007898516 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7276995305164319
[I 2024-04-15 14:41:58,804] Trial 7 finished with value: 0.7433829385982176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.715962441314554
[I 2024-04-15 14:41:59,090] Trial 8 finished with value: 0.7526603922254165 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7206572769953051
[I 2024-04-15 14:42:07,908] Trial 9 finished with value: 0.7327992570997183 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:42:11,662] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:42:13,516] Trial 11 finished with value: 0.7610279984130963 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:42:15,796] Trial 12 finished with value: 0.7656344262692516 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:42:17,762] Trial 13 finished with value: 0.7565522092481783 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-15 14:42:19,352] Trial 14 finished with value: 0.7616650689919885 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7136150234741784
[I 2024-04-15 14:42:20,484] Trial 15 finished with value: 0.7545769177214963 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7656344262692516.

Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.676056338028169
[I 2024-04-15 14:42:22,394] Trial 16 finished with value: 0.7335270596877141 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:42:23,686] Trial 17 finished with value: 0.7591715308548418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:42:25,832] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:42:27,417] Trial 19 finished with value: 0.7663281634231028 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-15 14:42:29,366] Trial 20 finished with value: 0.746722729311177 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8975839614288115, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:42:30,876] Trial 21 finished with value: 0.7629692767153701 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9830051091386647, 'min_weight_fraction_leaf': 0.11961357903200062}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:42:32,286] Trial 22 finished with value: 0.7628892919669691 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8609656753336752, 'min_weight_fraction_leaf': 0.15663178852989545}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-15 14:42:33,938] Trial 23 finished with value: 0.7509593791567746 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.737236690052532, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:42:35,167] Trial 24 finished with value: 0.7611911126952604 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9222263146213784, 'min_weight_fraction_leaf': 0.08957779552546857}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.859375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7136150234741784
[I 2024-04-15 14:42:36,128] Trial 25 finished with value: 0.7561901306130971 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8274383615832067, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:42:44,828] Trial 26 finished with value: 0.7444877442865183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6539680943502474, 'min_weight_fraction_leaf': 0.04317449484749}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:42:46,582] Trial 27 finished with value: 0.7566253755185277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9365238772272462, 'min_weight_fraction_leaf': 0.14306800767196773}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8415178571428571
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:42:48,692] Trial 28 finished with value: 0.7600206204906962 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7383223503010752, 'min_weight_fraction_leaf': 0.20900889157295355}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:42:52,806] Trial 29 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4766061840882204, 'min_weight_fraction_leaf': 0.25297594889320807}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:42:55,121] Trial 30 finished with value: 0.7619426335421767 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.09166005683798992}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-15 14:42:57,095] Trial 31 finished with value: 0.7601328692954678 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9462932212483206, 'min_weight_fraction_leaf': 0.12021009726526694}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:42:59,357] Trial 32 finished with value: 0.760869569103513 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9864877695110971, 'min_weight_fraction_leaf': 0.06164320836318145}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:43:01,840] Trial 33 finished with value: 0.7624746237982056 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9301489258006082, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7230046948356808
[I 2024-04-15 14:43:03,343] Trial 34 finished with value: 0.7567330098622376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9912043386887608, 'min_weight_fraction_leaf': 0.02249172399095729}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:43:08,643] Trial 35 finished with value: 0.7529807806767499 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.766068607890644, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-15 14:43:10,487] Trial 36 finished with value: 0.7591886238684845 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8553115001753557, 'min_weight_fraction_leaf': 0.22873450590105582}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7183098591549296
[I 2024-04-15 14:43:12,568] Trial 37 finished with value: 0.7555796977821257 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6217761713512069, 'min_weight_fraction_leaf': 0.12934411260414114}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-15 14:43:21,733] Trial 38 finished with value: 0.7535108102301846 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 428, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.04910893285740458}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7276995305164319
[I 2024-04-15 14:43:22,590] Trial 39 finished with value: 0.7553157338682244 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8005826243516873, 'min_weight_fraction_leaf': 0.07469351697759873}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7230046948356808
[I 2024-04-15 14:43:24,423] Trial 40 finished with value: 0.7605112688643425 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9569519035429586, 'min_weight_fraction_leaf': 0.2757731212264245}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:43:26,047] Trial 41 finished with value: 0.7609843014176124 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8687619648747806, 'min_weight_fraction_leaf': 0.15295888294766263}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-15 14:43:27,603] Trial 42 finished with value: 0.7638303926085905 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.906955015046886, 'min_weight_fraction_leaf': 0.10454210976347417}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8370535714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:43:29,144] Trial 43 finished with value: 0.7591740994887395 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8217177439443847, 'min_weight_fraction_leaf': 0.10552735389681006}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:43:30,455] Trial 44 finished with value: 0.7612405402767923 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9989309278077574, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-15 14:43:31,760] Trial 45 finished with value: 0.7628719194609885 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9091736520975473, 'min_weight_fraction_leaf': 0.0038012551219620827}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.7347417840375586
[I 2024-04-15 14:43:39,207] Trial 46 finished with value: 0.7501344600750558 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 359, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5368271784486555, 'min_weight_fraction_leaf': 0.10615317714605318}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-15 14:43:39,564] Trial 47 finished with value: 0.7516793229025998 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 31, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9594946112358607, 'min_weight_fraction_leaf': 0.17333335446497328}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-15 14:43:41,435] Trial 48 finished with value: 0.7562519939011765 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7685785296036635, 'min_weight_fraction_leaf': 0.13176023447811921}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5432900432900433
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5738396624472574
Fold 5 C-index: 0.460093896713615
[I 2024-04-15 14:43:43,358] Trial 49 finished with value: 0.5820501126470459 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8880373878399398, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:43:45,384] Trial 50 finished with value: 0.7630008769419695 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7034625855110039, 'min_weight_fraction_leaf': 0.07304621552955944}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:43:47,484] Trial 51 finished with value: 0.7612490374113632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7321671383859141, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:43:49,894] Trial 52 finished with value: 0.7629420794152763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6907063917898906, 'min_weight_fraction_leaf': 0.0661877659346652}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:43:52,983] Trial 53 finished with value: 0.7596563589778932 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 480, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9052538185294309, 'min_weight_fraction_leaf': 0.08508715956661925}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:43:54,827] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.577878588672621, 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7793427230046949
[I 2024-04-15 14:43:56,586] Trial 55 finished with value: 0.7704458139436589 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7999514777179073, 'min_weight_fraction_leaf': 0.035270943770753044}. Best is trial 55 with value: 0.7704458139436589.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.784037558685446
[I 2024-04-15 14:43:58,136] Trial 56 finished with value: 0.771384781079809 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7991467335557068, 'min_weight_fraction_leaf': 0.027992113153361142}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-15 14:44:03,402] Trial 57 finished with value: 0.74717809865806 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 248, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.79672071864693, 'min_weight_fraction_leaf': 0.016889715164357902}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7746478873239436
[I 2024-04-15 14:44:04,878] Trial 58 finished with value: 0.7677971640851675 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.828019859852415, 'min_weight_fraction_leaf': 0.03447642547531156}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7793427230046949
[I 2024-04-15 14:44:06,341] Trial 59 finished with value: 0.7697165233781805 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8346072695502785, 'min_weight_fraction_leaf': 0.0002567835070198393}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:44:07,735] Trial 60 finished with value: 0.7674757615164577 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 321, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6391411801898657, 'min_weight_fraction_leaf': 0.03561049450086254}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:44:09,192] Trial 61 finished with value: 0.7665829043736004 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6492185512714621, 'min_weight_fraction_leaf': 0.03617201704474487}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 14:44:10,980] Trial 62 finished with value: 0.7674728962234336 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 319, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5312924276275225, 'min_weight_fraction_leaf': 0.040385592930900376}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7605633802816901
[I 2024-04-15 14:44:12,650] Trial 63 finished with value: 0.7710730622821746 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5292658633860801, 'min_weight_fraction_leaf': 0.03711866587371772}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 14:44:14,287] Trial 64 finished with value: 0.7657902697781489 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.39806376813911337, 'min_weight_fraction_leaf': 0.03599381902829695}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-15 14:44:15,854] Trial 65 finished with value: 0.7621709115338706 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5323188905088267, 'min_weight_fraction_leaf': 0.010814253491385636}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-15 14:44:17,337] Trial 66 finished with value: 0.7691537029891617 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.49002509944053235, 'min_weight_fraction_leaf': 0.053181149195751426}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:44:18,603] Trial 67 finished with value: 0.7604151188182366 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.43798216039712035, 'min_weight_fraction_leaf': 0.0010098437298928856}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7605633802816901
[I 2024-04-15 14:44:19,691] Trial 68 finished with value: 0.7683829874029711 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6113081575629796, 'min_weight_fraction_leaf': 0.057217831184053644}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-15 14:44:20,877] Trial 69 finished with value: 0.7639295695425288 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5915899101823151, 'min_weight_fraction_leaf': 0.05522041323530981}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:44:22,545] Trial 70 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47632910975325155, 'min_weight_fraction_leaf': 0.35980997926626934}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:44:23,875] Trial 71 finished with value: 0.768254027368253 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6101916618563699, 'min_weight_fraction_leaf': 0.024998041606770292}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:44:25,201] Trial 72 finished with value: 0.7628057101379913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.32440915793159353, 'min_weight_fraction_leaf': 0.018643504112019715}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:44:26,525] Trial 73 finished with value: 0.7656587582763213 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5609478284070107, 'min_weight_fraction_leaf': 0.05622629784226072}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:44:27,647] Trial 74 finished with value: 0.7584779347240282 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5118014483585279, 'min_weight_fraction_leaf': 0.02563279470181265}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:44:28,971] Trial 75 finished with value: 0.7573932258116945 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6069046410719314, 'min_weight_fraction_leaf': 0.08378422745274237}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:44:34,013] Trial 76 finished with value: 0.7521751447219839 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.497864611352535, 'min_weight_fraction_leaf': 0.06709163220470778}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:44:34,949] Trial 77 finished with value: 0.7620487699772043 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 196, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6683682203156043, 'min_weight_fraction_leaf': 0.011300445410194197}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:44:36,169] Trial 78 finished with value: 0.760363871557148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.42677810376705305, 'min_weight_fraction_leaf': 0.052012092584961866}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:44:37,375] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7173081556448422, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.755868544600939
[I 2024-04-15 14:44:38,650] Trial 80 finished with value: 0.7683639336867342 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.35277360385569917, 'min_weight_fraction_leaf': 0.02852600943088988}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:44:39,681] Trial 81 finished with value: 0.7691928560351028 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3390678218166532, 'min_weight_fraction_leaf': 0.03153990098917725}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:44:40,654] Trial 82 finished with value: 0.7646076128469184 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 224, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3230507568153901, 'min_weight_fraction_leaf': 0.0014394857922413185}. Best is trial 56 with value: 0.771384781079809.
Fold 5 C-index: 0.7511737089201878
[I 2024-04-15 14:44:41,745] Trial 83 finished with value: 0.7614147057143738 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.23361689093258667, 'min_weight_fraction_leaf': 0.019775489029462356}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7089201877934272
[I 2024-04-15 14:44:42,877] Trial 84 finished with value: 0.7495893806395312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 260, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27445260818266226, 'min_weight_fraction_leaf': 0.09592965050134614}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:44:44,107] Trial 85 finished with value: 0.758556238262173 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3862488114937627, 'min_weight_fraction_leaf': 0.04471114770202597}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:44:44,992] Trial 86 finished with value: 0.7708567082564886 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 201, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.36377499756925225, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-15 14:44:46,755] Trial 87 finished with value: 0.7565355685297506 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3759670482683807, 'min_weight_fraction_leaf': 0.0767440911470792}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7652582159624414
[I 2024-04-15 14:44:49,627] Trial 88 finished with value: 0.7609903537745347 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.46073886535297426, 'min_weight_fraction_leaf': 0.05833982872177459}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7605633802816901
[I 2024-04-15 14:44:51,132] Trial 89 finished with value: 0.7699832161020457 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.295955749271664, 'min_weight_fraction_leaf': 0.010964572281232194}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.755868544600939
[I 2024-04-15 14:44:51,777] Trial 90 finished with value: 0.75952694664796 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27944226981321685, 'min_weight_fraction_leaf': 0.012928542240062478}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.784037558685446
[I 2024-04-15 14:44:53,240] Trial 91 finished with value: 0.7801238175459491 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3602425648795669, 'min_weight_fraction_leaf': 0.02981466940699433}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 14:44:54,703] Trial 92 finished with value: 0.7662740508689903 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.25077855422842626, 'min_weight_fraction_leaf': 0.04540069770937229}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-15 14:44:56,221] Trial 93 finished with value: 0.7619860192654835 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.34979442362410473, 'min_weight_fraction_leaf': 0.06734177243231611}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:44:57,020] Trial 94 finished with value: 0.7645085743822805 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.193678974775281, 'min_weight_fraction_leaf': 0.010805974584784796}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:44:58,623] Trial 95 finished with value: 0.7709939821242033 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30647854490295495, 'min_weight_fraction_leaf': 0.03078253598240698}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-15 14:45:00,153] Trial 96 finished with value: 0.7702698288265208 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3052686496163978, 'min_weight_fraction_leaf': 0.029515857916013147}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7511737089201878
[I 2024-04-15 14:45:01,904] Trial 97 finished with value: 0.7686062560974729 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30685683165847666, 'min_weight_fraction_leaf': 0.03193125520570377}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7981220657276995
[I 2024-04-15 14:45:03,646] Trial 98 finished with value: 0.7910857462403429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}. Best is trial 98 with value: 0.7910857462403429.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784

[I 2024-04-15 14:45:05,364] A new study created in memory with name: no-name-8243022c-dcb5-4d48-803d-5ba0d9f98cc4

Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 14:45:05,356] Trial 99 finished with value: 0.7902101231341658 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21478988941660257, 'min_weight_fraction_leaf': 0.0040275983337470555}. Best is trial 98 with value: 0.7910857462403429.


* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.7910857462403429], datetime_start=datetime.datetime(2024, 4, 15, 14, 45, 1, 938895), datetime_complete=datetime.datetime(2024, 4, 15, 14, 45, 3, 645630), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for C-index:
 0.7910857462403429

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1894050222499581
Fold 2 IBS: 0.18197094047238005
Fold 3 IBS: 0.18636461603352758
Fold 4 IBS: 0.19277723911134473
Fold 5 IBS: 0.19455867868991514
[I 2024-04-15 14:45:10,980] Trial 0 finished with value: 0.1890152993114251 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-15 14:45:19,624] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20172405646713062
Fold 2 IBS: 0.2032359255005334
Fold 3 IBS: 0.19513408046545
Fold 4 IBS: 0.2118539452893589
Fold 5 IBS: 0.20729390842542533
[I 2024-04-15 14:45:26,135] Trial 2 finished with value: 0.20384838322957965 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20209415878470963
Fold 2 IBS: 0.20376840661760706
Fold 3 IBS: 0.19482805354546556
Fold 4 IBS: 0.21132760062349532
Fold 5 IBS: 0.2062713273884813
[I 2024-04-15 14:45:28,429] Trial 3 finished with value: 0.2036579093919518 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-15 14:45:34,272] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-15 14:45:37,373] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1904913206168486
Fold 2 IBS: 0.18444679148666562
Fold 3 IBS: 0.1856399244213203
Fold 4 IBS: 0.19570316353343864
Fold 5 IBS: 0.19484476324380895
[I 2024-04-15 14:45:43,487] Trial 6 finished with value: 0.19022519266041643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.19248537415224085
Fold 2 IBS: 0.19105800071812176
Fold 3 IBS: 0.19070595715673386
Fold 4 IBS: 0.2001633927865564
Fold 5 IBS: 0.20070302537730883
[I 2024-04-15 14:45:47,913] Trial 7 finished with value: 0.19502315003819234 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20480968165568902
Fold 2 IBS: 0.20484102123135522
Fold 3 IBS: 0.1975354311772608
Fold 4 IBS: 0.21193929006953224
Fold 5 IBS: 0.20806725700632217
[I 2024-04-15 14:45:48,927] Trial 8 finished with value: 0.2054385362280319 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.2113464419407712
Fold 2 IBS: 0.2169269042702578
Fold 3 IBS: 0.2014624387193473
Fold 4 IBS: 0.2214616279249577
Fold 5 IBS: 0.21570168611580814
[I 2024-04-15 14:45:59,269] Trial 9 finished with value: 0.21337981979422843 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-15 14:46:07,034] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1959863918798848
Fold 2 IBS: 0.19656167181968498
Fold 3 IBS: 0.19210822980372252
Fold 4 IBS: 0.2085074674907661
Fold 5 IBS: 0.20360120107474317
[I 2024-04-15 14:46:16,487] Trial 11 finished with value: 0.1993529924137603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.18512904520321427
Fold 2 IBS: 0.1740527886135347
Fold 3 IBS: 0.1861816706148936
Fold 4 IBS: 0.1893061222535103
Fold 5 IBS: 0.18959027778216106
[I 2024-04-15 14:46:26,650] Trial 12 finished with value: 0.18485198089346278 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19581913848034474
Fold 2 IBS: 0.19606584700533666
Fold 3 IBS: 0.18996353898817178
Fold 4 IBS: 0.2052342771852341
Fold 5 IBS: 0.2042479606113508
[I 2024-04-15 14:46:34,800] Trial 13 finished with value: 0.19826615245408763 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19648331141303396
Fold 2 IBS: 0.1983397281797131
Fold 3 IBS: 0.19106070821891877
Fold 4 IBS: 0.20858865485637526
Fold 5 IBS: 0.20490088125230282
[I 2024-04-15 14:46:43,626] Trial 14 finished with value: 0.1998746567840688 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.18485198089346278.

Fold 1 IBS: 0.19593558348243098
Fold 2 IBS: 0.19875475852789654
Fold 3 IBS: 0.1903333352589917
Fold 4 IBS: 0.20748251302147644
Fold 5 IBS: 0.203704702028721
[I 2024-04-15 14:46:48,894] Trial 15 finished with value: 0.19924217846390332 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21249912881980682
Fold 2 IBS: 0.2205333193107399
Fold 3 IBS: 0.2035653160933136
Fold 4 IBS: 0.22350418932951804
Fold 5 IBS: 0.2173028001714802
[I 2024-04-15 14:46:55,913] Trial 16 finished with value: 0.21548095074497176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19183114805047974
Fold 2 IBS: 0.19128424686172338
Fold 3 IBS: 0.18814594086160835
Fold 4 IBS: 0.20499323686954313
Fold 5 IBS: 0.20021013474043506
[I 2024-04-15 14:47:00,757] Trial 17 finished with value: 0.1952929414767579 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-15 14:47:03,172] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.1938760896028742
Fold 2 IBS: 0.19481663520802522
Fold 3 IBS: 0.18987914648212936
Fold 4 IBS: 0.20616644798233227
Fold 5 IBS: 0.20329633873487413
[I 2024-04-15 14:47:08,942] Trial 19 finished with value: 0.19760693160204706 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.20735529929388963
Fold 2 IBS: 0.208787348599295
Fold 3 IBS: 0.20137982249029263
Fold 4 IBS: 0.22312888688520593
Fold 5 IBS: 0.21346429994402807
[I 2024-04-15 14:47:09,425] Trial 20 finished with value: 0.21082313144254225 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.190149663845766
Fold 2 IBS: 0.1836146541541013
Fold 3 IBS: 0.18617574190891484
Fold 4 IBS: 0.19484231855727627
Fold 5 IBS: 0.19454635613742202
[I 2024-04-15 14:47:16,877] Trial 21 finished with value: 0.18986574692069608 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.18788264608767696
Fold 2 IBS: 0.17893614961467227
Fold 3 IBS: 0.18648188730398177
Fold 4 IBS: 0.19163081844739127
Fold 5 IBS: 0.1923382065001444
[I 2024-04-15 14:47:24,021] Trial 22 finished with value: 0.18745394159077333 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.182703884521614
Fold 2 IBS: 0.16927944395517258
Fold 3 IBS: 0.18708643964817723
Fold 4 IBS: 0.18405528016378853
Fold 5 IBS: 0.18780835196581747
[I 2024-04-15 14:47:31,511] Trial 23 finished with value: 0.18218668005091396 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1895746301789297
Fold 2 IBS: 0.18039920275165355
Fold 3 IBS: 0.18517396368706437
Fold 4 IBS: 0.1961580074360814
Fold 5 IBS: 0.195878956164384
[I 2024-04-15 14:47:39,957] Trial 24 finished with value: 0.1894369520436226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19405738204668507
Fold 2 IBS: 0.19184743202663856
Fold 3 IBS: 0.19007884771101807
Fold 4 IBS: 0.20222541889504655
Fold 5 IBS: 0.20019121612149113
[I 2024-04-15 14:47:46,600] Trial 25 finished with value: 0.19568005936017588 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1940402932834844
Fold 2 IBS: 0.19432298692911043
Fold 3 IBS: 0.1892928247871703
Fold 4 IBS: 0.20429929982391268
Fold 5 IBS: 0.2021205628117341
[I 2024-04-15 14:47:55,042] Trial 26 finished with value: 0.19681519352708238 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19637495341237682
Fold 2 IBS: 0.1958296716242794
Fold 3 IBS: 0.19032854761836807
Fold 4 IBS: 0.20681694152044366
Fold 5 IBS: 0.2037201720927651
[I 2024-04-15 14:48:05,111] Trial 27 finished with value: 0.19861405725364661 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1975709578546784
Fold 2 IBS: 0.19829442573017972
Fold 3 IBS: 0.1915470690360173
Fold 4 IBS: 0.21031250675637114
Fold 5 IBS: 0.20365042057523824
[I 2024-04-15 14:48:09,908] Trial 28 finished with value: 0.20027507599049693 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.20387777006226956
Fold 2 IBS: 0.21044805665332703
Fold 3 IBS: 0.1968442774138352
Fold 4 IBS: 0.21672718054203935
Fold 5 IBS: 0.2104572520340109
[I 2024-04-15 14:48:13,893] Trial 29 finished with value: 0.20767090734109636 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.18218668005091396.

Fold 1 IBS: 0.18923073618097216
Fold 2 IBS: 0.17632006586851645
Fold 3 IBS: 0.18707067058836963
Fold 4 IBS: 0.19307240934736852
Fold 5 IBS: 0.19343354994654252
[I 2024-04-15 14:48:19,415] Trial 30 finished with value: 0.18782548638635385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1949036294792145
Fold 2 IBS: 0.1886371865011974
Fold 3 IBS: 0.19117863815442443
Fold 4 IBS: 0.2001198684681372
Fold 5 IBS: 0.19929856633981852
[I 2024-04-15 14:48:25,248] Trial 31 finished with value: 0.19482757778855841 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7284646777879923, 'min_weight_fraction_leaf': 0.03048718971899994}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.18836540230737153
Fold 2 IBS: 0.1781707184035029
Fold 3 IBS: 0.18564681721521098
Fold 4 IBS: 0.19277633701007463
Fold 5 IBS: 0.19331832607908583
[I 2024-04-15 14:48:30,837] Trial 32 finished with value: 0.18765552020304915 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8171100382086772, 'min_weight_fraction_leaf': 0.06242514513187879}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1837243286986642
Fold 2 IBS: 0.1726544375035722
Fold 3 IBS: 0.1857048039781507
Fold 4 IBS: 0.18788491866873833
Fold 5 IBS: 0.18954352546044614
[I 2024-04-15 14:48:39,374] Trial 33 finished with value: 0.18390240286191434 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.905569688846346, 'min_weight_fraction_leaf': 0.06699217911977255}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1801276242273068
Fold 2 IBS: 0.16520339426201733
Fold 3 IBS: 0.18553268896786967
Fold 4 IBS: 0.1845750159169672
Fold 5 IBS: 0.1835692206281775
[I 2024-04-15 14:48:46,223] Trial 34 finished with value: 0.1798015888004677 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.10969593086442025}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18049877857539035
Fold 2 IBS: 0.16663989287720696
Fold 3 IBS: 0.18469182662740596
Fold 4 IBS: 0.18574114889368326
Fold 5 IBS: 0.18477116270355273
[I 2024-04-15 14:48:55,118] Trial 35 finished with value: 0.18046856193544786 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 457, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9462418908074179, 'min_weight_fraction_leaf': 0.11750983562787085}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18037101974860273
Fold 2 IBS: 0.1669625142647935
Fold 3 IBS: 0.18453294697417297
Fold 4 IBS: 0.18631688561897877
Fold 5 IBS: 0.18678549330288546
[I 2024-04-15 14:49:04,511] Trial 36 finished with value: 0.18099377198188668 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.923638047949589, 'min_weight_fraction_leaf': 0.1257504807357439}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17994058405266816
Fold 2 IBS: 0.1669807265270973
Fold 3 IBS: 0.18438556878610593
Fold 4 IBS: 0.18645614257107018
Fold 5 IBS: 0.18554286319286462
[I 2024-04-15 14:49:13,630] Trial 37 finished with value: 0.18066117702596124 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.927527615447799, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18898732734511295
Fold 2 IBS: 0.1878387228485354
Fold 3 IBS: 0.18584838878907442
Fold 4 IBS: 0.20176513401286975
Fold 5 IBS: 0.1980065946518465
[I 2024-04-15 14:49:21,974] Trial 38 finished with value: 0.1924892335294878 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 413, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.22752773294338688}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17998400007564072
Fold 2 IBS: 0.1668284973568401
Fold 3 IBS: 0.1844288585354833
Fold 4 IBS: 0.1864703671417796
Fold 5 IBS: 0.18549779412503536
[I 2024-04-15 14:49:29,733] Trial 39 finished with value: 0.1806419034469558 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 395, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9298380017873809, 'min_weight_fraction_leaf': 0.12443904045417477}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.19739525553280404
Fold 2 IBS: 0.1991580825645237
Fold 3 IBS: 0.1908160522932353
Fold 4 IBS: 0.2108648699893906
Fold 5 IBS: 0.20525415655389037
[I 2024-04-15 14:49:35,169] Trial 40 finished with value: 0.2006976833867688 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8393239125172784, 'min_weight_fraction_leaf': 0.2776601558023945}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18022938402780667
Fold 2 IBS: 0.16672467510224806
Fold 3 IBS: 0.18478016395935146
Fold 4 IBS: 0.18505725419817942
Fold 5 IBS: 0.18499738141995034
[I 2024-04-15 14:49:44,798] Trial 41 finished with value: 0.1803577717415072 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9543142613189195, 'min_weight_fraction_leaf': 0.12203673286244354}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17977178159556786
Fold 2 IBS: 0.1648846924548364
Fold 3 IBS: 0.18522486265052154
Fold 4 IBS: 0.18475497257812473
Fold 5 IBS: 0.18410321441673297
[I 2024-04-15 14:49:57,497] Trial 42 finished with value: 0.17974790473915667 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9452765507108519, 'min_weight_fraction_leaf': 0.11124594841889346}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.19434886045869684
Fold 2 IBS: 0.1937482656990757
Fold 3 IBS: 0.18774938995929302
Fold 4 IBS: 0.2069666602426304
Fold 5 IBS: 0.20174569854155797
[I 2024-04-15 14:50:09,472] Trial 43 finished with value: 0.1969117749802508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503494540371628, 'min_weight_fraction_leaf': 0.16912809120322597}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.17791881709956506
Fold 2 IBS: 0.16086621549432498
Fold 3 IBS: 0.1866107993369831
Fold 4 IBS: 0.18206826755641561
Fold 5 IBS: 0.18254737423971062
[I 2024-04-15 14:50:18,309] Trial 44 finished with value: 0.17800229474539986 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996789958831329, 'min_weight_fraction_leaf': 0.1062495666001656}. Best is trial 44 with value: 0.17800229474539986.

Fold 1 IBS: 0.18107213977138975
Fold 2 IBS: 0.17375539456626857
Fold 3 IBS: 0.18442566650093445
Fold 4 IBS: 0.19068424307356363
Fold 5 IBS: 0.18831741970696433
[I 2024-04-15 14:50:26,643] Trial 45 finished with value: 0.18365097272382416 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9992649320581628, 'min_weight_fraction_leaf': 0.15624439720920977}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.19953982633918327
Fold 2 IBS: 0.19967504623742535
Fold 3 IBS: 0.19245042867286613
Fold 4 IBS: 0.2085347403492104
Fold 5 IBS: 0.20542311562702958
[I 2024-04-15 14:50:36,570] Trial 46 finished with value: 0.20112463144514292 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 471, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8649488262826621, 'min_weight_fraction_leaf': 0.10003378636590125}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18628122203639155
Fold 2 IBS: 0.18394244229194334
Fold 3 IBS: 0.18418434284415144
Fold 4 IBS: 0.2000447066326781
Fold 5 IBS: 0.19669443529653688
[I 2024-04-15 14:50:43,589] Trial 47 finished with value: 0.19022942982034025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 328, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9498767799232638, 'min_weight_fraction_leaf': 0.20999351713918613}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18671807379697955
Fold 2 IBS: 0.1852509952197599
Fold 3 IBS: 0.18550487325289164
Fold 4 IBS: 0.20047588792062881
Fold 5 IBS: 0.19727228734012894
[I 2024-04-15 14:50:53,450] Trial 48 finished with value: 0.19104442350607775 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.797873402462955, 'min_weight_fraction_leaf': 0.1860519578289726}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.1826607073352976
Fold 2 IBS: 0.175421589749594
Fold 3 IBS: 0.18312277636383603
Fold 4 IBS: 0.19167275635552322
Fold 5 IBS: 0.18980799753609187
[I 2024-04-15 14:51:03,824] Trial 49 finished with value: 0.18453716546806856 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 476, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.961215604578711, 'min_weight_fraction_leaf': 0.11365414847803179}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17958611811383737
Fold 2 IBS: 0.17743708698305577
Fold 3 IBS: 0.1852250945699171
Fold 4 IBS: 0.19623907958032022
Fold 5 IBS: 0.19263688422130817
[I 2024-04-15 14:51:06,602] Trial 50 finished with value: 0.18622485269368774 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7701980857578967, 'min_weight_fraction_leaf': 0.13552189689536387}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17789145417182875
Fold 2 IBS: 0.1616433832004363
Fold 3 IBS: 0.1864085525144377
Fold 4 IBS: 0.18238123808283335
Fold 5 IBS: 0.18355417475301875
[I 2024-04-15 14:51:14,615] Trial 51 finished with value: 0.17837576054451096 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 399, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9009463698475542, 'min_weight_fraction_leaf': 0.09217858789465802}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17799920113623321
Fold 2 IBS: 0.1605144874097507
Fold 3 IBS: 0.18702940084671463
Fold 4 IBS: 0.1819808205423802
Fold 5 IBS: 0.18038337030867524
[I 2024-04-15 14:51:22,697] Trial 52 finished with value: 0.1775814560487508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 354, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8951291579049074, 'min_weight_fraction_leaf': 0.08581751823710401}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17775260791357536
Fold 2 IBS: 0.16149694714321464
Fold 3 IBS: 0.18707407916258054
Fold 4 IBS: 0.18274340233986375
Fold 5 IBS: 0.18259760716876144
[I 2024-04-15 14:51:30,793] Trial 53 finished with value: 0.17833292874559917 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.09240390871992925}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17940640525802973
Fold 2 IBS: 0.16245697210383966
Fold 3 IBS: 0.1891181060291726
Fold 4 IBS: 0.18256414899356924
Fold 5 IBS: 0.18141515612084266
[I 2024-04-15 14:51:36,808] Trial 54 finished with value: 0.17899215770109078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8266050067672521, 'min_weight_fraction_leaf': 0.08824574600148365}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19512770880551733
Fold 2 IBS: 0.19505507233319871
Fold 3 IBS: 0.19092891056177175
Fold 4 IBS: 0.20445218046771954
Fold 5 IBS: 0.2016905007036287
[I 2024-04-15 14:51:42,911] Trial 55 finished with value: 0.19745087457436722 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8830194506473868, 'min_weight_fraction_leaf': 0.08551025986155897}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19639982363347272
Fold 2 IBS: 0.19605394572022347
Fold 3 IBS: 0.19089762812749347
Fold 4 IBS: 0.2039025193177431
Fold 5 IBS: 0.20198750112683878
[I 2024-04-15 14:51:47,661] Trial 56 finished with value: 0.19784828358515433 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8305267551869411, 'min_weight_fraction_leaf': 0.08769411360825642}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17994763927738225
Fold 2 IBS: 0.1548261798648236
Fold 3 IBS: 0.19395939238204377
Fold 4 IBS: 0.175460592586965
Fold 5 IBS: 0.1780360580615449
[I 2024-04-15 14:51:54,610] Trial 57 finished with value: 0.1764459724345519 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9047823438465082, 'min_weight_fraction_leaf': 0.052520359548060905}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.21397444187069029
Fold 2 IBS: 0.22136998164786137
Fold 3 IBS: 0.2048209672135687
Fold 4 IBS: 0.22466869218034594
Fold 5 IBS: 0.21857265758585154
[I 2024-04-15 14:52:00,477] Trial 58 finished with value: 0.21668134809966358 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8971095327680366, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17919617267498053
Fold 2 IBS: 0.15724293354129823
Fold 3 IBS: 0.18865418939534942
Fold 4 IBS: 0.17914737264855643
Fold 5 IBS: 0.17930084192384113
[I 2024-04-15 14:52:05,905] Trial 59 finished with value: 0.17670830203680515 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8551879186310293, 'min_weight_fraction_leaf': 0.052198438381039824}. Best is trial 57 with value: 0.1764459724345519.

Fold 1 IBS: 0.17659457791938485
Fold 2 IBS: 0.15948702371575116
Fold 3 IBS: 0.18725320428102982
Fold 4 IBS: 0.18157027728642194
Fold 5 IBS: 0.18138733472020935
[I 2024-04-15 14:52:12,786] Trial 60 finished with value: 0.17725848358455942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 346, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7897702249078459, 'min_weight_fraction_leaf': 0.017004106952235656}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17815851130122365
Fold 2 IBS: 0.15937759601308119
Fold 3 IBS: 0.18671233531081954
Fold 4 IBS: 0.18030514263303932
Fold 5 IBS: 0.18041925981213724
[I 2024-04-15 14:52:20,177] Trial 61 finished with value: 0.1769945690140602 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8618449302748573, 'min_weight_fraction_leaf': 0.05544116405394582}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.189985439243045
Fold 2 IBS: 0.18589864301215556
Fold 3 IBS: 0.1868011652028388
Fold 4 IBS: 0.1963593578324162
Fold 5 IBS: 0.19462526820614628
[I 2024-04-15 14:52:27,635] Trial 62 finished with value: 0.19073397469932035 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7867417360932117, 'min_weight_fraction_leaf': 0.05261239827242224}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17825665056431175
Fold 2 IBS: 0.15873188722190795
Fold 3 IBS: 0.18623232494405856
Fold 4 IBS: 0.1804776675580393
Fold 5 IBS: 0.18054470634521663
[I 2024-04-15 14:52:34,822] Trial 63 finished with value: 0.17684864732670685 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 370, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8646509137730156, 'min_weight_fraction_leaf': 0.021855538175638154}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17870866019509835
Fold 2 IBS: 0.15879041008416891
Fold 3 IBS: 0.1868471374565984
Fold 4 IBS: 0.17989027006562788
Fold 5 IBS: 0.18013032641306964
[I 2024-04-15 14:52:40,969] Trial 64 finished with value: 0.17687336084291264 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8648441638800866, 'min_weight_fraction_leaf': 0.01786212960035921}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17816324436800104
Fold 2 IBS: 0.16489393379706804
Fold 3 IBS: 0.18434438709838466
Fold 4 IBS: 0.1849311299136772
Fold 5 IBS: 0.18219012941004298
[I 2024-04-15 14:52:46,954] Trial 65 finished with value: 0.17890456491743478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 312, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.017748854587234637}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17911936362446912
Fold 2 IBS: 0.16110107360924447
Fold 3 IBS: 0.18681685101625886
Fold 4 IBS: 0.18222885762114663
Fold 5 IBS: 0.18129003273610622
[I 2024-04-15 14:52:52,228] Trial 66 finished with value: 0.17811123572144505 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7615860595939867, 'min_weight_fraction_leaf': 0.01711923253055358}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19752620497233223
Fold 2 IBS: 0.1978697596463517
Fold 3 IBS: 0.19204767218293306
Fold 4 IBS: 0.20544650914067045
Fold 5 IBS: 0.20224204696962983
[I 2024-04-15 14:52:58,310] Trial 67 finished with value: 0.19902643858238345 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6948127421387615, 'min_weight_fraction_leaf': 0.0007645315715799281}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18980037835825866
Fold 2 IBS: 0.18504474080399536
Fold 3 IBS: 0.18675479711869114
Fold 4 IBS: 0.19583872452973888
Fold 5 IBS: 0.1964614031322392
[I 2024-04-15 14:53:03,505] Trial 68 finished with value: 0.19078000878858464 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7554408511314311, 'min_weight_fraction_leaf': 0.05091993963276509}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19466218577890979
Fold 2 IBS: 0.19389682402255248
Fold 3 IBS: 0.1911241110746692
Fold 4 IBS: 0.2034533752298619
Fold 5 IBS: 0.20173582211641464
[I 2024-04-15 14:53:10,599] Trial 69 finished with value: 0.19697446364448162 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8049955125325536, 'min_weight_fraction_leaf': 0.06630598317301307}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18081283621129376
Fold 2 IBS: 0.16107815895963368
Fold 3 IBS: 0.18537244320497517
Fold 4 IBS: 0.18258777899134426
Fold 5 IBS: 0.1815710558255509
[I 2024-04-15 14:53:14,253] Trial 70 finished with value: 0.17828445463855955 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8704614691107458, 'min_weight_fraction_leaf': 0.03817571210017591}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.1784816385243448
Fold 2 IBS: 0.15527940159437076
Fold 3 IBS: 0.189332198745705
Fold 4 IBS: 0.17821728855635274
Fold 5 IBS: 0.17857494171269278
[I 2024-04-15 14:53:20,628] Trial 71 finished with value: 0.17597709382669321 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8554024477419847, 'min_weight_fraction_leaf': 0.025336147177118625}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17798712426248403
Fold 2 IBS: 0.15484687758413454
Fold 3 IBS: 0.19067949460417397
Fold 4 IBS: 0.17810023131975267
Fold 5 IBS: 0.17841198739744782
[I 2024-04-15 14:53:27,167] Trial 72 finished with value: 0.1760051430335986 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8330512937031878, 'min_weight_fraction_leaf': 0.018742428478884406}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17863483477490216
Fold 2 IBS: 0.1551139005400038
Fold 3 IBS: 0.18916719727949505
Fold 4 IBS: 0.17811149370150642
Fold 5 IBS: 0.1783525956517838
[I 2024-04-15 14:53:33,396] Trial 73 finished with value: 0.17587600438953827 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8535353080113882, 'min_weight_fraction_leaf': 0.02393524919371511}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17931869016352942
Fold 2 IBS: 0.15516920228584516
Fold 3 IBS: 0.19388065315077987
Fold 4 IBS: 0.17839512488731568
Fold 5 IBS: 0.17847323379272784
[I 2024-04-15 14:53:38,703] Trial 74 finished with value: 0.1770473808560396 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8501055473932629, 'min_weight_fraction_leaf': 0.028866969062217605}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.21400073415496554
Fold 2 IBS: 0.2208296768873117
Fold 3 IBS: 0.20504439468604338
Fold 4 IBS: 0.22482948519570425
Fold 5 IBS: 0.21793226667188703
[I 2024-04-15 14:53:44,420] Trial 75 finished with value: 0.21652731151918242 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.28939609623192764, 'min_weight_fraction_leaf': 0.38792353869222}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18092605908791307
Fold 2 IBS: 0.1626714178491272
Fold 3 IBS: 0.1886398695722679
Fold 4 IBS: 0.18093264680250482
Fold 5 IBS: 0.18045471816506836
[I 2024-04-15 14:53:48,837] Trial 76 finished with value: 0.17872494229537628 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827568227091456, 'min_weight_fraction_leaf': 0.07075108588012974}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17853049514002048
Fold 2 IBS: 0.1606985623136455
Fold 3 IBS: 0.18934483196588067
Fold 4 IBS: 0.18117152161929295
Fold 5 IBS: 0.18168995291214574
[I 2024-04-15 14:53:53,859] Trial 77 finished with value: 0.17828707279019707 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 253, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8619520401496605, 'min_weight_fraction_leaf': 0.0541974809924827}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19018486273820845
Fold 2 IBS: 0.18580998501512688
Fold 3 IBS: 0.18646870485036496
Fold 4 IBS: 0.20416606516994676
Fold 5 IBS: 0.1976686334381368
[I 2024-04-15 14:54:00,239] Trial 78 finished with value: 0.19285965024235677 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4023122117577047, 'min_weight_fraction_leaf': 0.011653305300887117}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18468957100688832
Fold 2 IBS: 0.16220991806931515
Fold 3 IBS: 0.18433081379618457
Fold 4 IBS: 0.17919815038465237
Fold 5 IBS: 0.18126334949504005
[I 2024-04-15 14:54:05,554] Trial 79 finished with value: 0.1783383605504161 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.03184523795085815}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17809409767141368
Fold 2 IBS: 0.16747623448062568
Fold 3 IBS: 0.18492844526895663
Fold 4 IBS: 0.18608517724457674
Fold 5 IBS: 0.18436399027788122
[I 2024-04-15 14:54:11,716] Trial 80 finished with value: 0.18018958898869078 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7484656416215983, 'min_weight_fraction_leaf': 0.04261824663727039}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17861172388733232
Fold 2 IBS: 0.15579353335819895
Fold 3 IBS: 0.1930699509858784
Fold 4 IBS: 0.17862157523488698
Fold 5 IBS: 0.17918780109521346
[I 2024-04-15 14:54:17,381] Trial 81 finished with value: 0.17705691691230202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 263, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8580633834636456, 'min_weight_fraction_leaf': 0.026226351015522897}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17739332474625047
Fold 2 IBS: 0.15403352099493925
Fold 3 IBS: 0.19030462796552475
Fold 4 IBS: 0.17855931327525473
Fold 5 IBS: 0.1790999880755793
[I 2024-04-15 14:54:24,354] Trial 82 finished with value: 0.1758781550115097 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8118689779244362, 'min_weight_fraction_leaf': 0.0010966926240786878}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1773851694171574
Fold 2 IBS: 0.16253921619926498
Fold 3 IBS: 0.18775729750357517
Fold 4 IBS: 0.1836022417123993
Fold 5 IBS: 0.18177710952263798
[I 2024-04-15 14:54:30,421] Trial 83 finished with value: 0.17861220687100693 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8057382985870164, 'min_weight_fraction_leaf': 0.009258817492808987}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1854433030470413
Fold 2 IBS: 0.17681758475146342
Fold 3 IBS: 0.18419070581251012
Fold 4 IBS: 0.19690664360230137
Fold 5 IBS: 0.19542658681834563
[I 2024-04-15 14:54:35,936] Trial 84 finished with value: 0.18775696480633236 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.00018800640948312233}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19527212215204012
Fold 2 IBS: 0.19258034396176488
Fold 3 IBS: 0.19043822340063868
Fold 4 IBS: 0.202063421121186
Fold 5 IBS: 0.2007148431354912
[I 2024-04-15 14:54:42,224] Trial 85 finished with value: 0.19621379075422415 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9164856547650563, 'min_weight_fraction_leaf': 0.04956990041330743}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1784741230904449
Fold 2 IBS: 0.16087953939758443
Fold 3 IBS: 0.1866329755757358
Fold 4 IBS: 0.18365448231497417
Fold 5 IBS: 0.1817122965130897
[I 2024-04-15 14:54:48,396] Trial 86 finished with value: 0.1782706833783658 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8799886531366731, 'min_weight_fraction_leaf': 0.0714128496838598}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18097049161570794
Fold 2 IBS: 0.1577854964552635
Fold 3 IBS: 0.18632859616594455
Fold 4 IBS: 0.17862370973831698
Fold 5 IBS: 0.1800955319809405
[I 2024-04-15 14:54:53,905] Trial 87 finished with value: 0.17676076519123468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8197308829626436, 'min_weight_fraction_leaf': 0.02805135094342286}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19437352689769452
Fold 2 IBS: 0.1865309874000275
Fold 3 IBS: 0.19048273944837096
Fold 4 IBS: 0.19874750141792227
Fold 5 IBS: 0.19780307418997603
[I 2024-04-15 14:54:59,358] Trial 88 finished with value: 0.19358756587079823 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 283, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8170223392194952, 'min_weight_fraction_leaf': 0.026015865108324397}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1843070555126035
Fold 2 IBS: 0.16138922163775485
Fold 3 IBS: 0.184029881060334
Fold 4 IBS: 0.18094300604589247
Fold 5 IBS: 0.18208306151695186
[I 2024-04-15 14:55:03,443] Trial 89 finished with value: 0.17855044515470733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.709051290189657, 'min_weight_fraction_leaf': 0.03884059880747235}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.18417873567489768
Fold 2 IBS: 0.17215507074054423
Fold 3 IBS: 0.18759974758071274
Fold 4 IBS: 0.1889870504957803
Fold 5 IBS: 0.18950903071510605
[I 2024-04-15 14:55:08,534] Trial 90 finished with value: 0.1844859270414082 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 262, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9722689668575789, 'min_weight_fraction_leaf': 0.013698489831834436}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17828049657703648
Fold 2 IBS: 0.15670442146325114
Fold 3 IBS: 0.1885595963781235
Fold 4 IBS: 0.17837564239035944
Fold 5 IBS: 0.17924664597888262
[I 2024-04-15 14:55:14,681] Trial 91 finished with value: 0.17623336055753064 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396105042050885, 'min_weight_fraction_leaf': 0.053257094236011215}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17808001067342502
Fold 2 IBS: 0.15510139507880186
Fold 3 IBS: 0.18938170342854968
Fold 4 IBS: 0.1775338584977204
Fold 5 IBS: 0.17890319352130446
[I 2024-04-15 14:55:20,983] Trial 92 finished with value: 0.17580003223996027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17659770951694037
Fold 2 IBS: 0.16139548906489803
Fold 3 IBS: 0.1883833499377513
Fold 4 IBS: 0.18122376165938103
Fold 5 IBS: 0.18108443878413408
[I 2024-04-15 14:55:27,771] Trial 93 finished with value: 0.17773694979262095 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7779337650340382, 'min_weight_fraction_leaf': 0.07493855611907659}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1788420501389833
Fold 2 IBS: 0.1563664608382856
Fold 3 IBS: 0.1914656292286683
Fold 4 IBS: 0.17846880498246692
Fold 5 IBS: 0.17925187035417264
[I 2024-04-15 14:55:32,630] Trial 94 finished with value: 0.17687896310851536 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8379618640137403, 'min_weight_fraction_leaf': 0.06135463764973173}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.18233221300286004
Fold 2 IBS: 0.1548941049902076
Fold 3 IBS: 0.1911036971629455
Fold 4 IBS: 0.17526110217876542
Fold 5 IBS: 0.17738838491733422
[I 2024-04-15 14:55:38,830] Trial 95 finished with value: 0.17619590045042255 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9112906365218221, 'min_weight_fraction_leaf': 0.035312691708068014}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.19307487236591833
Fold 2 IBS: 0.1896720972205889
Fold 3 IBS: 0.189921274941199
Fold 4 IBS: 0.19850258678674562
Fold 5 IBS: 0.19947771844377382
[I 2024-04-15 14:55:44,126] Trial 96 finished with value: 0.19412970995164514 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.915276824625892, 'min_weight_fraction_leaf': 0.043225362789876695}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17892075643860444
Fold 2 IBS: 0.15510444608753537
Fold 3 IBS: 0.19306794455023804
Fold 4 IBS: 0.17799888388058782
Fold 5 IBS: 0.1791674987979104
[I 2024-04-15 14:55:49,858] Trial 97 finished with value: 0.17685190595097522 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6707252385790339, 'min_weight_fraction_leaf': 0.03691531290573905}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.20874228003675835
Fold 2 IBS: 0.21425684765888878
Fold 3 IBS: 0.19860629371051958
Fold 4 IBS: 0.21913583881591187
Fold 5 IBS: 0.21337794366871632
[I 2024-04-15 14:55:55,712] Trial 98 finished with value: 0.210823840778159 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7396489612918897, 'min_weight_fraction_leaf': 0.3157312701103638}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1810496922027384
Fold 2 IBS: 0.15501841966956653
Fold 3 IBS: 0.19245123255364907
Fold 4 IBS: 0.17446547560484074
Fold 5 IBS: 0.17710424236035277
[I 2024-04-15 14:56:01,390] Trial 99 finished with value: 0.1760178124782295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8849892919469375, 'min_weight_fraction_leaf': 0.007259167100140962}. Best is trial 92 with value: 0.17580003223996027.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.17580003223996027], datetime_start=datetime.datetime(2024, 4, 15, 14, 55, 14, 687627), datetime_complete=datetime.datetime(2024, 4, 15, 14, 55, 20, 982142), params={'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=92, value=None)


* Best Score for IBS:
 0.17580003223996027

In [54]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.176

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=19, max_features=1, max_leaf_nodes=12,
                   max_samples=0.21404335777324493, min_samples_leaf=1,
                   min_samples_split=4,
                   min_weight_fraction_leaf=0.0013133682808468272,
                   n_estimators=405, random_state=123, warm_start=True)

C-index score: 0.572

ExtraSurvivalTrees(max_depth=14, max_features=None, max_leaf_nodes=6,
                   max_samples=0.8396800309305413, min_samples_leaf=5,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.02494499808293557,
                   n_estimators=305, oob_score=True, random_state=123)

IBS: 0.221

In [58]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:56:03,866] A new study created in memory with name: no-name-716f8b5d-efe7-4ee0-bfd9-28c07b2c527e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:56:34,073] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:56:49,999] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:57:05,366] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:57:30,634] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:57:40,403] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:57:42,887] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:58:08,425] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:58:15,716] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:58:16,965] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.784037558685446
[I 2024-04-15 14:59:29,206] Trial 9 finished with value: 0.7610259439316011 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.7253521126760564
[I 2024-04-15 15:01:15,810] Trial 10 finished with value: 0.6762046627675529 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:03:11,161] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7887323943661971
[I 2024-04-15 15:04:50,061] Trial 12 finished with value: 0.7542227664538642 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:05:37,954] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:06:46,698] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:07:58,604] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:09:00,885] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:11:26,258] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:14:12,187] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:14:17,977] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:15:19,013] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6995305164319249
[I 2024-04-15 15:17:40,634] Trial 21 finished with value: 0.6762505605169181 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.7535211267605634
[I 2024-04-15 15:19:38,709] Trial 22 finished with value: 0.713908524620727 and parameters: {'subsample': 0.8956069884856214, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2154325997461391, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.38657871816113815, 'max_features': 'auto', 'min_impurity_decrease': 5.581115247824534e-07, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:21:24,681] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7743503496065262, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.31930849090648333, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9663328483036315, 'min_weight_fraction_leaf': 0.441052304834414, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:22:50,185] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8969825748215434, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21976013005558012, 'n_estimators': 340, 'criterion': 'squared_error', 'ccp_alpha': 0.785180332493211, 'min_weight_fraction_leaf': 0.2669492013977464, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:24:29,806] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8840318412875596, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.27382248438555523, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 2.0183033060186855, 'min_weight_fraction_leaf': 0.33643534713187806, 'max_features': 'auto', 'min_impurity_decrease': 5.889654690360788e-06, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:26:00,845] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7565765917190008, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.4300954216773497, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6678836557349488, 'min_weight_fraction_leaf': 0.06207030473994396, 'max_features': 1, 'min_impurity_decrease': 7.622421032390112e-07, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:28:30,251] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.322970332048742, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 5.9472530603001, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 7.551787280023211e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:29:11,962] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.5232204998663266, 'n_estimators': 326, 'criterion': 'squared_error', 'ccp_alpha': 4.188554251555486, 'min_weight_fraction_leaf': 0.43612805409636834, 'max_features': 0.1, 'min_impurity_decrease': 3.2161459286083955e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:29:20,445] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.32499045544570565, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 2.694991982922698, 'min_weight_fraction_leaf': 0.37973053029520576, 'max_features': 'log2', 'min_impurity_decrease': 1.983769791843576e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:29:51,086] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.1618733123667288, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.29835074442775955, 'max_features': 'auto', 'min_impurity_decrease': 3.855449012555335e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.7511737089201878
[I 2024-04-15 15:31:48,535] Trial 31 finished with value: 0.7183781009689083 and parameters: {'subsample': 0.9458857893837966, 'learning_rate': 0.016420196712320707, 'dropout_rate': 0.2035906465216125, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.36089352993330637, 'max_features': 'auto', 'min_impurity_decrease': 4.318534340206297e-07, 'validation_fraction': 0.9595045281115817, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7793427230046949
[I 2024-04-15 15:33:52,531] Trial 32 finished with value: 0.7475960929275194 and parameters: {'subsample': 0.8638126341310897, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.22569622133720652, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.019083703384414813, 'min_weight_fraction_leaf': 0.351646089861356, 'max_features': 'auto', 'min_impurity_decrease': 1.0352347378444166e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:35:51,239] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9565444847948921, 'learning_rate': 0.016942278074178134, 'dropout_rate': 0.26584476281814184, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.3586353681932053, 'max_features': 'auto', 'min_impurity_decrease': 1.3326513674306949e-07, 'validation_fraction': 0.8389914767654065, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:37:34,283] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7038358300021869, 'learning_rate': 0.026650337425697362, 'dropout_rate': 0.369220485987212, 'n_estimators': 472, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8672217172879074, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0420752279999204e-07, 'validation_fraction': 0.9169827663346786, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:38:55,674] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.8615302123878027, 'learning_rate': 0.016287667469869524, 'dropout_rate': 0.16621310899612352, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1524333738759642, 'min_weight_fraction_leaf': 0.16211724647631331, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:39:43,081] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6682496627875864, 'learning_rate': 0.030254735591726832, 'dropout_rate': 0.29166011812932907, 'n_estimators': 299, 'criterion': 'squared_error', 'ccp_alpha': 0.48701662298918014, 'min_weight_fraction_leaf': 0.24844276308137436, 'max_features': 'auto', 'min_impurity_decrease': 2.2923203534620568e-05, 'validation_fraction': 0.8152696073327098, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:40:17,652] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7883126136564298, 'learning_rate': 0.02225236619873, 'dropout_rate': 0.7511928761026783, 'n_estimators': 408, 'criterion': 'squared_error', 'ccp_alpha': 1.198246212835568, 'min_weight_fraction_leaf': 0.42198945643308866, 'max_features': None, 'min_impurity_decrease': 8.54824079758415e-06, 'validation_fraction': 0.36353542989298265, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:42:02,659] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0010786268484829992, 'dropout_rate': 0.4076069474884072, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.295727563116735, 'max_features': 'auto', 'min_impurity_decrease': 1.0214527419957568e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:43:29,110] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.041857701576065075, 'dropout_rate': 0.3444296796757608, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.49564059074376393, 'max_features': 1, 'min_impurity_decrease': 2.966650399906854e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:44:31,321] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5863013406787322, 'learning_rate': 0.007311607072090859, 'dropout_rate': 0.22290618957651392, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 0.5271854997531392, 'min_weight_fraction_leaf': 0.2674270064426415, 'max_features': 'auto', 'min_impurity_decrease': 2.2073664358493507e-07, 'validation_fraction': 0.6520524706411407, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 10}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6455399061032864
[I 2024-04-15 15:44:31,711] Trial 41 finished with value: 0.6429727820316606 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.01362396235680392, 'dropout_rate': 0.2062435369784147, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.01657550447328801, 'min_weight_fraction_leaf': 0.3505399688940837, 'max_features': 'auto', 'min_impurity_decrease': 3.2101990795082183e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6774891774891775
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7394366197183099
[I 2024-04-15 15:46:22,821] Trial 42 finished with value: 0.7155999282604174 and parameters: {'subsample': 0.8533107407997301, 'learning_rate': 0.007773927115663986, 'dropout_rate': 0.13112078909045524, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.002608770948556355, 'min_weight_fraction_leaf': 0.4128432753433128, 'max_features': 'auto', 'min_impurity_decrease': 5.944083612909987e-07, 'validation_fraction': 0.8846352497042296, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:48:26,669] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8537828670002746, 'learning_rate': 0.006387564095638705, 'dropout_rate': 0.14103084365529428, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.817694027019807, 'min_weight_fraction_leaf': 0.4055199685421495, 'max_features': 'auto', 'min_impurity_decrease': 1.0127188716001679e-07, 'validation_fraction': 0.8846775181555923, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:49:52,074] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9979692688170061, 'learning_rate': 0.018866368595143467, 'dropout_rate': 0.13470507680405208, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.1995459782383484, 'min_weight_fraction_leaf': 0.46282880746501454, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7785221066313981, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:51:29,712] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.9423581992051376, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.1841937912472535, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.415353860249426, 'min_weight_fraction_leaf': 0.21565594544774125, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.9726137478639892, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:51:40,710] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8422605515062627, 'learning_rate': 0.023740342140917903, 'dropout_rate': 0.9694253886674298, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 6.2946137459239395, 'min_weight_fraction_leaf': 0.32020062193032595, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0058604443673675e-07, 'validation_fraction': 0.8666993731020032, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:53:30,999] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.8213077858159359, 'learning_rate': 0.006066129837698666, 'dropout_rate': 0.2502078347914406, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 1.0929789618945918, 'min_weight_fraction_leaf': 0.37165158771817175, 'max_features': 'log2', 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.7292699872905781, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:54:15,241] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7434813106553043, 'learning_rate': 0.014252633864159536, 'dropout_rate': 0.10308804442602489, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 0.43583456106887075, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 'auto', 'min_impurity_decrease': 1.1669342789968816e-06, 'validation_fraction': 0.9922167438954732, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:54:34,120] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7918904765497661, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.46610361399140793, 'max_features': None, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8725986413596462, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:55:47,115] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9263228105960017, 'learning_rate': 0.03241286314321831, 'dropout_rate': 0.28503824367896063, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.3883012665777896, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 5.669547081135241e-07, 'validation_fraction': 0.21769072749948642, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7347417840375586
[I 2024-04-15 15:57:23,904] Trial 51 finished with value: 0.7185570650203711 and parameters: {'subsample': 0.8666208085311428, 'learning_rate': 0.010299237341157315, 'dropout_rate': 0.22486517268782114, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.01237319335130728, 'min_weight_fraction_leaf': 0.40520668278071015, 'max_features': 'auto', 'min_impurity_decrease': 4.3165690993230386e-07, 'validation_fraction': 0.9299180470052416, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7279411764705882
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-15 15:58:53,057] Trial 52 finished with value: 0.7047318894129233 and parameters: {'subsample': 0.862657875185063, 'learning_rate': 0.008306104796295998, 'dropout_rate': 0.2416732200644876, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.03660243985093782, 'min_weight_fraction_leaf': 0.42223276607292903, 'max_features': 'auto', 'min_impurity_decrease': 1.9405719092810494e-07, 'validation_fraction': 0.9395823090270392, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:00:38,900] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.967375882472721, 'learning_rate': 0.001394900878889816, 'dropout_rate': 0.1429837848690379, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.45374308869283775, 'min_weight_fraction_leaf': 0.4108404544677715, 'max_features': 'auto', 'min_impurity_decrease': 4.0655981745194066e-07, 'validation_fraction': 0.8259835575505652, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:02:19,855] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8134129014758551, 'learning_rate': 0.019733381620994493, 'dropout_rate': 0.18641432881009587, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.9596523069530926, 'min_weight_fraction_leaf': 0.2970013736941614, 'max_features': 'auto', 'min_impurity_decrease': 1.1580334563112213e-06, 'validation_fraction': 0.8996663522529539, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:03:11,894] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9195938698764112, 'learning_rate': 0.015173363534313505, 'dropout_rate': 0.3034930079612927, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.35259963018802765, 'min_weight_fraction_leaf': 0.36508275980555405, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.9545460877946491, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:04:31,099] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.5150383761242161, 'learning_rate': 0.004332984500606809, 'dropout_rate': 0.23996644019536584, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6264958328369468, 'min_weight_fraction_leaf': 0.3385656815459147, 'max_features': 'auto', 'min_impurity_decrease': 5.479611541769766e-07, 'validation_fraction': 0.9991586611408243, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.6666666666666666
[I 2024-04-15 16:06:06,935] Trial 57 finished with value: 0.7056496649292628 and parameters: {'subsample': 0.8773751542246392, 'learning_rate': 0.008949552280352413, 'dropout_rate': 0.35136020576582316, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.001936457287774803, 'min_weight_fraction_leaf': 0.46006445679681335, 'max_features': 1, 'min_impurity_decrease': 4.834524920287448e-06, 'validation_fraction': 0.5189236064802895, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:07:57,099] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.6843244921733918, 'learning_rate': 0.0253510504546932, 'dropout_rate': 0.12033118040350205, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 1.625653153563989, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'auto', 'min_impurity_decrease': 1.5983704938418812e-07, 'validation_fraction': 0.7886847055500306, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:08:57,687] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.021369220605781735, 'dropout_rate': 0.4274904250363094, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.4410912197424578, 'max_features': 0.1, 'min_impurity_decrease': 3.251577586017116e-07, 'validation_fraction': 0.8548774558884649, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:09:15,106] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.18796169351263226, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 2.934583742024675, 'min_weight_fraction_leaf': 0.22745666702108258, 'max_features': 'log2', 'min_impurity_decrease': 1.7635925207609514e-06, 'validation_fraction': 0.8928900471979833, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:10:50,453] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.9082876532055691, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.22106826324294734, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22580244780696104, 'min_weight_fraction_leaf': 0.39038531498517337, 'max_features': 'auto', 'min_impurity_decrease': 6.513707268856941e-07, 'validation_fraction': 0.9307105316317981, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:12:47,417] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.9763302214447585, 'learning_rate': 0.01082289338801184, 'dropout_rate': 0.16671702405067812, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.7562237450148781, 'min_weight_fraction_leaf': 0.4020635676726066, 'max_features': 'auto', 'min_impurity_decrease': 9.006731163870761e-07, 'validation_fraction': 0.9167969646120265, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.744131455399061
[I 2024-04-15 16:14:32,876] Trial 63 finished with value: 0.7378685391643164 and parameters: {'subsample': 0.8703294082808486, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.2614766602947102, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.37595194847909125, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.9646429973127362, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:16:28,586] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7961678718772995, 'learning_rate': 0.015415575577593231, 'dropout_rate': 0.262554001169913, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.2777045506790212, 'min_weight_fraction_leaf': 0.33434502833689206, 'max_features': 'auto', 'min_impurity_decrease': 3.33975749875224e-07, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:18:11,192] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8385594937622445, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.30265220308227164, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.29056375204041135, 'min_weight_fraction_leaf': 0.28320128906700315, 'max_features': 'auto', 'min_impurity_decrease': 1.5031409606569138e-07, 'validation_fraction': 0.962588947418926, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:19:46,094] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8825125214383175, 'learning_rate': 0.01896416177644482, 'dropout_rate': 0.3845297883432178, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 2.1083391199212573, 'min_weight_fraction_leaf': 0.37068365181765817, 'max_features': 'auto', 'min_impurity_decrease': 2.926750067783851e-07, 'validation_fraction': 0.8532835495181553, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:21:07,805] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4585158632928328, 'learning_rate': 0.014185974978345665, 'dropout_rate': 0.20713420518497186, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.31472432527464905, 'max_features': 'sqrt', 'min_impurity_decrease': 4.927665175660364e-07, 'validation_fraction': 0.9061207180731781, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:22:37,489] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.9444579521154932, 'learning_rate': 0.003984164164187884, 'dropout_rate': 0.3349732603740458, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 1.078654850128927, 'min_weight_fraction_leaf': 0.1817947096952169, 'max_features': 'auto', 'min_impurity_decrease': 1.3822768751381375e-06, 'validation_fraction': 0.9998779842696178, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:23:24,572] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7351244679725103, 'learning_rate': 0.021607496405331474, 'dropout_rate': 0.6578270843665299, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.41822793529640967, 'max_features': 'auto', 'min_impurity_decrease': 7.981891756908656e-06, 'validation_fraction': 0.8252701554197789, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7535211267605634
[I 2024-04-15 16:25:08,374] Trial 70 finished with value: 0.7431871031407425 and parameters: {'subsample': 0.7696833733505561, 'learning_rate': 0.009479076517851487, 'dropout_rate': 0.27892959003506596, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.010016393064755276, 'min_weight_fraction_leaf': 0.38115268230138605, 'max_features': None, 'min_impurity_decrease': 1.0506244573812146e-07, 'validation_fraction': 0.7475037972329144, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7065727699530516
[I 2024-04-15 16:26:46,332] Trial 71 finished with value: 0.722533881479949 and parameters: {'subsample': 0.7726307722867607, 'learning_rate': 0.009349407530944867, 'dropout_rate': 0.272889788803047, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.43478396682346765, 'max_features': None, 'min_impurity_decrease': 1.417211124243175e-07, 'validation_fraction': 0.6051329974465358, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:28:51,923] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7701057123127394, 'learning_rate': 0.009957649760499912, 'dropout_rate': 0.27848137285412433, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.7357633085189087, 'min_weight_fraction_leaf': 0.37805750469189997, 'max_features': None, 'min_impurity_decrease': 1.0230782331935316e-07, 'validation_fraction': 0.6095946706874, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:30:17,971] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.82176382526325, 'learning_rate': 0.05058817311100894, 'dropout_rate': 0.23811185280532784, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.35666680166132303, 'min_weight_fraction_leaf': 0.4363333364980036, 'max_features': None, 'min_impurity_decrease': 1.4978008424793533e-07, 'validation_fraction': 0.6393756125190079, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:31:33,721] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6354098366620761, 'learning_rate': 0.013009902635057455, 'dropout_rate': 0.3101706081176934, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7099066346200665, 'min_weight_fraction_leaf': 0.4804502891962041, 'max_features': None, 'min_impurity_decrease': 2.271616193402817e-07, 'validation_fraction': 0.6862699083190502, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:33:13,139] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9104967643697162, 'learning_rate': 0.01724034992100258, 'dropout_rate': 0.26334849962817525, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.5692251904189567, 'min_weight_fraction_leaf': 0.35851813148439854, 'max_features': None, 'min_impurity_decrease': 2.0843558415731406e-07, 'validation_fraction': 0.5063775748030491, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:34:51,699] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5556564275523779, 'learning_rate': 0.0033204528527945613, 'dropout_rate': 0.3636837900816117, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3042363908259532, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.2249424139094463e-07, 'validation_fraction': 0.561045056767258, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:36:40,790] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7208569038924214, 'learning_rate': 0.026256982803923905, 'dropout_rate': 0.2305409399859041, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.9525490995769573, 'min_weight_fraction_leaf': 0.398138662499872, 'max_features': None, 'min_impurity_decrease': 3.9802168951657813e-07, 'validation_fraction': 0.7435745226595007, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.7723004694835681
[I 2024-04-15 16:37:45,282] Trial 78 finished with value: 0.7520537875882294 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.012134054211554952, 'dropout_rate': 0.17020981110797495, 'n_estimators': 371, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25792648841120175, 'max_features': None, 'min_impurity_decrease': 0.0002607692087694095, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7699530516431925
[I 2024-04-15 16:38:01,442] Trial 79 finished with value: 0.7612651729154684 and parameters: {'subsample': 0.5770898503146864, 'learning_rate': 0.005718089536250872, 'dropout_rate': 0.8831816560103296, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.006784676195889549, 'min_weight_fraction_leaf': 0.26783577777991785, 'max_features': None, 'min_impurity_decrease': 0.00026754667959111344, 'validation_fraction': 0.45556658035861064, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:38:15,172] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.005715181757518938, 'dropout_rate': 0.8564920404565602, 'n_estimators': 301, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.2585934440223751, 'max_features': None, 'min_impurity_decrease': 0.00022588848940598272, 'validation_fraction': 0.4281000770625221, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7793427230046949
[I 2024-04-15 16:38:44,352] Trial 81 finished with value: 0.7574041343834572 and parameters: {'subsample': 0.573469759644561, 'learning_rate': 0.00917313652468523, 'dropout_rate': 0.7551006664918564, 'n_estimators': 378, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025432538716388925, 'min_weight_fraction_leaf': 0.2330447322703676, 'max_features': None, 'min_impurity_decrease': 0.0003172843737611832, 'validation_fraction': 0.47647246663093756, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:39:04,626] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.6061238477976733, 'learning_rate': 0.012604022944147218, 'dropout_rate': 0.8294471229873877, 'n_estimators': 356, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5341063025845167, 'min_weight_fraction_leaf': 0.19664785169557314, 'max_features': None, 'min_impurity_decrease': 0.0007825748634975355, 'validation_fraction': 0.3806000784667706, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:39:21,403] Trial 83 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6535018868517685, 'learning_rate': 0.0014826800610252661, 'dropout_rate': 0.8992417742346922, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20169466462041857, 'min_weight_fraction_leaf': 0.22451223837031314, 'max_features': None, 'min_impurity_decrease': 0.0003609663069928288, 'validation_fraction': 0.4711031887993497, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:39:51,604] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.58189223841496, 'learning_rate': 0.008316297732970858, 'dropout_rate': 0.6818395627907664, 'n_estimators': 335, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.28172882309407266, 'max_features': None, 'min_impurity_decrease': 0.001202775121736422, 'validation_fraction': 0.38945203718855725, 'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 79 with value: 0.7612651729154684.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:40:12,395] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.6947678980383888, 'learning_rate': 0.06101724551624799, 'dropout_rate': 0.7652597742653805, 'n_estimators': 317, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5339563287597978, 'min_weight_fraction_leaf': 0.24506733493657065, 'max_features': None, 'min_impurity_decrease': 0.0001261040433430487, 'validation_fraction': 0.46765139398223676, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:40:32,056] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5329646889170038, 'learning_rate': 0.006001760143614843, 'dropout_rate': 0.8650393351469537, 'n_estimators': 381, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2772447793960837, 'min_weight_fraction_leaf': 0.2595916601449126, 'max_features': None, 'min_impurity_decrease': 8.277387430400139e-05, 'validation_fraction': 0.5331294902958005, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:41:19,561] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5772171688575647, 'learning_rate': 0.012297427382052604, 'dropout_rate': 0.5450508211122536, 'n_estimators': 389, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8948782241791482, 'min_weight_fraction_leaf': 0.30432090537719336, 'max_features': None, 'min_impurity_decrease': 0.000380077265080333, 'validation_fraction': 0.5815548971606083, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:41:24,812] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4900792232135173, 'learning_rate': 0.01688118268369649, 'dropout_rate': 0.9961303410511458, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 0.32151562869669414, 'min_weight_fraction_leaf': 0.22873481062830656, 'max_features': None, 'min_impurity_decrease': 0.0016050858690837527, 'validation_fraction': 0.47521875145819903, 'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7793427230046949
[I 2024-04-15 16:41:53,471] Trial 89 finished with value: 0.7615428784886943 and parameters: {'subsample': 0.6088139660412204, 'learning_rate': 0.007354720529210388, 'dropout_rate': 0.7165927205059781, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019083182133763817, 'min_weight_fraction_leaf': 0.16713831321323547, 'max_features': None, 'min_impurity_decrease': 6.11919023761631e-05, 'validation_fraction': 0.33082778557332754, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:42:15,425] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.6135996513302981, 'learning_rate': 0.0030759059571325367, 'dropout_rate': 0.714239153071518, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5934237823972953, 'min_weight_fraction_leaf': 0.15409787484394483, 'max_features': 1, 'min_impurity_decrease': 0.00026420223842921306, 'validation_fraction': 0.3182942803078493, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.7981220657276995
[I 2024-04-15 16:43:00,757] Trial 91 finished with value: 0.7168916928997893 and parameters: {'subsample': 0.6770337747529735, 'learning_rate': 0.007750641496074201, 'dropout_rate': 0.49424724681798277, 'n_estimators': 365, 'criterion': 'friedman_mse', 'ccp_alpha': 0.15430903718460776, 'min_weight_fraction_leaf': 0.16791051943811458, 'max_features': None, 'min_impurity_decrease': 0.00012772803486333308, 'validation_fraction': 0.2316993389350888, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:43:18,215] Trial 92 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6546522174060683, 'learning_rate': 0.009421883094809201, 'dropout_rate': 0.8281440643598538, 'n_estimators': 347, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20594179048085923, 'min_weight_fraction_leaf': 0.1883593742681352, 'max_features': None, 'min_impurity_decrease': 0.0006394831666927118, 'validation_fraction': 0.2857429575523451, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.784037558685446
[I 2024-04-15 16:43:34,398] Trial 93 finished with value: 0.7646572367824584 and parameters: {'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:43:53,523] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.5329981668085512, 'learning_rate': 0.00588357274756517, 'dropout_rate': 0.9010663710372596, 'n_estimators': 398, 'criterion': 'friedman_mse', 'ccp_alpha': 0.795356671502603, 'min_weight_fraction_leaf': 0.2746770457528657, 'max_features': None, 'min_impurity_decrease': 4.317472301123062e-05, 'validation_fraction': 0.5341505661514357, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:44:08,367] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.6002877490535967, 'learning_rate': 0.0013964687008740234, 'dropout_rate': 0.913293216331538, 'n_estimators': 380, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4770423805467064, 'min_weight_fraction_leaf': 0.23547436381465842, 'max_features': 0.1, 'min_impurity_decrease': 6.5600170925824e-05, 'validation_fraction': 0.1768997582284634, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:44:22,989] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.5679830672067219, 'learning_rate': 0.014679960066405966, 'dropout_rate': 0.9491815550373798, 'n_estimators': 409, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0851736428778953, 'min_weight_fraction_leaf': 0.2093965001338856, 'max_features': 'log2', 'min_impurity_decrease': 0.0003929451723108634, 'validation_fraction': 0.4438191336127031, 'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 93 with value: 0.7646572367824584.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:44:45,102] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.6256579983686182, 'learning_rate': 0.019674657185705456, 'dropout_rate': 0.7920862318111374, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.09841883603325133, 'max_features': None, 'min_impurity_decrease': 0.0029478086506526746, 'validation_fraction': 0.4123056392425912, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:45:12,797] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5456143354363114, 'learning_rate': 0.012065355654311702, 'dropout_rate': 0.7084124127731201, 'n_estimators': 352, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8220715155379084, 'min_weight_fraction_leaf': 0.2513160795401591, 'max_features': None, 'min_impurity_decrease': 0.00015199016859086491, 'validation_fraction': 0.337785152154958, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-15 16:45:16,244] A new study created in memory with name: no-name-9862b0f1-aae4-4946-81c2-f1bdd1cbae42

Fold 5 C-index: 0.5
[I 2024-04-15 16:45:16,231] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.599460814358584, 'learning_rate': 0.0043948047101492775, 'dropout_rate': 0.5980587986289647, 'n_estimators': 93, 'criterion': 'friedman_mse', 'ccp_alpha': 6.574588525520643, 'min_weight_fraction_leaf': 0.2853352301155438, 'max_features': None, 'min_impurity_decrease': 0.0002068890339707658, 'validation_fraction': 0.4936737452445755, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 93 with value: 0.7646572367824584.


* Best trial for C-index:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.7646572367824584], datetime_start=datetime.datetime(2024, 4, 15, 16, 43, 18, 255512), datetime_complete=datetime.datetime(2024, 4, 15, 16, 43, 34, 396442), params={'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=93, value=None)


* Best Score for C-index:
 0.7646572367824584

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 16:45:50,596] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 16:46:08,512] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 16:46:25,084] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 16:46:51,579] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 16:47:01,640] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 16:47:04,070] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 16:47:28,567] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 16:47:36,154] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 16:47:37,310] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21267714729986278
Fold 2 IBS: 0.21995458442119498
Fold 3 IBS: 0.2035491555712707
Fold 4 IBS: 0.22393486370134422
Fold 5 IBS: 0.21704380099016626
[I 2024-04-15 16:48:43,222] Trial 9 finished with value: 0.21543191039676776 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21361208429589837
Fold 2 IBS: 0.2211926211265032
Fold 3 IBS: 0.20422163542183314
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21784292940455638
[I 2024-04-15 16:50:23,907] Trial 10 finished with value: 0.21628654622010784 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 16:52:19,493] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21383702367729038
Fold 2 IBS: 0.22138950456459866
Fold 3 IBS: 0.20443495965406222
Fold 4 IBS: 0.22467340762574997
Fold 5 IBS: 0.21799662270999748
[I 2024-04-15 16:54:01,498] Trial 12 finished with value: 0.21646630364633973 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-15 16:54:53,780] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 16:56:28,306] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 16:57:43,690] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 16:58:26,448] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 16:59:58,510] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:00:44,669] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:00:52,440] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:02:08,654] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21372933425701268
Fold 2 IBS: 0.2215356606685715
Fold 3 IBS: 0.2044331250210804
Fold 4 IBS: 0.22465964732749286
Fold 5 IBS: 0.21808855196539592
[I 2024-04-15 17:03:29,772] Trial 21 finished with value: 0.2164892638479107 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21261860662587898
Fold 2 IBS: 0.2196324435594265

Fold 3 IBS: 0.20356521623761553
Fold 4 IBS: 0.22397661990425946
Fold 5 IBS: 0.21681927203314136
[I 2024-04-15 17:05:00,798] Trial 22 finished with value: 0.21532243167206438 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:06:14,261] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:07:03,441] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:07:46,896] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:08:47,592] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:08:53,562] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:09:14,711] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:10:06,435] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:10:27,253] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2135108348694222
Fold 2 IBS: 0.221167731954742
Fold 3 IBS: 0.20422105908762206
Fold 4 IBS: 0.22456358064764176
Fold 5 IBS: 0.21787287595995244
[I 2024-04-15 17:11:32,255] Trial 31 finished with value: 0.2162672165038761 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21277031226041587
Fold 2 IBS: 0.21977571218645117
Fold 3 IBS: 0.2037868553635057
Fold 4 IBS: 0.22437947964183458
Fold 5 IBS: 0.2169740152088292
[I 2024-04-15 17:12:38,388] Trial 32 finished with value: 0.2155372749322073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:13:21,056] Trial 33 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9175730211318314, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.23558036461669868, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 2.2672612842512112e-05, 'validation_fraction': 0.8391863465064515, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:14:05,123] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6818728654527908, 'learning_rate': 0.014570474664799389, 'dropout_rate': 0.39687420252491534, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9857366581537508, 'min_weight_fraction_leaf': 0.2451263696303153, 'max_features': 'sqrt', 'min_impurity_decrease': 7.173213136739857e-06, 'validation_fraction': 0.9231140468377321, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:14:17,583] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7474352307553052, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.29459319086620417, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 7.199479090473024e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:15:12,261] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.3498267997183648, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.2894426185614589, 'max_features': 'auto', 'min_impurity_decrease': 6.773052750173388e-05, 'validation_fraction': 0.7819324141806283, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:15:14,337] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.23919145342953393, 'max_features': None, 'min_impurity_decrease': 2.5414170052989375e-06, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-15 17:15:47,173] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8670579303141319, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.1728262906688144, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42202283765123816, 'min_weight_fraction_leaf': 0.35239546646921105, 'max_features': 'auto', 'min_impurity_decrease': 0.00017081434930634308, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:16:15,679] Trial 39 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8154589849054708, 'learning_rate': 0.006878494063124208, 'dropout_rate': 0.5323261217237781, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 1.1477698683125066, 'min_weight_fraction_leaf': 0.11023361948341703, 'max_features': 1, 'min_impurity_decrease': 1.7677159455067355e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:17:03,590] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.22290618957651392, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.5274073849776741, 'min_weight_fraction_leaf': 0.2739610635014299, 'max_features': 'auto', 'min_impurity_decrease': 2.272398816394983e-07, 'validation_fraction': 0.8717079478922802, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2111176339922491
Fold 2 IBS: 0.21706325506301344
Fold 3 IBS: 0.20271114308166202
Fold 4 IBS: 0.22388756035618385
Fold 5 IBS: 0.21496756928312347
[I 2024-04-15 17:18:12,351] Trial 41 finished with value: 0.21394943235524638 and parameters: {'subsample': 0.993176118879571, 'learning_rate': 0.01271988915310228, 'dropout_rate': 0.152367046323752, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.19182471840022747, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21394943235524638.
Fold 1 IBS: 0.21089915783305027
Fold 2 IBS: 0.21498627855376068
Fold 3 IBS: 0.2034648608532915
Fold 4 IBS: 0.22110504116581475
Fold 5 IBS: 0.21385442301724614
[I 2024-04-15 17:19:27,470] Trial 42 finished with value: 0.21286195228463267 and parameters: {'subsample': 0.9646924257252548, 'learning_rate': 0.012507391626216524, 'dropout_rate': 0.10802959125648778, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327408119788757, 'min_weight_fraction_leaf': 0.13510597987400375, 'max_features': 'auto', 'min_impurity_decrease': 1.0593992090305253e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-15 17:20:47,010] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828284890903175, 'learning_rate': 0.011543268886217308, 'dropout_rate': 0.11584589616484722, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.09682559138790292, 'max_features': 'auto', 'min_impurity_decrease': 1.0125868029922384e-07, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-15 17:21:51,352] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992870370700113, 'learning_rate': 0.022847552015173876, 'dropout_rate': 0.1556807870961761, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.1403134453903068, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21224782790603694
Fold 2 IBS: 0.2189260608342495
Fold 3 IBS: 0.20307124042767
Fold 4 IBS: 0.22313607826909793
Fold 5 IBS: 0.216439921823279
[I 2024-04-15 17:22:14,515] Trial 45 finished with value: 0.2147642258520667 and parameters: {'subsample': 0.8888212863898438, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.20487736976615575, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.027893207681183953, 'min_weight_fraction_leaf': 0.06753391487815072, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9448766575733668, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:22:27,456] Trial 46 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.016684121596597847, 'dropout_rate': 0.10891325683572217, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.04784747079432074, 'max_features': 0.1, 'min_impurity_decrease': 2.0166271580558924e-07, 'validation_fraction': 0.24435732275143762, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-15 17:22:47,893] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7729061863940228, 'learning_rate': 0.02995584278149796, 'dropout_rate': 0.19790330487666663, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.05716507411653311, 'max_features': 0.1, 'min_impurity_decrease': 1.0699422270078741e-07, 'validation_fraction': 0.9565097869700105, 'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-15 17:23:14,717] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8446010144291817, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.14247687075474555, 'n_estimators': 294, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 0.1, 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.8246274171002186, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:23:32,549] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6917414996198523, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.2874751071933402, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.08230947204902768, 'max_features': 0.1, 'min_impurity_decrease': 1.8211699167585496e-07, 'validation_fraction': 0.6513576271964052, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-15 17:23:51,585] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.019482931131151772, 'dropout_rate': 0.6676032114338903, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.013701950422388753, 'max_features': 'log2', 'min_impurity_decrease': 7.041814507237016e-07, 'validation_fraction': 0.7324600365192867, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2125423492162011
Fold 2 IBS: 0.21917859422188082
Fold 3 IBS: 0.20326597997084148
Fold 4 IBS: 0.22346421338690958
Fold 5 IBS: 0.21658511688910384
[I 2024-04-15 17:25:06,122] Trial 51 finished with value: 0.21500725073698734 and parameters: {'subsample': 0.9574902141624301, 'learning_rate': 0.013974517784402708, 'dropout_rate': 0.19663405810878032, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288632756573364, 'min_weight_fraction_leaf': 0.1845530130003769, 'max_features': 'sqrt', 'min_impurity_decrease': 5.505988736711189e-07, 'validation_fraction': 0.8981152080635156, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:26:23,729] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8963301244448798, 'learning_rate': 0.014496942793188729, 'dropout_rate': 0.149261379708028, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.3267109398107992, 'min_weight_fraction_leaf': 0.19350109364955276, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0314361105633666e-07, 'validation_fraction': 0.8673271583656655, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:27:27,333] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.937858776808653, 'learning_rate': 0.01317678110087918, 'dropout_rate': 0.20949679348390188, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.9371275797883157, 'min_weight_fraction_leaf': 0.16718449303286065, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0035393968280476e-07, 'validation_fraction': 0.9639725916044029, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:27:35,239] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5502453589475278, 'learning_rate': 0.005289059095661144, 'dropout_rate': 0.16758744743711101, 'n_estimators': 147, 'criterion': 'squared_error', 'ccp_alpha': 0.6055238018097719, 'min_weight_fraction_leaf': 0.1222904374725215, 'max_features': 'sqrt', 'min_impurity_decrease': 8.119424084486158e-07, 'validation_fraction': 0.8019436577478607, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21151156199161855
Fold 2 IBS: 0.21784621797452874

Fold 3 IBS: 0.20286393718880646
Fold 4 IBS: 0.22391249179729633
Fold 5 IBS: 0.21519882725417372
[I 2024-04-15 17:28:47,183] Trial 55 finished with value: 0.21426660724128474 and parameters: {'subsample': 0.9703353679292269, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.2676210325613897, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.036860238643527846, 'min_weight_fraction_leaf': 0.21798842867076448, 'max_features': None, 'min_impurity_decrease': 4.086647023052284e-07, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:29:28,697] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9556274374724505, 'learning_rate': 0.022777236721630217, 'dropout_rate': 0.36674252455714285, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.3101553395317078, 'min_weight_fraction_leaf': 0.21445816437013876, 'max_features': None, 'min_impurity_decrease': 4.99089267664694e-07, 'validation_fraction': 0.8444326224317742, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2111687028051771
Fold 2 IBS: 0.2144165092431595
Fold 3 IBS: 0.20113060921449374
Fold 4 IBS: 0.22322228050971296
Fold 5 IBS: 0.21261135031718192
[I 2024-04-15 17:29:29,583] Trial 57 finished with value: 0.21250989041794505 and parameters: {'subsample': 0.9885544496318819, 'learning_rate': 0.02570846317737359, 'dropout_rate': 0.11524078732039367, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.0019474604343284706, 'min_weight_fraction_leaf': 0.1539893411018015, 'max_features': None, 'min_impurity_decrease': 3.011740016899961e-07, 'validation_fraction': 0.8976605224112223, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:29:29,940] Trial 58 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9760257284010853, 'learning_rate': 0.044170756425452734, 'dropout_rate': 0.10695167335108825, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 0.7470878188226159, 'min_weight_fraction_leaf': 0.1623750980802567, 'max_features': None, 'min_impurity_decrease': 3.402621023187449e-07, 'validation_fraction': 0.8839190525574698, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:29:32,750] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8651178500686678, 'learning_rate': 0.031729459746086146, 'dropout_rate': 0.1294932593082019, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 2.4509996240950476, 'min_weight_fraction_leaf': 0.14999314729494934, 'max_features': None, 'min_impurity_decrease': 1.564084650521852e-07, 'validation_fraction': 0.996741201133535, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:29:39,036] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9167528164906635, 'learning_rate': 0.024844206422551217, 'dropout_rate': 0.10027142034172723, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 1.5027931264041994, 'min_weight_fraction_leaf': 0.1840765520407988, 'max_features': None, 'min_impurity_decrease': 0.026115039984674165, 'validation_fraction': 0.9013568181484788, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21273370328437058
Fold 2 IBS: 0.21868788641242787
Fold 3 IBS: 0.20291275785992635
Fold 4 IBS: 0.22394573517913938
Fold 5 IBS: 0.21633996486417809
[I 2024-04-15 17:30:46,821] Trial 61 finished with value: 0.21492400952000845 and parameters: {'subsample': 0.9931174804814122, 'learning_rate': 0.016529825628647618, 'dropout_rate': 0.1935981459085364, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.0813695010094894, 'min_weight_fraction_leaf': 0.12194954374946233, 'max_features': None, 'min_impurity_decrease': 1.1729202879091808e-06, 'validation_fraction': 0.9481060427790172, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:31:56,023] Trial 62 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9972168379620757, 'learning_rate': 0.028217399882747345, 'dropout_rate': 0.1806381271548384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.3084041748420949, 'min_weight_fraction_leaf': 0.12013391362008917, 'max_features': None, 'min_impurity_decrease': 1.1386618305709938e-06, 'validation_fraction': 0.9457754330032251, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21192094947972812
Fold 2 IBS: 0.21732792727914613
Fold 3 IBS: 0.20380983776958678
Fold 4 IBS: 0.22289315056880815
Fold 5 IBS: 0.21548234130166077
[I 2024-04-15 17:31:57,169] Trial 63 finished with value: 0.21428684127978598 and parameters: {'subsample': 0.9627141857439078, 'learning_rate': 0.019891228353589942, 'dropout_rate': 0.2615796624395084, 'n_estimators': 49, 'criterion': 'squared_error', 'ccp_alpha': 0.01736018686586977, 'min_weight_fraction_leaf': 0.04375001956932725, 'max_features': None, 'min_impurity_decrease': 2.9650355903328224e-07, 'validation_fraction': 0.9569907594316491, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:31:58,006] Trial 64 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9999396727165888, 'learning_rate': 0.018638455478477044, 'dropout_rate': 0.2603466948459836, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.002024697263514, 'min_weight_fraction_leaf': 0.044141253094182736, 'max_features': None, 'min_impurity_decrease': 2.608122256111053e-07, 'validation_fraction': 0.9599786586698028, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:31:59,639] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9663925144780658, 'learning_rate': 0.037231214360123326, 'dropout_rate': 0.32454189899564956, 'n_estimators': 65, 'criterion': 'squared_error', 'ccp_alpha': 0.35061828245011545, 'min_weight_fraction_leaf': 0.000243933620821285, 'max_features': None, 'min_impurity_decrease': 1.0838199976610403e-07, 'validation_fraction': 0.9980175670026158, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:31:59,946] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9019393211486977, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.14697195606329974, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.7042671412306138, 'min_weight_fraction_leaf': 0.07018529613097008, 'max_features': None, 'min_impurity_decrease': 3.137142110783047e-07, 'validation_fraction': 0.779814650235569, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-15 17:32:04,341] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.922035492452401, 'learning_rate': 0.02138812894899817, 'dropout_rate': 0.2208120967013012, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.09999708192212713, 'max_features': None, 'min_impurity_decrease': 1.467292826198341e-07, 'validation_fraction': 0.8460725291615868, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:32:05,882] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8097361669626262, 'learning_rate': 0.01637373351805548, 'dropout_rate': 0.2712783926055171, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.1308191878488825, 'min_weight_fraction_leaf': 0.02994710580328633, 'max_features': None, 'min_impurity_decrease': 1.0530798801381977e-06, 'validation_fraction': 0.9163895657291438, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:32:06,705] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8571881441778102, 'learning_rate': 0.0012168162419408535, 'dropout_rate': 0.42050912513013483, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 3.9712948739952747, 'min_weight_fraction_leaf': 0.12752076636262508, 'max_features': None, 'min_impurity_decrease': 4.3978604154583156e-07, 'validation_fraction': 0.964953947287593, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21002215842803912
Fold 2 IBS: 0.21297063105779915
Fold 3 IBS: 0.20313255536155353
Fold 4 IBS: 0.21999212755417724
Fold 5 IBS: 0.21255973126676214
[I 2024-04-15 17:32:17,218] Trial 70 finished with value: 0.21173544073366624 and parameters: {'subsample': 0.9468320464736178, 'learning_rate': 0.025309924459591012, 'dropout_rate': 0.1674120259573768, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010011659889289447, 'min_weight_fraction_leaf': 0.09294987278666268, 'max_features': None, 'min_impurity_decrease': 5.705070769293452e-06, 'validation_fraction': 0.8209425786658539, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21072608333691198
Fold 2 IBS: 0.21401453478291746
Fold 3 IBS: 0.20284454754508327
Fold 4 IBS: 0.22338804279177132
Fold 5 IBS: 0.21335338822747257
[I 2024-04-15 17:32:26,692] Trial 71 finished with value: 0.21286531933683134 and parameters: {'subsample': 0.9476651528090181, 'learning_rate': 0.024411666195060494, 'dropout_rate': 0.17430063929290213, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.026599566986409653, 'min_weight_fraction_leaf': 0.09751530095580928, 'max_features': None, 'min_impurity_decrease': 4.532054889066385e-06, 'validation_fraction': 0.8665443299833158, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:32:35,871] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9366080309436607, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.13262889403233624, 'n_estimators': 169, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6884427794811623, 'min_weight_fraction_leaf': 0.09471989813086933, 'max_features': None, 'min_impurity_decrease': 6.727144219685939e-06, 'validation_fraction': 0.7986403101682931, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:32:54,364] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8857292786754678, 'learning_rate': 0.026134449034871034, 'dropout_rate': 0.16958042534169554, 'n_estimators': 242, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3564153148878991, 'min_weight_fraction_leaf': 0.0675437991522329, 'max_features': None, 'min_impurity_decrease': 1.2822715066526718e-05, 'validation_fraction': 0.8508580960070242, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-15 17:33:03,156] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9667167267229794, 'learning_rate': 0.03460218408739485, 'dropout_rate': 0.23922069132815701, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9478289085025897, 'min_weight_fraction_leaf': 0.040648200160109275, 'max_features': None, 'min_impurity_decrease': 0.0004132854571878442, 'validation_fraction': 0.9118732389838691, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.2108264636051011
Fold 2 IBS: 0.21614741779802119
Fold 3 IBS: 0.20270071891532052
Fold 4 IBS: 0.22138908682592695
Fold 5 IBS: 0.21464613153207532
[I 2024-04-15 17:33:06,121] Trial 75 finished with value: 0.21314196373528901 and parameters: {'subsample': 0.9385875657011895, 'learning_rate': 0.03024192192848759, 'dropout_rate': 0.31026391284421334, 'n_estimators': 98, 'criterion': 'friedman_mse', 'ccp_alpha': 0.008766215704230302, 'min_weight_fraction_leaf': 0.088197239599825, 'max_features': 'log2', 'min_impurity_decrease': 2.34297511452969e-05, 'validation_fraction': 0.8182037482219422, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:33:18,420] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9478601603991035, 'learning_rate': 0.029703712882555727, 'dropout_rate': 0.30760503014637186, 'n_estimators': 217, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6031244247920138, 'min_weight_fraction_leaf': 0.08521606153633404, 'max_features': 'log2', 'min_impurity_decrease': 1.826805985778275e-05, 'validation_fraction': 0.7127838617807927, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-15 17:33:20,543] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.834194505922225, 'learning_rate': 0.023289065494024846, 'dropout_rate': 0.5946683576609367, 'n_estimators': 105, 'criterion': 'friedman_mse', 'ccp_alpha': 5.8752783688356525, 'min_weight_fraction_leaf': 0.10946812472698092, 'max_features': 'log2', 'min_impurity_decrease': 3.863869195457471e-05, 'validation_fraction': 0.8140600247331974, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:33:22,915] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9202091045129451, 'learning_rate': 0.019797687069268054, 'dropout_rate': 0.12670174450467558, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2910342652485194, 'min_weight_fraction_leaf': 0.15713001580184646, 'max_features': 'log2', 'min_impurity_decrease': 6.996091386072907e-06, 'validation_fraction': 0.7499357618644306, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:33:24,314] Trial 79 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9732609597246192, 'learning_rate': 0.027328730151233487, 'dropout_rate': 0.26312746311148777, 'n_estimators': 53, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3668553929390492, 'min_weight_fraction_leaf': 0.13178723776048706, 'max_features': 1, 'min_impurity_decrease': 3.5229801834435753e-06, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:33:28,628] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9344911008533908, 'learning_rate': 0.010633768390963052, 'dropout_rate': 0.3607582604573143, 'n_estimators': 130, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 'log2', 'min_impurity_decrease': 4.704228580458697e-05, 'validation_fraction': 0.8794203590137769, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21128104502826947
Fold 2 IBS: 0.2177939632602238
Fold 3 IBS: 0.202062918285923
Fold 4 IBS: 0.2220570307012409
Fold 5 IBS: 0.215203473940832
[I 2024-04-15 17:33:30,674] Trial 81 finished with value: 0.21367968624329783 and parameters: {'subsample': 0.883668494603156, 'learning_rate': 0.0320493886753143, 'dropout_rate': 0.22584451920971726, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038423779386081554, 'min_weight_fraction_leaf': 0.06634784234748042, 'max_features': 0.1, 'min_impurity_decrease': 1.4048004741754647e-05, 'validation_fraction': 0.9236349807357848, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.20983058110579608
Fold 2 IBS: 0.21307838506839907
Fold 3 IBS: 0.20156611960689727
Fold 4 IBS: 0.22102813568136667
Fold 5 IBS: 0.21191457851765924
[I 2024-04-15 17:33:32,939] Trial 82 finished with value: 0.2114835599960237 and parameters: {'subsample': 0.9775351216671477, 'learning_rate': 0.03625251959157783, 'dropout_rate': 0.2304960144192588, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017671076422469716, 'min_weight_fraction_leaf': 0.05682074279635106, 'max_features': None, 'min_impurity_decrease': 5.222380988059964e-06, 'validation_fraction': 0.8329660882357115, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:33:35,226] Trial 83 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.980690245556926, 'learning_rate': 0.031857704007181985, 'dropout_rate': 0.22968230522988387, 'n_estimators': 80, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8197918628434602, 'min_weight_fraction_leaf': 0.057928624179806834, 'max_features': None, 'min_impurity_decrease': 1.2599470077449364e-05, 'validation_fraction': 0.7797865611811227, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:33:39,447] Trial 84 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9075135722909342, 'learning_rate': 0.03559224920264127, 'dropout_rate': 0.16623286657907432, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.512352281665378, 'min_weight_fraction_leaf': 0.10287384413406744, 'max_features': 0.1, 'min_impurity_decrease': 5.529311462542002e-06, 'validation_fraction': 0.8246387147196982, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:33:47,939] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9399767088887255, 'learning_rate': 0.04090952135292814, 'dropout_rate': 0.15193033105151865, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3342330512314949, 'min_weight_fraction_leaf': 0.08669540229802705, 'max_features': 1, 'min_impurity_decrease': 1.6658136731423827e-05, 'validation_fraction': 0.8565340610034006, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 5}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:33:50,122] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.875251314446822, 'learning_rate': 0.054611780581555074, 'dropout_rate': 0.18611522621903143, 'n_estimators': 75, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23548502503527302, 'min_weight_fraction_leaf': 0.14949731859104587, 'max_features': None, 'min_impurity_decrease': 2.4419902202859148e-05, 'validation_fraction': 0.8919356176714629, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:33:50,741] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9722232383830184, 'learning_rate': 0.0372364299275435, 'dropout_rate': 0.3020378568783464, 'n_estimators': 28, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0716748672357443, 'min_weight_fraction_leaf': 0.17652784181036787, 'max_features': 'log2', 'min_impurity_decrease': 9.189811058262566e-06, 'validation_fraction': 0.9265266924948802, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:34:04,381] Trial 88 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.45521815335975935, 'learning_rate': 0.024635453467641497, 'dropout_rate': 0.22592407076200724, 'n_estimators': 225, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5932990711529844, 'min_weight_fraction_leaf': 0.05795880477433249, 'max_features': 0.1, 'min_impurity_decrease': 0.00010910005120952281, 'validation_fraction': 0.86583149343058, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 6}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.20406423720489414
Fold 2 IBS: 0.20607296701907554
Fold 3 IBS: 0.19811121797640907
Fold 4 IBS: 0.22011942798029224
Fold 5 IBS: 0.20776003972546755
[I 2024-04-15 17:34:07,357] Trial 89 finished with value: 0.2072255779812277 and parameters: {'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:34:10,469] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8590448841763807, 'learning_rate': 0.04392267936156322, 'dropout_rate': 0.13081530577107772, 'n_estimators': 94, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8187200341244589, 'min_weight_fraction_leaf': 0.1356329779047198, 'max_features': None, 'min_impurity_decrease': 6.919028711702198e-05, 'validation_fraction': 0.7579364095018994, 'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2139765219514961
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:34:14,583] Trial 91 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9464598565951264, 'learning_rate': 0.033436459700910935, 'dropout_rate': 0.1074479916910401, 'n_estimators': 111, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1567080004847236, 'min_weight_fraction_leaf': 0.21909447348643799, 'max_features': None, 'min_impurity_decrease': 3.232645761160545e-05, 'validation_fraction': 0.836686056082251, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-15 17:34:19,940] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9026696667848182, 'learning_rate': 0.028827888997212704, 'dropout_rate': 0.16259306451315403, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4965227315126272, 'min_weight_fraction_leaf': 0.22285254340641944, 'max_features': None, 'min_impurity_decrease': 0.00017018904827513644, 'validation_fraction': 0.796918264996305, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-15 17:34:21,763] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9798482306398367, 'learning_rate': 0.031825834623114814, 'dropout_rate': 0.2049131658034791, 'n_estimators': 69, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20667716682270093, 'min_weight_fraction_leaf': 0.2585203230729044, 'max_features': None, 'min_impurity_decrease': 3.0851445660062647e-06, 'validation_fraction': 0.9763122670150756, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2101879570260367
Fold 2 IBS: 0.21250628812533257
Fold 3 IBS: 0.20007025298318656
Fold 4 IBS: 0.22265647904327204
Fold 5 IBS: 0.21257939770958625
[I 2024-04-15 17:34:24,517] Trial 94 finished with value: 0.21160007497748282 and parameters: {'subsample': 0.9310591269229673, 'learning_rate': 0.02763334095363912, 'dropout_rate': 0.12795712192217606, 'n_estimators': 86, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05749842893076747, 'min_weight_fraction_leaf': 0.11026254544432534, 'max_features': 'auto', 'min_impurity_decrease': 5.8091196946415505e-05, 'validation_fraction': 0.9026577264245155, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:34:27,376] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9218225521402408, 'learning_rate': 0.02753178161235845, 'dropout_rate': 0.12793297330846434, 'n_estimators': 85, 'criterion': 'friedman_mse', 'ccp_alpha': 1.235276138540849, 'min_weight_fraction_leaf': 0.11051958866648452, 'max_features': 'auto', 'min_impurity_decrease': 6.515583307515859e-05, 'validation_fraction': 0.7292708592638782, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-15 17:34:27,906] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7993135167464014, 'learning_rate': 0.03108695961488799, 'dropout_rate': 0.14512603486936382, 'n_estimators': 24, 'criterion': 'friedman_mse', 'ccp_alpha': 0.49652833519783807, 'min_weight_fraction_leaf': 0.08008525725013409, 'max_features': 'auto', 'min_impurity_decrease': 4.444264351736355e-06, 'validation_fraction': 0.9242462136422857, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-15 17:34:38,348] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.845660486112679, 'learning_rate': 0.038767353066908594, 'dropout_rate': 0.18221216046279998, 'n_estimators': 200, 'criterion': 'friedman_mse', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.09201897280645036, 'max_features': 'auto', 'min_impurity_decrease': 0.0002353321351929941, 'validation_fraction': 0.8287626512220347, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-15 17:34:42,838] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8944546679246258, 'learning_rate': 0.036127203223985056, 'dropout_rate': 0.10388522337492916, 'n_estimators': 103, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8167233797377258, 'min_weight_fraction_leaf': 0.19553165108199336, 'max_features': 'auto', 'min_impurity_decrease': 1.7492280036351012e-05, 'validation_fraction': 0.899014721584761, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21406463377160456
Fold 2 IBS: 0.22130490881763304
Fold 3 IBS: 0.20441078654944964
Fold 4 IBS: 0.2243095706255849
Fold 5 IBS: 0.21724050836884118
[I 2024-04-15 17:34:43,128] Trial 99 finished with value: 0.21626608162662264 and parameters: {'subsample': 0.24110557495742024, 'learning_rate': 0.034155925108170324, 'dropout_rate': 0.12401586667496287, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004427324419918794, 'min_weight_fraction_leaf': 0.07004102983569523, 'max_features': 'auto', 'min_impurity_decrease': 3.069838649017234e-05, 'validation_fraction': 0.6766066266445131, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.

* Best trial for IBS:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.2072255779812277], datetime_start=datetime.datetime(2024, 4, 15, 17, 34, 4, 389376), datetime_complete=datetime.datetime(2024, 4, 15, 17, 34, 7, 356130), params={'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=89, value=None)


* Best Score for IBS:
 0.2072255779812277

In [60]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.765
train_ibs:  0.207

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.046986154574499193,
                                 dropout_rate=0.9141084507237711,
                                 learning_rate=0.005228819896792163,
                                 max_leaf_nodes=13,
                                 min_impurity_decrease=0.00017501601948817654,
                                 min_samples_leaf=15, min_samples_split=11,
                                 min_weight_fraction_leaf=0.2724947676380759,
                                 n_estimators=395, random_state=123,
                                 subsample=0.6128161811459047,
                                 validation_fraction=0.542037097833947)

C-index score: 0.579

GradientBoostingSurvivalAnalysis(ccp_alpha=0.019065157478907357,
                                 dropout_rate=0.10084377376256726,
                                 learning_rate=0.032246585462716706,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.552978044824526e-05,
                                 min_samples_leaf=9, min_samples_split=18,
                                 min_weight_fraction_leaf=0.21843803937299006,
                                 n_estimators=92, random_state=123,
                                 subsample=0.9081334064688743,
                                 validation_fraction=0.8292287698601738)

IBS: 0.218

In [64]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:34:46,035] A new study created in memory with name: no-name-2f0b01e5-4145-4fc5-9240-74e2fe23bdd2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:34:46,748] Trial 0 finished with value: 0.6779611770557914 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6779611770557914.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:34:53,580] Trial 1 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-15 17:34:54,875] Trial 2 finished with value: 0.6663524874852127 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:34:56,473] Trial 3 finished with value: 0.667127888043984 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.704225352112676
[I 2024-04-15 17:34:59,339] Trial 4 finished with value: 0.6693154459145041 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:02,374] Trial 5 finished with value: 0.6769807848989287 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:03,865] Trial 6 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.676056338028169
[I 2024-04-15 17:35:04,100] Trial 7 finished with value: 0.6668249458732585 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:05,605] Trial 8 finished with value: 0.6671059690347232 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:10,559] Trial 9 finished with value: 0.6646618584791086 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 1 with value: 0.6809023535263796.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:16,225] Trial 10 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 496, 'learning_rate': 0.09279671898160717}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:21,442] Trial 11 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7324662940063873, 'n_estimators': 485, 'learning_rate': 0.09656492760401554}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:25,047] Trial 12 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.7213847659091492, 'n_estimators': 393, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:28,530] Trial 13 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9944701185331792, 'dropout_rate': 0.7322663481529263, 'n_estimators': 386, 'learning_rate': 0.09915584389423529}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:30,910] Trial 14 finished with value: 0.6799219613695169 and parameters: {'subsample': 0.8619663815733164, 'dropout_rate': 0.97886644128982, 'n_estimators': 332, 'learning_rate': 0.0025916531369806137}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:35,392] Trial 15 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8897480564271555, 'dropout_rate': 0.6064727105060288, 'n_estimators': 448, 'learning_rate': 0.08616677729964022}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6854460093896714
[I 2024-04-15 17:35:37,671] Trial 16 finished with value: 0.6818469525040766 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.8054552653400341, 'n_estimators': 304, 'learning_rate': 0.08344309838925727}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:42,298] Trial 17 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 427, 'learning_rate': 0.08658185684301867}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:47,296] Trial 18 finished with value: 0.6750200005852032 and parameters: {'subsample': 0.6236867669661592, 'dropout_rate': 0.7861352339489561, 'n_estimators': 496, 'learning_rate': 0.09231790921735909}. Best is trial 10 with value: 0.6818827456832424.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:50,576] Trial 19 finished with value: 0.6799219613695169 and parameters: {'subsample': 0.8350722272141606, 'dropout_rate': 0.99497601792777, 'n_estimators': 431, 'learning_rate': 0.08172742798527305}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:52,831] Trial 20 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9139336698304192, 'dropout_rate': 0.6483171405010271, 'n_estimators': 296, 'learning_rate': 0.038682181981402025}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:35:56,366] Trial 21 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9876175410749531, 'dropout_rate': 0.7214521431639925, 'n_estimators': 397, 'learning_rate': 0.09591247627892314}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:00,346] Trial 22 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9670658719660202, 'dropout_rate': 0.749566046531592, 'n_estimators': 437, 'learning_rate': 0.09976046636649535}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:03,050] Trial 23 finished with value: 0.6799219613695169 and parameters: {'subsample': 0.8035922306127279, 'dropout_rate': 0.8583901704323202, 'n_estimators': 361, 'learning_rate': 0.07918017824457936}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:07,827] Trial 24 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9338991614103125, 'dropout_rate': 0.6880320457171679, 'n_estimators': 470, 'learning_rate': 0.08995349569526555}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:11,431] Trial 25 finished with value: 0.6799219613695169 and parameters: {'subsample': 0.8037716416766091, 'dropout_rate': 0.5449350839943904, 'n_estimators': 395, 'learning_rate': 0.06370784030442876}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:14,886] Trial 26 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9981944957438552, 'dropout_rate': 0.8085117448008347, 'n_estimators': 418, 'learning_rate': 0.09301216134836006}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:19,130] Trial 27 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9208977938727171, 'dropout_rate': 0.9019129570809951, 'n_estimators': 497, 'learning_rate': 0.0767949792404025}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:22,034] Trial 28 finished with value: 0.6769807848989287 and parameters: {'subsample': 0.6692336821130495, 'dropout_rate': 0.6165599624822959, 'n_estimators': 335, 'learning_rate': 0.014116661098438898}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:26,963] Trial 29 finished with value: 0.6799219613695169 and parameters: {'subsample': 0.7912448504145874, 'dropout_rate': 0.5028884427940175, 'n_estimators': 456, 'learning_rate': 0.06161847327233598}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-15 17:36:27,449] Trial 30 finished with value: 0.6644792381854928 and parameters: {'subsample': 0.5936384513688024, 'dropout_rate': 0.3892024351052794, 'n_estimators': 93, 'learning_rate': 0.08977928313998897}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:30,533] Trial 31 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9488701920274671, 'dropout_rate': 0.7321889254587483, 'n_estimators': 383, 'learning_rate': 0.09781836987516382}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:34,886] Trial 32 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9972125397554292, 'dropout_rate': 0.7067087249192361, 'n_estimators': 462, 'learning_rate': 0.0996485424783721}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:38,281] Trial 33 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8757106718787788, 'dropout_rate': 0.7700117170914431, 'n_estimators': 409, 'learning_rate': 0.06941351761009329}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:41,423] Trial 34 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9337467259199114, 'dropout_rate': 0.8479054407169416, 'n_estimators': 366, 'learning_rate': 0.09319244498036391}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:43,309] Trial 35 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.7552152054887563, 'dropout_rate': 0.6485928727497494, 'n_estimators': 256, 'learning_rate': 0.08212930104296796}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:49,166] Trial 36 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.7083391301049273, 'dropout_rate': 0.5847496282810936, 'n_estimators': 500, 'learning_rate': 0.0711317699490665}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:49,285] Trial 37 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8324556084993827, 'dropout_rate': 0.47096246897520044, 'n_estimators': 1, 'learning_rate': 0.07677405503763898}. Best is trial 10 with value: 0.6818827456832424.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:52,479] Trial 38 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9485832819053552, 'dropout_rate': 0.13272164755980653, 'n_estimators': 337, 'learning_rate': 0.09007603128714806}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 17:36:53,327] Trial 39 finished with value: 0.6729490344331384 and parameters: {'subsample': 0.22212752554206305, 'dropout_rate': 0.6881141432789704, 'n_estimators': 145, 'learning_rate': 0.08562293525961606}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:55,694] Trial 40 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8941050217622332, 'dropout_rate': 0.27073406810212547, 'n_estimators': 289, 'learning_rate': 0.09984942919729918}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:36:59,848] Trial 41 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9994962321376948, 'dropout_rate': 0.6364825383885335, 'n_estimators': 449, 'learning_rate': 0.08859266792184871}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:04,472] Trial 42 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8938069144870199, 'dropout_rate': 0.5910070315549997, 'n_estimators': 469, 'learning_rate': 0.0942809906226358}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:08,181] Trial 43 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9594135942894225, 'dropout_rate': 0.8218163360258883, 'n_estimators': 439, 'learning_rate': 0.08476503724026307}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:11,456] Trial 44 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8613042132005592, 'dropout_rate': 0.7514358707131008, 'n_estimators': 385, 'learning_rate': 0.09553312364143325}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:15,395] Trial 45 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9155651248954684, 'dropout_rate': 0.9122425977981868, 'n_estimators': 476, 'learning_rate': 0.07358829455007394}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6807511737089202
[I 2024-04-15 17:37:19,285] Trial 46 finished with value: 0.6661907405873905 and parameters: {'subsample': 0.3577075778842369, 'dropout_rate': 0.5304616989895755, 'n_estimators': 415, 'learning_rate': 0.08687458283787974}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:20,581] Trial 47 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8505335712619968, 'dropout_rate': 0.6814366281018536, 'n_estimators': 211, 'learning_rate': 0.08063451221472408}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:23,735] Trial 48 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9614279492208745, 'dropout_rate': 0.5758773874350814, 'n_estimators': 369, 'learning_rate': 0.05628240665900254}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.676056338028169
[I 2024-04-15 17:37:28,153] Trial 49 finished with value: 0.6689107370366744 and parameters: {'subsample': 0.4221719094018991, 'dropout_rate': 0.7762377490712176, 'n_estimators': 486, 'learning_rate': 0.06615495649623622}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:32,664] Trial 50 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9044213920602021, 'dropout_rate': 0.4326780653706334, 'n_estimators': 450, 'learning_rate': 0.09620299316074098}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:36,606] Trial 51 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8809584853040211, 'dropout_rate': 0.603479194088629, 'n_estimators': 430, 'learning_rate': 0.08611052458649876}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:40,517] Trial 52 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9646044008999738, 'dropout_rate': 0.7161293121038296, 'n_estimators': 421, 'learning_rate': 0.09167934146865997}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:42,157] Trial 53 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.7711834295399624, 'dropout_rate': 0.6514505914730948, 'n_estimators': 234, 'learning_rate': 0.07735300247618473}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:44,770] Trial 54 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.8357839582303415, 'dropout_rate': 0.6287074121597086, 'n_estimators': 318, 'learning_rate': 0.09565031368122733}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:49,877] Trial 55 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9702767327706239, 'dropout_rate': 0.5221121463400054, 'n_estimators': 481, 'learning_rate': 0.08789748738955261}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:52,739] Trial 56 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.7111326335187584, 'dropout_rate': 0.5629879526803889, 'n_estimators': 350, 'learning_rate': 0.037919945798086954}. Best is trial 10 with value: 0.6818827456832424.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:55,959] Trial 57 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9240270477116976, 'dropout_rate': 0.7438257872492274, 'n_estimators': 402, 'learning_rate': 0.08149465284084818}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:37:59,697] Trial 58 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.821887749819138, 'dropout_rate': 0.8287133209166155, 'n_estimators': 456, 'learning_rate': 0.09115553180853811}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:03,128] Trial 59 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9946844988488728, 'dropout_rate': 0.7879464668818117, 'n_estimators': 430, 'learning_rate': 0.09989621571967562}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:06,234] Trial 60 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8784766286133319, 'dropout_rate': 0.6735625241105511, 'n_estimators': 382, 'learning_rate': 0.08436855261778313}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:08,398] Trial 61 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9222972722028369, 'dropout_rate': 0.7063693162539825, 'n_estimators': 303, 'learning_rate': 0.044501508923334085}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:13,097] Trial 62 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.945883558848447, 'dropout_rate': 0.6115476427946167, 'n_estimators': 483, 'learning_rate': 0.03757129695610441}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:17,106] Trial 63 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9741038345745225, 'dropout_rate': 0.6570691083095543, 'n_estimators': 448, 'learning_rate': 0.024732012381502792}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:18,801] Trial 64 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8957116676717958, 'dropout_rate': 0.7557971807838051, 'n_estimators': 268, 'learning_rate': 0.09331920323677184}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:22,033] Trial 65 finished with value: 0.6799219613695169 and parameters: {'subsample': 0.8002058892116559, 'dropout_rate': 0.7172017974576959, 'n_estimators': 398, 'learning_rate': 0.04841446942458946}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:26,875] Trial 66 finished with value: 0.6692522389350886 and parameters: {'subsample': 0.5291753681956431, 'dropout_rate': 0.49924086079197083, 'n_estimators': 467, 'learning_rate': 0.035640893691442486}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:29,272] Trial 67 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8581475883438201, 'dropout_rate': 0.8794056998796148, 'n_estimators': 354, 'learning_rate': 0.030934053952606864}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:36,064] Trial 68 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9364364640300946, 'dropout_rate': 0.6742191325723852, 'n_estimators': 496, 'learning_rate': 0.0582375351466085}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:38,419] Trial 69 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9746194188462142, 'dropout_rate': 0.9490666653031774, 'n_estimators': 165, 'learning_rate': 0.0960254684133116}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:44,354] Trial 70 finished with value: 0.6740615274376011 and parameters: {'subsample': 0.6125267511035271, 'dropout_rate': 0.8019211235645807, 'n_estimators': 438, 'learning_rate': 0.008227552186261713}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:48,223] Trial 71 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9986675252371331, 'dropout_rate': 0.7281265138088411, 'n_estimators': 382, 'learning_rate': 0.09630819057137004}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:38:55,429] Trial 72 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9147495084755111, 'dropout_rate': 0.695840824581025, 'n_estimators': 409, 'learning_rate': 0.09023090484935194}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:00,381] Trial 73 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9475263966519448, 'dropout_rate': 0.6331241888915656, 'n_estimators': 423, 'learning_rate': 0.0980341168287804}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:05,074] Trial 74 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9801996742427174, 'dropout_rate': 0.5616458637951052, 'n_estimators': 374, 'learning_rate': 0.09311674956032978}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:10,830] Trial 75 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8992341526223592, 'dropout_rate': 0.7665739295803389, 'n_estimators': 461, 'learning_rate': 0.08851620509904888}. Best is trial 10 with value: 0.6818827456832424.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:14,942] Trial 76 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9352274739129932, 'dropout_rate': 0.6612769642005887, 'n_estimators': 394, 'learning_rate': 0.09800970574147538}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:18,095] Trial 77 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9772977309582147, 'dropout_rate': 0.618641100865597, 'n_estimators': 344, 'learning_rate': 0.0835870210161492}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:22,469] Trial 78 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8725636220932828, 'dropout_rate': 0.7289966355746446, 'n_estimators': 437, 'learning_rate': 0.07848493398074843}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:24,781] Trial 79 finished with value: 0.6760003927420659 and parameters: {'subsample': 0.6723788047810191, 'dropout_rate': 0.8314631694385664, 'n_estimators': 323, 'learning_rate': 0.09352214171589322}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:27,190] Trial 80 finished with value: 0.6799219613695169 and parameters: {'subsample': 0.779151264931973, 'dropout_rate': 0.1835064275776629, 'n_estimators': 275, 'learning_rate': 0.024789752967322706}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:30,921] Trial 81 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9493866155281071, 'dropout_rate': 0.6893518678273758, 'n_estimators': 410, 'learning_rate': 0.09997323530864267}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:35,311] Trial 82 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9962488544355672, 'dropout_rate': 0.7572674934272915, 'n_estimators': 473, 'learning_rate': 0.09148153200221322}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:40,132] Trial 83 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9106851184492886, 'dropout_rate': 0.5933579221678122, 'n_estimators': 447, 'learning_rate': 0.09700306335163215}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:46,138] Trial 84 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9618175139833081, 'dropout_rate': 0.8032281704986148, 'n_estimators': 498, 'learning_rate': 0.08730495089655357}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:50,820] Trial 85 finished with value: 0.6809023535263796 and parameters: {'subsample': 0.8243385545906782, 'dropout_rate': 0.7366903682174054, 'n_estimators': 422, 'learning_rate': 0.09500058414007766}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:39:57,020] Trial 86 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8483924636995817, 'dropout_rate': 0.7060346198817979, 'n_estimators': 487, 'learning_rate': 0.09107046334775476}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6948356807511737
[I 2024-04-15 17:40:00,109] Trial 87 finished with value: 0.6767830680465836 and parameters: {'subsample': 0.15366485952498626, 'dropout_rate': 0.7826265758888865, 'n_estimators': 359, 'learning_rate': 0.09837944000882021}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:04,760] Trial 88 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9289819826712857, 'dropout_rate': 0.64104345641972, 'n_estimators': 390, 'learning_rate': 0.09434365371023452}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:12,857] Trial 89 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9750196896343145, 'dropout_rate': 0.6594251226695511, 'n_estimators': 456, 'learning_rate': 0.0749789018604819}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:18,821] Trial 90 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8859196427384918, 'dropout_rate': 0.8593844076133618, 'n_estimators': 439, 'learning_rate': 0.08923299121826678}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:26,259] Trial 91 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9512882489933315, 'dropout_rate': 0.6916554792028329, 'n_estimators': 473, 'learning_rate': 0.08650877249835147}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:32,180] Trial 92 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9832384364154417, 'dropout_rate': 0.7332999601792679, 'n_estimators': 465, 'learning_rate': 0.04251553362296538}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:32,649] Trial 93 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9249999474330801, 'dropout_rate': 0.6759487313902742, 'n_estimators': 86, 'learning_rate': 0.08170874265368244}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:36,464] Trial 94 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9584062816542339, 'dropout_rate': 0.7096098613751931, 'n_estimators': 410, 'learning_rate': 0.09288072374646297}. Best is trial 10 with value: 0.6818827456832424.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:40,827] Trial 95 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9008608357441895, 'dropout_rate': 0.6078517037066634, 'n_estimators': 424, 'learning_rate': 0.09762233299977507}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:42,634] Trial 96 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.936304059902211, 'dropout_rate': 0.7585771837231472, 'n_estimators': 236, 'learning_rate': 0.08991761489703681}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:49,029] Trial 97 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9998613799315567, 'dropout_rate': 0.5747385548795975, 'n_estimators': 480, 'learning_rate': 0.050230273345475834}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.704225352112676
[I 2024-04-15 17:40:52,838] Trial 98 finished with value: 0.6696321635106335 and parameters: {'subsample': 0.32197567947477257, 'dropout_rate': 0.5473823126025558, 'n_estimators': 372, 'learning_rate': 0.08500085543247328}. Best is trial 10 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697

[I 2024-04-15 17:40:57,333] A new study created in memory with name: no-name-f0995048-6347-4892-8f2b-1e7b8b095db2

Fold 5 C-index: 0.6713615023474179
[I 2024-04-15 17:40:57,308] Trial 99 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8735353140313972, 'dropout_rate': 0.7858418090495674, 'n_estimators': 452, 'learning_rate': 0.09514471867552406}. Best is trial 10 with value: 0.6818827456832424.


* Best trial for C-index:
 FrozenTrial(number=10, state=TrialState.COMPLETE, values=[0.6818827456832424], datetime_start=datetime.datetime(2024, 4, 15, 17, 35, 10, 566812), datetime_complete=datetime.datetime(2024, 4, 15, 17, 35, 16, 225086), params={'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 496, 'learning_rate': 0.09279671898160717}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=10, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 496, 'learning_rate': 0.09279671898160717}


* Best Score for C-index:
 0.6818827456832424

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.20699145898488328
Fold 2 IBS: 0.17304948337342932
Fold 3 IBS: 0.18591999895239444
Fold 4 IBS: 0.18542968049493186
Fold 5 IBS: 0.18161276917344785
[I 2024-04-15 17:40:58,003] Trial 0 finished with value: 0.18660067819581735 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.18660067819581735.
Fold 1 IBS: 0.2598653641576557
Fold 2 IBS: 0.14389702090775328
Fold 3 IBS: 0.20413347649834074
Fold 4 IBS: 0.17297880259330858
Fold 5 IBS: 0.18937368678660815
[I 2024-04-15 17:41:04,059] Trial 1 finished with value: 0.1940496701887333 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.18660067819581735.
Fold 1 IBS: 0.2216227203785337
Fold 2 IBS: 0.14748311208798062
Fold 3 IBS: 0.20761223140808074
Fold 4 IBS: 0.16777679994851738
Fold 5 IBS: 0.171655104008037
[I 2024-04-15 17:41:05,237] Trial 2 finished with value: 0.18322999356622988 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.2263121661287902
Fold 2 IBS: 0.14603576283425723
Fold 3 IBS: 0.22557421772834182
Fold 4 IBS: 0.16488258678792048
Fold 5 IBS: 0.17167431610414435
[I 2024-04-15 17:41:06,954] Trial 3 finished with value: 0.1868958099166908 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.22102629079536057
Fold 2 IBS: 0.14844897306854762
Fold 3 IBS: 0.25827964735724146
Fold 4 IBS: 0.16465913249488764
Fold 5 IBS: 0.17133785638592522
[I 2024-04-15 17:41:09,649] Trial 4 finished with value: 0.1927503800203925 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.24286751759123798
Fold 2 IBS: 0.13925625124111304
Fold 3 IBS: 0.1960143262302863
Fold 4 IBS: 0.16485854918458642
Fold 5 IBS: 0.17898619391427245
[I 2024-04-15 17:41:13,007] Trial 5 finished with value: 0.18439656763229925 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.20536666173028972
Fold 2 IBS: 0.18606837477322213
Fold 3 IBS: 0.18936102935101107
Fold 4 IBS: 0.19631189837308577
Fold 5 IBS: 0.1898279603879094
[I 2024-04-15 17:41:14,759] Trial 6 finished with value: 0.1933871849231036 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.20825491540694005
Fold 2 IBS: 0.2075121599857637
Fold 3 IBS: 0.2033340825383308
Fold 4 IBS: 0.21085155193500044
Fold 5 IBS: 0.2031110793759146
[I 2024-04-15 17:41:15,063] Trial 7 finished with value: 0.20661275784838992 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.20704163967563702
Fold 2 IBS: 0.173082663466465
Fold 3 IBS: 0.20478598549641094
Fold 4 IBS: 0.18545996641362336
Fold 5 IBS: 0.1788921521177366
[I 2024-04-15 17:41:16,585] Trial 8 finished with value: 0.18985248143397457 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.24449301508287039
Fold 2 IBS: 0.13912161128566955
Fold 3 IBS: 0.2372548446053718
Fold 4 IBS: 0.16234408350223956
Fold 5 IBS: 0.1800136835535035
[I 2024-04-15 17:41:20,792] Trial 9 finished with value: 0.192645447605931 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.254602279977166
Fold 2 IBS: 0.14210916696659623
Fold 3 IBS: 0.19719027687169022
Fold 4 IBS: 0.17058006540228302
Fold 5 IBS: 0.18642832498419037
[I 2024-04-15 17:41:23,177] Trial 10 finished with value: 0.19018202284038516 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 322, 'learning_rate': 0.09279671898160717}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.2578911909448842
Fold 2 IBS: 0.14272191874095844
Fold 3 IBS: 0.20886234928262007
Fold 4 IBS: 0.16981895507251707
Fold 5 IBS: 0.18822436174581642
[I 2024-04-15 17:41:25,814] Trial 11 finished with value: 0.19350375515735924 and parameters: {'subsample': 0.6331931485087656, 'dropout_rate': 0.9718736866137505, 'n_estimators': 366, 'learning_rate': 0.088026097514438}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.250761407683884
Fold 2 IBS: 0.14090745358557533
Fold 3 IBS: 0.19136526034247572
Fold 4 IBS: 0.16845615909510434
Fold 5 IBS: 0.18427777065062292
[I 2024-04-15 17:41:28,673] Trial 12 finished with value: 0.18715361027153246 and parameters: {'subsample': 0.9130062069982081, 'dropout_rate': 0.7721129777446738, 'n_estimators': 361, 'learning_rate': 0.07543381562264323}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.20984306421573848
Fold 2 IBS: 0.2160542709354855
Fold 3 IBS: 0.20253971080772598
Fold 4 IBS: 0.21928073712973145
Fold 5 IBS: 0.20958330551661783
[I 2024-04-15 17:41:28,853] Trial 13 finished with value: 0.21146021772105983 and parameters: {'subsample': 0.19911958285971598, 'dropout_rate': 0.8221620437901842, 'n_estimators': 15, 'learning_rate': 0.06484130816286861}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.21297248716016082
Fold 2 IBS: 0.21889392579642944
Fold 3 IBS: 0.20350404196184815
Fold 4 IBS: 0.22276543688839204
Fold 5 IBS: 0.21572246352281813
[I 2024-04-15 17:41:29,487] Trial 14 finished with value: 0.2147716710659297 and parameters: {'subsample': 0.638341598789069, 'dropout_rate': 0.6257121219137264, 'n_estimators': 117, 'learning_rate': 0.0025916531369806137}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.2567798933686517
Fold 2 IBS: 0.14105072829895277
Fold 3 IBS: 0.26531729218533595
Fold 4 IBS: 0.1626894463719205
Fold 5 IBS: 0.18450511910381534
[I 2024-04-15 17:41:32,504] Trial 15 finished with value: 0.20206849586573522 and parameters: {'subsample': 0.36317278257214075, 'dropout_rate': 0.42541379031557736, 'n_estimators': 325, 'learning_rate': 0.09917499129944472}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.2379179386119539
Fold 2 IBS: 0.14341102538669057
Fold 3 IBS: 0.28769744038436146
Fold 4 IBS: 0.1561263013556213
Fold 5 IBS: 0.18479026965461062
[I 2024-04-15 17:41:37,178] Trial 16 finished with value: 0.20198859507864758 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.5672052413745938, 'n_estimators': 427, 'learning_rate': 0.08033475203870699}. Best is trial 2 with value: 0.18322999356622988.
Fold 1 IBS: 0.21469667677893503
Fold 2 IBS: 0.15600342530025588
Fold 3 IBS: 0.17327026860174397
Fold 4 IBS: 0.1735755063366431
Fold 5 IBS: 0.17310605880232657
[I 2024-04-15 17:41:39,650] Trial 17 finished with value: 0.1781303871639809 and parameters: {'subsample': 0.8580015035921449, 'dropout_rate': 0.23930666550173862, 'n_estimators': 274, 'learning_rate': 0.036208666639295596}. Best is trial 17 with value: 0.1781303871639809.
Fold 1 IBS: 0.21415933700176445
Fold 2 IBS: 0.15742795369700438
Fold 3 IBS: 0.17556681456857692
Fold 4 IBS: 0.17422822408723487
Fold 5 IBS: 0.17360372084479359
[I 2024-04-15 17:41:42,201] Trial 18 finished with value: 0.17899721003987484 and parameters: {'subsample': 0.8588948594700169, 'dropout_rate': 0.11655432561651174, 'n_estimators': 261, 'learning_rate': 0.03707183063684802}. Best is trial 17 with value: 0.1781303871639809.
Fold 1 IBS: 0.2056977743127328

Fold 2 IBS: 0.17892642660722471
Fold 3 IBS: 0.18267258430610997
Fold 4 IBS: 0.1910460474072693
Fold 5 IBS: 0.18440907707340753
[I 2024-04-15 17:41:44,938] Trial 19 finished with value: 0.18855038194134885 and parameters: {'subsample': 0.8447766709063648, 'dropout_rate': 0.12690048952433258, 'n_estimators': 281, 'learning_rate': 0.019107774444910287}. Best is trial 17 with value: 0.1781303871639809.
Fold 1 IBS: 0.21556848748356808
Fold 2 IBS: 0.15529895506013994
Fold 3 IBS: 0.17400594079322942
Fold 4 IBS: 0.17306227825948983
Fold 5 IBS: 0.1731153967884686
[I 2024-04-15 17:41:47,640] Trial 20 finished with value: 0.17821021167697917 and parameters: {'subsample': 0.8714518330888589, 'dropout_rate': 0.24699216442522764, 'n_estimators': 245, 'learning_rate': 0.04061880568044879}. Best is trial 17 with value: 0.1781303871639809.
Fold 1 IBS: 0.21383415966041183
Fold 2 IBS: 0.15768556648248103
Fold 3 IBS: 0.17557459979421097
Fold 4 IBS: 0.1746415770408096
Fold 5 IBS: 0.1738499618927359
[I 2024-04-15 17:41:50,046] Trial 21 finished with value: 0.17911717297412988 and parameters: {'subsample': 0.8587709768634099, 'dropout_rate': 0.25152243747660513, 'n_estimators': 252, 'learning_rate': 0.03695220140472054}. Best is trial 17 with value: 0.1781303871639809.
Fold 1 IBS: 0.22178562750984662
Fold 2 IBS: 0.1484020898903477
Fold 3 IBS: 0.17160773863434908
Fold 4 IBS: 0.1685179307183806
Fold 5 IBS: 0.17177260342120995
[I 2024-04-15 17:41:52,968] Trial 22 finished with value: 0.17641719803482678 and parameters: {'subsample': 0.9603719956332457, 'dropout_rate': 0.2825595354760141, 'n_estimators': 304, 'learning_rate': 0.040435406226492}. Best is trial 22 with value: 0.17641719803482678.
Fold 1 IBS: 0.20801608510466083
Fold 2 IBS: 0.16974387242836772
Fold 3 IBS: 0.1775657901007571
Fold 4 IBS: 0.18288706266960164
Fold 5 IBS: 0.17863363871454765
[I 2024-04-15 17:41:55,856] Trial 23 finished with value: 0.18336928980358697 and parameters: {'subsample': 0.9656608403256824, 'dropout_rate': 0.30705687846434804, 'n_estimators': 310, 'learning_rate': 0.0225117857896489}. Best is trial 22 with value: 0.17641719803482678.
Fold 1 IBS: 0.20558741242475587
Fold 2 IBS: 0.1799509061047345
Fold 3 IBS: 0.18398478619812203
Fold 4 IBS: 0.19162438314077992
Fold 5 IBS: 0.18457359222280081
[I 2024-04-15 17:42:00,228] Trial 24 finished with value: 0.1891442160182386 and parameters: {'subsample': 0.8073429168223376, 'dropout_rate': 0.21380258906323846, 'n_estimators': 404, 'learning_rate': 0.013004306476015196}. Best is trial 22 with value: 0.17641719803482678.
Fold 1 IBS: 0.21368018425651134
Fold 2 IBS: 0.1581929407179378
Fold 3 IBS: 0.17349717016743904
Fold 4 IBS: 0.17430068997060247
Fold 5 IBS: 0.1737542069763751
[I 2024-04-15 17:42:01,859] Trial 25 finished with value: 0.17868503841777314 and parameters: {'subsample': 0.9148809649113013, 'dropout_rate': 0.3297018950691607, 'n_estimators': 220, 'learning_rate': 0.04256870276931271}. Best is trial 22 with value: 0.17641719803482678.
Fold 1 IBS: 0.20539555660432007
Fold 2 IBS: 0.18730100382349993
Fold 3 IBS: 0.18556249009425535
Fold 4 IBS: 0.19709920632140837
Fold 5 IBS: 0.18968278830780066
[I 2024-04-15 17:42:03,011] Trial 26 finished with value: 0.19300820903025687 and parameters: {'subsample': 0.9979471445625029, 'dropout_rate': 0.21450467144479185, 'n_estimators': 150, 'learning_rate': 0.028125276287262947}. Best is trial 22 with value: 0.17641719803482678.
Fold 1 IBS: 0.22410796084459683
Fold 2 IBS: 0.14639429198596207
Fold 3 IBS: 0.1716450660568607
Fold 4 IBS: 0.16740037016100384
Fold 5 IBS: 0.17177855867790057
[I 2024-04-15 17:42:05,947] Trial 27 finished with value: 0.17626524954526482 and parameters: {'subsample': 0.9179336178622413, 'dropout_rate': 0.2936806234715784, 'n_estimators': 301, 'learning_rate': 0.043817723511479265}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.2251691176955808
Fold 2 IBS: 0.14565463960110378
Fold 3 IBS: 0.17175066654047472
Fold 4 IBS: 0.16696324985188749
Fold 5 IBS: 0.17183131407617883
[I 2024-04-15 17:42:08,590] Trial 28 finished with value: 0.17627379755304512 and parameters: {'subsample': 0.9306696847743131, 'dropout_rate': 0.3080593480767576, 'n_estimators': 293, 'learning_rate': 0.04630351600022239}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.24547925160795392
Fold 2 IBS: 0.13961450826032284
Fold 3 IBS: 0.18629521776525637
Fold 4 IBS: 0.16615512192038645
Fold 5 IBS: 0.1799383634775771
[I 2024-04-15 17:42:12,894] Trial 29 finished with value: 0.18349649260629933 and parameters: {'subsample': 0.7908146601028178, 'dropout_rate': 0.3784804276100209, 'n_estimators': 402, 'learning_rate': 0.05817445592729491}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.23063050156977158
Fold 2 IBS: 0.14209257408119527
Fold 3 IBS: 0.17312605673341397
Fold 4 IBS: 0.16545365675156587
Fold 5 IBS: 0.17284707965580962
[I 2024-04-15 17:42:15,615] Trial 30 finished with value: 0.17682997375835124 and parameters: {'subsample': 0.9429547105600394, 'dropout_rate': 0.3212574031910046, 'n_estimators': 300, 'learning_rate': 0.05279002147756341}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.22683596353938654
Fold 2 IBS: 0.14442989853295504
Fold 3 IBS: 0.17201711222141117
Fold 4 IBS: 0.1664244316233959
Fold 5 IBS: 0.1720241092328539
[I 2024-04-15 17:42:18,339] Trial 31 finished with value: 0.1763463030300005 and parameters: {'subsample': 0.9291377031076995, 'dropout_rate': 0.3185737983797614, 'n_estimators': 302, 'learning_rate': 0.04705673987544217}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.23037755642063568
Fold 2 IBS: 0.14211206189477243
Fold 3 IBS: 0.1807724117319786
Fold 4 IBS: 0.16503525650538903
Fold 5 IBS: 0.1730039466683799
[I 2024-04-15 17:42:21,509] Trial 32 finished with value: 0.17826024664423112 and parameters: {'subsample': 0.7082747713900285, 'dropout_rate': 0.1807381738274531, 'n_estimators': 335, 'learning_rate': 0.04786785153288355}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.21758953169739897
Fold 2 IBS: 0.15306430243220173
Fold 3 IBS: 0.172175395358759
Fold 4 IBS: 0.17139713669209009
Fold 5 IBS: 0.1722904788722062
[I 2024-04-15 17:42:24,593] Trial 33 finished with value: 0.1773033690105312 and parameters: {'subsample': 0.9304192439847225, 'dropout_rate': 0.48889967631172476, 'n_estimators': 346, 'learning_rate': 0.03090694595220763}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.2269300228561495
Fold 2 IBS: 0.14406441846423773
Fold 3 IBS: 0.17658288830284857
Fold 4 IBS: 0.16619400908579124
Fold 5 IBS: 0.1719705086128684
[I 2024-04-15 17:42:27,229] Trial 34 finished with value: 0.1771483694643791 and parameters: {'subsample': 0.786232818441406, 'dropout_rate': 0.3015127235473936, 'n_estimators': 299, 'learning_rate': 0.0472578232658475}. Best is trial 27 with value: 0.17626524954526482.
Fold 1 IBS: 0.22481892062638745
Fold 2 IBS: 0.14569153558442732
Fold 3 IBS: 0.17167470406853838
Fold 4 IBS: 0.16714429481746665
Fold 5 IBS: 0.17186079114879005
[I 2024-04-15 17:42:28,913] Trial 35 finished with value: 0.17623804924912195 and parameters: {'subsample': 0.8987483790220123, 'dropout_rate': 0.43682110832068877, 'n_estimators': 234, 'learning_rate': 0.057134385454111855}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22930707792740865
Fold 2 IBS: 0.14250893305114173
Fold 3 IBS: 0.18165054166047367
Fold 4 IBS: 0.1654730663013165
Fold 5 IBS: 0.17241136549849503
[I 2024-04-15 17:42:30,530] Trial 36 finished with value: 0.17827019688776713 and parameters: {'subsample': 0.7249013790779042, 'dropout_rate': 0.48633683911344266, 'n_estimators': 231, 'learning_rate': 0.065584780945425}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21550331819505467
Fold 2 IBS: 0.15534282001574717
Fold 3 IBS: 0.19681838794100887
Fold 4 IBS: 0.17183665109664364
Fold 5 IBS: 0.17317391033926402
[I 2024-04-15 17:42:31,868] Trial 37 finished with value: 0.18253501751754367 and parameters: {'subsample': 0.5729940322874101, 'dropout_rate': 0.43696212688443054, 'n_estimators': 178, 'learning_rate': 0.0565575070240422}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.24531938349446034

Fold 2 IBS: 0.13957734581072945
Fold 3 IBS: 0.1860801071022301
Fold 4 IBS: 0.16617625838199115
Fold 5 IBS: 0.17986715594608155
[I 2024-04-15 17:42:36,268] Trial 38 finished with value: 0.1834040501470985 and parameters: {'subsample': 0.8106303770923914, 'dropout_rate': 0.3720991365773877, 'n_estimators': 389, 'learning_rate': 0.05967708581399747}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2153213199042684
Fold 2 IBS: 0.1557220858168984
Fold 3 IBS: 0.17296664592719105
Fold 4 IBS: 0.1733821578831075
Fold 5 IBS: 0.17309761052642533
[I 2024-04-15 17:42:37,128] Trial 39 finished with value: 0.17809796401157812 and parameters: {'subsample': 0.8935775772493658, 'dropout_rate': 0.40729159514619007, 'n_estimators': 144, 'learning_rate': 0.06892741183938003}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2145395153982697
Fold 2 IBS: 0.1565353784804454
Fold 3 IBS: 0.17297575411525098
Fold 4 IBS: 0.17367276804259238
Fold 5 IBS: 0.17326366824345357
[I 2024-04-15 17:42:38,546] Trial 40 finished with value: 0.1781974168560024 and parameters: {'subsample': 0.9941192990157609, 'dropout_rate': 0.5443446234145757, 'n_estimators': 204, 'learning_rate': 0.04737083472484328}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2302340147546406
Fold 2 IBS: 0.14229911137342124
Fold 3 IBS: 0.17297933740489696
Fold 4 IBS: 0.16551203560503105
Fold 5 IBS: 0.17274983500672472
[I 2024-04-15 17:42:41,584] Trial 41 finished with value: 0.1767548668289429 and parameters: {'subsample': 0.9486853079677322, 'dropout_rate': 0.3007059679916281, 'n_estimators': 288, 'learning_rate': 0.054532767092015336}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2146551061314552
Fold 2 IBS: 0.15667476809684341
Fold 3 IBS: 0.17315249658657805
Fold 4 IBS: 0.17344710624787987
Fold 5 IBS: 0.17318356382370226
[I 2024-04-15 17:42:43,393] Trial 42 finished with value: 0.17822260817729177 and parameters: {'subsample': 0.9044675326975746, 'dropout_rate': 0.3610396901177846, 'n_estimators': 233, 'learning_rate': 0.04162749555870097}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22397395664783695
Fold 2 IBS: 0.14622976127313797
Fold 3 IBS: 0.17618334691149945
Fold 4 IBS: 0.16705092248584383
Fold 5 IBS: 0.1718010109959103
[I 2024-04-15 17:42:45,716] Trial 43 finished with value: 0.17704779966284573 and parameters: {'subsample': 0.7582860883826372, 'dropout_rate': 0.17747845551835437, 'n_estimators': 265, 'learning_rate': 0.050804712205793676}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22917155007583784
Fold 2 IBS: 0.14290657120066794
Fold 3 IBS: 0.1726197462018824
Fold 4 IBS: 0.1657907451169205
Fold 5 IBS: 0.1725174308166606
[I 2024-04-15 17:42:49,033] Trial 44 finished with value: 0.17660120868239385 and parameters: {'subsample': 0.9559150213945657, 'dropout_rate': 0.28592128738450795, 'n_estimators': 341, 'learning_rate': 0.04450424844427492}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2172381502809931
Fold 2 IBS: 0.15337544556305818
Fold 3 IBS: 0.17579728568424338
Fold 4 IBS: 0.171590347339782
Fold 5 IBS: 0.17245238482036893
[I 2024-04-15 17:42:51,489] Trial 45 finished with value: 0.1780907227376891 and parameters: {'subsample': 0.811390743929047, 'dropout_rate': 0.4738244269084236, 'n_estimators': 308, 'learning_rate': 0.03400538573985265}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2518634005804467
Fold 2 IBS: 0.14106206156549955
Fold 3 IBS: 0.19259136530466947
Fold 4 IBS: 0.168881412309425
Fold 5 IBS: 0.18432657448245074
[I 2024-04-15 17:42:56,385] Trial 46 finished with value: 0.1877449628484983 and parameters: {'subsample': 0.909617225343689, 'dropout_rate': 0.3344288711098706, 'n_estimators': 447, 'learning_rate': 0.06238658621276861}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22927820967715423
Fold 2 IBS: 0.14280211483635746
Fold 3 IBS: 0.17270107074166097
Fold 4 IBS: 0.16578797705983678
Fold 5 IBS: 0.17253886901289575
[I 2024-04-15 17:43:00,072] Trial 47 finished with value: 0.17662164826558105 and parameters: {'subsample': 0.9972866467703421, 'dropout_rate': 0.4039008076912235, 'n_estimators': 377, 'learning_rate': 0.0402686310155012}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21009179858899046
Fold 2 IBS: 0.16446673873317047
Fold 3 IBS: 0.18334186659856824
Fold 4 IBS: 0.1788139380079725
Fold 5 IBS: 0.17667953660876332
[I 2024-04-15 17:43:02,504] Trial 48 finished with value: 0.182678775707493 and parameters: {'subsample': 0.6917197484016825, 'dropout_rate': 0.2741743913368218, 'n_estimators': 284, 'learning_rate': 0.027763821111874188}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2053479965561668
Fold 2 IBS: 0.19154288115923557
Fold 3 IBS: 0.20610819522407392
Fold 4 IBS: 0.2000165920592937
Fold 5 IBS: 0.1906535966315774
[I 2024-04-15 17:43:02,973] Trial 49 finished with value: 0.1987338523260695 and parameters: {'subsample': 0.41713745629931753, 'dropout_rate': 0.5102223098023965, 'n_estimators': 81, 'learning_rate': 0.052983553392879516}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.24630509208654783
Fold 2 IBS: 0.1397662402076947
Fold 3 IBS: 0.18950854802451886
Fold 4 IBS: 0.1667459619054961
Fold 5 IBS: 0.18159540348271763
[I 2024-04-15 17:43:06,437] Trial 50 finished with value: 0.18478424914139502 and parameters: {'subsample': 0.7584722030913209, 'dropout_rate': 0.19529751669903572, 'n_estimators': 351, 'learning_rate': 0.07099361685934613}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2287397687395199
Fold 2 IBS: 0.14313854279484747
Fold 3 IBS: 0.17249193979787275
Fold 4 IBS: 0.16589173721840328
Fold 5 IBS: 0.17240751846494082
[I 2024-04-15 17:43:09,604] Trial 51 finished with value: 0.17653390140311684 and parameters: {'subsample': 0.9590272285889869, 'dropout_rate': 0.2893231452981179, 'n_estimators': 328, 'learning_rate': 0.04568212861048975}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22897242527919057
Fold 2 IBS: 0.14285461386255
Fold 3 IBS: 0.17260765578532222
Fold 4 IBS: 0.1659132809441579
Fold 5 IBS: 0.17238436300019022
[I 2024-04-15 17:43:13,622] Trial 52 finished with value: 0.17654646777428218 and parameters: {'subsample': 0.8894488969115067, 'dropout_rate': 0.3484326333263853, 'n_estimators': 326, 'learning_rate': 0.04596144198751952}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22912283394448804
Fold 2 IBS: 0.1429040618546848
Fold 3 IBS: 0.17274625739908922
Fold 4 IBS: 0.1658532850919044
Fold 5 IBS: 0.17259471923414818
[I 2024-04-15 17:43:17,226] Trial 53 finished with value: 0.17664423150486291 and parameters: {'subsample': 0.961915972153466, 'dropout_rate': 0.14265539782442407, 'n_estimators': 315, 'learning_rate': 0.04889065883480896}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21017608440125918
Fold 2 IBS: 0.1643986029243506
Fold 3 IBS: 0.17793128006269635
Fold 4 IBS: 0.17910044545341702
Fold 5 IBS: 0.1765017102309261
[I 2024-04-15 17:43:18,910] Trial 54 finished with value: 0.18162162461452985 and parameters: {'subsample': 0.8398142915069285, 'dropout_rate': 0.26225129036694333, 'n_estimators': 195, 'learning_rate': 0.04038189089616083}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2272797685224901
Fold 2 IBS: 0.14415689471726467
Fold 3 IBS: 0.17207142354438765
Fold 4 IBS: 0.16618688251577302
Fold 5 IBS: 0.17219242068812027
[I 2024-04-15 17:43:20,912] Trial 55 finished with value: 0.17637747799760714 and parameters: {'subsample': 0.9334905337978445, 'dropout_rate': 0.4405106392045769, 'n_estimators': 252, 'learning_rate': 0.05698968233674993}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.23823528143559275
Fold 2 IBS: 0.13960640969209345
Fold 3 IBS: 0.17902941036263
Fold 4 IBS: 0.16500111844414436
Fold 5 IBS: 0.17601140153868045
[I 2024-04-15 17:43:22,646] Trial 56 finished with value: 0.17957672429462818 and parameters: {'subsample': 0.8312437315110994, 'dropout_rate': 0.5896825924026827, 'n_estimators': 249, 'learning_rate': 0.07819754042044627}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.23473746418340444

Fold 2 IBS: 0.14040273178208976
Fold 3 IBS: 0.17509128263968832
Fold 4 IBS: 0.16499123304160157
Fold 5 IBS: 0.17454013496230905
[I 2024-04-15 17:43:24,880] Trial 57 finished with value: 0.17795256932181863 and parameters: {'subsample': 0.8862861902385478, 'dropout_rate': 0.4359332997838259, 'n_estimators': 268, 'learning_rate': 0.0656783260329411}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22698120271099279
Fold 2 IBS: 0.14410789602835403
Fold 3 IBS: 0.17207018536840524
Fold 4 IBS: 0.16639065609011652
Fold 5 IBS: 0.1721004094342305
[I 2024-04-15 17:43:26,416] Trial 58 finished with value: 0.1763300699264198 and parameters: {'subsample': 0.9333451032938084, 'dropout_rate': 0.5176718588682189, 'n_estimators': 233, 'learning_rate': 0.06122167786858218}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22318872923760744
Fold 2 IBS: 0.14732818664429548
Fold 3 IBS: 0.17159998040780355
Fold 4 IBS: 0.16798209411560538
Fold 5 IBS: 0.17175813348418825
[I 2024-04-15 17:43:27,806] Trial 59 finished with value: 0.17637142477790002 and parameters: {'subsample': 0.9220668939697135, 'dropout_rate': 0.6915407565234866, 'n_estimators': 222, 'learning_rate': 0.057306356361674846}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2159649306882868
Fold 2 IBS: 0.1540371405306164
Fold 3 IBS: 0.17258207713352103
Fold 4 IBS: 0.17298045561463776
Fold 5 IBS: 0.17283704619533144
[I 2024-04-15 17:43:28,727] Trial 60 finished with value: 0.17768033003247868 and parameters: {'subsample': 0.8626375752991438, 'dropout_rate': 0.7636590717459024, 'n_estimators': 161, 'learning_rate': 0.06273634438503752}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22301890972307056
Fold 2 IBS: 0.14724986516786875
Fold 3 IBS: 0.17160180074512285
Fold 4 IBS: 0.16793180612505512
Fold 5 IBS: 0.17175379621897133
[I 2024-04-15 17:43:30,638] Trial 61 finished with value: 0.17631123559601775 and parameters: {'subsample': 0.9305809611648059, 'dropout_rate': 0.6939202656849559, 'n_estimators': 222, 'learning_rate': 0.05715578549625058}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21998901190730527
Fold 2 IBS: 0.1500604525294406
Fold 3 IBS: 0.17203843467695284
Fold 4 IBS: 0.16995521221213852
Fold 5 IBS: 0.17190143609804287
[I 2024-04-15 17:43:32,110] Trial 62 finished with value: 0.17678890948477605 and parameters: {'subsample': 0.9097023755207646, 'dropout_rate': 0.6687273101852037, 'n_estimators': 223, 'learning_rate': 0.051737400075680534}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21378590330260652
Fold 2 IBS: 0.1566423682877169
Fold 3 IBS: 0.24208384921360093
Fold 4 IBS: 0.17441608666858952
Fold 5 IBS: 0.1722514198828156
[I 2024-04-15 17:43:33,246] Trial 63 finished with value: 0.1918359254710659 and parameters: {'subsample': 0.2675273969344081, 'dropout_rate': 0.5984010959816459, 'n_estimators': 190, 'learning_rate': 0.05988073335944977}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21989699310861105
Fold 2 IBS: 0.15016989587391055
Fold 3 IBS: 0.17175071469002343
Fold 4 IBS: 0.16961714137940376
Fold 5 IBS: 0.17188693901732396
[I 2024-04-15 17:43:34,675] Trial 64 finished with value: 0.17666433681385457 and parameters: {'subsample': 0.9284453471132577, 'dropout_rate': 0.7059467142696543, 'n_estimators': 212, 'learning_rate': 0.05455328480421653}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.23174583300330526
Fold 2 IBS: 0.14152086647041331
Fold 3 IBS: 0.17347795098598817
Fold 4 IBS: 0.1654672175290208
Fold 5 IBS: 0.17319462538848018
[I 2024-04-15 17:43:36,394] Trial 65 finished with value: 0.17708129867544156 and parameters: {'subsample': 0.8758120684375258, 'dropout_rate': 0.6329559998519282, 'n_estimators': 235, 'learning_rate': 0.06845788422543653}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.23164380099410967
Fold 2 IBS: 0.14137190618937334
Fold 3 IBS: 0.17495207742883845
Fold 4 IBS: 0.1653788003587841
Fold 5 IBS: 0.17317778733376937
[I 2024-04-15 17:43:38,405] Trial 66 finished with value: 0.177304874460975 and parameters: {'subsample': 0.8313075622911833, 'dropout_rate': 0.7872235459612831, 'n_estimators': 286, 'learning_rate': 0.0567132338091369}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21085646387064502
Fold 2 IBS: 0.16287839793518427
Fold 3 IBS: 0.17483860434929557
Fold 4 IBS: 0.17804047637228293
Fold 5 IBS: 0.17534267402829576
[I 2024-04-15 17:43:39,415] Trial 67 finished with value: 0.1803913233111407 and parameters: {'subsample': 0.9791744185724149, 'dropout_rate': 0.8756629820315567, 'n_estimators': 165, 'learning_rate': 0.049925217378876834}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.20978884743846554
Fold 2 IBS: 0.16416142905327424
Fold 3 IBS: 0.17884111683391607
Fold 4 IBS: 0.17990936141064198
Fold 5 IBS: 0.17606393984070687
[I 2024-04-15 17:43:40,313] Trial 68 finished with value: 0.18175293891540095 and parameters: {'subsample': 0.7808121282564754, 'dropout_rate': 0.5191177615058225, 'n_estimators': 125, 'learning_rate': 0.06236474680115347}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.24008190154310677
Fold 2 IBS: 0.1392660488136504
Fold 3 IBS: 0.18918758105415678
Fold 4 IBS: 0.16334019945001502
Fold 5 IBS: 0.17695232715307765
[I 2024-04-15 17:43:42,037] Trial 69 finished with value: 0.1817656116028013 and parameters: {'subsample': 0.6224820836901458, 'dropout_rate': 0.955189146742179, 'n_estimators': 242, 'learning_rate': 0.08403050744828938}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.23886259490938233
Fold 2 IBS: 0.13962260221463876
Fold 3 IBS: 0.1781011426899588
Fold 4 IBS: 0.16506440041628506
Fold 5 IBS: 0.17653394710384965
[I 2024-04-15 17:43:43,967] Trial 70 finished with value: 0.1796369374668229 and parameters: {'subsample': 0.926177523074218, 'dropout_rate': 0.727250506250643, 'n_estimators': 261, 'learning_rate': 0.07581216586201316}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22172150788879727
Fold 2 IBS: 0.1484691505080896
Fold 3 IBS: 0.17160949477070658
Fold 4 IBS: 0.16837948408723358
Fold 5 IBS: 0.17175798562648342
[I 2024-04-15 17:43:45,668] Trial 71 finished with value: 0.1763875245762621 and parameters: {'subsample': 0.933728554216989, 'dropout_rate': 0.44882794261953296, 'n_estimators': 212, 'learning_rate': 0.058002551516385115}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22648183232547345
Fold 2 IBS: 0.14448087434793364
Fold 3 IBS: 0.17203320946079687
Fold 4 IBS: 0.1669455653684293
Fold 5 IBS: 0.1719969466578615
[I 2024-04-15 17:43:47,610] Trial 72 finished with value: 0.17638768563209895 and parameters: {'subsample': 0.8776847746684695, 'dropout_rate': 0.6428685338797305, 'n_estimators': 251, 'learning_rate': 0.05537725949921437}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2349860026217769
Fold 2 IBS: 0.1403117401042985
Fold 3 IBS: 0.17550618338453752
Fold 4 IBS: 0.16497719117700374
Fold 5 IBS: 0.17460079523534186
[I 2024-04-15 17:43:50,024] Trial 73 finished with value: 0.1780763825045917 and parameters: {'subsample': 0.9657717641669707, 'dropout_rate': 0.5688826088366427, 'n_estimators': 272, 'learning_rate': 0.06539863569553321}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2348843853619861
Fold 2 IBS: 0.1404269484847121
Fold 3 IBS: 0.17524068760624317
Fold 4 IBS: 0.16497628286420585
Fold 5 IBS: 0.17460580915578114
[I 2024-04-15 17:43:53,494] Trial 74 finished with value: 0.17802682269458567 and parameters: {'subsample': 0.937464618017542, 'dropout_rate': 0.3959790111375998, 'n_estimators': 295, 'learning_rate': 0.06029896355312916}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21902329881368515
Fold 2 IBS: 0.15054317225290978
Fold 3 IBS: 0.17274649885928767
Fold 4 IBS: 0.17051037846074216
Fold 5 IBS: 0.172071274746713
[I 2024-04-15 17:43:55,623] Trial 75 finished with value: 0.17697892462666756 and parameters: {'subsample': 0.8549202286524867, 'dropout_rate': 0.5154917592158309, 'n_estimators': 225, 'learning_rate': 0.04986950173440331}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.20806866027032103

Fold 2 IBS: 0.16954053173030745
Fold 3 IBS: 0.1774760435677439
Fold 4 IBS: 0.18259907726741195
Fold 5 IBS: 0.17869941809076093
[I 2024-04-15 17:43:57,161] Trial 76 finished with value: 0.18327674618530906 and parameters: {'subsample': 0.9788165536606092, 'dropout_rate': 0.45549606805946546, 'n_estimators': 190, 'learning_rate': 0.03684462007229316}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.23442318874698415
Fold 2 IBS: 0.1404707945240763
Fold 3 IBS: 0.17496721384379338
Fold 4 IBS: 0.16506377542785522
Fold 5 IBS: 0.17436183465785568
[I 2024-04-15 17:43:59,290] Trial 77 finished with value: 0.17785736144011294 and parameters: {'subsample': 0.8943155387464099, 'dropout_rate': 0.6676023717320858, 'n_estimators': 256, 'learning_rate': 0.0683573703407812}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21268481271568046
Fold 2 IBS: 0.15819098367709067
Fold 3 IBS: 0.17561877424846498
Fold 4 IBS: 0.17606931646844712
Fold 5 IBS: 0.17422981263426884
[I 2024-04-15 17:44:00,732] Trial 78 finished with value: 0.17935873994879042 and parameters: {'subsample': 0.8252001556824575, 'dropout_rate': 0.8275062951227752, 'n_estimators': 206, 'learning_rate': 0.04350721788340461}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22782504677519996
Fold 2 IBS: 0.1434208846213117
Fold 3 IBS: 0.17233453189143735
Fold 4 IBS: 0.16621440906643556
Fold 5 IBS: 0.17222731878444839
[I 2024-04-15 17:44:03,515] Trial 79 finished with value: 0.17640443822776658 and parameters: {'subsample': 0.9131848563719752, 'dropout_rate': 0.23508132681509453, 'n_estimators': 280, 'learning_rate': 0.05304981194084567}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21652397019403136
Fold 2 IBS: 0.15415851472030964
Fold 3 IBS: 0.17242054860556852
Fold 4 IBS: 0.1718536123249009
Fold 5 IBS: 0.1726867747472571
[I 2024-04-15 17:44:04,923] Trial 80 finished with value: 0.17752868411841352 and parameters: {'subsample': 0.9808784281329473, 'dropout_rate': 0.3693186444443954, 'n_estimators': 182, 'learning_rate': 0.057077257689066394}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22169355984993525
Fold 2 IBS: 0.1484965026632258
Fold 3 IBS: 0.17161048750729008
Fold 4 IBS: 0.16839425023104534
Fold 5 IBS: 0.1717586305915624
[I 2024-04-15 17:44:06,467] Trial 81 finished with value: 0.17639068616861178 and parameters: {'subsample': 0.9339602357169172, 'dropout_rate': 0.4585181807773151, 'n_estimators': 212, 'learning_rate': 0.05794161401918143}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22898341231603664
Fold 2 IBS: 0.14298935673437047
Fold 3 IBS: 0.17255774334267726
Fold 4 IBS: 0.16572632905667029
Fold 5 IBS: 0.17258162240016628
[I 2024-04-15 17:44:08,120] Trial 82 finished with value: 0.17656769276998419 and parameters: {'subsample': 0.9360005093340426, 'dropout_rate': 0.40763361355612254, 'n_estimators': 237, 'learning_rate': 0.06383683854996125}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2277210894535507
Fold 2 IBS: 0.14364050284807733
Fold 3 IBS: 0.17321850617934414
Fold 4 IBS: 0.16623618270583582
Fold 5 IBS: 0.1721821957807551
[I 2024-04-15 17:44:09,796] Trial 83 finished with value: 0.1765996953935126 and parameters: {'subsample': 0.865752517497898, 'dropout_rate': 0.4273977680008796, 'n_estimators': 244, 'learning_rate': 0.05912504612911469}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22202359856344958
Fold 2 IBS: 0.14810907057923473
Fold 3 IBS: 0.17161229648777346
Fold 4 IBS: 0.1682611119988544
Fold 5 IBS: 0.1717763261619928
[I 2024-04-15 17:44:11,530] Trial 84 finished with value: 0.176356480758261 and parameters: {'subsample': 0.9049532504620404, 'dropout_rate': 0.3423556626976365, 'n_estimators': 227, 'learning_rate': 0.054430166937806}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22673773765421434
Fold 2 IBS: 0.14424568753275332
Fold 3 IBS: 0.17194114196733212
Fold 4 IBS: 0.16648592977383495
Fold 5 IBS: 0.17196944253144802
[I 2024-04-15 17:44:13,947] Trial 85 finished with value: 0.17627598789191654 and parameters: {'subsample': 0.8970660402270154, 'dropout_rate': 0.32143291752951275, 'n_estimators': 275, 'learning_rate': 0.051576418257458304}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22952972731174562
Fold 2 IBS: 0.1426147626938574
Fold 3 IBS: 0.1726754011493655
Fold 4 IBS: 0.1656951773809028
Fold 5 IBS: 0.17253095913995706
[I 2024-04-15 17:44:17,537] Trial 86 finished with value: 0.17660920553516568 and parameters: {'subsample': 0.9027405368737442, 'dropout_rate': 0.3232340824764945, 'n_estimators': 317, 'learning_rate': 0.04840291554511508}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21970348054953823
Fold 2 IBS: 0.15054147411725372
Fold 3 IBS: 0.17619115505074281
Fold 4 IBS: 0.1697418965069227
Fold 5 IBS: 0.1720522021072709
[I 2024-04-15 17:44:20,217] Trial 87 finished with value: 0.17764604166634568 and parameters: {'subsample': 0.7981768395114388, 'dropout_rate': 0.34093253916724564, 'n_estimators': 295, 'learning_rate': 0.03857710295128833}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22218236294971713
Fold 2 IBS: 0.14794134352666888
Fold 3 IBS: 0.17341104948004124
Fold 4 IBS: 0.1684713762653767
Fold 5 IBS: 0.17177898653247134
[I 2024-04-15 17:44:22,971] Trial 88 finished with value: 0.17675702375085506 and parameters: {'subsample': 0.8467032053481078, 'dropout_rate': 0.3143799402201794, 'n_estimators': 275, 'learning_rate': 0.04465604289726922}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2188935064737751
Fold 2 IBS: 0.15110501903504994
Fold 3 IBS: 0.20081380155032402
Fold 4 IBS: 0.16915714998391918
Fold 5 IBS: 0.17193396931118765
[I 2024-04-15 17:44:25,116] Trial 89 finished with value: 0.1823806892708512 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.3528072404539017, 'n_estimators': 227, 'learning_rate': 0.05111581657958066}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2124907218952909
Fold 2 IBS: 0.15967025651714464
Fold 3 IBS: 0.17384665469257665
Fold 4 IBS: 0.17625486389298917
Fold 5 IBS: 0.17398724642368726
[I 2024-04-15 17:44:28,410] Trial 90 finished with value: 0.17924994868433772 and parameters: {'subsample': 0.8834681396597655, 'dropout_rate': 0.22632503702549525, 'n_estimators': 262, 'learning_rate': 0.03436757545821918}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.21778963132035248
Fold 2 IBS: 0.15254292650897053
Fold 3 IBS: 0.17213562601480073
Fold 4 IBS: 0.170786734725593
Fold 5 IBS: 0.17230264186456143
[I 2024-04-15 17:44:30,270] Trial 91 finished with value: 0.17711151208685566 and parameters: {'subsample': 0.9513719699451664, 'dropout_rate': 0.27063708278212173, 'n_estimators': 199, 'learning_rate': 0.05473296393053623}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.22742784281299042
Fold 2 IBS: 0.1439684020047994
Fold 3 IBS: 0.172140812621546
Fold 4 IBS: 0.1662117165068955
Fold 5 IBS: 0.17227257161144782
[I 2024-04-15 17:44:33,363] Trial 92 finished with value: 0.17640426911153584 and parameters: {'subsample': 0.917594397883121, 'dropout_rate': 0.3800876601200347, 'n_estimators': 307, 'learning_rate': 0.04711743206057394}. Best is trial 35 with value: 0.17623804924912195.
Fold 1 IBS: 0.2232469578180775
Fold 2 IBS: 0.1467782641127805
Fold 3 IBS: 0.17162312620422984
Fold 4 IBS: 0.16776257110414144
Fold 5 IBS: 0.17175928207766458
[I 2024-04-15 17:44:35,319] Trial 93 finished with value: 0.17623404026337877 and parameters: {'subsample': 0.99766016156918, 'dropout_rate': 0.5332726920984945, 'n_estimators': 244, 'learning_rate': 0.052564680229078654}. Best is trial 93 with value: 0.17623404026337877.
Fold 1 IBS: 0.21965774105251537
Fold 2 IBS: 0.1502264871921199
Fold 3 IBS: 0.17174108244881411
Fold 4 IBS: 0.16969409913413733
Fold 5 IBS: 0.17193340593501727
[I 2024-04-15 17:44:36,959] Trial 94 finished with value: 0.1766505631525208 and parameters: {'subsample': 0.9938817744104784, 'dropout_rate': 0.5306326676271426, 'n_estimators': 218, 'learning_rate': 0.052778999075001456}. Best is trial 93 with value: 0.17623404026337877.
Fold 1 IBS: 0.24183120303189198

Fold 2 IBS: 0.13948590962604285
Fold 3 IBS: 0.18096535951774095
Fold 4 IBS: 0.16548661220266322
Fold 5 IBS: 0.17800070355702288
[I 2024-04-15 17:44:40,974] Trial 95 finished with value: 0.1811539575870724 and parameters: {'subsample': 0.9762033205972742, 'dropout_rate': 0.49501037899026445, 'n_estimators': 353, 'learning_rate': 0.0607083567203958}. Best is trial 93 with value: 0.17623404026337877.
Fold 1 IBS: 0.2207576570502906
Fold 2 IBS: 0.1492854267724223
Fold 3 IBS: 0.1716590418669343
Fold 4 IBS: 0.16914562033169253
Fold 5 IBS: 0.17183582183224355
[I 2024-04-15 17:44:43,309] Trial 96 finished with value: 0.17653671357071665 and parameters: {'subsample': 0.9534755793524864, 'dropout_rate': 0.5589265767344522, 'n_estimators': 273, 'learning_rate': 0.043402912975557775}. Best is trial 93 with value: 0.17623404026337877.
Fold 1 IBS: 0.2334916712205732
Fold 2 IBS: 0.14074869741869392
Fold 3 IBS: 0.17467276277616783
Fold 4 IBS: 0.16505173801398437
Fold 5 IBS: 0.1739403109193091
[I 2024-04-15 17:44:46,154] Trial 97 finished with value: 0.17758103606974568 and parameters: {'subsample': 0.9996285920875666, 'dropout_rate': 0.6065398819432302, 'n_estimators': 332, 'learning_rate': 0.051482345402000175}. Best is trial 93 with value: 0.17623404026337877.
Fold 1 IBS: 0.2268147716497721
Fold 2 IBS: 0.1440708775162612
Fold 3 IBS: 0.17215582426740778
Fold 4 IBS: 0.16668230131936876
Fold 5 IBS: 0.17213979279252475
[I 2024-04-15 17:44:48,569] Trial 98 finished with value: 0.17637271350906691 and parameters: {'subsample': 0.8992967119157801, 'dropout_rate': 0.6923677852245457, 'n_estimators': 290, 'learning_rate': 0.04890991502079249}. Best is trial 93 with value: 0.17623404026337877.
Fold 1 IBS: 0.22371798860334555
Fold 2 IBS: 0.14649367048684975
Fold 3 IBS: 0.17215738584616716
Fold 4 IBS: 0.16772954970943446
Fold 5 IBS: 0.17175393164788136
[I 2024-04-15 17:44:50,653] Trial 99 finished with value: 0.17637050525873563 and parameters: {'subsample': 0.8741616092572229, 'dropout_rate': 0.2971923215784751, 'n_estimators': 238, 'learning_rate': 0.05422796322778926}. Best is trial 93 with value: 0.17623404026337877.


* Best trial for IBS:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.17623404026337877], datetime_start=datetime.datetime(2024, 4, 15, 17, 44, 33, 373493), datetime_complete=datetime.datetime(2024, 4, 15, 17, 44, 35, 318123), params={'subsample': 0.99766016156918, 'dropout_rate': 0.5332726920984945, 'n_estimators': 244, 'learning_rate': 0.052564680229078654}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=93, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.99766016156918, 'dropout_rate': 0.5332726920984945, 'n_estimators': 244, 'learning_rate': 0.052564680229078654}


* Best Score for IBS:
 0.17623404026337877

In [66]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.682
train_ibs:  0.176

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7165502912345604,
                                              learning_rate=0.09279671898160717,
                                              n_estimators=496,
                                              random_state=123,
                                              subsample=0.985919291330434)

C-index score: 0.58

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5332726920984945,
                                              learning_rate=0.052564680229078654,
                                              n_estimators=244,
                                              random_state=123,
                                              subsample=0.99766016156918)

IBS: 0.229

In [70]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [71]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.846   1.0
ExtraSurvivalTrees               0.791   2.0
GradientBoosting                 0.765   3.0
CoxElastic                       0.738   4.0
CoxPH                            0.736   5.5
CoxLasso                         0.736   5.5
CoxRidge                         0.722   7.0
ComponentwiseGradientBoosting    0.682   8.0

In [72]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxLasso                       0.171   2.0
CoxElastic                     0.171   2.0
Randomsurvivalforest           0.171   2.0
CoxPH                          0.172   4.0
ExtraSurvivalTrees             0.176   5.5
ComponentwiseGradientBoosting  0.176   5.5
GradientBoosting               0.207   7.0
CoxRidge                       0.217   8.0

In [73]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.602   1.0
ComponentwiseGradientBoosting    0.580   2.0
GradientBoosting                 0.579   3.0
ExtraSurvivalTrees               0.572   4.0
CoxPH                            0.567   5.5
CoxElastic                       0.567   5.5
CoxLasso                         0.566   7.0
CoxRidge                         0.565   8.0

In [74]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.218   1.0
CoxRidge                       0.221   2.5
ExtraSurvivalTrees             0.221   2.5
ComponentwiseGradientBoosting  0.229   4.0
Randomsurvivalforest           0.233   5.0
CoxLasso                       0.257   6.5
CoxElastic                     0.257   6.5
CoxPH                          0.259   8.0

In [75]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/minmax/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_minmax_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [76]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-15