In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

In [14]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [15]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [16]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [17]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

# Feature Selection

In [18]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"glcm_ClusterShade_d_1_PET_b2",                        
"gldm_DependenceEntropy_d_1_PET_c04",            
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2"
]

In [19]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [20]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [23]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [24]:
X_new

,glcm_ClusterShade_d_1_PET_b2,gldm_DependenceEntropy_d_1_PET_c04,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,10.600998,6.795642,0.000959
1,1.734460,6.637753,0.002776
2,1.761780,6.894124,0.001179
3,0.159909,6.578202,0.002748
4,-0.177915,6.800483,0.002309
...,...,...,...
134,9.578449,6.662260,0.001347
135,-0.557128,6.874148,0.000850
136,28.029294,6.659339,0.001111
137,0.111923,6.812758,0.000935
138,-0.088922,6.758582,0.000629

In [25]:
X_new_std

,glcm_ClusterShade_d_1_PET_b2,gldm_DependenceEntropy_d_1_PET_c04,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,0.248118,0.865889,0.138260
1,0.222288,0.788611,0.522853
2,0.222368,0.914091,0.184826
3,0.217702,0.759464,0.516826
4,0.216717,0.868259,0.424002
...,...,...,...
134,0.245139,0.800606,0.220460
135,0.215613,0.904313,0.115152
136,0.298890,0.799176,0.170483
137,0.217562,0.874266,0.133243
138,0.216977,0.847750,0.068498

In [26]:
MAASTRO_new

,glcm_ClusterShade_d_1_PET_b2,gldm_DependenceEntropy_d_1_PET_c04,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,-6.132486,6.814563,0.000768
1,11.365721,6.154990,0.001213
2,18.556645,6.673632,0.001176
3,6.670130,6.577609,0.001192
4,6.613032,6.735323,0.000766
...,...,...,...
94,467.061873,6.559987,0.001137
95,34.619690,6.579052,0.000962
96,4.698589,6.675182,0.000621
97,20.628059,6.636306,0.000947
98,23.257105,6.421117,0.001661

In [27]:
MAASTRO_new_std

,glcm_ClusterShade_d_1_PET_b2,gldm_DependenceEntropy_d_1_PET_c04,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,0.199371,0.875150,0.097918
1,0.250346,0.552325,0.192033
2,0.271294,0.806172,0.184231
3,0.236667,0.759174,0.187680
4,0.236501,0.836366,0.097424
...,...,...,...
94,1.577870,0.750549,0.175997
95,0.318089,0.759880,0.138832
96,0.230923,0.806930,0.066663
97,0.277329,0.787903,0.135787
98,0.284988,0.682580,0.286841

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [28]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:31:47,098] A new study created in memory with name: no-name-b797f12c-4e20-4f37-99c6-dcb54af3e37c

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.5654008438818565

[I 2024-04-18 15:31:55,446] A new study created in memory with name: no-name-469979d8-7697-4abb-a108-280d9e24bc4e

Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:31:55,404] Trial 0 finished with value: 0.5865944720649081 and parameters: {}. Best is trial 0 with value: 0.5865944720649081.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5865944720649081], datetime_start=datetime.datetime(2024, 4, 18, 15, 31, 47, 344630), datetime_complete=datetime.datetime(2024, 4, 18, 15, 31, 55, 404320), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5865944720649081

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2072073965240718
Fold 2 IBS: 0.235783939334261
Fold 3 IBS: 0.2101831535572281
Fold 4 IBS: 0.2325951649890866
Fold 5 IBS: 0.2127734461819334
[I 2024-04-18 15:31:56,039] Trial 0 finished with value: 0.21970862011731618 and parameters: {}. Best is trial 0 with value: 0.21970862011731618.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21970862011731618], datetime_start=datetime.datetime(2024, 4, 18, 15, 31, 55, 491436), datetime_complete=datetime.datetime(2024, 4, 18, 15, 31, 56, 39460), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21970862011731618

In [29]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [30]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.587
train_ibs:  0.22

#### Test

In [31]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [32]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.51
IBS score: 0.244

In [33]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:31:56,519] A new study created in memory with name: no-name-9f1e98f1-5ef3-4395-bae0-aa2ab60c3350

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-18 15:31:56,799] A new study created in memory with name: no-name-a579926b-c2b8-4ea5-b6a1-3bf0f4c2b8dc

Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.4888392857142857
Fold 3 C-index: 0.4950980392156863
Fold 4 C-index: 0.4810126582278481
Fold 5 C-index: 0.5352112676056338
[I 2024-04-18 15:31:56,759] Trial 0 finished with value: 0.5091231592435997 and parameters: {}. Best is trial 0 with value: 0.5091231592435997.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5091231592435997], datetime_start=datetime.datetime(2024, 4, 18, 15, 31, 56, 587059), datetime_complete=datetime.datetime(2024, 4, 18, 15, 31, 56, 759529), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5091231592435997

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652170337672
Fold 2 IBS: 0.22157791714212602
Fold 3 IBS: 0.20453594728663624
Fold 4 IBS: 0.22473804149506002
Fold 5 IBS: 0.21812431419451353
[I 2024-04-18 15:31:57,140] Trial 0 finished with value: 0.21659054836434252 and parameters: {}. Best is trial 0 with value: 0.21659054836434252.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054836434252], datetime_start=datetime.datetime(2024, 4, 18, 15, 31, 56, 849372), datetime_complete=datetime.datetime(2024, 4, 18, 15, 31, 57, 140300), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054836434252

In [36]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.509
train_ibs:  0.217

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.515

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:31:57,621] A new study created in memory with name: no-name-ec3bdc2e-8881-4738-9c51-b28aa287b824

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-18 15:31:58,125] A new study created in memory with name: no-name-585f8f2e-418f-449d-b2ae-95930e566583

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5044642857142857
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:31:58,117] Trial 0 finished with value: 0.5829797987932105 and parameters: {}. Best is trial 0 with value: 0.5829797987932105.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5829797987932105], datetime_start=datetime.datetime(2024, 4, 18, 15, 31, 57, 661209), datetime_complete=datetime.datetime(2024, 4, 18, 15, 31, 58, 116725), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5829797987932105

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.20732081999162522
Fold 2 IBS: 0.23513408475992012
Fold 3 IBS: 0.21003243321526188
Fold 4 IBS: 0.2318346449499706
Fold 5 IBS: 0.21265563895030948
[I 2024-04-18 15:31:58,555] Trial 0 finished with value: 0.2193955243734175 and parameters: {}. Best is trial 0 with value: 0.2193955243734175.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2193955243734175], datetime_start=datetime.datetime(2024, 4, 18, 15, 31, 58, 229450), datetime_complete=datetime.datetime(2024, 4, 18, 15, 31, 58, 555371), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2193955243734175

In [42]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.583
train_ibs:  0.219

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.509

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.244

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:31:59,023] A new study created in memory with name: no-name-26a47cc2-4790-4271-b9eb-47ff33cdae0f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:31:59,583] Trial 0 finished with value: 0.5848530480929304 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.5848530480929304.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:31:59,911] Trial 1 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:00,117] Trial 2 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:00,663] Trial 3 finished with value: 0.5857920152290806 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:01,226] Trial 4 finished with value: 0.5848530480929304 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5316455696202531
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:01,875] Trial 5 finished with value: 0.5790190413674992 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5044642857142857
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:02,433] Trial 6 finished with value: 0.5829797987932105 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:03,070] Trial 7 finished with value: 0.5848530480929304 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:03,925] Trial 8 finished with value: 0.5849262143632797 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:04,400] Trial 9 finished with value: 0.5781970785202198 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:04,589] Trial 10 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:04,742] Trial 11 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.016444541243212374}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:04,921] Trial 12 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.0873928389796849}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:04,992] Trial 13 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.2094262397934587}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:05,081] Trial 14 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.22873824149538122}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:05,258] Trial 15 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.12238096132521564}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:05,556] Trial 16 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.30518868850921266}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:05,959] Trial 17 finished with value: 0.5967831044798996 and parameters: {'l1_ratio': 0.34921453367691924}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:06,314] Trial 18 finished with value: 0.5967831044798996 and parameters: {'l1_ratio': 0.33043909651116166}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:06,821] Trial 19 finished with value: 0.5857920152290806 and parameters: {'l1_ratio': 0.5894441580285619}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5044642857142857
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:07,213] Trial 20 finished with value: 0.5839601909500732 and parameters: {'l1_ratio': 0.8926263580615379}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:07,696] Trial 21 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.28958132109063406}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:08,064] Trial 22 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.28817431138728605}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:08,416] Trial 23 finished with value: 0.5849262143632797 and parameters: {'l1_ratio': 0.45587715553173785}. Best is trial 1 with value: 0.599461675908471.

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:08,680] Trial 24 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.16849061787677855}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:09,038] Trial 25 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.27595381852701706}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:09,382] Trial 26 finished with value: 0.5958441373437494 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:09,655] Trial 27 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:10,327] Trial 28 finished with value: 0.5857920152290806 and parameters: {'l1_ratio': 0.5503817127978923}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:10,794] Trial 29 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.29868667698439827}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:10,996] Trial 30 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.17419351850993045}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:11,241] Trial 31 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.3013220087820099}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:11,665] Trial 32 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.27357119396913165}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:12,118] Trial 33 finished with value: 0.5781970785202198 and parameters: {'l1_ratio': 0.3866409251813969}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:12,355] Trial 34 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.23800705470004122}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:12,997] Trial 35 finished with value: 0.5857920152290806 and parameters: {'l1_ratio': 0.5201794471554237}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5316455696202531
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:13,480] Trial 36 finished with value: 0.5798848422333001 and parameters: {'l1_ratio': 0.4368446763418297}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:14,005] Trial 37 finished with value: 0.5848530480929304 and parameters: {'l1_ratio': 0.6211628295087083}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:14,246] Trial 38 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.13839301450684327}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:14,715] Trial 39 finished with value: 0.5781970785202198 and parameters: {'l1_ratio': 0.3832648927387554}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:14,950] Trial 40 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.2033301466036544}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:15,291] Trial 41 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.2698523473587069}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:15,811] Trial 42 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.3126955471159528}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:16,163] Trial 43 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.257273419104366}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:16,380] Trial 44 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.062069898702991955}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5316455696202531
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:16,945] Trial 45 finished with value: 0.5790190413674992 and parameters: {'l1_ratio': 0.4239182736669648}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:17,146] Trial 46 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.18097197202077514}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:17,812] Trial 47 finished with value: 0.5857920152290806 and parameters: {'l1_ratio': 0.49175589163076455}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147

Fold 2 C-index: 0.5044642857142857
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:18,329] Trial 48 finished with value: 0.5839601909500732 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:18,813] Trial 49 finished with value: 0.5958441373437494 and parameters: {'l1_ratio': 0.355745098499332}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:19,009] Trial 50 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.14002150361461355}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:19,423] Trial 51 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.28405411815305653}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:19,522] Trial 52 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.3205419509778473}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:19,646] Trial 53 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.22583004193318748}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:19,974] Trial 54 finished with value: 0.5781970785202198 and parameters: {'l1_ratio': 0.3938644336733024}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:20,218] Trial 55 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.24696819434139322}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:20,627] Trial 56 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.30093462591446074}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:21,166] Trial 57 finished with value: 0.5958441373437494 and parameters: {'l1_ratio': 0.35155240719786784}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:22,324] Trial 58 finished with value: 0.5857920152290806 and parameters: {'l1_ratio': 0.4707414850815731}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:22,748] Trial 59 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.09306009261235579}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:22,887] Trial 60 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.19820203989734816}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:23,228] Trial 61 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.29756980464029664}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:23,601] Trial 62 finished with value: 0.5967831044798996 and parameters: {'l1_ratio': 0.33400177533927666}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:23,981] Trial 63 finished with value: 0.5781970785202198 and parameters: {'l1_ratio': 0.3901584848881458}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:24,546] Trial 64 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.26661410419426507}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:24,722] Trial 65 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.1681367108124294}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:24,883] Trial 66 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.2283450959509596}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:25,199] Trial 67 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.2948772650088152}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5316455696202531
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:25,792] Trial 68 finished with value: 0.5790190413674992 and parameters: {'l1_ratio': 0.45234365359655804}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5274261603375527
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:26,422] Trial 69 finished with value: 0.5781751595109591 and parameters: {'l1_ratio': 0.416313166934335}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:26,977] Trial 70 finished with value: 0.5967831044798996 and parameters: {'l1_ratio': 0.3462610088490078}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:27,307] Trial 71 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.2776620711522473}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524

Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:27,629] Trial 72 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.3199609828600934}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:27,854] Trial 73 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.24499966667724404}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:28,126] Trial 74 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.2105882521631447}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:28,681] Trial 75 finished with value: 0.5781970785202198 and parameters: {'l1_ratio': 0.3766127246458087}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:28,782] Trial 76 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.26684685126372826}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:29,045] Trial 77 finished with value: 0.5967831044798996 and parameters: {'l1_ratio': 0.36799046854789397}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:29,308] Trial 78 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.05973631796525841}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5044642857142857
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:29,790] Trial 79 finished with value: 0.5829797987932105 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:30,002] Trial 80 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.1284732856957044}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:30,302] Trial 81 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.2818902103613824}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:30,550] Trial 82 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.3232242891600939}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:30,745] Trial 83 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.19100776304589728}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:31,049] Trial 84 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.25480018262500165}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5274261603375527
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:31,796] Trial 85 finished with value: 0.57904096037676 and parameters: {'l1_ratio': 0.4070815650556022}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:31,987] Trial 86 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.22647898739896233}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:32,115] Trial 87 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.1670253023085477}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:32,272] Trial 88 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.3022437697098225}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:32,464] Trial 89 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.1546499322895154}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5611814345991561
Fold 5 C-index: 0.5727699530516432
[I 2024-04-18 15:32:32,989] Trial 90 finished with value: 0.5848530480929304 and parameters: {'l1_ratio': 0.7135825642664739}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:33,288] Trial 91 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.31222356637644405}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:33,575] Trial 92 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.27665864212400443}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:33,960] Trial 93 finished with value: 0.5967831044798996 and parameters: {'l1_ratio': 0.3324249909650436}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:34,409] Trial 94 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.21051514959835033}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:34,849] Trial 95 finished with value: 0.5958441373437494 and parameters: {'l1_ratio': 0.3597614551958207}. Best is trial 1 with value: 0.599461675908471.

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:35,321] Trial 96 finished with value: 0.599461675908471 and parameters: {'l1_ratio': 0.3023768503808651}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:35,612] Trial 97 finished with value: 0.5985227087723207 and parameters: {'l1_ratio': 0.25219563350867225}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5232067510548524
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 15:32:36,039] Trial 98 finished with value: 0.5967831044798996 and parameters: {'l1_ratio': 0.3407613992756223}. Best is trial 1 with value: 0.599461675908471.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5189873417721519
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:32:36,244] Trial 99 finished with value: 0.5976788269157807 and parameters: {'l1_ratio': 0.230041923372601}. Best is trial 1 with value: 0.599461675908471.

[I 2024-04-18 15:32:36,323] A new study created in memory with name: no-name-2384175c-e962-464f-a47e-b41507b2ab88

* Best trial for C-index:
 FrozenTrial(number=1, state=TrialState.COMPLETE, values=[0.599461675908471], datetime_start=datetime.datetime(2024, 4, 18, 15, 31, 59, 591071), datetime_complete=datetime.datetime(2024, 4, 18, 15, 31, 59, 911386), params={'l1_ratio': 0.28621072101688444}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=1, value=None)


* Best Score for C-index:
 0.599461675908471

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.20735306003203285
Fold 2 IBS: 0.23510689530110074
Fold 3 IBS: 0.20995562340403068
Fold 4 IBS: 0.2320868603307757
Fold 5 IBS: 0.212581035556721
[I 2024-04-18 15:32:37,036] Trial 0 finished with value: 0.21941669492493218 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.21941669492493218.
Fold 1 IBS: 0.21310497248745883
Fold 2 IBS: 0.22142902000754777
Fold 3 IBS: 0.2044380615998667
Fold 4 IBS: 0.2247079028259898
Fold 5 IBS: 0.21249787995653635
[I 2024-04-18 15:32:37,399] Trial 1 finished with value: 0.21523556737547986 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.213316077598853
Fold 2 IBS: 0.22146347690795165
Fold 3 IBS: 0.20445782912422153
Fold 4 IBS: 0.2247678764816068
Fold 5 IBS: 0.21550964200312706
[I 2024-04-18 15:32:37,631] Trial 2 finished with value: 0.21590298042315198 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.20735621439473806
Fold 2 IBS: 0.2350972901968195
Fold 3 IBS: 0.20993336833063617
Fold 4 IBS: 0.23213775126533648
Fold 5 IBS: 0.2125490685938215
[I 2024-04-18 15:32:38,263] Trial 3 finished with value: 0.21941473855627036 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.20734460447348496
Fold 2 IBS: 0.23508401243650356
Fold 3 IBS: 0.20995159911036493
Fold 4 IBS: 0.232058502266383
Fold 5 IBS: 0.2125726794725191
[I 2024-04-18 15:32:38,880] Trial 4 finished with value: 0.2194022795518511 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.2073585753584278
Fold 2 IBS: 0.23509027915335443
Fold 3 IBS: 0.2099179071312731
Fold 4 IBS: 0.22444048847709688
Fold 5 IBS: 0.21251411042826
[I 2024-04-18 15:32:39,580] Trial 5 finished with value: 0.21786427210968246 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.20732728119061328
Fold 2 IBS: 0.23515959903577435
Fold 3 IBS: 0.21002526883502365
Fold 4 IBS: 0.2318850555724941
Fold 5 IBS: 0.21264685970429717
[I 2024-04-18 15:32:40,171] Trial 6 finished with value: 0.2194088128676405 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.20735754271639573
Fold 2 IBS: 0.23508675804579696
Fold 3 IBS: 0.20994705080570336
Fold 4 IBS: 0.23207724763534157
Fold 5 IBS: 0.21257431110331956
[I 2024-04-18 15:32:40,634] Trial 7 finished with value: 0.21940858206131142 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.20735917770841367
Fold 2 IBS: 0.23508586562324016
Fold 3 IBS: 0.20992168105970568
Fold 4 IBS: 0.23215316266231026
Fold 5 IBS: 0.21251546103587476
[I 2024-04-18 15:32:41,065] Trial 8 finished with value: 0.2194070696179089 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21267663202552392
Fold 2 IBS: 0.23508381610156717
Fold 3 IBS: 0.20991269940724
Fold 4 IBS: 0.2245183217046315
Fold 5 IBS: 0.21251014484236938
[I 2024-04-18 15:32:41,684] Trial 9 finished with value: 0.21894032281626638 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.2137167077288099
Fold 2 IBS: 0.22153185093227398
Fold 3 IBS: 0.20450247490960766
Fold 4 IBS: 0.22479862903317668
Fold 5 IBS: 0.21704509593151822
[I 2024-04-18 15:32:41,987] Trial 10 finished with value: 0.2163189517070773 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21369860020720916
Fold 2 IBS: 0.221528686810189
Fold 3 IBS: 0.20450026904083235
Fold 4 IBS: 0.22480012240611386
Fold 5 IBS: 0.21697231585051088
[I 2024-04-18 15:32:42,313] Trial 11 finished with value: 0.21629999886297102 and parameters: {'l1_ratio': 0.10435988842665224}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21320604237225776
Fold 2 IBS: 0.2214453654631641
Fold 3 IBS: 0.2044471818029048
Fold 4 IBS: 0.22473978491586732
Fold 5 IBS: 0.21248841851835099
[I 2024-04-18 15:32:42,767] Trial 12 finished with value: 0.21526535861450896 and parameters: {'l1_ratio': 0.25848394608656616}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21322994322398098
Fold 2 IBS: 0.2214492722494351
Fold 3 IBS: 0.2044494318589687
Fold 4 IBS: 0.2247464953257202
Fold 5 IBS: 0.21519996323850538
[I 2024-04-18 15:32:43,024] Trial 13 finished with value: 0.21581502117932208 and parameters: {'l1_ratio': 0.25175477458330975}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21312834829540062
Fold 2 IBS: 0.22143277465531122
Fold 3 IBS: 0.20444011348041316
Fold 4 IBS: 0.22471576603667345
Fold 5 IBS: 0.21249011860511421
[I 2024-04-18 15:32:43,354] Trial 14 finished with value: 0.2152414242145825 and parameters: {'l1_ratio': 0.2799002900234457}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21396019300579033
Fold 2 IBS: 0.22157498730403924
Fold 3 IBS: 0.20453374606331673
Fold 4 IBS: 0.22474427457637436
Fold 5 IBS: 0.21805457783230373
[I 2024-04-18 15:32:43,678] Trial 15 finished with value: 0.2165735557563649 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21282836094967045
Fold 2 IBS: 0.23512435245506585
Fold 3 IBS: 0.20441653915318508
Fold 4 IBS: 0.22459463790427486
Fold 5 IBS: 0.2125000771115309
[I 2024-04-18 15:32:44,188] Trial 16 finished with value: 0.21789279351474544 and parameters: {'l1_ratio': 0.3565983398076921}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21351737872815854
Fold 2 IBS: 0.22149738768732025
Fold 3 IBS: 0.20447915040543757
Fold 4 IBS: 0.2247989153186614
Fold 5 IBS: 0.21626155031074545
[I 2024-04-18 15:32:44,542] Trial 17 finished with value: 0.21611087649006464 and parameters: {'l1_ratio': 0.16511694733206428}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.2073609326550757
Fold 2 IBS: 0.23507498292534193
Fold 3 IBS: 0.20992778827715167
Fold 4 IBS: 0.23211512942167759
Fold 5 IBS: 0.21254300554353514
[I 2024-04-18 15:32:45,250] Trial 18 finished with value: 0.21940436776455638 and parameters: {'l1_ratio': 0.5731306953413426}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21287822835125755
Fold 2 IBS: 0.23509515395759512
Fold 3 IBS: 0.20442003083332436
Fold 4 IBS: 0.2246176416130852
Fold 5 IBS: 0.2124903914497962
[I 2024-04-18 15:32:45,826] Trial 19 finished with value: 0.2179002892410117 and parameters: {'l1_ratio': 0.34446003329366204}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.2073374918032605
Fold 2 IBS: 0.23511126261448317
Fold 3 IBS: 0.2099946223760547
Fold 4 IBS: 0.2319549488102233
Fold 5 IBS: 0.21262937272299445
[I 2024-04-18 15:32:46,476] Trial 20 finished with value: 0.21940553966540324 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.2131523451943561
Fold 2 IBS: 0.22143664540417157
Fold 3 IBS: 0.2044422560971483
Fold 4 IBS: 0.22472353654313387
Fold 5 IBS: 0.21248476015971682
[I 2024-04-18 15:32:46,840] Trial 21 finished with value: 0.21524790867970536 and parameters: {'l1_ratio': 0.2733589608767589}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21312716120919267
Fold 2 IBS: 0.2214325836034118
Fold 3 IBS: 0.20444000843855092
Fold 4 IBS: 0.22471537366096128
Fold 5 IBS: 0.21249052283926967
[I 2024-04-18 15:32:47,184] Trial 22 finished with value: 0.21524112995027728 and parameters: {'l1_ratio': 0.28022220703139233}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.213539274598485
Fold 2 IBS: 0.22150113246593794
Fold 3 IBS: 0.20448160768137452
Fold 4 IBS: 0.22480051695670847
Fold 5 IBS: 0.21634572343422578
[I 2024-04-18 15:32:47,286] Trial 23 finished with value: 0.21613365102734633 and parameters: {'l1_ratio': 0.15804789191078314}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.2139327560937731
Fold 2 IBS: 0.22157007436439807
Fold 3 IBS: 0.20453007619381505
Fold 4 IBS: 0.22475395833234532
Fold 5 IBS: 0.21793796988796943
[I 2024-04-18 15:32:47,455] Trial 24 finished with value: 0.21654496697446018 and parameters: {'l1_ratio': 0.017436902412143185}. Best is trial 1 with value: 0.21523556737547986.
Fold 1 IBS: 0.21297069435941218
Fold 2 IBS: 0.22140776956608546
Fold 3 IBS: 0.2044269653495112
Fold 4 IBS: 0.22465738812184446

Fold 5 IBS: 0.21249065734361278
[I 2024-04-18 15:32:47,814] Trial 25 finished with value: 0.2151906949480932 and parameters: {'l1_ratio': 0.3213310297120281}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2073521174053621
Fold 2 IBS: 0.2351194373117346
Fold 3 IBS: 0.20990620898333778
Fold 4 IBS: 0.2244022331390709
Fold 5 IBS: 0.21250196464710835
[I 2024-04-18 15:32:48,283] Trial 26 finished with value: 0.21785639229732273 and parameters: {'l1_ratio': 0.43696099753129897}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21289613981078195
Fold 2 IBS: 0.2350840344314056
Fold 3 IBS: 0.2044213278505824
Fold 4 IBS: 0.2246256406318187
Fold 5 IBS: 0.21250787285575445
[I 2024-04-18 15:32:48,750] Trial 27 finished with value: 0.2179070031160686 and parameters: {'l1_ratio': 0.3400437980759289}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20735976559162822
Fold 2 IBS: 0.23508128860697247
Fold 3 IBS: 0.2099265523791654
Fold 4 IBS: 0.2321301216429068
Fold 5 IBS: 0.21254321474573412
[I 2024-04-18 15:32:49,396] Trial 28 finished with value: 0.2194081885932814 and parameters: {'l1_ratio': 0.5429131701707054}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21346644210700796
Fold 2 IBS: 0.2214887174411243
Fold 3 IBS: 0.20447353703194707
Fold 4 IBS: 0.22479377104692272
Fold 5 IBS: 0.21606755070543454
[I 2024-04-18 15:32:49,689] Trial 29 finished with value: 0.21605800366648734 and parameters: {'l1_ratio': 0.1812894646689271}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20734990052396232
Fold 2 IBS: 0.2351235205250305
Fold 3 IBS: 0.2099307815867047
Fold 4 IBS: 0.2321251311499394
Fold 5 IBS: 0.21256306815083695
[I 2024-04-18 15:32:50,411] Trial 30 finished with value: 0.21941848038729478 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2130445218793748
Fold 2 IBS: 0.22141938504636183
Fold 3 IBS: 0.20443291905362776
Fold 4 IBS: 0.2246862633598215
Fold 5 IBS: 0.2124913933925915
[I 2024-04-18 15:32:50,730] Trial 31 finished with value: 0.21521489654635548 and parameters: {'l1_ratio': 0.30225486973014093}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21297796711968636
Fold 2 IBS: 0.22140890618641354
Fold 3 IBS: 0.20442753562643615
Fold 4 IBS: 0.22466034819301706
Fold 5 IBS: 0.21248852991613248
[I 2024-04-18 15:32:51,149] Trial 32 finished with value: 0.2151926574083371 and parameters: {'l1_ratio': 0.31947640738175564}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2129160745322241
Fold 2 IBS: 0.23507123464995042
Fold 3 IBS: 0.20442279770386576
Fold 4 IBS: 0.22463437607340292
Fold 5 IBS: 0.21250270752630687
[I 2024-04-18 15:32:51,573] Trial 33 finished with value: 0.21790943809715002 and parameters: {'l1_ratio': 0.3350929716780729}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2073609805898535
Fold 2 IBS: 0.23507773227857617
Fold 3 IBS: 0.20991821541155592
Fold 4 IBS: 0.23214928760279052
Fold 5 IBS: 0.21251217690795687
[I 2024-04-18 15:32:52,217] Trial 34 finished with value: 0.21940367855814663 and parameters: {'l1_ratio': 0.4770138322209352}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21341803620085345
Fold 2 IBS: 0.2214805329212076
Fold 3 IBS: 0.20446833797031175
Fold 4 IBS: 0.22478712153839783
Fold 5 IBS: 0.21588553915389658
[I 2024-04-18 15:32:52,528] Trial 35 finished with value: 0.21600791355693344 and parameters: {'l1_ratio': 0.19631609988412568}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.207359026237845
Fold 2 IBS: 0.23508824323415792
Fold 3 IBS: 0.20991703970663073
Fold 4 IBS: 0.22444299160148873
Fold 5 IBS: 0.21251328895488797
[I 2024-04-18 15:32:53,210] Trial 36 finished with value: 0.21786411794700208 and parameters: {'l1_ratio': 0.42223193151326144}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21373726886472158
Fold 2 IBS: 0.22153545151382018
Fold 3 IBS: 0.20450500025432286
Fold 4 IBS: 0.22479654560658077
Fold 5 IBS: 0.21712812475389562
[I 2024-04-18 15:32:53,576] Trial 37 finished with value: 0.2163404781986682 and parameters: {'l1_ratio': 0.09069801726563134}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20734553198893313
Fold 2 IBS: 0.23507649200635838
Fold 3 IBS: 0.20996158973306772
Fold 4 IBS: 0.23201472672982876
Fold 5 IBS: 0.21259381289407533
[I 2024-04-18 15:32:54,207] Trial 38 finished with value: 0.21939843067045267 and parameters: {'l1_ratio': 0.7883002392124641}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21271543955347316
Fold 2 IBS: 0.23512513206044847
Fold 3 IBS: 0.20990372797733628
Fold 4 IBS: 0.224538715772376
Fold 5 IBS: 0.21250164758785087
[I 2024-04-18 15:32:54,956] Trial 39 finished with value: 0.21895693259029697 and parameters: {'l1_ratio': 0.3832648927387554}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2133560302616674
Fold 2 IBS: 0.22147012999098167
Fold 3 IBS: 0.20446187466212426
Fold 4 IBS: 0.22477623322188792
Fold 5 IBS: 0.21565573101643498
[I 2024-04-18 15:32:55,260] Trial 40 finished with value: 0.21594399983061924 and parameters: {'l1_ratio': 0.21509638047730995}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21305410904988112
Fold 2 IBS: 0.22142090579290713
Fold 3 IBS: 0.2044337187340287
Fold 4 IBS: 0.2246898183239994
Fold 5 IBS: 0.21249144968342004
[I 2024-04-18 15:32:55,649] Trial 41 finished with value: 0.2152180003168473 and parameters: {'l1_ratio': 0.299736338210703}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21297808900557957
Fold 2 IBS: 0.22140892524971506
Fold 3 IBS: 0.20442754521431405
Fold 4 IBS: 0.22466039758999046
Fold 5 IBS: 0.21248849400361183
[I 2024-04-18 15:32:56,010] Trial 42 finished with value: 0.2151926902126422 and parameters: {'l1_ratio': 0.3194452802726416}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2130244682406807
Fold 2 IBS: 0.2214162131563653
Fold 3 IBS: 0.2044312659360567
Fold 4 IBS: 0.22467868059828924
Fold 5 IBS: 0.21249748830463042
[I 2024-04-18 15:32:56,362] Trial 43 finished with value: 0.21520962324720444 and parameters: {'l1_ratio': 0.3074918284405299}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20735196935904843
Fold 2 IBS: 0.23511927301973395
Fold 3 IBS: 0.2099090823558716
Fold 4 IBS: 0.23217815665521838
Fold 5 IBS: 0.21253042165787736
[I 2024-04-18 15:32:57,111] Trial 44 finished with value: 0.21941778060954995 and parameters: {'l1_ratio': 0.4668494968407524}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20735321295777825
Fold 2 IBS: 0.23511182299629485
Fold 3 IBS: 0.20991241350431583
Fold 4 IBS: 0.2321556034828329
Fold 5 IBS: 0.2125277378468933
[I 2024-04-18 15:32:57,818] Trial 45 finished with value: 0.21941215815762302 and parameters: {'l1_ratio': 0.5261661445655661}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2073542613646691
Fold 2 IBS: 0.2351105288355682
Fold 3 IBS: 0.20989937608587705
Fold 4 IBS: 0.2244897194652864
Fold 5 IBS: 0.21252091724849273
[I 2024-04-18 15:32:58,454] Trial 46 finished with value: 0.2178749605999787 and parameters: {'l1_ratio': 0.4040796383337498}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21332704548722606
Fold 2 IBS: 0.22146529935199963
Fold 3 IBS: 0.20445893032502263
Fold 4 IBS: 0.224770272147066
Fold 5 IBS: 0.2155495919700768
[I 2024-04-18 15:32:58,761] Trial 47 finished with value: 0.21591422785627823 and parameters: {'l1_ratio': 0.22370100023118425}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2130519308825919
Fold 2 IBS: 0.22142056004034866
Fold 3 IBS: 0.20443353651991344
Fold 4 IBS: 0.2246890146644927
Fold 5 IBS: 0.21249213272963932
[I 2024-04-18 15:32:59,144] Trial 48 finished with value: 0.2152174349673972 and parameters: {'l1_ratio': 0.3003093882223252}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21297718175216768
Fold 2 IBS: 0.22140878336407124
Fold 3 IBS: 0.20442747387134813
Fold 4 IBS: 0.22466002973781754
Fold 5 IBS: 0.21248876111157447
[I 2024-04-18 15:32:59,577] Trial 49 finished with value: 0.2151924459673958 and parameters: {'l1_ratio': 0.31967693815336445}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21366470659075978

Fold 2 IBS: 0.22152278158169358
Fold 3 IBS: 0.20449618607519726
Fold 4 IBS: 0.22480208336126897
Fold 5 IBS: 0.21683694481520377
[I 2024-04-18 15:32:59,922] Trial 50 finished with value: 0.21626454048482469 and parameters: {'l1_ratio': 0.11612512579368928}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21274109430401958
Fold 2 IBS: 0.23511174863702403
Fold 3 IBS: 0.20989749818601244
Fold 4 IBS: 0.2245518736933974
Fold 5 IBS: 0.21249574487264933
[I 2024-04-18 15:33:00,536] Trial 51 finished with value: 0.21895959193862052 and parameters: {'l1_ratio': 0.377303304087378}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2129882466096663
Fold 2 IBS: 0.22141051559108696
Fold 3 IBS: 0.20442834776137575
Fold 4 IBS: 0.22466448956812973
Fold 5 IBS: 0.21248547069540644
[I 2024-04-18 15:33:00,919] Trial 52 finished with value: 0.21519541404513304 and parameters: {'l1_ratio': 0.3168459994027318}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21293931003623087
Fold 2 IBS: 0.23511863934926058
Fold 3 IBS: 0.20442454565029744
Fold 4 IBS: 0.2246443324334462
Fold 5 IBS: 0.21249644195945486
[I 2024-04-18 15:33:01,393] Trial 53 finished with value: 0.217924653885738 and parameters: {'l1_ratio': 0.3292742105256383}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2132765077596848
Fold 2 IBS: 0.22145692736401065
Fold 3 IBS: 0.20445391585289643
Fold 4 IBS: 0.22475861066007446
Fold 5 IBS: 0.2153664827678793
[I 2024-04-18 15:33:01,729] Trial 54 finished with value: 0.21586248888090914 and parameters: {'l1_ratio': 0.23844749655944242}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.207353316002173
Fold 2 IBS: 0.23511402589113
Fold 3 IBS: 0.2099036900517899
Fold 4 IBS: 0.22440968832166144
Fold 5 IBS: 0.21252368589442613
[I 2024-04-18 15:33:02,743] Trial 55 finished with value: 0.2178608812322361 and parameters: {'l1_ratio': 0.4343357565948371}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21358526324309235
Fold 2 IBS: 0.2215090315919285
Fold 3 IBS: 0.204486854301802
Fold 4 IBS: 0.22480263425328356
Fold 5 IBS: 0.2165240411022734
[I 2024-04-18 15:33:03,058] Trial 56 finished with value: 0.216181564898476 and parameters: {'l1_ratio': 0.14296433545275455}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21328002110701091
Fold 2 IBS: 0.2214575072588354
Fold 3 IBS: 0.2044542595074721
Fold 4 IBS: 0.22475947222474793
Fold 5 IBS: 0.21537913215031243
[I 2024-04-18 15:33:03,251] Trial 57 finished with value: 0.21586607844967576 and parameters: {'l1_ratio': 0.23743268071524276}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21280117978390056
Fold 2 IBS: 0.2350782130362541
Fold 3 IBS: 0.20441471086600985
Fold 4 IBS: 0.2245816545149448
Fold 5 IBS: 0.2125066483164093
[I 2024-04-18 15:33:03,639] Trial 58 finished with value: 0.21787648130350373 and parameters: {'l1_ratio': 0.3631193569357235}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21300950841582839
Fold 2 IBS: 0.221413855041473
Fold 3 IBS: 0.204430050086499
Fold 4 IBS: 0.22467289609065183
Fold 5 IBS: 0.21250187377104998
[I 2024-04-18 15:33:04,106] Trial 59 finished with value: 0.21520563668110046 and parameters: {'l1_ratio': 0.31137143130772715}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2073543124901971
Fold 2 IBS: 0.23510479356448505
Fold 3 IBS: 0.20994048504974022
Fold 4 IBS: 0.23212934576445346
Fold 5 IBS: 0.21255391312638328
[I 2024-04-18 15:33:05,079] Trial 60 finished with value: 0.2194165699990518 and parameters: {'l1_ratio': 0.5892984254164416}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.212992071174127
Fold 2 IBS: 0.22141111523902002
Fold 3 IBS: 0.20442865173873503
Fold 4 IBS: 0.2246660176363304
Fold 5 IBS: 0.2124843165289292
[I 2024-04-18 15:33:05,536] Trial 61 finished with value: 0.21519643446342834 and parameters: {'l1_ratio': 0.3158646192453951}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21320658443123275
Fold 2 IBS: 0.221445453895464
Fold 3 IBS: 0.20444723244241403
Fold 4 IBS: 0.2247399407242654
Fold 5 IBS: 0.2124882145086654
[I 2024-04-18 15:33:05,887] Trial 62 finished with value: 0.21526548520040834 and parameters: {'l1_ratio': 0.2583320804553656}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20735400532063186
Fold 2 IBS: 0.23511168533794952
Fold 3 IBS: 0.2098999144988289
Fold 4 IBS: 0.2244884064734825
Fold 5 IBS: 0.21250033598072843
[I 2024-04-18 15:33:06,596] Trial 63 finished with value: 0.21787086952232423 and parameters: {'l1_ratio': 0.4046105416941057}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20735525794016138
Fold 2 IBS: 0.23510443213026433
Fold 3 IBS: 0.20990217356309246
Fold 4 IBS: 0.23217107154979716
Fold 5 IBS: 0.2125213119313979
[I 2024-04-18 15:33:07,349] Trial 64 finished with value: 0.21941084942294262 and parameters: {'l1_ratio': 0.45943495250746047}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21297108273643292
Fold 2 IBS: 0.22140783022059413
Fold 3 IBS: 0.20442699571272682
Fold 4 IBS: 0.22465754682084463
Fold 5 IBS: 0.21249054449706467
[I 2024-04-18 15:33:07,875] Trial 65 finished with value: 0.2151907999975326 and parameters: {'l1_ratio': 0.3212321233695466}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2128060728501548
Fold 2 IBS: 0.23507533672162384
Fold 3 IBS: 0.20441503604827665
Fold 4 IBS: 0.22458401453150462
Fold 5 IBS: 0.21250548738402333
[I 2024-04-18 15:33:08,516] Trial 66 finished with value: 0.21787718950711663 and parameters: {'l1_ratio': 0.361950341540099}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21313157673676864
Fold 2 IBS: 0.22143329445160942
Fold 3 IBS: 0.2044403996100355
Fold 4 IBS: 0.2247168293717911
Fold 5 IBS: 0.21248901360464761
[I 2024-04-18 15:33:08,914] Trial 67 finished with value: 0.21524222275497046 and parameters: {'l1_ratio': 0.27902400006466904}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21339495702740663
Fold 2 IBS: 0.2214766500440964
Fold 3 IBS: 0.20446590626829597
Fold 4 IBS: 0.22478337236441118
Fold 5 IBS: 0.2157995643456918
[I 2024-04-18 15:33:09,189] Trial 68 finished with value: 0.21598409000998037 and parameters: {'l1_ratio': 0.20336664670394694}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21289038478238215
Fold 2 IBS: 0.23508764561713746
Fold 3 IBS: 0.20442090866370002
Fold 4 IBS: 0.22462308591753977
Fold 5 IBS: 0.2125093295513938
[I 2024-04-18 15:33:10,158] Trial 69 finished with value: 0.21790627090643064 and parameters: {'l1_ratio': 0.3414660479354518}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21320028178344352
Fold 2 IBS: 0.22144442616759166
Fold 3 IBS: 0.20444664476902596
Fold 4 IBS: 0.2247381188153561
Fold 5 IBS: 0.21249056930674118
[I 2024-04-18 15:33:10,518] Trial 70 finished with value: 0.2152640081684317 and parameters: {'l1_ratio': 0.26009572691590727}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21298469826474206
Fold 2 IBS: 0.22140995966589422
Fold 3 IBS: 0.2044280666180938
Fold 4 IBS: 0.2246630656603397
Fold 5 IBS: 0.21248653371305837
[I 2024-04-18 15:33:10,930] Trial 71 finished with value: 0.21519446478442558 and parameters: {'l1_ratio': 0.31775518239347156}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20736156573327502
Fold 2 IBS: 0.2350741638434753
Fold 3 IBS: 0.20991994560820754
Fold 4 IBS: 0.23213764494010844
Fold 5 IBS: 0.2125386973491785
[I 2024-04-18 15:33:11,819] Trial 72 finished with value: 0.21940640349484894 and parameters: {'l1_ratio': 0.5067312497107318}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2129488598076428
Fold 2 IBS: 0.23511261734341796
Fold 3 IBS: 0.2044252748142025
Fold 4 IBS: 0.22464835320019544
Fold 5 IBS: 0.2124937864933465
[I 2024-04-18 15:33:12,675] Trial 73 finished with value: 0.21792577833176105 and parameters: {'l1_ratio': 0.326867485095082}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.2127014937362562
Fold 2 IBS: 0.23507047422205044
Fold 3 IBS: 0.20990701271518583
Fold 4 IBS: 0.2245314543988913
Fold 5 IBS: 0.21250475914733807
[I 2024-04-18 15:33:13,400] Trial 74 finished with value: 0.2189430388439444 and parameters: {'l1_ratio': 0.3864823724877222}. Best is trial 25 with value: 0.2151906949480932.

Fold 1 IBS: 0.2131278693285293
Fold 2 IBS: 0.2214326975645994
Fold 3 IBS: 0.20444007108719633
Fold 4 IBS: 0.22471560781040995
Fold 5 IBS: 0.21249028183936308
[I 2024-04-18 15:33:13,871] Trial 75 finished with value: 0.2152413055260196 and parameters: {'l1_ratio': 0.2800301963124028}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.20735756133271416
Fold 2 IBS: 0.23509485784935716
Fold 3 IBS: 0.20991985774805327
Fold 4 IBS: 0.22443478232470485
Fold 5 IBS: 0.2125159575849069
[I 2024-04-18 15:33:14,259] Trial 76 finished with value: 0.21786460336794727 and parameters: {'l1_ratio': 0.42527513008536816}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.21285400530869233
Fold 2 IBS: 0.23510964867810263
Fold 3 IBS: 0.20441831269174682
Fold 4 IBS: 0.22460660109674224
Fold 5 IBS: 0.2124935927329752
[I 2024-04-18 15:33:14,791] Trial 77 finished with value: 0.21789643210165183 and parameters: {'l1_ratio': 0.3503847770046378}. Best is trial 25 with value: 0.2151906949480932.
Fold 1 IBS: 0.212967142265704
Fold 2 IBS: 0.221407215045146
Fold 3 IBS: 0.2044266881220955
Fold 4 IBS: 0.2246559333911916
Fold 5 IBS: 0.21249168549321024
[I 2024-04-18 15:33:15,255] Trial 78 finished with value: 0.21518973286346946 and parameters: {'l1_ratio': 0.3222349295857673}. Best is trial 78 with value: 0.21518973286346946.
Fold 1 IBS: 0.21351683858561252
Fold 2 IBS: 0.2214972954418593
Fold 3 IBS: 0.20447909012221513
Fold 4 IBS: 0.22479887109024432
Fold 5 IBS: 0.2162594797935451
[I 2024-04-18 15:33:15,895] Trial 79 finished with value: 0.21611031500669525 and parameters: {'l1_ratio': 0.16529043080131142}. Best is trial 78 with value: 0.21518973286346946.
Fold 1 IBS: 0.2073550984649226
Fold 2 IBS: 0.23510674776346824
Fold 3 IBS: 0.2098976157000035
Fold 4 IBS: 0.2244939671447687
Fold 5 IBS: 0.21251939332661204
[I 2024-04-18 15:33:16,871] Trial 80 finished with value: 0.21787456447995504 and parameters: {'l1_ratio': 0.4023531897471312}. Best is trial 78 with value: 0.21518973286346946.
Fold 1 IBS: 0.21296504321193369
Fold 2 IBS: 0.2214068875505251
Fold 3 IBS: 0.20442652470125314
Fold 4 IBS: 0.22465507097346432
Fold 5 IBS: 0.2124922897390523
[I 2024-04-18 15:33:17,399] Trial 81 finished with value: 0.2151891632352457 and parameters: {'l1_ratio': 0.32276848518211226}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21283376889922703
Fold 2 IBS: 0.23512130450257154
Fold 3 IBS: 0.2044169092513161
Fold 4 IBS: 0.22459718401749912
Fold 5 IBS: 0.2124987333149936
[I 2024-04-18 15:33:17,939] Trial 82 finished with value: 0.2178935799971215 and parameters: {'l1_ratio': 0.3552929909845347}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.2132386943398223
Fold 2 IBS: 0.22145070653383758
Fold 3 IBS: 0.20445026447968398
Fold 4 IBS: 0.2247488698115628
Fold 5 IBS: 0.21523109783611832
[I 2024-04-18 15:33:18,441] Trial 83 finished with value: 0.21582392660020502 and parameters: {'l1_ratio': 0.2492739175288984}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21310494816696599
Fold 2 IBS: 0.22142901610943394
Fold 3 IBS: 0.2044380594833046
Fold 4 IBS: 0.2247078944960026
Fold 5 IBS: 0.21249788781897241
[I 2024-04-18 15:33:18,936] Trial 84 finished with value: 0.21523556121493592 and parameters: {'l1_ratio': 0.28621725516751106}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21273951637554414
Fold 2 IBS: 0.23511258717393962
Fold 3 IBS: 0.20989788856756797
Fold 4 IBS: 0.22455107194045187
Fold 5 IBS: 0.21249611481112138
[I 2024-04-18 15:33:19,793] Trial 85 finished with value: 0.218959435773725 and parameters: {'l1_ratio': 0.3776715898417537}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21332107205767045
Fold 2 IBS: 0.22146430642030446
Fold 3 IBS: 0.2044583296943712
Fold 4 IBS: 0.22476897682163874
Fold 5 IBS: 0.21552781955168104
[I 2024-04-18 15:33:20,144] Trial 86 finished with value: 0.21590810090913318 and parameters: {'l1_ratio': 0.22546084218977774}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.20736188484813334
Fold 2 IBS: 0.23507452239205612
Fold 3 IBS: 0.20991388755065443
Fold 4 IBS: 0.22437841806193948
Fold 5 IBS: 0.21250924168378033
[I 2024-04-18 15:33:20,795] Trial 87 finished with value: 0.21784759090731276 and parameters: {'l1_ratio': 0.4451566901558241}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21292169105910663
Fold 2 IBS: 0.2351294738895243
Fold 3 IBS: 0.20442321680748465
Fold 4 IBS: 0.22463680512511888
Fold 5 IBS: 0.21250121774579891
[I 2024-04-18 15:33:21,634] Trial 88 finished with value: 0.2179224809254067 and parameters: {'l1_ratio': 0.3336912312013093}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21345717574238784
Fold 2 IBS: 0.22148714647451292
Fold 3 IBS: 0.20447253148821287
Fold 4 IBS: 0.22479262812230405
Fold 5 IBS: 0.216032531008796
[I 2024-04-18 15:33:22,171] Trial 89 finished with value: 0.21604840256724275 and parameters: {'l1_ratio': 0.1841914531935409}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21385621501227214
Fold 2 IBS: 0.22155643688574692
Fold 3 IBS: 0.2045200317180177
Fold 4 IBS: 0.22477583923389893
Fold 5 IBS: 0.2176164925368391
[I 2024-04-18 15:33:22,515] Trial 90 finished with value: 0.21646500307735494 and parameters: {'l1_ratio': 0.04699206978897974}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21298626311697036
Fold 2 IBS: 0.22141020478467063
Fold 3 IBS: 0.20442819050033154
Fold 4 IBS: 0.22466369435111302
Fold 5 IBS: 0.21248606583177934
[I 2024-04-18 15:33:22,884] Trial 91 finished with value: 0.21519488371697298 and parameters: {'l1_ratio': 0.3173543807994709}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.2130199513949608
Fold 2 IBS: 0.22141550043440444
Fold 3 IBS: 0.2044308972641227
Fold 4 IBS: 0.2246769455103061
Fold 5 IBS: 0.2124988265724112
[I 2024-04-18 15:33:23,302] Trial 92 finished with value: 0.21520842423524106 and parameters: {'l1_ratio': 0.30866563188674273}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.213100140972247
Fold 2 IBS: 0.22142824594700883
Fold 3 IBS: 0.20443764187023397
Fold 4 IBS: 0.22470624195525268
Fold 5 IBS: 0.2124994335095374
[I 2024-04-18 15:33:23,723] Trial 93 finished with value: 0.215234340850856 and parameters: {'l1_ratio': 0.28750752791108475}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.21322027706597504
Fold 2 IBS: 0.22144769037934386
Fold 3 IBS: 0.20444851763736513
Fold 4 IBS: 0.22474382094957557
Fold 5 IBS: 0.21248596528006947
[I 2024-04-18 15:33:24,309] Trial 94 finished with value: 0.21526925426246582 and parameters: {'l1_ratio': 0.2544843960996289}. Best is trial 81 with value: 0.2151891632352457.
Fold 1 IBS: 0.2129625383954793
Fold 2 IBS: 0.22140649693459186
Fold 3 IBS: 0.20442633008149894
Fold 4 IBS: 0.22465403915893403
Fold 5 IBS: 0.21249300758525755
[I 2024-04-18 15:33:24,641] Trial 95 finished with value: 0.21518848243115235 and parameters: {'l1_ratio': 0.3234046087455167}. Best is trial 95 with value: 0.21518848243115235.
Fold 1 IBS: 0.21277973978110104
Fold 2 IBS: 0.23509055004867177
Fold 3 IBS: 0.20441330654662584
Fold 4 IBS: 0.22457119688456026
Fold 5 IBS: 0.21251162588261846
[I 2024-04-18 15:33:25,138] Trial 96 finished with value: 0.21787328382871549 and parameters: {'l1_ratio': 0.36821666949442033}. Best is trial 95 with value: 0.21518848243115235.
Fold 1 IBS: 0.2131600437964878
Fold 2 IBS: 0.2214378906677198
Fold 3 IBS: 0.20444295120410305
Fold 4 IBS: 0.2247259636885929
Fold 5 IBS: 0.2124819782805602
[I 2024-04-18 15:33:25,509] Trial 97 finished with value: 0.21524976552749275 and parameters: {'l1_ratio': 0.2712466447137454}. Best is trial 95 with value: 0.21518848243115235.
Fold 1 IBS: 0.20735347477869914
Fold 2 IBS: 0.2351024756867118
Fold 3 IBS: 0.20996574226083398
Fold 4 IBS: 0.2320481664182877
Fold 5 IBS: 0.2125818421099137
[I 2024-04-18 15:33:26,107] Trial 98 finished with value: 0.2194103402508893 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 95 with value: 0.21518848243115235.
Fold 1 IBS: 0.2073528027772181
Fold 2 IBS: 0.23511711690418416
Fold 3 IBS: 0.20990244299375702
Fold 4 IBS: 0.2244821520492179
Fold 5 IBS: 0.21249946026965216
[I 2024-04-18 15:33:26,644] Trial 99 finished with value: 0.21787079499880585 and parameters: {'l1_ratio': 0.40712195890179537}. Best is trial 95 with value: 0.21518848243115235.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.21518848243115235], datetime_start=datetime.datetime(2024, 4, 18, 15, 33, 24, 311623), datetime_complete=datetime.datetime(2024, 4, 18, 15, 33, 24, 641550), params={'l1_ratio': 0.3234046087455167}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=95, value=None)


* Best Score for IBS:
 0.21518848243115235

In [48]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.599
train_ibs:  0.215

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.28621072101688444)

test_cindex : 0.561

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.3234046087455167)

test_ibs:  0.22

In [52]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 15:33:27,205] A new study created in memory with name: no-name-db541889-6ee2-4218-b850-2d3bd5630e7f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.47619047619047616
Fold 2 C-index: 0.45089285714285715
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.5864978902953587
Fold 5 C-index: 0.5516431924882629
[I 2024-04-18 15:33:34,168] Trial 0 finished with value: 0.555201745968489 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.555201745968489.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.46875
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.5868544600938967
[I 2024-04-18 15:33:39,032] Trial 1 finished with value: 0.5770737403617989 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.5770737403617989.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.4642857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.568075117370892
[I 2024-04-18 15:33:42,932] Trial 2 finished with value: 0.5805659925844923 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:33:44,310] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:33:47,293] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5367965367965368
Fold 2 C-index: 0.4375
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.5352112676056338
[I 2024-04-18 15:33:56,987] Trial 5 finished with value: 0.5622267035957481 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5151515151515151
Fold 2 C-index: 0.48214285714285715
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.568075117370892
[I 2024-04-18 15:34:16,400] Trial 6 finished with value: 0.5764891374465797 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:34:22,987] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5140845070422535
[I 2024-04-18 15:34:34,187] Trial 8 finished with value: 0.5028169014084507 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5238095238095238
Fold 2 C-index: 0.4419642857142857
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.5991561181434599
Fold 5 C-index: 0.5211267605633803
[I 2024-04-18 15:34:40,224] Trial 9 finished with value: 0.5534858474500515 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:34:40,672] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.5805659925844923.
Fold 1 C-index: 0.49783549783549785
Fold 2 C-index: 0.4955357142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.5915492957746479
[I 2024-04-18 15:34:44,216] Trial 11 finished with value: 0.5911960648454911 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 11 with value: 0.5911960648454911.
Fold 1 C-index: 0.5021645021645021
Fold 2 C-index: 0.46875
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.5774647887323944
[I 2024-04-18 15:34:47,358] Trial 12 finished with value: 0.5774346072486274 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8619834498485652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1611753146667314, 'warm_start': False}. Best is trial 11 with value: 0.5911960648454911.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:34:49,295] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1567471583060459, 'warm_start': False}. Best is trial 11 with value: 0.5911960648454911.
Fold 1 C-index: 0.5367965367965368
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.784037558685446
[I 2024-04-18 15:34:51,463] Trial 14 finished with value: 0.7134844892024137 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1306449501762567, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6139240506329114
Fold 5 C-index: 0.7018779342723005
[I 2024-04-18 15:34:52,630] Trial 15 finished with value: 0.6467109763036805 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.792913180904143, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09179883523732954, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.

Fold 1 C-index: 0.5865800865800865
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 15:34:52,987] Trial 16 finished with value: 0.6670576680768744 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.44827686549014745, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07731335546121543, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.551948051948052
Fold 2 C-index: 0.5959821428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7206572769953051
[I 2024-04-18 15:34:53,279] Trial 17 finished with value: 0.6581677301506187 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.40393394585149023, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07870453397143869, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:34:53,950] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.5031824061226939, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:34:55,237] Trial 19 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.31478192981222664, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2171861810731355, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.4935064935064935
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 15:34:57,365] Trial 20 finished with value: 0.7045412247055746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.6597464700466056, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10277527190610086, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.48917748917748916
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 15:34:59,477] Trial 21 finished with value: 0.6910506119253486 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.5629768093939237, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11317106636518007, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.4935064935064935
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 15:35:01,578] Trial 22 finished with value: 0.6991588029723956 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 203, 'oob_score': True, 'max_samples': 0.6844274762348865, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11169200097206694, 'warm_start': True}. Best is trial 14 with value: 0.7134844892024137.
Fold 1 C-index: 0.5108225108225108
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 15:35:03,989] Trial 23 finished with value: 0.7766467861638569 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.6805307839679446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5194805194805194
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 15:35:06,221] Trial 24 finished with value: 0.7633243287428263 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.839996573192809, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003269976302471944, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5194805194805194
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 15:35:08,596] Trial 25 finished with value: 0.7651071777355166 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.8481248605153263, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0009444354266301414, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8215962441314554
[I 2024-04-18 15:35:12,518] Trial 26 finished with value: 0.7559843440933968 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.9945915825555692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030529967348810284, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5151515151515151
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 15:35:15,252] Trial 27 finished with value: 0.71163920077018 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.7548696080051858, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019704169303428522, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5238095238095238
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.8075117370892019
[I 2024-04-18 15:35:18,318] Trial 28 finished with value: 0.7495459509351967 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 319, 'oob_score': True, 'max_samples': 0.7181093328236055, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003147635846425299, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5151515151515151
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8356807511737089
[I 2024-04-18 15:35:23,136] Trial 29 finished with value: 0.7734941134430401 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.8825050060566446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046866493685696446, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5194805194805194
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8262910798122066
[I 2024-04-18 15:35:27,808] Trial 30 finished with value: 0.7681156448948887 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 398, 'oob_score': True, 'max_samples': 0.8835387074810691, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05475390266239465, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.

Fold 1 C-index: 0.5194805194805194
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 15:35:33,262] Trial 31 finished with value: 0.770845011289334 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.8886265639012588, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05599975638328304, 'warm_start': True}. Best is trial 23 with value: 0.7766467861638569.
Fold 1 C-index: 0.5194805194805194
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 15:35:38,005] Trial 32 finished with value: 0.7769423548443349 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.8955348974688377, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055995520118963374, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.5238095238095238
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8356807511737089
[I 2024-04-18 15:35:44,065] Trial 33 finished with value: 0.76917161631991 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.9090261362569586, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06358652697591127, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.4329004329004329
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6983122362869199
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 15:35:49,930] Trial 34 finished with value: 0.6683592044493774 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.7629443870887174, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2091384081066805, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.48917748917748916
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 15:35:56,870] Trial 35 finished with value: 0.7752071177260997 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 449, 'oob_score': True, 'max_samples': 0.9839750203962229, 'max_features': None, 'min_weight_fraction_leaf': 0.044555426841645374, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.5108225108225108
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 15:36:03,646] Trial 36 finished with value: 0.6910821542672403 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 450, 'oob_score': True, 'max_samples': 0.9867562626816119, 'max_features': None, 'min_weight_fraction_leaf': 0.19268809890576422, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.4588744588744589
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 15:36:09,619] Trial 37 finished with value: 0.6502862384601161 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.9295667792428641, 'max_features': None, 'min_weight_fraction_leaf': 0.04774951654359915, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.5151515151515151
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 15:36:16,831] Trial 38 finished with value: 0.694199725871645 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.7232503826207304, 'max_features': None, 'min_weight_fraction_leaf': 0.1360848245875645, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.44805194805194803
Fold 2 C-index: 0.5602678571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.609704641350211
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 15:36:22,746] Trial 39 finished with value: 0.6187857785661145 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 419, 'oob_score': True, 'max_samples': 0.9444401923445911, 'max_features': None, 'min_weight_fraction_leaf': 0.383245486948687, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.5324675324675324
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 15:36:27,985] Trial 40 finished with value: 0.7096577263622349 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.7973674228510764, 'max_features': None, 'min_weight_fraction_leaf': 0.03804112883841601, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 15:36:34,963] Trial 41 finished with value: 0.7619555929067034 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.8929059834987324, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07548332751526049, 'warm_start': True}. Best is trial 32 with value: 0.7769423548443349.
Fold 1 C-index: 0.5151515151515151
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 15:36:41,666] Trial 42 finished with value: 0.7903357065609432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.9869212135212092, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055124222189877, 'warm_start': True}. Best is trial 42 with value: 0.7903357065609432.
Fold 1 C-index: 0.4935064935064935
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 15:36:46,164] Trial 43 finished with value: 0.8272959367704683 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.9912347101163792, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032342078513471456, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.45454545454545453
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7025316455696202
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 15:36:50,514] Trial 44 finished with value: 0.6715298813004836 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.9750803468169998, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25591336155079925, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.4675324675324675
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9061032863849765
[I 2024-04-18 15:36:52,502] Trial 45 finished with value: 0.8123344088765994 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.9999068199721711, 'max_features': None, 'min_weight_fraction_leaf': 0.02515154095758285, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.

Fold 1 C-index: 0.5064935064935064
Fold 2 C-index: 0.41517857142857145
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.48826291079812206
[I 2024-04-18 15:37:00,364] Trial 46 finished with value: 0.5455263375305874 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.9454898371578867, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020572581930849695, 'warm_start': False}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5281385281385281
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 15:37:02,015] Trial 47 finished with value: 0.7619555929067034 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.9336237748566397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08764043636214691, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:37:07,071] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.6164178606890751, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.491438551581221, 'warm_start': False}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5238095238095238
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 15:37:09,015] Trial 49 finished with value: 0.7013778251539516 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.807475837275153, 'max_features': None, 'min_weight_fraction_leaf': 0.13432055707088622, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5108225108225108
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 15:37:11,836] Trial 50 finished with value: 0.7052516025778535 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.9946558786616233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1860144738469976, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.48484848484848486
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8732394366197183
[I 2024-04-18 15:37:15,215] Trial 51 finished with value: 0.7832612924097985 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.9642647473321502, 'max_features': None, 'min_weight_fraction_leaf': 0.023771200543370258, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.4935064935064935
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 15:37:20,546] Trial 52 finished with value: 0.7813321108764095 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.9210402968590522, 'max_features': None, 'min_weight_fraction_leaf': 0.028067687688059527, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5021645021645021
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8075117370892019
[I 2024-04-18 15:37:24,524] Trial 53 finished with value: 0.7536413606756176 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9179428768983321, 'max_features': None, 'min_weight_fraction_leaf': 0.06567784281034368, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5064935064935064
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.8262910798122066
[I 2024-04-18 15:37:27,390] Trial 54 finished with value: 0.7394671573065278 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.9591460266612453, 'max_features': None, 'min_weight_fraction_leaf': 0.02588019976858258, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5151515151515151
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 15:37:29,514] Trial 55 finished with value: 0.735741845928796 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.8650031094377825, 'max_features': None, 'min_weight_fraction_leaf': 0.09266077234325004, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.4588744588744589
Fold 2 C-index: 0.45089285714285715
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.580168776371308
Fold 5 C-index: 0.5633802816901409
[I 2024-04-18 15:37:37,614] Trial 56 finished with value: 0.5552711179530079 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.9644226807012062, 'max_features': None, 'min_weight_fraction_leaf': 0.29669443075161894, 'warm_start': False}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.47186147186147187
Fold 2 C-index: 0.6160714285714286
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 15:37:39,741] Trial 57 finished with value: 0.6724652065237836 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.9994018516139036, 'max_features': None, 'min_weight_fraction_leaf': 0.0281482194368256, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5021645021645021
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7934272300469484
[I 2024-04-18 15:37:42,441] Trial 58 finished with value: 0.7418677436695356 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8296809048320443, 'max_features': None, 'min_weight_fraction_leaf': 0.07134930827982264, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5108225108225108
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.8028169014084507
[I 2024-04-18 15:37:44,524] Trial 59 finished with value: 0.7319687433475149 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.9081121349439835, 'max_features': None, 'min_weight_fraction_leaf': 0.10346073076942694, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 15:37:51,551] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.13319246988341354, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12562175210772666, 'warm_start': False}. Best is trial 43 with value: 0.8272959367704683.

Fold 1 C-index: 0.5151515151515151
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.9107981220657277
[I 2024-04-18 15:37:54,644] Trial 61 finished with value: 0.8238755282660561 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.9295715498276746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.015236949392132727, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.47186147186147187
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 15:37:57,675] Trial 62 finished with value: 0.8201132909848813 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.9577529190495756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014576231232554693, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
Fold 1 C-index: 0.47619047619047616
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 15:38:00,626] Trial 63 finished with value: 0.8185349812950674 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9547364219755952, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010285664740814352, 'warm_start': True}. Best is trial 43 with value: 0.8272959367704683.
[W 2024-04-18 15:38:02,325] Trial 64 failed with parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.9542503271400232, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.015578230768928732, 'warm_start': True} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_16285/3295956579.py", line 56, in objective
    model.fit(X_train, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/ensemble/forest.py", line 148, in fit
    trees = Parallel(n_jobs=self.n_jobs, verbose=self.verbose, prefer="threads")(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 1088, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/tree/tree.py", line 209, in fit
    random_state = check_random_state(self.random_state)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1226, in check_random_state
    return np.random.RandomState(seed)
  File "mtrand.pyx", line 184, in numpy.random.mtrand.RandomState.__init__
  File "_mt19937.pyx", line 130, in numpy.random._mt19937.MT19937.__init__
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
KeyboardInterrupt
[W 2024-04-18 15:38:02,365] Trial 64 failed with value None.

KeyboardInterrupt:

In [ ]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [ ]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [ ]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [ ]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

In [ ]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [ ]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

#### Test

In [ ]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [ ]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO,y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

In [ ]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [ ]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

In [ ]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

In [ ]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

In [ ]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

In [ ]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/minmax/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_minmax_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [ ]:
from datetime import date

current_date = date.today()
print(current_date)