In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from lifelines import CoxPHFitter
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
response_OUS.isna().sum().sum()

0

In [4]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [5]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [6]:
# Check null values in D3
clinical_train.isnull().sum().sum()

0

In [7]:
clinical_train

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,event_DFS
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,...,0.029974,0.815962,0.000000,0.002035,0.140311,0.000062,0.009991,0.000370,32.909589,0
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,...,0.059728,0.707300,0.000000,0.008732,0.191058,0.000349,0.023402,0.000699,27.715068,0
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,...,0.039463,0.819828,0.000034,0.002518,0.126531,0.000000,0.009452,0.000414,43.101370,1
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,...,0.061133,0.716212,0.000000,0.003296,0.192388,0.000000,0.018879,0.000899,17.589041,1
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,...,0.058589,0.696493,0.000199,0.008968,0.202073,0.000399,0.029892,0.001395,47.473973,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,...,0.029444,0.804831,0.000000,0.001442,0.152626,0.000000,0.009734,0.000361,41.490411,0
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,...,0.046451,0.792151,0.000000,0.004094,0.142778,0.000079,0.011810,0.000630,36.821918,0
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,...,0.016316,0.832202,0.000000,0.000914,0.140582,0.000000,0.009137,0.000522,40.043836,0
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,...,0.038862,0.787588,0.000000,0.003144,0.156640,0.000054,0.011978,0.000705,40.964384,0
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,...,0.011577,0.830670,0.000000,0.000978,0.147644,0.000000,0.008642,0.000408,30.608219,0

## Test dataset: MAASTRO

In [8]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [9]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [10]:
rows_with_nan = response_MAASTRO[response_MAASTRO.isna().any(axis=1)]

print("Rows with NaN values:")
print(rows_with_nan)

Rows with NaN values:
    patient_id  OS  OS_event  LRC  LRC_event  DFS  DFS_event
10          11 NaN       NaN  NaN        NaN  NaN        NaN
20          21 NaN       NaN  NaN        NaN  NaN        NaN
31          32 NaN       NaN  NaN        NaN  NaN        NaN
51          52 NaN       NaN  NaN        NaN  NaN        NaN
83          84 NaN       NaN  NaN        NaN  NaN        NaN
86          87 NaN       NaN  NaN        NaN  NaN        NaN

In [11]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

In [12]:
MAASTRO_D3

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,1,55,0,0,1,0,0,1,1,1,...,0.000026,0.001181,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341
1,2,55,0,0,1,0,0,0,0,0,...,0.000056,0.002735,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335
2,3,55,0,0,1,0,0,0,0,1,...,0.000286,0.001888,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229
3,4,61,1,0,0,0,1,1,0,1,...,0.000160,0.003037,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240
4,6,70,0,0,1,0,0,1,1,1,...,0.000071,0.000881,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.000000,0.000544,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078
95,111,63,0,0,0,0,1,0,0,1,...,0.000109,0.000869,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489
96,112,63,0,0,1,0,0,1,1,1,...,0.000000,0.000734,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141
97,113,54,0,0,1,0,0,1,1,0,...,0.000114,0.001640,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038
98,114,62,0,0,0,1,0,1,0,0,...,0.000000,0.000225,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337

In [13]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(MAASTRO_D3['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: [5, 9, 11, 21, 32, 36, 46, 52, 65, 76, 78, 81, 84, 87, 92]

In [14]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: []

In [15]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [16]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [17]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [18]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [19]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [20]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 388)
y_train:  (139,)

(99, 390)

# Feature Selection: RENT

In [21]:
selected_features = ["shape_Sphericity",
"hpv_related",
"glszm_SmallAreaLowGrayLevelEmphasis_CT_c16",
"LBP_102_PET",
"shape_Flatness",
"shape_Elongation",
"uicc8_III-IV",
"shape_MajorAxisLength",
"glrlm_HighGrayLevelRunEmphasis_PET_c04"]


# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [22]:
original_X = X.copy()

In [23]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [24]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [25]:
X_new

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.761164,0.0,0.029425,0.000000,0.535140,0.600926,0.0,42.073251,16.969770
1,0.697049,0.0,0.037915,0.000000,0.367109,0.841579,0.0,24.613845,15.598394
2,0.565792,0.0,0.008009,0.000034,0.597785,0.772821,1.0,48.030294,17.334294
3,0.684364,0.0,0.018398,0.000000,0.405730,0.847727,0.0,25.589900,14.009277
4,0.503142,0.0,0.013051,0.000199,0.442406,0.831483,0.0,34.684750,21.202180
...,...,...,...,...,...,...,...,...,...
134,0.742102,1.0,0.014938,0.000000,0.523608,0.680294,0.0,33.069705,16.110383
135,0.722918,1.0,0.011441,0.000000,0.735524,0.758193,1.0,41.043692,21.249575
136,0.652963,1.0,0.020431,0.000000,0.648063,0.770113,0.0,36.618802,14.873884
137,0.724255,1.0,0.019663,0.000000,0.492193,0.628897,1.0,45.870392,21.648860
138,0.722633,1.0,0.013864,0.000000,0.756267,0.892637,1.0,30.363259,20.191288

In [26]:
X_new_std

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.704475,0.0,1.172200,0.000000,0.064971,-0.485459,0.0,0.059912,0.085656
1,0.101791,0.0,1.947696,0.000000,-0.952446,0.666232,0.0,-0.755402,-0.291967
2,-1.132016,0.0,-0.783916,0.524263,0.444285,0.337179,1.0,0.338093,0.186031
3,-0.017443,0.0,0.165035,0.000000,-0.718597,0.695653,0.0,-0.709822,-0.729547
4,-1.720923,0.0,-0.323382,3.028668,-0.496529,0.617917,0.0,-0.285114,1.251094
...,...,...,...,...,...,...,...,...,...
134,0.525285,1.0,-0.151010,0.000000,-0.004852,-0.105628,0.0,-0.360532,-0.150985
135,0.344965,1.0,-0.470412,0.000000,1.278289,0.267171,1.0,0.011834,1.264145
136,-0.312609,1.0,0.350720,0.000000,0.748713,0.324219,0.0,-0.194798,-0.491468
137,0.357529,1.0,0.280586,0.000000,-0.195069,-0.351598,1.0,0.237230,1.374092
138,0.342282,1.0,-0.249118,0.000000,1.403881,0.910577,1.0,-0.486917,0.972735

In [27]:
MAASTRO_new

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.668072,1,0.010495,0.000026,0.610062,0.765178,0,50.002093,19.034156
1,0.669961,0,0.035018,0.000167,0.504616,0.776540,1,41.753334,11.392444
2,0.624081,0,0.012819,0.000057,0.478604,0.697164,1,44.375483,14.567421
3,0.577624,0,0.029974,0.000000,0.446059,0.574636,1,46.115989,13.477331
4,0.630933,1,0.013458,0.000000,0.480378,0.633419,0,54.394967,16.365554
...,...,...,...,...,...,...,...,...,...
94,0.671754,0,0.039092,0.000000,0.577884,0.882411,1,34.218615,17.492295
95,0.632189,0,0.015831,0.000000,0.455642,0.535802,1,51.046869,14.267900
96,0.645548,1,0.011031,0.000000,0.631485,0.716610,1,50.417953,12.143752
97,0.727488,1,0.019801,0.000000,0.628338,0.665145,0,44.901412,15.300229
98,0.672838,0,0.015813,0.000000,0.469139,0.616262,1,36.574294,13.850774

In [28]:
MAASTRO_new_std

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,-0.170593,1,-0.556880,0.398737,0.518623,0.300600,0,0.430171,0.654106
1,-0.152832,0,1.683040,2.544568,-0.119851,0.354974,1,0.044973,-1.450119
2,-0.584101,0,-0.344618,0.869691,-0.277351,-0.024893,1,0.167421,-0.575856
3,-1.020797,0,1.222314,0.000000,-0.474407,-0.611274,1,0.248699,-0.876024
4,-0.519690,1,-0.286171,0.000000,-0.266607,-0.329957,0,0.635308,-0.080721
...,...,...,...,...,...,...,...,...,...
94,-0.135979,0,2.055216,0.000000,0.323784,0.861639,1,-0.306881,0.229539
95,-0.507883,0,-0.069508,0.000000,-0.416383,-0.797117,1,0.478960,-0.658333
96,-0.382318,1,-0.507885,0.000000,0.648334,0.068172,1,0.449591,-1.243239
97,0.387916,1,0.293176,0.000000,0.629283,-0.178126,0,0.191981,-0.374070
98,-0.125793,0,-0.071098,0.000000,-0.334661,-0.412064,1,-0.196876,-0.773193

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [29]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:31:26,313] A new study created in memory with name: no-name-e1d9ef13-4d17-4956-8d33-b511ece8908b

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-19 14:31:30,342] A new study created in memory with name: no-name-3e48b656-3af5-4fe1-af9d-750625779caa

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.759656652360515
[I 2024-04-19 14:31:30,331] Trial 0 finished with value: 0.72444161978659 and parameters: {}. Best is trial 0 with value: 0.72444161978659.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.72444161978659], datetime_start=datetime.datetime(2024, 4, 19, 14, 31, 26, 386182), datetime_complete=datetime.datetime(2024, 4, 19, 14, 31, 30, 330646), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.72444161978659

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.22218111763385023
Fold 2 IBS: 0.18214519470787685
Fold 3 IBS: 0.19943058215780185
Fold 4 IBS: 0.2249881896341226
Fold 5 IBS: 0.1707910917826678
[I 2024-04-19 14:31:30,621] Trial 0 finished with value: 0.19990723518326386 and parameters: {}. Best is trial 0 with value: 0.19990723518326386.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19990723518326386], datetime_start=datetime.datetime(2024, 4, 19, 14, 31, 30, 393105), datetime_complete=datetime.datetime(2024, 4, 19, 14, 31, 30, 620947), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19990723518326386

In [30]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.724
train_ibs:  0.2

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.562
IBS score: 0.29

In [34]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [35]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:31:30,810] A new study created in memory with name: no-name-eb912af5-aac0-47b6-bdb8-c3a56f30c091

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7151162790697675
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.7072243346007605

[I 2024-04-19 14:31:30,972] A new study created in memory with name: no-name-89d7537d-8e2e-4c60-813e-cc4671de1911

Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 14:31:30,967] Trial 0 finished with value: 0.6509766589481208 and parameters: {}. Best is trial 0 with value: 0.6509766589481208.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6509766589481208], datetime_start=datetime.datetime(2024, 4, 19, 14, 31, 30, 846174), datetime_complete=datetime.datetime(2024, 4, 19, 14, 31, 30, 966942), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6509766589481208

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709781339987
Fold 2 IBS: 0.2320398746717657
Fold 3 IBS: 0.2289818676351831
Fold 4 IBS: 0.2419747644101402
Fold 5 IBS: 0.22939558596182483
[I 2024-04-19 14:31:31,156] Trial 0 finished with value: 0.23592783809846277 and parameters: {}. Best is trial 0 with value: 0.23592783809846277.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783809846277], datetime_start=datetime.datetime(2024, 4, 19, 14, 31, 31, 4197), datetime_complete=datetime.datetime(2024, 4, 19, 14, 31, 31, 156102), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783809846277

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.651
train_ibs:  0.236

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.535

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:31:31,338] A new study created in memory with name: no-name-842b286e-fd38-4e53-86ef-9c1e1159a29f

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6254980079681275

[I 2024-04-19 14:31:31,659] A new study created in memory with name: no-name-050974c2-c318-4528-a251-44ba711d5f78

Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:31,655] Trial 0 finished with value: 0.7245031761362986 and parameters: {}. Best is trial 0 with value: 0.7245031761362986.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7245031761362986], datetime_start=datetime.datetime(2024, 4, 19, 14, 31, 31, 386966), datetime_complete=datetime.datetime(2024, 4, 19, 14, 31, 31, 655021), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7245031761362986

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.22253167582735317
Fold 2 IBS: 0.1820013069462648
Fold 3 IBS: 0.19910377379051175
Fold 4 IBS: 0.22395364989497227
Fold 5 IBS: 0.1685762806839025
[I 2024-04-19 14:31:32,004] Trial 0 finished with value: 0.1992333374286009 and parameters: {}. Best is trial 0 with value: 0.1992333374286009.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1992333374286009], datetime_start=datetime.datetime(2024, 4, 19, 14, 31, 31, 692517), datetime_complete=datetime.datetime(2024, 4, 19, 14, 31, 32, 4010), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1992333374286009

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.725
train_ibs:  0.199

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.561

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.288

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:31:32,218] A new study created in memory with name: no-name-64d6b652-56a0-4b40-b01e-c58318386128

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:32,499] Trial 0 finished with value: 0.725361545235011 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.725361545235011.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:32,822] Trial 1 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:33,073] Trial 2 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:33,303] Trial 3 finished with value: 0.7230359638396621 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:33,519] Trial 4 finished with value: 0.7245863514365614 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:33,748] Trial 5 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:33,981] Trial 6 finished with value: 0.7245031761362986 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:34,218] Trial 7 finished with value: 0.725361545235011 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:34,474] Trial 8 finished with value: 0.7238870276694493 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:34,917] Trial 9 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:35,235] Trial 10 finished with value: 0.6798250342684959 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:35,515] Trial 11 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.2694535558091148}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:35,813] Trial 12 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.21257181845809592}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-19 14:31:35,938] Trial 13 finished with value: 0.6528656014614025 and parameters: {'l1_ratio': 0.007125118463963187}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:36,196] Trial 14 finished with value: 0.7246944297550717 and parameters: {'l1_ratio': 0.2799002900234457}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:36,470] Trial 15 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.28852188637754794}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:36,834] Trial 16 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.14603446716586505}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:37,071] Trial 17 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.34921453367691924}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:37,301] Trial 18 finished with value: 0.7238111576381117 and parameters: {'l1_ratio': 0.5645122744065265}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.703862660944206
[I 2024-04-19 14:31:37,412] Trial 19 finished with value: 0.652804045111694 and parameters: {'l1_ratio': 0.013522847250075798}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:37,647] Trial 20 finished with value: 0.7245031761362986 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:37,923] Trial 21 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3212333814818189}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:38,188] Trial 22 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.15356416654588492}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:38,429] Trial 23 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.23007377748858485}. Best is trial 1 with value: 0.7255527988537841.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:38,658] Trial 24 finished with value: 0.7238870276694493 and parameters: {'l1_ratio': 0.4863655198534047}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:38,912] Trial 25 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.31701825327701266}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:39,105] Trial 26 finished with value: 0.6798250342684959 and parameters: {'l1_ratio': 0.09445651598854757}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:39,357] Trial 27 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3903221810064512}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:39,622] Trial 28 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.27224188955756884}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:39,868] Trial 29 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.17406270109951794}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:40,079] Trial 30 finished with value: 0.7238111576381117 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:40,334] Trial 31 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.3103144474009149}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:40,561] Trial 32 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3704627095418852}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:40,776] Trial 33 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.43350930496097856}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:41,002] Trial 34 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.26182543114011203}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:41,245] Trial 35 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.20921826056558182}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:41,472] Trial 36 finished with value: 0.7230359638396621 and parameters: {'l1_ratio': 0.5411641129675752}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:41,687] Trial 37 finished with value: 0.6798250342684959 and parameters: {'l1_ratio': 0.09026330918228417}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:41,909] Trial 38 finished with value: 0.725361545235011 and parameters: {'l1_ratio': 0.7883002392124641}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:42,137] Trial 39 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:42,373] Trial 40 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3219946834973448}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:42,606] Trial 41 finished with value: 0.7246944297550717 and parameters: {'l1_ratio': 0.27936373110641877}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:42,849] Trial 42 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.24413123835486522}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:43,098] Trial 43 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.1871854641056116}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:43,323] Trial 44 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.35376470832630813}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:43,560] Trial 45 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.4020612476081732}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:43,836] Trial 46 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.13446934148690134}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:44,100] Trial 47 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.3139964895493561}. Best is trial 1 with value: 0.7255527988537841.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:44,344] Trial 48 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.26268375459327914}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 14:31:44,475] Trial 49 finished with value: 0.659106528404234 and parameters: {'l1_ratio': 0.04475149791307237}. Best is trial 1 with value: 0.7255527988537841.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:44,752] Trial 50 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.21890747475310213}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:45,025] Trial 51 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.1988260309768138}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:45,314] Trial 52 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.20577853333291146}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:45,789] Trial 53 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.13864239196038106}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:46,111] Trial 54 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.34424329888520155}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:46,531] Trial 55 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.2322767948640527}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:46,807] Trial 56 finished with value: 0.6712831649608649 and parameters: {'l1_ratio': 0.05541429941650869}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:47,186] Trial 57 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3548377516002993}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:47,516] Trial 58 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.1751081059439046}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:47,869] Trial 59 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.45351270059179083}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:48,287] Trial 60 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.1156049552058715}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:48,632] Trial 61 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.11675960257776002}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:48,909] Trial 62 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.2929775217955545}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:49,196] Trial 63 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.16506199146911588}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:49,520] Trial 64 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.2237440999684088}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 14:31:49,695] Trial 65 finished with value: 0.6575492593814658 and parameters: {'l1_ratio': 0.049835279379473185}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:49,961] Trial 66 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.19455536466700524}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:50,220] Trial 67 finished with value: 0.7246944297550717 and parameters: {'l1_ratio': 0.24851850509425827}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:50,523] Trial 68 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.10971656887275383}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:50,844] Trial 69 finished with value: 0.7238870276694493 and parameters: {'l1_ratio': 0.5223885220566613}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:51,086] Trial 70 finished with value: 0.6805854905422603 and parameters: {'l1_ratio': 0.08259964501344405}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:51,345] Trial 71 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.29662527200427424}. Best is trial 50 with value: 0.7263496116027881.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:51,597] Trial 72 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.33486946044811833}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:51,843] Trial 73 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.39355047309386115}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:52,103] Trial 74 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.33668309939117175}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:52,356] Trial 75 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.32584124105566836}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:52,662] Trial 76 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.3754326451820461}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:52,980] Trial 77 finished with value: 0.7238111576381117 and parameters: {'l1_ratio': 0.5834831993138945}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:53,280] Trial 78 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.4114974853693986}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:53,646] Trial 79 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.34805724557461937}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:53,895] Trial 80 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.3740657101474589}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:54,146] Trial 81 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.36139612400335963}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:54,420] Trial 82 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.45673478834632036}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:54,745] Trial 83 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.42993157146127076}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:55,280] Trial 84 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.37461007387193324}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:55,561] Trial 85 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.33218847491866843}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:55,812] Trial 86 finished with value: 0.7254226777416634 and parameters: {'l1_ratio': 0.4939482094701635}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:56,130] Trial 87 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.338374925876444}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:56,425] Trial 88 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.38326048305395843}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:56,699] Trial 89 finished with value: 0.7247380914992366 and parameters: {'l1_ratio': 0.46760786033215884}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:56,965] Trial 90 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.4306604255408164}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:57,239] Trial 91 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3805613990192099}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:57,538] Trial 92 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.29773651933293843}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:57,804] Trial 93 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.41307952270178244}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:58,074] Trial 94 finished with value: 0.7263496116027881 and parameters: {'l1_ratio': 0.34484323942441436}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:58,349] Trial 95 finished with value: 0.7254985477730008 and parameters: {'l1_ratio': 0.3698288879455905}. Best is trial 50 with value: 0.7263496116027881.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:58,660] Trial 96 finished with value: 0.7255527988537841 and parameters: {'l1_ratio': 0.2614018115274258}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:59,168] Trial 97 finished with value: 0.7246944297550717 and parameters: {'l1_ratio': 0.27606272033911816}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:31:59,466] Trial 98 finished with value: 0.725361545235011 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 50 with value: 0.7263496116027881.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043

[I 2024-04-19 14:31:59,785] A new study created in memory with name: no-name-cf66970f-2204-4211-abf6-e05ad95bf2d1

Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:31:59,774] Trial 99 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.23318848268204723}. Best is trial 50 with value: 0.7263496116027881.


* Best trial for C-index:
 FrozenTrial(number=50, state=TrialState.COMPLETE, values=[0.7263496116027881], datetime_start=datetime.datetime(2024, 4, 19, 14, 31, 44, 478692), datetime_complete=datetime.datetime(2024, 4, 19, 14, 31, 44, 752102), params={'l1_ratio': 0.21890747475310213}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=50, value=None)


* Best Score for C-index:
 0.7263496116027881

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2225704262218376
Fold 2 IBS: 0.1819498270902588
Fold 3 IBS: 0.19886768747656922
Fold 4 IBS: 0.22386567170541638
Fold 5 IBS: 0.16840167511994572
[I 2024-04-19 14:32:00,256] Trial 0 finished with value: 0.19913105752280555 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.19913105752280555.
Fold 1 IBS: 0.22256851645545656
Fold 2 IBS: 0.18183149525695486
Fold 3 IBS: 0.19831127087456324
Fold 4 IBS: 0.22374002106557006
Fold 5 IBS: 0.16804963785268703
[I 2024-04-19 14:32:00,645] Trial 1 finished with value: 0.19890018830104633 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.19890018830104633.
Fold 1 IBS: 0.22256240629167903
Fold 2 IBS: 0.18180990729063937
Fold 3 IBS: 0.1980949387348138
Fold 4 IBS: 0.2237057863023476
Fold 5 IBS: 0.16798363636883748
[I 2024-04-19 14:32:00,978] Trial 2 finished with value: 0.19883133499766345 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.2225858084948348
Fold 2 IBS: 0.18190936294471594
Fold 3 IBS: 0.19868690461078364
Fold 4 IBS: 0.22386584107293184
Fold 5 IBS: 0.16829062521578061
[I 2024-04-19 14:32:01,584] Trial 3 finished with value: 0.19906770846780936 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.22256336609436816
Fold 2 IBS: 0.1819424488126053
Fold 3 IBS: 0.19885158376866574
Fold 4 IBS: 0.22389524311424086
Fold 5 IBS: 0.16841326617515573
[I 2024-04-19 14:32:02,024] Trial 4 finished with value: 0.19913318159300714 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.22257573080825171
Fold 2 IBS: 0.18188090806319354
Fold 3 IBS: 0.19853065444102216
Fold 4 IBS: 0.22382345305949772
Fold 5 IBS: 0.16818431663760727
[I 2024-04-19 14:32:02,748] Trial 5 finished with value: 0.19899901260191447 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.22253540062329444
Fold 2 IBS: 0.1819974471847107
Fold 3 IBS: 0.19908853414830863
Fold 4 IBS: 0.22393954749201553
Fold 5 IBS: 0.16856996748674416
[I 2024-04-19 14:32:03,493] Trial 6 finished with value: 0.19922617938701467 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.22257414616828544
Fold 2 IBS: 0.18194593496119107
Fold 3 IBS: 0.19885184114920312
Fold 4 IBS: 0.22385089518076848
Fold 5 IBS: 0.16839554835503937
[I 2024-04-19 14:32:03,987] Trial 7 finished with value: 0.1991236731628975 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.22258115719513752
Fold 2 IBS: 0.18189205054434746
Fold 3 IBS: 0.19860275996449386
Fold 4 IBS: 0.2238422787998055
Fold 5 IBS: 0.16823412568011092
[I 2024-04-19 14:32:04,572] Trial 8 finished with value: 0.19903047443677907 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.2225592193975444
Fold 2 IBS: 0.18185635763512048
Fold 3 IBS: 0.19843888633193105
Fold 4 IBS: 0.22374231338725753
Fold 5 IBS: 0.16815409006214538
[I 2024-04-19 14:32:05,061] Trial 9 finished with value: 0.19895017336279977 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.22255024788715083
Fold 2 IBS: 0.1817367268628445
Fold 3 IBS: 0.22875147163974346
Fold 4 IBS: 0.23700727959810097
Fold 5 IBS: 0.16785100487359222
[I 2024-04-19 14:32:05,488] Trial 10 finished with value: 0.2075793461722864 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.19883133499766345.
Fold 1 IBS: 0.2225748623152803
Fold 2 IBS: 0.1817812943912922
Fold 3 IBS: 0.19807275866786828
Fold 4 IBS: 0.2236117641250916
Fold 5 IBS: 0.16795020182813336
[I 2024-04-19 14:32:05,887] Trial 11 finished with value: 0.19879817626553314 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 11 with value: 0.19879817626553314.
Fold 1 IBS: 0.2225582759704399
Fold 2 IBS: 0.22774726066107645
Fold 3 IBS: 0.22881811255712187
Fold 4 IBS: 0.23889479523969104
Fold 5 IBS: 0.22632067666519162
[I 2024-04-19 14:32:06,150] Trial 12 finished with value: 0.2288678242187042 and parameters: {'l1_ratio': 0.04835900598617554}. Best is trial 11 with value: 0.19879817626553314.
Fold 1 IBS: 0.22258032508501402
Fold 2 IBS: 0.18178789318042674
Fold 3 IBS: 0.19810650258258788
Fold 4 IBS: 0.2237402181851155
Fold 5 IBS: 0.1679727110452127
[I 2024-04-19 14:32:06,594] Trial 13 finished with value: 0.19883753001567137 and parameters: {'l1_ratio': 0.2114475350243538}. Best is trial 11 with value: 0.19879817626553314.
Fold 1 IBS: 0.22257661008131882
Fold 2 IBS: 0.1818061930784974
Fold 3 IBS: 0.19819360004801928
Fold 4 IBS: 0.22366501948525605
Fold 5 IBS: 0.16801194828680643
[I 2024-04-19 14:32:07,056] Trial 14 finished with value: 0.19885067419597963 and parameters: {'l1_ratio': 0.24307964185836162}. Best is trial 11 with value: 0.19879817626553314.
Fold 1 IBS: 0.2225569945367208
Fold 2 IBS: 0.1817778106500557
Fold 3 IBS: 0.19805072386218522
Fold 4 IBS: 0.22363889036219053
Fold 5 IBS: 0.1679217148827643
[I 2024-04-19 14:32:07,431] Trial 15 finished with value: 0.1987892268587833 and parameters: {'l1_ratio': 0.15965289527445112}. Best is trial 15 with value: 0.1987892268587833.
Fold 1 IBS: 0.2471427844411003
Fold 2 IBS: 0.23165467508157409
Fold 3 IBS: 0.22896507881590783
Fold 4 IBS: 0.24169931390184737
Fold 5 IBS: 0.22911892050401936
[I 2024-04-19 14:32:07,635] Trial 16 finished with value: 0.23571615454888978 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 15 with value: 0.1987892268587833.
Fold 1 IBS: 0.2225770570938568
Fold 2 IBS: 0.18177290868629395
Fold 3 IBS: 0.19789486566849612
Fold 4 IBS: 0.22365104319469917
Fold 5 IBS: 0.1678954352514017
[I 2024-04-19 14:32:08,048] Trial 17 finished with value: 0.19875826197894955 and parameters: {'l1_ratio': 0.13260147423242452}. Best is trial 17 with value: 0.19875826197894955.
Fold 1 IBS: 0.2225692747708769
Fold 2 IBS: 0.18178233633282487
Fold 3 IBS: 0.1979413884401666
Fold 4 IBS: 0.22368835345036364
Fold 5 IBS: 0.16790750154921066
[I 2024-04-19 14:32:08,478] Trial 18 finished with value: 0.19877777090868853 and parameters: {'l1_ratio': 0.13659466528206826}. Best is trial 17 with value: 0.19875826197894955.
Fold 1 IBS: 0.22256218652339424
Fold 2 IBS: 0.1818556777413481
Fold 3 IBS: 0.19833097907010921
Fold 4 IBS: 0.22368621132489047
Fold 5 IBS: 0.1681043940049369
[I 2024-04-19 14:32:08,918] Trial 19 finished with value: 0.1989078897329358 and parameters: {'l1_ratio': 0.336433957019475}. Best is trial 17 with value: 0.19875826197894955.
Fold 1 IBS: 0.2225791481491399
Fold 2 IBS: 0.1817533255196509
Fold 3 IBS: 0.1979293561231659
Fold 4 IBS: 0.22359848426024714
Fold 5 IBS: 0.16788632577295612
[I 2024-04-19 14:32:09,443] Trial 20 finished with value: 0.198749327965032 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 20 with value: 0.198749327965032.
Fold 1 IBS: 0.22255120674950954
Fold 2 IBS: 0.18175196629358284
Fold 3 IBS: 0.22873091189631373
Fold 4 IBS: 0.2235929415220885
Fold 5 IBS: 0.16788074477782533
[I 2024-04-19 14:32:09,862] Trial 21 finished with value: 0.20490155424786397 and parameters: {'l1_ratio': 0.10457346814139208}. Best is trial 20 with value: 0.198749327965032.
Fold 1 IBS: 0.22256842373861252
Fold 2 IBS: 0.18175572800494638
Fold 3 IBS: 0.1979464126210484
Fold 4 IBS: 0.22369238847528028
Fold 5 IBS: 0.16790881040850894
[I 2024-04-19 14:32:10,207] Trial 22 finished with value: 0.1987743526496793 and parameters: {'l1_ratio': 0.1370395803870924}. Best is trial 20 with value: 0.198749327965032.
Fold 1 IBS: 0.24718433268895415
Fold 2 IBS: 0.2318068885072882
Fold 3 IBS: 0.22897166987708772
Fold 4 IBS: 0.24180821520933402
Fold 5 IBS: 0.22922824630044986
[I 2024-04-19 14:32:10,355] Trial 23 finished with value: 0.2357998705166228 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 20 with value: 0.198749327965032.
Fold 1 IBS: 0.2225841138082969
Fold 2 IBS: 0.18184825368969723
Fold 3 IBS: 0.19839604553459717
Fold 4 IBS: 0.22374277660494665
Fold 5 IBS: 0.16811711753539335
[I 2024-04-19 14:32:10,810] Trial 24 finished with value: 0.1989376614345863 and parameters: {'l1_ratio': 0.3537677379169781}. Best is trial 20 with value: 0.198749327965032.
Fold 1 IBS: 0.22258545780056535

Fold 2 IBS: 0.18182827943475607
Fold 3 IBS: 0.1983027056168231
Fold 4 IBS: 0.2236969058051047
Fold 5 IBS: 0.16807672058593062
[I 2024-04-19 14:32:11,275] Trial 25 finished with value: 0.19889801384863598 and parameters: {'l1_ratio': 0.30614008618835464}. Best is trial 20 with value: 0.198749327965032.
Fold 1 IBS: 0.2225581693835911
Fold 2 IBS: 0.18175084032337233
Fold 3 IBS: 0.19791958521091388
Fold 4 IBS: 0.22357324265909004
Fold 5 IBS: 0.16788657871133672
[I 2024-04-19 14:32:11,692] Trial 26 finished with value: 0.1987376832576608 and parameters: {'l1_ratio': 0.11368595762521919}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22257263067044297
Fold 2 IBS: 0.18192383838742884
Fold 3 IBS: 0.19874727605699896
Fold 4 IBS: 0.22381170476765064
Fold 5 IBS: 0.16832179413382806
[I 2024-04-19 14:32:12,143] Trial 27 finished with value: 0.1990754488032699 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22253855595779784
Fold 2 IBS: 0.18199417160944042
Fold 3 IBS: 0.19907555909716915
Fold 4 IBS: 0.22392752931208285
Fold 5 IBS: 0.16856461439751547
[I 2024-04-19 14:32:12,531] Trial 28 finished with value: 0.19922008607480113 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225661602257356
Fold 2 IBS: 0.22654587206525226
Fold 3 IBS: 0.2287837460067176
Fold 4 IBS: 0.23803189079698037
Fold 5 IBS: 0.16789618878492774
[I 2024-04-19 14:32:12,956] Trial 29 finished with value: 0.21676477157592272 and parameters: {'l1_ratio': 0.06391141854855716}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22257903806966356
Fold 2 IBS: 0.18180397259717915
Fold 3 IBS: 0.19818359447843675
Fold 4 IBS: 0.22365627306588637
Fold 5 IBS: 0.16800905142509315
[I 2024-04-19 14:32:13,622] Trial 30 finished with value: 0.1988463859272518 and parameters: {'l1_ratio': 0.24134237659584223}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22255969471679804
Fold 2 IBS: 0.18177439901778264
Fold 3 IBS: 0.19803512194420797
Fold 4 IBS: 0.22362274227744822
Fold 5 IBS: 0.1679173223036158
[I 2024-04-19 14:32:14,332] Trial 31 finished with value: 0.19878185605197055 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22257070012970154
Fold 2 IBS: 0.18174040223553914
Fold 3 IBS: 0.22876023826489164
Fold 4 IBS: 0.23731970361627908
Fold 5 IBS: 0.16788851787493306
[I 2024-04-19 14:32:14,760] Trial 32 finished with value: 0.2076559124242689 and parameters: {'l1_ratio': 0.0775732681201072}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225637316669545
Fold 2 IBS: 0.181761669897299
Fold 3 IBS: 0.1979739943546655
Fold 4 IBS: 0.22358796145860607
Fold 5 IBS: 0.16789050797866123
[I 2024-04-19 14:32:15,179] Trial 33 finished with value: 0.19875557307123726 and parameters: {'l1_ratio': 0.13953192462147126}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22258792669872743
Fold 2 IBS: 0.18183219865021183
Fold 3 IBS: 0.19820760832292803
Fold 4 IBS: 0.22364705507317864
Fold 5 IBS: 0.16803163998346213
[I 2024-04-19 14:32:15,585] Trial 34 finished with value: 0.1988612857457016 and parameters: {'l1_ratio': 0.2650294016254606}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22256756005372555
Fold 2 IBS: 0.18179039614239967
Fold 3 IBS: 0.19811424765984154
Fold 4 IBS: 0.22364813867262973
Fold 5 IBS: 0.16796199743869522
[I 2024-04-19 14:32:16,241] Trial 35 finished with value: 0.19881646799345837 and parameters: {'l1_ratio': 0.19631609988412568}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22256359750142915
Fold 2 IBS: 0.1819676335673173
Fold 3 IBS: 0.19897062723635794
Fold 4 IBS: 0.22393335235485834
Fold 5 IBS: 0.16849430860415224
[I 2024-04-19 14:32:16,712] Trial 36 finished with value: 0.199185903852823 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.246325540947242
Fold 2 IBS: 0.22895366670934333
Fold 3 IBS: 0.22885831400607476
Fold 4 IBS: 0.2397619558469924
Fold 5 IBS: 0.22718329509768811
[I 2024-04-19 14:32:16,918] Trial 37 finished with value: 0.23421655452146814 and parameters: {'l1_ratio': 0.03370472780775656}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225710124904745
Fold 2 IBS: 0.18182851527136393
Fold 3 IBS: 0.1982981137363616
Fold 4 IBS: 0.22372859849110383
Fold 5 IBS: 0.16804548751629075
[I 2024-04-19 14:32:17,495] Trial 38 finished with value: 0.19889434550111892 and parameters: {'l1_ratio': 0.2833441121940795}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22256056222635476
Fold 2 IBS: 0.18187879686603944
Fold 3 IBS: 0.19852988679907058
Fold 4 IBS: 0.22377710652253163
Fold 5 IBS: 0.16820953061246288
[I 2024-04-19 14:32:18,368] Trial 39 finished with value: 0.19899117660529186 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22255212336550048
Fold 2 IBS: 0.18175078892733945
Fold 3 IBS: 0.2287311686708867
Fold 4 IBS: 0.22358580384425236
Fold 5 IBS: 0.1678794442722376
[I 2024-04-19 14:32:18,881] Trial 40 finished with value: 0.2048998658160433 and parameters: {'l1_ratio': 0.10420213819145041}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225804910666873
Fold 2 IBS: 0.18175985047526286
Fold 3 IBS: 0.19796133834316088
Fold 4 IBS: 0.22361232292217534
Fold 5 IBS: 0.1678700807872167
[I 2024-04-19 14:32:19,273] Trial 41 finished with value: 0.1987568167189006 and parameters: {'l1_ratio': 0.1168365867214849}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22256077511181976
Fold 2 IBS: 0.18175617140315653
Fold 3 IBS: 0.19794583186667086
Fold 4 IBS: 0.22358063763575176
Fold 5 IBS: 0.16790067321945848
[I 2024-04-19 14:32:20,102] Trial 42 finished with value: 0.19874881784737147 and parameters: {'l1_ratio': 0.12591197171927954}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22257886916512973
Fold 2 IBS: 0.18191709513046103
Fold 3 IBS: 0.19871925447443475
Fold 4 IBS: 0.22378577790349038
Fold 5 IBS: 0.1683113409695703
[I 2024-04-19 14:32:20,714] Trial 43 finished with value: 0.19906246752861723 and parameters: {'l1_ratio': 0.5684779587956832}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225712729449147
Fold 2 IBS: 0.18178580421939783
Fold 3 IBS: 0.1980933640828128
Fold 4 IBS: 0.22362984191500437
Fold 5 IBS: 0.16795604798184838
[I 2024-04-19 14:32:21,393] Trial 44 finished with value: 0.1988072662287956 and parameters: {'l1_ratio': 0.1934886329988997}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22255069419499035
Fold 2 IBS: 0.1817455096119767
Fold 3 IBS: 0.22873982018354258
Fold 4 IBS: 0.23651810070825702
Fold 5 IBS: 0.16787081647266627
[I 2024-04-19 14:32:21,797] Trial 45 finished with value: 0.20748498823428657 and parameters: {'l1_ratio': 0.09396801909915135}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22254907200848167
Fold 2 IBS: 0.22834950130090068
Fold 3 IBS: 0.2288375208495475
Fold 4 IBS: 0.2393276906839005
Fold 5 IBS: 0.22675114832258977
[I 2024-04-19 14:32:22,391] Trial 46 finished with value: 0.22916298663308404 and parameters: {'l1_ratio': 0.04092894430859198}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225766805743878
Fold 2 IBS: 0.18179114664886212
Fold 3 IBS: 0.19799091253317122
Fold 4 IBS: 0.22369174931579536
Fold 5 IBS: 0.1679156468088239
[I 2024-04-19 14:32:22,981] Trial 47 finished with value: 0.1987932271762081 and parameters: {'l1_ratio': 0.16653572390273655}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225665578215133
Fold 2 IBS: 0.18180483406758727
Fold 3 IBS: 0.19818319850002672
Fold 4 IBS: 0.2236859941731954
Fold 5 IBS: 0.16797663893454085
[I 2024-04-19 14:32:23,453] Trial 48 finished with value: 0.1988434446993727 and parameters: {'l1_ratio': 0.223203460085997}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22256834839135017
Fold 2 IBS: 0.18186650921278158
Fold 3 IBS: 0.1983897969810453
Fold 4 IBS: 0.22381395721807026
Fold 5 IBS: 0.16814286066528716
[I 2024-04-19 14:32:24,104] Trial 49 finished with value: 0.19895629449370691 and parameters: {'l1_ratio': 0.37736514210267713}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22257990258066748

Fold 2 IBS: 0.18183484175067388
Fold 3 IBS: 0.19833177688925338
Fold 4 IBS: 0.22372220531719153
Fold 5 IBS: 0.168075203534567
[I 2024-04-19 14:32:24,593] Trial 50 finished with value: 0.19890878601447065 and parameters: {'l1_ratio': 0.31297686520002327}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22255942575194992
Fold 2 IBS: 0.18175788943781737
Fold 3 IBS: 0.19795379708750568
Fold 4 IBS: 0.22358765093995706
Fold 5 IBS: 0.16787604959358524
[I 2024-04-19 14:32:25,234] Trial 51 finished with value: 0.19874696256216307 and parameters: {'l1_ratio': 0.1265696579057886}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22258042673434433
Fold 2 IBS: 0.18175992873615382
Fold 3 IBS: 0.197961699317436
Fold 4 IBS: 0.22361263992858413
Fold 5 IBS: 0.16787018091678751
[I 2024-04-19 14:32:25,882] Trial 52 finished with value: 0.19875697512666118 and parameters: {'l1_ratio': 0.11686454792811474}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22255804829497908
Fold 2 IBS: 0.2273342788362322
Fold 3 IBS: 0.228805617479062
Fold 4 IBS: 0.2385980213401165
Fold 5 IBS: 0.16793407002901334
[I 2024-04-19 14:32:26,256] Trial 53 finished with value: 0.21704600719588063 and parameters: {'l1_ratio': 0.05359228079143073}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22257362566034317
Fold 2 IBS: 0.1817947938499715
Fold 3 IBS: 0.19800873730874166
Fold 4 IBS: 0.22370604679021955
Fold 5 IBS: 0.1679206207635744
[I 2024-04-19 14:32:26,856] Trial 54 finished with value: 0.19880076487457005 and parameters: {'l1_ratio': 0.16850086923982294}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.24696553951286024
Fold 2 IBS: 0.23102528675110673
Fold 3 IBS: 0.22893839736248303
Fold 4 IBS: 0.24124885312886624
Fold 5 IBS: 0.22866736777950664
[I 2024-04-19 14:32:27,093] Trial 55 finished with value: 0.23536908890696456 and parameters: {'l1_ratio': 0.010531383940684869}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225607606993247
Fold 2 IBS: 0.18182545976277578
Fold 3 IBS: 0.19817535694666563
Fold 4 IBS: 0.2237424264055159
Fold 5 IBS: 0.16802230033428833
[I 2024-04-19 14:32:27,636] Trial 56 finished with value: 0.19886526082971406 and parameters: {'l1_ratio': 0.2590406280116174}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22255772401917914
Fold 2 IBS: 0.1819237921830207
Fold 3 IBS: 0.19876016707207889
Fold 4 IBS: 0.22387503776942835
Fold 5 IBS: 0.16834669307990768
[I 2024-04-19 14:32:28,161] Trial 57 finished with value: 0.19909268282472298 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22256561873897698
Fold 2 IBS: 0.18175575169793978
Fold 3 IBS: 0.22874540592349818
Fold 4 IBS: 0.23676636089403313
Fold 5 IBS: 0.16784337225483867
[I 2024-04-19 14:32:28,618] Trial 58 finished with value: 0.20753530190185737 and parameters: {'l1_ratio': 0.08876672088029003}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.2225657104605673
Fold 2 IBS: 0.18175916480858725
Fold 3 IBS: 0.197962386670345
Fold 4 IBS: 0.2237052083303367
Fold 5 IBS: 0.1678872862276782
[I 2024-04-19 14:32:29,496] Trial 59 finished with value: 0.1987759512995029 and parameters: {'l1_ratio': 0.13847261653372273}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22258780144332427
Fold 2 IBS: 0.1818045735117955
Fold 3 IBS: 0.19806433270637439
Fold 4 IBS: 0.22370648154964923
Fold 5 IBS: 0.16796074687499915
[I 2024-04-19 14:32:30,608] Trial 60 finished with value: 0.19882478721722852 and parameters: {'l1_ratio': 0.20547545226024982}. Best is trial 26 with value: 0.1987376832576608.
Fold 1 IBS: 0.22257875623033557
Fold 2 IBS: 0.18176196026121788
Fold 3 IBS: 0.19783782230838287
Fold 4 IBS: 0.22362085736910126
Fold 5 IBS: 0.16787277977649034
[I 2024-04-19 14:32:31,235] Trial 61 finished with value: 0.19873443518910555 and parameters: {'l1_ratio': 0.1175940625021486}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22257830652510308
Fold 2 IBS: 0.18177140100362774
Fold 3 IBS: 0.19788738629991023
Fold 4 IBS: 0.22364501497114198
Fold 5 IBS: 0.16789350435825004
[I 2024-04-19 14:32:31,835] Trial 62 finished with value: 0.1987551226316066 and parameters: {'l1_ratio': 0.13198007206997864}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255592317337516
Fold 2 IBS: 0.18177916363829402
Fold 3 IBS: 0.19805689642492363
Fold 4 IBS: 0.22364429529603833
Fold 5 IBS: 0.16792345642519815
[I 2024-04-19 14:32:32,280] Trial 63 finished with value: 0.19879194699156585 and parameters: {'l1_ratio': 0.16033039291463586}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255449176498093
Fold 2 IBS: 0.18174976708317375
Fold 3 IBS: 0.22877830064419785
Fold 4 IBS: 0.23787880614931117
Fold 5 IBS: 0.1679725206979016
[I 2024-04-19 14:32:32,745] Trial 64 finished with value: 0.2077867772679131 and parameters: {'l1_ratio': 0.06678158959538745}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225492921751059
Fold 2 IBS: 0.2283523112700346
Fold 3 IBS: 0.2288376145690649
Fold 4 IBS: 0.23932971060836472
Fold 5 IBS: 0.22675315754500813
[I 2024-04-19 14:32:33,040] Trial 65 finished with value: 0.22916441723351566 and parameters: {'l1_ratio': 0.040894821186707564}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22256085524471622
Fold 2 IBS: 0.18181180096613087
Fold 3 IBS: 0.19810412327259125
Fold 4 IBS: 0.2237131409796151
Fold 5 IBS: 0.1679862484590452
[I 2024-04-19 14:32:33,773] Trial 66 finished with value: 0.19883523378441972 and parameters: {'l1_ratio': 0.2283450959509596}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225571413563912
Fold 2 IBS: 0.18194884380855275
Fold 3 IBS: 0.19887786127598378
Fold 4 IBS: 0.22391762900457876
Fold 5 IBS: 0.16842260931663972
[I 2024-04-19 14:32:34,259] Trial 67 finished with value: 0.19914481695242925 and parameters: {'l1_ratio': 0.7392393754397737}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22256929597282468
Fold 2 IBS: 0.18178231083584778
Fold 3 IBS: 0.197941263187018
Fold 4 IBS: 0.22368825283915802
Fold 5 IBS: 0.1679074689336646
[I 2024-04-19 14:32:34,714] Trial 68 finished with value: 0.19877771835370261 and parameters: {'l1_ratio': 0.1365836085503488}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255549667550234
Fold 2 IBS: 0.18179326554167258
Fold 3 IBS: 0.1980049857842627
Fold 4 IBS: 0.2236818439043527
Fold 5 IBS: 0.16793133377579791
[I 2024-04-19 14:32:35,154] Trial 69 finished with value: 0.19879338513631764 and parameters: {'l1_ratio': 0.18233648467842511}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22254941463920033
Fold 2 IBS: 0.1817378129252715
Fold 3 IBS: 0.22875112017699414
Fold 4 IBS: 0.23699395997942094
Fold 5 IBS: 0.1678553855383682
[I 2024-04-19 14:32:35,669] Trial 70 finished with value: 0.20757753865185102 and parameters: {'l1_ratio': 0.08409772933959295}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225670752446227
Fold 2 IBS: 0.18176811397696518
Fold 3 IBS: 0.19786616411598948
Fold 4 IBS: 0.2236581473572849
Fold 5 IBS: 0.16787277772035894
[I 2024-04-19 14:32:36,265] Trial 71 finished with value: 0.19874645568304422 and parameters: {'l1_ratio': 0.10988274578004145}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.24646891321427364
Fold 2 IBS: 0.22939503839899952
Fold 3 IBS: 0.22887428602260695
Fold 4 IBS: 0.24007910715349084
Fold 5 IBS: 0.22749918656879858
[I 2024-04-19 14:32:36,441] Trial 72 finished with value: 0.23446330627163392 and parameters: {'l1_ratio': 0.028565984952455714}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225643556133229
Fold 2 IBS: 0.18175161002424398
Fold 3 IBS: 0.19792461573930623
Fold 4 IBS: 0.2236907816110182
Fold 5 IBS: 0.16789515343876718
[I 2024-04-19 14:32:37,002] Trial 73 finished with value: 0.19876530328533168 and parameters: {'l1_ratio': 0.1241914205732045}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255388628246386
Fold 2 IBS: 0.18175052340319509
Fold 3 IBS: 0.22877801617679236
Fold 4 IBS: 0.23787064478562758
Fold 5 IBS: 0.167976529267853
[I 2024-04-19 14:32:37,585] Trial 74 finished with value: 0.2077859199831864 and parameters: {'l1_ratio': 0.06693559750774121}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22256167455573364

Fold 2 IBS: 0.18189566613314634
Fold 3 IBS: 0.1986289263483389
Fold 4 IBS: 0.2238144063367587
Fold 5 IBS: 0.16827084120297273
[I 2024-04-19 14:32:38,181] Trial 75 finished with value: 0.19903430291539004 and parameters: {'l1_ratio': 0.523110210901512}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255792160452792
Fold 2 IBS: 0.18176901837548343
Fold 3 IBS: 0.19800787253280158
Fold 4 IBS: 0.22361774383674754
Fold 5 IBS: 0.16789995287837237
[I 2024-04-19 14:32:38,592] Trial 76 finished with value: 0.19877050184558656 and parameters: {'l1_ratio': 0.14271358093225087}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225804671366443
Fold 2 IBS: 0.18180060546395152
Fold 3 IBS: 0.1980408252218206
Fold 4 IBS: 0.22371059269718394
Fold 5 IBS: 0.16794118873714264
[I 2024-04-19 14:32:39,374] Trial 77 finished with value: 0.19881473585134862 and parameters: {'l1_ratio': 0.18670775174471713}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2472380196791119
Fold 2 IBS: 0.23200590676385877
Fold 3 IBS: 0.2289803727569629
Fold 4 IBS: 0.2419504933182197
Fold 5 IBS: 0.2293711888675162
[I 2024-04-19 14:32:39,830] Trial 78 finished with value: 0.2359091962771339 and parameters: {'l1_ratio': 0.0003446446976768519}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255181561417037
Fold 2 IBS: 0.18175118425041528
Fold 3 IBS: 0.22873108217270094
Fold 4 IBS: 0.22358742087202316
Fold 5 IBS: 0.1678799207373591
[I 2024-04-19 14:32:41,076] Trial 79 finished with value: 0.2049002847293338 and parameters: {'l1_ratio': 0.10432659002249547}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255983363404838
Fold 2 IBS: 0.18182657801564464
Fold 3 IBS: 0.19818072293341693
Fold 4 IBS: 0.22374670921305764
Fold 5 IBS: 0.16802385005021436
[I 2024-04-19 14:32:41,676] Trial 80 finished with value: 0.19886753876927638 and parameters: {'l1_ratio': 0.2600189979607764}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225680722155953
Fold 2 IBS: 0.1817750491040148
Fold 3 IBS: 0.19790246849473656
Fold 4 IBS: 0.22367297860408658
Fold 5 IBS: 0.16788941270677393
[I 2024-04-19 14:32:42,027] Trial 81 finished with value: 0.19876159622504141 and parameters: {'l1_ratio': 0.12244233859759034}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22255383039088134
Fold 2 IBS: 0.1817485956961448
Fold 3 IBS: 0.22873165363101813
Fold 4 IBS: 0.22357681707614815
Fold 5 IBS: 0.16787680003471586
[I 2024-04-19 14:32:42,647] Trial 82 finished with value: 0.20489753936578164 and parameters: {'l1_ratio': 0.10351586133705698}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225733753925237
Fold 2 IBS: 0.1817870521898612
Fold 3 IBS: 0.1979675211175728
Fold 4 IBS: 0.22369200717887328
Fold 5 IBS: 0.16789844468353796
[I 2024-04-19 14:32:43,307] Trial 83 finished with value: 0.19878368011247377 and parameters: {'l1_ratio': 0.15102576258950196}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225479420082341
Fold 2 IBS: 0.1817337517997663
Fold 3 IBS: 0.22876255068296217
Fold 4 IBS: 0.23739675276795857
Fold 5 IBS: 0.16785641375463753
[I 2024-04-19 14:32:43,850] Trial 84 finished with value: 0.20765948220271171 and parameters: {'l1_ratio': 0.07605622913191278}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.222567174706989
Fold 2 IBS: 0.18180407965752768
Fold 3 IBS: 0.19817981083941522
Fold 4 IBS: 0.22368303988796528
Fold 5 IBS: 0.16797559843888257
[I 2024-04-19 14:32:44,366] Trial 85 finished with value: 0.19884194070615593 and parameters: {'l1_ratio': 0.22265790499667526}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22257779782626824
Fold 2 IBS: 0.1818037428809826
Fold 3 IBS: 0.19805606826718758
Fold 4 IBS: 0.22372279871500747
Fold 5 IBS: 0.16794548390766226
[I 2024-04-19 14:32:44,902] Trial 86 finished with value: 0.19882117831942164 and parameters: {'l1_ratio': 0.18862792891142766}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225537228626791
Fold 2 IBS: 0.18175652736688414
Fold 3 IBS: 0.19794598400233895
Fold 4 IBS: 0.2235964905876321
Fold 5 IBS: 0.1678934450340528
[I 2024-04-19 14:32:45,513] Trial 87 finished with value: 0.19874923397071742 and parameters: {'l1_ratio': 0.11565889348185741}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2465312940995923
Fold 2 IBS: 0.22959070230987746
Fold 3 IBS: 0.2288815669106707
Fold 4 IBS: 0.2402196588106632
Fold 5 IBS: 0.2276392748493936
[I 2024-04-19 14:32:45,785] Trial 88 finished with value: 0.23457249939603947 and parameters: {'l1_ratio': 0.026324196779796527}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22258116386289112
Fold 2 IBS: 0.18178578579147403
Fold 3 IBS: 0.19796459938707747
Fold 4 IBS: 0.22367061131651375
Fold 5 IBS: 0.1679319763409697
[I 2024-04-19 14:32:46,338] Trial 89 finished with value: 0.1987868273397852 and parameters: {'l1_ratio': 0.16371314317900412}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.22256860402382372
Fold 2 IBS: 0.22749620472813412
Fold 3 IBS: 0.22881043491279626
Fold 4 IBS: 0.23871437067263138
Fold 5 IBS: 0.22614131601232765
[I 2024-04-19 14:32:47,046] Trial 90 finished with value: 0.22874618606994263 and parameters: {'l1_ratio': 0.05152664731855751}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.222556026014189
Fold 2 IBS: 0.18175358235601694
Fold 3 IBS: 0.19793233283118242
Fold 4 IBS: 0.22358447387384908
Fold 5 IBS: 0.16788989051701592
[I 2024-04-19 14:32:47,959] Trial 91 finished with value: 0.19874326111845067 and parameters: {'l1_ratio': 0.11463061903055634}. Best is trial 61 with value: 0.19873443518910555.
Fold 1 IBS: 0.2225733941096181
Fold 2 IBS: 0.18176040859395742
Fold 3 IBS: 0.19782781023896617
Fold 4 IBS: 0.2236272060550689
Fold 5 IBS: 0.16786294657835807
[I 2024-04-19 14:32:49,769] Trial 92 finished with value: 0.19873035311519377 and parameters: {'l1_ratio': 0.10729770639367668}. Best is trial 92 with value: 0.19873035311519377.
Fold 1 IBS: 0.2225505619194093
Fold 2 IBS: 0.1817456802739303
Fold 3 IBS: 0.22873977230482345
Fold 4 IBS: 0.2365158299838463
Fold 5 IBS: 0.16787150301446732
[I 2024-04-19 14:32:51,369] Trial 93 finished with value: 0.20748466949929534 and parameters: {'l1_ratio': 0.09401613046654367}. Best is trial 92 with value: 0.19873035311519377.
Fold 1 IBS: 0.2225640013375969
Fold 2 IBS: 0.1817520614955756
Fold 3 IBS: 0.1979267202228927
Fold 4 IBS: 0.22369247188405733
Fold 5 IBS: 0.16789570006827367
[I 2024-04-19 14:32:52,540] Trial 94 finished with value: 0.19876619100167928 and parameters: {'l1_ratio': 0.12436008972859439}. Best is trial 92 with value: 0.19873035311519377.
Fold 1 IBS: 0.22255744791618678
Fold 2 IBS: 0.18174607231783285
Fold 3 IBS: 0.2287796867629895
Fold 4 IBS: 0.2379183323126347
Fold 5 IBS: 0.167952931331479
[I 2024-04-19 14:32:53,160] Trial 95 finished with value: 0.20779089412822457 and parameters: {'l1_ratio': 0.06603714481357004}. Best is trial 92 with value: 0.19873035311519377.
Fold 1 IBS: 0.22256498405581324
Fold 2 IBS: 0.1817789220582648
Fold 3 IBS: 0.19805870436062173
Fold 4 IBS: 0.22362265327573377
Fold 5 IBS: 0.16793465769587784
[I 2024-04-19 14:32:53,721] Trial 96 finished with value: 0.19879198428926226 and parameters: {'l1_ratio': 0.1742523324716236}. Best is trial 92 with value: 0.19873035311519377.
Fold 1 IBS: 0.2225730668174751
Fold 2 IBS: 0.18176080814765344
Fold 3 IBS: 0.1978298061131826
Fold 4 IBS: 0.22362881821148495
Fold 5 IBS: 0.16786345658832055
[I 2024-04-19 14:32:55,443] Trial 97 finished with value: 0.19873119117562332 and parameters: {'l1_ratio': 0.1074293860522331}. Best is trial 92 with value: 0.19873035311519377.
Fold 1 IBS: 0.22255626467884193
Fold 2 IBS: 0.18180433490800066
Fold 3 IBS: 0.19806317235631993
Fold 4 IBS: 0.2237055518175853
Fold 5 IBS: 0.16796041906696868
[I 2024-04-19 14:32:56,078] Trial 98 finished with value: 0.1988179485655433 and parameters: {'l1_ratio': 0.20531566073804333}. Best is trial 92 with value: 0.19873035311519377.
Fold 1 IBS: 0.2225721051971188
Fold 2 IBS: 0.18176198180045194
Fold 3 IBS: 0.19783566431140043
Fold 4 IBS: 0.22363354885629286
Fold 5 IBS: 0.167864954551415
[I 2024-04-19 14:32:56,873] Trial 99 finished with value: 0.1987336509433358 and parameters: {'l1_ratio': 0.10781765565647045}. Best is trial 92 with value: 0.19873035311519377.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.19873035311519377], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 48, 9753), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 49, 718122), params={'l1_ratio': 0.10729770639367668}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=92, value=None)


* Best Score for IBS:
 0.19873035311519377

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.726
train_ibs:  0.199

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.21890747475310213)

test_cindex : 0.56

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.10729770639367668)

test_ibs:  0.289

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:58,424] A new study created in memory with name: no-name-88a5c509-d094-4074-829e-215034fbbdec

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 14:33:04,901] Trial 0 finished with value: 0.6991621322401306 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6991621322401306.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7510729613733905
[I 2024-04-19 14:33:09,270] Trial 1 finished with value: 0.7355301592065651 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7339055793991416
[I 2024-04-19 14:33:12,748] Trial 2 finished with value: 0.7272289231066792 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:33:13,685] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:33:15,471] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7510729613733905
[I 2024-04-19 14:33:21,676] Trial 5 finished with value: 0.7346380398835799 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7339055793991416
[I 2024-04-19 14:33:25,875] Trial 6 finished with value: 0.7176325154358497 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:33:28,534] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 14:33:35,089] Trial 8 finished with value: 0.5339055793991416 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7510729613733905
[I 2024-04-19 14:33:39,740] Trial 9 finished with value: 0.7297749791965019 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:33:40,039] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7167381974248928
[I 2024-04-19 14:33:42,301] Trial 11 finished with value: 0.7275011596037759 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7339055793991416
[I 2024-04-19 14:33:48,346] Trial 12 finished with value: 0.7312271571122319 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7124463519313304
[I 2024-04-19 14:33:55,050] Trial 13 finished with value: 0.7285078854302759 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017530569165213797, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.776824034334764
[I 2024-04-19 14:33:56,138] Trial 14 finished with value: 0.7726196368380054 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.48589405900235655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17488909350671974, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7751937984496124

Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.759656652360515
[I 2024-04-19 14:33:57,284] Trial 15 finished with value: 0.7430557612306835 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.3692598016141903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17993556917544976, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:33:57,651] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1937382585942945, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:33:58,906] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 123, 'oob_score': True, 'max_samples': 0.21593809517049486, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7939914163090128
[I 2024-04-19 14:34:00,062] Trial 18 finished with value: 0.7670383225171615 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 113, 'oob_score': True, 'max_samples': 0.44482585532317004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17047935743788273, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:34:00,917] Trial 19 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.4891559132906001, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42883326307517006, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:34:02,360] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.4189734961049175, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2519967097606023, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:34:03,368] Trial 21 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.31767468948360755, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16572240592344814, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7725321888412017
[I 2024-04-19 14:34:04,102] Trial 22 finished with value: 0.7691752300964144 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.5356189047828304, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2038631927701136, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-19 14:34:04,646] Trial 23 finished with value: 0.8046827761584172 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.5413453585840211, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07940861604666782, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8068669527896996
[I 2024-04-19 14:34:04,915] Trial 24 finished with value: 0.7968628519610398 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 12, 'oob_score': True, 'max_samples': 0.5434778837030446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08417649111696884, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.812015503875969
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7253218884120172
[I 2024-04-19 14:34:05,093] Trial 25 finished with value: 0.781126535297143 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07045653823703169, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8412017167381974
[I 2024-04-19 14:34:05,434] Trial 26 finished with value: 0.8041494497509662 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.6794016704774145, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8412017167381974
[I 2024-04-19 14:34:06,272] Trial 27 finished with value: 0.8126094014577081 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.8630402705028295, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07610225238763382, 'warm_start': True}. Best is trial 27 with value: 0.8126094014577081.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8454935622317596
[I 2024-04-19 14:34:06,693] Trial 28 finished with value: 0.8020961148667425 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.9854572776620717, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1322471380695946, 'warm_start': True}. Best is trial 27 with value: 0.8126094014577081.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8927038626609443
[I 2024-04-19 14:34:08,348] Trial 29 finished with value: 0.839683794009181 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 163, 'oob_score': True, 'max_samples': 0.8309193149442771, 'max_features': None, 'min_weight_fraction_leaf': 0.061461466531914734, 'warm_start': True}. Best is trial 29 with value: 0.839683794009181.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9012875536480687
[I 2024-04-19 14:34:10,198] Trial 30 finished with value: 0.8471808956568762 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 162, 'oob_score': True, 'max_samples': 0.8384725652873207, 'max_features': None, 'min_weight_fraction_leaf': 0.03824151200409104, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8969957081545065
[I 2024-04-19 14:34:12,336] Trial 31 finished with value: 0.8438452051001395 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.8383718236388968, 'max_features': None, 'min_weight_fraction_leaf': 0.05349821135610229, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8969957081545065
[I 2024-04-19 14:34:14,070] Trial 32 finished with value: 0.8463115133784891 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.844850651135347, 'max_features': None, 'min_weight_fraction_leaf': 0.047131601168288385, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8969957081545065
[I 2024-04-19 14:34:16,690] Trial 33 finished with value: 0.8477634373205489 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.8400958521101125, 'max_features': None, 'min_weight_fraction_leaf': 0.003787219752160495, 'warm_start': True}. Best is trial 33 with value: 0.8477634373205489.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8798283261802575
[I 2024-04-19 14:34:19,253] Trial 34 finished with value: 0.8348953318242721 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.7437347513388699, 'max_features': None, 'min_weight_fraction_leaf': 0.002606193898855683, 'warm_start': True}. Best is trial 33 with value: 0.8477634373205489.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9098712446351931
[I 2024-04-19 14:34:21,857] Trial 35 finished with value: 0.8513492046079651 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8867083209187331, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8927038626609443
[I 2024-04-19 14:34:25,253] Trial 36 finished with value: 0.8327544194780486 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.9510497756961918, 'max_features': None, 'min_weight_fraction_leaf': 0.03820571175421267, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9184549356223176
[I 2024-04-19 14:34:28,843] Trial 37 finished with value: 0.8513421961952613 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 256, 'oob_score': True, 'max_samples': 0.8905785303043968, 'max_features': None, 'min_weight_fraction_leaf': 0.0015959813648095014, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-19 14:34:32,503] Trial 38 finished with value: 0.8036433012288817 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.8788883038694885, 'max_features': None, 'min_weight_fraction_leaf': 0.002532290324689703, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:34:37,850] Trial 39 finished with value: 0.7672578212055718 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.9144710105629309, 'max_features': None, 'min_weight_fraction_leaf': 0.12930362433818024, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8884120171673819
[I 2024-04-19 14:34:43,653] Trial 40 finished with value: 0.8277166012617376 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9980478663893719, 'max_features': None, 'min_weight_fraction_leaf': 0.029813810847214628, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9098712446351931
[I 2024-04-19 14:34:47,495] Trial 41 finished with value: 0.8520485283750772 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 207, 'oob_score': True, 'max_samples': 0.8024276641096046, 'max_features': None, 'min_weight_fraction_leaf': 0.041434068575410196, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9012875536480687
[I 2024-04-19 14:34:51,358] Trial 42 finished with value: 0.8479087198004114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.7648836348187944, 'max_features': None, 'min_weight_fraction_leaf': 0.033423986218882616, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9012875536480687
[I 2024-04-19 14:34:54,289] Trial 43 finished with value: 0.8496540853610947 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 205, 'oob_score': True, 'max_samples': 0.7796080313426239, 'max_features': None, 'min_weight_fraction_leaf': 0.014857830524255941, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8454935622317596
[I 2024-04-19 14:34:56,537] Trial 44 finished with value: 0.8078917831058507 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7797897259787169, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-19 14:34:58,619] Trial 45 finished with value: 0.7904418608687293 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7138201818624347, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14694492074117838, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:35:08,402] Trial 46 finished with value: 0.7254981239299447 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 284, 'oob_score': True, 'max_samples': 0.8992746801558931, 'max_features': None, 'min_weight_fraction_leaf': 0.028181408583194678, 'warm_start': False}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9012875536480687
[I 2024-04-19 14:35:10,202] Trial 47 finished with value: 0.8365327725015698 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.7205133550183166, 'max_features': None, 'min_weight_fraction_leaf': 0.05574216570821283, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 14:35:19,460] Trial 48 finished with value: 0.7086009095296246 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.8036505209305815, 'max_features': None, 'min_weight_fraction_leaf': 0.22178657477496955, 'warm_start': False}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-19 14:35:23,698] Trial 49 finished with value: 0.7960271358026422 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.610884224629099, 'max_features': None, 'min_weight_fraction_leaf': 0.10220826251839069, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7939914163090128
[I 2024-04-19 14:35:25,487] Trial 50 finished with value: 0.7854372155985099 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9361939014586368, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.28018530821993104, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-19 14:35:28,093] Trial 51 finished with value: 0.7756710134041036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.7993151610130277, 'max_features': None, 'min_weight_fraction_leaf': 0.0005063458363507817, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9141630901287554
[I 2024-04-19 14:35:30,825] Trial 52 finished with value: 0.8535946407970745 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.8921259102671709, 'max_features': None, 'min_weight_fraction_leaf': 0.018293305903393637, 'warm_start': True}. Best is trial 52 with value: 0.8535946407970745.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.927038626609442
[I 2024-04-19 14:35:33,575] Trial 53 finished with value: 0.8585132240941041 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.9658618134365592, 'max_features': None, 'min_weight_fraction_leaf': 0.014650326015013641, 'warm_start': True}. Best is trial 53 with value: 0.8585132240941041.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:35:36,585] Trial 54 finished with value: 0.8632581679559443 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.9625534179904701, 'max_features': None, 'min_weight_fraction_leaf': 0.019842323563345525, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.9186046511627907
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:35:38,358] Trial 55 finished with value: 0.8631822979246067 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.9637396879166721, 'max_features': None, 'min_weight_fraction_leaf': 0.02006130607634453, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.759656652360515
[I 2024-04-19 14:35:45,563] Trial 56 finished with value: 0.7258200494907298 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 141, 'oob_score': True, 'max_samples': 0.9627981016911359, 'max_features': None, 'min_weight_fraction_leaf': 0.05237976583817004, 'warm_start': False}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.927038626609442
[I 2024-04-19 14:35:50,272] Trial 57 finished with value: 0.8624540499380153 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.969742549381378, 'max_features': None, 'min_weight_fraction_leaf': 0.023371324683680833, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:35:53,774] Trial 58 finished with value: 0.8623951162735353 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9690133939480812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021524357754764783, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:35:55,961] Trial 59 finished with value: 0.8623951162735353 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9702801247369853, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01939288260546853, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7167381974248928
[I 2024-04-19 14:36:00,737] Trial 60 finished with value: 0.7174226465122555 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9713481779848987, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.354956875935207, 'warm_start': False}. Best is trial 54 with value: 0.8632581679559443.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9356223175965666
[I 2024-04-19 14:36:02,466] Trial 61 finished with value: 0.863249761027237 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.9315899812443563, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023014102784859193, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9055793991416309
[I 2024-04-19 14:36:03,430] Trial 62 finished with value: 0.8405373371031004 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9238731528894242, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06716848446483438, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:36:04,749] Trial 63 finished with value: 0.7482015307786698 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.949454174371522, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42582787243459574, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8798283261802575
[I 2024-04-19 14:36:06,263] Trial 64 finished with value: 0.8273796413200459 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.9917921798289998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09031712086014251, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:36:08,782] Trial 65 finished with value: 0.8592294842280737 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9240040548597519, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02047626469173783, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9012875536480687
[I 2024-04-19 14:36:10,616] Trial 66 finished with value: 0.8394945958114837 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9229156191863954, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06380717535025415, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8412017167381974
[I 2024-04-19 14:36:12,783] Trial 67 finished with value: 0.7955811892681643 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.995009976038662, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02429896250829207, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8884120171673819
[I 2024-04-19 14:36:13,855] Trial 68 finished with value: 0.8338770961561366 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.9428503920721849, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-19 14:36:15,201] Trial 69 finished with value: 0.8069246578719019 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 146, 'oob_score': False, 'max_samples': 0.8666896988471977, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.124823245098527, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8154506437768241
[I 2024-04-19 14:36:16,741] Trial 70 finished with value: 0.7945878301699866 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 130, 'oob_score': False, 'max_samples': 0.12462860681265314, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02126228748040546, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:36:18,716] Trial 71 finished with value: 0.859189970671976 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.9740624334770935, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016292071205830195, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.927038626609442
[I 2024-04-19 14:36:20,272] Trial 72 finished with value: 0.8567849383213751 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.9162488213949347, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05261359898316401, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9356223175965666
[I 2024-04-19 14:36:22,039] Trial 73 finished with value: 0.8633946196640432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.9999354575629575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031604961665606564, 'warm_start': True}. Best is trial 73 with value: 0.8633946196640432.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9356223175965666
[I 2024-04-19 14:36:23,887] Trial 74 finished with value: 0.8649624944576914 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.9395463682850804, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03591904730025234, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8884120171673819

[I 2024-04-19 14:36:25,270] Trial 75 finished with value: 0.8291758140384612 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 151, 'oob_score': False, 'max_samples': 0.9558720298384755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08775783727116993, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9574468085106383
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9356223175965666
[I 2024-04-19 14:36:26,660] Trial 76 finished with value: 0.8644300556867346 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.993930256699719, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0398572345294084, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8927038626609443
[I 2024-04-19 14:36:27,978] Trial 77 finished with value: 0.8340113654563247 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9913390641588559, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04234216642710123, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8884120171673819
[I 2024-04-19 14:36:29,697] Trial 78 finished with value: 0.8409578033411496 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.8630045149985799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0609070149180181, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8540772532188842
[I 2024-04-19 14:36:30,525] Trial 79 finished with value: 0.8035852429701545 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 127, 'oob_score': False, 'max_samples': 0.9045813350723169, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07865274171241976, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-19 14:36:32,654] Trial 80 finished with value: 0.7261480403266783 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9452700606717033, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03478111510727396, 'warm_start': False}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9227467811158798
[I 2024-04-19 14:36:34,246] Trial 81 finished with value: 0.8600881237347175 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9701774756059413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009387333105181828, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-19 14:36:35,861] Trial 82 finished with value: 0.8634130815337395 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.9740317203146824, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031105510537608762, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:36:37,648] Trial 83 finished with value: 0.855212788352825 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.9452433661930899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.046861909789421494, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-19 14:36:39,840] Trial 84 finished with value: 0.85060280804216 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.991804397125127, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03327645272133899, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8626609442060086
[I 2024-04-19 14:36:41,687] Trial 85 finished with value: 0.8142802013847452 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.9999498552793648, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11550818315944608, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:36:43,589] Trial 86 finished with value: 0.8662268726917273 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.8746458616251406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030922977401692878, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8841201716738197
[I 2024-04-19 14:36:44,724] Trial 87 finished with value: 0.840718756224406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.8654172382794998, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06452241723435258, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.871244635193133
[I 2024-04-19 14:36:45,519] Trial 88 finished with value: 0.8168442790669467 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.9315642015297859, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0949696957319068, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9184549356223176
[I 2024-04-19 14:36:47,062] Trial 89 finished with value: 0.8558359452323782 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 125, 'oob_score': False, 'max_samples': 0.9038308798666062, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.044442422879351094, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:47,716] Trial 90 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.8757558739983621, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4966080828658863, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9399141630901288
[I 2024-04-19 14:36:50,031] Trial 91 finished with value: 0.8626884309053237 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.9776306114812428, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.028839161868997508, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9313304721030042
[I 2024-04-19 14:36:52,926] Trial 92 finished with value: 0.8560280629715251 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9311993321115322, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030551566023909363, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9227467811158798
[I 2024-04-19 14:36:54,823] Trial 93 finished with value: 0.8541564276305669 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.9091701552343036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009137289628038645, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-19 14:36:56,453] Trial 94 finished with value: 0.85451761277378 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9564057018609697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05197512631502196, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8798283261802575
[I 2024-04-19 14:36:58,804] Trial 95 finished with value: 0.8337498517029143 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8876723605013093, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07696236087701544, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9055793991416309
[I 2024-04-19 14:37:00,154] Trial 96 finished with value: 0.843083647166593 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9760183262225188, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00019495076365802846, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9399141630901288
[I 2024-04-19 14:37:01,808] Trial 97 finished with value: 0.8633118846410982 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.8197716452211096, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03271483017646171, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7811158798283262
[I 2024-04-19 14:37:09,439] Trial 98 finished with value: 0.7399225237760426 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.8315355201803293, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03474288685672425, 'warm_start': False}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9356223175965666
[I 2024-04-19 14:37:10,516] Trial 99 finished with value: 0.8552780690475444 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.9381470917280882, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.058903635501878514, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.

[I 2024-04-19 14:37:10,598] A new study created in memory with name: no-name-d02f89cd-0b0e-4711-87fc-521cae1eed3b

* Best trial for C-index:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.8662268726917273], datetime_start=datetime.datetime(2024, 4, 19, 14, 36, 41, 702255), datetime_complete=datetime.datetime(2024, 4, 19, 14, 36, 43, 588003), params={'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.8746458616251406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030922977401692878, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=86, value=None)


* Best Score for C-index:
 0.8662268726917273

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21762433179841878
Fold 2 IBS: 0.18195020133812084
Fold 3 IBS: 0.2361143230502189
Fold 4 IBS: 0.2073285062122392
Fold 5 IBS: 0.21392727346918483
[I 2024-04-19 14:37:20,482] Trial 0 finished with value: 0.21138892717363653 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21138892717363653.
Fold 1 IBS: 0.21581044184076711
Fold 2 IBS: 0.17697992286624134
Fold 3 IBS: 0.20953123826339945
Fold 4 IBS: 0.19758108917721037
Fold 5 IBS: 0.20179307042175074
[I 2024-04-19 14:37:22,234] Trial 1 finished with value: 0.2003391525138738 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-19 14:37:23,350] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-19 14:37:32,039] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-19 14:37:37,200] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.221854155851065
Fold 2 IBS: 0.17690263638724796
Fold 3 IBS: 0.1967547177467275
Fold 4 IBS: 0.18843430540942496
Fold 5 IBS: 0.18075314399111414
[I 2024-04-19 14:37:44,657] Trial 5 finished with value: 0.1929397918771159 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2131217857918839
Fold 2 IBS: 0.19307243279090222
Fold 3 IBS: 0.25137354374382015
Fold 4 IBS: 0.20218154161317498
Fold 5 IBS: 0.2126608840238083
[I 2024-04-19 14:37:52,943] Trial 6 finished with value: 0.2144820375927179 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2388433246721578
Fold 2 IBS: 0.22464552665811907
Fold 3 IBS: 0.22584090572561383
Fold 4 IBS: 0.231868515757187
Fold 5 IBS: 0.22190410121033288
[I 2024-04-19 14:38:05,705] Trial 7 finished with value: 0.22862047480468214 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-19 14:38:18,764] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.21807767436739164
Fold 2 IBS: 0.18501717466232873
Fold 3 IBS: 0.19984578577268608
Fold 4 IBS: 0.2107172403878465
Fold 5 IBS: 0.20405390685508257
[I 2024-04-19 14:38:21,923] Trial 9 finished with value: 0.20354235640906712 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-19 14:38:40,507] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.22667865765971248
Fold 2 IBS: 0.18386911210968868
Fold 3 IBS: 0.19650770014771463
Fold 4 IBS: 0.20835591158437963
Fold 5 IBS: 0.203472559428523
[I 2024-04-19 14:38:46,326] Trial 11 finished with value: 0.20377678818600367 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.23112230630238642
Fold 2 IBS: 0.1674454512633998
Fold 3 IBS: 0.19855471836895786
Fold 4 IBS: 0.1938632953802893
Fold 5 IBS: 0.18962922951564953
[I 2024-04-19 14:38:47,213] Trial 12 finished with value: 0.1961230001661366 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2413073544619049
Fold 2 IBS: 0.1811958871683442
Fold 3 IBS: 0.22244250686987974
Fold 4 IBS: 0.19750724899733643
Fold 5 IBS: 0.18232843513858982
[I 2024-04-19 14:38:47,936] Trial 13 finished with value: 0.20495628652721104 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2242647329441179
Fold 2 IBS: 0.17883999941146664
Fold 3 IBS: 0.1918443810565798
Fold 4 IBS: 0.19214931253213374
Fold 5 IBS: 0.1731968530886853
[I 2024-04-19 14:38:55,681] Trial 14 finished with value: 0.19205905580659666 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.6604916334814492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2288883257443599
Fold 2 IBS: 0.1738046533368976
Fold 3 IBS: 0.1959496843821166
Fold 4 IBS: 0.19095725701045163
Fold 5 IBS: 0.18213576812388554
[I 2024-04-19 14:39:03,708] Trial 15 finished with value: 0.19434713771954226 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9870260431565661, 'max_features': 'log2', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 14 with value: 0.19205905580659666.

Fold 1 IBS: 0.221052045952944
Fold 2 IBS: 0.17864590278571793
Fold 3 IBS: 0.20121068717993237
Fold 4 IBS: 0.19156051442456593
Fold 5 IBS: 0.18700261900559814
[I 2024-04-19 14:39:11,266] Trial 16 finished with value: 0.19589435386975168 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.6248405086569909, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.054994509022204895}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.24661458596136437
Fold 2 IBS: 0.23231122477788718
Fold 3 IBS: 0.229689256646579
Fold 4 IBS: 0.2413341340131506
Fold 5 IBS: 0.2302248378800009
[I 2024-04-19 14:39:16,324] Trial 17 finished with value: 0.23603480785579642 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.39119490979325144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.222887661575006
Fold 2 IBS: 0.18421435942452744
Fold 3 IBS: 0.19421453594382496
Fold 4 IBS: 0.19981786115023864
Fold 5 IBS: 0.1912096155424649
[I 2024-04-19 14:39:21,309] Trial 18 finished with value: 0.1984688067272124 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.21062982570611943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22047405758964184
Fold 2 IBS: 0.1966030079539471
Fold 3 IBS: 0.21350757148135177
Fold 4 IBS: 0.20455158700455836
Fold 5 IBS: 0.2019153339379839
[I 2024-04-19 14:39:26,941] Trial 19 finished with value: 0.20741031159349657 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.4386108822397098, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17720383372155285}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2203832582181566
Fold 2 IBS: 0.19931517540854854
Fold 3 IBS: 0.21442829878986364
Fold 4 IBS: 0.2069356513930878
Fold 5 IBS: 0.20374628014066523
[I 2024-04-19 14:39:38,349] Trial 20 finished with value: 0.20896173279006436 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.6164262808144682, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2275442075846795
Fold 2 IBS: 0.17484137550996653
Fold 3 IBS: 0.19334185644794946
Fold 4 IBS: 0.19132538175744745
Fold 5 IBS: 0.18115113844013128
[I 2024-04-19 14:39:44,040] Trial 21 finished with value: 0.19364079194803485 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9621081290297763, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01052588707306133}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.23054333285986953
Fold 2 IBS: 0.1724746302154596
Fold 3 IBS: 0.20261710681612344
Fold 4 IBS: 0.1926073795425933
Fold 5 IBS: 0.18185095277627958
[I 2024-04-19 14:39:49,488] Trial 22 finished with value: 0.1960186804420651 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.9874289067540774, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012068014135528271}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22601236961439128
Fold 2 IBS: 0.17969996069427818
Fold 3 IBS: 0.19876167471795514
Fold 4 IBS: 0.196787842235057
Fold 5 IBS: 0.18785036721027695
[I 2024-04-19 14:39:56,642] Trial 23 finished with value: 0.19782244289439171 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.8598545784448618, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08754103994167567}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22736870474237106
Fold 2 IBS: 0.17759080498432794
Fold 3 IBS: 0.1907220147867818
Fold 4 IBS: 0.19684291499550113
Fold 5 IBS: 0.173335537233157
[I 2024-04-19 14:40:00,387] Trial 24 finished with value: 0.19317199534842777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 171, 'oob_score': False, 'max_samples': 0.7977844441295365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03359112238003443}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22154369312237301
Fold 2 IBS: 0.17529814117915438
Fold 3 IBS: 0.19940916065427428
Fold 4 IBS: 0.19644777061534635
Fold 5 IBS: 0.18432305180010988
[I 2024-04-19 14:40:03,888] Trial 25 finished with value: 0.19540436347425158 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7991522227764232, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11631986143324591}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21676007374411307
Fold 2 IBS: 0.17824797677237728
Fold 3 IBS: 0.20701000107269518
Fold 4 IBS: 0.19291445170373886
Fold 5 IBS: 0.19374462748985236
[I 2024-04-19 14:40:08,145] Trial 26 finished with value: 0.19773542615655534 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 182, 'oob_score': True, 'max_samples': 0.6679645097491387, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038185359995283503}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21502992986795352
Fold 2 IBS: 0.1870308796226911
Fold 3 IBS: 0.2076665120334582
Fold 4 IBS: 0.19610467365474676
Fold 5 IBS: 0.2006394525445189
[I 2024-04-19 14:40:16,121] Trial 27 finished with value: 0.2012942895446737 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.4929150044278433, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15117671554446085}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22061913161771582
Fold 2 IBS: 0.1760211535374804
Fold 3 IBS: 0.1985451645372839
Fold 4 IBS: 0.1895387815583719
Fold 5 IBS: 0.18196669319802622
[I 2024-04-19 14:40:21,147] Trial 28 finished with value: 0.19333818488977564 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.7046067597565696, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08480904388715302}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21738957168254863
Fold 2 IBS: 0.18629216965440445
Fold 3 IBS: 0.23966304898222662
Fold 4 IBS: 0.21639319543648572
Fold 5 IBS: 0.21400347731487693
[I 2024-04-19 14:40:23,302] Trial 29 finished with value: 0.2147482926141085 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.6118767285087061, 'max_features': None, 'min_weight_fraction_leaf': 0.21149318025001101}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22758569118959
Fold 2 IBS: 0.1745807047630518
Fold 3 IBS: 0.19331240272244285
Fold 4 IBS: 0.19188841853726443
Fold 5 IBS: 0.17272789020296123
[I 2024-04-19 14:40:33,306] Trial 30 finished with value: 0.19201902148306207 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.770559095997367, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027011468511437653}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22584092896742133
Fold 2 IBS: 0.17585075081924822
Fold 3 IBS: 0.1972070156814071
Fold 4 IBS: 0.18881994130282825

Fold 5 IBS: 0.17585992091527558
[I 2024-04-19 14:40:40,494] Trial 31 finished with value: 0.19271571153723607 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.7600957156160437, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.045073432551245296}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22236771464371266
Fold 2 IBS: 0.17701546684229433
Fold 3 IBS: 0.19851905347240079
Fold 4 IBS: 0.18732302760178435
Fold 5 IBS: 0.18167933628393707
[I 2024-04-19 14:40:46,595] Trial 32 finished with value: 0.19338091976882582 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.6752379846937863, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07718385932974292}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2270170034083123
Fold 2 IBS: 0.1795970779202372
Fold 3 IBS: 0.19695809379393509
Fold 4 IBS: 0.1963645526898038
Fold 5 IBS: 0.18960590139682051
[I 2024-04-19 14:40:52,929] Trial 33 finished with value: 0.19790852584182178 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.7392038686189389, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050681546729188336}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22913107555986495
Fold 2 IBS: 0.1713200021524253
Fold 3 IBS: 0.20174276009751624
Fold 4 IBS: 0.19170526770572746
Fold 5 IBS: 0.18122337614028983
[I 2024-04-19 14:41:01,587] Trial 34 finished with value: 0.19502449633116475 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8878735229014442, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10769272272367647}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2263994177575451
Fold 2 IBS: 0.1782493853587001
Fold 3 IBS: 0.19967435367391417
Fold 4 IBS: 0.18957084972922195
Fold 5 IBS: 0.1806713908816942
[I 2024-04-19 14:41:11,100] Trial 35 finished with value: 0.1949130794802151 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.5635984815237928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.031068687969102886}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2140834251920096
Fold 2 IBS: 0.18302541234920544
Fold 3 IBS: 0.20583049051646687
Fold 4 IBS: 0.19225672545423975
Fold 5 IBS: 0.1950395683265298
[I 2024-04-19 14:41:18,766] Trial 36 finished with value: 0.19804712436769029 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.6797083197848384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16437366905173617}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2232352512407339
Fold 2 IBS: 0.1768499163180223
Fold 3 IBS: 0.20266000918435328
Fold 4 IBS: 0.19138188589544256
Fold 5 IBS: 0.18665967315448365
[I 2024-04-19 14:41:26,593] Trial 37 finished with value: 0.19615734715860716 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.7779331709919757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13312369867225185}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.24610665966261314
Fold 2 IBS: 0.23223155236224916
Fold 3 IBS: 0.22952300914119636
Fold 4 IBS: 0.2414811194823906
Fold 5 IBS: 0.23018872339055935
[I 2024-04-19 14:41:35,675] Trial 38 finished with value: 0.23590621280780172 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.48580268101444124, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22481799036239483
Fold 2 IBS: 0.17685147774699653
Fold 3 IBS: 0.20049010291951425
Fold 4 IBS: 0.18982857043914958
Fold 5 IBS: 0.18254203063054433
[I 2024-04-19 14:41:42,884] Trial 39 finished with value: 0.1949060344197199 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.5843062137973745, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07067430477200148}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2466142294056291
Fold 2 IBS: 0.23220067379443807
Fold 3 IBS: 0.22953256065286004
Fold 4 IBS: 0.24149352725075382
Fold 5 IBS: 0.23034005575836422
[I 2024-04-19 14:41:47,427] Trial 40 finished with value: 0.23603620937240904 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.6533926233121279, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3997341974880029}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22008661582176534
Fold 2 IBS: 0.17191458989661332
Fold 3 IBS: 0.19041182470823828
Fold 4 IBS: 0.1994085393279668
Fold 5 IBS: 0.17049962251252426
[I 2024-04-19 14:41:50,983] Trial 41 finished with value: 0.19046423845342159 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 196, 'oob_score': False, 'max_samples': 0.8079255109979475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03389223938021847}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.22280111750039264
Fold 2 IBS: 0.17796243072588608
Fold 3 IBS: 0.18962417076714974
Fold 4 IBS: 0.19463536301610113
Fold 5 IBS: 0.17836205501155145
[I 2024-04-19 14:41:54,239] Trial 42 finished with value: 0.19267702740421622 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.7310718829833422, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.029447700275051822}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.24650381632587262
Fold 2 IBS: 0.23211797085492242
Fold 3 IBS: 0.22955740353559057
Fold 4 IBS: 0.24157053900567507
Fold 5 IBS: 0.23027910552347802
[I 2024-04-19 14:41:58,314] Trial 43 finished with value: 0.23600576704910775 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.9068225316738959, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.2272741837619837
Fold 2 IBS: 0.18010040335739258
Fold 3 IBS: 0.18917888351764922
Fold 4 IBS: 0.19497471406918135
Fold 5 IBS: 0.17759835230906024
[I 2024-04-19 14:42:02,740] Trial 44 finished with value: 0.19382530740305343 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.8278518214882832, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032724850462757596}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.21818859674129706
Fold 2 IBS: 0.19182889723265809
Fold 3 IBS: 0.20645079219948698
Fold 4 IBS: 0.2039075995565362
Fold 5 IBS: 0.20251751001463825
[I 2024-04-19 14:42:05,928] Trial 45 finished with value: 0.2045786791489233 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.7211266599729008, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0184904067184055}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.24605956999356746
Fold 2 IBS: 0.1715522843932026
Fold 3 IBS: 0.22997512987796287
Fold 4 IBS: 0.2114434138594334
Fold 5 IBS: 0.20680985045195013
[I 2024-04-19 14:42:12,659] Trial 46 finished with value: 0.2131680497152233 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.8319888092703853, 'max_features': None, 'min_weight_fraction_leaf': 0.0015300457559763413}. Best is trial 41 with value: 0.19046423845342159.

Fold 1 IBS: 0.22670665484519142
Fold 2 IBS: 0.175184981867077
Fold 3 IBS: 0.20276219990812896
Fold 4 IBS: 0.19658107727261281
Fold 5 IBS: 0.17640448174832232
[I 2024-04-19 14:42:14,936] Trial 47 finished with value: 0.1955278791282665 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.7533756239183884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05433383705425634}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.21833683794653208
Fold 2 IBS: 0.16845072186321247
Fold 3 IBS: 0.20168040343516955
Fold 4 IBS: 0.1937674426294509
Fold 5 IBS: 0.19051837676249267
[I 2024-04-19 14:42:16,886] Trial 48 finished with value: 0.19455075652737155 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 82, 'oob_score': False, 'max_samples': 0.7075209195984526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10074510594123325}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.22242522647319046
Fold 2 IBS: 0.17089945636142403
Fold 3 IBS: 0.195613872409514
Fold 4 IBS: 0.18922142541007175
Fold 5 IBS: 0.17303791504234847
[I 2024-04-19 14:42:21,101] Trial 49 finished with value: 0.19023957913930975 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.7890788621794695, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04458702793409107}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22555617401744368
Fold 2 IBS: 0.17741085594825706
Fold 3 IBS: 0.20242485916185912
Fold 4 IBS: 0.19387487722329108
Fold 5 IBS: 0.18754644311102073
[I 2024-04-19 14:42:24,093] Trial 50 finished with value: 0.19736264189237435 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 220, 'oob_score': False, 'max_samples': 0.8555734953303252, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14147922592542847}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21627803680039687
Fold 2 IBS: 0.18166264021393835
Fold 3 IBS: 0.2092710829548924
Fold 4 IBS: 0.19595939612381622
Fold 5 IBS: 0.2011472544518922
[I 2024-04-19 14:42:28,327] Trial 51 finished with value: 0.20086368210898717 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.792480439746047, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04337189753109918}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22826690607978067
Fold 2 IBS: 0.17514993464852044
Fold 3 IBS: 0.19499180688840081
Fold 4 IBS: 0.19607308855822925
Fold 5 IBS: 0.1785126372364033
[I 2024-04-19 14:42:32,633] Trial 52 finished with value: 0.1945988746822669 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.7551979832732026, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0695275941074916}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2272968554576038
Fold 2 IBS: 0.1698341110510439
Fold 3 IBS: 0.19814117513373936
Fold 4 IBS: 0.20422983853085452
Fold 5 IBS: 0.16857687543461305
[I 2024-04-19 14:42:35,518] Trial 53 finished with value: 0.19361577112157094 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.9323805201970561, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024719341884636734}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22481757046708095
Fold 2 IBS: 0.17677433524674352
Fold 3 IBS: 0.19744731736557988
Fold 4 IBS: 0.1900684049643577
Fold 5 IBS: 0.17563795002659072
[I 2024-04-19 14:42:40,824] Trial 54 finished with value: 0.19294911561407058 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.7054751660094117, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05861070426347463}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22109268216759362
Fold 2 IBS: 0.1795317897821966
Fold 3 IBS: 0.19864062457744264
Fold 4 IBS: 0.1887540514309438
Fold 5 IBS: 0.18579795261641194
[I 2024-04-19 14:42:45,420] Trial 55 finished with value: 0.1947634201149177 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.6301567839071449, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08753416190089439}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23313488896504717
Fold 2 IBS: 0.19865251149482616
Fold 3 IBS: 0.20707690430687525
Fold 4 IBS: 0.20382506127552455
Fold 5 IBS: 0.20806640771791665
[I 2024-04-19 14:42:51,953] Trial 56 finished with value: 0.21015115475203797 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.8215366083160163, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021781106435660526}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.251405085227788
Fold 2 IBS: 0.17971245840591804
Fold 3 IBS: 0.20892416859276688
Fold 4 IBS: 0.2096604234179674
Fold 5 IBS: 0.18424709009072612
[I 2024-04-19 14:42:57,251] Trial 57 finished with value: 0.20678984514703327 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.8705287129013517, 'max_features': None, 'min_weight_fraction_leaf': 0.04455613136763016}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22775475401909703
Fold 2 IBS: 0.17495565316697842
Fold 3 IBS: 0.20607913041505693
Fold 4 IBS: 0.19159948662275345
Fold 5 IBS: 0.18048871793748186
[I 2024-04-19 14:43:01,010] Trial 58 finished with value: 0.19617554843227353 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.9463423717095281, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1156031725017496}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22758477258081827
Fold 2 IBS: 0.17158899508130857
Fold 3 IBS: 0.19616659435415607
Fold 4 IBS: 0.19199468063765252
Fold 5 IBS: 0.17000810523027976
[I 2024-04-19 14:43:06,094] Trial 59 finished with value: 0.19146862957684302 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.7604421792719349, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003738110192922882}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22873607517785616
Fold 2 IBS: 0.17390045472096774
Fold 3 IBS: 0.19717465713467122
Fold 4 IBS: 0.19069798125902654
Fold 5 IBS: 0.16839044559038258
[I 2024-04-19 14:43:11,353] Trial 60 finished with value: 0.19177992277658085 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.8025318592826676, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0035012585111243765}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23001446011337487
Fold 2 IBS: 0.17351898966358764
Fold 3 IBS: 0.19693929350409167
Fold 4 IBS: 0.19025194043534524
Fold 5 IBS: 0.16918574368972547
[I 2024-04-19 14:43:16,879] Trial 61 finished with value: 0.19198208548122497 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.7900678450377102, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00572289564152078}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22738806352311317
Fold 2 IBS: 0.17362132403038696
Fold 3 IBS: 0.19727565424618765
Fold 4 IBS: 0.19024256592293678

Fold 5 IBS: 0.16839194066878888
[I 2024-04-19 14:43:21,761] Trial 62 finished with value: 0.1913839096782827 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.8075940187858324, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0028869935676452026}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22802304509837604
Fold 2 IBS: 0.17093887708958988
Fold 3 IBS: 0.19997810028764312
Fold 4 IBS: 0.19416891669551373
Fold 5 IBS: 0.16864914160971897
[I 2024-04-19 14:43:27,695] Trial 63 finished with value: 0.19235161615616833 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.899801190989709, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0075083578814244606}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22706249643509485
Fold 2 IBS: 0.1740741132334453
Fold 3 IBS: 0.1982770517299122
Fold 4 IBS: 0.1942932217810348
Fold 5 IBS: 0.17209778370511547
[I 2024-04-19 14:43:34,183] Trial 64 finished with value: 0.1931609333769205 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8279032572597822, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0005239520819106591}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2249627623000506
Fold 2 IBS: 0.17734214004526475
Fold 3 IBS: 0.20042821363889923
Fold 4 IBS: 0.19132512948604202
Fold 5 IBS: 0.17992503554600825
[I 2024-04-19 14:43:38,923] Trial 65 finished with value: 0.19479665620325298 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7929889902503702, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0003379495295398175}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2258580567600176
Fold 2 IBS: 0.1725987117538336
Fold 3 IBS: 0.19691363075454665
Fold 4 IBS: 0.19294818573115283
Fold 5 IBS: 0.16674549590339433
[I 2024-04-19 14:43:45,553] Trial 66 finished with value: 0.191012816180589 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.8542677970427669, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02018893978213555}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22715985053253537
Fold 2 IBS: 0.175194067127973
Fold 3 IBS: 0.20235598060063445
Fold 4 IBS: 0.1915473606751296
Fold 5 IBS: 0.17533957463955674
[I 2024-04-19 14:43:50,889] Trial 67 finished with value: 0.19431936671516584 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.8537028925191168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06691183155682784}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2276240233573705
Fold 2 IBS: 0.17466029156341425
Fold 3 IBS: 0.19585094966145308
Fold 4 IBS: 0.1956019894346285
Fold 5 IBS: 0.17236600002537372
[I 2024-04-19 14:43:55,356] Trial 68 finished with value: 0.19322065080844802 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.8153568706687296, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020589797791063878}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2300113020332438
Fold 2 IBS: 0.1687511692442822
Fold 3 IBS: 0.200433873197082
Fold 4 IBS: 0.19350383522262551
Fold 5 IBS: 0.1749683856491631
[I 2024-04-19 14:44:01,989] Trial 69 finished with value: 0.1935337130692793 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'max_samples': 0.9627183310414489, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04180485598378051}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21313163321533152
Fold 2 IBS: 0.18353505015435204
Fold 3 IBS: 0.21120737776495918
Fold 4 IBS: 0.19490170617054509
Fold 5 IBS: 0.19862473265977015
[I 2024-04-19 14:44:07,013] Trial 70 finished with value: 0.2002800999929916 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.9259785083383683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.26527703823768367}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22671408988493402
Fold 2 IBS: 0.17109357051379762
Fold 3 IBS: 0.19869894342562636
Fold 4 IBS: 0.1930683536390453
Fold 5 IBS: 0.1684970080938331
[I 2024-04-19 14:44:11,745] Trial 71 finished with value: 0.19161439311144726 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.8750321012509876, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016570826484099625}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22688669905527847
Fold 2 IBS: 0.17075390562804646
Fold 3 IBS: 0.1985253537047414
Fold 4 IBS: 0.19308404898587175
Fold 5 IBS: 0.16784784499547226
[I 2024-04-19 14:44:17,008] Trial 72 finished with value: 0.19141957047388206 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.8727329170058532, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014958115304314575}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22972629414025617
Fold 2 IBS: 0.1714974106484998
Fold 3 IBS: 0.19533970259706934
Fold 4 IBS: 0.19369830153535858
Fold 5 IBS: 0.17274176927442175
[I 2024-04-19 14:44:22,622] Trial 73 finished with value: 0.19260069563912113 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.8762219604530712, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017456169974200266}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22245678083193057
Fold 2 IBS: 0.17710628298553246
Fold 3 IBS: 0.2034119116741666
Fold 4 IBS: 0.19479658460004864
Fold 5 IBS: 0.19147425591218886
[I 2024-04-19 14:44:26,972] Trial 74 finished with value: 0.19784916320077342 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 235, 'oob_score': False, 'max_samples': 0.8496697690131644, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06167959702360663}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22047766774477437
Fold 2 IBS: 0.19344669693934774
Fold 3 IBS: 0.21000391860404677
Fold 4 IBS: 0.20477338938353398
Fold 5 IBS: 0.20541683976071617
[I 2024-04-19 14:44:31,040] Trial 75 finished with value: 0.2068237024864838 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.890700122872072, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3160611948377179}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22684996172732363
Fold 2 IBS: 0.17136700641226504
Fold 3 IBS: 0.20076384707932607
Fold 4 IBS: 0.19600823288434543
Fold 5 IBS: 0.17509643852531095
[I 2024-04-19 14:44:37,056] Trial 76 finished with value: 0.19401709732571423 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.963490685502655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03671779555332485}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22243091080935176
Fold 2 IBS: 0.17909250139952151
Fold 3 IBS: 0.2011051393467259
Fold 4 IBS: 0.1920426126768079
Fold 5 IBS: 0.19402260004185645
[I 2024-04-19 14:44:40,150] Trial 77 finished with value: 0.1977387528548527 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.331919983653197, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07824582320277648}. Best is trial 49 with value: 0.19023957913930975.

Fold 1 IBS: 0.22661384896598818
Fold 2 IBS: 0.20671937958697834
Fold 3 IBS: 0.22631312111115084
Fold 4 IBS: 0.21497952798665046
Fold 5 IBS: 0.21282749449450544
[I 2024-04-19 14:44:45,803] Trial 78 finished with value: 0.21749067442905465 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9147835512625551, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.43785214928176214}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23052477127318172
Fold 2 IBS: 0.16982397129659127
Fold 3 IBS: 0.197745679074635
Fold 4 IBS: 0.19675496948041768
Fold 5 IBS: 0.1770213286573074
[I 2024-04-19 14:44:51,710] Trial 79 finished with value: 0.1943741439564266 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.9974228392350986, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013882614482266749}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21778031450040175
Fold 2 IBS: 0.18157476210786558
Fold 3 IBS: 0.20901936393117487
Fold 4 IBS: 0.19843253192688598
Fold 5 IBS: 0.20260500447363683
[I 2024-04-19 14:44:54,846] Trial 80 finished with value: 0.201882395387993 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 196, 'oob_score': False, 'max_samples': 0.8074163719785258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2343729610964786}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23020712569648552
Fold 2 IBS: 0.17016574705246248
Fold 3 IBS: 0.19437724163558126
Fold 4 IBS: 0.19048729146333454
Fold 5 IBS: 0.16923782983271543
[I 2024-04-19 14:45:01,355] Trial 81 finished with value: 0.19089504713611585 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.7784763388289013, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010595244727030426}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22633537924660144
Fold 2 IBS: 0.17245435825621444
Fold 3 IBS: 0.198261807277501
Fold 4 IBS: 0.19375808006799025
Fold 5 IBS: 0.17259241286993124
[I 2024-04-19 14:45:07,928] Trial 82 finished with value: 0.19268040754364765 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8431704918534557, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051048753251538945}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22652319655125724
Fold 2 IBS: 0.17122256301203548
Fold 3 IBS: 0.19686503258087146
Fold 4 IBS: 0.1924915525324402
Fold 5 IBS: 0.16992775902187662
[I 2024-04-19 14:45:11,935] Trial 83 finished with value: 0.1914060207396962 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 211, 'oob_score': False, 'max_samples': 0.8754608137046987, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015226300624484834}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22719481979011316
Fold 2 IBS: 0.17681042979834713
Fold 3 IBS: 0.19352861064606583
Fold 4 IBS: 0.19070454017783864
Fold 5 IBS: 0.17349666127523256
[I 2024-04-19 14:45:16,232] Trial 84 finished with value: 0.19234701233751947 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.8790183350095053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0330313828916208}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2284060883547397
Fold 2 IBS: 0.17419251077518969
Fold 3 IBS: 0.19970363198080762
Fold 4 IBS: 0.19473581568220244
Fold 5 IBS: 0.176828897729793
[I 2024-04-19 14:45:21,019] Trial 85 finished with value: 0.19477338890454649 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.7631874187375279, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01872628122372143}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22305736755182187
Fold 2 IBS: 0.17574939085892582
Fold 3 IBS: 0.19568084111601947
Fold 4 IBS: 0.19164045666660487
Fold 5 IBS: 0.1705187427582713
[I 2024-04-19 14:45:25,485] Trial 86 finished with value: 0.19132935979032867 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.74503188520459, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.049354259957534494}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2240633369122398
Fold 2 IBS: 0.17538320131641633
Fold 3 IBS: 0.19866223365506058
Fold 4 IBS: 0.19055945999140522
Fold 5 IBS: 0.17899242470900267
[I 2024-04-19 14:45:29,261] Trial 87 finished with value: 0.19353213131682495 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 188, 'oob_score': False, 'max_samples': 0.7394132698699142, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09171826513128181}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22531436049097633
Fold 2 IBS: 0.17338649398202335
Fold 3 IBS: 0.19541984829438955
Fold 4 IBS: 0.19633643985222626
Fold 5 IBS: 0.17132056753628644
[I 2024-04-19 14:45:34,303] Trial 88 finished with value: 0.19235554203118038 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7818271131584801, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04741359111187626}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.24634541122033987
Fold 2 IBS: 0.2321226179655187
Fold 3 IBS: 0.22957248320549392
Fold 4 IBS: 0.24133401177007524
Fold 5 IBS: 0.22999623321892046
[I 2024-04-19 14:45:37,310] Trial 89 finished with value: 0.23587415147606966 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.15094844814066605, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18451336087256687}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22279933131837096
Fold 2 IBS: 0.17181835390229477
Fold 3 IBS: 0.2007160874798753
Fold 4 IBS: 0.197203380481848
Fold 5 IBS: 0.17515803600889934
[I 2024-04-19 14:45:40,475] Trial 90 finished with value: 0.19353903783825768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 129, 'oob_score': False, 'max_samples': 0.7242871632922839, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06749203999049488}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22424300030428562
Fold 2 IBS: 0.17328433759407055
Fold 3 IBS: 0.19523917924376888
Fold 4 IBS: 0.19315716958653814
Fold 5 IBS: 0.1704614508554719
[I 2024-04-19 14:45:45,108] Trial 91 finished with value: 0.19127702751682701 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.8334209164391518, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014138517009539523}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22184929782482737
Fold 2 IBS: 0.17627486877830942
Fold 3 IBS: 0.1943876201108137
Fold 4 IBS: 0.19108122099131164
Fold 5 IBS: 0.17147705560864723
[I 2024-04-19 14:45:52,109] Trial 92 finished with value: 0.19101401266278187 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.6946552112995523, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03125200733960136}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2239870857063055
Fold 2 IBS: 0.17944345181206486
Fold 3 IBS: 0.1900538617099537
Fold 4 IBS: 0.19293425732594438

Fold 5 IBS: 0.16901501941163646
[I 2024-04-19 14:45:55,332] Trial 93 finished with value: 0.19108673519318098 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.8387093701884653, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030817946786640082}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22184856220737365
Fold 2 IBS: 0.17312992964385657
Fold 3 IBS: 0.1948930255496256
Fold 4 IBS: 0.1925411854591036
Fold 5 IBS: 0.1730631403095586
[I 2024-04-19 14:45:59,252] Trial 94 finished with value: 0.1910951686339036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.688472014648766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03451598429298541}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.24047052597810953
Fold 2 IBS: 0.17250441339722747
Fold 3 IBS: 0.20953833222155935
Fold 4 IBS: 0.2100206291818941
Fold 5 IBS: 0.17584248631889507
[I 2024-04-19 14:46:04,396] Trial 95 finished with value: 0.2016752774195371 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.6970192006469513, 'max_features': None, 'min_weight_fraction_leaf': 0.03192478980412634}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2258454786784926
Fold 2 IBS: 0.17622029117710752
Fold 3 IBS: 0.19704459447649766
Fold 4 IBS: 0.18859439451234322
Fold 5 IBS: 0.17741716444849034
[I 2024-04-19 14:46:11,207] Trial 96 finished with value: 0.19302438465858626 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.6860275498472574, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05374102069256326}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22481323122042657
Fold 2 IBS: 0.17216098643824315
Fold 3 IBS: 0.19306385345921517
Fold 4 IBS: 0.19583934030263228
Fold 5 IBS: 0.17882594481487218
[I 2024-04-19 14:46:14,550] Trial 97 finished with value: 0.19294067124707787 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.6513894290159268, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04184810194054517}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2281068681622065
Fold 2 IBS: 0.17408803145260857
Fold 3 IBS: 0.19824195355773988
Fold 4 IBS: 0.1904600456326597
Fold 5 IBS: 0.17922094521554732
[I 2024-04-19 14:46:20,248] Trial 98 finished with value: 0.1940235688041524 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.7342462417517636, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07703075927677872}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2259945894827042
Fold 2 IBS: 0.17396367577577646
Fold 3 IBS: 0.2055533021506421
Fold 4 IBS: 0.1955608834617829
Fold 5 IBS: 0.1805672129301506
[I 2024-04-19 14:46:23,144] Trial 99 finished with value: 0.19632793276021127 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.8324527674106177, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09813787485590943}. Best is trial 49 with value: 0.19023957913930975.


* Best trial for IBS:
 FrozenTrial(number=49, state=TrialState.COMPLETE, values=[0.19023957913930975], datetime_start=datetime.datetime(2024, 4, 19, 14, 42, 16, 898497), datetime_complete=datetime.datetime(2024, 4, 19, 14, 42, 21, 100989), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.7890788621794695, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04458702793409107}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=49, value=None)


* Best Score for IBS:
 0.19023957913930975

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.866
train_ibs:  0.19

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [58]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=10, max_leaf_nodes=14,
                     max_samples=0.8746458616251406, min_samples_leaf=2,
                     min_weight_fraction_leaf=0.030922977401692878,
                     n_estimators=113, random_state=123, warm_start=True)

test_cindex:  0.546

RandomSurvivalForest(max_depth=8, max_leaf_nodes=17,
                     max_samples=0.7890788621794695, min_samples_leaf=2,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.04458702793409107,
                     n_estimators=215, random_state=123)

test_ibs:  0.263

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [61]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:46:25,083] A new study created in memory with name: no-name-697d832d-732d-4a96-af7c-bdfd83d034ac

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7639484978540773
[I 2024-04-19 14:46:27,002] Trial 0 finished with value: 0.7623102721396274 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:30,644] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 14:46:37,978] Trial 2 finished with value: 0.7156366754220176 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7253218884120172
[I 2024-04-19 14:46:38,596] Trial 3 finished with value: 0.7402725229380251 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:41,117] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:44,317] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7381974248927039
[I 2024-04-19 14:46:45,822] Trial 6 finished with value: 0.7499745725457844 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-19 14:46:49,484] Trial 7 finished with value: 0.744770291905024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7296137339055794
[I 2024-04-19 14:46:49,646] Trial 8 finished with value: 0.7197332454598995 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 14:46:58,716] Trial 9 finished with value: 0.7117523204127156 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:01,800] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-19 14:47:03,173] Trial 11 finished with value: 0.7295841326588206 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8111587982832618
[I 2024-04-19 14:47:05,451] Trial 12 finished with value: 0.7867972827001483 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-19 14:47:07,168] Trial 13 finished with value: 0.7316705235163293 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-19 14:47:09,239] Trial 14 finished with value: 0.7390987799796523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-19 14:47:10,445] Trial 15 finished with value: 0.7406634812581807 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7867972827001483.

Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6759656652360515
[I 2024-04-19 14:47:12,573] Trial 16 finished with value: 0.7032137338705444 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 14:47:14,138] Trial 17 finished with value: 0.731554986493769 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:16,692] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 14:47:18,414] Trial 19 finished with value: 0.7358463917100135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8361702127659575
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6630901287553648
[I 2024-04-19 14:47:18,656] Trial 20 finished with value: 0.7074965456605569 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7381974248927039
[I 2024-04-19 14:47:20,460] Trial 21 finished with value: 0.7550267044437244 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.759656652360515
[I 2024-04-19 14:47:22,336] Trial 22 finished with value: 0.7661315662080361 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8197424892703863
[I 2024-04-19 14:47:24,327] Trial 23 finished with value: 0.7937218312264874 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7424892703862661
[I 2024-04-19 14:47:26,378] Trial 24 finished with value: 0.7580764020718593 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8068669527896996
[I 2024-04-19 14:47:28,273] Trial 25 finished with value: 0.762803163214613 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 14:47:37,856] Trial 26 finished with value: 0.7223549195144154 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.703862660944206
[I 2024-04-19 14:47:40,441] Trial 27 finished with value: 0.7342711010948667 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7112403100775194
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 14:47:41,935] Trial 28 finished with value: 0.7193098171027112 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 14:47:43,136] Trial 29 finished with value: 0.7198566127686613 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.759656652360515
[I 2024-04-19 14:47:44,186] Trial 30 finished with value: 0.7622850722651587 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.7937218312264874.

Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-19 14:47:46,174] Trial 31 finished with value: 0.7651208885111453 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6357896182918609, 'min_weight_fraction_leaf': 0.043457520259011145}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7553648068669528
[I 2024-04-19 14:47:48,370] Trial 32 finished with value: 0.7493192073790584 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4847410905891233, 'min_weight_fraction_leaf': 0.054624644214656966}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.703862660944206
[I 2024-04-19 14:47:50,303] Trial 33 finished with value: 0.7351654028257627 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.527493679418052, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8111587982832618
[I 2024-04-19 14:47:52,426] Trial 34 finished with value: 0.760702458675475 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9202590430146967, 'min_weight_fraction_leaf': 0.07023282430953717}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7939914163090128
[I 2024-04-19 14:47:55,455] Trial 35 finished with value: 0.7624993862330411 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6140705076527802, 'min_weight_fraction_leaf': 0.02925664606041241}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6995708154506438
[I 2024-04-19 14:48:00,587] Trial 36 finished with value: 0.719921700077874 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 349, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6785531388726883, 'min_weight_fraction_leaf': 0.1272251175690979}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:48:02,602] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8050041507306814, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 14:48:04,870] Trial 38 finished with value: 0.7247202242856303 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 435, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.05649565215079118}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-19 14:48:15,671] Trial 39 finished with value: 0.7213553719700059 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 472, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5401322211198275, 'min_weight_fraction_leaf': 0.09113105544483305}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8197424892703863
[I 2024-04-19 14:48:17,085] Trial 40 finished with value: 0.7770575045494358 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7399942977302993, 'min_weight_fraction_leaf': 0.025013264992292644}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8497854077253219
[I 2024-04-19 14:48:18,241] Trial 41 finished with value: 0.7896617263093931 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7332367119565565, 'min_weight_fraction_leaf': 0.0016561031617871522}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8326180257510729
[I 2024-04-19 14:48:18,982] Trial 42 finished with value: 0.780595334917785 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 155, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7291601013114538, 'min_weight_fraction_leaf': 0.0015116719780719767}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8369098712446352
[I 2024-04-19 14:48:20,074] Trial 43 finished with value: 0.7901642333193999 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7528934931474498, 'min_weight_fraction_leaf': 0.007759295188642418}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8454935622317596
[I 2024-04-19 14:48:20,612] Trial 44 finished with value: 0.7872592837754979 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8327721232082076, 'min_weight_fraction_leaf': 0.01305046995423322}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8369098712446352
[I 2024-04-19 14:48:21,516] Trial 45 finished with value: 0.777513445436739 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 157, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8255054025331079, 'min_weight_fraction_leaf': 0.0031249321027524285}. Best is trial 23 with value: 0.7937218312264874.

Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8326180257510729
[I 2024-04-19 14:48:22,454] Trial 46 finished with value: 0.7917141970732431 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9257094805962044, 'min_weight_fraction_leaf': 0.022307192777154376}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:48:25,547] Trial 47 finished with value: 0.7453719568208577 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 196, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9265198018232372, 'min_weight_fraction_leaf': 0.05973916326993964}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7167381974248928
[I 2024-04-19 14:48:26,784] Trial 48 finished with value: 0.7193712893481361 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 121, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7632274813615122, 'min_weight_fraction_leaf': 0.3078000969326991}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.8148936170212766
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6802575107296137
[I 2024-04-19 14:48:27,862] Trial 49 finished with value: 0.7112005967373427 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 221, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9454880021924575, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8154506437768241
[I 2024-04-19 14:48:28,647] Trial 50 finished with value: 0.763269836859631 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 117, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.843804589889048, 'min_weight_fraction_leaf': 0.0873347394612367}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8497854077253219
[I 2024-04-19 14:48:29,577] Trial 51 finished with value: 0.7911199644131695 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.025973798263736272}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8326180257510729
[I 2024-04-19 14:48:30,546] Trial 52 finished with value: 0.7867595541571949 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7903103587545204, 'min_weight_fraction_leaf': 0.023179220994950622}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8240343347639485
[I 2024-04-19 14:48:31,358] Trial 53 finished with value: 0.7789155204597524 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 78, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.01957247755969179}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-19 14:48:32,770] Trial 54 finished with value: 0.7748590141721845 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8980357949184589, 'min_weight_fraction_leaf': 0.04833675638502302}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8068669527896996
[I 2024-04-19 14:48:33,909] Trial 55 finished with value: 0.7810021652909311 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 177, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8672614385579406, 'min_weight_fraction_leaf': 0.07284912883734934}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8326180257510729
[I 2024-04-19 14:48:34,685] Trial 56 finished with value: 0.7813968466847471 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 141, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8280080010077513, 'min_weight_fraction_leaf': 0.014205042834379285}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7081545064377682
[I 2024-04-19 14:48:36,114] Trial 57 finished with value: 0.7352517352068838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 247, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7559818229866901, 'min_weight_fraction_leaf': 0.12105610192383184}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-19 14:48:39,993] Trial 58 finished with value: 0.7495185198345575 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 223, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6819194445137657, 'min_weight_fraction_leaf': 0.0412960148860697}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8454935622317596
[I 2024-04-19 14:48:42,586] Trial 59 finished with value: 0.8084662710816808 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 271, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.964838395481847, 'min_weight_fraction_leaf': 4.407900941855603e-05}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 14:48:45,003] Trial 60 finished with value: 0.7300297987713386 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9553308503405183, 'min_weight_fraction_leaf': 0.2583710069782479}. Best is trial 59 with value: 0.8084662710816808.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8454935622317596
[I 2024-04-19 14:48:46,869] Trial 61 finished with value: 0.8006710951960759 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 191, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.99214746221766, 'min_weight_fraction_leaf': 0.00034340752043091755}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8326180257510729
[I 2024-04-19 14:48:48,791] Trial 62 finished with value: 0.7829099031334593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 194, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.995392611213117, 'min_weight_fraction_leaf': 0.03766384718061227}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8540772532188842
[I 2024-04-19 14:48:50,752] Trial 63 finished with value: 0.8166801836932367 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 231, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9159857443892336, 'min_weight_fraction_leaf': 0.000272750956431346}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8369098712446352
[I 2024-04-19 14:48:52,448] Trial 64 finished with value: 0.800657051922378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 181, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9104584386149728, 'min_weight_fraction_leaf': 0.05591333445734158}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8283261802575107
[I 2024-04-19 14:48:54,589] Trial 65 finished with value: 0.7934970372032099 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9648986760030055, 'min_weight_fraction_leaf': 0.06680538576359879}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8240343347639485
[I 2024-04-19 14:48:56,370] Trial 66 finished with value: 0.7878220023993864 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 203, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9095982739365324, 'min_weight_fraction_leaf': 0.06752219873139698}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7896995708154506
[I 2024-04-19 14:48:58,727] Trial 67 finished with value: 0.7729438440738962 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 271, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8746455577810428, 'min_weight_fraction_leaf': 0.09750609016881821}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-19 14:49:00,580] Trial 68 finished with value: 0.7972745425406186 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 240, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.968180725622439, 'min_weight_fraction_leaf': 0.054110870458248334}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7296137339055794
[I 2024-04-19 14:49:02,647] Trial 69 finished with value: 0.7490725417029068 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 232, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.995297083745019, 'min_weight_fraction_leaf': 0.16115376582527763}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7682403433476395
[I 2024-04-19 14:49:08,669] Trial 70 finished with value: 0.7431377642689725 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9769199467223223, 'min_weight_fraction_leaf': 0.055426720208080725}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8283261802575107
[I 2024-04-19 14:49:11,084] Trial 71 finished with value: 0.8004580691916237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9375782206126794, 'min_weight_fraction_leaf': 0.04507778368190728}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8240343347639485
[I 2024-04-19 14:49:13,767] Trial 72 finished with value: 0.7916358642120349 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9676798282975951, 'min_weight_fraction_leaf': 0.0787773084868472}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7424892703862661
[I 2024-04-19 14:49:16,140] Trial 73 finished with value: 0.7571821003409633 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8950935256166086, 'min_weight_fraction_leaf': 0.11229900026623069}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-19 14:49:19,397] Trial 74 finished with value: 0.795695654567296 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9359651513439894, 'min_weight_fraction_leaf': 0.05058223539315274}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8240343347639485
[I 2024-04-19 14:49:21,862] Trial 75 finished with value: 0.7939103516074585 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9343716260288816, 'min_weight_fraction_leaf': 0.043108638690303853}. Best is trial 63 with value: 0.8166801836932367.

Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-19 14:49:24,369] Trial 76 finished with value: 0.7784671388150444 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 286, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9321739716438541, 'min_weight_fraction_leaf': 0.03655310676155976}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-19 14:49:26,907] Trial 77 finished with value: 0.7875133994130215 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 254, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8655648399730119, 'min_weight_fraction_leaf': 0.04756050968696869}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7982832618025751
[I 2024-04-19 14:49:29,941] Trial 78 finished with value: 0.7817849347662374 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 269, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9999098672482281, 'min_weight_fraction_leaf': 0.0863331818418738}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-19 14:49:33,289] Trial 79 finished with value: 0.7456694044778016 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.034493408415334006}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7339055793991416
[I 2024-04-19 14:49:35,948] Trial 80 finished with value: 0.753005935291058 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9098917820806076, 'min_weight_fraction_leaf': 0.13389187501653388}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8283261802575107
[I 2024-04-19 14:49:37,727] Trial 81 finished with value: 0.8051772459148425 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9424018134336887, 'min_weight_fraction_leaf': 0.05108896602934009}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8497854077253219
[I 2024-04-19 14:49:40,982] Trial 82 finished with value: 0.809469091408405 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 282, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9410740612472716, 'min_weight_fraction_leaf': 0.012322578348389443}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8540772532188842
[I 2024-04-19 14:49:44,309] Trial 83 finished with value: 0.8167597780695852 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 285, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8871550861115998, 'min_weight_fraction_leaf': 0.013985838803987693}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-19 14:49:45,709] Trial 84 finished with value: 0.812474687015057 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 138, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8841264487793694, 'min_weight_fraction_leaf': 0.016386251952087417}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8540772532188842
[I 2024-04-19 14:49:47,057] Trial 85 finished with value: 0.8158908196342545 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 141, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.888479352560009, 'min_weight_fraction_leaf': 0.012716341560856033}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6972111553784861
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8841201716738197
[I 2024-04-19 14:49:49,546] Trial 86 finished with value: 0.8257675162186733 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8608986608214496, 'min_weight_fraction_leaf': 0.013300177959391254}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7081545064377682
[I 2024-04-19 14:49:51,325] Trial 87 finished with value: 0.7417472944772566 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 91, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8607992629190876, 'min_weight_fraction_leaf': 0.01139343678306486}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.8025751072961373
[I 2024-04-19 14:49:53,731] Trial 88 finished with value: 0.7421126194553279 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 84, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8099246282391572, 'min_weight_fraction_leaf': 0.013604529607415802}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.701195219123506
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8626609442060086
[I 2024-04-19 14:49:55,533] Trial 89 finished with value: 0.8246591973761161 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 139, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8911664954143093, 'min_weight_fraction_leaf': 0.0010890713950365803}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-19 14:49:57,777] Trial 90 finished with value: 0.8093017497006703 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8846592522748477, 'min_weight_fraction_leaf': 0.027028995364682774}. Best is trial 86 with value: 0.8257675162186733.

Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8283261802575107
[I 2024-04-19 14:49:59,282] Trial 91 finished with value: 0.8083385863511406 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 133, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8818337195376095, 'min_weight_fraction_leaf': 0.029196432033481958}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7296137339055794
[I 2024-04-19 14:50:00,954] Trial 92 finished with value: 0.7552483413861439 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 135, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.887423031596968, 'min_weight_fraction_leaf': 0.025844049706309193}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8283261802575107
[I 2024-04-19 14:50:01,975] Trial 93 finished with value: 0.8059160832380525 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 66, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8488078188965495, 'min_weight_fraction_leaf': 0.013011220287553072}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-19 14:50:03,294] Trial 94 finished with value: 0.8092765498262015 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 111, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7853435226199493, 'min_weight_fraction_leaf': 0.02738269110214168}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8755364806866953
[I 2024-04-19 14:50:04,567] Trial 95 finished with value: 0.826448505102924 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8161032428574773, 'min_weight_fraction_leaf': 0.001106761767719347}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8154506437768241
[I 2024-04-19 14:50:05,843] Trial 96 finished with value: 0.7842940671166678 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 113, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7755580189933128, 'min_weight_fraction_leaf': 0.015997371825892767}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.759656652360515
[I 2024-04-19 14:50:06,438] Trial 97 finished with value: 0.7672112148047836 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 39, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8147988676493763, 'min_weight_fraction_leaf': 0.0308224860074267}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7124463519313304
[I 2024-04-19 14:50:07,684] Trial 98 finished with value: 0.7385526112254805 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 97, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7875371195797898, 'min_weight_fraction_leaf': 0.20718461376465755}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.720532319391635

[I 2024-04-19 14:50:09,160] A new study created in memory with name: no-name-1daa13b4-4baf-4d39-9c91-eff191a01a8c

Fold 5 C-index: 0.6459227467811158
[I 2024-04-19 14:50:09,055] Trial 99 finished with value: 0.6919788612158724 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 126, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8515495175736911, 'min_weight_fraction_leaf': 0.4077588868802398}. Best is trial 95 with value: 0.826448505102924.


* Best trial for C-index:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.826448505102924], datetime_start=datetime.datetime(2024, 4, 19, 14, 50, 3, 335770), datetime_complete=datetime.datetime(2024, 4, 19, 14, 50, 4, 566496), params={'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8161032428574773, 'min_weight_fraction_leaf': 0.001106761767719347}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=95, value=None)


* Best Score for C-index:
 0.826448505102924

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2216883708385238
Fold 2 IBS: 0.20116513124707355
Fold 3 IBS: 0.18963496960925966
Fold 4 IBS: 0.20548033840998792
Fold 5 IBS: 0.18750823813035528
[I 2024-04-19 14:50:15,219] Trial 0 finished with value: 0.20109540964704004 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-19 14:50:24,148] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23328845550406502
Fold 2 IBS: 0.21810066709735482
Fold 3 IBS: 0.2100774317752478
Fold 4 IBS: 0.22329553132649185
Fold 5 IBS: 0.2114469499436477
[I 2024-04-19 14:50:32,623] Trial 2 finished with value: 0.21924180712936142 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.2351174850348692
Fold 2 IBS: 0.219828345872527
Fold 3 IBS: 0.21173255582990505
Fold 4 IBS: 0.22584022524964367
Fold 5 IBS: 0.21387778959798523
[I 2024-04-19 14:50:35,648] Trial 3 finished with value: 0.22127928031698602 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-19 14:50:42,021] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-19 14:50:44,777] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.22285591564464766
Fold 2 IBS: 0.20324049199979516
Fold 3 IBS: 0.19028540014692436
Fold 4 IBS: 0.2090397510159576
Fold 5 IBS: 0.1897288358797867
[I 2024-04-19 14:50:52,297] Trial 6 finished with value: 0.20303007893742228 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.22779745048944502
Fold 2 IBS: 0.21116263533467225
Fold 3 IBS: 0.20158439716136908
Fold 4 IBS: 0.21503406407606104
Fold 5 IBS: 0.2009534751387103
[I 2024-04-19 14:50:57,356] Trial 7 finished with value: 0.21130640444005158 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.2336849435018476
Fold 2 IBS: 0.21699322646377178
Fold 3 IBS: 0.20944474413453934
Fold 4 IBS: 0.22497867659365728
Fold 5 IBS: 0.21355042601743562
[I 2024-04-19 14:50:58,223] Trial 8 finished with value: 0.21973040334225033 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23735614317408008
Fold 2 IBS: 0.22250970142913065
Fold 3 IBS: 0.21632908896013436
Fold 4 IBS: 0.23142974084173232
Fold 5 IBS: 0.21892814505251118
[I 2024-04-19 14:51:06,734] Trial 9 finished with value: 0.22531056389151768 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-19 14:51:13,482] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23022250449663892
Fold 2 IBS: 0.20809523912377517
Fold 3 IBS: 0.19803303843460215
Fold 4 IBS: 0.21550808264334878
Fold 5 IBS: 0.20218737765773626
[I 2024-04-19 14:51:20,325] Trial 11 finished with value: 0.21080924847122023 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.21613989052002444
Fold 2 IBS: 0.1966321312406504
Fold 3 IBS: 0.18848837574478716
Fold 4 IBS: 0.20253748024407425
Fold 5 IBS: 0.18190788145678702
[I 2024-04-19 14:51:32,119] Trial 12 finished with value: 0.19714115184126466 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22624638824497345
Fold 2 IBS: 0.208132783074928
Fold 3 IBS: 0.1957266434056336
Fold 4 IBS: 0.21533929207751132
Fold 5 IBS: 0.19842738811030086
[I 2024-04-19 14:51:41,515] Trial 13 finished with value: 0.20877449898266948 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22734034749345805
Fold 2 IBS: 0.20875433795400827
Fold 3 IBS: 0.19554481462030096
Fold 4 IBS: 0.217258375641282
Fold 5 IBS: 0.19872227743792803
[I 2024-04-19 14:51:50,628] Trial 14 finished with value: 0.20952403062939545 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.19714115184126466.

Fold 1 IBS: 0.2285622101008634
Fold 2 IBS: 0.20843529070864095
Fold 3 IBS: 0.19501846306370746
Fold 4 IBS: 0.21559689896401366
Fold 5 IBS: 0.19971924614220493
[I 2024-04-19 14:51:56,690] Trial 15 finished with value: 0.20946642179588607 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.2404239471321595
Fold 2 IBS: 0.22515713522164824
Fold 3 IBS: 0.21747041451130297
Fold 4 IBS: 0.23590557558587374
Fold 5 IBS: 0.2189832067887446
[I 2024-04-19 14:52:09,066] Trial 16 finished with value: 0.2275880558479458 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.2265766966093104
Fold 2 IBS: 0.21304461762010127
Fold 3 IBS: 0.19686726071348115
Fold 4 IBS: 0.21529218618416335
Fold 5 IBS: 0.19893026398098457
[I 2024-04-19 14:52:15,204] Trial 17 finished with value: 0.21014220502160813 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-19 14:52:17,880] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.226522202989843
Fold 2 IBS: 0.20703960609508038
Fold 3 IBS: 0.1942721352571641
Fold 4 IBS: 0.21479270879307474
Fold 5 IBS: 0.19770773184290516
[I 2024-04-19 14:52:24,033] Trial 19 finished with value: 0.2080668769956135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22860530313751873
Fold 2 IBS: 0.2197286802115928
Fold 3 IBS: 0.20141531822386521
Fold 4 IBS: 0.23000502351334556
Fold 5 IBS: 0.20897153269462923
[I 2024-04-19 14:52:24,381] Trial 20 finished with value: 0.2177451715561903 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22277384041815695
Fold 2 IBS: 0.20334257879097034
Fold 3 IBS: 0.19030809415067831
Fold 4 IBS: 0.2080413933204737
Fold 5 IBS: 0.18916272546530452
[I 2024-04-19 14:52:31,895] Trial 21 finished with value: 0.20272572642911676 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22001622035995086
Fold 2 IBS: 0.20143159104176697
Fold 3 IBS: 0.18930871547839062
Fold 4 IBS: 0.20556188928342486
Fold 5 IBS: 0.18618950630512082
[I 2024-04-19 14:52:39,402] Trial 22 finished with value: 0.20050158449373084 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.21613582256339794
Fold 2 IBS: 0.19387991553904665
Fold 3 IBS: 0.18688212496978923
Fold 4 IBS: 0.19909456369999257
Fold 5 IBS: 0.1769669671210479
[I 2024-04-19 14:52:47,697] Trial 23 finished with value: 0.19459187877865486 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22098376153714128
Fold 2 IBS: 0.2017790967079455
Fold 3 IBS: 0.18977869471880326
Fold 4 IBS: 0.20562300123773503
Fold 5 IBS: 0.1895750781822595
[I 2024-04-19 14:52:56,346] Trial 24 finished with value: 0.2015479264767769 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2283056563231173
Fold 2 IBS: 0.21007958258826712
Fold 3 IBS: 0.20299281229435043
Fold 4 IBS: 0.21313667345754783
Fold 5 IBS: 0.20072093838312854
[I 2024-04-19 14:53:03,116] Trial 25 finished with value: 0.21104713260928226 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22547573656030792
Fold 2 IBS: 0.2067128508655798
Fold 3 IBS: 0.1939155139277123
Fold 4 IBS: 0.21316063898492277
Fold 5 IBS: 0.1966361463030427
[I 2024-04-19 14:53:13,633] Trial 26 finished with value: 0.20718017732831312 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22651286012786861
Fold 2 IBS: 0.2071828931412121
Fold 3 IBS: 0.19383543230944772
Fold 4 IBS: 0.21404492643798378
Fold 5 IBS: 0.1965677671793665
[I 2024-04-19 14:53:22,035] Trial 27 finished with value: 0.20762877583917572 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2296162488525048
Fold 2 IBS: 0.21553963633321688
Fold 3 IBS: 0.19785601697252495
Fold 4 IBS: 0.2188768233602731
Fold 5 IBS: 0.20093600143211168
[I 2024-04-19 14:53:27,548] Trial 28 finished with value: 0.2125649453901263 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2320037319505613
Fold 2 IBS: 0.21529282635362382
Fold 3 IBS: 0.20073796574461872
Fold 4 IBS: 0.22374477453593242
Fold 5 IBS: 0.20919202181500016
[I 2024-04-19 14:53:31,918] Trial 29 finished with value: 0.2161942640799473 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.19459187877865486.

Fold 1 IBS: 0.2233579319393271
Fold 2 IBS: 0.20096408163499427
Fold 3 IBS: 0.19049881866793233
Fold 4 IBS: 0.20774755146340546
Fold 5 IBS: 0.19123419554925844
[I 2024-04-19 14:53:39,189] Trial 30 finished with value: 0.20276051585098354 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2179837541713329
Fold 2 IBS: 0.19996868148399857
Fold 3 IBS: 0.18950194352113112
Fold 4 IBS: 0.20402491486791338
Fold 5 IBS: 0.18472430994108335
[I 2024-04-19 14:53:47,229] Trial 31 finished with value: 0.19924072079709187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.923666057752446, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2165115875368992
Fold 2 IBS: 0.19730089666900102
Fold 3 IBS: 0.18932681429498213
Fold 4 IBS: 0.2026285347669489
Fold 5 IBS: 0.18129650151368074
[I 2024-04-19 14:53:56,316] Trial 32 finished with value: 0.1974128669563024 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.939007534925735, 'min_weight_fraction_leaf': 0.056106269226335825}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22215223881932283
Fold 2 IBS: 0.20404673534195444
Fold 3 IBS: 0.19059256536590438
Fold 4 IBS: 0.20867030880038456
Fold 5 IBS: 0.1902323613350749
[I 2024-04-19 14:54:03,219] Trial 33 finished with value: 0.20313884193252824 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9138848353483187, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.21571300333932517
Fold 2 IBS: 0.1845951559627474
Fold 3 IBS: 0.18880163665481287
Fold 4 IBS: 0.1949110082696481
Fold 5 IBS: 0.17373428623842993
[I 2024-04-19 14:54:12,925] Trial 34 finished with value: 0.1915510180929927 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.06204686171902169}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21454541287943435
Fold 2 IBS: 0.18693346330112653
Fold 3 IBS: 0.19102421355153448
Fold 4 IBS: 0.19551337596236062
Fold 5 IBS: 0.1761961240257905
[I 2024-04-19 14:54:25,562] Trial 35 finished with value: 0.1928425179440493 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8327847526324277, 'min_weight_fraction_leaf': 0.055940476394666754}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21421473813611983
Fold 2 IBS: 0.18781798129221267
Fold 3 IBS: 0.19253146542248586
Fold 4 IBS: 0.19760463791446536
Fold 5 IBS: 0.17599130386074804
[I 2024-04-19 14:54:36,090] Trial 36 finished with value: 0.19363202532520635 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827098326399153, 'min_weight_fraction_leaf': 0.06897665469252873}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.220989467263724
Fold 2 IBS: 0.19890804921057023
Fold 3 IBS: 0.1955995866337726
Fold 4 IBS: 0.20347488198691915
Fold 5 IBS: 0.18652218714210275
[I 2024-04-19 14:54:47,034] Trial 37 finished with value: 0.20109883444741775 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8333567609683693, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21403271727225354
Fold 2 IBS: 0.1880480951062635
Fold 3 IBS: 0.1927275263843754
Fold 4 IBS: 0.19690061622051883
Fold 5 IBS: 0.17593442460775408
[I 2024-04-19 14:54:55,424] Trial 38 finished with value: 0.19352867591823306 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 345, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8095186934535692, 'min_weight_fraction_leaf': 0.06981260769852976}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.228306499716191
Fold 2 IBS: 0.211502363047124
Fold 3 IBS: 0.19915744044493738
Fold 4 IBS: 0.21580761059677792
Fold 5 IBS: 0.19923517798027957
[I 2024-04-19 14:55:03,828] Trial 39 finished with value: 0.21080181835706197 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8235915436715224, 'min_weight_fraction_leaf': 0.2150204152808745}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22009212142996487
Fold 2 IBS: 0.20235485246883128
Fold 3 IBS: 0.19662068942862213
Fold 4 IBS: 0.20713783696954896
Fold 5 IBS: 0.18874034333226591
[I 2024-04-19 14:55:07,425] Trial 40 finished with value: 0.20298916872584663 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 166, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7763291518258434, 'min_weight_fraction_leaf': 0.1415885205487063}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21512726209197802
Fold 2 IBS: 0.19166650395727697
Fold 3 IBS: 0.19078575336790274
Fold 4 IBS: 0.19733338482496118
Fold 5 IBS: 0.1785081121582588
[I 2024-04-19 14:55:19,368] Trial 41 finished with value: 0.19468420328007555 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 470, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7318083142370735, 'min_weight_fraction_leaf': 0.06567312882813131}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21532149949188067
Fold 2 IBS: 0.1847817766100537
Fold 3 IBS: 0.18879463768311291
Fold 4 IBS: 0.19584692384132116
Fold 5 IBS: 0.17539535562149766
[I 2024-04-19 14:55:29,766] Trial 42 finished with value: 0.19202803864957324 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 443, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0507620305497474}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21471296520718855
Fold 2 IBS: 0.19373402376691015
Fold 3 IBS: 0.1935782510317697
Fold 4 IBS: 0.19816815937172588
Fold 5 IBS: 0.18130190427253323
[I 2024-04-19 14:55:38,885] Trial 43 finished with value: 0.1962990607300255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8055193729946044, 'min_weight_fraction_leaf': 0.08265746982147082}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22368717006762112
Fold 2 IBS: 0.20588683903754684
Fold 3 IBS: 0.19891768749780012
Fold 4 IBS: 0.20962858279474328
Fold 5 IBS: 0.1937212074562581
[I 2024-04-19 14:55:45,648] Trial 44 finished with value: 0.20636829737079393 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 292, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7663562356315471, 'min_weight_fraction_leaf': 0.16789080732305503}. Best is trial 34 with value: 0.1915510180929927.

Fold 1 IBS: 0.22018361682359297
Fold 2 IBS: 0.19767576801393197
Fold 3 IBS: 0.19421270363305465
Fold 4 IBS: 0.20406059613721392
Fold 5 IBS: 0.1854331539519078
[I 2024-04-19 14:55:56,445] Trial 45 finished with value: 0.20031316771194024 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8420791678401572, 'min_weight_fraction_leaf': 0.1114478053387663}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22677495195617972
Fold 2 IBS: 0.20938982706068335
Fold 3 IBS: 0.20301008325030304
Fold 4 IBS: 0.21538736174154596
Fold 5 IBS: 0.2016448459853074
[I 2024-04-19 14:56:06,190] Trial 46 finished with value: 0.21124141399880392 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9457056327934814, 'min_weight_fraction_leaf': 0.062092086072191535}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22930830715400474
Fold 2 IBS: 0.21438051208781905
Fold 3 IBS: 0.20096996720018
Fold 4 IBS: 0.21969610541253728
Fold 5 IBS: 0.20049850908169184
[I 2024-04-19 14:56:13,853] Trial 47 finished with value: 0.21297068018724657 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8736971337878316, 'min_weight_fraction_leaf': 0.026438797227417946}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.213913284691646
Fold 2 IBS: 0.19365644684493624
Fold 3 IBS: 0.19264144608983128
Fold 4 IBS: 0.1978352759197991
Fold 5 IBS: 0.1792186928752932
[I 2024-04-19 14:56:24,026] Trial 48 finished with value: 0.19545302928430117 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7979948724878182, 'min_weight_fraction_leaf': 0.08705758256253036}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.23833976091790518
Fold 2 IBS: 0.21548114767509935
Fold 3 IBS: 0.2019224001063648
Fold 4 IBS: 0.22951033126413029
Fold 5 IBS: 0.2066617134943696
[I 2024-04-19 14:56:31,399] Trial 49 finished with value: 0.21838307069157384 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 332, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.944869727275161, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2248852208588708
Fold 2 IBS: 0.2086945344469891
Fold 3 IBS: 0.19533980848254817
Fold 4 IBS: 0.2116409132896753
Fold 5 IBS: 0.19616008958660672
[I 2024-04-19 14:56:42,985] Trial 50 finished with value: 0.20734411333293803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 482, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2139844395487544
Fold 2 IBS: 0.18914728968054922
Fold 3 IBS: 0.18993424334874043
Fold 4 IBS: 0.19861945136516718
Fold 5 IBS: 0.17532292501761673
[I 2024-04-19 14:56:53,432] Trial 51 finished with value: 0.19340166979216558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 448, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6952532733159762, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21359431074388344
Fold 2 IBS: 0.18845827623129896
Fold 3 IBS: 0.18920811875796045
Fold 4 IBS: 0.19741430133274535
Fold 5 IBS: 0.17472384859961296
[I 2024-04-19 14:57:03,374] Trial 52 finished with value: 0.19267977113310025 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895352885746311, 'min_weight_fraction_leaf': 0.05243800385790333}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2116998447565635
Fold 2 IBS: 0.18628912985639196
Fold 3 IBS: 0.18838500488320775
Fold 4 IBS: 0.19561139573019
Fold 5 IBS: 0.17448408339296287
[I 2024-04-19 14:57:14,357] Trial 53 finished with value: 0.1912938917238632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7530104333187604, 'min_weight_fraction_leaf': 0.04825576822079568}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.21465186773648143
Fold 2 IBS: 0.18855005015058893
Fold 3 IBS: 0.18511049876087637
Fold 4 IBS: 0.19705279145523985
Fold 5 IBS: 0.17274909831863947
[I 2024-04-19 14:57:23,404] Trial 54 finished with value: 0.1916228612843652 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 380, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6854242983573284, 'min_weight_fraction_leaf': 0.016297809364208576}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22796071086903075
Fold 2 IBS: 0.20969832304654898
Fold 3 IBS: 0.20267836033689163
Fold 4 IBS: 0.21278935271450855
Fold 5 IBS: 0.20040468065389563
[I 2024-04-19 14:57:32,128] Trial 55 finished with value: 0.2107062855241751 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6628876016595922, 'min_weight_fraction_leaf': 0.01845633424767698}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.24625934471253716
Fold 2 IBS: 0.23214786228629494
Fold 3 IBS: 0.2295871449534552
Fold 4 IBS: 0.24147697769672616
Fold 5 IBS: 0.23025545386023222
[I 2024-04-19 14:57:41,686] Trial 56 finished with value: 0.23594535670184916 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 425, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6032533491002975, 'min_weight_fraction_leaf': 0.3230607190970375}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22111769895311692
Fold 2 IBS: 0.204017488716264
Fold 3 IBS: 0.19621805096093797
Fold 4 IBS: 0.20670229645207078
Fold 5 IBS: 0.1917979613090219
[I 2024-04-19 14:57:52,545] Trial 57 finished with value: 0.20397069927828232 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 485, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7531615546706312, 'min_weight_fraction_leaf': 0.005684521692916746}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22003274498373035
Fold 2 IBS: 0.1998660068050171
Fold 3 IBS: 0.1881698580726066
Fold 4 IBS: 0.20239036180242276
Fold 5 IBS: 0.18399424930109848
[I 2024-04-19 14:58:01,900] Trial 58 finished with value: 0.19889064419297506 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5394996653270911, 'min_weight_fraction_leaf': 0.023602592097570048}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.21789189671655823
Fold 2 IBS: 0.1830618664362058
Fold 3 IBS: 0.192172012950134
Fold 4 IBS: 0.1957675158574896
Fold 5 IBS: 0.16932510927863137
[I 2024-04-19 14:58:13,729] Trial 59 finished with value: 0.19164368024780382 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8661967641372095, 'min_weight_fraction_leaf': 0.039584340366555525}. Best is trial 53 with value: 0.1912938917238632.

Fold 1 IBS: 0.21476513837056027
Fold 2 IBS: 0.18143050987640613
Fold 3 IBS: 0.1908356407571883
Fold 4 IBS: 0.19427180424062881
Fold 5 IBS: 0.16683442835564766
[I 2024-04-19 14:58:24,012] Trial 60 finished with value: 0.18962750432008624 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 439, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8952499671372233, 'min_weight_fraction_leaf': 0.036398817545426995}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21627361369698
Fold 2 IBS: 0.1817225137067132
Fold 3 IBS: 0.19073393689024337
Fold 4 IBS: 0.19494098781318964
Fold 5 IBS: 0.16750297353174665
[I 2024-04-19 14:58:36,491] Trial 61 finished with value: 0.19023480512777455 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 438, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8757721856898264, 'min_weight_fraction_leaf': 0.04046785921890601}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21569547676030276
Fold 2 IBS: 0.19406435056789098
Fold 3 IBS: 0.18599781327998668
Fold 4 IBS: 0.19890833105526054
Fold 5 IBS: 0.17390689345537047
[I 2024-04-19 14:58:45,723] Trial 62 finished with value: 0.19371457302376227 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 422, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9066387670860593, 'min_weight_fraction_leaf': 0.03189756237329784}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21402139447730326
Fold 2 IBS: 0.18083663656728602
Fold 3 IBS: 0.18753380129692818
Fold 4 IBS: 0.19255745305291946
Fold 5 IBS: 0.1667002799097155
[I 2024-04-19 14:58:55,050] Trial 63 finished with value: 0.1883299130608305 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002786019075411844}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2139897789072574
Fold 2 IBS: 0.18091332402839688
Fold 3 IBS: 0.1877363493532483
Fold 4 IBS: 0.1926457442603295
Fold 5 IBS: 0.16686510313910077
[I 2024-04-19 14:59:03,940] Trial 64 finished with value: 0.18843005993766654 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 370, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.002799383925114314}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21356453199756695
Fold 2 IBS: 0.18414337595624433
Fold 3 IBS: 0.19135848396732294
Fold 4 IBS: 0.19567506298543985
Fold 5 IBS: 0.16902410400423407
[I 2024-04-19 14:59:12,316] Trial 65 finished with value: 0.19075311178216164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996741200655364, 'min_weight_fraction_leaf': 0.013343672274008771}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.24654787550564836
Fold 2 IBS: 0.23215877749004982
Fold 3 IBS: 0.22951426045636053
Fold 4 IBS: 0.2415490288777898
Fold 5 IBS: 0.23029214299076572
[I 2024-04-19 14:59:19,980] Trial 66 finished with value: 0.23601241706412285 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2266323511377712
Fold 2 IBS: 0.2071535974555395
Fold 3 IBS: 0.20048051366340186
Fold 4 IBS: 0.21211123932933376
Fold 5 IBS: 0.197924092034569
[I 2024-04-19 14:59:29,051] Trial 67 finished with value: 0.20886035872412304 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 363, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8902348249567581, 'min_weight_fraction_leaf': 0.0005656859239113344}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21760444020822703
Fold 2 IBS: 0.19984684424100796
Fold 3 IBS: 0.1923024665200439
Fold 4 IBS: 0.2028177913477314
Fold 5 IBS: 0.18410276014280125
[I 2024-04-19 14:59:35,349] Trial 68 finished with value: 0.1993348604919623 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9860764994598216, 'min_weight_fraction_leaf': 0.022286815780540634}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2365591490720433
Fold 2 IBS: 0.22131703584518395
Fold 3 IBS: 0.21468130634418622
Fold 4 IBS: 0.22918783390849085
Fold 5 IBS: 0.2181320987477092
[I 2024-04-19 14:59:41,149] Trial 69 finished with value: 0.2239754847835227 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 236, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9608682699921427, 'min_weight_fraction_leaf': 0.2864016846718066}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2141001980700463
Fold 2 IBS: 0.18008333278426925
Fold 3 IBS: 0.1879725741810636
Fold 4 IBS: 0.19498909793486166
Fold 5 IBS: 0.16584373802214583
[I 2024-04-19 14:59:51,714] Trial 70 finished with value: 0.18859778819847733 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9969480236364259, 'min_weight_fraction_leaf': 0.013812205414924436}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2140966903857263
Fold 2 IBS: 0.18072561052771724
Fold 3 IBS: 0.18882252022842136
Fold 4 IBS: 0.19597566403934094
Fold 5 IBS: 0.16539717562089074
[I 2024-04-19 15:00:03,344] Trial 71 finished with value: 0.18900353216041932 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9918558396160204, 'min_weight_fraction_leaf': 0.0068952357522586456}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21603071934692913
Fold 2 IBS: 0.18199677410478105
Fold 3 IBS: 0.18857834975768964
Fold 4 IBS: 0.1931833546739912
Fold 5 IBS: 0.16659700790160611
[I 2024-04-19 15:00:14,872] Trial 72 finished with value: 0.18927724115699943 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9121256508534055, 'min_weight_fraction_leaf': 0.0005212216954084261}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21375162072413798
Fold 2 IBS: 0.18715392969930847
Fold 3 IBS: 0.19203353721517546
Fold 4 IBS: 0.19646864440812928
Fold 5 IBS: 0.17158213719923593
[I 2024-04-19 15:00:24,001] Trial 73 finished with value: 0.1921979738491974 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9980006295053775, 'min_weight_fraction_leaf': 0.0006603867898888157}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21401318872018266
Fold 2 IBS: 0.18291770353148368
Fold 3 IBS: 0.1878785582518727
Fold 4 IBS: 0.1915900349059854
Fold 5 IBS: 0.16636063217999533
[I 2024-04-19 15:00:32,831] Trial 74 finished with value: 0.18855202351790395 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 372, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9034857567027796, 'min_weight_fraction_leaf': 0.013280468186275795}. Best is trial 63 with value: 0.1883299130608305.

Fold 1 IBS: 0.21657675292627207
Fold 2 IBS: 0.18996174454319362
Fold 3 IBS: 0.18393478555155848
Fold 4 IBS: 0.19722264590644567
Fold 5 IBS: 0.17340727825186003
[I 2024-04-19 15:00:41,356] Trial 75 finished with value: 0.19222064143586598 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9086795540810024, 'min_weight_fraction_leaf': 0.03284410208925504}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21374362171322053
Fold 2 IBS: 0.1809837734102344
Fold 3 IBS: 0.1928804193379134
Fold 4 IBS: 0.19389862294434004
Fold 5 IBS: 0.16641872761123616
[I 2024-04-19 15:00:51,911] Trial 76 finished with value: 0.1895850330033889 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8605344738061455, 'min_weight_fraction_leaf': 0.0132289654357266}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2136263783710042
Fold 2 IBS: 0.1797844883476793
Fold 3 IBS: 0.19019941306366508
Fold 4 IBS: 0.19332643220320936
Fold 5 IBS: 0.16540838604898453
[I 2024-04-19 15:01:00,620] Trial 77 finished with value: 0.18846901960690848 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8553757827166253, 'min_weight_fraction_leaf': 0.01267833398506176}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21394057344768827
Fold 2 IBS: 0.18063564607564772
Fold 3 IBS: 0.19110178366055228
Fold 4 IBS: 0.1933325146794154
Fold 5 IBS: 0.165642771743641
[I 2024-04-19 15:01:08,837] Trial 78 finished with value: 0.1889306579213889 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8575353599751615, 'min_weight_fraction_leaf': 0.011808738308151196}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2126262135430542
Fold 2 IBS: 0.18696373447968684
Fold 3 IBS: 0.1916799280019377
Fold 4 IBS: 0.19683095724446073
Fold 5 IBS: 0.17241956982191808
[I 2024-04-19 15:01:17,650] Trial 79 finished with value: 0.19210408061821152 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9589922281293288, 'min_weight_fraction_leaf': 0.00023409421845237187}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2153469063453449
Fold 2 IBS: 0.18778468182940314
Fold 3 IBS: 0.1866708606567345
Fold 4 IBS: 0.19691516821506336
Fold 5 IBS: 0.17754995961266154
[I 2024-04-19 15:01:23,796] Trial 80 finished with value: 0.1928535153318415 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2869597372530869, 'min_weight_fraction_leaf': 0.015545952867167576}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.20902792603358883
Fold 2 IBS: 0.18006042053021734
Fold 3 IBS: 0.18911702889503695
Fold 4 IBS: 0.19734675827568018
Fold 5 IBS: 0.16680814632667756
[I 2024-04-19 15:01:32,840] Trial 81 finished with value: 0.1884720560122402 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 309, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9259652503609331, 'min_weight_fraction_leaf': 0.011333713500102472}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.20965756514521555
Fold 2 IBS: 0.1814081067821129
Fold 3 IBS: 0.1896445243994355
Fold 4 IBS: 0.19634790225481819
Fold 5 IBS: 0.1667849972674436
[I 2024-04-19 15:01:41,446] Trial 82 finished with value: 0.1887686191698051 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9323699691639797, 'min_weight_fraction_leaf': 0.02308562555518695}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2153817227869837
Fold 2 IBS: 0.19064494420871675
Fold 3 IBS: 0.1928363140916346
Fold 4 IBS: 0.19848435688688135
Fold 5 IBS: 0.17685355407979692
[I 2024-04-19 15:01:48,692] Trial 83 finished with value: 0.19484017841080264 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9339793672931662, 'min_weight_fraction_leaf': 0.022004474344811363}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.24653067306998416
Fold 2 IBS: 0.23215271642663415
Fold 3 IBS: 0.23010902544257975
Fold 4 IBS: 0.24116005900490298
Fold 5 IBS: 0.23000207632521744
[I 2024-04-19 15:01:56,859] Trial 84 finished with value: 0.2359909100538637 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.07505434810839277}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.23013207588924356
Fold 2 IBS: 0.21649686531732093
Fold 3 IBS: 0.20821441289778195
Fold 4 IBS: 0.22098308423517524
Fold 5 IBS: 0.20804654146185125
[I 2024-04-19 15:02:05,032] Trial 85 finished with value: 0.21677459596027457 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9650657834803271, 'min_weight_fraction_leaf': 0.035745447715905855}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.23776519245318667
Fold 2 IBS: 0.21599806462497675
Fold 3 IBS: 0.19854293183949293
Fold 4 IBS: 0.22768263426905036
Fold 5 IBS: 0.20526222555074036
[I 2024-04-19 15:02:13,368] Trial 86 finished with value: 0.2170502097474894 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8552680427767512, 'min_weight_fraction_leaf': 0.381622326839403}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.22498794680095857
Fold 2 IBS: 0.20871296427131997
Fold 3 IBS: 0.1986932860108566
Fold 4 IBS: 0.21342471202843274
Fold 5 IBS: 0.19611500802990536
[I 2024-04-19 15:02:21,202] Trial 87 finished with value: 0.20838678342829464 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 322, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9346631200415512, 'min_weight_fraction_leaf': 0.011829639629513685}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2162799881668905
Fold 2 IBS: 0.19232899542734697
Fold 3 IBS: 0.18648368909793978
Fold 4 IBS: 0.19899335757357461
Fold 5 IBS: 0.17300447570342775
[I 2024-04-19 15:02:30,534] Trial 88 finished with value: 0.19341810119383593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8961097715415979, 'min_weight_fraction_leaf': 0.025293850990263902}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21685001465299827
Fold 2 IBS: 0.1961691885413081
Fold 3 IBS: 0.19377583257578665
Fold 4 IBS: 0.19986684493416645
Fold 5 IBS: 0.17774512608127138
[I 2024-04-19 15:02:38,813] Trial 89 finished with value: 0.1968814013571062 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9273501023983637, 'min_weight_fraction_leaf': 0.04735901557972175}. Best is trial 63 with value: 0.1883299130608305.

Fold 1 IBS: 0.21649654230068696
Fold 2 IBS: 0.1994536066038553
Fold 3 IBS: 0.1910443715333566
Fold 4 IBS: 0.20311940988854024
Fold 5 IBS: 0.18412454653280888
[I 2024-04-19 15:02:46,604] Trial 90 finished with value: 0.1988476953718496 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9531106840561406, 'min_weight_fraction_leaf': 0.09026278115621361}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21417020956953955
Fold 2 IBS: 0.18221070479947724
Fold 3 IBS: 0.1876123093586995
Fold 4 IBS: 0.1945453292939215
Fold 5 IBS: 0.1658337819099612
[I 2024-04-19 15:03:00,896] Trial 91 finished with value: 0.1888744669863198 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 390, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9155821930769641, 'min_weight_fraction_leaf': 0.0071593216081176705}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21334772506121008
Fold 2 IBS: 0.1816182181383867
Fold 3 IBS: 0.18952956072516672
Fold 4 IBS: 0.19750128460117958
Fold 5 IBS: 0.1685827762577281
[I 2024-04-19 15:03:11,213] Trial 92 finished with value: 0.19011591295673422 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.97798257382931, 'min_weight_fraction_leaf': 0.009783759359771677}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21517609409586363
Fold 2 IBS: 0.1821811797549699
Fold 3 IBS: 0.1870785183222405
Fold 4 IBS: 0.19102878902606021
Fold 5 IBS: 0.17067480247963093
[I 2024-04-19 15:03:22,320] Trial 93 finished with value: 0.18922787673575306 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 387, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8774391513202735, 'min_weight_fraction_leaf': 0.033797847017769014}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21137091510190062
Fold 2 IBS: 0.18839244695486237
Fold 3 IBS: 0.18742029037727956
Fold 4 IBS: 0.19491638605970943
Fold 5 IBS: 0.17114179611166253
[I 2024-04-19 15:03:32,042] Trial 94 finished with value: 0.19064836692108292 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3830871059653363, 'min_weight_fraction_leaf': 0.02515706968561085}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2138966882370574
Fold 2 IBS: 0.1844877510679235
Fold 3 IBS: 0.19259781557758243
Fold 4 IBS: 0.1952141807236525
Fold 5 IBS: 0.16975439013355925
[I 2024-04-19 15:03:41,793] Trial 95 finished with value: 0.191190165147955 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 331, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.853090178217675, 'min_weight_fraction_leaf': 0.012155059432012595}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2278103724303231
Fold 2 IBS: 0.20998652770068607
Fold 3 IBS: 0.2016895045401415
Fold 4 IBS: 0.2145197300147786
Fold 5 IBS: 0.20079551362441908
[I 2024-04-19 15:03:51,949] Trial 96 finished with value: 0.21096032966206962 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 376, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9196471588164407, 'min_weight_fraction_leaf': 0.04764222809243661}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2129544257256905
Fold 2 IBS: 0.188757190081597
Fold 3 IBS: 0.1913596765199584
Fold 4 IBS: 0.19299294688332613
Fold 5 IBS: 0.16956267469915398
[I 2024-04-19 15:04:02,028] Trial 97 finished with value: 0.19112538278194519 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7906318813789162, 'min_weight_fraction_leaf': 0.05576114935877039}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21517779568864578
Fold 2 IBS: 0.18674501277395147
Fold 3 IBS: 0.19147087886044026
Fold 4 IBS: 0.1973182121218361
Fold 5 IBS: 0.170619113683073
[I 2024-04-19 15:04:10,415] Trial 98 finished with value: 0.19226620262558933 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8265091641061248, 'min_weight_fraction_leaf': 0.06956660551772675}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21291524232383788
Fold 2 IBS: 0.17927405181896092
Fold 3 IBS: 0.19353115438588406
Fold 4 IBS: 0.19297220466886353
Fold 5 IBS: 0.17269237403404555
[I 2024-04-19 15:04:13,426] Trial 99 finished with value: 0.1902770054463184 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 101, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.88561888536106, 'min_weight_fraction_leaf': 0.028367714803137684}. Best is trial 63 with value: 0.1883299130608305.


* Best trial for IBS:
 FrozenTrial(number=63, state=TrialState.COMPLETE, values=[0.1883299130608305], datetime_start=datetime.datetime(2024, 4, 19, 14, 58, 45, 729017), datetime_complete=datetime.datetime(2024, 4, 19, 14, 58, 55, 49234), params={'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002786019075411844}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=63, value=None)


* Best Score for IBS:
 0.1883299130608305

In [62]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.188

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_leaf_nodes=18,
                   max_samples=0.8161032428574773, min_samples_leaf=2,
                   min_samples_split=11,
                   min_weight_fraction_leaf=0.001106761767719347,
                   n_estimators=105, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.607

ExtraSurvivalTrees(max_depth=10, max_features=None, max_leaf_nodes=12,
                   max_samples=0.8664901703822724, min_samples_split=13,
                   min_weight_fraction_leaf=0.0002786019075411844,
                   n_estimators=373, oob_score=True, random_state=123)

IBS: 0.252

In [66]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 15:04:16,943] A new study created in memory with name: no-name-c90e7784-dca9-4af7-8374-a11e65d20595

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:04:56,411] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:05:19,314] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:05:40,461] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:06:14,160] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:06:28,798] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:06:32,069] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:07:04,086] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:07:13,418] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:07:14,814] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 15:08:42,854] Trial 9 finished with value: 0.7053891693443892 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-19 15:10:58,433] Trial 10 finished with value: 0.6731409344204184 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:13:30,273] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-19 15:15:33,284] Trial 12 finished with value: 0.6892369560938594 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:16:32,720] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:17:51,651] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:19:05,926] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:19:53,894] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:21:37,432] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:24:01,593] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:24:08,007] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:24:55,189] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-19 15:26:40,526] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6437768240343348
[I 2024-04-19 15:28:25,724] Trial 22 finished with value: 0.6634639504505081 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:30:16,848] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:31:32,579] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:32:57,324] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:33:35,729] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:35:35,097] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:35:41,350] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:36:51,171] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:37:12,760] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.648068669527897
[I 2024-04-19 15:38:44,197] Trial 31 finished with value: 0.6148553306063567 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:40:35,233] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:41:49,065] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:43:00,339] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-19 15:43:52,444] Trial 35 finished with value: 0.6720678122425536 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:44:32,417] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:45:01,760] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:45:23,551] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:45:47,676] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:46:18,673] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6330472103004292
[I 2024-04-19 15:48:05,428] Trial 41 finished with value: 0.6603814554989593 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:49:24,528] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:51:07,800] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:51:41,191] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:53:17,441] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 15:53:30,335] Trial 46 finished with value: 0.7270154738948459 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:53:52,198] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:53:52,688] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:54:06,763] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:55:07,301] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.703862660944206
[I 2024-04-19 15:56:10,570] Trial 51 finished with value: 0.6957971729128621 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:56:41,966] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6792828685258964
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6995708154506438
[I 2024-04-19 15:57:37,109] Trial 53 finished with value: 0.7166400375279826 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:58:25,142] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.04642759977764528, 'dropout_rate': 0.5787056799551111, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8043967529855988, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.9987906743578988, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:58:44,221] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9338509253358491, 'learning_rate': 0.05026798356278357, 'dropout_rate': 0.8859792395781099, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 2.0925706859481137, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.9220343002247878, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:59:41,921] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8543724704763108, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.3004273858397456, 'min_weight_fraction_leaf': 0.19369329911983815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7124463519313304
[I 2024-04-19 15:59:48,422] Trial 57 finished with value: 0.71352028974883 and parameters: {'subsample': 0.9087026240599475, 'learning_rate': 0.08124746006044987, 'dropout_rate': 0.997784793728882, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.410591151226506, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8063875242325604, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:59:55,999] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8212698530092863, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.181840851947653, 'min_weight_fraction_leaf': 0.4057697411163346, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8125246339086644, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 5}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:00:06,202] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9193087392842657, 'learning_rate': 0.0872713586054678, 'dropout_rate': 0.9474892480356638, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.3337975605954647, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.7937489212794213, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:00:08,838] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.7446094350786215, 'learning_rate': 0.09733264341118891, 'dropout_rate': 0.9841116957888287, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.6816514323618716, 'min_weight_fraction_leaf': 0.21423049941460018, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.7693486777346097, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:00:26,724] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.079755577636651, 'dropout_rate': 0.9141007682217919, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.3860962100040052, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.960062895620913, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6545064377682404
[I 2024-04-19 16:00:50,275] Trial 62 finished with value: 0.6738863298917944 and parameters: {'subsample': 0.9950153281899117, 'learning_rate': 0.08115591715872426, 'dropout_rate': 0.8285090704895912, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.46340528439350875, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.8636512797881153, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5836909871244635
[I 2024-04-19 16:01:10,341] Trial 63 finished with value: 0.5422175565840008 and parameters: {'subsample': 0.9879857181271309, 'learning_rate': 0.08167353877257796, 'dropout_rate': 0.8555425487679464, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.4732508331244123, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.8698220228130342, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:01:25,843] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9998194099499076, 'learning_rate': 0.08518105894428284, 'dropout_rate': 0.9084790128000951, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.43893162961234394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0018957941321912743, 'validation_fraction': 0.6573317669908815, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:02:02,275] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8863506781235784, 'learning_rate': 0.09077517237486941, 'dropout_rate': 0.7155053041594167, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 1.0503703250594787, 'min_weight_fraction_leaf': 0.41623993393470454, 'max_features': 'sqrt', 'min_impurity_decrease': 5.4764171179088326e-05, 'validation_fraction': 0.7243703387674565, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:02:32,480] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9116050534419412, 'learning_rate': 0.07264703745168608, 'dropout_rate': 0.8194893498338957, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.5401195366715463, 'min_weight_fraction_leaf': 0.45613333197683914, 'max_features': 'sqrt', 'min_impurity_decrease': 0.013056447447707517, 'validation_fraction': 0.9169313175992941, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:02:40,823] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.2507118299802445, 'learning_rate': 0.036515998728865476, 'dropout_rate': 0.9726102863603132, 'n_estimators': 371, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.48294812651480895, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0016007967193364127, 'validation_fraction': 0.8429859516851567, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:03:12,165] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8371795305913793, 'learning_rate': 0.04255428671400532, 'dropout_rate': 0.633247084204052, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.8386209432307415, 'min_weight_fraction_leaf': 0.43086676861494394, 'max_features': 1, 'min_impurity_decrease': 0.006343103938039445, 'validation_fraction': 0.8911962268662544, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:03:25,530] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.9464359352204211, 'learning_rate': 0.06174138905299288, 'dropout_rate': 0.9285880327607973, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.45960319442458425, 'min_weight_fraction_leaf': 0.23985000065202236, 'max_features': 'log2', 'min_impurity_decrease': 0.00030338628790529525, 'validation_fraction': 0.329118980782965, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7896995708154506
[I 2024-04-19 16:04:14,463] Trial 70 finished with value: 0.7584899292280459 and parameters: {'subsample': 0.7868009537469239, 'learning_rate': 0.06760822881110454, 'dropout_rate': 0.4501645913744281, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.010068295219290181, 'min_weight_fraction_leaf': 0.31623455708072684, 'max_features': 0.1, 'min_impurity_decrease': 1.7127716189044953e-05, 'validation_fraction': 0.773508933151765, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7553648068669528
[I 2024-04-19 16:05:10,717] Trial 71 finished with value: 0.7490850897378227 and parameters: {'subsample': 0.8731481729382106, 'learning_rate': 0.06824697098399125, 'dropout_rate': 0.44693614056417824, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.3047914794183888, 'max_features': 0.1, 'min_impurity_decrease': 3.976633059647162e-05, 'validation_fraction': 0.7895458945773391, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:06:06,006] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7823514804378748, 'learning_rate': 0.05594196279186142, 'dropout_rate': 0.4470080666838303, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 0.3009753821860147, 'min_weight_fraction_leaf': 0.3059540589853319, 'max_features': 0.1, 'min_impurity_decrease': 1.5867418332223817e-05, 'validation_fraction': 0.7793460995771967, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 70 with value: 0.7584899292280459.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:07:05,907] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8663908775735847, 'learning_rate': 0.06632362371857915, 'dropout_rate': 0.5067723878896389, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.618560685045426, 'min_weight_fraction_leaf': 0.31460076590199093, 'max_features': 0.1, 'min_impurity_decrease': 8.328437416038891e-06, 'validation_fraction': 0.7008907913024036, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 7}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:08:16,266] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8288686373854733, 'learning_rate': 0.05998088897970471, 'dropout_rate': 0.35479137028960395, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.9759418026741545, 'min_weight_fraction_leaf': 0.2773249572889655, 'max_features': 0.1, 'min_impurity_decrease': 5.198140001660516e-05, 'validation_fraction': 0.7466111961316684, 'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7510729613733905
[I 2024-04-19 16:08:53,756] Trial 75 finished with value: 0.7593045273013703 and parameters: {'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:09:31,692] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.90806151385064, 'learning_rate': 0.06937411702873973, 'dropout_rate': 0.5775100962015742, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.3026218647170148, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 3.1759196242669716e-05, 'validation_fraction': 0.8054405672668666, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:10:04,559] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8021858195531186, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.4930834587163687, 'n_estimators': 291, 'criterion': 'squared_error', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.25797282688791734, 'max_features': 0.1, 'min_impurity_decrease': 8.194270761449124e-05, 'validation_fraction': 0.8191017051978536, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7553648068669528
[I 2024-04-19 16:10:49,039] Trial 78 finished with value: 0.7529889918423416 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.05690511629279836, 'dropout_rate': 0.5670668275300401, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.3008453270284027, 'max_features': 0.1, 'min_impurity_decrease': 9.997537740252558e-05, 'validation_fraction': 0.634085956732461, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:11:38,183] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7354140786592815, 'learning_rate': 0.04969314557779707, 'dropout_rate': 0.44525279135712004, 'n_estimators': 366, 'criterion': 'squared_error', 'ccp_alpha': 0.5591541411162989, 'min_weight_fraction_leaf': 0.27054049814219927, 'max_features': 0.1, 'min_impurity_decrease': 0.0001332335562751616, 'validation_fraction': 0.6322159428309632, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:12:35,645] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.4097359359491849, 'n_estimators': 387, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.2916012333412588, 'max_features': 0.1, 'min_impurity_decrease': 3.446222542448271e-05, 'validation_fraction': 0.658619742124138, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7339055793991416
[I 2024-04-19 16:13:10,917] Trial 81 finished with value: 0.7481542616623006 and parameters: {'subsample': 0.8900437147371856, 'learning_rate': 0.05732267025618887, 'dropout_rate': 0.5675964787359803, 'n_estimators': 338, 'criterion': 'squared_error', 'ccp_alpha': 0.02537647186946867, 'min_weight_fraction_leaf': 0.3203794260312518, 'max_features': 0.1, 'min_impurity_decrease': 0.00011928163703594395, 'validation_fraction': 0.5473179941373633, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:13:49,203] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.674646944161499, 'learning_rate': 0.06428673292745038, 'dropout_rate': 0.5603615855034783, 'n_estimators': 347, 'criterion': 'squared_error', 'ccp_alpha': 0.28819151280834227, 'min_weight_fraction_leaf': 0.30301215361806194, 'max_features': 0.1, 'min_impurity_decrease': 0.00011381045599980596, 'validation_fraction': 0.5688457919188374, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:14:21,006] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7076615576312072, 'learning_rate': 0.056710204467247914, 'dropout_rate': 0.6033560518396526, 'n_estimators': 335, 'criterion': 'squared_error', 'ccp_alpha': 0.8202792651285943, 'min_weight_fraction_leaf': 0.31878503420088733, 'max_features': 0.1, 'min_impurity_decrease': 0.0002767446387407935, 'validation_fraction': 0.51243688588132, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:15:07,233] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8885223542936614, 'learning_rate': 0.07000519724522539, 'dropout_rate': 0.5288642574811846, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 0.5149081571445734, 'min_weight_fraction_leaf': 0.34755924952935247, 'max_features': 0.1, 'min_impurity_decrease': 1.6951185184740712e-05, 'validation_fraction': 0.4777741397542481, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7896995708154506
[I 2024-04-19 16:15:44,126] Trial 85 finished with value: 0.7550455930886464 and parameters: {'subsample': 0.8605990508338958, 'learning_rate': 0.052056821807615235, 'dropout_rate': 0.4591414560091507, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 0.011402478584663527, 'min_weight_fraction_leaf': 0.33201592938914204, 'max_features': 0.1, 'min_impurity_decrease': 4.500909928644848e-05, 'validation_fraction': 0.585795551959921, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:16:25,608] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.8602325771048466, 'learning_rate': 0.060666799241958703, 'dropout_rate': 0.4544018342257149, 'n_estimators': 320, 'criterion': 'squared_error', 'ccp_alpha': 0.22931497714889953, 'min_weight_fraction_leaf': 0.36106190454255527, 'max_features': 0.1, 'min_impurity_decrease': 0.0001528555634091728, 'validation_fraction': 0.5817279039264187, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:16:55,055] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7587617437729911, 'learning_rate': 0.04761165440524907, 'dropout_rate': 0.4957903377584335, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 1.080975311316525, 'min_weight_fraction_leaf': 0.3363100713943507, 'max_features': 0.1, 'min_impurity_decrease': 0.00046289489298800726, 'validation_fraction': 0.5377854514350624, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:17:20,309] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9306795844790319, 'learning_rate': 0.051627622421456736, 'dropout_rate': 0.4234035172725829, 'n_estimators': 252, 'criterion': 'squared_error', 'ccp_alpha': 0.7265789482493736, 'min_weight_fraction_leaf': 0.3769812431626508, 'max_features': 0.1, 'min_impurity_decrease': 4.642862113005286e-05, 'validation_fraction': 0.4739493451385479, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7510729613733905
[I 2024-04-19 16:17:50,240] Trial 89 finished with value: 0.7451295099349646 and parameters: {'subsample': 0.8391283049189849, 'learning_rate': 0.055724086293807554, 'dropout_rate': 0.6569553700677857, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.01877120542983873, 'min_weight_fraction_leaf': 0.32461639571647416, 'max_features': 0.1, 'min_impurity_decrease': 8.851047050185397e-05, 'validation_fraction': 0.6010087752598334, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:18:33,312] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.826829689860655, 'learning_rate': 0.05508607313298636, 'dropout_rate': 0.4747673828195568, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.46861411786043294, 'min_weight_fraction_leaf': 0.3271740396549214, 'max_features': 0.1, 'min_impurity_decrease': 9.545901155149427e-05, 'validation_fraction': 0.5913771141991949, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6995708154506438
[I 2024-04-19 16:19:08,939] Trial 91 finished with value: 0.7237191125293256 and parameters: {'subsample': 0.9670051193547057, 'learning_rate': 0.05358528744281843, 'dropout_rate': 0.658599767424636, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.037871277159682165, 'min_weight_fraction_leaf': 0.28864883630713, 'max_features': 0.1, 'min_impurity_decrease': 0.00022284757650732192, 'validation_fraction': 0.6230196429197797, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:19:37,284] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.04507048157049061, 'dropout_rate': 0.6619274742089222, 'n_estimators': 319, 'criterion': 'squared_error', 'ccp_alpha': 0.1977251065362092, 'min_weight_fraction_leaf': 0.2997333226617717, 'max_features': 0.1, 'min_impurity_decrease': 3.110697272043209e-05, 'validation_fraction': 0.7057224083251947, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:20:07,515] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8713442146116508, 'learning_rate': 0.056893055161794756, 'dropout_rate': 0.6240038144153928, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.2020936997276668, 'min_weight_fraction_leaf': 0.27879305118961123, 'max_features': 0.1, 'min_impurity_decrease': 0.0002253362395408032, 'validation_fraction': 0.5411649201375784, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 7}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:20:41,461] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.846552766071321, 'learning_rate': 0.05225166033787123, 'dropout_rate': 0.5466158596699147, 'n_estimators': 343, 'criterion': 'squared_error', 'ccp_alpha': 0.5371670207357605, 'min_weight_fraction_leaf': 0.25551392419012386, 'max_features': 0.1, 'min_impurity_decrease': 1.9306777571724905e-05, 'validation_fraction': 0.612298406876781, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:21:17,841] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.7863806056473801, 'learning_rate': 0.06528678713702542, 'dropout_rate': 0.5828268476051283, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.9669214947186134, 'min_weight_fraction_leaf': 0.31565449545198027, 'max_features': 0.1, 'min_impurity_decrease': 9.721858189938487e-05, 'validation_fraction': 0.6404170541911562, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7167381974248928
[I 2024-04-19 16:21:53,576] Trial 96 finished with value: 0.7361464780146243 and parameters: {'subsample': 0.8988051132134279, 'learning_rate': 0.06223070527189957, 'dropout_rate': 0.5156283651894482, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.03101134846799354, 'min_weight_fraction_leaf': 0.34626128365000786, 'max_features': 0.1, 'min_impurity_decrease': 1.3094627017216677e-05, 'validation_fraction': 0.6632572619204413, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:22:11,163] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8930015289701463, 'learning_rate': 0.06902066318585262, 'dropout_rate': 0.6637119170834406, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5827663286593292, 'min_weight_fraction_leaf': 0.34069712252087353, 'max_features': 0.1, 'min_impurity_decrease': 1.0966163456816475e-05, 'validation_fraction': 0.6202090272853855, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:22:32,905] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8120824030153192, 'learning_rate': 0.06065076232609097, 'dropout_rate': 0.750396388680249, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.2855531941206882, 'max_features': 0.1, 'min_impurity_decrease': 6.3587125691091546e-06, 'validation_fraction': 0.565884480208947, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-19 16:23:04,631] A new study created in memory with name: no-name-73f60618-7ba6-493a-ae55-1e8ab3143545

Fold 5 C-index: 0.5
[I 2024-04-19 16:23:04,545] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.9759866968226103, 'learning_rate': 0.06186324982491159, 'dropout_rate': 0.38086979950007127, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 1.2268388380947401, 'min_weight_fraction_leaf': 0.32648395112982853, 'max_features': 0.1, 'min_impurity_decrease': 4.1512935010412314e-05, 'validation_fraction': 0.669722021056952, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.7593045273013703], datetime_start=datetime.datetime(2024, 4, 19, 16, 8, 16, 410030), datetime_complete=datetime.datetime(2024, 4, 19, 16, 8, 53, 754465), params={'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for C-index:
 0.7593045273013703

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:23:35,153] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:23:52,352] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:24:11,853] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 16:24:42,688] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:24:54,337] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:24:56,732] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:25:29,431] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:25:38,291] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:25:39,840] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24608005079919942
Fold 2 IBS: 0.23042815803611094
Fold 3 IBS: 0.22863801065607092
Fold 4 IBS: 0.24084051984701824
Fold 5 IBS: 0.22855540564358753
[I 2024-04-19 16:26:59,947] Trial 9 finished with value: 0.2349084289963974 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23166000859087926
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-19 16:28:48,940] Trial 10 finished with value: 0.23563424132764627 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 16:30:32,484] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24715489611868932
Fold 2 IBS: 0.23185086387290396
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-19 16:32:02,537] Trial 12 finished with value: 0.23582817076967802 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:32:46,382] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:34:05,463] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:35:12,637] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:35:50,021] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:37:24,107] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:38:22,072] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:38:32,542] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:40:00,150] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24710981631467982
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-19 16:41:33,456] Trial 21 finished with value: 0.2358286001617127 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.2460949705832435
Fold 2 IBS: 0.23011947144053765
Fold 3 IBS: 0.22852853905222809

Fold 4 IBS: 0.24075460977388422
Fold 5 IBS: 0.22861261428074
[I 2024-04-19 16:42:59,773] Trial 22 finished with value: 0.23482204102612672 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:44:08,980] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:44:56,304] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:45:36,660] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:46:34,629] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:46:40,191] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 16:46:59,540] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:47:46,487] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:48:07,075] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24695000891576355
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-19 16:49:26,363] Trial 31 finished with value: 0.2356643163163706 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24623846601283667
Fold 2 IBS: 0.23034600631535648
Fold 3 IBS: 0.22852247093857828
Fold 4 IBS: 0.24075522979606004
Fold 5 IBS: 0.22871472601162812
[I 2024-04-19 16:50:37,918] Trial 32 finished with value: 0.23491537981489188 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:51:33,601] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:52:33,769] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 16:52:46,901] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:53:58,914] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:54:00,938] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 16:54:33,034] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:55:11,827] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:55:50,707] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2466243968963398
Fold 2 IBS: 0.230928831475849
Fold 3 IBS: 0.22863585294540403
Fold 4 IBS: 0.24117285713517794
Fold 5 IBS: 0.22893530922896765
[I 2024-04-19 16:56:51,180] Trial 41 finished with value: 0.23525944953634767 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24629176115681264
Fold 2 IBS: 0.23044441839041935
Fold 3 IBS: 0.22846692796424145
Fold 4 IBS: 0.2408165395500078
Fold 5 IBS: 0.22873017992338907
[I 2024-04-19 16:57:57,585] Trial 42 finished with value: 0.23494996539697408 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:59:09,995] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 16:59:58,260] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24690838091318074
Fold 2 IBS: 0.231606265379147
Fold 3 IBS: 0.22862607626808185
Fold 4 IBS: 0.24158411302700467
Fold 5 IBS: 0.22903582211104476
[I 2024-04-19 17:00:46,053] Trial 45 finished with value: 0.2355521315396918 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:01:31,044] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:01:50,818] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:01:51,126] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 17:02:01,633] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:02:56,654] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24692974063860446
Fold 2 IBS: 0.23163323773848501
Fold 3 IBS: 0.2286226342984277
Fold 4 IBS: 0.24159022036393826
Fold 5 IBS: 0.22903704159821506
[I 2024-04-19 17:03:40,986] Trial 51 finished with value: 0.23556257492753413 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:04:40,918] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2464290885826847
Fold 2 IBS: 0.23073960203048824
Fold 3 IBS: 0.2279244913585667
Fold 4 IBS: 0.2408200570354747
Fold 5 IBS: 0.22834887416862718
[I 2024-04-19 17:05:29,208] Trial 53 finished with value: 0.2348524226351683 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 17:06:24,693] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 17:07:10,598] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:07:56,552] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:08:40,021] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:09:45,165] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:10:46,465] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:11:28,977] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 17:12:19,899] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24682210218858872
Fold 2 IBS: 0.2313482899879881
Fold 3 IBS: 0.2284490764743384
Fold 4 IBS: 0.24135605392900966
Fold 5 IBS: 0.22883648614819466
[I 2024-04-19 17:12:54,429] Trial 62 finished with value: 0.2353624017456239 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:13:31,204] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24645999930951334
Fold 2 IBS: 0.23079036542305653
Fold 3 IBS: 0.22815699680939372
Fold 4 IBS: 0.24117712757037893
Fold 5 IBS: 0.22868044791806658
[I 2024-04-19 17:14:04,904] Trial 64 finished with value: 0.23505298740608183 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-19 17:14:36,838] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:15:23,529] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:15:57,212] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:17:22,868] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:19:29,278] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:21:14,855] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2468431050789432
Fold 2 IBS: 0.23139350861857055
Fold 3 IBS: 0.2284780982446439
Fold 4 IBS: 0.24138770464805553
Fold 5 IBS: 0.22885953849816865
[I 2024-04-19 17:23:13,732] Trial 71 finished with value: 0.23539239101767637 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24699749437820576
Fold 2 IBS: 0.23165218847082278
Fold 3 IBS: 0.22865219650261898
Fold 4 IBS: 0.24159606345259071
Fold 5 IBS: 0.229036727569616
[I 2024-04-19 17:25:08,721] Trial 72 finished with value: 0.2355869340747708 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 17:25:26,199] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:30:00,734] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:31:50,108] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:34:07,422] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 17:37:05,948] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:38:32,627] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:41:41,611] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 17:43:04,441] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24681345447018593
Fold 2 IBS: 0.2313872832399048
Fold 3 IBS: 0.22845032192169396
Fold 4 IBS: 0.24137509385879735
Fold 5 IBS: 0.22882473993565516
[I 2024-04-19 18:43:54,725] Trial 81 finished with value: 0.23537017868524743 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 18:59:29,530] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:01:53,033] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898042024574092
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293926775107472
[I 2024-04-19 19:03:06,490] Trial 84 finished with value: 0.23592697084005448 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2453657442225769
Fold 2 IBS: 0.22798116508039243
Fold 3 IBS: 0.22690390767406562
Fold 4 IBS: 0.2389258130051501
Fold 5 IBS: 0.22739074180659022
[I 2024-04-19 19:07:03,886] Trial 85 finished with value: 0.23331347435775504 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:10:31,950] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8908016266221349, 'learning_rate': 0.020782252048892114, 'dropout_rate': 0.20248417164561996, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.025928909209021245, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:11:41,045] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953409887733455, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:15:22,642] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.0030671608519508686, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.27772784044341225, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:18:45,927] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9240076064991638, 'learning_rate': 0.036372907201929795, 'dropout_rate': 0.16604269499086277, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.6288732373244443, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.8456629128553931, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:22:00,066] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.22333957383529762, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24645393673926166
Fold 2 IBS: 0.23072722650379557
Fold 3 IBS: 0.22798170496299774
Fold 4 IBS: 0.240998787435527
Fold 5 IBS: 0.22853988200436828
[I 2024-04-19 19:25:15,356] Trial 91 finished with value: 0.23494030752919004 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.01642165444052923, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.901410266511097, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:28:33,758] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.012238074680872561, 'dropout_rate': 0.2583752131981347, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 2.0262506829884978e-07, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:31:52,732] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9444060832329966, 'learning_rate': 0.017856303491279684, 'dropout_rate': 0.30303355573944185, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.011908761872398903, 'max_features': 'auto', 'min_impurity_decrease': 6.055732421263935e-07, 'validation_fraction': 0.864284511598723, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:34:37,599] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8821760782294449, 'learning_rate': 0.005785552173633914, 'dropout_rate': 0.28058975756978766, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.8506324992317083, 'min_weight_fraction_leaf': 0.04622694094641695, 'max_features': None, 'min_impurity_decrease': 1.3402986834437386e-07, 'validation_fraction': 0.8985100287316004, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 19:37:59,931] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9761707513926794, 'learning_rate': 0.019567902784876703, 'dropout_rate': 0.3201948574529592, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.0386964570043107, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9417888137501867, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.246384587613419
Fold 2 IBS: 0.22951287202587697
Fold 3 IBS: 0.22811619002717504
Fold 4 IBS: 0.2407635260296621
Fold 5 IBS: 0.22839097135136704
[I 2024-04-19 19:40:49,570] Trial 96 finished with value: 0.23463362940950003 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.01055205151962401, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.09708890262536518, 'max_features': 'auto', 'min_impurity_decrease': 3.7395479538673736e-07, 'validation_fraction': 0.992337544991608, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:43:46,239] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.010954886262406833, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 1.603167122698403, 'min_weight_fraction_leaf': 0.06013220413302209, 'max_features': 'auto', 'min_impurity_decrease': 3.972456306049239e-07, 'validation_fraction': 0.9976245698846969, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-19 19:45:48,888] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8505038223267275, 'learning_rate': 0.013402809510359784, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 0.25666428673598457, 'min_weight_fraction_leaf': 0.1129024126904408, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.9625603744870045, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-19 19:48:46,496] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.06808689488183181, 'dropout_rate': 0.25443633448028735, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5386043790221791, 'min_weight_fraction_leaf': 0.03403879613376609, 'max_features': 'auto', 'min_impurity_decrease': 8.69596280226011e-07, 'validation_fraction': 0.9221483446288596, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23331347435775504], datetime_start=datetime.datetime(2024, 4, 19, 19, 3, 6, 502810), datetime_complete=datetime.datetime(2024, 4, 19, 19, 7, 3, 885478), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23331347435775504

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.759
train_ibs:  0.233

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008821356078039954,
                                 criterion='squared_error',
                                 dropout_rate=0.5604101432191428,
                                 learning_rate=0.05159117661647313, max_depth=4,
                                 max_features=0.1, max_leaf_nodes=18,
                                 min_impurity_decrease=9.803482393630746e-05,
                                 min_samples_leaf=7, min_samples_split=8,
                                 min_weight_fraction_leaf=0.26023745967507866,
                                 n_estimators=350, random_state=123,
                                 subsample=0.9197287558651637,
                                 validation_fraction=0.8247616419720114)

C-index score: 0.586

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.228

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 19:49:38,128] A new study created in memory with name: no-name-c01abfa8-52ca-4eb5-a62f-98a2c4801f09

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-19 19:49:41,151] Trial 0 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-19 19:50:04,984] Trial 1 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-19 19:50:09,569] Trial 2 finished with value: 0.6248486830300205 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6248486830300205.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:50:16,065] Trial 3 finished with value: 0.6338486920671272 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6338486920671272.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:50:25,361] Trial 4 finished with value: 0.6352789970586328 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-19 19:50:36,768] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-19 19:50:42,050] Trial 6 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:50:43,280] Trial 7 finished with value: 0.6319865279687434 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-19 19:50:49,725] Trial 8 finished with value: 0.624787126680312 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-19 19:51:07,416] Trial 9 finished with value: 0.623990313931308 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:51:19,674] Trial 10 finished with value: 0.6430073667466798 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6430073667466798.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 19:51:33,627] Trial 11 finished with value: 0.6529201065158555 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 19:51:46,926] Trial 12 finished with value: 0.6513480999684019 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:52:02,807] Trial 13 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:52:15,998] Trial 14 finished with value: 0.6469012303444714 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:52:28,677] Trial 15 finished with value: 0.6391071725529104 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:52:49,687] Trial 16 finished with value: 0.6460969853397073 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:53:08,900] Trial 17 finished with value: 0.6360685045387116 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-19 19:53:20,074] Trial 18 finished with value: 0.6304983909725402 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 11 with value: 0.6529201065158555.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:53:23,411] Trial 19 finished with value: 0.6476906108377152 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:53:50,324] Trial 20 finished with value: 0.6399802791763081 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 11 with value: 0.6529201065158555.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:53:51,151] Trial 21 finished with value: 0.6580155204688062 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.7075879968118339, 'n_estimators': 12, 'learning_rate': 0.09417886707495288}. Best is trial 21 with value: 0.6580155204688062.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:53:52,698] Trial 22 finished with value: 0.6413085231547985 and parameters: {'subsample': 0.18302526270385422, 'dropout_rate': 0.6797578358009322, 'n_estimators': 31, 'learning_rate': 0.09016744377002948}. Best is trial 21 with value: 0.6580155204688062.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:54:04,561] Trial 23 finished with value: 0.6398312723514349 and parameters: {'subsample': 0.1529963084044875, 'dropout_rate': 0.8293972968657299, 'n_estimators': 311, 'learning_rate': 0.06523678593976207}. Best is trial 21 with value: 0.6580155204688062.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-19 19:54:08,109] Trial 24 finished with value: 0.6296184029232734 and parameters: {'subsample': 0.3073558694541275, 'dropout_rate': 0.9639676260548358, 'n_estimators': 125, 'learning_rate': 0.07736898361535043}. Best is trial 21 with value: 0.6580155204688062.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:54:10,397] Trial 25 finished with value: 0.6350979089334217 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.5515081710932523, 'n_estimators': 71, 'learning_rate': 0.09163056701298726}. Best is trial 21 with value: 0.6580155204688062.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:54:19,794] Trial 26 finished with value: 0.6274237903261579 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.5707562654379044, 'n_estimators': 245, 'learning_rate': 0.08146277028320098}. Best is trial 21 with value: 0.6580155204688062.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6008583690987125
[I 2024-04-19 19:54:20,447] Trial 27 finished with value: 0.6672323922890245 and parameters: {'subsample': 0.1001314126580015, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.04133902891970489}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-19 19:54:21,047] Trial 28 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.3080593480767576, 'n_estimators': 6, 'learning_rate': 0.03545838957871889}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-19 19:54:23,345] Trial 29 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.4175950896276197, 'n_estimators': 81, 'learning_rate': 0.059959634327150395}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-19 19:54:23,948] Trial 30 finished with value: 0.6486749970143832 and parameters: {'subsample': 0.2171908589366593, 'dropout_rate': 0.7839643216652376, 'n_estimators': 2, 'learning_rate': 0.01658846646892042}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 19:54:28,775] Trial 31 finished with value: 0.6518630515426098 and parameters: {'subsample': 0.10788468267704324, 'dropout_rate': 0.15299510312424375, 'n_estimators': 144, 'learning_rate': 0.038020387978666075}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:54:33,181] Trial 32 finished with value: 0.645952253689736 and parameters: {'subsample': 0.15536598902320387, 'dropout_rate': 0.19328089386245983, 'n_estimators': 134, 'learning_rate': 0.04299322364488643}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:54:36,314] Trial 33 finished with value: 0.6493169954527871 and parameters: {'subsample': 0.10123762816272218, 'dropout_rate': 0.2821364046853404, 'n_estimators': 99, 'learning_rate': 0.045280631342427366}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:54:37,816] Trial 34 finished with value: 0.6360321480634717 and parameters: {'subsample': 0.23352222193662872, 'dropout_rate': 0.16361303426323773, 'n_estimators': 47, 'learning_rate': 0.03424693619359124}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:54:43,298] Trial 35 finished with value: 0.6447205240201903 and parameters: {'subsample': 0.16650812596288117, 'dropout_rate': 0.49453374472084644, 'n_estimators': 139, 'learning_rate': 0.021505948280347173}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:54:45,216] Trial 36 finished with value: 0.6360580421889281 and parameters: {'subsample': 0.3081010329923931, 'dropout_rate': 0.3456578368173444, 'n_estimators': 67, 'learning_rate': 0.07158461284458016}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:54:51,807] Trial 37 finished with value: 0.6438584305764671 and parameters: {'subsample': 0.1540186635771032, 'dropout_rate': 0.6198740536882945, 'n_estimators': 169, 'learning_rate': 0.05621431261796065}. Best is trial 27 with value: 0.6672323922890245.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:54:52,904] Trial 38 finished with value: 0.6328560536682268 and parameters: {'subsample': 0.29705265581319856, 'dropout_rate': 0.14460259719192237, 'n_estimators': 30, 'learning_rate': 0.03100730936388326}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:55:00,766] Trial 39 finished with value: 0.6368978224311095 and parameters: {'subsample': 0.22884368952376716, 'dropout_rate': 0.4678780957024635, 'n_estimators': 221, 'learning_rate': 0.04210354514561851}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:55:06,210] Trial 40 finished with value: 0.6330734982686776 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.201097176743482, 'n_estimators': 170, 'learning_rate': 0.06637711752186487}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 19:55:19,528] Trial 41 finished with value: 0.6512322925379104 and parameters: {'subsample': 0.11354699347645357, 'dropout_rate': 0.13901743213482892, 'n_estimators': 290, 'learning_rate': 0.09399684836020622}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:55:36,104] Trial 42 finished with value: 0.6493711195467353 and parameters: {'subsample': 0.10316318299905759, 'dropout_rate': 0.13661676516072546, 'n_estimators': 344, 'learning_rate': 0.03886138718878005}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:55:55,066] Trial 43 finished with value: 0.6400487169518856 and parameters: {'subsample': 0.19116045916462487, 'dropout_rate': 0.3836769535493768, 'n_estimators': 389, 'learning_rate': 0.04914017710938557}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:56:06,306] Trial 44 finished with value: 0.6422980044728407 and parameters: {'subsample': 0.16514599400755703, 'dropout_rate': 0.27255182260230876, 'n_estimators': 276, 'learning_rate': 0.025344716328606274}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:56:21,461] Trial 45 finished with value: 0.6401150993063871 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.1043186622541777, 'n_estimators': 329, 'learning_rate': 0.09685517314186484}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:56:31,220] Trial 46 finished with value: 0.6469155440261006 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.217336053780198, 'n_estimators': 244, 'learning_rate': 0.04923570429071793}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:56:32,172] Trial 47 finished with value: 0.6328596345921411 and parameters: {'subsample': 0.26895413105752575, 'dropout_rate': 0.3107035958868576, 'n_estimators': 25, 'learning_rate': 0.008209618821055878}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:56:33,819] Trial 48 finished with value: 0.6258881402539439 and parameters: {'subsample': 0.5990656023377149, 'dropout_rate': 0.1697005887593727, 'n_estimators': 56, 'learning_rate': 0.027763821111874188}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 19:56:36,420] Trial 49 finished with value: 0.6534566770406178 and parameters: {'subsample': 0.13863970196859363, 'dropout_rate': 0.24267717737429462, 'n_estimators': 91, 'learning_rate': 0.08279319000993074}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6695278969957081
[I 2024-04-19 19:56:39,780] Trial 50 finished with value: 0.6336528664172307 and parameters: {'subsample': 0.2471283975237478, 'dropout_rate': 0.42732372125147283, 'n_estimators': 106, 'learning_rate': 0.07394725079870926}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:56:42,448] Trial 51 finished with value: 0.6517399388431929 and parameters: {'subsample': 0.14355893570072276, 'dropout_rate': 0.2339976900110086, 'n_estimators': 90, 'learning_rate': 0.092826890343268}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:56:45,338] Trial 52 finished with value: 0.6485491069232626 and parameters: {'subsample': 0.19257647346606938, 'dropout_rate': 0.23676479690640828, 'n_estimators': 95, 'learning_rate': 0.0828463279400354}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:56:50,178] Trial 53 finished with value: 0.6416207234993392 and parameters: {'subsample': 0.18971475239825097, 'dropout_rate': 0.3082427857073471, 'n_estimators': 148, 'learning_rate': 0.09232142628447584}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 19:56:56,671] Trial 54 finished with value: 0.6518088004618265 and parameters: {'subsample': 0.1356905131249151, 'dropout_rate': 0.21344995201840233, 'n_estimators': 195, 'learning_rate': 0.08004725442654687}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 19:57:02,997] Trial 55 finished with value: 0.6510046824438974 and parameters: {'subsample': 0.12820387196181615, 'dropout_rate': 0.2682553403015329, 'n_estimators': 180, 'learning_rate': 0.07842964102544413}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753

Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 19:57:11,230] Trial 56 finished with value: 0.6510046824438974 and parameters: {'subsample': 0.13601825735860568, 'dropout_rate': 0.20365610348803556, 'n_estimators': 216, 'learning_rate': 0.08827179395515578}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:57:18,205] Trial 57 finished with value: 0.6413352649663672 and parameters: {'subsample': 0.3332767496673731, 'dropout_rate': 0.12699299444062345, 'n_estimators': 198, 'learning_rate': 0.08490740029942108}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:57:19,111] Trial 58 finished with value: 0.6455509435723705 and parameters: {'subsample': 0.19823722561423657, 'dropout_rate': 0.36573681723837637, 'n_estimators': 20, 'learning_rate': 0.07101780141273595}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:57:24,357] Trial 59 finished with value: 0.6376657109606338 and parameters: {'subsample': 0.24652793797062872, 'dropout_rate': 0.5065802886056728, 'n_estimators': 160, 'learning_rate': 0.0998582191898498}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:57:30,339] Trial 60 finished with value: 0.6416022616296431 and parameters: {'subsample': 0.13517922102904775, 'dropout_rate': 0.6121214744948075, 'n_estimators': 193, 'learning_rate': 0.08032393760157862}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:57:32,808] Trial 61 finished with value: 0.6500704433138473 and parameters: {'subsample': 0.14398117316966802, 'dropout_rate': 0.24390563549861982, 'n_estimators': 85, 'learning_rate': 0.09606976089569776}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 19:57:36,375] Trial 62 finished with value: 0.6495232834524669 and parameters: {'subsample': 0.1646151002251655, 'dropout_rate': 0.16336596886030455, 'n_estimators': 117, 'learning_rate': 0.08920079690198425}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6952789699570815
[I 2024-04-19 19:57:37,903] Trial 63 finished with value: 0.6513306292059146 and parameters: {'subsample': 0.10599031436769236, 'dropout_rate': 0.1888495036643864, 'n_estimators': 47, 'learning_rate': 0.0852253095754108}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 19:57:39,727] Trial 64 finished with value: 0.6454560608414457 and parameters: {'subsample': 0.17937964549772492, 'dropout_rate': 0.22083062972894274, 'n_estimators': 63, 'learning_rate': 0.03829569119695749}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 19:57:44,642] Trial 65 finished with value: 0.6448689635809111 and parameters: {'subsample': 0.13318739610681174, 'dropout_rate': 0.7487758294270637, 'n_estimators': 152, 'learning_rate': 0.07627622771775072}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6652360515021459
[I 2024-04-19 19:57:46,886] Trial 66 finished with value: 0.6342395398347092 and parameters: {'subsample': 0.21353596867324975, 'dropout_rate': 0.9077310681004186, 'n_estimators': 85, 'learning_rate': 0.0945547570167292}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-19 19:57:47,472] Trial 67 finished with value: 0.6301250581213471 and parameters: {'subsample': 0.28375358678262047, 'dropout_rate': 0.2903071529868851, 'n_estimators': 8, 'learning_rate': 0.05459083551018182}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 19:58:16,000] Trial 68 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.9580333130215919, 'dropout_rate': 0.2528855165909306, 'n_estimators': 496, 'learning_rate': 0.09077118519704158}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-19 19:58:17,247] Trial 69 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.5298738738357347, 'dropout_rate': 0.33613927102744956, 'n_estimators': 38, 'learning_rate': 0.084356035699454}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:58:25,514] Trial 70 finished with value: 0.636181154888345 and parameters: {'subsample': 0.39928696795489355, 'dropout_rate': 0.12659526986357855, 'n_estimators': 228, 'learning_rate': 0.0470439222756462}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:58:39,938] Trial 71 finished with value: 0.6476980430934753 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.1723011440322656, 'n_estimators': 309, 'learning_rate': 0.08840188130727805}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 19:58:51,768] Trial 72 finished with value: 0.650236920901208 and parameters: {'subsample': 0.1567247673962298, 'dropout_rate': 0.15030037357665654, 'n_estimators': 274, 'learning_rate': 0.08007105633598396}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 19:59:12,678] Trial 73 finished with value: 0.6452749727162346 and parameters: {'subsample': 0.18114304747690108, 'dropout_rate': 0.10495942741643126, 'n_estimators': 399, 'learning_rate': 0.09762592494165344}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 19:59:38,557] Trial 74 finished with value: 0.6537316567895448 and parameters: {'subsample': 0.10099983845623818, 'dropout_rate': 0.20607083119197417, 'n_estimators': 446, 'learning_rate': 0.09233666472869427}. Best is trial 27 with value: 0.6672323922890245.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 20:00:06,757] Trial 75 finished with value: 0.652902211910312 and parameters: {'subsample': 0.1020837689230717, 'dropout_rate': 0.21922945768332813, 'n_estimators': 458, 'learning_rate': 0.09298804225645142}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 20:00:34,751] Trial 76 finished with value: 0.6503126639457106 and parameters: {'subsample': 0.10181323866447063, 'dropout_rate': 0.19759917171117053, 'n_estimators': 465, 'learning_rate': 0.087174206261307}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 20:00:56,527] Trial 77 finished with value: 0.6360178343818426 and parameters: {'subsample': 0.2162832701171794, 'dropout_rate': 0.6872306855497551, 'n_estimators': 440, 'learning_rate': 0.09202408464646958}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 20:01:17,527] Trial 78 finished with value: 0.6454483317294641 and parameters: {'subsample': 0.12380704786315203, 'dropout_rate': 0.8275062951227752, 'n_estimators': 447, 'learning_rate': 0.059798294518916995}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6652360515021459
[I 2024-04-19 20:01:48,357] Trial 79 finished with value: 0.6250297711552315 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.21332115983228078, 'n_estimators': 481, 'learning_rate': 0.040601825507372534}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 20:02:08,400] Trial 80 finished with value: 0.6422763855222863 and parameters: {'subsample': 0.1728148146699734, 'dropout_rate': 0.2877067944011079, 'n_estimators': 374, 'learning_rate': 0.03682828872698621}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-19 20:02:37,462] Trial 81 finished with value: 0.6437899928008897 and parameters: {'subsample': 0.1488205609335708, 'dropout_rate': 0.2392686427181129, 'n_estimators': 467, 'learning_rate': 0.03270203367141013}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:02:42,305] Trial 82 finished with value: 0.6494690323716836 and parameters: {'subsample': 0.12966942693503272, 'dropout_rate': 0.17260120502848314, 'n_estimators': 128, 'learning_rate': 0.09384167844146639}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:03:08,985] Trial 83 finished with value: 0.6526672965473741 and parameters: {'subsample': 0.10233517967024328, 'dropout_rate': 0.2625892803711813, 'n_estimators': 443, 'learning_rate': 0.09056762097346885}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:03:33,295] Trial 84 finished with value: 0.6486395874924507 and parameters: {'subsample': 0.1163811042628912, 'dropout_rate': 0.3181242634333376, 'n_estimators': 427, 'learning_rate': 0.0981803454407226}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:03:56,431] Trial 85 finished with value: 0.6526672965473741 and parameters: {'subsample': 0.10222250198880209, 'dropout_rate': 0.26205027511777046, 'n_estimators': 409, 'learning_rate': 0.09046579426483291}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 20:04:18,181] Trial 86 finished with value: 0.6469269974830928 and parameters: {'subsample': 0.1638081785747318, 'dropout_rate': 0.2610213319300016, 'n_estimators': 406, 'learning_rate': 0.09045606006685238}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:04:44,024] Trial 87 finished with value: 0.6518921027489244 and parameters: {'subsample': 0.10443666058949341, 'dropout_rate': 0.3701493198396464, 'n_estimators': 452, 'learning_rate': 0.09523143696971798}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:05:08,550] Trial 88 finished with value: 0.6518921027489244 and parameters: {'subsample': 0.1018046306562625, 'dropout_rate': 0.3612566071828456, 'n_estimators': 453, 'learning_rate': 0.09504958181396482}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 20:05:34,598] Trial 89 finished with value: 0.6399655416516228 and parameters: {'subsample': 0.2011476171764956, 'dropout_rate': 0.42972575206494795, 'n_estimators': 481, 'learning_rate': 0.09986245461672588}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 20:05:57,527] Trial 90 finished with value: 0.6422763855222863 and parameters: {'subsample': 0.15718771012020263, 'dropout_rate': 0.38530318654966667, 'n_estimators': 435, 'learning_rate': 0.08630624566902663}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:06:21,709] Trial 91 finished with value: 0.6486179685418964 and parameters: {'subsample': 0.11279930602845119, 'dropout_rate': 0.36096259640921774, 'n_estimators': 462, 'learning_rate': 0.09508333683738919}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 20:06:45,681] Trial 92 finished with value: 0.6477522941742586 and parameters: {'subsample': 0.1197838090295782, 'dropout_rate': 0.33574678123142476, 'n_estimators': 454, 'learning_rate': 0.08291572808578257}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:07:05,164] Trial 93 finished with value: 0.6535183603771613 and parameters: {'subsample': 0.1011615045121455, 'dropout_rate': 0.41200689746521035, 'n_estimators': 407, 'learning_rate': 0.09089778570296998}. Best is trial 27 with value: 0.6672323922890245.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 20:07:24,716] Trial 94 finished with value: 0.6369341789063492 and parameters: {'subsample': 0.23646661342674163, 'dropout_rate': 0.4081285024556842, 'n_estimators': 410, 'learning_rate': 0.09008279936437151}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:07:44,179] Trial 95 finished with value: 0.6526672965473741 and parameters: {'subsample': 0.10055111756459449, 'dropout_rate': 0.299238738709253, 'n_estimators': 392, 'learning_rate': 0.09210415562872176}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-19 20:08:02,645] Trial 96 finished with value: 0.6486795248916047 and parameters: {'subsample': 0.14644234975251774, 'dropout_rate': 0.28235461524567945, 'n_estimators': 388, 'learning_rate': 0.08791879465920027}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-19 20:08:18,500] Trial 97 finished with value: 0.6430152228454962 and parameters: {'subsample': 0.18475599354546457, 'dropout_rate': 0.31803652519690956, 'n_estimators': 350, 'learning_rate': 0.092844184878561}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-19 20:08:36,382] Trial 98 finished with value: 0.6477490101065656 and parameters: {'subsample': 0.17059892692874823, 'dropout_rate': 0.2624803166063389, 'n_estimators': 369, 'learning_rate': 0.09699209099410584}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654

[I 2024-04-19 20:08:59,223] A new study created in memory with name: no-name-54d1684c-1587-45f9-9a29-270ba3f449fb

Fold 5 C-index: 0.6824034334763949
[I 2024-04-19 20:08:59,213] Trial 99 finished with value: 0.6462092118462847 and parameters: {'subsample': 0.1309259185984863, 'dropout_rate': 0.2951109796053327, 'n_estimators': 421, 'learning_rate': 0.08353081440312332}. Best is trial 27 with value: 0.6672323922890245.


* Best trial for C-index:
 FrozenTrial(number=27, state=TrialState.COMPLETE, values=[0.6672323922890245], datetime_start=datetime.datetime(2024, 4, 19, 19, 54, 19, 797693), datetime_complete=datetime.datetime(2024, 4, 19, 19, 54, 20, 433146), params={'subsample': 0.1001314126580015, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.04133902891970489}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=27, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.1001314126580015, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.04133902891970489}


* Best Score for C-index:
 0.6672323922890245

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.32184685283009035
Fold 2 IBS: 0.24269519626988276
Fold 3 IBS: 0.32845286241320015
Fold 4 IBS: 0.28361609336040605
Fold 5 IBS: 0.2729305473144034
[I 2024-04-19 20:09:02,287] Trial 0 finished with value: 0.2899083104375965 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.42279422613772155
Fold 2 IBS: 0.3901128382737591
Fold 3 IBS: 0.39247472286878254
Fold 4 IBS: 0.36956665696576196
Fold 5 IBS: 0.3399595615106552
[I 2024-04-19 20:09:27,047] Trial 1 finished with value: 0.3829816011513361 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38477559331402056
Fold 2 IBS: 0.3002072982420411
Fold 3 IBS: 0.37939668767639545
Fold 4 IBS: 0.3096779826388825
Fold 5 IBS: 0.3252308860734576
[I 2024-04-19 20:09:32,348] Trial 2 finished with value: 0.33985768958895946 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38791718483853127
Fold 2 IBS: 0.28308398609663094
Fold 3 IBS: 0.38075337593630443
Fold 4 IBS: 0.30896380743221213
Fold 5 IBS: 0.33290864228938033
[I 2024-04-19 20:09:38,961] Trial 3 finished with value: 0.3387253993186118 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38792738170860425
Fold 2 IBS: 0.2795795393275598
Fold 3 IBS: 0.3843436493133732
Fold 4 IBS: 0.30670925738900373
Fold 5 IBS: 0.3382261071090519
[I 2024-04-19 20:09:49,143] Trial 4 finished with value: 0.33935718696951855 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.41105192261386453
Fold 2 IBS: 0.3777174719916462
Fold 3 IBS: 0.3915300176353505
Fold 4 IBS: 0.3447295660931382
Fold 5 IBS: 0.32992002164058554
[I 2024-04-19 20:10:01,922] Trial 5 finished with value: 0.370989799994917 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.2950866836605978
Fold 2 IBS: 0.21617356864727175
Fold 3 IBS: 0.2960476577766528
Fold 4 IBS: 0.26116838532173825
Fold 5 IBS: 0.2492059247499634
[I 2024-04-19 20:10:07,240] Trial 6 finished with value: 0.2635364440312448 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2635364440312448.
Fold 1 IBS: 0.2525596717266013
Fold 2 IBS: 0.2009504851975363
Fold 3 IBS: 0.2554759579529817
Fold 4 IBS: 0.22423261256383803
Fold 5 IBS: 0.2116650686406854
[I 2024-04-19 20:10:08,696] Trial 7 finished with value: 0.22897675921632854 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.32773085091505505
Fold 2 IBS: 0.24764667449835662
Fold 3 IBS: 0.3381279691027075
Fold 4 IBS: 0.28727873359875167
Fold 5 IBS: 0.2819856805230031
[I 2024-04-19 20:10:15,352] Trial 8 finished with value: 0.2965539817275748 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.4128629984024713
Fold 2 IBS: 0.3805312612875153
Fold 3 IBS: 0.39180424534594577
Fold 4 IBS: 0.3483594650353357
Fold 5 IBS: 0.3350263678028636
[I 2024-04-19 20:10:33,605] Trial 9 finished with value: 0.3737168675748263 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24690378026135393
Fold 2 IBS: 0.230918196199329
Fold 3 IBS: 0.2288651535714008
Fold 4 IBS: 0.24118860634197958
Fold 5 IBS: 0.22809859267819335
[I 2024-04-19 20:10:34,612] Trial 10 finished with value: 0.23519486581045132 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24596520377467238
Fold 2 IBS: 0.22745516260233242
Fold 3 IBS: 0.22872408268029404
Fold 4 IBS: 0.23875682318201075
Fold 5 IBS: 0.22421110618785597
[I 2024-04-19 20:10:35,327] Trial 11 finished with value: 0.2330224756854331 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.27173013199000834
Fold 2 IBS: 0.20866318918988855
Fold 3 IBS: 0.3057008256941006
Fold 4 IBS: 0.24335789289875134
Fold 5 IBS: 0.23895352312088064
[I 2024-04-19 20:10:36,877] Trial 12 finished with value: 0.2536811125787259 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24540145164058172
Fold 2 IBS: 0.22486461618174694
Fold 3 IBS: 0.2288799372028231
Fold 4 IBS: 0.23700499011587697
Fold 5 IBS: 0.22141183261877637
[I 2024-04-19 20:10:37,593] Trial 13 finished with value: 0.23151256555196104 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.2801288012575852
Fold 2 IBS: 0.20642643701643856
Fold 3 IBS: 0.2855821246683042
Fold 4 IBS: 0.2448269379427668
Fold 5 IBS: 0.23496945372244868
[I 2024-04-19 20:10:40,341] Trial 14 finished with value: 0.2503867509215087 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.34250383730825085
Fold 2 IBS: 0.2562261533432662
Fold 3 IBS: 0.35681785243304703
Fold 4 IBS: 0.2914232791743898
Fold 5 IBS: 0.29999553893473496
[I 2024-04-19 20:10:42,763] Trial 15 finished with value: 0.3093933322387378 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.3481444155513587
Fold 2 IBS: 0.2557484157443354
Fold 3 IBS: 0.36748207225232277
Fold 4 IBS: 0.28540747334430555
Fold 5 IBS: 0.3119369611284676
[I 2024-04-19 20:10:51,714] Trial 16 finished with value: 0.31374386760415807 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24607714741491096
Fold 2 IBS: 0.21115546325606438
Fold 3 IBS: 0.23474191594216773
Fold 4 IBS: 0.2296381561690892
Fold 5 IBS: 0.21122928902161456
[I 2024-04-19 20:10:53,585] Trial 17 finished with value: 0.2265683943607694 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2883901804573134
Fold 2 IBS: 0.2112037980068735
Fold 3 IBS: 0.28770446755792806
Fold 4 IBS: 0.2544520687837577
Fold 5 IBS: 0.2431612806129336
[I 2024-04-19 20:11:06,152] Trial 18 finished with value: 0.2569823590837612 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.27019935319228533
Fold 2 IBS: 0.20101355307479882

Fold 3 IBS: 0.27495840642227154
Fold 4 IBS: 0.2403770465027076
Fold 5 IBS: 0.22389919673997055
[I 2024-04-19 20:11:09,715] Trial 19 finished with value: 0.24208951118640676 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24532728078212304
Fold 2 IBS: 0.21338053568843193
Fold 3 IBS: 0.23280583204014674
Fold 4 IBS: 0.23050963160208696
Fold 5 IBS: 0.21229213294998353
[I 2024-04-19 20:11:11,593] Trial 20 finished with value: 0.22686308261255445 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480948267779246
Fold 2 IBS: 0.217894217650721
Fold 3 IBS: 0.23043919128917217
Fold 4 IBS: 0.23275995527788665
Fold 5 IBS: 0.215372968667489
[I 2024-04-19 20:11:13,203] Trial 21 finished with value: 0.22825516311261226 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24643766317823718
Fold 2 IBS: 0.22924023219100237
Fold 3 IBS: 0.2287550024184287
Fold 4 IBS: 0.2400059006469264
Fold 5 IBS: 0.2262805735657194
[I 2024-04-19 20:11:15,337] Trial 22 finished with value: 0.23414387440006285 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.257478169662288
Fold 2 IBS: 0.20248903467735407
Fold 3 IBS: 0.252469752257427
Fold 4 IBS: 0.23159280968783177
Fold 5 IBS: 0.2169495351817077
[I 2024-04-19 20:11:18,931] Trial 23 finished with value: 0.2321958602933217 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24591385980787991
Fold 2 IBS: 0.21157801995971165
Fold 3 IBS: 0.23448495664364996
Fold 4 IBS: 0.229737329537672
Fold 5 IBS: 0.2112912785040094
[I 2024-04-19 20:11:20,458] Trial 24 finished with value: 0.22660108889058458 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2756443151410581
Fold 2 IBS: 0.20473874541146792
Fold 3 IBS: 0.27375023358490214
Fold 4 IBS: 0.2440459127498442
Fold 5 IBS: 0.23246982801186947
[I 2024-04-19 20:11:23,848] Trial 25 finished with value: 0.2461298069798284 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.32538815518873926
Fold 2 IBS: 0.2468744663909679
Fold 3 IBS: 0.3332171412462654
Fold 4 IBS: 0.28581063346445296
Fold 5 IBS: 0.2781065825703804
[I 2024-04-19 20:11:29,913] Trial 26 finished with value: 0.29387939577216116 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24492083546093882
Fold 2 IBS: 0.21628333393840363
Fold 3 IBS: 0.23138494832945591
Fold 4 IBS: 0.23162572469168902
Fold 5 IBS: 0.21394160498647347
[I 2024-04-19 20:11:31,236] Trial 27 finished with value: 0.2276312894813922 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24503999552218353
Fold 2 IBS: 0.21507419381927734
Fold 3 IBS: 0.23200152410434108
Fold 4 IBS: 0.23109618679052704
Fold 5 IBS: 0.21308573107611234
[I 2024-04-19 20:11:33,607] Trial 28 finished with value: 0.22725952626248827 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3030591065047406
Fold 2 IBS: 0.22336679794652556
Fold 3 IBS: 0.3044396799522218
Fold 4 IBS: 0.2678287080975696
Fold 5 IBS: 0.25695858296703405
[I 2024-04-19 20:11:36,626] Trial 29 finished with value: 0.2711305750936183 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.30057401042692355
Fold 2 IBS: 0.22109327570196485
Fold 3 IBS: 0.30174720098020524
Fold 4 IBS: 0.2651400266811706
Fold 5 IBS: 0.2537066735825353
[I 2024-04-19 20:11:41,421] Trial 30 finished with value: 0.26845223747455993 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24486090508062983
Fold 2 IBS: 0.21682633491745948
Fold 3 IBS: 0.23109486987541575
Fold 4 IBS: 0.23197486961623204
Fold 5 IBS: 0.21430589760825255
[I 2024-04-19 20:11:43,929] Trial 31 finished with value: 0.22781257541959793 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480604491948196
Fold 2 IBS: 0.21843195389759032
Fold 3 IBS: 0.23024293091022538
Fold 4 IBS: 0.23321504110381971
Fold 5 IBS: 0.21568765554273314
[I 2024-04-19 20:11:45,330] Trial 32 finished with value: 0.2284767252747701 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24434472696223403
Fold 2 IBS: 0.22006483265789914
Fold 3 IBS: 0.23001501374819164
Fold 4 IBS: 0.23353575529737952
Fold 5 IBS: 0.21714562015932423
[I 2024-04-19 20:11:47,338] Trial 33 finished with value: 0.2290211897650057 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25788116008451006
Fold 2 IBS: 0.20226079778720082
Fold 3 IBS: 0.2544783586806218
Fold 4 IBS: 0.23143342088904706
Fold 5 IBS: 0.21567691855898308
[I 2024-04-19 20:11:50,562] Trial 34 finished with value: 0.23234613120007258 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24665787355022445
Fold 2 IBS: 0.23001468040084486
Fold 3 IBS: 0.228802523121071
Fold 4 IBS: 0.24061435934394168
Fold 5 IBS: 0.2271257607053576
[I 2024-04-19 20:11:51,463] Trial 35 finished with value: 0.2346430394242879 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.36295049794153883
Fold 2 IBS: 0.27664373471149467
Fold 3 IBS: 0.3675445917607911
Fold 4 IBS: 0.3032504418743303
Fold 5 IBS: 0.311762833506537
[I 2024-04-19 20:12:13,471] Trial 36 finished with value: 0.3244304199589384 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3956248057488727
Fold 2 IBS: 0.3239854573821247
Fold 3 IBS: 0.38499901982444784
Fold 4 IBS: 0.31514930414846015
Fold 5 IBS: 0.3335159079818787
[I 2024-04-19 20:12:21,383] Trial 37 finished with value: 0.35065489901715685 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25969526762239703
Fold 2 IBS: 0.20212138827340803
Fold 3 IBS: 0.25611019690719544

Fold 4 IBS: 0.23376225132374828
Fold 5 IBS: 0.21475575962300342
[I 2024-04-19 20:12:27,455] Trial 38 finished with value: 0.23328897274995045 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.29108106719697524
Fold 2 IBS: 0.21415810554809628
Fold 3 IBS: 0.2917820507930866
Fold 4 IBS: 0.2588982634047282
Fold 5 IBS: 0.24407574900323586
[I 2024-04-19 20:12:29,111] Trial 39 finished with value: 0.25999904718922445 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2925659515921918
Fold 2 IBS: 0.2140746731129848
Fold 3 IBS: 0.2919432513336724
Fold 4 IBS: 0.257477121073266
Fold 5 IBS: 0.24657769529804316
[I 2024-04-19 20:12:31,727] Trial 40 finished with value: 0.2605277384820316 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24534003818367572
Fold 2 IBS: 0.21351313222790674
Fold 3 IBS: 0.23284352524242438
Fold 4 IBS: 0.2304630885922339
Fold 5 IBS: 0.21224567728236968
[I 2024-04-19 20:12:33,216] Trial 41 finished with value: 0.22688109230572212 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485006409680624
Fold 2 IBS: 0.21706394797525833
Fold 3 IBS: 0.23093672935586954
Fold 4 IBS: 0.23224267333240983
Fold 5 IBS: 0.21443505260308193
[I 2024-04-19 20:12:34,320] Trial 42 finished with value: 0.22790569347268522 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2638458495823219
Fold 2 IBS: 0.2020440306627012
Fold 3 IBS: 0.2599892350953784
Fold 4 IBS: 0.2353149724721722
Fold 5 IBS: 0.2221900668187372
[I 2024-04-19 20:12:36,520] Trial 43 finished with value: 0.2366768309262622 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2455964708749073
Fold 2 IBS: 0.22570478266765567
Fold 3 IBS: 0.228795022876604
Fold 4 IBS: 0.23752979609395375
Fold 5 IBS: 0.22236478482517102
[I 2024-04-19 20:12:38,211] Trial 44 finished with value: 0.23199817146765836 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24519921983594833
Fold 2 IBS: 0.22330524452579645
Fold 3 IBS: 0.2290157433965299
Fold 4 IBS: 0.23588777848641265
Fold 5 IBS: 0.2204866110425217
[I 2024-04-19 20:12:39,315] Trial 45 finished with value: 0.2307789194574418 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.34065073189493716
Fold 2 IBS: 0.2597363049038525
Fold 3 IBS: 0.3496713953679775
Fold 4 IBS: 0.2946768758327706
Fold 5 IBS: 0.29269474527583145
[I 2024-04-19 20:12:43,554] Trial 46 finished with value: 0.30748601065507386 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25039205968447736
Fold 2 IBS: 0.19881662927592997
Fold 3 IBS: 0.2539048960518954
Fold 4 IBS: 0.22477789659354785
Fold 5 IBS: 0.21270184763960173
[I 2024-04-19 20:12:45,525] Trial 47 finished with value: 0.22811866584909044 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2556573719237732
Fold 2 IBS: 0.20234787848056301
Fold 3 IBS: 0.2522638016406119
Fold 4 IBS: 0.23093407281830788
Fold 5 IBS: 0.21250246234410652
[I 2024-04-19 20:12:51,726] Trial 48 finished with value: 0.23074111744147255 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24675070321456416
Fold 2 IBS: 0.23043515587015717
Fold 3 IBS: 0.2288281703390381
Fold 4 IBS: 0.2408551079349057
Fold 5 IBS: 0.22755526151412517
[I 2024-04-19 20:12:52,454] Trial 49 finished with value: 0.23488487977455805 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.26805889781388065
Fold 2 IBS: 0.20252886898813807
Fold 3 IBS: 0.26533134677822295
Fold 4 IBS: 0.23829437556390634
Fold 5 IBS: 0.22589258667890266
[I 2024-04-19 20:12:56,050] Trial 50 finished with value: 0.2400212151646101 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24512963190106926
Fold 2 IBS: 0.2147274537502438
Fold 3 IBS: 0.2321986628737604
Fold 4 IBS: 0.23091267007941935
Fold 5 IBS: 0.21292902132889352
[I 2024-04-19 20:12:57,432] Trial 51 finished with value: 0.22717948798667725 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24662205885932792
Fold 2 IBS: 0.22993687263943438
Fold 3 IBS: 0.22879053467216642
Fold 4 IBS: 0.24048347407202147
Fold 5 IBS: 0.22699896965015748
[I 2024-04-19 20:12:59,124] Trial 52 finished with value: 0.23456638197862154 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485579223129506
Fold 2 IBS: 0.21998745903015368
Fold 3 IBS: 0.22977573478865335
Fold 4 IBS: 0.23404920712862456
Fold 5 IBS: 0.21705606342896017
[I 2024-04-19 20:13:00,458] Trial 53 finished with value: 0.22914485132153736 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2531442464481051
Fold 2 IBS: 0.20414594462184135
Fold 3 IBS: 0.2459059794082717
Fold 4 IBS: 0.22963377950406882
Fold 5 IBS: 0.21079567993043571
[I 2024-04-19 20:13:01,551] Trial 54 finished with value: 0.22872512598254455 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2524170789262838
Fold 2 IBS: 0.20420643525007415
Fold 3 IBS: 0.24534527368601658
Fold 4 IBS: 0.2294272521646032
Fold 5 IBS: 0.21300726025333291
[I 2024-04-19 20:13:04,116] Trial 55 finished with value: 0.22888066005606209 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24626134547224643
Fold 2 IBS: 0.21072141911440245
Fold 3 IBS: 0.23515116577403225
Fold 4 IBS: 0.22942525598464827
Fold 5 IBS: 0.21111562686038168
[I 2024-04-19 20:13:05,431] Trial 56 finished with value: 0.22653496264114223 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.32236762054514384
Fold 2 IBS: 0.24369761993112318
Fold 3 IBS: 0.32961555540384646
Fold 4 IBS: 0.28411316345226234

Fold 5 IBS: 0.27450442032616973
[I 2024-04-19 20:13:13,392] Trial 57 finished with value: 0.29085967593170914 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2514876544143989
Fold 2 IBS: 0.20473165445913052
Fold 3 IBS: 0.2442786298594191
Fold 4 IBS: 0.2292932477615486
Fold 5 IBS: 0.2122783863810015
[I 2024-04-19 20:13:14,919] Trial 58 finished with value: 0.2284139145750997 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2450009034050451
Fold 2 IBS: 0.21574021216390366
Fold 3 IBS: 0.2316126494096215
Fold 4 IBS: 0.2313085066143514
Fold 5 IBS: 0.2135215585555951
[I 2024-04-19 20:13:15,895] Trial 59 finished with value: 0.22743676602970336 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.27643234236120234
Fold 2 IBS: 0.20531960631582807
Fold 3 IBS: 0.2756328535259464
Fold 4 IBS: 0.24566178547120296
Fold 5 IBS: 0.23379390635926353
[I 2024-04-19 20:13:18,854] Trial 60 finished with value: 0.24736809880668864 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24511487846402005
Fold 2 IBS: 0.2227836793360944
Fold 3 IBS: 0.22915537398733413
Fold 4 IBS: 0.2355788750800659
Fold 5 IBS: 0.21936511210219634
[I 2024-04-19 20:13:20,645] Trial 61 finished with value: 0.23039958379394215 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.25492402733786423
Fold 2 IBS: 0.2031585290599715
Fold 3 IBS: 0.24895077307909572
Fold 4 IBS: 0.2303647335144685
Fold 5 IBS: 0.21487736782477726
[I 2024-04-19 20:13:23,132] Trial 62 finished with value: 0.23045508616323543 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24531708021685963
Fold 2 IBS: 0.22395449249387253
Fold 3 IBS: 0.22892582490539293
Fold 4 IBS: 0.23652996695441353
Fold 5 IBS: 0.2211888183692411
[I 2024-04-19 20:13:24,370] Trial 63 finished with value: 0.23118323658795595 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24543346554687298
Fold 2 IBS: 0.21302518909492982
Fold 3 IBS: 0.23348544240148608
Fold 4 IBS: 0.22993870744839895
Fold 5 IBS: 0.21193762927195595
[I 2024-04-19 20:13:26,043] Trial 64 finished with value: 0.22676408675272874 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24427299434478603
Fold 2 IBS: 0.2145724066475789
Fold 3 IBS: 0.23244031403754764
Fold 4 IBS: 0.2308013778601708
Fold 5 IBS: 0.21301937769687632
[I 2024-04-19 20:13:27,632] Trial 65 finished with value: 0.22702129411739191 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24414268593072253
Fold 2 IBS: 0.21442849246434953
Fold 3 IBS: 0.23260330769031967
Fold 4 IBS: 0.23070773208679712
Fold 5 IBS: 0.212827602266059
[I 2024-04-19 20:13:29,345] Trial 66 finished with value: 0.2269419640876496 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.29808498998226407
Fold 2 IBS: 0.22021424313364715
Fold 3 IBS: 0.3008089717671045
Fold 4 IBS: 0.26320289852555373
Fold 5 IBS: 0.25043406288056935
[I 2024-04-19 20:13:38,581] Trial 67 finished with value: 0.2665490332578278 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.36891251562644484
Fold 2 IBS: 0.28320463913092336
Fold 3 IBS: 0.3735215508072975
Fold 4 IBS: 0.30452010490955944
Fold 5 IBS: 0.3196121754758854
[I 2024-04-19 20:13:59,399] Trial 68 finished with value: 0.32995419719002206 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24694744262426244
Fold 2 IBS: 0.23112662775390544
Fold 3 IBS: 0.22888040570607412
Fold 4 IBS: 0.24129039277709646
Fold 5 IBS: 0.2284229264424595
[I 2024-04-19 20:14:00,305] Trial 69 finished with value: 0.23533355906075962 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.3789820127073879
Fold 2 IBS: 0.2881919135260274
Fold 3 IBS: 0.37987359081709904
Fold 4 IBS: 0.30582173340243274
Fold 5 IBS: 0.3297183983009644
[I 2024-04-19 20:14:17,195] Trial 70 finished with value: 0.3365175297507823 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2442747298878039
Fold 2 IBS: 0.21394603308037777
Fold 3 IBS: 0.2329347454389621
Fold 4 IBS: 0.23037646611901139
Fold 5 IBS: 0.21249651991354515
[I 2024-04-19 20:14:18,872] Trial 71 finished with value: 0.22680569888794005 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24446665909481854
Fold 2 IBS: 0.2202286409877386
Fold 3 IBS: 0.2298979855224926
Fold 4 IBS: 0.23386125106403746
Fold 5 IBS: 0.21736824836572086
[I 2024-04-19 20:14:20,725] Trial 72 finished with value: 0.2291645570069616 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24809645932076727
Fold 2 IBS: 0.20746362379997257
Fold 3 IBS: 0.23887206962421953
Fold 4 IBS: 0.2284825651773238
Fold 5 IBS: 0.2100698715233792
[I 2024-04-19 20:14:23,564] Trial 73 finished with value: 0.22659691788913244 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2543888239593833
Fold 2 IBS: 0.20292319894393337
Fold 3 IBS: 0.24852527226160065
Fold 4 IBS: 0.22955225079581343
Fold 5 IBS: 0.21241475262132198
[I 2024-04-19 20:14:26,336] Trial 74 finished with value: 0.22956085971641055 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2586670573078814
Fold 2 IBS: 0.20043803485847264
Fold 3 IBS: 0.2585285364856659
Fold 4 IBS: 0.23185266301823715
Fold 5 IBS: 0.21512351643127495
[I 2024-04-19 20:14:28,748] Trial 75 finished with value: 0.23292196162030643 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24487192319121745
Fold 2 IBS: 0.21645877330178392
Fold 3 IBS: 0.23106107310931137
Fold 4 IBS: 0.2321278197949212

Fold 5 IBS: 0.21457551785343906
[I 2024-04-19 20:14:29,861] Trial 76 finished with value: 0.2278190214501346 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24975605957417094
Fold 2 IBS: 0.20544669926019324
Fold 3 IBS: 0.24292589881032364
Fold 4 IBS: 0.2283240329592914
Fold 5 IBS: 0.21054396005104126
[I 2024-04-19 20:14:34,002] Trial 77 finished with value: 0.22739933013100408 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24684927097070503
Fold 2 IBS: 0.2094952280230178
Fold 3 IBS: 0.23652719105524916
Fold 4 IBS: 0.22913951054643386
Fold 5 IBS: 0.2106573202990221
[I 2024-04-19 20:14:36,125] Trial 78 finished with value: 0.2265337041788856 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24502409439696052
Fold 2 IBS: 0.22205787317352343
Fold 3 IBS: 0.22926533447627775
Fold 4 IBS: 0.2352795597651623
Fold 5 IBS: 0.2188730593846164
[I 2024-04-19 20:14:38,506] Trial 79 finished with value: 0.23009998423930805 and parameters: {'subsample': 0.5862245141488869, 'dropout_rate': 0.7413305472330791, 'n_estimators': 79, 'learning_rate': 0.00518700542803859}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.2548529205408104
Fold 2 IBS: 0.2029551856530423
Fold 3 IBS: 0.2494742616554397
Fold 4 IBS: 0.23041757963367823
Fold 5 IBS: 0.21265412243334256
[I 2024-04-19 20:14:41,884] Trial 80 finished with value: 0.23007081398326265 and parameters: {'subsample': 0.5412030995339159, 'dropout_rate': 0.7943244209025906, 'n_estimators': 120, 'learning_rate': 0.015049190001982352}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24503928639713976
Fold 2 IBS: 0.22210439837147225
Fold 3 IBS: 0.22923064761200726
Fold 4 IBS: 0.23532466695341075
Fold 5 IBS: 0.2188890235672119
[I 2024-04-19 20:14:43,557] Trial 81 finished with value: 0.23011760458024838 and parameters: {'subsample': 0.6124074983469379, 'dropout_rate': 0.6341528845468055, 'n_estimators': 48, 'learning_rate': 0.008581896342583242}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24566232614650538
Fold 2 IBS: 0.20763330396179233
Fold 3 IBS: 0.2399122667638913
Fold 4 IBS: 0.22729435575947432
Fold 5 IBS: 0.20971833255484604
[I 2024-04-19 20:14:45,559] Trial 82 finished with value: 0.22604411703730184 and parameters: {'subsample': 0.36882902998484507, 'dropout_rate': 0.9266770484936306, 'n_estimators': 72, 'learning_rate': 0.01836411354022466}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.24387668061602458
Fold 2 IBS: 0.21367297665454796
Fold 3 IBS: 0.2333362520374528
Fold 4 IBS: 0.22948421407755595
Fold 5 IBS: 0.21270096527180668
[I 2024-04-19 20:14:47,677] Trial 83 finished with value: 0.22661421773147755 and parameters: {'subsample': 0.3619635368676717, 'dropout_rate': 0.9281653685578871, 'n_estimators': 75, 'learning_rate': 0.01174447149382581}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.2481782165598782
Fold 2 IBS: 0.2032648830515002
Fold 3 IBS: 0.2505921898057478
Fold 4 IBS: 0.22803942510176736
Fold 5 IBS: 0.21128535620380667
[I 2024-04-19 20:14:49,877] Trial 84 finished with value: 0.22827201414454007 and parameters: {'subsample': 0.3276130954169086, 'dropout_rate': 0.9694546795228237, 'n_estimators': 84, 'learning_rate': 0.022169484737510906}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.2449916816071917
Fold 2 IBS: 0.21034889723149172
Fold 3 IBS: 0.23561656068011147
Fold 4 IBS: 0.2278223716435641
Fold 5 IBS: 0.21102078940314542
[I 2024-04-19 20:14:52,454] Trial 85 finished with value: 0.22596006011310088 and parameters: {'subsample': 0.363388210801912, 'dropout_rate': 0.8895677781947375, 'n_estimators': 93, 'learning_rate': 0.011252915568896725}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2507644683324895
Fold 2 IBS: 0.19921462815138938
Fold 3 IBS: 0.2542760719339917
Fold 4 IBS: 0.22500598026486066
Fold 5 IBS: 0.2125124481679968
[I 2024-04-19 20:14:55,263] Trial 86 finished with value: 0.22835471937014562 and parameters: {'subsample': 0.2377998071866918, 'dropout_rate': 0.9263524121710748, 'n_estimators': 107, 'learning_rate': 0.01902085002480073}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24461520451936894
Fold 2 IBS: 0.21162187155184128
Fold 3 IBS: 0.2344490116850452
Fold 4 IBS: 0.22917043508852472
Fold 5 IBS: 0.21178897460870122
[I 2024-04-19 20:14:58,940] Trial 87 finished with value: 0.22632909949069627 and parameters: {'subsample': 0.35810969899809325, 'dropout_rate': 0.8886867033584094, 'n_estimators': 134, 'learning_rate': 0.007190805934355407}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24456370610129832
Fold 2 IBS: 0.22128022630882604
Fold 3 IBS: 0.22947409303221045
Fold 4 IBS: 0.23463118790461507
Fold 5 IBS: 0.2191508748909942
[I 2024-04-19 20:15:03,104] Trial 88 finished with value: 0.2298200176475888 and parameters: {'subsample': 0.3554257183364478, 'dropout_rate': 0.8515802063127001, 'n_estimators': 151, 'learning_rate': 0.002966804106888144}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2775193161210976
Fold 2 IBS: 0.2056495855781246
Fold 3 IBS: 0.28613237088303234
Fold 4 IBS: 0.24447960031747357
Fold 5 IBS: 0.23382248801015568
[I 2024-04-19 20:15:06,680] Trial 89 finished with value: 0.24952067218197677 and parameters: {'subsample': 0.2975632154761778, 'dropout_rate': 0.8979603248959219, 'n_estimators': 137, 'learning_rate': 0.026327304724599293}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24489792409125763
Fold 2 IBS: 0.2147507134735931
Fold 3 IBS: 0.23214478243102468
Fold 4 IBS: 0.2311366433597866
Fold 5 IBS: 0.21331168885551222
[I 2024-04-19 20:15:09,215] Trial 90 finished with value: 0.22724835044223485 and parameters: {'subsample': 0.4239438985312938, 'dropout_rate': 0.8842980981030877, 'n_estimators': 94, 'learning_rate': 0.008199816001785099}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24443912868099016
Fold 2 IBS: 0.2106555205421554
Fold 3 IBS: 0.2361002830373223
Fold 4 IBS: 0.22815140478159898
Fold 5 IBS: 0.21090216410324303
[I 2024-04-19 20:15:11,391] Trial 91 finished with value: 0.226049700229062 and parameters: {'subsample': 0.36316393582436224, 'dropout_rate': 0.9330356356373378, 'n_estimators': 74, 'learning_rate': 0.014627227900695133}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24696395568562218
Fold 2 IBS: 0.206328757542603
Fold 3 IBS: 0.24098516387669733
Fold 4 IBS: 0.22738668862012074
Fold 5 IBS: 0.2096198352018724
[I 2024-04-19 20:15:15,056] Trial 92 finished with value: 0.22625688018538312 and parameters: {'subsample': 0.373278308068316, 'dropout_rate': 0.8205446675130532, 'n_estimators': 127, 'learning_rate': 0.010840707181494103}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2445959002519018
Fold 2 IBS: 0.21367655385448994
Fold 3 IBS: 0.23288855680962822
Fold 4 IBS: 0.23008083622513512
Fold 5 IBS: 0.21285389160286478
[I 2024-04-19 20:15:18,342] Trial 93 finished with value: 0.22681914774880396 and parameters: {'subsample': 0.4052623501935374, 'dropout_rate': 0.8224708293111835, 'n_estimators': 122, 'learning_rate': 0.006828423866425095}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.26160555948702097
Fold 2 IBS: 0.20039367088884036
Fold 3 IBS: 0.267173994295559
Fold 4 IBS: 0.2305106627684761
Fold 5 IBS: 0.21639436758841524
[I 2024-04-19 20:15:23,369] Trial 94 finished with value: 0.23521565100566236 and parameters: {'subsample': 0.2685207405457639, 'dropout_rate': 0.5306326676271426, 'n_estimators': 159, 'learning_rate': 0.016919236533565633}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2458959493820953
Fold 2 IBS: 0.20854810474644417
Fold 3 IBS: 0.23772658465187374
Fold 4 IBS: 0.22767957442334677

Fold 5 IBS: 0.21018857248815617
[I 2024-04-19 20:15:26,341] Trial 95 finished with value: 0.22600775713838323 and parameters: {'subsample': 0.37798247189331685, 'dropout_rate': 0.8572208063796695, 'n_estimators': 112, 'learning_rate': 0.01063058308878333}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2471425193657016
Fold 2 IBS: 0.20576111765918625
Fold 3 IBS: 0.2415748835282002
Fold 4 IBS: 0.22741639083301954
Fold 5 IBS: 0.209543331672624
[I 2024-04-19 20:15:29,850] Trial 96 finished with value: 0.22628764861174636 and parameters: {'subsample': 0.34523349906195283, 'dropout_rate': 0.7739280807288145, 'n_estimators': 132, 'learning_rate': 0.010648288131411126}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24385115968166024
Fold 2 IBS: 0.21643646571599923
Fold 3 IBS: 0.23116557489710682
Fold 4 IBS: 0.23167317839356094
Fold 5 IBS: 0.21518657563145072
[I 2024-04-19 20:15:35,194] Trial 97 finished with value: 0.22766259086395557 and parameters: {'subsample': 0.37469859653908655, 'dropout_rate': 0.8528934112321543, 'n_estimators': 187, 'learning_rate': 0.003684889317176295}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24621689559308768
Fold 2 IBS: 0.2055572040394727
Fold 3 IBS: 0.24230333094691225
Fold 4 IBS: 0.22648768747110257
Fold 5 IBS: 0.20950699582535112
[I 2024-04-19 20:15:42,205] Trial 98 finished with value: 0.22601442277518524 and parameters: {'subsample': 0.340063793125768, 'dropout_rate': 0.7630617995157165, 'n_estimators': 226, 'learning_rate': 0.006438550621538491}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24106601000226005
Fold 2 IBS: 0.20817303425836378
Fold 3 IBS: 0.2365485578566005
Fold 4 IBS: 0.223095844393265
Fold 5 IBS: 0.21131937637628836
[I 2024-04-19 20:15:48,545] Trial 99 finished with value: 0.22404056457735555 and parameters: {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}. Best is trial 99 with value: 0.22404056457735555.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.22404056457735555], datetime_start=datetime.datetime(2024, 4, 19, 20, 15, 42, 210420), datetime_complete=datetime.datetime(2024, 4, 19, 20, 15, 48, 545432), params={'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=99, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}


* Best Score for IBS:
 0.22404056457735555

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.667
train_ibs:  0.224

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3060837787360696,
                                              learning_rate=0.04133902891970489,
                                              n_estimators=1, random_state=123,
                                              subsample=0.1001314126580015)

C-index score: 0.535

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7782160113329367,
                                              learning_rate=0.005308151321564225,
                                              n_estimators=212,
                                              random_state=123,
                                              subsample=0.17778434918103095)

IBS: 0.233

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [80]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.866   1.0
ExtraSurvivalTrees               0.826   2.0
GradientBoosting                 0.759   3.0
CoxElastic                       0.726   4.0
CoxLasso                         0.725   5.0
CoxPH                            0.724   6.0
ComponentwiseGradientBoosting    0.667   7.0
CoxRidge                         0.651   8.0

In [81]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.188   1.0
Randomsurvivalforest           0.190   2.0
CoxLasso                       0.199   3.5
CoxElastic                     0.199   3.5
CoxPH                          0.200   5.0
ComponentwiseGradientBoosting  0.224   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [82]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.607   1.0
GradientBoosting                 0.586   2.0
CoxPH                            0.562   3.0
CoxLasso                         0.561   4.0
CoxElastic                       0.560   5.0
Randomsurvivalforest             0.546   6.0
CoxRidge                         0.535   7.5
ComponentwiseGradientBoosting    0.535   7.5

In [83]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.228   1.0
CoxRidge                       0.229   2.0
ComponentwiseGradientBoosting  0.233   3.0
ExtraSurvivalTrees             0.252   4.0
Randomsurvivalforest           0.263   5.0
CoxLasso                       0.288   6.0
CoxElastic                     0.289   7.0
CoxPH                          0.290   8.0

In [84]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/robust/rent/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_robust_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [85]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-19