In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

## Test dataset: MAASTRO

In [5]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [6]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [7]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [8]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [9]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [10]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [11]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# Set y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [12]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [13]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [14]:
# Change the name of a column 'DFS_event' in the clincial_test 
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [15]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

### COX PLSR

In [16]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"shape_Elongation",
"shape_MajorAxisLength",
"hpv_related",
"cavum_oris",
"shape_Sphericity",
"uicc8_III-IV",
"shape_Flatness"
]

In [17]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [18]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [19]:
# Copy the original X for later 
original_X = X.copy()

In [20]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [21]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [22]:
X_new

,shape_Elongation,shape_MajorAxisLength,hpv_related,cavum_oris,shape_Sphericity,uicc8_III-IV,shape_Flatness
0,0.600926,42.073251,0.0,0,0.761164,0.0,0.535140
1,0.841579,24.613845,0.0,0,0.697049,0.0,0.367109
2,0.772821,48.030294,0.0,1,0.565792,1.0,0.597785
3,0.847727,25.589900,0.0,0,0.684364,0.0,0.405730
4,0.831483,34.684750,0.0,0,0.503142,0.0,0.442406
...,...,...,...,...,...,...,...
134,0.680294,33.069705,1.0,0,0.742102,0.0,0.523608
135,0.758193,41.043692,1.0,0,0.722918,1.0,0.735524
136,0.770113,36.618802,1.0,0,0.652963,0.0,0.648063
137,0.628897,45.870392,1.0,0,0.724255,1.0,0.492193
138,0.892637,30.363259,1.0,0,0.722633,1.0,0.756267

In [23]:
X_new_std

,shape_Elongation,shape_MajorAxisLength,hpv_related,cavum_oris,shape_Sphericity,uicc8_III-IV,shape_Flatness
0,-0.485459,0.059912,0.0,0,0.704475,0.0,0.064971
1,0.666232,-0.755402,0.0,0,0.101791,0.0,-0.952446
2,0.337179,0.338093,0.0,1,-1.132016,1.0,0.444285
3,0.695653,-0.709822,0.0,0,-0.017443,0.0,-0.718597
4,0.617917,-0.285114,0.0,0,-1.720923,0.0,-0.496529
...,...,...,...,...,...,...,...
134,-0.105628,-0.360532,1.0,0,0.525285,0.0,-0.004852
135,0.267171,0.011834,1.0,0,0.344965,1.0,1.278289
136,0.324219,-0.194798,1.0,0,-0.312609,0.0,0.748713
137,-0.351598,0.237230,1.0,0,0.357529,1.0,-0.195069
138,0.910577,-0.486917,1.0,0,0.342282,1.0,1.403881

In [24]:
MAASTRO_new

,shape_Elongation,shape_MajorAxisLength,hpv_related,cavum_oris,shape_Sphericity,uicc8_III-IV,shape_Flatness
0,0.765178,50.002093,1,0,0.668072,0,0.610062
1,0.776540,41.753334,0,0,0.669961,1,0.504616
2,0.697164,44.375483,0,0,0.624081,1,0.478604
3,0.574636,46.115989,0,0,0.577624,1,0.446059
4,0.633419,54.394967,1,0,0.630933,0,0.480378
...,...,...,...,...,...,...,...
94,0.882411,34.218615,0,0,0.671754,1,0.577884
95,0.535802,51.046869,0,0,0.632189,1,0.455642
96,0.716610,50.417953,1,0,0.645548,1,0.631485
97,0.665145,44.901412,1,0,0.727488,0,0.628338
98,0.616262,36.574294,0,0,0.672838,1,0.469139

In [25]:
MAASTRO_new_std

,shape_Elongation,shape_MajorAxisLength,hpv_related,cavum_oris,shape_Sphericity,uicc8_III-IV,shape_Flatness
0,0.300600,0.430171,1,0,-0.170593,0,0.518623
1,0.354974,0.044973,0,0,-0.152832,1,-0.119851
2,-0.024893,0.167421,0,0,-0.584101,1,-0.277351
3,-0.611274,0.248699,0,0,-1.020797,1,-0.474407
4,-0.329957,0.635308,1,0,-0.519690,0,-0.266607
...,...,...,...,...,...,...,...
94,0.861639,-0.306881,0,0,-0.135979,1,0.323784
95,-0.797117,0.478960,0,0,-0.507883,1,-0.416383
96,0.068172,0.449591,1,0,-0.382318,1,0.648334
97,-0.178126,0.191981,1,0,0.387916,0,0.629283
98,-0.412064,-0.196876,0,0,-0.125793,1,-0.334661

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [26]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:05:01,468] A new study created in memory with name: no-name-69708343-0782-4393-9df0-fd3fdbbd8ff0

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:13,376] Trial 0 finished with value: 0.7145119462550232 and parameters: {}. Best is trial 0 with value: 0.7145119462550232.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7145119462550232], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 1, 566717), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 13, 361910), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7145119462550232

[I 2024-04-17 14:05:13,388] A new study created in memory with name: no-name-9fccb589-bcd0-4e63-8085-6e54d7d05895

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23538523110319692
Fold 2 IBS: 0.1899261593875249
Fold 3 IBS: 0.19727300356874158
Fold 4 IBS: 0.19757472980917043
Fold 5 IBS: 0.17989392824267253
[I 2024-04-17 14:05:14,046] Trial 0 finished with value: 0.2000106104222613 and parameters: {}. Best is trial 0 with value: 0.2000106104222613.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2000106104222613], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 13, 462917), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 14, 46517), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2000106104222613

In [27]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [28]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.715
train_ibs:  0.2

#### Test

In [29]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [30]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.568
IBS score: 0.263

In [31]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [32]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [33]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:05:14,609] A new study created in memory with name: no-name-b3d2a920-efa7-4436-8e09-c30fe433cfba

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6759656652360515
[I 2024-04-17 14:05:15,295] Trial 0 finished with value: 0.6506780364238784 and parameters: {}. Best is trial 0 with value: 0.6506780364238784.

[I 2024-04-17 14:05:15,302] A new study created in memory with name: no-name-5ae43f6c-daaf-46e6-b3cb-ae20103bc26c

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6506780364238784], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 14, 728214), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 15, 295093), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6506780364238784

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2472470961322622
Fold 2 IBS: 0.23203987476422633
Fold 3 IBS: 0.2289818676351831
Fold 4 IBS: 0.2419747644101403
Fold 5 IBS: 0.22939558698202767
[I 2024-04-17 14:05:16,014] Trial 0 finished with value: 0.23592783798476794 and parameters: {}. Best is trial 0 with value: 0.23592783798476794.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783798476794], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 15, 539770), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 16, 13947), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783798476794

In [34]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [35]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.651
train_ibs:  0.236

#### Test

In [36]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [37]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.541

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [38]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [39]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:05:16,391] A new study created in memory with name: no-name-537abf14-0b63-4089-871c-110016cff113

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012

[I 2024-04-17 14:05:17,134] A new study created in memory with name: no-name-bcbe7de1-0da2-4d3d-ba10-6437828905bb

Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:17,130] Trial 0 finished with value: 0.7168117769460121 and parameters: {}. Best is trial 0 with value: 0.7168117769460121.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7168117769460121], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 16, 427552), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 17, 130159), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7168117769460121

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2341863280747747
Fold 2 IBS: 0.18871473870741187
Fold 3 IBS: 0.19822110991533345
Fold 4 IBS: 0.19650803493993982
Fold 5 IBS: 0.1791141254821675
[I 2024-04-17 14:05:17,879] Trial 0 finished with value: 0.1993488674239255 and parameters: {}. Best is trial 0 with value: 0.1993488674239255.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1993488674239255], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 17, 213166), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 17, 879201), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1993488674239255

In [40]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [41]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.717
train_ibs:  0.199

#### Test

In [42]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [43]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.571

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.262

In [44]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [45]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:05:18,335] A new study created in memory with name: no-name-5c91361f-05fe-442d-af7e-b0719607ec8f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:19,045] Trial 0 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:19,707] Trial 1 finished with value: 0.7151565950982957 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:20,430] Trial 2 finished with value: 0.7151565950982957 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:21,379] Trial 3 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:22,019] Trial 4 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:22,753] Trial 5 finished with value: 0.7159534078472997 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:23,536] Trial 6 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:24,276] Trial 7 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:24,930] Trial 8 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:25,605] Trial 9 finished with value: 0.7159534078472997 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:26,333] Trial 10 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 14:05:26,672] Trial 11 finished with value: 0.6468033175195231 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:27,379] Trial 12 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6978253640763652}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:28,447] Trial 13 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6189362712539238}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:29,299] Trial 14 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8403787283021946}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:30,045] Trial 15 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5892251114089379}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:30,935] Trial 16 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8361111870922124}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:31,946] Trial 17 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5632480038685016}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:32,820] Trial 18 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:33,688] Trial 19 finished with value: 0.7151565950982957 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:34,729] Trial 20 finished with value: 0.7159317888967454 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:35,420] Trial 21 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7501344475278824}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:36,267] Trial 22 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5339346419626306}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:36,826] Trial 23 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.651954326927192}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673

Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:37,500] Trial 24 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7602371709740536}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:38,182] Trial 25 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.891573855041803}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:38,813] Trial 26 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.4514399534035586}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:39,469] Trial 27 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7284175098086105}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:40,177] Trial 28 finished with value: 0.7159534078472997 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:40,919] Trial 29 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5124352690792928}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:41,617] Trial 30 finished with value: 0.7159534078472997 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:42,259] Trial 31 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9660663971217622}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:42,881] Trial 32 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6393034577533845}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:43,440] Trial 33 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.914571411927465}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:44,134] Trial 34 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7856939143902578}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:44,696] Trial 35 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8963881835877474}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:45,367] Trial 36 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.698425974143177}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:46,002] Trial 37 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.4595613720024655}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:46,598] Trial 38 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5883737477322043}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:47,163] Trial 39 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9465340727804966}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:47,704] Trial 40 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9996455549049067}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:48,464] Trial 41 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7030105763086383}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:49,164] Trial 42 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6467086020812518}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:49,930] Trial 43 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6703798638434219}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:50,528] Trial 44 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8466388571073736}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:51,091] Trial 45 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5591224516670668}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:51,751] Trial 46 finished with value: 0.7159534078472997 and parameters: {'l1_ratio': 0.4178465972493743}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:52,302] Trial 47 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5961283203881889}. Best is trial 0 with value: 0.7168117769460121.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:53,123] Trial 48 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:54,010] Trial 49 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8520147594086461}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:54,926] Trial 50 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5059499849722756}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:55,525] Trial 51 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.4714046994764885}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:56,203] Trial 52 finished with value: 0.7159534078472997 and parameters: {'l1_ratio': 0.3649507484125762}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:05:57,030] Trial 53 finished with value: 0.7150807250669582 and parameters: {'l1_ratio': 0.16504314926261965}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:57,945] Trial 54 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5474260308302842}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:59,168] Trial 55 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6798704964829347}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:05:59,832] Trial 56 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.741968632048434}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 14:06:00,149] Trial 57 finished with value: 0.6483242300670518 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:00,875] Trial 58 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6084884529962878}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:06:01,649] Trial 59 finished with value: 0.7151565950982957 and parameters: {'l1_ratio': 0.26760961619373064}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:02,568] Trial 60 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.4053234463810215}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:03,302] Trial 61 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.949035304646828}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:04,057] Trial 62 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9904527886240021}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:04,767] Trial 63 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8247398568539042}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:05,413] Trial 64 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7734009965953919}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:06,291] Trial 65 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.922259657657684}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:07,432] Trial 66 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8791901523794641}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:08,446] Trial 67 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7063532881264725}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:09,147] Trial 68 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5277275595022933}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:09,858] Trial 69 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.48533448187701334}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:10,431] Trial 70 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6278366970608916}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:11,042] Trial 71 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5756335763457792}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673

Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:11,650] Trial 72 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.740630846861278}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:12,258] Trial 73 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.4444560608728035}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:12,877] Trial 74 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6571690409753883}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:13,439] Trial 75 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7125952476337342}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:14,060] Trial 76 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8090609636490127}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:15,024] Trial 77 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.863503783935895}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:15,778] Trial 78 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.622255153261479}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:16,581] Trial 79 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6730374637561107}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:06:18,362] Trial 80 finished with value: 0.7159534078472997 and parameters: {'l1_ratio': 0.30931033899220917}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:19,263] Trial 81 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5683583305414788}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:19,935] Trial 82 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7674451933514177}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:20,784] Trial 83 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5181769079027152}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:21,466] Trial 84 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6840938668865189}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:22,110] Trial 85 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6009733315768886}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:22,798] Trial 86 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7189521426677989}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:23,445] Trial 87 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.5400673291140528}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:24,040] Trial 88 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9655660156128469}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:24,817] Trial 89 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6470210900958189}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:25,444] Trial 90 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.4382089494039095}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:26,060] Trial 91 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9261339288806291}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:26,690] Trial 92 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7937604237677911}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:27,279] Trial 93 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.894727450872193}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:27,992] Trial 94 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.8286361420574496}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:28,661] Trial 95 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.75272539878931}. Best is trial 0 with value: 0.7168117769460121.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:29,230] Trial 96 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.9860680336866003}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:30,149] Trial 97 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6884131873492754}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:30,917] Trial 98 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.7267462557335511}. Best is trial 0 with value: 0.7168117769460121.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149

[I 2024-04-17 14:06:31,656] A new study created in memory with name: no-name-c3803e83-9d07-4da7-b61c-9cc63223793b

Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:06:31,616] Trial 99 finished with value: 0.7168117769460121 and parameters: {'l1_ratio': 0.6263077111579471}. Best is trial 0 with value: 0.7168117769460121.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7168117769460121], datetime_start=datetime.datetime(2024, 4, 17, 14, 5, 18, 378730), datetime_complete=datetime.datetime(2024, 4, 17, 14, 5, 19, 44787), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.7168117769460121

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2341965339295303
Fold 2 IBS: 0.18874267310739173
Fold 3 IBS: 0.19814553245276037
Fold 4 IBS: 0.19651163093536023
Fold 5 IBS: 0.1790498109807477
[I 2024-04-17 14:06:32,415] Trial 0 finished with value: 0.19932923628115806 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.19932923628115806.
Fold 1 IBS: 0.23431758973113054
Fold 2 IBS: 0.1887028958426281
Fold 3 IBS: 0.1975913539905288
Fold 4 IBS: 0.1966259517282194
Fold 5 IBS: 0.17880389731179114
[I 2024-04-17 14:06:33,164] Trial 1 finished with value: 0.1992083377208596 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.1992083377208596.
Fold 1 IBS: 0.23428179958077452
Fold 2 IBS: 0.1887257432511915
Fold 3 IBS: 0.1974781947948211
Fold 4 IBS: 0.19668129265657386
Fold 5 IBS: 0.17873453253521282
[I 2024-04-17 14:06:33,938] Trial 2 finished with value: 0.19918031256371477 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23421784030776813
Fold 2 IBS: 0.18871812751760134
Fold 3 IBS: 0.19800197978771544
Fold 4 IBS: 0.19653223721818985
Fold 5 IBS: 0.1789524678274787
[I 2024-04-17 14:06:34,653] Trial 3 finished with value: 0.19928453053175071 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23420374339846878
Fold 2 IBS: 0.1886648601619896
Fold 3 IBS: 0.19815382243270846
Fold 4 IBS: 0.19652116855311302
Fold 5 IBS: 0.17905126950598385
[I 2024-04-17 14:06:35,313] Trial 4 finished with value: 0.19931897281045274 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23421058050201246
Fold 2 IBS: 0.18866937624913854
Fold 3 IBS: 0.1978557271878983
Fold 4 IBS: 0.19661761296472113
Fold 5 IBS: 0.17890564367280054
[I 2024-04-17 14:06:35,989] Trial 5 finished with value: 0.1992517881153142 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23418486949447162
Fold 2 IBS: 0.18870611291972164
Fold 3 IBS: 0.19821752924231195
Fold 4 IBS: 0.1965035639107245
Fold 5 IBS: 0.1791133281367132
[I 2024-04-17 14:06:36,745] Trial 6 finished with value: 0.19934508074078855 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23419114989649653
Fold 2 IBS: 0.1887338524081225
Fold 3 IBS: 0.19805888392715607
Fold 4 IBS: 0.19650656568343397
Fold 5 IBS: 0.17904904911862926
[I 2024-04-17 14:06:37,477] Trial 7 finished with value: 0.19930790020676767 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23426590884252632
Fold 2 IBS: 0.18873953510091365
Fold 3 IBS: 0.19789592427790767
Fold 4 IBS: 0.19657643415114692
Fold 5 IBS: 0.17895069665474755
[I 2024-04-17 14:06:38,203] Trial 8 finished with value: 0.1992856998054484 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23427642268887722
Fold 2 IBS: 0.18871099643114483
Fold 3 IBS: 0.19777748636661882
Fold 4 IBS: 0.1965880936847093
Fold 5 IBS: 0.17887133722902065
[I 2024-04-17 14:06:38,918] Trial 9 finished with value: 0.19924486728007418 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.23442055220185073
Fold 2 IBS: 0.1887406572231172
Fold 3 IBS: 0.22875147163974346
Fold 4 IBS: 0.2370076029927104
Fold 5 IBS: 0.17860005724421155
[I 2024-04-17 14:06:39,567] Trial 10 finished with value: 0.21350406826032664 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.19918031256371477.
Fold 1 IBS: 0.2343636766091839
Fold 2 IBS: 0.1887729884489461
Fold 3 IBS: 0.19737865139323385
Fold 4 IBS: 0.19667547306809555
Fold 5 IBS: 0.17869779275810313
[I 2024-04-17 14:06:40,237] Trial 11 finished with value: 0.1991777164555125 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 11 with value: 0.1991777164555125.
Fold 1 IBS: 0.24535840930681202
Fold 2 IBS: 0.22778003265359684
Fold 3 IBS: 0.22881811255712187
Fold 4 IBS: 0.2388948758485644
Fold 5 IBS: 0.22671874988867083
[I 2024-04-17 14:06:40,636] Trial 12 finished with value: 0.2335140360509532 and parameters: {'l1_ratio': 0.04835900598617554}. Best is trial 11 with value: 0.1991777164555125.
Fold 1 IBS: 0.23433411082616537
Fold 2 IBS: 0.1887578505566331
Fold 3 IBS: 0.19743210796608027
Fold 4 IBS: 0.19664607059617925
Fold 5 IBS: 0.17873131412874704
[I 2024-04-17 14:06:41,406] Trial 13 finished with value: 0.199180290814761 and parameters: {'l1_ratio': 0.2114475350243538}. Best is trial 11 with value: 0.1991777164555125.
Fold 1 IBS: 0.23434344743717134
Fold 2 IBS: 0.18874733912893693
Fold 3 IBS: 0.19736571758023086
Fold 4 IBS: 0.19665805658472268
Fold 5 IBS: 0.17869630330091993
[I 2024-04-17 14:06:42,085] Trial 14 finished with value: 0.19916217280639634 and parameters: {'l1_ratio': 0.18459727307810245}. Best is trial 14 with value: 0.19916217280639634.
Fold 1 IBS: 0.24696818513619784
Fold 2 IBS: 0.23140874937537698
Fold 3 IBS: 0.22895428401890255
Fold 4 IBS: 0.24151911225144607
Fold 5 IBS: 0.2290030141547366
[I 2024-04-17 14:06:42,439] Trial 15 finished with value: 0.23557066898733203 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.19916217280639634.
Fold 1 IBS: 0.2343177206256033
Fold 2 IBS: 0.18872476715076228
Fold 3 IBS: 0.19734933066931112
Fold 4 IBS: 0.19671590092376737
Fold 5 IBS: 0.17869492179613183
[I 2024-04-17 14:06:43,221] Trial 16 finished with value: 0.19916052823311517 and parameters: {'l1_ratio': 0.1772909900515591}. Best is trial 16 with value: 0.19916052823311517.
Fold 1 IBS: 0.23427958910771585
Fold 2 IBS: 0.18868662794365512
Fold 3 IBS: 0.19766743414972446
Fold 4 IBS: 0.196592284996202
Fold 5 IBS: 0.17883453747548803
[I 2024-04-17 14:06:43,936] Trial 17 finished with value: 0.1992120947345571 and parameters: {'l1_ratio': 0.32162557863487895}. Best is trial 16 with value: 0.19916052823311517.
Fold 1 IBS: 0.23432340279854064
Fold 2 IBS: 0.1887125917488455
Fold 3 IBS: 0.1972881335899761
Fold 4 IBS: 0.19672258039999746
Fold 5 IBS: 0.17866652526097374
[I 2024-04-17 14:06:44,869] Trial 18 finished with value: 0.1991426467596667 and parameters: {'l1_ratio': 0.1552967775121356}. Best is trial 18 with value: 0.1991426467596667.
Fold 1 IBS: 0.23439546470631709
Fold 2 IBS: 0.18874452457796015
Fold 3 IBS: 0.19717344672724518
Fold 4 IBS: 0.19671234426541
Fold 5 IBS: 0.1786324575655649
[I 2024-04-17 14:06:45,701] Trial 19 finished with value: 0.19913164756849944 and parameters: {'l1_ratio': 0.11626329996616502}. Best is trial 19 with value: 0.19913164756849944.
Fold 1 IBS: 0.23441106623345304
Fold 2 IBS: 0.18875078180907673
Fold 3 IBS: 0.19713958807927787
Fold 4 IBS: 0.1967277300629833
Fold 5 IBS: 0.17862216810420128
[I 2024-04-17 14:06:46,503] Trial 20 finished with value: 0.19913026685779844 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 20 with value: 0.19913026685779844.
Fold 1 IBS: 0.23440815435499165
Fold 2 IBS: 0.1887472683412114
Fold 3 IBS: 0.22873091189631373
Fold 4 IBS: 0.19672527270378395
Fold 5 IBS: 0.17862150784639436
[I 2024-04-17 14:06:47,382] Trial 21 finished with value: 0.205446623028539 and parameters: {'l1_ratio': 0.10457346814139208}. Best is trial 20 with value: 0.19913026685779844.
Fold 1 IBS: 0.23438148759298824
Fold 2 IBS: 0.18873671195132755
Fold 3 IBS: 0.1971649951247273
Fold 4 IBS: 0.1967005214233574
Fold 5 IBS: 0.17863227026457384
[I 2024-04-17 14:06:48,126] Trial 22 finished with value: 0.19912319727139485 and parameters: {'l1_ratio': 0.1139775430155659}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.24714518937213148
Fold 2 IBS: 0.23180902263551983
Fold 3 IBS: 0.22897166987708772
Fold 4 IBS: 0.2418082681156393
Fold 5 IBS: 0.2292522486265266
[I 2024-04-17 14:06:48,523] Trial 23 finished with value: 0.23579727972538098 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2343117769883826
Fold 2 IBS: 0.18869468136624637
Fold 3 IBS: 0.19758740040424744
Fold 4 IBS: 0.19662084180365177
Fold 5 IBS: 0.17880337869562704
[I 2024-04-17 14:06:49,183] Trial 24 finished with value: 0.19920361585163104 and parameters: {'l1_ratio': 0.2830544587085615}. Best is trial 22 with value: 0.19912319727139485.

Fold 1 IBS: 0.23439716816647496
Fold 2 IBS: 0.1887340498232072
Fold 3 IBS: 0.2287320438949615
Fold 4 IBS: 0.19671600400020503
Fold 5 IBS: 0.17861429459397207
[I 2024-04-17 14:06:49,888] Trial 25 finished with value: 0.20543871209576414 and parameters: {'l1_ratio': 0.10297700483781348}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23422637929906345
Fold 2 IBS: 0.1887402516103256
Fold 3 IBS: 0.19774152953496238
Fold 4 IBS: 0.19663176971967364
Fold 5 IBS: 0.1788381909342659
[I 2024-04-17 14:06:50,581] Trial 26 finished with value: 0.19923562421965818 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23423873617668486
Fold 2 IBS: 0.18865757086990564
Fold 3 IBS: 0.19801827639065275
Fold 4 IBS: 0.19655155406440863
Fold 5 IBS: 0.17899842660911816
[I 2024-04-17 14:06:51,274] Trial 27 finished with value: 0.199292912822154 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23418093374065643
Fold 2 IBS: 0.18869878790325487
Fold 3 IBS: 0.19821448211710063
Fold 4 IBS: 0.1964997580129486
Fold 5 IBS: 0.1791126552145211
[I 2024-04-17 14:06:51,969] Trial 28 finished with value: 0.19934132339769634 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23415827012010926
Fold 2 IBS: 0.18865705619837758
Fold 3 IBS: 0.19820183488660018
Fold 4 IBS: 0.19657493806725407
Fold 5 IBS: 0.17910889538751323
[I 2024-04-17 14:06:52,611] Trial 29 finished with value: 0.19934019893197089 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23438688580960823
Fold 2 IBS: 0.18874814021679004
Fold 3 IBS: 0.19721606469911634
Fold 4 IBS: 0.19670258908867697
Fold 5 IBS: 0.17864193056978608
[I 2024-04-17 14:06:53,422] Trial 30 finished with value: 0.19913912207679554 and parameters: {'l1_ratio': 0.13048781200302498}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23438333149424143
Fold 2 IBS: 0.18872653483099433
Fold 3 IBS: 0.22873352111882
Fold 4 IBS: 0.19670434069935583
Fold 5 IBS: 0.1786145979411459
[I 2024-04-17 14:06:54,197] Trial 31 finished with value: 0.2054324652169115 and parameters: {'l1_ratio': 0.10103338112661776}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23429351715766814
Fold 2 IBS: 0.18875790209630536
Fold 3 IBS: 0.19757500369379125
Fold 4 IBS: 0.1966048030889396
Fold 5 IBS: 0.1787798894422657
[I 2024-04-17 14:06:54,988] Trial 32 finished with value: 0.199202223095794 and parameters: {'l1_ratio': 0.27357119396913165}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23433669154526093
Fold 2 IBS: 0.18871177387260143
Fold 3 IBS: 0.19723803991806863
Fold 4 IBS: 0.19673535932703892
Fold 5 IBS: 0.1786533303729536
[I 2024-04-17 14:06:55,671] Trial 33 finished with value: 0.1991350390071847 and parameters: {'l1_ratio': 0.13833195289260838}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23433470668087514
Fold 2 IBS: 0.18869649012840325
Fold 3 IBS: 0.19751274991871434
Fold 4 IBS: 0.19664339268809458
Fold 5 IBS: 0.17875597803281135
[I 2024-04-17 14:06:56,484] Trial 34 finished with value: 0.19918866348977976 and parameters: {'l1_ratio': 0.24840395436271276}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.24668729710336118
Fold 2 IBS: 0.23077416682999854
Fold 3 IBS: 0.22892757046520476
Fold 4 IBS: 0.24106074323064214
Fold 5 IBS: 0.22860687899241683
[I 2024-04-17 14:06:56,768] Trial 35 finished with value: 0.23521133132432465 and parameters: {'l1_ratio': 0.013339535951618589}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23440492025278678
Fold 2 IBS: 0.2274445339070492
Fold 3 IBS: 0.22880785494847736
Fold 4 IBS: 0.23865247986172292
Fold 5 IBS: 0.2265055268103503
[I 2024-04-17 14:06:57,367] Trial 36 finished with value: 0.23116306315607732 and parameters: {'l1_ratio': 0.0526249606187868}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23430686990451055
Fold 2 IBS: 0.1887469994819848
Fold 3 IBS: 0.1974942799702356
Fold 4 IBS: 0.19661913003563014
Fold 5 IBS: 0.17875366662361533
[I 2024-04-17 14:06:58,175] Trial 37 finished with value: 0.1991841892031953 and parameters: {'l1_ratio': 0.2364723475855005}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2343754299351699
Fold 2 IBS: 0.18874981272972638
Fold 3 IBS: 0.197261988107602
Fold 4 IBS: 0.19669039313569042
Fold 5 IBS: 0.17865463464154022
[I 2024-04-17 14:06:58,981] Trial 38 finished with value: 0.19914645170994577 and parameters: {'l1_ratio': 0.1464457345953863}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23429815865764533
Fold 2 IBS: 0.18871343014368855
Fold 3 IBS: 0.19767969691612877
Fold 4 IBS: 0.1966088353115563
Fold 5 IBS: 0.17883561127068312
[I 2024-04-17 14:06:59,676] Trial 39 finished with value: 0.1992271464599404 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23425126656453824
Fold 2 IBS: 0.18871991325067405
Fold 3 IBS: 0.19788638798980943
Fold 4 IBS: 0.19656482217203863
Fold 5 IBS: 0.17891019096963398
[I 2024-04-17 14:07:00,536] Trial 40 finished with value: 0.19926651618933885 and parameters: {'l1_ratio': 0.4659485687485523}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2343989094935364
Fold 2 IBS: 0.18874867922224517
Fold 3 IBS: 0.19717551808678238
Fold 4 IBS: 0.19671523982657593
Fold 5 IBS: 0.17863236678785144
[I 2024-04-17 14:07:01,337] Trial 41 finished with value: 0.19913414268339827 and parameters: {'l1_ratio': 0.1168365867214849}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23440039697903575
Fold 2 IBS: 0.22649860669768515
Fold 3 IBS: 0.22878151811012426
Fold 4 IBS: 0.2379701320453148
Fold 5 IBS: 0.22590294008635198
[I 2024-04-17 14:07:01,750] Trial 42 finished with value: 0.2307107187837024 and parameters: {'l1_ratio': 0.06506835223938401}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23434918927719492
Fold 2 IBS: 0.18872693722764802
Fold 3 IBS: 0.19724575076717668
Fold 4 IBS: 0.1967451375628758
Fold 5 IBS: 0.17865325722153416
[I 2024-04-17 14:07:02,474] Trial 43 finished with value: 0.1991440544112859 and parameters: {'l1_ratio': 0.14085114181946065}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23433192480145823
Fold 2 IBS: 0.1887550476219229
Fold 3 IBS: 0.1974306862978719
Fold 4 IBS: 0.19664417706605045
Fold 5 IBS: 0.1787158284511241
[I 2024-04-17 14:07:03,258] Trial 44 finished with value: 0.1991755328476855 and parameters: {'l1_ratio': 0.21067289160059371}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2342251547197731
Fold 2 IBS: 0.188729668446623
Fold 3 IBS: 0.1980076739518824
Fold 4 IBS: 0.19653898903394393
Fold 5 IBS: 0.17899668509701555
[I 2024-04-17 14:07:03,855] Trial 45 finished with value: 0.1992996342498476 and parameters: {'l1_ratio': 0.5624129529049803}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.24544920768752368
Fold 2 IBS: 0.22798459544813912
Fold 3 IBS: 0.22882458855892834
Fold 4 IBS: 0.23904274317658786
Fold 5 IBS: 0.22684861574159562
[I 2024-04-17 14:07:04,233] Trial 46 finished with value: 0.23362995012255494 and parameters: {'l1_ratio': 0.04579430891553225}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.234196851112517
Fold 2 IBS: 0.1886527792361124
Fold 3 IBS: 0.19814817252325487
Fold 4 IBS: 0.1965146693856895
Fold 5 IBS: 0.17905027222642417
[I 2024-04-17 14:07:04,901] Trial 47 finished with value: 0.19931254889679959 and parameters: {'l1_ratio': 0.7036682769982799}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2342266207639263
Fold 2 IBS: 0.18869142040594994
Fold 3 IBS: 0.1981736072001521
Fold 4 IBS: 0.19654255298731402
Fold 5 IBS: 0.17905465423148695
[I 2024-04-17 14:07:05,569] Trial 48 finished with value: 0.19933777111776588 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23428810712371723
Fold 2 IBS: 0.18872851688636047
Fold 3 IBS: 0.19783888315915996
Fold 4 IBS: 0.19659861765195266
Fold 5 IBS: 0.1788718460127691
[I 2024-04-17 14:07:06,242] Trial 49 finished with value: 0.19926519416679186 and parameters: {'l1_ratio': 0.402705511740666}. Best is trial 22 with value: 0.19912319727139485.

Fold 1 IBS: 0.23431019495683353
Fold 2 IBS: 0.1887154409415021
Fold 3 IBS: 0.1973445501084278
Fold 4 IBS: 0.1967099583590094
Fold 5 IBS: 0.17868203752508852
[I 2024-04-17 14:07:07,143] Trial 50 finished with value: 0.19915243637817226 and parameters: {'l1_ratio': 0.17526057356525065}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2344009139349268
Fold 2 IBS: 0.18875111604946618
Fold 3 IBS: 0.19717673205648287
Fold 4 IBS: 0.1967169364686223
Fold 5 IBS: 0.1786323137671258
[I 2024-04-17 14:07:07,880] Trial 51 finished with value: 0.1991356024553248 and parameters: {'l1_ratio': 0.11717503156407644}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23436473328704885
Fold 2 IBS: 0.18871667186997113
Fold 3 IBS: 0.19715488661429642
Fold 4 IBS: 0.19676177597432631
Fold 5 IBS: 0.17862265091554613
[I 2024-04-17 14:07:08,700] Trial 52 finished with value: 0.1991241437322378 and parameters: {'l1_ratio': 0.11135131087864078}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23440828110774634
Fold 2 IBS: 0.1887259403603832
Fold 3 IBS: 0.2287665565774803
Fold 4 IBS: 0.2375261520834911
Fold 5 IBS: 0.17855321813112643
[I 2024-04-17 14:07:09,323] Trial 53 finished with value: 0.21359602965204547 and parameters: {'l1_ratio': 0.07353491666177281}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23430076361030702
Fold 2 IBS: 0.18872524952661132
Fold 3 IBS: 0.19741045754329622
Fold 4 IBS: 0.19670005406454102
Fold 5 IBS: 0.17871350887817236
[I 2024-04-17 14:07:10,170] Trial 54 finished with value: 0.1991700067245856 and parameters: {'l1_ratio': 0.20020150935739411}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23432691393486396
Fold 2 IBS: 0.18868568444823192
Fold 3 IBS: 0.19750757018159878
Fold 4 IBS: 0.19663659409271206
Fold 5 IBS: 0.17875530983101873
[I 2024-04-17 14:07:10,910] Trial 55 finished with value: 0.1991824144976851 and parameters: {'l1_ratio': 0.244945043002325}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.24581907081959864
Fold 2 IBS: 0.22881752633405325
Fold 3 IBS: 0.22885259718426593
Fold 4 IBS: 0.23964520920792953
Fold 5 IBS: 0.22737619779974078
[I 2024-04-17 14:07:11,237] Trial 56 finished with value: 0.23410212026911764 and parameters: {'l1_ratio': 0.03562567283648875}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23435040730608594
Fold 2 IBS: 0.18876192799679062
Fold 3 IBS: 0.22874883419680345
Fold 4 IBS: 0.23690587310150185
Fold 5 IBS: 0.17855797633668893
[I 2024-04-17 14:07:11,945] Trial 57 finished with value: 0.21346500378757413 and parameters: {'l1_ratio': 0.08590074373612532}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23433951327842356
Fold 2 IBS: 0.18873235452317583
Fold 3 IBS: 0.19729821439977552
Fold 4 IBS: 0.19673524172006907
Fold 5 IBS: 0.1786673511652159
[I 2024-04-17 14:07:12,730] Trial 58 finished with value: 0.199154535017332 and parameters: {'l1_ratio': 0.1590669780580116}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23417088688475224
Fold 2 IBS: 0.188700943075848
Fold 3 IBS: 0.19804402435494184
Fold 4 IBS: 0.19658199378433686
Fold 5 IBS: 0.1790028641492759
[I 2024-04-17 14:07:13,463] Trial 59 finished with value: 0.19930014244983096 and parameters: {'l1_ratio': 0.6443692288191284}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23427391859236943
Fold 2 IBS: 0.18867849903564435
Fold 3 IBS: 0.1976634788030649
Fold 4 IBS: 0.19658725308798625
Fold 5 IBS: 0.1788340109815501
[I 2024-04-17 14:07:14,201] Trial 60 finished with value: 0.19920743210012298 and parameters: {'l1_ratio': 0.3180391659359798}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23440617826799023
Fold 2 IBS: 0.18875752603470258
Fold 3 IBS: 0.19717992202391896
Fold 4 IBS: 0.19672139346042783
Fold 5 IBS: 0.17863217508200577
[I 2024-04-17 14:07:15,001] Trial 61 finished with value: 0.1991394389738091 and parameters: {'l1_ratio': 0.11807314702296054}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2343348998069625
Fold 2 IBS: 0.18877920701715276
Fold 3 IBS: 0.19719067603314225
Fold 4 IBS: 0.19673640507585552
Fold 5 IBS: 0.1786317794327869
[I 2024-04-17 14:07:15,724] Trial 62 finished with value: 0.19913459347318 and parameters: {'l1_ratio': 0.12119784568517752}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23436507531538625
Fold 2 IBS: 0.18875465043691914
Fold 3 IBS: 0.19731426177327152
Fold 4 IBS: 0.1966790136358633
Fold 5 IBS: 0.17867988895322853
[I 2024-04-17 14:07:16,471] Trial 63 finished with value: 0.19915857802293374 and parameters: {'l1_ratio': 0.1654340282374526}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2459669493598767
Fold 2 IBS: 0.2291505165663387
Fold 3 IBS: 0.22886449110577123
Fold 4 IBS: 0.23988616275024424
Fold 5 IBS: 0.2275865384171104
[I 2024-04-17 14:07:16,788] Trial 64 finished with value: 0.23429093163986825 and parameters: {'l1_ratio': 0.03167919973867572}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23430439221981694
Fold 2 IBS: 0.1887298143563339
Fold 3 IBS: 0.19741280498468317
Fold 4 IBS: 0.1967029366235348
Fold 5 IBS: 0.1787137716199861
[I 2024-04-17 14:07:17,534] Trial 65 finished with value: 0.19917274396087098 and parameters: {'l1_ratio': 0.2013662270774649}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.2344257613877499
Fold 2 IBS: 0.18874685329649082
Fold 3 IBS: 0.22875070073216933
Fold 4 IBS: 0.23697829976240087
Fold 5 IBS: 0.1786001702252825
[I 2024-04-17 14:07:18,188] Trial 66 finished with value: 0.21350035708081866 and parameters: {'l1_ratio': 0.08442270929254024}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23436866510100499
Fold 2 IBS: 0.18873513037114154
Fold 3 IBS: 0.19720492358871441
Fold 4 IBS: 0.19668728173641206
Fold 5 IBS: 0.1786423648952596
[I 2024-04-17 14:07:18,882] Trial 67 finished with value: 0.1991276731385065 and parameters: {'l1_ratio': 0.1270766197409599}. Best is trial 22 with value: 0.19912319727139485.
Fold 1 IBS: 0.23437458667586286
Fold 2 IBS: 0.1887284403460712
Fold 3 IBS: 0.19716082865323495
Fold 4 IBS: 0.19669468792229503
Fold 5 IBS: 0.17862271307952363
[I 2024-04-17 14:07:19,637] Trial 68 finished with value: 0.1991162513353975 and parameters: {'l1_ratio': 0.11288124265625091}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23429018526780082
Fold 2 IBS: 0.1887531725037824
Fold 3 IBS: 0.19757257468153122
Fold 4 IBS: 0.19660165754668305
Fold 5 IBS: 0.1787795805454046
[I 2024-04-17 14:07:20,335] Trial 69 finished with value: 0.1991994341090404 and parameters: {'l1_ratio': 0.27178298079126917}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23428247104280325
Fold 2 IBS: 0.18872659931618532
Fold 3 IBS: 0.19747863766935775
Fold 4 IBS: 0.1966818298575943
Fold 5 IBS: 0.17873458482784146
[I 2024-04-17 14:07:21,023] Trial 70 finished with value: 0.19918082454275643 and parameters: {'l1_ratio': 0.2271818231982216}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2344124043473134
Fold 2 IBS: 0.18875239783882553
Fold 3 IBS: 0.19714039069321249
Fold 4 IBS: 0.19672885945451898
Fold 5 IBS: 0.1786224722291704
[I 2024-04-17 14:07:21,959] Trial 71 finished with value: 0.19913130491260816 and parameters: {'l1_ratio': 0.10520407620317028}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.24697699159432643
Fold 2 IBS: 0.23142891402247676
Fold 3 IBS: 0.22895513899906525
Fold 4 IBS: 0.24153349758119586
Fold 5 IBS: 0.2290154224843004
[I 2024-04-17 14:07:22,376] Trial 72 finished with value: 0.23558199293627294 and parameters: {'l1_ratio': 0.006343096768500811}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23443176080020775
Fold 2 IBS: 0.18874482041972213
Fold 3 IBS: 0.22876286522119546
Fold 4 IBS: 0.23740733988478205
Fold 5 IBS: 0.17859146026558825
[I 2024-04-17 14:07:23,004] Trial 73 finished with value: 0.2135876493182991 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23430321690802838
Fold 2 IBS: 0.18870649745808676
Fold 3 IBS: 0.1973399558881316
Fold 4 IBS: 0.19670424352550392
Fold 5 IBS: 0.17868154263521038
[I 2024-04-17 14:07:23,907] Trial 74 finished with value: 0.19914709128299218 and parameters: {'l1_ratio': 0.1733498469030269}. Best is trial 68 with value: 0.1991162513353975.

Fold 1 IBS: 0.23438355614879777
Fold 2 IBS: 0.18872680161678496
Fold 3 IBS: 0.22873349671415405
Fold 4 IBS: 0.1967045299911008
Fold 5 IBS: 0.1786145929779028
[I 2024-04-17 14:07:24,882] Trial 75 finished with value: 0.20543259548974807 and parameters: {'l1_ratio': 0.10106436333699645}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23432354536961464
Fold 2 IBS: 0.18878074485662752
Fold 3 IBS: 0.1972323004723012
Fold 4 IBS: 0.19672508185405035
Fold 5 IBS: 0.17865371132600033
[I 2024-04-17 14:07:25,790] Trial 76 finished with value: 0.19914307677571882 and parameters: {'l1_ratio': 0.13577605948707372}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.245346659320654
Fold 2 IBS: 0.22775355665982508
Fold 3 IBS: 0.2288172865049832
Fold 4 IBS: 0.2388757414772828
Fold 5 IBS: 0.2267019336960901
[I 2024-04-17 14:07:26,107] Trial 77 finished with value: 0.23349903553176704 and parameters: {'l1_ratio': 0.04869294464040792}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.234345222519359
Fold 2 IBS: 0.1887495802560826
Fold 3 IBS: 0.19736685078126345
Fold 4 IBS: 0.19665958370334544
Fold 5 IBS: 0.17869643143244063
[I 2024-04-17 14:07:27,039] Trial 78 finished with value: 0.1991635337384982 and parameters: {'l1_ratio': 0.18512339368041814}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.24627197730752995
Fold 2 IBS: 0.22983759521348388
Fold 3 IBS: 0.2288901975637935
Fold 4 IBS: 0.24038334673686076
Fold 5 IBS: 0.22801942125413535
[I 2024-04-17 14:07:27,405] Trial 79 finished with value: 0.2346805076151607 and parameters: {'l1_ratio': 0.023740317097176084}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23439458805194466
Fold 2 IBS: 0.1887399334989654
Fold 3 IBS: 0.22873231519444726
Fold 4 IBS: 0.19671382843059906
Fold 5 IBS: 0.17861435079815008
[I 2024-04-17 14:07:28,157] Trial 80 finished with value: 0.20543900319482128 and parameters: {'l1_ratio': 0.10260903740530293}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23438579070709656
Fold 2 IBS: 0.1887467991840082
Fold 3 IBS: 0.19721539424527793
Fold 4 IBS: 0.1967016592234103
Fold 5 IBS: 0.17864189670182365
[I 2024-04-17 14:07:29,199] Trial 81 finished with value: 0.19913830801232332 and parameters: {'l1_ratio': 0.1302777135293407}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23442501514653044
Fold 2 IBS: 0.22634459472449336
Fold 3 IBS: 0.2287776127032511
Fold 4 IBS: 0.23785922749858948
Fold 5 IBS: 0.17853624009206073
[I 2024-04-17 14:07:30,099] Trial 82 finished with value: 0.22118853803298505 and parameters: {'l1_ratio': 0.06715476522889921}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23436389285469236
Fold 2 IBS: 0.18873558167319957
Fold 3 IBS: 0.19725484111926841
Fold 4 IBS: 0.19668056203865728
Fold 5 IBS: 0.1786540266377323
[I 2024-04-17 14:07:31,071] Trial 83 finished with value: 0.19913778086470998 and parameters: {'l1_ratio': 0.14393299942151516}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23439776623680533
Fold 2 IBS: 0.18874729029282292
Fold 3 IBS: 0.19717482584194512
Fold 4 IBS: 0.19671427222377477
Fold 5 IBS: 0.17863239708207407
[I 2024-04-17 14:07:32,142] Trial 84 finished with value: 0.19913331033548448 and parameters: {'l1_ratio': 0.11664440974603944}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2343667005937274
Fold 2 IBS: 0.1887798862960534
Fold 3 IBS: 0.22874663091573497
Fold 4 IBS: 0.23681743364923558
Fold 5 IBS: 0.17858635662802455
[I 2024-04-17 14:07:32,857] Trial 85 finished with value: 0.2134594016165552 and parameters: {'l1_ratio': 0.08771830849886143}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23433816678721037
Fold 2 IBS: 0.18876305879516084
Fold 3 IBS: 0.19743474715389187
Fold 4 IBS: 0.19664958484676998
Fold 5 IBS: 0.17873162159267925
[I 2024-04-17 14:07:33,570] Trial 86 finished with value: 0.19918343583514245 and parameters: {'l1_ratio': 0.21289986931051744}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2344515639350078
Fold 2 IBS: 0.22719766035032904
Fold 3 IBS: 0.2288006048148592
Fold 4 IBS: 0.23847422640364357
Fold 5 IBS: 0.22634845273107435
[I 2024-04-17 14:07:34,068] Trial 87 finished with value: 0.2310545016469828 and parameters: {'l1_ratio': 0.05581238160846672}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2343454422845213
Fold 2 IBS: 0.18873019207249758
Fold 3 IBS: 0.19730193076851962
Fold 4 IBS: 0.1966622116528678
Fold 5 IBS: 0.17866766017514205
[I 2024-04-17 14:07:34,953] Trial 88 finished with value: 0.19914148739070966 and parameters: {'l1_ratio': 0.16050032202882855}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23439382707454412
Fold 2 IBS: 0.18874253809048122
Fold 3 IBS: 0.19717245561452784
Fold 4 IBS: 0.1967109585025447
Fold 5 IBS: 0.17863250113981757
[I 2024-04-17 14:07:35,806] Trial 89 finished with value: 0.1991304560843831 and parameters: {'l1_ratio': 0.11599084313148471}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2342678439227001
Fold 2 IBS: 0.18872389492352673
Fold 3 IBS: 0.19755747539657215
Fold 4 IBS: 0.19666693352472586
Fold 5 IBS: 0.1787777902097365
[I 2024-04-17 14:07:36,704] Trial 90 finished with value: 0.19919878759545226 and parameters: {'l1_ratio': 0.2611458107477292}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2343736313068872
Fold 2 IBS: 0.1887150394836379
Fold 3 IBS: 0.22873458697109658
Fold 4 IBS: 0.19677070822148723
Fold 5 IBS: 0.17861481344719785
[I 2024-04-17 14:07:37,508] Trial 91 finished with value: 0.20544175588606137 and parameters: {'l1_ratio': 0.09971315449377276}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2343939145126804
Fold 2 IBS: 0.1887426441196444
Fold 3 IBS: 0.1971725085271428
Fold 4 IBS: 0.19671103248901015
Fold 5 IBS: 0.17863249881124632
[I 2024-04-17 14:07:38,321] Trial 92 finished with value: 0.19913051969194479 and parameters: {'l1_ratio': 0.1160053587213441}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23430844466877904
Fold 2 IBS: 0.1887793199658759
Fold 3 IBS: 0.1972767308129475
Fold 4 IBS: 0.19671064367657218
Fold 5 IBS: 0.17866573154183824
[I 2024-04-17 14:07:39,311] Trial 93 finished with value: 0.19914817413320257 and parameters: {'l1_ratio': 0.1518968521256044}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23433844672041612
Fold 2 IBS: 0.1887410353167229
Fold 3 IBS: 0.19736252692946377
Fold 4 IBS: 0.19665375560215886
Fold 5 IBS: 0.17869601161541218
[I 2024-04-17 14:07:40,238] Trial 94 finished with value: 0.19915835523683473 and parameters: {'l1_ratio': 0.1831308734481637}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23438386454678503
Fold 2 IBS: 0.2270971388221282
Fold 3 IBS: 0.22879772708252477
Fold 4 IBS: 0.23840167639990884
Fold 5 IBS: 0.226284454833318
[I 2024-04-17 14:07:40,728] Trial 95 finished with value: 0.23099297233693297 and parameters: {'l1_ratio': 0.0571221965630183}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23424740229183058
Fold 2 IBS: 0.18873030974335975
Fold 3 IBS: 0.1976442201118493
Fold 4 IBS: 0.19664939015957833
Fold 5 IBS: 0.178806360844594
[I 2024-04-17 14:07:41,721] Trial 96 finished with value: 0.19921553663024238 and parameters: {'l1_ratio': 0.30160575326843037}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.24608379971729574
Fold 2 IBS: 0.2294136742658017
Fold 3 IBS: 0.22887415603521624
Fold 4 IBS: 0.2400765955323909
Fold 5 IBS: 0.22775251990564488
[I 2024-04-17 14:07:42,106] Trial 97 finished with value: 0.2344401490912699 and parameters: {'l1_ratio': 0.02860655076242108}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.2344098245522827
Fold 2 IBS: 0.18876200595980855
Fold 3 IBS: 0.19718214862148534
Fold 4 IBS: 0.19672450332767738
Fold 5 IBS: 0.17863207882614845
[I 2024-04-17 14:07:43,200] Trial 98 finished with value: 0.1991421122574805 and parameters: {'l1_ratio': 0.11870768094326359}. Best is trial 68 with value: 0.1991162513353975.
Fold 1 IBS: 0.23427638500507106
Fold 2 IBS: 0.18871885797313867
Fold 3 IBS: 0.19747462957430398
Fold 4 IBS: 0.1966769668639263
Fold 5 IBS: 0.1787341135107649
[I 2024-04-17 14:07:44,236] Trial 99 finished with value: 0.199176190585441 and parameters: {'l1_ratio': 0.22491073646298582}. Best is trial 68 with value: 0.1991162513353975.


* Best trial for IBS:
 FrozenTrial(number=68, state=TrialState.COMPLETE, values=[0.1991162513353975], datetime_start=datetime.datetime(2024, 4, 17, 14, 7, 18, 888658), datetime_complete=datetime.datetime(2024, 4, 17, 14, 7, 19, 637550), params={'l1_ratio': 0.11288124265625091}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=68, value=None)


* Best Score for IBS:
 0.1991162513353975

In [46]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [47]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.717
train_ibs:  0.199

#### Test

In [48]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [49]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.569

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.11288124265625091)

test_ibs:  0.262

In [50]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [51]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:07:44,894] A new study created in memory with name: no-name-601a56f6-a76f-40f5-92b4-03265b432064

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 14:07:56,467] Trial 0 finished with value: 0.7008282041264783 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7008282041264783.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.7167381974248928
[I 2024-04-17 14:08:02,137] Trial 1 finished with value: 0.7097710980423982 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7097710980423982.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.7124463519313304
[I 2024-04-17 14:08:06,091] Trial 2 finished with value: 0.7176881150982514 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:08:08,155] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:08:10,841] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.8079847908745247
Fold 5 C-index: 0.7296137339055794
[I 2024-04-17 14:08:17,817] Trial 5 finished with value: 0.7129433411057975 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7889733840304183
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 14:08:28,486] Trial 6 finished with value: 0.708319505096433 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:08:33,709] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.7081545064377682
[I 2024-04-17 14:08:49,518] Trial 8 finished with value: 0.5416309012875536 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.7167381974248928
[I 2024-04-17 14:08:56,117] Trial 9 finished with value: 0.7155876245824015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:08:56,668] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7176881150982514.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.811787072243346
Fold 5 C-index: 0.721030042918455
[I 2024-04-17 14:09:01,202] Trial 11 finished with value: 0.7198581050990792 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9946615697742256, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14395013146412383, 'warm_start': False}. Best is trial 11 with value: 0.7198581050990792.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.7124463519313304
[I 2024-04-17 14:09:04,684] Trial 12 finished with value: 0.7190983430763026 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8486887300949394, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1611753146667314, 'warm_start': False}. Best is trial 11 with value: 0.7198581050990792.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.723175965665236
[I 2024-04-17 14:09:07,447] Trial 13 finished with value: 0.7204513708045972 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 92, 'oob_score': False, 'max_samples': 0.8350722272141606, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1591074208868987, 'warm_start': False}. Best is trial 13 with value: 0.7204513708045972.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:09:08,963] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.12081912190592481, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13141808331049987, 'warm_start': True}. Best is trial 13 with value: 0.7204513708045972.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.779467680608365

Fold 5 C-index: 0.723175965665236
[I 2024-04-17 14:09:10,124] Trial 15 finished with value: 0.720046173250796 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.8172106754568015, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': False}. Best is trial 13 with value: 0.7204513708045972.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.6
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6673819742489271
[I 2024-04-17 14:09:10,466] Trial 16 finished with value: 0.667554300810756 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 4, 'oob_score': False, 'max_samples': 0.8031165510675999, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37909912926450273, 'warm_start': False}. Best is trial 13 with value: 0.7204513708045972.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7538759689922481
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.7467811158798283
[I 2024-04-17 14:09:12,176] Trial 17 finished with value: 0.7126509368239871 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 77, 'oob_score': False, 'max_samples': 0.4976948984753373, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23092307811767449, 'warm_start': False}. Best is trial 13 with value: 0.7204513708045972.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.811787072243346
Fold 5 C-index: 0.8154506437768241
[I 2024-04-17 14:09:13,498] Trial 18 finished with value: 0.7760423666153204 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.7251663359279349, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07958856082174798, 'warm_start': True}. Best is trial 18 with value: 0.7760423666153204.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7965779467680608
Fold 5 C-index: 0.8283261802575107
[I 2024-04-17 14:09:14,888] Trial 19 finished with value: 0.7730440762775934 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.6699202158763117, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10237905029177659, 'warm_start': True}. Best is trial 18 with value: 0.7760423666153204.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.8154506437768241
[I 2024-04-17 14:09:16,522] Trial 20 finished with value: 0.7724859805897759 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.6900047169915593, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08335730674180963, 'warm_start': True}. Best is trial 18 with value: 0.7760423666153204.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.8154506437768241
[I 2024-04-17 14:09:18,084] Trial 21 finished with value: 0.7748221677560045 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 113, 'oob_score': True, 'max_samples': 0.6876137083450079, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0587391455650732, 'warm_start': True}. Best is trial 18 with value: 0.7760423666153204.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.8111587982832618
[I 2024-04-17 14:09:21,217] Trial 22 finished with value: 0.7659626316282286 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.5591736375489325, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07918224002301208, 'warm_start': True}. Best is trial 18 with value: 0.7760423666153204.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.7832618025751072
[I 2024-04-17 14:09:23,099] Trial 23 finished with value: 0.7306996043294393 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.39734452155349825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 18 with value: 0.7760423666153204.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.7467811158798283
[I 2024-04-17 14:09:24,209] Trial 24 finished with value: 0.7674590565887007 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 57, 'oob_score': True, 'max_samples': 0.6661492942805792, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08160258365132947, 'warm_start': True}. Best is trial 18 with value: 0.7760423666153204.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7889733840304183
Fold 5 C-index: 0.8154506437768241
[I 2024-04-17 14:09:25,925] Trial 25 finished with value: 0.7766807344962124 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.7383769916209949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06050235008924422, 'warm_start': True}. Best is trial 25 with value: 0.7766807344962124.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.8025751072961373
[I 2024-04-17 14:09:28,061] Trial 26 finished with value: 0.7764302339224767 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.7475994771535035, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 25 with value: 0.7766807344962124.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7965779467680608
Fold 5 C-index: 0.8068669527896996
[I 2024-04-17 14:09:30,567] Trial 27 finished with value: 0.777379210577212 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.7559201623663098, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04810535800309272, 'warm_start': True}. Best is trial 27 with value: 0.777379210577212.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.8025751072961373
[I 2024-04-17 14:09:33,846] Trial 28 finished with value: 0.7746738551821188 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.7504152447230351, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03325721334872854, 'warm_start': True}. Best is trial 27 with value: 0.777379210577212.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.7939914163090128
[I 2024-04-17 14:09:36,630] Trial 29 finished with value: 0.7755971916850679 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.8645982519832335, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.195620523179365, 'warm_start': True}. Best is trial 27 with value: 0.777379210577212.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:09:38,656] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.760159147741993, 'max_features': None, 'min_weight_fraction_leaf': 0.41069818790111035, 'warm_start': True}. Best is trial 27 with value: 0.777379210577212.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.7982832618025751
[I 2024-04-17 14:09:41,416] Trial 31 finished with value: 0.7732136512981864 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.7844685228092624, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05627888575582617, 'warm_start': True}. Best is trial 27 with value: 0.777379210577212.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8155893536121673
Fold 5 C-index: 0.8283261802575107
[I 2024-04-17 14:09:43,512] Trial 32 finished with value: 0.7810800578447965 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 148, 'oob_score': True, 'max_samples': 0.7491610353975477, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0037800024178660865, 'warm_start': True}. Best is trial 32 with value: 0.7810800578447965.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8369098712446352
[I 2024-04-17 14:09:46,202] Trial 33 finished with value: 0.7839905003125922 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.8869032190551784, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003781846979666846, 'warm_start': True}. Best is trial 33 with value: 0.7839905003125922.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8412017167381974
[I 2024-04-17 14:09:49,628] Trial 34 finished with value: 0.7814662330427102 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.8557081235361716, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002606059702277188, 'warm_start': True}. Best is trial 33 with value: 0.7839905003125922.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8369098712446352
[I 2024-04-17 14:09:52,740] Trial 35 finished with value: 0.783052553271793 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.9080645029440096, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0018298533674900239, 'warm_start': True}. Best is trial 33 with value: 0.7839905003125922.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8650190114068441
Fold 5 C-index: 0.8497854077253219
[I 2024-04-17 14:09:56,669] Trial 36 finished with value: 0.7828932539665227 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.8814421827962158, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 33 with value: 0.7839905003125922.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8612167300380228
Fold 5 C-index: 0.8497854077253219
[I 2024-04-17 14:10:01,029] Trial 37 finished with value: 0.7829622425719912 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.9033809144429317, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0015662491608526554, 'warm_start': True}. Best is trial 33 with value: 0.7839905003125922.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:10:05,856] Trial 38 finished with value: 0.7842367257114262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 375, 'oob_score': True, 'max_samples': 0.9054934637093376, 'max_features': None, 'min_weight_fraction_leaf': 0.11256019847675, 'warm_start': True}. Best is trial 38 with value: 0.7842367257114262.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8612167300380228
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:10:11,749] Trial 39 finished with value: 0.7891007610714513 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 395, 'oob_score': True, 'max_samples': 0.9213735536200489, 'max_features': None, 'min_weight_fraction_leaf': 0.11634525026550895, 'warm_start': True}. Best is trial 39 with value: 0.7891007610714513.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:10:16,733] Trial 40 finished with value: 0.7883733607709722 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 395, 'oob_score': True, 'max_samples': 0.9988577270580707, 'max_features': None, 'min_weight_fraction_leaf': 0.10850977602008305, 'warm_start': True}. Best is trial 39 with value: 0.7891007610714513.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:10:22,223] Trial 41 finished with value: 0.7883733607709722 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.9998994857543887, 'max_features': None, 'min_weight_fraction_leaf': 0.11326817389095635, 'warm_start': True}. Best is trial 39 with value: 0.7891007610714513.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8231939163498099
Fold 5 C-index: 0.8454935622317596
[I 2024-04-17 14:10:27,584] Trial 42 finished with value: 0.7737779606091751 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.9881149833245676, 'max_features': None, 'min_weight_fraction_leaf': 0.18716966099632062, 'warm_start': True}. Best is trial 39 with value: 0.7891007610714513.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.8111587982832618
[I 2024-04-17 14:10:33,193] Trial 43 finished with value: 0.7749427844262151 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 395, 'oob_score': True, 'max_samples': 0.9388551492979577, 'max_features': None, 'min_weight_fraction_leaf': 0.2572557196708605, 'warm_start': True}. Best is trial 39 with value: 0.7891007610714513.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.876425855513308
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:10:39,479] Trial 44 finished with value: 0.7986549219483811 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 471, 'oob_score': True, 'max_samples': 0.948808274172012, 'max_features': None, 'min_weight_fraction_leaf': 0.11527878914787343, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8726235741444867
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:10:45,312] Trial 45 finished with value: 0.7947288336291553 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.9998750375957942, 'max_features': None, 'min_weight_fraction_leaf': 0.11815124841300996, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8346007604562737
Fold 5 C-index: 0.8454935622317596
[I 2024-04-17 14:10:51,490] Trial 46 finished with value: 0.7753167677622472 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.9655515068674165, 'max_features': None, 'min_weight_fraction_leaf': 0.17161779867163243, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:10:56,860] Trial 47 finished with value: 0.785156778146682 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 449, 'oob_score': True, 'max_samples': 0.9514188134169226, 'max_features': None, 'min_weight_fraction_leaf': 0.13273635436705447, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8626609442060086
[I 2024-04-17 14:11:02,382] Trial 48 finished with value: 0.7891517280845415 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 484, 'oob_score': True, 'max_samples': 0.9886971208804156, 'max_features': None, 'min_weight_fraction_leaf': 0.10999216096014283, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.651394422310757
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7723404255319148
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.8133047210300429
[I 2024-04-17 14:11:07,881] Trial 49 finished with value: 0.7532940811338732 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 488, 'oob_score': True, 'max_samples': 0.9329723888343817, 'max_features': None, 'min_weight_fraction_leaf': 0.13143062694507274, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.8111587982832618
[I 2024-04-17 14:11:13,835] Trial 50 finished with value: 0.7773473929337597 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 462, 'oob_score': True, 'max_samples': 0.9666166130505479, 'max_features': None, 'min_weight_fraction_leaf': 0.21890451519522972, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8422053231939164
Fold 5 C-index: 0.8626609442060086
[I 2024-04-17 14:11:19,248] Trial 51 finished with value: 0.7785694364538458 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.9942712269123081, 'max_features': None, 'min_weight_fraction_leaf': 0.10760207735121173, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:11:25,849] Trial 52 finished with value: 0.7779303975072737 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 471, 'oob_score': True, 'max_samples': 0.9283988047550052, 'max_features': None, 'min_weight_fraction_leaf': 0.14911604550311863, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8384030418250951
Fold 5 C-index: 0.8497854077253219
[I 2024-04-17 14:11:30,491] Trial 53 finished with value: 0.7793044124311815 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.9966347907204837, 'max_features': None, 'min_weight_fraction_leaf': 0.1769969783833071, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8454935622317596
[I 2024-04-17 14:11:36,422] Trial 54 finished with value: 0.7815967779978873 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.829198859957719, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09791679487924128, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.8068669527896996
[I 2024-04-17 14:11:39,163] Trial 55 finished with value: 0.7690829867857671 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.9636894445071732, 'max_features': None, 'min_weight_fraction_leaf': 0.2886607381144328, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 14:11:51,825] Trial 56 finished with value: 0.6962632302958052 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.9176948884887206, 'max_features': None, 'min_weight_fraction_leaf': 0.14110886582173582, 'warm_start': False}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:11:58,191] Trial 57 finished with value: 0.7869530942861939 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 473, 'oob_score': True, 'max_samples': 0.9991060130673742, 'max_features': None, 'min_weight_fraction_leaf': 0.12183573082171431, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8346007604562737
Fold 5 C-index: 0.8454935622317596
[I 2024-04-17 14:12:00,505] Trial 58 finished with value: 0.7794203468485082 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.880446677909093, 'max_features': None, 'min_weight_fraction_leaf': 0.1581009003511888, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.7510729613733905
[I 2024-04-17 14:12:10,359] Trial 59 finished with value: 0.7392061237359553 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 374, 'oob_score': True, 'max_samples': 0.3136523402046788, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09588345651084344, 'warm_start': False}. Best is trial 44 with value: 0.7986549219483811.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:12:14,873] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.13319246988341354, 'max_features': None, 'min_weight_fraction_leaf': 0.06919201617271206, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8612167300380228
Fold 5 C-index: 0.8497854077253219
[I 2024-04-17 14:12:21,285] Trial 61 finished with value: 0.7867030175555142 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 467, 'oob_score': True, 'max_samples': 0.9667021035639505, 'max_features': None, 'min_weight_fraction_leaf': 0.12168844115545442, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8536121673003803
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:12:27,741] Trial 62 finished with value: 0.7852868992588029 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.9909255399113079, 'max_features': None, 'min_weight_fraction_leaf': 0.1247577442171287, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8688212927756654
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:12:34,840] Trial 63 finished with value: 0.7938382562432701 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 473, 'oob_score': True, 'max_samples': 0.9416964082577167, 'max_features': None, 'min_weight_fraction_leaf': 0.03523974552630588, 'warm_start': True}. Best is trial 44 with value: 0.7986549219483811.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8802281368821293
Fold 5 C-index: 0.8626609442060086
[I 2024-04-17 14:12:40,384] Trial 64 finished with value: 0.800230509419749 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.9340425349060235, 'max_features': None, 'min_weight_fraction_leaf': 0.03384338624965312, 'warm_start': True}. Best is trial 64 with value: 0.800230509419749.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9106463878326996
Fold 5 C-index: 0.8841201716738197
[I 2024-04-17 14:12:45,653] Trial 65 finished with value: 0.8244455110085529 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 418, 'oob_score': True, 'max_samples': 0.8446058811158439, 'max_features': None, 'min_weight_fraction_leaf': 0.022674617805812716, 'warm_start': True}. Best is trial 65 with value: 0.8244455110085529.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:12:51,923] Trial 66 finished with value: 0.8345503823766958 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 438, 'oob_score': True, 'max_samples': 0.8495184549027122, 'max_features': None, 'min_weight_fraction_leaf': 0.023881627072705698, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8927038626609443
[I 2024-04-17 14:12:55,190] Trial 67 finished with value: 0.8304689730708803 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 416, 'oob_score': False, 'max_samples': 0.8055695127054889, 'max_features': None, 'min_weight_fraction_leaf': 0.0329260788264709, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:12:58,956] Trial 68 finished with value: 0.8313343505822968 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.7958669068874025, 'max_features': None, 'min_weight_fraction_leaf': 0.029076572805012874, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.721030042918455
[I 2024-04-17 14:13:09,149] Trial 69 finished with value: 0.7156298410822198 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.7863192088261158, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021405969747331416, 'warm_start': False}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:13:11,973] Trial 70 finished with value: 0.8256693707194621 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.6252712550001975, 'max_features': None, 'min_weight_fraction_leaf': 0.02417037348589839, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8841201716738197
[I 2024-04-17 14:13:15,063] Trial 71 finished with value: 0.8240326507414419 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.6316554714729948, 'max_features': None, 'min_weight_fraction_leaf': 0.030594879046112848, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:13:18,826] Trial 72 finished with value: 0.8265204345492494 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.6280411143639701, 'max_features': None, 'min_weight_fraction_leaf': 0.023595254611073188, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:13:22,444] Trial 73 finished with value: 0.8241337206472483 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.5856132855983748, 'max_features': None, 'min_weight_fraction_leaf': 0.0250659979067216, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:13:25,757] Trial 74 finished with value: 0.8256693707194621 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.6242387890502427, 'max_features': None, 'min_weight_fraction_leaf': 0.02054557365066301, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.871244635193133
[I 2024-04-17 14:13:29,534] Trial 75 finished with value: 0.81749882299585 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.5678692893456054, 'max_features': None, 'min_weight_fraction_leaf': 0.021715340803886724, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:13:32,988] Trial 76 finished with value: 0.8079052755496573 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.5917750656718981, 'max_features': None, 'min_weight_fraction_leaf': 0.04665395409416433, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:13:36,419] Trial 77 finished with value: 0.7982057052060303 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.4846612666306126, 'max_features': None, 'min_weight_fraction_leaf': 0.016763026021916767, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8688212927756654
Fold 5 C-index: 0.8497854077253219
[I 2024-04-17 14:13:38,535] Trial 78 finished with value: 0.7862179149093231 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.532567568435676, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06849392053593935, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:13:41,480] Trial 79 finished with value: 0.8266588520375043 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 416, 'oob_score': False, 'max_samples': 0.7018494763385984, 'max_features': None, 'min_weight_fraction_leaf': 0.042454333996327726, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8798283261802575
[I 2024-04-17 14:13:44,405] Trial 80 finished with value: 0.8152794343673218 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 379, 'oob_score': False, 'max_samples': 0.6971181712296595, 'max_features': None, 'min_weight_fraction_leaf': 0.04525611328489093, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:13:47,593] Trial 81 finished with value: 0.8265204345492494 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.6302445102036108, 'max_features': None, 'min_weight_fraction_leaf': 0.019343032337071193, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.871244635193133
[I 2024-04-17 14:13:50,339] Trial 82 finished with value: 0.8230364314186271 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.6270165680525538, 'max_features': None, 'min_weight_fraction_leaf': 0.015698677240256323, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8802281368821293
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:13:53,021] Trial 83 finished with value: 0.799393759271591 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.6599506156093816, 'max_features': None, 'min_weight_fraction_leaf': 0.06564568225072917, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8927038626609443
[I 2024-04-17 14:13:56,002] Trial 84 finished with value: 0.828136102840868 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'max_samples': 0.7019144088034109, 'max_features': None, 'min_weight_fraction_leaf': 0.04122801035588532, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8755364806866953
[I 2024-04-17 14:13:58,919] Trial 85 finished with value: 0.8175719597893856 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.7122097452393518, 'max_features': None, 'min_weight_fraction_leaf': 0.04207146535922428, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.8497854077253219
[I 2024-04-17 14:14:01,481] Trial 86 finished with value: 0.7864897375773919 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.6157631061994502, 'max_features': None, 'min_weight_fraction_leaf': 0.08243401157835789, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.721030042918455
[I 2024-04-17 14:14:10,416] Trial 87 finished with value: 0.7149977940840648 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.6460066260905444, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05559626251289447, 'warm_start': False}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:14:12,891] Trial 88 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.5295320338879155, 'max_features': None, 'min_weight_fraction_leaf': 0.4978507265200673, 'warm_start': True}. Best is trial 66 with value: 0.8345503823766958.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:14:16,566] Trial 89 finished with value: 0.8377555279782554 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.8033377717782966, 'max_features': None, 'min_weight_fraction_leaf': 0.01402489143929412, 'warm_start': True}. Best is trial 89 with value: 0.8377555279782554.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9315589353612167
Fold 5 C-index: 0.9141630901287554
[I 2024-04-17 14:14:19,273] Trial 90 finished with value: 0.8385774300491547 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8036432492984903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.011849120996884583, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:14:21,747] Trial 91 finished with value: 0.8313306591058091 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.7788054931995144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.038378841215117476, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8841201716738197
[I 2024-04-17 14:14:24,116] Trial 92 finished with value: 0.827984082356233 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.7986687062661717, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.039004141128624666, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8841201716738197
[I 2024-04-17 14:14:26,598] Trial 93 finished with value: 0.8287445386299972 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.8028169577485633, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.038782965656716406, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8841201716738197
[I 2024-04-17 14:14:28,796] Trial 94 finished with value: 0.8271656506566746 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 333, 'oob_score': False, 'max_samples': 0.8042526478673692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.043310076016989205, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:14:31,896] Trial 95 finished with value: 0.799517045686186 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8085728356552186, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07339640948586423, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.871244635193133
[I 2024-04-17 14:14:34,040] Trial 96 finished with value: 0.8149530801965099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 290, 'oob_score': False, 'max_samples': 0.7750021666896956, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05537405216097899, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:14:36,667] Trial 97 finished with value: 0.7957069082185483 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.8211398568655293, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09176142523438077, 'warm_start': True}. Best is trial 90 with value: 0.8385774300491547.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9098712446351931
[I 2024-04-17 14:14:39,706] Trial 98 finished with value: 0.8386607323362524 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.7345514773225368, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010983857117523536, 'warm_start': True}. Best is trial 98 with value: 0.8386607323362524.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.9277566539923955

[I 2024-04-17 14:14:42,305] A new study created in memory with name: no-name-d7909110-ce3d-4275-9b74-800d6e9b169a

Fold 5 C-index: 0.9098712446351931
[I 2024-04-17 14:14:42,280] Trial 99 finished with value: 0.8411054216640477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.7347203615160294, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.009228383305913348, 'warm_start': True}. Best is trial 99 with value: 0.8411054216640477.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.8411054216640477], datetime_start=datetime.datetime(2024, 4, 17, 14, 14, 39, 712893), datetime_complete=datetime.datetime(2024, 4, 17, 14, 14, 42, 279521), params={'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.7347203615160294, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.009228383305913348, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=99, value=None)


* Best Score for C-index:
 0.8411054216640477

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2102043288114331
Fold 2 IBS: 0.1807887562051505
Fold 3 IBS: 0.23782055019071674
Fold 4 IBS: 0.2087896104379427
Fold 5 IBS: 0.21531375946427117
[I 2024-04-17 14:14:50,663] Trial 0 finished with value: 0.21058340102190284 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21058340102190284.
Fold 1 IBS: 0.2190216333557402
Fold 2 IBS: 0.18870205623284697
Fold 3 IBS: 0.20230823566347436
Fold 4 IBS: 0.1996204222708952
Fold 5 IBS: 0.19567393381020678
[I 2024-04-17 14:14:53,106] Trial 1 finished with value: 0.20106525626663269 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20106525626663269.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-17 14:14:54,952] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20106525626663269.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-17 14:15:01,282] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20106525626663269.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-17 14:15:05,739] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20106525626663269.
Fold 1 IBS: 0.22390627390313256
Fold 2 IBS: 0.1849650171096094
Fold 3 IBS: 0.21100057898663394
Fold 4 IBS: 0.18376769771621682
Fold 5 IBS: 0.1867210692746838
[I 2024-04-17 14:15:11,684] Trial 5 finished with value: 0.1980721273980553 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.2085590938373763
Fold 2 IBS: 0.19298462842165104
Fold 3 IBS: 0.2517028500594773
Fold 4 IBS: 0.20183713995561461
Fold 5 IBS: 0.2131360164839383
[I 2024-04-17 14:15:17,594] Trial 6 finished with value: 0.2136439457516115 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.2390702008198702
Fold 2 IBS: 0.22489679991029116
Fold 3 IBS: 0.2259303948204604
Fold 4 IBS: 0.23185979986642452
Fold 5 IBS: 0.22331888852904894
[I 2024-04-17 14:15:24,875] Trial 7 finished with value: 0.22901521678921904 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-17 14:15:36,226] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.21770726021802314
Fold 2 IBS: 0.1926183200645422
Fold 3 IBS: 0.19692874775515612
Fold 4 IBS: 0.20396248686300955
Fold 5 IBS: 0.1996508393676255
[I 2024-04-17 14:15:38,814] Trial 9 finished with value: 0.20217353085367132 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-17 14:15:52,349] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.22560371341744562
Fold 2 IBS: 0.18806245234664268
Fold 3 IBS: 0.19823831740252298
Fold 4 IBS: 0.20359706196578892
Fold 5 IBS: 0.19709434913443796
[I 2024-04-17 14:15:55,451] Trial 11 finished with value: 0.20251917885336762 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.24434728711372863
Fold 2 IBS: 0.17564025520531187
Fold 3 IBS: 0.1964344785230259
Fold 4 IBS: 0.20066504741276348
Fold 5 IBS: 0.2042937255015592
[I 2024-04-17 14:15:56,275] Trial 12 finished with value: 0.2042761587512778 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.21216102198148995
Fold 2 IBS: 0.18919601933384075
Fold 3 IBS: 0.2066327760052573
Fold 4 IBS: 0.1939715053581915
Fold 5 IBS: 0.19090321273082206
[I 2024-04-17 14:16:02,798] Trial 13 finished with value: 0.1985729070819203 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.6258340703868753, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1381576993491155}. Best is trial 5 with value: 0.1980721273980553.
Fold 1 IBS: 0.21249195532933093
Fold 2 IBS: 0.1898752295867087
Fold 3 IBS: 0.20397648370856328
Fold 4 IBS: 0.19540137063940666
Fold 5 IBS: 0.18838446196326458
[I 2024-04-17 14:16:09,118] Trial 14 finished with value: 0.19802590024545483 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.3504269596884479, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06379307425059985}. Best is trial 14 with value: 0.19802590024545483.
Fold 1 IBS: 0.2123189701249148
Fold 2 IBS: 0.1925883129708542
Fold 3 IBS: 0.20573326739783718
Fold 4 IBS: 0.2006951268596476
Fold 5 IBS: 0.1907107426979207
[I 2024-04-17 14:16:16,289] Trial 15 finished with value: 0.2004092840102349 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.29884410326021704, 'max_features': 'log2', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 14 with value: 0.19802590024545483.

Fold 1 IBS: 0.22692065812616447
Fold 2 IBS: 0.21206769226916225
Fold 3 IBS: 0.2156838785290527
Fold 4 IBS: 0.21751128610517312
Fold 5 IBS: 0.20651691315558138
[I 2024-04-17 14:16:20,659] Trial 16 finished with value: 0.21574008563702676 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 207, 'oob_score': False, 'max_samples': 0.18676357459308748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08290882329946764}. Best is trial 14 with value: 0.19802590024545483.
Fold 1 IBS: 0.24663170760567513
Fold 2 IBS: 0.2323870797941858
Fold 3 IBS: 0.22958416300292336
Fold 4 IBS: 0.24138875984302413
Fold 5 IBS: 0.23032206247962175
[I 2024-04-17 14:16:26,703] Trial 17 finished with value: 0.23606275454508605 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.43542441691728756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 14 with value: 0.19802590024545483.
Fold 1 IBS: 0.21881474055605862
Fold 2 IBS: 0.18547633539682304
Fold 3 IBS: 0.20656928960283655
Fold 4 IBS: 0.18457460523523875
Fold 5 IBS: 0.1874811230898664
[I 2024-04-17 14:16:39,326] Trial 18 finished with value: 0.19658321877616466 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 427, 'oob_score': True, 'max_samples': 0.4182008755315777, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 18 with value: 0.19658321877616466.
Fold 1 IBS: 0.2190564402081514
Fold 2 IBS: 0.188087384218288
Fold 3 IBS: 0.20027037422611715
Fold 4 IBS: 0.18998842673109817
Fold 5 IBS: 0.18619636671454978
[I 2024-04-17 14:16:50,415] Trial 19 finished with value: 0.19671979841964088 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 421, 'oob_score': True, 'max_samples': 0.32716882378018636, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04236939612720242}. Best is trial 18 with value: 0.19658321877616466.
Fold 1 IBS: 0.21760377375677656
Fold 2 IBS: 0.1919866250125153
Fold 3 IBS: 0.1994311682850577
Fold 4 IBS: 0.19344693614799174
Fold 5 IBS: 0.18848306798857528
[I 2024-04-17 14:17:03,565] Trial 20 finished with value: 0.1981903142381833 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.23419761201309758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02932816021927626}. Best is trial 18 with value: 0.19658321877616466.
Fold 1 IBS: 0.2187364828729307
Fold 2 IBS: 0.18570116810153495
Fold 3 IBS: 0.20579682392692403
Fold 4 IBS: 0.18451525957304432
Fold 5 IBS: 0.18672553972768577
[I 2024-04-17 14:17:14,761] Trial 21 finished with value: 0.19629505484042398 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 418, 'oob_score': True, 'max_samples': 0.4083052793728847, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055733491992129076}. Best is trial 21 with value: 0.19629505484042398.
Fold 1 IBS: 0.2148776080007169
Fold 2 IBS: 0.18589632387757568
Fold 3 IBS: 0.20583906879200672
Fold 4 IBS: 0.19198285372084095
Fold 5 IBS: 0.18966630127598744
[I 2024-04-17 14:17:26,301] Trial 22 finished with value: 0.1976524311334255 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 424, 'oob_score': True, 'max_samples': 0.4489358259619997, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10311631329898263}. Best is trial 21 with value: 0.19629505484042398.
Fold 1 IBS: 0.2195276294815096
Fold 2 IBS: 0.18746841039112355
Fold 3 IBS: 0.2041899426449591
Fold 4 IBS: 0.18395365830619403
Fold 5 IBS: 0.187112855303304
[I 2024-04-17 14:17:38,300] Trial 23 finished with value: 0.19645049922541807 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.37300104376030563, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.044499398714530014}. Best is trial 21 with value: 0.19629505484042398.
Fold 1 IBS: 0.21884442571529134
Fold 2 IBS: 0.2021812788389083
Fold 3 IBS: 0.21231270668511018
Fold 4 IBS: 0.20640803781328734
Fold 5 IBS: 0.19848257323904545
[I 2024-04-17 14:17:48,801] Trial 24 finished with value: 0.20764580445832853 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.41924101495562033, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17316288716343614}. Best is trial 21 with value: 0.19629505484042398.
Fold 1 IBS: 0.24617409986767202
Fold 2 IBS: 0.23220310997315666
Fold 3 IBS: 0.2294334113300275
Fold 4 IBS: 0.24157148532206885
Fold 5 IBS: 0.21241482781916313
[I 2024-04-17 14:18:00,942] Trial 25 finished with value: 0.23235938686241764 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 463, 'oob_score': True, 'max_samples': 0.4805708985439409, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2353566663168092}. Best is trial 21 with value: 0.19629505484042398.
Fold 1 IBS: 0.2153359487584027
Fold 2 IBS: 0.185613429495983
Fold 3 IBS: 0.2012976940812754
Fold 4 IBS: 0.18846188635254363
Fold 5 IBS: 0.18293117638833895
[I 2024-04-17 14:18:11,466] Trial 26 finished with value: 0.19472802701530875 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.2106576337639432, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04105835602710747}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.245862074498824
Fold 2 IBS: 0.232133559935509
Fold 3 IBS: 0.23015563458545543
Fold 4 IBS: 0.24127484718020611
Fold 5 IBS: 0.23015417308711794
[I 2024-04-17 14:18:21,767] Trial 27 finished with value: 0.2359160578574225 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.15130066111462132, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10784864417124447}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2147127329276155
Fold 2 IBS: 0.18915927460137008
Fold 3 IBS: 0.20138188056447207
Fold 4 IBS: 0.19412122965078105
Fold 5 IBS: 0.189717207344614
[I 2024-04-17 14:18:31,795] Trial 28 finished with value: 0.1978184650177705 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 387, 'oob_score': True, 'max_samples': 0.26154064534881144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02713013980424927}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.24632883572900457
Fold 2 IBS: 0.23224359394586241
Fold 3 IBS: 0.23009838187867598
Fold 4 IBS: 0.24120474591709296
Fold 5 IBS: 0.23016994528826507
[I 2024-04-17 14:18:40,820] Trial 29 finished with value: 0.2360091005517802 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.23884398326654083, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19732369509207953}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21716524020443764
Fold 2 IBS: 0.19430165052524462
Fold 3 IBS: 0.20158565058707717
Fold 4 IBS: 0.20210267645926885
Fold 5 IBS: 0.19188907306377254
[I 2024-04-17 14:18:48,344] Trial 30 finished with value: 0.20140885816796014 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 334, 'oob_score': True, 'max_samples': 0.1847402094137134, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0019497906788698074}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21854306589903388
Fold 2 IBS: 0.18358501451609627
Fold 3 IBS: 0.20598889392344666
Fold 4 IBS: 0.18474092896902128

Fold 5 IBS: 0.18616608441835306
[I 2024-04-17 14:18:59,406] Trial 31 finished with value: 0.19580479754519023 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.3742524669147902, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.058072702675878746}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21680042114818004
Fold 2 IBS: 0.18633469852302703
Fold 3 IBS: 0.20579918371614245
Fold 4 IBS: 0.1907081836641897
Fold 5 IBS: 0.18824112277850577
[I 2024-04-17 14:19:09,871] Trial 32 finished with value: 0.197576721966009 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.3792544247914643, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08827452661142118}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21340885426989026
Fold 2 IBS: 0.19249546980979154
Fold 3 IBS: 0.20635099548953367
Fold 4 IBS: 0.1979657246461944
Fold 5 IBS: 0.1938939464753035
[I 2024-04-17 14:19:20,634] Trial 33 finished with value: 0.2008229981381427 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.4893475927346802, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1516942164957436}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.23814950798080808
Fold 2 IBS: 0.1863613127632771
Fold 3 IBS: 0.22723951430017747
Fold 4 IBS: 0.18944403920770272
Fold 5 IBS: 0.20351468792066657
[I 2024-04-17 14:19:33,998] Trial 34 finished with value: 0.20894181243452636 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.3731318631373402, 'max_features': None, 'min_weight_fraction_leaf': 0.036851118012920084}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2461694058931825
Fold 2 IBS: 0.23225147430918527
Fold 3 IBS: 0.22972816301527224
Fold 4 IBS: 0.24136133269198848
Fold 5 IBS: 0.23039203898311741
[I 2024-04-17 14:19:45,704] Trial 35 finished with value: 0.23598048297854918 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.2717132398533613, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1717544381346019}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22127322759082121
Fold 2 IBS: 0.18817282228893922
Fold 3 IBS: 0.20104231209902237
Fold 4 IBS: 0.1931693561969045
Fold 5 IBS: 0.18918668128559316
[I 2024-04-17 14:19:52,112] Trial 36 finished with value: 0.19856887989225608 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.5503644695740508, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10310384633131614}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.24950826880472254
Fold 2 IBS: 0.18856162603285437
Fold 3 IBS: 0.22451139530910216
Fold 4 IBS: 0.1977867955529262
Fold 5 IBS: 0.2020315813216362
[I 2024-04-17 14:20:03,426] Trial 37 finished with value: 0.21247993340424828 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.6134779412492984, 'max_features': None, 'min_weight_fraction_leaf': 0.053624327533504934}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.24616915000906578
Fold 2 IBS: 0.23222225397286284
Fold 3 IBS: 0.22951253927531856
Fold 4 IBS: 0.24148871528907226
Fold 5 IBS: 0.23026574963067495
[I 2024-04-17 14:20:15,127] Trial 38 finished with value: 0.23593168163539885 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 449, 'oob_score': True, 'max_samples': 0.501036510723255, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21461458109876938
Fold 2 IBS: 0.188204232499965
Fold 3 IBS: 0.2047756433523795
Fold 4 IBS: 0.19316724130667273
Fold 5 IBS: 0.1868804621811678
[I 2024-04-17 14:20:24,564] Trial 39 finished with value: 0.1975284320877909 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 402, 'oob_score': True, 'max_samples': 0.3543289565036298, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07650931366535661}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22346494811757328
Fold 2 IBS: 0.18195777972867497
Fold 3 IBS: 0.2055034131544804
Fold 4 IBS: 0.1911812829253941
Fold 5 IBS: 0.19545468167081193
[I 2024-04-17 14:20:33,595] Trial 40 finished with value: 0.19951242111938694 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.1379216899482924, 'max_features': None, 'min_weight_fraction_leaf': 0.024686558616577252}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2462386080521047
Fold 2 IBS: 0.23227226980918256
Fold 3 IBS: 0.22979453828851176
Fold 4 IBS: 0.24148073524023875
Fold 5 IBS: 0.23035642285290572
[I 2024-04-17 14:20:44,005] Trial 41 finished with value: 0.2360285148485887 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.40677659613723144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49366996466795}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22213699289906183
Fold 2 IBS: 0.19262685771001906
Fold 3 IBS: 0.20085228509218442
Fold 4 IBS: 0.19758489051797906
Fold 5 IBS: 0.19262321190152334
[I 2024-04-17 14:20:58,550] Trial 42 finished with value: 0.20116484762415357 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.30210397668236244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05313129636952871}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2462227191802105
Fold 2 IBS: 0.23214971991692446
Fold 3 IBS: 0.22959726215964507
Fold 4 IBS: 0.24147715121017269
Fold 5 IBS: 0.2302941351789007
[I 2024-04-17 14:21:13,579] Trial 43 finished with value: 0.23594819752917068 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.5863397484404475, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41190911385432105}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.218244715768343
Fold 2 IBS: 0.18579650093297204
Fold 3 IBS: 0.20571371481176473
Fold 4 IBS: 0.18990928125430567
Fold 5 IBS: 0.18736735563785747
[I 2024-04-17 14:21:27,269] Trial 44 finished with value: 0.19740631368104858 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.5204066826422848, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11677033230689388}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2195229409277238
Fold 2 IBS: 0.18386714631547418
Fold 3 IBS: 0.20623545128011705
Fold 4 IBS: 0.18437642735737744
Fold 5 IBS: 0.1861870136049103
[I 2024-04-17 14:21:44,076] Trial 45 finished with value: 0.19603779589712056 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 471, 'oob_score': True, 'max_samples': 0.38596042546249815, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06019832785625927}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21777534072255536
Fold 2 IBS: 0.18388001229747647
Fold 3 IBS: 0.20567868044901855
Fold 4 IBS: 0.1847943862306208
Fold 5 IBS: 0.18923042007189297
[I 2024-04-17 14:21:58,061] Trial 46 finished with value: 0.19627176795431284 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.4564757279414969, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07953195899434512}. Best is trial 26 with value: 0.19472802701530875.

Fold 1 IBS: 0.21826580427208442
Fold 2 IBS: 0.18587467681641034
Fold 3 IBS: 0.2052036910380681
Fold 4 IBS: 0.18770622456106834
Fold 5 IBS: 0.18950656244053213
[I 2024-04-17 14:22:11,799] Trial 47 finished with value: 0.19731139182563268 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.4674743064217755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08523218063639464}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.24609415388725878
Fold 2 IBS: 0.23220299979144535
Fold 3 IBS: 0.22960252169703754
Fold 4 IBS: 0.24122082372935674
Fold 5 IBS: 0.23052166868873505
[I 2024-04-17 14:22:24,390] Trial 48 finished with value: 0.23592843355876666 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.20761893689550356, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14500785795513438}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2468036787719249
Fold 2 IBS: 0.23224060615619452
Fold 3 IBS: 0.22949472559112255
Fold 4 IBS: 0.2411812409179721
Fold 5 IBS: 0.2301471702024984
[I 2024-04-17 14:22:29,128] Trial 49 finished with value: 0.2359734843279425 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.329319779965102, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01980912659993596}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22874743523488048
Fold 2 IBS: 0.18144234354687283
Fold 3 IBS: 0.21437128716806075
Fold 4 IBS: 0.1764868685585472
Fold 5 IBS: 0.18827366255157654
[I 2024-04-17 14:22:42,699] Trial 50 finished with value: 0.19786431941198757 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.9856992496851368, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07083539535605461}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21828585745295095
Fold 2 IBS: 0.18794181223915027
Fold 3 IBS: 0.20327675558432648
Fold 4 IBS: 0.18505768941449757
Fold 5 IBS: 0.186549792249403
[I 2024-04-17 14:22:55,074] Trial 51 finished with value: 0.19622238138806564 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.3837938773056691, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04364287522424891}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21397483755138832
Fold 2 IBS: 0.1874544005064987
Fold 3 IBS: 0.20626637464949518
Fold 4 IBS: 0.19357715163042719
Fold 5 IBS: 0.1899045739478458
[I 2024-04-17 14:23:05,957] Trial 52 finished with value: 0.19823546765713101 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.39143588368582644, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09770740491265198}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2252011910917729
Fold 2 IBS: 0.20900582931177425
Fold 3 IBS: 0.21766656913228746
Fold 4 IBS: 0.21408635453490685
Fold 5 IBS: 0.2075887759357219
[I 2024-04-17 14:23:16,832] Trial 53 finished with value: 0.2147097440012927 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 466, 'oob_score': True, 'max_samples': 0.2774111455190974, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12677555454042966}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21750427200718483
Fold 2 IBS: 0.1849682099568589
Fold 3 IBS: 0.2011947538957837
Fold 4 IBS: 0.18831833360234362
Fold 5 IBS: 0.18984278166426155
[I 2024-04-17 14:23:28,987] Trial 54 finished with value: 0.1963656702252865 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.4431057475544241, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06648930845207582}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22387911117848697
Fold 2 IBS: 0.19150901989856767
Fold 3 IBS: 0.20679554175193693
Fold 4 IBS: 0.18170071205337018
Fold 5 IBS: 0.1879962697141026
[I 2024-04-17 14:23:40,519] Trial 55 finished with value: 0.1983761309192929 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.5297775222944199, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0069198875931894}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21210310075767175
Fold 2 IBS: 0.1904525365690198
Fold 3 IBS: 0.20787975508661058
Fold 4 IBS: 0.1959440099728264
Fold 5 IBS: 0.19342199945202426
[I 2024-04-17 14:23:51,321] Trial 56 finished with value: 0.19996028036763058 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.6882525064531181, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04313686574908496}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2451048739637309
Fold 2 IBS: 0.2303970990144524
Fold 3 IBS: 0.22902429594931714
Fold 4 IBS: 0.23978697565713364
Fold 5 IBS: 0.2272598537102799
[I 2024-04-17 14:23:59,521] Trial 57 finished with value: 0.2343146196589828 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.3466596936983887, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02243209896487393}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.23642706090422158
Fold 2 IBS: 0.17873540514538863
Fold 3 IBS: 0.22839961586786137
Fold 4 IBS: 0.19281998509358012
Fold 5 IBS: 0.2086679735608439
[I 2024-04-17 14:24:08,797] Trial 58 finished with value: 0.20901000811437914 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.43835893792858327, 'max_features': None, 'min_weight_fraction_leaf': 0.07438011818993595}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21540749105630058
Fold 2 IBS: 0.18565701597821407
Fold 3 IBS: 0.20386125179615522
Fold 4 IBS: 0.18920238381811685
Fold 5 IBS: 0.18763682053044314
[I 2024-04-17 14:24:17,891] Trial 59 finished with value: 0.196352992635846 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.5883120564012534, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11772702636102221}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.24653824804713512
Fold 2 IBS: 0.2321219673793574
Fold 3 IBS: 0.23028626141419709
Fold 4 IBS: 0.2409883501654297
Fold 5 IBS: 0.22974826782740948
[I 2024-04-17 14:24:29,445] Trial 60 finished with value: 0.23593661896670573 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.10212772299519245, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05458912355606277}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22063208346729457
Fold 2 IBS: 0.1861311884828633
Fold 3 IBS: 0.2048801714829906
Fold 4 IBS: 0.18634184483621866
Fold 5 IBS: 0.18812878546817977
[I 2024-04-17 14:24:40,490] Trial 61 finished with value: 0.19722281474750938 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.7800913669036267, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09292596954962928}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21969269229278238
Fold 2 IBS: 0.19111014044323302
Fold 3 IBS: 0.20204419817972805
Fold 4 IBS: 0.200440088268544
Fold 5 IBS: 0.1945296032083531
[I 2024-04-17 14:24:51,852] Trial 62 finished with value: 0.20156334447852808 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.5733126288745112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12223304985234582}. Best is trial 26 with value: 0.19472802701530875.

Fold 1 IBS: 0.21966048398107768
Fold 2 IBS: 0.19129772512794055
Fold 3 IBS: 0.20250622585648823
Fold 4 IBS: 0.18868145334994946
Fold 5 IBS: 0.18722401007552733
[I 2024-04-17 14:25:01,991] Trial 63 finished with value: 0.19787397967819667 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.6602193953048239, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04143492559229172}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22441948181751695
Fold 2 IBS: 0.20764396947816882
Fold 3 IBS: 0.21126840742544478
Fold 4 IBS: 0.2137784503905903
Fold 5 IBS: 0.19933277094836385
[I 2024-04-17 14:25:03,768] Trial 64 finished with value: 0.21128861601201693 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.4764215998907, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20225237341748686}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2249644011080851
Fold 2 IBS: 0.18525522670516392
Fold 3 IBS: 0.21036838111998118
Fold 4 IBS: 0.18031474296152905
Fold 5 IBS: 0.18707246569618
[I 2024-04-17 14:25:11,200] Trial 65 finished with value: 0.19759504351818785 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 375, 'oob_score': False, 'max_samples': 0.5155774302837967, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.062842822794926}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22034865729895695
Fold 2 IBS: 0.20267008382004897
Fold 3 IBS: 0.20965813460866753
Fold 4 IBS: 0.2087693904668862
Fold 5 IBS: 0.1975522173990944
[I 2024-04-17 14:25:17,671] Trial 66 finished with value: 0.20779969671873083 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.61724036951632, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25696978293944095}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.22811517702661704
Fold 2 IBS: 0.2002244875602664
Fold 3 IBS: 0.20205425734208335
Fold 4 IBS: 0.20075288933589275
Fold 5 IBS: 0.20326641061280382
[I 2024-04-17 14:25:27,338] Trial 67 finished with value: 0.20688264437553266 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 419, 'oob_score': True, 'max_samples': 0.3919208537952881, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01597187562164963}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.2147390861774992
Fold 2 IBS: 0.1981751062437161
Fold 3 IBS: 0.20419796643955812
Fold 4 IBS: 0.20207484195871778
Fold 5 IBS: 0.19510052568119485
[I 2024-04-17 14:25:37,179] Trial 68 finished with value: 0.20285750530013721 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.30534140769982127, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1071610885798284}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21579586805821951
Fold 2 IBS: 0.18816516315577353
Fold 3 IBS: 0.19989209339023067
Fold 4 IBS: 0.1857114649045257
Fold 5 IBS: 0.18464378062658382
[I 2024-04-17 14:25:48,620] Trial 69 finished with value: 0.19484167402706667 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.23359013421883335, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03452095557908811}. Best is trial 26 with value: 0.19472802701530875.
Fold 1 IBS: 0.21389739919291467
Fold 2 IBS: 0.18557396783248045
Fold 3 IBS: 0.20276426673771367
Fold 4 IBS: 0.18611628975844563
Fold 5 IBS: 0.18384851255662701
[I 2024-04-17 14:25:57,741] Trial 70 finished with value: 0.19444008721563627 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.22701187241580995, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042574949229199924}. Best is trial 70 with value: 0.19444008721563627.
Fold 1 IBS: 0.21232393790978374
Fold 2 IBS: 0.1863577532232234
Fold 3 IBS: 0.20313692089886407
Fold 4 IBS: 0.18792023643969663
Fold 5 IBS: 0.18483593509608945
[I 2024-04-17 14:26:06,696] Trial 71 finished with value: 0.19491495671353143 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.21759394216593397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03677268538077186}. Best is trial 70 with value: 0.19444008721563627.
Fold 1 IBS: 0.2154312323732342
Fold 2 IBS: 0.1854896773270869
Fold 3 IBS: 0.20353130922472215
Fold 4 IBS: 0.18239508000469618
Fold 5 IBS: 0.18451590026791514
[I 2024-04-17 14:26:16,667] Trial 72 finished with value: 0.19427263983953091 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.23147069159708078, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03140239314591447}. Best is trial 72 with value: 0.19427263983953091.
Fold 1 IBS: 0.2142372407506157
Fold 2 IBS: 0.18435425061038285
Fold 3 IBS: 0.20423041135438974
Fold 4 IBS: 0.17968898908689032
Fold 5 IBS: 0.1851439250225952
[I 2024-04-17 14:26:25,828] Trial 73 finished with value: 0.19353096336497475 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.22968721500163153, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0009593300891976506}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.21531173640388315
Fold 2 IBS: 0.18453465528277493
Fold 3 IBS: 0.2042171719000752
Fold 4 IBS: 0.18132921563126206
Fold 5 IBS: 0.18263690349268777
[I 2024-04-17 14:26:36,382] Trial 74 finished with value: 0.19360593654213662 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.2100854071392845, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004129771737052812}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.2151728233246765
Fold 2 IBS: 0.19004455518134059
Fold 3 IBS: 0.199914388265541
Fold 4 IBS: 0.1910222131209018
Fold 5 IBS: 0.1868507007529534
[I 2024-04-17 14:26:44,691] Trial 75 finished with value: 0.19660093612908267 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.15033893400643428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001474860232376458}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.21333981642668087
Fold 2 IBS: 0.18765444501926729
Fold 3 IBS: 0.20277798733708235
Fold 4 IBS: 0.1884353778671576
Fold 5 IBS: 0.18333940118304162
[I 2024-04-17 14:26:53,466] Trial 76 finished with value: 0.19510940556664597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.214160747212656, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03134486470278475}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.2134072161520808
Fold 2 IBS: 0.18767974670459284
Fold 3 IBS: 0.2027534897700664
Fold 4 IBS: 0.18839348886833288
Fold 5 IBS: 0.18416750847217667
[I 2024-04-17 14:27:03,534] Trial 77 finished with value: 0.1952802899934499 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 488, 'oob_score': False, 'max_samples': 0.21922924713505096, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031073567510404323}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.21729044921831714
Fold 2 IBS: 0.19915648643481346
Fold 3 IBS: 0.20467938072682307
Fold 4 IBS: 0.20577294956667078

Fold 5 IBS: 0.19626791200555305
[I 2024-04-17 14:27:11,761] Trial 78 finished with value: 0.20463343559043548 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.1776414302372801, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01245609753689763}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.22506992941916096
Fold 2 IBS: 0.1956675734053738
Fold 3 IBS: 0.2004354181713437
Fold 4 IBS: 0.1985159039517795
Fold 5 IBS: 0.19425564254565922
[I 2024-04-17 14:27:20,877] Trial 79 finished with value: 0.20278889349866347 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.2393243379655301, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001038000069520234}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.2189041410044779
Fold 2 IBS: 0.1960740828984194
Fold 3 IBS: 0.2057448147388659
Fold 4 IBS: 0.2035653202183879
Fold 5 IBS: 0.1947760853651195
[I 2024-04-17 14:27:28,474] Trial 80 finished with value: 0.20381288884505416 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.13301807040021585, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031073565967035213}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.2138323338957447
Fold 2 IBS: 0.1870350815206029
Fold 3 IBS: 0.20245106413303612
Fold 4 IBS: 0.18725446767968562
Fold 5 IBS: 0.18418241786758527
[I 2024-04-17 14:27:38,550] Trial 81 finished with value: 0.19495107301933096 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.2207813975090672, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031510287062149554}. Best is trial 73 with value: 0.19353096336497475.
Fold 1 IBS: 0.2131278439163959
Fold 2 IBS: 0.18404079209648558
Fold 3 IBS: 0.2013840414196853
Fold 4 IBS: 0.18411108116836367
Fold 5 IBS: 0.1841775243972767
[I 2024-04-17 14:27:47,536] Trial 82 finished with value: 0.19336825659964144 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.19913245689586032, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.021423573926650424}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21455916410850653
Fold 2 IBS: 0.18719179450702228
Fold 3 IBS: 0.20288768089549797
Fold 4 IBS: 0.18732259096695528
Fold 5 IBS: 0.18485237700052712
[I 2024-04-17 14:27:57,018] Trial 83 finished with value: 0.19536272149570183 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.17415902681293857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010755160360672634}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21733099763808209
Fold 2 IBS: 0.18826339589012345
Fold 3 IBS: 0.19877671218327206
Fold 4 IBS: 0.18690497136101897
Fold 5 IBS: 0.18401922794838124
[I 2024-04-17 14:28:04,685] Trial 84 finished with value: 0.19505906100417553 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.2528752116904652, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02143607789412913}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21625434239679683
Fold 2 IBS: 0.18496478720701012
Fold 3 IBS: 0.20163784518172384
Fold 4 IBS: 0.18523010446010993
Fold 5 IBS: 0.1874693460272692
[I 2024-04-17 14:28:13,053] Trial 85 finished with value: 0.19511128505458197 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.28509092298129435, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04767660959327923}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.2150202095602379
Fold 2 IBS: 0.1849295223704728
Fold 3 IBS: 0.2006612155824318
Fold 4 IBS: 0.18919121291053104
Fold 5 IBS: 0.18537249705548428
[I 2024-04-17 14:28:22,617] Trial 86 finished with value: 0.19503493149583156 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.19693497238896676, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.036119034746724406}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21692351357470402
Fold 2 IBS: 0.1978206523560774
Fold 3 IBS: 0.20435952666666607
Fold 4 IBS: 0.20515805119057104
Fold 5 IBS: 0.19505102401186647
[I 2024-04-17 14:28:30,919] Trial 87 finished with value: 0.20386255355997704 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.1647376528823824, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016694658010836975}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.2462548338390022
Fold 2 IBS: 0.2322277557854328
Fold 3 IBS: 0.22978722371689156
Fold 4 IBS: 0.24129969377643612
Fold 5 IBS: 0.23046006004245603
[I 2024-04-17 14:28:40,973] Trial 88 finished with value: 0.23600591343204375 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 478, 'oob_score': False, 'max_samples': 0.2301789273399505, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3922982329820186}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.22405316408961914
Fold 2 IBS: 0.21091232961279643
Fold 3 IBS: 0.2164803579950275
Fold 4 IBS: 0.2165601754404421
Fold 5 IBS: 0.20601203743593924
[I 2024-04-17 14:28:49,604] Trial 89 finished with value: 0.21480361291476488 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.20273021304497926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.034680599253518164}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.2214463064845696
Fold 2 IBS: 0.1941391756292239
Fold 3 IBS: 0.20334084682387513
Fold 4 IBS: 0.19666566812472758
Fold 5 IBS: 0.19455176931708903
[I 2024-04-17 14:28:59,184] Trial 90 finished with value: 0.20202875327589703 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 466, 'oob_score': False, 'max_samples': 0.12822924636239066, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.013218521528771825}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.2126339747603219
Fold 2 IBS: 0.1854978535127189
Fold 3 IBS: 0.19626370247335143
Fold 4 IBS: 0.19315666663180917
Fold 5 IBS: 0.1832124671686707
[I 2024-04-17 14:29:03,517] Trial 91 finished with value: 0.19415293290937444 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.19455164199377284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04013827401309928}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21854564872536342
Fold 2 IBS: 0.1839717594146773
Fold 3 IBS: 0.19998430268501047
Fold 4 IBS: 0.18650572631137868
Fold 5 IBS: 0.18429610167218993
[I 2024-04-17 14:29:07,807] Trial 92 finished with value: 0.19466070776172398 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.25371848063016794, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05034608761488911}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21694637787059937
Fold 2 IBS: 0.181397061465793
Fold 3 IBS: 0.1998969153049947
Fold 4 IBS: 0.1857510536405655
Fold 5 IBS: 0.18573329622634188
[I 2024-04-17 14:29:13,678] Trial 93 finished with value: 0.19394494090165887 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.2597127058540918, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04985330238321208}. Best is trial 82 with value: 0.19336825659964144.

Fold 1 IBS: 0.21169240339518186
Fold 2 IBS: 0.1886341595650372
Fold 3 IBS: 0.202140293031865
Fold 4 IBS: 0.19785454404349312
Fold 5 IBS: 0.18716831705434622
[I 2024-04-17 14:29:17,029] Trial 94 finished with value: 0.19749794341798468 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.25112197997211044, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07196182779958107}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.22897478326996884
Fold 2 IBS: 0.1770364873003973
Fold 3 IBS: 0.226843018801927
Fold 4 IBS: 0.1897067076457147
Fold 5 IBS: 0.20446826637628404
[I 2024-04-17 14:29:21,362] Trial 95 finished with value: 0.20540585267885839 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.2756463981676094, 'max_features': None, 'min_weight_fraction_leaf': 0.04847819376400821}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.24653874908733783
Fold 2 IBS: 0.23210880636334807
Fold 3 IBS: 0.2300239551582043
Fold 4 IBS: 0.24130560036708915
Fold 5 IBS: 0.22971657292484735
[I 2024-04-17 14:29:26,211] Trial 96 finished with value: 0.23593873678016536 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.15717138302725103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08847138750402889}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.246396892029323
Fold 2 IBS: 0.2321919583623202
Fold 3 IBS: 0.22982109033734824
Fold 4 IBS: 0.24111470538908114
Fold 5 IBS: 0.23029393923816027
[I 2024-04-17 14:29:31,981] Trial 97 finished with value: 0.23596371707124658 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.18562775725713698, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3126608885366039}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21458765639507066
Fold 2 IBS: 0.18421585090220524
Fold 3 IBS: 0.19783784527710385
Fold 4 IBS: 0.19514428513055418
Fold 5 IBS: 0.18502137642125668
[I 2024-04-17 14:29:35,149] Trial 98 finished with value: 0.19536140282523812 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 163, 'oob_score': False, 'max_samples': 0.2536494232187598, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.062101691441718544}. Best is trial 82 with value: 0.19336825659964144.
Fold 1 IBS: 0.21430465385732558
Fold 2 IBS: 0.18876514742969877
Fold 3 IBS: 0.20390169074615871
Fold 4 IBS: 0.18665846140868889
Fold 5 IBS: 0.18644282189837874
[I 2024-04-17 14:29:38,885] Trial 99 finished with value: 0.19601455506805016 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.12695468003736576, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0014364143127286802}. Best is trial 82 with value: 0.19336825659964144.


* Best trial for IBS:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.19336825659964144], datetime_start=datetime.datetime(2024, 4, 17, 14, 27, 38, 561075), datetime_complete=datetime.datetime(2024, 4, 17, 14, 27, 47, 534938), params={'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.19913245689586032, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.021423573926650424}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for IBS:
 0.19336825659964144

In [52]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [53]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.841
train_ibs:  0.193

#### Test

In [54]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [55]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=9, max_features='log2', max_leaf_nodes=13,
                     max_samples=0.7347203615160294,
                     min_weight_fraction_leaf=0.009228383305913348,
                     n_estimators=388, random_state=123, warm_start=True)

test_cindex:  0.567

RandomSurvivalForest(max_depth=3, max_features='log2', max_leaf_nodes=16,
                     max_samples=0.19913245689586032, min_samples_leaf=4,
                     min_samples_split=3,
                     min_weight_fraction_leaf=0.021423573926650424,
                     n_estimators=458, random_state=123)

test_ibs:  0.247

In [56]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [57]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [58]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:29:42,101] A new study created in memory with name: no-name-48e880ba-dc50-4fd5-9652-461db3823f10

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7167381974248928
[I 2024-04-17 14:29:43,855] Trial 0 finished with value: 0.7309095025528539 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:29:47,811] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6952789699570815
[I 2024-04-17 14:29:55,629] Trial 2 finished with value: 0.7083821051222271 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.7081545064377682
[I 2024-04-17 14:29:56,351] Trial 3 finished with value: 0.7251581738746367 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:29:59,431] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:30:03,277] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7167381974248928
[I 2024-04-17 14:30:05,308] Trial 6 finished with value: 0.7284648132250587 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7296137339055794
[I 2024-04-17 14:30:10,651] Trial 7 finished with value: 0.7223012647205163 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6974248927038627
[I 2024-04-17 14:30:11,044] Trial 8 finished with value: 0.7251373742540215 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 14:30:21,203] Trial 9 finished with value: 0.714224642455631 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:30:24,340] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 14:30:26,279] Trial 11 finished with value: 0.7208773579950105 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7309095025528539.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7965779467680608
Fold 5 C-index: 0.7725321888412017
[I 2024-04-17 14:30:28,668] Trial 12 finished with value: 0.7572934917498981 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6995708154506438
[I 2024-04-17 14:30:31,848] Trial 13 finished with value: 0.7211126972010048 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 14:30:34,238] Trial 14 finished with value: 0.7138115317557795 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7572934917498981.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6995708154506438
[I 2024-04-17 14:30:35,768] Trial 15 finished with value: 0.7198013235215133 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.8063829787234043
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6888412017167382
[I 2024-04-17 14:30:38,361] Trial 16 finished with value: 0.7065350567715983 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 14:30:39,965] Trial 17 finished with value: 0.715021235065976 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:30:42,501] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6995708154506438
[I 2024-04-17 14:30:44,334] Trial 19 finished with value: 0.7217646513132026 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.4960159362549801
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.759656652360515
[I 2024-04-17 14:30:44,610] Trial 20 finished with value: 0.672049623936753 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7167381974248928
[I 2024-04-17 14:30:46,646] Trial 21 finished with value: 0.7300368197725123 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:30:48,714] Trial 22 finished with value: 0.7415536638237409 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7572934917498981.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-17 14:30:51,111] Trial 23 finished with value: 0.7664602890904068 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.7664602890904068.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:30:53,443] Trial 24 finished with value: 0.7355416387841441 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.7664602890904068.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7811158798283262
[I 2024-04-17 14:30:55,347] Trial 25 finished with value: 0.7544584087916586 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.7664602890904068.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6952789699570815
[I 2024-04-17 14:31:06,828] Trial 26 finished with value: 0.7117073333291801 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7226268366017338, 'min_weight_fraction_leaf': 0.14724522382749441}. Best is trial 23 with value: 0.7664602890904068.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.703862660944206
[I 2024-04-17 14:31:08,775] Trial 27 finished with value: 0.7163281127962315 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.0910755188453143}. Best is trial 23 with value: 0.7664602890904068.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.687984496124031
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.7081545064377682
[I 2024-04-17 14:31:11,058] Trial 28 finished with value: 0.7144996215688828 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9159590537617217, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.7664602890904068.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.7167381974248928
[I 2024-04-17 14:31:12,782] Trial 29 finished with value: 0.7293522335300857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8201511224658254, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 23 with value: 0.7664602890904068.

Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8154506437768241
[I 2024-04-17 14:31:14,200] Trial 30 finished with value: 0.7809914325332163 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.05879574792157449}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.7896995708154506
[I 2024-04-17 14:31:15,666] Trial 31 finished with value: 0.773052656951504 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6298966865274057, 'min_weight_fraction_leaf': 0.05405927482118079}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8231939163498099
Fold 5 C-index: 0.8025751072961373
[I 2024-04-17 14:31:17,359] Trial 32 finished with value: 0.7764640905527432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.722056772295139, 'min_weight_fraction_leaf': 0.06665303212999554}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.7253218884120172
[I 2024-04-17 14:31:19,285] Trial 33 finished with value: 0.7455516009730723 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7504103077643619, 'min_weight_fraction_leaf': 0.07228058521385833}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:31:20,508] Trial 34 finished with value: 0.7446856726317648 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 218, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.699719011795045, 'min_weight_fraction_leaf': 0.1126902739511941}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 14:31:24,075] Trial 35 finished with value: 0.7141917901867433 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 282, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6215694472638225, 'min_weight_fraction_leaf': 0.16733609036803293}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:31:28,356] Trial 36 finished with value: 0.7300019817182524 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5190557919565845, 'min_weight_fraction_leaf': 0.05223373774757657}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 14:31:29,568] Trial 37 finished with value: 0.7184764573982152 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 168, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8268387836003009, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 14:31:31,316] Trial 38 finished with value: 0.7092003366583175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6034576762401722, 'min_weight_fraction_leaf': 0.22096529439752421}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 14:31:36,749] Trial 39 finished with value: 0.7035478593734058 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5204645655829614, 'min_weight_fraction_leaf': 0.07994626083099707}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.7081545064377682
[I 2024-04-17 14:31:37,663] Trial 40 finished with value: 0.7263968346036487 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7462583966462045, 'min_weight_fraction_leaf': 0.027601004831219272}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.7939914163090128
[I 2024-04-17 14:31:39,245] Trial 41 finished with value: 0.7724148895341005 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6676760673731118, 'min_weight_fraction_leaf': 0.0019860067692131778}. Best is trial 30 with value: 0.7809914325332163.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8384030418250951
Fold 5 C-index: 0.8197424892703863
[I 2024-04-17 14:31:40,765] Trial 42 finished with value: 0.7885607265955813 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6725672668712916, 'min_weight_fraction_leaf': 0.06134016294643}. Best is trial 42 with value: 0.7885607265955813.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 14:31:42,273] Trial 43 finished with value: 0.7077145623952383 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6659953080114266, 'min_weight_fraction_leaf': 0.27764552944355786}. Best is trial 42 with value: 0.7885607265955813.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8079847908745247
Fold 5 C-index: 0.776824034334764
[I 2024-04-17 14:31:43,619] Trial 44 finished with value: 0.766667412187729 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5606440507914384, 'min_weight_fraction_leaf': 0.06554582209581696}. Best is trial 42 with value: 0.7885607265955813.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8497854077253219
[I 2024-04-17 14:31:45,388] Trial 45 finished with value: 0.8089579183471379 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7853496457812107, 'min_weight_fraction_leaf': 0.015745612245557046}. Best is trial 45 with value: 0.8089579183471379.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:31:47,203] Trial 46 finished with value: 0.8089652236160629 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7702604596394105, 'min_weight_fraction_leaf': 0.02501102546800585}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7424892703862661
[I 2024-04-17 14:31:53,467] Trial 47 finished with value: 0.7247127949620398 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 324, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8009854768869007, 'min_weight_fraction_leaf': 0.025373757162150387}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8079847908745247
Fold 5 C-index: 0.7854077253218884
[I 2024-04-17 14:31:57,524] Trial 48 finished with value: 0.7667472869860373 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 349, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8479579012888129, 'min_weight_fraction_leaf': 0.09256170689310786}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 14:31:58,914] Trial 49 finished with value: 0.7144702238727497 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7862703089830011, 'min_weight_fraction_leaf': 0.021891853731296304}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 14:32:00,566] Trial 50 finished with value: 0.7200768209009956 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9256153933677993, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8412017167381974
[I 2024-04-17 14:32:02,524] Trial 51 finished with value: 0.7999688119371322 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7596824539947467, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:32:04,023] Trial 52 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7565523755943866, 'min_weight_fraction_leaf': 0.46068944029286296}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8412017167381974
[I 2024-04-17 14:32:05,553] Trial 53 finished with value: 0.7993754005148812 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 267, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8459507728986935, 'min_weight_fraction_leaf': 0.06066059326959871}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.8111587982832618
[I 2024-04-17 14:32:07,048] Trial 54 finished with value: 0.7773987535258495 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 249, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8483312647315421, 'min_weight_fraction_leaf': 0.08285527189465233}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:32:08,593] Trial 55 finished with value: 0.7985087614883246 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7824438103232705, 'min_weight_fraction_leaf': 0.016416118984306168}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.7854077253218884
[I 2024-04-17 14:32:10,573] Trial 56 finished with value: 0.762088835360676 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7832587730997999, 'min_weight_fraction_leaf': 0.017544692352515514}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8240343347639485
[I 2024-04-17 14:32:11,938] Trial 57 finished with value: 0.7778720684828867 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9448775455684517, 'min_weight_fraction_leaf': 0.013806353884736229}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6952789699570815
[I 2024-04-17 14:32:13,308] Trial 58 finished with value: 0.7202179716270526 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 261, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8514292980355059, 'min_weight_fraction_leaf': 0.04695960464870107}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7936170212765957
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6587982832618026
[I 2024-04-17 14:32:21,616] Trial 59 finished with value: 0.6995816446139427 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8160395059852231, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 46 with value: 0.8089652236160629.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.7124463519313304
[I 2024-04-17 14:32:23,416] Trial 60 finished with value: 0.7316990100329326 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8931072429775935, 'min_weight_fraction_leaf': 0.09869194371308154}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8412017167381974
[I 2024-04-17 14:32:25,240] Trial 61 finished with value: 0.7999688119371322 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7582468632632998, 'min_weight_fraction_leaf': 0.05264169980341253}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8412017167381974
[I 2024-04-17 14:32:26,858] Trial 62 finished with value: 0.8049598113284201 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7871045726921452, 'min_weight_fraction_leaf': 0.03424986695222214}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8412017167381974
[I 2024-04-17 14:32:28,073] Trial 63 finished with value: 0.8008014138972233 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 205, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7662964040348412, 'min_weight_fraction_leaf': 0.0339014300920848}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8454935622317596
[I 2024-04-17 14:32:29,215] Trial 64 finished with value: 0.7994358223362844 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8613969290436121, 'min_weight_fraction_leaf': 0.034734565474048365}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8412017167381974
[I 2024-04-17 14:32:31,878] Trial 65 finished with value: 0.8049629684092782 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 196, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9545442370663418, 'min_weight_fraction_leaf': 0.03734828248539529}. Best is trial 46 with value: 0.8089652236160629.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8669527896995708
[I 2024-04-17 14:32:33,568] Trial 66 finished with value: 0.809805411267039 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9076949731885966, 'min_weight_fraction_leaf': 0.04083860987001704}. Best is trial 66 with value: 0.809805411267039.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:32:34,825] Trial 67 finished with value: 0.8338221508243657 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 133, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9512690653294484, 'min_weight_fraction_leaf': 0.0010143626946411619}. Best is trial 67 with value: 0.8338221508243657.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9055793991416309
[I 2024-04-17 14:32:35,926] Trial 68 finished with value: 0.8379149971529121 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9311626349378656, 'min_weight_fraction_leaf': 0.0064310860003202654}. Best is trial 68 with value: 0.8379149971529121.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:32:36,701] Trial 69 finished with value: 0.8392537927343522 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 92, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9574465175194102, 'min_weight_fraction_leaf': 0.004790443631859553}. Best is trial 69 with value: 0.8392537927343522.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9012875536480687
[I 2024-04-17 14:32:37,445] Trial 70 finished with value: 0.840891079976525 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.953229637324892, 'min_weight_fraction_leaf': 0.0029509030346900195}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:32:38,103] Trial 71 finished with value: 0.8407025595955538 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 78, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9621007830221302, 'min_weight_fraction_leaf': 0.006015247231338199}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8969957081545065
[I 2024-04-17 14:32:38,689] Trial 72 finished with value: 0.8407025595955538 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 78, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9651900028217072, 'min_weight_fraction_leaf': 0.00052737318632801}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:32:39,382] Trial 73 finished with value: 0.8308806913700992 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 70, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9987314558896175, 'min_weight_fraction_leaf': 0.0006604513922534648}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8841201716738197
[I 2024-04-17 14:32:40,172] Trial 74 finished with value: 0.8323764040431589 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 72, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9995368365368067, 'min_weight_fraction_leaf': 0.003200823966453802}. Best is trial 70 with value: 0.840891079976525.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8927038626609443
[I 2024-04-17 14:32:40,828] Trial 75 finished with value: 0.8302830047729464 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 73, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9870891342469079, 'min_weight_fraction_leaf': 0.00026534283741594514}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7167381974248928
[I 2024-04-17 14:32:42,798] Trial 76 finished with value: 0.7277840686581776 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 70, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9603023972274102, 'min_weight_fraction_leaf': 0.013254234099407477}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:32:43,154] Trial 77 finished with value: 0.8214574064444413 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 17, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9315552481330696, 'min_weight_fraction_leaf': 0.0014080421868506}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8755364806866953
[I 2024-04-17 14:32:44,133] Trial 78 finished with value: 0.8283667165806141 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9999460843510554, 'min_weight_fraction_leaf': 0.0018895756366870452}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-17 14:32:44,730] Trial 79 finished with value: 0.8180707047207129 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 56, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9641045598543692, 'min_weight_fraction_leaf': 0.0145572372199312}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8540772532188842
[I 2024-04-17 14:32:45,551] Trial 80 finished with value: 0.7998250108062066 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 103, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9022907665083136, 'min_weight_fraction_leaf': 0.02502911966074306}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:32:46,374] Trial 81 finished with value: 0.8293450412978853 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9978026560926501, 'min_weight_fraction_leaf': 0.003307545111141476}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8669527896995708
[I 2024-04-17 14:32:46,846] Trial 82 finished with value: 0.8206897277346851 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 35, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9382866563894526, 'min_weight_fraction_leaf': 0.000702593446105074}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8197424892703863
[I 2024-04-17 14:32:47,556] Trial 83 finished with value: 0.7828494484435331 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 83, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.973113924642658, 'min_weight_fraction_leaf': 0.016444135296345613}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8884120171673819
[I 2024-04-17 14:32:48,426] Trial 84 finished with value: 0.8300402333111918 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 129, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9806383268972433, 'min_weight_fraction_leaf': 0.00018527122422710323}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8111587982832618
[I 2024-04-17 14:32:48,916] Trial 85 finished with value: 0.7842545371263083 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 39, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8802859343485059, 'min_weight_fraction_leaf': 0.031146221374218932}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7854077253218884
[I 2024-04-17 14:32:49,522] Trial 86 finished with value: 0.7584012736223842 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9430538478782141, 'min_weight_fraction_leaf': 0.04418151283043829}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.7381974248927039
[I 2024-04-17 14:32:50,406] Trial 87 finished with value: 0.7480756142692846 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 125, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9153151805473887, 'min_weight_fraction_leaf': 0.07323973028758114}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-17 14:32:52,861] Trial 88 finished with value: 0.7182164153374415 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 88, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9695915274829453, 'min_weight_fraction_leaf': 0.014938639782074818}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8197424892703863
[I 2024-04-17 14:32:53,683] Trial 89 finished with value: 0.782603376479824 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 117, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9991414632644102, 'min_weight_fraction_leaf': 0.026602610287146645}. Best is trial 70 with value: 0.840891079976525.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8626609442060086
[I 2024-04-17 14:32:54,110] Trial 90 finished with value: 0.8169546832144643 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 23, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8834670252008057, 'min_weight_fraction_leaf': 0.010793481716879718}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8798283261802575
[I 2024-04-17 14:32:55,033] Trial 91 finished with value: 0.8292683235804355 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9786809179317413, 'min_weight_fraction_leaf': 0.0020420085063257666}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8583690987124464
[I 2024-04-17 14:32:55,743] Trial 92 finished with value: 0.8042865515561509 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 75, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.928372589925232, 'min_weight_fraction_leaf': 0.024248639093334554}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8111587982832618
[I 2024-04-17 14:32:56,547] Trial 93 finished with value: 0.7764383095543017 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 97, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9554693546927394, 'min_weight_fraction_leaf': 0.04189745422532261}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7896995708154506
[I 2024-04-17 14:32:57,075] Trial 94 finished with value: 0.7762362802952625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 51, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9742116217110314, 'min_weight_fraction_leaf': 0.010327563453309159}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.7253218884120172
[I 2024-04-17 14:32:58,014] Trial 95 finished with value: 0.7158404200284727 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9146957484715288, 'min_weight_fraction_leaf': 0.29852071039763683}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.6918604651162791
Fold 3 C-index: 0.8106382978723404
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 14:32:58,845] Trial 96 finished with value: 0.7168915622744366 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 116, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.16631853158382698, 'min_weight_fraction_leaf': 0.056782093839129195}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7339055793991416
[I 2024-04-17 14:32:59,463] Trial 97 finished with value: 0.7494558466621555 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 72, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.35270511877442323, 'min_weight_fraction_leaf': 0.026038840773405847}. Best is trial 70 with value: 0.840891079976525.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-17 14:33:00,235] Trial 98 finished with value: 0.8122981809349976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 94, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9880752289178929, 'min_weight_fraction_leaf': 0.0006600230517183562}. Best is trial 70 with value: 0.840891079976525.

[I 2024-04-17 14:33:00,815] A new study created in memory with name: no-name-5ee9b64e-3f60-4137-8774-d62c2de02200

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8454935622317596
[I 2024-04-17 14:33:00,806] Trial 99 finished with value: 0.7901497762166744 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 61, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9501415322280076, 'min_weight_fraction_leaf': 0.011913117013166752}. Best is trial 70 with value: 0.840891079976525.


* Best trial for C-index:
 FrozenTrial(number=70, state=TrialState.COMPLETE, values=[0.840891079976525], datetime_start=datetime.datetime(2024, 4, 17, 14, 32, 36, 707335), datetime_complete=datetime.datetime(2024, 4, 17, 14, 32, 37, 436159), params={'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.953229637324892, 'min_weight_fraction_leaf': 0.0029509030346900195}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=70, value=None)


* Best Score for C-index:
 0.840891079976525

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2246638825755847
Fold 2 IBS: 0.2042332794483991
Fold 3 IBS: 0.19652601247076693
Fold 4 IBS: 0.2062846062337406
Fold 5 IBS: 0.1938619757756916
[I 2024-04-17 14:33:07,392] Trial 0 finished with value: 0.20511395130083657 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-17 14:33:16,892] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.2320733115583041
Fold 2 IBS: 0.21625098862635225
Fold 3 IBS: 0.20821949377476995
Fold 4 IBS: 0.21991258601768016
Fold 5 IBS: 0.20890124327833173
[I 2024-04-17 14:33:25,867] Trial 2 finished with value: 0.21707152465108764 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.23316183734759477
Fold 2 IBS: 0.21659046510067825
Fold 3 IBS: 0.20823138697267976
Fold 4 IBS: 0.22337372439256084
Fold 5 IBS: 0.21062047260611894
[I 2024-04-17 14:33:29,271] Trial 3 finished with value: 0.2183955772839265 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-17 14:33:36,967] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-17 14:33:40,416] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.22355888828630424
Fold 2 IBS: 0.2058920273673241
Fold 3 IBS: 0.19634187772192208
Fold 4 IBS: 0.20806246364991932
Fold 5 IBS: 0.1958343361367008
[I 2024-04-17 14:33:47,938] Trial 6 finished with value: 0.2059379186324341 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.22619880778504137
Fold 2 IBS: 0.20681656029484266
Fold 3 IBS: 0.1995134318053787
Fold 4 IBS: 0.21205607993694223
Fold 5 IBS: 0.19523375854617825
[I 2024-04-17 14:33:53,351] Trial 7 finished with value: 0.20796372767367663 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.23572756766823696
Fold 2 IBS: 0.2159954067804657
Fold 3 IBS: 0.207897540948402
Fold 4 IBS: 0.22335086095631992
Fold 5 IBS: 0.21082765695144778
[I 2024-04-17 14:33:54,328] Trial 8 finished with value: 0.21875980666097447 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.2362913854865242
Fold 2 IBS: 0.223119067098338
Fold 3 IBS: 0.21393735884208107
Fold 4 IBS: 0.2300813418212608
Fold 5 IBS: 0.21757086050309835
[I 2024-04-17 14:34:03,942] Trial 9 finished with value: 0.2242000027502605 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-17 14:34:12,067] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.22780493869829074
Fold 2 IBS: 0.2138061308976434
Fold 3 IBS: 0.2023305449080885
Fold 4 IBS: 0.21756438410745618
Fold 5 IBS: 0.20529268129027906
[I 2024-04-17 14:34:19,165] Trial 11 finished with value: 0.21335973598035157 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.20511395130083657.
Fold 1 IBS: 0.2214148363034931
Fold 2 IBS: 0.19900942691989856
Fold 3 IBS: 0.1962942205304067
Fold 4 IBS: 0.20169870785830693
Fold 5 IBS: 0.18810787505970553
[I 2024-04-17 14:34:30,388] Trial 12 finished with value: 0.20130501333436218 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.227905072273538
Fold 2 IBS: 0.21034413984894398
Fold 3 IBS: 0.1999399236505226
Fold 4 IBS: 0.2176424409962597
Fold 5 IBS: 0.20281855683931566
[I 2024-04-17 14:34:41,630] Trial 13 finished with value: 0.211730026721716 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.22872868047813785
Fold 2 IBS: 0.21165293011075872
Fold 3 IBS: 0.19988027214002238
Fold 4 IBS: 0.21880281498255888
Fold 5 IBS: 0.203773369570737
[I 2024-04-17 14:34:49,068] Trial 14 finished with value: 0.21256761345644293 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.20130501333436218.

Fold 1 IBS: 0.22847123890236778
Fold 2 IBS: 0.2119572241713072
Fold 3 IBS: 0.2000209382674373
Fold 4 IBS: 0.2191476540177961
Fold 5 IBS: 0.20357090040058298
[I 2024-04-17 14:34:54,430] Trial 15 finished with value: 0.21263359115189825 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.24156769282885268
Fold 2 IBS: 0.2253932217984834
Fold 3 IBS: 0.21934029294786409
Fold 4 IBS: 0.23668338930124344
Fold 5 IBS: 0.22091698014071526
[I 2024-04-17 14:35:03,924] Trial 16 finished with value: 0.2287803154034318 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.22751150452372834
Fold 2 IBS: 0.21595426691446282
Fold 3 IBS: 0.1987326228216213
Fold 4 IBS: 0.21555309372636242
Fold 5 IBS: 0.20038896211621152
[I 2024-04-17 14:35:09,909] Trial 17 finished with value: 0.21162809002047728 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-17 14:35:12,773] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.2271206509247316
Fold 2 IBS: 0.2107489366172366
Fold 3 IBS: 0.19876113302439577
Fold 4 IBS: 0.21767607677621764
Fold 5 IBS: 0.20290378562177042
[I 2024-04-17 14:35:19,860] Trial 19 finished with value: 0.21144211659287038 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.24630370330606782
Fold 2 IBS: 0.22814560512347226
Fold 3 IBS: 0.21504958463340565
Fold 4 IBS: 0.24002484073788238
Fold 5 IBS: 0.222605947332832
[I 2024-04-17 14:35:20,341] Trial 20 finished with value: 0.23042593622673202 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.22339877629584753
Fold 2 IBS: 0.20508241698130164
Fold 3 IBS: 0.1965271544083015
Fold 4 IBS: 0.20730377140127726
Fold 5 IBS: 0.19556939221244835
[I 2024-04-17 14:35:28,845] Trial 21 finished with value: 0.20557630225983528 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.22289946045951353
Fold 2 IBS: 0.20341606213443808
Fold 3 IBS: 0.1966994615163492
Fold 4 IBS: 0.2031257184708353
Fold 5 IBS: 0.19154678870450914
[I 2024-04-17 14:35:37,046] Trial 22 finished with value: 0.20353749825712902 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.20130501333436218.
Fold 1 IBS: 0.22272723121968271
Fold 2 IBS: 0.19724867621664788
Fold 3 IBS: 0.19443177973349035
Fold 4 IBS: 0.1962190697287693
Fold 5 IBS: 0.18349524361811503
[I 2024-04-17 14:35:45,873] Trial 23 finished with value: 0.19882440010334107 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22345098916983588
Fold 2 IBS: 0.2027689124449806
Fold 3 IBS: 0.19736683686527592
Fold 4 IBS: 0.20776701093398742
Fold 5 IBS: 0.19267662791643828
[I 2024-04-17 14:35:53,917] Trial 24 finished with value: 0.20480607546610363 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22638847467663406
Fold 2 IBS: 0.20725079077563022
Fold 3 IBS: 0.19876800375684234
Fold 4 IBS: 0.20761737722441556
Fold 5 IBS: 0.19496177718799687
[I 2024-04-17 14:36:01,268] Trial 25 finished with value: 0.2069972847243038 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22628270583539217
Fold 2 IBS: 0.20948295779114495
Fold 3 IBS: 0.19868315563945044
Fold 4 IBS: 0.21574454721463973
Fold 5 IBS: 0.2008347487136111
[I 2024-04-17 14:36:11,328] Trial 26 finished with value: 0.21020562303884768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22755340696919882
Fold 2 IBS: 0.21151266936026275
Fold 3 IBS: 0.19918109683566926
Fold 4 IBS: 0.21654596986858501
Fold 5 IBS: 0.20243427024718016
[I 2024-04-17 14:36:19,609] Trial 27 finished with value: 0.2114454826561792 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.23171259666402433
Fold 2 IBS: 0.21826154058430602
Fold 3 IBS: 0.20103399437656957
Fold 4 IBS: 0.21826038610030746
Fold 5 IBS: 0.20152593855346065
[I 2024-04-17 14:36:25,289] Trial 28 finished with value: 0.2141588912557336 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.23237455396731452
Fold 2 IBS: 0.21824821543770398
Fold 3 IBS: 0.2050112905415354
Fold 4 IBS: 0.2240853001357716
Fold 5 IBS: 0.20979060098607696
[I 2024-04-17 14:36:29,490] Trial 29 finished with value: 0.2179019922136805 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.19882440010334107.

Fold 1 IBS: 0.22598027269401894
Fold 2 IBS: 0.20325616222593693
Fold 3 IBS: 0.1974550403175071
Fold 4 IBS: 0.2074023934687235
Fold 5 IBS: 0.19292642074350533
[I 2024-04-17 14:36:36,479] Trial 30 finished with value: 0.20540405788993837 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22967288859416762
Fold 2 IBS: 0.2113244797524532
Fold 3 IBS: 0.20298863335242717
Fold 4 IBS: 0.21680618508524163
Fold 5 IBS: 0.2034856086972431
[I 2024-04-17 14:36:45,409] Trial 31 finished with value: 0.21285555909630655 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.38729268205187145, 'min_weight_fraction_leaf': 0.043457520259011145}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22215939279829072
Fold 2 IBS: 0.20406128322932277
Fold 3 IBS: 0.19868816781122678
Fold 4 IBS: 0.20644922360265452
Fold 5 IBS: 0.19471767862574318
[I 2024-04-17 14:36:53,178] Trial 32 finished with value: 0.20521514921344758 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.31539812817326685, 'min_weight_fraction_leaf': 0.032883966884085084}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22722514387815515
Fold 2 IBS: 0.21241529341635676
Fold 3 IBS: 0.1995266420867072
Fold 4 IBS: 0.21760562571736547
Fold 5 IBS: 0.20251859648128132
[I 2024-04-17 14:37:00,894] Trial 33 finished with value: 0.21185826031597316 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5072649448849403, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.21725071401761925
Fold 2 IBS: 0.2013904000442137
Fold 3 IBS: 0.19957146101343257
Fold 4 IBS: 0.20069417355042404
Fold 5 IBS: 0.19062240021044768
[I 2024-04-17 14:37:09,676] Trial 34 finished with value: 0.20190582976722746 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3838567274379424, 'min_weight_fraction_leaf': 0.06580888670307859}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22665420190632668
Fold 2 IBS: 0.21335803529479347
Fold 3 IBS: 0.1946231271496964
Fold 4 IBS: 0.21906087358989002
Fold 5 IBS: 0.20008040437617358
[I 2024-04-17 14:37:19,951] Trial 35 finished with value: 0.21075532846337602 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.17523937322026623, 'min_weight_fraction_leaf': 0.06944032885941434}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22423767130305491
Fold 2 IBS: 0.21210214699476843
Fold 3 IBS: 0.19843911522305432
Fold 4 IBS: 0.21272113213745045
Fold 5 IBS: 0.2002906811433587
[I 2024-04-17 14:37:26,776] Trial 36 finished with value: 0.2095581493603374 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 397, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4313463114219205, 'min_weight_fraction_leaf': 0.12553564094995012}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.2326431610313935
Fold 2 IBS: 0.21634579946736437
Fold 3 IBS: 0.2083110712935426
Fold 4 IBS: 0.22179451813666606
Fold 5 IBS: 0.21014356540715134
[I 2024-04-17 14:37:35,206] Trial 37 finished with value: 0.21784762306722358 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 478, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9245147124114204, 'min_weight_fraction_leaf': 0.07016272904381007}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22121215114542173
Fold 2 IBS: 0.20550048218542336
Fold 3 IBS: 0.19668646438804474
Fold 4 IBS: 0.20838912699790116
Fold 5 IBS: 0.1951153540611416
[I 2024-04-17 14:37:42,402] Trial 38 finished with value: 0.20538071575558653 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 419, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.510965036356378, 'min_weight_fraction_leaf': 0.002361340929773935}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.2463407640793776
Fold 2 IBS: 0.23222770604144616
Fold 3 IBS: 0.2295959489992517
Fold 4 IBS: 0.24144849402457555
Fold 5 IBS: 0.23023903004134166
[I 2024-04-17 14:37:52,820] Trial 39 finished with value: 0.23597038863719852 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 467, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.32764837275051567, 'min_weight_fraction_leaf': 0.060087725678669386}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.24652986191080353
Fold 2 IBS: 0.23217849061627138
Fold 3 IBS: 0.22956711411017128
Fold 4 IBS: 0.24149762354595625
Fold 5 IBS: 0.23028521039269648
[I 2024-04-17 14:37:59,042] Trial 40 finished with value: 0.23601166011517977 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8098970257094581, 'min_weight_fraction_leaf': 0.4492877633512613}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22182715338926792
Fold 2 IBS: 0.1971203828926341
Fold 3 IBS: 0.19372066265367915
Fold 4 IBS: 0.20029046815156606
Fold 5 IBS: 0.18609575427584582
[I 2024-04-17 14:38:07,333] Trial 41 finished with value: 0.19981088427259858 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4236302312050163, 'min_weight_fraction_leaf': 0.023335569624003825}. Best is trial 23 with value: 0.19882440010334107.
Fold 1 IBS: 0.22052229467390852
Fold 2 IBS: 0.19586251243792238
Fold 3 IBS: 0.19448990345933642
Fold 4 IBS: 0.1959737560347358
Fold 5 IBS: 0.18375986008560802
[I 2024-04-17 14:38:15,767] Trial 42 finished with value: 0.19812166533830222 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.444674248871581, 'min_weight_fraction_leaf': 0.025352461449765364}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22835083449517915
Fold 2 IBS: 0.2124876432582329
Fold 3 IBS: 0.2018598774101289
Fold 4 IBS: 0.21862537589106695
Fold 5 IBS: 0.20395153448278852
[I 2024-04-17 14:38:25,368] Trial 43 finished with value: 0.2130550531074793 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 480, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.38949500900395695, 'min_weight_fraction_leaf': 0.09223032857209086}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23205032788502086
Fold 2 IBS: 0.21530046226822966
Fold 3 IBS: 0.20723977990768186
Fold 4 IBS: 0.22170345784855205
Fold 5 IBS: 0.20818788681000544
[I 2024-04-17 14:38:36,221] Trial 44 finished with value: 0.21689638294389796 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.2723357299344083, 'min_weight_fraction_leaf': 0.05122761665822432}. Best is trial 42 with value: 0.19812166533830222.

Fold 1 IBS: 0.22287647469700594
Fold 2 IBS: 0.1940553114390468
Fold 3 IBS: 0.19175155066892782
Fold 4 IBS: 0.19737115000131933
Fold 5 IBS: 0.18562449372445605
[I 2024-04-17 14:38:39,069] Trial 45 finished with value: 0.1983357961061512 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 144, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.45259524202136425, 'min_weight_fraction_leaf': 0.018417023499892313}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22916955270668096
Fold 2 IBS: 0.19778087431618338
Fold 3 IBS: 0.1854433526765588
Fold 4 IBS: 0.20181347277974873
Fold 5 IBS: 0.1880563668012256
[I 2024-04-17 14:38:41,821] Trial 46 finished with value: 0.20045272385607946 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5411966867921882, 'min_weight_fraction_leaf': 0.017191498668975277}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2286517614062511
Fold 2 IBS: 0.2024246897093376
Fold 3 IBS: 0.19566178279010998
Fold 4 IBS: 0.20856491007803662
Fold 5 IBS: 0.19305121295599553
[I 2024-04-17 14:38:44,718] Trial 47 finished with value: 0.20567087138794618 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 127, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4614720952395339, 'min_weight_fraction_leaf': 0.022114053360980213}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.24664981502463437
Fold 2 IBS: 0.2322200826398056
Fold 3 IBS: 0.2293961495661191
Fold 4 IBS: 0.24138691788295835
Fold 5 IBS: 0.23043671773087732
[I 2024-04-17 14:38:49,200] Trial 48 finished with value: 0.23601793656887896 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 186, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5312564762628779, 'min_weight_fraction_leaf': 0.3078000969326991}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2280583666158949
Fold 2 IBS: 0.2129628772808487
Fold 3 IBS: 0.20214538042054536
Fold 4 IBS: 0.21686595696137076
Fold 5 IBS: 0.20244528658522282
[I 2024-04-17 14:38:50,873] Trial 49 finished with value: 0.21249557357277649 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 78, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5689440748118932, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22307454948143876
Fold 2 IBS: 0.201656579793062
Fold 3 IBS: 0.19587335518782037
Fold 4 IBS: 0.2021592567272975
Fold 5 IBS: 0.1885465903827517
[I 2024-04-17 14:38:53,428] Trial 50 finished with value: 0.20226206631447408 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 131, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.45737813033560454, 'min_weight_fraction_leaf': 0.02217994825057899}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22575198901352286
Fold 2 IBS: 0.19728174813173505
Fold 3 IBS: 0.19022390087463992
Fold 4 IBS: 0.20134720530082095
Fold 5 IBS: 0.1857757615414519
[I 2024-04-17 14:38:57,694] Trial 51 finished with value: 0.20007612097243413 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 185, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5333707780157013, 'min_weight_fraction_leaf': 0.0006963634720382195}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22592696171875998
Fold 2 IBS: 0.1980728231758125
Fold 3 IBS: 0.19134119683513995
Fold 4 IBS: 0.19927050101953694
Fold 5 IBS: 0.1857655196544986
[I 2024-04-17 14:39:01,232] Trial 52 finished with value: 0.2000754004807496 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5941643843137101, 'min_weight_fraction_leaf': 0.013630010251522993}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2252792134936032
Fold 2 IBS: 0.20059105623198428
Fold 3 IBS: 0.19303182567537377
Fold 4 IBS: 0.19973035474739095
Fold 5 IBS: 0.18579989112662446
[I 2024-04-17 14:39:05,305] Trial 53 finished with value: 0.20088646825499534 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 183, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5932340680159316, 'min_weight_fraction_leaf': 0.05145650947946475}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2269573445989057
Fold 2 IBS: 0.2111251167120231
Fold 3 IBS: 0.19997288394660034
Fold 4 IBS: 0.2162830165333461
Fold 5 IBS: 0.20087533963044873
[I 2024-04-17 14:39:10,702] Trial 54 finished with value: 0.2110427402842648 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 233, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4246584722161516, 'min_weight_fraction_leaf': 0.08564868526856925}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22153296336318662
Fold 2 IBS: 0.1979283273734307
Fold 3 IBS: 0.19565811758670162
Fold 4 IBS: 0.19661730335381764
Fold 5 IBS: 0.18032696247992536
[I 2024-04-17 14:39:14,942] Trial 55 finished with value: 0.19841273483141236 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 170, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6785839853149422, 'min_weight_fraction_leaf': 0.006217254192513115}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22245486973400452
Fold 2 IBS: 0.1994359258369329
Fold 3 IBS: 0.20015800583247942
Fold 4 IBS: 0.1949488297532662
Fold 5 IBS: 0.18239438326437343
[I 2024-04-17 14:39:17,799] Trial 56 finished with value: 0.1998784028842113 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 91, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6829589151594135, 'min_weight_fraction_leaf': 0.02620374672350434}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2227483016986916
Fold 2 IBS: 0.200307177727005
Fold 3 IBS: 0.19896528378682302
Fold 4 IBS: 0.1957480516364794
Fold 5 IBS: 0.18430091047361627
[I 2024-04-17 14:39:20,438] Trial 57 finished with value: 0.20041394506452304 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6800417073883052, 'min_weight_fraction_leaf': 0.05292835037307202}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22502248031379737
Fold 2 IBS: 0.1961099241407523
Fold 3 IBS: 0.19834706370450256
Fold 4 IBS: 0.19552143553581539
Fold 5 IBS: 0.18333721001777056
[I 2024-04-17 14:39:21,999] Trial 58 finished with value: 0.19966762274252764 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 62, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7181937541518727, 'min_weight_fraction_leaf': 0.032977443851488014}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.24641468172291092
Fold 2 IBS: 0.23210064262481112
Fold 3 IBS: 0.22968290256148355
Fold 4 IBS: 0.2417098388579302
Fold 5 IBS: 0.23035428988406187
[I 2024-04-17 14:39:23,595] Trial 59 finished with value: 0.2360524711302395 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 54, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7532175548267749, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 42 with value: 0.19812166533830222.

Fold 1 IBS: 0.23220651508936468
Fold 2 IBS: 0.21369563680773865
Fold 3 IBS: 0.20608638014766714
Fold 4 IBS: 0.22151810446466122
Fold 5 IBS: 0.20573567128046852
[I 2024-04-17 14:39:24,999] Trial 60 finished with value: 0.21584846155798004 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 58, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8169268332392909, 'min_weight_fraction_leaf': 0.10367333825975117}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2476024556204402
Fold 2 IBS: 0.2003214659562389
Fold 3 IBS: 0.19754714531258735
Fold 4 IBS: 0.20444596709444926
Fold 5 IBS: 0.1958957946158515
[I 2024-04-17 14:39:25,633] Trial 61 finished with value: 0.20916256571991348 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 12, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6660458430919959, 'min_weight_fraction_leaf': 0.034544336684675755}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22234667075813594
Fold 2 IBS: 0.19830375650942964
Fold 3 IBS: 0.1979066601828649
Fold 4 IBS: 0.19679582501279227
Fold 5 IBS: 0.1855797918053288
[I 2024-04-17 14:39:28,091] Trial 62 finished with value: 0.20018654085371032 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7527248151727444, 'min_weight_fraction_leaf': 0.025983046016598774}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2290421934220616
Fold 2 IBS: 0.19329926715642626
Fold 3 IBS: 0.19623249702611428
Fold 4 IBS: 0.19967470141089896
Fold 5 IBS: 0.18444570915149164
[I 2024-04-17 14:39:29,126] Trial 63 finished with value: 0.20053887363339853 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 36, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7158683957133232, 'min_weight_fraction_leaf': 0.04701405291807835}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2241203582941189
Fold 2 IBS: 0.20249757065061852
Fold 3 IBS: 0.19587125290629856
Fold 4 IBS: 0.20140332263670432
Fold 5 IBS: 0.19264586660065758
[I 2024-04-17 14:39:31,147] Trial 64 finished with value: 0.2033076742176796 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 76, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7784596861095077, 'min_weight_fraction_leaf': 0.08800507468207153}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2357782232834001
Fold 2 IBS: 0.2223042136579298
Fold 3 IBS: 0.21162270791479876
Fold 4 IBS: 0.23272784389203716
Fold 5 IBS: 0.21360482397617886
[I 2024-04-17 14:39:34,184] Trial 65 finished with value: 0.22320756254486893 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6160444444195798, 'min_weight_fraction_leaf': 0.25328155748023795}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.24661395559203125
Fold 2 IBS: 0.23218668788182192
Fold 3 IBS: 0.22954559488292564
Fold 4 IBS: 0.24150370266153354
Fold 5 IBS: 0.23041755393088637
[I 2024-04-17 14:39:39,222] Trial 66 finished with value: 0.23605349898983974 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6906372706489559, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2216568689212585
Fold 2 IBS: 0.2030133456600498
Fold 3 IBS: 0.19398879092519633
Fold 4 IBS: 0.20158328598846784
Fold 5 IBS: 0.19182907574197927
[I 2024-04-17 14:39:41,388] Trial 67 finished with value: 0.20241427344739032 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 101, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.480015026475249, 'min_weight_fraction_leaf': 0.0008246381471130292}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22882169151665857
Fold 2 IBS: 0.19110712630149604
Fold 3 IBS: 0.19803369472609647
Fold 4 IBS: 0.19358062270199736
Fold 5 IBS: 0.1869401963057543
[I 2024-04-17 14:39:42,330] Trial 68 finished with value: 0.19969666631040056 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 29, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.35822869031202215, 'min_weight_fraction_leaf': 0.03523982197149468}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.24073325759567724
Fold 2 IBS: 0.22484843724633022
Fold 3 IBS: 0.21666324023566227
Fold 4 IBS: 0.2325576659085032
Fold 5 IBS: 0.21753082370047921
[I 2024-04-17 14:39:43,103] Trial 69 finished with value: 0.2264666849373304 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.35021176388391145, 'min_weight_fraction_leaf': 0.15522746828620693}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2304070359545042
Fold 2 IBS: 0.2104044722879192
Fold 3 IBS: 0.2047887732641865
Fold 4 IBS: 0.22269749542149225
Fold 5 IBS: 0.2016439465280454
[I 2024-04-17 14:39:45,016] Trial 70 finished with value: 0.2139883446912295 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 68, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.2872166313030818, 'min_weight_fraction_leaf': 0.07215682640836035}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2253250722458979
Fold 2 IBS: 0.18875631121073763
Fold 3 IBS: 0.19921374952578366
Fold 4 IBS: 0.19141242687767238
Fold 5 IBS: 0.1937641077978392
[I 2024-04-17 14:39:45,793] Trial 71 finished with value: 0.19969433353158617 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 23, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3454941192472654, 'min_weight_fraction_leaf': 0.03232459084626502}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22896852236378681
Fold 2 IBS: 0.19717626084884676
Fold 3 IBS: 0.19763133343447675
Fold 4 IBS: 0.19342336606612162
Fold 5 IBS: 0.18520142886070687
[I 2024-04-17 14:39:46,957] Trial 72 finished with value: 0.20048018231478776 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 41, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.41358043570173236, 'min_weight_fraction_leaf': 0.03663479473408826}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23207943379779034
Fold 2 IBS: 0.19178758006757565
Fold 3 IBS: 0.2000784762872502
Fold 4 IBS: 0.1984983231717325
Fold 5 IBS: 0.18505636652297486
[I 2024-04-17 14:39:47,944] Trial 73 finished with value: 0.2015000359694647 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 32, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3463741057874233, 'min_weight_fraction_leaf': 0.015671195337093036}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23314204718151213
Fold 2 IBS: 0.2038449866626099
Fold 3 IBS: 0.19946510487345934
Fold 4 IBS: 0.21225172085787483
Fold 5 IBS: 0.20797990276426534
[I 2024-04-17 14:39:48,642] Trial 74 finished with value: 0.21133675246794428 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 16, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.37363203769482983, 'min_weight_fraction_leaf': 0.057617119440732015}. Best is trial 42 with value: 0.19812166533830222.

Fold 1 IBS: 0.2294093489012678
Fold 2 IBS: 0.20504726666419198
Fold 3 IBS: 0.20006965758583992
Fold 4 IBS: 0.2050072246769953
Fold 5 IBS: 0.19894671385728707
[I 2024-04-17 14:39:50,097] Trial 75 finished with value: 0.20769604233711642 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 60, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.24692331207272655, 'min_weight_fraction_leaf': 0.039366648465568074}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22918583286229247
Fold 2 IBS: 0.2105362939816168
Fold 3 IBS: 0.20102170693056107
Fold 4 IBS: 0.2158880397581989
Fold 5 IBS: 0.2037774224979302
[I 2024-04-17 14:39:54,012] Trial 76 finished with value: 0.2120818592061199 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 208, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3557782593003899, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2186481953338902
Fold 2 IBS: 0.19928742351837064
Fold 3 IBS: 0.19719530949023986
Fold 4 IBS: 0.20166371723748883
Fold 5 IBS: 0.1861566215214532
[I 2024-04-17 14:39:58,377] Trial 77 finished with value: 0.20059025342028852 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.30274987025373723, 'min_weight_fraction_leaf': 0.012852788783809403}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23289305479610728
Fold 2 IBS: 0.20902492533529068
Fold 3 IBS: 0.20831081359895617
Fold 4 IBS: 0.21319021524709614
Fold 5 IBS: 0.21217480709262776
[I 2024-04-17 14:39:59,184] Trial 78 finished with value: 0.2151187632140156 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 23, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.44390074520095374, 'min_weight_fraction_leaf': 0.11420271634452443}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23851087427569898
Fold 2 IBS: 0.1972888644887421
Fold 3 IBS: 0.19830820059838758
Fold 4 IBS: 0.23266766955014692
Fold 5 IBS: 0.219844788114054
[I 2024-04-17 14:39:59,771] Trial 79 finished with value: 0.21732407940540593 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.410836620907804, 'min_weight_fraction_leaf': 0.058545101525741314}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23140269346681075
Fold 2 IBS: 0.21451878197522486
Fold 3 IBS: 0.20639446911427722
Fold 4 IBS: 0.22014654958950228
Fold 5 IBS: 0.20916213077589133
[I 2024-04-17 14:40:02,241] Trial 80 finished with value: 0.2163249249843413 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 110, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5095861562397511, 'min_weight_fraction_leaf': 0.09501184585248543}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2278648473315173
Fold 2 IBS: 0.20016964597375025
Fold 3 IBS: 0.1990565680545547
Fold 4 IBS: 0.19645630273585746
Fold 5 IBS: 0.18527564230060622
[I 2024-04-17 14:40:03,478] Trial 81 finished with value: 0.2017646012792572 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 49, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7082931432590726, 'min_weight_fraction_leaf': 0.03247592420855491}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22071515471570607
Fold 2 IBS: 0.1991831764870978
Fold 3 IBS: 0.19921662729395856
Fold 4 IBS: 0.19533843012017205
Fold 5 IBS: 0.18282286910390352
[I 2024-04-17 14:40:05,316] Trial 82 finished with value: 0.1994552515441676 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 80, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.652132905435162, 'min_weight_fraction_leaf': 0.026025171676801587}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2940293555469905
Fold 2 IBS: 0.20605816105107896
Fold 3 IBS: 0.1562898279520896
Fold 4 IBS: 0.22032462010508333
Fold 5 IBS: 0.22015133083239552
[I 2024-04-17 14:40:05,730] Trial 83 finished with value: 0.2193706590975276 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 2, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6629775025015184, 'min_weight_fraction_leaf': 0.010803271900999365}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22338434249488293
Fold 2 IBS: 0.20084736024579483
Fold 3 IBS: 0.19668406967724325
Fold 4 IBS: 0.20077439480485587
Fold 5 IBS: 0.18470439672448138
[I 2024-04-17 14:40:08,555] Trial 84 finished with value: 0.2012789127894517 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 140, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7413450808637427, 'min_weight_fraction_leaf': 0.046479058761281195}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23230347770380416
Fold 2 IBS: 0.21752594991862342
Fold 3 IBS: 0.20571700606482463
Fold 4 IBS: 0.2250922937089719
Fold 5 IBS: 0.20959844707120232
[I 2024-04-17 14:40:16,791] Trial 85 finished with value: 0.21804743489348527 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.21037897764136995, 'min_weight_fraction_leaf': 0.027121125275212953}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.2231694391739802
Fold 2 IBS: 0.20533984228120053
Fold 3 IBS: 0.19658340268163357
Fold 4 IBS: 0.20533116155774087
Fold 5 IBS: 0.1913834433376034
[I 2024-04-17 14:40:19,235] Trial 86 finished with value: 0.20436145780643172 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 120, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6240152479043125, 'min_weight_fraction_leaf': 0.06411489657371686}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.23204225510300125
Fold 2 IBS: 0.21874798507721377
Fold 3 IBS: 0.2058550176040823
Fold 4 IBS: 0.22542690048932143
Fold 5 IBS: 0.21117323765154636
[I 2024-04-17 14:40:26,435] Trial 87 finished with value: 0.218649079185033 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4743004019536968, 'min_weight_fraction_leaf': 0.012119053430116652}. Best is trial 42 with value: 0.19812166533830222.
Fold 1 IBS: 0.22086781296332894
Fold 2 IBS: 0.19758021710660906
Fold 3 IBS: 0.19462976661960638
Fold 4 IBS: 0.19439187294753865
Fold 5 IBS: 0.1826393476626777
[I 2024-04-17 14:40:35,801] Trial 88 finished with value: 0.19802180345995218 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.645870061571142, 'min_weight_fraction_leaf': 0.04343316649769846}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.2212418284793883
Fold 2 IBS: 0.1979901984361561
Fold 3 IBS: 0.1949115074920968
Fold 4 IBS: 0.19508830715332773
Fold 5 IBS: 0.18220265554858003
[I 2024-04-17 14:40:43,037] Trial 89 finished with value: 0.19828689942190977 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 402, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6462128487527559, 'min_weight_fraction_leaf': 0.04232137501041048}. Best is trial 88 with value: 0.19802180345995218.

Fold 1 IBS: 0.22333454988172624
Fold 2 IBS: 0.20471686652589108
Fold 3 IBS: 0.1965824831525379
Fold 4 IBS: 0.20553535669394332
Fold 5 IBS: 0.1931394895314824
[I 2024-04-17 14:40:50,735] Trial 90 finished with value: 0.20466174915711619 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 410, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6447189305878098, 'min_weight_fraction_leaf': 0.07726698990049516}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.22258797570811703
Fold 2 IBS: 0.19713732800880507
Fold 3 IBS: 0.19548622953950795
Fold 4 IBS: 0.19512550692672126
Fold 5 IBS: 0.18346894725823412
[I 2024-04-17 14:40:58,764] Trial 91 finished with value: 0.19876119748827709 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7102601080400145, 'min_weight_fraction_leaf': 0.044389506981875285}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.22017855824133473
Fold 2 IBS: 0.19894240698624552
Fold 3 IBS: 0.19467138837478914
Fold 4 IBS: 0.195876440513952
Fold 5 IBS: 0.18503590001111012
[I 2024-04-17 14:41:06,567] Trial 92 finished with value: 0.1989409388254863 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7092736652144245, 'min_weight_fraction_leaf': 0.04626855999010507}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.2201169987594542
Fold 2 IBS: 0.19917771729421638
Fold 3 IBS: 0.19548322424694997
Fold 4 IBS: 0.19681283094076096
Fold 5 IBS: 0.18494506650526044
[I 2024-04-17 14:41:14,691] Trial 93 finished with value: 0.1993071675493284 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7091922565633831, 'min_weight_fraction_leaf': 0.04649245645436455}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.22001579888059922
Fold 2 IBS: 0.20109546319547683
Fold 3 IBS: 0.19660339255365275
Fold 4 IBS: 0.1988327271872217
Fold 5 IBS: 0.18842811022971234
[I 2024-04-17 14:41:22,711] Trial 94 finished with value: 0.20099509840933258 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6577082313264122, 'min_weight_fraction_leaf': 0.05687387629179948}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.22909376708334614
Fold 2 IBS: 0.21435950985576488
Fold 3 IBS: 0.20221185326386787
Fold 4 IBS: 0.22071413058827744
Fold 5 IBS: 0.20789992858401282
[I 2024-04-17 14:41:29,925] Trial 95 finished with value: 0.21485583787505386 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7985768737694462, 'min_weight_fraction_leaf': 0.2160659665932624}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.22085748906821134
Fold 2 IBS: 0.19912052088527124
Fold 3 IBS: 0.19550238986251847
Fold 4 IBS: 0.19631719407920872
Fold 5 IBS: 0.18432635862129187
[I 2024-04-17 14:41:36,762] Trial 96 finished with value: 0.19922479050330033 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7001971199693383, 'min_weight_fraction_leaf': 0.04485182043039717}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.22773265225864803
Fold 2 IBS: 0.20901201846884213
Fold 3 IBS: 0.19878014203376515
Fold 4 IBS: 0.21366126703201188
Fold 5 IBS: 0.2013740887055449
[I 2024-04-17 14:41:43,434] Trial 97 finished with value: 0.2101120336997624 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7365948032843015, 'min_weight_fraction_leaf': 0.043313998146245244}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.22194962782480768
Fold 2 IBS: 0.2016137869000081
Fold 3 IBS: 0.1956776138898432
Fold 4 IBS: 0.20096392448926065
Fold 5 IBS: 0.1898638227454881
[I 2024-04-17 14:41:50,690] Trial 98 finished with value: 0.20201375516988157 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.756800955881348, 'min_weight_fraction_leaf': 0.0656100959753811}. Best is trial 88 with value: 0.19802180345995218.
Fold 1 IBS: 0.2205024791551057
Fold 2 IBS: 0.19857637625119653
Fold 3 IBS: 0.19546440617936373
Fold 4 IBS: 0.19535190892463417
Fold 5 IBS: 0.18401838259646244
[I 2024-04-17 14:41:58,786] Trial 99 finished with value: 0.1987827106213525 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7060835680698947, 'min_weight_fraction_leaf': 0.04637429036508914}. Best is trial 88 with value: 0.19802180345995218.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.19802180345995218], datetime_start=datetime.datetime(2024, 4, 17, 14, 40, 26, 443913), datetime_complete=datetime.datetime(2024, 4, 17, 14, 40, 35, 798987), params={'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.645870061571142, 'min_weight_fraction_leaf': 0.04343316649769846}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.19802180345995218

In [59]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.841
train_ibs:  0.198

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=14, max_features=0.1, max_leaf_nodes=19,
                   max_samples=0.953229637324892, min_samples_leaf=1,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.0029509030346900195,
                   n_estimators=77, random_state=123, warm_start=True)

C-index score: 0.581

ExtraSurvivalTrees(max_depth=12, max_leaf_nodes=20,
                   max_samples=0.645870061571142, min_samples_split=5,
                   min_weight_fraction_leaf=0.04343316649769846,
                   n_estimators=432, random_state=123, warm_start=True)

IBS: 0.229

In [63]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [64]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:42:00,920] A new study created in memory with name: no-name-66454e24-0af7-4c34-9226-c817035d4107

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:42:39,458] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:42:59,366] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:43:18,001] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:43:48,532] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:44:01,440] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:44:04,589] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:44:35,507] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:44:45,001] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:44:46,082] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 14:46:08,448] Trial 9 finished with value: 0.7029978834112648 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-17 14:48:14,399] Trial 10 finished with value: 0.6731409344204184 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:50:39,101] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-17 14:52:42,796] Trial 12 finished with value: 0.6896245529930841 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7029978834112648.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:53:48,387] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:55:08,279] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:56:17,286] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:02,932] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:58:38,184] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:01:04,922] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:01:10,623] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:02:10,362] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-17 15:04:09,051] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7344961240310077
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6437768240343348
[I 2024-04-17 15:05:58,252] Trial 22 finished with value: 0.6595732439335746 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:07:48,903] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:09:12,304] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:11:00,574] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:11:47,260] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:13:47,392] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:13:53,834] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:15:09,315] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:15:32,109] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.648068669527897
[I 2024-04-17 15:17:10,380] Trial 31 finished with value: 0.6148553306063567 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:17,856] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:41,077] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:03,486] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-17 15:23:01,292] Trial 35 finished with value: 0.6720678122425536 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:23:42,792] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:24:15,021] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:24:42,127] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:09,561] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:41,766] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.6553784860557769
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6330472103004292
[I 2024-04-17 15:27:41,838] Trial 41 finished with value: 0.6575921235409717 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:29:10,226] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:31:01,944] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:31:33,209] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:33:34,219] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7029978834112648.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.6995708154506438
[I 2024-04-17 15:33:51,151] Trial 46 finished with value: 0.7298446961928315 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7298446961928315.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:34:19,518] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7298446961928315.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:34:20,042] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.7298446961928315.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:34:37,744] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.7298446961928315.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:35:42,340] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.7298446961928315.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 15:36:54,044] Trial 51 finished with value: 0.6976681882569395 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7298446961928315.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:37:32,680] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7298446961928315.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.7274678111587983
[I 2024-04-17 15:38:50,375] Trial 53 finished with value: 0.7357373040500256 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:39:49,308] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.04642759977764528, 'dropout_rate': 0.5787056799551111, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8043967529855988, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.9987906743578988, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:40:16,826] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9338509253358491, 'learning_rate': 0.05026798356278357, 'dropout_rate': 0.8859792395781099, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 2.0925706859481137, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.9220343002247878, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:41:31,770] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8543724704763108, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.3004273858397456, 'min_weight_fraction_leaf': 0.19369329911983815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.7360515021459227
[I 2024-04-17 15:41:39,790] Trial 57 finished with value: 0.7237998832081741 and parameters: {'subsample': 0.9087026240599475, 'learning_rate': 0.08124746006044987, 'dropout_rate': 0.997784793728882, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.410591151226506, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8063875242325604, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:41:48,594] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8212698530092863, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.181840851947653, 'min_weight_fraction_leaf': 0.4057697411163346, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8125246339086644, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 5}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:42:01,552] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9193087392842657, 'learning_rate': 0.0872713586054678, 'dropout_rate': 0.9474892480356638, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.3337975605954647, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.7937489212794213, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:42:04,851] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.7446094350786215, 'learning_rate': 0.09733264341118891, 'dropout_rate': 0.9841116957888287, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.6816514323618716, 'min_weight_fraction_leaf': 0.21423049941460018, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.7693486777346097, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.7357373040500256.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:42:27,118] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.079755577636651, 'dropout_rate': 0.9141007682217919, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.3860962100040052, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.960062895620913, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6630901287553648
[I 2024-04-17 15:42:56,487] Trial 62 finished with value: 0.6806892172723108 and parameters: {'subsample': 0.9950153281899117, 'learning_rate': 0.08115591715872426, 'dropout_rate': 0.8285090704895912, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.46340528439350875, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.8636512797881153, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5836909871244635
[I 2024-04-17 15:43:22,421] Trial 63 finished with value: 0.5392388331797455 and parameters: {'subsample': 0.9879857181271309, 'learning_rate': 0.08167353877257796, 'dropout_rate': 0.8555425487679464, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.4732508331244123, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.8698220228130342, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:43:41,235] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9998194099499076, 'learning_rate': 0.08518105894428284, 'dropout_rate': 0.9084790128000951, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.43893162961234394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0018957941321912743, 'validation_fraction': 0.6573317669908815, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:44:36,588] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8863506781235784, 'learning_rate': 0.09077517237486941, 'dropout_rate': 0.7155053041594167, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 1.0503703250594787, 'min_weight_fraction_leaf': 0.41623993393470454, 'max_features': 'sqrt', 'min_impurity_decrease': 5.4764171179088326e-05, 'validation_fraction': 0.7243703387674565, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:45:15,695] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9116050534419412, 'learning_rate': 0.07264703745168608, 'dropout_rate': 0.8194893498338957, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.5401195366715463, 'min_weight_fraction_leaf': 0.45613333197683914, 'max_features': 'sqrt', 'min_impurity_decrease': 0.013056447447707517, 'validation_fraction': 0.9169313175992941, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:45:26,786] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.2507118299802445, 'learning_rate': 0.036515998728865476, 'dropout_rate': 0.9726102863603132, 'n_estimators': 371, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.48294812651480895, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0016007967193364127, 'validation_fraction': 0.8429859516851567, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:46:11,908] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8371795305913793, 'learning_rate': 0.04255428671400532, 'dropout_rate': 0.633247084204052, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.8386209432307415, 'min_weight_fraction_leaf': 0.43086676861494394, 'max_features': 1, 'min_impurity_decrease': 0.006343103938039445, 'validation_fraction': 0.8911962268662544, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:46:30,493] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.9464359352204211, 'learning_rate': 0.06174138905299288, 'dropout_rate': 0.9285880327607973, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.45960319442458425, 'min_weight_fraction_leaf': 0.23985000065202236, 'max_features': 'log2', 'min_impurity_decrease': 0.00030338628790529525, 'validation_fraction': 0.329118980782965, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7357373040500256.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7170212765957447
Fold 4 C-index: 0.8307984790874525
Fold 5 C-index: 0.7296137339055794
[I 2024-04-17 15:47:32,088] Trial 70 finished with value: 0.7444332373414558 and parameters: {'subsample': 0.7868009537469239, 'learning_rate': 0.06760822881110454, 'dropout_rate': 0.4501645913744281, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.010068295219290181, 'min_weight_fraction_leaf': 0.31623455708072684, 'max_features': 0.1, 'min_impurity_decrease': 1.7127716189044953e-05, 'validation_fraction': 0.773508933151765, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7444332373414558.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.8269961977186312
Fold 5 C-index: 0.7060085836909872
[I 2024-04-17 15:48:44,291] Trial 71 finished with value: 0.7388000109620979 and parameters: {'subsample': 0.8731481729382106, 'learning_rate': 0.06824697098399125, 'dropout_rate': 0.44693614056417824, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.3047914794183888, 'max_features': 0.1, 'min_impurity_decrease': 3.976633059647162e-05, 'validation_fraction': 0.7895458945773391, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7444332373414558.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:49:47,662] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7823514804378748, 'learning_rate': 0.05594196279186142, 'dropout_rate': 0.4470080666838303, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 0.3009753821860147, 'min_weight_fraction_leaf': 0.3059540589853319, 'max_features': 0.1, 'min_impurity_decrease': 1.5867418332223817e-05, 'validation_fraction': 0.7793460995771967, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 70 with value: 0.7444332373414558.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:50:58,971] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8663908775735847, 'learning_rate': 0.06632362371857915, 'dropout_rate': 0.5067723878896389, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.618560685045426, 'min_weight_fraction_leaf': 0.31460076590199093, 'max_features': 0.1, 'min_impurity_decrease': 8.328437416038891e-06, 'validation_fraction': 0.7008907913024036, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 7}. Best is trial 70 with value: 0.7444332373414558.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:52:16,399] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8288686373854733, 'learning_rate': 0.05998088897970471, 'dropout_rate': 0.35479137028960395, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.9759418026741545, 'min_weight_fraction_leaf': 0.2773249572889655, 'max_features': 0.1, 'min_impurity_decrease': 5.198140001660516e-05, 'validation_fraction': 0.7466111961316684, 'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 70 with value: 0.7444332373414558.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8269961977186312
Fold 5 C-index: 0.7296137339055794
[I 2024-04-17 15:52:58,244] Trial 75 finished with value: 0.748814332624946 and parameters: {'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:53:37,248] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.90806151385064, 'learning_rate': 0.06937411702873973, 'dropout_rate': 0.5775100962015742, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.3026218647170148, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 3.1759196242669716e-05, 'validation_fraction': 0.8054405672668666, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:54:08,803] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8021858195531186, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.4930834587163687, 'n_estimators': 291, 'criterion': 'squared_error', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.25797282688791734, 'max_features': 0.1, 'min_impurity_decrease': 8.194270761449124e-05, 'validation_fraction': 0.8191017051978536, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.7124463519313304
[I 2024-04-17 15:54:56,322] Trial 78 finished with value: 0.7385613491771981 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.05690511629279836, 'dropout_rate': 0.5670668275300401, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.3008453270284027, 'max_features': 0.1, 'min_impurity_decrease': 9.997537740252558e-05, 'validation_fraction': 0.634085956732461, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:55:48,455] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7354140786592815, 'learning_rate': 0.04969314557779707, 'dropout_rate': 0.44525279135712004, 'n_estimators': 366, 'criterion': 'squared_error', 'ccp_alpha': 0.5591541411162989, 'min_weight_fraction_leaf': 0.27054049814219927, 'max_features': 0.1, 'min_impurity_decrease': 0.0001332335562751616, 'validation_fraction': 0.6322159428309632, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:56:49,062] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.4097359359491849, 'n_estimators': 387, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.2916012333412588, 'max_features': 0.1, 'min_impurity_decrease': 3.446222542448271e-05, 'validation_fraction': 0.658619742124138, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7060085836909872
[I 2024-04-17 15:57:24,113] Trial 81 finished with value: 0.7361779275600209 and parameters: {'subsample': 0.8900437147371856, 'learning_rate': 0.05732267025618887, 'dropout_rate': 0.5675964787359803, 'n_estimators': 338, 'criterion': 'squared_error', 'ccp_alpha': 0.02537647186946867, 'min_weight_fraction_leaf': 0.3203794260312518, 'max_features': 0.1, 'min_impurity_decrease': 0.00011928163703594395, 'validation_fraction': 0.5473179941373633, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:58:01,697] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.674646944161499, 'learning_rate': 0.06428673292745038, 'dropout_rate': 0.5603615855034783, 'n_estimators': 347, 'criterion': 'squared_error', 'ccp_alpha': 0.28819151280834227, 'min_weight_fraction_leaf': 0.30301215361806194, 'max_features': 0.1, 'min_impurity_decrease': 0.00011381045599980596, 'validation_fraction': 0.5688457919188374, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:58:35,234] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7076615576312072, 'learning_rate': 0.056710204467247914, 'dropout_rate': 0.6033560518396526, 'n_estimators': 335, 'criterion': 'squared_error', 'ccp_alpha': 0.8202792651285943, 'min_weight_fraction_leaf': 0.31878503420088733, 'max_features': 0.1, 'min_impurity_decrease': 0.0002767446387407935, 'validation_fraction': 0.51243688588132, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:59:20,800] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8885223542936614, 'learning_rate': 0.07000519724522539, 'dropout_rate': 0.5288642574811846, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 0.5149081571445734, 'min_weight_fraction_leaf': 0.34755924952935247, 'max_features': 0.1, 'min_impurity_decrease': 1.6951185184740712e-05, 'validation_fraction': 0.4777741397542481, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.748814332624946.

Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.8231939163498099
Fold 5 C-index: 0.723175965665236
[I 2024-04-17 15:59:59,186] Trial 85 finished with value: 0.7409093350180296 and parameters: {'subsample': 0.8605990508338958, 'learning_rate': 0.052056821807615235, 'dropout_rate': 0.4591414560091507, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 0.011402478584663527, 'min_weight_fraction_leaf': 0.33201592938914204, 'max_features': 0.1, 'min_impurity_decrease': 4.500909928644848e-05, 'validation_fraction': 0.585795551959921, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:00:39,155] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.8602325771048466, 'learning_rate': 0.060666799241958703, 'dropout_rate': 0.4544018342257149, 'n_estimators': 320, 'criterion': 'squared_error', 'ccp_alpha': 0.22931497714889953, 'min_weight_fraction_leaf': 0.36106190454255527, 'max_features': 0.1, 'min_impurity_decrease': 0.0001528555634091728, 'validation_fraction': 0.5817279039264187, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:01:11,105] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7587617437729911, 'learning_rate': 0.04761165440524907, 'dropout_rate': 0.4957903377584335, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 1.080975311316525, 'min_weight_fraction_leaf': 0.3363100713943507, 'max_features': 0.1, 'min_impurity_decrease': 0.00046289489298800726, 'validation_fraction': 0.5377854514350624, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:01:36,970] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9306795844790319, 'learning_rate': 0.051627622421456736, 'dropout_rate': 0.4234035172725829, 'n_estimators': 252, 'criterion': 'squared_error', 'ccp_alpha': 0.7265789482493736, 'min_weight_fraction_leaf': 0.3769812431626508, 'max_features': 0.1, 'min_impurity_decrease': 4.642862113005286e-05, 'validation_fraction': 0.4739493451385479, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.6832669322709163
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.8231939163498099
Fold 5 C-index: 0.723175965665236
[I 2024-04-17 16:02:08,073] Trial 89 finished with value: 0.7436710540991518 and parameters: {'subsample': 0.8391283049189849, 'learning_rate': 0.055724086293807554, 'dropout_rate': 0.6569553700677857, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.01877120542983873, 'min_weight_fraction_leaf': 0.32461639571647416, 'max_features': 0.1, 'min_impurity_decrease': 8.851047050185397e-05, 'validation_fraction': 0.6010087752598334, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:02:55,721] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.826829689860655, 'learning_rate': 0.05508607313298636, 'dropout_rate': 0.4747673828195568, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.46861411786043294, 'min_weight_fraction_leaf': 0.3271740396549214, 'max_features': 0.1, 'min_impurity_decrease': 9.545901155149427e-05, 'validation_fraction': 0.5913771141991949, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.6974248927038627
[I 2024-04-17 16:03:35,615] Trial 91 finished with value: 0.7246235252770237 and parameters: {'subsample': 0.9670051193547057, 'learning_rate': 0.05358528744281843, 'dropout_rate': 0.658599767424636, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.037871277159682165, 'min_weight_fraction_leaf': 0.28864883630713, 'max_features': 0.1, 'min_impurity_decrease': 0.00022284757650732192, 'validation_fraction': 0.6230196429197797, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:04:03,203] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.04507048157049061, 'dropout_rate': 0.6619274742089222, 'n_estimators': 319, 'criterion': 'squared_error', 'ccp_alpha': 0.1977251065362092, 'min_weight_fraction_leaf': 0.2997333226617717, 'max_features': 0.1, 'min_impurity_decrease': 3.110697272043209e-05, 'validation_fraction': 0.7057224083251947, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:04:46,208] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8713442146116508, 'learning_rate': 0.056893055161794756, 'dropout_rate': 0.6240038144153928, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.2020936997276668, 'min_weight_fraction_leaf': 0.27879305118961123, 'max_features': 0.1, 'min_impurity_decrease': 0.0002253362395408032, 'validation_fraction': 0.5411649201375784, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 7}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:05:26,203] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.846552766071321, 'learning_rate': 0.05225166033787123, 'dropout_rate': 0.5466158596699147, 'n_estimators': 343, 'criterion': 'squared_error', 'ccp_alpha': 0.5371670207357605, 'min_weight_fraction_leaf': 0.25551392419012386, 'max_features': 0.1, 'min_impurity_decrease': 1.9306777571724905e-05, 'validation_fraction': 0.612298406876781, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:06:09,696] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.7863806056473801, 'learning_rate': 0.06528678713702542, 'dropout_rate': 0.5828268476051283, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.9669214947186134, 'min_weight_fraction_leaf': 0.31565449545198027, 'max_features': 0.1, 'min_impurity_decrease': 9.721858189938487e-05, 'validation_fraction': 0.6404170541911562, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7081545064377682
[I 2024-04-17 16:06:58,399] Trial 96 finished with value: 0.7357318928807334 and parameters: {'subsample': 0.8988051132134279, 'learning_rate': 0.06223070527189957, 'dropout_rate': 0.5156283651894482, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.03101134846799354, 'min_weight_fraction_leaf': 0.34626128365000786, 'max_features': 0.1, 'min_impurity_decrease': 1.3094627017216677e-05, 'validation_fraction': 0.6632572619204413, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:07:29,988] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8930015289701463, 'learning_rate': 0.06902066318585262, 'dropout_rate': 0.5184399591044937, 'n_estimators': 283, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5919142503363208, 'min_weight_fraction_leaf': 0.3422673006104069, 'max_features': 0.1, 'min_impurity_decrease': 5.5764874089214735e-06, 'validation_fraction': 0.7616280705465504, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:08:28,804] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.942045846088557, 'learning_rate': 0.06288058679534973, 'dropout_rate': 0.3935493432557001, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.3577731226925447, 'max_features': 0.1, 'min_impurity_decrease': 1.156868105608801e-05, 'validation_fraction': 0.600618054420014, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 75 with value: 0.748814332624946.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-17 16:09:08,581] A new study created in memory with name: no-name-fb2b7715-ec6b-427b-ba85-9d1611076e7a

Fold 5 C-index: 0.5
[I 2024-04-17 16:09:08,551] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.049284729388966816, 'dropout_rate': 0.45996102545694106, 'n_estimators': 303, 'criterion': 'squared_error', 'ccp_alpha': 0.7672999858929114, 'min_weight_fraction_leaf': 0.32399936293704884, 'max_features': 0.1, 'min_impurity_decrease': 3.940812479835256e-05, 'validation_fraction': 0.6748895535913024, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 75 with value: 0.748814332624946.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.748814332624946], datetime_start=datetime.datetime(2024, 4, 17, 15, 52, 16, 410569), datetime_complete=datetime.datetime(2024, 4, 17, 15, 52, 58, 243082), params={'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for C-index:
 0.748814332624946

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:09:51,499] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:10:11,558] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:10:29,999] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 16:11:00,564] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:11:14,436] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:11:17,844] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:11:47,575] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:11:55,805] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:11:56,862] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.2460306488370946
Fold 2 IBS: 0.23040447180712803
Fold 3 IBS: 0.22864024470832855
Fold 4 IBS: 0.24082820787468318
Fold 5 IBS: 0.22855419382361605
[I 2024-04-17 16:13:17,419] Trial 9 finished with value: 0.2348915534101701 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23166000859087926
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-17 16:15:31,147] Trial 10 finished with value: 0.23563424132764627 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 16:17:48,928] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24715489611868932
Fold 2 IBS: 0.23184894207719414
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-17 16:19:44,647] Trial 12 finished with value: 0.23582778641053603 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:20:42,513] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:22:33,715] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:23:58,624] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:24:42,686] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:26:27,816] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:27:21,514] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:27:30,876] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:29:05,436] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24710981631467982
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-17 16:30:43,482] Trial 21 finished with value: 0.2358286001617127 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348915534101701.
Fold 1 IBS: 0.24611420173689824
Fold 2 IBS: 0.23009057354067086
Fold 3 IBS: 0.2285343921071035

Fold 4 IBS: 0.24076992163194547
Fold 5 IBS: 0.2286216341553957
[I 2024-04-17 16:32:31,914] Trial 22 finished with value: 0.23482614463440274 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:34:04,083] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:35:01,608] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:35:49,765] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:37:06,110] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:37:13,873] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 16:37:40,659] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:38:48,672] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:39:17,445] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24695000891576355
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-17 16:40:44,957] Trial 31 finished with value: 0.2356643163163706 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24599192585726218
Fold 2 IBS: 0.23031071547913376
Fold 3 IBS: 0.22852247093857828
Fold 4 IBS: 0.24075522979606004
Fold 5 IBS: 0.2286298290337006
[I 2024-04-17 16:42:12,310] Trial 32 finished with value: 0.23484203422094696 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:43:23,011] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:44:38,719] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 16:44:54,106] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:46:16,812] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:46:19,381] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 16:47:02,431] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:47:54,932] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:48:50,483] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24645924748918105
Fold 2 IBS: 0.23089886934018614
Fold 3 IBS: 0.22863585294540403
Fold 4 IBS: 0.24117285579166686
Fold 5 IBS: 0.22886101346789353
[I 2024-04-17 16:50:09,344] Trial 41 finished with value: 0.2352055678068663 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24604888143635387
Fold 2 IBS: 0.23040319886053304
Fold 3 IBS: 0.22846574053812793
Fold 4 IBS: 0.24081655094508178
Fold 5 IBS: 0.22858855522706506
[I 2024-04-17 16:51:37,049] Trial 42 finished with value: 0.23486458540143235 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:53:06,204] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:54:08,236] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24690672041183456
Fold 2 IBS: 0.23157081218881248
Fold 3 IBS: 0.22867880509098854
Fold 4 IBS: 0.24153436098244543
Fold 5 IBS: 0.22904780221266594
[I 2024-04-17 16:55:10,167] Trial 45 finished with value: 0.23554770017734938 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:56:15,825] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:56:42,944] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:56:43,399] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 16:56:57,955] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 16:58:18,650] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24694416117476983
Fold 2 IBS: 0.23160597050254403
Fold 3 IBS: 0.2286958830541089
Fold 4 IBS: 0.2415494327143545
Fold 5 IBS: 0.2290607688112509
[I 2024-04-17 16:59:18,290] Trial 51 finished with value: 0.2355712432514056 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:00:40,712] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24636181005117128
Fold 2 IBS: 0.23077149269210562
Fold 3 IBS: 0.22812031035041508
Fold 4 IBS: 0.24076852239901633
Fold 5 IBS: 0.22843795521572158
[I 2024-04-17 17:01:43,524] Trial 53 finished with value: 0.23489201814168598 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 17:03:00,741] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 17:04:03,082] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:05:02,766] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:05:56,210] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:07:15,859] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:08:24,706] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:09:01,305] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 17:09:51,267] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24682815897035923
Fold 2 IBS: 0.23135765186743468
Fold 3 IBS: 0.22855207174648276
Fold 4 IBS: 0.24130022398885415
Fold 5 IBS: 0.22889414601547717
[I 2024-04-17 17:10:35,709] Trial 62 finished with value: 0.23538645051772158 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:11:22,955] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24639260947577715
Fold 2 IBS: 0.2305545660317617
Fold 3 IBS: 0.22810454878348146
Fold 4 IBS: 0.24117497242562638
Fold 5 IBS: 0.2286573507456251
[I 2024-04-17 17:12:03,306] Trial 64 finished with value: 0.2349768094924544 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-17 17:12:42,793] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:13:32,321] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:14:00,826] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:15:10,313] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:16:10,162] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:17:04,589] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.2468392769985588
Fold 2 IBS: 0.23136481806402914
Fold 3 IBS: 0.22855322831427202
Fold 4 IBS: 0.24129654189301625
Fold 5 IBS: 0.22890663760885824
[I 2024-04-17 17:17:52,491] Trial 71 finished with value: 0.2353921005757469 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24699367022861488
Fold 2 IBS: 0.23163799997148876
Fold 3 IBS: 0.22871439628387724
Fold 4 IBS: 0.24157051782049635
Fold 5 IBS: 0.22909863489447807
[I 2024-04-17 17:18:32,635] Trial 72 finished with value: 0.23560304383979105 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 17:18:40,148] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:20:21,118] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:21:02,514] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:21:53,032] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 17:23:06,218] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:23:38,609] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:24:56,346] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:25:28,684] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24681258486716454
Fold 2 IBS: 0.23134147719336226
Fold 3 IBS: 0.22854574454813859
Fold 4 IBS: 0.24128654304100933
Fold 5 IBS: 0.22888390765584835
[I 2024-04-17 17:26:19,546] Trial 81 finished with value: 0.23537405146110463 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:27:13,366] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:28:17,416] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203682949502244
Fold 3 IBS: 0.22898144124325057
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.229392082451369
[I 2024-04-17 17:28:49,541] Trial 84 finished with value: 0.23592644501910062 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.23482614463440274.
Fold 1 IBS: 0.24542149296597732
Fold 2 IBS: 0.22770211124461134
Fold 3 IBS: 0.22691486820362494
Fold 4 IBS: 0.23917713799273424
Fold 5 IBS: 0.22748926827337662
[I 2024-04-17 17:30:04,920] Trial 85 finished with value: 0.23334097573606488 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:31:25,731] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8921917646046833, 'learning_rate': 0.03493887873396886, 'dropout_rate': 0.20248417164561996, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.02811592341251499, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:31:55,858] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9521381251132186, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:33:23,204] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8783477148356468, 'learning_rate': 0.019145642246983192, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.11068414611763369, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:34:35,382] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9225585795675643, 'learning_rate': 0.0028206049164217276, 'dropout_rate': 0.16604269499086277, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 1.572109186144046, 'min_weight_fraction_leaf': 0.27088299579805813, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.905787363075094, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:35:40,665] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.09273837444215938, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8657908240711146, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24614488503153836
Fold 2 IBS: 0.23016616133151105
Fold 3 IBS: 0.2277835711911129
Fold 4 IBS: 0.24067233443904054
Fold 5 IBS: 0.22826471766821568
[I 2024-04-17 17:36:41,453] Trial 91 finished with value: 0.23460633393228375 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.021129279003315533, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.9309517539709111, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:37:43,400] Trial 92 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.02241134247478034, 'dropout_rate': 0.2583752131981347, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.4943670196310161, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 9.135609514383116e-07, 'validation_fraction': 0.929257109542098, 'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-17 17:38:37,428] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9562310140378132, 'learning_rate': 0.017182645082053097, 'dropout_rate': 0.30303355573944185, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.20362952808416507, 'min_weight_fraction_leaf': 0.06487551572722715, 'max_features': 'auto', 'min_impurity_decrease': 2.2745718823187047e-07, 'validation_fraction': 0.979813726530939, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:39:28,310] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9803432784281702, 'learning_rate': 0.011448180194224972, 'dropout_rate': 0.28058975756978766, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6843293477116347, 'min_weight_fraction_leaf': 0.1982598024964269, 'max_features': None, 'min_impurity_decrease': 5.981184732872339e-07, 'validation_fraction': 0.9454695844953723, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:40:34,107] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9455952167309377, 'learning_rate': 0.03849480232107322, 'dropout_rate': 0.3201948574529592, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.9601205383555245, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 3.7935126700511503e-07, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24556839577871034
Fold 2 IBS: 0.2284656550519615
Fold 3 IBS: 0.22857721621066904
Fold 4 IBS: 0.2400598315906517
Fold 5 IBS: 0.2279355389988583
[I 2024-04-17 17:41:27,887] Trial 96 finished with value: 0.23412132752617015 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.02041047784766359, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.2253662010001949, 'max_features': 'auto', 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.32386831053055254, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:42:23,098] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.026783144722107532, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 0.43549519886063537, 'min_weight_fraction_leaf': 0.22023393103598612, 'max_features': 'auto', 'min_impurity_decrease': 1.3568805622065066e-07, 'validation_fraction': 0.31617010634192105, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:43:03,908] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7743094980751969, 'learning_rate': 0.020410071578111352, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 1.1387001784940558, 'min_weight_fraction_leaf': 0.22558745505753475, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.1600852440936258, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23334097573606488.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-17 17:44:14,418] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.25443633448028735, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.2223066295281712, 'min_weight_fraction_leaf': 0.25005462596245476, 'max_features': 'auto', 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.4189919199463679, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.23334097573606488.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23334097573606488], datetime_start=datetime.datetime(2024, 4, 17, 17, 28, 49, 550503), datetime_complete=datetime.datetime(2024, 4, 17, 17, 30, 4, 919538), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23334097573606488

In [65]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.749
train_ibs:  0.233

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008821356078039954,
                                 criterion='squared_error',
                                 dropout_rate=0.5604101432191428,
                                 learning_rate=0.05159117661647313, max_depth=4,
                                 max_features=0.1, max_leaf_nodes=18,
                                 min_impurity_decrease=9.803482393630746e-05,
                                 min_samples_leaf=7, min_samples_split=8,
                                 min_weight_fraction_leaf=0.26023745967507866,
                                 n_estimators=350, random_state=123,
                                 subsample=0.9197287558651637,
                                 validation_fraction=0.8247616419720114)

C-index score: 0.565

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.229

In [69]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [70]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [71]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 17:44:32,485] A new study created in memory with name: no-name-ffedf783-507a-46e2-8ebf-82753a09e751

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:44:33,564] Trial 0 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:44:42,428] Trial 1 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 17:44:44,100] Trial 2 finished with value: 0.6248486830300205 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6248486830300205.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:44:46,355] Trial 3 finished with value: 0.6338486920671272 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6338486920671272.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:44:49,531] Trial 4 finished with value: 0.6352789970586328 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:44:53,277] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 17:44:54,884] Trial 6 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 17:44:55,240] Trial 7 finished with value: 0.6319865279687434 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:44:57,230] Trial 8 finished with value: 0.624787126680312 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:45:02,853] Trial 9 finished with value: 0.623990313931308 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6352789970586328.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:45:06,788] Trial 10 finished with value: 0.6421489976479674 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6421489976479674.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:45:11,219] Trial 11 finished with value: 0.6510437721569392 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6510437721569392.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:45:15,529] Trial 12 finished with value: 0.6550388490816335 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:45:20,750] Trial 13 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:45:24,753] Trial 14 finished with value: 0.6485632936180569 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:45:28,767] Trial 15 finished with value: 0.6391071725529104 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:45:35,778] Trial 16 finished with value: 0.6453217915412577 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:45:42,297] Trial 17 finished with value: 0.6360685045387116 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-17 17:45:45,289] Trial 18 finished with value: 0.6304983909725402 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.6550388490816335.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:45:46,337] Trial 19 finished with value: 0.64767587331303 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:45:53,955] Trial 20 finished with value: 0.6408386482750206 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:45:58,255] Trial 21 finished with value: 0.6485632936180569 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.7075879968118339, 'n_estimators': 348, 'learning_rate': 0.09588015704350664}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:46:02,113] Trial 22 finished with value: 0.6383787975794839 and parameters: {'subsample': 0.17037433318378448, 'dropout_rate': 0.764223918656215, 'n_estimators': 305, 'learning_rate': 0.09979249643444077}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:46:06,580] Trial 23 finished with value: 0.6383935351041692 and parameters: {'subsample': 0.1882001920901971, 'dropout_rate': 0.5767392416088596, 'n_estimators': 339, 'learning_rate': 0.09228487500058613}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:46:11,022] Trial 24 finished with value: 0.6510589335246807 and parameters: {'subsample': 0.10032123431548137, 'dropout_rate': 0.9684931648209879, 'n_estimators': 388, 'learning_rate': 0.0802723125714484}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-17 17:46:15,321] Trial 25 finished with value: 0.6248486830300205 and parameters: {'subsample': 0.4133596270549855, 'dropout_rate': 0.9814337999737701, 'n_estimators': 405, 'learning_rate': 0.07897720038644866}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 17:46:18,085] Trial 26 finished with value: 0.6328528965873688 and parameters: {'subsample': 0.29436693962013616, 'dropout_rate': 0.30720738642318285, 'n_estimators': 245, 'learning_rate': 0.06349383809213646}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 17:46:24,992] Trial 27 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.6087801618108066, 'n_estimators': 456, 'learning_rate': 0.06676860919367211}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:46:29,724] Trial 28 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.8192295755232234, 'n_estimators': 384, 'learning_rate': 0.08078072275147408}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:46:34,105] Trial 29 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 322, 'learning_rate': 0.0892538312157202}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:46:37,723] Trial 30 finished with value: 0.63988236635136 and parameters: {'subsample': 0.21797436717278929, 'dropout_rate': 0.16903977002361698, 'n_estimators': 283, 'learning_rate': 0.044040119088987244}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:46:41,814] Trial 31 finished with value: 0.6446120054243624 and parameters: {'subsample': 0.12927234629827838, 'dropout_rate': 0.9690972067181969, 'n_estimators': 383, 'learning_rate': 0.09233052029041879}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 17:46:47,447] Trial 32 finished with value: 0.6503490204209503 and parameters: {'subsample': 0.10197013154249483, 'dropout_rate': 0.9006234235846082, 'n_estimators': 449, 'learning_rate': 0.09214772080187031}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:46:52,973] Trial 33 finished with value: 0.639092435028225 and parameters: {'subsample': 0.16421336528135802, 'dropout_rate': 0.9268713272970187, 'n_estimators': 453, 'learning_rate': 0.07794503671868204}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:46:59,411] Trial 34 finished with value: 0.6359562780321342 and parameters: {'subsample': 0.23087858755854718, 'dropout_rate': 0.8311198269799329, 'n_estimators': 477, 'learning_rate': 0.07104054321866782}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 17:47:01,314] Trial 35 finished with value: 0.6289120707434576 and parameters: {'subsample': 0.29440822025230656, 'dropout_rate': 0.9999753567840282, 'n_estimators': 232, 'learning_rate': 0.09340164470114515}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:47:09,366] Trial 36 finished with value: 0.6430910928768337 and parameters: {'subsample': 0.1472825644233607, 'dropout_rate': 0.45922216511134195, 'n_estimators': 490, 'learning_rate': 0.07364671948774787}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263

Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 17:47:15,774] Trial 37 finished with value: 0.6358947216824257 and parameters: {'subsample': 0.22877221290518623, 'dropout_rate': 0.5102437401048863, 'n_estimators': 437, 'learning_rate': 0.059207327336158105}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 17:47:20,104] Trial 38 finished with value: 0.631313522170144 and parameters: {'subsample': 0.3297325755614151, 'dropout_rate': 0.8867789132968811, 'n_estimators': 392, 'learning_rate': 0.08480908032505553}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:47:21,467] Trial 39 finished with value: 0.6392050853778585 and parameters: {'subsample': 0.1910828860959901, 'dropout_rate': 0.29848665859072016, 'n_estimators': 145, 'learning_rate': 0.06892741183938003}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 17:47:21,831] Trial 40 finished with value: 0.624171402056519 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.7942402623613096, 'n_estimators': 44, 'learning_rate': 0.09083529332655457}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:47:25,790] Trial 41 finished with value: 0.6510589335246807 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.9432108264211424, 'n_estimators': 354, 'learning_rate': 0.0993939723603888}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:47:28,472] Trial 42 finished with value: 0.6509683259686577 and parameters: {'subsample': 0.10319905773816981, 'dropout_rate': 0.9428165272301137, 'n_estimators': 279, 'learning_rate': 0.09477321051183016}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:47:31,992] Trial 43 finished with value: 0.6439931237197112 and parameters: {'subsample': 0.15781638407044, 'dropout_rate': 0.9339744762032774, 'n_estimators': 331, 'learning_rate': 0.09546413769326056}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6652360515021459
[I 2024-04-17 17:47:34,671] Trial 44 finished with value: 0.6312224907710647 and parameters: {'subsample': 0.24640386966932498, 'dropout_rate': 0.8562163290458892, 'n_estimators': 276, 'learning_rate': 0.08347032770705055}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 17:47:37,294] Trial 45 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.9563394286277414, 'n_estimators': 292, 'learning_rate': 0.02274904980797578}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:47:42,795] Trial 46 finished with value: 0.6470455381513865 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.14648424644002478, 'n_estimators': 359, 'learning_rate': 0.09948189805667967}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:47:44,705] Trial 47 finished with value: 0.6367167343058984 and parameters: {'subsample': 0.19598228689905128, 'dropout_rate': 0.8722233582145169, 'n_estimators': 215, 'learning_rate': 0.08796121694988046}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:47:46,290] Trial 48 finished with value: 0.6224546638590941 and parameters: {'subsample': 0.5990656023377149, 'dropout_rate': 0.6604314111556595, 'n_estimators': 184, 'learning_rate': 0.07586281947120743}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:47:49,722] Trial 49 finished with value: 0.6407259979253871 and parameters: {'subsample': 0.13769168070012916, 'dropout_rate': 0.20960059631780176, 'n_estimators': 272, 'learning_rate': 0.00524351186486742}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:47:53,734] Trial 50 finished with value: 0.6329360718876316 and parameters: {'subsample': 0.3066139185824137, 'dropout_rate': 0.37515029244711084, 'n_estimators': 319, 'learning_rate': 0.09624719899312528}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:47:57,948] Trial 51 finished with value: 0.6494759137975527 and parameters: {'subsample': 0.10365964858846104, 'dropout_rate': 0.9008789240484298, 'n_estimators': 363, 'learning_rate': 0.09023478185166049}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:48:02,707] Trial 52 finished with value: 0.6446735617740709 and parameters: {'subsample': 0.13637380813559394, 'dropout_rate': 0.9424845632006149, 'n_estimators': 408, 'learning_rate': 0.08484015817171084}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 17:48:02,938] Trial 53 finished with value: 0.6426529196082391 and parameters: {'subsample': 0.17965648718891908, 'dropout_rate': 0.9077848773686094, 'n_estimators': 9, 'learning_rate': 0.09477772623342627}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:48:08,233] Trial 54 finished with value: 0.647903907250099 and parameters: {'subsample': 0.11909044813837467, 'dropout_rate': 0.1199791728353166, 'n_estimators': 338, 'learning_rate': 0.0814788871905445}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:48:13,504] Trial 55 finished with value: 0.6359778969826885 and parameters: {'subsample': 0.20092103281432938, 'dropout_rate': 0.996389441333784, 'n_estimators': 442, 'learning_rate': 0.08980501569442459}. Best is trial 12 with value: 0.6550388490816335.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:48:16,894] Trial 56 finished with value: 0.6424206933292014 and parameters: {'subsample': 0.16065976519930922, 'dropout_rate': 0.7864890587902392, 'n_estimators': 310, 'learning_rate': 0.09808267212418638}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:48:21,392] Trial 57 finished with value: 0.6502511075960021 and parameters: {'subsample': 0.10148833491313695, 'dropout_rate': 0.8311613166012197, 'n_estimators': 369, 'learning_rate': 0.08690625713960494}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:48:24,263] Trial 58 finished with value: 0.6408386482750206 and parameters: {'subsample': 0.26289040708152583, 'dropout_rate': 0.19660164188953635, 'n_estimators': 253, 'learning_rate': 0.0934182493670741}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 17:48:30,862] Trial 59 finished with value: 0.6511637277754978 and parameters: {'subsample': 0.10183265607410649, 'dropout_rate': 0.2645251087109975, 'n_estimators': 400, 'learning_rate': 0.0998582191898498}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:48:35,799] Trial 60 finished with value: 0.6422911230469717 and parameters: {'subsample': 0.22377215973477588, 'dropout_rate': 0.27069780521427733, 'n_estimators': 349, 'learning_rate': 0.0966828865127487}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:48:42,431] Trial 61 finished with value: 0.6478207319498361 and parameters: {'subsample': 0.14403304231386152, 'dropout_rate': 0.12666752739579462, 'n_estimators': 396, 'learning_rate': 0.09980158481816102}. Best is trial 12 with value: 0.6550388490816335.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:48:49,276] Trial 62 finished with value: 0.6566645558799793 and parameters: {'subsample': 0.10637687141780292, 'dropout_rate': 0.10144570768327635, 'n_estimators': 428, 'learning_rate': 0.09251439643756458}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:48:52,703] Trial 63 finished with value: 0.6469334386316441 and parameters: {'subsample': 0.16797626930456266, 'dropout_rate': 0.14213818814606993, 'n_estimators': 299, 'learning_rate': 0.08920687718823156}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:48:59,396] Trial 64 finished with value: 0.6437861414690438 and parameters: {'subsample': 0.19301059862707368, 'dropout_rate': 0.10341951285125658, 'n_estimators': 421, 'learning_rate': 0.08142269138938249}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:49:04,502] Trial 65 finished with value: 0.6510479203450061 and parameters: {'subsample': 0.13213577813414473, 'dropout_rate': 0.17026153335936856, 'n_estimators': 378, 'learning_rate': 0.09421203774761983}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:49:09,592] Trial 66 finished with value: 0.6510115638697664 and parameters: {'subsample': 0.14167813930230821, 'dropout_rate': 0.172051935071797, 'n_estimators': 375, 'learning_rate': 0.08743811059718656}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:49:15,036] Trial 67 finished with value: 0.641515929248522 and parameters: {'subsample': 0.24491837796398347, 'dropout_rate': 0.21881494099078103, 'n_estimators': 392, 'learning_rate': 0.09262939397739599}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:49:21,255] Trial 68 finished with value: 0.6399508041269375 and parameters: {'subsample': 0.17246440371575278, 'dropout_rate': 0.26991471653248456, 'n_estimators': 431, 'learning_rate': 0.03557646010123462}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:49:27,949] Trial 69 finished with value: 0.6445583051734702 and parameters: {'subsample': 0.20854320822899344, 'dropout_rate': 0.1569119731806641, 'n_estimators': 413, 'learning_rate': 0.0969743287796588}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:49:32,334] Trial 70 finished with value: 0.6518557462736847 and parameters: {'subsample': 0.12915704372976497, 'dropout_rate': 0.1806794570956778, 'n_estimators': 331, 'learning_rate': 0.05474597229332904}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:49:36,736] Trial 71 finished with value: 0.6501536186141101 and parameters: {'subsample': 0.13112813702193857, 'dropout_rate': 0.1990833126785695, 'n_estimators': 329, 'learning_rate': 0.05056792253825018}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:49:42,006] Trial 72 finished with value: 0.6502078696948934 and parameters: {'subsample': 0.11925637043172176, 'dropout_rate': 0.17839260728566292, 'n_estimators': 345, 'learning_rate': 0.04462549298051328}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:49:47,925] Trial 73 finished with value: 0.6468501363445462 and parameters: {'subsample': 0.1525994189907754, 'dropout_rate': 0.131132627415633, 'n_estimators': 372, 'learning_rate': 0.0639239065250396}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6920152091254753

Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 17:49:55,974] Trial 74 finished with value: 0.6519931726547308 and parameters: {'subsample': 0.10099983845623818, 'dropout_rate': 0.2546871227739602, 'n_estimators': 460, 'learning_rate': 0.02502249046663426}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:50:04,172] Trial 75 finished with value: 0.6267465093526564 and parameters: {'subsample': 0.6882223870109341, 'dropout_rate': 0.24457364497654346, 'n_estimators': 478, 'learning_rate': 0.05728703006070357}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:50:12,213] Trial 76 finished with value: 0.623990313931308 and parameters: {'subsample': 0.5158288238320929, 'dropout_rate': 0.31120678009933567, 'n_estimators': 466, 'learning_rate': 0.022152482718302495}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 17:50:19,681] Trial 77 finished with value: 0.6511421088249435 and parameters: {'subsample': 0.10010954670890948, 'dropout_rate': 0.3447061559073807, 'n_estimators': 462, 'learning_rate': 0.02900320800283515}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:50:27,822] Trial 78 finished with value: 0.6391903478531732 and parameters: {'subsample': 0.18267890611891185, 'dropout_rate': 0.34612811357105955, 'n_estimators': 490, 'learning_rate': 0.013546180465617197}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:50:36,054] Trial 79 finished with value: 0.6438804733700776 and parameters: {'subsample': 0.15952425849167606, 'dropout_rate': 0.23191373364441525, 'n_estimators': 462, 'learning_rate': 0.027942007151173433}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:50:42,986] Trial 80 finished with value: 0.6502837397262311 and parameters: {'subsample': 0.10241628263382933, 'dropout_rate': 0.4208771039898602, 'n_estimators': 432, 'learning_rate': 0.03421946338249707}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:50:48,932] Trial 81 finished with value: 0.6462923871465475 and parameters: {'subsample': 0.1278088723503249, 'dropout_rate': 0.28935219728891354, 'n_estimators': 402, 'learning_rate': 0.0167590134541572}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:50:55,127] Trial 82 finished with value: 0.6518014951929014 and parameters: {'subsample': 0.12215062772924273, 'dropout_rate': 0.15926932419922477, 'n_estimators': 385, 'learning_rate': 0.03695959965829722}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:51:02,660] Trial 83 finished with value: 0.6510263013944517 and parameters: {'subsample': 0.10212226204834485, 'dropout_rate': 0.1937463729660434, 'n_estimators': 442, 'learning_rate': 0.03772422340557778}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:51:07,021] Trial 84 finished with value: 0.6430441470649757 and parameters: {'subsample': 0.15312875726031014, 'dropout_rate': 0.3233647046882656, 'n_estimators': 356, 'learning_rate': 0.027204108732831453}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:51:14,662] Trial 85 finished with value: 0.6375715224806965 and parameters: {'subsample': 0.21363945247590896, 'dropout_rate': 0.26205027511777046, 'n_estimators': 496, 'learning_rate': 0.039905813076466574}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 17:51:21,211] Trial 86 finished with value: 0.6276048784513688 and parameters: {'subsample': 0.992873343787547, 'dropout_rate': 0.10104917813239328, 'n_estimators': 421, 'learning_rate': 0.04734840298664302}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-17 17:51:26,929] Trial 87 finished with value: 0.623990313931308 and parameters: {'subsample': 0.45799346480592396, 'dropout_rate': 0.36825082093259265, 'n_estimators': 386, 'learning_rate': 0.0278444446597096}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:51:33,556] Trial 88 finished with value: 0.6510046824438974 and parameters: {'subsample': 0.11987538574936739, 'dropout_rate': 0.15370382207122774, 'n_estimators': 405, 'learning_rate': 0.031192478999699305}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:51:43,065] Trial 89 finished with value: 0.6413885413742031 and parameters: {'subsample': 0.17356457015475854, 'dropout_rate': 0.21637616275395405, 'n_estimators': 481, 'learning_rate': 0.025056796383218}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:51:49,563] Trial 90 finished with value: 0.6470818946266264 and parameters: {'subsample': 0.11978578332598643, 'dropout_rate': 0.5407927170707892, 'n_estimators': 452, 'learning_rate': 0.01949229524639421}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:51:54,773] Trial 91 finished with value: 0.6463214383528619 and parameters: {'subsample': 0.14420107915872915, 'dropout_rate': 0.16799755019024815, 'n_estimators': 376, 'learning_rate': 0.03293311950197661}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:51:59,987] Trial 92 finished with value: 0.6518014951929014 and parameters: {'subsample': 0.12063481717000281, 'dropout_rate': 0.13699294020867783, 'n_estimators': 383, 'learning_rate': 0.041976738365940285}. Best is trial 62 with value: 0.6566645558799793.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:52:04,647] Trial 93 finished with value: 0.6431347546209988 and parameters: {'subsample': 0.19528857956165535, 'dropout_rate': 0.12892147108310306, 'n_estimators': 360, 'learning_rate': 0.040907943609684756}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-17 17:52:10,980] Trial 94 finished with value: 0.6493568058651061 and parameters: {'subsample': 0.11969733939154474, 'dropout_rate': 0.18619257295551966, 'n_estimators': 428, 'learning_rate': 0.053757449018078954}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6952789699570815
[I 2024-04-17 17:52:16,133] Trial 95 finished with value: 0.6536483545024472 and parameters: {'subsample': 0.10068705156084184, 'dropout_rate': 0.2401505585600089, 'n_estimators': 340, 'learning_rate': 0.029898003284277906}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6909871244635193
[I 2024-04-17 17:52:20,080] Trial 96 finished with value: 0.6447972417376404 and parameters: {'subsample': 0.1542489196934704, 'dropout_rate': 0.2890241158062875, 'n_estimators': 317, 'learning_rate': 0.04734794828761702}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 17:52:24,223] Trial 97 finished with value: 0.6360321480634717 and parameters: {'subsample': 0.24114651636813722, 'dropout_rate': 0.23076496556598028, 'n_estimators': 335, 'learning_rate': 0.030367084935656083}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:52:29,795] Trial 98 finished with value: 0.6415843670240996 and parameters: {'subsample': 0.18032280797681166, 'dropout_rate': 0.250460274967092, 'n_estimators': 398, 'learning_rate': 0.036610470552491656}. Best is trial 62 with value: 0.6566645558799793.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753

[I 2024-04-17 17:52:37,541] A new study created in memory with name: no-name-95794c0d-3f87-4fa6-93df-418c971b3875

Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 17:52:37,529] Trial 99 finished with value: 0.6485200557169482 and parameters: {'subsample': 0.13663139807943914, 'dropout_rate': 0.12027435935479405, 'n_estimators': 468, 'learning_rate': 0.04227321748008733}. Best is trial 62 with value: 0.6566645558799793.


* Best trial for C-index:
 FrozenTrial(number=62, state=TrialState.COMPLETE, values=[0.6566645558799793], datetime_start=datetime.datetime(2024, 4, 17, 17, 48, 42, 443784), datetime_complete=datetime.datetime(2024, 4, 17, 17, 48, 49, 275146), params={'subsample': 0.10637687141780292, 'dropout_rate': 0.10144570768327635, 'n_estimators': 428, 'learning_rate': 0.09251439643756458}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=62, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10637687141780292, 'dropout_rate': 0.10144570768327635, 'n_estimators': 428, 'learning_rate': 0.09251439643756458}


* Best Score for C-index:
 0.6566645558799793

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.32184685283009035
Fold 2 IBS: 0.24269519626988276
Fold 3 IBS: 0.32845286241320015
Fold 4 IBS: 0.28361609336040605
Fold 5 IBS: 0.2729305473144034
[I 2024-04-17 17:52:38,412] Trial 0 finished with value: 0.2899083104375965 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.42279422613772155
Fold 2 IBS: 0.3901128382737591
Fold 3 IBS: 0.39247472286878254
Fold 4 IBS: 0.36956665696576196
Fold 5 IBS: 0.3399595615106552
[I 2024-04-17 17:52:45,520] Trial 1 finished with value: 0.3829816011513361 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38477559331402056
Fold 2 IBS: 0.3002072982420411
Fold 3 IBS: 0.37939668767639545
Fold 4 IBS: 0.3096779826388825
Fold 5 IBS: 0.3252308860734576
[I 2024-04-17 17:52:46,941] Trial 2 finished with value: 0.33985768958895946 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38791718483853127
Fold 2 IBS: 0.28308398609663094
Fold 3 IBS: 0.38075337593630443
Fold 4 IBS: 0.30896380743221213
Fold 5 IBS: 0.33290864228938033
[I 2024-04-17 17:52:49,001] Trial 3 finished with value: 0.3387253993186118 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38792738170860425
Fold 2 IBS: 0.2795795393275598
Fold 3 IBS: 0.3843436493133732
Fold 4 IBS: 0.30670925738900373
Fold 5 IBS: 0.3393049043553044
[I 2024-04-17 17:52:52,540] Trial 4 finished with value: 0.3395729464187691 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.41105192261386453
Fold 2 IBS: 0.3777174719916462
Fold 3 IBS: 0.3915300176353505
Fold 4 IBS: 0.3447295660931382
Fold 5 IBS: 0.32992002164058554
[I 2024-04-17 17:52:56,769] Trial 5 finished with value: 0.370989799994917 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.2950866836605978
Fold 2 IBS: 0.21617356864727175
Fold 3 IBS: 0.2960476577766528
Fold 4 IBS: 0.26116838532173825
Fold 5 IBS: 0.2492059247499634
[I 2024-04-17 17:52:58,797] Trial 6 finished with value: 0.2635364440312448 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2635364440312448.
Fold 1 IBS: 0.2525596717266013
Fold 2 IBS: 0.2009504851975363
Fold 3 IBS: 0.2554759579529817
Fold 4 IBS: 0.22423261256383803
Fold 5 IBS: 0.2116650686406854
[I 2024-04-17 17:52:59,233] Trial 7 finished with value: 0.22897675921632854 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.32773085091505505
Fold 2 IBS: 0.24764667449835662
Fold 3 IBS: 0.3381279691027075
Fold 4 IBS: 0.28727873359875167
Fold 5 IBS: 0.2819856805230031
[I 2024-04-17 17:53:01,391] Trial 8 finished with value: 0.2965539817275748 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.4128629984024713
Fold 2 IBS: 0.3805312612875153
Fold 3 IBS: 0.39180424534594577
Fold 4 IBS: 0.3483594650353357
Fold 5 IBS: 0.3350263678028636
[I 2024-04-17 17:53:06,833] Trial 9 finished with value: 0.3737168675748263 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24690378026135393
Fold 2 IBS: 0.230918196199329
Fold 3 IBS: 0.2288651535714008
Fold 4 IBS: 0.24118860634197958
Fold 5 IBS: 0.22809859267819335
[I 2024-04-17 17:53:07,128] Trial 10 finished with value: 0.23519486581045132 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24596520377467238
Fold 2 IBS: 0.22745516260233242
Fold 3 IBS: 0.22872408268029404
Fold 4 IBS: 0.23875682318201075
Fold 5 IBS: 0.22421110618785597
[I 2024-04-17 17:53:07,310] Trial 11 finished with value: 0.2330224756854331 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.2728756335912118
Fold 2 IBS: 0.20866318918988855
Fold 3 IBS: 0.3057008256941006
Fold 4 IBS: 0.24757598083644636
Fold 5 IBS: 0.24442168144336573
[I 2024-04-17 17:53:07,753] Trial 12 finished with value: 0.2558474621510026 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24540145164058172
Fold 2 IBS: 0.22486461618174694
Fold 3 IBS: 0.2288799372028231
Fold 4 IBS: 0.23700499011587697
Fold 5 IBS: 0.22141183261877637
[I 2024-04-17 17:53:07,947] Trial 13 finished with value: 0.23151256555196104 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.2801288012575852
Fold 2 IBS: 0.20642643701643856
Fold 3 IBS: 0.2855821246683042
Fold 4 IBS: 0.2448269379427668
Fold 5 IBS: 0.23496945372244868
[I 2024-04-17 17:53:08,729] Trial 14 finished with value: 0.2503867509215087 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.34250383730825085
Fold 2 IBS: 0.2562261533432662
Fold 3 IBS: 0.35681785243304703
Fold 4 IBS: 0.2914232791743898
Fold 5 IBS: 0.29999553893473496
[I 2024-04-17 17:53:09,435] Trial 15 finished with value: 0.3093933322387378 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.34999306438751004
Fold 2 IBS: 0.25296468831957614
Fold 3 IBS: 0.36810911249855677
Fold 4 IBS: 0.2847840246003582
Fold 5 IBS: 0.31897027021141183
[I 2024-04-17 17:53:12,026] Trial 16 finished with value: 0.31496423200348256 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24607714741491096
Fold 2 IBS: 0.21115546325606438
Fold 3 IBS: 0.23474191594216773
Fold 4 IBS: 0.2296381561690892
Fold 5 IBS: 0.21122928902161456
[I 2024-04-17 17:53:12,479] Trial 17 finished with value: 0.2265683943607694 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2883901804573134
Fold 2 IBS: 0.2112037980068735
Fold 3 IBS: 0.28770446755792806
Fold 4 IBS: 0.2544520687837577
Fold 5 IBS: 0.2431612806129336
[I 2024-04-17 17:53:16,087] Trial 18 finished with value: 0.2569823590837612 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.27019935319228533
Fold 2 IBS: 0.20101355307479882

Fold 3 IBS: 0.27495840642227154
Fold 4 IBS: 0.2403770465027076
Fold 5 IBS: 0.22389919673997055
[I 2024-04-17 17:53:17,052] Trial 19 finished with value: 0.24208951118640676 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24532728078212304
Fold 2 IBS: 0.21338053568843193
Fold 3 IBS: 0.23280583204014674
Fold 4 IBS: 0.23050963160208696
Fold 5 IBS: 0.21229213294998353
[I 2024-04-17 17:53:17,524] Trial 20 finished with value: 0.22686308261255445 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480948267779246
Fold 2 IBS: 0.217894217650721
Fold 3 IBS: 0.23043919128917217
Fold 4 IBS: 0.23275995527788665
Fold 5 IBS: 0.215372968667489
[I 2024-04-17 17:53:17,980] Trial 21 finished with value: 0.22825516311261226 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24643766317823718
Fold 2 IBS: 0.22924023219100237
Fold 3 IBS: 0.2287550024184287
Fold 4 IBS: 0.2400059006469264
Fold 5 IBS: 0.2262805735657194
[I 2024-04-17 17:53:18,516] Trial 22 finished with value: 0.23414387440006285 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.257478169662288
Fold 2 IBS: 0.20248903467735407
Fold 3 IBS: 0.252469752257427
Fold 4 IBS: 0.23159280968783177
Fold 5 IBS: 0.2169495351817077
[I 2024-04-17 17:53:19,713] Trial 23 finished with value: 0.2321958602933217 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24591385980787991
Fold 2 IBS: 0.21157801995971165
Fold 3 IBS: 0.23448495664364996
Fold 4 IBS: 0.229737329537672
Fold 5 IBS: 0.2112912785040094
[I 2024-04-17 17:53:20,155] Trial 24 finished with value: 0.22660108889058458 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2756443151410581
Fold 2 IBS: 0.20473874541146792
Fold 3 IBS: 0.27375023358490214
Fold 4 IBS: 0.2440459127498442
Fold 5 IBS: 0.23246982801186947
[I 2024-04-17 17:53:21,211] Trial 25 finished with value: 0.2461298069798284 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.32538815518873926
Fold 2 IBS: 0.2468744663909679
Fold 3 IBS: 0.3332171412462654
Fold 4 IBS: 0.28581063346445296
Fold 5 IBS: 0.2781065825703804
[I 2024-04-17 17:53:23,189] Trial 26 finished with value: 0.29387939577216116 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24492083546093882
Fold 2 IBS: 0.21628333393840363
Fold 3 IBS: 0.23138494832945591
Fold 4 IBS: 0.23162572469168902
Fold 5 IBS: 0.21394160498647347
[I 2024-04-17 17:53:23,572] Trial 27 finished with value: 0.2276312894813922 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24503999552218353
Fold 2 IBS: 0.21507419381927734
Fold 3 IBS: 0.23200152410434108
Fold 4 IBS: 0.23109618679052704
Fold 5 IBS: 0.21308573107611234
[I 2024-04-17 17:53:24,283] Trial 28 finished with value: 0.22725952626248827 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3030591065047406
Fold 2 IBS: 0.22336679794652556
Fold 3 IBS: 0.3044396799522218
Fold 4 IBS: 0.2678287080975696
Fold 5 IBS: 0.25695858296703405
[I 2024-04-17 17:53:25,142] Trial 29 finished with value: 0.2711305750936183 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.30057401042692355
Fold 2 IBS: 0.22109327570196485
Fold 3 IBS: 0.30174720098020524
Fold 4 IBS: 0.2651400266811706
Fold 5 IBS: 0.2537066735825353
[I 2024-04-17 17:53:26,525] Trial 30 finished with value: 0.26845223747455993 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24486090508062983
Fold 2 IBS: 0.21682633491745948
Fold 3 IBS: 0.23109486987541575
Fold 4 IBS: 0.23197486961623204
Fold 5 IBS: 0.21430589760825255
[I 2024-04-17 17:53:27,134] Trial 31 finished with value: 0.22781257541959793 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480604491948196
Fold 2 IBS: 0.21843195389759032
Fold 3 IBS: 0.23024293091022538
Fold 4 IBS: 0.23321504110381971
Fold 5 IBS: 0.21568765554273314
[I 2024-04-17 17:53:27,546] Trial 32 finished with value: 0.2284767252747701 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24434472696223403
Fold 2 IBS: 0.22006483265789914
Fold 3 IBS: 0.23001501374819164
Fold 4 IBS: 0.23353575529737952
Fold 5 IBS: 0.21714562015932423
[I 2024-04-17 17:53:28,232] Trial 33 finished with value: 0.2290211897650057 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25788116008451006
Fold 2 IBS: 0.20226079778720082
Fold 3 IBS: 0.2544783586806218
Fold 4 IBS: 0.23143342088904706
Fold 5 IBS: 0.21567691855898308
[I 2024-04-17 17:53:29,520] Trial 34 finished with value: 0.23234613120007258 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24665787355022445
Fold 2 IBS: 0.23001468040084486
Fold 3 IBS: 0.228802523121071
Fold 4 IBS: 0.24061435934394168
Fold 5 IBS: 0.2271257607053576
[I 2024-04-17 17:53:29,829] Trial 35 finished with value: 0.2346430394242879 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.36295049794153883
Fold 2 IBS: 0.27664373471149467
Fold 3 IBS: 0.3675445917607911
Fold 4 IBS: 0.3032504418743303
Fold 5 IBS: 0.311762833506537
[I 2024-04-17 17:53:37,034] Trial 36 finished with value: 0.3244304199589384 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3956248057488727
Fold 2 IBS: 0.3239854573821247
Fold 3 IBS: 0.38499901982444784
Fold 4 IBS: 0.31514930414846015
Fold 5 IBS: 0.3335159079818787
[I 2024-04-17 17:53:39,554] Trial 37 finished with value: 0.35065489901715685 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25969526762239703
Fold 2 IBS: 0.20212138827340803
Fold 3 IBS: 0.25611019690719544

Fold 4 IBS: 0.23376225132374828
Fold 5 IBS: 0.21475575962300342
[I 2024-04-17 17:53:41,345] Trial 38 finished with value: 0.23328897274995045 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.29108106719697524
Fold 2 IBS: 0.21415810554809628
Fold 3 IBS: 0.2917820507930866
Fold 4 IBS: 0.2588982634047282
Fold 5 IBS: 0.24407574900323586
[I 2024-04-17 17:53:41,891] Trial 39 finished with value: 0.25999904718922445 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2925659515921918
Fold 2 IBS: 0.2140746731129848
Fold 3 IBS: 0.2919432513336724
Fold 4 IBS: 0.257477121073266
Fold 5 IBS: 0.24657769529804316
[I 2024-04-17 17:53:42,742] Trial 40 finished with value: 0.2605277384820316 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24534003818367572
Fold 2 IBS: 0.21351313222790674
Fold 3 IBS: 0.23284352524242438
Fold 4 IBS: 0.2304630885922339
Fold 5 IBS: 0.21224567728236968
[I 2024-04-17 17:53:43,186] Trial 41 finished with value: 0.22688109230572212 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485006409680624
Fold 2 IBS: 0.21706394797525833
Fold 3 IBS: 0.23093672935586954
Fold 4 IBS: 0.23224267333240983
Fold 5 IBS: 0.21443505260308193
[I 2024-04-17 17:53:43,549] Trial 42 finished with value: 0.22790569347268522 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2638458495823219
Fold 2 IBS: 0.2020440306627012
Fold 3 IBS: 0.2599892350953784
Fold 4 IBS: 0.2353149724721722
Fold 5 IBS: 0.2221900668187372
[I 2024-04-17 17:53:44,211] Trial 43 finished with value: 0.2366768309262622 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2455964708749073
Fold 2 IBS: 0.22570478266765567
Fold 3 IBS: 0.228795022876604
Fold 4 IBS: 0.23752979609395375
Fold 5 IBS: 0.22236478482517102
[I 2024-04-17 17:53:44,794] Trial 44 finished with value: 0.23199817146765836 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24519921983594833
Fold 2 IBS: 0.22330524452579645
Fold 3 IBS: 0.2290157433965299
Fold 4 IBS: 0.23588777848641265
Fold 5 IBS: 0.2204866110425217
[I 2024-04-17 17:53:45,139] Trial 45 finished with value: 0.2307789194574418 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.34065073189493716
Fold 2 IBS: 0.2597363049038525
Fold 3 IBS: 0.3496713953679775
Fold 4 IBS: 0.2946768758327706
Fold 5 IBS: 0.29269474527583145
[I 2024-04-17 17:53:46,473] Trial 46 finished with value: 0.30748601065507386 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25039205968447736
Fold 2 IBS: 0.19881662927592997
Fold 3 IBS: 0.2539048960518954
Fold 4 IBS: 0.22477789659354785
Fold 5 IBS: 0.21334860039787545
[I 2024-04-17 17:53:47,052] Trial 47 finished with value: 0.2282480164007452 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2556573719237732
Fold 2 IBS: 0.20234787848056301
Fold 3 IBS: 0.2522638016406119
Fold 4 IBS: 0.23093407281830788
Fold 5 IBS: 0.21250246234410652
[I 2024-04-17 17:53:48,994] Trial 48 finished with value: 0.23074111744147255 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24675070321456416
Fold 2 IBS: 0.23043515587015717
Fold 3 IBS: 0.2288281703390381
Fold 4 IBS: 0.2408551079349057
Fold 5 IBS: 0.22755526151412517
[I 2024-04-17 17:53:49,174] Trial 49 finished with value: 0.23488487977455805 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.26805889781388065
Fold 2 IBS: 0.20252886898813807
Fold 3 IBS: 0.26533134677822295
Fold 4 IBS: 0.23829437556390634
Fold 5 IBS: 0.22589258667890266
[I 2024-04-17 17:53:50,139] Trial 50 finished with value: 0.2400212151646101 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24512963190106926
Fold 2 IBS: 0.2147274537502438
Fold 3 IBS: 0.2321986628737604
Fold 4 IBS: 0.23091267007941935
Fold 5 IBS: 0.21292902132889352
[I 2024-04-17 17:53:50,564] Trial 51 finished with value: 0.22717948798667725 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24662205885932792
Fold 2 IBS: 0.22993687263943438
Fold 3 IBS: 0.22879053467216642
Fold 4 IBS: 0.24048347407202147
Fold 5 IBS: 0.22699896965015748
[I 2024-04-17 17:53:51,047] Trial 52 finished with value: 0.23456638197862154 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485579223129506
Fold 2 IBS: 0.21998745903015368
Fold 3 IBS: 0.22977573478865335
Fold 4 IBS: 0.23404920712862456
Fold 5 IBS: 0.21705606342896017
[I 2024-04-17 17:53:51,410] Trial 53 finished with value: 0.22914485132153736 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2531442464481051
Fold 2 IBS: 0.20414594462184135
Fold 3 IBS: 0.2459059794082717
Fold 4 IBS: 0.22963377950406882
Fold 5 IBS: 0.21079567993043571
[I 2024-04-17 17:53:51,682] Trial 54 finished with value: 0.22872512598254455 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2524170789262838
Fold 2 IBS: 0.20420643525007415
Fold 3 IBS: 0.24534527368601658
Fold 4 IBS: 0.2294272521646032
Fold 5 IBS: 0.21300726025333291
[I 2024-04-17 17:53:52,362] Trial 55 finished with value: 0.22888066005606209 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24626134547224643
Fold 2 IBS: 0.21072141911440245
Fold 3 IBS: 0.23515116577403225
Fold 4 IBS: 0.22942525598464827
Fold 5 IBS: 0.21111562686038168
[I 2024-04-17 17:53:52,721] Trial 56 finished with value: 0.22653496264114223 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.32236762054514384
Fold 2 IBS: 0.24369761993112318
Fold 3 IBS: 0.32961555540384646
Fold 4 IBS: 0.28411316345226234

Fold 5 IBS: 0.27450442032616973
[I 2024-04-17 17:53:54,927] Trial 57 finished with value: 0.29085967593170914 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2514876544143989
Fold 2 IBS: 0.20473165445913052
Fold 3 IBS: 0.2442786298594191
Fold 4 IBS: 0.2292932477615486
Fold 5 IBS: 0.2122783863810015
[I 2024-04-17 17:53:55,382] Trial 58 finished with value: 0.2284139145750997 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2450009034050451
Fold 2 IBS: 0.21574021216390366
Fold 3 IBS: 0.2316126494096215
Fold 4 IBS: 0.2313085066143514
Fold 5 IBS: 0.2135215585555951
[I 2024-04-17 17:53:55,633] Trial 59 finished with value: 0.22743676602970336 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.27643234236120234
Fold 2 IBS: 0.20531960631582807
Fold 3 IBS: 0.2756328535259464
Fold 4 IBS: 0.24566178547120296
Fold 5 IBS: 0.23379390635926353
[I 2024-04-17 17:53:56,371] Trial 60 finished with value: 0.24736809880668864 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24511487846402005
Fold 2 IBS: 0.2227836793360944
Fold 3 IBS: 0.22915537398733413
Fold 4 IBS: 0.2355788750800659
Fold 5 IBS: 0.21936511210219634
[I 2024-04-17 17:53:56,868] Trial 61 finished with value: 0.23039958379394215 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.25492402733786423
Fold 2 IBS: 0.2031585290599715
Fold 3 IBS: 0.24895077307909572
Fold 4 IBS: 0.2303647335144685
Fold 5 IBS: 0.21487736782477726
[I 2024-04-17 17:53:57,501] Trial 62 finished with value: 0.23045508616323543 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24531708021685963
Fold 2 IBS: 0.22395449249387253
Fold 3 IBS: 0.22892582490539293
Fold 4 IBS: 0.23652996695441353
Fold 5 IBS: 0.2211888183692411
[I 2024-04-17 17:53:57,812] Trial 63 finished with value: 0.23118323658795595 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24543346554687298
Fold 2 IBS: 0.21302518909492982
Fold 3 IBS: 0.23348544240148608
Fold 4 IBS: 0.22993870744839895
Fold 5 IBS: 0.21193762927195595
[I 2024-04-17 17:53:58,219] Trial 64 finished with value: 0.22676408675272874 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24427299434478603
Fold 2 IBS: 0.2145724066475789
Fold 3 IBS: 0.23244031403754764
Fold 4 IBS: 0.2308013778601708
Fold 5 IBS: 0.21301937769687632
[I 2024-04-17 17:53:58,630] Trial 65 finished with value: 0.22702129411739191 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24414268593072253
Fold 2 IBS: 0.21442849246434953
Fold 3 IBS: 0.23260330769031967
Fold 4 IBS: 0.23070773208679712
Fold 5 IBS: 0.212827602266059
[I 2024-04-17 17:53:59,087] Trial 66 finished with value: 0.2269419640876496 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.29808498998226407
Fold 2 IBS: 0.22021424313364715
Fold 3 IBS: 0.3008089717671045
Fold 4 IBS: 0.26320289852555373
Fold 5 IBS: 0.25043406288056935
[I 2024-04-17 17:54:01,567] Trial 67 finished with value: 0.2665490332578278 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.36891251562644484
Fold 2 IBS: 0.28320463913092336
Fold 3 IBS: 0.3735215508072975
Fold 4 IBS: 0.30452010490955944
Fold 5 IBS: 0.3196121754758854
[I 2024-04-17 17:54:06,930] Trial 68 finished with value: 0.32995419719002206 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24694744262426244
Fold 2 IBS: 0.23112662775390544
Fold 3 IBS: 0.22888040570607412
Fold 4 IBS: 0.24129039277709646
Fold 5 IBS: 0.2284229264424595
[I 2024-04-17 17:54:07,160] Trial 69 finished with value: 0.23533355906075962 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.3789820127073879
Fold 2 IBS: 0.2881919135260274
Fold 3 IBS: 0.37987359081709904
Fold 4 IBS: 0.30550298278527566
Fold 5 IBS: 0.3303526100527719
[I 2024-04-17 17:54:11,331] Trial 70 finished with value: 0.3365806219777124 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2442747298878039
Fold 2 IBS: 0.21394603308037777
Fold 3 IBS: 0.2329347454389621
Fold 4 IBS: 0.23037646611901139
Fold 5 IBS: 0.21249651991354515
[I 2024-04-17 17:54:11,754] Trial 71 finished with value: 0.22680569888794005 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24446665909481854
Fold 2 IBS: 0.2202286409877386
Fold 3 IBS: 0.2298979855224926
Fold 4 IBS: 0.23386125106403746
Fold 5 IBS: 0.21736824836572086
[I 2024-04-17 17:54:12,206] Trial 72 finished with value: 0.2291645570069616 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24809645932076727
Fold 2 IBS: 0.20746362379997257
Fold 3 IBS: 0.23887206962421953
Fold 4 IBS: 0.2284825651773238
Fold 5 IBS: 0.2100698715233792
[I 2024-04-17 17:54:12,866] Trial 73 finished with value: 0.22659691788913244 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2543888239593833
Fold 2 IBS: 0.20292319894393337
Fold 3 IBS: 0.24852527226160065
Fold 4 IBS: 0.22955225079581343
Fold 5 IBS: 0.21241475262132198
[I 2024-04-17 17:54:13,537] Trial 74 finished with value: 0.22956085971641055 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2586670573078814
Fold 2 IBS: 0.20043803485847264
Fold 3 IBS: 0.2585285364856659
Fold 4 IBS: 0.23185266301823715
Fold 5 IBS: 0.21512351643127495
[I 2024-04-17 17:54:14,144] Trial 75 finished with value: 0.23292196162030643 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24487192319121745
Fold 2 IBS: 0.21645877330178392
Fold 3 IBS: 0.23106107310931137
Fold 4 IBS: 0.2321278197949212
Fold 5 IBS: 0.21457551785343906
[I 2024-04-17 17:54:14,454] Trial 76 finished with value: 0.2278190214501346 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22653496264114223.

Fold 1 IBS: 0.24975605957417094
Fold 2 IBS: 0.20544669926019324
Fold 3 IBS: 0.24292589881032364
Fold 4 IBS: 0.2283240329592914
Fold 5 IBS: 0.21054396005104126
[I 2024-04-17 17:54:15,450] Trial 77 finished with value: 0.22739933013100408 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24684927097070503
Fold 2 IBS: 0.2094952280230178
Fold 3 IBS: 0.23652719105524916
Fold 4 IBS: 0.22913951054643386
Fold 5 IBS: 0.2106573202990221
[I 2024-04-17 17:54:15,923] Trial 78 finished with value: 0.2265337041788856 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24502409439696052
Fold 2 IBS: 0.22205787317352343
Fold 3 IBS: 0.22926533447627775
Fold 4 IBS: 0.2352795597651623
Fold 5 IBS: 0.2188730593846164
[I 2024-04-17 17:54:16,444] Trial 79 finished with value: 0.23009998423930805 and parameters: {'subsample': 0.5862245141488869, 'dropout_rate': 0.7413305472330791, 'n_estimators': 79, 'learning_rate': 0.00518700542803859}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.2548529205408104
Fold 2 IBS: 0.2029551856530423
Fold 3 IBS: 0.2494742616554397
Fold 4 IBS: 0.23041757963367823
Fold 5 IBS: 0.21265412243334256
[I 2024-04-17 17:54:17,190] Trial 80 finished with value: 0.23007081398326265 and parameters: {'subsample': 0.5412030995339159, 'dropout_rate': 0.7943244209025906, 'n_estimators': 120, 'learning_rate': 0.015049190001982352}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24503928639713976
Fold 2 IBS: 0.22210439837147225
Fold 3 IBS: 0.22923064761200726
Fold 4 IBS: 0.23532466695341075
Fold 5 IBS: 0.2188890235672119
[I 2024-04-17 17:54:17,561] Trial 81 finished with value: 0.23011760458024838 and parameters: {'subsample': 0.6124074983469379, 'dropout_rate': 0.6341528845468055, 'n_estimators': 48, 'learning_rate': 0.008581896342583242}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24566232614650538
Fold 2 IBS: 0.20763330396179233
Fold 3 IBS: 0.2399122667638913
Fold 4 IBS: 0.22729435575947432
Fold 5 IBS: 0.20971833255484604
[I 2024-04-17 17:54:18,057] Trial 82 finished with value: 0.22604411703730184 and parameters: {'subsample': 0.36882902998484507, 'dropout_rate': 0.9266770484936306, 'n_estimators': 72, 'learning_rate': 0.01836411354022466}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.24387668061602458
Fold 2 IBS: 0.21367297665454796
Fold 3 IBS: 0.2333362520374528
Fold 4 IBS: 0.22948421407755595
Fold 5 IBS: 0.21270096527180668
[I 2024-04-17 17:54:18,533] Trial 83 finished with value: 0.22661421773147755 and parameters: {'subsample': 0.3619635368676717, 'dropout_rate': 0.9281653685578871, 'n_estimators': 75, 'learning_rate': 0.01174447149382581}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.2481782165598782
Fold 2 IBS: 0.2032648830515002
Fold 3 IBS: 0.2505921898057478
Fold 4 IBS: 0.22803942510176736
Fold 5 IBS: 0.21128535620380667
[I 2024-04-17 17:54:19,137] Trial 84 finished with value: 0.22827201414454007 and parameters: {'subsample': 0.3276130954169086, 'dropout_rate': 0.9694546795228237, 'n_estimators': 84, 'learning_rate': 0.022169484737510906}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.2449916816071917
Fold 2 IBS: 0.21034889723149172
Fold 3 IBS: 0.23561656068011147
Fold 4 IBS: 0.2278223716435641
Fold 5 IBS: 0.21102078940314542
[I 2024-04-17 17:54:19,720] Trial 85 finished with value: 0.22596006011310088 and parameters: {'subsample': 0.363388210801912, 'dropout_rate': 0.8895677781947375, 'n_estimators': 93, 'learning_rate': 0.011252915568896725}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2507644683324895
Fold 2 IBS: 0.19921462815138938
Fold 3 IBS: 0.2542760719339917
Fold 4 IBS: 0.22500598026486066
Fold 5 IBS: 0.2130039704603047
[I 2024-04-17 17:54:20,390] Trial 86 finished with value: 0.2284530238286072 and parameters: {'subsample': 0.2377998071866918, 'dropout_rate': 0.9263524121710748, 'n_estimators': 107, 'learning_rate': 0.01902085002480073}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24461520451936894
Fold 2 IBS: 0.21162187155184128
Fold 3 IBS: 0.2344490116850452
Fold 4 IBS: 0.22917043508852472
Fold 5 IBS: 0.21178897460870122
[I 2024-04-17 17:54:21,222] Trial 87 finished with value: 0.22632909949069627 and parameters: {'subsample': 0.35810969899809325, 'dropout_rate': 0.8886867033584094, 'n_estimators': 134, 'learning_rate': 0.007190805934355407}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24456370610129832
Fold 2 IBS: 0.22128022630882604
Fold 3 IBS: 0.22947409303221045
Fold 4 IBS: 0.23463118790461507
Fold 5 IBS: 0.2191508748909942
[I 2024-04-17 17:54:22,208] Trial 88 finished with value: 0.2298200176475888 and parameters: {'subsample': 0.3554257183364478, 'dropout_rate': 0.8515802063127001, 'n_estimators': 151, 'learning_rate': 0.002966804106888144}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2775193161210976
Fold 2 IBS: 0.2056495855781246
Fold 3 IBS: 0.28613237088303234
Fold 4 IBS: 0.24447960031747357
Fold 5 IBS: 0.23382248801015568
[I 2024-04-17 17:54:23,114] Trial 89 finished with value: 0.24952067218197677 and parameters: {'subsample': 0.2975632154761778, 'dropout_rate': 0.8979603248959219, 'n_estimators': 137, 'learning_rate': 0.026327304724599293}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24489792409125763
Fold 2 IBS: 0.2147507134735931
Fold 3 IBS: 0.23214478243102468
Fold 4 IBS: 0.2311366433597866
Fold 5 IBS: 0.21331168885551222
[I 2024-04-17 17:54:23,696] Trial 90 finished with value: 0.22724835044223485 and parameters: {'subsample': 0.4239438985312938, 'dropout_rate': 0.8842980981030877, 'n_estimators': 94, 'learning_rate': 0.008199816001785099}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24443912868099016
Fold 2 IBS: 0.2106555205421554
Fold 3 IBS: 0.2361002830373223
Fold 4 IBS: 0.22815140478159898
Fold 5 IBS: 0.21090216410324303
[I 2024-04-17 17:54:24,197] Trial 91 finished with value: 0.226049700229062 and parameters: {'subsample': 0.36316393582436224, 'dropout_rate': 0.9330356356373378, 'n_estimators': 74, 'learning_rate': 0.014627227900695133}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24696395568562218
Fold 2 IBS: 0.206328757542603
Fold 3 IBS: 0.24098516387669733
Fold 4 IBS: 0.22738668862012074
Fold 5 IBS: 0.2096198352018724
[I 2024-04-17 17:54:25,002] Trial 92 finished with value: 0.22625688018538312 and parameters: {'subsample': 0.373278308068316, 'dropout_rate': 0.8205446675130532, 'n_estimators': 127, 'learning_rate': 0.010840707181494103}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2445959002519018
Fold 2 IBS: 0.21367655385448994
Fold 3 IBS: 0.23288855680962822
Fold 4 IBS: 0.23008083622513512
Fold 5 IBS: 0.21285389160286478
[I 2024-04-17 17:54:25,846] Trial 93 finished with value: 0.22681914774880396 and parameters: {'subsample': 0.4052623501935374, 'dropout_rate': 0.8224708293111835, 'n_estimators': 122, 'learning_rate': 0.006828423866425095}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.26112728548129654
Fold 2 IBS: 0.20039367088884036
Fold 3 IBS: 0.267173994295559
Fold 4 IBS: 0.23029824587397804
Fold 5 IBS: 0.21639436758841524
[I 2024-04-17 17:54:27,085] Trial 94 finished with value: 0.23507751282561787 and parameters: {'subsample': 0.2685207405457639, 'dropout_rate': 0.5306326676271426, 'n_estimators': 159, 'learning_rate': 0.016919236533565633}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2458959493820953
Fold 2 IBS: 0.20854810474644417
Fold 3 IBS: 0.23772658465187374
Fold 4 IBS: 0.22767957442334677
Fold 5 IBS: 0.21018857248815617
[I 2024-04-17 17:54:28,067] Trial 95 finished with value: 0.22600775713838323 and parameters: {'subsample': 0.37798247189331685, 'dropout_rate': 0.8572208063796695, 'n_estimators': 112, 'learning_rate': 0.01063058308878333}. Best is trial 85 with value: 0.22596006011310088.

Fold 1 IBS: 0.2471425193657016
Fold 2 IBS: 0.20576111765918625
Fold 3 IBS: 0.2415748835282002
Fold 4 IBS: 0.22741639083301954
Fold 5 IBS: 0.20957521984090532
[I 2024-04-17 17:54:28,980] Trial 96 finished with value: 0.2262940262454026 and parameters: {'subsample': 0.34523349906195283, 'dropout_rate': 0.7739280807288145, 'n_estimators': 132, 'learning_rate': 0.010648288131411126}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24385115968166024
Fold 2 IBS: 0.21643646571599923
Fold 3 IBS: 0.23116557489710682
Fold 4 IBS: 0.23167317839356094
Fold 5 IBS: 0.21516282794158326
[I 2024-04-17 17:54:30,289] Trial 97 finished with value: 0.22765784132598207 and parameters: {'subsample': 0.37469859653908655, 'dropout_rate': 0.8528934112321543, 'n_estimators': 187, 'learning_rate': 0.003684889317176295}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24621689559308768
Fold 2 IBS: 0.2055572040394727
Fold 3 IBS: 0.24230333094691225
Fold 4 IBS: 0.22648768747110257
Fold 5 IBS: 0.20952956681329585
[I 2024-04-17 17:54:32,122] Trial 98 finished with value: 0.22601893697277423 and parameters: {'subsample': 0.340063793125768, 'dropout_rate': 0.7630617995157165, 'n_estimators': 226, 'learning_rate': 0.006438550621538491}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24106601000226005
Fold 2 IBS: 0.20816190318997677
Fold 3 IBS: 0.23679287394758858
Fold 4 IBS: 0.22257166193265793
Fold 5 IBS: 0.21154595518502317
[I 2024-04-17 17:54:33,931] Trial 99 finished with value: 0.2240276808515013 and parameters: {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}. Best is trial 99 with value: 0.2240276808515013.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.2240276808515013], datetime_start=datetime.datetime(2024, 4, 17, 17, 54, 32, 132276), datetime_complete=datetime.datetime(2024, 4, 17, 17, 54, 33, 931256), params={'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=99, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}


* Best Score for IBS:
 0.2240276808515013

In [72]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [73]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.657
train_ibs:  0.224

#### Test

In [74]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [75]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10144570768327635,
                                              learning_rate=0.09251439643756458,
                                              n_estimators=428,
                                              random_state=123,
                                              subsample=0.10637687141780292)

C-index score: 0.536

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7782160113329367,
                                              learning_rate=0.005308151321564225,
                                              n_estimators=212,
                                              random_state=123,
                                              subsample=0.17778434918103095)

IBS: 0.233

In [76]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [77]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.841   1.5
ExtraSurvivalTrees               0.841   1.5
GradientBoosting                 0.749   3.0
CoxLasso                         0.717   4.5
CoxElastic                       0.717   4.5
CoxPH                            0.715   6.0
ComponentwiseGradientBoosting    0.657   7.0
CoxRidge                         0.651   8.0

In [78]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.193   1.0
ExtraSurvivalTrees             0.198   2.0
CoxLasso                       0.199   3.5
CoxElastic                     0.199   3.5
CoxPH                          0.200   5.0
ComponentwiseGradientBoosting  0.224   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [79]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.581   1.0
CoxLasso                         0.571   2.0
CoxElastic                       0.569   3.0
CoxPH                            0.568   4.0
Randomsurvivalforest             0.567   5.0
GradientBoosting                 0.565   6.0
CoxRidge                         0.541   7.0
ComponentwiseGradientBoosting    0.536   8.0

In [80]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   2.0
ExtraSurvivalTrees             0.229   2.0
GradientBoosting               0.229   2.0
ComponentwiseGradientBoosting  0.233   4.0
Randomsurvivalforest           0.247   5.0
CoxLasso                       0.262   6.5
CoxElastic                     0.262   6.5
CoxPH                          0.263   8.0

In [81]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/robust/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_robust_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [82]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-17